import Mathlib
import InfoGeometry.Canonical.CantorCoadjointHamiltonianFlowBridge.Basic

/-!
# InfoGeometry.Canonical.CantorCoadjointHamiltonianFlowBridge.Flow

Flow theorems for the Coadjoint Hamiltonian Flow of the Information Crystal.
-/

noncomputable section

set_option linter.dupNamespace false

namespace InfoGeometry.Canonical.CantorCoadjointHamiltonianFlowBridge

open InfoGeometry.Canonical.SouriauCoadjointOrbitMetriplectic
open InfoGeometry.Canonical.FractalCantorCuntzKacMoodyVirasoroBridge
open InfoGeometry.Thermodynamics.SouriauWeylPartitionBridge
open VirasoroProject

namespace CantorCoadjointHamiltonianFlowBridge

variable
    {Orbit E Op H Finite Alg : Type}
    [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] [Module ℝ E]
    [Ring Op] [StarRing Op]
    [NormedAddCommGroup H] [NormedSpace ℂ H] [SMul Op H] [CompleteSpace H]
    [InnerProductSpace ℝ H]
    [AddCommGroup Finite] [Module ℝ Finite] [LieRing Finite] [LieAlgebra ℝ Finite]
    [AddCommGroup Alg] [Module ℝ Alg] [LieRing Alg] [LieAlgebra ℝ Alg]

variable (B : CantorCoadjointHamiltonianFlowBridge Orbit E Op H Finite Alg)

/-- 
The Hamiltonian of the system is the Souriau temperature vector 
pointing along the L₀ direction.
-/
@[rep_depth transport]
theorem hamiltonian_eq_L0 :
    B.dynamics.geometricTemperature = B.crystal.virasoro.Lmode 0 :=
  B.hamiltonian_is_L0

/--
The actual dynamic owner surface identifies the Hamiltonian with the Tomita
thermal generator.
-/
@[rep_depth transport]
theorem flow_hamiltonian_is_souriau_generator :
    B.flow.selfAdjointHamiltonian =
      B.flow.modularContext.logContext.modularHamiltonian :=
  InfoGeometry.Dynamics.HamiltonianFlowBridge.HamiltonianFlowBridge.hamiltonian_is_souriau_generator
    (B := B.flow)

/--
The actual dynamic owner surface identifies the KMS inverse temperature with
the real part of the Souriau temperature parameter.
-/
@[rep_depth transport]
theorem flow_kms_inverse_temperature_eq_real_part_of_s :
    B.flow.modularContext.beta = B.flow.partition.temperature.s.re :=
  InfoGeometry.Dynamics.HamiltonianFlowBridge.HamiltonianFlowBridge.kms_inverse_temperature_eq_real_part_of_s
    (B := B.flow)

/-- The actual dynamic owner surface encodes positive roots spectrally. -/
@[rep_depth transport]
theorem flow_positive_roots_spectral_encoding (p : ℕ) (hp : p ∈ B.flow.partition.positiveRoots) :
    ∃ (energy : ℝ), energy = Real.log (p : ℝ) :=
  InfoGeometry.Dynamics.HamiltonianFlowBridge.HamiltonianFlowBridge.positive_roots_spectral_encoding
    (B := B.flow) p hp

/--
The reversible (Hamiltonian) flow on the coadjoint orbit is exactly the 
time evolution generated by the L₀ Virasoro mode.
-/
@[rep_depth transport]
theorem reversible_flow_is_L0_evolution :
    B.dynamics.reversibleVectorField = B.virasoro_flow_generator 0 :=
  B.L0_generator_is_reversible.symm

/-- 
The Virasoro flow generators satisfy the conformal commutator law.
This ensures the 'bits' evolve into 'waves' (integrable systems like KdV).
-/
@[rep_depth transport]
theorem conformal_flow_holds (m n : ℤ) :
    ∃ (bracket : (Orbit → Orbit) → (Orbit → Orbit) → (Orbit → Orbit)),
        bracket (B.virasoro_flow_generator m) (B.virasoro_flow_generator n) =
          B.virasoro_flow_generator (m + n) :=
  B.conformal_equations_of_motion m n

end CantorCoadjointHamiltonianFlowBridge

end InfoGeometry.Canonical.CantorCoadjointHamiltonianFlowBridge
