import InfoGeometry.Analysis.BipolarWindingExactSequence
import Mathlib.Analysis.Complex.CoveringMap
import Mathlib.Tactic

/-!
# Native exponential covering behind the bipolar period quotient

Mathlib already proves that

`exp : ℂ → {z : ℂ // z ≠ 0}`

is an additive quotient covering map with deck subgroup generated by `2πi`.
This file identifies the image of the repository's explicit bipolar winding
pairing with that native subgroup.

Thus the algebraic quotient descent constructed in `BipolarPeriodDescent` is a
readback of a genuine Mathlib covering-space theorem.  The source winding
carrier is still `ℤ × ℤ`; only its residue-difference image is the cyclic deck
subgroup.  The rational map `q` is a map from the punctured plane into `ℂˣ`; it
is not called a group character because no multiplication law on the punctured
plane has been chosen.
-/

noncomputable section

namespace InfoGeometry.Analysis.BipolarNativeExpCoveringBridge

open InfoGeometry.Analysis.BipolarCrossRatioLog
open InfoGeometry.Analysis.BipolarWindingPeriodLattice
open InfoGeometry.Analysis.BipolarPeriodDescent
open InfoGeometry.Analysis.BipolarWindingExactSequence

/-- Native additive deck subgroup generated by `2πi`. -/
def twoPiIPeriodSubgroup : AddSubgroup ℂ :=
  AddSubgroup.zmultiples (2 * Real.pi * Complex.I : ℂ)

/-- Membership in the native subgroup is exactly membership in the explicit
period lattice predicate. -/
theorem mem_twoPiIPeriodSubgroup_iff (z : ℂ) :
    z ∈ twoPiIPeriodSubgroup ↔ IsTwoPiIPeriod z := by
  constructor
  · intro hz
    obtain ⟨k, hk⟩ :=
      AddSubgroup.mem_zmultiples_iff.mp hz
    refine ⟨k, ?_⟩
    calc
      z = k • (2 * Real.pi * Complex.I : ℂ) := hk.symm
      _ = (k : ℂ) * (2 * Real.pi * Complex.I : ℂ) := by
        rw [zsmul_eq_mul]
  · rintro ⟨k, rfl⟩
    apply AddSubgroup.mem_zmultiples_iff.mpr
    exact ⟨k, by rw [zsmul_eq_mul]⟩

/-- Every period detected by the bipolar logarithmic form belongs to the native
deck subgroup of the exponential covering. -/
theorem circulationPeriod_mem_twoPiIPeriodSubgroup (w : WindingPair) :
    circulationPeriod w ∈ twoPiIPeriodSubgroup := by
  rw [mem_twoPiIPeriodSubgroup_iff]
  exact circulationPeriod_isTwoPiIPeriod w

/-- Conversely every native deck translation is realized by an explicit
bipolar winding pair. -/
theorem every_twoPiIPeriodSubgroup_mem_is_circulationPeriod
    {z : ℂ} (hz : z ∈ twoPiIPeriodSubgroup) :
    ∃ w : WindingPair, circulationPeriod w = z := by
  rw [mem_twoPiIPeriodSubgroup_iff] at hz
  exact (mem_circulationPeriod_range_iff z).2 hz

/-- The range of the genuine additive period homomorphism is exactly the native
deck subgroup. -/
theorem circulationPeriodHom_range_eq_twoPiIPeriodSubgroup :
    circulationPeriodHom.range = twoPiIPeriodSubgroup := by
  simpa [twoPiIPeriodSubgroup] using
    circulationPeriodHom_range_eq_zmultiples

/-- Exact subgroup form of period equivalence. -/
theorem PeriodEquivalent_iff_sub_mem
    (W₁ W₂ : ℂ) :
    PeriodEquivalent W₁ W₂ ↔ W₁ - W₂ ∈ twoPiIPeriodSubgroup := by
  constructor
  · rintro ⟨w, hw⟩
    rw [hw]
    exact circulationPeriod_mem_twoPiIPeriodSubgroup w
  · intro h
    obtain ⟨w, hw⟩ :=
      every_twoPiIPeriodSubgroup_mem_is_circulationPeriod h
    exact ⟨w, hw.symm⟩

/-- Native quotient-additive carrier of logarithmic potentials modulo `2πi`. -/
abbrev NativeLogPotentialQuotient :=
  ℂ ⧸ twoPiIPeriodSubgroup

/-- Canonical projection to the native additive quotient. -/
def nativeLogClass : ℂ →+ NativeLogPotentialQuotient :=
  QuotientAddGroup.mk' twoPiIPeriodSubgroup

/-- Equality in the native quotient is exactly the bipolar period relation. -/
theorem nativeLogClass_eq_iff (W₁ W₂ : ℂ) :
    nativeLogClass W₁ = nativeLogClass W₂ ↔ PeriodEquivalent W₁ W₂ := by
  change
    QuotientAddGroup.mk' twoPiIPeriodSubgroup W₁ =
      QuotientAddGroup.mk' twoPiIPeriodSubgroup W₂ ↔
        PeriodEquivalent W₁ W₂
  rw [QuotientAddGroup.eq_iff_sub_mem,
    PeriodEquivalent_iff_sub_mem]

/-- The exact Mathlib theorem: complex exponentiation is an additive quotient
covering map with deck subgroup `2πiℤ`. -/
theorem exp_isAddQuotientCoveringMap :
    IsAddQuotientCoveringMap
      (fun z : ℂ =>
        (⟨Complex.exp z, Complex.exp_ne_zero z⟩ : {z : ℂ // z ≠ 0}))
      twoPiIPeriodSubgroup := by
  simpa [twoPiIPeriodSubgroup] using
    Complex.isAddQuotientCoveringMap_exp

/-- Fiber equality of the native covering is precisely bipolar period
equivalence. -/
theorem exp_fiber_iff_PeriodEquivalent (W₁ W₂ : ℂ) :
    (⟨Complex.exp W₁, Complex.exp_ne_zero W₁⟩ : {z : ℂ // z ≠ 0}) =
        ⟨Complex.exp W₂, Complex.exp_ne_zero W₂⟩ ↔
      PeriodEquivalent W₁ W₂ := by
  simpa only [Subtype.ext_iff] using
    (PeriodEquivalent_iff_exp_eq W₁ W₂).symm

/-- Native carrier for the twice-punctured plane. -/
abbrev PuncturedPlaneCarrier :=
  {s : ℂ // s ∈ punctured01}

/-- The globally single-valued rational coordinate as a map into nonzero
complex numbers.  This is the geometric map whose local logarithms differ by
deck translations. -/
def bipolarCrossRatioMap :
    PuncturedPlaneCarrier → {z : ℂ // z ≠ 0} :=
  fun s => ⟨crossRatio01 s.1, crossRatio01_ne_zero s.2⟩

@[simp] theorem bipolarCrossRatioMap_val (s : PuncturedPlaneCarrier) :
    (bipolarCrossRatioMap s : ℂ) = crossRatio01 s.1 := rfl

/-- Pointwise exponential readback through the selected principal logarithm.
This is an equality of values, not a claim that the principal logarithm is a
global continuous lift. -/
theorem bipolarCrossRatioMap_eq_exp_principal
    (s : PuncturedPlaneCarrier) :
    bipolarCrossRatioMap s =
      ⟨Complex.exp (bipolarLog s.1),
        Complex.exp_ne_zero (bipolarLog s.1)⟩ := by
  apply Subtype.ext
  exact (exp_bipolarLog s.2).symm

/-- Compact native covering packet. -/
theorem bipolar_native_exp_covering_packet
    (w : WindingPair) (W₁ W₂ : ℂ) :
    circulationPeriod w ∈ twoPiIPeriodSubgroup ∧
      circulationPeriodHom.range = twoPiIPeriodSubgroup ∧
      (nativeLogClass W₁ = nativeLogClass W₂ ↔
        PeriodEquivalent W₁ W₂) ∧
      ((⟨Complex.exp W₁, Complex.exp_ne_zero W₁⟩ :
          {z : ℂ // z ≠ 0}) =
        ⟨Complex.exp W₂, Complex.exp_ne_zero W₂⟩ ↔
          PeriodEquivalent W₁ W₂) := by
  exact ⟨circulationPeriod_mem_twoPiIPeriodSubgroup w,
    circulationPeriodHom_range_eq_twoPiIPeriodSubgroup,
    nativeLogClass_eq_iff W₁ W₂,
    exp_fiber_iff_PeriodEquivalent W₁ W₂⟩

end InfoGeometry.Analysis.BipolarNativeExpCoveringBridge
