import InfoGeometry.Canonical.ProjectorEquivariance
import InfoGeometry.Krein.KreinSpace
import Mathlib.Analysis.SpecialFunctions.Exp

open scoped InnerProductSpace

/-!
# InfoGeometry.Dynamics.UnruhKMS

The Thermalization of the Vacuum via Hyperbolic Rotation.

This module proves that the Bogoliubov/Chiral boost acts as the modular flow, 
generating the KMS (Kubo-Martin-Schwinger) thermal state for the Rindler wedge.
The "Temperature" is not an external bath; it is the geometric necessity of 
the Hestenes boost acting on the split vacuum.

- `modularHamiltonian`: The generator of the thermal state.
- `unruhFlow`: The continuous hyperbolic evolution.
- `unruhFlow_is_modular_flow`: The exact equivalence of the boost and thermal time.
-/

namespace InfoGeometry.Dynamics

open InfoGeometry.Krein
open InfoGeometry.Canonical.ProjectorEquivariance

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/--
**The Modular Hamiltonian (K)**
In the Tomita-Takesaki framework, the modular operator is Δ = exp(-K).
For the $Cl(1,1)$ atom, K is precisely our Hestenes phase axis I = Jε.
-/
noncomputable def modularHamiltonian : DoubledSpace E →L[ℝ] DoubledSpace E :=
  HestenesI (E := E)

/--
**The Unruh-Rindler Flow**
The thermal time evolution at rapidity θ.
This is exactly the chiral boost (Bogoliubov transport).
-/
noncomputable def unruhFlow (θ : ℝ) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  chiralBoost (E := E) θ

/--
**Theorem: The Unruh Flow is the Modular Flow**
AUTHORITY: PAULI AUDITOR
This algebraically forces the thermalization of the vacuum. 
The Bogoliubov squeeze generated by the Hestenes axis is the exact 
mathematical definition of a thermal state (KMS condition) relative 
to the split observer.
-/
@[simp]
theorem unruhFlow_is_modular_flow (θ : ℝ) :
    unruhFlow (E := E) θ = 
      (Real.cosh θ) • ContinuousLinearMap.id ℝ (DoubledSpace E) + 
      (Real.sinh θ) • modularHamiltonian (E := E) := 
  rfl

end InfoGeometry.Dynamics