import Mathlib.Algebra.Ring.Basic
import Mathlib.Algebra.Module.LinearMap.Basic
import Mathlib.Tactic

/-!
# The Dual Exponential Commutator Bridge

This module formalizes the fundamental commutation identity between:
1. An Outer Geometric Derivation `D : A → A` (e.g. D ∈ 𝔤_{2(2)})
2. An Inner Modular Derivation `ad_K : A → A` (e.g. ad_K(X) = [K, X])

THEOREM:
  [D, ad_K](X) = D(ad_K(X)) - ad_K(D(X)) = ad_{D(K)}(X)

All proofs are complete in native Mathlib with zero `sorry`s.
-/

noncomputable section

namespace InfoGeometry.Modular

variable {A : Type*} [Ring A]

/-- The Adjoint Action (Modular Commutator): ad_K(X) = [K, X] = K * X - X * K -/
def adK_dual (K : A) (X : A) : A :=
  K * X - X * K

@[simp]
theorem adK_dual_apply (K X : A) : adK_dual K X = K * X - X * K := rfl

theorem adK_dual_map_add (K x y : A) :
    adK_dual K (x + y) = adK_dual K x + adK_dual K y := by
  dsimp [adK_dual]
  simp only [mul_add, add_mul]
  abel

theorem adK_dual_leibniz (K x y : A) :
    adK_dual K (x * y) = adK_dual K x * y + x * adK_dual K y := by
  dsimp [adK_dual]
  calc
    K * (x * y) - (x * y) * K =
        (K * x * y - x * K * y) + (x * K * y - x * y * K) := by
          simp only [mul_assoc]
          abel
    _ = (K * x - x * K) * y + x * (K * y - y * K) := by
          simp only [sub_mul, mul_sub, mul_assoc]

/-- An additive map D is a derivation if it satisfies the Leibniz product rule. -/
structure RingDerivation (A : Type*) [Ring A] where
  toFun : A → A
  map_add' : ∀ x y, toFun (x + y) = toFun x + toFun y
  leibniz' : ∀ x y, toFun (x * y) = toFun x * y + x * toFun y

namespace RingDerivation

instance : CoeFun (RingDerivation A) (fun _ => A → A) where
  coe D := D.toFun

variable (D : RingDerivation A)

@[simp] theorem map_add (x y : A) : D (x + y) = D x + D y := D.map_add' x y
@[simp] theorem leibniz (x y : A) : D (x * y) = D x * y + x * D y := D.leibniz' x y

@[simp]
theorem map_zero : D 0 = 0 := by
  have h : D (0 + 0) = D 0 + D 0 := D.map_add 0 0
  rw [add_zero] at h
  -- h : D 0 = D 0 + D 0
  have h' : D 0 + D 0 = D 0 := by simpa using h
  have h'' : D 0 = 0 := by
    apply add_left_cancel (a := D 0)
    simpa using h'.symm
  exact h''

@[simp]
theorem map_neg (x : A) : D (-x) = - D x := by
  have h : D (x + -x) = D x + D (-x) := D.map_add x (-x)
  rw [add_neg_cancel, D.map_zero] at h
  exact eq_neg_of_add_eq_zero_right h.symm

@[simp]
theorem map_sub (x y : A) : D (x - y) = D x - D y := by
  rw [sub_eq_add_neg, D.map_add, D.map_neg, ← sub_eq_add_neg]

@[simp]
theorem map_one : D 1 = 0 := by
  have h : D 1 = D 1 + D 1 := by
    calc
      D 1 = D (1 * 1) := by rw [mul_one]
      _ = D 1 * 1 + 1 * D 1 := D.leibniz 1 1
      _ = D 1 + D 1 := by rw [mul_one, one_mul]
  apply add_left_cancel (a := D 1)
  simpa using h.symm

theorem extensionality {D E : RingDerivation A}
    (h : ∀ x, D x = E x) : D = E := by
  cases D
  cases E
  congr
  funext x
  exact h x

/-! ### Bundled inner derivations and their commutators -/

def innerDerivation (K : A) : RingDerivation A where
  toFun := adK_dual K
  map_add' := adK_dual_map_add K
  leibniz' := adK_dual_leibniz K

@[simp]
theorem innerDerivation_apply (K X : A) :
    innerDerivation K X = adK_dual K X := rfl

def commutator (D₁ D₂ : RingDerivation A) : RingDerivation A where
  toFun := fun X => D₁ (D₂ X) - D₂ (D₁ X)
  map_add' := by
    intro x y
    rw [D₂.map_add, D₁.map_add, D₁.map_add, D₂.map_add]
    abel
  leibniz' := by
    intro x y
    rw [D₂.leibniz, D₁.leibniz, D₁.map_add, D₁.leibniz,
      D₁.leibniz, D₂.map_add, D₂.leibniz, D₂.leibniz]
    simp only [sub_mul, mul_sub]
    abel

@[simp]
theorem commutator_apply (D₁ D₂ : RingDerivation A) (X : A) :
    commutator D₁ D₂ X = D₁ (D₂ X) - D₂ (D₁ X) := rfl

theorem commutator_skew (D₁ D₂ : RingDerivation A) (X : A) :
    commutator D₁ D₂ X = -commutator D₂ D₁ X := by
  dsimp [commutator]
  abel

@[simp]
theorem commutator_self (D : RingDerivation A) (X : A) :
    commutator D D X = 0 := by
  dsimp [commutator]
  abel

theorem commutator_jacobi (D₁ D₂ D₃ : RingDerivation A) (X : A) :
    commutator D₁ (commutator D₂ D₃) X +
        commutator D₂ (commutator D₃ D₁) X +
        commutator D₃ (commutator D₁ D₂) X = 0 := by
  dsimp [commutator]
  rw [D₁.map_sub, D₂.map_sub, D₃.map_sub]
  abel

/-- 
  THEOREM 1: The Master Commutator Identity between Outer and Inner Derivations
  [D, ad_K](X) = ad_{D(K)}(X)
  
  The commutator of an outer geometric derivation D with an inner modular 
  derivation ad_K is identically the inner derivation generated by D(K).
-/
theorem derivation_adK_comm (K X : A) :
    D (adK_dual K X) - adK_dual K (D X) = adK_dual (D K) X := by
  dsimp [adK_dual]
  rw [D.map_sub, D.leibniz, D.leibniz]
  -- D(K) * X + K * D(X) - (D(X) * K + X * D(K)) - (K * D(X) - D(X) * K)
  -- = D(K) * X - X * D(K)
  abel

theorem commutator_innerDerivation_eq (D : RingDerivation A) (K : A) :
    commutator D (innerDerivation K) = innerDerivation (D K) := by
  apply extensionality
  intro X
  exact derivation_adK_comm D K X

theorem commutator_innerDerivation_apply_of_invariant
    (D : RingDerivation A) (K : A) (hK : D K = 0) (X : A) :
    commutator D (innerDerivation K) X = 0 := by
  rw [commutator_innerDerivation_eq D K, hK]
  change adK_dual 0 X = 0
  simp [adK_dual]

theorem adK_dual_bracket (K₁ K₂ X : A) :
    adK_dual K₁ (adK_dual K₂ X) - adK_dual K₂ (adK_dual K₁ X) = adK_dual (adK_dual K₁ K₂) X := by
  dsimp [adK_dual]
  noncomm_ring

theorem commutator_innerDerivation_innerDerivation_eq (K₁ K₂ : A) :
    commutator (innerDerivation K₁) (innerDerivation K₂) =
      innerDerivation (adK_dual K₁ K₂) := by
  apply extensionality
  intro X
  rw [commutator_apply]
  exact adK_dual_bracket K₁ K₂ X

/-- 
  THEOREM 2: Adiabatic / Invariant Commutation
  If the modular surprisal K is invariant under the geometric flow (D(K) = 0),
  then the outer geometric flow and the inner modular flow strictly commute:
  [D, ad_K] = 0
-/
theorem derivation_adK_comm_of_invariant (K : A) (hK : D K = 0) (X : A) :
    D (adK_dual K X) - adK_dual K (D X) = 0 := by
  rw [derivation_adK_comm D K X, hK]
  simp [adK_dual]

/-- 
  THEOREM 3: Central Modular Invariance
  If K is in the center of the ring (or a central scalar λ • 1), 
  its modular derivation is strictly zero: ad_K = 0.
-/
theorem adK_dual_eq_zero_of_central (K : A) (h_central : ∀ x, K * x = x * K) (X : A) :
    adK_dual K X = 0 := by
  dsimp [adK_dual]
  rw [h_central X, sub_self]

theorem central_of_adK_dual_eq_zero (K : A) (h_zero : ∀ X, adK_dual K X = 0) (X : A) :
    K * X = X * K := by
  exact sub_eq_zero.mp (h_zero X)

theorem adK_dual_eq_zero_iff_central (K : A) :
    (∀ X, adK_dual K X = 0) ↔ ∀ X, K * X = X * K := by
  constructor
  · exact central_of_adK_dual_eq_zero K
  · intro h X
    exact adK_dual_eq_zero_of_central K h X

end RingDerivation

end InfoGeometry.Modular
