import Mathlib.Algebra.Ring.Basic
import Mathlib.Algebra.Module.LinearMap.Basic
import Mathlib.Tactic

/-!
# The Dual Exponential Commutator Bridge

This module formalizes the fundamental commutation identity between:
1. An Outer Geometric Derivation `D : A → A` (e.g. D ∈ 𝔤_{2(2)})
2. An Inner Modular Derivation `ad_K : A → A` (e.g. ad_K(X) = [K, X])

THEOREM:
  [D, ad_K](X) = D(ad_K(X)) - ad_K(D(X)) = ad_{D(K)}(X)

All proofs are complete in native Mathlib with zero `sorry`s.
-/

noncomputable section

namespace InfoGeometry.Modular

variable {A : Type*} [Ring A]

/-- The Adjoint Action (Modular Commutator): ad_K(X) = [K, X] = K * X - X * K -/
def adK (K : A) (X : A) : A :=
  K * X - X * K

@[simp]
theorem adK_apply (K X : A) : adK K X = K * X - X * K := rfl

theorem adK_map_add (K x y : A) :
    adK K (x + y) = adK K x + adK K y := by
  dsimp [adK]
  simp only [mul_add, add_mul]
  abel

theorem adK_leibniz (K x y : A) :
    adK K (x * y) = adK K x * y + x * adK K y := by
  dsimp [adK]
  calc
    K * (x * y) - (x * y) * K =
        (K * x * y - x * K * y) + (x * K * y - x * y * K) := by
          simp only [mul_assoc]
          abel
    _ = (K * x - x * K) * y + x * (K * y - y * K) := by
          simp only [sub_mul, mul_sub, mul_assoc]

/-- An additive map D is a derivation if it satisfies the Leibniz product rule. -/
structure RingDerivation (A : Type*) [Ring A] where
  toFun : A → A
  map_add' : ∀ x y, toFun (x + y) = toFun x + toFun y
  leibniz' : ∀ x y, toFun (x * y) = toFun x * y + x * toFun y

namespace RingDerivation

instance : CoeFun (RingDerivation A) (fun _ => A → A) where
  coe D := D.toFun

variable (D : RingDerivation A)

@[simp] theorem map_add (x y : A) : D (x + y) = D x + D y := D.map_add' x y
@[simp] theorem leibniz (x y : A) : D (x * y) = D x * y + x * D y := D.leibniz' x y

@[simp]
theorem map_zero : D 0 = 0 := by
  have h : D (0 + 0) = D 0 + D 0 := D.map_add 0 0
  rw [add_zero] at h
  -- h : D 0 = D 0 + D 0
  have h' : D 0 + D 0 = D 0 := by simpa using h
  have h'' : D 0 = 0 := by
    apply add_left_cancel (a := D 0)
    simpa using h'.symm
  exact h''

@[simp]
theorem map_neg (x : A) : D (-x) = - D x := by
  have h : D (x + -x) = D x + D (-x) := D.map_add x (-x)
  rw [add_neg_cancel, D.map_zero] at h
  exact eq_neg_of_add_eq_zero_right h.symm

@[simp]
theorem map_sub (x y : A) : D (x - y) = D x - D y := by
  rw [sub_eq_add_neg, D.map_add, D.map_neg, ← sub_eq_add_neg]

/-- 
  THEOREM 1: The Master Commutator Identity between Outer and Inner Derivations
  [D, ad_K](X) = ad_{D(K)}(X)
  
  The commutator of an outer geometric derivation D with an inner modular 
  derivation ad_K is identically the inner derivation generated by D(K).
-/
theorem derivation_adK_comm (K X : A) :
    D (adK K X) - adK K (D X) = adK (D K) X := by
  dsimp [adK]
  rw [D.map_sub, D.leibniz, D.leibniz]
  -- D(K) * X + K * D(X) - (D(X) * K + X * D(K)) - (K * D(X) - D(X) * K)
  -- = D(K) * X - X * D(K)
  abel

/-- 
  THEOREM 2: Adiabatic / Invariant Commutation
  If the modular surprisal K is invariant under the geometric flow (D(K) = 0),
  then the outer geometric flow and the inner modular flow strictly commute:
  [D, ad_K] = 0
-/
theorem derivation_adK_comm_of_invariant (K : A) (hK : D K = 0) (X : A) :
    D (adK K X) - adK K (D X) = 0 := by
  rw [derivation_adK_comm D K X, hK]
  simp [adK]

/-- 
  THEOREM 3: Central Modular Invariance
  If K is in the center of the ring (or a central scalar λ • 1), 
  its modular derivation is strictly zero: ad_K = 0.
-/
theorem adK_eq_zero_of_central (K : A) (h_central : ∀ x, K * x = x * K) (X : A) :
    adK K X = 0 := by
  dsimp [adK]
  rw [h_central X, sub_self]

theorem central_of_adK_eq_zero (K : A) (h_zero : ∀ X, adK K X = 0) (X : A) :
    K * X = X * K := by
  exact sub_eq_zero.mp (h_zero X)

theorem adK_eq_zero_iff_central (K : A) :
    (∀ X, adK K X = 0) ↔ ∀ X, K * X = X * K := by
  constructor
  · exact central_of_adK_eq_zero K
  · intro h X
    exact adK_eq_zero_of_central K h X

end RingDerivation

end InfoGeometry.Modular
