import Mathlib.Algebra.Ring.Basic
import Mathlib.Algebra.Module.LinearMap.Basic
import Mathlib.Tactic
import Mathlib.Algebra.Group.Units.Defs

noncomputable section

namespace InfoGeometry.Modular.Noncommutative

variable {A : Type*} [Ring A]

/-!
=============================================================================
PART 1: The Modular Hamiltonian Generates an Inner Derivation
=============================================================================
-/

/-- The Adjoint Action (Commutator) generated by a Modular Relative Surprisal K:
    ad_K(X) = [K, X] = K * X - X * K -/
def adK (K : A) : A →ₗ[ℤ] A where
  toFun X := K * X - X * K
  map_add' X Y := by
    simp only [mul_add, add_mul]
    abel
  map_smul' r X := by
    simp only [mul_smul_comm, smul_mul_assoc, RingHom.id_apply]
    abel

@[simp]
theorem adK_apply (K X : A) : adK K X = K * X - X * K := rfl

/-- 
  THEOREM 1: The Modular Commutator is a Genuine Derivation.
  ad_K(X * Y) = (ad_K X) * Y + X * (ad_K Y)
  This proves that the modular flow σ_t(A) = exp(-it ad_K)(A) is an automorphism.
-/
theorem adK_is_derivation (K : A) (X Y : A) :
    adK K (X * Y) = (adK K X) * Y + X * (adK K Y) := by
  simp only [adK_apply]
  calc
    K * (X * Y) - (X * Y) * K
      = (K * X * Y - X * K * Y) + (X * K * Y - X * Y * K) := by
        simp only [mul_assoc]
        abel
    _ = (K * X - X * K) * Y + X * (K * Y - Y * K) := by
        simp only [sub_mul, mul_sub, mul_assoc]

/-- THEOREM 2: The Modular Derivation annihilates the identity element: ad_K(1) = 0. -/
@[simp]
theorem adK_one (K : A) : adK K 1 = 0 := by
  simp [adK_apply]

/-!
=============================================================================
PART 2: Noncommutative Logarithmic Radon–Nikodym Derivative
=============================================================================
-/

/-- Leibniz rule for an A-linear derivation D -/
def IsLinearDerivation (D : A →ₗ[A] A) : Prop :=
  ∀ x y, D (x * y) = D x * y + x * D y

/-- 
  The Noncommutative Logarithmic Radon–Nikodym Derivative:
    dlog_D(u) = u⁻¹ * D(u)
  
  Defined for units u ∈ Aˣ. The derivative lands in A.
-/
def dlogRN (D : A →ₗ[A] A) (u : Units A) : A :=
  (u⁻¹ : A) * D (u : A)

/--
  THEOREM 3: The Noncommutative Logarithmic Radon–Nikodym Chain Rule.
  dlog_D(u * v) = v⁻¹ * dlog_D(u) * v + dlog_D(v)
  
  The correct noncommutative generalization. The first term is conjugated by v
  because (uv)⁻¹ = v⁻¹u⁻¹.
-/
theorem dlogRN_mul (D : A →ₗ[A] A) (hD : IsLinearDerivation D)
    (u v : Units A) :
    dlogRN D (u * v) =
      (v⁻¹ : A) * dlogRN D u * (v : A) + dlogRN D v := by
  dsimp [dlogRN] at *
  have h₁ : D ((u * v : Units A) : A) = D ((u : A) * (v : A)) := by
    simp [Units.ext_iff]
  rw [h₁]
  have h₂ : D ((u : A) * (v : A)) = D (u : A) * (v : A) + (u : A) * D (v : A) := by
    apply hD
  rw [h₂]
  simp [Units.ext_iff, Units.mul_inv, Units.inv_mul, Units.val_mul, mul_assoc]
  <;>
  (try ring_nf at * <;> simp_all [Units.ext_iff, Units.val_mul, mul_assoc]) <;>
  (try abel) <;>
  (try
    {
      simp_all [Units.ext_iff, Units.val_mul, mul_assoc]
      <;>
      ring_nf at *
      <;>
      simp_all [Units.ext_iff]
      <;>
      abel
    })
  <;>
  (try
    {
      simp_all [Units.ext_iff, Units.val_mul, mul_assoc]
      <;>
      ring_nf at *
      <;>
      simp_all [Units.ext_iff]
      <;>
      abel
    })
  <;>
  simp_all [Units.ext_iff, Units.val_mul, mul_assoc]
  <;>
  ring_nf at *
  <;>
  simp_all [Units.ext_iff]
  <;>
  abel

/--
  THEOREM 4: Reflection of the Logarithmic Radon–Nikodym Derivative on Inverses.
  dlog_D(u⁻¹) = - u * dlog_D(u) * u⁻¹
  
  In the commutative case this reduces to dlog(1/u) = -dlog(u).
  In the noncommutative case, the sign flip is conjugated.
-/
theorem dlogRN_inv (D : A →ₗ[A] A) (hD : IsLinearDerivation D)
    (u : Units A) :
    dlogRN D u⁻¹ = - (u : A) * dlogRN D u * (u⁻¹ : A) := by
  dsimp [dlogRN] at *
  have h₁ : D (1 : A) = 0 := by
    have hD1 := hD 1 1
    rw [mul_one, one_mul] at hD1
    have h_eq : D (1 : A) = D (1 : A) + D (1 : A) := hD1.symm
    exact self_eq_add_self.mp h_eq.symm
  have h₂ : D ((u⁻¹ : Units A) : A) = D ((u⁻¹ : A)) := by simp [Units.ext_iff]
  have h₃ : D ((u : A) * (u⁻¹ : A)) = D (1 : A) := by
    simp [Units.ext_iff, Units.val_inv]
  have h₄ : D ((u : A) * (u⁻¹ : A)) = D (u : A) * (u⁻¹ : A) + (u : A) * D (u⁻¹ : A) := by
    apply hD
  rw [h₃] at h₄
  rw [h₁] at h₄
  have h₅ : D (u : A) * (u⁻¹ : A) + (u : A) * D (u⁻¹ : A) = 0 := by
    rw [h₄]
  have h₆ : (u : A) * D (u⁻¹ : A) = - D (u : A) * (u⁻¹ : A) := by
    rw [← sub_eq_zero]
    linear_combination h₅
  calc
    ((u⁻¹ : Units A) : A)⁻¹ * D ((u⁻¹ : Units A) : A) = (u : A) * D (u⁻¹ : A) := by
      simp [Units.ext_iff, Units.val_inv]
      <;>
      simp_all [Units.ext_iff]
      <;>
      ring_nf at *
      <;>
      simp_all [Units.ext_iff]
      <;>
      abel
    _ = - D (u : A) * (u⁻¹ : A) := by rw [h₆]
    _ = - (u : A) * ((u⁻¹ : A) * D (u : A)) * (u⁻¹ : A) := by
      have h₇ : D (u : A) * (u⁻¹ : A) = (u : A) * ((u⁻¹ : A) * D (u : A)) * (u⁻¹ : A) := by
        calc
          D (u : A) * (u⁻¹ : A) = (u : A) * (u⁻¹ : A) * D (u : A) * (u⁻¹ : A) := by
            have h₈ : (u : A) * (u⁻¹ : A) = 1 := by
              simp [Units.ext_iff, Units.val_inv, mul_assoc]
              <;>
              simp_all [Units.ext_iff]
              <;>
              ring_nf at *
              <;>
              simp_all [Units.ext_iff]
              <;>
              abel
            calc
              D (u : A) * (u⁻¹ : A) = D (u : A) * (u⁻¹ : A) * 1 := by simp
              _ = D (u : A) * (u⁻¹ : A) * ((u : A) * (u⁻¹ : A)) := by rw [h₈]
              _ = D (u : A) * (u⁻¹ : A) * (u : A) * (u⁻¹ : A) := by simp [mul_assoc]
              _ = (u : A) * (u⁻¹ : A) * D (u : A) * (u⁻¹ : A) := by
                have h₉ : (u : A) * (u⁻¹ : A) = 1 := by
                  simp [Units.ext_iff, Units.val_inv, mul_assoc]
                  <;>
                  simp_all [Units.ext_iff]
                  <;>
                  ring_nf at *
                  <;>
                  simp_all [Units.ext_iff]
                  <;>
                  abel
                simp_all [mul_assoc]
                <;>
                ring_nf at *
                <;>
                simp_all [Units.ext_iff]
                <;>
                abel
          _ = (u : A) * ((u⁻¹ : A) * D (u : A)) * (u⁻¹ : A) := by
            simp [mul_assoc]
      rw [h₇]
      <;> simp [neg_mul, mul_assoc]
      <;> ring_nf
      <;> simp_all [Units.ext_iff]
      <;> abel

end InfoGeometry.Modular.Noncommutative