import Mathlib
import InfoGeometry.Clifford.ConformalLieAlgebra55Dilation
import InfoGeometry.OperatorAlgebra.PO55ConformalClosure
import InfoGeometry.Krein.DoubledSpace

/-!
# Conformal SL₂ Generator Bridge

SymPy-verified `P, D, K` sl₂ conformal generator table, stated as explicit
theorem aliases against the existing `Cl(5,5)` conformal surfaces.

SymPy witness: `tools/sympy/conformal_group_generator_test.py`

## Generator table (verified by SymPy)

```
P = [[0,1],[0,0]]              translation
D = [[1/2,0],[0,-1/2]]         dilation
K = [[0,0],[1,0]]              special conformal
```

Commutation:
```
[P, K] = 2·D    [D, P] = P    [D, K] = -K
P² = K² = 0                   (nilpotent)
```

## Ambient group

- `O(5,5)` / `Pin(5,5)` — full orthogonal conformal symmetry
- `Spin(5,5)` — even orientation-preserving subgroup
- `PO(5,5)` — projective action on null rays (the conformal compactification)

The generators `P, D, K` are the infinitesimal readout of the ambient
`Pin(5,5)` geometry on the projective-chart boundary.

## Existing Lean surfaces

| Concept | Lean file |
|---------|-----------|
| Null pair `u, v` | `Clifford.ConformalLieAlgebra55Dilation` |
| Dilation `D` | `Clifford.ConformalLieAlgebra55Dilation` |
| Inversion `J` | `Clifford.ConformalLieAlgebra55Dilation` |
| Möbius `T` / `S` | `Clifford.DiscreteMoebiusGroup` |
| PO(5,5) projective closure | `OperatorAlgebra.PO55ConformalClosure` |
| Pin(5,5) reflections | `Clifford.ConformalReflection55` |

All verified by SymPy; all existing Lean surfaces compile clean.
-/

set_option linter.dupNamespace false

noncomputable section

open InfoGeometry.Clifford.ConformalLieAlgebra55
open InfoGeometry.Clifford.ClNN

namespace InfoGeometry.Canonical.ConformalSL2GeneratorBridge

/-! ## 1. SymPy-verified generator table -/

/--
Translation generator `P = [[0,1],[0,0]]`.

In `Cl(5,5)` language, this is the null raising operator `u5` from
`ConformalLieAlgebra55`.  It satisfies `P² = 0` (nilpotent).
-/
def P : Alg 5 := u5

/--
Dilation generator `D = [[1/2,0],[0,-1/2]]`.

This is the `D5` (the top-level dilation) from `ConformalLieAlgebra55`.
It acts as the infinitesimal conformal scaling.
-/
def D : Alg 5 := D5

/--
Special conformal generator `K = [[0,0],[1,0]]`.

In `Cl(5,5)` language, this is the null lowering operator `v5` from
`ConformalLieAlgebra55`.  It satisfies `K² = 0` (nilpotent).
-/
def K : Alg 5 := v5

/-! ## 2. Commutation relations -/

/-- `[P, K] = 2·D` — the raising/lowering bracket closes to dilation. -/
theorem comm_P_K : P * K - K * P = 2 • D := by
  dsimp [P, D, K, u5, v5, D5]
  calc
    u5 * v5 - v5 * u5 = (2 : ℝ) • ((1 / 2 : ℝ) • (u5 * v5 - v5 * u5)) := by
      rw [smul_smul]
      norm_num
    _ = 2 • D5 := rfl
    _ = 2 • D := rfl

/-- `[D, P] = P` — dilation scales translation. -/
theorem comm_D_P : D * P - P * D = P := by
  simpa [P, D] using
    (InfoGeometry.Clifford.ConformalLieAlgebra55Dilation.adD5_u5)

/-- `[D, K] = -K` — dilation scales special conformal inversely. -/
theorem comm_D_K : D * K - K * D = -K := by
  simpa [K, D] using
    (InfoGeometry.Clifford.ConformalLieAlgebra55Dilation.adD5_v5)

/-- `P² = 0` — nilpotent. -/
theorem P_sq_zero : P * P = 0 := u5_sq

/-- `K² = 0` — nilpotent. -/
theorem K_sq_zero : K * K = 0 := v5_sq

/-! ## 3. Ambient group identification -/

/-!
### Lemma: Ambient Conformal Group is O(5,5)

**Mathematical context.** The split real Clifford algebra `Cl(5,5)` carries
a natural quadratic form of signature `(5,5)`. The orthogonal group `O(5,5)`
acts on the projective null cone `PN := {[x] ∈ P(Cl(5,5)) : x² = 0, x ≠ 0}`,
where `P` denotes projectivization.

The conformal compactification of `ℝ^{3,3}` (or equivalently, the split
signature conformal space) is the projective null cone of `Cl(5,5)`,
and its conformal group is `O(5,5)`.

**Premises.**
- `Alg 5` is the Clifford algebra `Cl(5,5)` represented as an algebra over `ℝ`
- `P, D, K` are the translation, dilation, and special conformal generators
  in the `(2|1)` supermatrix format, realized as elements of `Alg 5`:
  - `P = u5` (translation generator, nilpotent: `P² = 0`)
  - `D = D5` (dilation generator, diagonal)
  - `K = v5` (special conformal generator, nilpotent: `K² = 0`)
- `[P, K] = 2D`, `[D, P] = P`, `[D, K] = -K` — the `𝔰𝔩(2)` commutation
  relations of the conformal algebra

**Claim.** The Lie algebra generated by `{P, D, K}` inside `Cl(5,5)` is
isomorphic to `𝔰𝔩(2,ℝ)`, which is a subalgebra of `𝔬(5,5)`. The ambient
conformal symmetry group is `O(5,5)`, acting on the projective null cone
`{x ∈ Alg 5 : x² = 0}` via the Clifford group `Pin(5,5)`:

    Pin(5,5) → O(5,5)
    g ↦ (x ↦ g x g^{-1})

where the action preserves the quadratic form: `(g x g^{-1})² = x²`.

**Proof sketch.**
1. Show that `P, D, K` generate `𝔰𝔩(2,ℝ)` inside the even subalgebra
   `Cl⁰(5,5) ≅ Cl(4,4)`.
2. The Clifford group `Pin(5,5) = {g ∈ Cl(5,5)^× : g V g^{-1} = V, α(g) = ±g}`
   maps onto `O(5,5)` with kernel `ℝ^×`.
3. The infinitesimal generators of the Pin action are commutators
   `ad_x(y) = [x, y]`. For `x ∈ 𝔰𝔩(2,ℝ) ⊂ Cl⁰(5,5)`, `ad_x` preserves
   the null cone.
4. The orbit of the highest-weight null vector under `Pin(5,5)` is the
   projective null cone, proving transitivity.

**Literature.**
- Porteous (1995), *Clifford Algebras and the Classical Groups*, §16
- Lounesto (2001), *Clifford Algebras and Spinors*, §17
- Dirac (1936), *Wave equations in conformal space*
- Kastrup (2008), *On the advancements of conformal transformations...*, Ann. Phys. 17
-/

/-- Bundled sl(2) commutation relations -/
theorem sl2_algebra_relations :
    P * K - K * P = 2 • D ∧ D * P - P * D = P ∧ D * K - K * D = -K ∧
    P * P = 0 ∧ K * K = 0 := by
  exact ⟨comm_P_K, comm_D_P, comm_D_K, P_sq_zero, K_sq_zero⟩

/-!
We remove the `ambient_group_is_O55` fake proof and expose the hole as `sorry`.
The proper formalization requires defining `O(5,5)` action.
-/
theorem ambient_group_is_O55 : False := sorry

/-! ## 4. Rosetta stone translation table

Rosetta stone mapping from the SymPy-verified 2×2 matrix picture to the
`Cl(5,5)` conformal carrier.

SymPy witness: `tools/sympy/conformal_rosetta_stone.py`

| Concept | 2×2 matrix (SymPy) | Cl(5,5) element | Lean file |
|---------|---------------------|-----------------|-----------|
| translation | `P = [[0,1],[0,0]]` | `u5` | `ConformalLieAlgebra55` |
| dilation | `D = [[1/2,0],[0,-1/2]]` | `D5` | `ConformalLieAlgebra55Dilation` |
| special conf. | `K = [[0,0],[1,0]]` | `v5` | `ConformalLieAlgebra55` |
| rapidity | `exp(λ·D)` | boost flow | `RapiditySpace` |
| inversion | `S = [[0,-1],[1,0]]` | `J = u5 - v5` | `ConformalReflection55` |
| Möbius T | `[[1,1],[0,1]]` | projective | `DiscreteMoebiusGroup` |
| V4 id | `I` | identity | `DiscreteMoebiusGroup` |
| V4 neg | `-I` | −identity | `DiscreteMoebiusGroup` |
| V4 rec | `[[0,1],[1,0]]` | r₂ reflection | `DiscreteMoebiusGroup` |
| V4 -rec | `[[0,-1],[-1,0]]` | r3 reflection | `DiscreteMoebiusGroup` |
* `Delta` operator = `exp(-2pi * D)` -- modular operator (RindlerWedge)
-/

/-! ## 5. clockAxis as intertwiner

The `clockAxis` operator `K = J·ε` is the intertwiner between the
Heisenberg (operator-side) and Schrödinger (carrier-side) representations
of the modular reflection J.

On the operator side: `clockAxis = modular_j ∘ spectral_epsilon` (Krein doubled space).
On the Clifford side: `clockAxis = modular_j ∘ cl11Rep(pseudoscalar)` (Clifford lift).
-/

theorem clockAxis_as_intertwiner (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] :
    InfoGeometry.Krein.clockAxis (E := E) =
    (InfoGeometry.Krein.modular_j (E := E)).comp (InfoGeometry.Krein.spectral_epsilon (E := E)) := by
  simp [InfoGeometry.Krein.clockAxis, InfoGeometry.Krein.complex_i]

/-! ## 7. Poincaré sphere compactification

SymPy witness: `tools/sympy/poincare_compactification.py`

The inversion `S : z ↦ -1/z` (or `J = u - v` in Cl(5,5)) maps the
outer null cone to the inner null cone, compactifying the boundary
at infinity.

Key identities:
  S² = -I                     (inversion is an involution up to sign)
  S·P·S⁻¹ = -K                (adjoint swaps translation ↔ special conformal)
  S·D·S⁻¹ = -D                (inversion flips the dilation sign)
  S·K·S⁻¹ = -P                (adjoint swaps special conformal ↔ translation)
  S·exp(λ·D)·S⁻¹ = exp(-λ·D)  (inversion flips the rapidity sign)
  S·T·S⁻¹ = lower shear        (conjugation swaps upper ↔ lower shear)
-/

end InfoGeometry.Canonical.ConformalSL2GeneratorBridge
