import Mathlib
import InfoGeometryCore.Basic

open InfoGeometryCore

/-!
# Finite V4 root-system socket

This module records the Klein four group table associated with the two sign
reflections of the finite `A₁ × A₁` root picture.  It proves the point-inversion
composition and involution laws.

#### BUCKET 1: CLOSED FINITE THEOREMS

* the Klein-four multiplication/involution table;
* the tripotent scalar spectrum `{-1,0,+1}` and projector-style classifiers;
* the finite `A₁ × A₁` sign-root action of `V₄`;
* a triality-shaped 3-cycle on the three non-identity `V₄` labels.

#### BUCKET 2: CONDITIONAL THEOREMS FROM EXPLICIT WITNESSES

None in this file.

#### BUCKET 3: OPEN CLOSURE DEBT

This file does **not** prove `SO(4)`, Lorentz symmetry, spin geometry,
`Cl(1,1)` representation equivalence, D₄/Spin(8) triality, a Klein-bottle
quotient theorem, wallpaper classification, or relativistic spacetime
emergence.  Those require additional representation/manifold/topology data not
present in this finite Cayley-table file.
-/

namespace InfoGeometry.Topology.V4RootSystem

/-- The four-element Klein group generated by two commuting sign reflections. -/
inductive V4Group where
  | I
  | W1
  | W2
  | W12
  deriving DecidableEq, Repr

open V4Group

/-- Multiplication table for the Klein four group. -/
def v4_mul : V4Group → V4Group → V4Group
  | I, x => x
  | x, I => x
  | W1, W1 => I
  | W2, W2 => I
  | W12, W12 => I
  | W1, W2 => W12
  | W2, W1 => W12
  | W1, W12 => W2
  | W12, W1 => W2
  | W2, W12 => W1
  | W12, W2 => W1

instance : Mul V4Group where
  mul := v4_mul

/-- The identity element of the finite Klein four group. -/
instance : One V4Group where
  one := I

/-- Every element of the finite Klein four group is its own inverse. -/
instance : Inv V4Group where
  inv := id

lemma v4_mul_assoc (a b c : V4Group) : (a * b) * c = a * (b * c) := by
  cases a <;> cases b <;> cases c <;> rfl

lemma v4_one_mul (a : V4Group) : 1 * a = a := by
  cases a <;> rfl

lemma v4_mul_one (a : V4Group) : a * 1 = a := by
  cases a <;> rfl

lemma v4_inv_mul_cancel (a : V4Group) : a⁻¹ * a = 1 := by
  cases a <;> rfl

/-- The finite Klein four group as an actual group structure. -/
instance : Group V4Group where
  one := 1
  mul := (· * ·)
  inv := (·⁻¹)
  mul_assoc := v4_mul_assoc
  one_mul := v4_one_mul
  mul_one := v4_mul_one
  inv_mul_cancel := v4_inv_mul_cancel

/-- On `V₄`, inversion is trivial. -/
theorem v4_inv_eq_self (x : V4Group) : x⁻¹ = x := by
  cases x <;> rfl

/-- Point inversion is the composition of the two coordinate sign reflections. -/
theorem varlamov_v4_inversion : W1 * W2 = W12 := by
  rfl

/-- The two coordinate sign reflections commute. -/
theorem v4_reflections_commute : W1 * W2 = W2 * W1 := by
  rfl

/-- Every element of the Klein four group is an involution. -/
theorem v4_involution (x : V4Group) : x * x = I := by
  cases x <;> rfl

/-- The point inversion is also an involution. -/
theorem v4_point_inversion_involution : W12 * W12 = I := by
  rfl

/-- The three non-identity `V₄` labels. -/
inductive NontrivialV4 where
  | x
  | y
  | xy
  deriving DecidableEq, Repr

namespace NontrivialV4

/-- Inclusion of the non-identity labels into the Klein-four group. -/
def toV4 : NontrivialV4 → V4Group
  | x => W1
  | y => W2
  | xy => W12

/-- Triality-shaped 3-cycle on the three non-identity `V₄` labels. -/
def trialityCycle : NontrivialV4 → NontrivialV4
  | x => y
  | y => xy
  | xy => x

/-- The non-identity `V₄` triality cycle has order three. -/
theorem trialityCycle_cube (g : NontrivialV4) :
    trialityCycle (trialityCycle (trialityCycle g)) = g := by
  cases g <;> rfl

/-- The triality cycle never lands on the identity after inclusion into `V₄`. -/
theorem trialityCycle_toV4_ne_identity (g : NontrivialV4) :
    toV4 (trialityCycle g) ≠ I := by
  cases g <;> decide

end NontrivialV4

/-- The four roots of the finite `A₁ × A₁` sign-root picture. -/
inductive A1xA1Root where
  | posX
  | negX
  | posY
  | negY
  deriving DecidableEq, Repr

namespace A1xA1Root

/-- Integer coordinates of the finite roots. -/
def coord : A1xA1Root → ℤ × ℤ
  | posX => (1, 0)
  | negX => (-1, 0)
  | posY => (0, 1)
  | negY => (0, -1)

/-- Every coordinate of every finite root lies in the tripotent spectrum. -/
theorem coord_tripotent_spectrum (r : A1xA1Root) :
    ((coord r).1 = -1 ∨ (coord r).1 = 0 ∨ (coord r).1 = 1) ∧
      ((coord r).2 = -1 ∨ (coord r).2 = 0 ∨ (coord r).2 = 1) := by
  cases r <;> simp [coord]

/-- The first coordinate sign reflection. -/
def reflectX : A1xA1Root → A1xA1Root
  | posX => negX
  | negX => posX
  | posY => posY
  | negY => negY

/-- The second coordinate sign reflection. -/
def reflectY : A1xA1Root → A1xA1Root
  | posX => posX
  | negX => negX
  | posY => negY
  | negY => posY

/-- Point inversion on the `A₁ × A₁` root set. -/
def pointInvert : A1xA1Root → A1xA1Root
  | posX => negX
  | negX => posX
  | posY => negY
  | negY => posY

/-- `reflectX` is an involution. -/
theorem reflectX_involutive : Function.Involutive reflectX := by
  intro r
  cases r <;> rfl

/-- `reflectY` is an involution. -/
theorem reflectY_involutive : Function.Involutive reflectY := by
  intro r
  cases r <;> rfl

/-- Point inversion is an involution on the finite root set. -/
theorem pointInvert_involutive : Function.Involutive pointInvert := by
  intro r
  cases r <;> rfl

/-- The two coordinate reflections commute on the finite roots. -/
theorem reflectX_reflectY_commute (r : A1xA1Root) :
    reflectX (reflectY r) = reflectY (reflectX r) := by
  cases r <;> rfl

/-- The composition of the two coordinate reflections is point inversion. -/
theorem reflectX_reflectY_eq_pointInvert (r : A1xA1Root) :
    reflectX (reflectY r) = pointInvert r := by
  cases r <;> rfl

/-- The concrete `V₄` action on finite `A₁ × A₁` roots. -/
def v4Action : V4Group → A1xA1Root → A1xA1Root
  | I => id
  | W1 => reflectX
  | W2 => reflectY
  | W12 => pointInvert

/-- Every element of the concrete `V₄` action is an involution. -/
theorem v4Action_involutive (g : V4Group) : Function.Involutive (v4Action g) := by
  intro r
  cases g <;> cases r <;> rfl

/-- The finite action respects multiplication in the Klein-four table. -/
theorem v4Action_mul (g h : V4Group) (r : A1xA1Root) :
    v4Action (g * h) r = v4Action g (v4Action h r) := by
  cases g <;> cases h <;> cases r <;> rfl

end A1xA1Root

/--
Finite Varlamov/V₄/trifactor statement: the closed content is only tripotent
classification, the `A₁ × A₁` root action, and a triality-shaped 3-cycle on the
three non-identity `V₄` labels.
-/
structure VarlamovV4TrifactorTrialityStatement where
  cube_eq_self : ∀ s : TripotentState, TripotentState.toInt s ^ 3 = TripotentState.toInt s
  trifactor_projector_partition : ∀ s : TripotentState,
      TripotentState.pNeg s + TripotentState.pZero s + TripotentState.pPos s = 1
  trifactor_projector_idempotent_neg : ∀ s : TripotentState,
      TripotentState.pNeg s * TripotentState.pNeg s = TripotentState.pNeg s
  trifactor_projector_idempotent_zero : ∀ s : TripotentState,
        TripotentState.pZero s * TripotentState.pZero s = TripotentState.pZero s
  trifactor_projector_idempotent_pos : ∀ s : TripotentState,
        TripotentState.pPos s * TripotentState.pPos s = TripotentState.pPos s
  trialityCycle_cube : ∀ g : NontrivialV4, NontrivialV4.trialityCycle
      (NontrivialV4.trialityCycle (NontrivialV4.trialityCycle g)) = g
  v4Action_involutive : ∀ g : V4Group, Function.Involutive (A1xA1Root.v4Action g)
  v4Action_mul : ∀ g h : V4Group, ∀ r : A1xA1Root,
      A1xA1Root.v4Action (g * h) r =
        A1xA1Root.v4Action g (A1xA1Root.v4Action h r)

/-- The finite Varlamov/V₄/trifactor/triality statement is fully closed and instantiated. -/
def varlamov_v4_trifactor_triality_packet : VarlamovV4TrifactorTrialityStatement := {
  cube_eq_self := TripotentState.cube_eq_self,
  trifactor_projector_partition := TripotentState.trifactor_projector_partition,
  trifactor_projector_idempotent_neg := fun s => (TripotentState.trifactor_projector_idempotent s).1,
  trifactor_projector_idempotent_zero := fun s => (TripotentState.trifactor_projector_idempotent s).2.1,
  trifactor_projector_idempotent_pos := fun s => (TripotentState.trifactor_projector_idempotent s).2.2,
  trialityCycle_cube := NontrivialV4.trialityCycle_cube,
  v4Action_involutive := A1xA1Root.v4Action_involutive,
  v4Action_mul := A1xA1Root.v4Action_mul
}

end InfoGeometry.Topology.V4RootSystem
