import InfoGeometry.Tessellation.Incidence
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Tactic

/-!
# Tessellation volume transport

This file owns the finite algebraic `H^1` volume/trace transport theorem.

It is separate from `Tessellation.Incidence`: incidence proves that supported
arrows between orthogonal idempotent sectors are square-zero.  This file starts
from square-zero data, builds the unipotent unit `1 + N`, and applies mathlib's
matrix unit-conjugation invariance theorems for determinant and trace.

No analytic exponential, symplectic capacity, Gromov--Witten invariant, entropy
formula, or cyclic cohomology statement is asserted here.
-/

namespace InfoGeometry.Tessellation

/-! ## Unit conjugation preserves sectors -/

/-- Ring-level unit conjugation. -/
def unitConjRing {A : Type*} [Monoid A] (g : Aˣ) (x : A) : A :=
  (g : A) * x * ((g⁻¹ : Aˣ) : A)

/--
Unit conjugation preserves idempotents, hence sends causal diamonds to causal
diamonds.
-/
theorem unitConj_idempotent
    {A : Type*} [Monoid A]
    (g : Aˣ) {P : A}
    (hP : P * P = P) :
    unitConjRing g P * unitConjRing g P = unitConjRing g P := by
  unfold unitConjRing
  calc
    ((g : A) * P * ((g⁻¹ : Aˣ) : A)) * ((g : A) * P * ((g⁻¹ : Aˣ) : A))
        = (g : A) * P * (((g⁻¹ : Aˣ) : A) * (g : A)) * P *
            ((g⁻¹ : Aˣ) : A) := by
            simp [mul_assoc]
    _ = (g : A) * (P * P) * ((g⁻¹ : Aˣ) : A) := by
            simp [mul_assoc]
    _ = (g : A) * P * ((g⁻¹ : Aˣ) : A) := by
            rw [hP]

/-! ## Square-zero unipotent units -/

/-- A square-zero element generates the unit `1 + x` with inverse `1 - x`. -/
def squareZeroUnit {A : Type*} [Ring A] (x : A) (hx : x * x = 0) : Aˣ where
  val := 1 + x
  inv := 1 - x
  val_inv := by
    noncomm_ring [hx]
  inv_val := by
    noncomm_ring [hx]

@[simp]
theorem squareZeroUnit_val
    {A : Type*} [Ring A] (x : A) (hx : x * x = 0) :
    (squareZeroUnit x hx : A) = 1 + x :=
  rfl

@[simp]
theorem squareZeroUnit_inv_val
    {A : Type*} [Ring A] (x : A) (hx : x * x = 0) :
    (((squareZeroUnit x hx)⁻¹ : Aˣ) : A) = 1 - x :=
  rfl

/-- The unipotent flow unit attached to explicit supported-incidence data. -/
def supportedLightrayFlowUnit
    {A : Type*} [Ring A] {P Q N : A}
    (hPQ : P * Q = 0) (hQN : Q * N = N) (hNP : N * P = N) : Aˣ :=
  squareZeroUnit N (incident_lightray_square_zero hPQ hQN hNP)

@[simp]
theorem supportedLightrayFlowUnit_val
    {A : Type*} [Ring A] {P Q N : A}
    (hPQ : P * Q = 0) (hQN : Q * N = N) (hNP : N * P = N) :
    (supportedLightrayFlowUnit hPQ hQN hNP : A) = 1 + N :=
  rfl

/-! ## Matrix lightray units -/

open Matrix

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- A scalar multiple of a square-zero matrix is square-zero. -/
theorem smul_square_zero_matrix
    {R : Type*} [CommRing R]
    (t : R) {N : Matrix ι ι R} (hN : N * N = 0) :
    (t • N) * (t • N) = 0 := by
  rw [smul_mul_smul, hN, smul_zero]

/--
The unit `1 + t • N` generated by a square-zero matrix lightray.

This is the finite algebraic flow `G_t`; its inverse is `1 - t • N`.
-/
def lightrayFlowUnit
    {R : Type*} [CommRing R]
    (t : R) (N : Matrix ι ι R) (hN : N * N = 0) : (Matrix ι ι R)ˣ :=
  squareZeroUnit (t • N) (smul_square_zero_matrix t hN)

@[simp]
theorem lightrayFlowUnit_val
    {R : Type*} [CommRing R]
    (t : R) (N : Matrix ι ι R) (hN : N * N = 0) :
    (lightrayFlowUnit t N hN : Matrix ι ι R) = 1 + t • N :=
  rfl

@[simp]
theorem lightrayFlowUnit_inv_val
    {R : Type*} [CommRing R]
    (t : R) (N : Matrix ι ι R) (hN : N * N = 0) :
    (((lightrayFlowUnit t N hN)⁻¹ : (Matrix ι ι R)ˣ) : Matrix ι ι R) =
      1 - t • N :=
  rfl

/--
The lightray flow unit attached to a matrix incidence datum.

The square-zero input is derived from the source/target support laws and
directional orthogonality; it is not an extra field or hypothesis socket.
-/
def incidentLightrayFlowUnit
    {R : Type*} [CommRing R]
    (t : R)
    {src tgt : Diamond (Matrix ι ι R)}
    (L : IncidentLightray (Matrix ι ι R) src tgt)
    (horth : Diamond.OrthogonalForRay src tgt) :
    (Matrix ι ι R)ˣ :=
  lightrayFlowUnit t L.N (L.square_zero_of_orthogonal horth)

@[simp]
theorem incidentLightrayFlowUnit_val
    {R : Type*} [CommRing R]
    (t : R)
    {src tgt : Diamond (Matrix ι ι R)}
    (L : IncidentLightray (Matrix ι ι R) src tgt)
    (horth : Diamond.OrthogonalForRay src tgt) :
    (incidentLightrayFlowUnit t L horth : Matrix ι ι R) = 1 + t • L.N :=
  rfl

@[simp]
theorem incidentLightrayFlowUnit_inv_val
    {R : Type*} [CommRing R]
    (t : R)
    {src tgt : Diamond (Matrix ι ι R)}
    (L : IncidentLightray (Matrix ι ι R) src tgt)
    (horth : Diamond.OrthogonalForRay src tgt) :
    (((incidentLightrayFlowUnit t L horth)⁻¹ : (Matrix ι ι R)ˣ) :
        Matrix ι ι R) =
      1 - t • L.N :=
  rfl

/-! ## Determinant and trace transport -/

/-- Matrix unit conjugation. -/
def unitConj {R : Type*} [Semiring R]
    (g : (Matrix ι ι R)ˣ) (A : Matrix ι ι R) : Matrix ι ι R :=
  (g : Matrix ι ι R) * A * ((g⁻¹ : (Matrix ι ι R)ˣ) : Matrix ι ι R)

/-- Alias with the matrix-specific name used by the tessellation layer. -/
def matrixUnitConj {R : Type*} [Semiring R]
    (g : (Matrix ι ι R)ˣ) (A : Matrix ι ι R) : Matrix ι ι R :=
  unitConj g A

/--
Determinant volume is preserved by unit conjugation.

This is the determinant part of finite incidence volume transport.
-/
theorem det_unitConj
    {R : Type*} [CommRing R]
    (g : (Matrix ι ι R)ˣ) (A : Matrix ι ι R) :
    Matrix.det (unitConj g A) = Matrix.det A := by
  exact Matrix.det_units_conj g A

/-- Determinant volume is preserved by matrix unit conjugation. -/
theorem det_matrixUnitConj
    {R : Type*} [CommRing R]
    (g : (Matrix ι ι R)ˣ) (A : Matrix ι ι R) :
    Matrix.det (matrixUnitConj g A) = Matrix.det A := by
  exact det_unitConj g A

/--
Trace is preserved by unit conjugation.

This is the additive/log-generator part of finite incidence volume transport.
-/
theorem trace_unitConj
    {R : Type*} [CommSemiring R]
    (g : (Matrix ι ι R)ˣ) (A : Matrix ι ι R) :
    Matrix.trace (unitConj g A) = Matrix.trace A := by
  exact Matrix.trace_units_conj g A

/-- Trace is preserved by matrix unit conjugation. -/
theorem trace_matrixUnitConj
    {R : Type*} [CommSemiring R]
    (g : (Matrix ι ι R)ˣ) (A : Matrix ι ι R) :
    Matrix.trace (matrixUnitConj g A) = Matrix.trace A := by
  exact trace_unitConj g A

/-- Determinant rigidity for the unit generated by explicit supported-incidence data. -/
theorem det_supported_lightray_conj
    {R : Type*} [CommRing R]
    {P Q N : Matrix ι ι R}
    (hPQ : P * Q = 0) (hQN : Q * N = N) (hNP : N * P = N)
    (A : Matrix ι ι R) :
    Matrix.det (unitConj (supportedLightrayFlowUnit hPQ hQN hNP) A) =
      Matrix.det A :=
  det_unitConj (supportedLightrayFlowUnit hPQ hQN hNP) A

/-- Trace rigidity for the unit generated by explicit supported-incidence data. -/
theorem trace_supported_lightray_conj
    {R : Type*} [CommRing R]
    {P Q N : Matrix ι ι R}
    (hPQ : P * Q = 0) (hQN : Q * N = N) (hNP : N * P = N)
    (A : Matrix ι ι R) :
    Matrix.trace (unitConj (supportedLightrayFlowUnit hPQ hQN hNP) A) =
      Matrix.trace A :=
  trace_unitConj (supportedLightrayFlowUnit hPQ hQN hNP) A

/-- Determinant rigidity for the finite lightray flow `G_t = 1 + t • N`. -/
theorem det_square_zero_lightray_conj
    {R : Type*} [CommRing R]
    (t : R) {N : Matrix ι ι R} (hN : N * N = 0) (A : Matrix ι ι R) :
    Matrix.det (unitConj (lightrayFlowUnit t N hN) A) = Matrix.det A :=
  det_unitConj (lightrayFlowUnit t N hN) A

/-- Trace rigidity for the finite lightray flow `G_t = 1 + t • N`. -/
theorem trace_square_zero_lightray_conj
    {R : Type*} [CommRing R]
    (t : R) {N : Matrix ι ι R} (hN : N * N = 0) (A : Matrix ι ι R) :
    Matrix.trace (unitConj (lightrayFlowUnit t N hN) A) = Matrix.trace A :=
  trace_unitConj (lightrayFlowUnit t N hN) A

/-- H¹ determinant rigidity under the flow generated by an incident lightray. -/
theorem volume_rigidity
    {R : Type*} [CommRing R]
    (t : R)
    {src tgt : Diamond (Matrix ι ι R)}
    (L : IncidentLightray (Matrix ι ι R) src tgt)
    (horth : Diamond.OrthogonalForRay src tgt)
    (A : Matrix ι ι R) :
    Matrix.det (matrixUnitConj (incidentLightrayFlowUnit t L horth) A) =
      Matrix.det A := by
  exact det_matrixUnitConj (incidentLightrayFlowUnit t L horth) A

/-- Trace rigidity under the flow generated by an incident lightray. -/
theorem trace_rigidity
    {R : Type*} [CommRing R]
    (t : R)
    {src tgt : Diamond (Matrix ι ι R)}
    (L : IncidentLightray (Matrix ι ι R) src tgt)
    (horth : Diamond.OrthogonalForRay src tgt)
    (A : Matrix ι ι R) :
    Matrix.trace (matrixUnitConj (incidentLightrayFlowUnit t L horth) A) =
      Matrix.trace A := by
  exact trace_matrixUnitConj (incidentLightrayFlowUnit t L horth) A

end InfoGeometry.Tessellation


import Mathlib.Data.Real.Basic

/-- An unproven conjecture represented as a compiling definition. -/
theorem riemann_hypothesis : ∀ (s : ℂ), RiemannZeta s = 0 → s.re = 1/2 ∨ ∃ (n : ℤ), s = -2 * n := by
  sorry