import proofs.KleinPresentedGroup
import Mathlib.GroupTheory.SemidirectProduct

/-!
# The presented Klein group as an integral semidirect product

This file identifies the presentation `⟨a,b | aba⁻¹=b⁻¹⟩` with
`Z ⋊ Z`, where the second copy acts on the first by parity-dependent
inversion.  The first factor is generated by `b`; the second by `a`.
-/

namespace KleinAffineDeckGroup

open KleinPresentedGroup

abbrev ZMul := Multiplicative ℤ
abbrev ParityMul := Multiplicative (ZMod 2)

/-- Inversion of the multiplicative copy of `ℤ`. -/
def inversionAut : MulAut ZMul :=
  AddEquiv.toMultiplicative (AddEquiv.neg ℤ)

/-- The nontrivial element of `ZMod 2` acts by inversion. -/
def parityAction : ParityMul →* MulAut ZMul where
  toFun e := if e.toAdd = 0 then 1 else inversionAut
  map_one' := by simp
  map_mul' x y := by
    have h11 : (1 + 1 : ZMod 2) = 0 := by native_decide
    obtain ⟨a, rfl⟩ : ∃ a : ZMod 2, Multiplicative.ofAdd a = x := ⟨x.toAdd, rfl⟩
    obtain ⟨b, rfl⟩ : ∃ b : ZMod 2, Multiplicative.ofAdd b = y := ⟨y.toAdd, rfl⟩
    fin_cases a <;> fin_cases b <;>
      ext n <;> simp [inversionAut, h11]

/-- Reduction modulo two, viewed multiplicatively. -/
def parityHom : ZMul →* ParityMul :=
  AddMonoidHom.toMultiplicative (Int.castAddHom (ZMod 2))

/-- The integral parity action used by the Klein semidirect product. -/
def kleinAction : ZMul →* MulAut ZMul :=
  parityAction.comp parityHom

/-- Concrete normal-form group: elements are `b^n a^m`. -/
abbrev AffineKleinGroup := ZMul ⋊[kleinAction] ZMul

def bGen : AffineKleinGroup := SemidirectProduct.inl (Multiplicative.ofAdd 1)
def aGen : AffineKleinGroup := SemidirectProduct.inr (Multiplicative.ofAdd 1)

@[simp] theorem kleinAction_one_apply (n : ZMul) :
    kleinAction (Multiplicative.ofAdd 1) n = n⁻¹ := by
  change inversionAut n = n⁻¹
  rfl

theorem affine_klein_relation : aGen * bGen * aGen⁻¹ = bGen⁻¹ := by
  change SemidirectProduct.inr (Multiplicative.ofAdd 1) *
      SemidirectProduct.inl (Multiplicative.ofAdd 1) *
      (SemidirectProduct.inr (Multiplicative.ofAdd 1))⁻¹ =
    (SemidirectProduct.inl (Multiplicative.ofAdd 1))⁻¹
  calc
    _ = SemidirectProduct.inl
          (kleinAction (Multiplicative.ofAdd 1) (Multiplicative.ofAdd 1)) :=
      (SemidirectProduct.inl_aut _ _).symm
    _ = _ := by ext <;> simp

/-- The map from the presentation to affine normal forms. -/
def presentedToAffine : KleinGroup →* AffineKleinGroup :=
  kleinRep aGen bGen affine_klein_relation

/-- Integer powers of the presented `b` and `a` generators. -/
def bPowers : ZMul →* KleinGroup :=
  zpowersHom KleinGroup (toKlein genB)

def aPowers : ZMul →* KleinGroup :=
  zpowersHom KleinGroup (toKlein genA)

theorem presented_klein_relation :
    toKlein genA * toKlein genB * (toKlein genA)⁻¹ = (toKlein genB)⁻¹ := by
  have h := kleinRelator_eq_one
  change toKlein genA * toKlein genB * (toKlein genA)⁻¹ * toKlein genB = 1 at h
  exact eq_inv_of_mul_eq_one_left h

theorem kleinAction_add_one_apply (m : ℤ) (n : ZMul) :
    kleinAction (Multiplicative.ofAdd (m + 1)) n =
      (kleinAction (Multiplicative.ofAdd m) n)⁻¹ := by
  rw [show Multiplicative.ofAdd (m + 1) =
      Multiplicative.ofAdd m * Multiplicative.ofAdd 1 by rfl, map_mul]
  simp

theorem kleinAction_sub_one_apply (m : ℤ) (n : ZMul) :
    kleinAction (Multiplicative.ofAdd (m - 1)) n =
      (kleinAction (Multiplicative.ofAdd m) n)⁻¹ := by
  rw [show Multiplicative.ofAdd (m - 1) =
      Multiplicative.ofAdd m * Multiplicative.ofAdd (-1) by rfl, map_mul]
  change kleinAction (Multiplicative.ofAdd m) (inversionAut n) = _
  simp [inversionAut]

theorem powers_compatibility (m : ZMul) :
    bPowers.comp (kleinAction m).toMonoidHom =
      (MulAut.conj (aPowers m)).toMonoidHom.comp bPowers := by
  apply MonoidHom.ext_mint
  obtain ⟨m, rfl⟩ : ∃ z : ℤ, Multiplicative.ofAdd z = m := ⟨m.toAdd, rfl⟩
  change (toKlein genB) ^ (kleinAction (Multiplicative.ofAdd m)
      (Multiplicative.ofAdd 1)).toAdd =
    aPowers (Multiplicative.ofAdd m) * (toKlein genB) *
      (aPowers (Multiplicative.ofAdd m))⁻¹
  -- Both sides depend only on the parity of `m`; integer induction uses the
  -- defining Klein relation for the successor step.
  induction m using Int.induction_on with
  | zero => simp [aPowers, kleinAction, parityHom, parityAction]
  | succ m ih =>
      rw [kleinAction_add_one_apply]
      rw [show ((kleinAction (Multiplicative.ofAdd (m : ℤ))
          (Multiplicative.ofAdd 1))⁻¹).toAdd =
          -(kleinAction (Multiplicative.ofAdd (m : ℤ))
            (Multiplicative.ofAdd 1)).toAdd by rfl, zpow_neg]
      change (toKlein genB ^
          (kleinAction (Multiplicative.ofAdd (m : ℤ)) (Multiplicative.ofAdd 1)).toAdd)⁻¹ = _
      rw [ih]
      change ((toKlein genA) ^ (m : ℤ) * toKlein genB *
          ((toKlein genA) ^ (m : ℤ))⁻¹)⁻¹ =
        (toKlein genA) ^ ((m : ℤ) + 1) * toKlein genB *
          ((toKlein genA) ^ ((m : ℤ) + 1))⁻¹
      rw [zpow_add_one]
      calc
        ((toKlein genA) ^ (m : ℤ) * toKlein genB *
            ((toKlein genA) ^ (m : ℤ))⁻¹)⁻¹ =
            (toKlein genA) ^ (m : ℤ) * (toKlein genB)⁻¹ *
              ((toKlein genA) ^ (m : ℤ))⁻¹ := by group
        _ = (toKlein genA) ^ (m : ℤ) * toKlein genA * toKlein genB *
              (toKlein genA)⁻¹ * ((toKlein genA) ^ (m : ℤ))⁻¹ := by
              rw [← presented_klein_relation]
              group
        _ = (toKlein genA) ^ (m : ℤ) * toKlein genA * toKlein genB *
              ((toKlein genA) ^ (m : ℤ) * toKlein genA)⁻¹ := by group
  | pred m ih =>
      rw [show -((m : ℤ)) - 1 = -((m : ℤ)) - 1 by rfl,
        kleinAction_sub_one_apply]
      rw [show ((kleinAction (Multiplicative.ofAdd (-(m : ℤ)))
          (Multiplicative.ofAdd 1))⁻¹).toAdd =
          -(kleinAction (Multiplicative.ofAdd (-(m : ℤ)))
            (Multiplicative.ofAdd 1)).toAdd by rfl, zpow_neg]
      change (toKlein genB ^
          (kleinAction (Multiplicative.ofAdd (-(m : ℤ))) (Multiplicative.ofAdd 1)).toAdd)⁻¹ = _
      rw [ih]
      change ((toKlein genA) ^ (-(m : ℤ)) * toKlein genB *
          ((toKlein genA) ^ (-(m : ℤ)))⁻¹)⁻¹ =
        (toKlein genA) ^ (-(m : ℤ) - 1) * toKlein genB *
          ((toKlein genA) ^ (-(m : ℤ) - 1))⁻¹
      rw [show (-(m : ℤ) - 1) = -(m : ℤ) + (-1) by ring, zpow_add,
        zpow_neg_one]
      have hinv : toKlein genA * (toKlein genB)⁻¹ * (toKlein genA)⁻¹ =
          toKlein genB := by
        calc
          _ = (toKlein genA * toKlein genB * (toKlein genA)⁻¹)⁻¹ := by group
          _ = _ := by rw [presented_klein_relation]; simp
      have hrelInv : (toKlein genA)⁻¹ * toKlein genB * toKlein genA =
          (toKlein genB)⁻¹ := by
        calc
          _ = (toKlein genA)⁻¹ *
              (toKlein genA * (toKlein genB)⁻¹ * (toKlein genA)⁻¹) *
              toKlein genA := congrArg
                (fun x ↦ (toKlein genA)⁻¹ * x * toKlein genA) hinv.symm
          _ = _ := by group
      calc
        ((toKlein genA) ^ (-(m : ℤ)) * toKlein genB *
            ((toKlein genA) ^ (-(m : ℤ)))⁻¹)⁻¹ =
            (toKlein genA) ^ (-(m : ℤ)) * (toKlein genB)⁻¹ *
              ((toKlein genA) ^ (-(m : ℤ)))⁻¹ := by group
        _ = (toKlein genA) ^ (-(m : ℤ)) * (toKlein genA)⁻¹ *
              toKlein genB * toKlein genA *
              ((toKlein genA) ^ (-(m : ℤ)))⁻¹ := by
              rw [← hrelInv]
              group
        _ = (toKlein genA) ^ (-(m : ℤ)) * (toKlein genA)⁻¹ *
              toKlein genB *
              ((toKlein genA) ^ (-(m : ℤ)) * (toKlein genA)⁻¹)⁻¹ := by group

/-- The normal-form map back to the presented group. -/
def affineToPresented : AffineKleinGroup →* KleinGroup :=
  SemidirectProduct.lift bPowers aPowers powers_compatibility

@[simp] theorem presentedToAffine_a : presentedToAffine (toKlein genA) = aGen :=
  (kleinRep_relator_relation aGen bGen affine_klein_relation).1

@[simp] theorem presentedToAffine_b : presentedToAffine (toKlein genB) = bGen :=
  (kleinRep_relator_relation aGen bGen affine_klein_relation).2

@[simp] theorem affineToPresented_inl (n : ZMul) :
    affineToPresented (SemidirectProduct.inl n) = bPowers n := by
  exact SemidirectProduct.lift_inl _ _ _ _

@[simp] theorem affineToPresented_inr (m : ZMul) :
    affineToPresented (SemidirectProduct.inr m) = aPowers m := by
  exact SemidirectProduct.lift_inr _ _ _ _

theorem presentedToAffine_after_affineToPresented (x : AffineKleinGroup) :
    presentedToAffine (affineToPresented x) = x := by
  rw [← SemidirectProduct.inl_left_mul_inr_right x, map_mul]
  rw [map_mul]
  congr 1
  · rw [affineToPresented_inl]
    apply DFunLike.congr_fun
      (MonoidHom.ext_mint (f := presentedToAffine.comp bPowers)
        (g := SemidirectProduct.inl) (by
          change presentedToAffine (toKlein genB) = bGen
          exact presentedToAffine_b))
  · rw [affineToPresented_inr]
    apply DFunLike.congr_fun
      (MonoidHom.ext_mint (f := presentedToAffine.comp aPowers)
        (g := SemidirectProduct.inr) (by
          change presentedToAffine (toKlein genA) = aGen
          exact presentedToAffine_a))

theorem affineToPresented_after_presentedToAffine (x : KleinGroup) :
    affineToPresented (presentedToAffine x) = x := by
  refine Quotient.inductionOn x ?_
  intro w
  change affineToPresented (presentedToAffine (toKlein w)) = toKlein w
  refine FreeGroup.induction_on w ?_ ?_ ?_ ?_
  · simp
  · intro g
    cases g
    · change affineToPresented (presentedToAffine (toKlein genA)) = toKlein genA
      rw [presentedToAffine_a]
      change affineToPresented (SemidirectProduct.inr (Multiplicative.ofAdd 1)) = _
      rw [affineToPresented_inr]
      rfl
    · change affineToPresented (presentedToAffine (toKlein genB)) = toKlein genB
      rw [presentedToAffine_b]
      change affineToPresented (SemidirectProduct.inl (Multiplicative.ofAdd 1)) = _
      rw [affineToPresented_inl]
      rfl
  · intro g ih
    simpa using congrArg Inv.inv ih
  · intro x y hx hy
    simpa only [map_mul] using congrArg₂ (· * ·) hx hy

/-- Native group equivalence between affine normal forms and the presentation. -/
def affineKleinEquivPresented : AffineKleinGroup ≃* KleinGroup where
  toFun := affineToPresented
  invFun := presentedToAffine
  left_inv := presentedToAffine_after_affineToPresented
  right_inv := affineToPresented_after_presentedToAffine
  map_mul' := map_mul affineToPresented

end KleinAffineDeckGroup
