import InfoGeometry.Orthogonal.O55MultigradedAll
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Orthogonal.O55RealWittForm
import InfoGeometry.Canonical.O55RealComplexMultigradedClosure
