import InfoGeometry.Canonical.CausalFunctor
import InfoGeometry.OperatorAlgebra.CliffordInfinityCAR
import InfoGeometry.Algebraic.SplitQuadraticForm
import Mathlib.CategoryTheory.Category.Preorder
import Mathlib.CategoryTheory.Limits.HasLimits

open CategoryTheory Limits
open InfoGeometry.OperatorAlgebra
open InfoGeometry.Algebraic.SplitSignature

/-!
# The Clifford-Causal Bridge

This formalizes the connection between the Causal Universe architecture
and the explicit Clifford Tower `Cl_functor`.

We prove that the `Cl_functor` over `ℕ` is structurally a `CausalFunctor`,
and that the resulting `CliffordInfinity` is identically its `UniversalCausalFuture`.
-/

namespace InfoGeometry.Canonical

/-- 
  The discrete sequence of scales/times `ℕ` equipped with causality,
  acting as the domain for the Causal Functor. 
-/
abbrev DiscreteSpacetime := CausalSpacetime ℕ

/--
  The Clifford Functor is formally cast as a Causal Functor.
  The arrows `m ≤ n` are exactly the causal light rays bonding the sequence
  of Clifford algebras `Cl(n,n)`.
-/
def cliffordCausalFunctor : CausalFunctor ℕ :=
  Cl_functor

/--
  The formal proof that the analytic limit `CliffordInfinity`
  is exactly the `UniversalCausalFuture` generated by the causal spacetime category.
-/
noncomputable def cliffordInfinityIsUniversalCausalFuture :
    UniversalCausalFuture cliffordCausalFunctor = CliffordInfinity :=
  rfl

/--
  The structural verification that information propagating through the Clifford
  tower is fully conserved inside the Universal Causal Future.
-/
theorem clifford_information_conservation 
    (m n : ℕ) (causal_link : m ≤ n) (x : Cl_nn m) :
    (colimit.ι cliffordCausalFunctor m) x = 
      (colimit.ι cliffordCausalFunctor n) ((Cl_bonding_map_of_le causal_link) x) := by
  -- Follows identically from the universal causal conservation law.
  have h_conserv := causal_information_conservation cliffordCausalFunctor causal_link x
  exact h_conserv

end InfoGeometry.Canonical
