import Mathlib
import InfoGeometry.Canonical.TwoSheetThreeColorWeyl
import InfoGeometry.Topology.AharonovBohmConcreteVortex

/-!
# The canonical nine-word qutrit Weyl family

This owner records the concrete finite operator family generated by the
canonical colour shift and clock.  It proves its linear independence directly
from matrix entries; no abstract basis or witness structure is postulated.
-/

noncomputable section

namespace InfoGeometry.Canonical.QutritWeylOperatorBasis

open Matrix
open InfoGeometry.Canonical.TwoSheetThreeColorWeyl
open InfoGeometry.Topology.Parafermion

abbrev QutritMatrix := Matrix (Fin 3) (Fin 3) ℂ

def weylWord (a b : Fin 3) : QutritMatrix :=
  colorShift ^ (a : ℕ) * colorClock omega ^ (b : ℕ)

theorem weyl_clock_mul_shift_pow (c : ℕ) :
    colorClock omega * colorShift ^ c =
      omega ^ c • (colorShift ^ c * colorClock omega) := by
  induction c with
  | zero => simp
  | succ c ih =>
      calc
        colorClock omega * colorShift ^ (c + 1) =
            (colorClock omega * colorShift ^ c) * colorShift := by
              rw [pow_succ, mul_assoc]
        _ = (omega ^ c • (colorShift ^ c * colorClock omega)) * colorShift := by
              rw [ih]
        _ = omega ^ c • (colorShift ^ c * (colorClock omega * colorShift)) := by
              simp [mul_assoc]
        _ = omega ^ (c + 1) • (colorShift ^ (c + 1) * colorClock omega) := by
              rw [color_weyl_relation omega omega_cube_eq_one]
              simp [pow_succ, smul_smul, mul_assoc]

theorem weyl_clock_pow_mul_shift_pow (b c : ℕ) :
    colorClock omega ^ b * colorShift ^ c =
      omega ^ (b * c) • (colorShift ^ c * colorClock omega ^ b) := by
  induction b with
  | zero => simp
  | succ b ih =>
      calc
        colorClock omega ^ (b + 1) * colorShift ^ c =
            colorClock omega ^ b *
              (colorClock omega * colorShift ^ c) := by
                rw [pow_succ, mul_assoc]
        _ = colorClock omega ^ b *
              (omega ^ c • (colorShift ^ c * colorClock omega)) := by
                rw [weyl_clock_mul_shift_pow]
        _ = omega ^ c •
              (colorClock omega ^ b * (colorShift ^ c * colorClock omega)) := by
                rw [Matrix.mul_smul]
        _ = omega ^ c •
              (omega ^ (b * c) •
                ((colorShift ^ c * colorClock omega ^ b) * colorClock omega)) := by
                congr 1
                calc
                  colorClock omega ^ b *
                      (colorShift ^ c * colorClock omega) =
                    (colorClock omega ^ b * colorShift ^ c) *
                      colorClock omega := by simp [mul_assoc]
                  _ = (omega ^ (b * c) •
                      (colorShift ^ c * colorClock omega ^ b)) *
                      colorClock omega := by rw [ih]
                  _ = omega ^ (b * c) •
                      ((colorShift ^ c * colorClock omega ^ b) *
                        colorClock omega) := by rw [smul_mul_assoc]
        _ = omega ^ ((b + 1) * c) •
              (colorShift ^ c * colorClock omega ^ (b + 1)) := by
                simp [pow_succ, pow_add, add_mul, smul_smul, mul_assoc, add_comm]

theorem weylWord_mul_nat (a b c d : ℕ) :
    (colorShift ^ a * colorClock omega ^ b) *
        (colorShift ^ c * colorClock omega ^ d) =
      omega ^ (b * c) •
        (colorShift ^ (a + c) * colorClock omega ^ (b + d)) := by
  calc
    (colorShift ^ a * colorClock omega ^ b) *
        (colorShift ^ c * colorClock omega ^ d) =
      colorShift ^ a *
        (colorClock omega ^ b * (colorShift ^ c * colorClock omega ^ d)) := by
          simp only [mul_assoc]
    _ = colorShift ^ a *
        ((colorClock omega ^ b * colorShift ^ c) * colorClock omega ^ d) := by
          simp only [mul_assoc]
    _ = colorShift ^ a *
        ((omega ^ (b * c) •
          (colorShift ^ c * colorClock omega ^ b)) * colorClock omega ^ d) := by
          rw [weyl_clock_pow_mul_shift_pow]
    _ = omega ^ (b * c) •
        (colorShift ^ a *
          ((colorShift ^ c * colorClock omega ^ b) * colorClock omega ^ d)) := by
          simp [mul_assoc]
    _ = omega ^ (b * c) •
        (colorShift ^ (a + c) * colorClock omega ^ (b + d)) := by
          simp [pow_add, mul_assoc]

theorem colorShift_pow_fin_add (a c : Fin 3) :
    colorShift ^ ((a : ℕ) + (c : ℕ)) =
      colorShift ^ ((a + c : Fin 3) : ℕ) := by
  rw [pow_eq_pow_mod (a + c : ℕ) colorShift_cubed, Fin.val_add]

theorem colorClock_pow_fin_add (b d : Fin 3) :
    colorClock omega ^ ((b : ℕ) + (d : ℕ)) =
      colorClock omega ^ ((b + d : Fin 3) : ℕ) := by
  rw [pow_eq_pow_mod (b + d : ℕ)
      (colorClock_cubed omega omega_cube_eq_one), Fin.val_add]

theorem weylWord_mul (a b c d : Fin 3) :
    weylWord a b * weylWord c d =
      omega ^ ((b : ℕ) * (c : ℕ)) • weylWord (a + c) (b + d) := by
  change (colorShift ^ (a : ℕ) * colorClock omega ^ (b : ℕ)) *
      (colorShift ^ (c : ℕ) * colorClock omega ^ (d : ℕ)) = _
  rw [weylWord_mul_nat, colorShift_pow_fin_add, colorClock_pow_fin_add]
  rfl

theorem weylWord_phase_commutation (a b c d : Fin 3) :
    omega ^ ((d : ℕ) * (a : ℕ)) •
        (weylWord a b * weylWord c d) =
      omega ^ ((b : ℕ) * (c : ℕ)) •
        (weylWord c d * weylWord a b) := by
  rw [weylWord_mul, weylWord_mul]
  simp [smul_smul, mul_comm, add_comm]

theorem omega_star_eq_sq : star omega = omega ^ 2 := by
  have hnorm : ‖omega‖ = 1 := by
    rw [omega, Complex.norm_exp]
    simp [Complex.mul_re]
  change (starRingEnd ℂ) omega = omega ^ 2
  rw [← Complex.inv_eq_conj hnorm]
  have hmul : omega ^ 2 * omega = 1 := by
    calc
      omega ^ 2 * omega = omega ^ 3 := by ring
      _ = 1 := omega_cube_eq_one
  exact (eq_inv_of_mul_eq_one_left hmul).symm

theorem weylWord_linearIndependent :
    LinearIndependent ℂ (fun p : Fin 3 × Fin 3 => weylWord p.1 p.2) := by
  rw [Fintype.linearIndependent_iff]
  intro c h
  have h00 := congrArg (fun M : QutritMatrix => M 0 0) h
  have h01 := congrArg (fun M : QutritMatrix => M 0 1) h
  have h02 := congrArg (fun M : QutritMatrix => M 0 2) h
  have h10 := congrArg (fun M : QutritMatrix => M 1 0) h
  have h11 := congrArg (fun M : QutritMatrix => M 1 1) h
  have h12 := congrArg (fun M : QutritMatrix => M 1 2) h
  have h20 := congrArg (fun M : QutritMatrix => M 2 0) h
  have h21 := congrArg (fun M : QutritMatrix => M 2 1) h
  have h22 := congrArg (fun M : QutritMatrix => M 2 2) h
  simp [weylWord, colorShift, colorClock, Fintype.sum_prod_type,
    Fin.sum_univ_three, pow_succ] at h00 h01 h02 h10 h11 h12 h20 h21 h22
  have hsum : 1 + omega + omega ^ 2 = 0 := by
    have hfactor : (omega - 1) * (1 + omega + omega ^ 2) = 0 := by
      calc
        (omega - 1) * (1 + omega + omega ^ 2) = omega ^ 3 - 1 := by ring
        _ = 0 := by rw [omega_cube_eq_one]; ring
    exact (mul_eq_zero.mp hfactor).resolve_left (sub_ne_zero.mpr omega_ne_one)
  have hpow4 : omega ^ 4 = omega := by
    calc
      omega ^ 4 = omega ^ 3 * omega := by ring
      _ = omega := by rw [omega_cube_eq_one]; simp
  have hpow5 : omega ^ 5 = omega ^ 2 := by
    calc
      omega ^ 5 = omega ^ 3 * omega ^ 2 := by ring
      _ = omega ^ 2 := by rw [omega_cube_eq_one]; simp
  have hpow6 : omega ^ 6 = 1 := by
    calc
      omega ^ 6 = (omega ^ 3) ^ 2 := by ring
      _ = 1 := by rw [omega_cube_eq_one]; norm_num
  have solve_three : ∀ x y z : ℂ,
      x + y + z = 0 →
      x + y * omega + z * omega ^ 2 = 0 →
      x + y * omega ^ 2 + z * omega ^ 4 = 0 →
      x = 0 ∧ y = 0 ∧ z = 0 := by
    intro x y z h0 h1 h2
    have identity_x :
        3 * x =
          (x + y + z) + (x + y * omega + z * omega ^ 2) +
              (x + y * omega ^ 2 + z * omega ^ 4) -
            (y + z) * (1 + omega + omega ^ 2) := by
      rw [hpow4]
      ring
    have identity_y :
        3 * y =
          (x + y + z) + omega ^ 2 * (x + y * omega + z * omega ^ 2) +
              omega * (x + y * omega ^ 2 + z * omega ^ 4) -
            (x + z) * (1 + omega + omega ^ 2) := by
      ring_nf
      simp [omega_cube_eq_one, hpow4, hpow5]
      ring
    have identity_z :
        3 * z =
          (x + y + z) + omega * (x + y * omega + z * omega ^ 2) +
              omega ^ 2 * (x + y * omega ^ 2 + z * omega ^ 4) -
            (x + y) * (1 + omega + omega ^ 2) := by
      ring_nf
      simp [omega_cube_eq_one, hpow4, hpow6]
      ring
    have hx : 3 * x = 0 := by
      rw [identity_x, h0, h1, h2, hsum]
      ring
    have hy : 3 * y = 0 := by
      rw [identity_y, h0, h1, h2, hsum]
      ring
    have hz : 3 * z = 0 := by
      rw [identity_z, h0, h1, h2, hsum]
      ring
    have hx' : x = 0 := by
      exact (mul_eq_zero.mp hx).resolve_left (by norm_num)
    have hy' : y = 0 := by
      exact (mul_eq_zero.mp hy).resolve_left (by norm_num)
    have hz' : z = 0 := by
      exact (mul_eq_zero.mp hz).resolve_left (by norm_num)
    exact ⟨hx', hy', hz'⟩
  have h11pow : c (0, 0) + c (0, 1) * omega + c (0, 2) * omega ^ 2 = 0 := by
    simpa [pow_two] using h11
  have h21pow : c (1, 0) + c (1, 1) * omega + c (1, 2) * omega ^ 2 = 0 := by
    simpa [pow_two] using h21
  have h01pow : c (2, 0) + c (2, 1) * omega + c (2, 2) * omega ^ 2 = 0 := by
    simpa [pow_two] using h01
  have h02pow : c (1, 0) + c (1, 1) * omega ^ 2 + c (1, 2) * omega ^ 4 = 0 := by
    convert h02 using 1; ring
  have h12pow : c (2, 0) + c (2, 1) * omega ^ 2 + c (2, 2) * omega ^ 4 = 0 := by
    convert h12 using 1; ring
  have h22pow : c (0, 0) + c (0, 1) * omega ^ 2 + c (0, 2) * omega ^ 4 = 0 := by
    convert h22 using 1; ring
  have hdiag := solve_three _ _ _ h00 h11pow h22pow
  have hforward := solve_three _ _ _ h10 h21pow h02pow
  have hreverse := solve_three _ _ _ h20 h01pow h12pow
  rcases hdiag with ⟨h00', h01', h02'⟩
  rcases hforward with ⟨h10', h11', h12'⟩
  rcases hreverse with ⟨h20', h21', h22'⟩
  intro p
  rcases p with ⟨a, b⟩
  fin_cases a <;> fin_cases b
  all_goals first
    | exact h00'
    | exact h01'
    | exact h02'
    | exact h10'
    | exact h11'
    | exact h12'
    | exact h20'
    | exact h21'
    | exact h22'

theorem weylWord_span_eq_top :
    Submodule.span ℂ (Set.range (fun p : Fin 3 × Fin 3 => weylWord p.1 p.2)) = ⊤ := by
  apply weylWord_linearIndependent.span_eq_top_of_card_eq_finrank
  simp [Module.finrank_matrix]

noncomputable def weylBasis :
    Module.Basis (Fin 3 × Fin 3) ℂ QutritMatrix :=
  basisOfLinearIndependentOfCardEqFinrank weylWord_linearIndependent (by
    simp [Module.finrank_matrix])

@[simp] theorem weylBasis_apply (p : Fin 3 × Fin 3) :
    weylBasis p = weylWord p.1 p.2 := by
  simp [weylBasis]

def weylCoefficient (A : QutritMatrix) (p : Fin 3 × Fin 3) : ℂ :=
  (weylBasis.repr A) p

theorem weyl_expansion (A : QutritMatrix) :
    ∑ p : Fin 3 × Fin 3,
        weylCoefficient A p • weylWord p.1 p.2 = A := by
  simpa [weylCoefficient] using Module.Basis.sum_repr weylBasis A

theorem weyl_expansion_unique (A : QutritMatrix)
    (c : Fin 3 × Fin 3 → ℂ)
    (h : ∑ p : Fin 3 × Fin 3, c p • weylWord p.1 p.2 = A) :
    ∀ p, c p = weylCoefficient A p := by
  have hzero :
      ∑ p : Fin 3 × Fin 3,
          (c p - weylCoefficient A p) • weylWord p.1 p.2 = 0 := by
    simp_rw [sub_smul]
    rw [Finset.sum_sub_distrib, h, weyl_expansion]
    simp
  have hcoeff :=
    (Fintype.linearIndependent_iff.mp weylWord_linearIndependent)
      (fun p => c p - weylCoefficient A p) hzero
  intro p
  exact sub_eq_zero.mp (hcoeff p)

theorem weylWord_trace (a b : Fin 3) :
    Matrix.trace (weylWord a b) =
      if a = 0 ∧ b = 0 then 3 else 0 := by
  have hsum : 1 + omega + omega ^ 2 = 0 := by
    have hfactor : (omega - 1) * (1 + omega + omega ^ 2) = 0 := by
      calc
        (omega - 1) * (1 + omega + omega ^ 2) = omega ^ 3 - 1 := by ring
        _ = 0 := by rw [omega_cube_eq_one]; ring
    exact (mul_eq_zero.mp hfactor).resolve_left (sub_ne_zero.mpr omega_ne_one)
  have hsum' : 1 + omega + omega * omega = 0 := by
    simpa [pow_two] using hsum
  have hpow4 : omega ^ 4 = omega := by
    calc
      omega ^ 4 = omega ^ 3 * omega := by ring
      _ = omega := by rw [omega_cube_eq_one]; simp
  have hsum₂ : 1 + omega ^ 2 + omega ^ 4 = 0 := by
    rw [hpow4]
    simpa [add_comm, add_left_comm, add_assoc] using hsum
  have hsum₂' : 1 + omega * omega + omega * omega * (omega * omega) = 0 := by
    convert hsum₂ using 1; ring
  fin_cases a <;> fin_cases b <;>
    simp [weylWord, colorShift, colorClock, Matrix.trace,
      Fin.sum_univ_three, pow_succ, hsum', hsum₂']

theorem colorShift_conjTranspose :
    colorShiftᴴ = colorShift ^ 2 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [colorShift, Matrix.conjTranspose, Matrix.mul_apply,
      Fin.sum_univ_three, pow_succ]

theorem colorClock_conjTranspose :
    (colorClock omega)ᴴ = colorClock (omega ^ 2) := by
  have hstar : (starRingEnd ℂ) omega = omega ^ 2 := by
    change (starRingEnd ℂ) omega = omega ^ 2
    exact omega_star_eq_sq
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [colorClock, Matrix.conjTranspose, hstar]

theorem weylWord_conjTranspose (a b : Fin 3) :
    (weylWord a b)ᴴ =
      (colorClock omega ^ (b : ℕ))ᴴ *
        (colorShift ^ (a : ℕ))ᴴ := by
  simp [weylWord, Matrix.conjTranspose_mul]

set_option maxHeartbeats 1000000 in
theorem weylWord_hs_orthogonal (a b c d : Fin 3) :
    Matrix.trace ((weylWord a b)ᴴ * weylWord c d) =
      if a = c ∧ b = d then 3 else 0 := by
  have hsum : 1 + omega + omega ^ 2 = 0 := by
    have hfactor : (omega - 1) * (1 + omega + omega ^ 2) = 0 := by
      calc
        (omega - 1) * (1 + omega + omega ^ 2) = omega ^ 3 - 1 := by ring
        _ = 0 := by rw [omega_cube_eq_one]; ring
    exact (mul_eq_zero.mp hfactor).resolve_left (sub_ne_zero.mpr omega_ne_one)
  have hsum' : 1 + omega + omega * omega = 0 := by
    simpa [pow_two] using hsum
  have hpow4 : omega ^ 4 = omega := by
    calc
      omega ^ 4 = omega ^ 3 * omega := by ring
      _ = omega := by rw [omega_cube_eq_one]; simp
  have hpow3 : omega ^ 3 = 1 := omega_cube_eq_one
  have hpow5 : omega ^ 5 = omega ^ 2 := by
    calc
      omega ^ 5 = omega ^ 3 * omega ^ 2 := by ring
      _ = omega ^ 2 := by rw [omega_cube_eq_one]; simp
  have hpow6 : omega ^ 6 = 1 := by
    calc
      omega ^ 6 = (omega ^ 3) ^ 2 := by ring
      _ = 1 := by rw [omega_cube_eq_one]; norm_num
  have hpow8 : omega ^ 8 = omega ^ 2 := by
    calc
      omega ^ 8 = omega ^ 6 * omega ^ 2 := by ring
      _ = omega ^ 2 := by rw [hpow6]; simp
  have hpow10 : omega ^ 10 = omega := by
    calc
      omega ^ 10 = omega ^ 9 * omega := by ring
      _ = omega := by rw [show omega ^ 9 = 1 by
        calc
          omega ^ 9 = (omega ^ 3) ^ 3 := by ring
          _ = 1 := by rw [omega_cube_eq_one]; norm_num]; simp
  have hpow12 : omega ^ 12 = 1 := by
    calc
      omega ^ 12 = (omega ^ 3) ^ 4 := by ring
      _ = 1 := by rw [omega_cube_eq_one]; norm_num
  have hsum₂' : 1 + omega * omega + omega * omega * (omega * omega) = 0 := by
    calc
      1 + omega * omega + omega * omega * (omega * omega) =
          1 + omega ^ 2 + omega ^ 4 := by ring
      _ = 0 := by
        rw [hpow4]
        simpa [add_comm, add_left_comm, add_assoc] using hsum
  have hstar : (starRingEnd ℂ) omega = omega ^ 2 := by
    change (starRingEnd ℂ) omega = omega ^ 2
    exact omega_star_eq_sq
  rw [weylWord_conjTranspose]
  fin_cases a <;> fin_cases b <;> fin_cases c <;> fin_cases d <;>
    simp [weylWord, colorShift, colorClock, Matrix.conjTranspose, Matrix.trace,
      Matrix.mul_apply, Fin.sum_univ_three, pow_succ, hsum', hsum₂', hstar] <;>
    ring_nf <;>
    all_goals first
      | simpa [hpow4, hpow8, add_comm, add_left_comm, add_assoc] using hsum
      | simpa [hpow5, hpow10, add_comm, add_left_comm, add_assoc] using hsum
      | simpa [add_comm, add_left_comm, add_assoc] using hsum
      | (rw [hpow3, hpow6]; norm_num)
      | (rw [hpow6, hpow12]; norm_num)

theorem weyl_trace_readout (A : QutritMatrix) (p : Fin 3 × Fin 3) :
    Matrix.trace ((weylWord p.1 p.2)ᴴ * A) =
      3 * weylCoefficient A p := by
  have h := congrArg
    (fun M : QutritMatrix =>
      Matrix.trace ((weylWord p.1 p.2)ᴴ * M))
    (weyl_expansion A)
  change Matrix.trace
      ((weylWord p.1 p.2)ᴴ *
        (∑ q : Fin 3 × Fin 3,
          weylCoefficient A q • weylWord q.1 q.2)) =
      Matrix.trace ((weylWord p.1 p.2)ᴴ * A) at h
  rw [Matrix.mul_sum, Matrix.trace_sum] at h
  simp only [Matrix.mul_smul, Matrix.trace_smul, smul_eq_mul] at h
  simp_rw [weylWord_hs_orthogonal] at h
  have hcollapse :
      (∑ q : Fin 3 × Fin 3,
        weylCoefficient A q *
          if p.1 = q.1 ∧ p.2 = q.2 then 3 else 0) =
        3 * weylCoefficient A p := by
    classical
    rw [Finset.sum_eq_single p]
    · simp [mul_comm]
    · intro q hq hne
      have hcond : ¬ (p.1 = q.1 ∧ p.2 = q.2) := by
        intro hcond
        apply hne
        exact Prod.ext hcond.1.symm hcond.2.symm
      simp [hcond]
    · simp
  rw [hcollapse] at h
  exact h.symm

theorem weylCoefficient_eq_trace (A : QutritMatrix)
    (p : Fin 3 × Fin 3) :
    weylCoefficient A p =
      (3 : ℂ)⁻¹ * Matrix.trace ((weylWord p.1 p.2)ᴴ * A) := by
  rw [weyl_trace_readout]
  field_simp

theorem weyl_trace_reconstruction (A : QutritMatrix) :
    ∑ p : Fin 3 × Fin 3,
        ((3 : ℂ)⁻¹ * Matrix.trace
          ((weylWord p.1 p.2)ᴴ * A)) • weylWord p.1 p.2 = A := by
  calc
    ∑ p : Fin 3 × Fin 3,
        ((3 : ℂ)⁻¹ * Matrix.trace
          ((weylWord p.1 p.2)ᴴ * A)) • weylWord p.1 p.2 =
      ∑ p : Fin 3 × Fin 3,
        weylCoefficient A p • weylWord p.1 p.2 := by
          apply Finset.sum_congr rfl
          intro p hp
          rw [weylCoefficient_eq_trace]
    _ = A := weyl_expansion A

end InfoGeometry.Canonical.QutritWeylOperatorBasis

end noncomputable section
