# wheeler_complexity.g

Print("=========================================================\n");
Print(" Wheeler Complexity: Growth from Simple Generators       \n");
Print("=========================================================\n\n");

# 1. Initialize a finitely presented group
F := FreeGroup("x", "y");
x := F.1;
y := F.2;

rels_H := [ Comm(x, Comm(x, y)), Comm(y, Comm(x, y)) ];
H := F / rels_H;

Print("1. Finitely Presented Group (Heisenberg Group)\n");
Print("----------------------------------------------\n");
Print("Generators: 2 (x, y)\n");
Print("Relators: [x, [x, y]] = 1, [y, [x, y]] = 1\n");
Print("This simple seed defines a nilpotent structure.\n\n");

Print("2. Computing Lower Central Series (Structural Complexity)\n");
Print("---------------------------------------------------------\n");
if LoadPackage("nq") = true then
    Print("Using the 'nq' package to compute nilpotent quotients of class up to 5.\n");
    H_nq := NilpotentQuotient(H, 5);
    lcs := LowerCentralSeries(H_nq);
    Print("Quotient sequence sizes (polynomial complexity growth):\n");
    for i in [1..Length(lcs)-1] do
        Print("  gamma_", i, " / gamma_", i+1, " rank indicator: ", AbelianInvariants(lcs[i]/lcs[i+1]), "\n");
    od;
else
    Print("Package 'nq' not available. Demonstrating with a finite nilpotent quotient.\n");
    Print("Constructing the Sylow 2-subgroup of the Symmetric Group S_8.\n");
    G := SylowSubgroup(SymmetricGroup(8), 2);
    lcs := LowerCentralSeries(G);
    Print("Quotient sequence sizes for this nilpotent group:\n");
    for i in [1..Length(lcs)-1] do
        Print("  gamma_", i, " / gamma_", i+1, " size: ", Size(lcs[i]) / Size(lcs[i+1]), "\n");
    od;
fi;

Print("\n3. Computing State Space Growth (Exponential vs Polynomial)\n");
Print("-----------------------------------------------------------\n");
Print("If we remove the commutator relators, we obtain the Free Group F = < x, y >.\n");
Print("Its growth function is exactly exponential: 1, 4, 12, 36, 108...\n");
Print("To formally show growth functions, we compute the sphere sizes.\n\n");

# We implement a generic naive growth function calculator
ComputeGrowth := function(grp, max_len)
    local gens, all_gens, elements, boundary, n, new_boundary, g, h, gh, counts;
    gens := GeneratorsOfGroup(grp);
    all_gens := Set(Concatenation(gens, List(gens, Inverse)));
    elements := Set([()]);
    boundary := Set([()]);
    counts := [1];
    
    Print("Length 0: 1 element\n");
    for n in [1..max_len] do
        new_boundary := Set([]);
        for g in boundary do
            for h in all_gens do
                gh := g * h;
                if not gh in elements then
                    AddSet(elements, gh);
                    AddSet(new_boundary, gh);
                fi;
            od;
        od;
        boundary := new_boundary;
        Add(counts, Length(boundary));
        Print("Length ", n, ": ", Length(boundary), " new elements. Cumulative size: ", Length(elements), "\n");
    od;
    return counts;
end;

Print("Growth of finite polynomial-like state space (S_5 generated by 2 elements):\n");
S5 := Group((1,2), (1,2,3,4,5));
ComputeGrowth(S5, 8);

Print("\nConclusion:\n");
Print("The Wheeler complexity formalization demonstrates how simply posed generators\n");
Print("produce vast state spaces and structured hierarchies unless tightly constrained.\n");
Print("Polynomial sequences in Lower Central Series indicate structured 'deep' complexity,\n");
Print("while free group exponential growth indicates 'unconstrained' chaos.\n");
