/-
Copyright (c) 2024 InfoGeometry Contributors.
All rights reserved.

Algebraic Structure of the Nuclear Hamiltonian
TKK 5-Graded Algebra, SO(8) Casimirs, and K-Theoretic Mass
-/

import Mathlib.Algebra.Lie.Basic
import Mathlib.Algebra.Lie.UniversalEnveloping
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Order.Ring.Defs
import Mathlib.Analysis.SpecialFunctions.Log.Basic

namespace InfoGeometry.NuclearHamiltonian

variable (R : Type*) [CommRing R]

/-! ## 1. TKK 5-Graded Algebra Closure -/

/--
The 5-grading of the TKK Algebra built over the D_4 Jordan pair.
Indices range from -2 to +2.
-/
inductive TKKGrading
| minus_two | minus_one | zero | plus_one | plus_two

/-- 
The Fermi pairing property: [g_1, g_1] ⊆ g_2.
Tensor modes are generated by fermion bilinears.
-/
def fermiPairing {g : Type*} [LieRing g] [AddCommGroup g] [Module R g] [LieAlgebra R g]
    (g_plus_one : Submodule R g) (g_plus_two : Submodule R g) : Prop :=
  ∀ (x y : g), x ∈ g_plus_one → y ∈ g_plus_one → ⁅x, y⁆ ∈ g_plus_two

/-! ## 2. Carter Generators & Isospin Projection -/

/--
The nuclear state parameterized by proton count (N) and neutron count (Z).
Wait, conventionally Z is protons and N is neutrons, but we follow the exact notation.
-/
structure NuclearState where
  N : ℝ
  Z : ℝ

/--
Isospin operator projection onto the Cartan subalgebra weights.
$\hat{I}_3 |\Psi\rangle = \frac{1}{2}(N - Z) |\Psi\rangle$
-/
noncomputable def isospinWeight (psi : NuclearState) : ℝ :=
  (psi.N - psi.Z) / (2 : ℝ)

/-- Asymmetry N ≠ Z implies a non-zero displacement in the weight lattice. -/
theorem asymmetry_implies_weight_shift (psi : NuclearState) :
    psi.N ≠ psi.Z ↔ isospinWeight psi ≠ 0 := by
  unfold isospinWeight
  constructor
  · intro h hz
    have h1 : psi.N - psi.Z = 0 := by linarith
    exact h (sub_eq_zero.mp h1)
  · intro h heq
    rw [heq] at h
    simp at h

/-! ## 3. Casimir Operators and Mass Spectrometry -/

variable (k : ℤ)

/--
The topological instanton charge from K-Theory
$k \in K_0(\text{Inst}) \cong \mathbb{Z}$
Mass squared is proportional to the quadratic Casimir.
For k = 0 (gauge bosons), mass is 0.
For k ≠ 0 (fermions/matter), mass is strictly positive.
-/
def MassSquared (C2 : ℝ) (charge : ℤ) : ℝ :=
  if charge = 0 then 0 else C2

/-! ## 4. K-Theoretic Hamiltonian -/

/--
The Triality projection operator onto the S_3 symmetric subspace.
It must be idempotent.
-/
class TrialityProjector (V : Type*) [AddCommMonoid V] [Module R V] where
  Pi : V →ₗ[R] V
  idempotent : Pi ∘ₗ Pi = Pi

/--
The final TKK Hamiltonian formulation:
$\hat{H}_{TKK} = \omega \hat{N}_{osc} + A \mathcal{C}_2 + \Delta_{trip} \hat{\Pi}_{triality}$
-/
def HTKK {V : Type*} [AddCommMonoid V] [Module R V] [TrialityProjector R V]
    (omega A Delta : R)
    (N_osc C2 : V →ₗ[R] V) : V →ₗ[R] V :=
  omega • N_osc + A • C2 + Delta • TrialityProjector.Pi

/-! ## Rotational-vibrational spectroscopy model -/

/-- Parameters of a rotational-vibrational spectroscopy energy model. -/
structure SpectroscopyParams where
  chiS3 : ℝ
  kleinPartition : ℝ
  hbarOmegaVac : ℝ
  Arot : ℝ
  Brot : ℝ
  decoupling : ℝ
  inertiaFactor : ℝ
  coriolisParity : ℝ

/-- Spectroscopic quantum-number labels. -/
structure SpectroscopyQuantumNumbers where
  nPlus : ℕ
  nMinus : ℕ
  J : ℝ
  K : ℝ
  p : ℕ

/-- Indicator of the `K = 1/2` Coriolis band. -/
noncomputable def deltaKHalf (K : ℝ) : ℝ := if K = (1 / 2 : ℝ) then 1 else 0

@[simp] theorem deltaKHalf_half : deltaKHalf (1 / 2 : ℝ) = 1 := by
  simp [deltaKHalf]

/-- Logarithmic contribution of the finite label `p`. -/
noncomputable def spectroscopyTopologicalEnergy
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers) : ℝ :=
  |P.chiS3| / P.kleinPartition * Real.log Q.p

/-- Two-lane vibrational contribution including zero-point energy. -/
noncomputable def spectroscopyVibrationalEnergy
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers) : ℝ :=
  P.hbarOmegaVac * ((Q.nPlus : ℝ) + (Q.nMinus : ℝ) + 1)

/-- Axially symmetric rotational contribution. -/
noncomputable def spectroscopyRotationalEnergy
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers) : ℝ :=
  P.Arot * (Q.J * (Q.J + 1) - Q.K ^ 2)

/-- Coriolis contribution in the `K = 1/2` band. -/
noncomputable def spectroscopyCoriolisEnergy
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers) : ℝ :=
  P.coriolisParity * P.decoupling * P.inertiaFactor *
    (Q.J + 1 / 2) * deltaKHalf Q.K

/-- Sum of the four spectroscopy energy components. -/
noncomputable def spectroscopyTotalEnergy
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers) : ℝ :=
  spectroscopyTopologicalEnergy P Q + spectroscopyVibrationalEnergy P Q +
    spectroscopyRotationalEnergy P Q + spectroscopyCoriolisEnergy P Q

/-- Asymmetric-rotor presentation of the spectroscopy energy. -/
noncomputable def spectroscopyUnifiedEnergy
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers) : ℝ :=
  (|P.chiS3| / P.kleinPartition * Real.log Q.p + P.hbarOmegaVac) +
    P.hbarOmegaVac * ((Q.nPlus : ℝ) + (Q.nMinus : ℝ)) +
    P.Arot * (Q.J * (Q.J + 1)) +
    (P.Brot - P.Arot) * Q.K ^ 2 + spectroscopyCoriolisEnergy P Q

/-- At `Brot = 0`, the asymmetric-rotor and decomposed energies agree. -/
theorem spectroscopyUnifiedEnergy_eq_total_of_Brot_zero
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers)
    (hB : P.Brot = 0) :
    spectroscopyUnifiedEnergy P Q = spectroscopyTotalEnergy P Q := by
  simp [spectroscopyUnifiedEnergy, spectroscopyTotalEnergy,
    spectroscopyTopologicalEnergy, spectroscopyVibrationalEnergy,
    spectroscopyRotationalEnergy, hB]
  ring

/-- The Coriolis contribution vanishes away from the selected band. -/
theorem spectroscopyCoriolisEnergy_off_band
    (P : SpectroscopyParams) (Q : SpectroscopyQuantumNumbers)
    (hK : Q.K ≠ (1 / 2 : ℝ)) :
    spectroscopyCoriolisEnergy P Q = 0 := by
  rw [spectroscopyCoriolisEnergy, deltaKHalf, if_neg hK]
  ring

/-! ## 5. Electromagnetic Transitions and Lifetimes -/

/--
The transition rate Γ is inversely proportional to the lifetime τ.
Γ = 1 / τ
-/
noncomputable def transitionRate (tau : ℝ) : ℝ := 1 / tau

/--
The reduced transition probability B(Eλ) is related to the lifetime and transition energy E_gamma.
For E1 transitions (λ = 1): B(E1) ∝ Γ / E_gamma^3
For E2 transitions (λ = 2): B(E2) ∝ Γ / E_gamma^5
-/
noncomputable def BE_lambda (tau : ℝ) (E_gamma : ℝ) (lambda : ℕ) : ℝ :=
  (transitionRate tau) / (E_gamma ^ (2 * lambda + 1))

/--
The isoscalar mixing component in B(E1) transitions for mirror nuclei.
This maps the experimental deviation in mirror pairs (e.g. 31P / 31S).
-/
noncomputable def isoscalarMixingRatio (B_E1_proton_rich B_E1_neutron_rich : ℝ) : ℝ :=
  |B_E1_proton_rich - B_E1_neutron_rich| / (B_E1_proton_rich + B_E1_neutron_rich)

/-- Proof-carrying structure for the geometric parallax bound in the TKK framework. -/
structure GeometricParallaxBound where
  (bound : ∀ {B_p B_n : ℝ}, B_p > 0 → isoscalarMixingRatio B_p B_n ≤ 0.231)

end InfoGeometry.NuclearHamiltonian
