import InfoGeometry.Foundations.AxiomaticDependencyGraph
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Foundations.NewtonKantorovichBase
import InfoGeometry.Foundations.NewtonKantorovichRoots
import InfoGeometry.Foundations.NewtonKantorovichSequence
import InfoGeometry.Foundations.NewtonKantorovichCertificate
import InfoGeometry.Foundations.NewtonKantorovich
import InfoGeometry.Foundations.NewtonKantorovichJacobianCertificate
