import InfoGeometry.Canonical.RealBdG
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv

/-!
# Massive doubled oscillator

The canonical doubled/BdG carrier already has a square-minus-one axis
`modularK`.  This owner records the finite algebraic mass-dependent generator
`D ω = ω K`.  It proves the generator square and the resulting second-order
equation; it does not assert an observable-level Zitterbewegung frequency.
-/

namespace InfoGeometry.Canonical.MassiveDoubledZitterbewegung

open InfoGeometry.Canonical.RealBdG
open InfoGeometry.Krein

section

variable {E : Type} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [CompleteSpace E]

/-- The mass/frequency-scaled doubled oscillator generator. -/
noncomputable def massiveGenerator (ω : ℝ) : EndH (E := E) :=
  ω • modularK (E := E)

omit [CompleteSpace E] in
@[simp] theorem massiveGenerator_apply (ω : ℝ) (v : DoubledSpace E) :
    massiveGenerator (E := E) ω v = ω • modularK (E := E) v := by
  rfl

/-- The massive doubled generator has the expected square. -/
theorem massiveGenerator_sq (ω : ℝ) :
    (massiveGenerator (E := E) ω).comp
        (massiveGenerator (E := E) ω) =
      (-(ω ^ 2)) • ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  apply ContinuousLinearMap.ext
  intro v
  change ω • modularK (E := E) (ω • modularK (E := E) v) =
    -(ω ^ 2) • v
  rw [map_smul, modularK_apply_modularK]
  module

/-- Right-hand side of the finite first-order doubled flow. -/
noncomputable def firstOrderRhs (ω : ℝ) (ψ : DoubledSpace E) : DoubledSpace E :=
  massiveGenerator (E := E) ω ψ

/-- The explicit finite oscillatory transport generated by the doubled
complex-structure axis. -/
noncomputable def massiveFlow (ω t : ℝ) : EndH (E := E) :=
  Real.cos (t * ω) • ContinuousLinearMap.id ℝ (DoubledSpace E) +
    Real.sin (t * ω) • modularK (E := E)

@[simp] theorem massiveFlow_zero (ω : ℝ) :
    massiveFlow (E := E) ω 0 = ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  apply ContinuousLinearMap.ext
  intro v
  simp [massiveFlow]

theorem massiveFlow_apply (ω t : ℝ) (v : DoubledSpace E) :
    massiveFlow (E := E) ω t v =
      Real.cos (t * ω) • v +
        Real.sin (t * ω) • modularK (E := E) v := by
  simp [massiveFlow]

/-- The explicit doubled flow solves the first-order equation generated by
`massiveGenerator`.  This is the differential form of the finite flow law;
no separate analytic carrier is introduced. -/
theorem hasDerivAt_massiveFlow (ω t : ℝ) (v : DoubledSpace E) :
    HasDerivAt (fun s => massiveFlow (E := E) ω s v)
      (massiveGenerator (E := E) ω
        (massiveFlow (E := E) ω t v)) t := by
  have harg : HasDerivAt (fun s : ℝ => s * ω) ω t :=
    hasDerivAt_mul_const ω
  have hcos : HasDerivAt (fun s : ℝ => Real.cos (s * ω))
      (-Real.sin (t * ω) * ω) t := by
    exact (Real.hasDerivAt_cos (t * ω)).comp t harg
  have hsin : HasDerivAt (fun s : ℝ => Real.sin (s * ω))
      (Real.cos (t * ω) * ω) t := by
    exact (Real.hasDerivAt_sin (t * ω)).comp t harg
  have hsum := (hcos.smul_const v).add
    (hsin.smul_const (modularK (E := E) v))
  rw [show (fun s => massiveFlow (E := E) ω s v) =
      (fun s => Real.cos (s * ω) • v +
        Real.sin (s * ω) • modularK (E := E) v) by
        funext s
        exact massiveFlow_apply ω s v]
  rw [massiveFlow_apply]
  convert hsum using 1
  simp only [massiveGenerator_apply, map_add, map_smul,
    modularK_apply_modularK]
  module

theorem massiveFlow_add (ω s t : ℝ) :
    massiveFlow (E := E) ω (s + t) =
      (massiveFlow (E := E) ω s).comp (massiveFlow (E := E) ω t) := by
  apply ContinuousLinearMap.ext
  intro v
  rw [massiveFlow_apply, ContinuousLinearMap.comp_apply,
    massiveFlow_apply, massiveFlow_apply]
  have harg : (s + t) * ω = s * ω + t * ω := by ring
  rw [harg, Real.cos_add, Real.sin_add]
  have hK : modularK (E := E) (modularK (E := E) v) = -v :=
    modularK_apply_modularK v
  simp only [map_add, map_smul]
  rw [hK]
  module

theorem massiveFlow_neg_comp (ω t : ℝ) :
    (massiveFlow (E := E) ω (-t)).comp (massiveFlow (E := E) ω t) =
      ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  rw [← massiveFlow_add ω (-t) t]
  simp

theorem massiveFlow_comp_neg (ω t : ℝ) :
    (massiveFlow (E := E) ω t).comp (massiveFlow (E := E) ω (-t)) =
      ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  rw [← massiveFlow_add ω t (-t)]
  simp

/-- Every state satisfies the algebraic second-order equation induced by the
massive generator. -/
theorem massive_second_order (ω : ℝ) (v : DoubledSpace E) :
    massiveGenerator (E := E) ω
        (massiveGenerator (E := E) ω v) =
      -(ω ^ 2) • v := by
  have h := congrArg
    (fun T : EndH (E := E) => T v) (massiveGenerator_sq (E := E) ω)
  simpa using h

/-- The finite oscillator flow commutes with its scaled generator. -/
theorem massiveGenerator_comp_massiveFlow (ω t : ℝ) :
    (massiveGenerator (E := E) ω).comp (massiveFlow (E := E) ω t) =
      (massiveFlow (E := E) ω t).comp (massiveGenerator (E := E) ω) := by
  apply ContinuousLinearMap.ext
  intro v
  rw [ContinuousLinearMap.comp_apply, ContinuousLinearMap.comp_apply,
    massiveFlow_apply, massiveFlow_apply, massiveGenerator_apply,
    massiveGenerator_apply]
  simp only [map_add, map_smul]
  rw [modularK_apply_modularK]
  module

end

end InfoGeometry.Canonical.MassiveDoubledZitterbewegung
