import InfoGeometry.Clifford.Cl11

section KreinClifford

variable {E : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Explicit dictionary: chirality operator is the grading involution. -/
def chiralityOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  modularJ (E := E)

/-- Explicit dictionary: complex-structure operator derived from Clifford generators. -/
def complexStructureOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  complexI (E := E)

/-- Endomorphism-level notion of an internal complex structure (`I^2 = -Id`). -/
def isComplexStructureOp (A : DoubledSpace E →L[ℝ] DoubledSpace E) : Prop :=
  A.comp A = -(ContinuousLinearMap.id ℝ (DoubledSpace E))

lemma complexI_sq_neg_id :
    (complexI (E := E)).comp (complexI (E := E))
      = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) := by
  apply ContinuousLinearMap.ext
  intro v
  rcases v with ⟨x, y⟩
  simp [complexI, modularJ, spectralEpsilon]

lemma complexI_isComplexStructureOp :
    isComplexStructureOp (E := E) (complexI (E := E)) :=
  complexI_sq_neg_id (E := E)

lemma neg_complexI_isComplexStructureOp :
    isComplexStructureOp (E := E) (-(complexI (E := E))) := by
  unfold isComplexStructureOp
  calc
    (-(complexI (E := E))).comp (-(complexI (E := E)))
        = (complexI (E := E)).comp (complexI (E := E)) := by
            apply ContinuousLinearMap.ext
            intro v
            rcases v with ⟨x, y⟩
            simp
    _ = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) :=
          complexI_sq_neg_id (E := E)

/-- Minimal vacuum/polarization viewpoint: choice of internal `i` among admissible
complex structures generated by the Clifford pair. -/
structure VacuumChoice where
  imag : DoubledSpace E →L[ℝ] DoubledSpace E
  imag_sq_neg_id : isComplexStructureOp (E := E) imag

def vacuumChoicePlus : VacuumChoice (E := E) where
  imag := complexI (E := E)
  imag_sq_neg_id := complexI_isComplexStructureOp (E := E)

def vacuumChoiceMinus : VacuumChoice (E := E) where
  imag := -(complexI (E := E))
  imag_sq_neg_id := neg_complexI_isComplexStructureOp (E := E)

/-- Vacuum-dependent polarization projector `(Id + imag)/2`. -/
noncomputable def vacuumPolarizationPlus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  ((2 : ℝ)⁻¹) •
    (ContinuousLinearMap.id ℝ (DoubledSpace E) + V.imag)

/-- Vacuum-dependent polarization projector `(Id - imag)/2`. -/
noncomputable def vacuumPolarizationMinus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  ((2 : ℝ)⁻¹) •
    (ContinuousLinearMap.id ℝ (DoubledSpace E) - V.imag)

theorem vacuumChoice_switch_swaps_polarizations_plus :
    vacuumPolarizationPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  apply ContinuousLinearMap.ext
  intro v
  rcases v with ⟨x, y⟩
  simp [vacuumPolarizationPlus, vacuumPolarizationMinus,
    vacuumChoicePlus, vacuumChoiceMinus, sub_eq_add_neg]

theorem vacuumChoice_switch_swaps_polarizations_minus :
    vacuumPolarizationMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  apply ContinuousLinearMap.ext
  intro v
  rcases v with ⟨x, y⟩
  simp [vacuumPolarizationPlus, vacuumPolarizationMinus,
    vacuumChoicePlus, vacuumChoiceMinus, sub_eq_add_neg]

end KreinClifford
