import InfoGeometry.Krein.DoubledSpace
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Clifford.Grading
set_option linter.unusedSimpArgs false
set_option linter.unusedSectionVars false

open InfoGeometry.Krein

section KreinClifford

variable {E : Type} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- Explicit dictionary: chirality operator is the grading involution. -/
noncomputable def chiralityOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  modular_j (E := E)

/-- Explicit dictionary: complex-structure operator derived from Clifford generators. -/
noncomputable def complexStructureOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  complex_i (E := E)

@[simp] lemma chiralityOperator_eq_modular_j :
    chiralityOperator (E := E) = modular_j (E := E) := rfl

@[simp] lemma complexStructureOperator_eq_complex_i :
    complexStructureOperator (E := E) = complex_i (E := E) := rfl

/-- Endomorphism-level notion of an internal complex structure (`I^2 = -Id`). -/
def isComplexStructureOp (A : DoubledSpace E →L[ℝ] DoubledSpace E) : Prop :=
  A.comp A = -(ContinuousLinearMap.id ℝ (DoubledSpace E))

lemma complex_i_sq_neg_id :
    (complex_i (E := E)).comp (complex_i (E := E))
      = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) := by
  exact complex_i_sq (E := E)

lemma complex_i_isComplexStructureOp :
    isComplexStructureOp (E := E) (complex_i (E := E)) :=
  complex_i_sq_neg_id (E := E)

/-- Real chirality projector `(Id + J)/2`, where `J^2 = Id`. -/
noncomputable def chiralityProjPlus : DoubledSpace E →L[ℝ] DoubledSpace E :=
  gradePlusProj (E := E)

/-- Real chirality projector `(Id - J)/2`, where `J^2 = Id`. -/
noncomputable def chiralityProjMinus : DoubledSpace E →L[ℝ] DoubledSpace E :=
  gradeMinusProj (E := E)

@[simp] lemma chiralityProjPlus_eq_gradePlusProj :
    chiralityProjPlus (E := E) = gradePlusProj (E := E) := rfl

@[simp] lemma chiralityProjMinus_eq_gradeMinusProj :
    chiralityProjMinus (E := E) = gradeMinusProj (E := E) := rfl

@[simp] lemma chiralityProjPlus_apply (v : DoubledSpace E) :
    chiralityProjPlus (E := E) v
      = gradePlusProj (E := E) v := rfl

@[simp] lemma chiralityProjMinus_apply (v : DoubledSpace E) :
    chiralityProjMinus (E := E) v
      = gradeMinusProj (E := E) v := rfl

lemma chiralityProjPlus_idempotent :
    (chiralityProjPlus (E := E)).comp (chiralityProjPlus (E := E))
      = chiralityProjPlus (E := E) := by
  simpa [chiralityProjPlus] using gradePlusProj_idempotent (E := E)

lemma chiralityProjMinus_idempotent :
    (chiralityProjMinus (E := E)).comp (chiralityProjMinus (E := E))
      = chiralityProjMinus (E := E) := by
  simpa [chiralityProjMinus] using gradeMinusProj_idempotent (E := E)

lemma chiralityProjPlus_comp_chiralityProjMinus :
    (chiralityProjPlus (E := E)).comp (chiralityProjMinus (E := E)) = 0 := by
  apply ContinuousLinearMap.ext
  intro v
  apply DoubledSpace.ext <;>
    simp [chiralityProjPlus, chiralityProjMinus, gradePlusProj, gradeMinusProj,
      modular_j_apply, sub_eq_add_neg, add_assoc, add_comm, smul_add]

lemma chiralityProjMinus_comp_chiralityProjPlus :
    (chiralityProjMinus (E := E)).comp (chiralityProjPlus (E := E)) = 0 := by
  apply ContinuousLinearMap.ext
  intro v
  apply DoubledSpace.ext <;>
    simp [chiralityProjPlus, chiralityProjMinus, gradePlusProj, gradeMinusProj,
      modular_j_apply, sub_eq_add_neg, add_assoc, add_comm, smul_add]

lemma chiralityProjPlus_add_chiralityProjMinus :
    chiralityProjPlus (E := E) + chiralityProjMinus (E := E)
      = ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  simpa [chiralityProjPlus, chiralityProjMinus] using
    gradeProj_sum (E := E)

lemma neg_complex_i_isComplexStructureOp :
    isComplexStructureOp (E := E) (-(complex_i (E := E))) := by
  unfold isComplexStructureOp
  calc
    (-(complex_i (E := E))).comp (-(complex_i (E := E)))
        = (complex_i (E := E)).comp (complex_i (E := E)) := by
            apply ContinuousLinearMap.ext
            intro v
            simp
    _ = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) :=
          complex_i_sq_neg_id (E := E)

/-- Minimal vacuum/polarization viewpoint: choice of internal `i` among admissible
complex structures generated by the Clifford pair. -/
structure VacuumChoice where
  imag : DoubledSpace E →L[ℝ] DoubledSpace E
  imag_sq_neg_id : isComplexStructureOp (E := E) imag

noncomputable def vacuumChoicePlus : VacuumChoice (E := E) where
  imag := complex_i (E := E)
  imag_sq_neg_id := complex_i_isComplexStructureOp (E := E)

noncomputable def vacuumChoiceMinus : VacuumChoice (E := E) where
  imag := -(complex_i (E := E))
  imag_sq_neg_id := neg_complex_i_isComplexStructureOp (E := E)

/-- Vacuum-dependent real splitting operator `(Id + imag)/2`.
Over `ℝ`, this is not a projector when `imag^2 = -Id`. -/
noncomputable def vacuumSplitPlus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  ((2 : ℝ)⁻¹) •
    (ContinuousLinearMap.id ℝ (DoubledSpace E) + V.imag)

/-- Vacuum-dependent real splitting operator `(Id - imag)/2`.
Over `ℝ`, this is not a projector when `imag^2 = -Id`. -/
noncomputable def vacuumSplitMinus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  ((2 : ℝ)⁻¹) •
    (ContinuousLinearMap.id ℝ (DoubledSpace E) - V.imag)

noncomputable def vacuumPolarizationPlus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  vacuumSplitPlus (E := E) V

noncomputable def vacuumPolarizationMinus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  vacuumSplitMinus (E := E) V

theorem vacuumChoice_switch_swaps_splits_plus :
    vacuumSplitPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumSplitMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  apply ContinuousLinearMap.ext
  intro v
  simp [vacuumSplitPlus, vacuumSplitMinus,
    vacuumChoicePlus, vacuumChoiceMinus, sub_eq_add_neg]

theorem vacuumChoice_switch_swaps_splits_minus :
    vacuumSplitMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumSplitPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  apply ContinuousLinearMap.ext
  intro v
  simp [vacuumSplitPlus, vacuumSplitMinus,
    vacuumChoicePlus, vacuumChoiceMinus, sub_eq_add_neg]

theorem vacuumChoice_switch_swaps_polarizations_plus :
    vacuumPolarizationPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa [vacuumPolarizationPlus, vacuumPolarizationMinus] using
    vacuumChoice_switch_swaps_splits_plus (E := E)

theorem vacuumChoice_switch_swaps_polarizations_minus :
    vacuumPolarizationMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa [vacuumPolarizationPlus, vacuumPolarizationMinus] using
    vacuumChoice_switch_swaps_splits_minus (E := E)

end KreinClifford


namespace InfoGeometry.Krein.Prelude

section KreinClifford

variable {E : Type} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

noncomputable abbrev chiralityOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.chiralityOperator (E := E)

noncomputable abbrev complexStructureOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.complexStructureOperator (E := E)

@[simp] theorem chiralityOperator_eq_modular_j :
    chiralityOperator (E := E) = modular_j (E := E) := by
  exact _root_.chiralityOperator_eq_modular_j (E := E)

@[simp] theorem complexStructureOperator_eq_complex_i :
    complexStructureOperator (E := E) = complex_i (E := E) := by
  exact _root_.complexStructureOperator_eq_complex_i (E := E)

theorem complex_i_sq_neg_id :
    (complex_i (E := E)).comp (complex_i (E := E))
      = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) := by
  simpa using (_root_.complex_i_sq_neg_id (E := E))

theorem complex_i_isComplexStructureOp :
    _root_.isComplexStructureOp (E := E) (complex_i (E := E)) := by
  exact _root_.complex_i_isComplexStructureOp (E := E)

noncomputable abbrev chiralityProjPlus : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.chiralityProjPlus (E := E)

noncomputable abbrev chiralityProjMinus : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.chiralityProjMinus (E := E)

@[simp] theorem chiralityProjPlus_eq_gradePlusProj :
    chiralityProjPlus (E := E) = gradePlusProj (E := E) := by
  exact _root_.chiralityProjPlus_eq_gradePlusProj (E := E)

@[simp] theorem chiralityProjMinus_eq_gradeMinusProj :
    chiralityProjMinus (E := E) = gradeMinusProj (E := E) := by
  exact _root_.chiralityProjMinus_eq_gradeMinusProj (E := E)

abbrev VacuumChoice
    (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] :=
  _root_.VacuumChoice (E := E)

noncomputable abbrev vacuumChoicePlus : VacuumChoice E :=
  _root_.vacuumChoicePlus (E := E)

noncomputable abbrev vacuumChoiceMinus : VacuumChoice E :=
  _root_.vacuumChoiceMinus (E := E)

noncomputable abbrev vacuumSplitPlus
    (V : VacuumChoice E) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.vacuumSplitPlus (E := E) V

noncomputable abbrev vacuumSplitMinus
    (V : VacuumChoice E) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.vacuumSplitMinus (E := E) V

noncomputable abbrev vacuumPolarizationPlus
    (V : VacuumChoice E) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.vacuumPolarizationPlus (E := E) V

noncomputable abbrev vacuumPolarizationMinus
    (V : VacuumChoice E) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  _root_.vacuumPolarizationMinus (E := E) V

theorem vacuumChoice_switch_swaps_splits_plus :
    vacuumSplitPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumSplitMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa using (_root_.vacuumChoice_switch_swaps_splits_plus (E := E))

theorem vacuumChoice_switch_swaps_splits_minus :
    vacuumSplitMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumSplitPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa using (_root_.vacuumChoice_switch_swaps_splits_minus (E := E))

theorem vacuumChoice_switch_swaps_polarizations_plus :
    vacuumPolarizationPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa using (_root_.vacuumChoice_switch_swaps_polarizations_plus (E := E))

theorem vacuumChoice_switch_swaps_polarizations_minus :
    vacuumPolarizationMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa using (_root_.vacuumChoice_switch_swaps_polarizations_minus (E := E))

end KreinClifford

end InfoGeometry.Krein.Prelude
