import InfoGeometry.Clifford.Grading
import Mathlib.Tactic.NormNum

section KreinClifford

variable {E : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Explicit dictionary: chirality operator is the grading involution. -/
def chiralityOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  modularJ (E := E)

/-- Explicit dictionary: complex-structure operator derived from Clifford generators. -/
def complexStructureOperator : DoubledSpace E →L[ℝ] DoubledSpace E :=
  complexI (E := E)

/-- Endomorphism-level notion of an internal complex structure (`I^2 = -Id`). -/
def isComplexStructureOp (A : DoubledSpace E →L[ℝ] DoubledSpace E) : Prop :=
  A.comp A = -(ContinuousLinearMap.id ℝ (DoubledSpace E))

lemma complexI_sq_neg_id :
    (complexI (E := E)).comp (complexI (E := E))
      = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) := by
  exact complexI_sq (E := E)

lemma complexI_isComplexStructureOp :
    isComplexStructureOp (E := E) (complexI (E := E)) :=
  complexI_sq_neg_id (E := E)

/-- Real chirality projector `(Id + J)/2`, where `J^2 = Id`. -/
noncomputable def chiralityProjPlus : DoubledSpace E →L[ℝ] DoubledSpace E :=
  gradePlusProj (E := E)

/-- Real chirality projector `(Id - J)/2`, where `J^2 = Id`. -/
noncomputable def chiralityProjMinus : DoubledSpace E →L[ℝ] DoubledSpace E :=
  gradeMinusProj (E := E)

@[simp] lemma chiralityProjPlus_apply (v : DoubledSpace E) :
    chiralityProjPlus (E := E) v
      = (((2 : ℝ)⁻¹) • (v.1 + v.2), ((2 : ℝ)⁻¹) • (v.1 + v.2)) := by
  rcases v with ⟨x, y⟩
  simp [chiralityProjPlus, gradePlusProj, modularJ, smul_add, add_comm]

@[simp] lemma chiralityProjMinus_apply (v : DoubledSpace E) :
    chiralityProjMinus (E := E) v
      = (((2 : ℝ)⁻¹) • (v.1 - v.2), ((2 : ℝ)⁻¹) • (v.2 - v.1)) := by
  rcases v with ⟨x, y⟩
  simp [chiralityProjMinus, gradeMinusProj, modularJ, smul_add, sub_eq_add_neg]

lemma chiralityProjPlus_idempotent :
    (chiralityProjPlus (E := E)).comp (chiralityProjPlus (E := E))
      = chiralityProjPlus (E := E) := by
  simpa [chiralityProjPlus] using gradePlusProj_idempotent (E := E)

lemma chiralityProjMinus_idempotent :
    (chiralityProjMinus (E := E)).comp (chiralityProjMinus (E := E))
      = chiralityProjMinus (E := E) := by
  simpa [chiralityProjMinus] using gradeMinusProj_idempotent (E := E)

lemma chiralityProjPlus_comp_chiralityProjMinus :
    (chiralityProjPlus (E := E)).comp (chiralityProjMinus (E := E)) = 0 := by
  simpa [chiralityProjPlus, chiralityProjMinus] using
    gradePlusProj_comp_gradeMinusProj (E := E)

lemma chiralityProjMinus_comp_chiralityProjPlus :
    (chiralityProjMinus (E := E)).comp (chiralityProjPlus (E := E)) = 0 := by
  simpa [chiralityProjPlus, chiralityProjMinus] using
    gradeMinusProj_comp_gradePlusProj (E := E)

lemma chiralityProjPlus_add_chiralityProjMinus :
    chiralityProjPlus (E := E) + chiralityProjMinus (E := E)
      = ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  simpa [chiralityProjPlus, chiralityProjMinus] using
    gradeProj_sum (E := E)

lemma neg_complexI_isComplexStructureOp :
    isComplexStructureOp (E := E) (-(complexI (E := E))) := by
  unfold isComplexStructureOp
  calc
    (-(complexI (E := E))).comp (-(complexI (E := E)))
        = (complexI (E := E)).comp (complexI (E := E)) := by
            apply ContinuousLinearMap.ext
            intro v
            rcases v with ⟨x, y⟩
            simp
    _ = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) :=
          complexI_sq_neg_id (E := E)

/-- Minimal vacuum/polarization viewpoint: choice of internal `i` among admissible
complex structures generated by the Clifford pair. -/
structure VacuumChoice where
  imag : DoubledSpace E →L[ℝ] DoubledSpace E
  imag_sq_neg_id : isComplexStructureOp (E := E) imag

def vacuumChoicePlus : VacuumChoice (E := E) where
  imag := complexI (E := E)
  imag_sq_neg_id := complexI_isComplexStructureOp (E := E)

def vacuumChoiceMinus : VacuumChoice (E := E) where
  imag := -(complexI (E := E))
  imag_sq_neg_id := neg_complexI_isComplexStructureOp (E := E)

/-- Vacuum-dependent real splitting operator `(Id + imag)/2`.
Over `ℝ`, this is not a projector when `imag^2 = -Id`. -/
noncomputable def vacuumSplitPlus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  ((2 : ℝ)⁻¹) •
    (ContinuousLinearMap.id ℝ (DoubledSpace E) + V.imag)

/-- Vacuum-dependent real splitting operator `(Id - imag)/2`.
Over `ℝ`, this is not a projector when `imag^2 = -Id`. -/
noncomputable def vacuumSplitMinus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  ((2 : ℝ)⁻¹) •
    (ContinuousLinearMap.id ℝ (DoubledSpace E) - V.imag)

noncomputable def vacuumPolarizationPlus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  vacuumSplitPlus (E := E) V

noncomputable def vacuumPolarizationMinus
    (V : VacuumChoice (E := E)) : DoubledSpace E →L[ℝ] DoubledSpace E :=
  vacuumSplitMinus (E := E) V

theorem vacuumChoice_switch_swaps_splits_plus :
    vacuumSplitPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumSplitMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  apply ContinuousLinearMap.ext
  intro v
  rcases v with ⟨x, y⟩
  simp [vacuumSplitPlus, vacuumSplitMinus,
    vacuumChoicePlus, vacuumChoiceMinus, sub_eq_add_neg]

theorem vacuumChoice_switch_swaps_splits_minus :
    vacuumSplitMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumSplitPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  apply ContinuousLinearMap.ext
  intro v
  rcases v with ⟨x, y⟩
  simp [vacuumSplitPlus, vacuumSplitMinus,
    vacuumChoicePlus, vacuumChoiceMinus, sub_eq_add_neg]

theorem vacuumChoice_switch_swaps_polarizations_plus :
    vacuumPolarizationPlus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationMinus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa [vacuumPolarizationPlus, vacuumPolarizationMinus] using
    vacuumChoice_switch_swaps_splits_plus (E := E)

theorem vacuumChoice_switch_swaps_polarizations_minus :
    vacuumPolarizationMinus (E := E) (vacuumChoicePlus (E := E))
      = vacuumPolarizationPlus (E := E) (vacuumChoiceMinus (E := E)) := by
  simpa [vacuumPolarizationPlus, vacuumPolarizationMinus] using
    vacuumChoice_switch_swaps_splits_minus (E := E)

end KreinClifford
