import InfoGeometry.Krein.Grading

namespace InfoGeometry.Krein

variable {E : Type _} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Algebraic supercharge package: odd generator and its square Hamiltonian. -/
structure Supercharge where
  Q : DoubledSpace E →L[ℝ] DoubledSpace E
  odd : isOdd (E := E) Q

/-- Algebraic square of a supercharge. -/
abbrev superSquare (S : Supercharge (E := E)) :
    DoubledSpace E →L[ℝ] DoubledSpace E :=
  S.Q.comp S.Q

def superHamiltonian (S : Supercharge (E := E)) :
    DoubledSpace E →L[ℝ] DoubledSpace E :=
  superSquare (E := E) S

lemma superHamiltonian_isEven (S : Supercharge (E := E)) :
    isEven (E := E) (superHamiltonian (E := E) S) := by
  unfold isEven superHamiltonian superSquare
  calc
    (modular_j (E := E)).comp (S.Q.comp S.Q)
        = ((modular_j (E := E)).comp S.Q).comp S.Q := by simp [ContinuousLinearMap.comp_assoc]
    _ = (-(S.Q.comp (modular_j (E := E)))).comp S.Q := by rw [S.odd]
    _ = -((S.Q.comp (modular_j (E := E))).comp S.Q) := by simp
    _ = -(S.Q.comp ((modular_j (E := E)).comp S.Q)) := by simp [ContinuousLinearMap.comp_assoc]
    _ = -(S.Q.comp (-(S.Q.comp (modular_j (E := E))))) := by
          have h : (modular_j (E := E)).comp S.Q = -(S.Q.comp (modular_j (E := E))) := S.odd
          rw [h]
    _ = S.Q.comp (S.Q.comp (modular_j (E := E))) := by simp
    _ = (S.Q.comp S.Q).comp (modular_j (E := E)) := by simp [ContinuousLinearMap.comp_assoc]

lemma supercharge_maps_plus_to_minus
    (S : Supercharge (E := E))
    {v : DoubledSpace E}
    (hv : inGradePlus (E := E) v) :
    inGradeMinus (E := E) (S.Q v) := by
  unfold inGradeMinus
  have hoddv : (modular_j (E := E) (S.Q v)) = -(S.Q (modular_j (E := E) v)) := by
    have h := ContinuousLinearMap.ext_iff.1 S.odd v
    simpa [isOdd, ContinuousLinearMap.comp_apply] using h
  rw [hoddv, hv]

lemma supercharge_maps_minus_to_plus
    (S : Supercharge (E := E))
    {v : DoubledSpace E}
    (hv : inGradeMinus (E := E) v) :
    inGradePlus (E := E) (S.Q v) := by
  unfold inGradePlus
  have hoddv : (modular_j (E := E) (S.Q v)) = -(S.Q (modular_j (E := E) v)) := by
    have h := ContinuousLinearMap.ext_iff.1 S.odd v
    simpa [isOdd, ContinuousLinearMap.comp_apply] using h
  rw [hoddv, hv, map_neg, neg_neg]

lemma superHamiltonian_maps_plus_to_plus
    (S : Supercharge (E := E))
    {v : DoubledSpace E}
    (hv : inGradePlus (E := E) v) :
    inGradePlus (E := E) ((superHamiltonian (E := E) S) v) := by
  unfold superHamiltonian superSquare
  apply supercharge_maps_minus_to_plus
  apply supercharge_maps_plus_to_minus
  exact hv

lemma superHamiltonian_maps_minus_to_minus
    (S : Supercharge (E := E))
    {v : DoubledSpace E}
    (hv : inGradeMinus (E := E) v) :
    inGradeMinus (E := E) ((superHamiltonian (E := E) S) v) := by
  unfold superHamiltonian superSquare
  apply supercharge_maps_plus_to_minus
  apply supercharge_maps_minus_to_plus
  exact hv

/-- Canonical supercharge generated by `ε`. -/
noncomputable def epsilonSupercharge : Supercharge (E := E) where
  Q := spectral_epsilon (E := E)
  odd := spectral_epsilon_isOdd (E := E)

lemma epsilonSupercharge_hamiltonian :
    superHamiltonian (E := E) (epsilonSupercharge (E := E))
      = ContinuousLinearMap.id ℝ (DoubledSpace E) := by
  unfold superHamiltonian superSquare epsilonSupercharge
  exact spectral_epsilon_involution (E := E)

lemma complex_i_isOdd :
    isOdd (E := E) (complex_i (E := E)) := by
  unfold isOdd complex_i
  apply ContinuousLinearMap.ext
  intro v
  rcases v with ⟨x, y⟩
  simp [modular_j, spectral_epsilon]

/-- Canonical supercharge generated by `I = J ∘ ε`. -/
noncomputable def complex_iSupercharge : Supercharge (E := E) where
  Q := complex_i (E := E)
  odd := complex_i_isOdd (E := E)

lemma complex_iSupercharge_hamiltonian :
    superHamiltonian (E := E) (complex_iSupercharge (E := E))
      = -(ContinuousLinearMap.id ℝ (DoubledSpace E)) := by
  unfold superHamiltonian superSquare complex_iSupercharge
  exact complex_i_sq (E := E)

end InfoGeometry.Krein
