import InfoGeometry.Krein.DoubledSpace
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Analysis.Normed.Algebra.Exponential
import Mathlib.Analysis.Normed.Module.Basic
import Mathlib.Analysis.Normed.Operator.Basic
import Mathlib.Analysis.Normed.Operator.Mul
import Mathlib.Analysis.Normed.Algebra.Basic
import Mathlib.Topology.Algebra.Ring.Basic

namespace InfoGeometry.Krein

section KreinThermalRoot

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H] [KreinSpace H]

local notation "EndK" => H →L[ℝ] H

noncomputable local instance : NormedRing EndK := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndK := inferInstance
local instance : IsTopologicalRing EndK := inferInstance
local instance : CompleteSpace EndK := inferInstance

/-- Genuine Krein-rooted modular conjugation of an observable by the flow generated by `K`. -/
noncomputable def krein_modular_shift
    (K : EndK) (β : ℝ) (B : EndK) : EndK :=
  (NormedSpace.exp (β • K)) * B * (NormedSpace.exp ((-β) • K))

omit [CompleteSpace H] in
@[simp] lemma krein_modular_shift_zero
    (K : EndK) (B : EndK) :
    krein_modular_shift K 0 B = B := by
  simp [krein_modular_shift]

omit [KreinSpace H] in
/-- Additive-time law for Krein-rooted modular conjugation. -/
lemma krein_modular_shift_add
    (K : EndK) (s t : ℝ) (B : EndK) :
    krein_modular_shift K (s + t) B =
      krein_modular_shift K s (krein_modular_shift K t B) := by
  have h_comm : Commute (s • K) (t • K) :=
    ((Commute.refl K).smul_left s).smul_right t
  have h_comm_neg : Commute ((-t) • K) ((-s) • K) :=
    ((Commute.refl K).smul_left (-t)).smul_right (-s)
  unfold krein_modular_shift
  change
    NormedSpace.exp ((s + t) • K) * B * NormedSpace.exp ((-(s + t)) • K) =
      NormedSpace.exp (s • K) *
          (NormedSpace.exp (t • K) * B * NormedSpace.exp ((-t) • K)) *
        NormedSpace.exp ((-s) • K)
  calc
    NormedSpace.exp ((s + t) • K) * B * NormedSpace.exp ((-(s + t)) • K)
        = (NormedSpace.exp (s • K) * NormedSpace.exp (t • K)) * B *
            (NormedSpace.exp ((-t) • K) * NormedSpace.exp ((-s) • K)) := by
          rw [← NormedSpace.exp_add_of_commute h_comm]
          rw [← NormedSpace.exp_add_of_commute h_comm_neg]
          simp [add_smul, mul_assoc, add_comm]
    _ = NormedSpace.exp (s • K) *
          (NormedSpace.exp (t • K) * B * NormedSpace.exp ((-t) • K)) *
        NormedSpace.exp ((-s) • K) := by
          ring_nf
          simp [mul_assoc]

/-- Simplified Krein-rooted KMS-like algebraic identity at inverse temperature `β`. -/
noncomputable def krein_satisfies_kms_like
    (K : EndK)
    (ω : EndK →L[ℝ] ℝ)
    (β : ℝ) : Prop :=
  ∀ A B : EndK, ω (A * krein_modular_shift K β B) = ω (B * A)

/-- Compatibility alias for the Krein-rooted KMS identity. -/
noncomputable def krein_satisfies_kms
    (K : EndK)
    (ω : EndK →L[ℝ] ℝ)
    (β : ℝ) : Prop :=
  krein_satisfies_kms_like K ω β

omit [CompleteSpace H] in
lemma krein_kms_like_zero_implies_commutation
    (K : EndK)
    (ω : EndK →L[ℝ] ℝ)
    (hKMS : krein_satisfies_kms_like K ω 0) :
    ∀ A B : EndK, ω (A * B) = ω (B * A) := by
  intro A B
  have h := hKMS A B
  have hshift : krein_modular_shift K 0 B = B := by
    simp [krein_modular_shift]
  simpa [hshift] using h

omit [CompleteSpace H] in
lemma krein_kms_zero_implies_commutation
    (K : EndK)
    (ω : EndK →L[ℝ] ℝ)
    (hKMS : krein_satisfies_kms K ω 0) :
    ∀ A B : EndK, ω (A * B) = ω (B * A) :=
  krein_kms_like_zero_implies_commutation K ω hKMS

end KreinThermalRoot

section KreinThermal

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "H₂" => DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂

noncomputable local instance : NormedRing EndH := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndH := inferInstance
local instance : IsTopologicalRing EndH := inferInstance
local instance : CompleteSpace EndH := inferInstance

/-- Compatibility specialization of the Krein-rooted modular shift to `DoubledSpace E`. -/
noncomputable abbrev modular_shift
    (K : EndH) (β : ℝ) (B : EndH) : EndH :=
  krein_modular_shift (H := H₂) K β B

omit [CompleteSpace E] in
@[simp] lemma modular_shift_zero
    (K : EndH) (B : EndH) :
    modular_shift K 0 B = B := by
  exact krein_modular_shift_zero (H := H₂) K B

/-- Compatibility specialization of the additive-time modular-shift law to `DoubledSpace E`. -/
lemma modular_shift_add
    (K : EndH) (s t : ℝ) (B : EndH) :
    modular_shift K (s + t) B =
      modular_shift K s (modular_shift K t B) := by
  simpa [modular_shift] using krein_modular_shift_add (H := H₂) K s t B

/-- Compatibility specialization of the Krein-rooted KMS-like identity. -/
noncomputable abbrev satisfies_kms_like
    (K : EndH)
    (ω : EndH →L[ℝ] ℝ)
    (β : ℝ) : Prop :=
  krein_satisfies_kms_like (H := H₂) K ω β

/-- Compatibility alias for `satisfies_kms_like`. -/
noncomputable abbrev satisfies_kms
    (K : EndH)
    (ω : EndH →L[ℝ] ℝ)
    (β : ℝ) : Prop :=
  krein_satisfies_kms (H := H₂) K ω β

omit [CompleteSpace E] in
/-- At `β = 0`, the KMS-like identity reduces to commutation symmetry `ω (A B) = ω (B A)`. -/
lemma kms_like_zero_implies_commutation
    (K : EndH)
    (ω : EndH →L[ℝ] ℝ)
    (hKMS : satisfies_kms_like K ω 0) :
    ∀ A B : EndH, ω (A * B) = ω (B * A) := by
  simpa [satisfies_kms_like] using
    (krein_kms_like_zero_implies_commutation (H := H₂) K ω hKMS)

omit [CompleteSpace E] in
/-- Compatibility alias for `kms_like_zero_implies_commutation`. -/
lemma kms_zero_implies_commutation
    (K : EndH)
    (ω : EndH →L[ℝ] ℝ)
    (hKMS : satisfies_kms K ω 0) :
    ∀ A B : EndH, ω (A * B) = ω (B * A) := by
  simpa [satisfies_kms] using
    (krein_kms_zero_implies_commutation (H := H₂) K ω hKMS)

/-- Thermal vacuum data for a chosen modular generator `K`. -/
structure ThermalVacuum (K : EndH) where
  Omega : H₂
  modular_j_fixed : modular_j Omega = Omega
  generator_annihilates : K Omega = 0
  vacuum_nonzero : Omega ≠ 0

omit [CompleteSpace E] in
lemma spectral_epsilon_eq_zero_iff (v : H₂) :
    spectral_epsilon v = 0 ↔ v = 0 := by
  constructor
  · intro h
    apply DoubledSpace.ext
    · simpa using (congr_arg WithLp.fst h)
    · simpa using (congr_arg WithLp.snd h)
  · rintro rfl; simp

omit [CompleteSpace E] in
lemma ThermalVacuum.modular_j_Omega
    {K : EndH}
    (Ω : ThermalVacuum K) :
    modular_j Ω.Omega = Ω.Omega :=
  Ω.modular_j_fixed

omit [CompleteSpace E] in
/-- Special case: if the generator is `spectral_epsilon`, the vacuum is forced to be zero. -/
lemma ThermalVacuum.eq_zero_of_spectral_epsilon
    (Ω : ThermalVacuum (spectral_epsilon : EndH)) :
    Ω.Omega = 0 :=
  (spectral_epsilon_eq_zero_iff Ω.Omega).1 Ω.generator_annihilates

omit [CompleteSpace E] in
/-- Degenerate special case: for generator `ε`, the modular flow fixes the (zero) vacuum. -/
lemma modular_flow_inv_Omega_of_spectral_epsilon
    (Ω : ThermalVacuum (spectral_epsilon : EndH))
    (t : ℝ) :
    (NormedSpace.exp (t • (spectral_epsilon : EndH))) Ω.Omega = Ω.Omega := by
  have hzero : Ω.Omega = 0 := Ω.eq_zero_of_spectral_epsilon
  rw [hzero]
  simp

omit [CompleteSpace E] in
/-- Compatibility alias for the degenerate `ε`-generated flow statement. -/
lemma modular_flow_inv_Omega
    (Ω : ThermalVacuum (spectral_epsilon : EndH))
    (t : ℝ) :
    (NormedSpace.exp (t • (spectral_epsilon : EndH))) Ω.Omega = Ω.Omega :=
  modular_flow_inv_Omega_of_spectral_epsilon Ω t

end KreinThermal

end InfoGeometry.Krein
