import sympy as sp

def verify_quaternion_clifford_embedding():
    print("--- SymPy Verification: H -> Cl(1,3; C) Embedding ---")

    # Pauli matrices
    I = sp.I
    sigma_1 = sp.Matrix([[0, 1], [1, 0]])
    sigma_2 = sp.Matrix([[0, -I], [I, 0]])
    sigma_3 = sp.Matrix([[1, 0], [0, -1]])

    # Zero and Identity for 2x2 blocks
    Z = sp.zeros(2)
    Id2 = sp.eye(2)

    # Dirac Gamma Matrices in Dirac Representation
    # gamma^0 = diag(I, -I)
    gamma_0 = sp.Matrix(sp.BlockMatrix([[Id2, Z], [Z, -Id2]]))

    # gamma^k = [[0, sigma_k], [-sigma_k, 0]]
    gamma_1 = sp.Matrix(sp.BlockMatrix([[Z, sigma_1], [-sigma_1, Z]]))
    gamma_2 = sp.Matrix(sp.BlockMatrix([[Z, sigma_2], [-sigma_2, Z]]))
    gamma_3 = sp.Matrix(sp.BlockMatrix([[Z, sigma_3], [-sigma_3, Z]]))

    # The Quaternion Basis Embedding:
    # 1 |-> I
    # i |-> gamma^1 * gamma^2
    # j |-> gamma^2 * gamma^3
    # k |-> gamma^3 * gamma^1

    E1 = sp.eye(4)
    Ei = gamma_1 * gamma_2
    Ej = gamma_2 * gamma_3
    Ek = gamma_3 * gamma_1

    print("Verifying i^2 = j^2 = k^2 = -1...")
    assert sp.simplify(Ei * Ei + E1) == sp.zeros(4), "i^2 != -1"
    assert sp.simplify(Ej * Ej + E1) == sp.zeros(4), "j^2 != -1"
    assert sp.simplify(Ek * Ek + E1) == sp.zeros(4), "k^2 != -1"

    print("Verifying i*j = k...")
    assert sp.simplify(Ei * Ej - Ek) == sp.zeros(4), "i*j != k"

    print("Verifying j*k = i...")
    assert sp.simplify(Ej * Ek - Ei) == sp.zeros(4), "j*k != i"

    print("Verifying k*i = j...")
    assert sp.simplify(Ek * Ei - Ej) == sp.zeros(4), "k*i != j"

    print("Verifying i*j*k = -1...")
    assert sp.simplify(Ei * Ej * Ek + E1) == sp.zeros(4), "i*j*k != -1"

    print("--- Embedding Verification Successful! ---")
    print("The quaternion algebra H is perfectly isomorphic to the Cl(0,2) subalgebra generated by gamma^1*gamma^2, etc.")

if __name__ == "__main__":
    verify_quaternion_clifford_embedding()
