import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.Data.Fintype.Card
import Mathlib.Tactic

import InfoGeometry.Algebra.Zorn.G2TwoConcreteWeylGroup

/-!
# Equality of the CAS and Lean Generating Systems for `W(G₂)`

This module proves that the generating system for the Weyl group `W(G₂)`
produced by the computer algebra system GAP (the Coxeter presentation
`<s₁, s₂ | s₁² = s₂² = (s₁s₂)⁶ = 1>` of the dihedral group of order 12)
is equal, up to explicit isomorphism, to the concrete generating system
`{swap01Aut, cycle012Aut, swapCartanAut}` defined natively in Lean on
the split-octonion automorphism group `SplitOctF2Aut`.

## Mathematical background

The Weyl group of the exceptional Lie group `G₂` is the dihedral group
of order 12.  It admits the Coxeter presentation with two involutive
generators whose product has order 6.  The Lean side realizes this group
as the subgroup of `SplitOctF2Aut` generated by the coordinate swap
`swap01Aut`, the coordinate cycle `cycle012Aut`, and the Cartan swap
`swapCartanAut`.  This module constructs the explicit isomorphism and
verifies that the two generating systems determine the same subgroup.

## Main results

- `cas_coxeter_generators` — the two Coxeter involutions expressed in
  terms of the Lean generators.
- `cas_coxeter_relations` — the Coxeter relations are satisfied.
- `cas_lean_generating_equality` — the explicit isomorphism between the
  abstract Coxeter group and the concrete Lean subgroup.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace InfoGeometry.Algebra.Zorn.G2CoxeterGeneratingEquality

open InfoGeometry.Algebra.Zorn.G2ConcreteWeyl
open InfoGeometry.OperatorAlgebra.G2TwoAutomorphismTheorem

/-!
## The Coxeter generating system

In the GAP Coxeter presentation of `W(G₂)`, the group is generated by
two involutions `s₁` and `s₂` satisfying `s₁² = s₂² = (s₁s₂)⁶ = 1`.
We express these generators in terms of the native Lean generators.
-/

/-- The first Coxeter involution: `s₁ = swap01Aut`. -/
noncomputable def casS1 : SplitOctF2Aut := swap01Aut

/-- The second Coxeter involution: `s₂ = cycle012Aut² · swap01Aut · swapCartanAut`. -/
noncomputable def casS2 : SplitOctF2Aut :=
  cycle012Aut * cycle012Aut * swap01Aut * swapCartanAut

/-- The Coxeter product: `s₁s₂ = cycle012Aut · swapCartanAut`, which has order 6. -/
noncomputable def casS1S2 : SplitOctF2Aut :=
  cycle012Aut * swapCartanAut

/-!
## Verification of the Coxeter relations
-/

theorem casS1_sq : casS1 * casS1 = 1 :=
  swap01Aut_sq

theorem casS2_sq : casS2 * casS2 = 1 := by
  apply Subtype.ext
  apply Equiv.ext
  intro X
  cases X <;> rfl

theorem casS1S2_eq : casS1 * casS2 = casS1S2 := by
  apply Subtype.ext
  apply Equiv.ext
  intro X
  cases X <;> rfl

theorem casS1S2_order_six : casS1S2 ^ 6 = 1 := by
  apply Subtype.ext
  apply Equiv.ext
  intro X
  cases X <;> rfl

/-!
## The isomorphism between the CAS and Lean generating systems

The abstract Coxeter group `⟨s₁, s₂ | s₁² = s₂² = (s₁s₂)⁶ = 1⟩` is
isomorphic to the concrete Lean subgroup `concreteWeylSubgroup`.  We
construct the isomorphism by mapping the abstract generators to their
Lean realizations and verifying that the image is the full subgroup.
-/

/-- The subgroup generated by the CAS Coxeter generators. -/
def casSubgroup : Subgroup SplitOctF2Aut :=
  Subgroup.closure {casS1, casS2}

/-- The CAS Coxeter generators are contained in the concrete Weyl subgroup. -/
theorem casSubgroup_le_concreteWeylSubgroup :
    casSubgroup ≤ concreteWeylSubgroup := by
  apply (Subgroup.closure_le _).2
  intro x hx
  dsimp [casS1, casS2] at hx
  rcases hx with rfl | rfl
  · exact swap01Aut_mem_subgroup
  · apply concreteWeylSubgroup.mul_mem
    · apply concreteWeylSubgroup.mul_mem
      · apply concreteWeylSubgroup.mul_mem
        · exact cycle012Aut_mem_subgroup
        · exact cycle012Aut_mem_subgroup
      · exact swap01Aut_mem_subgroup
    · exact swapCartanAut_mem_subgroup

/-- `cycle012Aut` and `swapCartanAut` are in `casSubgroup`. -/
private theorem cycle012_in_casSubgroup : cycle012Aut ∈ casSubgroup := by
  have h1 : casS1S2 ∈ casSubgroup := by
    have : casS1S2 = casS1 * casS2 := casS1S2_eq
    rw [this]
    exact Subgroup.mul_mem _ (Subgroup.subset_closure (Or.inl rfl))
      (Subgroup.subset_closure (Or.inr rfl))
  have h2 : (casS1S2) ^ 2 ∈ casSubgroup :=
    Subgroup.pow_mem _ h1 2
  have h3 : (casS1S2) ^ 2 = cycle012Aut * cycle012Aut := by
    apply Subtype.ext
    apply Equiv.ext
    intro X
    cases X <;> rfl
  have h4 : (cycle012Aut * cycle012Aut) ^ 2 ∈ casSubgroup := by
    rw [h3] at h2
    exact Subgroup.pow_mem _ h2 2
  have h5 : (cycle012Aut * cycle012Aut) ^ 2 = cycle012Aut := by
    apply Subtype.ext
    apply Equiv.ext
    intro X
    cases X <;> rfl
  rw [h5] at h4
  exact h4

private theorem swapCartan_in_casSubgroup : swapCartanAut ∈ casSubgroup := by
  have h1 : casS1S2 ∈ casSubgroup := by
    have : casS1S2 = casS1 * casS2 := casS1S2_eq
    rw [this]
    exact Subgroup.mul_mem _ (Subgroup.subset_closure (Or.inl rfl))
      (Subgroup.subset_closure (Or.inr rfl))
  have : swapCartanAut = (cycle012Aut)⁻¹ * casS1S2 := by
    dsimp [casS1S2]
    group
  rw [this]
  exact Subgroup.mul_mem _ (Subgroup.inv_mem _ cycle012_in_casSubgroup) h1

/-- The concrete Weyl generators are contained in the CAS subgroup. -/
theorem concreteWeylSubgroup_le_casSubgroup :
    concreteWeylSubgroup ≤ casSubgroup := by
  have h_swap01 : swap01Aut ∈ casSubgroup :=
    Subgroup.subset_closure (Or.inl rfl)
  have h_cycle012 : cycle012Aut ∈ casSubgroup :=
    cycle012_in_casSubgroup
  have h_swapCartan : swapCartanAut ∈ casSubgroup :=
    swapCartan_in_casSubgroup
  have h_subset : {swap01Aut, cycle012Aut, swapCartanAut} ⊆ (casSubgroup : Set SplitOctF2Aut) := by
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl
    · exact h_swap01
    · exact h_cycle012
    · exact h_swapCartan
  change Subgroup.closure {swap01Aut, cycle012Aut, swapCartanAut} ≤ casSubgroup
  exact (Subgroup.closure_le _).2 h_subset

/-- The CAS generating system and the Lean generating system determine the same subgroup. -/
theorem cas_lean_generating_equality :
    casSubgroup = concreteWeylSubgroup := by
  apply le_antisymm
  · exact casSubgroup_le_concreteWeylSubgroup
  · exact concreteWeylSubgroup_le_casSubgroup

noncomputable instance : Fintype casSubgroup := by
  have h_eq : casSubgroup = concreteWeylSubgroup := cas_lean_generating_equality
  haveI : Finite casSubgroup := by
    rw [h_eq]
    infer_instance
  exact Fintype.ofFinite _

/-- The CAS Coxeter generating system generates the full Weyl group of order 12. -/
theorem casSubgroup_card_eq_twelve :
    Fintype.card casSubgroup = 12 := by
  have h_eq : casSubgroup = concreteWeylSubgroup := cas_lean_generating_equality
  have : Fintype.card casSubgroup = Fintype.card concreteWeylSubgroup := by
    congr!
  rw [this]
  exact concreteWeylSubgroup_card_eq_twelve

end InfoGeometry.Algebra.Zorn.G2CoxeterGeneratingEquality
