import Mathlib.Tactic
import Mathlib.Algebra.Algebra.Opposite
import Mathlib.Algebra.Star.StarAlgHom
import Mathlib.LinearAlgebra.TensorAlgebra.Basic

/-!
# Algebraic Cuntz quotient via the tensor algebra

A Clifford-style algebraic presentation of the finite Cuntz relations.

This is **not** a C*-algebra completion.  It is the purely algebraic universal
semiring/algebra generated by formal symbols `Sᵢ` and `Tᵢ` modulo

* `Tᵢ Sⱼ = δᵢⱼ`,
* `∑ᵢ Sᵢ Tᵢ = 1`.

The construction follows mathlib's `CliffordAlgebra` pattern:
`TensorAlgebra` on a free module of generators, then `RingQuot` by an
inductive relation.  The universal `lift` only checks the defining relations on
relation constructors, avoiding nested tensor-product associator bookkeeping.
-/

noncomputable section

namespace AlgebraicCuntzQuotient

open TensorAlgebra

/-- Formal Cuntz letters: `s i` and its formal adjoint/right inverse `t i`. -/
inductive CuntzLetter (ι : Type*) where
  | s : ι → CuntzLetter ι
  | t : ι → CuntzLetter ι
  deriving DecidableEq, Repr

variable {R ι A : Type*} [CommSemiring R] [Fintype ι] [DecidableEq ι]

/-- Swap a formal Cuntz generator with its formal adjoint. -/
def letterSwap : CuntzLetter ι ≃ CuntzLetter ι where
  toFun
    | .s i => .t i
    | .t i => .s i
  invFun
    | .s i => .t i
    | .t i => .s i
  left_inv := by
    intro a
    cases a <;> rfl
  right_inv := by
    intro a
    cases a <;> rfl

/-- Free `R`-module on the formal Cuntz letters. -/
abbrev Gen (R : Type*) [CommSemiring R] (ι : Type*) := CuntzLetter ι →₀ R

/-- Linear swap on the free module of formal Cuntz generators. -/
def starGen : Gen R ι ≃ₗ[R] Gen R ι :=
  Finsupp.mapDomain.linearEquiv R R (letterSwap (ι := ι))

/-- Tensor algebra before imposing the Cuntz relations. -/
abbrev TAlg (R : Type*) [CommSemiring R] (ι : Type*) := TensorAlgebra R (Gen R ι)

/-- Basis vector corresponding to one formal Cuntz letter. -/
def letter (a : CuntzLetter ι) : Gen R ι := Finsupp.single a 1

/-- Free-algebra generator `Sᵢ`. -/
def S₀ (i : ι) : TAlg R ι := TensorAlgebra.ι R (letter (R := R) (CuntzLetter.s i))

/-- Free-algebra generator `Tᵢ`, the formal adjoint/right inverse of `Sᵢ`. -/
def T₀ (i : ι) : TAlg R ι := TensorAlgebra.ι R (letter (R := R) (CuntzLetter.t i))

/-- The algebraic Cuntz relations in the tensor algebra. -/
inductive Rel : TAlg R ι → TAlg R ι → Prop
  | ortho (i j : ι) : Rel (T₀ (R := R) i * S₀ (R := R) j) (if i = j then 1 else 0)
  | partition : Rel (∑ i : ι, S₀ (R := R) i * T₀ (R := R) i) 1

/-- The algebraic finite Cuntz algebra: tensor algebra modulo Cuntz relations. -/
def CuntzAlg (R : Type*) [CommSemiring R] (ι : Type*) [Fintype ι] [DecidableEq ι] :=
  RingQuot (@Rel R ι _ _ _)
deriving Inhabited, Semiring, Algebra R

/-- Quotient map from the tensor algebra. -/
def mk : TAlg R ι →ₐ[R] CuntzAlg R ι := RingQuot.mkAlgHom R (@Rel R ι _ _ _)

/-- Quotient generator `Sᵢ`. -/
def S (i : ι) : CuntzAlg R ι := mk (R := R) (S₀ (R := R) i)

/-- Quotient generator `Tᵢ`. -/
def T (i : ι) : CuntzAlg R ι := mk (R := R) (T₀ (R := R) i)

/-- In the quotient, `Tᵢ Sⱼ = δᵢⱼ`. -/
theorem T_mul_S (i j : ι) : T (R := R) i * S (R := R) j = if i = j then 1 else 0 := by
  change mk (R := R) (T₀ (R := R) i) * mk (R := R) (S₀ (R := R) j) = _
  rw [← map_mul]
  simpa using RingQuot.mkAlgHom_rel R (Rel.ortho (R := R) i j)

/-- In the quotient, the range projections sum to one. -/
theorem partition_one : (∑ i : ι, S (R := R) i * T (R := R) i) = 1 := by
  calc
    (∑ i : ι, S (R := R) i * T (R := R) i) =
        ∑ i : ι, mk (R := R) (S₀ (R := R) i * T₀ (R := R) i) := by
      simp [S, T]
    _ = mk (R := R) (∑ i : ι, S₀ (R := R) i * T₀ (R := R) i) := by
      exact (map_sum (mk (R := R)) (fun i : ι => S₀ (R := R) i * T₀ (R := R) i) Finset.univ).symm
    _ = 1 := by
      simpa using RingQuot.mkAlgHom_rel R (Rel.partition (R := R) (ι := ι))

variable [Semiring A] [Algebra R A]

/-- Evaluate free generators by a proposed Cuntz family in an `R`-algebra `A`. -/
def evalGen (s t : ι → A) : Gen R ι →ₗ[R] A :=
  Finsupp.linearCombination R (fun a : CuntzLetter ι =>
    match a with
    | .s i => s i
    | .t i => t i)

omit [Fintype ι] [DecidableEq ι] in
@[simp] theorem evalGen_s (s t : ι → A) (i : ι) :
    evalGen (R := R) s t (letter (R := R) (CuntzLetter.s i)) = s i := by
  simp [evalGen, letter]

omit [Fintype ι] [DecidableEq ι] in
@[simp] theorem evalGen_t (s t : ι → A) (i : ι) :
    evalGen (R := R) s t (letter (R := R) (CuntzLetter.t i)) = t i := by
  simp [evalGen, letter]

/-- The tensor-algebra lift respects the Cuntz relation constructors. -/
def liftCondition (s t : ι → A)
    (h_ortho : ∀ i j, t i * s j = if i = j then 1 else 0)
    (h_partition : (∑ i : ι, s i * t i) = 1) :
    ∀ ⦃x y : TAlg R ι⦄, Rel x y →
      (TensorAlgebra.lift R (evalGen (R := R) s t)) x =
        (TensorAlgebra.lift R (evalGen (R := R) s t)) y := by
  intro x y h
  cases h with
  | ortho i j =>
      simp [S₀, T₀, h_ortho]
  | partition =>
      simpa [S₀, T₀] using h_partition

/-- Universal property: any algebraic Cuntz family in `A` receives a hom from
`CuntzAlg`.  The proof is exactly the Clifford/RingQuot pattern: lift from the
tensor algebra, then check the two relation constructors. -/
def lift (s t : ι → A)
    (h_ortho : ∀ i j, t i * s j = if i = j then 1 else 0)
    (h_partition : (∑ i : ι, s i * t i) = 1) : CuntzAlg R ι →ₐ[R] A :=
  RingQuot.liftAlgHom R
    ⟨TensorAlgebra.lift R (evalGen (R := R) s t), liftCondition (R := R) s t h_ortho h_partition⟩

/-- The universal hom sends quotient `Sᵢ` to the chosen `sᵢ`. -/
theorem lift_S (s t : ι → A)
    (h_ortho : ∀ i j, t i * s j = if i = j then 1 else 0)
    (h_partition : (∑ i : ι, s i * t i) = 1) (i : ι) :
    lift (R := R) s t h_ortho h_partition (S (R := R) i) = s i := by
  calc
    lift (R := R) s t h_ortho h_partition (S (R := R) i)
        = (TensorAlgebra.lift R (evalGen (R := R) s t)) (S₀ (R := R) i) := by
      change ((RingQuot.liftAlgHom R)
          ⟨TensorAlgebra.lift R (evalGen (R := R) s t),
            liftCondition (R := R) s t h_ortho h_partition⟩)
          ((RingQuot.mkAlgHom R (@Rel R ι _ _ _)) (S₀ (R := R) i)) =
        (TensorAlgebra.lift R (evalGen (R := R) s t)) (S₀ (R := R) i)
      exact RingQuot.liftAlgHom_mkAlgHom_apply R
        (TensorAlgebra.lift R (evalGen (R := R) s t))
        (liftCondition (R := R) s t h_ortho h_partition)
        (S₀ (R := R) i)
    _ = s i := by
      simp [S₀]

/-- The universal hom sends quotient `Tᵢ` to the chosen `tᵢ`. -/
theorem lift_T (s t : ι → A)
    (h_ortho : ∀ i j, t i * s j = if i = j then 1 else 0)
    (h_partition : (∑ i : ι, s i * t i) = 1) (i : ι) :
    lift (R := R) s t h_ortho h_partition (T (R := R) i) = t i := by
  calc
    lift (R := R) s t h_ortho h_partition (T (R := R) i)
        = (TensorAlgebra.lift R (evalGen (R := R) s t)) (T₀ (R := R) i) := by
      change ((RingQuot.liftAlgHom R)
          ⟨TensorAlgebra.lift R (evalGen (R := R) s t),
            liftCondition (R := R) s t h_ortho h_partition⟩)
          ((RingQuot.mkAlgHom R (@Rel R ι _ _ _)) (T₀ (R := R) i)) =
        (TensorAlgebra.lift R (evalGen (R := R) s t)) (T₀ (R := R) i)
      exact RingQuot.liftAlgHom_mkAlgHom_apply R
        (TensorAlgebra.lift R (evalGen (R := R) s t))
        (liftCondition (R := R) s t h_ortho h_partition)
        (T₀ (R := R) i)
    _ = t i := by
      simp [T₀]

section Star

open MulOpposite

/-- The algebraic adjoint/reversal map, valued in the opposite algebra.

It sends the formal Cuntz generator `Sᵢ` to `op Tᵢ` and `Tᵢ` to `op Sᵢ`,
so multiplication order is reversed by the target opposite algebra. -/
def starOp : CuntzAlg R ι →ₐ[R] (CuntzAlg R ι)ᵐᵒᵖ :=
  lift (R := R) (A := (CuntzAlg R ι)ᵐᵒᵖ)
    (fun i => op (T (R := R) i))
    (fun i => op (S (R := R) i))
    (by
      intro i j
      apply unop_injective
      by_cases hij : i = j
      · subst hij
        simp [T_mul_S]
      · have hji : j ≠ i := by exact fun h => hij h.symm
        simp [T_mul_S, hij, hji])
    (by
      apply unop_injective
      simp [partition_one])

@[simp] theorem starOp_S (i : ι) :
    starOp (R := R) (AlgebraicCuntzQuotient.S (R := R) i) = op (T (R := R) i) := by
  exact lift_S (R := R) (A := (CuntzAlg R ι)ᵐᵒᵖ)
    (fun i => op (T (R := R) i))
    (fun i => op (S (R := R) i))
    (by
      intro i j
      apply unop_injective
      by_cases hij : i = j
      · subst hij
        simp [T_mul_S]
      · have hji : j ≠ i := by exact fun h => hij h.symm
        simp [T_mul_S, hij, hji])
    (by
      apply unop_injective
      simp [partition_one])
    i

@[simp] theorem starOp_T (i : ι) :
    starOp (R := R) (AlgebraicCuntzQuotient.T (R := R) i) = op (S (R := R) i) := by
  exact lift_T (R := R) (A := (CuntzAlg R ι)ᵐᵒᵖ)
    (fun i => op (T (R := R) i))
    (fun i => op (S (R := R) i))
    (by
      intro i j
      apply unop_injective
      by_cases hij : i = j
      · subst hij
        simp [T_mul_S]
      · have hji : j ≠ i := by exact fun h => hij h.symm
        simp [T_mul_S, hij, hji])
    (by
      apply unop_injective
      simp [partition_one])
    i

omit [Fintype ι] [DecidableEq ι] in
@[simp] theorem starGen_letter_s (i : ι) :
    starGen (R := R) (letter (R := R) (CuntzLetter.s i)) =
      letter (R := R) (CuntzLetter.t i) := by
  simp [starGen, letter, letterSwap]

omit [Fintype ι] [DecidableEq ι] in
@[simp] theorem starGen_letter_t (i : ι) :
    starGen (R := R) (letter (R := R) (CuntzLetter.t i)) =
      letter (R := R) (CuntzLetter.s i) := by
  simp [starGen, letter, letterSwap]

theorem starOp_mk_ι (x : Gen R ι) :
    starOp (R := R) (mk (R := R) (TensorAlgebra.ι R x)) =
      op (mk (R := R) (TensorAlgebra.ι R (starGen (R := R) x))) := by
  induction x using Finsupp.induction_linear with
  | zero =>
      simp [starGen]
  | add x y hx hy =>
      simp [map_add, hx, hy]
  | single a r =>
      cases a with
      | s i =>
          rw [← Finsupp.smul_single_one]
          calc
            starOp (R := R) (mk (R := R)
                (TensorAlgebra.ι R (r • letter (R := R) (CuntzLetter.s i)))) =
                r • starOp (R := R) (S (R := R) i) := by
              simp [S, S₀]
            _ = r • op (T (R := R) i) := by
              rw [starOp_S]
            _ = op (mk (R := R)
                (TensorAlgebra.ι R (starGen (R := R) (r • letter (R := R) (CuntzLetter.s i))))) := by
              simp [T, T₀]
      | t i =>
          rw [← Finsupp.smul_single_one]
          calc
            starOp (R := R) (mk (R := R)
                (TensorAlgebra.ι R (r • letter (R := R) (CuntzLetter.t i)))) =
                r • starOp (R := R) (T (R := R) i) := by
              simp [T, T₀]
            _ = r • op (S (R := R) i) := by
              rw [starOp_T]
            _ = op (mk (R := R)
                (TensorAlgebra.ι R (starGen (R := R) (r • letter (R := R) (CuntzLetter.t i))))) := by
              simp [S, S₀]

omit [Fintype ι] [DecidableEq ι] in
@[simp] theorem starGen_starGen (x : Gen R ι) :
    starGen (R := R) (starGen (R := R) x) = x := by
  change Finsupp.mapDomain (letterSwap (ι := ι))
      (Finsupp.mapDomain (letterSwap (ι := ι)) x) = x
  rw [← Finsupp.mapDomain_comp]
  convert Finsupp.mapDomain_id (v := x) using 2
  ext a
  cases a <;> rfl

/-- The algebraic Cuntz quotient carries the formal adjoint operation
`Sᵢ ↦ Tᵢ`, `Tᵢ ↦ Sᵢ`. -/
instance instStar : Star (CuntzAlg R ι) where
  star x := unop (starOp (R := R) x)

@[simp] theorem star_mk_ι (x : Gen R ι) :
    star (mk (R := R) (TensorAlgebra.ι R x)) =
      mk (R := R) (TensorAlgebra.ι R (starGen (R := R) x)) := by
  change unop (starOp (R := R) (mk (R := R) (TensorAlgebra.ι R x))) = _
  rw [starOp_mk_ι]
  rfl

@[simp] theorem star_S (i : ι) : star (S (R := R) i) = T (R := R) i := by
  simp [Star.star]

@[simp] theorem star_T (i : ι) : star (T (R := R) i) = S (R := R) i := by
  simp [Star.star]

@[simp] theorem star_mk (x : TAlg R ι) :
    star (mk (R := R) x) = unop (starOp (R := R) (mk (R := R) x)) := rfl

@[simp] theorem star_algebraMap (r : R) :
    star (algebraMap R (CuntzAlg R ι) r) = algebraMap R (CuntzAlg R ι) r := by
  change unop (starOp (R := R) (algebraMap R (CuntzAlg R ι) r)) =
    algebraMap R (CuntzAlg R ι) r
  simp

theorem star_mul (x y : CuntzAlg R ι) : star (x * y) = star y * star x := by
  change unop (starOp (R := R) (x * y)) =
    unop (starOp (R := R) y) * unop (starOp (R := R) x)
  simp

theorem star_add (x y : CuntzAlg R ι) : star (x + y) = star x + star y := by
  change unop (starOp (R := R) (x + y)) =
    unop (starOp (R := R) x) + unop (starOp (R := R) y)
  simp

theorem star_star_mk (x : TAlg R ι) : star (star (mk (R := R) x)) = mk (R := R) x := by
  induction x using TensorAlgebra.induction with
  | algebraMap r =>
      simp
  | ι x =>
      rw [star_mk_ι, star_mk_ι, starGen_starGen]
  | mul x y hx hy =>
      rw [map_mul, star_mul, star_mul, hx, hy]
  | add x y hx hy =>
      rw [map_add, star_add, star_add, hx, hy]

theorem star_star (x : CuntzAlg R ι) : star (star x) = x := by
  rcases RingQuot.mkAlgHom_surjective R (@Rel R ι _ _ _) x with ⟨x, rfl⟩
  exact star_star_mk (R := R) x

instance instStarRing : StarRing (CuntzAlg R ι) where
  star_involutive := star_star (R := R)
  star_mul := star_mul (R := R)
  star_add := star_add (R := R)

#check starOp
#check starOp_S
#check starOp_T
#check star_S
#check star_T
#check star_mul
#check star_add
#check star_star
#check instStarRing

end Star

#check CuntzAlg
#check T_mul_S
#check partition_one
#check lift
#check lift_S
#check lift_T

end AlgebraicCuntzQuotient
