import Mathlib.Analysis.CStarAlgebra.Classes
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Algebra.Star.Subalgebra
import Mathlib.Topology.Algebra.StarSubalgebra
import InfoGeometry.Topology.AlgebraicCuntzQuotient

/-!
# C⋆ interface for the algebraic Cuntz tensor quotient

This file connects the tensor-algebra/RingQuot presentation
`InfoGeometry.Topology.AlgebraicCuntzQuotient.CuntzAlg ℂ ι` to genuine mathlib C⋆-algebras.

The quotient constructed in `AlgebraicCuntzQuotient` is algebraic, but it now
has the formal adjoint `star Sᵢ = Tᵢ`, `star Tᵢ = Sᵢ`.  A universal
C⋆-completion/norm is not constructed here.  Instead, this file proves the
representation interface into an existing mathlib `CStarAlgebra`.
-/

noncomputable section

universe uι uA uB

namespace InfoGeometry.Physics.CStarCuntzTensorQuotient

open InfoGeometry.Topology.AlgebraicCuntzQuotient

variable {ι A : Type*} [Fintype ι] [DecidableEq ι]

/-- A finite Cuntz family inside a mathlib C⋆-algebra. -/
structure CStarCuntzFamily (A : Type*) [CStarAlgebra A] (ι : Type*) [Fintype ι] [DecidableEq ι] where
  S : ι → A
  ortho : ∀ i j, star (S i) * S j = if i = j then 1 else 0
  partition : (∑ i : ι, S i * star (S i)) = 1

namespace CStarCuntzFamily

variable [CStarAlgebra A]

/-- The formal `Tᵢ` image determined by the C⋆-adjoint. -/
def T (F : CStarCuntzFamily A ι) (i : ι) : A := star (F.S i)

@[simp] theorem T_def (F : CStarCuntzFamily A ι) (i : ι) : F.T i = star (F.S i) := rfl

/-- Any C⋆ Cuntz family gives an algebra representation of the algebraic Cuntz quotient. -/
def lift (F : CStarCuntzFamily A ι) : InfoGeometry.Topology.AlgebraicCuntzQuotient.CuntzAlg ℂ ι →ₐ[ℂ] A :=
  InfoGeometry.Topology.AlgebraicCuntzQuotient.lift (R := ℂ) F.S F.T F.ortho (by simpa [T] using F.partition)

/-- The universal representation sends formal `Sᵢ` to the C⋆ generator. -/
theorem lift_S (F : CStarCuntzFamily A ι) (i : ι) :
    F.lift (InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i) = F.S i := by
  exact InfoGeometry.Topology.AlgebraicCuntzQuotient.lift_S (R := ℂ) F.S F.T F.ortho
    (by simpa [T] using F.partition) i

/-- The universal representation sends formal `Tᵢ` to `star (Sᵢ)`. -/
theorem lift_T (F : CStarCuntzFamily A ι) (i : ι) :
    F.lift (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i) = star (F.S i) := by
  exact InfoGeometry.Topology.AlgebraicCuntzQuotient.lift_T (R := ℂ) F.S F.T F.ortho
    (by simpa [T] using F.partition) i

/-- The C⋆ representation is compatible with the formal adjoint on generators. -/
theorem lift_star_S (F : CStarCuntzFamily A ι) (i : ι) :
    F.lift (star (InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i)) =
      star (F.lift (InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i)) := by
  simp [lift_S, lift_T]

/-- The C⋆ representation is compatible with the formal adjoint on formal adjoints. -/
theorem lift_star_T (F : CStarCuntzFamily A ι) (i : ι) :
    F.lift (star (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i)) =
      star (F.lift (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i)) := by
  simp [lift_S, lift_T]

/-- Each Cuntz generator is an isometry in the C⋆ sense: `Sᵢ⋆ Sᵢ = 1`. -/
theorem isometry_relation (F : CStarCuntzFamily A ι) (i : ι) :
    star (F.S i) * F.S i = 1 := by
  simpa using F.ortho i i

/-- Distinct Cuntz generators have orthogonal initial spaces. -/
theorem orthogonal_relation (F : CStarCuntzFamily A ι) {i j : ι} (hij : i ≠ j) :
    star (F.S i) * F.S j = 0 := by
  simpa [hij] using F.ortho i j

/-- The algebraic quotient relations are satisfied after applying the C⋆ representation. -/
theorem represented_cuntz_relations (F : CStarCuntzFamily A ι) :
    (∀ i j, F.lift (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i *
        InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) j) = if i = j then 1 else 0) ∧
    F.lift (∑ i : ι, InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i *
        InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i) = 1 := by
  constructor
  · intro i j
    simp [map_mul, lift_S, lift_T, F.ortho]
  · simp [map_sum, map_mul, lift_S, lift_T, F.partition]

/-! ## Concrete generated C⋆-subalgebra inside an ambient C⋆-algebra -/

/-- The closed star subalgebra generated by the Cuntz family inside the ambient C⋆-algebra. -/
def generatedCStarSubalgebra (F : CStarCuntzFamily A ι) : StarSubalgebra ℂ A :=
  (StarAlgebra.adjoin ℂ (Set.range F.S)).topologicalClosure

/-- Each generator belongs to the generated closed star subalgebra. -/
theorem S_mem_generatedCStarSubalgebra (F : CStarCuntzFamily A ι) (i : ι) :
    F.S i ∈ F.generatedCStarSubalgebra := by
  exact StarSubalgebra.le_topologicalClosure _
    (StarAlgebra.subset_adjoin ℂ (Set.range F.S) ⟨i, rfl⟩)

/-- The generated closed star subalgebra inherits a genuine mathlib C⋆-algebra structure. -/
instance generatedCStarSubalgebra.cstar (F : CStarCuntzFamily A ι) :
    CStarAlgebra F.generatedCStarSubalgebra :=
  StarSubalgebra.cstarAlgebra F.generatedCStarSubalgebra
    (h_closed := by
      dsimp [generatedCStarSubalgebra]
      exact StarSubalgebra.isClosed_topologicalClosure _)

/-- The same Cuntz family, now internal to its generated C⋆-subalgebra. -/
def generatedFamily (F : CStarCuntzFamily A ι) :
    CStarCuntzFamily F.generatedCStarSubalgebra ι where
  S i := ⟨F.S i, F.S_mem_generatedCStarSubalgebra i⟩
  ortho i j := by
    ext
    by_cases h : i = j
    · subst j
      simp [F.ortho]
    · simp [h, F.ortho]
  partition := by
    ext
    simpa using F.partition

/-- The algebraic Cuntz quotient maps into the concrete generated C⋆-subalgebra. -/
def liftToGenerated (F : CStarCuntzFamily A ι) :
    InfoGeometry.Topology.AlgebraicCuntzQuotient.CuntzAlg ℂ ι →ₐ[ℂ] F.generatedCStarSubalgebra :=
  F.generatedFamily.lift

/-- In the generated C⋆-subalgebra, formal `Sᵢ` maps to the included generator. -/
theorem liftToGenerated_S (F : CStarCuntzFamily A ι) (i : ι) :
    F.liftToGenerated (InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i) =
      ⟨F.S i, F.S_mem_generatedCStarSubalgebra i⟩ := by
  exact CStarCuntzFamily.lift_S F.generatedFamily i

/-- In the generated C⋆-subalgebra, formal `Tᵢ` maps to the included adjoint. -/
theorem liftToGenerated_T (F : CStarCuntzFamily A ι) (i : ι) :
    F.liftToGenerated (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i) =
      star (⟨F.S i, F.S_mem_generatedCStarSubalgebra i⟩ : F.generatedCStarSubalgebra) := by
  exact CStarCuntzFamily.lift_T F.generatedFamily i

end CStarCuntzFamily

/-- Data describing a C⋆ completion/realization of the algebraic Cuntz quotient.

This packages the analytic boundary not supplied by `RingQuot`: a carrier with
a genuine mathlib `CStarAlgebra` instance, Cuntz generators which topologically
generate the carrier, and the universal star-homomorphism property.
-/
structure CStarCuntzCompletion (ι : Type uι) [Fintype ι] [DecidableEq ι] where
  carrier : Type uA
  [cstar : CStarAlgebra carrier]
  family : CStarCuntzFamily carrier ι
  /-- The completion has no extra C⋆ part beyond the closed algebra generated by `Sᵢ`. -/
  universalNormCompletion :
    family.generatedCStarSubalgebra = ⊤
  /--
  Every Cuntz family in a complex C⋆-algebra receives a unique star-algebra
  homomorphism from the completion, determined by the images of the generators.
  -/
  universalStarHomProperty :
    ∀ (B : Type uB) [CStarAlgebra B] (F : CStarCuntzFamily B ι),
      ∃! phi : StarAlgHom ℂ carrier B,
        ∀ i : ι, phi (family.S i) = F.S i

attribute [instance] CStarCuntzCompletion.cstar

namespace CStarCuntzCompletion

/-- The selected Cuntz generators topologically generate the completion. -/
theorem generatedCStarSubalgebra_eq_top
    (U : CStarCuntzCompletion ι) :
    U.family.generatedCStarSubalgebra = ⊤ :=
  U.universalNormCompletion

/-- Universal star-homomorphism out of the selected C⋆ Cuntz completion. -/
abbrev existsUnique_starAlgHom
    (U : CStarCuntzCompletion ι) :=
  U.universalStarHomProperty

/-- The canonical algebraic representation into the C⋆ completion/realization. -/
def algebraicToCStar (U : CStarCuntzCompletion ι) :
    InfoGeometry.Topology.AlgebraicCuntzQuotient.CuntzAlg ℂ ι →ₐ[ℂ] U.carrier :=
  U.family.lift

/-- The algebraic generator `Sᵢ` maps to the C⋆ generator in the completion. -/
theorem algebraicToCStar_S (U : CStarCuntzCompletion ι) (i : ι) :
    U.algebraicToCStar (InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i) = U.family.S i := by
  exact CStarCuntzFamily.lift_S U.family i

/-- The algebraic generator `Tᵢ` maps to the adjoint of the C⋆ generator. -/
theorem algebraicToCStar_T (U : CStarCuntzCompletion ι) (i : ι) :
    U.algebraicToCStar (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i) = star (U.family.S i) := by
  exact CStarCuntzFamily.lift_T U.family i

/-- The C⋆ realization satisfies the represented Cuntz relations. -/
theorem represented_relations (U : CStarCuntzCompletion ι) :
    (∀ i j, U.algebraicToCStar
        (InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i * InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) j) =
      if i = j then 1 else 0) ∧
    U.algebraicToCStar
        (∑ i : ι, InfoGeometry.Topology.AlgebraicCuntzQuotient.S (R := ℂ) i *
          InfoGeometry.Topology.AlgebraicCuntzQuotient.T (R := ℂ) i) = 1 := by
  exact CStarCuntzFamily.represented_cuntz_relations U.family

end CStarCuntzCompletion

#check InfoGeometry.Topology.AlgebraicCuntzQuotient.starOp
#check InfoGeometry.Topology.AlgebraicCuntzQuotient.star_S
#check InfoGeometry.Topology.AlgebraicCuntzQuotient.star_T
#check CStarCuntzFamily
#check CStarCuntzFamily.lift
#check CStarCuntzFamily.lift_S
#check CStarCuntzFamily.lift_T
#check CStarCuntzFamily.lift_star_S
#check CStarCuntzFamily.lift_star_T
#check CStarCuntzFamily.represented_cuntz_relations
#check CStarCuntzFamily.generatedCStarSubalgebra
#check CStarCuntzFamily.generatedFamily
#check CStarCuntzFamily.liftToGenerated
#check CStarCuntzFamily.liftToGenerated_S
#check CStarCuntzFamily.liftToGenerated_T
#check CStarCuntzCompletion

end InfoGeometry.Physics.CStarCuntzTensorQuotient
