import InfoGeometry.Physics.LogCFT
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Clifford.LogCftMonodromy
import InfoGeometry.Clifford.DiscreteMoebiusGroup
import InfoGeometry.LogJordanKreinCore
import InfoGeometry.Physics.LogCFTJordanShear
import Mathlib.Tactic

/-!
# Finite logarithmic-CFT Jordan and unipotent-flow identities

This is the finite-dimensional algebraic bridge for a logarithmic partner.
It reuses `InfoGeometry.Physics.LogCFT` and records only identities of the
explicit two-dimensional matrix block.  No scaling-limit or continuum CFT
statement is asserted.
-/

namespace InfoGeometry.Physics

variable {R : Type*} [CommRing R]

/-- The physics `L0` owner and the Clifford logarithmic-cell owner are the
same finite matrix carrier. -/
theorem L0_eq_virasoroL0Cell (h : R) :
    L0 h = InfoGeometry.Clifford.LogCftMonodromy.virasoroL0Cell h := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [L0, N_log,
      InfoGeometry.Clifford.LogCftMonodromy.virasoroL0Cell,
      InfoGeometry.Clifford.LogCftMonodromy.upperJordan,
      Matrix.add_apply, Matrix.smul_apply]

/-- The nilpotent part of `L0` is recovered by subtracting its scalar weight. -/
theorem L0_sub_scalar_eq_N_log (h : R) :
    L0 h - h • (1 : Matrix (Fin 2) (Fin 2) R) = N_log := by
  simp [L0, sub_eq_add_neg, add_assoc]

/-- The centered finite scaling operator has square-zero deviation. -/
theorem L0_centered_sq_zero (h : R) :
    (L0 h - h • (1 : Matrix (Fin 2) (Fin 2) R)) ^ 2 = 0 := by
  rw [L0_sub_scalar_eq_N_log]
  simpa [pow_two] using N_log_sq_zero (R := R)

/-- The finite logarithmic flow generated by the Jordan nilpotent. -/
def logCFTUnipotentFlow (t : R) : Matrix (Fin 2) (Fin 2) R :=
  (1 : Matrix (Fin 2) (Fin 2) R) + t • N_log

/-! The complex analytic owner and this finite flow owner have the same
explicit rank-two carrier. -/
theorem complex_logCFTUnipotentFlow_eq_jordanShear (t : ℂ) :
    logCFTUnipotentFlow t =
      InfoGeometry.Physics.LogCFTJordanShear.unipotentShear t := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [logCFTUnipotentFlow,
      InfoGeometry.Physics.LogCFTJordanShear.unipotentShear,
      N_log, InfoGeometry.Physics.LogCFTJordanShear.nilpotentN,
      Matrix.add_apply]

theorem complex_logCFTUnipotentFlow_eq_exp (t : ℂ) :
    logCFTUnipotentFlow t =
      NormedSpace.exp (t • N_log) := by
  have hN : N_log =
      InfoGeometry.Physics.LogCFTJordanShear.nilpotentN := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [N_log, InfoGeometry.Physics.LogCFTJordanShear.nilpotentN]
  rw [hN, InfoGeometry.Physics.LogCFTJordanShear.exp_scaledNilpotent]
  exact complex_logCFTUnipotentFlow_eq_jordanShear t

theorem logCFTUnipotentFlow_zero :
    logCFTUnipotentFlow (0 : R) = 1 := by
  simp [logCFTUnipotentFlow]

theorem logCFTUnipotentFlow_add (s t : R) :
    logCFTUnipotentFlow (s + t) =
      logCFTUnipotentFlow s * logCFTUnipotentFlow t := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [logCFTUnipotentFlow, N_log, Matrix.mul_apply,
      Fin.sum_univ_two]
  ring

theorem logCFTUnipotentFlow_inverse (t : R) :
    logCFTUnipotentFlow t * logCFTUnipotentFlow (-t) = 1 := by
  have h := logCFTUnipotentFlow_add t (-t)
  simpa [logCFTUnipotentFlow_zero, neg_smul] using h.symm

theorem logCFTUnipotentFlow_pow (t : R) (n : ℕ) :
    logCFTUnipotentFlow t ^ n = logCFTUnipotentFlow (n • t) := by
  induction n with
  | zero =>
      simp [logCFTUnipotentFlow_zero]
  | succ n ih =>
      rw [pow_succ, ih, ← logCFTUnipotentFlow_add]
      <;> simp [add_smul, one_smul]
      <;> ring_nf
      <;> simp_all [logCFTUnipotentFlow_add]
      <;> try ring_nf
      <;> try simp_all [Matrix.mul_apply, Fin.sum_univ_two, N_log]
      <;> try aesop

theorem logCFTUnipotentFlow_apply (t : R) :
    logCFTUnipotentFlow t = !![1, t; 0, 1] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [logCFTUnipotentFlow, N_log, Matrix.add_apply]

/-! The unipotent flow is the centered `L0` flow: the conformal weight is
separated from the nilpotent logarithmic partner direction. -/
theorem logCFTUnipotentFlow_eq_centered_L0_flow (h t : R) :
    logCFTUnipotentFlow t =
      (1 : Matrix (Fin 2) (Fin 2) R) +
        t • (L0 h - h • (1 : Matrix (Fin 2) (Fin 2) R)) := by
  rw [L0_sub_scalar_eq_N_log]
  rfl

/-! The real finite clock is read on the existing complex affine chart by
the canonical parabolic Möbius action. -/
theorem real_logCFT_projective_shear (t : ℝ) (z : ℂ) :
    InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction
        (InfoGeometry.Clifford.MonodromyFlowAdapter.lcftParabolicFlowStep (t : ℂ)) z =
      z + (t : ℂ) := by
  exact InfoGeometry.Clifford.DiscreteMoebiusGroup.moebius_monodromy_flow_action
    (t : ℂ) z

/-! The real Krein owner uses the same finite Jordan carrier. -/
theorem real_L0_eq_logJordanKreinCore_L (h : ℝ) :
    L0 h = InfoGeometry.LogJordanKreinCore.L h := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [L0, N_log, InfoGeometry.LogJordanKreinCore.L,
      InfoGeometry.LogJordanKreinCore.scalarMatrix,
      InfoGeometry.LogJordanKreinCore.N, Matrix.add_apply,
      Matrix.smul_apply]

theorem real_logCFT_detector_trace (t h : ℝ) :
    Matrix.trace
        (InfoGeometry.LogJordanKreinCore.N.transpose *
          (Real.exp (t * h) •
            (1 + t • InfoGeometry.LogJordanKreinCore.N))) =
      t * Real.exp (t * h) := by
  exact InfoGeometry.LogJordanKreinCore.detector_trace_jordanCell t h

theorem real_logCFT_parity_trace_zero (t h : ℝ) :
    Matrix.trace
        (InfoGeometry.LogJordanKreinCore.χ *
          (Real.exp (t * h) •
            (1 + t • InfoGeometry.LogJordanKreinCore.N))) = 0 := by
  exact InfoGeometry.LogJordanKreinCore.parity_trace_jordanCell t h

end InfoGeometry.Physics
