import InfoGeometry.Physics.MDPASJMSouriau
import InfoGeometry.Physics.MDPASJMSouriauDigest
import InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction
import InfoGeometry.Physics.SouriauEntropyFoliation
import InfoGeometry.Topology.ThermodynamicGauge
import InfoGeometry.Topology.WilsonLoopThermodynamics

/-!
# MDPAS-JMSouriau paper digest

Finite theorem-honest packet for Souriau's 1974 spin-particle paper.

This module does not claim the global distributional, symplectic, or
quantization theorems of the paper.  It only re-exports the finite owner
lemmas already present in the repository and packages them into a single
finite-stage carrier for future inductive-limit transport.

Covered finite content:

* decomposable spin bivectors and Pfaffian/Plücker identities;
* antisymmetric electromagnetic tensor readouts and Lorentz-force power;
* mass-shell and normal gyromagnetic finite readouts;
* finite Gibbs / Massieu / Fisher identities and entropy-sheet transport;
* finite detailed-balance path readouts and prequantum scaling laws.
-/

noncomputable section

namespace InfoGeometry.Physics.MDPASJMSouriauPaperDigest

open InfoGeometry.Topology.ThermodynamicGauge
open InfoGeometry.Topology.WilsonLoopThermodynamics
open InfoGeometry.Physics.SouriauEntropyFoliation
open InfoGeometry.Physics.MDPASJMSouriauDigest.FiniteMDPASJMDirectSystem

/-- Finite-stage packet bundling the paper's particle and thermodynamic spines. -/
def FiniteMDPASPaperPacket
    (ι : Type*) [Fintype ι] [Nonempty ι]
    (Op : Type*) [Ring Op] [Algebra ℝ Op]
    (State LieAlgebra LieDual : Type*) :=
  InfoGeometry.Physics.MDPASJMSouriau.FiniteSpinParticleCertificate ×
    InfoGeometry.Physics.MDPASJMSouriauDigest.FiniteMDPASJMStageData
      ι Op State LieAlgebra LieDual × ℝ × (ι → ℝ)

namespace FiniteMDPASPaperPacket

variable {ι : Type*} [Fintype ι] [Nonempty ι]
variable {Op : Type*} [Ring Op] [Algebra ℝ Op]
variable {State LieAlgebra LieDual : Type*}

/-- The particle spin bivector is decomposable, hence Pfaffian-zero. -/
theorem spin_pfaffian_zero
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual) :
    InfoGeometry.Physics.MDPASJMSouriau.pfaffian4
        (InfoGeometry.Physics.MDPASJMSouriau.wedge D.1.u D.1.v) = 0 :=
  D.1.spin_plucker

/-- The finite Lorentz-force power readout vanishes for the supplied antisymmetric field. -/
theorem lorentz_power_zero
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual) :
    InfoGeometry.Physics.MDPASJMSouriau.dot
      D.1.p
      (InfoGeometry.Physics.MDPASJMSouriau.lorentzForce D.1.field D.1.p) = 0 :=
  D.1.lorentz_power_zero

/-- The normal spin-half prequantization readout is integral. -/
theorem spin_half_prequantized
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual)
    (h : ℚ) :
    InfoGeometry.Physics.MDPASJMSouriau.SpinPrequantized (h / 2) h :=
  D.1.spin_half_prequantization h

/-- The finite Souriau sheet entropy obeys the Massieu-Planck identity. -/
theorem souriauSheetEntropy_eq_massieu_add_beta_meanEnergy
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual) :
    souriauSheetEntropy D.2.2.1 D.2.2.2 =
      massieuPlanckPotential D.2.2.1 D.2.2.2 + D.2.2.1 * meanEnergy D.2.2.1 D.2.2.2 :=
  InfoGeometry.Physics.SouriauEntropyFoliation.souriauSheetEntropy_eq_massieu_add_beta_meanEnergy
    D.2.2.1 D.2.2.2

/-- Permuting the finite Gibbs weights preserves the Boltzmann entropy. -/
theorem boltzmannEntropy_gibbsWeight_permuteWeight
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual)
    (σ : Equiv.Perm ι) :
    boltzmannEntropy (permuteWeight σ (gibbsWeight D.2.2.1 D.2.2.2)) =
      boltzmannEntropy (gibbsWeight D.2.2.1 D.2.2.2) :=
  boltzmannEntropy_permuteWeight σ (gibbsWeight D.2.2.1 D.2.2.2)

/-- The Gibbs weights generated by the packet lie on a single entropy sheet. -/
theorem sameEntropySheet_gibbsWeight_permuteWeight
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual)
    (σ : Equiv.Perm ι) :
    sameEntropySheet (permuteWeight σ (gibbsWeight D.2.2.1 D.2.2.2))
      (gibbsWeight D.2.2.1 D.2.2.2) :=
  sameEntropySheet_permuteWeight σ (gibbsWeight D.2.2.1 D.2.2.2)

/-- The finite path entropy vanishes in detailed balance. -/
theorem pathEntropy_eq_zero_of_detailed_balance
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual)
    (hdb : entropy_production D.2.1.flow = 0) :
    D.2.1.pathPacket.pathEntropy = 0 :=
  D.2.1.pathEntropy_eq_zero_of_detailed_balance hdb

/-- The finite caliber vanishes in detailed balance. -/
theorem caliber_eq_zero_of_detailed_balance
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual)
    (hdb : entropy_production D.2.1.flow = 0) :
    D.2.1.pathPacket.caliber = 0 :=
  D.2.1.caliber_eq_zero_of_detailed_balance hdb

/-- The finite path entropy is the curvature trace. -/
theorem pathEntropy_eq_curvatureTrace
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual) :
    D.2.1.pathPacket.pathEntropy =
      D.2.1.pathPacket.trace
        (thermodynamic_curvature D.2.1.pathPacket.flow) :=
  D.2.1.pathPacket.pathEntropy_eq_curvatureTrace

/-- The packet's prequantum holonomy scale is `ω / ħ`. -/
theorem prequantum_holonomyScale_eq_omega_over_hbar
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual) :
    D.2.1.prequantum.holonomyScale =
      D.2.1.prequantum.omegaScale / D.2.1.prequantum.hbar :=
  D.2.1.prequantum_holonomyScale_eq_omega_over_hbar

/-- The packet's prequantum covariant scale is gauge-invariant. -/
theorem prequantum_covariantScale_smul
    (D : FiniteMDPASPaperPacket ι Op State LieAlgebra LieDual)
    (u : PrequantumData.Gauge) :
    PrequantumData.covariantScale (u • D.2.1.prequantum) =
      PrequantumData.covariantScale D.2.1.prequantum :=
  D.2.1.prequantum_covariantScale_smul u

/--
The finite `FiniteMDPASJMStageData` tower admits a genuine direct-limit carrier
with a concrete quotient carrier and stage-to-stage compatibility of the finite
identities along the bonding maps.

This is the paper-level re-export of the owner theorem in
`InfoGeometry.Physics.MDPASJMSouriauDigest`.
-/
theorem finiteStageTower_inductiveLimitCarrier_lifts_finiteIdentities
  (T : InfoGeometry.Physics.MDPASJMSouriauDigest.FiniteMDPASJMDirectSystem
      ι Op State LieAlgebra LieDual) :
    Nonempty
      (DirectLimitCarrier T) ∧
      ∃ ofStageMap : ∀ _n : ℕ,
          Op → DirectLimitCarrier T,
        (∀ n x, ofStageMap (n + 1) (T.bond n x) = ofStageMap n x) ∧
        (∀ n,
          ofStageMap (n + 1)
              (entropy_production (T.tower.stage (n + 1)).flow) =
            ofStageMap n
              (entropy_production (T.tower.stage n).flow)) ∧
        (∀ n,
          ofStageMap (n + 1)
              (thermodynamic_gauge_connection (T.tower.stage (n + 1)).flow) =
            ofStageMap n
              (thermodynamic_gauge_connection (T.tower.stage n).flow)) ∧
        (∀ n,
          ofStageMap (n + 1)
              (thermodynamic_curvature (T.tower.stage (n + 1)).flow) =
            ofStageMap n
              (thermodynamic_curvature (T.tower.stage n).flow)) ∧
        (∀ n,
          (T.tower.stage n).rn.entropy =
            (T.tower.stage n).rn.expectationBeta
              (T.tower.stage n).rn.modularPotential) ∧
        (∀ n,
          (T.tower.stage n).pathPacket.pathEntropy =
            (T.tower.stage n).pathPacket.trace
              (thermodynamic_curvature (T.tower.stage n).pathPacket.flow)) :=
  inductiveLimitCarrier_lifts_finiteIdentities T

end FiniteMDPASPaperPacket

/-! ## Finite de Rham obstruction / symplectic / KK / quantization packet -/

namespace FiniteMDPASObstructionPacket

open InfoGeometry.Physics.MDPASJMSouriau
open InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction
open InfoGeometry.Physics.MDPASJMSouriauDigest.FiniteMDPASJMDirectSystem

variable {ι : Type*} [Fintype ι] [Nonempty ι]
variable {Op : Type*} [Ring Op] [Algebra ℝ Op]
variable {State LieAlgebra LieDual : Type*}

/-- The cellular `S²` area class is closed but not exact. -/
theorem sphereArea_not_exact :
    ¬ Exact2 sphereArea :=
  InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction.sphereArea_not_exact

/-- The finite symplectic plane is skew and nondegenerate. -/
theorem omega2_skew (v w : V2) :
    omega2 v w = - omega2 w v :=
  InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction.omega2_skew v w

/-- The finite symplectic plane is nondegenerate. -/
theorem omega2_nondegenerate (v : V2) (h : ∀ w : V2, omega2 v w = 0) :
    v = 0 :=
  InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction.omega2_nondegenerate v h

/-- The finite 5D Kaluza--Klein split identity. -/
theorem kk5_split (x : Vec5) :
    kk5Quadratic x =
      InfoGeometry.Physics.MDPASJMSouriau.minkowskiDot (fourPart x) (fourPart x) -
        fifthPart x ^ 2 :=
  InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction.kk5_split x

/-- A null 5D vector projects to a 4D mass shell. -/
theorem kk5_null_implies_four_mass_shell (x : Vec5) (hx : kkNull x) :
    InfoGeometry.Physics.MDPASJMSouriau.minkowskiDot (fourPart x) (fourPart x) =
      fifthPart x ^ 2 :=
  InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction.kk5_null_implies_four_mass_shell x hx

/-- Spin-half integrality is the finite prequantization readout. -/
theorem spin_half_integral_prequantization (h : ℚ) :
    PrequantizationIntegral (h / 2) h :=
  InfoGeometry.Physics.MDPASJMSouriauGlobalObstruction.spin_half_integral_prequantization h

/-- The finite MDPAS tower has a genuine quotient carrier and compatible identities. -/
theorem finiteStageTower_inductiveLimitCarrier_lifts_finiteIdentities
  (T : InfoGeometry.Physics.MDPASJMSouriauDigest.FiniteMDPASJMDirectSystem
      ι Op State LieAlgebra LieDual) :
    Nonempty (DirectLimitCarrier T) ∧
      ∃ ofStageMap : ∀ _n : ℕ,
          Op → DirectLimitCarrier T,
        (∀ n x, ofStageMap (n + 1) (T.bond n x) = ofStageMap n x) ∧
        (∀ n,
          ofStageMap (n + 1)
              (entropy_production (T.tower.stage (n + 1)).flow) =
            ofStageMap n
              (entropy_production (T.tower.stage n).flow)) ∧
        (∀ n,
          ofStageMap (n + 1)
              (thermodynamic_gauge_connection (T.tower.stage (n + 1)).flow) =
            ofStageMap n
              (thermodynamic_gauge_connection (T.tower.stage n).flow)) ∧
        (∀ n,
          ofStageMap (n + 1)
              (thermodynamic_curvature (T.tower.stage (n + 1)).flow) =
            ofStageMap n
              (thermodynamic_curvature (T.tower.stage n).flow)) ∧
        (∀ n,
          (T.tower.stage n).rn.entropy =
            (T.tower.stage n).rn.expectationBeta
              (T.tower.stage n).rn.modularPotential) ∧
        (∀ n,
          (T.tower.stage n).pathPacket.pathEntropy =
            (T.tower.stage n).pathPacket.trace
              (thermodynamic_curvature (T.tower.stage n).pathPacket.flow)) :=
  inductiveLimitCarrier_lifts_finiteIdentities T

end FiniteMDPASObstructionPacket

end InfoGeometry.Physics.MDPASJMSouriauPaperDigest
