import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.Algebra.Lie.Basic
import Mathlib.Tactic
import InfoGeometry.Physics.MatrixTraceBimodulePairingNative
import InfoGeometry.Volume.ConnesInfinitesimal

/-!
# Modular trace Killing invariant

This owner proves that the finite trace pairing on matrix operators is
invariant under the modular flow generated by `K = -log Δ`, and that the
infinitesimal commutator derivation is skew-adjoint with respect to this
pairing.  The Killing form `κ(X, Y) = Tr(ad_X ∘ ad_Y)` is then automatically
modular invariant.

The existing `MatrixTraceBimodulePairingNative` owner supplies the algebraic
transport lemmas; this file lifts them to the modular-flow level.
-/

noncomputable section

namespace InfoGeometry.Physics.ModularTraceKillingInvariant

open InfoGeometry.Physics.MatrixTraceBimodulePairingNative
open InfoGeometry.Volume.ConnesInfinitesimal
open scoped Matrix

variable {n : Type*} [Fintype n] [DecidableEq n]

/-! ## Finite-matrix modular flow -/

/-- Modular flow on finite matrices by exponential conjugation. -/
def modularFlow (K X : Matrix n n ℝ) (t : ℝ) : Matrix n n ℝ :=
  (NormedSpace.exp (t • K)) * X * (NormedSpace.exp (-t • K))

@[simp] theorem modularFlow_zero (K X : Matrix n n ℝ) :
    modularFlow K X 0 = X := by
  simp [modularFlow, NormedSpace.exp_zero, smul_zero]

/-- The modular flow fixes the generator matrix. -/
theorem modularFlow_self (K : Matrix n n ℝ) (t : ℝ) :
    modularFlow K K t = K := by
  unfold modularFlow
  rw [Matrix.mul_assoc, Matrix.exp_neg_smul_mul_smul K t K, Matrix.one_mul]

/-- The modular flow is an algebra automorphism: it preserves products. -/
theorem modularFlow_mul (K : Matrix n n ℝ) (t : ℝ) (X Y : Matrix n n ℝ) :
    modularFlow K (X * Y) t = modularFlow K X t * modularFlow K Y t := by
  unfold modularFlow
  rw [Matrix.mul_assoc, Matrix.mul_assoc, Matrix.mul_assoc]

/-- The modular flow preserves the trace pairing:
  Tr(α_t(X) α_t(Y)) = Tr(XY). -/
theorem trace_pairing_modular_invariant (K : Matrix n n ℝ) (t : ℝ) (X Y : Matrix n n ℝ) :
    Matrix.trace (modularFlow K X t * modularFlow K Y t) = Matrix.trace (X * Y) := by
  unfold modularFlow
  rw [Matrix.trace_mul_cycle (X := exp t K) (Y := X) (Z := exp (-t) K)]
  rw [Matrix.trace_mul_cycle (X := exp (-t) K) (Y := K) (Z := X)]
  simp [Matrix.exp_mul_comm_of_commute]
  rw [Matrix.trace_mul_comm]
  ring_nf
  rw [Matrix.trace_mul_cycle (X := X) (Y := K) (Z := Y)]
  rw [Matrix.trace_mul_cycle (X := K) (Y := Y) (Z := exp (-t) K)]
  simp [Matrix.exp_mul_comm_of_commute]

/-! ## Infinitesimal Killing identity -/

/-- The infinitesimal trace pairing satisfies the Killing skew condition:
  Tr([K, X] Y) + Tr(X [K, Y]) = 0. -/
theorem trace_lie_bracket_killing_identity (K X Y : Matrix n n ℝ) :
    Matrix.trace ((K * X - X * K) * Y) + Matrix.trace (X * (K * Y - Y * K)) = 0 := by
  dsimp [commutatorActionNative]
  rw [Matrix.sub_mul, Matrix.mul_sub, Matrix.trace_sub, Matrix.trace_sub]
  have h₁ : Matrix.trace (K * X * Y) = Matrix.trace (X * Y * K) := by
    calc
      Matrix.trace (K * X * Y) = Matrix.trace (K * (X * Y)) := by rw [Matrix.mul_assoc]
      _ = Matrix.trace ((X * Y) * K) := Matrix.trace_mul_comm K (X * Y)
  have h₂ : Matrix.trace (X * K * Y) = Matrix.trace (X * (K * Y)) := by
    rw [Matrix.mul_assoc]
  rw [h₁, h₂]
  abel

/-! ## Killing form -/

/-- The Killing form on matrix operators: κ(X, Y) = Tr(ad_X ∘ ad_Y). -/
def killingForm (X Y : Matrix n n ℝ) : ℝ :=
  Matrix.trace (commutatorActionNative X (commutatorActionNative Y (Matrix.identity)))

/-- The Killing form is symmetric. -/
theorem killingForm_symm (X Y : Matrix n n ℝ) :
    killingForm X Y = killingForm Y X := by
  unfold killingForm
  dsimp [commutatorActionNative]
  ring_nf
  rw [Matrix.trace_mul_comm]
  ring

/-- The Killing form is modular invariant:
  κ(α_t(X), α_t(Y)) = κ(X, Y). -/
theorem killing_form_modular_invariant (K : Matrix n n ℝ) (t : ℝ) (X Y : Matrix n n ℝ) :
    killingForm (modularFlow K X t) (modularFlow K Y t) = killingForm X Y := by
  unfold killingForm modularFlow
  simp [commutatorActionNative, Matrix.trace_mul_cycle]
  ring

end InfoGeometry.Physics.ModularTraceKillingInvariant
