import InfoGeometry.Lint.Vacuity
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Physics.NuclearCartanProjectorParityBridge
import InfoGeometry.Physics.NuclearFiniteCARCartanSolovievBridge
import InfoGeometry.Physics.NuclearParityGradedHamiltonian
import InfoGeometry.Physics.NuclearSolovievParitySymmetry
import InfoGeometry.Physics.NuclearWignerDensityProjectorBridge
import InfoGeometry.Physics.NuclearSpectroscopyZ2GradingBridge

/-! Focused diagnostics for the established nuclear theorem packets. -/

#check InfoGeometry.Physics.NuclearQuasiparticleCAR.QuasiparticleCAR.nuclear_sl2_packet
#check InfoGeometry.Physics.NuclearFiniteCARCartanSolovievBridge.finite_cartan_parity_soloviev_packet
#check InfoGeometry.Physics.NuclearParityGradedHamiltonian.conjugate_parameterHamiltonian
#check InfoGeometry.Physics.NuclearSolovievParitySymmetry.parity_conj_coupledHamiltonian_native
#check InfoGeometry.Physics.NuclearWignerDensityProjectorBridge.wigner_density_projector_packet
#check InfoGeometry.Physics.NuclearSpectroscopyZ2GradingBridge.shared_Z2_odd_operator_packet

#print axioms InfoGeometry.Physics.NuclearQuasiparticleCAR.QuasiparticleCAR.nuclear_sl2_packet
#print axioms InfoGeometry.Physics.NuclearFiniteCARCartanSolovievBridge.finite_cartan_parity_soloviev_packet
#print axioms InfoGeometry.Physics.NuclearParityGradedHamiltonian.conjugate_parameterHamiltonian
#print axioms InfoGeometry.Physics.NuclearSolovievParitySymmetry.parity_conj_coupledHamiltonian_native
#print axioms InfoGeometry.Physics.NuclearWignerDensityProjectorBridge.wigner_density_projector_packet
#print axioms InfoGeometry.Physics.NuclearSpectroscopyZ2GradingBridge.shared_Z2_odd_operator_packet
