import InfoGeometry.Physics.NuclearFiveGradeSolovievBdGAll

/-!
# Transitive axiom inspection for the nuclear closure lane

These commands inspect the elaborated dependency closures when Lean executes
this file. Any `sorryAx` or project-specific custom axiom is a verification
failure. The audit is not a substitute for kernel execution.
-/

#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeLieModel.comm_jacobi
#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeLieModel.comm_hasGrade
#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeLieModel.pair_extreme_bracket
#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeLieModel.concrete_nuclear_five_grade_packet
#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeSubmodules.gradeSpace
#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeSubmodules.gradeBracket
#print axioms InfoGeometry.Physics.NuclearTwoModeFiveGradeSubmodules.bundled_five_grade_packet

#print axioms InfoGeometry.Physics.NuclearFiveGradeKantorComponentBridge.gradingOperator_isTripotent
#print axioms InfoGeometry.Physics.NuclearFiveGradeKantorComponentBridge.hasGrade_iff_isCommutatorComponent
#print axioms InfoGeometry.Physics.NuclearFiveGradeKantorComponentBridge.product_isCommutatorComponent
#print axioms InfoGeometry.Physics.NuclearFiveGradeKantorComponentBridge.named_kantor_component_packet

#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.fermionAction_mul
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.representation_mul
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.representation_commutator
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.representation_preserves_grade
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.represented_mode1_CAR
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.phonon_CCR
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierRepresentation.five_grade_common_representation_packet
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierLieHom.commonRepresentationLieHom
#print axioms InfoGeometry.Physics.NuclearFiveGradeCommonCarrierLieHom.common_lie_representation_packet

#print axioms InfoGeometry.Physics.NuclearFiveGradeDegreeZeroSL2.degreeZeroCartan_comm_raise
#print axioms InfoGeometry.Physics.NuclearFiveGradeDegreeZeroSL2.degreeZero_raise_comm_lower
#print axioms InfoGeometry.Physics.NuclearFiveGradeDegreeZeroSL2.represented_degreeZero_sl2_packet
#print axioms InfoGeometry.Physics.NuclearFiveGradeDegreeZeroSL2.degree_zero_sl2_selection_packet

#print axioms InfoGeometry.Physics.NuclearFiveGradeSolovievCommonCompression.modelProjection_idempotent
#print axioms InfoGeometry.Physics.NuclearFiveGradeSolovievCommonCompression.compressedAction_eq_qpnm_mulVec
#print axioms InfoGeometry.Physics.NuclearFiveGradeSolovievCommonCompression.projected_fullHamiltonian_on_model
#print axioms InfoGeometry.Physics.NuclearFiveGradeSolovievCommonCompression.five_grade_soloviev_same_carrier_packet

#print axioms InfoGeometry.Physics.NuclearCARPhononCommonCarrier.qp_CAR
#print axioms InfoGeometry.Physics.NuclearCARPhononCommonCarrier.phonon_CCR
#print axioms InfoGeometry.Physics.NuclearCARPhononCommonCarrier.commonCoupledSystem
#print axioms InfoGeometry.Physics.NuclearCARPhononCommonCarrier.coefficientLift_commutator
#print axioms InfoGeometry.Physics.NuclearCARPhononCommonCarrier.common_car_phonon_packet

#print axioms InfoGeometry.Physics.NuclearSolovievCompression.modelReadout_modelEmbed
#print axioms InfoGeometry.Physics.NuclearSolovievCompression.compressedAction_eq_qpnm_mulVec
#print axioms InfoGeometry.Physics.NuclearSolovievCompression.compressed_eigenvalue_system
#print axioms InfoGeometry.Physics.NuclearSolovievProjectedHamiltonian.modelProjection_idempotent
#print axioms InfoGeometry.Physics.NuclearSolovievProjectedHamiltonian.projected_fullQPNM_on_model
#print axioms InfoGeometry.Physics.NuclearSolovievProjectedHamiltonian.projected_soloviev_packet

#print axioms InfoGeometry.Physics.NuclearBdGTwoLevelExact.bdgBlock_sq
#print axioms InfoGeometry.Physics.NuclearBdGTwoLevelExact.bdg_characteristic
#print axioms InfoGeometry.Physics.NuclearBdGTwoLevelExact.bdg_eigenbasis_intertwines
#print axioms InfoGeometry.Physics.NuclearBdGTwoLevelExact.particleHole_sq
#print axioms InfoGeometry.Physics.NuclearBdGTwoLevelExact.particleHole_anticommutes
#print axioms InfoGeometry.Physics.NuclearBdGBogoliubovCAR.uCoeff_sq_add_vCoeff_sq
#print axioms InfoGeometry.Physics.NuclearBdGBogoliubovCAR.normalizedPositiveEigenvector_eigen
#print axioms InfoGeometry.Physics.NuclearBdGBogoliubovCAR.normalized_bdg_CAR
#print axioms InfoGeometry.Physics.NuclearBdGBogoliubovCAR.normalized_bdg_bogoliubov_packet
#print axioms InfoGeometry.Physics.NuclearBdGBogoliubovCAR.exists_normalized_positive_eigenmode_with_CAR

#print axioms InfoGeometry.Physics.NuclearBdGSolovievAffineBridge.qpnm_eq_center_add_bdg
#print axioms InfoGeometry.Physics.NuclearBdGSolovievAffineBridge.qpnm_upper_bdg_root
#print axioms InfoGeometry.Physics.NuclearBdGSolovievAffineBridge.bdgSoloviev_compression

#print axioms InfoGeometry.Physics.NuclearFiveGradeSolovievBdGClosure.projected_soloviev_closure
#print axioms InfoGeometry.Physics.NuclearFiveGradeSolovievBdGClosure.nuclear_five_grade_car_phonon_bdg_soloviev_packet
#print axioms InfoGeometry.Physics.NuclearFiveGradeSameCarrierClosure.nuclear_same_carrier_closure_packet
