import Mathlib

/-!
# Two-mode CAR and an exact nuclear five-grading

This file constructs a finite four-state fermionic carrier and its associative
endomorphism algebra. The grading is generated by the centered occupation
operator `H = N₁ + N₂ - 1`.

The odd ladder operators have grades `±1`, their pair products have grades
`±2`, and `H` has grade zero. The pair operators and `H` form an exact
`sl₂`-triple. This is an operator five-grading; it is not obtained from the raw
commutator of the nonassociative split-octonion product.
-/

noncomputable section

namespace InfoGeometry.Physics.NuclearTwoModeCARFiveGrade

abbrev Fock4 := Fin 4 → ℂ
abbrev Op := Module.End ℂ Fock4

/-- Annihilation in the first fermionic mode. -/
def annihilationOne : Op where
  toFun ψ := ![ψ 1, 0, ψ 3, 0]
  map_add' ψ φ := by
    ext i
    fin_cases i <;> simp
  map_smul' c ψ := by
    ext i
    fin_cases i <;> simp

/-- Creation in the first fermionic mode. -/
def creationOne : Op where
  toFun ψ := ![0, ψ 0, 0, ψ 2]
  map_add' ψ φ := by
    ext i
    fin_cases i <;> simp
  map_smul' c ψ := by
    ext i
    fin_cases i <;> simp

/-- Jordan--Wigner annihilation in the second fermionic mode. -/
def annihilationTwo : Op where
  toFun ψ := ![ψ 2, -ψ 3, 0, 0]
  map_add' ψ φ := by
    ext i
    fin_cases i <;> simp
  map_smul' c ψ := by
    ext i
    fin_cases i <;> simp

/-- Jordan--Wigner creation in the second fermionic mode. -/
def creationTwo : Op where
  toFun ψ := ![0, 0, ψ 0, -ψ 1]
  map_add' ψ φ := by
    ext i
    fin_cases i <;> simp
  map_smul' c ψ := by
    ext i
    fin_cases i <;> simp

@[simp] theorem annihilationOne_apply (ψ : Fock4) :
    annihilationOne ψ = ![ψ 1, 0, ψ 3, 0] := rfl

@[simp] theorem creationOne_apply (ψ : Fock4) :
    creationOne ψ = ![0, ψ 0, 0, ψ 2] := rfl

@[simp] theorem annihilationTwo_apply (ψ : Fock4) :
    annihilationTwo ψ = ![ψ 2, -ψ 3, 0, 0] := rfl

@[simp] theorem creationTwo_apply (ψ : Fock4) :
    creationTwo ψ = ![0, 0, ψ 0, -ψ 1] := rfl

/-! ## Exact two-mode CAR -/

@[simp] theorem annihilationOne_sq :
    annihilationOne * annihilationOne = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem creationOne_sq :
    creationOne * creationOne = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem annihilationTwo_sq :
    annihilationTwo * annihilationTwo = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem creationTwo_sq :
    creationTwo * creationTwo = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-- Same-mode CAR for the first mode. -/
theorem CAR_one :
    annihilationOne * creationOne + creationOne * annihilationOne = 1 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-- Same-mode CAR for the second mode. -/
theorem CAR_two :
    annihilationTwo * creationTwo + creationTwo * annihilationTwo = 1 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-- Distinct annihilation operators anticommute. -/
theorem CAR_annihilation_cross :
    annihilationOne * annihilationTwo + annihilationTwo * annihilationOne = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-- Distinct creation operators anticommute. -/
theorem CAR_creation_cross :
    creationOne * creationTwo + creationTwo * creationOne = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-- Mixed distinct-mode CAR. -/
theorem CAR_one_two_mixed :
    annihilationOne * creationTwo + creationTwo * annihilationOne = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-- The other mixed distinct-mode CAR. -/
theorem CAR_two_one_mixed :
    annihilationTwo * creationOne + creationOne * annihilationTwo = 0 := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

/-! ## Occupation Cartan and pair operators -/

/-- Occupation of the first mode. -/
def numberOne : Op := creationOne * annihilationOne

/-- Occupation of the second mode. -/
def numberTwo : Op := creationTwo * annihilationTwo

/-- Centered total occupation, with eigenvalues `-1,0,0,+1`. -/
def gradeCartan : Op := numberOne + numberTwo - 1

/-- Pair creation. -/
def pairCreation : Op := creationOne * creationTwo

/-- Pair annihilation. -/
def pairAnnihilation : Op := annihilationTwo * annihilationOne

@[simp] theorem numberOne_apply (ψ : Fock4) :
    numberOne ψ = ![0, ψ 1, 0, ψ 3] := by
  ext i
  fin_cases i <;> simp [numberOne, Module.End.mul_apply]

@[simp] theorem numberTwo_apply (ψ : Fock4) :
    numberTwo ψ = ![0, 0, ψ 2, ψ 3] := by
  ext i
  fin_cases i <;> simp [numberTwo, Module.End.mul_apply]

@[simp] theorem gradeCartan_apply (ψ : Fock4) :
    gradeCartan ψ = ![-ψ 0, 0, 0, ψ 3] := by
  ext i
  fin_cases i <;>
    simp [gradeCartan, numberOne, numberTwo, Module.End.mul_apply]

@[simp] theorem pairCreation_apply (ψ : Fock4) :
    pairCreation ψ = ![0, 0, 0, ψ 0] := by
  ext i
  fin_cases i <;> simp [pairCreation, Module.End.mul_apply]

@[simp] theorem pairAnnihilation_apply (ψ : Fock4) :
    pairAnnihilation ψ = ![ψ 3, 0, 0, 0] := by
  ext i
  fin_cases i <;> simp [pairAnnihilation, Module.End.mul_apply]

/-- Commutator in the associative endomorphism algebra. -/
def commutator (X Y : Op) : Op := X * Y - Y * X

@[simp] theorem commutator_self (X : Op) : commutator X X = 0 := by
  simp [commutator]

/-- The adjoint action is a derivation of operator multiplication. -/
theorem commutator_mul_leibniz (H X Y : Op) :
    commutator H (X * Y) = commutator H X * Y + X * commutator H Y := by
  unfold commutator
  noncomm_ring

/-- Jacobi in derivation form. -/
theorem commutator_commutator_leibniz (H X Y : Op) :
    commutator H (commutator X Y) =
      commutator (commutator H X) Y + commutator X (commutator H Y) := by
  unfold commutator
  noncomm_ring

/-- Weight equation for the occupation Cartan. -/
def HasGrade (k : ℤ) (X : Op) : Prop :=
  commutator gradeCartan X = (k : ℂ) • X

@[simp] theorem grade_creationOne : HasGrade 1 creationOne := by
  unfold HasGrade commutator
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem grade_creationTwo : HasGrade 1 creationTwo := by
  unfold HasGrade commutator
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem grade_annihilationOne : HasGrade (-1) annihilationOne := by
  unfold HasGrade commutator
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem grade_annihilationTwo : HasGrade (-1) annihilationTwo := by
  unfold HasGrade commutator
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem grade_pairCreation : HasGrade 2 pairCreation := by
  unfold HasGrade commutator
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem grade_pairAnnihilation : HasGrade (-2) pairAnnihilation := by
  unfold HasGrade commutator
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [Module.End.mul_apply]

@[simp] theorem grade_gradeCartan : HasGrade 0 gradeCartan := by
  simp [HasGrade]

/-- Brackets add Cartan grades. -/
theorem HasGrade.commutator
    {m n : ℤ} {X Y : Op}
    (hX : HasGrade m X) (hY : HasGrade n Y) :
    HasGrade (m + n) (commutator X Y) := by
  unfold HasGrade at hX hY ⊢
  rw [commutator_commutator_leibniz, hX, hY]
  apply LinearMap.ext
  intro ψ
  ext i
  simp [commutator, Module.End.mul_apply, Int.cast_add]
  ring

/-! ## Exact pair `sl₂` relations -/

/-- Pair commutator equals the centered occupation Cartan. -/
theorem pairCreation_pairAnnihilation_commutator :
    commutator pairCreation pairAnnihilation = gradeCartan := by
  apply LinearMap.ext
  intro ψ
  ext i
  fin_cases i <;> simp [commutator, Module.End.mul_apply]

/-- Positive-root weight. -/
theorem gradeCartan_pairCreation_commutator :
    commutator gradeCartan pairCreation = (2 : ℂ) • pairCreation := by
  simpa [HasGrade] using grade_pairCreation

/-- Negative-root weight. -/
theorem gradeCartan_pairAnnihilation_commutator :
    commutator gradeCartan pairAnnihilation = (-2 : ℂ) • pairAnnihilation := by
  simpa [HasGrade] using grade_pairAnnihilation

/-- Exact finite five-grade packet generated by the two-mode CAR algebra. -/
theorem nuclear_two_mode_five_grade_packet :
    annihilationOne * creationOne + creationOne * annihilationOne = 1 ∧
      annihilationTwo * creationTwo + creationTwo * annihilationTwo = 1 ∧
      HasGrade (-2) pairAnnihilation ∧
      HasGrade (-1) annihilationOne ∧
      HasGrade 0 gradeCartan ∧
      HasGrade 1 creationOne ∧
      HasGrade 2 pairCreation ∧
      commutator pairCreation pairAnnihilation = gradeCartan ∧
      commutator gradeCartan pairCreation = (2 : ℂ) • pairCreation ∧
      commutator gradeCartan pairAnnihilation = (-2 : ℂ) • pairAnnihilation := by
  exact ⟨CAR_one, CAR_two, grade_pairAnnihilation,
    grade_annihilationOne, grade_gradeCartan, grade_creationOne,
    grade_pairCreation, pairCreation_pairAnnihilation_commutator,
    gradeCartan_pairCreation_commutator,
    gradeCartan_pairAnnihilation_commutator⟩

end InfoGeometry.Physics.NuclearTwoModeCARFiveGrade
