import Mathlib
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Lint.Vacuity
import InfoGeometry.Physics.NuclearExceptionalSymmetryAll

/-!
# Focused diagnostics for the nuclear exceptional/Artin/Galois lane
-/

#check InfoGeometry.Physics.NuclearChargeSpinSymmetry.QuantumNumberSymmetry.preservation_packet
#check InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.nuclear_five_grade_relation_packet
#check InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.g2_artin_spin_packet
#check InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.artin_conjugation_preserves_nuclear_nilpotent_shape
#check InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.g2_cyclotomic_sector_packet
#check InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.galois_preserves_nuclear_charge_spin

#print axioms InfoGeometry.Physics.NuclearChargeSpinSymmetry.QuantumNumberSymmetry.preservation_packet
#print axioms InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.nuclear_five_grade_relation_packet
#print axioms InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.g2_artin_spin_packet
#print axioms InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.artin_conjugation_preserves_nuclear_nilpotent_shape
#print axioms InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.g2_cyclotomic_sector_packet
#print axioms InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.galois_preserves_nuclear_charge_spin

#lint_vacuity_decl InfoGeometry.Physics.NuclearChargeSpinSymmetry.QuantumNumberSymmetry.preservation_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.nuclear_five_grade_relation_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.g2_artin_spin_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.artin_conjugation_preserves_nuclear_nilpotent_shape
#lint_vacuity_decl InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.g2_cyclotomic_sector_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearExceptionalArtinGaloisBridge.galois_preserves_nuclear_charge_spin

#audit_nuclear_exceptional_symmetry_logos
