import Mathlib
import InfoGeometry.Lint.Vacuity
import InfoGeometry.Physics.NuclearSuperGeometryAll

/-!
# Focused diagnostics for the nuclear supergeometry lane

This module is intentionally diagnostic.  It forces elaboration of the
capstone declarations, prints their axiom dependencies, and runs the
repository's vacuity linter on the main theorem surfaces.
-/

#check InfoGeometry.Physics.NuclearOperatorSuperSoloviev.totalParity_conjugation_formula
#check InfoGeometry.Physics.NuclearOperatorSuperSoloviev.invariant_of_even_diagonal_odd_offDiagonal
#check InfoGeometry.Physics.NuclearOperatorSuperSoloviev.InternalParity.superalgebra_multiplication_packet
#check InfoGeometry.Physics.NuclearZ2Superalgebra.superBracket_homogeneous
#check InfoGeometry.Physics.NuclearSuperSolovievPeirceBridge.PeirceCompatibleBlock.peirce_channel_packet
#check InfoGeometry.Physics.NuclearOperatorZornSuperSolovievBridge.diracSuperHamiltonian_invariant
#check InfoGeometry.Physics.NuclearFiniteNilpotentSoul.FiniteSoul.finite_soul_packet
#check InfoGeometry.Physics.NuclearExteriorGrassmannSoul.grassmann_one_form_packet
#check InfoGeometry.Physics.NuclearOperatorSchurComplement.soul_schur_packet
#check InfoGeometry.Physics.NuclearZornAssociatorOperatorBridge.leftOp_multiplicative_at_iff_associator_zero

#print axioms InfoGeometry.Physics.NuclearOperatorSuperSoloviev.totalParity_conjugation_formula
#print axioms InfoGeometry.Physics.NuclearOperatorSuperSoloviev.invariant_of_even_diagonal_odd_offDiagonal
#print axioms InfoGeometry.Physics.NuclearOperatorSuperSoloviev.InternalParity.superalgebra_multiplication_packet
#print axioms InfoGeometry.Physics.NuclearZ2Superalgebra.superBracket_homogeneous
#print axioms InfoGeometry.Physics.NuclearSuperSolovievPeirceBridge.PeirceCompatibleBlock.peirce_channel_packet
#print axioms InfoGeometry.Physics.NuclearOperatorZornSuperSolovievBridge.diracSuperHamiltonian_invariant
#print axioms InfoGeometry.Physics.NuclearFiniteNilpotentSoul.FiniteSoul.finite_soul_packet
#print axioms InfoGeometry.Physics.NuclearExteriorGrassmannSoul.grassmann_one_form_packet
#print axioms InfoGeometry.Physics.NuclearOperatorSchurComplement.soul_schur_packet
#print axioms InfoGeometry.Physics.NuclearZornAssociatorOperatorBridge.leftOp_multiplicative_at_iff_associator_zero

#lint_vacuity_decl InfoGeometry.Physics.NuclearOperatorSuperSoloviev.totalParity_conjugation_formula
#lint_vacuity_decl InfoGeometry.Physics.NuclearOperatorSuperSoloviev.invariant_of_even_diagonal_odd_offDiagonal
#lint_vacuity_decl InfoGeometry.Physics.NuclearOperatorSuperSoloviev.InternalParity.superalgebra_multiplication_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearZ2Superalgebra.superBracket_homogeneous
#lint_vacuity_decl InfoGeometry.Physics.NuclearSuperSolovievPeirceBridge.PeirceCompatibleBlock.peirce_channel_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearOperatorZornSuperSolovievBridge.diracSuperHamiltonian_invariant
#lint_vacuity_decl InfoGeometry.Physics.NuclearFiniteNilpotentSoul.FiniteSoul.finite_soul_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearExteriorGrassmannSoul.grassmann_one_form_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearOperatorSchurComplement.soul_schur_packet
#lint_vacuity_decl InfoGeometry.Physics.NuclearZornAssociatorOperatorBridge.leftOp_multiplicative_at_iff_associator_zero
