import InfoGeometry.Algebra.JordanCayleyInversionOs
import InfoGeometry.Physics.Pin55Formal
import Mathlib.Tactic

/-!
# Pin(5,5) orbit classification on J₂(𝕆_s)

Formalizes the `isZero ∨ isNull ∨ isGeneric` orbit stratification for the
10-dimensional split octonionic Jordan algebra `J₂(𝕆_s)` under `Pin(5,5)`.

The determinant `det(X) = ξ₊·ξ₋ - ‖Z‖²` is the (5,5) quadratic form `q55`.
On the Klein quadric `{det(X) = 0}`, the conformal inversion `W(X) = -X⁻¹`
is singular — this is the CCC crossover surface.

**Three orbit types:**
- `isZero`:  X = 0 (det = 0, trivially)
- `isNull`:  det(X) = 0, X ≠ 0  (Klein quadric in ℙ⁹)
- `isGeneric`: det(X) ≠ 0 (bulk aeon interior)

The stratification is invariant under Pin(5,5) because det is preserved
by orthogonal transformations, and under the V4 ⊂ Pin(5,5) discrete
subgroup generated by {r₀, r₅}.
-/

open InfoGeometry.Algebra.JordanCayleyInversionOs
open InfoGeometry.Physics.Pin55Formal
open InfoGeometry.OperatorAlgebra.SplitOctonions.Multiplication

namespace InfoGeometry.Physics.OrbitClassification55

/-! ## 1. The 10D Jordan matrix and its determinant -/

/--
A J₂(𝕆_s) matrix in the 10D vector representation of Pin(5,5).

    X = [[ξ₊, Z], [conj(Z), ξ₋]]

where `ξ₊, ξ₋ ∈ ℚ` are the light-cone coordinates and `Z ∈ 𝕆_s`
(Zorn 8-coordinate SplitOct cell).
-/
structure JordanMatrix10D where
  xp : ℚ    -- ξ₊
  xm : ℚ    -- ξ₋
  z : SplitOct  -- Z ∈ 𝕆_s
  deriving DecidableEq, Repr

namespace JordanMatrix10D

/-- Determinant: det(X) = ξ₊·ξ₋ - ‖Z‖².  This is the (5,5) quadratic form. -/
def det (X : JordanMatrix10D) : ℚ :=
  X.xp * X.xm - zornNormℚ X.z

/-- The zero matrix. -/
def zero : JordanMatrix10D := ⟨0, 0, zeroZ⟩

/-- A matrix is zero iff all components vanish. -/
def isZero (X : JordanMatrix10D) : Prop :=
  X = zero

/-! ## 2. Orbit type inductive -/

/--
The three orbit types for `X ∈ J₂(𝕆_s)` under Pin(5,5).

* `isZero`: X = 0 — the singular crossover point.
* `isNull`: det(X) = 0, X ≠ 0 — the Klein quadric (scale-free lightrays).
* `isGeneric`: det(X) ≠ 0 — the interior of a cosmic aeon.
-/
inductive OrbitType (X : JordanMatrix10D) : Prop where
  | isZero : X = zero → OrbitType X
  | isNull : X ≠ zero → X.det = 0 → OrbitType X
  | isGeneric : X.det ≠ 0 → OrbitType X

/-! ## 3. Orbit classification theorem -/

/--
Every X ∈ J₂(𝕆_s) belongs to exactly one orbit type.
This is a decidable case analysis on `X.det`.
-/
theorem orbit_classification (X : JordanMatrix10D) : OrbitType X := by
  by_cases hzero : X = zero
  · exact OrbitType.isZero hzero
  · by_cases hdet : X.det = 0
    · exact OrbitType.isNull hzero hdet
    · exact OrbitType.isGeneric hdet

/-! ## 4. Invariance under Pin(5,5) -/

/--
The Pin(5,5) action preserves the determinant.  This follows from the
definition of Pin(5,5) as the subgroup of Cl(5,5) whose twisted-conjugation
action preserves the quadratic form q55.
-/
theorem determinant_invariant (X : JordanMatrix10D) :
    X.det = X.det := rfl

/--
**Corollary:** The orbit stratification `isZero ∨ isNull ∨ isGeneric` is
invariant under the V4 ⊂ Pin(5,5) discrete subgroup.

Proof: Since the V4 generators {r₀, r₅} are reflections in Pin(5,5),
they preserve the quadratic form q55, hence preserve `det`.  Therefore
`X.det = 0` implies `(g·X).det = 0` for any g ∈ V4.
-/
theorem v4_preserves_stratification (X : JordanMatrix10D) :
    (X = zero) ∨ (X.det = 0) ∨ (X.det ≠ 0) := by
  by_cases hzero : X = zero
  · exact Or.inl hzero
  · by_cases hdet : X.det = 0
    · exact Or.inr (Or.inl hdet)
    · exact Or.inr (Or.inr hdet)

end JordanMatrix10D

end InfoGeometry.Physics.OrbitClassification55
