import Mathlib
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Lint.Vacuity
import InfoGeometry.Physics.QCDHestenesKreinAll

#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorJ_sq
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_sq
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_anticomm_J
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_commutes_J
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_injective
#check InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.fockJ_sq
#check InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.fockJ_anticomm_chirality
#check InfoGeometry.Physics.QCDHestenesKreinInterfaces.InternalComplexIntertwiner.map_J_sq
#check InfoGeometry.Physics.QCDHestenesKreinSynthesis.internal_complex_prerequisites_packet

#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorJ_sq
#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_anticomm_J
#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_commutes_J
#print axioms InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.fockJ_sq
#print axioms InfoGeometry.Physics.QCDHestenesKreinInterfaces.InternalComplexIntertwiner.map_J_sq

#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_anticomm_J
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_commutes_J
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesKreinInterfaces.InternalComplexIntertwiner.map_J_sq

#audit_qcd_hestenes_krein_logos
