import Mathlib
import InfoGeometry.Lint.Vacuity
import InfoGeometry.Physics.QCDHestenesKreinAll

#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorJ_sq
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_sq
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_anticomm_J
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_commutes_J
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_injective
#check InfoGeometry.Physics.QCDHestenesRealColorRepresentation.hestenes_real_color_packet
#check InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.fockJ_sq
#check InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.fockJ_anticomm_chirality
#check InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.two_sheet_and_fock_complex_axes_packet
#check InfoGeometry.Physics.QCDHestenesKreinInterfaces.InternalComplexIntertwiner.map_J_sq
#check InfoGeometry.Physics.QCDHestenesKreinSynthesis.hestenes_krein_parallel_packet
#check InfoGeometry.Physics.QCDHestenesKreinSynthesis.hestenes_zorn_furey_carrier_packet
#check InfoGeometry.Physics.QCDHestenesKreinSynthesis.internal_complex_prerequisites_packet

#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorJ_sq
#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_anticomm_J
#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_commutes_J
#print axioms InfoGeometry.Physics.QCDHestenesRealColorRepresentation.hestenes_real_color_packet
#print axioms InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.fockJ_sq
#print axioms InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.two_sheet_and_fock_complex_axes_packet
#print axioms InfoGeometry.Physics.QCDHestenesKreinInterfaces.InternalComplexIntertwiner.map_J_sq
#print axioms InfoGeometry.Physics.QCDHestenesKreinSynthesis.hestenes_krein_parallel_packet
#print axioms InfoGeometry.Physics.QCDHestenesKreinSynthesis.hestenes_zorn_furey_carrier_packet

#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorConj_anticomm_J
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesRealColorRepresentation.realColorAction_commutes_J
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesRealColorRepresentation.hestenes_real_color_packet
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesKreinFockPhaseBridge.two_sheet_and_fock_complex_axes_packet
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesKreinInterfaces.InternalComplexIntertwiner.map_J_sq
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesKreinSynthesis.hestenes_krein_parallel_packet
#lint_vacuity_decl InfoGeometry.Physics.QCDHestenesKreinSynthesis.hestenes_zorn_furey_carrier_packet

#audit_qcd_hestenes_krein_logos
