import Mathlib.Data.Complex.Basic
import Mathlib.Data.Fin.Basic

open Complex

namespace InfoGeometry.Physics.Relativity

/-- 
The Wick Rotation operator applied to a 4-vector (t, x, y, z).
Multiplies the 0-th coordinate (time) by the complex unit I.
-/
def wick_rotate (v : Fin 4 → ℂ) : Fin 4 → ℂ :=
  fun i => if i = 0 then I * v i else v i

/-- The Euclidean metric inner product generated by the V4 lattice. -/
def euclidean_inner (v w : Fin 4 → ℂ) : ℂ :=
  v 0 * w 0 + v 1 * w 1 + v 2 * w 2 + v 3 * w 3

/-- The Minkowski metric inner product defining relativistic SO(3,1) space. -/
def minkowski_inner (v w : Fin 4 → ℂ) : ℂ :=
  - (v 0 * w 0) + v 1 * w 1 + v 2 * w 2 + v 3 * w 3

/-- 
THEOREM: The Wick Rotation generates Relativistic Spacetime.
Applying the Wick rotation to the Euclidean V4 lattice perfectly yields 
the physical Minkowski metric of the SO(3,1) Lorentz group.
-/
theorem wick_euclidean_is_minkowski (v w : Fin 4 → ℂ) :
    euclidean_inner (wick_rotate v) (wick_rotate w) = minkowski_inner v w := by
  dsimp [euclidean_inner, minkowski_inner, wick_rotate]
  -- Evaluate the coordinate-wise rotation
  have h0_1 : (if (0 : Fin 4) = 0 then I * v 0 else v 0) = I * v 0 := if_pos rfl
  have h0_2 : (if (0 : Fin 4) = 0 then I * w 0 else w 0) = I * w 0 := if_pos rfl
  have h1_1 : (if (1 : Fin 4) = 0 then I * v 1 else v 1) = v 1 := rfl
  have h1_2 : (if (1 : Fin 4) = 0 then I * w 1 else w 1) = w 1 := rfl
  have h2_1 : (if (2 : Fin 4) = 0 then I * v 2 else v 2) = v 2 := rfl
  have h2_2 : (if (2 : Fin 4) = 0 then I * w 2 else w 2) = w 2 := rfl
  have h3_1 : (if (3 : Fin 4) = 0 then I * v 3 else v 3) = v 3 := rfl
  have h3_2 : (if (3 : Fin 4) = 0 then I * w 3 else w 3) = w 3 := rfl
  rw [h0_1, h0_2, h1_1, h1_2, h2_1, h2_2, h3_1, h3_2]
  calc
    (I * v 0) * (I * w 0) + v 1 * w 1 + v 2 * w 2 + v 3 * w 3
      = I * I * (v 0 * w 0) + v 1 * w 1 + v 2 * w 2 + v 3 * w 3 := by ring
    _ = -1 * (v 0 * w 0) + v 1 * w 1 + v 2 * w 2 + v 3 * w 3 := by rw [I_sq]
    _ = -(v 0 * w 0) + v 1 * w 1 + v 2 * w 2 + v 3 * w 3 := by ring

end InfoGeometry.Physics.Relativity
