import InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder

#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.baseA_mul_baseAMP
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.baseAMP_mul_baseA
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.baseA_isMoorePenrose
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1Z_eq
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1Border_mul_case1BorderMP
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1BorderMP_mul_case1Border
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1Border_isMoorePenrose
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1Schur_mul_case1SchurMP
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1SchurMP_mul_case1Schur
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1Schur_isMoorePenrose
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case3Border_mul_case3BorderMP
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case3BorderMP_mul_case3Border
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case3Border_isMoorePenrose
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case3Schur_mul_case3SchurMP
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case3SchurMP_mul_case3Schur
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case3Schur_isMoorePenrose
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.borderPermutation_sq_eq_one
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.borderPermutation_star_eq_self
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.unitConj_isMoorePenrose
#print axioms InfoGeometry.Canonical.Hartwig1976SVDMoorePenroseBorder.case1_conjugated_border_isMoorePenrose
