import InfoGeometry.Quantum.NoncommutativeFockBridge

#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_creation_add_annihilation
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_creation_annihilation_orthogonal
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_annihilation_kills_vacuum
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_creation_idempotent
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_annihilation_idempotent
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_annihilation_creation_orthogonal
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.cas_clifford_projector_idempotence_certificate
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.fock_clifford_projector_idempotence
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.noncommutative_sector_CAR
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.noncommutative_sector_CAR_transport
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.bogoliubov_maps_weylPlus
#print axioms InfoGeometry.Quantum.NoncommutativeFockBridge.bogoliubov_maps_weylMinus
