import InfoGeometry.Canonical.CampbellMeyerWeakDrazin

#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.Drazin_isWeakDrazin
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakNilpotentLane_sq_eq_zero
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakA_sq_readout
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakA_pow_three
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakA_cubic_eq_two_smul_square
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakDrazinInverse_isDrazin
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakDrazinInverse_isWeak
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakWildInverse_isWeak
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakWildInverse_ne_Drazin
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakWildInverse_not_commuting
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakPolynomialInverse_isWeak
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakPolynomialInverse_isCommuting
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakPolynomialInverse_ne_Drazin
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakSouriauFrame_formula_eq_polynomial
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakProjectiveInverse_isWeak
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakProjectiveInverse_BA_readout
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakProjectiveInverse_BA_idempotent
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakCommutingInverse_isCommuting
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weakPermutation_sq_eq_one
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.unitConj_mul
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.unitConj_pow
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.unitConj_isWeakDrazin
#print axioms InfoGeometry.Canonical.CampbellMeyerWeakDrazin.weak_conjugated_polynomial_inverse_isWeak
