import Mathlib
import InfoGeometry.Canonical.H3ZornPeirce0SO55

/-!
# Twelve-dimensional conformal/TKK generator spine over the Peirce-0 block

For the verified ten-dimensional split spin-factor metric `BQ10`, this file
constructs the standard null extension

`V12 = ℝ ⊕ V10 ⊕ ℝ`

with bilinear form

`B66((s,z,t),(s',z',t')) = s t' + t s' + BQ10(z,z')`.

Translation, special-conformal, dilation, and middle `BQ10`-skew generators are
bundled as real linear maps.  We prove that each lies in the infinitesimal
orthogonal algebra of `B66`, prove the basic 3-grading commutators, and prove
that the full graded parameterization is injective by evaluating at the two
null basis vectors and the middle `V10` slice.

This is a generator/injectivity theorem.  It deliberately does not identify
the Lie subalgebra generated by these maps with a separately constructed full
`so(6,6)` object until an explicit span/isomorphism theorem is supplied.
-/

noncomputable section

namespace InfoGeometry.Canonical.H3ZornPeirce0TKK66

open InfoGeometry.Canonical.H3ZornPeirce0QuadraticRepresentation
open InfoGeometry.Canonical.H3ZornPeirce0QuadraticHomothety
open InfoGeometry.Canonical.H3ZornPeirce0SO55

abbrev V10 := Minkowski10
abbrev End10 := V10 →ₗ[ℝ] V10

/-- Null extension `ℝ ⊕ V10 ⊕ ℝ`; products associate to the right. -/
abbrev V12 := ℝ × V10 × ℝ
abbrev End12 := V12 →ₗ[ℝ] V12

/-- Neutral conformal bilinear form on the null extension. -/
def B66 (x y : V12) : ℝ :=
  x.1 * y.2.2 + x.2.2 * y.1 + BQ10 x.2.1 y.2.1

@[simp] theorem B66_comm (x y : V12) : B66 x y = B66 y x := by
  rw [B66, B66, BQ10_comm]
  ring

/-- Infinitesimal orthogonality condition for the 12D conformal metric. -/
def InSO66 (T : End12) : Prop :=
  ∀ x y : V12, B66 (T x) y + B66 x (T y) = 0

/-- Translation / degree `-1` generator. -/
noncomputable def P (u : V10) : End12 where
  toFun := fun x =>
    ⟨-BQ10 u x.2.1, ⟨x.2.2 • u, 0⟩⟩
  map_add' x y := by
    ext <;> simp [BQ10_add_right, add_smul]
  map_smul' r x := by
    ext <;> simp [BQ10_smul_right, smul_smul]

/-- Special conformal / degree `+1` generator. -/
noncomputable def K (v : V10) : End12 where
  toFun := fun x =>
    ⟨0, ⟨x.1 • v, -BQ10 v x.2.1⟩⟩
  map_add' x y := by
    ext <;> simp [BQ10_add_right, add_smul]
  map_smul' r x := by
    ext <;> simp [BQ10_smul_right, smul_smul]

/-- Grading/dilatation generator in degree zero. -/
noncomputable def D (λ : ℝ) : End12 where
  toFun := fun x =>
    ⟨λ * x.1, ⟨0, -λ * x.2.2⟩⟩
  map_add' x y := by
    ext <;> simp <;> ring
  map_smul' r x := by
    ext <;> simp <;> ring

/-- Embed a ten-dimensional linear map in the middle block. -/
noncomputable def Mrot (M : End10) : End12 where
  toFun := fun x => ⟨0, ⟨M x.2.1, 0⟩⟩
  map_add' x y := by ext <;> simp
  map_smul' r x := by ext <;> simp

/-- Translations are infinitesimally orthogonal for `B66`. -/
theorem P_in_so66 (u : V10) : InSO66 (P u) := by
  intro x y
  simp only [InSO66, B66, P, LinearMap.coe_mk, AddHom.coe_mk]
  rw [BQ10_smul_left, BQ10_smul_right,
    BQ10_comm x.2.1 u]
  ring

/-- Special conformal generators are infinitesimally orthogonal for `B66`. -/
theorem K_in_so66 (v : V10) : InSO66 (K v) := by
  intro x y
  simp only [InSO66, B66, K, LinearMap.coe_mk, AddHom.coe_mk]
  rw [BQ10_smul_left, BQ10_smul_right,
    BQ10_comm x.2.1 v]
  ring

/-- Dilatations preserve the split null-pairing infinitesimally. -/
theorem D_in_so66 (λ : ℝ) : InSO66 (D λ) := by
  intro x y
  simp [InSO66, B66, D]
  ring

/-- A `BQ10`-skew middle-block map gives a `B66`-skew degree-zero map. -/
theorem Mrot_in_so66
    (M : End10) (hM : InSO55BQ M) : InSO66 (Mrot M) := by
  intro x y
  simp only [InSO66, B66, Mrot, LinearMap.coe_mk, AddHom.coe_mk,
    zero_mul, mul_zero, zero_add, add_zero]
  exact hM x.2.1 y.2.1

/-- Standard commutator of 12D endomorphisms. -/
def bracket (A B : End12) : End12 := A.comp B - B.comp A

/-- Degree `-1` is abelian. -/
theorem bracket_P_P (u v : V10) : bracket (P u) (P v) = 0 := by
  ext x
  simp [bracket, P, BQ10_smul_right, BQ10_comm u v]

/-- Degree `+1` is abelian. -/
theorem bracket_K_K (u v : V10) : bracket (K u) (K v) = 0 := by
  ext x
  simp [bracket, K, BQ10_smul_right, BQ10_comm u v]

/-- Dilatation grading on translations. -/
theorem bracket_D_P (λ : ℝ) (u : V10) :
    bracket (D λ) (P u) = P (λ • u) := by
  ext x
  simp [bracket, D, P, BQ10_smul_left, BQ10_smul_right]
  module

/-- Dilatation grading on special conformal generators. -/
theorem bracket_D_K (λ : ℝ) (v : V10) :
    bracket (D λ) (K v) = -K (λ • v) := by
  ext x
  simp [bracket, D, K, BQ10_smul_left, BQ10_smul_right]
  module

/-- The middle rotation appearing in the cross bracket.  It is a scalar
multiple of the already-proved elementary bivector generator. -/
def crossRotation (u v : V10) : End10 :=
  (-1 / 2 : ℝ) • bivectorGen u v

/-- The cross-bracket rotation is `BQ10`-skew. -/
theorem crossRotation_in_so55 (u v : V10) :
    InSO55BQ (crossRotation u v) := by
  intro x y
  simp [crossRotation, BQ10_smul_left, BQ10_smul_right]
  have h := bivectorGen_in_so55 u v x y
  linarith

/-- Readout of the cross rotation. -/
theorem crossRotation_apply (u v z : V10) :
    crossRotation u v z = BQ10 u z • v - BQ10 v z • u := by
  ext i
  simp [crossRotation, bivectorGen]
  ring

/-- TKK cross bracket: degree `-1` against degree `+1` lands in degree zero as
one dilatation plus one metric rotation. -/
theorem bracket_P_K (u v : V10) :
    bracket (P u) (K v) =
      D (-BQ10 u v) + Mrot (crossRotation u v) := by
  ext x
  simp [bracket, P, K, D, Mrot, crossRotation_apply,
    BQ10_smul_left, BQ10_smul_right, BQ10_comm]
  module

/-- Closure of the displayed cross-bracket inside the 12D metric-skew class. -/
theorem bracket_P_K_in_so66 (u v : V10) :
    InSO66 (bracket (P u) (K v)) := by
  rw [bracket_P_K]
  intro x y
  simp only [LinearMap.add_apply]
  rw [B66]
  have hD := D_in_so66 (-BQ10 u v) x y
  have hM := Mrot_in_so66 (crossRotation u v)
    (crossRotation_in_so55 u v) x y
  unfold B66 at hD hM ⊢
  simp only [Prod.fst_add, Prod.snd_add, add_mul, mul_add,
    BQ10_add_left, BQ10_add_right]
  linarith

/-! ## Linear independence of the three grading components -/

/-- The `BQ10`-skew middle maps form a real vector subspace of `End10`. -/
def so55BQSubmodule : Submodule ℝ End10 where
  carrier := { A | InSO55BQ A }
  zero_mem' := by
    intro x y
    simp [InSO55BQ]
  add_mem' := by
    intro A B hA hB x y
    simp only [LinearMap.add_apply, BQ10_add_left, BQ10_add_right]
    have h1 := hA x y
    have h2 := hB x y
    linarith
  smul_mem' := by
    intro r A hA x y
    simp only [LinearMap.smul_apply, BQ10_smul_left, BQ10_smul_right]
    have h := hA x y
    nlinarith

/-- The full TKK parameter module `g₋₁ ⊕ (ℝD ⊕ so(BQ10)) ⊕ g₊₁`. -/
abbrev TKKParams := V10 × ℝ × so55BQSubmodule × V10

/-- Linear parameterization by translation, dilation, middle rotation, and
special-conformal blocks. -/
noncomputable def tkkParamMap : TKKParams →ₗ[ℝ] End12 where
  toFun p := P p.1 + D p.2.1 + Mrot p.2.2.1.1 + K p.2.2.2
  map_add' p q := by
    ext x <;> simp [P, D, Mrot, K, BQ10_add_left]
  map_smul' r p := by
    ext x <;> simp [P, D, Mrot, K, BQ10_smul_left, smul_smul] <;> ring

/-- Test-vector uniqueness: if the sum of the four graded components vanishes,
then every parameter vanishes.  No nondegeneracy theorem for `BQ10` is needed:
the two null basis vectors read off `(λ,v)` and `(u,λ)`, and the middle slice
then reads off `A`. -/
theorem tkk_param_zero
    (u : V10) (λ : ℝ) (A : End10) (v : V10)
    (h_zero : P u + D λ + Mrot A + K v = 0) :
    u = 0 ∧ λ = 0 ∧ A = 0 ∧ v = 0 := by
  have h1 := LinearMap.congr_fun h_zero ((1 : ℝ), (0 : V10), (0 : ℝ))
  have h2 := LinearMap.congr_fun h_zero ((0 : ℝ), (0 : V10), (1 : ℝ))
  have hλ : λ = 0 := by
    have hs := congrArg (fun w : V12 => w.1) h1
    simpa [P, D, Mrot, K] using hs
  have hv : v = 0 := by
    have hz := congrArg (fun w : V12 => w.2.1) h1
    simpa [P, D, Mrot, K] using hz
  have hu : u = 0 := by
    have hz := congrArg (fun w : V12 => w.2.1) h2
    simpa [P, D, Mrot, K] using hz
  have hA : A = 0 := by
    ext z
    have hz := LinearMap.congr_fun h_zero ((0 : ℝ), z, (0 : ℝ))
    have hm := congrArg (fun w : V12 => w.2.1) hz
    simpa [P, D, Mrot, K, hu, hv, hλ] using hm
  exact ⟨hu, hλ, hA, hv⟩

/-- The 3-graded TKK parameterization is injective. -/
theorem tkkParamMap_injective : Function.Injective tkkParamMap := by
  rw [LinearMap.injective_iff_map_eq_zero]
  intro p hp
  rcases p with ⟨u, λ, A, v⟩
  change P u + D λ + Mrot A.1 + K v = 0 at hp
  have h := tkk_param_zero u λ A.1 v hp
  rcases h with ⟨hu, hλ, hA, hv⟩
  apply Prod.ext
  · exact hu
  · apply Prod.ext
    · exact hλ
    · apply Prod.ext
      · exact Subtype.ext hA
      · exact hv

/-- The null extension really has real dimension twelve. -/
theorem finrank_V12 : Module.finrank ℝ V12 = 12 := by
  simp [V12, finrank_minkowski10]

/-- Arithmetic dimension target for a full `so(6,6)` identification.  This is
only a dimension numeral, not an isomorphism theorem. -/
theorem so66_dimension_numeral : 12 * (12 - 1) / 2 = 66 := by
  norm_num

/-- Compact 3-grading generator packet. -/
theorem tkk66_generator_packet :
    Module.finrank ℝ V12 = 12 ∧
    Function.Injective tkkParamMap ∧
    (∀ u, InSO66 (P u)) ∧
    (∀ v, InSO66 (K v)) ∧
    (∀ λ, InSO66 (D λ)) ∧
    (∀ u v, bracket (P u) (P v) = 0) ∧
    (∀ u v, bracket (K u) (K v) = 0) := by
  exact ⟨finrank_V12, tkkParamMap_injective, P_in_so66, K_in_so66,
    D_in_so66, bracket_P_P, bracket_K_K⟩

end InfoGeometry.Canonical.H3ZornPeirce0TKK66
