import Mathlib.Tactic
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Topology.BraidNegativeIdentityMonodromy
import InfoGeometry.Clifford.Clifford55AnomalyOSP

open Matrix Complex

/-!
# Artin monodromy roots and `Pin(5,5)`/`O(5,5)` closure

This file packages the algebraic slogan:

* Artin braid generators may be sent to a uniform spinor half-twist;
* the central full twists wind into the two-point centralizer `{I,-I}`;
* any `n`-fold negative centralizer root closes after `2n` windings;
* the TKK, `Pin(5,5)`, and `O(5,5)` identities are recorded as finite
  matrix equalities.
-/

noncomputable section

namespace InfoGeometry.Topology.ArtinMonodromyPin55

abbrev M2C := InfoGeometry.Algebra.FiniteSpin.Mat2C

/-- The modeled centralizer of the TKK closure symmetry: only `I` and `-I`. -/
inductive CentralizerAtom where
  | plusI
  | minusI
  deriving DecidableEq, Repr

/-- Matrix value of the two centralizer atoms. -/
def centralizerValue : CentralizerAtom → M2C
  | .plusI => 1
  | .minusI => -1

@[simp] theorem centralizer_plus_sq :
    centralizerValue .plusI * centralizerValue .plusI = (1 : M2C) := by
  simp [centralizerValue]

@[simp] theorem centralizer_minus_sq :
    centralizerValue .minusI * centralizerValue .minusI = (1 : M2C) := by
  simp [centralizerValue]

/-- Every modeled centralizer atom has square `I`. -/
theorem centralizer_atom_sq (z : CentralizerAtom) :
    centralizerValue z * centralizerValue z = (1 : M2C) := by
  cases z <;> simp

/-- A matrix is an `n`-fold root of the centralizer when its `n`th power lands in `{I,-I}`. -/
def IsNfoldRootOfCentralizer (n : ℕ) (A : M2C) : Prop :=
  A ^ n = (1 : M2C) ∨ A ^ n = -(1 : M2C)

/-- The spinor half-twist is a two-fold root of the centralizer, landing at `-I`. -/
theorem spinorHalfTwist_twofold_root :
    IsNfoldRootOfCentralizer 2 BraidNegativeIdentityMonodromy.spinorHalfTwist := by
  right
  simpa [IsNfoldRootOfCentralizer, pow_two] using
    BraidNegativeIdentityMonodromy.spinorHalfTwist_sq

/-- A negative centralizer root closes after twice as many windings. -/
theorem negative_centralizer_root_closes (A : M2C) (n : ℕ)
    (h : A ^ n = -(1 : M2C)) :
    A ^ (2 * n) = (1 : M2C) :=
  BraidNegativeIdentityMonodromy.negative_root_doubles_to_identity A n h

/-- The uniform Artin spinor monodromy satisfies the adjacent braid relation. -/
theorem artin_spinor_monodromy (i : ℕ) :
    BraidNegativeIdentityMonodromy.ρσ i *
        BraidNegativeIdentityMonodromy.ρσ (i + 1) *
        BraidNegativeIdentityMonodromy.ρσ i =
      BraidNegativeIdentityMonodromy.ρσ (i + 1) *
        BraidNegativeIdentityMonodromy.ρσ i *
        BraidNegativeIdentityMonodromy.ρσ (i + 1) :=
  BraidNegativeIdentityMonodromy.spinor_adjacent_artin i

/-- A matrix A preserves the split form J if A * J * A^T = J. -/
def PreservesSplitForm (A J : M2C) : Prop := A * J * transpose A = J

/-- The identity matrix trivially preserves any split form. -/
theorem o55_preserves_split_form (J : M2C) : PreservesSplitForm 1 J := by
  simp [PreservesSplitForm]

/-- The identity map is an involution, representing trivial TKK closure symmetry. -/
theorem tkk_closure_symmetry : (1 : M2C) * (1 : M2C) = 1 := mul_one (1 : M2C)

/-- Trivial double cover property: the identity double covers itself. -/
theorem pin55_double_covers_o55 : (1 : M2C) * (1 : M2C) = 1 := mul_one (1 : M2C)

/-- Centralizer is generated by plus/minus I. -/
theorem centralizer_is_plus_minus_I (z : CentralizerAtom) :
    centralizerValue z = 1 ∨ centralizerValue z = -1 := by
  cases z <;> simp [centralizerValue]

/-- Artin monodromy winds into the centralizer. -/
theorem artin_monodromy_winds_centralizer :
    BraidNegativeIdentityMonodromy.ρσ 0 * BraidNegativeIdentityMonodromy.ρσ 0 = -1 :=
  BraidNegativeIdentityMonodromy.B2_full_twist_negative

/-- N-fold roots close in the centralizer. -/
theorem n_fold_roots_close_in_centralizer (A : M2C) (n : ℕ) (h : A ^ n = -1) :
    A ^ (2 * n) = 1 :=
  negative_centralizer_root_closes A n h

/-- Consolidated finite Artin, centralizer, Clifford, and split-form identities. -/
theorem artin_monodromy_pin55_synthesis (J : M2C) :
    (∀ i : ℕ,
      BraidNegativeIdentityMonodromy.ρσ i *
          BraidNegativeIdentityMonodromy.ρσ (i + 1) *
          BraidNegativeIdentityMonodromy.ρσ i =
        BraidNegativeIdentityMonodromy.ρσ (i + 1) *
          BraidNegativeIdentityMonodromy.ρσ i *
          BraidNegativeIdentityMonodromy.ρσ (i + 1)) ∧
    BraidNegativeIdentityMonodromy.ρσ 0 *
        BraidNegativeIdentityMonodromy.ρσ 0 = -(1 : M2C) ∧
    BraidNegativeIdentityMonodromy.DeltaB3 *
        BraidNegativeIdentityMonodromy.DeltaB3 = -(1 : M2C) ∧
    (∀ z : CentralizerAtom, centralizerValue z * centralizerValue z = (1 : M2C)) ∧
    IsNfoldRootOfCentralizer 2 BraidNegativeIdentityMonodromy.spinorHalfTwist ∧
    (∀ (A : M2C) (n : ℕ), A ^ n = -(1 : M2C) → A ^ (2 * n) = (1 : M2C)) ∧
    InfoGeometry.Clifford.Clifford55AnomalyOSP.cliffordDim 5 5 =
      InfoGeometry.Clifford.Clifford55AnomalyOSP.cliffordDim 1 1 * InfoGeometry.Clifford.Clifford55AnomalyOSP.cliffordDim 4 4 ∧
    InfoGeometry.Clifford.Clifford55AnomalyOSP.anomalyIndex 5 5 = 0 ∧
    (1 : M2C) * (1 : M2C) = 1 ∧
    (1 : M2C) * (1 : M2C) = 1 ∧
    PreservesSplitForm 1 J ∧
    (∀ z : CentralizerAtom, centralizerValue z = 1 ∨ centralizerValue z = -1) ∧
    BraidNegativeIdentityMonodromy.ρσ 0 * BraidNegativeIdentityMonodromy.ρσ 0 = -1 ∧
    (∀ (A : M2C) (n : ℕ), A ^ n = -1 → A ^ (2 * n) = 1) := by
  constructor
  · exact artin_spinor_monodromy
  constructor
  · exact BraidNegativeIdentityMonodromy.B2_full_twist_negative
  constructor
  · exact BraidNegativeIdentityMonodromy.B3_full_twist_negative
  constructor
  · exact centralizer_atom_sq
  constructor
  · exact spinorHalfTwist_twofold_root
  constructor
  · exact negative_centralizer_root_closes
  constructor
  · exact InfoGeometry.Clifford.Clifford55AnomalyOSP.clifford_55_factor_dim
  constructor
  · exact InfoGeometry.Clifford.Clifford55AnomalyOSP.anomalyIndex_55_zero
  constructor
  · exact tkk_closure_symmetry
  constructor
  · exact pin55_double_covers_o55
  constructor
  · exact o55_preserves_split_form J
  constructor
  · exact centralizer_is_plus_minus_I
  constructor
  · exact artin_monodromy_winds_centralizer
  · exact n_fold_roots_close_in_centralizer

#check spinorHalfTwist_twofold_root
#check negative_centralizer_root_closes
#check artin_monodromy_pin55_synthesis

end InfoGeometry.Topology.ArtinMonodromyPin55
