import Mathlib.Topology.Algebra.Module.FiniteDimension
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Topology.Algebra.Group.Basic
import InfoGeometry.Clifford.Cl55RealSplitPin
import InfoGeometry.Clifford.Cl55PinPlusMinusNative
import InfoGeometry.Clifford.Cl55SpinorAlgebraEquiv

/-!
# Induced topological Pin groups in signature `(5,5)`

This file gives the two sign conventions genuine topological-group carriers.
The topology is the one induced from the finite-dimensional real Clifford
algebra and its unit group; no discrete topology and no unproved Lie-group
identification is introduced.

`PinPlus55` is the repository's real split Pin subgroup generated by
normalised vectors of square `+1` or `-1`.  `PinMinus55` is the corresponding
subgroup for the opposite quadratic form `-Q55`.  These are kept as separate
Clifford presentations.  An isomorphism between them would require an
explicit isometry of quadratic spaces and is not definitionally available.
-/

noncomputable section

namespace InfoGeometry.Topology.Pin55TopologicalGroups

open CliffordAlgebra
open InfoGeometry.Clifford.Clifford55
open InfoGeometry.Clifford.Clifford55PinPlusMinusNative

abbrev PinPlus55 := realSplitPin55

abbrev Cl55Opposite := CliffordAlgebra Q55Opposite

noncomputable def oppositeToPlusIsometry :
    QuadraticMap.IsometryEquiv Q55Opposite Q55 where
  toLinearEquiv :=
    { toFun := swap55
      invFun := swap55
      left_inv := by intro v; ext <;> rfl
      right_inv := by intro v; ext <;> rfl
      map_add' := by intro v w; exact map_add swap55 v w
      map_smul' := by intro c v; exact map_smul swap55 c v }
  map_app' v := by
    simpa [Q55Opposite_apply] using Q55_swap_eq_neg v

noncomputable def oppositeToPlus :
    Cl55Opposite ≃ₐ[ℝ] CliffordAlgebra Q55 :=
  CliffordAlgebra.equivOfIsometry oppositeToPlusIsometry

noncomputable def oppositeUnitsToPlus :
    Cl55Oppositeˣ →* (CliffordAlgebra Q55)ˣ :=
  Units.map oppositeToPlus.toRingEquiv.toMonoidHom

noncomputable def PinMinus55 : Subgroup Cl55Oppositeˣ :=
  Subgroup.comap oppositeUnitsToPlus realSplitPin55

noncomputable instance : FiniteDimensional ℝ (CliffordAlgebra Q55) :=
  LinearEquiv.finiteDimensional
    InfoGeometry.Clifford.Clifford55.cl55SpinorAlgEquiv.toLinearEquiv.symm

noncomputable instance : FiniteDimensional ℝ Cl55Opposite :=
  LinearEquiv.finiteDimensional oppositeToPlus.toLinearEquiv.symm

instance : TopologicalSpace (CliffordAlgebra Q55) :=
  moduleTopology ℝ (CliffordAlgebra Q55)

instance : IsTopologicalRing (CliffordAlgebra Q55) := by
  apply IsModuleTopology.isTopologicalRing ℝ

instance : IsModuleTopology ℝ (CliffordAlgebra Q55) :=
  ⟨rfl⟩

instance : T2Space (CliffordAlgebra Q55) :=
  T2Space.of_injective_continuous cl55SpinorAlgEquiv.injective
    (IsModuleTopology.continuous_of_linearMap
      cl55SpinorAlgEquiv.toLinearEquiv.toLinearMap)

instance : IsTopologicalGroup (CliffordAlgebra Q55)ˣ :=
  inferInstance

instance : IsTopologicalGroup PinPlus55 :=
  inferInstance

instance : TopologicalSpace Cl55Opposite :=
  moduleTopology ℝ Cl55Opposite

instance : IsTopologicalRing Cl55Opposite := by
  apply IsModuleTopology.isTopologicalRing ℝ

instance : IsModuleTopology ℝ Cl55Opposite :=
  ⟨rfl⟩

instance : T2Space Cl55Opposite :=
  T2Space.of_injective_continuous oppositeToPlus.injective
    (IsModuleTopology.continuous_of_linearMap oppositeToPlus.toLinearMap)

instance : IsTopologicalGroup Cl55Oppositeˣ :=
  inferInstance

instance : IsTopologicalGroup PinMinus55 :=
  Topology.IsInducing.topologicalGroup PinMinus55.subtype ⟨rfl⟩

theorem pinPlus55_is_topological_group : IsTopologicalGroup PinPlus55 := by
  infer_instance

theorem pinMinus55_is_topological_group : IsTopologicalGroup PinMinus55 := by
  infer_instance

@[simp] theorem pinMinus55_one_mem :
    (1 : Cl55Oppositeˣ) ∈ PinMinus55 := by
  exact Submonoid.one_mem _

/-! ## Carrier compatibility

The two Pin carriers are subgroups of units in different Clifford algebras.
They are therefore not definitionally equal.  The quadratic-form isometry
above nevertheless induces a genuine group equivalence between them. -/

noncomputable def pinMinus55ToPlus : PinMinus55 →* PinPlus55 where
  toFun g :=
    ⟨oppositeUnitsToPlus (g : Cl55Oppositeˣ), g.property⟩
  map_one' := by
    apply Subtype.ext
    simp
  map_mul' g h := by
    apply Subtype.ext
    simp

noncomputable def pinPlus55ToMinus : PinPlus55 →* PinMinus55 where
  toFun g :=
    ⟨Units.map oppositeToPlus.symm.toRingEquiv.toMonoidHom
        (g : (CliffordAlgebra Q55)ˣ), by
      have hmap :
          oppositeUnitsToPlus
              (Units.map oppositeToPlus.symm.toRingEquiv.toMonoidHom
                (g : (CliffordAlgebra Q55)ˣ)) =
            (g : (CliffordAlgebra Q55)ˣ) := by
        apply Units.ext
        simp only [oppositeUnitsToPlus, Units.coe_map]
        exact oppositeToPlus.apply_symm_apply _
      change oppositeUnitsToPlus
          (Units.map oppositeToPlus.symm.toRingEquiv.toMonoidHom
            (g : (CliffordAlgebra Q55)ˣ)) ∈ realSplitPin55
      rw [hmap]
      exact g.property⟩
  map_one' := by
    apply Subtype.ext
    simp [oppositeUnitsToPlus]
  map_mul' g h := by
    apply Subtype.ext
    simp [oppositeUnitsToPlus]

theorem pinMinus55ToPlus_coe (g : PinMinus55) :
    ((pinMinus55ToPlus g : PinPlus55) : (CliffordAlgebra Q55)ˣ) =
      oppositeUnitsToPlus (g : Cl55Oppositeˣ) :=
  rfl

theorem pinPlus55ToMinus_coe (g : PinPlus55) :
    ((pinPlus55ToMinus g : PinMinus55) : Cl55Oppositeˣ) =
      Units.map oppositeToPlus.symm.toRingEquiv.toMonoidHom
        (g : (CliffordAlgebra Q55)ˣ) :=
  rfl

theorem pinMinus55ToPlus_leftInverse (g : PinMinus55) :
    pinPlus55ToMinus (pinMinus55ToPlus g) = g := by
  apply Subtype.ext
  apply Units.ext
  simp only [pinMinus55ToPlus, pinPlus55ToMinus, oppositeUnitsToPlus]
  exact oppositeToPlus.symm_apply_apply _

theorem pinMinus55ToPlus_rightInverse (g : PinPlus55) :
    pinMinus55ToPlus (pinPlus55ToMinus g) = g := by
  apply Subtype.ext
  apply Units.ext
  simp only [pinMinus55ToPlus, pinPlus55ToMinus, oppositeUnitsToPlus]
  exact oppositeToPlus.apply_symm_apply _

noncomputable def pinMinus55EquivPlus : PinMinus55 ≃* PinPlus55 :=
  MulEquiv.ofBijective pinMinus55ToPlus
    ⟨fun g h hgh => by
      rw [← pinMinus55ToPlus_leftInverse g, ← pinMinus55ToPlus_leftInverse h,
        hgh],
      fun g => ⟨pinPlus55ToMinus g, pinMinus55ToPlus_rightInverse g⟩⟩

theorem pinMinus55EquivPlus_apply (g : PinMinus55) :
    pinMinus55EquivPlus g = pinMinus55ToPlus g :=
  rfl

end InfoGeometry.Topology.Pin55TopologicalGroups
