import InfoGeometry.Geometry.MobiusInfinitesimal
import InfoGeometry.Canonical.MatrixDetExpTraceJacobi
import InfoGeometry.Clifford.DiscreteMoebiusGroup
import InfoGeometry.Physics.SouriauEntropyFoliation
import Mathlib.Analysis.Complex.RealDeriv
import Mathlib.Analysis.InnerProductSpace.Calculus
import Mathlib.Analysis.SpecialFunctions.Complex.LogDeriv

/-!
# Thermodynamic `sl₂` Möbius flow

This module maps three local thermodynamic first-variation channels to the canonical
trace-zero Möbius generator. Its matrix exponential is the finite one-parameter flow;
the induced affine-chart infinitesimal orbit has the canonical Riccati vector field.
-/

noncomputable section

namespace ThermodynamicSL2MobiusFlow

open InfoGeometry.Geometry
open InfoGeometry.Canonical.MatrixDetExpTraceJacobi
open InfoGeometry.Physics.SouriauEntropyFoliation
open scoped RealInnerProductSpace

/-- Branch-free derivative of the real logarithmic norm of a nonvanishing complex curve. -/
theorem hasDerivAt_real_log_norm
    {f : ℝ → ℂ} {f' : ℂ} {t : ℝ}
    (hf : HasDerivAt f f' t) (hne : f t ≠ 0) :
    HasDerivAt (fun s => Real.log ‖f s‖) (f' / f t).re t := by
  have hsq := hf.norm_sq
  have hnorm : ‖f t‖ ≠ 0 := norm_ne_zero_iff.mpr hne
  have hlog := hsq.log (pow_ne_zero 2 hnorm)
  have hhalf := hlog.const_mul (1 / 2 : ℝ)
  convert hhalf using 1
  · funext s
    rw [Real.log_pow]
    ring
  · rw [Complex.div_re]
    simp only [Complex.normSq_eq_norm_sq]
    field_simp [hnorm]
    rw [Complex.inner]
    simp only [Complex.mul_re, Complex.conj_re, Complex.conj_im]
    ring

/-- Assemble translation, dilation, and special-conformal thermodynamic forces. -/
def thermodynamicSL2Generator
    (translation dilation specialConformal : ℝ) : sl2C :=
  ⟨(dilation : ℂ), (translation : ℂ), (specialConformal : ℂ)⟩

/-- Matrix readback of the thermodynamic `sl₂` generator. -/
theorem thermodynamicSL2Generator_matrix
    (translation dilation specialConformal : ℝ) :
    (thermodynamicSL2Generator translation dilation specialConformal).matrix =
      !![(dilation : ℂ), (translation : ℂ);
         (specialConformal : ℂ), -(dilation : ℂ)] := by
  rfl

/-- Canonical Riccati vector field driven by the three thermodynamic channels. -/
def thermodynamicSL2VectorField
    (translation dilation specialConformal : ℝ) (z : ℂ) : ℂ :=
  (thermodynamicSL2Generator translation dilation specialConformal).vectorField z

/-- Explicit `P + D + K` decomposition of the thermodynamic Möbius velocity. -/
theorem thermodynamicSL2VectorField_eq
    (translation dilation specialConformal : ℝ) (z : ℂ) :
    thermodynamicSL2VectorField translation dilation specialConformal z =
      -(specialConformal : ℂ) * z ^ 2 + 2 * (dilation : ℂ) * z + translation := by
  rfl

/-- Finite one-parameter Möbius matrix flow generated by the thermodynamic `sl₂` element. -/
def thermodynamicSL2MatrixFlow
    (translation dilation specialConformal : ℝ) (t : ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  matrixExpFlow (thermodynamicSL2Generator translation dilation specialConformal).matrix t

/-- The finite matrix flow solves the constant-generator matrix ODE. -/
theorem hasDerivAt_thermodynamicSL2MatrixFlow
    (translation dilation specialConformal : ℝ) (t : ℂ) :
    HasDerivAt (thermodynamicSL2MatrixFlow translation dilation specialConformal)
      ((thermodynamicSL2Generator translation dilation specialConformal).matrix *
        thermodynamicSL2MatrixFlow translation dilation specialConformal t) t := by
  exact hasDerivAt_matrixExpFlow_left
    (thermodynamicSL2Generator translation dilation specialConformal).matrix t

/-- Trace-zero generation forces the finite matrix flow to have determinant one. -/
theorem thermodynamicSL2MatrixFlow_det
    (translation dilation specialConformal : ℝ) (t : ℂ) :
    Matrix.det (thermodynamicSL2MatrixFlow translation dilation specialConformal t) = 1 := by
  rw [show thermodynamicSL2MatrixFlow translation dilation specialConformal t =
      matrixExpFlow (thermodynamicSL2Generator translation dilation specialConformal).matrix t by rfl]
  rw [det_matrixExpFlow_eq_exp_trace_mul]
  simp [Matrix.trace, thermodynamicSL2Generator, sl2C.matrix]

/-- The thermodynamic exponential flow starts at the identity matrix. -/
theorem thermodynamicSL2MatrixFlow_zero
    (translation dilation specialConformal : ℝ) :
    thermodynamicSL2MatrixFlow translation dilation specialConformal 0 = 1 := by
  simp [thermodynamicSL2MatrixFlow, matrixExpFlow]

/-- The thermodynamic exponential matrices form an additive one-parameter group. -/
theorem thermodynamicSL2MatrixFlow_add
    (translation dilation specialConformal : ℝ) (s t : ℂ) :
    thermodynamicSL2MatrixFlow translation dilation specialConformal (s + t) =
      thermodynamicSL2MatrixFlow translation dilation specialConformal s *
        thermodynamicSL2MatrixFlow translation dilation specialConformal t := by
  let A := (thermodynamicSL2Generator translation dilation specialConformal).matrix
  have hcomm : Commute (s • A) (t • A) :=
    ((Commute.refl A).smul_left s).smul_right t
  simpa [thermodynamicSL2MatrixFlow, matrixExpFlow, A, add_smul] using
    (Matrix.exp_add_of_commute (s • A) (t • A) hcomm)

/-- Matrix multiplication agrees with nested affine Möbius action away from the inner pole. -/
theorem moebiusAction_mul_of_den_ne_zero
    (M N : Matrix (Fin 2) (Fin 2) ℂ) (z : ℂ)
    (hden : N 1 0 * z + N 1 1 ≠ 0) :
    InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction (M * N) z =
      InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction M
        (InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction N z) := by
  unfold InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction
  simp only [Matrix.mul_apply, Fin.sum_univ_two]
  field_simp [hden]
  ring

/-- Quadratic PGL₂ Riccati vector field associated to a `2 × 2` infinitesimal matrix. -/
def pgl2RiccatiVectorField (A : Matrix (Fin 2) (Fin 2) ℂ) (z : ℂ) : ℂ :=
  A 0 1 + (A 0 0 - A 1 1) * z - A 1 0 * z ^ 2

/-- First-order PGL₂ fractional-linear chart action of `I + τ A`. -/
def pgl2InfinitesimalAction (A : Matrix (Fin 2) (Fin 2) ℂ) (z τ : ℂ) : ℂ :=
  ((1 + τ * A 0 0) * z + τ * A 0 1) /
    (τ * A 1 0 * z + (1 + τ * A 1 1))

/-- Trace-zero matrices recover the `sl₂` infinitesimal vector field from the PGL₂ Riccati field. -/
theorem pgl2RiccatiVectorField_sl2_matrix (A : sl2C) (z : ℂ) :
    pgl2RiccatiVectorField A.matrix z = A.vectorField z := by
  simp [pgl2RiccatiVectorField, sl2C.matrix, sl2C.vectorField]
  ring

/-- The thermodynamic `sl₂` vector field is the PGL₂ Riccati field of its matrix. -/
theorem pgl2RiccatiVectorField_thermodynamicSL2Generator
    (translation dilation specialConformal : ℝ) (z : ℂ) :
    pgl2RiccatiVectorField
        (thermodynamicSL2Generator translation dilation specialConformal).matrix z =
      thermodynamicSL2VectorField translation dilation specialConformal z := by
  exact pgl2RiccatiVectorField_sl2_matrix
    (thermodynamicSL2Generator translation dilation specialConformal) z

/-- The PGL₂ first-order chart action differentiates to the Riccati vector field. -/
theorem hasDerivAt_pgl2InfinitesimalAction_zero
    (A : Matrix (Fin 2) (Fin 2) ℂ) (z : ℂ) :
    HasDerivAt (pgl2InfinitesimalAction A z)
      (pgl2RiccatiVectorField A z) 0 := by
  let a := A 0 0
  let b := A 0 1
  let c := A 1 0
  let d := A 1 1
  have hnum0 :
      HasDerivAt (fun τ : ℂ => z + τ * (a * z + b)) (a * z + b) 0 := by
    simpa only [Pi.add_apply, id_eq, zero_add, one_mul] using
      ((hasDerivAt_const (x := (0 : ℂ)) (c := z)).add
        ((hasDerivAt_id (0 : ℂ)).mul_const (a * z + b)))
  have hnum :
      HasDerivAt (fun τ : ℂ => (1 + τ * a) * z + τ * b) (a * z + b) 0 := by
    convert hnum0 using 1
    funext τ
    ring
  have hden0 :
      HasDerivAt (fun τ : ℂ => 1 + τ * (c * z + d)) (c * z + d) 0 := by
    simpa only [Pi.add_apply, id_eq, zero_add, one_mul] using
      ((hasDerivAt_const (x := (0 : ℂ)) (c := (1 : ℂ))).add
        ((hasDerivAt_id (0 : ℂ)).mul_const (c * z + d)))
  have hden :
      HasDerivAt (fun τ : ℂ => τ * c * z + (1 + τ * d)) (c * z + d) 0 := by
    convert hden0 using 1
    funext τ
    ring
  have hden_ne : (fun τ : ℂ => τ * c * z + (1 + τ * d)) 0 ≠ 0 := by
    norm_num
  have h := hnum.div hden hden_ne
  have h' : HasDerivAt (pgl2InfinitesimalAction A z)
      (((a * z + b) * (0 * c * z + (1 + 0 * d)) -
          ((1 + 0 * a) * z + 0 * b) * (c * z + d)) /
        (0 * c * z + (1 + 0 * d)) ^ 2) 0 := by
    convert h using 1
  convert h' using 1
  simp [pgl2RiccatiVectorField, a, b, c, d]
  ring

/--
Affine-chart orbit of the first-order matrix `I + tA`. This owner exposes the
infinitesimal action without pretending that a truncated matrix is the finite flow.
-/
def thermodynamicSL2InfinitesimalOrbit
    (translation dilation specialConformal : ℝ) (z t : ℂ) : ℂ :=
  (z + t * ((dilation : ℂ) * z + translation)) /
    (1 + t * ((specialConformal : ℂ) * z - dilation))

/-- The derivative of the Möbius chart orbit is the thermodynamic Riccati field. -/
theorem hasDerivAt_thermodynamicSL2InfinitesimalOrbit
    (translation dilation specialConformal : ℝ) (z : ℂ) :
    HasDerivAt (thermodynamicSL2InfinitesimalOrbit translation dilation specialConformal z)
      (thermodynamicSL2VectorField translation dilation specialConformal z) 0 := by
  unfold thermodynamicSL2InfinitesimalOrbit thermodynamicSL2VectorField
  convert
    (((hasDerivAt_const (x := (0 : ℂ)) (c := z)).add
        ((hasDerivAt_id (𝕜 := ℂ) 0).mul_const
          ((dilation : ℂ) * z + translation))).div
      ((hasDerivAt_const (x := (0 : ℂ)) (c := 1)).add
        ((hasDerivAt_id (𝕜 := ℂ) 0).mul_const
          ((specialConformal : ℂ) * z - dilation))) (by norm_num)) using 1 <;>
    simp [sl2C.vectorField, thermodynamicSL2Generator] <;>
    ring

/-- The translation-only sector recovers the parabolic constant vector field. -/
theorem thermodynamicSL2_parabolic_recovery (translation : ℝ) (z : ℂ) :
    thermodynamicSL2VectorField translation 0 0 z = translation := by
  simp [thermodynamicSL2VectorField_eq]

/-! ## Souriau-derived `P/D/K` channels -/

/-- Raw local variations entering one Souriau free-entropy force channel. -/
structure SouriauVariation where
  dMassieu : ℝ
  dKL : ℝ
  dIncidenceFriction : ℝ
  dFreeEnergy : ℝ
  lambdaIncidence : ℝ
  lambdaFreeEnergy : ℝ

namespace SouriauVariation

/-- Native Souriau free-entropy first variation carried by the raw local data. -/
def force (v : SouriauVariation) : ℝ :=
  InfoGeometry.Physics.SouriauMassieuPlanckFunctional.souriauFreeEntropyFirstVariation
    v.dMassieu v.dKL v.dIncidenceFriction v.dFreeEnergy
    v.lambdaIncidence v.lambdaFreeEnergy

theorem force_eq (v : SouriauVariation) :
    v.force = v.dMassieu - v.dKL -
      v.lambdaIncidence * v.dIncidenceFriction -
      v.lambdaFreeEnergy * v.dFreeEnergy := by
  rfl

end SouriauVariation

/-- Three Souriau variation channels sourcing translation, dilation, and special conformal flow. -/
structure ThermodynamicSL2Variation where
  translation : SouriauVariation
  dilation : SouriauVariation
  specialConformal : SouriauVariation

namespace ThermodynamicSL2Variation

/-- Canonical trace-zero generator sourced by the three Souriau first variations. -/
def generator (v : ThermodynamicSL2Variation) : sl2C :=
  thermodynamicSL2Generator v.translation.force v.dilation.force v.specialConformal.force

/-- Riccati field sourced by the three Souriau first variations. -/
def vectorField (v : ThermodynamicSL2Variation) (z : ℂ) : ℂ :=
  thermodynamicSL2VectorField v.translation.force v.dilation.force
    v.specialConformal.force z

/-- Explicit Souriau-driven `P + D + K` Riccati velocity. -/
theorem vectorField_eq (v : ThermodynamicSL2Variation) (z : ℂ) :
    v.vectorField z = -(v.specialConformal.force : ℂ) * z ^ 2 +
      2 * (v.dilation.force : ℂ) * z + v.translation.force := by
  exact thermodynamicSL2VectorField_eq v.translation.force v.dilation.force
    v.specialConformal.force z

/-- Determinant-one exponential flow sourced by the three Souriau channels. -/
def matrixFlow (v : ThermodynamicSL2Variation) (t : ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  thermodynamicSL2MatrixFlow v.translation.force v.dilation.force
    v.specialConformal.force t

theorem matrixFlow_det (v : ThermodynamicSL2Variation) (t : ℂ) :
    Matrix.det (v.matrixFlow t) = 1 := by
  exact thermodynamicSL2MatrixFlow_det v.translation.force v.dilation.force
    v.specialConformal.force t

theorem matrixFlow_zero (v : ThermodynamicSL2Variation) : v.matrixFlow 0 = 1 := by
  exact thermodynamicSL2MatrixFlow_zero v.translation.force v.dilation.force
    v.specialConformal.force

theorem matrixFlow_add (v : ThermodynamicSL2Variation) (s t : ℂ) :
    v.matrixFlow (s + t) = v.matrixFlow s * v.matrixFlow t := by
  exact thermodynamicSL2MatrixFlow_add v.translation.force v.dilation.force
    v.specialConformal.force s t

/-- Actual affine-chart Möbius orbit of the determinant-one exponential flow. -/
def finiteOrbit (v : ThermodynamicSL2Variation) (t z : ℂ) : ℂ :=
  InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction (v.matrixFlow t) z

theorem finiteOrbit_zero (v : ThermodynamicSL2Variation) (z : ℂ) :
    v.finiteOrbit 0 z = z := by
  rw [finiteOrbit, matrixFlow_zero]
  simp [InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction]

/-- Affine-chart denominator of the finite determinant-one Möbius orbit. -/
def finiteOrbitDenominator (v : ThermodynamicSL2Variation) (t z : ℂ) : ℂ :=
  v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1

/-- Denominators multiply under time composition whenever the inner chart is valid. -/
theorem finiteOrbitDenominator_add
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (ht : v.finiteOrbitDenominator t z ≠ 0) :
    v.finiteOrbitDenominator (s + t) z =
      v.finiteOrbitDenominator s (v.finiteOrbit t z) *
        v.finiteOrbitDenominator t z := by
  simp only [finiteOrbitDenominator] at ht
  unfold finiteOrbitDenominator finiteOrbit
  rw [matrixFlow_add]
  unfold InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction
  simp only [Matrix.mul_apply, Fin.sum_univ_two]
  field_simp [ht]
  ring

/-- Nested affine-chart validity propagates to the composite time. -/
theorem finiteOrbit_chart_add
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (ht : v.finiteOrbitDenominator t z ≠ 0)
    (hs : v.finiteOrbitDenominator s (v.finiteOrbit t z) ≠ 0) :
    v.finiteOrbitDenominator (s + t) z ≠ 0 := by
  rw [v.finiteOrbitDenominator_add s t z ht]
  exact mul_ne_zero hs ht

/-- The finite Souriau-driven affine orbit composes away from the inner chart pole. -/
theorem finiteOrbit_add (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    v.finiteOrbit (s + t) z = v.finiteOrbit s (v.finiteOrbit t z) := by
  rw [finiteOrbit, matrixFlow_add]
  exact moebiusAction_mul_of_den_ne_zero (v.matrixFlow s) (v.matrixFlow t) z hden

/-- The actual finite exponential Möbius orbit differentiates to the Souriau Riccati field. -/
theorem hasDerivAt_finiteOrbit (v : ThermodynamicSL2Variation) (z : ℂ) :
    HasDerivAt (fun t => v.finiteOrbit t z) (v.vectorField z) 0 := by
  let A := v.generator.matrix
  have h00 : HasDerivAt (fun t : ℂ => v.matrixFlow t 0 0) (A 0 0) 0 := by
    simpa [matrixFlow, thermodynamicSL2MatrixFlow, A, generator, matrixExpFlow] using
      (hasDerivAt_matrixEntry_matrixExpFlow_left A 0 0 0)
  have h01 : HasDerivAt (fun t : ℂ => v.matrixFlow t 0 1) (A 0 1) 0 := by
    simpa [matrixFlow, thermodynamicSL2MatrixFlow, A, generator, matrixExpFlow] using
      (hasDerivAt_matrixEntry_matrixExpFlow_left A 0 0 1)
  have h10 : HasDerivAt (fun t : ℂ => v.matrixFlow t 1 0) (A 1 0) 0 := by
    simpa [matrixFlow, thermodynamicSL2MatrixFlow, A, generator, matrixExpFlow] using
      (hasDerivAt_matrixEntry_matrixExpFlow_left A 0 1 0)
  have h11 : HasDerivAt (fun t : ℂ => v.matrixFlow t 1 1) (A 1 1) 0 := by
    simpa [matrixFlow, thermodynamicSL2MatrixFlow, A, generator, matrixExpFlow] using
      (hasDerivAt_matrixEntry_matrixExpFlow_left A 0 1 1)
  have hnum := (h00.mul_const z).add h01
  have hden := (h10.mul_const z).add h11
  have hden0 : v.matrixFlow 0 1 0 * z + v.matrixFlow 0 1 1 ≠ 0 := by
    rw [matrixFlow_zero]
    norm_num
  unfold finiteOrbit InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction
  convert hnum.div hden hden0 using 1 <;>
    simp [A, generator, thermodynamicSL2Generator, sl2C.matrix, vectorField,
      thermodynamicSL2VectorField, sl2C.vectorField, matrixFlow_zero] <;>
    ring

/-- Away from an affine-chart pole, the finite orbit solves the autonomous Riccati ODE. -/
theorem hasDerivAt_finiteOrbit_eq_vectorField
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    HasDerivAt (fun u => v.finiteOrbit u z) (v.vectorField (v.finiteOrbit t z)) t := by
  have hshift :
      HasDerivAt (fun s => v.finiteOrbit (s + t) z)
        (v.vectorField (v.finiteOrbit t z)) 0 := by
    convert hasDerivAt_finiteOrbit v (v.finiteOrbit t z) using 1
    funext s
    exact finiteOrbit_add v s t z hden
  have hshift0 :
      HasDerivAt (fun s => v.finiteOrbit (s + t) z)
        (v.vectorField (v.finiteOrbit t z)) (-t + t) := by
    simpa using hshift
  have hback := hshift0.comp_const_add (-t) t
  simpa [add_assoc] using hback

/-- Expanded Souriau-force form of the finite autonomous Riccati ODE. -/
theorem hasDerivAt_finiteOrbit_eq_explicit
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    HasDerivAt (fun u => v.finiteOrbit u z)
      (-(v.specialConformal.force : ℂ) * v.finiteOrbit t z ^ 2 +
        2 * (v.dilation.force : ℂ) * v.finiteOrbit t z + v.translation.force) t := by
  simpa [vectorField_eq] using hasDerivAt_finiteOrbit_eq_vectorField v t z hden

/-- Complex spatial Jacobian of the determinant-one finite Möbius orbit. -/
def finiteOrbitJacobian (v : ThermodynamicSL2Variation) (t z : ℂ) : ℂ :=
  1 / (v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1) ^ 2

/-- Denominator formula for the spatial Jacobian. -/
theorem finiteOrbitJacobian_eq (v : ThermodynamicSL2Variation) (t z : ℂ) :
    v.finiteOrbitJacobian t z =
      1 / (v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1) ^ 2 := by
  rfl

/-- Away from the affine pole, the spatial derivative is the determinant-one Jacobian. -/
theorem hasDerivAt_finiteOrbit_space
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    HasDerivAt (v.finiteOrbit t) (v.finiteOrbitJacobian t z) z := by
  let a := v.matrixFlow t 0 0
  let b := v.matrixFlow t 0 1
  let c := v.matrixFlow t 1 0
  let d := v.matrixFlow t 1 1
  have hnum : HasDerivAt (fun w : ℂ => a * w + b) a z := by
    simpa using ((hasDerivAt_id (𝕜 := ℂ) z).const_mul a).add_const b
  have hden' : HasDerivAt (fun w : ℂ => c * w + d) c z := by
    simpa using ((hasDerivAt_id (𝕜 := ℂ) z).const_mul c).add_const d
  have hdet := v.matrixFlow_det t
  rw [Matrix.det_fin_two] at hdet
  unfold finiteOrbit InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction finiteOrbitJacobian
  change HasDerivAt (fun w => (a * w + b) / (c * w + d))
    (1 / (c * z + d) ^ 2) z
  convert hnum.div hden' (by simpa [c, d] using hden) using 1
  field_simp [show c * z + d ≠ 0 by simpa [c, d] using hden]
  rw [← hdet]
  simp only [a, b, c, d]
  ring

/-- The determinant-one spatial Jacobian cannot vanish away from an affine pole. -/
theorem finiteOrbitJacobian_ne_zero
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    v.finiteOrbitJacobian t z ≠ 0 := by
  simp [finiteOrbitJacobian, hden]

/-- Raw matrix-entry denominator cocycle for compatibility with existing affine APIs. -/
theorem finiteOrbit_den_add
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    v.matrixFlow (s + t) 1 0 * z + v.matrixFlow (s + t) 1 1 =
      (v.matrixFlow s 1 0 * v.finiteOrbit t z + v.matrixFlow s 1 1) *
        (v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1) := by
  rw [matrixFlow_add]
  unfold finiteOrbit InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction
  simp only [Matrix.mul_apply, Fin.sum_univ_two]
  field_simp [hinner]
  ring

/-- Nonzero denominator cocycle under inner and outer chart conditions. -/
theorem finiteOrbit_den_add_ne_zero
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0)
    (houter : v.matrixFlow s 1 0 * v.finiteOrbit t z + v.matrixFlow s 1 1 ≠ 0) :
    v.matrixFlow (s + t) 1 0 * z + v.matrixFlow (s + t) 1 1 ≠ 0 := by
  rw [finiteOrbit_den_add v s t z hinner]
  exact mul_ne_zero houter hinner

/-- Multiplicative cocycle for the determinant-one finite-orbit Jacobian. -/
theorem finiteOrbitJacobian_add
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    v.finiteOrbitJacobian (s + t) z =
      v.finiteOrbitJacobian s (v.finiteOrbit t z) * v.finiteOrbitJacobian t z := by
  unfold finiteOrbitJacobian
  rw [finiteOrbit_den_add v s t z hinner]
  field_simp [hinner]

/-- Jacobian cocycle with the exact inner and outer affine-chart nonzero readouts. -/
theorem finiteOrbitJacobian_cocycle_packet
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0)
    (houter : v.matrixFlow s 1 0 * v.finiteOrbit t z + v.matrixFlow s 1 1 ≠ 0) :
    v.finiteOrbitJacobian (s + t) z =
        v.finiteOrbitJacobian s (v.finiteOrbit t z) * v.finiteOrbitJacobian t z ∧
      v.finiteOrbitJacobian t z ≠ 0 ∧
      v.finiteOrbitJacobian s (v.finiteOrbit t z) ≠ 0 ∧
      v.finiteOrbitJacobian (s + t) z ≠ 0 := by
  exact ⟨finiteOrbitJacobian_add v s t z hinner,
    finiteOrbitJacobian_ne_zero v t z hinner,
    finiteOrbitJacobian_ne_zero v s (v.finiteOrbit t z) houter,
    finiteOrbitJacobian_ne_zero v (s + t) z
      (finiteOrbit_den_add_ne_zero v s t z hinner houter)⟩

/-- Real logarithmic norm of the complex spatial Jacobian. -/
noncomputable def logJacobianNorm
    (v : ThermodynamicSL2Variation) (t z : ℂ) : ℝ :=
  Real.log ‖v.finiteOrbitJacobian t z‖

/-- The logarithmic Jacobian norm is an additive cocycle on nested affine charts. -/
theorem logJacobianNorm_add
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0)
    (houter : v.matrixFlow s 1 0 * v.finiteOrbit t z + v.matrixFlow s 1 1 ≠ 0) :
    v.logJacobianNorm (s + t) z =
      v.logJacobianNorm s (v.finiteOrbit t z) + v.logJacobianNorm t z := by
  unfold logJacobianNorm
  rw [finiteOrbitJacobian_add v s t z hinner, norm_mul]
  exact Real.log_mul
    (norm_ne_zero_iff.mpr (finiteOrbitJacobian_ne_zero v s (v.finiteOrbit t z) houter))
    (norm_ne_zero_iff.mpr (finiteOrbitJacobian_ne_zero v t z hinner))

/-- Real log-norm of the finite-orbit complex Jacobian. -/
def finiteOrbitJacobianLogNorm (v : ThermodynamicSL2Variation) (t z : ℂ) : ℝ :=
  Real.log ‖v.finiteOrbitJacobian t z‖

/-- Additive real log-norm cocycle for the nonzero finite-orbit Jacobian. -/
theorem finiteOrbitJacobian_log_norm_add
    (v : ThermodynamicSL2Variation) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0)
    (houter : v.matrixFlow s 1 0 * v.finiteOrbit t z + v.matrixFlow s 1 1 ≠ 0) :
    v.finiteOrbitJacobianLogNorm (s + t) z =
      v.finiteOrbitJacobianLogNorm s (v.finiteOrbit t z) +
        v.finiteOrbitJacobianLogNorm t z := by
  exact logJacobianNorm_add v s t z hinner houter

/-- The complex spatial Jacobian obeys the linearized Souriau–Riccati equation. -/
theorem hasDerivAt_finiteOrbitJacobian
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    HasDerivAt (fun u => v.finiteOrbitJacobian u z)
      ((2 * (v.dilation.force : ℂ) -
          2 * (v.specialConformal.force : ℂ) * v.finiteOrbit t z) *
        v.finiteOrbitJacobian t z) t := by
  let A := v.generator.matrix
  have h10 : HasDerivAt (fun u : ℂ => v.matrixFlow u 1 0)
      ((A * v.matrixFlow t) 1 0) t := by
    simpa [matrixFlow, thermodynamicSL2MatrixFlow, A, generator] using
      (hasDerivAt_matrixEntry_matrixExpFlow_left A t 1 0)
  have h11 : HasDerivAt (fun u : ℂ => v.matrixFlow u 1 1)
      ((A * v.matrixFlow t) 1 1) t := by
    simpa [matrixFlow, thermodynamicSL2MatrixFlow, A, generator] using
      (hasDerivAt_matrixEntry_matrixExpFlow_left A t 1 1)
  have hq := (h10.mul_const z).add h11
  have hq' :
      (A * v.matrixFlow t) 1 0 * z + (A * v.matrixFlow t) 1 1 =
        ((v.specialConformal.force : ℂ) * v.finiteOrbit t z -
          v.dilation.force) *
          (v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1) := by
    unfold finiteOrbit InfoGeometry.Clifford.DiscreteMoebiusGroup.moebiusAction
    simp [A, generator, thermodynamicSL2Generator, sl2C.matrix,
      Matrix.mul_apply, Fin.sum_univ_two]
    field_simp [hden]
    ring
  rw [hq'] at hq
  have hinv := hq.inv hden
  have hpow := hinv.pow 2
  convert hpow using 1
  · funext u
    simp [finiteOrbitJacobian, one_div, pow_two]
  · simp [finiteOrbitJacobian, one_div, pow_two]
    field_simp [hden]
    ring

/-- Branch-free logarithmic derivative ratio of the nonvanishing complex Jacobian. -/
theorem finiteOrbitJacobian_logarithmicGenerator
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    ((2 * (v.dilation.force : ℂ) -
          2 * (v.specialConformal.force : ℂ) * v.finiteOrbit t z) *
        v.finiteOrbitJacobian t z) /
      v.finiteOrbitJacobian t z =
        2 * (v.dilation.force : ℂ) -
          2 * (v.specialConformal.force : ℂ) * v.finiteOrbit t z := by
  exact mul_div_cancel_right₀ _ (v.finiteOrbitJacobian_ne_zero t z hden)

/-- Branch-free `deriv J / J` form of the finite-orbit Jacobian generator. -/
theorem finiteOrbitJacobian_logDeriv
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0) :
    deriv (fun u : ℂ => v.finiteOrbitJacobian u z) t /
        v.finiteOrbitJacobian t z =
      2 * (v.dilation.force : ℂ) -
        2 * (v.specialConformal.force : ℂ) * v.finiteOrbit t z := by
  rw [(v.hasDerivAt_finiteOrbitJacobian t z hden).deriv]
  exact v.finiteOrbitJacobian_logarithmicGenerator t z hden

/-- On the principal logarithm chart, `log J` has the Souriau logarithmic generator. -/
theorem hasDerivAt_log_finiteOrbitJacobian
    (v : ThermodynamicSL2Variation) (t z : ℂ)
    (hden : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0)
    (hslit : v.finiteOrbitJacobian t z ∈ Complex.slitPlane) :
    HasDerivAt (fun u => Complex.log (v.finiteOrbitJacobian u z))
      (2 * (v.dilation.force : ℂ) -
        2 * (v.specialConformal.force : ℂ) * v.finiteOrbit t z) t := by
  have hlog := (v.hasDerivAt_finiteOrbitJacobian t z hden).clog hslit
  convert hlog using 1
  exact (v.finiteOrbitJacobian_logarithmicGenerator t z hden).symm

/-- Along real time, the logarithmic Jacobian norm differentiates to the real part of the
Souriau–Riccati linearization generator. -/
theorem hasDerivAt_logJacobianNorm_real
    (v : ThermodynamicSL2Variation) (t : ℝ) (z : ℂ)
    (hden : v.matrixFlow (t : ℂ) 1 0 * z + v.matrixFlow (t : ℂ) 1 1 ≠ 0) :
    HasDerivAt (fun r : ℝ => v.logJacobianNorm (r : ℂ) z)
      (2 * (v.dilation.force : ℂ) -
        2 * (v.specialConformal.force : ℂ) * v.finiteOrbit (t : ℂ) z).re t := by
  have hf := (v.hasDerivAt_finiteOrbitJacobian (t : ℂ) z hden).comp_ofReal
  have hne := v.finiteOrbitJacobian_ne_zero (t : ℂ) z hden
  have hlog := hasDerivAt_real_log_norm hf hne
  convert hlog using 1
  exact (congrArg Complex.re
    (v.finiteOrbitJacobian_logarithmicGenerator (t : ℂ) z hden)).symm

/-- Positive-sign local Boltzmann log-volume potential `kB * log ‖J‖`.
This is not identified here with normalized Gibbs or von Neumann entropy. -/
noncomputable def boltzmannLogJacobianEntropy
    (v : ThermodynamicSL2Variation) (kB : ℝ) (t z : ℂ) : ℝ :=
  kB * v.logJacobianNorm t z

/-- The local Boltzmann log-volume potential inherits the additive Jacobian cocycle. -/
theorem boltzmannLogJacobianEntropy_add
    (v : ThermodynamicSL2Variation) (kB : ℝ) (s t z : ℂ)
    (hinner : v.matrixFlow t 1 0 * z + v.matrixFlow t 1 1 ≠ 0)
    (houter : v.matrixFlow s 1 0 * v.finiteOrbit t z + v.matrixFlow s 1 1 ≠ 0) :
    v.boltzmannLogJacobianEntropy kB (s + t) z =
      v.boltzmannLogJacobianEntropy kB s (v.finiteOrbit t z) +
        v.boltzmannLogJacobianEntropy kB t z := by
  unfold boltzmannLogJacobianEntropy
  rw [v.logJacobianNorm_add s t z hinner houter]
  ring

/-- Along real time, local Boltzmann log-volume production is `kB` times the real
Riccati linearization generator. -/
theorem hasDerivAt_boltzmannLogJacobianEntropy_real
    (v : ThermodynamicSL2Variation) (kB t : ℝ) (z : ℂ)
    (hden : v.matrixFlow (t : ℂ) 1 0 * z + v.matrixFlow (t : ℂ) 1 1 ≠ 0) :
    HasDerivAt (fun r : ℝ => v.boltzmannLogJacobianEntropy kB (r : ℂ) z)
      (kB * (2 * (v.dilation.force : ℂ) -
        2 * (v.specialConformal.force : ℂ) * v.finiteOrbit (t : ℂ) z).re) t := by
  exact (v.hasDerivAt_logJacobianNorm_real t z hden).const_mul kB

/-- At the identity time, the finite-orbit Jacobian is `1`. -/
theorem finiteOrbitJacobian_zero (v : ThermodynamicSL2Variation) (z : ℂ) :
    v.finiteOrbitJacobian 0 z = 1 := by
  simp [finiteOrbitJacobian, matrixFlow_zero]

/-- At the identity time, the logarithmic Jacobian norm vanishes. -/
theorem logJacobianNorm_zero (v : ThermodynamicSL2Variation) (z : ℂ) :
    v.logJacobianNorm 0 z = 0 := by
  simp [logJacobianNorm, finiteOrbitJacobian_zero]

/-- At the identity time, the local Boltzmann log-volume potential vanishes. -/
theorem boltzmannLogJacobianEntropy_zero
    (v : ThermodynamicSL2Variation) (kB : ℝ) (z : ℂ) :
    v.boltzmannLogJacobianEntropy kB 0 z = 0 := by
  simp [boltzmannLogJacobianEntropy, logJacobianNorm_zero]

/-- The Souriau-derived Möbius chart variation differentiates to its Riccati field. -/
theorem hasDerivAt_infinitesimalOrbit (v : ThermodynamicSL2Variation) (z : ℂ) :
    HasDerivAt
      (thermodynamicSL2InfinitesimalOrbit v.translation.force v.dilation.force
        v.specialConformal.force z)
      (v.vectorField z) 0 := by
  exact hasDerivAt_thermodynamicSL2InfinitesimalOrbit v.translation.force
    v.dilation.force v.specialConformal.force z

end ThermodynamicSL2Variation

end ThermodynamicSL2MobiusFlow
