import Mathlib

/-!
# Finite V4 root-system socket

This module records the Klein four group table associated with the two sign
reflections of the finite `A₁ × A₁` root picture.  It proves the point-inversion
composition and involution laws.

It does **not** prove `SO(4)`, Lorentz symmetry, spin geometry, or relativistic
spacetime emergence.  Those require additional representation/manifold data not
present in this finite Cayley-table file.
-/

namespace InfoGeometry.Topology.V4RootSystem

/-- The four-element Klein group generated by two commuting sign reflections. -/
inductive V4Group where
  | I
  | W1
  | W2
  | W12
  deriving DecidableEq, Repr

open V4Group

/-- Multiplication table for the Klein four group. -/
def v4_mul : V4Group → V4Group → V4Group
  | I, x => x
  | x, I => x
  | W1, W1 => I
  | W2, W2 => I
  | W12, W12 => I
  | W1, W2 => W12
  | W2, W1 => W12
  | W1, W12 => W2
  | W12, W1 => W2
  | W2, W12 => W1
  | W12, W2 => W1

instance : Mul V4Group where
  mul := v4_mul

/-- Point inversion is the composition of the two coordinate sign reflections. -/
theorem varlamov_v4_inversion : W1 * W2 = W12 := by
  rfl

/-- The two coordinate sign reflections commute. -/
theorem v4_reflections_commute : W1 * W2 = W2 * W1 := by
  rfl

/-- Every element of the Klein four group is an involution. -/
theorem v4_involution (x : V4Group) : x * x = I := by
  cases x <;> rfl

/-- The point inversion is also an involution. -/
theorem v4_point_inversion_involution : W12 * W12 = I := by
  rfl

end InfoGeometry.Topology.V4RootSystem
