import InfoGeometry.Volume.ConnesTomitaKreinDerivation

/-!
# InfoGeometry.Volume.ConnesTomitaKreinBridge

Public theorem surface connecting the constructive Connes infinitesimal layer
to the finite Tomita/Krein projector calculus.

The proofs live in `ConnesTomitaKreinDerivation`; this module re-exports the
small bridge statements under the requested public name.  No mode-indexed
current, normal-ordering construction, or central extension is asserted here.
-/

namespace InfoGeometry.Volume.ConnesTomitaKreinBridge

open InfoGeometry.Clifford.SplitQ11PhaseFlip
open InfoGeometry.Clifford.SplitQ11Projectors
open InfoGeometry.Canonical.KreinProjectorLattice

/-! ## Public finite modular/Krein readout -/

/-- Finite split-`Cl(1,1)` modular derivation generated by the Krein sign `ε`. -/
@[rep_depth krein]
noncomputable abbrev finiteKreinModularDerivation (A : Alg) : Alg :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKreinModularDerivation A

/-- Finite sector-leakage commutator with the positive Krein projector. -/
@[rep_depth krein]
noncomputable abbrev finiteKreinPositiveProjectorCommutator (A : Alg) : Alg :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKreinPositiveProjectorCommutator A

/--
The finite Krein sign commutator is twice the positive-projector commutator:
`[ε, A] = 2 [P₊, A]`, with `P₊ = (1 + ε) / 2`.
-/
@[rep_depth krein]
theorem finiteKrein_projector_commutator_as_modular_derivation (A : Alg) :
    finiteKreinModularDerivation A =
      (2 : ℝ) • finiteKreinPositiveProjectorCommutator A :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKrein_projector_commutator_as_modular_derivation A

/-- The finite modular generator is the Krein involution recovered from the lattice. -/
@[rep_depth krein]
theorem finiteKreinModularGenerator_eq_latticeInvolution :
    epsGen = KreinSector.kreinInvolution :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKreinModularGenerator_eq_latticeInvolution

/--
The same commutator readout using the lattice-recovered Krein involution.
-/
@[rep_depth krein]
theorem finiteKrein_lattice_projector_commutator_as_modular_derivation (A : Alg) :
    KreinSector.kreinInvolution * A - A * KreinSector.kreinInvolution =
      (2 : ℝ) • finiteKreinPositiveProjectorCommutator A :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKrein_lattice_projector_commutator_as_modular_derivation A

/-! ## Public finite idempotent exponential readout -/

/--
Finite idempotent expansion of the exponential generated by the Krein sign:
`exp(t ε) = exp(t) P₊ + exp(-t) P₋`.
-/
@[rep_depth krein]
noncomputable abbrev finiteKreinIdempotentExponential (t : ℝ) : Alg :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKreinIdempotentExponential t

/-- Readback of the finite projector formula for `exp(t ε)`. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_formula (t : ℝ) :
    finiteKreinIdempotentExponential t =
      Real.exp t • epsPlusProjector + Real.exp (-t) • epsMinusProjector :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKrein_idempotent_exponential_formula t

/-- The finite idempotent exponential is the identity at zero modular time. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_zero :
    finiteKreinIdempotentExponential 0 = (1 : Alg) :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKrein_idempotent_exponential_zero

/-- Orthogonal idempotents make the finite exponential multiplicative in time. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_add (s t : ℝ) :
    finiteKreinIdempotentExponential (s + t) =
      finiteKreinIdempotentExponential s * finiteKreinIdempotentExponential t :=
  InfoGeometry.Volume.ConnesTomitaKreinDerivation.finiteKrein_idempotent_exponential_add s t

end InfoGeometry.Volume.ConnesTomitaKreinBridge
