import InfoGeometry.LLM.McbalFullNativeCorridor

/-!
Transitive axiom audit for the repository-native mcbal corridor.
-/

#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.sinkhorn_two_step_is_weyl_gauge
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.sinkhorn_balance_has_birkhoff_von_neumann_decomposition
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.balanced_mixture_has_permutation_readback
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.poisson_sinkhorn_primal_dual_gap_is_bregman_gap
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.detailed_balance_iff_weighted_self_adjoint
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.path_ratio_is_exponential_affinity_integral
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.cross_gramian_transpose_reverses_feature_slices
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.nonzero_causal_transfer_strictly_lowers_mass
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.frozen_ba_modular_potential_is_beta_kl_plus_partition_gauge
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.ib_trajectory_converges_under_subunit_lipschitz_bound
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.modular_dynamics_eq_gauge_add_source
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.modular_phase_is_metric_twisted_by_complex_axis
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.bkm_reduces_to_classical_fisher_on_diagonal
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.harmonic_bayesian_posterior_is_locally_protected
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.jko_proximal_steps_form_additive_semigroup
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.contractive_orbit_stays_in_nested_dikin_ellipsoids
#print axioms InfoGeometry.LLM.McbalFullNativeCorridor.bkm_dikin_quadratic_is_positive_off_zero
