import InfoGeometry.Canonical.SinkhornGaugeThermodynamicsBridge
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Canonical.SinkhornFoundation
import InfoGeometry.LLM.BogoliubovSinkhornRouting
import InfoGeometry.Inference.PoissonSinkhornPotentials
import InfoGeometry.Probability.FiniteMarkovWeightedAdjoint
import InfoGeometry.Canonical.MaximumCaliberPath
import InfoGeometry.MassSpectrometry.CausalTransferArchitecture
import InfoGeometry.Canonical.IBFrozenModularBridge
import InfoGeometry.Canonical.IBCanonical
import InfoGeometry.Canonical.RelationalInformationCore
import InfoGeometry.Canonical.ModularHessian
import InfoGeometry.InformationGeometry.BKMMetricModularBridge
import InfoGeometry.Canonical.BayesianThermoMetricHodgeBridge
import InfoGeometry.Dynamics.WassersteinProximalBridge
import InfoGeometry.Canonical.DikinFiniteOrbitColimit

noncomputable section

namespace InfoGeometry.LLM.McbalFullNativeCorridor

alias sinkhorn_two_step_is_weyl_gauge := InfoGeometry.Canonical.SinkhornGaugeThermodynamicsBridge.sinkhornTwoStep_is_twoSidedWeylGauge
alias sinkhorn_balance_has_birkhoff_von_neumann_decomposition := InfoGeometry.Canonical.MoE.exists_perm_decomposition_of_sinkhornBalanced
alias balanced_mixture_has_permutation_readback := InfoGeometry.LLM.BogoliubovSinkhornRouting.sinkhornBalanced_permutation_decomposition
alias poisson_row_assignment_is_unique_entropy_minimizer := InfoGeometry.Inference.poissonTransportAssignment_unique_entropy_minimizer
alias poisson_sinkhorn_primal_dual_gap_is_bregman_gap := InfoGeometry.Inference.poissonSinkhornPrimalDual_gap_eq_bregmanGap
alias poisson_sinkhorn_primal_dual_gap_nonnegative := InfoGeometry.Inference.poissonSinkhornPrimalDual_gap_nonneg
alias detailed_balance_iff_weighted_self_adjoint := InfoGeometry.Probability.detailedBalance_iff_weightedAdjoint_eq
alias detailed_balance_iff_whitened_symmetric := InfoGeometry.Probability.detailedBalance_iff_whitened_symmetric
alias path_ratio_is_exponential_affinity_integral := InfoGeometry.Canonical.MaximumCaliberPath.pathForwardBackwardRatio_eq_exp_maxCalConstraint
alias zero_cycle_affinity_implies_cycle_detailed_balance := InfoGeometry.Canonical.MaximumCaliberPath.detailedBalanceOnCycle_of_pathEntropyProduction_eq_zero
alias directed_operator_eq_symmetric_add_antisymmetric := InfoGeometry.MassSpectrometry.symmetricPart_add_antisymmetricPart
alias cross_gramian_transpose_reverses_feature_slices := InfoGeometry.MassSpectrometry.crossGramOperator_transpose
alias auto_gramian_has_zero_antisymmetric_part := InfoGeometry.MassSpectrometry.antisymmetricPart_crossGram_self_eq_zero
alias nonzero_causal_transfer_strictly_lowers_mass := InfoGeometry.MassSpectrometry.CausalTransferSystem.transfer_mass_decreases
alias frozen_ba_modular_potential_is_beta_kl_plus_partition_gauge := InfoGeometry.Canonical.IB.ibBlahutArimotoStepFrozen_scalarModularPotential_eq_betaKL_add_logPartitionFrozen
alias frozen_ba_modular_potential_gauge_reduction := InfoGeometry.Canonical.IB.ibBlahutArimotoStepFrozen_scalarModularPotential_sub_logPartitionFrozen_eq_betaKL
alias frozen_ba_variational_descent := InfoGeometry.Canonical.IB.frozenVariational_descent
alias ib_trajectory_converges_under_subunit_lipschitz_bound := InfoGeometry.Canonical.IB.tendsto_ibTrajectory_fixedPoint_of_lipschitz
alias modular_dynamics_eq_gauge_add_source := InfoGeometry.Canonical.RelationalInformationCore.comparisonInducedDynamics_eq_gauge_add_source
alias modular_phase_is_metric_twisted_by_complex_axis := InfoGeometry.Canonical.RelationalInformationCore.comparisonPhaseReadout_eq_metric_comp_modularComplexI
alias bkm_reduces_to_classical_fisher_on_diagonal := InfoGeometry.InformationGeometry.BKM.bkm_classical_fisher_reduction
alias harmonic_bayesian_posterior_is_locally_protected := InfoGeometry.Canonical.BayesianThermoMetricHodgeBridge.posterior_harmonic_protected
alias coexact_maxcal_current_is_dlog_readout := InfoGeometry.Canonical.BayesianThermoMetricHodgeBridge.coexact_current_eq_dlnQ
alias jko_proximal_steps_form_additive_semigroup := InfoGeometry.Dynamics.WassersteinProximalBridge.jkoEntropyStep_composition
alias contractive_orbit_stays_in_nested_dikin_ellipsoids := InfoGeometry.Canonical.DikinFiniteOrbitColimit.orbit_mem_dikin_ellipsoid
alias bkm_dikin_quadratic_is_positive_off_zero := InfoGeometry.Canonical.DikinFiniteOrbitColimit.bkmDikinQuadratic_pos_of_ne_zero

end InfoGeometry.LLM.McbalFullNativeCorridor
