import InfoGeometry
import InfoGeometry.Analysis.All
import InfoGeometry.Canonical.CasiniBekensteinBound
import InfoGeometry.Canonical.OperatorialFierzDerivationBridge
import InfoGeometry.Canonical.MeasureScaleShape
import InfoGeometry.Canonical.CantorProjectiveLimit
import InfoGeometry.Canonical.CantorProjectiveLimitCategoricalIsoTopCat
import InfoGeometry.Canonical.SplitG2MetricDerivedHodgeStar
import InfoGeometry.Canonical.SplitQuaternionAssociativeCoassociativeCalibrationBridge
import InfoGeometry.Canonical.MealySplitOctonionBridge
import InfoGeometry.Canonical.HarveyLawsonDiracDeformation
import InfoGeometry.Canonical.ConnesNoncommutativeGeometry
import InfoGeometry.Canonical.ConnesSpectralDistanceTopCatBridge
import InfoGeometry.Canonical.CayleyBoundaryFlowBridge
import InfoGeometry.Canonical.BCFWOnShellShift
import InfoGeometry.Topology.BCFWOnShellShiftTopological
import InfoGeometry.Canonical.BCFWMeromorphicResidueRecursion
import InfoGeometry.Topology.PeirceBCFWResidueFactorizationTopological
import InfoGeometry.Topology.BCFWResidueFactorizationTopologicalBridge
import InfoGeometry.Physics.SupergradedDiracCrystalTopCatColimit
import InfoGeometry.Physics.JaynesMaxEntKMSBridge
import InfoGeometry.Canonical.ComplexAnalyticBridge
import InfoGeometry.Topology.ContinuousModularFlowQuotientTopCat
import InfoGeometry.Topology.PoissonGibbsTopCatBridge
import InfoGeometry.Topology.SymbolicLatentObservationRangeCompHaus
import InfoGeometry.Topology.SymbolicLatentPathFamilyImageCompHaus
import InfoGeometry.Topology.SymbolicLatentFeasibleRegionCompHaus
import InfoGeometry.Topology.SymbolicLatentModularOrbitClosureCompHaus
import InfoGeometry.Topology.SymbolicLatentNoncommutativeObservable
import InfoGeometry.Topology.SymbolicLatentBoundaryCylinderNeighborhoodTopCat
import InfoGeometry.Topology.SymbolicLatentVaryingCarrierCompHaus

-- Simple sanity check that key theorems and definitions compile

-- Bekenstein current surface
#check InfoGeometry.Canonical.BekensteinBound.trajectoryRNBarrier_nonneg
#check InfoGeometry.Canonical.BekensteinBound.topologicalBekensteinBound_of_sinkhornTrajectory
#check InfoGeometry.Canonical.BekensteinBound.TopologicalBekensteinBound

-- Casini-Bekenstein Bound (True Bound)
#check InfoGeometry.Canonical.CasiniBekenstein.true_bekenstein_bound

-- Operatorial Fierz Derivation (Commutator properties)
#check InfoGeometry.Canonical.OperatorialFierz.innerDerivation
#check InfoGeometry.Canonical.OperatorialFierz.emergentSpacetime_is_derivation

-- Native projective-limit boundary and its TopCat comparison
#check InfoGeometry.Canonical.CantorProjectiveLimit.PrefixProjectiveLimit
#check InfoGeometry.Canonical.CantorProjectiveLimit.PrefixProjectiveLimit.cantorHomeomorphPrefixProjectiveLimit
#check InfoGeometry.Canonical.CantorProjectiveLimitCategoricalIsoTopCat.projectiveToCategoricalLimitTopCatIso

-- Native supergraded Dirac crystal colimit
#check InfoGeometry.Physics.SupergradedDiracCrystalTopCatColimit.supergradedDiracCrystalTopCatColimit
#check InfoGeometry.Physics.SupergradedDiracCrystalTopCatColimit.supergradedDiracCrystalTopCatDescend

-- Jaynes / Poisson / modular quotient surface
#check InfoGeometry.Physics.jaynesGibbsState
#check InfoGeometry.Physics.jaynes_state_is_strictly_kms
#check InfoGeometry.Analysis.binaryEntropy_half
#check InfoGeometry.Analysis.binaryEntropy_le_log_two
#check InfoGeometry.Analysis.binaryEntropy_eq_log_two_iff
#check InfoGeometry.Analysis.cuntz_symmetric_branch_entropy_eq_log_two
#check InfoGeometry.Topology.ContinuousQuotientDescent.descendedModularFlowTopCatHom
#check InfoGeometry.Topology.ContinuousQuotientDescent.descendedModularFlowTopCatHom_isIso
#check InfoGeometry.Topology.PoissonGibbsTopCatBridge.poissonWeightTopCatHom
#check InfoGeometry.Topology.PoissonGibbsTopCatBridge.poissonFreeEnergyTopCatHom

-- Native split-G₂ metric/Hodge bridge
#check InfoGeometry.Canonical.SplitG2MetricDerivedHodgeStar.metricStar43_metricStar34
#check InfoGeometry.Canonical.SplitG2MetricDerivedHodgeStar.hodge_star_double_application_identity

-- Native split-quaternion calibration bridge
#check InfoGeometry.Canonical.SplitQuaternionAssociativeCoassociativeCalibrationBridge.associativePlane_finrank
#check InfoGeometry.Canonical.SplitQuaternionAssociativeCoassociativeCalibrationBridge.standard_associative_three_form_value
#check InfoGeometry.Canonical.SplitQuaternionAssociativeCoassociativeCalibrationBridge.standard_coassociative_generator_three_form_zero

-- Mealy consequences over the native split-octonion slice
#check InfoGeometry.Canonical.MealySplitOctonionBridge.standard_associative_three_form_mealy_consequence
#check InfoGeometry.Canonical.MealySplitOctonionBridge.standard_coassociative_three_form_mealy_shadow

-- Harvey--Lawson aliases over the same native split-octonion slice
#check InfoGeometry.Canonical.HarveyLawsonDiracDeformation.standard_associative_three_form_harvey_lawson_consequence
#check InfoGeometry.Canonical.HarveyLawsonDiracDeformation.standard_coassociative_three_form_harvey_lawson_shadow

-- Native Connes noncommutative geometry bridge
#check InfoGeometry.Canonical.ConnesNoncommutativeGeometry.differential_leibniz
#check InfoGeometry.Canonical.ConnesNoncommutativeGeometry.state_distance_triangle

-- Native topological spectral-distance bridge
#check InfoGeometry.Canonical.ConnesSpectralDistanceTopCatBridge.lipSet_closed
#check InfoGeometry.Canonical.ConnesSpectralDistanceTopCatBridge.pointwise_le_supremum_spectral_dist

-- Cayley boundary flow bridge
#check InfoGeometry.Canonical.CayleyBoundaryFlowBridge.continuous_cayleyBoundary
#check InfoGeometry.Canonical.CayleyBoundaryFlowBridge.cayley_boundary_flow_bridge

-- BCFW on-shell shift and its topological packaging
#check InfoGeometry.Canonical.bcfw_shift_left_null
#check InfoGeometry.Canonical.bcfw_shift_right_null
#check InfoGeometry.Canonical.bcfw_shift_momentum_conservation
#check InfoGeometry.Canonical.bcfw_channel_goes_onShell
#check InfoGeometry.Topology.BCFWOnShellShift.continuous_shiftedChannel
#check InfoGeometry.Topology.BCFWOnShellShift.isClosed_shiftedChannel_onShell_locus

-- BCFW residue factorization bridge
#check InfoGeometry.Canonical.algebraic_residue_identity
#check InfoGeometry.Topology.continuousOn_peirceBCFWChannelTerm
#check InfoGeometry.Topology.BCFWResidueFactorizationTopologicalBridge.peirce_bcfw_residue_topological_bridge

-- Native CompHaus packaging of compact symbolic observation ranges
#check InfoGeometry.Topology.symbolicObservationRangeCompHaus
#check InfoGeometry.Topology.symbolicObservationRangeCompHausTopCatHom_isIso
#check InfoGeometry.Topology.observedSymbolicLatentPathFamilyImageCompHaus
#check InfoGeometry.Topology.observedSymbolicLatentPathFamilyImageCompHaus_factorization
#check InfoGeometry.Topology.symbolicLatentFeasibleFeatureRegionCompHaus
#check InfoGeometry.Topology.symbolicLatentFeasibleRegionObservationCompHausTopCatHom_apply
#check InfoGeometry.Topology.symbolicLatentModularOrbitClosureCompHaus
#check InfoGeometry.Topology.symbolicLatentModularOrbitClosureCompHausTopCatHom
#check InfoGeometry.Topology.operatorCommutator_eq_zero_iff
#check InfoGeometry.Topology.pointwiseOperatorCommutator_eq_zero_iff
#check InfoGeometry.Topology.NoncommutativeObservableSystem.scalarized_observationMap
#check InfoGeometry.Topology.SymbolicLatentBoundaryCylinderNeighborhood.colimitBoundaryCylinder_mem_nhds
#check InfoGeometry.Topology.SymbolicLatentBoundaryCylinderNeighborhood.colimitBoundaryCylinder_preimage_stage
#check InfoGeometry.Topology.compactSymbolicLatentObservationRangeCompHausFunctor_map_forget

-- Complex analytic doubled bridge
open InfoGeometry.Canonical.ComplexAnalyticBridge
#check analyticAt_liftedToDoubled_cauchyAnalyticAt
#check complexDoubledCLE
#check lifted
#check clockAxis_complexToDoubled

-- Zero-holonomy / primitive exactness bridge
open InfoGeometry.Canonical.ZeroHolonomyAnalyticity
#check isExactOn_to_analyticAt
#check isExactOn_to_cauchyAnalyticAt
#check isExactOn_to_doubled_cauchyAnalyticAt
#check primitiveExactness_to_zeroHolonomy_cauchyAnalyticAt
#check primitiveExactness_to_zeroHolonomy_doubled_cauchyAnalyticAt

example (z : ℂ) : doubledToComplex (complexToDoubled z) = z := by
  simp

example (v : InfoGeometry.Krein.DoubledSpace ℝ) :
    complexToDoubled (doubledToComplex v) = v := by
  simp
