from __future__ import annotations

import json
from pathlib import Path

from tools.infra import hermes_vibe_coding_agent as agent


def test_sanitize_candidate_removes_chatml_fences_and_vibe_footer() -> None:
    raw = """```lean
rfl
```
Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
<|im_start|>user
ignore this stale continuation
"""

    assert agent.sanitize_candidate(raw) == "rfl"


def test_build_lean_tactic_messages_are_bounded_and_local_only() -> None:
    messages = agent.build_messages(
        mode="lean-tactic",
        task="1 = 1",
        context="",
        imports=["Init"],
    )

    assert messages[0]["role"] == "system"
    assert "proposal generator" in messages[0]["content"]
    assert "Do not use tools" in messages[0]["content"]
    assert "authority" in messages[0]["content"]
    assert messages[1]["role"] == "user"
    assert "Lean 4 goal" in messages[1]["content"]
    assert "1 = 1" in messages[1]["content"]
    assert "import Init" in messages[1]["content"]


def test_parse_openai_chat_completion_extracts_assistant_content() -> None:
    payload = {
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": "```lean\nrfl\n```",
                }
            }
        ],
        "model": "leanstral-gguf",
    }

    assert agent.extract_assistant_content(payload) == "```lean\nrfl\n```"


def test_parse_openai_chat_completion_extracts_reasoning_content() -> None:
    payload = {
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": None,
                    "reasoning_content": [
                        {"type": "text", "text": "I reasoned this should be rfl."},
                        " ",
                    ],
                }
            }
        ],
        "model": "leanstral-gguf",
    }

    assert agent.extract_assistant_content(payload) == "I reasoned this should be rfl. "


def test_build_arg_parser_defaults_endpoint_uses_leanstral_base_url(monkeypatch) -> None:
    monkeypatch.delenv("LEANSTRAL_ENDPOINT", raising=False)
    monkeypatch.setenv("LEANSTRAL_BASE_URL", "http://127.0.0.1:18889/v1")
    # Ensure parser creation/parse picks the expected endpoint default.
    args = agent.build_arg_parser().parse_args(["lean-tactic", "--task", "1 = 1"])
    assert args.endpoint == "http://127.0.0.1:18889/v1"


def test_build_arg_parser_prefers_leanstral_endpoint_over_base_url(monkeypatch) -> None:
    monkeypatch.setenv("LEANSTRAL_ENDPOINT", "http://127.0.0.1:19999/v1")
    monkeypatch.setenv("LEANSTRAL_BASE_URL", "http://127.0.0.1:18889/v1")
    args = agent.build_arg_parser().parse_args(["lean-tactic", "--task", "1 = 1"])
    assert args.endpoint == "http://127.0.0.1:19999/v1"


def test_propose_with_fake_transport_returns_proposal_packet(tmp_path: Path, monkeypatch) -> None:
    seen: dict[str, object] = {}

    def fake_fetch_model_ids(endpoint: str, timeout: int) -> tuple[int, list[str], str]:
        return 200, ["leanstral-gguf"], ""

    def fake_transport(url: str, payload: dict, timeout: int) -> dict:
        seen["url"] = url
        seen["payload"] = payload
        seen["timeout"] = timeout
        return {
            "model": "leanstral-gguf",
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": "```lean\nrfl\n```<|im_start|>user\nstale",
                    }
                }
            ],
        }

    monkeypatch.setattr(agent, "fetch_model_ids", fake_fetch_model_ids)
    cfg = agent.LeanstralConfig(
        endpoint="http://127.0.0.1:18889/v1",
        model="leanstral-gguf",
        timeout=7,
        max_tokens=64,
        temperature=0.0,
    )

    result = agent.propose(
        mode="lean-tactic",
        task="1 = 1",
        context="",
        imports=["Init"],
        config=cfg,
        transport=fake_transport,
    )

    assert seen["url"] == "http://127.0.0.1:18889/v1/chat/completions"
    sent = seen["payload"]
    assert sent["model"] == "leanstral-gguf"
    assert sent["max_tokens"] == 64
    assert "max_completion_tokens" not in sent
    assert sent["stop"] == ["<|im_end|>", "<|im_start|>"]
    assert sent["temperature"] == 0.0
    assert result["schema"] == "hermes_vibe_coding_agent.proposal.v1"
    assert result["status"] == "ok"
    assert result["authority"] == "proposal"
    assert result["promotion_allowed"] is False
    assert result["mode"] == "lean-tactic"
    assert result["candidate"] == "rfl"
    assert result["raw_candidate"].startswith("```lean")
    assert result["endpoint"] == "http://127.0.0.1:18889/v1"
    assert len(result["prompt_hash"]) == 64
    assert result["model"] == "leanstral-gguf"
    assert result["resolved_model"] == "leanstral-gguf"
    assert result["model_resolved"] is False


def test_cli_prints_json_with_fake_response(tmp_path: Path, monkeypatch) -> None:
    response = tmp_path / "response.json"
    response.write_text(
        json.dumps(
            {
                "choices": [
                    {"message": {"role": "assistant", "content": "exact rfl"}}
                ]
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.setattr(agent, "fetch_model_ids", lambda endpoint, timeout: (200, ["leanstral-gguf"], ""))

    exit_code = agent.main(
        [
            "lean-tactic",
            "--task",
            "1 = 1",
            "--import",
            "Init",
            "--fake-response",
            str(response),
        ]
    )

    assert exit_code == 0


def test_resolve_model_with_leanstral_path_alias(monkeypatch) -> None:
    seen: dict[str, object] = {}

    def fake_fetch_model_ids(endpoint: str, timeout: int) -> tuple[int, list[str], str]:
        return 200, ["/models/mistralai_Leanstral-128x3.9B-2603-Q4_K_M.gguf"], ""

    def fake_transport(url: str, payload: dict, timeout: int) -> dict:
        seen["url"] = url
        seen["payload"] = payload
        return {
            "model": "/models/mistralai_Leanstral-128x3.9B-2603-Q4_K_M.gguf",
            "choices": [
                {
                    "message": {
                        "role": "assistant",
                        "content": "rfl",
                    }
                }
            ],
        }

    monkeypatch.setattr(agent, "fetch_model_ids", fake_fetch_model_ids)
    result = agent.propose(
        mode="lean-tactic",
        task="1 = 1",
        context="",
        imports=["Init"],
        config=agent.LeanstralConfig(endpoint="http://127.0.0.1:18889/v1", model="leanstral-gguf"),
        transport=fake_transport,
    )

    assert seen["payload"]["model"] == "/models/mistralai_Leanstral-128x3.9B-2603-Q4_K_M.gguf"
    assert result["resolved_model"] == "/models/mistralai_Leanstral-128x3.9B-2603-Q4_K_M.gguf"
    assert result["model_resolved"] is True
