import InfoGeometry.GroupTheory.GeneratedSetExhaustion
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Algebra.Zorn.G2ConcreteGeneratorInfrastructure

/-!
# Concrete BN-generated Bruhat exhaustion for `G₂(2)`

This owner separates the proved generated-carrier coverage from the stronger,
still independent ambient generation statement.

Assuming the concrete simple-reflection transition `ConcreteBN2Transition`, the
Bruhat covering is stable under the unipotent subgroup and under the two simple
Weyl reflections `s` and `t`.  Since `s` and `t` are involutions, one-way
invariance upgrades to membership in the generic left stabilizer.  Therefore
every element of `concreteBNGeneratorSubgroup` belongs to the concrete Bruhat
covering.

No theorem identifying `concreteBNGeneratorSubgroup` with all of
`SplitOctF2Aut` is asserted here.
-/

namespace InfoGeometry.Algebra.Zorn.G2ConcreteBNBruhatExhaustion

open InfoGeometry.GroupTheory.GeneratedSetExhaustion
open InfoGeometry.OperatorAlgebra.G2TwoAutomorphismTheorem
open InfoGeometry.Algebra.Zorn.G2ConcreteWeylG2
open InfoGeometry.Algebra.Zorn.G2TwoBruhatClassification
open InfoGeometry.Algebra.Zorn.G2TwoPCSubgroupClosure
open InfoGeometry.Algebra.Zorn.G2ConcreteGeneratorInfrastructure

/-- The identity automorphism lies in the concrete twelve-cell Bruhat union. -/
theorem one_mem_concreteBruhatCovering :
    (1 : SplitOctF2Aut) ∈ concreteBruhatCovering := by
  apply Set.mem_iUnion.mpr
  refine ⟨(0, false), ?_⟩
  simpa [weylNF_zero_false] using
    (weyl_mem_concreteBruhatCell (1 : SplitOctF2Aut))

/-- The unipotent subgroup acts by two-way left membership preservation on the
Bruhat covering. -/
theorem unipotentSubgroup_le_bruhat_leftStabilizer :
    unipotentSubgroup ≤ leftStabilizer concreteBruhatCovering := by
  intro b hb
  rw [mem_leftStabilizer_iff]
  intro x
  constructor
  · intro hx
    exact concreteBruhatCovering_left_mul_borel b hb hx
  · intro hbx
    have hbinv : b⁻¹ ∈ unipotentSubgroup :=
      unipotentSubgroup.inv_mem hb
    have hback :=
      concreteBruhatCovering_left_mul_borel b⁻¹ hbinv hbx
    simpa [mul_assoc] using hback

/-- Under the concrete BN2 transition, the simple reflection `s` belongs to
    the left stabilizer of the Bruhat covering. -/
theorem s_mem_bruhat_leftStabilizer
    (h : ConcreteBN2Transition) :
    s ∈ leftStabilizer concreteBruhatCovering := by
  apply mem_leftStabilizer_of_involution_mapsTo
  · exact s_sq
  · intro x hx
    exact concreteBruhatCovering_left_mul_simple_of_transition
      h s (by simp) hx

/-- Under the concrete BN2 transition, the simple reflection `t` belongs to
    the left stabilizer of the Bruhat covering. -/
theorem t_mem_bruhat_leftStabilizer
    (h : ConcreteBN2Transition) :
    t ∈ leftStabilizer concreteBruhatCovering := by
  apply mem_leftStabilizer_of_involution_mapsTo
  · exact t_sq
  · intro x hx
    exact concreteBruhatCovering_left_mul_simple_of_transition
      h t (by simp) hx

/-- The full concrete BN generating set stabilizes the Bruhat covering. -/
theorem concreteBN_generators_subset_bruhat_leftStabilizer
    (h : ConcreteBN2Transition) :
    ((unipotentSubgroup : Set SplitOctF2Aut) ∪ {s, t}) ⊆
      (leftStabilizer concreteBruhatCovering : Set SplitOctF2Aut) := by
  intro g hg
  rcases hg with hgU | hgST
  · exact unipotentSubgroup_le_bruhat_leftStabilizer hgU
  · rcases hgST with rfl | rfl
    · exact s_mem_bruhat_leftStabilizer h
    · exact t_mem_bruhat_leftStabilizer h

/-- The subgroup generated by the concrete Borel/unipotent sector and the two
simple Weyl reflections lies in the generic left stabilizer of the Bruhat
covering. -/
theorem concreteBNGeneratorSubgroup_le_bruhat_leftStabilizer
    (h : ConcreteBN2Transition) :
    concreteBNGeneratorSubgroup ≤ leftStabilizer concreteBruhatCovering := by
  apply (Subgroup.closure_le _).2
  exact concreteBN_generators_subset_bruhat_leftStabilizer h

/-- **Generated-carrier Bruhat exhaustion.**

Every element generated by the concrete unipotent subgroup together with the
simple Weyl reflections `s,t` lies in one of the twelve concrete Bruhat cells.
This is strictly weaker than ambient coverage unless a separate theorem proves
`concreteBNGeneratorSubgroup = ⊤`. -/
theorem concreteBNGeneratorSubgroup_le_concreteBruhatCovering
    (h : ConcreteBN2Transition) :
    ∀ g : SplitOctF2Aut,
      g ∈ concreteBNGeneratorSubgroup → g ∈ concreteBruhatCovering := by
  intro g hg
  have hgstab : g ∈ leftStabilizer concreteBruhatCovering :=
    concreteBNGeneratorSubgroup_le_bruhat_leftStabilizer h hg
  have h_eval :=
    ((mem_leftStabilizer_iff concreteBruhatCovering g).mp hgstab 1).mp
      one_mem_concreteBruhatCovering
  simpa using h_eval

/-- Direct specialization from the stronger canonical peeling obligation. -/
theorem concreteBNGeneratorSubgroup_le_concreteBruhatCovering_of_canonicalPeeling
    (h : ConcreteCanonicalPeelingStep) :
    ∀ g : SplitOctF2Aut,
      g ∈ concreteBNGeneratorSubgroup → g ∈ concreteBruhatCovering := by
  exact concreteBNGeneratorSubgroup_le_concreteBruhatCovering
    (concreteBN2Transition_of_canonicalPeeling h)

/-- If a future, separate generation theorem identifies the concrete BN
subgroup with the full ambient automorphism group, then the twelve Bruhat cells
cover the full carrier. -/
theorem concreteBruhatCovering_eq_univ_of_generation
    (htransition : ConcreteBN2Transition)
    (hgen : concreteBNGeneratorSubgroup = ⊤) :
    concreteBruhatCovering = Set.univ := by
  ext g
  simp only [Set.mem_univ, iff_true]
  apply concreteBNGeneratorSubgroup_le_concreteBruhatCovering htransition g
  rw [hgen]
  exact Subgroup.mem_top g

end InfoGeometry.Algebra.Zorn.G2ConcreteBNBruhatExhaustion
