import InfoGeometry.Algebra.Zorn.G2ConcreteBN2CorrectSecondConjugation
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Algebra.Zorn.G2TwoPCSubgroupClosure
import InfoGeometry.Algebra.Zorn.G2TwoPCConcreteCollector
import InfoGeometry.Algebra.Zorn.G2TwoPCConcreteFacts

/-!
# Exact size of the corrected complementary PC subgroup

The subgroup generated by PC generators `1,...,5` is identified structurally
with the six-bit PC words whose zeroth coordinate is false.  No enumeration of
automorphisms is used: closure is obtained from the PC multiplication and
inverse normal-form laws.
-/

namespace InfoGeometry.Algebra.Zorn.G2CorrectedTComplementCard

open InfoGeometry.Algebra.Zorn.G2ConcreteBN2CorrectSecondConjugation
open InfoGeometry.Algebra.Zorn.G2TwoPCSubgroupClosure
open InfoGeometry.Algebra.Zorn.G2TwoPCNormalForm
open InfoGeometry.Algebra.Zorn.G2TwoPCConcreteCollector
open InfoGeometry.Algebra.Zorn.G2TwoPCConcreteFacts
open InfoGeometry.Algebra.Zorn.G2TwoSylowSubgroup
open InfoGeometry.OperatorAlgebra.G2TwoAutomorphismTheorem

def zeroBitPCSubgroup : Subgroup SplitOctF2Aut where
  carrier := {x | ∃ e : PCExponent, e 0 = false ∧ pcWord e = x}
  one_mem' := by
    refine ⟨zeroPC, ?_, ?_⟩
    · rfl
    · exact pcWord_zero_eq_one
  mul_mem' := by
    intro x y hx hy
    rcases hx with ⟨e, he, rfl⟩
    rcases hy with ⟨f, hf, rfl⟩
    refine ⟨pcCombine e f, ?_, ?_⟩
    · simp [pcCombine_apply_zero, he, hf]
    · exact (pcWord_mul_pcWord e f).symm
  inv_mem' := by
    intro x hx
    rcases hx with ⟨e, he, rfl⟩
    refine ⟨pcInverse e, ?_, ?_⟩
    · simpa [pcInverse_apply_zero] using he
    · exact (pcWord_inv e).symm

theorem zeroBitPCSubgroup_eq_correctedTComplementSubgroup :
    zeroBitPCSubgroup = correctedTComplementSubgroup := by
  apply le_antisymm
  · intro x hx
    rcases hx with ⟨e, he, rfl⟩
    exact pcWord_mem_correctedTComplement e he
  · refine (Subgroup.closure_le _).2 ?_
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl | rfl | rfl
    · exact ⟨oneAtBit 1 true, by decide, by
        simpa [pcWord_oneAtBit] using (pcWord_oneAt_eq_generator 1).symm⟩
    · exact ⟨oneAtBit 2 true, by decide, by
        simpa [pcWord_oneAtBit] using (pcWord_oneAt_eq_generator 2).symm⟩
    · exact ⟨oneAtBit 3 true, by decide, by
        simpa [pcWord_oneAtBit] using (pcWord_oneAt_eq_generator 3).symm⟩
    · exact ⟨oneAtBit 4 true, by decide, by
        simpa [pcWord_oneAtBit] using (pcWord_oneAt_eq_generator 4).symm⟩
    · exact ⟨oneAtBit 5 true, by decide, by
        simpa [pcWord_oneAtBit] using (pcWord_oneAt_eq_generator 5).symm⟩

theorem correctedTComplementSubgroup_card :
    Nat.card correctedTComplementSubgroup = 32 := by
  rw [← zeroBitPCSubgroup_eq_correctedTComplementSubgroup]
  letI : Fintype zeroBitPCSubgroup := Fintype.ofFinite _
  let E := {e : PCExponent // e 0 = false}
  let f : E → zeroBitPCSubgroup := fun e =>
    ⟨pcWord e.1, ⟨e.1, e.2, rfl⟩⟩
  have hf : Function.Injective f := by
    intro e₁ e₂ h
    apply Subtype.ext
    apply pcWord_injective
    exact congrArg Subtype.val h
  have hsurj : Function.Surjective f := by
    intro x
    rcases x.2 with ⟨e, he, hxe⟩
    refine ⟨⟨e, he⟩, ?_⟩
    apply Subtype.ext
    exact hxe
  have heq : E ≃ zeroBitPCSubgroup :=
    Equiv.ofBijective f ⟨hf, hsurj⟩
  have hc : Fintype.card E = 32 := by decide
  calc
    Nat.card zeroBitPCSubgroup = Fintype.card zeroBitPCSubgroup :=
      Nat.card_eq_fintype_card
    _ = Fintype.card E := Fintype.card_congr heq.symm
    _ = 32 := hc

end InfoGeometry.Algebra.Zorn.G2CorrectedTComplementCard
