import InfoGeometry.Algebra.Zorn.G2TwoSylowPCGenerators
import InfoGeometry.Algebra.Zorn.G2TwoSylowPCAutomorphisms

namespace InfoGeometry.Algebra.Zorn.G2TwoSylowSubgroup

open InfoGeometry.OperatorAlgebra.G2TwoAutomorphismTheorem
open InfoGeometry.Algebra.Zorn.G2TwoSylowPCGenerators (pc1Fun pc2Fun pc3Fun pc4Fun pc5Fun pc6Fun)
open InfoGeometry.Algebra.Zorn.G2TwoSylowPCAutomorphisms

/-- A boolean exponent choice for the 6 PC generators. -/
abbrev PCWordExp := Fin 6 → Bool

def pcTerm (i : Fin 6) (b : Bool) : SplitOctF2Aut :=
  if b then pcGenerator i else 1

/-- The ordered polycyclic normal form word p1^e0 * p2^e1 * p3^e2 * p4^e3 * p5^e4 * p6^e5. -/
def pcWord (e : PCWordExp) : SplitOctF2Aut :=
  pcTerm 0 (e 0) * pcTerm 1 (e 1) * pcTerm 2 (e 2) *
  pcTerm 3 (e 3) * pcTerm 4 (e 4) * pcTerm 5 (e 5)

/-- The 2-Sylow subgroup generated by the 6 polycyclic generators. -/
def sylowTwoSubgroup : Subgroup SplitOctF2Aut :=
  Subgroup.closure (Set.range pcGenerator)

theorem pcTerm_mem_sylow (i : Fin 6) (b : Bool) :
    pcTerm i b ∈ sylowTwoSubgroup := by
  dsimp [pcTerm]
  split_ifs
  · exact Subgroup.subset_closure ⟨i, rfl⟩
  · exact Subgroup.one_mem _

/-- Every PC word belongs to the 2-Sylow subgroup. -/
theorem pcWord_mem_sylow (e : PCWordExp) : pcWord e ∈ sylowTwoSubgroup := by
  dsimp [pcWord]
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ (Subgroup.mul_mem _
    (Subgroup.mul_mem _ (Subgroup.mul_mem _
      (pcTerm_mem_sylow 0 (e 0)) (pcTerm_mem_sylow 1 (e 1)))
      (pcTerm_mem_sylow 2 (e 2))) (pcTerm_mem_sylow 3 (e 3)))
      (pcTerm_mem_sylow 4 (e 4))) (pcTerm_mem_sylow 5 (e 5))

/-- The domain of 6-bit exponents has cardinality 64. -/
theorem pcWordExp_card : Fintype.card PCWordExp = 64 := by
  rw [Fintype.card_fun, Fintype.card_fin, Fintype.card_bool]
  norm_num

/-- Term action on SplitOctF2. -/
def pcTermFun (i : Fin 6) (b : Bool) (X : SplitOctF2) : SplitOctF2 :=
  if b then
    match i with
    | 0 => pc1Fun X
    | 1 => pc2Fun X
    | 2 => pc3Fun X
    | 3 => pc4Fun X
    | 4 => pc5Fun X
    | 5 => pc6Fun X
  else X

theorem pcTerm_apply (i : Fin 6) (b : Bool) (X : SplitOctF2) :
    (pcTerm i b).1 X = pcTermFun i b X := by
  dsimp [pcTerm, pcTermFun, pcGenerator, pc1Aut, pc2Aut, pc3Aut, pc4Aut, pc5Aut, pc6Aut,
    involutiveEquiv, pc2Equiv, pc3Equiv]
  cases b
  · rfl
  · fin_cases i <;> rfl

/-- Computable action of PC word on SplitOctF2. -/
def pcWordFun (e : PCWordExp) (X : SplitOctF2) : SplitOctF2 :=
  pcTermFun 5 (e 5) (pcTermFun 4 (e 4) (pcTermFun 3 (e 3)
    (pcTermFun 2 (e 2) (pcTermFun 1 (e 1) (pcTermFun 0 (e 0) X)))))

theorem aut_mul_apply (g h : SplitOctF2Aut) (X : SplitOctF2) :
    (g * h).1 X = h.1 (g.1 X) := rfl

theorem pcWord_apply (e : PCWordExp) (X : SplitOctF2) :
    (pcWord e).1 X = pcWordFun e X := by
  dsimp [pcWord, pcWordFun]
  repeat rw [aut_mul_apply]
  repeat rw [pcTerm_apply]

/-- The concrete 8-basis action of each PC exponent word. -/
def basisAction (e : PCWordExp) : Fin 8 → SplitOctF2 :=
  fun i => pcWordFun e (basis8 i)

/-- Structural coordinate recovery functions on basisAction. -/
def recover0 (A : Fin 8 → SplitOctF2) : Bool := (A 7).x0
def recover1 (A : Fin 8 → SplitOctF2) : Bool := (A 2).x1
def recover2 (A : Fin 8 → SplitOctF2) : Bool := (A 2).a
def recover4 (A : Fin 8 → SplitOctF2) : Bool :=
  let b1 := recover1 A
  let b2 := recover2 A
  (A 2).y1 ^^ b1 ^^ b2
def recover3 (A : Fin 8 → SplitOctF2) : Bool :=
  let b0 := recover0 A
  let b1 := recover1 A
  let b2 := recover2 A
  let b4 := recover4 A
  (A 3).x2 ^^ (b0 && b2) ^^ b0 ^^ b1 ^^ b2 ^^ b4
def recover5 (A : Fin 8 → SplitOctF2) : Bool :=
  let b1 := recover1 A
  let b3 := recover3 A
  let b4 := recover4 A
  (A 2).x2 ^^ (b1 && b3) ^^ (b1 && b4)

theorem recover0_basisAction (e : PCWordExp) :
    recover0 (basisAction e) = e 0 := by
  dsimp [recover0, basisAction, pcWordFun, pcTermFun, basis8]
  rcases e 0 with _|_ <;> rcases e 1 with _|_ <;> rcases e 2 with _|_ <;>
  rcases e 3 with _|_ <;> rcases e 4 with _|_ <;> rcases e 5 with _|_ <;> rfl

theorem recover1_basisAction (e : PCWordExp) :
    recover1 (basisAction e) = e 1 := by
  dsimp [recover1, basisAction, pcWordFun, pcTermFun, basis8]
  rcases e 0 with _|_ <;> rcases e 1 with _|_ <;> rcases e 2 with _|_ <;>
  rcases e 3 with _|_ <;> rcases e 4 with _|_ <;> rcases e 5 with _|_ <;> rfl

theorem recover2_basisAction (e : PCWordExp) :
    recover2 (basisAction e) = e 2 := by
  dsimp [recover2, basisAction, pcWordFun, pcTermFun, basis8]
  rcases e 0 with _|_ <;> rcases e 1 with _|_ <;> rcases e 2 with _|_ <;>
  rcases e 3 with _|_ <;> rcases e 4 with _|_ <;> rcases e 5 with _|_ <;> rfl

theorem recover4_basisAction (e : PCWordExp) :
    recover4 (basisAction e) = e 4 := by
  dsimp [recover4, recover1, recover2, basisAction, pcWordFun, pcTermFun, basis8]
  rcases e 0 with _|_ <;> rcases e 1 with _|_ <;> rcases e 2 with _|_ <;>
  rcases e 3 with _|_ <;> rcases e 4 with _|_ <;> rcases e 5 with _|_ <;> rfl

theorem recover3_basisAction (e : PCWordExp) :
    recover3 (basisAction e) = e 3 := by
  dsimp [recover3, recover4, recover0, recover1, recover2, basisAction, pcWordFun, pcTermFun, basis8]
  rcases e 0 with _|_ <;> rcases e 1 with _|_ <;> rcases e 2 with _|_ <;>
  rcases e 3 with _|_ <;> rcases e 4 with _|_ <;> rcases e 5 with _|_ <;> rfl

theorem recover5_basisAction (e : PCWordExp) :
    recover5 (basisAction e) = e 5 := by
  dsimp [recover5, recover3, recover4, recover0, recover1, recover2, basisAction, pcWordFun, pcTermFun, basis8]
  rcases e 0 with _|_ <;> rcases e 1 with _|_ <;> rcases e 2 with _|_ <;>
  rcases e 3 with _|_ <;> rcases e 4 with _|_ <;> rcases e 5 with _|_ <;> rfl

/-- 🏆 THEOREM: The 64 PC basis actions are 100% distinct (injective) by structural recovery. -/
theorem basisAction_injective : Function.Injective basisAction := by
  intro e1 e2 h
  have h0 : e1 0 = e2 0 := by rw [← recover0_basisAction e1, ← recover0_basisAction e2, h]
  have h1 : e1 1 = e2 1 := by rw [← recover1_basisAction e1, ← recover1_basisAction e2, h]
  have h2 : e1 2 = e2 2 := by rw [← recover2_basisAction e1, ← recover2_basisAction e2, h]
  have h3 : e1 3 = e2 3 := by rw [← recover3_basisAction e1, ← recover3_basisAction e2, h]
  have h4 : e1 4 = e2 4 := by rw [← recover4_basisAction e1, ← recover4_basisAction e2, h]
  have h5 : e1 5 = e2 5 := by rw [← recover5_basisAction e1, ← recover5_basisAction e2, h]
  ext i
  fin_cases i
  · exact h0
  · exact h1
  · exact h2
  · exact h3
  · exact h4
  · exact h5

theorem pcWord_apply_basis (e : PCWordExp) (i : Fin 8) :
    (pcWord e).1 (basis8 i) = basisAction e i := by
  dsimp [basisAction]
  rw [pcWord_apply]

theorem pcWord_injective : Function.Injective pcWord := by
  intro e1 e2 h
  apply basisAction_injective
  funext i
  have hi : (pcWord e1).1 (basis8 i) = (pcWord e2).1 (basis8 i) := by
    rw [h]
  rw [pcWord_apply_basis, pcWord_apply_basis] at hi
  exact hi

/-- 🏆 THEOREM: The image of pcWord in SplitOctF2Aut has cardinality exactly 64. -/
theorem pcWord_range_card :
    Nat.card (Set.range pcWord) = 64 := by
  rw [Nat.card_range_of_injective pcWord_injective, Nat.card_eq_fintype_card, pcWordExp_card]

end InfoGeometry.Algebra.Zorn.G2TwoSylowSubgroup
