import Mathlib

/-!
# Two-sheet Krein ideal transport

This file records the finite algebraic consequence of a fundamental symmetry
which exchanges two idempotents.  It deliberately does not identify a
particular Clifford algebra with a chiral carrier; that is a separate bridge.
The statements below determine the transported principal ideals without
assuming their codomains.
-/

namespace InfoGeometry.Krein

section

variable {A : Type*} [Monoid A]

/-- The left principal ideal generated by an element. -/
def leftPrincipal (f : A) : Set A := {x | ∃ a : A, a * f = x}

/-- The right principal ideal generated by an element. -/
def rightPrincipal (f : A) : Set A := {x | ∃ a : A, f * a = x}

/-- A Peirce corner cut out by a pair of idempotent-side markers. -/
def peirceCorner (fleft fright : A) : Set A :=
  {x | fleft * x * fright = x}

/-- Conjugation by an involutive algebra element. -/
def kreinConjugate (eta x : A) : A := eta * x * eta

theorem kreinConjugate_involutive
    (eta : A) (hη : eta * eta = 1) (x : A) :
    kreinConjugate eta (kreinConjugate eta x) = x := by
  simp only [kreinConjugate]
  calc
    eta * (eta * x * eta) * eta = (eta * eta) * x * (eta * eta) := by
      simp only [mul_assoc]
    _ = x := by simp [hη]

theorem kreinConjugate_mul
    (eta : A) (hη : eta * eta = 1) (x y : A) :
    kreinConjugate eta (x * y) =
      kreinConjugate eta x * kreinConjugate eta y := by
  simp only [kreinConjugate]
  symm
  calc
    eta * x * eta * (eta * y * eta) =
        eta * x * (eta * eta) * y * eta := by simp only [mul_assoc]
    _ = eta * (x * y) * eta := by rw [hη, mul_one]; simp only [mul_assoc]

theorem kreinConjugate_leftPrincipal_mem
    (eta fplus fminus : A)
    (hη : eta * eta = 1)
    (hex : eta * fplus * eta = fminus)
    {x : A} (hx : x ∈ leftPrincipal fplus) :
    kreinConjugate eta x ∈ leftPrincipal fminus := by
  rcases hx with ⟨a, rfl⟩
  refine ⟨eta * a * eta, ?_⟩
  calc
    (eta * a * eta) * fminus =
        (eta * a * eta) * (eta * fplus * eta) := by rw [hex]
    _ = eta * (a * fplus) * eta := by
      calc
        eta * a * eta * (eta * fplus * eta) =
            eta * a * (eta * eta) * (fplus * eta) := by
              simp only [mul_assoc]
        _ = eta * a * (fplus * eta) := by rw [hη, mul_one]
        _ = eta * (a * fplus) * eta := by simp only [mul_assoc]

theorem kreinConjugate_rightPrincipal_mem
    (eta fplus fminus : A)
    (hη : eta * eta = 1)
    (hex : eta * fplus * eta = fminus)
    {x : A} (hx : x ∈ rightPrincipal fplus) :
    kreinConjugate eta x ∈ rightPrincipal fminus := by
  rcases hx with ⟨a, rfl⟩
  refine ⟨eta * a * eta, ?_⟩
  calc
    fminus * (eta * a * eta) =
        (eta * fplus * eta) * (eta * a * eta) := by rw [hex]
    _ = eta * (fplus * a) * eta := by
      calc
        eta * fplus * eta * (eta * a * eta) =
            eta * fplus * (eta * eta) * (a * eta) := by
              simp only [mul_assoc]
        _ = eta * fplus * (a * eta) := by rw [hη, mul_one]
        _ = eta * (fplus * a) * eta := by simp only [mul_assoc]

theorem kreinConjugate_leftPrincipal_iff
    (eta fplus fminus : A)
    (hη : eta * eta = 1)
    (hex : eta * fplus * eta = fminus)
    {x : A} :
    x ∈ leftPrincipal fplus ↔ kreinConjugate eta x ∈ leftPrincipal fminus := by
  constructor
  · exact kreinConjugate_leftPrincipal_mem eta fplus fminus hη hex
  · intro hx
    have hback := kreinConjugate_leftPrincipal_mem eta fminus fplus hη (by
      calc
        eta * fminus * eta = eta * (eta * fplus * eta) * eta := by rw [hex]
        _ = fplus := by
          calc
            eta * (eta * fplus * eta) * eta = (eta * eta) * fplus * (eta * eta) := by
              simp only [mul_assoc]
            _ = fplus := by simp [hη]) hx
    rw [kreinConjugate_involutive eta hη x] at hback
    exact hback

theorem kreinConjugate_peirceCorner_mem
    (eta fplus fminus : A)
    (hη : eta * eta = 1)
    (hplus : eta * fplus * eta = fminus)
    (hminus : eta * fminus * eta = fplus)
    {x : A} (hx : x ∈ peirceCorner fplus fminus) :
    kreinConjugate eta x ∈ peirceCorner fminus fplus := by
  change fminus * kreinConjugate eta x * fplus = kreinConjugate eta x
  change fminus * (eta * x * eta) * fplus = eta * x * eta
  calc
    fminus * (eta * x * eta) * fplus =
        (eta * fplus * eta) * (eta * x * eta) *
          (eta * fminus * eta) := by rw [hplus, hminus]
    _ = eta * (fplus * x * fminus) * eta := by
      calc
        eta * fplus * eta * (eta * x * eta) *
              (eta * fminus * eta) =
            eta * fplus * (eta * eta) * x *
              (eta * eta) * fminus * eta := by
                simp only [mul_assoc]
        _ = eta * (fplus * x * fminus) * eta := by
          rw [hη, mul_one]
          simp [mul_assoc]
    _ = eta * x * eta := by rw [hx]

theorem kreinConjugate_peirceCorner_iff
    (eta fplus fminus : A)
    (hη : eta * eta = 1)
    (hplus : eta * fplus * eta = fminus)
    (hminus : eta * fminus * eta = fplus)
    {x : A} :
    x ∈ peirceCorner fplus fminus ↔
      kreinConjugate eta x ∈ peirceCorner fminus fplus := by
  constructor
  · exact kreinConjugate_peirceCorner_mem eta fplus fminus hη hplus hminus
  · intro hx
    have hback := kreinConjugate_peirceCorner_mem
      eta fminus fplus hη hminus hplus hx
    rw [kreinConjugate_involutive eta hη x] at hback
    exact hback

end

end InfoGeometry.Krein
