import Mathlib

/-!
# Mapping-torus gluing data

This file owns only the quotient-level construction.  It does not assert that
the quotient is nonorientable, a Klein bottle, or anomaly-free.  Those claims
require additional geometric and operator-theoretic hypotheses.
-/

namespace InfoGeometry.Topology.MappingTorusGluing

universe u

variable {F : Type u}

/-- The endpoint gluing relation generated by a self-map of the fibre. -/
def endpointStep (f : F → F) (p q : ℝ × F) : Prop :=
    (p.1 = 0 ∧ q.1 = 1 ∧ q.2 = f p.2) ∨
    (p.1 = 1 ∧ q.1 = 0 ∧ p.2 = f q.2)

def endpointRelation (f : F → F) : Setoid (ℝ × F) where
  r := Relation.EqvGen (endpointStep f)
  iseqv := Relation.EqvGen.is_equivalence (endpointStep f)

/-- The mapping-torus quotient associated with a fibre self-map. -/
def mappingTorus (f : F → F) : Type u :=
  @Quotient (ℝ × F) (endpointRelation f)

/-- The canonical projection into the mapping-torus quotient. -/
def mappingTorusMk (f : F → F) : ℝ × F → mappingTorus f :=
  fun x => @Quotient.mk (ℝ × F) (endpointRelation f) x

theorem mappingTorusMk_eq
    (f : F → F) (x : ℝ × F) :
    mappingTorusMk f x = @Quotient.mk (ℝ × F) (endpointRelation f) x :=
  rfl

/-- The endpoint identification defining the mapping torus. -/
theorem mappingTorus_endpoint
    (f : F → F) (x : F) :
    mappingTorusMk f (0, x) = mappingTorusMk f (1, f x) := by
  apply Quotient.sound
  exact Relation.EqvGen.rel _ _ (Or.inl ⟨rfl, rfl, rfl⟩)

/-- A supplied involution gives an order-two gluing datum. -/
structure InvolutiveGluing where
  map : F → F
  involutive : Function.Involutive map

namespace InvolutiveGluing

/-- The mapping torus attached to an involutive gluing map. -/
def torus (g : InvolutiveGluing (F := F)) : Type u :=
  mappingTorus g.map

theorem endpoint (g : InvolutiveGluing (F := F)) (x : F) :
    mappingTorusMk g.map (0, x) = mappingTorusMk g.map (1, g.map x) :=
  mappingTorus_endpoint g.map x

theorem map_map (g : InvolutiveGluing (F := F)) (x : F) :
    g.map (g.map x) = x :=
  g.involutive x

end InvolutiveGluing

end InfoGeometry.Topology.MappingTorusGluing
