import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Ring

set_option autoImplicit false

/-!
# InfoGeometry.Prequantum.FiniteSymmetryAtoms

Small finite symmetry atoms extracted from larger physics-motivated snippets.

The scope is deliberately finite and algebraic:

* the `2π` return of a coordinate `U(1)` circle;
* invariance of the concrete Minkowski interval under total sign inversion;
* the generic algebraic order reversal of `X ↦ J * X * J` when `J² = 1`;
* the algebraic polarization identity for an explicitly additive symmetric
  bilinear readout.

This module is only a finite algebraic atom layer.  Broader CPT,
Tomita--Takesaki, holographic, KMS, and modular-flow statements are owned by
other repository modules and are not re-proved here.
-/

noncomputable section

namespace InfoGeometry.Prequantum.FiniteSymmetryAtoms

/-- Real coordinate proxy for a unit complex number. -/
@[ext]
structure HestenesComplex where
  /-- Real coordinate. -/
  re : ℝ
  /-- Imaginary coordinate. -/
  im : ℝ

instance : One HestenesComplex where
  one := ⟨1, 0⟩

/-- Coordinate circle flow `θ ↦ (cos θ, sin θ)`. -/
def ellipticFlow (θ : ℝ) : HestenesComplex :=
  ⟨Real.cos θ, Real.sin θ⟩

/-- A full `2π` turn returns the coordinate circle flow to `(1,0)`. -/
theorem master_loop_holonomy :
    ellipticFlow (2 * Real.pi) = 1 := by
  change ⟨Real.cos (2 * Real.pi), Real.sin (2 * Real.pi)⟩ =
    (⟨1, 0⟩ : HestenesComplex)
  ext <;> simp [Real.cos_two_pi, Real.sin_two_pi]

/-- Four-coordinate real spacetime slice with `(+---)` interval. -/
structure RealSpacetime4 where
  t : ℝ
  x : ℝ
  y : ℝ
  z : ℝ

/-- The concrete `(+---)` interval readout. -/
def interval (X : RealSpacetime4) : ℝ :=
  X.t ^ 2 - X.x ^ 2 - X.y ^ 2 - X.z ^ 2

/-- Total sign inversion on the finite spacetime slice. -/
def spaceTimeInversion (X : RealSpacetime4) : RealSpacetime4 :=
  ⟨-X.t, -X.x, -X.y, -X.z⟩

/-- Total sign inversion preserves the concrete `(+---)` interval. -/
theorem inversion_preserves_interval (X : RealSpacetime4) :
    interval (spaceTimeInversion X) = interval X := by
  unfold interval spaceTimeInversion
  ring

/-- Algebraic mirror/conjugation map `X ↦ J * X * J`. -/
def modularMirror {A : Type*} [Mul A] (J X : A) : A :=
  J * X * J

/-- In any monoid, `X ↦ J * X * J` reverses products when `J² = 1`. -/
theorem modularMirror_reverse_mul {A : Type*} [Monoid A]
    (J X Y : A) (hJ : J * J = 1) :
    modularMirror J Y * modularMirror J X = modularMirror J (Y * X) := by
  unfold modularMirror
  calc
    (J * Y * J) * (J * X * J) = J * Y * (J * J) * X * J := by
      simp [mul_assoc]
    _ = J * Y * 1 * X * J := by rw [hJ]
    _ = J * (Y * X) * J := by simp [mul_assoc]

/-- Ring commutator, used as a finite algebraic modular-flow generator. -/
def ringCommutator {A : Type*} [Mul A] [Sub A] (K X : A) : A :=
  K * X - X * K

/--
Equivariance of the finite commutator-flow generator under the algebraic mirror
`X ↦ γ * X * γ`, assuming `γ² = 1`.

This is a finite covariance identity for the generator.  Analytic/KMS/modular
flow statements are owned by the Krein/Canonical/OperatorAlgebra modules and are
not re-proved by this local atom.
-/
theorem modularMirror_commutator_equivariance {A : Type*} [Ring A]
    (γ K X : A) (hγ : γ * γ = 1) :
    modularMirror γ (ringCommutator K X) =
      ringCommutator (modularMirror γ K) (modularMirror γ X) := by
  unfold modularMirror ringCommutator
  have h1 : (γ * K * γ) * (γ * X * γ) = γ * K * X * γ := by
    calc
      (γ * K * γ) * (γ * X * γ) = γ * K * (γ * γ) * X * γ := by
        simp [mul_assoc]
      _ = γ * K * 1 * X * γ := by rw [hγ]
      _ = γ * K * X * γ := by simp [mul_assoc]
  have h2 : (γ * X * γ) * (γ * K * γ) = γ * X * K * γ := by
    calc
      (γ * X * γ) * (γ * K * γ) = γ * X * (γ * γ) * K * γ := by
        simp [mul_assoc]
      _ = γ * X * 1 * K * γ := by rw [hγ]
      _ = γ * X * K * γ := by simp [mul_assoc]
  rw [h1, h2]
  rw [mul_sub, sub_mul]
  simp [mul_assoc]

/-- If both the generator and the state are mirror-fixed, their commutator is mirror-fixed. -/
theorem modularMirror_commutator_fixed {A : Type*} [Ring A]
    (γ K X : A) (hγ : γ * γ = 1)
    (hK : modularMirror γ K = K) (hX : modularMirror γ X = X) :
    modularMirror γ (ringCommutator K X) = ringCommutator K X := by
  rw [modularMirror_commutator_equivariance γ K X hγ, hK, hX]

/-- Quadratic readout generated by a bilinear metric-like function. -/
def quadraticForm {V : Type*} (g : V → V → ℝ) (x : V) : ℝ :=
  g x x

/-- Polarization identity for an explicitly additive symmetric real pairing. -/
theorem polarization_identity {V : Type*} [Add V]
    (g : V → V → ℝ)
    (add_left : ∀ x₁ x₂ y, g (x₁ + x₂) y = g x₁ y + g x₂ y)
    (add_right : ∀ x y₁ y₂, g x (y₁ + y₂) = g x y₁ + g x y₂)
    (symm : ∀ x y, g x y = g y x) (x y : V) :
    quadraticForm g (x + y) - quadraticForm g x - quadraticForm g y = 2 * g x y := by
  unfold quadraticForm
  rw [add_left, add_right, add_right]
  rw [symm y x]
  ring

end InfoGeometry.Prequantum.FiniteSymmetryAtoms
