import Mathlib.Algebra.Algebra.Basic
import Mathlib.Algebra.Star.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Real.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

/-!
# Finite 1-Parameter Modular Automorphism Flow on CAR Generators

Formalizes the finite unitary modular flow generated by the chiral Hamiltonian
`K_β = β • Γ` on the CAR algebra generators `c, c†`:

  `σ_t(c)  = cos(2βt) • c  + i sin(2βt) • (Γ * c)`
  `σ_t(c†) = cos(2βt) • c† + i sin(2βt) • (Γ * c†)`

Mathematical components:
  1. Unitary rotation element: `u(θ) = cos(θ) • 1 + i sin(θ) • Γ` with `θ = βt`.
  2. Parity reflection identities: `(Γ * c) * Γ = -c` and `Γ * (Γ * c) = c`.
  3. Sandwich modular flow: `σ_t(c) = u(θ) * c * u(-θ)`.
  4. Exact reduction to `cos(2θ) • c + i sin(2θ) • (Γ * c)` via double-angle relations.
  5. 1-Parameter group law: `σ_{s+t}(c) = σ_s(σ_t(c))`.
  6. Invariance of the number operator: `σ_t(N) = N`.

All proofs are complete in native Mathlib with 0 `sorry`s and 0 custom axioms.
-/

noncomputable section

namespace InfoGeometry.Modular.CARModularFlow

open Complex

variable {A : Type*} [Ring A] [Algebra ℂ A] [StarRing A] [StarModule ℂ A]

/-! =========================================================================
    1. Single-Mode CAR Operator System with Parity Involution Γ
    ========================================================================= -/

/-- Single-mode CAR generator system `(c, c†, Γ)` with grading involution relations. -/
structure SingleModeCAR (A : Type*) [Ring A] [Algebra ℂ A] where
  c : A
  c_dag : A
  Gamma : A
  gamma_sq : Gamma * Gamma = 1
  anticomm_c : Gamma * c = - (c * Gamma)
  anticomm_cdag : Gamma * c_dag = - (c_dag * Gamma)
  car_anticomm : c * c_dag + c_dag * c = 1
  c_nilpotent : c * c = 0
  cdag_nilpotent : c_dag * c_dag = 0

variable (car : SingleModeCAR A)

/-- Fermion number operator `N = c† * c`. -/
def numberOp : A :=
  car.c_dag * car.c

/-! =========================================================================
    2. Parity Reflection Identities on Odd CAR Elements
    ========================================================================= -/

/-- LEMMA: `c * Γ = - (Γ * c)`. -/
theorem c_mul_gamma : car.c * car.Gamma = - (car.Gamma * car.c) := by
  have h := car.anticomm_c
  rw [h, neg_neg]

/-- LEMMA: `(Γ * c) * Γ = - car.c`. -/
theorem gamma_c_mul_gamma : (car.Gamma * car.c) * car.Gamma = - car.c := by
  rw [mul_assoc, c_mul_gamma, mul_neg, ← mul_assoc, car.gamma_sq, one_mul]

/-- LEMMA: `Γ * (Γ * c) = car.c`. -/
theorem gamma_mul_gamma_c : car.Gamma * (car.Gamma * car.c) = car.c := by
  rw [← mul_assoc, car.gamma_sq, one_mul]

/-- LEMMA: `c_dag * Γ = - (Γ * c_dag)`. -/
theorem cdag_mul_gamma : car.c_dag * car.Gamma = - (car.Gamma * car.c_dag) := by
  have h := car.anticomm_cdag
  rw [h, neg_neg]

/-- LEMMA: `(Γ * c_dag) * Γ = - car.c_dag`. -/
theorem gamma_cdag_mul_gamma : (car.Gamma * car.c_dag) * car.Gamma = - car.c_dag := by
  rw [mul_assoc, cdag_mul_gamma, mul_neg, ← mul_assoc, car.gamma_sq, one_mul]

/-- LEMMA: `Γ * (Γ * c_dag) = car.c_dag`. -/
theorem gamma_mul_gamma_cdag : car.Gamma * (car.Gamma * car.c_dag) = car.c_dag := by
  rw [← mul_assoc, car.gamma_sq, one_mul]

/-! =========================================================================
    3. Unitary Rotation Curve u(θ) = cos(θ) • 1 + i sin(θ) • Γ
    ========================================================================= -/

/-- Unitary operator `u(θ) = cos(θ) • 1 + i sin(θ) • Γ`. -/
def chiralUnitary (theta : ℝ) : A :=
  ((Real.cos theta : ℂ) • (1 : A)) + (Complex.I * (Real.sin theta : ℂ)) • car.Gamma

/-- The sandwich modular evolution: `σ_θ(x) = u(θ) * x * u(-θ)`. -/
def modularSandwich (theta : ℝ) (x : A) : A :=
  chiralUnitary car theta * x * chiralUnitary car (-theta)

/-- Explicit 2-mode chiral rotation formula. -/
def chiralFlowExplicit (x gamma_x : A) (theta : ℝ) : A :=
  ((Real.cos (2 * theta) : ℂ) • x) + (Complex.I * (Real.sin (2 * theta) : ℂ)) • gamma_x

/-! =========================================================================
    4. Exact Reduction: Sandwich Flow = Explicit Trigonometric Flow
    ========================================================================= -/

theorem cos_two_theta (theta : ℝ) :
    (Real.cos (2 * theta) : ℂ) =
      (Real.cos theta : ℂ) ^ 2 - (Real.sin theta : ℂ) ^ 2 := by
  have h : 2 * theta = theta + theta := by ring
  rw [h, Real.cos_add]
  push_cast
  ring

theorem sin_two_theta (theta : ℝ) :
    (Real.sin (2 * theta) : ℂ) =
      2 * (Real.sin theta : ℂ) * (Real.cos theta : ℂ) := by
  have h : 2 * theta = theta + theta := by ring
  rw [h, Real.sin_add]
  push_cast
  ring

theorem prod_gamma (a1 b1 a2 b2 : ℂ) :
    (a1 • (1 : A) + b1 • car.Gamma) * (a2 • (1 : A) + b2 • car.Gamma) =
    (a1 * a2 + b1 * b2) • (1 : A) + (a1 * b2 + b1 * a2) • car.Gamma := by
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm, one_mul, mul_one,
             car.gamma_sq, smul_add, smul_smul, add_smul]
  have h1 : a2 * a1 = a1 * a2 := mul_comm a2 a1
  have h2 : a2 * b1 = b1 * a2 := mul_comm a2 b1
  have h3 : b2 * a1 = a1 * b2 := mul_comm b2 a1
  have h4 : b2 * b1 = b1 * b2 := mul_comm b2 b1
  rw [h1, h2, h3, h4]
  abel

theorem sandwich_odd_gamma (a1 b1 a2 b2 : ℂ) (x : A)
    (h_anticomm : car.Gamma * x = - (x * car.Gamma)) :
    (a1 • (1 : A) + b1 • car.Gamma) * x * (a2 • (1 : A) + b2 • car.Gamma) =
    (a1 * a2 - b1 * b2) • x + (a1 * b2 - b1 * a2) • (x * car.Gamma) := by
  have h_x_gamma : car.Gamma * x = - (x * car.Gamma) := h_anticomm
  have h_x_gamma_sq : (x * car.Gamma) * car.Gamma = x := by
    rw [mul_assoc, car.gamma_sq, mul_one]
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm, one_mul, mul_one,
             h_x_gamma, h_x_gamma_sq, smul_add, smul_smul, sub_smul,
             neg_mul, smul_neg]
  have h1 : a2 * a1 = a1 * a2 := mul_comm a2 a1
  have h2 : a2 * b1 = b1 * a2 := mul_comm a2 b1
  have h3 : b2 * a1 = a1 * b2 := mul_comm b2 a1
  have h4 : b2 * b1 = b1 * b2 := mul_comm b2 b1
  rw [h1, h2, h3, h4]
  abel

/-- Helper formula for expanding u(θ) * x * u(-θ) on odd generators. -/
theorem modularSandwich_odd (x : A) (h_anticomm : car.Gamma * x = - (x * car.Gamma)) (theta : ℝ) :
    modularSandwich car theta x =
      ((Real.cos (2 * theta) : ℂ) • x) + (Complex.I * (Real.sin (2 * theta) : ℂ)) • (car.Gamma * x) := by
  change (((Real.cos theta : ℂ) • (1 : A)) + (Complex.I * (Real.sin theta : ℂ)) • car.Gamma) * x *
         (((Real.cos (-theta) : ℂ) • (1 : A)) + (Complex.I * (Real.sin (-theta) : ℂ)) • car.Gamma) =
         ((Real.cos (2 * theta) : ℂ) • x) + (Complex.I * (Real.sin (2 * theta) : ℂ)) • (car.Gamma * x)
  rw [sandwich_odd_gamma car]
  have h_cos_neg : (Real.cos (-theta) : ℂ) = (Real.cos theta : ℂ) := by rw [Real.cos_neg]
  have h_sin_neg : (Real.sin (-theta) : ℂ) = - (Real.sin theta : ℂ) := by rw [Real.sin_neg]; push_cast; rfl
  rw [h_cos_neg, h_sin_neg]
  have h_x_gamma : x * car.Gamma = - (car.Gamma * x) := by rw [h_anticomm, neg_neg]
  rw [h_x_gamma, smul_neg, ← sub_eq_add_neg]
  have h_i_sq : Complex.I ^ 2 = -1 := Complex.I_sq
  have h_x_coeff :
      (Real.cos theta : ℂ) * (Real.cos theta : ℂ) -
      (Complex.I * (Real.sin theta : ℂ)) * (Complex.I * - (Real.sin theta : ℂ)) =
      (Real.cos (2 * theta) : ℂ) := by
    rw [cos_two_theta]
    calc
      (Real.cos theta : ℂ) * (Real.cos theta : ℂ) -
      (Complex.I * (Real.sin theta : ℂ)) * (Complex.I * - (Real.sin theta : ℂ))
        = (Real.cos theta : ℂ) ^ 2 + Complex.I ^ 2 * (Real.sin theta : ℂ) ^ 2 := by ring
      _ = (Real.cos theta : ℂ) ^ 2 - (Real.sin theta : ℂ) ^ 2 := by rw [h_i_sq]; ring
  have h_gx_coeff :
      - ((Real.cos theta : ℂ) * (Complex.I * - (Real.sin theta : ℂ)) -
         (Complex.I * (Real.sin theta : ℂ)) * (Real.cos theta : ℂ)) =
      Complex.I * (Real.sin (2 * theta) : ℂ) := by
    rw [sin_two_theta]
    ring
  rw [h_x_coeff, sub_eq_add_neg, ← neg_smul, h_gx_coeff]
  exact h_anticomm

/--
MAIN THEOREM 1 (Exact Modular Flow on the Annihilation Operator c):
  `u(θ) * c * u(-θ) = cos(2θ) • c + i sin(2θ) • (Γ * c)`
-/
theorem modularSandwich_c (theta : ℝ) :
    modularSandwich car theta car.c =
      chiralFlowExplicit (car.c) (car.Gamma * car.c) theta := by
  dsimp [chiralFlowExplicit]
  exact modularSandwich_odd car car.c car.anticomm_c theta

/--
MAIN THEOREM 2 (Exact Modular Flow on the Creation Operator c†):
  `u(θ) * c† * u(-θ) = cos(2θ) • c† + i sin(2θ) • (Γ * c†)`
-/
theorem modularSandwich_cdag (theta : ℝ) :
    modularSandwich car theta car.c_dag =
      chiralFlowExplicit (car.c_dag) (car.Gamma * car.c_dag) theta := by
  dsimp [chiralFlowExplicit]
  exact modularSandwich_odd car car.c_dag car.anticomm_cdag theta

/-! =========================================================================
    5. 1-Parameter Group Law: σ_{s+t} = σ_s ∘ σ_t
    ========================================================================= -/

/--
MAIN THEOREM 3 (1-Parameter Group Homomorphism Law on c):
  `σ_{s + t}(c) = σ_s(σ_t(c))`
-/
theorem chiralFlowExplicit_add (s t : ℝ) :
    chiralFlowExplicit (car.c) (car.Gamma * car.c) (s + t) =
      ((Real.cos (2 * s) : ℂ) • (chiralFlowExplicit (car.c) (car.Gamma * car.c) t)) +
      (Complex.I * (Real.sin (2 * s) : ℂ)) •
        (car.Gamma * (chiralFlowExplicit (car.c) (car.Gamma * car.c) t)) := by
  dsimp [chiralFlowExplicit]
  have h_gamma_distrib :
      car.Gamma * (((Real.cos (2 * t) : ℂ) • car.c) + (Complex.I * (Real.sin (2 * t) : ℂ)) • (car.Gamma * car.c)) =
      ((Real.cos (2 * t) : ℂ) • (car.Gamma * car.c)) + (Complex.I * (Real.sin (2 * t) : ℂ)) • car.c := by
    rw [mul_add, mul_smul_comm, mul_smul_comm]
    have h_gamma_sq_c : car.Gamma * (car.Gamma * car.c) = car.c := by
      rw [← mul_assoc, car.gamma_sq, one_mul]
    rw [h_gamma_sq_c]
  have h_cos : (Real.cos (2 * (s + t)) : ℂ) =
      (Real.cos (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) -
      (Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ) := by
    have h : 2 * (s + t) = 2 * s + 2 * t := by ring
    rw [h, Real.cos_add]
    push_cast; ring
  have h_sin : (Real.sin (2 * (s + t)) : ℂ) =
      (Real.sin (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) +
      (Real.cos (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ) := by
    have h : 2 * (s + t) = 2 * s + 2 * t := by ring
    rw [h, Real.sin_add]
    push_cast; ring
  have h_i_sq : Complex.I ^ 2 = -1 := Complex.I_sq
  have h_c_coeff :
      - ((Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ)) =
      (Complex.I * (Real.sin (2 * s) : ℂ)) * (Complex.I * (Real.sin (2 * t) : ℂ)) := by
    calc
      - ((Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ))
        = Complex.I ^ 2 * ((Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ)) := by rw [h_i_sq]; ring
      _ = (Complex.I * (Real.sin (2 * s) : ℂ)) * (Complex.I * (Real.sin (2 * t) : ℂ)) := by ring
  have h_gc_coeff :
      Complex.I * ((Real.sin (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) +
                   (Real.cos (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ)) =
      (Real.cos (2 * s) : ℂ) * (Complex.I * (Real.sin (2 * t) : ℂ)) +
      (Complex.I * (Real.sin (2 * s) : ℂ)) * (Real.cos (2 * t) : ℂ) := by ring
  have h_gc_split :
      (Complex.I * ((Real.sin (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) +
                    (Real.cos (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ))) • (car.Gamma * car.c) =
      ((Real.cos (2 * s) : ℂ) * (Complex.I * (Real.sin (2 * t) : ℂ))) • (car.Gamma * car.c) +
      ((Complex.I * (Real.sin (2 * s) : ℂ)) * (Real.cos (2 * t) : ℂ)) • (car.Gamma * car.c) := by
    rw [h_gc_coeff, add_smul]
  have h_c_split :
      - (((Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ)) • car.c) =
      ((Complex.I * (Real.sin (2 * s) : ℂ)) * (Complex.I * (Real.sin (2 * t) : ℂ))) • car.c := by
    rw [← neg_smul, h_c_coeff]
  calc
    (Real.cos (2 * (s + t)) : ℂ) • car.c + (Complex.I * (Real.sin (2 * (s + t)))) • (car.Gamma * car.c)
      = ((Real.cos (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) -
         (Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ)) • car.c +
        (Complex.I * ((Real.sin (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) +
                      (Real.cos (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ))) • (car.Gamma * car.c) := by rw [h_cos, h_sin]
    _ = (((Real.cos (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ)) • car.c +
         -(((Real.sin (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ)) • car.c)) +
        (Complex.I * ((Real.sin (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ) +
                      (Real.cos (2 * s) : ℂ) * (Real.sin (2 * t) : ℂ))) • (car.Gamma * car.c) := by
          rw [sub_smul, sub_eq_add_neg]
    _ = (((Real.cos (2 * s) : ℂ) * (Real.cos (2 * t) : ℂ)) • car.c +
         ((Complex.I * (Real.sin (2 * s) : ℂ)) * (Complex.I * (Real.sin (2 * t) : ℂ))) • car.c) +
        (((Real.cos (2 * s) : ℂ) * (Complex.I * (Real.sin (2 * t) : ℂ))) • (car.Gamma * car.c) +
         ((Complex.I * (Real.sin (2 * s) : ℂ)) * (Real.cos (2 * t) : ℂ)) • (car.Gamma * car.c)) := by
          rw [h_c_split, h_gc_split]
    _ = (Real.cos (2 * s) : ℂ) • ((Real.cos (2 * t) : ℂ) • car.c + (Complex.I * (Real.sin (2 * t) : ℂ)) • (car.Gamma * car.c)) +
        (Complex.I * (Real.sin (2 * s) : ℂ)) • ((Real.cos (2 * t) : ℂ) • (car.Gamma * car.c) + (Complex.I * (Real.sin (2 * t) : ℂ)) • car.c) := by
          simp only [smul_add, smul_smul]; abel
    _ = (Real.cos (2 * s) : ℂ) • ((Real.cos (2 * t) : ℂ) • car.c + (Complex.I * (Real.sin (2 * t) : ℂ)) • (car.Gamma * car.c)) +
        (Complex.I * (Real.sin (2 * s) : ℂ)) • (car.Gamma * ((Real.cos (2 * t) : ℂ) • car.c + (Complex.I * (Real.sin (2 * t) : ℂ)) • (car.Gamma * car.c))) := by
          rw [h_gamma_distrib]

/-! =========================================================================
    6. Preservation of Even Observables (Number Operator N)
    ========================================================================= -/

theorem chiralUnitary_inv_prod (theta : ℝ) :
    chiralUnitary car theta * chiralUnitary car (-theta) = 1 := by
  change (((Real.cos theta : ℂ) • (1 : A)) + (Complex.I * (Real.sin theta : ℂ)) • car.Gamma) *
         (((Real.cos (-theta) : ℂ) • (1 : A)) + (Complex.I * (Real.sin (-theta) : ℂ)) • car.Gamma) = 1
  rw [prod_gamma car]
  have h_cos_neg : (Real.cos (-theta) : ℂ) = (Real.cos theta : ℂ) := by rw [Real.cos_neg]
  have h_sin_neg : (Real.sin (-theta) : ℂ) = - (Real.sin theta : ℂ) := by rw [Real.sin_neg]; push_cast; rfl
  rw [h_cos_neg, h_sin_neg]
  have h_i_sq : Complex.I ^ 2 = -1 := Complex.I_sq
  have h_one_coeff :
      (Real.cos theta : ℂ) * (Real.cos theta : ℂ) +
      (Complex.I * (Real.sin theta : ℂ)) * (Complex.I * - (Real.sin theta : ℂ)) = 1 := by
    calc
      (Real.cos theta : ℂ) * (Real.cos theta : ℂ) +
      (Complex.I * (Real.sin theta : ℂ)) * (Complex.I * - (Real.sin theta : ℂ))
        = (Real.cos theta : ℂ) ^ 2 - Complex.I ^ 2 * (Real.sin theta : ℂ) ^ 2 := by ring
      _ = (Real.cos theta : ℂ) ^ 2 + (Real.sin theta : ℂ) ^ 2 := by rw [h_i_sq]; ring
      _ = ((Real.cos theta ^ 2 + Real.sin theta ^ 2 : ℝ) : ℂ) := by push_cast; rfl
      _ = ((1 : ℝ) : ℂ) := by rw [Real.cos_sq_add_sin_sq]
      _ = 1 := by push_cast; rfl
  have h_gamma_coeff :
      (Real.cos theta : ℂ) * (Complex.I * - (Real.sin theta : ℂ)) +
      (Complex.I * (Real.sin theta : ℂ)) * (Real.cos theta : ℂ) = 0 := by ring
  rw [h_one_coeff, h_gamma_coeff, one_smul, zero_smul, add_zero]

/--
MAIN THEOREM 4 (Conservation of Fermion Number under Modular Flow):
The number operator `N = c† * c` is strictly stationary under the chiral modular flow:
  `σ_t(N) = N`
-/
theorem modularSandwich_numberOp_invariant (theta : ℝ) :
    modularSandwich car theta (numberOp car) = numberOp car := by
  dsimp [modularSandwich, numberOp]
  have h_comm : chiralUnitary car theta * (car.c_dag * car.c) =
      (car.c_dag * car.c) * chiralUnitary car theta := by
    dsimp [chiralUnitary]
    rw [add_mul, mul_add, smul_mul_assoc, one_mul, mul_smul_comm, mul_one]
    rw [smul_mul_assoc, mul_smul_comm]
    congr 2
    calc
      car.Gamma * (car.c_dag * car.c)
        = (car.Gamma * car.c_dag) * car.c := by rw [mul_assoc]
      _ = (- (car.c_dag * car.Gamma)) * car.c := by rw [car.anticomm_cdag]
      _ = - (car.c_dag * (car.Gamma * car.c)) := by rw [neg_mul, mul_assoc]
      _ = - (car.c_dag * (- (car.c * car.Gamma))) := by rw [car.anticomm_c]
      _ = car.c_dag * (car.c * car.Gamma) := by rw [mul_neg, neg_neg]
      _ = (car.c_dag * car.c) * car.Gamma := by rw [mul_assoc]
  have h_inv := chiralUnitary_inv_prod car theta
  calc
    chiralUnitary car theta * (car.c_dag * car.c) * chiralUnitary car (-theta)
      = ((car.c_dag * car.c) * chiralUnitary car theta) * chiralUnitary car (-theta) := by rw [h_comm]
    _ = (car.c_dag * car.c) * (chiralUnitary car theta * chiralUnitary car (-theta)) := by rw [mul_assoc]
    _ = (car.c_dag * car.c) * 1 := by rw [h_inv]
    _ = car.c_dag * car.c := by rw [mul_one]

end InfoGeometry.Modular.CARModularFlow

