import InfoGeometry.Optics.JonesCalibration
import InfoGeometry.Optics.OperatorialJonesCalculus
import InfoGeometry.Optics.OperatorValuedCliffordJones
import InfoGeometry.Optics.OperatorCl11JonesRepresentation
import InfoGeometry.Optics.SheetWittCircularBasis
import InfoGeometry.Optics.ChiralCircularTransport
import InfoGeometry.Optics.ChiralCircularSectorReadout
import InfoGeometry.Optics.OperatorLoxodromicFiniteReadout
import InfoGeometry.Optics.Cl55PolarizationBridge
import InfoGeometry.Optics.OperatorValuedConnection
import InfoGeometry.Optics.AbelianOperatorValuedConnection
import InfoGeometry.Optics.OperatorValuedSuperconnection
import InfoGeometry.Optics.CircularPolarizationSuperconnectionBridge
import InfoGeometry.Canonical.ChiralSuperconnectionCurvatureBridge
import InfoGeometry.Optics.OperatorDerivationForms
import InfoGeometry.Optics.OperatorLiftCarrier
import InfoGeometry.Optics.RealHestenesOperatorLift
import InfoGeometry.Optics.OperatorCausalSoldering
import InfoGeometry.Optics.FiniteOperatorValuedPolarization
import InfoGeometry.Optics.OperatorCausalFramework
import InfoGeometry.Optics.OperatorQGTSoldering
import InfoGeometry.Optics.OperatorBogoliubovPauliBridge
import InfoGeometry.Optics.OperatorQGTBogoliubovPauliSoldering
import InfoGeometry.Optics.Cl11SplitQuaternionQGTSoldering
import InfoGeometry.Optics.Cl11SplitQuaternionConjugationSoldering
import InfoGeometry.Optics.Cl11QuaternionTwistedConjugationBridge
import InfoGeometry.Optics.QuaternionCl44DiracOperatorBridge
import InfoGeometry.Optics.QuaternionCl44TwistedConjugationLift
import InfoGeometry.Optics.QuaternionCl44DiracImplementer
import InfoGeometry.Optics.QuaternionCl44QGTDiracCovariance
import InfoGeometry.Optics.QuaternionCl44QGTCurvatureCovariance
import InfoGeometry.Optics.QuaternionCl44QGTBianchiChernWeil
import InfoGeometry.Optics.QuaternionCl44QGTNormedFrechetRealization
import InfoGeometry.Optics.QuaternionCl44QGTExponentialTransport
import InfoGeometry.Optics.HestenesCl11Cl44OperatorBridge
import InfoGeometry.Optics.HestenesCl11QGTCurvatureBridge
import InfoGeometry.Optics.HestenesCl11QGTNormedFrechetBridge
import InfoGeometry.Optics.HestenesCl11QGTBianchiChernWeilBridge
import InfoGeometry.Optics.FiniteBKMDiracTransport
import InfoGeometry.Optics.FiniteBKMDiracCurvatureBridge
import InfoGeometry.Optics.FiniteBKMDiracFrechetBridge
import InfoGeometry.Optics.FiniteBKMDiracBianchiChernWeil
import InfoGeometry.Optics.FiniteBKMDiracMetricReadout
import InfoGeometry.Optics.FiniteBKMDiracBerryReadout
import InfoGeometry.Optics.Cl11OperatorConjugationNorm
import InfoGeometry.Optics.Cl11OperatorProjectiveRatio
import InfoGeometry.Optics.OperatorQGTBogoliubovNaturality
import InfoGeometry.Optics.OperatorQGTConnectionCovariance
import InfoGeometry.Optics.LocalGaugeQGTCovariance
import InfoGeometry.Optics.LocalGaugeCovariantDerivative
import InfoGeometry.Optics.LocalGaugeFrameComposition
import InfoGeometry.Optics.LocalGaugeFrameInverse
import InfoGeometry.Optics.LocalGaugeGroupAction
import InfoGeometry.Optics.LocalGaugeAdjointAction
import InfoGeometry.Optics.OperatorQGTGaugeModuli
import InfoGeometry.Optics.OperatorQGTGaugeInvariants
import InfoGeometry.Optics.OperatorQGTChernWeil
import InfoGeometry.Optics.OperatorQGTFrechetChernCharacter
import InfoGeometry.Optics.ChiralLorentzOperatorLift
import InfoGeometry.Optics.FiniteJonesModel
import InfoGeometry.Optics.JonesPoincareSphere
import InfoGeometry.Optics.FiniteJonesErlanger
import InfoGeometry.Optics.FiniteJonesBrewsterCollapse
import InfoGeometry.Optics.FiniteJonesBregman
import InfoGeometry.Optics.FiniteJonesStinespring
import InfoGeometry.Optics.FiniteJonesStinespringConstructive
import InfoGeometry.Optics.FiniteJonesKasparovBoundary

namespace InfoGeometry.Optics

/-!
# Optics Interfaces

Optical Jones/Fresnel bridges for projective polarization transport.
-/

end InfoGeometry.Optics
