import InfoGeometry.Optics.JonesCalibration
import InfoGeometry.Optics.OperatorialJonesCalculus
import InfoGeometry.Optics.OperatorValuedCliffordJones
import InfoGeometry.Optics.OperatorCl11JonesRepresentation
import InfoGeometry.Optics.SheetWittCircularBasis
import InfoGeometry.Optics.ChiralCircularTransport
import InfoGeometry.Optics.OperatorLoxodromicFiniteReadout
import InfoGeometry.Optics.Cl55PolarizationBridge
import InfoGeometry.Optics.OperatorValuedConnection
import InfoGeometry.Optics.OperatorDerivationForms
import InfoGeometry.Optics.OperatorLiftCarrier
import InfoGeometry.Optics.RealHestenesOperatorLift
import InfoGeometry.Optics.OperatorCausalSoldering
import InfoGeometry.Optics.FiniteOperatorValuedPolarization
import InfoGeometry.Optics.OperatorCausalFramework
import InfoGeometry.Optics.OperatorQGTSoldering
import InfoGeometry.Optics.OperatorBogoliubovPauliBridge
import InfoGeometry.Optics.ChiralLorentzOperatorLift
import InfoGeometry.Optics.FiniteJonesModel
import InfoGeometry.Optics.JonesPoincareSphere
import InfoGeometry.Optics.FiniteJonesErlanger
import InfoGeometry.Optics.FiniteJonesBrewsterCollapse
import InfoGeometry.Optics.FiniteJonesBregman
import InfoGeometry.Optics.FiniteJonesStinespring
import InfoGeometry.Optics.FiniteJonesStinespringConstructive
import InfoGeometry.Optics.FiniteJonesKasparovBoundary

namespace InfoGeometry.Optics

/-!
# Optics Interfaces

Optical Jones/Fresnel sockets for projective polarization transport.
-/

end InfoGeometry.Optics
