import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Real.Basic
import InfoGeometry.Topology.KANWallpaperIsomorphism
import InfoGeometry.Algebra.CuntzTensorQuotient
import InfoGeometry.Algebra.CuntzSuperalgebra

/-!
# Cuntz wallpaper supergraded SUSY shadow

This module records the finite supergraded-algebra shadow of the KAN-wallpaper
matrix bridge.

It does not prove physical supersymmetry, super-Poincare representation theory,
or a collider-scale SUSY model.  It proves the finite algebraic pattern:

* an odd generator `Q` is represented by the glide matrix `G`;
* an even generator `P_x` is represented by the translation matrix `T_x`;
* the self-anticommutator of `Q` is twice `P_x`;
* `Q` commutes with `P_x` in this finite projective matrix model.

#### BUCKET 1: CLOSED FINITE THEOREMS

`susy_anticommutator_generates_spacetime`,
`susy_anticommutator_generates_two_smul_momentum`,
`wallpaper_generates_SUSY`,
`supercharge_commutes_with_momentum_matrix`, and
`supercharge_commutator_with_momentum_zero`.

#### BUCKET 2: CONDITIONAL THEOREMS FROM EXPLICIT WITNESSES

None.

#### BUCKET 3: OPEN CLOSURE DEBT

The full Cuntz algebra representation, a Hilbert-space supercharge operator,
super-Poincare covariance, and physical supersymmetry remain outside this
finite matrix module.
-/

noncomputable section

namespace InfoGeometry.Algebra.SupergradedSUSY

open Matrix InfoGeometry.Topology.KANWallpaper

/-- The odd generator `Q`, represented by the non-symmorphic glide reflection. -/
def Q : ProjMatrix := G

/-- The even translation generator `P_x`, represented by the unit `x` translation. -/
def P_x : ProjMatrix := T_x

/-- Matrix anticommutator `{A,B} = AB + BA`. -/
def superAnticommutator (A B : ProjMatrix) : ProjMatrix :=
  A * B + B * A

/-- Matrix commutator `[A,B] = AB - BA`. -/
def commutator (A B : ProjMatrix) : ProjMatrix :=
  A * B - B * A

/--
Finite SUSY-shaped anticommutator relation.

The self-anticommutator of the odd glide generator is twice the even
translation generator.
-/
theorem susy_anticommutator_generates_spacetime :
    superAnticommutator Q Q = P_x + P_x := by
  unfold superAnticommutator Q P_x
  rw [glide_squared_is_translation]

/-- Scalar form of the finite SUSY-shaped anticommutator `{Q,Q} = 2 • P_x`. -/
theorem susy_anticommutator_generates_two_smul_momentum :
    superAnticommutator Q Q = (2 : ℝ) • P_x := by
  rw [susy_anticommutator_generates_spacetime]
  ext i j
  simp
  ring

/-- Compatibility name for the finite wallpaper-generated SUSY-shaped identity. -/
theorem wallpaper_generates_SUSY :
    superAnticommutator Q Q = (2 : ℝ) • P_x :=
  susy_anticommutator_generates_two_smul_momentum

/-- The odd glide generator commutes with the even translation matrix. -/
theorem supercharge_commutes_with_momentum_matrix :
    Q * P_x = P_x * Q := by
  unfold Q P_x
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [G, T_x, Matrix.mul_apply, Fin.sum_univ_three]
  norm_num

/-- The matrix commutator of `Q` with `P_x` is zero. -/
theorem supercharge_commutator_with_momentum_zero :
    commutator Q P_x = 0 := by
  unfold commutator
  rw [supercharge_commutes_with_momentum_matrix]
  simp

/--
Backwards-compatible theorem name for the finite commutation statement.
-/
theorem supercharge_commutes_with_momentum :
    Q * P_x - P_x * Q = 0 := by
  simpa [commutator] using supercharge_commutator_with_momentum_zero

/-! ## Cuntz quotient supercharge algebra -/

open InfoGeometry.Algebra.CuntzTensorQuotient
open CuntzSuperalgebra

/-- Algebraic odd--odd anticommutator. -/
def algebraicAnticommutator {A : Type*} [Mul A] [Add A] (x y : A) : A :=
  x * y + y * x

/-- The momentum generated by one supercharge is its square. -/
def superMomentum {A : Type*} [Mul A] (Q : A) : A :=
  Q * Q

/-- Central element predicate. -/
def IsCentralElement {A : Type*} [Mul A] (Z : A) : Prop :=
  ∀ X : A, Z * X = X * Z

/-- The self-anticommutator of `Q` is twice the momentum `Q²`. -/
theorem algebraicAnticommutator_self_eq_two_nsmul_momentum
    {A : Type*} [AddMonoid A] [Mul A] (Q : A) :
    algebraicAnticommutator Q Q = (2 : ℕ) • superMomentum Q := by
  rw [algebraicAnticommutator, superMomentum, two_nsmul]

/-- Complex-linear form of `{Q,Q}=2P`, used by the Cuntz quotient. -/
theorem algebraicAnticommutator_self_eq_two_smul_momentum
    {A : Type*} [AddCommMonoid A] [Mul A] [Module ℂ A] (Q : A) :
    algebraicAnticommutator Q Q = (2 : ℂ) • superMomentum Q := by
  simp [algebraicAnticommutator, superMomentum, two_smul]

/--
Explicit super-Poincare-style socket.

This stores the Lorentz/Poincare carriers and actions as hypotheses; the
proved algebraic content is the supercharge-generated momentum and centrality.
-/
structure SuperPoincareSuperchargeSocket (A : Type*) [Ring A] where
  LorentzGroup : Type
  PoincareGroup : Type
  lorentzGroup : Group LorentzGroup
  poincareGroup : Group PoincareGroup
  lorentzAction : LorentzGroup → A → A
  poincareAction : PoincareGroup → A → A
  grade : A → ZMod 2
  supercharge : A
  momentum : A
  centralCharge : A
  poincareTranslation : A
  supercharge_odd : grade supercharge = 1
  momentum_even : grade momentum = 0
  centralCharge_even : grade centralCharge = 0
  momentum_eq_supercharge_square : momentum = superMomentum supercharge
  poincareTranslation_eq_momentum : poincareTranslation = momentum
  centralCharge_central : IsCentralElement centralCharge

namespace SuperPoincareSuperchargeSocket

variable {A : Type*} [Ring A]
variable (S : SuperPoincareSuperchargeSocket A)

/-- In any socket, momentum is defined by the supercharge square. -/
theorem momentum_defined_by_supercharge :
    S.momentum = superMomentum S.supercharge :=
  S.momentum_eq_supercharge_square

/-- In any socket, the distinguished Poincare translation is the supercharge momentum. -/
theorem poincare_translation_defined_by_supercharge :
    S.poincareTranslation = superMomentum S.supercharge := by
  rw [S.poincareTranslation_eq_momentum, S.momentum_eq_supercharge_square]

/-- In any socket, the central charge commutes with every algebra element. -/
theorem centralCharge_commutes (X : A) :
    S.centralCharge * X = X * S.centralCharge :=
  S.centralCharge_central X

/-- In any socket, `{Q,Q}=2P` with natural scalar multiplication. -/
theorem anticommutator_generates_momentum :
    algebraicAnticommutator S.supercharge S.supercharge =
      (2 : ℕ) • S.momentum := by
  rw [S.momentum_eq_supercharge_square]
  exact algebraicAnticommutator_self_eq_two_nsmul_momentum S.supercharge

end SuperPoincareSuperchargeSocket

/-- Cuntz Majorana-type supercharge `Qᵢ = Sᵢ + Sᵢ†`. -/
def cuntzMajoranaSupercharge (n : ℕ) (i : Fin n) : CuntzAlg n :=
  cuntzS n i + cuntzSdag n i

/-- Momentum generated by the Cuntz supercharge. -/
def cuntzSuperMomentum (n : ℕ) (i : Fin n) : CuntzAlg n :=
  superMomentum (cuntzMajoranaSupercharge n i)

/-- The unit is the finite central-charge carrier in the algebraic Cuntz quotient. -/
def cuntzCentralCharge (n : ℕ) : CuntzAlg n :=
  1

/-- The Cuntz Majorana supercharge is self-adjoint. -/
theorem star_cuntzMajoranaSupercharge (n : ℕ) (i : Fin n) :
    star (cuntzMajoranaSupercharge n i) = cuntzMajoranaSupercharge n i := by
  simp [cuntzMajoranaSupercharge, star_add, star_cuntzS, star_cuntzSdag, add_comm]

/-- The Cuntz Majorana supercharge is odd for the quotient parity involution. -/
theorem parity_cuntzMajoranaSupercharge (n : ℕ) (i : Fin n) :
    parity n (cuntzMajoranaSupercharge n i) = -cuntzMajoranaSupercharge n i := by
  simp [cuntzMajoranaSupercharge, parity_S, parity_Sdag, add_comm]

/-- The momentum generated by the Cuntz supercharge is even for the quotient parity involution. -/
theorem parity_cuntzSuperMomentum (n : ℕ) (i : Fin n) :
    parity n (cuntzSuperMomentum n i) = cuntzSuperMomentum n i := by
  rw [cuntzSuperMomentum, superMomentum, map_mul, parity_cuntzMajoranaSupercharge]
  exact neg_mul_neg (cuntzMajoranaSupercharge n i) (cuntzMajoranaSupercharge n i)

/-- The finite Cuntz central charge commutes with every observable. -/
theorem cuntzCentralCharge_central (n : ℕ) :
    IsCentralElement (cuntzCentralCharge n) := by
  intro X
  simp [cuntzCentralCharge]

/-- The unit central-charge carrier is even for the quotient parity involution. -/
theorem parity_cuntzCentralCharge (n : ℕ) :
    parity n (cuntzCentralCharge n) = cuntzCentralCharge n := by
  simp [cuntzCentralCharge, parity]

/-- Cuntz quotient form of `{Qᵢ,Qᵢ}=2Pᵢ`. -/
theorem cuntz_anticommutator_generates_momentum (n : ℕ) (i : Fin n) :
    algebraicAnticommutator (cuntzMajoranaSupercharge n i) (cuntzMajoranaSupercharge n i) =
      (2 : ℂ) • cuntzSuperMomentum n i := by
  exact algebraicAnticommutator_self_eq_two_smul_momentum (cuntzMajoranaSupercharge n i)

/-- Odd plus odd is even in the `ZMod 2` grade bookkeeping. -/
theorem odd_add_odd_grade_even :
    (1 : ZMod 2) + (1 : ZMod 2) = 0 := by
  native_decide

/-- Concrete finite Cuntz super-Poincare packet with explicit grade labels. -/
structure CuntzSuperPoincarePacket (n : ℕ) where
  mode : Fin n
  supercharge : CuntzAlg n
  momentum : CuntzAlg n
  centralCharge : CuntzAlg n
  poincareTranslation : CuntzAlg n
  superchargeGrade : ZMod 2
  momentumGrade : ZMod 2
  centralChargeGrade : ZMod 2
  supercharge_eq : supercharge = cuntzMajoranaSupercharge n mode
  momentum_eq : momentum = superMomentum supercharge
  centralCharge_eq : centralCharge = cuntzCentralCharge n
  poincareTranslation_eq_momentum : poincareTranslation = momentum
  supercharge_odd : superchargeGrade = 1
  momentum_even : momentumGrade = 0
  centralCharge_even : centralChargeGrade = 0
  odd_odd_grade_even : superchargeGrade + superchargeGrade = momentumGrade
  centralCharge_central : IsCentralElement centralCharge

namespace CuntzSuperPoincarePacket

variable {n : ℕ}
variable (P : CuntzSuperPoincarePacket n)

/-- The packet momentum is exactly the supercharge square. -/
theorem momentum_defined_by_supercharge :
    P.momentum = superMomentum P.supercharge :=
  P.momentum_eq

/-- The packet Poincare translation is exactly the supercharge momentum. -/
theorem poincare_translation_defined_by_supercharge :
    P.poincareTranslation = superMomentum P.supercharge := by
  rw [P.poincareTranslation_eq_momentum, P.momentum_eq]

/-- The packet central charge commutes with every Cuntz observable. -/
theorem centralCharge_commutes (X : CuntzAlg n) :
    P.centralCharge * X = X * P.centralCharge :=
  P.centralCharge_central X

/-- The packet supercharge anticommutator generates its momentum. -/
theorem anticommutator_generates_momentum :
    algebraicAnticommutator P.supercharge P.supercharge = (2 : ℂ) • P.momentum := by
  rw [P.momentum_eq]
  exact algebraicAnticommutator_self_eq_two_smul_momentum P.supercharge

end CuntzSuperPoincarePacket

/-- Canonical finite Cuntz packet at one mode. -/
def canonicalCuntzSuperPoincarePacket (n : ℕ) (i : Fin n) :
    CuntzSuperPoincarePacket n where
  mode := i
  supercharge := cuntzMajoranaSupercharge n i
  momentum := cuntzSuperMomentum n i
  centralCharge := cuntzCentralCharge n
  poincareTranslation := cuntzSuperMomentum n i
  superchargeGrade := 1
  momentumGrade := 0
  centralChargeGrade := 0
  supercharge_eq := rfl
  momentum_eq := rfl
  centralCharge_eq := rfl
  poincareTranslation_eq_momentum := rfl
  supercharge_odd := rfl
  momentum_even := rfl
  centralCharge_even := rfl
  odd_odd_grade_even := odd_add_odd_grade_even
  centralCharge_central := cuntzCentralCharge_central n

/-- Closed finite Cuntz supercharge/momentum/central-charge packet. -/
theorem canonicalCuntzSuperPoincarePacket_closure (n : ℕ) (i : Fin n) :
    let P := canonicalCuntzSuperPoincarePacket n i
    star P.supercharge = P.supercharge ∧
      algebraicAnticommutator P.supercharge P.supercharge = (2 : ℂ) • P.momentum ∧
        P.poincareTranslation = superMomentum P.supercharge ∧
          IsCentralElement P.centralCharge ∧
            P.superchargeGrade + P.superchargeGrade = P.momentumGrade ∧
              parity n P.supercharge = -P.supercharge ∧
                parity n P.momentum = P.momentum ∧
                  parity n P.centralCharge = P.centralCharge := by
  simp only
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact star_cuntzMajoranaSupercharge n i
  · exact CuntzSuperPoincarePacket.anticommutator_generates_momentum
      (canonicalCuntzSuperPoincarePacket n i)
  · exact CuntzSuperPoincarePacket.poincare_translation_defined_by_supercharge
      (canonicalCuntzSuperPoincarePacket n i)
  · exact (canonicalCuntzSuperPoincarePacket n i).centralCharge_central
  · exact (canonicalCuntzSuperPoincarePacket n i).odd_odd_grade_even
  · exact parity_cuntzMajoranaSupercharge n i
  · exact parity_cuntzSuperMomentum n i
  · exact parity_cuntzCentralCharge n

end InfoGeometry.Algebra.SupergradedSUSY

end noncomputable section
