import InfoGeometry.Algebra.CuntzDerivationTangent
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Algebra.CuntzQuotientDiracBridge

/-!
# Quotient-Cuntz inner tangent packet

A concrete specialization of the generic star-derivation tangent theorem to
the repository's tensor-algebra quotient presentation of `O_n`.
-/

namespace InfoGeometry.Algebra.CuntzQuotientDiracBridge

open InfoGeometry.Algebra.Cuntz
open InfoGeometry.Algebra.CuntzTensorQuotient

noncomputable section

/-- The skew-adjoint generator obtained from a quotient Cuntz isometry. -/
def skewGenerator (n : ℕ) (i : Fin n) : CuntzAlg n :=
  cuntzS n i - star (cuntzS n i)

@[simp] theorem star_skewGenerator (n : ℕ) (i : Fin n) :
    star (skewGenerator n i) = -skewGenerator n i := by
  simp [skewGenerator, star_sub, star_cuntzS, star_cuntzSdag]

/-- The inner star derivation generated by the quotient skew generator. -/
noncomputable def quotientInnerStarDerivation (n : ℕ) (i : Fin n) :
    StarDerivation (A := CuntzAlg n) :=
  innerStarDerivation (skewGenerator n i) (star_skewGenerator n i)

/-- Concrete quotient-Cuntz tangent generated by `Sᵢ - Sᵢ*`. -/
noncomputable def quotientInnerCuntzTangent (n : ℕ) (i : Fin n) :
    CuntzTangent (quotientCuntzNAlgebra n) :=
  (quotientInnerStarDerivation n i).cuntzTangent (quotientCuntzNAlgebra n)

@[simp] theorem quotientInnerCuntzTangent_variation
    (n : ℕ) (i j : Fin n) :
    (quotientInnerCuntzTangent n i).X j =
      skewGenerator n i * cuntzS n j - cuntzS n j * skewGenerator n i := by
  rfl

end

end InfoGeometry.Algebra.CuntzQuotientDiracBridge
