import InfoGeometry.Algebra.GrothendieckMathlibNatIso
#check InfoGeometry.Categorical.grothendieckCompletionFunctor
#check InfoGeometry.Algebra.GrothendieckMathlibNatIso.mathlibGrothendieckFunctor
#check InfoGeometry.Algebra.GrothendieckMathlibNatIso.grothendieckFunctorNatIso
#check InfoGeometry.Algebra.GrothendieckMathlibNatIso.grothendieckFunctorNatIso_hom_app
#print axioms InfoGeometry.Algebra.GrothendieckMathlibNatIso.grothendieckFunctorNatIso
#print axioms InfoGeometry.Algebra.GrothendieckMathlibNatIso.grothendieckFunctorNatIso_naturality
