import InfoGeometry.Topology.ArtinBraidS3Quotient
import InfoGeometry.Algebra.FiniteSpinAlgebra

/-!
# Kingdon Petersson permutation shadow

This module records the finite three-cycle in `S₃` that is later used by braid
and coordinate-permutation lanes. It does not claim the full Petersson isotope
construction on the Kingdon split-octonion carrier.
-/

namespace InfoGeometry.Algebra.KingdonPetersson

/-- The even three-cycle generated by the adjacent transpositions in `S₃`. -/
def peterssonCyclePermutation : Equiv.Perm (Fin 3) where
  toFun
    | 0 => 1
    | 1 => 2
    | 2 => 0
  invFun
    | 0 => 2
    | 1 => 0
    | 2 => 1
  left_inv := by
    intro i
    fin_cases i <;> rfl
  right_inv := by
    intro i
    fin_cases i <;> rfl

@[simp] theorem peterssonCyclePermutation_zero :
    peterssonCyclePermutation 0 = 1 := rfl

@[simp] theorem peterssonCyclePermutation_one :
    peterssonCyclePermutation 1 = 2 := rfl

@[simp] theorem peterssonCyclePermutation_two :
    peterssonCyclePermutation 2 = 0 := rfl

@[simp] theorem peterssonCyclePermutation_symm_zero :
    peterssonCyclePermutation.symm 0 = 2 := rfl

@[simp] theorem peterssonCyclePermutation_symm_one :
    peterssonCyclePermutation.symm 1 = 0 := rfl

@[simp] theorem peterssonCyclePermutation_symm_two :
    peterssonCyclePermutation.symm 2 = 1 := rfl

/-- The three-cycle has order three. -/
theorem peterssonCyclePermutation_order_three :
    peterssonCyclePermutation * peterssonCyclePermutation * peterssonCyclePermutation = 1 := by
  apply Equiv.ext
  intro i
  fin_cases i <;> rfl

end InfoGeometry.Algebra.KingdonPetersson
