import InfoGeometry.Algebra.NonAssocDerivationKernel
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Topology.Algebra.Module.FiniteDimensionBilinear
import Mathlib.Tactic

/-!
# Exponentiating a finite-dimensional nonassociative derivation

Let `A` be a finite-dimensional real normed vector space with a bilinear,
possibly nonassociative multiplication.  A derivation `D : End(A)` is first
viewed as a continuous endomorphism.  Its exponential is then formed inside
the associative Banach algebra `A →L[ℝ] A`:

`E_D(t) = exp (t D)`.

The central theorem proves that `E_D(t)` preserves the nonassociative product.
The proof does not assume associativity of multiplication on `A`.  It uses:

* the ordinary Banach-algebra exponential on continuous endomorphisms;
* the Leibniz rule for `D`;
* continuity of every bilinear map in finite dimension;
* the derivative-zero identity for
  `E_D(-t) (E_D(t)x * E_D(t)y)`.

The resulting map is packaged as the repository-native `NonAssocAut`.
Time-dependent/path-ordered evolution is deliberately outside this owner.
-/

noncomputable section

namespace InfoGeometry.Algebra.NonAssocDerivationExponential

open InfoGeometry.Lie.BaezG2SplitOctonion

variable {A : Type*}
variable [NormedAddCommGroup A] [NormedSpace ℝ A] [CompleteSpace A]
variable [FiniteDimensional ℝ A]
variable [NonUnitalNonAssocRing A] [IsScalarTower ℝ A A]
variable [SMulCommClass ℝ A A] [One A]

abbrev ContinuousEnd := A →L[ℝ] A

/-- The bilinear multiplication map before continuity is added. -/
def mulLinear : A →ₗ[ℝ] A →ₗ[ℝ] A :=
  LinearMap.mk₂ ℝ
    (fun x y => x * y)
    (fun x₁ x₂ y => add_mul x₁ x₂ y)
    (fun r x y => smul_mul_assoc r x y)
    (fun x y₁ y₂ => mul_add x y₁ y₂)
    (fun r x y => mul_smul_comm r x y)

/-- In finite dimension, the nonassociative bilinear multiplication is
continuous. -/
def mulContinuous : A →L[ℝ] A →L[ℝ] A :=
  LinearMap.toContinuousBilinearMap (mulLinear (A := A))

@[simp]
theorem mulContinuous_apply (x y : A) :
    mulContinuous (A := A) x y = x * y :=
  rfl

/-- A linear endomorphism regarded as a continuous endomorphism. -/
def continuousEnd (D : Module.End ℝ A) : ContinuousEnd (A := A) :=
  LinearMap.toContinuousLinearMap D

@[simp]
theorem continuousEnd_apply (D : Module.End ℝ A) (x : A) :
    continuousEnd D x = D x :=
  rfl

/-- The operator exponential flow generated by `D`. -/
def derivationFlow (D : Module.End ℝ A) (t : ℝ) : ContinuousEnd (A := A) :=
  NormedSpace.exp (t • continuousEnd D)

/-- The opposite-parameter flow, written as the exponential generated by
`-D`.  This form gives the required derivative without a separate chain-rule
calculation. -/
def inverseDerivationFlow (D : Module.End ℝ A) (t : ℝ) : ContinuousEnd (A := A) :=
  NormedSpace.exp (t • (-continuousEnd D))

@[simp]
theorem derivationFlow_zero (D : Module.End ℝ A) :
    derivationFlow D 0 = ContinuousLinearMap.id ℝ A := by
  simp [derivationFlow]

@[simp]
theorem inverseDerivationFlow_zero (D : Module.End ℝ A) :
    inverseDerivationFlow D 0 = ContinuousLinearMap.id ℝ A := by
  simp [inverseDerivationFlow]

/-- Scalar multiples of the same endomorphism commute. -/
theorem smul_continuousEnd_commute
    (D : Module.End ℝ A) (s t : ℝ) :
    Commute (s • continuousEnd D) (t • continuousEnd D) := by
  show (s • continuousEnd D) * (t • continuousEnd D) =
    (t • continuousEnd D) * (s • continuousEnd D)
  ext x
  simp [mul_comm]

/-- The exponential flow has the one-parameter group law. -/
theorem derivationFlow_add
    (D : Module.End ℝ A) (s t : ℝ) :
    derivationFlow D (s + t) = derivationFlow D s * derivationFlow D t := by
  calc
    derivationFlow D (s + t) =
        NormedSpace.exp (s • continuousEnd D + t • continuousEnd D) := by
      rw [derivationFlow, add_smul]
    _ = NormedSpace.exp (s • continuousEnd D) *
        NormedSpace.exp (t • continuousEnd D) :=
      NormedSpace.exp_add_of_commute (smul_continuousEnd_commute D s t)
    _ = derivationFlow D s * derivationFlow D t := rfl

/-- The explicitly generated inverse flow is the negative-parameter flow. -/
theorem inverseDerivationFlow_eq_neg
    (D : Module.End ℝ A) (t : ℝ) :
    inverseDerivationFlow D t = derivationFlow D (-t) := by
  unfold inverseDerivationFlow derivationFlow
  congr 1
  module

@[simp]
theorem inverseDerivationFlow_mul_flow
    (D : Module.End ℝ A) (t : ℝ) :
    inverseDerivationFlow D t * derivationFlow D t = 1 := by
  rw [inverseDerivationFlow_eq_neg]
  calc
    derivationFlow D (-t) * derivationFlow D t =
        derivationFlow D (-t + t) := (derivationFlow_add D (-t) t).symm
    _ = 1 := by simp

@[simp]
theorem derivationFlow_mul_inverseDerivationFlow
    (D : Module.End ℝ A) (t : ℝ) :
    derivationFlow D t * inverseDerivationFlow D t = 1 := by
  rw [inverseDerivationFlow_eq_neg]
  calc
    derivationFlow D t * derivationFlow D (-t) =
        derivationFlow D (t + -t) := (derivationFlow_add D t (-t)).symm
    _ = 1 := by simp

/-- The operator exponential as a genuine linear equivalence. -/
def derivationFlowLinearEquiv
    (D : Module.End ℝ A) (t : ℝ) : A ≃ₗ[ℝ] A where
  toFun := derivationFlow D t
  invFun := inverseDerivationFlow D t
  left_inv x := by
    have h := congrArg
      (fun T : ContinuousEnd (A := A) => T x)
      (inverseDerivationFlow_mul_flow D t)
    simpa using h
  right_inv x := by
    have h := congrArg
      (fun T : ContinuousEnd (A := A) => T x)
      (derivationFlow_mul_inverseDerivationFlow D t)
    simpa using h
  map_add' x y := (derivationFlow D t).map_add x y
  map_smul' r x := (derivationFlow D t).map_smul r x

/-! ## Differential identities -/

/-- Left-generator form of the differential equation in the endomorphism
algebra. -/
theorem derivationFlow_hasStrictDerivAt_left
    (D : Module.End ℝ A) (t : ℝ) :
    HasStrictDerivAt (derivationFlow D)
      (continuousEnd D * derivationFlow D t) t := by
  simpa [derivationFlow] using
    (NormedSpace.hasStrictDerivAt_exp_smul_const'
      (continuousEnd D) t)

/-- Right-generator form of the differential equation in the endomorphism
algebra. -/
theorem derivationFlow_hasStrictDerivAt_right
    (D : Module.End ℝ A) (t : ℝ) :
    HasStrictDerivAt (derivationFlow D)
      (derivationFlow D t * continuousEnd D) t := by
  simpa [derivationFlow] using
    (NormedSpace.hasStrictDerivAt_exp_smul_const
      (continuousEnd D) t)

/-- Pointwise orbit equation in left-generator form:
`d/dt (E_D(t)x) = D(E_D(t)x)`. -/
theorem derivationFlow_apply_hasStrictDerivAt_left
    (D : Module.End ℝ A) (x : A) (t : ℝ) :
    HasStrictDerivAt (fun s => derivationFlow D s x)
      (D (derivationFlow D t x)) t := by
  have h := (derivationFlow_hasStrictDerivAt_left D t).clm_apply
    (hasStrictDerivAt_const t x)
  simpa using h

/-- Pointwise orbit equation in right-generator form:
`d/dt (E_D(t)x) = E_D(t)(D x)`. -/
theorem derivationFlow_apply_hasStrictDerivAt_right
    (D : Module.End ℝ A) (x : A) (t : ℝ) :
    HasStrictDerivAt (fun s => derivationFlow D s x)
      (derivationFlow D t (D x)) t := by
  have h := (derivationFlow_hasStrictDerivAt_right D t).clm_apply
    (hasStrictDerivAt_const t x)
  simpa using h

/-- Differential equation for the opposite-generator flow. -/
theorem inverseDerivationFlow_hasStrictDerivAt
    (D : Module.End ℝ A) (t : ℝ) :
    HasStrictDerivAt (inverseDerivationFlow D)
      (inverseDerivationFlow D t * (-continuousEnd D)) t := by
  simpa [inverseDerivationFlow] using
    (NormedSpace.hasStrictDerivAt_exp_smul_const
      (-continuousEnd D) t)

/-- Product of two flowing vectors. -/
def productCurve (D : Module.End ℝ A) (x y : A) (t : ℝ) : A :=
  derivationFlow D t x * derivationFlow D t y

/-- Leibniz makes the derivative of the flowing product equal to `D` applied
to that product, without assuming that the flow is already multiplicative. -/
theorem productCurve_hasStrictDerivAt
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (x y : A) (t : ℝ) :
    HasStrictDerivAt (productCurve D x y)
      (D (productCurve D x y t)) t := by
  have h := (mulContinuous (A := A)).hasStrictDerivAt_of_bilinear
    (derivationFlow_apply_hasStrictDerivAt_left D x t)
    (derivationFlow_apply_hasStrictDerivAt_left D y t)
  simpa only [productCurve, mulContinuous_apply, hD, add_comm] using h

/-- The flowing product pulled back by the inverse flow. -/
def conjugatedProductCurve
    (D : Module.End ℝ A) (x y : A) (t : ℝ) : A :=
  inverseDerivationFlow D t (productCurve D x y t)

/-- The conjugated product has zero derivative. -/
theorem conjugatedProductCurve_hasStrictDerivAt_zero
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (x y : A) (t : ℝ) :
    HasStrictDerivAt (conjugatedProductCurve D x y) 0 t := by
  have h := (inverseDerivationFlow_hasStrictDerivAt D t).clm_apply
    (productCurve_hasStrictDerivAt D hD x y t)
  simpa [conjugatedProductCurve, continuousEnd_apply] using h

/-- The inverse-flow pullback of the flowing product is constant. -/
theorem conjugatedProductCurve_eq
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (x y : A) (t : ℝ) :
    conjugatedProductCurve D x y t = x * y := by
  have hderiv : ∀ s : ℝ,
      HasDerivAt (conjugatedProductCurve D x y) 0 s :=
    fun s => (conjugatedProductCurve_hasStrictDerivAt_zero D hD x y s).hasDerivAt
  have hdiff : Differentiable ℝ (conjugatedProductCurve D x y) :=
    fun s => (hderiv s).differentiableAt
  have hfderiv : ∀ s : ℝ,
      fderiv ℝ (conjugatedProductCurve D x y) s = 0 := by
    intro s
    simpa using (hderiv s).fderiv
  have hconst := is_const_of_fderiv_eq_zero hdiff hfderiv t 0
  simpa [conjugatedProductCurve, productCurve] using hconst

/-- The exponential of a derivation preserves the nonassociative product. -/
theorem derivationFlow_map_mul
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (t : ℝ) (x y : A) :
    derivationFlow D t (x * y) =
      derivationFlow D t x * derivationFlow D t y := by
  let z := derivationFlow D t x * derivationFlow D t y
  have hpull : inverseDerivationFlow D t z = x * y := by
    simpa [z, conjugatedProductCurve, productCurve] using
      conjugatedProductCurve_eq D hD x y t
  calc
    derivationFlow D t (x * y) =
        derivationFlow D t (inverseDerivationFlow D t z) := by rw [hpull]
    _ = z := by
      have h := congrArg
        (fun T : ContinuousEnd (A := A) => T z)
        (derivationFlow_mul_inverseDerivationFlow D t)
      simpa using h
    _ = derivationFlow D t x * derivationFlow D t y := rfl

/-- Since `D 1 = 0`, the exponential flow fixes the unit. -/
theorem derivationFlow_map_one
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (one_mul' : ∀ x : A, (1 : A) * x = x)
    (mul_one' : ∀ x : A, x * (1 : A) = x)
    (t : ℝ) :
    derivationFlow D t (1 : A) = 1 := by
  have hD1 : D (1 : A) = 0 :=
    InfoGeometry.Algebra.NonAssocDerivationKernel.linearDerivation_kills_one
      D hD one_mul' mul_one'
  let orbit : ℝ → A := fun s => derivationFlow D s (1 : A)
  have hderiv : ∀ s : ℝ, HasDerivAt orbit 0 s := by
    intro s
    have h := (derivationFlow_apply_hasStrictDerivAt_right D (1 : A) s).hasDerivAt
    simpa [orbit, hD1] using h
  have hdiff : Differentiable ℝ orbit := fun s => (hderiv s).differentiableAt
  have hfderiv : ∀ s : ℝ, fderiv ℝ orbit s = 0 := by
    intro s
    simpa using (hderiv s).fderiv
  have hconst := is_const_of_fderiv_eq_zero hdiff hfderiv t 0
  simpa [orbit] using hconst

/-- The genuine one-parameter nonassociative automorphism generated by `D`. -/
def expNonAssocDerivation
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (one_mul' : ∀ x : A, (1 : A) * x = x)
    (mul_one' : ∀ x : A, x * (1 : A) = x)
    (t : ℝ) : NonAssocAut ℝ A where
  toLinearEquiv := derivationFlowLinearEquiv D t
  map_one' := derivationFlow_map_one D hD one_mul' mul_one' t
  map_mul' := derivationFlow_map_mul D hD t

@[simp]
theorem expNonAssocDerivation_apply
    (D : Module.End ℝ A)
    (hD : ∀ x y : A, D (x * y) = D x * y + x * D y)
    (one_mul' : ∀ x : A, (1 : A) * x = x)
    (mul_one' : ∀ x : A, x * (1 : A) = x)
    (t : ℝ) (x : A) :
    expNonAssocDerivation D hD one_mul' mul_one' t x =
      derivationFlow D t x :=
  rfl

/-- Orbit form of the autonomous linear ODE `u' = D u`. -/
theorem expOrbit_hasDerivAt
    (D : Module.End ℝ A) (u₀ : A) (t : ℝ) :
    HasDerivAt (fun s => derivationFlow D s u₀)
      (D (derivationFlow D t u₀)) t :=
  (derivationFlow_apply_hasStrictDerivAt_left D u₀ t).hasDerivAt

@[simp]
theorem expOrbit_zero (D : Module.End ℝ A) (u₀ : A) :
    derivationFlow D 0 u₀ = u₀ := by
  simp

end InfoGeometry.Algebra.NonAssocDerivationExponential
