import InfoGeometry.Algebra.TensorAlgebraCanonical
import InfoGeometry.Algebra.InductiveSuperClosureLemmas
import InfoGeometry.Algebra.InfiniteSuperClosureLemmas
import InfoGeometry.Algebra.DirectLimitSuperClosureLemmas
import InfoGeometry.Algebra.FiniteInductiveSUSY
import InfoGeometry.Algebra.InfiniteInductiveSUSY

/-!
# Tensor-algebra inductive transport

This file specializes the repository's existing finite-stage, compatible-cone,
direct-limit, and SUSY induction lanes to Mathlib tensor algebras.

It does not introduce a new completion or Cantor-limit object.  A chain of
linear maps between modules induces a chain of tensor-algebra ring homomorphisms
by the Mathlib universal property of `TensorAlgebra`; all closure transport
below is delegated to the existing algebraic owner lemmas.
-/

noncomputable section

set_option autoImplicit false

namespace TensorAlgebraInduction

open InfoGeometry.Algebra.TensorAlgebraCanonical
open InfoGeometry.Algebra.InductiveSuperClosureLemmas

universe u v

section Functoriality

variable {R : Type u} [CommSemiring R]
variable {M N P : Type v}
variable [AddCommMonoid M] [Module R M]
variable [AddCommMonoid N] [Module R N]
variable [AddCommMonoid P] [Module R P]

/-- A linear map of generators induces an algebra homomorphism of tensor algebras. -/
def mapLinear (f : M →ₗ[R] N) : TensorAlgebra R M →ₐ[R] TensorAlgebra R N :=
  liftLinear ((includeLinear (R := R) (M := N)).comp f)

@[simp]
theorem mapLinear_include (f : M →ₗ[R] N) (x : M) :
    mapLinear f (includeLinear (R := R) x) = includeLinear (R := R) (f x) := by
  simp [mapLinear]

@[simp]
theorem mapLinear_id :
    mapLinear (R := R) (M := M) (N := M) LinearMap.id =
      AlgHom.id R (TensorAlgebra R M) := by
  apply algHom_ext_from_include
  ext x
  simp [mapLinear]

@[simp]
theorem mapLinear_comp (g : N →ₗ[R] P) (f : M →ₗ[R] N) :
    mapLinear (g.comp f) = (mapLinear g).comp (mapLinear f) := by
  apply algHom_ext_from_include
  ext x
  simp [mapLinear]

/-- Ring-homomorphism form used by the repository's induction lanes. -/
def mapLinearRing (f : M →ₗ[R] N) : TensorAlgebra R M →+* TensorAlgebra R N :=
  (mapLinear f).toRingHom

@[simp]
theorem mapLinearRing_include (f : M →ₗ[R] N) (x : M) :
    mapLinearRing f (includeLinear (R := R) x) = includeLinear (R := R) (f x) := by
  simp [mapLinearRing]

end Functoriality

section SemiringChain

variable {R : Type u} [CommSemiring R]
variable {V : ℕ → Type v}
variable [∀ n : ℕ, AddCommMonoid (V n)] [∀ n : ℕ, Module R (V n)]

/-- Tensor-algebra stages generated by a chain of modules. -/
abbrev TensorStage (R : Type u) [CommSemiring R] (V : ℕ → Type v)
    [∀ n : ℕ, AddCommMonoid (V n)] [∀ n : ℕ, Module R (V n)]
    (n : ℕ) : Type (max u v) :=
  TensorAlgebra R (V n)

/-- Tensor-algebra bonding maps induced from linear bonding maps of generators. -/
def tensorBond (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (n : ℕ) : TensorStage R V n →+* TensorStage R V (n + 1) :=
  mapLinearRing (R := R) (M := V n) (N := V (n + 1)) (f n)

@[simp]
theorem tensorBond_include
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (n : ℕ) (x : V n) :
    tensorBond f n (includeLinear (R := R) x) =
      includeLinear (R := R) (f n x) := by
  simp [tensorBond]

/-- Single-supercharge closure transported along tensor-algebra stages. -/
theorem tensor_superClosure_all
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (Q H Z : ∀ n : ℕ, TensorStage R V n)
    (h0 : SuperClosureAt Q H Z 0)
    (hQ : ∀ n, tensorBond f n (Q n) = Q (n + 1))
    (hH : ∀ n, tensorBond f n (H n) = H (n + 1))
    (hZ : ∀ n, tensorBond f n (Z n) = Z (n + 1)) :
    ∀ n : ℕ, SuperClosureAt Q H Z n := by
  exact superClosure_all (tensorBond f) Q H Z h0 hQ hH hZ

/-- Mixed odd-odd closure transported along tensor-algebra stages. -/
theorem tensor_mixedSuperClosure_all
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (QA QB K Z : ∀ n : ℕ, TensorStage R V n)
    (h0 : MixedSuperClosureAt QA QB K Z 0)
    (hQA : ∀ n, tensorBond f n (QA n) = QA (n + 1))
    (hQB : ∀ n, tensorBond f n (QB n) = QB (n + 1))
    (hK : ∀ n, tensorBond f n (K n) = K (n + 1))
    (hZ : ∀ n, tensorBond f n (Z n) = Z (n + 1)) :
    ∀ n : ℕ, MixedSuperClosureAt QA QB K Z n := by
  exact mixedSuperClosure_all (tensorBond f) QA QB K Z h0 hQA hQB hK hZ

/-- Algebraic direct limit of the tensor-algebra chain. -/
abbrev TensorDirectLimit (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1)) : Type (max u v) :=
  DirectLimitSuperClosureLemmas.DirectLimitSuperClosure
    (Stage := fun n => TensorStage R V n) (tensorBond f)

/-- Canonical map from a tensor-algebra stage into its algebraic direct limit. -/
def ofTensorStage
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (n : ℕ) : TensorStage R V n →+* TensorDirectLimit f :=
  DirectLimitSuperClosureLemmas.directLimitOf
    (Stage := fun n => TensorStage R V n) (tensorBond f) n

@[simp]
theorem ofTensorStage_bond
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (n : ℕ) (x : TensorStage R V n) :
    ofTensorStage f (n + 1) (tensorBond f n x) = ofTensorStage f n x := by
  exact DirectLimitSuperClosureLemmas.directLimitOf_bond
    (Stage := fun n => TensorStage R V n) (tensorBond f) n x

/-- Single-supercharge tensor closure on canonical images in the algebraic direct limit. -/
theorem tensor_directLimit_superClosure_all
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (Q H Z : ∀ n : ℕ, TensorStage R V n)
    (h0 : SuperClosureAt Q H Z 0)
    (hQ : ∀ n, tensorBond f n (Q n) = Q (n + 1))
    (hH : ∀ n, tensorBond f n (H n) = H (n + 1))
    (hZ : ∀ n, tensorBond f n (Z n) = Z (n + 1)) :
    ∀ n : ℕ,
      anticommutator (ofTensorStage f n (Q n)) (ofTensorStage f n (Q n)) =
        ofTensorStage f n (H n) + ofTensorStage f n (Z n) := by
  exact DirectLimitSuperClosureLemmas.directLimit_superClosure_all
    (Stage := fun n => TensorStage R V n)
    (tensorBond f) Q H Z h0 hQ hH hZ

/-- Mixed tensor closure on canonical images in the algebraic direct limit. -/
theorem tensor_directLimit_mixedSuperClosure_all
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (QA QB K Z : ∀ n : ℕ, TensorStage R V n)
    (h0 : MixedSuperClosureAt QA QB K Z 0)
    (hQA : ∀ n, tensorBond f n (QA n) = QA (n + 1))
    (hQB : ∀ n, tensorBond f n (QB n) = QB (n + 1))
    (hK : ∀ n, tensorBond f n (K n) = K (n + 1))
    (hZ : ∀ n, tensorBond f n (Z n) = Z (n + 1)) :
    ∀ n : ℕ,
      anticommutator (ofTensorStage f n (QA n)) (ofTensorStage f n (QB n)) =
        ofTensorStage f n (K n) + ofTensorStage f n (Z n) := by
  exact DirectLimitSuperClosureLemmas.directLimit_mixedSuperClosure_all
    (Stage := fun n => TensorStage R V n)
    (tensorBond f) QA QB K Z h0 hQA hQB hK hZ

/-- Image-local tensor closure in any compatible infinite target semiring. -/
theorem tensor_limitImage_superClosure_all
    {L : Type (max u v)} [Semiring L]
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (toLimit : ∀ n : ℕ, TensorStage R V n →+* L)
    (Q H Z : ∀ n : ℕ, TensorStage R V n)
    (h0 : SuperClosureAt Q H Z 0)
    (hQ : ∀ n, tensorBond f n (Q n) = Q (n + 1))
    (hH : ∀ n, tensorBond f n (H n) = H (n + 1))
    (hZ : ∀ n, tensorBond f n (Z n) = Z (n + 1)) :
    ∀ n : ℕ,
      anticommutator (toLimit n (Q n)) (toLimit n (Q n)) =
        toLimit n (H n) + toLimit n (Z n) := by
  exact InfiniteSuperClosureLemmas.limitImage_superClosure_all
    (Stage := fun n => TensorStage R V n)
    (Limit := L) (tensorBond f) toLimit Q H Z h0 hQ hH hZ

/-- Compatible-cone tensor closure in an external target, reduced to stage zero. -/
theorem tensor_compatibleCone_limitImage_superClosure_zeroStage
    {L : Type (max u v)} [Semiring L]
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (toLimit : ∀ n : ℕ, TensorStage R V n →+* L)
    (hcone : InfiniteSuperClosureLemmas.CompatibleCone (tensorBond f) toLimit)
    (Q H Z : ∀ n : ℕ, TensorStage R V n)
    (h0 : SuperClosureAt Q H Z 0)
    (hQ : ∀ n, tensorBond f n (Q n) = Q (n + 1))
    (hH : ∀ n, tensorBond f n (H n) = H (n + 1))
    (hZ : ∀ n, tensorBond f n (Z n) = Z (n + 1)) :
    ∀ n : ℕ,
      anticommutator (toLimit n (Q n)) (toLimit n (Q n)) =
        toLimit 0 (H 0) + toLimit 0 (Z 0) := by
  exact InfiniteSuperClosureLemmas.compatibleCone_limitImage_superClosure_zeroStage
    (Stage := fun n => TensorStage R V n)
    (Limit := L) (tensorBond f) toLimit hcone Q H Z h0 hQ hH hZ

end SemiringChain

section RingSUSYChain

variable {R : Type u} [CommRing R]
variable {V : ℕ → Type v}
variable [∀ n : ℕ, AddCommGroup (V n)] [∀ n : ℕ, Module R (V n)]

/-- Tensor-algebra nilpotency transported along a ring-valued SUSY chain. -/
theorem tensor_nilpotent_chain
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (Q : ∀ n : ℕ, TensorStage R V n)
    (hQ0 : Q 0 * Q 0 = 0)
    (hQstep : ∀ n : ℕ, Q (n + 1) = tensorBond f n (Q n)) :
    ∀ n : ℕ, Q n * Q n = 0 := by
  exact FiniteInductiveSUSY.nilpotent_chain (tensorBond f) Q hQ0 hQstep

/-- Tensor-algebra odd-odd SUSY closure transported along the finite chain. -/
theorem tensor_superclosure_chain
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (Q S H Z : ∀ n : ℕ, TensorStage R V n)
    (hclosure0 : FiniteInductiveSUSY.anticomm (Q 0) (S 0) = H 0 + Z 0)
    (hQstep : ∀ n : ℕ, Q (n + 1) = tensorBond f n (Q n))
    (hSstep : ∀ n : ℕ, S (n + 1) = tensorBond f n (S n))
    (hHstep : ∀ n : ℕ, H (n + 1) = tensorBond f n (H n))
    (hZstep : ∀ n : ℕ, Z (n + 1) = tensorBond f n (Z n)) :
    ∀ n : ℕ, FiniteInductiveSUSY.anticomm (Q n) (S n) = H n + Z n := by
  exact FiniteInductiveSUSY.superclosure_chain
    (tensorBond f) Q S H Z hclosure0 hQstep hSstep hHstep hZstep

/-- Tensor-algebra Dirac-square SUSY closure transported along the finite chain. -/
theorem tensor_dirac_square_closure_chain
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (Q S H Z : ∀ n : ℕ, TensorStage R V n)
    (hQ0 : Q 0 * Q 0 = 0)
    (hS0 : S 0 * S 0 = 0)
    (hclosure0 : FiniteInductiveSUSY.anticomm (Q 0) (S 0) = H 0 + Z 0)
    (hQstep : ∀ n : ℕ, Q (n + 1) = tensorBond f n (Q n))
    (hSstep : ∀ n : ℕ, S (n + 1) = tensorBond f n (S n))
    (hHstep : ∀ n : ℕ, H (n + 1) = tensorBond f n (H n))
    (hZstep : ∀ n : ℕ, Z (n + 1) = tensorBond f n (Z n)) :
    ∀ n : ℕ, (Q n + S n) * (Q n + S n) = H n + Z n := by
  exact FiniteInductiveSUSY.dirac_square_closure_chain
    (tensorBond f) Q S H Z hQ0 hS0 hclosure0 hQstep hSstep hHstep hZstep

/-- Image-local tensor SUSY closure in an explicit infinite target ring. -/
theorem tensor_limit_image_inductive_susy_closure
    {L : Type (max u v)} [Ring L]
    (f : ∀ n : ℕ, V n →ₗ[R] V (n + 1))
    (toLimit : ∀ n : ℕ, TensorStage R V n →+* L)
    (Q S H Z : ∀ n : ℕ, TensorStage R V n)
    (hQ0 : Q 0 * Q 0 = 0)
    (hS0 : S 0 * S 0 = 0)
    (hclosure0 : FiniteInductiveSUSY.anticomm (Q 0) (S 0) = H 0 + Z 0)
    (hZQ0 : Z 0 * Q 0 = Q 0 * Z 0)
    (hZS0 : Z 0 * S 0 = S 0 * Z 0)
    (hQstep : ∀ n : ℕ, Q (n + 1) = tensorBond f n (Q n))
    (hSstep : ∀ n : ℕ, S (n + 1) = tensorBond f n (S n))
    (hHstep : ∀ n : ℕ, H (n + 1) = tensorBond f n (H n))
    (hZstep : ∀ n : ℕ, Z (n + 1) = tensorBond f n (Z n)) :
    ∀ n : ℕ,
      toLimit n (Q n) * toLimit n (Q n) = 0 ∧
      toLimit n (S n) * toLimit n (S n) = 0 ∧
      FiniteInductiveSUSY.anticomm (toLimit n (Q n)) (toLimit n (S n)) =
        toLimit n (H n) + toLimit n (Z n) ∧
      toLimit n (Z n) * toLimit n (Q n) = toLimit n (Q n) * toLimit n (Z n) ∧
      toLimit n (Z n) * toLimit n (S n) = toLimit n (S n) * toLimit n (Z n) ∧
      toLimit n (Q n + S n) * toLimit n (Q n + S n) =
        toLimit n (H n) + toLimit n (Z n) := by
  exact InfiniteInductiveSUSY.limit_image_inductive_susy_closure
    (tensorBond f) toLimit Q S H Z hQ0 hS0 hclosure0 hZQ0 hZS0
    hQstep hSstep hHstep hZstep

end RingSUSYChain

end TensorAlgebraInduction
