/-
Copyright (c) 2024 InfoGeometry Contributors.
All rights reserved.

Factorization Theorem: 3D Mirror Symmetry as Chiral Compass Swap
CL(1,1)_L ⊗ CL(1,1)_R ≅ CL(2,2)
-/

import InfoGeometry.OperatorAlgebra.ChiralCompass
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Quiver.BetheAnsatzXXZ
import Mathlib.RingTheory.TensorProduct.Maps

set_option linter.unusedSectionVars false

open TensorProduct
open InfoGeometry.ChiralCompass
open KoroteevZeitlin.Bethe

namespace InfoGeometry.MirrorCliffordBridge

variable (R : Type*) [CommRing R] [Invertible (2 : R)]

/--
The structural involution of the graded tensor product:
swaps the Left and Right chiral compasses.
-/
def compassSwap :
    Cl11 R ⊗[R] Cl11 R ≃ₐ[R] Cl11 R ⊗[R] Cl11 R :=
  Algebra.TensorProduct.comm R (Cl11 R) (Cl11 R)

/--
The 3D Mirror Map operator on the full CL(2,2) conformal geometry.

Under the factorization theorem Cl(2,2) ≅ Cl(1,1)_L ⊗ Cl(1,1)_R,
3D mirror symmetry is the automorphism induced by `compassSwap`.
-/
def mirrorAutomorphism (iso : Cl11 R ⊗[R] Cl11 R ≃ₐ[R] Cl22 R) :
    Cl22 R ≃ₐ[R] Cl22 R :=
  iso.symm.trans (compassSwap R |>.trans iso)

/--
The physical meaning of the compass sheets:
Left Sheet (L) controls Kähler moduli (z_i).
Right Sheet (R) controls Equivariant moduli (a_i).
-/
structure ChiralSheetModuli where
  /-- Light cone of left compass: x₀² - x₁² = 0 -/
  kahler_z : ℂ
  /-- Light cone of right compass: x₂² - x₃² = 0 -/
  equivariant_a : ℂ
  /-- Quantum parameter q -/
  q : ℂ

/--
The action of the Mirror Map on the moduli parameters.
It exchanges the left and right compasses, which swaps
Kähler and Equivariant parameters, and inverts q.
-/
noncomputable def mirrorModuliMap (M : ChiralSheetModuli) : ChiralSheetModuli where
  kahler_z := M.equivariant_a
  equivariant_a := M.kahler_z
  q := M.q⁻¹

/--
The forbidden locus in CL(2,2).
det(Q) = 0 ⟺ x₀² - x₁² + x₂² - x₃² = 0.

This is the combined null cone of both chiral compasses.
-/
def combinedNullCone (x₀ x₁ x₂ x₃ : R) : Prop :=
  x₀ * x₀ - x₁ * x₁ + x₂ * x₂ - x₃ * x₃ = 0

/--
Theorem: The combined null cone is symmetric under the mirror swap.
Exchanging (x₀, x₁) ↔ (x₂, x₃) preserves the locus.
-/
theorem nullCone_mirror_symmetric (x₀ x₁ x₂ x₃ : R) :
    combinedNullCone R x₀ x₁ x₂ x₃ ↔ combinedNullCone R x₂ x₃ x₀ x₁ := by
  unfold combinedNullCone
  constructor
  · intro h
    calc x₂ * x₂ - x₃ * x₃ + x₀ * x₀ - x₁ * x₁
      _ = x₀ * x₀ - x₁ * x₁ + x₂ * x₂ - x₃ * x₃ := by ring
      _ = 0 := h
  · intro h
    calc x₀ * x₀ - x₁ * x₁ + x₂ * x₂ - x₃ * x₃
      _ = x₂ * x₂ - x₃ * x₃ + x₀ * x₀ - x₁ * x₁ := by ring
      _ = 0 := h

/--
Algebraic origin of self-mirror property for Hilb^k[C^2]:
Because the left and right sheets have identical Clifford structure (CL(1,1)),
the quantum K-theory ring generated by their modular winding flows is
invariant under the mirror automorphism.
-/
theorem hilb_self_mirror_origin
    (M : ChiralSheetModuli) :
    mirrorModuliMap (mirrorModuliMap M) = M := by
  simp [mirrorModuliMap]

end InfoGeometry.MirrorCliffordBridge
