import InfoGeometry.Canonical.SpinorialCore.All

#print axioms InfoGeometry.Canonical.SpinorialCore.mixed_bivector_square
#print axioms InfoGeometry.Canonical.SpinorialCore.innerDiff_square_is_even
#print axioms InfoGeometry.Canonical.SpinorialCore.order_one_factorization
#print axioms InfoGeometry.Canonical.SpinorialCore.polynomialTrace_conjugation
#print axioms InfoGeometry.Canonical.SpinorialCore.network_index_eq_trace
#print axioms InfoGeometry.Canonical.SpinorialCore.dual_coordinate_linearization
#print axioms InfoGeometry.Canonical.SpinorialCore.phase_conjugate_current
#print axioms InfoGeometry.Canonical.SpinorialCore.G2.smith_certificate
#print axioms InfoGeometry.Canonical.SpinorialCore.G2.cokernelEquiv
#print axioms InfoGeometry.Canonical.SpinorialCore.G2.relation_kernel_zero
#print axioms InfoGeometry.Canonical.SpinorialCore.G2.primaryDecomposition
#print axioms InfoGeometry.Canonical.SpinorialCore.G2.no_surjection_to_zmod16
