import proofs.BraidProject.FreeMonoid_mine
import proofs.BraidProject.Congruence_mine

/-!
# Presented Monoids, Compatibility Layer

This is the small presentation API used by the braid monoid files.  A presented
monoid is the quotient of the free monoid by the congruence generated by the
given relations.
-/

variable {α β : Type*}

/-- The monoid presented by generators `α` and relations `rel`. -/
def PresentedMonoid (rel : FreeMonoid' α → FreeMonoid' α → Prop) :=
  (con'Gen rel).Quotient

namespace PresentedMonoid

instance (rels : FreeMonoid' α → FreeMonoid' α → Prop) : Monoid (PresentedMonoid rels) :=
  Con'.monoid (con'Gen rels)

/-- Quotient map from the free monoid. -/
def mk (rels : FreeMonoid' α → FreeMonoid' α → Prop) (a : FreeMonoid' α) :
    PresentedMonoid rels :=
  _root_.Quotient.mk (con'Gen rels).toSetoid a

@[simp] theorem mul_mk (rels : FreeMonoid' α → FreeMonoid' α → Prop)
    (a b : FreeMonoid' α) :
    mk rels (a * b) = mk rels a * mk rels b := rfl

@[simp] theorem one_def (rels : FreeMonoid' α → FreeMonoid' α → Prop) :
    mk rels 1 = (1 : PresentedMonoid rels) := rfl

/-- Canonical generator. -/
def of (rels : FreeMonoid' α → FreeMonoid' α → Prop) (x : α) :
    PresentedMonoid rels :=
  mk rels (FreeMonoid'.of x)

@[elab_as_elim, induction_eliminator]
protected theorem inductionOn {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {δ : PresentedMonoid rels → Prop} (q : PresentedMonoid rels)
    (h : ∀ a, δ (mk rels a)) : δ q :=
  _root_.Quotient.ind h q

/-- The generated relation of a presentation. -/
def rel (rels : FreeMonoid' α → FreeMonoid' α → Prop) :=
  Con'Gen.Rel rels

theorem refl {rels : FreeMonoid' α → FreeMonoid' α → Prop} {a : FreeMonoid' α} :
    rel rels a a :=
  Con'Gen.Rel.refl a

theorem reg {rels : FreeMonoid' α → FreeMonoid' α → Prop} {a b : FreeMonoid' α} :
    ∀ c d, rels a b → rel rels (c * a * d) (c * b * d) :=
  fun c d h =>
    Con'Gen.Rel.mul
      (Con'Gen.Rel.mul (Con'Gen.Rel.refl c) (Con'Gen.Rel.of a b h))
      (Con'Gen.Rel.refl d)

theorem symm {rels : FreeMonoid' α → FreeMonoid' α → Prop} {a b : FreeMonoid' α} :
    ∀ c d, rels a b → rel rels (c * b * d) (c * a * d) :=
  fun c d h =>
    Con'Gen.Rel.mul
      (Con'Gen.Rel.mul (Con'Gen.Rel.refl c) (Con'Gen.Rel.symm (Con'Gen.Rel.of a b h)))
      (Con'Gen.Rel.refl d)

theorem trans {rels : FreeMonoid' α → FreeMonoid' α → Prop} {a b c : FreeMonoid' α} :
    rel rels a b → rel rels b c → rel rels a c :=
  Con'Gen.Rel.trans

theorem mul {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b c d : FreeMonoid' α} :
    rel rels a b → rel rels c d → rel rels (a * c) (b * d) :=
  Con'Gen.Rel.mul

theorem append_left {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a c d : FreeMonoid' α} :
    rel rels c d → rel rels (a * c) (a * d) :=
  fun h => Con'Gen.Rel.mul (Con'Gen.Rel.refl a) h

theorem append_right {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b c : FreeMonoid' α} :
    rel rels a b → rel rels (a * c) (b * c) :=
  fun h => Con'Gen.Rel.mul h (Con'Gen.Rel.refl c)

theorem rel_left {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a c d : FreeMonoid' α} :
    rels c d → rel rels (a * c) (a * d) :=
  fun h => append_left (Con'Gen.Rel.of c d h)

theorem rel_right {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b c : FreeMonoid' α} :
    rels a b → rel rels (a * c) (b * c) :=
  fun h => append_right (Con'Gen.Rel.of a b h)

theorem rel_alone {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} :
    rels a b → rel rels a b :=
  fun h => Con'Gen.Rel.of a b h

theorem symm_alone {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} :
    rels a b → rel rels b a :=
  fun h => Con'Gen.Rel.symm (Con'Gen.Rel.of a b h)

theorem swap {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} :
    rel rels a b → rel rels b a :=
  Con'Gen.Rel.symm

protected theorem sound {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} (h : rel rels a b) :
    mk rels a = mk rels b :=
  _root_.Quotient.sound h

theorem exact {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} (h : mk rels a = mk rels b) :
    rel rels a b :=
  _root_.Quotient.exact h

/-- Lift a function out of a presented monoid when it respects multiplication and relations. -/
def lift_of_mul {rels : FreeMonoid' α → FreeMonoid' α → Prop} {β : Type*}
    (f : FreeMonoid' α → β)
    (hm : ∀ {a b c d}, f a = f c → f b = f d → f (a * b) = f (c * d))
    (h : ∀ (a b : FreeMonoid' α), rels a b → f a = f b) :
    PresentedMonoid rels → β :=
  fun q =>
    _root_.Quotient.liftOn q f (by
      intro a b hr
      induction hr with
      | of x y hxy => exact h x y hxy
      | refl x => rfl
      | symm hxy ih => exact ih.symm
      | trans hxy hyz ihxy ihyz => exact ihxy.trans ihyz
      | mul h₁ h₂ ih₁ ih₂ => exact hm ih₁ ih₂)

@[simp] theorem lift_of_mul_mk {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {β : Type*} (x : FreeMonoid' α) (f : FreeMonoid' α → β)
    (hm : ∀ {a b c d}, f a = f c → f b = f d → f (a * b) = f (c * d))
    (h : ∀ (a b : FreeMonoid' α), rels a b → f a = f b) :
    lift_of_mul f hm h (mk rels x) = f x := rfl

section ToMonoid

variable {M : Type*} [Monoid M] (f : α → M)
variable {rels : FreeMonoid' α → FreeMonoid' α → Prop}
variable (h : ∀ a b : FreeMonoid' α, rels a b → FreeMonoid'.lift f a = FreeMonoid'.lift f b)

/-- Extend a generator map respecting the presentation relations to a monoid homomorphism. -/
def toMonoid : PresentedMonoid rels →* M where
  toFun :=
    lift_of_mul (FreeMonoid'.lift f)
      (fun h₁ h₂ => by
        rw [MonoidHom.map_mul, MonoidHom.map_mul, h₁, h₂])
      h
  map_one' := rfl
  map_mul' := by
    intro x y
    induction x using PresentedMonoid.inductionOn with
    | h a =>
      induction y using PresentedMonoid.inductionOn with
      | h b =>
        exact MonoidHom.map_mul (FreeMonoid'.lift f) a b

@[simp] theorem toMonoid.of {x : α} :
    (toMonoid f h) (of rels x) = f x := by
  unfold PresentedMonoid.toMonoid PresentedMonoid.of PresentedMonoid.mk PresentedMonoid.lift_of_mul
  change (FreeMonoid'.lift f) (FreeMonoid'.of x) = f x
  exact FreeMonoid'.lift_eval_of f x

end ToMonoid

private inductive rw_system (rels : FreeMonoid' α → FreeMonoid' α → Prop) :
    FreeMonoid' α → FreeMonoid' α → Prop
  | refl : rw_system rels a a
  | reg : ∀ c d, rels a b → rw_system rels (c * a * d) (c * b * d)
  | symm : ∀ c d, rels a b → rw_system rels (c * b * d) (c * a * d)
  | trans : rw_system rels a b → rw_system rels b c → rw_system rels a c

private theorem rw_system_symm {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} :
    rw_system rels a b → rw_system rels b a := by
  intro h
  induction h with
  | refl => exact rw_system.refl
  | reg c d h => exact rw_system.symm c d h
  | symm c d h => exact rw_system.reg c d h
  | trans _ _ ih₁ ih₂ => exact rw_system.trans ih₂ ih₁

private theorem mul_front {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b c : FreeMonoid' α} :
    rw_system rels a b → rw_system rels (a * c) (b * c) := by
  intro h
  induction h with
  | refl => exact rw_system.refl
  | reg p q h =>
      rw [mul_assoc _ q c, mul_assoc _ q c]
      exact rw_system.reg p (q * c) h
  | symm p q h =>
      rw [mul_assoc _ q c, mul_assoc _ q c]
      exact rw_system.symm p (q * c) h
  | trans _ _ ih₁ ih₂ => exact rw_system.trans ih₁ ih₂

private theorem mul_back {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b c : FreeMonoid' α} :
    rw_system rels a b → rw_system rels (c * a) (c * b) := by
  intro h
  induction h with
  | refl => exact rw_system.refl
  | reg p q h =>
      rw [← mul_assoc, ← mul_assoc, ← mul_assoc, ← mul_assoc]
      exact rw_system.reg (c * p) q h
  | symm p q h =>
      rw [← mul_assoc, ← mul_assoc, ← mul_assoc, ← mul_assoc]
      exact rw_system.symm (c * p) q h
  | trans _ _ ih₁ ih₂ => exact rw_system.trans ih₁ ih₂

private theorem rw_system_mul {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b c d : FreeMonoid' α} :
    rw_system rels a b → rw_system rels c d → rw_system rels (a * c) (b * d) := by
  intro h₁ h₂
  exact rw_system.trans (mul_front h₁) (mul_back h₂)

private theorem rw_system_cg {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {a b : FreeMonoid' α} :
    rw_system rels a b ↔ rel rels a b := by
  constructor
  · intro h
    induction h with
    | refl => exact refl
    | reg c d h => exact reg c d h
    | symm c d h => exact symm c d h
    | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  · intro h
    induction h with
    | of x y hxy =>
        rw [← mul_one x, ← mul_one y, ← one_mul x, ← one_mul y]
        exact rw_system.reg 1 1 hxy
    | refl x => exact rw_system.refl
    | symm hxy ih => exact rw_system_symm ih
    | trans h₁ h₂ ih₁ ih₂ => exact rw_system.trans ih₁ ih₂
    | mul h₁ h₂ ih₁ ih₂ => exact rw_system_mul ih₁ ih₂

/-- Contextual induction over generated presentation relations. -/
theorem rel_induction_rw {rels : FreeMonoid' α → FreeMonoid' α → Prop}
    {P : FreeMonoid' α → FreeMonoid' α → Prop} {a b : FreeMonoid' α}
    (h : rel rels a b)
    (h1 : ∀ a, P a a)
    (h2 : ∀ a b {c d}, rels a b → P (c * a * d) (c * b * d))
    (h3 : ∀ a b {c d}, rels b a → P (c * a * d) (c * b * d))
    (h4 : ∀ a b c, P a b ∧ P b c → P a c) :
    P a b := by
  have hrw : rw_system rels a b := rw_system_cg.mpr h
  induction hrw with
  | refl => exact h1 _
  | reg c d hr => exact h2 _ _ hr
  | symm c d hr => exact h3 _ _ hr
  | trans h₁ h₂ ih₁ ih₂ =>
      exact h4 _ _ _ ⟨ih₁ (rw_system_cg.mp h₁), ih₂ (rw_system_cg.mp h₂)⟩

end PresentedMonoid
