import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Analysis.Calculus.ContDiff.Basic
import Mathlib.Analysis.Calculus.ContDiff.Operations
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.Convex.SpecificFunctions.Basic
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Data.Fintype.Basic
import Mathlib.Tactic.Ring
import InfoGeometry.Convex.Bregman

open scoped BigOperators

/-!
# Log-Sum-Exp (Finite)

Finite log-sum-exp potentials with smoothness and positivity facts used by
the Legendre/exponential-family bridge.
-/

namespace InfoGeometry.Analytic

/-- Unnormalized partition sum underlying finite `logSumExp`. -/
noncomputable def logSumExpPartition
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  ∑ i, w i * Real.exp (θ * a i)

/-- Finite log-sum-exp potential with weights `w` and slopes `a`. -/
noncomputable def logSumExp
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  Real.log (logSumExpPartition w a θ)

/-- Softmax/Gibbs weights induced by finite `logSumExp` data. -/
noncomputable def logSumExpWeight
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) (i : ι) : ℝ :=
  w i * Real.exp (θ * a i) / logSumExpPartition w a θ

/-- Unnormalized first moment `∑ wᵢ e^{θ aᵢ} aᵢ`. -/
noncomputable def logSumExpMoment1
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  ∑ i, w i * Real.exp (θ * a i) * a i

/-- Unnormalized second moment `∑ wᵢ e^{θ aᵢ} aᵢ²`. -/
noncomputable def logSumExpMoment2
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  ∑ i, w i * Real.exp (θ * a i) * (a i) ^ (2 : ℕ)

/-- Mean of slopes under the softmax/Gibbs weights. -/
noncomputable def logSumExpMean
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  logSumExpMoment1 w a θ / logSumExpPartition w a θ

/-- Second moment of slopes under the softmax/Gibbs weights. -/
noncomputable def logSumExpSecondMoment
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  logSumExpMoment2 w a θ / logSumExpPartition w a θ

/-- Variance of slopes under the softmax/Gibbs weights. -/
noncomputable def logSumExpVariance
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) : ℝ :=
  logSumExpSecondMoment w a θ - (logSumExpMean w a θ) ^ (2 : ℕ)

/-- `ε`-scaled partition sum `Z_ε(θ) = ∑ᵢ wᵢ exp((θ aᵢ)/ε)`. -/
noncomputable def logSumExpScaledPartition
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (ε θ : ℝ) : ℝ :=
  logSumExpPartition w (fun i => a i / ε) θ

/-- `ε`-scaled potential `ψ_ε(θ) = ε log Z_ε(θ)`. -/
noncomputable def logSumExpScaled
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (ε θ : ℝ) : ℝ :=
  ε * logSumExp w (fun i => a i / ε) θ

/-- `ε`-scaled Gibbs/softmax weights. -/
noncomputable def logSumExpScaledWeight
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (ε θ : ℝ) (i : ι) : ℝ :=
  logSumExpWeight w (fun j => a j / ε) θ i

/-- Mean slope under `ε`-scaled Gibbs weights. -/
noncomputable def logSumExpScaledMean
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (ε θ : ℝ) : ℝ :=
  ∑ i, logSumExpScaledWeight w a ε θ i * a i

/-- Parameterized KL divergence for the `ε`-scaled Gibbs family. -/
noncomputable def logSumExpScaledKL
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (ε θ η : ℝ) : ℝ :=
  ∑ i, logSumExpScaledWeight w a ε θ i *
    (Real.log (logSumExpScaledWeight w a ε θ i)
      - Real.log (logSumExpScaledWeight w a ε η i))

/-- Bregman divergence generated by `ψ_ε`. -/
noncomputable def logSumExpScaledBregman
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (ε η θ : ℝ) : ℝ :=
  InfoGeometry.bregmanDiv (logSumExpScaled w a ε) η θ

/-- Positivity of the finite weighted exponential sum for strictly positive weights. -/
lemma logSumExp_sum_pos
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    0 < logSumExpPartition w a θ := by
  classical
  unfold logSumExpPartition
  simpa using
    (Finset.sum_pos
      (s := (Finset.univ : Finset ι))
      (f := fun i => w i * Real.exp (θ * a i))
      (by
        intro i hi
        exact mul_pos (hw i) (Real.exp_pos _))
      Finset.univ_nonempty)

lemma logSumExpScaledPartition_pos
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    0 < logSumExpScaledPartition w a ε θ := by
  simpa [logSumExpScaledPartition] using
    logSumExp_sum_pos (w := w) (a := fun i => a i / ε) hw θ

lemma logSumExpWeight_sum_one
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    ∑ i, logSumExpWeight w a θ i = 1 := by
  unfold logSumExpWeight
  have hZne : logSumExpPartition w a θ ≠ 0 :=
    (logSumExp_sum_pos w a hw θ).ne'
  calc
    ∑ i, w i * Real.exp (θ * a i) / logSumExpPartition w a θ
        = (∑ i, w i * Real.exp (θ * a i)) / logSumExpPartition w a θ := by
            symm
            simpa [logSumExpPartition] using
              (Finset.sum_div
                (s := (Finset.univ : Finset ι))
                (f := fun i => w i * Real.exp (θ * a i))
                (a := logSumExpPartition w a θ))
    _ = 1 := by
          rw [show (∑ i, w i * Real.exp (θ * a i)) = logSumExpPartition w a θ by rfl]
          exact div_self hZne

lemma logSumExpWeight_pos
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) (i : ι) :
    0 < logSumExpWeight w a θ i := by
  unfold logSumExpWeight
  exact div_pos
    (mul_pos (hw i) (Real.exp_pos _))
    (logSumExp_sum_pos w a hw θ)

lemma logSumExpScaledWeight_sum_one
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    ∑ i, logSumExpScaledWeight w a ε θ i = 1 := by
  simpa [logSumExpScaledWeight] using
    logSumExpWeight_sum_one (w := w) (a := fun i => a i / ε) hw θ

lemma logSumExpScaledWeight_pos
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) (i : ι) :
    0 < logSumExpScaledWeight w a ε θ i := by
  simpa [logSumExpScaledWeight] using
    logSumExpWeight_pos (w := w) (a := fun j => a j / ε) hw θ i

lemma hasDerivAt_logSumExpPartition_term
    {ι : Type _}
    (w a : ι → ℝ) (i : ι) (θ : ℝ) :
    HasDerivAt
      (fun t : ℝ => w i * Real.exp (t * a i))
      (w i * (a i * Real.exp (θ * a i)))
      θ := by
  have hlin : HasDerivAt (fun t : ℝ => t * a i) (a i) θ := by
    simpa [mul_comm, mul_left_comm, mul_assoc] using
      ((hasDerivAt_id' θ).mul_const (a i))
  have hExp :
      HasDerivAt (fun t : ℝ => Real.exp (t * a i))
        (a i * Real.exp (θ * a i)) θ := by
    simpa [mul_comm, mul_left_comm, mul_assoc] using
      (Real.hasDerivAt_exp (θ * a i)).comp θ hlin
  simpa [mul_assoc, mul_left_comm, mul_comm] using hExp.const_mul (w i)

lemma hasDerivAt_logSumExpPartition
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) :
    HasDerivAt (logSumExpPartition w a) (logSumExpMoment1 w a θ) θ := by
  classical
  unfold logSumExpPartition logSumExpMoment1
  simpa [mul_assoc, mul_left_comm, mul_comm] using
    (HasDerivAt.fun_sum
      (u := (Finset.univ : Finset ι))
      (fun i _ => hasDerivAt_logSumExpPartition_term (w := w) (a := a) (i := i) (θ := θ)))

lemma deriv_logSumExpPartition
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) :
    deriv (logSumExpPartition w a) θ = logSumExpMoment1 w a θ :=
  (hasDerivAt_logSumExpPartition w a θ).deriv

lemma hasDerivAt_logSumExpMoment1
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) :
    HasDerivAt (logSumExpMoment1 w a) (logSumExpMoment2 w a θ) θ := by
  classical
  unfold logSumExpMoment1 logSumExpMoment2
  refine (HasDerivAt.fun_sum (u := (Finset.univ : Finset ι)) (fun i _ => ?_))
  have hbase :
      HasDerivAt
        (fun t : ℝ => w i * Real.exp (t * a i))
        (w i * (a i * Real.exp (θ * a i)))
        θ :=
    hasDerivAt_logSumExpPartition_term (w := w) (a := a) (i := i) (θ := θ)
  have hmul :
      HasDerivAt
        (fun t : ℝ => (w i * Real.exp (t * a i)) * a i)
        ((w i * (a i * Real.exp (θ * a i))) * a i)
        θ :=
    hbase.mul_const (a i)
  simpa [pow_two, mul_assoc, mul_left_comm, mul_comm] using hmul

lemma deriv_logSumExpMoment1
    {ι : Type _} [Fintype ι]
    (w a : ι → ℝ) (θ : ℝ) :
    deriv (logSumExpMoment1 w a) θ = logSumExpMoment2 w a θ :=
  (hasDerivAt_logSumExpMoment1 w a θ).deriv

lemma logSumExpMean_eq_weighted_sum
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    logSumExpMean w a θ = ∑ i, logSumExpWeight w a θ i * a i := by
  unfold logSumExpMean logSumExpMoment1 logSumExpWeight
  have hZne : logSumExpPartition w a θ ≠ 0 :=
    (logSumExp_sum_pos w a hw θ).ne'
  calc
    (∑ i, w i * Real.exp (θ * a i) * a i) / logSumExpPartition w a θ
        = ∑ i, (w i * Real.exp (θ * a i) * a i) / logSumExpPartition w a θ := by
            simpa using
              (Finset.sum_div
                (s := (Finset.univ : Finset ι))
                (f := fun i => w i * Real.exp (θ * a i) * a i)
                (a := logSumExpPartition w a θ))
    _ = ∑ i, (w i * Real.exp (θ * a i) / logSumExpPartition w a θ) * a i := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          field_simp [hZne]
    _ = ∑ i, logSumExpWeight w a θ i * a i := by
          rfl

lemma logSumExpSecondMoment_eq_weighted_sum
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    logSumExpSecondMoment w a θ = ∑ i, logSumExpWeight w a θ i * (a i) ^ (2 : ℕ) := by
  unfold logSumExpSecondMoment logSumExpMoment2 logSumExpWeight
  have hZne : logSumExpPartition w a θ ≠ 0 :=
    (logSumExp_sum_pos w a hw θ).ne'
  calc
    (∑ i, w i * Real.exp (θ * a i) * (a i) ^ (2 : ℕ)) / logSumExpPartition w a θ
        =
      ∑ i, (w i * Real.exp (θ * a i) * (a i) ^ (2 : ℕ)) / logSumExpPartition w a θ := by
            simpa using
              (Finset.sum_div
                (s := (Finset.univ : Finset ι))
                (f := fun i => w i * Real.exp (θ * a i) * (a i) ^ (2 : ℕ))
                (a := logSumExpPartition w a θ))
    _ = ∑ i, (w i * Real.exp (θ * a i) / logSumExpPartition w a θ) * (a i) ^ (2 : ℕ) := by
          refine Finset.sum_congr rfl ?_
          intro i hi
          field_simp [hZne]
    _ = ∑ i, logSumExpWeight w a θ i * (a i) ^ (2 : ℕ) := by
          rfl

lemma logSumExp_deriv_eq_ratio
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    deriv (logSumExp w a) θ
      = logSumExpMoment1 w a θ / logSumExpPartition w a θ := by
  have hdiff : DifferentiableAt ℝ (logSumExpPartition w a) θ :=
    (hasDerivAt_logSumExpPartition (w := w) (a := a) (θ := θ)).differentiableAt
  have hne : logSumExpPartition w a θ ≠ 0 :=
    (logSumExp_sum_pos w a hw θ).ne'
  unfold logSumExp
  calc
    deriv (fun t => Real.log (logSumExpPartition w a t)) θ
        = deriv (logSumExpPartition w a) θ / logSumExpPartition w a θ := by
            simpa using (deriv.log (f := logSumExpPartition w a) hdiff hne)
    _ = logSumExpMoment1 w a θ / logSumExpPartition w a θ := by
          rw [deriv_logSumExpPartition]

lemma logSumExp_deriv_eq_mean
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    deriv (logSumExp w a) θ = logSumExpMean w a θ := by
  simpa [logSumExpMean] using logSumExp_deriv_eq_ratio (w := w) (a := a) hw θ

lemma logSumExp_secondDeriv_eq_ratio
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    deriv (fun t => deriv (logSumExp w a) t) θ
      =
      (logSumExpMoment2 w a θ * logSumExpPartition w a θ
        - logSumExpMoment1 w a θ * logSumExpMoment1 w a θ)
        / (logSumExpPartition w a θ) ^ (2 : ℕ) := by
  have hderiv :
      (fun t => deriv (logSumExp w a) t)
        = fun t => logSumExpMoment1 w a t / logSumExpPartition w a t := by
    funext t
    simpa using logSumExp_deriv_eq_ratio (w := w) (a := a) hw t
  rw [hderiv]
  have hnumDiff : DifferentiableAt ℝ (logSumExpMoment1 w a) θ :=
    (hasDerivAt_logSumExpMoment1 (w := w) (a := a) (θ := θ)).differentiableAt
  have hdenDiff : DifferentiableAt ℝ (logSumExpPartition w a) θ :=
    (hasDerivAt_logSumExpPartition (w := w) (a := a) (θ := θ)).differentiableAt
  have hZne : logSumExpPartition w a θ ≠ 0 :=
    (logSumExp_sum_pos w a hw θ).ne'
  calc
    deriv (fun t => logSumExpMoment1 w a t / logSumExpPartition w a t) θ
        =
        (deriv (logSumExpMoment1 w a) θ * logSumExpPartition w a θ
          - logSumExpMoment1 w a θ * deriv (logSumExpPartition w a) θ)
          / (logSumExpPartition w a θ) ^ (2 : ℕ) := by
            simpa using
              (deriv_div
                (c := logSumExpMoment1 w a)
                (d := logSumExpPartition w a)
                (x := θ) hnumDiff hdenDiff hZne)
    _ =
      (logSumExpMoment2 w a θ * logSumExpPartition w a θ
        - logSumExpMoment1 w a θ * logSumExpMoment1 w a θ)
        / (logSumExpPartition w a θ) ^ (2 : ℕ) := by
          rw [deriv_logSumExpMoment1, deriv_logSumExpPartition]

lemma logSumExp_secondDeriv_eq_variance
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) :
    deriv (fun t => deriv (logSumExp w a) t) θ = logSumExpVariance w a θ := by
  rw [logSumExpVariance, logSumExpSecondMoment, logSumExpMean]
  rw [logSumExp_secondDeriv_eq_ratio (w := w) (a := a) hw θ]
  have hZne : logSumExpPartition w a θ ≠ 0 :=
    (logSumExp_sum_pos w a hw θ).ne'
  field_simp [hZne]

lemma logSumExpScaledMean_eq_eps_mul_mean
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (heps : ε ≠ 0)
    (θ : ℝ) :
    logSumExpScaledMean w a ε θ
      = ε * logSumExpMean w (fun i => a i / ε) θ := by
  let p : ι → ℝ := fun i => logSumExpScaledWeight w a ε θ i
  have hmean :
      logSumExpMean w (fun i => a i / ε) θ
        = ∑ i, p i * (a i / ε) := by
    simpa [p, logSumExpScaledWeight] using
      logSumExpMean_eq_weighted_sum (w := w) (a := fun i => a i / ε) hw θ
  unfold logSumExpScaledMean
  calc
    ∑ i, p i * a i
        = ∑ i, ε * (p i * (a i / ε)) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            have hεi : ε * (a i / ε) = a i := by
              field_simp [heps]
            calc
              p i * a i = p i * (ε * (a i / ε)) := by rw [hεi]
              _ = ε * (p i * (a i / ε)) := by ring
    _ = ε * ∑ i, p i * (a i / ε) := by
          rw [Finset.mul_sum]
    _ = ε * logSumExpMean w (fun i => a i / ε) θ := by
          rw [hmean]

/-- First derivative of `ψ_ε` equals the `ε`-scaled Gibbs mean. -/
lemma logSumExpScaled_deriv_eq_mean
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (heps : ε ≠ 0)
    (θ : ℝ) :
    deriv (logSumExpScaled w a ε) θ = logSumExpScaledMean w a ε θ := by
  unfold logSumExpScaled
  calc
    deriv (fun t => ε * logSumExp w (fun i => a i / ε) t) θ
        = ε * deriv (fun t => logSumExp w (fun i => a i / ε) t) θ := by
            rw [deriv_const_mul_field]
    _ = ε * logSumExpMean w (fun i => a i / ε) θ := by
          rw [logSumExp_deriv_eq_mean (w := w) (a := fun i => a i / ε) hw θ]
    _ = logSumExpScaledMean w a ε θ := by
          symm
          exact logSumExpScaledMean_eq_eps_mul_mean
            (w := w) (a := a) (ε := ε) hw heps θ

lemma logSumExpScaled_logWeight_eq
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (θ : ℝ) (i : ι) :
    Real.log (logSumExpScaledWeight w a ε θ i)
      =
      Real.log (w i)
        + (θ * a i) / ε
        - Real.log (logSumExpScaledPartition w a ε θ) := by
  unfold logSumExpScaledWeight logSumExpWeight
  have hwi : w i ≠ 0 := (hw i).ne'
  have hexp : Real.exp (θ * (a i / ε)) ≠ 0 := (Real.exp_pos _).ne'
  have hZ : logSumExpScaledPartition w a ε θ ≠ 0 :=
    (logSumExpScaledPartition_pos (w := w) (a := a) (ε := ε) hw θ).ne'
  calc
    Real.log (w i * Real.exp (θ * (a i / ε)) / logSumExpScaledPartition w a ε θ)
        =
        Real.log (w i * Real.exp (θ * (a i / ε)))
          - Real.log (logSumExpScaledPartition w a ε θ) := by
            rw [Real.log_div (mul_ne_zero hwi hexp) hZ]
    _ =
      Real.log (w i) + Real.log (Real.exp (θ * (a i / ε)))
        - Real.log (logSumExpScaledPartition w a ε θ) := by
          rw [Real.log_mul hwi hexp]
    _ =
      Real.log (w i) + (θ * (a i / ε))
        - Real.log (logSumExpScaledPartition w a ε θ) := by
          simp
    _ =
      Real.log (w i) + (θ * a i) / ε
        - Real.log (logSumExpScaledPartition w a ε θ) := by
          ring

/-- Expanded KL formula for the `ε`-scaled Gibbs family. -/
lemma logSumExpScaledKL_eq
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (θ η : ℝ) :
    logSumExpScaledKL w a ε θ η
      =
      ((θ - η) / ε) * logSumExpScaledMean w a ε θ
        -
      (Real.log (logSumExpScaledPartition w a ε θ)
        - Real.log (logSumExpScaledPartition w a ε η)) := by
  unfold logSumExpScaledKL logSumExpScaledMean
  calc
    ∑ i,
      logSumExpScaledWeight w a ε θ i
        *
      (Real.log (logSumExpScaledWeight w a ε θ i)
        - Real.log (logSumExpScaledWeight w a ε η i))
      =
      ∑ i,
        logSumExpScaledWeight w a ε θ i
          *
        ((((θ - η) * a i) / ε)
          - (Real.log (logSumExpScaledPartition w a ε θ)
            - Real.log (logSumExpScaledPartition w a ε η))) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            rw [logSumExpScaled_logWeight_eq (w := w) (a := a) (ε := ε) hw θ i]
            rw [logSumExpScaled_logWeight_eq (w := w) (a := a) (ε := ε) hw η i]
            ring
    _ =
      ∑ i,
        (((θ - η) / ε) * (logSumExpScaledWeight w a ε θ i * a i)
          - (Real.log (logSumExpScaledPartition w a ε θ)
              - Real.log (logSumExpScaledPartition w a ε η))
              * logSumExpScaledWeight w a ε θ i) := by
            refine Finset.sum_congr rfl ?_
            intro i hi
            ring
    _ =
      ((θ - η) / ε) * (∑ i, logSumExpScaledWeight w a ε θ i * a i)
        -
      (Real.log (logSumExpScaledPartition w a ε θ)
        - Real.log (logSumExpScaledPartition w a ε η))
        * (∑ i, logSumExpScaledWeight w a ε θ i) := by
          rw [Finset.sum_sub_distrib, Finset.mul_sum, Finset.mul_sum]
    _ =
      ((θ - η) / ε) * logSumExpScaledMean w a ε θ
        -
      (Real.log (logSumExpScaledPartition w a ε θ)
        - Real.log (logSumExpScaledPartition w a ε η)) := by
          rw [show (∑ i, logSumExpScaledWeight w a ε θ i * a i)
              = logSumExpScaledMean w a ε θ by rfl]
          rw [logSumExpScaledWeight_sum_one (w := w) (a := a) (ε := ε) hw θ]
          ring

/-- `ε`-scaled KL as an inverse-temperature weighted primal gap. -/
lemma logSumExpScaledKL_eq_inv_eps_mul_gap
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (heps : ε ≠ 0)
    (θ η : ℝ) :
    logSumExpScaledKL w a ε θ η
      =
      (1 / ε) *
        ((θ - η) * logSumExpScaledMean w a ε θ
          - (logSumExpScaled w a ε θ - logSumExpScaled w a ε η)) := by
  rw [logSumExpScaledKL_eq (w := w) (a := a) (ε := ε) hw θ η]
  unfold logSumExpScaled logSumExpScaledPartition logSumExpPartition logSumExp
  simp [logSumExpPartition]
  field_simp [heps]

/-- KL/Bregman identity for the `ε`-scaled potential:
`KL_ε = (1/ε) * Bregman(ψ_ε)`. -/
lemma logSumExpScaledKL_eq_inv_eps_mul_bregman
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (heps : ε ≠ 0)
    (θ η : ℝ) :
    logSumExpScaledKL w a ε θ η
      = (1 / ε) * logSumExpScaledBregman w a ε η θ := by
  rw [logSumExpScaledKL_eq_inv_eps_mul_gap (w := w) (a := a) (ε := ε) hw heps θ η]
  unfold logSumExpScaledBregman InfoGeometry.bregmanDiv
  rw [logSumExpScaled_deriv_eq_mean (w := w) (a := a) (ε := ε) hw heps θ]
  ring

/-- Equivalent scaled form: `Bregman(ψ_ε) = ε * KL_ε`. -/
lemma logSumExpScaledBregman_eq_eps_mul_KL
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ) (ε : ℝ)
    (hw : ∀ i, 0 < w i)
    (heps : ε ≠ 0)
    (θ η : ℝ) :
    logSumExpScaledBregman w a ε η θ
      = ε * logSumExpScaledKL w a ε θ η := by
  have hKL :
      (1 / ε) * logSumExpScaledBregman w a ε η θ
        = logSumExpScaledKL w a ε θ η := by
    simpa [eq_comm] using
      (logSumExpScaledKL_eq_inv_eps_mul_bregman
        (w := w) (a := a) (ε := ε) hw heps θ η)
  calc
    logSumExpScaledBregman w a ε η θ
        = ε * ((1 / ε) * logSumExpScaledBregman w a ε η θ) := by
            field_simp [heps]
    _ = ε * logSumExpScaledKL w a ε θ η := by
          rw [hKL]

/-- `C²` smoothness of the finite log-sum-exp potential. -/
lemma logSumExp_contDiff
    {ι : Type _} [Fintype ι] [Nonempty ι]
    (w a : ι → ℝ)
    (hw : ∀ i, 0 < w i) :
    ContDiff ℝ 2 (logSumExp w a) := by
  classical
  unfold logSumExp
  refine (ContDiff.sum fun i _ => ?_).log ?_
  · have hlin : ContDiff ℝ 2 (fun θ : ℝ => θ * a i) := by
      simpa [mul_comm] using (contDiff_id.mul contDiff_const)
    have hExp : ContDiff ℝ 2 (fun θ : ℝ => Real.exp (θ * a i)) :=
      Real.contDiff_exp.comp hlin
    simpa [mul_assoc] using (contDiff_const.mul hExp)
  · intro θ
    exact (logSumExp_sum_pos w a hw θ).ne'

end InfoGeometry.Analytic
