import InfoGeometry.Algebra.Zorn.G2TwoPCAbstractGroup
import InfoGeometry.Algebra.Zorn.G2TwoPCNormalFormInverse
import Mathlib.Data.Fintype.Card
import Mathlib.Tactic.FinCases

namespace InfoGeometry.Algebra.Zorn.G2TwoPCNormalForm

/-!
# Polycyclic Non-Abelian 2-Group of Order 64

The CAS-certified polycyclic coordinate law is an abstract group law on .
Here we formalize the group structure, cardinality (|U₆| = 64 = 2⁶), exponent (e⁸ = 1),
and central involution generated by the highest root bit e₅.
-/

noncomputable instance : Group PCExponent where
  mul := pcCombine
  one := zeroPC
  inv := pcInverse
  div := fun e f => pcCombine e (pcInverse f)
  mul_assoc := pcCombine_assoc
  one_mul := pcCombine_zero_left
  mul_one := pcCombine_zero_right
  inv_mul_cancel := pcCombine_left_inverse

@[simp] theorem pcCombine_eq_mul (e f : PCExponent) :
    pcCombine e f = e * f := rfl

@[simp] theorem pcInverse_involutive (e : PCExponent) :
    pcInverse (pcInverse e) = e := by
  exact inv_inv e

@[simp] theorem pcInverse_eq_inv (e : PCExponent) :
    pcInverse e = e⁻¹ := rfl

@[simp] theorem zeroPC_eq_one :
    zeroPC = (1 : PCExponent) := rfl

/-- THEOREM: Cardinality of the unipotent Sylow 2-subgroup U₆ is 2⁶ = 64. -/
theorem card_pcExponent : Fintype.card PCExponent = 64 := by
  rw [Fintype.card_fun, Fintype.card_fin, Fintype.card_bool]
  norm_num

/-- The central highest-root involution generator: e₅ = (0,0,0,0,0,1). -/
def pcCenterGen : PCExponent
  | 0 => false
  | 1 => false
  | 2 => false
  | 3 => false
  | 4 => false
  | 5 => true

/-- THEOREM: e₅ is an involution (has order 2). -/
theorem pcCenterGen_sq : pcCenterGen * pcCenterGen = 1 := by
  change pcCombine pcCenterGen pcCenterGen = zeroPC
  funext i
  fin_cases i <;> simp [pcCombine, pcCenterGen, zeroPC]

/-- THEOREM: e₅ commutes with every element in U₆ (it lies in the center Z(U₆)). -/
theorem pcCenterGen_comm (e : PCExponent) :
    pcCenterGen * e = e * pcCenterGen := by
  change pcCombine pcCenterGen e = pcCombine e pcCenterGen
  funext i
  fin_cases i <;> simp [pcCombine, pcCenterGen]

/-- THEOREM: The square of any element has vanishing coordinate 0, 1, 4 (depth ≥ 2 in lower central series). -/
theorem pc_sq_coord0 (e : PCExponent) : (e * e) 0 = false := by
  change pcCombine e e 0 = false
  simp [pcCombine]

theorem pc_sq_coord1 (e : PCExponent) : (e * e) 1 = false := by
  change pcCombine e e 1 = false
  simp [pcCombine]

theorem pc_sq_coord4 (e : PCExponent) : (e * e) 4 = false := by
  change pcCombine e e 4 = false
  simp [pcCombine]

end InfoGeometry.Algebra.Zorn.G2TwoPCNormalForm
