import InfoGeometry.SignedNetwork.BranchingFrontier

/-!
# Transitive axiom audit for the branching frontier

These commands must actually run before there is an axiom-cleanliness claim.
Only propext, Classical.choice, and Quot.sound are accepted by the accompanying
runner. Absence of local source placeholders is not a transitive proof audit.
-/

#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.total_pairRate_all
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.atom_cast
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.signedReal_eq
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.signedReal_cancel
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.signedReal_addNullPairs
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.signedReal_birthPositive_sub
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.signedReal_birthNegative_sub
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.population_birthPositive
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.population_birthNegative
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.population_cancel_le
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.mass_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.mass_eq_sum
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.eventRate_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.totalRate_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.eventRate_le_totalRate
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.eventRate_eq_zero_of_totalRate_eq_zero
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generator_eq_zero_of_totalRate_eq_zero
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.population_applyEvent
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.mass_applyEvent
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.totalRate_eq
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.pairRate_atom_difference
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generator_signedReal
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generatorAfterCancel_signedReal
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generator_signedReal_cancel_input
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.linearDrift_eq_zero_of_totalRate_eq_zero
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generator_mass
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generator_mass_sq
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.totalRate_le
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.uniformRateBound_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.individualRate_le_uniformRateBound
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.totalRate_le_uniformRateBound
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generator_mass_le
#print axioms InfoGeometry.SignedNetwork.BranchingEnsembleGenerator.generatorAfterCancel_mass_le
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.eventProbability_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.sum_eventProbability
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.eventPMF_toReal
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.eventPMF_none_of_active
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.eventPMF_of_absorbing
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.signedReal_pruneState
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.nextStatePMF_pruned
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.eventIterates_zero
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.generator_eq_uncentered
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.integral_next_event
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.integral_next_signedReal
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.integral_next_signedReal_pruned
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.activeJumpLaw_probability
#print axioms InfoGeometry.SignedNetwork.BranchingEventLaw.holdingTime_cdf
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.abs_mul_seedSign
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.seedMass_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.coordinate_eq_zero_of_seedMass_zero
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.seedProbability_nonneg
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.sum_seedProbability
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.seedPMF_toReal
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.signedReal_seed_none
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.signedReal_seed_some
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.population_seed_some
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.weighted_seed_term
#print axioms InfoGeometry.SignedNetwork.BranchingInitialization.integral_weighted_seed
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.synthesis_analysis_pauli
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.expected_initial_coordinates_reconstruct
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.empiricalDensity_cancel
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.empiricalDensity_addNullPairs
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.ensemble_generator_intertwines
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.canceled_generator_intertwines
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.qubit_rate_bound
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.integrable_empiricalDensity_cancel_iff
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.integral_empiricalDensity_cancel
#print axioms InfoGeometry.SignedNetwork.BranchingQubitGenerator.integral_signedReal_cancel
