import Mathlib
import InfoGeometry.Algebra.CyclotomicOperatorProjectors

/-!
# Exact finite nilpotent-soul calculus

This module formalizes the theorem-safe algebraic core behind a finite
Grassmann/DeWitt "soul" without assuming a Berezinian or analytic functional
calculus.

A certified soul is simply an element `s` of an associative ring together with
an explicit nilpotence order `k`, i.e. `s^k = 0`.

Consequences:

* every power `s^m` with `k ≤ m` vanishes;
* every right polynomial term of degree at least `k` vanishes;
* `1+s` has the exact finite polynomial inverse already proved by the
  repository's native nilpotent-to-unipotent owner.

These are exact finite algebraic statements.  No automatic Taylor theorem for
an arbitrary spectral function, no Berezinian identity, and no convergence
claim is made here.
-/

noncomputable section

namespace InfoGeometry.Physics.NuclearFiniteNilpotentSoul

open Finset
open InfoGeometry.Algebra.CyclotomicOperatorProjectors

variable {A : Type*} [Ring A]

/-- A finite nilpotent operator soul with an explicit truncation order. -/
structure FiniteSoul (A : Type*) [Ring A] where
  value : A
  order : ℕ
  nilpotent : IsNilpotent value order

namespace FiniteSoul

variable (S : FiniteSoul A)

/-- Every power at or beyond the certified nilpotence order vanishes. -/
theorem pow_eq_zero_of_order_le (m : ℕ) (hm : S.order ≤ m) :
    S.value ^ m = 0 := by
  have hsplit : S.order + (m - S.order) = m := by omega
  calc
    S.value ^ m = S.value ^ (S.order + (m - S.order)) := by rw [hsplit]
    _ = S.value ^ S.order * S.value ^ (m - S.order) := by rw [pow_add]
    _ = 0 := by rw [S.nilpotent]; simp

/-- A coefficient multiplying a sufficiently high soul power contributes
exactly zero. -/
theorem right_term_eq_zero_of_order_le
    (c : A) (m : ℕ) (hm : S.order ≤ m) :
    c * S.value ^ m = 0 := by
  rw [S.pow_eq_zero_of_order_le m hm, mul_zero]

/-- The corresponding left polynomial term also vanishes. -/
theorem left_term_eq_zero_of_order_le
    (c : A) (m : ℕ) (hm : S.order ≤ m) :
    S.value ^ m * c = 0 := by
  rw [S.pow_eq_zero_of_order_le m hm, zero_mul]

/-- Exact finite inverse polynomial for the unipotent element `1+s`. -/
def inversePolynomial : A :=
  unipotentInvPoly S.value S.order

/-- Exact left inverse of `1+s`. -/
theorem one_add_mul_inversePolynomial :
    (1 + S.value) * S.inversePolynomial = 1 := by
  exact unipotent_mul_inv_eq_one S.nilpotent

/-- Exact right inverse of `1+s`. -/
theorem inversePolynomial_mul_one_add :
    S.inversePolynomial * (1 + S.value) = 1 := by
  exact unipotent_inv_mul_eq_one S.nilpotent

/-- The unipotent perturbation generated by a finite soul is a unit. -/
theorem one_add_isUnit : IsUnit (1 + S.value) := by
  exact unipotent_isUnit_of_nilpotent S.nilpotent

/-- Polynomial evaluation with coefficients on the left. -/
def rightPolynomial (coeff : ℕ → A) : A :=
  ∑ i ∈ range S.order, coeff i * S.value ^ i

/-- A polynomial tail whose exponents all start at the nilpotence order is
identically zero. -/
theorem tail_sum_eq_zero
    (coeff : ℕ → A) (N : ℕ) :
    (∑ j ∈ range N, coeff (S.order + j) * S.value ^ (S.order + j)) = 0 := by
  apply Finset.sum_eq_zero
  intro j hj
  exact S.right_term_eq_zero_of_order_le _ _ (by omega)

/-- Adding any finite higher-order tail to the truncated polynomial does not
change its value. -/
theorem rightPolynomial_add_tail
    (coeff : ℕ → A) (N : ℕ) :
    S.rightPolynomial coeff +
        (∑ j ∈ range N,
          coeff (S.order + j) * S.value ^ (S.order + j)) =
      S.rightPolynomial coeff := by
  rw [S.tail_sum_eq_zero coeff N, add_zero]

/-- Consolidated finite-soul truncation packet. -/
theorem finite_soul_packet :
    (1 + S.value) * S.inversePolynomial = 1 ∧
      S.inversePolynomial * (1 + S.value) = 1 ∧
      IsUnit (1 + S.value) :=
  ⟨S.one_add_mul_inversePolynomial,
    S.inversePolynomial_mul_one_add,
    S.one_add_isUnit⟩

end FiniteSoul

end InfoGeometry.Physics.NuclearFiniteNilpotentSoul

end noncomputable section
