import Mathlib

/-!
# Souriau Complex Temperature and Modular Flow Vectors

This module records the finite algebraic core of the phrase
`exp(eps.K)`: a complex Souriau inverse-temperature parameter
`eps = beta + i tau` acting on a real modular Hamiltonian `K`.

The complex parameter is also represented as a real two-vector.  The affine
chart of the Riemann sphere is the usual identification `(beta, tau) ↦ beta +
i tau`; the point at infinity is represented separately by `none`.
-/

noncomputable section

open Complex

/-- Real two-vector carrying inverse temperature and modular phase. -/
structure BetaVector where
  beta : ℝ
  tau : ℝ

/-- Complex Souriau temperature `eps = beta + i tau`. -/
def complexTemperature (v : BetaVector) : ℂ :=
  (v.beta : ℂ) + Complex.I * (v.tau : ℂ)

/-- Affine chart of the Riemann sphere. `none` is the point at infinity. -/
def riemannSphereChart (v : Option BetaVector) : Option ℂ :=
  v.map complexTemperature

/-- Modular cocycle generated by the complex temperature and real Hamiltonian. -/
noncomputable def souriauModularExp (eps : ℂ) (K : ℝ) : ℂ :=
  Complex.exp (eps * (K : ℂ))

/-- The master-equation density at complex modular time `eps.K`. -/
noncomputable def complexMasterDensity (eps : ℂ) (K : ℝ) : ℂ :=
  souriauModularExp eps K - 1 - eps * (K : ℂ)

/-- Real beta direction: ordinary thermal scaling. -/
def betaDirection : BetaVector where
  beta := 1
  tau := 0

/-- Imaginary beta direction: modular phase/rotation. -/
def phaseDirection : BetaVector where
  beta := 0
  tau := 1

def addBetaVector (u v : BetaVector) : BetaVector where
  beta := u.beta + v.beta
  tau := u.tau + v.tau

def smulBetaVector (a : ℝ) (v : BetaVector) : BetaVector where
  beta := a * v.beta
  tau := a * v.tau

theorem complexTemperature_eq (β τ : ℝ) :
    complexTemperature ⟨β, τ⟩ = (β : ℂ) + Complex.I * (τ : ℂ) := rfl

theorem complexTemperature_betaDirection :
    complexTemperature betaDirection = 1 := by
  simp [complexTemperature, betaDirection]

theorem complexTemperature_phaseDirection :
    complexTemperature phaseDirection = Complex.I := by
  simp [complexTemperature, phaseDirection]

theorem complexTemperature_add (u v : BetaVector) :
    complexTemperature (addBetaVector u v) =
      complexTemperature u + complexTemperature v := by
  cases u
  cases v
  simp [complexTemperature, addBetaVector]
  ring

theorem complexTemperature_smul (a : ℝ) (v : BetaVector) :
    complexTemperature (smulBetaVector a v) =
      (a : ℂ) * complexTemperature v := by
  cases v
  simp [complexTemperature, smulBetaVector]
  ring

theorem riemannSphereChart_some (v : BetaVector) :
    riemannSphereChart (some v) = some (complexTemperature v) := rfl

theorem riemannSphereChart_none :
    riemannSphereChart none = none := rfl

theorem souriauModularExp_zero_eps (K : ℝ) :
    souriauModularExp 0 K = 1 := by
  simp [souriauModularExp]

theorem souriauModularExp_zero_K (eps : ℂ) :
    souriauModularExp eps 0 = 1 := by
  simp [souriauModularExp]

theorem souriauModularExp_add_eps (eps₁ eps₂ : ℂ) (K : ℝ) :
    souriauModularExp (eps₁ + eps₂) K =
      souriauModularExp eps₁ K * souriauModularExp eps₂ K := by
  unfold souriauModularExp
  rw [← Complex.exp_add]
  congr 1
  ring

theorem souriauModularExp_add_betaVector (u v : BetaVector) (K : ℝ) :
    souriauModularExp (complexTemperature (addBetaVector u v)) K =
      souriauModularExp (complexTemperature u) K *
        souriauModularExp (complexTemperature v) K := by
  rw [complexTemperature_add]
  exact souriauModularExp_add_eps (complexTemperature u) (complexTemperature v) K

theorem souriauModularExp_real_beta (β K : ℝ) :
    souriauModularExp (complexTemperature ⟨β, 0⟩) K =
      Complex.exp ((β * K : ℝ) : ℂ) := by
  unfold souriauModularExp complexTemperature
  congr 1
  simp

theorem souriauModularExp_phase_beta (τ K : ℝ) :
    souriauModularExp (complexTemperature ⟨0, τ⟩) K =
      Complex.exp (Complex.I * ((τ * K : ℝ) : ℂ)) := by
  unfold souriauModularExp complexTemperature
  congr 1
  simp
  ring

theorem complexMasterDensity_zero (K : ℝ) :
    complexMasterDensity 0 K = 0 := by
  simp [complexMasterDensity, souriauModularExp]

/-- The Souriau complex-temperature package: real beta vector chart, Riemann
    sphere affine chart, and multiplicative modular exponential law. -/
theorem souriau_complex_temperature_theorem :
    complexTemperature betaDirection = 1 ∧
    complexTemperature phaseDirection = Complex.I ∧
    (∀ u v, complexTemperature (addBetaVector u v) =
      complexTemperature u + complexTemperature v) ∧
    (∀ v, riemannSphereChart (some v) = some (complexTemperature v)) ∧
    riemannSphereChart none = none ∧
    (∀ eps₁ eps₂ K,
      souriauModularExp (eps₁ + eps₂) K =
        souriauModularExp eps₁ K * souriauModularExp eps₂ K) ∧
    (∀ K, complexMasterDensity 0 K = 0) := by
  exact ⟨complexTemperature_betaDirection, complexTemperature_phaseDirection,
    complexTemperature_add, riemannSphereChart_some, riemannSphereChart_none,
    souriauModularExp_add_eps, complexMasterDensity_zero⟩
