import InfoGeometry.Algebra.CuntzFibonacciBraidInclusion
import Mathlib

open Matrix
open InfoGeometry.Algebra.CuntzTensorQuotient
open InfoGeometry.Algebra.CuntzFibonacciBraidInclusion

namespace GoldenMeanShift

noncomputable section

/-- The golden ratio transfer matrix. -/
def A : Matrix (Fin 2) (Fin 2) ℂ :=
  !![1, 1; 1, 0]

/-- The matrix A satisfies A^2 = A + 1. -/
theorem A_sq : A * A = A + 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;> { simp [A] }

/-- The canonical Cuntz embedding preserves matrix addition. -/
lemma matrixToCuntz_add (n : ℕ) (M N : Matrix (Fin n) (Fin n) ℂ) :
    matrixToCuntz n (M + N) = matrixToCuntz n M + matrixToCuntz n N := by
  dsimp [matrixToCuntz]
  simp [map_add, add_mul, Finset.sum_add_distrib]

/-- The canonical Cuntz embedding preserves the identity matrix. -/
lemma matrixToCuntz_one (n : ℕ) :
    matrixToCuntz n (1 : Matrix (Fin n) (Fin n) ℂ) = 1 := by
  dsimp [matrixToCuntz]
  have h : ∀ (i j : Fin n), algebraMap ℂ (CuntzAlg n) ((1 : Matrix (Fin n) (Fin n) ℂ) i j) =
      if i = j then 1 else 0 := by
    intro i j
    rw [Matrix.one_apply]
    split_ifs with h_eq
    · simp
    · simp
  simp_rw [h]
  have h2 : ∀ (i j : Fin n), (if i = j then (1 : CuntzAlg n) else 0) * (cuntzS n i * cuntzSdag n j) =
      if i = j then cuntzS n i * cuntzSdag n j else 0 := by
    intro i j
    split_ifs with h_eq
    · simp
    · simp
  simp_rw [h2]
  have h3 : ∀ (i : Fin n), (∑ j : Fin n, if i = j then cuntzS n i * cuntzSdag n j else 0) =
      cuntzS n i * cuntzSdag n i := by
    intro i
    rw [Finset.sum_ite_eq]
    simp
  simp_rw [h3]
  exact cuntz_ranges_sum_one n

/-- The noncommutative lift of the golden transfer matrix into O_2. -/
def X : CuntzAlg 2 :=
  matrixToCuntz 2 A

/--
HYPOTHESIS 1 (Spectral/Polynomial Relation):
The noncommutative lift X satisfies X^2 = X + 1 inside O_2.
-/
theorem X_sq : X * X = X + 1 := by
  dsimp [X]
  rw [← matrixToCuntz_mul, A_sq, matrixToCuntz_add, matrixToCuntz_one]

/-- X is invertible in O_2, with inverse X - 1. -/
noncomputable instance : Invertible X where
  invOf := X - 1
  invOf_mul_self := by
    rw [sub_mul, one_mul, X_sq]
    abel
  mul_invOf_self := by
    rw [mul_sub, mul_one, X_sq]
    abel

mutual
  /-- The Fibonacci A-coefficients. -/
  def fibA : ℕ → ℂ
    | 0 => 1
    | n + 1 => fibB n

  /-- The Fibonacci B-coefficients. -/
  def fibB : ℕ → ℂ
    | 0 => 0
    | n + 1 => fibA n + fibB n
end

/--
HYPOTHESIS 2 (Fibonacci Semigroup Reduction):
Every power X^n collapses to a linear combination of 1 and X.
-/
theorem X_pow (n : ℕ) :
    X ^ n = algebraMap ℂ (CuntzAlg 2) (fibA n) + algebraMap ℂ (CuntzAlg 2) (fibB n) * X := by
  induction n with
  | zero =>
    simp [fibA, fibB]
  | succ n ih =>
    rw [pow_succ, ih, add_mul, mul_assoc, X_sq, mul_add, mul_one]
    have h_comm : algebraMap ℂ (CuntzAlg 2) (fibA n) * X +
        (algebraMap ℂ (CuntzAlg 2) (fibB n) * X + algebraMap ℂ (CuntzAlg 2) (fibB n)) =
        algebraMap ℂ (CuntzAlg 2) (fibB n) +
        (algebraMap ℂ (CuntzAlg 2) (fibA n) + algebraMap ℂ (CuntzAlg 2) (fibB n)) * X := by
      rw [add_mul]
      abel
    rw [h_comm]
    simp [fibA, fibB, map_add]

/--
HYPOTHESIS 3 (Operator Roots in the Subalgebra):
Any m-th root of X that commutes with X is expressible as a linear combination of 1 and X.
-/
theorem X_root (m : ℕ) (Y : CuntzAlg 2) (h_comm : Y * X = X * Y) (h_root : Y ^ m = X) :
    ∃ (a b : ℂ), Y = algebraMap ℂ (CuntzAlg 2) a + algebraMap ℂ (CuntzAlg 2) b * X := by
  sorry

/--
HYPOTHESIS 4 (Fibonacci Braid flow noncommutativity):
Conjugation of the Fibonacci braid generators by powers of X preserves their non-commutativity.
-/
theorem braid_flow_noncomm (k : ℕ) (h_inj : Function.Injective (matrixToCuntz 2)) :
    let R_conj := X ^ k * fibonacciBraidCuntzRepresentation R * (Invertible.invOf X) ^ k
    let B_conj := X ^ k * fibonacciBraidCuntzRepresentation B * (Invertible.invOf X) ^ k
    R_conj * B_conj ≠ B_conj * R_conj := by
  sorry

/--
HYPOTHESIS 5 (Subalgebra Isomorphism):
The subalgebra of CuntzAlg 2 generated by X is isomorphic to the quotient of the
polynomial ring Polynomial ℂ by the golden polynomial X^2 - X - 1.
-/
theorem subalgebra_isomorphic_to_golden_quotient :
    Nonempty (Algebra.adjoin ℂ ({X} : Set (CuntzAlg 2)) ≃ₐ[ℂ] (Polynomial ℂ ⧸ Ideal.span ({(Polynomial.X ^ 2 - Polynomial.X - 1 : Polynomial ℂ)} : Set (Polynomial ℂ)))) := by
  sorry

end

end GoldenMeanShift
