import Mathlib

open scoped BigOperators

/-!
# Generic Dirac Self-Adjointness — No Cuntz Relations Required

Corrected formal package per Cuntz theory:
1. `selfAdjoint_add_star`: x + x* is self-adjoint ∀ x.
2. `finiteDirac_selfAdjoint`: D = Σ_i (S_i + S*_i) is self-adjoint.
3. Cuntz relations needed only for idempotent projections.
-/

namespace InfoGeometry.Algebra.Cuntz

/-- The finite star-Dirac sum generated by a finite family of star-algebra elements. -/
def finiteDirac {A ι : Type*} [AddCommMonoid A] [StarAddMonoid A] [Fintype ι]
    (S : ι → A) : A :=
  ∑ i, (S i + star (S i))

/-- x + x* is always self-adjoint. -/
lemma selfAdjoint_add_star {A : Type*} [AddCommMonoid A] [StarAddMonoid A]
    (x : A) :
    IsSelfAdjoint (x + star x) := by
  dsimp [IsSelfAdjoint]
  calc
    star (x + star x) = star x + star (star x) := StarAddMonoid.star_add x (star x)
    _ = star x + x := by rw [star_star]
    _ = x + star x := by rw [add_comm]

/-- Finite Dirac D = Σ_i (S_i + S*_i) is self-adjoint. No Cuntz hypotheses. -/
lemma finiteDirac_selfAdjoint {A ι : Type*} [AddCommMonoid A] [StarAddMonoid A]
    [Fintype ι] (S : ι → A) :
    IsSelfAdjoint (finiteDirac S) := by
  classical
  dsimp [finiteDirac, IsSelfAdjoint]
  calc
    star (∑ i, (S i + star (S i))) = ∑ i, star (S i + star (S i)) := by
      exact star_sum Finset.univ (fun i => S i + star (S i))
    _ = ∑ i, (S i + star (S i)) := by
      apply Finset.sum_congr rfl
      intro i _hi
      exact (selfAdjoint_add_star (S i)).star_eq

/-- Range projection idempotence for a raw family satisfying `S*_i · S_i = 1`. -/
lemma range_projection_idempotent_of_isometry {A : Type*} [Ring A] [StarRing A]
    {ι : Type*} [DecidableEq ι] (S : ι → A)
    (h_isometry : ∀ i j, star (S i) * S j = if i = j then 1 else 0)
    (i : ι) : (S i * star (S i)) * (S i * star (S i)) = S i * star (S i) := by
  have h_isom : star (S i) * S i = 1 := by simpa using h_isometry i i
  calc
    (S i * star (S i)) * (S i * star (S i))
        = S i * (star (S i) * S i) * star (S i) := by noncomm_ring
    _ = S i * 1 * star (S i) := by rw [h_isom]
    _ = S i * star (S i) := by simp

/-- Range projection orthogonality for a raw family satisfying `S*_i · S_j = 0`. -/
lemma range_projection_orthogonal_of_isometry {A : Type*} [Ring A] [StarRing A]
    {ι : Type*} [DecidableEq ι] (S : ι → A)
    (h_isometry : ∀ i j, star (S i) * S j = if i = j then 1 else 0)
    {i j : ι} (hij : i ≠ j) :
    (S i * star (S i)) * (S j * star (S j)) = 0 := by
  have h_orth : star (S i) * S j = 0 := by
    have := h_isometry i j
    simpa [hij] using this
  calc
    (S i * star (S i)) * (S j * star (S j))
        = S i * (star (S i) * S j) * star (S j) := by noncomm_ring
    _ = S i * 0 * star (S j) := by rw [h_orth]
    _ = 0 := by simp

end InfoGeometry.Algebra.Cuntz
