/-
InfoGeometry/OperatorAlgebra/VirasoroProjectBridge.lean

Partial transport between the abstract Virasoro socket and the
`VirasoroProject` surface.

This file is honest about its scope:

- the concrete `VirasoroDatum` realization is certified by `VirasoroProject`.
- the Sugawara central charge calibration for the Heisenberg case is honest debt.
-/

import InfoGeometry.External.Virasoro.VirasoroAlgebra
import InfoGeometry.OperatorAlgebra.AffineVirasoroBridge
import InfoGeometry.Canonical.CurrentSugawaraBridge

noncomputable section

namespace InfoGeometry.OperatorAlgebra.VirasoroProjectBridge

open AffineVirasoroBridge
open VirasoroProject
open InfoGeometry.Canonical.CurrentSugawaraBridge

/--
Predicate recording that a given `VirasoroDatum` is realized by the
`VirasoroProject` implementation on `ℝ`.
-/
def VirasoroProjectRealizes (V : VirasoroDatum (VirasoroAlgebra ℝ)) : Prop :=
  (∀ n, V.Lmode n = VirasoroAlgebra.lgen ℝ n) ∧ V.central = VirasoroAlgebra.cgen ℝ

/-- The concrete Virasoro datum induced by `VirasoroProject`. -/
def virasoroProjectVirasoroDatum :
    VirasoroDatum (VirasoroAlgebra ℝ) :=
{ Lmode := fun n => VirasoroAlgebra.lgen ℝ n
  central := VirasoroAlgebra.cgen ℝ }

/-- The concrete `VirasoroProject` datum is realized by its own generators. -/
theorem virasoroProjectVirasoroDatum_realizes :
    VirasoroProjectRealizes virasoroProjectVirasoroDatum := by
  constructor
  · intro n
    rfl
  · rfl

/-- The concrete central element commutes, via the partial affine bridge laws. -/
theorem virasoroProjectVirasoroDatum_central_commutes :
    ∀ X : VirasoroAlgebra ℝ, ⁅virasoroProjectVirasoroDatum.central, X⁆ = 0 := by
  intro X
  simpa [virasoroProjectVirasoroDatum] using VirasoroAlgebra.cgen_bracket (𝕜 := ℝ) X

/-- The concrete Virasoro bracket law is the expected one. -/
theorem virasoroProjectVirasoroDatum_bracket :
    ∀ m n : ℤ,
      ⁅virasoroProjectVirasoroDatum.Lmode m, virasoroProjectVirasoroDatum.Lmode n⁆ =
        (m - n : ℝ) • virasoroProjectVirasoroDatum.Lmode (m + n) +
          (virasoroCentralCoefficient m n : ℝ) • virasoroProjectVirasoroDatum.central := by
  intro m n
  by_cases hmn : m + n = 0
  · simpa [virasoroProjectVirasoroDatum, virasoroCentralCoefficient, hmn] using
      (VirasoroAlgebra.lgen_bracket (𝕜 := ℝ) m n)
  · simpa [virasoroProjectVirasoroDatum, virasoroCentralCoefficient, hmn] using
      (VirasoroAlgebra.lgen_bracket (𝕜 := ℝ) m n)

/--
Existence of a concrete `VirasoroDatum` realized by `VirasoroProject`.
-/
theorem virasoro_project_has_realized_datum :
    ∃ V : VirasoroDatum (VirasoroAlgebra ℝ), VirasoroProjectRealizes V :=
  ⟨virasoroProjectVirasoroDatum, virasoroProjectVirasoroDatum_realizes⟩

/-- Alias for compatibility with prime bridge naming. -/
theorem virasoro_project_is_certified :
    ∃ V : VirasoroDatum (VirasoroAlgebra ℝ), VirasoroProjectRealizes V :=
  virasoro_project_has_realized_datum

/--
Concrete Sugawara datum for the Heisenberg case.

For a single boson (dimG = 1) and abelian affine algebra (hDual = 0), the
central charge is `1`.
-/
def heisenbergSugawaraDatum : AffineVirasoroBridge.SugawaraDatum where
  level := 1
  dimG := 1
  hDual := 0
  centralCharge := 1

/-- The concrete Sugawara datum satisfies the expected central-charge law. -/
theorem heisenbergSugawaraDatum_sugawara :
    heisenbergSugawaraDatum.centralCharge =
      sugawaraCentralCharge heisenbergSugawaraDatum.level heisenbergSugawaraDatum.dimG
        heisenbergSugawaraDatum.hDual := by
  unfold sugawaraCentralCharge heisenbergSugawaraDatum
  norm_num

/-! ## Native Heisenberg-to-Virasoro projection -/

/--
The concrete `VirasoroDatum` generated by a proved real Heisenberg current
representation through the upstream `VirasoroProject` Sugawara construction.
-/
noncomputable def currentHeisenbergVirasoroDatum
    {V : Type*} [AddCommGroup V] [Module ℝ V]
    (H : CurrentHeisenbergRep ℝ V) :
    VirasoroDatum (V →ₗ[ℝ] V) where
  Lmode := H.sugawaraStressMode
  central := 1

/--
The central element of the Heisenberg Sugawara datum commutes with every
endomorphism.  This is derived from the native endomorphism-algebra theorem,
not stored as evidence in the datum.
-/
theorem currentHeisenbergVirasoroDatum_central_commutes
    {V : Type*} [AddCommGroup V] [Module ℝ V]
    (H : CurrentHeisenbergRep ℝ V) :
    ∀ X : V →ₗ[ℝ] V, ⁅(currentHeisenbergVirasoroDatum H).central, X⁆ = 0 := by
  intro X
  simpa [currentHeisenbergVirasoroDatum] using
    (heisenberg_central_term_commutator_eq_zero
      (𝕜 := ℝ) (V := V) 1 X)

/--
The genuine Virasoro bracket on the datum produced from a Heisenberg current.

The proof is the upstream `VirasoroProject` Sugawara theorem transported into
the repository's coefficient-normalized `VirasoroDatum` interface.
-/
theorem currentHeisenbergVirasoroDatum_bracket
    {V : Type*} [AddCommGroup V] [Module ℝ V]
    (H : CurrentHeisenbergRep ℝ V) :
    ∀ m n : ℤ,
      ⁅(currentHeisenbergVirasoroDatum H).Lmode m,
        (currentHeisenbergVirasoroDatum H).Lmode n⁆ =
        (m - n : ℝ) • (currentHeisenbergVirasoroDatum H).Lmode (m + n) +
          (virasoroCentralCoefficient m n : ℝ) •
            (currentHeisenbergVirasoroDatum H).central := by
  intro m n
  have h := H.sugawaraStressMode_virasoroBracket m n
  by_cases hmn : m + n = 0
  · simpa [currentHeisenbergVirasoroDatum, virasoroCentralCoefficient, hmn,
      LinearMap.commutator, Ring.lie_def, Algebra.smul_def] using h
  · simpa [currentHeisenbergVirasoroDatum, virasoroCentralCoefficient, hmn,
      LinearMap.commutator, Ring.lie_def, Algebra.smul_def] using h

end InfoGeometry.OperatorAlgebra.VirasoroProjectBridge
