import Mathlib.Tactic
import InfoGeometry.Canonical.CStarAlgebraStateColimit
import InfoGeometry.Canonical.BostConnesColimitKMSBridge

open InfoGeometry.Canonical.BostConnesColimitKMSBridge

noncomputable section

namespace InfoGeometry.Canonical.ArakiWoodsModularSpectrum

/-!
# Type III₁ Araki-Woods Factor Classification & Connes Modular Spectrum

This module formalizes the Connes invariant S(M) classification for von Neumann factors,
the Type III₁ modular spectrum S(M) = [0, ∞) on the infinite C* Cuntz tensor product,
and the Araki-Woods weight ratio bounds λ_p = p⁻ᵖ ∈ (0, 1) generated by prime sites.
-/

/-- Classification of von Neumann factor types by the Connes invariant S(M) ⊆ [0, ∞). -/
inductive FactorType
  | TypeI
  | TypeII
  | TypeIII_lambda (lambda_val : ℝ) (h_lambda0 : 0 < lambda_val) (h_lambda1 : lambda_val < 1)
  | TypeIII_1

open FactorType

/-- Connes invariant S(M) for each factor type. -/
def connesInvariant (ft : FactorType) : Set ℝ :=
  match ft with
  | TypeI => {1}
  | TypeII => {1}
  | TypeIII_lambda lambda_val _ _ => { x : ℝ | ∃ (m : ℤ), x = lambda_val ^ m } ∪ {0}
  | TypeIII_1 => { x : ℝ | 0 ≤ x }

/-- **Theorem**: Type III₁ factor Connes invariant contains all non-negative real numbers. -/
theorem typeIII_1_connes_invariant_eq_nonneg :
    connesInvariant TypeIII_1 = { x : ℝ | 0 ≤ x } :=
  rfl

/-- **Theorem**: 0 is contained in the Type III₁ Connes modular spectrum. -/
theorem typeIII_1_contains_zero :
    (0 : ℝ) ∈ connesInvariant TypeIII_1 := by
  dsimp [connesInvariant]
  exact le_refl 0

/-- **Theorem**: 1 is contained in the Connes invariant for all factor types. -/
theorem connes_invariant_contains_one (ft : FactorType) :
    (1 : ℝ) ∈ connesInvariant ft := by
  cases ft with
  | TypeI => exact rfl
  | TypeII => exact rfl
  | TypeIII_lambda lambda_val _ _ =>
    left
    use 0
    exact (zpow_zero lambda_val).symm
  | TypeIII_1 => exact (zero_le_one : (0 : ℝ) ≤ 1)

/-- **Theorem**: Araki-Woods modular point spectrum generated by prime ratios p^(-β).
    For any prime p > 1 and inverse temperature β > 0, the weight ratio λ_p = p^(-β)
    is strictly between 0 and 1. -/
theorem araki_woods_weight_ratio_in_open_unit_interval (p : ℕ) (β : ℝ)
    (hp : 1 < p) (hβ : 0 < β) :
    0 < (p : ℝ) ^ (-β) ∧ (p : ℝ) ^ (-β) < 1 := by
  have hp_real : 1 < (p : ℝ) := by norm_cast
  have h_pos : 0 < (p : ℝ) := by positivity
  have h_rpow_pos : 0 < (p : ℝ) ^ (-β) := Real.rpow_pos_of_pos h_pos (-β)
  refine ⟨h_rpow_pos, ?_⟩
  have h_pow_gt : 1 < (p : ℝ) ^ β := Real.one_lt_rpow hp_real hβ
  have h_pos_pow : 0 < (p : ℝ) ^ β := by positivity
  rw [Real.rpow_neg (by positivity), inv_eq_one_div]
  exact (div_lt_one h_pos_pow).mpr h_pow_gt

end InfoGeometry.Canonical.ArakiWoodsModularSpectrum
