"""Configuration utilities for igf."""

from igf.config.env_aliases import (
    DEFAULT_ARANGO_DATABASE,
    DEFAULT_ARANGO_ENDPOINT,
    DEFAULT_ARANGO_ENV,
    DEFAULT_ALEXANDRIA_ARANGO_ENDPOINT,
    DEFAULT_HIVE_ARANGO_DATABASE,
    DEFAULT_HIVE_ARANGO_ENDPOINT,
    arango_database,
    arango_endpoint,
    arango_password,
    arango_username,
    first_present_name,
    hive_arango_database,
    hive_arango_endpoint,
    hive_arango_password,
    hive_arango_username,
    alexandria_arango_database,
    alexandria_arango_endpoint,
    alexandria_arango_password,
    alexandria_arango_username,
    normalized_alexandria_arango_env,
    load_repo_arango_env,
    normalized_arango_env,
    normalized_hive_arango_env,
    repo_root_from,
)
from igf.config.graph_profile import (
    DEFAULT_GRAPH_MODE,
    GRAPH_LANE_PROFILES,
    GRAPH_MODE_ALIASES,
    GRAPH_MODE_CHOICES,
    GraphCollections,
    GraphLaneProfile,
    resolve_graph_mode,
)
from igf.config.loader import load_arango_config
from igf.config.model import ArangoConfig

__all__ = [
    "ArangoConfig",
    "DEFAULT_ARANGO_DATABASE",
    "DEFAULT_ARANGO_ENDPOINT",
    "DEFAULT_ARANGO_ENV",
    "DEFAULT_ALEXANDRIA_ARANGO_ENDPOINT",
    "DEFAULT_GRAPH_MODE",
    "DEFAULT_HIVE_ARANGO_DATABASE",
    "DEFAULT_HIVE_ARANGO_ENDPOINT",
    "GRAPH_LANE_PROFILES",
    "GRAPH_MODE_ALIASES",
    "GRAPH_MODE_CHOICES",
    "GraphCollections",
    "GraphLaneProfile",
    "arango_database",
    "arango_endpoint",
    "arango_password",
    "arango_username",
    "alexandria_arango_database",
    "alexandria_arango_endpoint",
    "alexandria_arango_password",
    "alexandria_arango_username",
    "first_present_name",
    "hive_arango_database",
    "hive_arango_endpoint",
    "hive_arango_password",
    "hive_arango_username",
    "load_arango_config",
    "load_repo_arango_env",
    "normalized_alexandria_arango_env",
    "normalized_arango_env",
    "normalized_hive_arango_env",
    "repo_root_from",
    "resolve_graph_mode",
]
