import Mathlib.Analysis.Calculus.FDeriv.Basic
import Mathlib.Analysis.Convex.Deriv
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Analysis.InnerProductSpace.Dual
import Mathlib.Order.Closure
import Mathlib.Tactic.Abel
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring
import InfoGeometry.Convex.Bregman
import InfoGeometry.Projective.Rays
import InfoGeometry.MaxEnt.Core

namespace InfoGeometry.Geometry

variable {Θ : Type _}
variable [NormedAddCommGroup Θ]
variable [NormedSpace ℝ Θ]

/-- Hessian geometry generated by a potential function. -/
structure HessianGeometry (Θ : Type _) where
  ψ : Θ → ℝ

/-- Hessian operator at a point. -/
noncomputable def hessian
    (H : HessianGeometry Θ)
    (x : Θ) : Θ →L[ℝ] (Θ →L[ℝ] ℝ) :=
  fderiv ℝ (fun y => fderiv ℝ H.ψ y) x

/-- Metric tensor induced by the Hessian. -/
noncomputable def metric
    (H : HessianGeometry Θ)
    (x : Θ)
    (u v : Θ) : ℝ :=
  (hessian H x u) v

/-- Dual-coordinate map given by the gradient covector. -/
noncomputable def dualCoord
    (H : HessianGeometry Θ)
    (x : Θ) : Θ →L[ℝ] ℝ :=
  fderiv ℝ H.ψ x

/-- Bregman divergence induced by the Hessian potential. -/
noncomputable def divergence
    (H : HessianGeometry Θ)
    (η θ : Θ) : ℝ :=
  H.ψ η - H.ψ θ - (dualCoord H θ) (η - θ)

@[simp] lemma divergence_self
    (H : HessianGeometry Θ) (θ : Θ) :
    divergence H θ θ = 0 := by
  unfold divergence
  simp

section Structural

/-- Affine `e`-geodesic in primal coordinates. -/
noncomputable def eGeodesic
    (x y : Θ)
    (t : ℝ) : Θ :=
  (1 - t) • x + t • y

@[simp]
lemma eGeodesic_zero
    (x y : Θ) :
    eGeodesic x y 0 = x := by
  simp [eGeodesic]

@[simp]
lemma eGeodesic_one
    (x y : Θ) :
    eGeodesic x y 1 = y := by
  simp [eGeodesic]

/-- Geodesic convexity along affine `e`-geodesics. -/
def eGeodesicConvex
    (f : Θ → ℝ) : Prop :=
  ∀ x y t,
    0 ≤ t → t ≤ 1 →
      f (eGeodesic x y t) ≤ (1 - t) * f x + t * f y

lemma ConvexOn.eGeodesicConvex
    {f : Θ → ℝ}
    (hconv : ConvexOn ℝ Set.univ f) :
    eGeodesicConvex f := by
  rcases hconv with ⟨_, hineq⟩
  intro x y t ht0 ht1
  have ht1' : 0 ≤ 1 - t := by linarith
  have hsum : (1 - t) + t = (1 : ℝ) := by ring
  simpa [eGeodesic] using
    hineq (x := x) (by simp) (y := y) (by simp)
      (a := 1 - t) (b := t) ht1' ht0 hsum

lemma eGeodesicConvex.convexOn_univ
    {f : Θ → ℝ}
    (hgeo : eGeodesicConvex f) :
    ConvexOn ℝ Set.univ f := by
  refine ⟨convex_univ, ?_⟩
  intro x hx y hy a b ha hb hab
  have ha' : a = 1 - b := by linarith
  rw [ha']
  exact hgeo x y b hb (by linarith)

/-- Convexity on the ambient affine space is equivalent to `e`-geodesic convexity. -/
theorem convexOn_univ_iff_eGeodesicConvex
    (f : Θ → ℝ) :
    ConvexOn ℝ Set.univ f ↔ eGeodesicConvex f := by
  constructor
  · intro hconv
    exact ConvexOn.eGeodesicConvex hconv
  · intro hgeo
    exact hgeo.convexOn_univ

/-- Alias for the main convexity/e-geodesic-convexity equivalence. -/
theorem convex_iff_eGeodesicConvex
    (f : Θ → ℝ) :
    ConvexOn ℝ Set.univ f ↔ eGeodesicConvex f :=
  convexOn_univ_iff_eGeodesicConvex f

/-- Data witnessing that `dualCoord` is bijective with a chosen inverse. -/
structure GradientBijection
    (H : HessianGeometry Θ) where
  invDual : (Θ →L[ℝ] ℝ) → Θ
  left_inv : ∀ θ, invDual (dualCoord H θ) = θ
  right_inv : ∀ η, dualCoord H (invDual η) = η

/-- Dual (`m`-) geodesic: affine interpolation in dual coordinates, pulled back by the inverse gradient. -/
noncomputable def mGeodesic
    (H : HessianGeometry Θ)
    (hGrad : GradientBijection H)
    (x y : Θ)
    (t : ℝ) : Θ :=
  hGrad.invDual ((1 - t) • dualCoord H x + t • dualCoord H y)

@[simp]
lemma mGeodesic_zero
    (H : HessianGeometry Θ)
    (hGrad : GradientBijection H)
    (x y : Θ) :
    mGeodesic H hGrad x y 0 = x := by
  simp [mGeodesic, hGrad.left_inv]

@[simp]
lemma mGeodesic_one
    (H : HessianGeometry Θ)
    (hGrad : GradientBijection H)
    (x y : Θ) :
    mGeodesic H hGrad x y 1 = y := by
  simp [mGeodesic, hGrad.left_inv]

lemma dualCoord_mGeodesic
    (H : HessianGeometry Θ)
    (hGrad : GradientBijection H)
    (x y : Θ)
    (t : ℝ) :
    dualCoord H (mGeodesic H hGrad x y t)
      = (1 - t) • dualCoord H x + t • dualCoord H y := by
  simp [mGeodesic, hGrad.right_inv]

/-- Algebraic three-point identity for the Hessian/Bregman divergence. -/
lemma divergence_three_point
    (H : HessianGeometry Θ)
    (η θ θ' : Θ) :
    divergence H η θ
      =
      divergence H η θ'
        + divergence H θ' θ
        + ((dualCoord H θ' - dualCoord H θ) (η - θ')) := by
  unfold divergence
  have hsplit : η - θ = (η - θ') + (θ' - θ) := by
    abel_nf
  have hlin :
      (dualCoord H θ) (η - θ)
        = (dualCoord H θ) (η - θ') + (dualCoord H θ) (θ' - θ) := by
    rw [hsplit, map_add]
  rw [hlin]
  simp [sub_eq_add_neg, add_assoc, add_left_comm, add_comm]
  ring

/-- Pythagorean decomposition from orthogonality of the residual term. -/
lemma divergence_pythagorean
    (H : HessianGeometry Θ)
    (η θ θ' : Θ)
    (horth : ((dualCoord H θ' - dualCoord H θ) (η - θ')) = 0) :
    divergence H η θ = divergence H η θ' + divergence H θ' θ := by
  rw [divergence_three_point (H := H) (η := η) (θ := θ) (θ' := θ')]
  simp [horth]

end Structural

section Riesz

variable {E : Type _}
variable [NormedAddCommGroup E]
variable [InnerProductSpace ℝ E]
variable [CompleteSpace E]

/-- Riesz-identified vector gradient corresponding to `dualCoord`. -/
noncomputable def dualCoordVec
    (H : HessianGeometry E)
    (x : E) : E :=
  (InnerProductSpace.toDual ℝ E).symm (dualCoord (Θ := E) H x)

/-- `dualCoordVec` represents the same functional as `dualCoord` via Riesz. -/
lemma dualCoordVec_spec
    (H : HessianGeometry E)
    (x y : E) :
    inner ℝ (dualCoordVec H x) y = (dualCoord (Θ := E) H x) y := by
  change inner ℝ
      ((InnerProductSpace.toDual ℝ E).symm (dualCoord (Θ := E) H x)) y
      = (dualCoord (Θ := E) H x) y
  exact InnerProductSpace.toDual_symm_apply
    (𝕜 := ℝ) (E := E) (x := y) (y := dualCoord (Θ := E) H x)

/-- Vector-gradient form of Bregman divergence. -/
noncomputable def divergenceVec
    (H : HessianGeometry E)
    (η θ : E) : ℝ :=
  H.ψ η - H.ψ θ - inner ℝ (dualCoordVec H θ) (η - θ)

@[simp] lemma divergenceVec_self
    (H : HessianGeometry E) (θ : E) :
    divergenceVec H θ θ = 0 := by
  unfold divergenceVec
  simp

lemma divergence_eq_divergenceVec
    (H : HessianGeometry E)
    (η θ : E) :
    divergence (Θ := E) H η θ = divergenceVec H η θ := by
  unfold divergence divergenceVec
  simp [dualCoordVec_spec]

lemma divergenceVec_three_point
    (H : HessianGeometry E)
    (η θ θ' : E) :
    divergenceVec H η θ
      =
      divergenceVec H η θ'
        + divergenceVec H θ' θ
        + inner ℝ (dualCoordVec H θ' - dualCoordVec H θ) (η - θ') := by
  have hinner :
      ((dualCoord H θ' - dualCoord H θ) (η - θ'))
        = inner ℝ (dualCoordVec H θ' - dualCoordVec H θ) (η - θ') := by
    calc
      ((dualCoord H θ' - dualCoord H θ) (η - θ'))
          = (dualCoord H θ') (η - θ') - (dualCoord H θ) (η - θ') := by
              simp [ContinuousLinearMap.sub_apply]
      _ = inner ℝ (dualCoordVec H θ') (η - θ')
            - inner ℝ (dualCoordVec H θ) (η - θ') := by
              simp [dualCoordVec_spec]
      _ = inner ℝ (dualCoordVec H θ' - dualCoordVec H θ) (η - θ') := by
            simp [inner_sub_left]
  rw [← divergence_eq_divergenceVec (H := H) (η := η) (θ := θ)]
  rw [← divergence_eq_divergenceVec (H := H) (η := η) (θ := θ')]
  rw [← divergence_eq_divergenceVec (H := H) (η := θ') (θ := θ)]
  rw [divergence_three_point (H := H) (η := η) (θ := θ) (θ' := θ')]
  rw [hinner]

lemma divergenceVec_pythagorean
    (H : HessianGeometry E)
    (η θ θ' : E)
    (horth : inner ℝ (dualCoordVec H θ' - dualCoordVec H θ) (η - θ') = 0) :
    divergenceVec H η θ = divergenceVec H η θ' + divergenceVec H θ' θ := by
  rw [divergenceVec_three_point (H := H) (η := η) (θ := θ) (θ' := θ')]
  simp [horth]

end Riesz

section Abstract

/-! Abstract Hessian-manifold wrappers for finite/infinite-dimensional use. -/

structure HessianManifold (Θ : Type _)
    [NormedAddCommGroup Θ] [NormedSpace ℝ Θ] where
  ψ : Θ → ℝ
  twiceDiff :
    ∀ x,
      HasFDerivAt
        (fun y => fderiv ℝ ψ y)
        (fderiv ℝ (fun y => fderiv ℝ ψ y) x)
        x

noncomputable def HessianManifold.metric
    (H : HessianManifold Θ)
    (x : Θ)
    (u v : Θ) : ℝ :=
  (fderiv ℝ (fun y => fderiv ℝ H.ψ y) x u) v

structure HilbertHessian (H : Type _)
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H] where
  ψ : H → ℝ
  twiceDiff :
    ∀ x,
      HasFDerivAt
        (fun y => fderiv ℝ ψ y)
        (fderiv ℝ (fun y => fderiv ℝ ψ y) x)
        x

noncomputable def HilbertHessian.metric
    {H : Type _}
    [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (M : HilbertHessian H)
    (x : H)
    (u v : H) : ℝ :=
  (fderiv ℝ (fun y => fderiv ℝ M.ψ y) x u) v

end Abstract

end InfoGeometry.Geometry

/-!
# Dual Flat Geometry and Projective Bayesian Bridge

An explicit dual-flat package over inner-product spaces, together with a
projective/statistical bridge theorem phrased as a Bregman Pythagorean identity.
-/

namespace InfoGeometry.Geometry.DualFlat

open Set
open scoped Real

variable {E : Type _}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/--
A dual-flat structure generated by a strictly convex differentiable potential `ψ`.
Via Riesz, the dual gradient is represented as a vector field on `E`.
-/
structure DualFlatStructure (E : Type _)
    [NormedAddCommGroup E] [InnerProductSpace ℝ E] where
  ψ : E → ℝ
  h_convex : StrictConvexOn ℝ Set.univ ψ
  h_diff : Differentiable ℝ ψ

variable (S : DualFlatStructure E)

/-- Repackage a dual-flat potential as a Hessian-geometry potential. -/
def toHessianGeometry : InfoGeometry.Geometry.HessianGeometry E where
  ψ := S.ψ

/-- Primal gradient coordinates `∇ψ`, represented in `E` using Riesz. -/
noncomputable def nabla (x : E) : E :=
  InfoGeometry.Geometry.dualCoordVec (H := toHessianGeometry S) x

/-- Bregman divergence induced by `ψ`. -/
noncomputable def divergence (x y : E) : ℝ :=
  InfoGeometry.Geometry.divergenceVec (H := toHessianGeometry S) x y

@[simp] lemma divergence_self (x : E) :
    divergence S x x = 0 := by
  simp [divergence, toHessianGeometry]

/-- Three-point identity (dual-flat law of cosines). -/
theorem three_point_identity (x y z : E) :
    divergence S x z
      = divergence S x y + divergence S y z
        - inner ℝ (nabla S z - nabla S y) (x - y) := by
  have hbase :=
    InfoGeometry.Geometry.divergenceVec_three_point
      (H := toHessianGeometry S) (η := x) (θ := z) (θ' := y)
  have hsign :
      inner ℝ (nabla S y - nabla S z) (x - y)
        = -inner ℝ (nabla S z - nabla S y) (x - y) := by
    have hswap : nabla S y - nabla S z = -(nabla S z - nabla S y) := by
      abel_nf
    rw [hswap, inner_neg_left]
  calc
    divergence S x z
        = divergence S x y + divergence S y z
            + inner ℝ (nabla S y - nabla S z) (x - y) := by
              simpa [divergence, nabla, toHessianGeometry] using hbase
    _ = divergence S x y + divergence S y z
          - inner ℝ (nabla S z - nabla S y) (x - y) := by
            rw [hsign]
            ring

/--
Generalized Bregman Pythagorean theorem:
orthogonality of dual and primal residual directions implies additive divergence
decomposition.
-/
theorem bregman_pythagorean
    (x y z : E)
    (h_ortho : inner ℝ (nabla S z - nabla S y) (x - y) = 0) :
    divergence S x z = divergence S x y + divergence S y z := by
  rw [three_point_identity (S := S), h_ortho]
  simp

section RealBridge

lemma dualCoord_apply_sub_eq_deriv_mul
    (SR : DualFlatStructure ℝ) (x y : ℝ) :
    (InfoGeometry.Geometry.dualCoord (Θ := ℝ) (toHessianGeometry SR) y) (x - y)
      = deriv SR.ψ y * (x - y) := by
  change (fderiv ℝ SR.ψ y : ℝ →L[ℝ] ℝ) (x - y) = deriv SR.ψ y * (x - y)
  calc
    (fderiv ℝ SR.ψ y : ℝ →L[ℝ] ℝ) (x - y)
        = (x - y) * deriv SR.ψ y := by
            rw [fderiv_eq_smul_deriv (f := SR.ψ) (x := y) (y := x - y)]
            simp [smul_eq_mul]
    _ = deriv SR.ψ y * (x - y) := by ring

lemma divergence_eq_bregmanDiv_real
    (SR : DualFlatStructure ℝ) (x y : ℝ) :
    divergence SR x y = InfoGeometry.bregmanDiv SR.ψ x y := by
  unfold divergence
  unfold InfoGeometry.Geometry.divergenceVec InfoGeometry.bregmanDiv
  rw [InfoGeometry.Geometry.dualCoordVec_spec
    (H := toHessianGeometry SR) (x := y) (y := x - y)]
  rw [dualCoord_apply_sub_eq_deriv_mul (SR := SR) (x := x) (y := y)]
  simp [toHessianGeometry]

end RealBridge

namespace ProjectiveBridge

open InfoGeometry.MaxEnt

variable {Ω : Type _} [MeasurableSpace Ω]

/-- Unnormalized state/mass package used for projective-probability interpretation. -/
structure UnnormalizedMeasure (μ₀ : MeasureTheory.Measure Ω) where
  representative : ACProbMeasure μ₀
  totalMass : ℝ
  mass_pos : 0 < totalMass

/-- Conceptual ray space of probability states via doubled-space projectivization. -/
abbrev ProjectiveProbability : Type _ := InfoGeometry.Projective.ProjectiveState (E := E)

/-- Projective divergence on representatives: measure-theoretic KL on AC probabilities. -/
noncomputable def projectiveDivergence
    {μ₀ : MeasureTheory.Measure Ω}
    (P Q : UnnormalizedMeasure μ₀) : ENNReal :=
  InfoGeometry.KL.kl_div P.representative.μ Q.representative.μ

lemma projectiveDivergence_eq_kl
    {μ₀ : MeasureTheory.Measure Ω}
    (P Q : UnnormalizedMeasure μ₀) :
    projectiveDivergence P Q
      = InfoGeometry.KL.kl_div P.representative.μ Q.representative.μ :=
  rfl

lemma projectiveDivergence_eq_of_representative_eq
    {μ₀ : MeasureTheory.Measure Ω}
    {P P' Q Q' : UnnormalizedMeasure μ₀}
    (hP : P.representative = P'.representative)
    (hQ : Q.representative = Q'.representative) :
    projectiveDivergence P Q = projectiveDivergence P' Q' := by
  cases P
  cases P'
  cases Q
  cases Q'
  cases hP
  cases hQ
  rfl

theorem bayesian_update_pythagorean_point
    (Prior Posterior Alt : E)
    (h_ortho :
      inner ℝ (nabla S Prior - nabla S Posterior) (Alt - Posterior) = 0) :
    divergence S Alt Prior
      = divergence S Alt Posterior + divergence S Posterior Prior := by
  exact bregman_pythagorean (S := S) (x := Alt) (y := Posterior) (z := Prior) h_ortho

/--
Bayesian/MaxEnt update as Bregman-orthogonal projection:
for any feasible alternative `Alt`, divergence to `Prior` decomposes through
the projected posterior.
-/
theorem bayesian_update_pythagorean
    (Prior Posterior Alt : E)
    (h_projection :
      ∀ v, (∃ t : ℝ, v = Alt + t • (Posterior - Alt)) →
        inner ℝ (nabla S Prior - nabla S Posterior) (v - Posterior) = 0) :
    divergence S Alt Prior
      = divergence S Alt Posterior + divergence S Posterior Prior := by
  exact bayesian_update_pythagorean_point (S := S) Prior Posterior Alt
    (h_projection Alt ⟨0, by simp⟩)

/--
Bayesian/MaxEnt update as a scalar Bregman Pythagorean identity in `ℝ`,
bridging `Geometry.DualFlat` with `InfoGeometry.bregmanDiv`.
-/
theorem bayesian_update_pythagorean_bregman
    (SR : DualFlatStructure ℝ)
    (Prior Posterior Alt : ℝ)
    (h_projection :
      ∀ v, (∃ t : ℝ, v = Alt + t • (Posterior - Alt)) →
        inner ℝ (nabla SR Prior - nabla SR Posterior) (v - Posterior) = 0) :
    InfoGeometry.bregmanDiv SR.ψ Alt Prior
      = InfoGeometry.bregmanDiv SR.ψ Alt Posterior
        + InfoGeometry.bregmanDiv SR.ψ Posterior Prior := by
  have hgeom :
      divergence SR Alt Prior
        = divergence SR Alt Posterior + divergence SR Posterior Prior :=
    bayesian_update_pythagorean (S := SR) Prior Posterior Alt h_projection
  simpa [divergence_eq_bregmanDiv_real] using hgeom

end ProjectiveBridge

end InfoGeometry.Geometry.DualFlat
