import Mathlib.Data.Real.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

set_option autoImplicit false

/-!
# Finite Hestenes/Cauchy--Riemann algebra

This file records only finite algebraic facts:

* a two-real-coordinate model of complex multiplication;
* the pointwise linear-algebra equivalence between complex-linearity and the
  Cauchy--Riemann equations;
* the finite even `Cl(3,0)`/quaternion-style multiplication table used by the
  Hestenes spinor proxy;
* the componentwise equivalence between the right-`e₁₂` Hestenes CR equation
  and the ordinary Cauchy--Riemann equations on the `{1,e₁₂}` subalgebra.

It deliberately does not assert global holomorphy, Weierstrass expansion,
Morera equivalence, contour integration, conformality, or Dirac-equation
analytic equivalence.  Those remain analytic/differential owner-file work.
-/

namespace InfoGeometry.Geometry.FiniteHestenesCR

/-- Complex numbers modeled as a two-dimensional real vector space. -/
structure ComplexReal where
  re : ℝ
  im : ℝ

@[ext]
lemma complex_ext {z1 z2 : ComplexReal} (hre : z1.re = z2.re) (him : z1.im = z2.im) :
    z1 = z2 := by
  cases z1
  cases z2
  congr

/-- Standard complex multiplication in real coordinates. -/
def c_mul (z1 z2 : ComplexReal) : ComplexReal :=
  ⟨z1.re * z2.re - z1.im * z2.im, z1.re * z2.im + z1.im * z2.re⟩

/-- A real linear map on the tangent plane of `ℂ`, written by its matrix entries. -/
structure RealLinearMap where
  ux : ℝ
  uy : ℝ
  vx : ℝ
  vy : ℝ

/-- Action of a real linear map on a tangent vector. -/
def realLinearApply (L : RealLinearMap) (z : ComplexReal) : ComplexReal :=
  ⟨L.ux * z.re + L.uy * z.im, L.vx * z.re + L.vy * z.im⟩

/-- Pointwise complex-linearity: the map is multiplication by a fixed complex scalar. -/
def is_complex_linear (L : RealLinearMap) : Prop :=
  ∃ A : ComplexReal, ∀ z : ComplexReal, realLinearApply L z = c_mul A z

/-- Pointwise Cauchy--Riemann equations in real-coordinate notation. -/
def satisfy_cauchy_riemann (L : RealLinearMap) : Prop :=
  L.ux = L.vy ∧ L.uy = -L.vx

/--
Finite linear-algebra equivalence between complex-linearity and the
Cauchy--Riemann equations at one tangent plane.
-/
theorem complex_linear_iff_cauchy_riemann (L : RealLinearMap) :
    is_complex_linear L ↔ satisfy_cauchy_riemann L := by
  constructor
  · rintro ⟨A, h⟩
    have h1 := h ⟨1, 0⟩
    have h2 := h ⟨0, 1⟩
    unfold realLinearApply c_mul at h1 h2
    have h1_re := congr_arg ComplexReal.re h1
    have h1_im := congr_arg ComplexReal.im h1
    have h2_re := congr_arg ComplexReal.re h2
    have h2_im := congr_arg ComplexReal.im h2
    unfold satisfy_cauchy_riemann
    constructor <;> linarith
  · rintro ⟨h_eq1, h_eq2⟩
    use ⟨L.ux, L.vx⟩
    intro z
    cases z with
    | mk z_re z_im =>
      ext <;> simp [realLinearApply, c_mul, h_eq1, h_eq2] <;> ring

/--
The Hestenes spinor proxy for the even subalgebra of `Cl(3,0)`, with basis
`1`, `e₂₃`, `e₃₁`, `e₁₂`.
-/
@[ext]
structure HestenesSpinor where
  a : ℝ
  b : ℝ
  c : ℝ
  d : ℝ

/-- Explicit even-Clifford/quaternion-style multiplication table. -/
def hestenesMul (q1 q2 : HestenesSpinor) : HestenesSpinor := ⟨
  q1.a * q2.a - q1.b * q2.b - q1.c * q2.c - q1.d * q2.d,
  q1.a * q2.b + q1.b * q2.a - q1.c * q2.d + q1.d * q2.c,
  q1.a * q2.c + q1.c * q2.a - q1.d * q2.b + q1.b * q2.d,
  q1.a * q2.d + q1.d * q2.a - q1.b * q2.c + q1.c * q2.b⟩

instance : Mul HestenesSpinor where
  mul := hestenesMul

@[simp] theorem hestenes_mul_def (q1 q2 : HestenesSpinor) :
    q1 * q2 = hestenesMul q1 q2 := rfl

instance : One HestenesSpinor where
  one := ⟨1, 0, 0, 0⟩

@[simp] theorem hestenes_one_def :
    (1 : HestenesSpinor) = ⟨1, 0, 0, 0⟩ := rfl

/-- Coordinatewise addition for the spinor proxy. -/
def hestenesAdd (q1 q2 : HestenesSpinor) : HestenesSpinor :=
  ⟨q1.a + q2.a, q1.b + q2.b, q1.c + q2.c, q1.d + q2.d⟩

instance : Add HestenesSpinor where
  add := hestenesAdd

@[simp] theorem hestenes_add_def (q1 q2 : HestenesSpinor) :
    q1 + q2 = hestenesAdd q1 q2 := rfl

instance : Zero HestenesSpinor where
  zero := ⟨0, 0, 0, 0⟩

@[simp] theorem hestenes_zero_def :
    (0 : HestenesSpinor) = ⟨0, 0, 0, 0⟩ := rfl

/-- Reversion flips the bivector coordinates. -/
def reverse (q : HestenesSpinor) : HestenesSpinor :=
  ⟨q.a, -q.b, -q.c, -q.d⟩

/-- Positive coordinate norm of the finite spinor proxy. -/
def h_norm (q : HestenesSpinor) : ℝ :=
  q.a * q.a + q.b * q.b + q.c * q.c + q.d * q.d

/-- Scalar part of `q₁ * reverse q₂`. -/
def krein_inner (q1 q2 : HestenesSpinor) : ℝ :=
  (q1 * reverse q2).a

/-- The spin-plane bivector `e₁₂`, acting as the imaginary unit in the subalgebra. -/
def bivector_i : HestenesSpinor := ⟨0, 0, 0, 1⟩

/-- Complex-number proxy for the subalgebra generated by `{1,e₁₂}`. -/
structure HestenesComplex where
  re : ℝ
  im : ℝ

/-- Complex multiplication in the `{1,e₁₂}` coordinate proxy. -/
def hestenesComplexMul (z1 z2 : HestenesComplex) : HestenesComplex :=
  ⟨z1.re * z2.re - z1.im * z2.im, z1.re * z2.im + z1.im * z2.re⟩

instance : Mul HestenesComplex where
  mul := hestenesComplexMul

@[simp] theorem hestenesComplex_mul_def (z1 z2 : HestenesComplex) :
    z1 * z2 = hestenesComplexMul z1 z2 := rfl

/-- Embed the complex proxy into the `{1,e₁₂}` Hestenes subalgebra. -/
def to_spinor (z : HestenesComplex) : HestenesSpinor :=
  ⟨z.re, 0, 0, z.im⟩

/-- Associativity of the finite even-subalgebra multiplication table. -/
theorem even_algebra_mul_assoc (q1 q2 q3 : HestenesSpinor) :
    (q1 * q2) * q3 = q1 * (q2 * q3) := by
  ext <;> simp [hestenesMul] <;> ring

/-- Multiplication by reversion gives a pure scalar equal to the coordinate norm. -/
theorem spinor_mul_reverse (q : HestenesSpinor) :
    q * reverse q = ⟨h_norm q, 0, 0, 0⟩ := by
  unfold reverse h_norm
  ext <;> simp [hestenesMul] <;> ring

/-- The spin bivector `e₁₂` squares to `-1`. -/
theorem bivector_i_squared : bivector_i * bivector_i = ⟨-1, 0, 0, 0⟩ := by
  unfold bivector_i
  ext <;> simp [hestenesMul]

/-- The `{1,e₁₂}` embedding preserves multiplication. -/
theorem bivector_isomorphism_mul (z1 z2 : HestenesComplex) :
    to_spinor (z1 * z2) = to_spinor z1 * to_spinor z2 := by
  unfold to_spinor
  ext <;> simp [hestenesMul, hestenesComplexMul]

/-- Symmetry of the scalar-part reversion pairing in the finite spinor proxy. -/
theorem krein_inner_symmetry (q1 q2 : HestenesSpinor) :
    krein_inner q1 q2 = krein_inner q2 q1 := by
  unfold krein_inner reverse
  simp [hestenesMul]
  ring

/-- Explicit predicate for a rotor-like normalized spinor; use as an explicit premise. -/
def IsHestenesRotor (R : HestenesSpinor) : Prop :=
  R * reverse R = 1

/-- Rotor normalization is exactly its explicit predicate, not a hidden class field. -/
theorem hestenesRotor_mul_reverse {R : HestenesSpinor} (hR : IsHestenesRotor R) :
    R * reverse R = ⟨1, 0, 0, 0⟩ := by
  simpa [IsHestenesRotor]

/-- Directional derivatives of a spinor-valued function along a real two-plane. -/
structure HestenesPartialDerivs where
  dx : HestenesSpinor
  dy : HestenesSpinor

/-- Hestenes-form CR equation: `∂ₓ ψ + (∂ᵧ ψ) e₁₂ = 0`. -/
def satisfy_hestenes_cr (D : HestenesPartialDerivs) : Prop :=
  D.dx + D.dy * bivector_i = 0

/-- Standard coordinate Cauchy--Riemann components. -/
structure StandardCRComponents where
  ux : ℝ
  uy : ℝ
  vx : ℝ
  vy : ℝ

/-- Standard coordinate Cauchy--Riemann equations. -/
def satisfy_standard_cr (C : StandardCRComponents) : Prop :=
  C.ux = C.vy ∧ C.uy = -C.vx

/--
Finite component equivalence between the Hestenes CR equation on the `{1,e₁₂}`
subalgebra and the ordinary Cauchy--Riemann equations.
-/
theorem hestenes_cr_equivalence (C : StandardCRComponents) :
    satisfy_hestenes_cr ⟨⟨C.ux, 0, 0, C.vx⟩, ⟨C.uy, 0, 0, C.vy⟩⟩ ↔
      satisfy_standard_cr C := by
  constructor
  · intro h
    unfold satisfy_hestenes_cr bivector_i at h
    unfold satisfy_standard_cr
    have h_a := congr_arg HestenesSpinor.a h
    have h_d := congr_arg HestenesSpinor.d h
    simp [hestenesAdd, hestenesMul] at h_a h_d
    constructor <;> linarith
  · intro h
    unfold satisfy_standard_cr at h
    unfold satisfy_hestenes_cr bivector_i
    ext <;> simp [hestenesAdd, hestenesMul, h.1, h.2]

/-! ## Explicit non-claims / debt markers -/

/--
Debt marker only: global equivalence of Weierstrass/Cauchy/Riemann/Morera
analyticity requires topology and integration hypotheses not present here.
-/
def classical_analyticity_equivalence_debt : String :=
  "Open: add topology/integration hypotheses and prove equivalence with classical analyticity notions."

/--
Debt marker only: equivalence with the four-dimensional Hestenes--Dirac
differential formulation requires a separate STA/gamma/differentiation owner.
-/
def hestenes_dirac_differential_equivalence_debt : String :=
  "Open: connect finite Hestenes CR equations to a four-dimensional Hestenes-Dirac differential owner."

/--
Debt marker only: conformality of Hestenes-analytic maps is analytic/differential
geometry work, not a consequence of the finite algebra in this file alone.
-/
def hestenes_conformal_mapping_preservation_debt : String :=
  "Open: prove conformality of Hestenes-analytic maps under explicit differential-geometric hypotheses."

end InfoGeometry.Geometry.FiniteHestenesCR
