import InfoGeometry.Geometry.DualFlatKreinLegendreGraph
import InfoGeometry.Krein.Metric
import Mathlib.Analysis.InnerProductSpace.Calculus
import Mathlib.Analysis.InnerProductSpace.Dual
import Mathlib.Analysis.Normed.Operator.Prod

/-!
# Mixed para-Hessian potential on a doubled real carrier

This owner supplies the finite analytic calculation behind the neutral
primal/dual picture.  On `E × E`, the scalar potential

`Phi (x,y) = inner x y`

has gradient `(y,x)` and constant Hessian given by the exchange involution.
The induced bilinear form is mixed: both coordinate halves are isotropic and
pair only with each other.  Together with the signed product grading this
gives the elementary para-Hermitian packet used by the split-Zorn bridge.

No integrability, curvature, Fisher-model, or physical-surprisal claim is made
here.
-/

noncomputable section

namespace InfoGeometry.Geometry.ParaHessianMixedPotential

open scoped InnerProductSpace
open InfoGeometry.Geometry.DualFlatKreinLegendreGraph

variable {E : Type*}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

abbrev Doubled (E : Type*) := E × E

/-- Exchange of the two real halves.  This is the Hessian operator of the
mixed quadratic potential. -/
def exchange : Doubled E →L[ℝ] Doubled E :=
  (ContinuousLinearMap.snd ℝ E E).prod (ContinuousLinearMap.fst ℝ E E)

/-- The real para-complex/product grading. -/
def grading : Doubled E →L[ℝ] Doubled E :=
  (ContinuousLinearMap.fst ℝ E E).prod
    (-(ContinuousLinearMap.snd ℝ E E))

@[simp] theorem exchange_apply (X : Doubled E) :
    exchange X = (X.2, X.1) := rfl

@[simp] theorem grading_apply (X : Doubled E) :
    grading X = (X.1, -X.2) := rfl

theorem exchange_sq : exchange (E := E).comp exchange =
    ContinuousLinearMap.id ℝ (Doubled E) := by
  ext X <;> rfl

theorem grading_sq : grading (E := E).comp grading =
    ContinuousLinearMap.id ℝ (Doubled E) := by
  ext X <;> simp

theorem exchange_anticommutes_grading :
    exchange (E := E).comp grading = -(grading.comp exchange) := by
  ext X <;> simp

/-- The mixed quadratic generating potential. -/
def potential (X : Doubled E) : ℝ := inner ℝ X.1 X.2

/-- Its gradient in the product Hilbert structure. -/
def gradient (X : Doubled E) : Doubled E := exchange X

/-- The constant mixed Hessian operator. -/
def hessian : Doubled E →L[ℝ] Doubled E := exchange

/-- The bilinear metric generated by the mixed Hessian. -/
def metric (U V : Doubled E) : ℝ :=
  inner ℝ U.1 V.2 + inner ℝ U.2 V.1

theorem metric_apply (U V : Doubled E) :
    metric U V = inner ℝ U.1 V.2 + inner ℝ U.2 V.1 := rfl

theorem metric_eq_hessian_indefinite_formCoord (U V : Doubled E) :
    metric U V =
      InfoGeometry.Krein.hessian_indefinite_formCoord U V := by
  simp [metric, InfoGeometry.Krein.hessian_indefinite_formCoord,
    real_inner_comm]

theorem metric_symmetric (U V : Doubled E) : metric U V = metric V U := by
  simp [metric_apply, real_inner_comm, add_comm]

theorem metric_exchange (U V : Doubled E) :
    metric (exchange U) (exchange V) = metric U V := by
  simp [metric_apply, real_inner_comm, add_comm]

theorem potential_eq_half_metric_self (X : Doubled E) :
    potential X = (1 / 2 : ℝ) * metric X X := by
  rw [metric_apply]
  simp [potential, real_inner_comm]
  ring

theorem potential_exchange (X : Doubled E) :
    potential (exchange X) = potential X := by
  simp [potential, real_inner_comm]

theorem potential_grading (X : Doubled E) :
    potential (grading X) = -potential X := by
  simp [potential, grading_apply]

theorem first_half_isotropic (u v : E) :
    metric (u, 0) (v, 0) = 0 := by simp [metric_apply]

theorem second_half_isotropic (u v : E) :
    metric (0, u) (0, v) = 0 := by simp [metric_apply]

theorem mixed_pairing (u v : E) :
    metric (u, 0) (0, v) = inner ℝ u v := by simp [metric_apply]

/-! ### Nondegeneracy of the finite mixed Hessian metric -/

theorem metric_nondegenerate (U : Doubled E)
    (hU : ∀ V : Doubled E, metric U V = 0) : U = 0 := by
  have h₁ : inner ℝ U.1 U.1 = 0 := by
    simpa [metric_apply] using hU (0, U.1)
  have h₂ : inner ℝ U.2 U.2 = 0 := by
    simpa [metric_apply] using hU (U.2, 0)
  have h₁' : U.1 = 0 := inner_self_eq_zero.mp h₁
  have h₂' : U.2 = 0 := inner_self_eq_zero.mp h₂
  exact Prod.ext h₁' h₂'

theorem grading_anti_isometry (U V : Doubled E) :
    metric (grading U) (grading V) = -metric U V := by
  simp [metric_apply]
  ring

/-- The compatible skew form `omega(U,V) = g(KU,V)`. -/
def symplectic (U V : Doubled E) : ℝ := metric (grading U) V

theorem symplectic_apply (U V : Doubled E) :
    symplectic U V = inner ℝ U.1 V.2 - inner ℝ U.2 V.1 := by
  simp [symplectic, metric_apply, sub_eq_add_neg]

theorem symplectic_skew (U V : Doubled E) :
    symplectic U V = -symplectic V U := by
  simp [symplectic_apply, real_inner_comm]

theorem symplectic_nondegenerate (U : Doubled E)
    (hU : ∀ V : Doubled E, symplectic U V = 0) : U = 0 := by
  have hgraded : grading U = 0 := by
    apply metric_nondegenerate (grading U)
    intro V
    simpa [symplectic] using hU V
  have hU' : grading (grading U) = 0 := by
    rw [hgraded, map_zero]
  simpa [grading_sq] using hU'

theorem symplectic_left_ext {U W : Doubled E}
    (h : ∀ V : Doubled E, symplectic U V = symplectic W V) : U = W := by
  apply sub_eq_zero.mp
  apply symplectic_nondegenerate (U - W)
  intro V
  have hV := h V
  rw [symplectic_apply, symplectic_apply] at hV
  rw [symplectic_apply]
  simp only [Prod.fst_sub, Prod.snd_sub, inner_sub_left]
  linear_combination hV

theorem symplectic_right_ext {U W : Doubled E}
    (h : ∀ V : Doubled E, symplectic V U = symplectic V W) : U = W := by
  apply symplectic_left_ext
  intro V
  calc
    symplectic U V = -symplectic V U := symplectic_skew U V
    _ = -symplectic V W := by rw [h V]
    _ = symplectic W V := by rw [symplectic_skew W V]

theorem symplectic_exchange (U V : Doubled E) :
    symplectic (exchange U) (exchange V) = -symplectic U V := by
  simp [symplectic_apply, real_inner_comm]

theorem symplectic_grading (U V : Doubled E) :
    symplectic (grading U) (grading V) = -symplectic U V := by
  simp [symplectic, metric_apply, grading_apply, real_inner_comm]
  ring

/-! ### Explicit para-Hermitian compatibility readouts -/

theorem symplectic_grading_left (U V : Doubled E) :
    symplectic (grading U) V = metric U V := by
  simp [symplectic, grading_apply, metric_apply]

theorem symplectic_grading_right (U V : Doubled E) :
    symplectic U (grading V) = -metric U V := by
  simpa [symplectic] using grading_anti_isometry U V

theorem symplectic_grading_grading (U V : Doubled E) :
    symplectic (grading U) (grading V) = -symplectic U V :=
  symplectic_grading U V

/-- First derivative of the mixed potential at `X`. -/
def potentialDerivative (X : Doubled E) : Doubled E →L[ℝ] ℝ :=
  (fderivInnerCLM ℝ (X.1, X.2)).comp
    ((ContinuousLinearMap.fst ℝ E E).prod
      (ContinuousLinearMap.snd ℝ E E))

theorem potentialDerivative_apply (X V : Doubled E) :
    potentialDerivative X V = inner ℝ V.1 X.2 + inner ℝ X.1 V.2 := by
  simp [potentialDerivative, fderivInnerCLM_apply, add_comm]

/-- The first derivative is the metric-dual of the base point. -/
theorem potentialDerivative_eq_metric (X V : Doubled E) :
    potentialDerivative X V = metric X V := by
  rw [potentialDerivative_apply, metric_apply]
  rw [real_inner_comm V.1 X.2]
  ring

theorem hasFDerivAt_potential (X : Doubled E) :
    HasFDerivAt potential (potentialDerivative X) X := by
  have hfst : HasFDerivAt (fun Y : Doubled E => Y.1)
      (ContinuousLinearMap.fst ℝ E E) X :=
    (ContinuousLinearMap.fst ℝ E E).hasFDerivAt
  have hsnd : HasFDerivAt (fun Y : Doubled E => Y.2)
      (ContinuousLinearMap.snd ℝ E E) X :=
    (ContinuousLinearMap.snd ℝ E E).hasFDerivAt
  simpa [potential, potentialDerivative] using hfst.inner ℝ hsnd

theorem hasFDerivAt_gradient (X : Doubled E) :
    HasFDerivAt gradient hessian X := by
  simpa [gradient, hessian] using (exchange (E := E)).hasFDerivAt

theorem fderiv_potential (X : Doubled E) :
    fderiv ℝ potential X = potentialDerivative X :=
  (hasFDerivAt_potential X).fderiv

theorem fderiv_potential_apply_eq_metric (X V : Doubled E) :
    fderiv ℝ potential X V = metric X V := by
  rw [fderiv_potential, potentialDerivative_eq_metric]

theorem symplectic_grading_eq_fderiv_potential (X V : Doubled E) :
    symplectic (grading X) V = fderiv ℝ potential X V := by
  rw [symplectic_grading_left, ← fderiv_potential_apply_eq_metric]

theorem grading_unique_for_potential_derivative {X Y : Doubled E}
    (h : ∀ V : Doubled E,
      symplectic X V = fderiv ℝ potential Y V) :
    X = grading Y := by
  apply symplectic_left_ext
  intro V
  calc
    symplectic X V = fderiv ℝ potential Y V := h V
    _ = symplectic (grading Y) V :=
      (symplectic_grading_eq_fderiv_potential Y V).symm

theorem fderiv_potential_apply_grading_eq_zero (X : Doubled E) :
    fderiv ℝ potential X (grading X) = 0 := by
  rw [← symplectic_grading_eq_fderiv_potential]
  have h := symplectic_skew (grading X) (grading X)
  linarith

theorem fderiv_gradient (X : Doubled E) :
    fderiv ℝ gradient X = hessian :=
  (hasFDerivAt_gradient X).fderiv

/-- Literal Mathlib derivative readout of the Hessian operator.  Since the
potential is quadratic, the derivative of its Riesz gradient is constant. -/
theorem fderiv_gradient_apply (X U : Doubled E) :
    fderiv ℝ gradient X U = hessian U := by
  rw [fderiv_gradient]

/-- Product-Hilbert pairing, written coordinatewise because the repository's
plain product carrier does not install a global `Inner` instance. -/
def productPairing (U V : Doubled E) : ℝ :=
  inner ℝ U.1 V.1 + inner ℝ U.2 V.2

/-- Pairing the literal derivative of the gradient with a second direction
recovers exactly the mixed Hessian metric. -/
theorem fderiv_gradient_inner_eq_metric (X U V : Doubled E) :
    productPairing (fderiv ℝ gradient X U) V = metric U V := by
  rw [fderiv_gradient_apply]
  simp [productPairing, hessian, exchange, metric, real_inner_comm]
  ring

/-! ## Relation to the existing neutral primal/dual graph owner -/

/-- Riesz identification, retained as a real linear map into the algebraic
module dual used by `DualFlatKreinLegendreGraph`. -/
def rieszDuality : E →ₗ[ℝ] Module.Dual ℝ E where
  toFun u := (InnerProductSpace.toDual ℝ E u).toLinearMap
  map_add' u v := by
    ext w
    simp [InnerProductSpace.toDual_apply_apply, inner_add_left]
  map_smul' r u := by
    ext w
    simp [InnerProductSpace.toDual_apply_apply]

theorem rieszDuality_symmetric : IsSymmetricDuality (rieszDuality (E := E)) := by
  intro u v
  simp [rieszDuality, InnerProductSpace.toDual_apply_apply, real_inner_comm]

theorem graph_neutral_eq_inner (u v : E) :
    normalizedNeutralPairing
        (graphLift (rieszDuality (E := E)) u)
        (graphLift (rieszDuality (E := E)) v) = inner ℝ u v := by
  rw [graph_neutral_pairing _ rieszDuality_symmetric]
  simp [rieszDuality, InnerProductSpace.toDual_apply_apply]

theorem graph_symplectic_zero (u v : E) :
    canonicalSymplectic
        (graphLift (rieszDuality (E := E)) u)
        (graphLift (rieszDuality (E := E)) v) = 0 :=
  graph_symplectic_isotropic _ rieszDuality_symmetric u v

end InfoGeometry.Geometry.ParaHessianMixedPotential
