import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.Tactic
import InfoGeometry.Canonical.TwelveFoldArithmeticNative
import InfoGeometry.Canonical.KleinSixStateC12Compatibility

/-!
# Cyclic group structure of the twelvefold master operator

This owner records only the group-theoretic consequences of the already
proved concrete matrix identities.  The carrier is the subgroup of the
matrix unit group generated by `masterUnit`; no abstract identification
with a different representation is assumed.
-/

namespace InfoGeometry.Canonical.TwelveFoldCyclicGroupStructure

open InfoGeometry.Canonical.TwelveFoldExplicitOperators
open InfoGeometry.Canonical.TwelveFoldArithmeticNative
open InfoGeometry.Canonical.KleinSixStateC12Compatibility

noncomputable section

abbrev MasterCyclic := Subgroup.zpowers masterUnit

theorem orderOf_master_eq_twelve : orderOf masterTwelve = 12 :=
  masterTwelve_order_exact

theorem orderOf_masterUnit_eq_twelve : orderOf masterUnit = 12 := by
  calc
    orderOf masterUnit = orderOf (masterUnit : StateMatrix) := orderOf_units.symm
    _ = orderOf masterTwelve := by rw [masterUnit_val]
    _ = 12 := orderOf_master_eq_twelve

noncomputable def master_zpowers_equiv_cyclic12 :
    Fin 12 ≃ MasterCyclic := by
  simpa only [orderOf_masterUnit_eq_twelve] using
    (finEquivZPowers (isOfFinOrder_iff_pow_eq_one.mpr
      ⟨12, by norm_num, masterUnit_twelve⟩))

theorem orderOf_master_sq_eq_six : orderOf (masterUnit ^ 2) = 6 := by
  rw [orderOf_pow' masterUnit (by norm_num), orderOf_masterUnit_eq_twelve]
  norm_num

theorem orderOf_master_cube_eq_four : orderOf (masterUnit ^ 3) = 4 := by
  rw [orderOf_pow' masterUnit (by norm_num), orderOf_masterUnit_eq_twelve]
  norm_num

theorem orderOf_master_six_eq_two : orderOf (masterUnit ^ 6) = 2 := by
  rw [orderOf_pow' masterUnit (by norm_num), orderOf_masterUnit_eq_twelve]
  norm_num

theorem orderOf_master_eight_eq_three : orderOf (masterUnit ^ 8) = 3 := by
  rw [orderOf_pow' masterUnit (by norm_num), orderOf_masterUnit_eq_twelve]
  norm_num

theorem triality_subgroup_le_master :
    Subgroup.zpowers (masterUnit ^ 2) ≤ MasterCyclic := by
  rw [Subgroup.zpowers_le]
  exact Subgroup.zpow_mem_zpowers masterUnit 2

theorem quartic_subgroup_le_master :
    Subgroup.zpowers (masterUnit ^ 3) ≤ MasterCyclic := by
  rw [Subgroup.zpowers_le]
  exact Subgroup.zpow_mem_zpowers masterUnit 3

theorem parity_subgroup_le_master :
    Subgroup.zpowers (masterUnit ^ 6) ≤ MasterCyclic := by
  rw [Subgroup.zpowers_le]
  exact Subgroup.zpow_mem_zpowers masterUnit 6

theorem colour_subgroup_le_master :
    Subgroup.zpowers (masterUnit ^ 8) ≤ MasterCyclic := by
  rw [Subgroup.zpowers_le]
  exact Subgroup.zpow_mem_zpowers masterUnit 8

theorem triality_quartic_common_power :
    (masterUnit ^ 2) ^ 3 = (masterUnit ^ 3) ^ 2 := by
  rw [← pow_mul, ← pow_mul]

end
end InfoGeometry.Canonical.TwelveFoldCyclicGroupStructure
