import proofs.NonIsoConf3LogWedgeObstruction
import proofs.NonIsoConf3RankDecision

/-!
# Projection/quotient status of the OS-alpha branch

The rank-24 Orlik--Solomon alpha presentation is useful finite bookkeeping, but
it is not the literal logarithmic de Rham algebra generated by the three quadric
forms `dlog(q12)`, `dlog(q13)`, `dlog(q23)`.

The key compiled obstruction is imported from
`NonIsoConf3LogWedgeObstruction`: at a concrete non-isotropic D=4 evaluation, the
common-denominator numerator of the naive quadric Arnold relation has
`dx0∧dy0` coefficient `52`, hence is nonzero.

Thus this file records the theorem-honest status:

* rank 32 is the independent/product-Leray finite branch;
* rank 24 is the OS-alpha quotient/projection branch;
* selecting the actual de Rham branch still requires a Dupont/Gysin comparison,
  not a naive `dlog` Arnold identity.
-/

namespace NonIsoConf3ProjectionQuotient

open NonIsoConf3DeRhamCooperad
open NonIsoConf3LogWedgeObstruction
open NonIsoConf3RankDecision

/-- Data saying that the OS-alpha branch is being used as a quotient/projection
presentation rather than as the literal algebra of quadric logarithmic forms. -/
structure OSAlphaProjectionQuotient where
  branch : ModelChoice
  branch_eq_osAlpha : branch = ModelChoice.osAlpha
  imposesAlphaArnoldRelation : Prop
  isCommutativeProjection : Prop
  notLiteralQuadricDLogIdentity : Prop
  actualDeRhamRequiresDupontGysin : Prop

/-- Canonical name for the rank-32 independent/product branch. -/
def independentProductBranch : ModelChoice := ModelChoice.productLeray

/-- Canonical name for the rank-24 OS-alpha quotient branch. -/
def osAlphaProjectionBranch : ModelChoice := ModelChoice.osAlpha

@[simp] theorem independentProductBranch_eq :
    independentProductBranch = ModelChoice.productLeray := rfl

@[simp] theorem osAlphaProjectionBranch_eq :
    osAlphaProjectionBranch = ModelChoice.osAlpha := rfl

/-- The concrete obstruction coefficient proves that the OS-alpha
Arnold relation cannot be read as a literal identity among the three quadric
`dlog` forms. -/
theorem literal_quadric_dlog_arnold_not_zero :
    arnoldDlogNumerator_dx0dy0 = 52 ∧ arnoldDlogNumerator_dx0dy0 ≠ 0 :=
  naive_dlog_arnold_relation_obstructed

/-- The finite rank fork: the product/Leray branch has rank `32`, while the
OS-alpha quotient/projection branch has rank `24`. -/
theorem product_vs_os_projection_rank_fork :
    Fintype.card ProductBasis = 32 ∧
    Fintype.card OSFluxBasis = 24 ∧
    Fintype.card ProductBasis - Fintype.card OSFluxBasis = 8 :=
by
  constructor
  · simpa using productBasis_card
  constructor
  · simpa using osFluxBasis_card
  · simpa using product_vs_os_rank_gap

/-- Main quotient theorem: once the OS-alpha presentation is explicitly marked
as a projection/quotient, the Lean kernel records both the useful rank-24
bookkeeping and the obstruction preventing it from being the literal quadric
`dlog` algebra. -/
theorem os_alpha_is_projection_not_literal_quadric_dlog
    (Q : OSAlphaProjectionQuotient)
    (hArnold : Q.imposesAlphaArnoldRelation)
    (hComm : Q.isCommutativeProjection)
    (hNotLiteral : Q.notLiteralQuadricDLogIdentity)
    (hNeeds : Q.actualDeRhamRequiresDupontGysin) :
    Q.branch = ModelChoice.osAlpha ∧
    Q.imposesAlphaArnoldRelation ∧
    Q.isCommutativeProjection ∧
    Q.notLiteralQuadricDLogIdentity ∧
    Q.actualDeRhamRequiresDupontGysin ∧
    arnoldDlogNumerator_dx0dy0 = 52 ∧
    arnoldDlogNumerator_dx0dy0 ≠ 0 ∧
    Fintype.card ProductBasis = 32 ∧
    Fintype.card OSFluxBasis = 24 ∧
    Fintype.card ProductBasis - Fintype.card OSFluxBasis = 8 := by
  rcases literal_quadric_dlog_arnold_not_zero with ⟨h52, hne⟩
  constructor
  · simpa using Q.branch_eq_osAlpha
  constructor
  · simpa using hArnold
  constructor
  · simpa using hComm
  constructor
  · simpa using hNotLiteral
  constructor
  · simpa using hNeeds
  constructor
  · simpa using h52
  constructor
  · simpa using hne
  constructor
  · simpa using productBasis_card
  constructor
  · simpa using osFluxBasis_card
  · simpa using product_vs_os_rank_gap

/-- Conditional theorem-honest branch selection: if the Dupont/Gysin rank
discharges the independence data, the rank-32 branch is selected, while the
rank-24 OS-alpha branch remains only a projection quotient. -/
theorem rank32_actual_vs_os_projection
    (Q : OSAlphaProjectionQuotient)
    (hArnold : Q.imposesAlphaArnoldRelation)
    (hComm : Q.isCommutativeProjection)
    (hNotLiteral : Q.notLiteralQuadricDLogIdentity)
    (hNeeds : Q.actualDeRhamRequiresDupontGysin) :
    ¬ tripleDependent expectedCodimData ∧
    Fintype.card ProductBasis = 32 ∧
    Fintype.card OSFluxBasis = 24 ∧
    Fintype.card ProductBasis - Fintype.card OSFluxBasis = 8 ∧
    Q.branch = ModelChoice.osAlpha ∧
    arnoldDlogNumerator_dx0dy0 ≠ 0 ∧
    Q.actualDeRhamRequiresDupontGysin := by
  rcases rank32_decision_from_dupont_independence with
    ⟨hInd, h32, h24, hgap⟩
  rcases os_alpha_is_projection_not_literal_quadric_dlog Q
      hArnold hComm hNotLiteral hNeeds with
    ⟨hBranch, _hA, _hC, _hNL, hNeed, _h52, hne, _h32', _h24', _hgap'⟩
  constructor
  · simpa using hInd
  constructor
  · simpa using h32
  constructor
  · simpa using h24
  constructor
  · simpa using hgap
  constructor
  · simpa using hBranch
  constructor
  · simpa using hne
  · simpa using hNeed

end NonIsoConf3ProjectionQuotient
