import InfoGeometry.Canonical.BiQuaternionKahlerLagrangian

/-!
# InfoGeometry.Canonical.BiQuaternionKahlerKilling

This module formally implements Step 3 of the Unified Framework:
Identifying Killing Vectors and their associated conserved quantities via Noether's theorem
on the Bi-Quaternion-Kähler manifold.

1. **Skew-Symmetric Operators**: Generate the Killing vector fields $K(\Phi) = A\Phi$.
2. **Potential Invariance**: The self-interacting potential is invariant under $K$.
3. **Noether's Theorem**: The Noether charge $Q_K = g(K(\Phi), P)$ is strictly conserved
   along the Hamiltonian flow.
-/

noncomputable section

namespace InfoGeometry.Canonical.BiQuaternionKahler

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- A continuous linear map A is Skew-Symmetric if g(AX, Y) = -g(X, AY).
    These generate the Killing vector fields K(Φ) = A Φ on the flat manifold. -/
def IsSkewSymmetric (A : E →L[ℝ] E) : Prop :=
  ∀ X Y : E, KaehlerMetric (A X) Y = - KaehlerMetric X (A Y)

-- The directional derivative (gradient action) of the potential V along a vector v.
variable (gradV : E → E)

/-- The self-interacting potential V is invariant under the Killing vector field generated by A
    if the directional derivative of V along A(Φ) is zero for all Φ. -/
def IsPotentialInvariant (A : E →L[ℝ] E) : Prop :=
  ∀ Φ : E, KaehlerMetric (gradV Φ) (A Φ) = 0

/-- The Noether Charge associated with the Killing vector field A.
    $Q_A(\Phi, P) = g(A\Phi, P)$ -/
def NoetherCharge (A : E →L[ℝ] E) (Φ P : E) : ℝ :=
  KaehlerMetric (A Φ) P

/-- The Hamiltonian equations of motion evaluate the time derivative of a phase space function.
    $\dot{\Phi} = P$
    $\dot{P} = - \nabla V(\Phi)$
    For $Q_A = g(A\Phi, P)$, the time derivative is $g(A\dot{\Phi}, P) + g(A\Phi, \dot{P})$. -/
def NoetherChargeTimeDeriv (A : E →L[ℝ] E) (Φ P : E) : ℝ :=
  KaehlerMetric (A P) P + KaehlerMetric (A Φ) (- gradV Φ)

/-- Theorem: A skew-symmetric operator generates a Killing vector field.
    The self-inner product of a skew-symmetric operator applied to a vector is zero. -/
theorem skew_symmetric_self_orthogonal (A : E →L[ℝ] E) (hA : IsSkewSymmetric A) (P : E) :
    KaehlerMetric (A P) P = 0 := by
  have h1 : KaehlerMetric (A P) P = - KaehlerMetric P (A P) := hA P P
  have h2 : KaehlerMetric P (A P) = KaehlerMetric (A P) P := by
    unfold KaehlerMetric
    exact Eq.symm (@real_inner_comm E _ _ P (A P))
  linarith

/-- Noether's Theorem for Bi-Quaternion Kähler Manifolds:
    If the potential is invariant under the Killing vector field generated by a skew-symmetric operator A,
    then the associated Noether Charge is strictly conserved ($\frac{d}{dt} Q_A = 0$). -/
theorem noether_charge_conserved (A : E →L[ℝ] E) (hA : IsSkewSymmetric A) (hV : IsPotentialInvariant gradV A) (Φ P : E) :
    NoetherChargeTimeDeriv gradV A Φ P = 0 := by
  unfold NoetherChargeTimeDeriv
  rw [skew_symmetric_self_orthogonal A hA P]
  have h_inv : KaehlerMetric (gradV Φ) (A Φ) = 0 := hV Φ
  have h_inner_neg : KaehlerMetric (A Φ) (- gradV Φ) = - KaehlerMetric (A Φ) (gradV Φ) := by
    unfold KaehlerMetric
    exact @inner_neg_right ℝ E _ _ _ (A Φ) (gradV Φ)
  rw [h_inner_neg]
  have h_comm : KaehlerMetric (A Φ) (gradV Φ) = KaehlerMetric (gradV Φ) (A Φ) := by
    unfold KaehlerMetric
    exact Eq.symm (@real_inner_comm E _ _ (A Φ) (gradV Φ))
  rw [h_comm, h_inv]
  ring

end InfoGeometry.Canonical.BiQuaternionKahler
