import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic
import InfoGeometry.Twistor.PenroseTwistor

/-!
# Finite twistor operators and a quadratic symplectic shear

This is the finite algebraic part of the operator/symplectic content of the
twistor programme.  The operator carrier is the existing `ℂ^4` twistor
carrier.  A finite truncation cannot satisfy an exact Heisenberg relation
`[a,a†] = 1`; the owner therefore records the boundary defect explicitly.
The second part gives the corresponding honest finite-dimensional canonical
shear and proves preservation of the standard alternating form.
-/

namespace InfoGeometry.Canonical.FiniteTwistorCCRGeneratingFunction

noncomputable section

open InfoGeometry.Twistor.PenroseTwistor

abbrev TwistorOperator := Matrix (Fin 4) (Fin 4) ℂ

def commutator (A B : TwistorOperator) : TwistorOperator := A * B - B * A

/-- The four-level truncated lowering operator. -/
def twistorCoordinate : TwistorOperator :=
  !![0, 1, 0, 0;
     0, 0, 1, 0;
     0, 0, 0, 1;
     0, 0, 0, 0]

/-- The transpose raising operator for the finite truncation. -/
def twistorDerivative : TwistorOperator :=
  !![0, 0, 0, 0;
     1, 0, 0, 0;
     0, 1, 0, 0;
     0, 0, 1, 0]

/-- Same-type operators commute in this one-mode finite model. -/
@[simp] theorem twistorCoordinate_self_commutator :
    commutator twistorCoordinate twistorCoordinate = 0 := by
  simp [commutator]

@[simp] theorem twistorDerivative_self_commutator :
    commutator twistorDerivative twistorDerivative = 0 := by
  simp [commutator]

/--
The exact finite-dimensional CCR readout.  The last diagonal entry is the
boundary defect; it is not silently replaced by the identity matrix.
-/
theorem finite_twistor_commutator :
    commutator twistorCoordinate twistorDerivative =
      !![1, 0, 0, 0;
         0, 0, 0, 0;
         0, 0, 0, 0;
         0, 0, 0, -1] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [commutator, twistorCoordinate, twistorDerivative]

/-! ## Finite canonical symplectic algebra -/

abbrev PhasePoint := ℂ × ℂ

def finiteSymplecticForm (x y : PhasePoint) : ℂ :=
  x.1 * y.2 - x.2 * y.1

@[simp] theorem finiteSymplecticForm_swap (x y : PhasePoint) :
    finiteSymplecticForm x y = -finiteSymplecticForm y x := by
  dsimp [finiteSymplecticForm]
  ring

@[simp] theorem finiteSymplecticForm_self (x : PhasePoint) :
    finiteSymplecticForm x x = 0 := by
  dsimp [finiteSymplecticForm]
  ring

/-- The linear canonical shear generated by a quadratic potential. -/
def canonicalShear (c : ℂ) (x : PhasePoint) : PhasePoint :=
  (x.1, x.2 + c * x.1)

def quadraticPotential (c q : ℂ) : ℂ := (c / 2) * q ^ 2

def quadraticGradient (c q : ℂ) : ℂ := c * q

@[simp] theorem quadraticPotential_add (c q h : ℂ) :
    quadraticPotential c (q + h) =
      quadraticPotential c q + quadraticGradient c q * h +
        quadraticPotential c h := by
  dsimp [quadraticPotential, quadraticGradient]
  ring

@[simp] theorem canonicalShear_quadraticGradient (c : ℂ) (x : PhasePoint) :
    canonicalShear c x = (x.1, x.2 + quadraticGradient c x.1) := by
  rfl

@[simp] theorem canonicalShear_preserves_symplectic
    (c : ℂ) (x y : PhasePoint) :
    finiteSymplecticForm (canonicalShear c x) (canonicalShear c y) =
      finiteSymplecticForm x y := by
  dsimp [canonicalShear, finiteSymplecticForm]
  ring

end

end InfoGeometry.Canonical.FiniteTwistorCCRGeneratingFunction
