import InfoGeometry.Projective.HadjiivanovLogConnectionReadoutBridge

/-!
# Commutation of logarithmic connection and residue readout

The unipotent shear `I + pN` is a polynomial in the square-zero residue
direction.  It therefore commutes with the residue `hI + N`; after lifting
over the unchanged Laurent base, it commutes with the full algebraic
logarithmic connection.  The same holds for the phase-decorated Hadjiivanov
readout.

No exponential transport or analytic holonomy is used.
-/

namespace InfoGeometry.Projective.HadjiivanovLogConnectionReadoutCommutationBridge

open scoped TensorProduct
open InfoGeometry.Projective.HadjiivanovLogConnectionBridge
open InfoGeometry.Projective.HadjiivanovLogConnectionReadoutBridge

noncomputable section

variable {V : Type*} [AddCommGroup V] [Module ℂ V]

/-- The residue commutes with every finite unipotent shear generated by its
nilpotent direction. -/
theorem residueOperator_unipotent_commute
    (R : LogResidue V) (p : ℂ) (v : V) :
    residueOperator R (unipotentResidueReadout R p v) =
      unipotentResidueReadout R p (residueOperator R v) := by
  simp only [residueOperator_apply, unipotentResidueReadout_apply,
    map_add, map_smul, nilpotent_apply_twice, smul_zero]
  module

/-- Lift the unipotent residue readout across the unchanged Laurent base. -/
def sectionUnipotentReadout (R : LogResidue V) (p : ℂ) :
    LogSection V →ₗ[ℂ] LogSection V :=
  TensorProduct.map LinearMap.id (unipotentResidueReadout R p)

@[simp] theorem sectionUnipotentReadout_tmul
    (R : LogResidue V) (p : ℂ)
    (f : HadjiivanovLogConnectionBridge.LaurentRing) (v : V) :
    sectionUnipotentReadout R p (f ⊗ₜ[ℂ] v) =
      f ⊗ₜ[ℂ] unipotentResidueReadout R p v := by
  simp [sectionUnipotentReadout]

/-- Pure-tensor commutation of connection and unipotent readout. -/
theorem logarithmicConnection_unipotent_tmul
    (R : LogResidue V) (p : ℂ)
    (f : HadjiivanovLogConnectionBridge.LaurentRing) (v : V) :
    logarithmicConnection R
        (sectionUnipotentReadout R p (f ⊗ₜ[ℂ] v)) =
      sectionUnipotentReadout R p
        (logarithmicConnection R (f ⊗ₜ[ℂ] v)) := by
  simp only [sectionUnipotentReadout_tmul, logarithmicConnection,
    LinearMap.add_apply, baseLogOperator_tmul,
    residueSectionOperator_tmul, map_add]
  rw [residueOperator_unipotent_commute]

/-- Full-carrier commutation of connection and unipotent readout. -/
theorem logarithmicConnection_unipotent
    (R : LogResidue V) (p : ℂ) (x : LogSection V) :
    logarithmicConnection R (sectionUnipotentReadout R p x) =
      sectionUnipotentReadout R p (logarithmicConnection R x) := by
  refine TensorProduct.induction_on x ?_ ?_ ?_
  · simp
  · exact logarithmicConnection_unipotent_tmul R p
  · intro x y hx hy
    simp [map_add, hx, hy]

theorem logarithmicConnection_unipotent_comp
    (R : LogResidue V) (p : ℂ) :
    (logarithmicConnection R).comp (sectionUnipotentReadout R p) =
      (sectionUnipotentReadout R p).comp (logarithmicConnection R) := by
  apply LinearMap.ext
  intro x
  exact logarithmicConnection_unipotent R p x

/-- Phase-decorated Hadjiivanov readout lifted to Laurent sections. -/
def sectionMonodromyReadout (R : LogResidue V) :
    LogSection V →ₗ[ℂ] LogSection V :=
  TensorProduct.map LinearMap.id (residueMonodromyEnd R)

@[simp] theorem sectionMonodromyReadout_tmul
    (R : LogResidue V)
    (f : HadjiivanovLogConnectionBridge.LaurentRing) (v : V) :
    sectionMonodromyReadout R (f ⊗ₜ[ℂ] v) =
      f ⊗ₜ[ℂ] residueMonodromyEnd R v := by
  simp [sectionMonodromyReadout]

/-- The residue also commutes with its phase-decorated readout. -/
theorem residueOperator_monodromyReadout_commute
    (R : LogResidue V) (v : V) :
    residueOperator R (residueMonodromyEnd R v) =
      residueMonodromyEnd R (residueOperator R v) := by
  simp only [residueMonodromyEnd, LinearMap.smul_apply, map_smul]
  rw [residueOperator_unipotent_commute]

/-- The full connection commutes with its phase-decorated Hadjiivanov
readout. -/
theorem logarithmicConnection_monodromyReadout
    (R : LogResidue V) (x : LogSection V) :
    logarithmicConnection R (sectionMonodromyReadout R x) =
      sectionMonodromyReadout R (logarithmicConnection R x) := by
  refine TensorProduct.induction_on x ?_ ?_ ?_
  · simp
  · intro f v
    simp only [sectionMonodromyReadout_tmul, logarithmicConnection,
      LinearMap.add_apply, baseLogOperator_tmul,
      residueSectionOperator_tmul, map_add]
    rw [residueOperator_monodromyReadout_commute]
  · intro x y hx hy
    simp [map_add, hx, hy]

theorem logarithmicConnection_monodromyReadout_comp (R : LogResidue V) :
    (logarithmicConnection R).comp (sectionMonodromyReadout R) =
      (sectionMonodromyReadout R).comp (logarithmicConnection R) := by
  apply LinearMap.ext
  intro x
  exact logarithmicConnection_monodromyReadout R x

end

end InfoGeometry.Projective.HadjiivanovLogConnectionReadoutCommutationBridge
