import Mathlib.Probability.CondVar

/-!
# Conditional Expectation Except One Coordinate

Mathlib-native packaging for “condition on all coordinates except `i`”.
-/

open MeasureTheory ProbabilityTheory

namespace InfoGeometry.SLT

variable {n : ℕ} {α : Type*} [MeasurableSpace α]

/-- The sigma-algebra generated by all coordinate projections except `i`. -/
def measurableSpaceExcept (i : Fin n) : MeasurableSpace (Fin n → α) :=
  ⨆ j : {j : Fin n // j ≠ i},
    MeasurableSpace.comap (fun x : Fin n → α => x j.1) (inferInstance : MeasurableSpace α)

/-- Conditional expectation given all coordinates except `i`. -/
noncomputable def condExpExcept
    (i : Fin n) (μ : Measure (Fin n → α)) (f : (Fin n → α) → ℝ) :
    (Fin n → α) → ℝ :=
  μ[f | measurableSpaceExcept (n := n) (α := α) i]

/-- Conditional variance given all coordinates except `i`. -/
noncomputable def condVarExcept
    (i : Fin n) (μ : Measure (Fin n → α)) (f : (Fin n → α) → ℝ) :
    (Fin n → α) → ℝ :=
  Var[f; μ | measurableSpaceExcept (n := n) (α := α) i]

/-- Conditional-variance integral identity for the “all-but-`i`” sigma-algebra. -/
lemma setIntegral_condVarExcept_eq
    (i : Fin n)
    (μ : Measure (Fin n → α))
    (f : (Fin n → α) → ℝ)
    (hm : measurableSpaceExcept (n := n) (α := α) i ≤
      (inferInstance : MeasurableSpace (Fin n → α)))
    [SigmaFinite (μ.trim hm)]
    (hfi : Integrable
      (fun ω => (f ω - (condExpExcept (n := n) (α := α) i μ f) ω) ^ 2) μ)
    {s : Set (Fin n → α)}
    (hs : MeasurableSet[measurableSpaceExcept (n := n) (α := α) i] s) :
    ∫ ω in s, (condVarExcept (n := n) (α := α) i μ f) ω ∂μ
      = ∫ ω in s, (f ω - (condExpExcept (n := n) (α := α) i μ f) ω) ^ 2 ∂μ := by
  simpa [condExpExcept, condVarExcept] using
    (ProbabilityTheory.setIntegral_condVar
      (m := measurableSpaceExcept (n := n) (α := α) i)
      (μ := μ)
      (X := f)
      (hm := hm)
      hfi hs)

end InfoGeometry.SLT
