import InfoGeometry.Clifford.SplitQ11Projectors
import InfoGeometry.Canonical.KreinProjectorLattice
import InfoGeometry.Volume.ConnesInfinitesimal
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Tactic.Module

/-!
# InfoGeometry.Volume.ConnesTomitaKreinDerivation

Finite Tomita/Krein readout of the Connes infinitesimal commutator law.

`InfoGeometry.Volume.ConnesInfinitesimal` proves that an exponential modular
Hamiltonian flow has infinitesimal generator `[K, A]`.  This module keeps the
corresponding finite split-`Cl(1,1)` statement at the local algebraic level:
when the modular sign is the split Krein involution `epsGen`, the commutator
with `epsGen` is exactly twice the commutator with the positive spectral
projector `epsPlusProjector`.

No mode-indexed current, normal ordering, or central extension is asserted here.
-/

namespace ConnesTomitaKreinDerivation

open InfoGeometry.Clifford.SplitQ11PhaseFlip
open InfoGeometry.Clifford.SplitQ11Projectors
open InfoGeometry.Canonical.KreinProjectorLattice

/-! ## Finite modular/Krein commutator readout -/

/-- Finite split-`Cl(1,1)` modular derivation generated by the Krein sign `ε`. -/
@[rep_depth krein]
noncomputable def finiteKreinModularDerivation (A : Alg) : Alg :=
  epsGen * A - A * epsGen

/-- Finite sector-leakage commutator with the positive Krein projector. -/
@[rep_depth krein]
noncomputable def finiteKreinPositiveProjectorCommutator (A : Alg) : Alg :=
  epsPlusProjector * A - A * epsPlusProjector

/--
The finite Krein sign commutator is twice the positive-projector commutator.

This is the local algebraic identification between the Connes infinitesimal
commutator generator and the Tomita/Krein idempotent sector calculus:
`[ε, A] = 2 [P₊, A]`, with `P₊ = (1 + ε) / 2`.
-/
@[rep_depth krein]
theorem finiteKrein_projector_commutator_as_modular_derivation (A : Alg) :
    finiteKreinModularDerivation A =
      (2 : ℝ) • finiteKreinPositiveProjectorCommutator A := by
  simp [finiteKreinModularDerivation, finiteKreinPositiveProjectorCommutator,
    epsPlusProjector_eq_half_one_add_eps, mul_add, add_mul, smul_add]
  module

/-- The finite modular generator is the Krein involution recovered from the lattice. -/
@[rep_depth krein]
theorem finiteKreinModularGenerator_eq_latticeInvolution :
    epsGen = KreinSector.kreinInvolution := by
  exact KreinSector.kreinInvolution_eq_epsGen.symm

/--
The same commutator readout using the lattice-recovered Krein involution.

This pins the Connes-style finite modular derivation to the projector lattice
owner theorem `KreinSector.kreinInvolution_eq_epsGen`.
-/
@[rep_depth krein]
theorem finiteKrein_lattice_projector_commutator_as_modular_derivation (A : Alg) :
    KreinSector.kreinInvolution * A - A * KreinSector.kreinInvolution =
      (2 : ℝ) • finiteKreinPositiveProjectorCommutator A := by
  rw [KreinSector.kreinInvolution_eq_epsGen]
  exact finiteKrein_projector_commutator_as_modular_derivation A

/-! ## Finite idempotent exponential representative -/

/--
Finite idempotent expansion of the exponential generated by the Krein sign:
`exp(t ε) = exp(t) P₊ + exp(-t) P₋`.

This is a finite algebraic representative of the exponential form; it is not an
analytic operator exponential theorem for an infinite-dimensional algebra.
-/
@[rep_depth krein]
noncomputable def finiteKreinIdempotentExponential (t : ℝ) : Alg :=
  Real.exp t • epsPlusProjector + Real.exp (-t) • epsMinusProjector

/-- Readback of the finite projector formula for `exp(t ε)`. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_formula (t : ℝ) :
    finiteKreinIdempotentExponential t =
      Real.exp t • epsPlusProjector + Real.exp (-t) • epsMinusProjector :=
  rfl

/-- The finite idempotent exponential is the identity at zero modular time. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_zero :
    finiteKreinIdempotentExponential 0 = (1 : Alg) := by
  simp only [finiteKreinIdempotentExponential, Real.exp_zero, neg_zero, one_smul]
  rw [add_comm, epsMinusProjector_add_epsPlusProjector]

/-- Orthogonal idempotents make the finite exponential multiplicative in time. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_add (s t : ℝ) :
    finiteKreinIdempotentExponential (s + t) =
      finiteKreinIdempotentExponential s * finiteKreinIdempotentExponential t := by
  unfold finiteKreinIdempotentExponential
  simp only [mul_add, add_mul, smul_mul_assoc, mul_smul_comm,
    epsPlusProjector_idempotent, epsMinusProjector_idempotent,
    epsPlusProjector_mul_epsMinusProjector, epsMinusProjector_mul_epsPlusProjector,
    smul_zero]
  rw [Real.exp_add]
  have hneg : Real.exp (-(s + t)) = Real.exp (-s) * Real.exp (-t) := by
    rw [neg_add, Real.exp_add]
  rw [hneg]
  module

/-- The inverse time finite exponential is the multiplicative inverse on this projector split. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_mul_neg (t : ℝ) :
    finiteKreinIdempotentExponential t * finiteKreinIdempotentExponential (-t) =
      (1 : Alg) := by
  rw [← finiteKrein_idempotent_exponential_add, add_neg_cancel,
    finiteKrein_idempotent_exponential_zero]

/-- The opposite product also closes to the identity. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_exponential_neg_mul (t : ℝ) :
    finiteKreinIdempotentExponential (-t) * finiteKreinIdempotentExponential t =
      (1 : Alg) := by
  rw [← finiteKrein_idempotent_exponential_add, neg_add_cancel,
    finiteKrein_idempotent_exponential_zero]

/--
Finite modular conjugation by the idempotent exponential.

This is the local algebraic analogue of the exponential conjugation
`exp(tK) A exp(-tK)` from `ConnesInfinitesimal`.
-/
@[rep_depth krein]
noncomputable def finiteKreinIdempotentTransport (t : ℝ) (A : Alg) : Alg :=
  finiteKreinIdempotentExponential t * A * finiteKreinIdempotentExponential (-t)

/-- At zero modular time the finite idempotent transport is the identity action. -/
@[rep_depth krein]
theorem finiteKrein_idempotent_transport_zero (A : Alg) :
    finiteKreinIdempotentTransport 0 A = A := by
  simp [finiteKreinIdempotentTransport, finiteKrein_idempotent_exponential_zero]

end ConnesTomitaKreinDerivation
