import Lean
import DAG.Basic
import DAG.Hydrate
import DAG.Analysis

/-!
# Docs.emit_blueprint_tex

LaTeX blueprint emission from DAG-derived skeletons.
-/

open Lean
open DAG

namespace Docs

/-- Escapes Lean names for LaTeX (e.g., replaces underscores with \_). -/
def escapeLatex (s : String) : String :=
  s.replace "_" "\\_"

/-- Generates a LaTeX section for a specific node in the True Skeleton. -/
def emitSkeletonNode (env : Environment) (name : Name) (vulSrcs : Nat) : IO String := do
  let nameStr := escapeLatex name.toString
  let mut out := "\\subsection{" ++ nameStr ++ "}\n"

  -- Add a metric badge showing its topological importance
  out := out ++
    "\\noindent\\textbf{Topological Vulnerability:} " ++
    toString vulSrcs ++ " downstream dependencies.\\\\ \n\n"

  -- Extract docstring if available
  if let some doc ← Lean.findDocString? env name then
    out := out ++ doc ++ "\n\n"

  -- Extract type signature
  if let some ci := env.find? name then
    let typeStr := toString ci.type
    let kind := match ci with
      | .thmInfo _ => "theorem"
      | .defnInfo _ => "definition"
      | _ => "remark"

    out := out ++ "\\begin{" ++ kind ++ "}[" ++ nameStr ++ "]\n"
    out := out ++ "\\begin{verbatim}\n" ++ typeStr ++ "\n\\end{verbatim}\n"
    out := out ++ "\\end{" ++ kind ++ "}\n\n"

  return out

/-- Generates the full LaTeX Blueprint document. -/
def emitBlueprint (env : Environment) (nsPrefix : String) (outPath : String) : IO Unit := do
  IO.println "[Blueprint] Hydrating DAG and extracting True Skeleton..."
  let g := buildGraphFromEnv env (some nsPrefix)
  let h := hydrate g
  let skeleton := extractTheorySkeleton h 1

  let mut tex := "% Auto-generated by InfoGeometry DAG Engine\n"
  tex := tex ++ "\\documentclass{article}\n"
  tex := tex ++ "\\usepackage{amsmath, amssymb, amsthm}\n"
  tex := tex ++ "\\usepackage[colorlinks=true]{hyperref}\n"
  tex := tex ++ "\\newtheorem{theorem}{Theorem}[section]\n"
  tex := tex ++ "\\newtheorem{definition}{Definition}[section]\n"
  tex := tex ++ "\\begin{document}\n"
  tex := tex ++ "\\title{InfoGeometry: Automated Blueprint}\n"
  tex := tex ++ "\\author{Socratic AI \\& Lean 4}\n"
  tex := tex ++ "\\maketitle\n\n"

  tex := tex ++ "\\section{The Core Topological Skeleton}\n"
  tex := tex ++
    "The following concepts form the structural load-bearing pillars of the theory, " ++
    "ranked by their downstream impact.\n\n"

  for (n, _, vulSrcs) in skeleton do
    let nodeTex ← emitSkeletonNode env n vulSrcs
    tex := tex ++ nodeTex

  tex := tex ++ "\\end{document}\n"

  IO.FS.writeFile (System.FilePath.mk outPath) tex
  IO.println s!"[Blueprint] Successfully wrote LaTeX blueprint to {outPath}"

end Docs

/-- Top-level `--run` entry point for blueprint emission. -/
def emit_blueprint_main (args : List String) : IO UInt32 := do
  let ns := args.headD "InfoGeometry"
  let outPath := if args.length > 1 then args[1]! else "blueprint.tex"

  Lean.initSearchPath (← Lean.findSysroot)
  let env ← Lean.importModules #[{ module := `InfoGeometry }] {}

  Docs.emitBlueprint env ns outPath
  return 0

/-- `lake env lean --run` entrypoint. -/
def main (args : List String) : IO UInt32 :=
  emit_blueprint_main args
