import InfoGeometry.Clifford.Cl55WittCartanDieudonneFull
import InfoGeometry.Clifford.Cl55WittReflectionPinBridge
import InfoGeometry.Clifford.Cl55WittOrthogonalNative

namespace InfoGeometry.Clifford.Clifford55

/-!
# Surjectivity of the explicit real split-Pin orthogonal action

The Cartan--Dieudonne factorization identifies the subgroup generated by
quadratic reflections with the native orthogonal group.  The existing image
bridge then turns this subgroup equality into a genuine surjectivity theorem
for the explicit real split-Pin action.
-/

theorem realSplitPinOrthogonalAction_map_top_eq_top :
    Subgroup.map realSplitPinOrthogonalAction ⊤ = (⊤ : Subgroup orthogonalGroup55) := by
  rw [realSplitPinImage_eq_quadraticReflectionSubgroup,
    quadraticReflectionSubgroup_eq_top]

theorem realSplitPinOrthogonalAction_surjective :
    Function.Surjective realSplitPinOrthogonalAction := by
  intro g
  have hg : g ∈ Subgroup.map realSplitPinOrthogonalAction ⊤ := by
    rw [realSplitPinOrthogonalAction_map_top_eq_top]
    trivial
  rcases hg with ⟨p, hp, hpg⟩
  exact ⟨p, hpg⟩

theorem realSplitPinOrthogonalAction_native_surjective :
    Function.Surjective (fun g : realSplitPin55 =>
      orthogonalGroup55IsometryEquiv (realSplitPinOrthogonalAction g)) := by
  intro h
  rcases realSplitPinOrthogonalAction_surjective
      (orthogonalGroup55IsometryEquiv.symm h) with ⟨g, hg⟩
  exact ⟨g, by
    change orthogonalGroup55IsometryEquiv
      (realSplitPinOrthogonalAction g) = h
    rw [hg, orthogonalGroup55IsometryEquiv.apply_symm_apply]
  ⟩

end InfoGeometry.Clifford.Clifford55
