import Mathlib.Data.Real.Star
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Algebra.Star.Basic
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NoncommRing
import InfoGeometry.Meta.MarkovJonesInduction
import InfoGeometry.Prequantum.LiouvilleCapacity

set_option autoImplicit false

/-!
# InfoGeometry.Prequantum.AlgebraicGNSState

Algebraic state surface for the GNS horizon.

The repository policy here is two-lane:

* use an abstract positive normalized real state when proving GNS algebraic
  identities such as the quadratic positivity and Cauchy--Schwarz estimates;
* use a compatible finite trace/state net for concrete tensor towers.  A
  completed Hilbert space, hyperfinite Type II₁ factor, or von Neumann closure
  is not constructed in this file.
-/

noncomputable section

namespace InfoGeometry.Prequantum.AlgebraicGNSState

/--
A real algebraic state on a real `*`-algebra.

This is the algebraic input needed before the GNS quotient: normalized linear
functional, positivity on `star x * x`, and a real symmetry condition used for
the real Cauchy--Schwarz theorem below.
-/
structure RealAlgebraicState
    (A : Type*) [Ring A] [Algebra ℝ A] [StarRing A] [StarModule ℝ A] where
  /-- Underlying real-linear functional. -/
  toLinearMap : A →ₗ[ℝ] ℝ
  /-- State normalization. -/
  normalized : toLinearMap 1 = 1
  /-- Positivity on algebraic squares. -/
  positive : ∀ x : A, 0 ≤ toLinearMap (star x * x)
  /-- Real symmetry of the quadratic pairing. -/
  symmetric : ∀ x y : A, toLinearMap (star y * x) = toLinearMap (star x * y)

namespace RealAlgebraicState

variable {A : Type*} [Ring A] [Algebra ℝ A] [StarRing A] [StarModule ℝ A]

/-- Evaluation notation for an algebraic state. -/
def eval (F : RealAlgebraicState A) (x : A) : ℝ :=
  F.toLinearMap x

@[simp]
theorem eval_one (F : RealAlgebraicState A) :
    F.eval 1 = 1 :=
  F.normalized

/-- Algebraic vacuum normalization: the quadratic readout of the unit is one. -/
theorem gns_vacuum_norm_eq_one (F : RealAlgebraicState A) :
    F.eval (star (1 : A) * 1) = 1 := by
  rw [star_one, one_mul]
  exact F.eval_one

@[simp]
theorem eval_add (F : RealAlgebraicState A) (x y : A) :
    F.eval (x + y) = F.eval x + F.eval y :=
  F.toLinearMap.map_add x y

@[simp]
theorem eval_smul (F : RealAlgebraicState A) (c : ℝ) (x : A) :
    F.eval (c • x) = c * F.eval x :=
  F.toLinearMap.map_smul c x

/-- The GNS null set associated to the algebraic quadratic form. -/
def gnsNullSet (F : RealAlgebraicState A) : Set A :=
  {x : A | F.eval (star x * x) = 0}

@[simp]
theorem mem_gnsNullSet_iff (F : RealAlgebraicState A) (x : A) :
    x ∈ F.gnsNullSet ↔ F.eval (star x * x) = 0 :=
  Iff.rfl

/-- Exact expansion of the algebraic GNS quadratic expression. -/
theorem state_quadratic_expansion (x y : A) (t : ℝ) :
    star (x + t • y) * (x + t • y) =
      star x * x + t • (star x * y + star y * x) + (t * t) • (star y * y) := by
  rw [star_add, star_smul]
  simp only [star_trivial]
  rw [add_mul, mul_add, mul_add]
  rw [mul_smul_comm, smul_mul_assoc]
  have h_double : (t • star y) * (t • y) = (t * t) • (star y * y) := by
    rw [smul_mul_assoc, mul_smul_comm, smul_smul]
  rw [h_double]
  simp only [smul_add]
  simp [add_assoc]

/-- Positivity of the real quadratic polynomial generated by a positive state. -/
theorem state_quadratic_nonneg
    (F : RealAlgebraicState A) (x y : A) (t : ℝ) :
    0 ≤ F.eval (star x * x) + 2 * t * F.eval (star y * x) +
      t ^ 2 * F.eval (star y * y) := by
  have h_pos := F.positive (x + t • y)
  rw [state_quadratic_expansion x y t] at h_pos
  rw [map_add, map_add, map_smul, map_smul] at h_pos
  have h_symm := F.symmetric x y
  have h_add_eval : F.toLinearMap (star x * y + star y * x) =
      2 * F.toLinearMap (star y * x) := by
    rw [map_add, h_symm]
    ring
  rw [h_add_eval] at h_pos
  simpa [eval, smul_eq_mul, pow_two, mul_assoc, mul_left_comm, mul_comm] using h_pos

/--
Algebraic real GNS Cauchy--Schwarz estimate, away from the zero vector in the
second slot.
-/
theorem algebraic_cauchy_schwarz
    (F : RealAlgebraicState A) (x y : A) (hy : 0 < F.eval (star y * y)) :
    (F.eval (star y * x)) ^ 2 ≤ F.eval (star x * x) * F.eval (star y * y) := by
  let B := F.eval (star y * x)
  let C := F.eval (star y * y)
  let t := -B / C
  have h_nonneg := state_quadratic_nonneg F x y t
  have h_eval : F.eval (star x * x) + 2 * t * B + t ^ 2 * C =
      F.eval (star x * x) - B ^ 2 / C := by
    unfold t B C
    field_simp [ne_of_gt hy]
    ring
  rw [h_eval] at h_nonneg
  have h_mul := mul_le_mul_of_nonneg_right h_nonneg (le_of_lt hy)
  have h_simp : (F.eval (star x * x) - B ^ 2 / C) * C =
      F.eval (star x * x) * C - B ^ 2 := by
    unfold B C
    field_simp [ne_of_gt hy]
  rw [h_simp] at h_mul
  linarith

/-- If a real affine-linear expression is nonnegative for every slope parameter,
then its slope is zero. -/
lemma linear_nonneg_imp_zero (B C : ℝ)
    (h_linear : ∀ t : ℝ, 0 ≤ C + 2 * t * B) :
    B = 0 := by
  by_contra hB
  let t : ℝ := - (C + 1) / (2 * B)
  have h_val : C + 2 * t * B = -1 := by
    unfold t
    field_simp [hB]
    ring
  have h_nonneg := h_linear t
  rw [h_val] at h_nonneg
  linarith

/-- If `y` is GNS-null, then its real algebraic inner product with every `x`
vanishes. -/
theorem state_null_product_zero (F : RealAlgebraicState A) (x y : A)
    (hy : y ∈ F.gnsNullSet) :
    F.eval (star y * x) = 0 := by
  have hy_eval : F.eval (star y * y) = 0 := hy
  have h_linear : ∀ t : ℝ, 0 ≤ F.eval (star x * x) + 2 * t * F.eval (star y * x) := by
    intro t
    have h_pos := F.state_quadratic_nonneg x y t
    rw [hy_eval] at h_pos
    have h_rewrite :
        F.eval (star x * x) + 2 * t * F.eval (star y * x) + t ^ 2 * 0 =
          F.eval (star x * x) + 2 * t * F.eval (star y * x) := by ring
    rwa [h_rewrite] at h_pos
  exact linear_nonneg_imp_zero (F.eval (star y * x)) (F.eval (star x * x)) h_linear

/-- The algebraic GNS null set contains zero. -/
theorem zero_mem_gnsNullSet (F : RealAlgebraicState A) :
    (0 : A) ∈ F.gnsNullSet := by
  change F.eval (star (0 : A) * 0) = 0
  simp [eval]

/-- The algebraic GNS null set is closed under negation. -/
theorem neg_mem_gnsNullSet (F : RealAlgebraicState A) {x : A}
    (hx : x ∈ F.gnsNullSet) :
    -x ∈ F.gnsNullSet := by
  change F.eval (star (-x) * (-x)) = 0
  rw [show (-x : A) = (-1 : ℝ) • x by simp, star_smul]
  simp only [star_trivial]
  rw [smul_mul_assoc, mul_smul_comm, smul_smul, F.eval_smul]
  simpa [hx]

/-- The algebraic GNS null set is closed under addition. -/
theorem add_mem_gnsNullSet (F : RealAlgebraicState A) {u v : A}
    (hu : u ∈ F.gnsNullSet) (hv : v ∈ F.gnsNullSet) :
    u + v ∈ F.gnsNullSet := by
  change F.eval (star (u + v) * (u + v)) = 0
  rw [star_add, add_mul, mul_add, mul_add]
  rw [F.eval_add, F.eval_add, F.eval_add]
  have huv : F.eval (star u * v) = 0 := state_null_product_zero F v u hu
  have hvu : F.eval (star v * u) = 0 := state_null_product_zero F u v hv
  have hu' : F.eval (star u * u) = 0 := hu
  have hv' : F.eval (star v * v) = 0 := hv
  rw [hu', huv, hvu, hv']
  ring

/-- Algebraic GNS equivalence: two elements differ by a GNS-null vector. -/
protected def gnsEquiv (F : RealAlgebraicState A) (x y : A) : Prop :=
  x - y ∈ F.gnsNullSet

/-- Reflexivity of algebraic GNS equivalence. -/
theorem gnsEquiv_refl (F : RealAlgebraicState A) (x : A) :
    F.gnsEquiv x x := by
  unfold RealAlgebraicState.gnsEquiv
  simpa using F.zero_mem_gnsNullSet

/-- Symmetry of algebraic GNS equivalence. -/
theorem gnsEquiv_symm (F : RealAlgebraicState A) {x y : A}
    (h : F.gnsEquiv x y) :
    F.gnsEquiv y x := by
  unfold RealAlgebraicState.gnsEquiv at h ⊢
  have hneg : y - x = -(x - y) := by noncomm_ring
  rw [hneg]
  exact F.neg_mem_gnsNullSet h

/-- Transitivity of algebraic GNS equivalence. -/
theorem gnsEquiv_trans (F : RealAlgebraicState A) {x y z : A}
    (hxy : F.gnsEquiv x y) (hyz : F.gnsEquiv y z) :
    F.gnsEquiv x z := by
  unfold RealAlgebraicState.gnsEquiv at hxy hyz ⊢
  have hsum : x - z = (x - y) + (y - z) := by noncomm_ring
  rw [hsum]
  exact F.add_mem_gnsNullSet hxy hyz

/-- Setoid generated by the algebraic GNS null set.  This is only the algebraic
quotient carrier relation; no Hilbert completion is constructed here. -/
def gnsSetoid (F : RealAlgebraicState A) : Setoid A where
  r := F.gnsEquiv
  iseqv := {
    refl := gnsEquiv_refl F
    symm := by
      intro x y h
      exact gnsEquiv_symm F h
    trans := by
      intro x y z hxy hyz
      exact gnsEquiv_trans F hxy hyz
  }

/-- The algebraic GNS quotient carrier.  This is not a completed Hilbert space. -/
abbrev GNSQuotient (F : RealAlgebraicState A) : Type _ :=
  Quotient (F.gnsSetoid)

end RealAlgebraicState

section CompatibleFiniteNet

open InfoGeometry.Meta.MarkovJonesInduction

variable {A : Nat → Type*}
variable [∀ n : Nat, Ring (A n)] [∀ n : Nat, Algebra ℝ (A n)]
variable [∀ n : Nat, StarRing (A n)] [∀ n : Nat, StarModule ℝ (A n)]

/--
Constructive finite-state net for tensor towers.

This is the state representation used before any completed GNS Hilbert space is
built: each finite stage has a positive normalized functional, and the
functionals agree along the one-step embeddings.
-/
structure CompatibleAlgebraicStateNet
    (Net : InductiveAlgebraNet (𝕜 := ℝ) (A := A)) where
  /-- Finite-stage state functional. -/
  state : ∀ n : Nat, A n →ₗ[ℝ] ℝ
  /-- Finite-stage normalization. -/
  normalized : ∀ n : Nat, state n 1 = 1
  /-- Finite-stage positivity. -/
  positive : ∀ n : Nat, ∀ x : A n, 0 ≤ state n (star x * x)
  /-- One-step compatibility with the algebraic embeddings. -/
  stable_one_step : ∀ n : Nat, ∀ x : A n, state (n + 1) (Net.embed n x) = state n x

namespace CompatibleAlgebraicStateNet

variable {Net : InductiveAlgebraNet (𝕜 := ℝ) (A := A)}

/-- Convert one finite stage of a compatible state net into an abstract algebraic state. -/
def atStage
    (S : CompatibleAlgebraicStateNet Net) (n : Nat)
    (hsymm : ∀ x y : A n, S.state n (star y * x) = S.state n (star x * y)) :
    RealAlgebraicState (A n) where
  toLinearMap := S.state n
  normalized := S.normalized n
  positive := S.positive n
  symmetric := hsymm

omit [∀ n : Nat, StarModule ℝ (A n)] in
/-- Compatibility along every finite iterated embedding. -/
theorem stable_embedMap
    (S : CompatibleAlgebraicStateNet Net)
    (m n : Nat) (h : m ≤ n) (x : A m) :
    S.state n (Net.embedMap m n h x) = S.state m x := by
  refine Nat.le_induction
    (m := m)
    (P := fun t ht => S.state t (Net.embedMap m t ht x) = S.state m x)
    ?base ?succ n h
  · change S.state m (Net.embedMap m m le_rfl x) = S.state m x
    rw [Net.embedMap_refl]
    rfl
  · intro t hmt ih
    rw [Net.embedMap_succ m t hmt]
    exact (S.stable_one_step t (Net.embedMap m t hmt x)).trans ih

/-- Build a compatible algebraic state net from a Markov trace net plus positivity. -/
def ofMarkovTraceNet
    (Tr : MarkovTraceNet Net)
    (hpos : ∀ n : Nat, ∀ x : A n, 0 ≤ Tr.trace n (star x * x)) :
    CompatibleAlgebraicStateNet Net where
  state := Tr.trace
  normalized := Tr.trace_one
  positive := hpos
  stable_one_step := Tr.trace_stable

omit [∀ n : Nat, StarModule ℝ (A n)] in
@[simp]
theorem ofMarkovTraceNet_state
    (Tr : MarkovTraceNet Net)
    (hpos : ∀ n : Nat, ∀ x : A n, 0 ≤ Tr.trace n (star x * x))
    (n : Nat) (x : A n) :
    (ofMarkovTraceNet (Net := Net) Tr hpos).state n x = Tr.trace n x :=
  rfl

end CompatibleAlgebraicStateNet

end CompatibleFiniteNet

end InfoGeometry.Prequantum.AlgebraicGNSState
