import sympy as sp
from sympy import Matrix, eye, zeros


def comm(a: Matrix, b: Matrix) -> Matrix:
    return a * b - b * a


def mobius_action(m: Matrix, z):
    return sp.simplify((m[0, 0] * z + m[0, 1]) / (m[1, 0] * z + m[1, 1]))


def upper_affine(a, b):
    return Matrix([[a, b], [0, 1 / a]])


def projective_T_power(m: int) -> Matrix:
    return Matrix([[1, m], [0, 1]])


I2 = eye(2)
t, s, z = sp.symbols("t s z")

# sl2 basis on the projective line / conformal line:
#   P = translation, D = dilation, K = special conformal.
P = Matrix([[0, 1], [0, 0]])
D = Matrix([[sp.Rational(1, 2), 0], [0, -sp.Rational(1, 2)]])
K = Matrix([[0, 0], [1, 0]])

# Standard projective generators.
T = Matrix([[1, 1], [0, 1]])
S = Matrix([[0, -1], [1, 0]])
S_inv = Matrix([[0, 1], [-1, 0]])

# Ambient null-pair witnesses for the conformal lift side.
u = Matrix([[0, 1], [0, 0]])
v = Matrix([[0, 0], [1, 0]])
J = u - v


def exp_translation(t):
    return I2 + t * P


def exp_dilation(s):
    return Matrix([[sp.exp(s / 2), 0], [0, sp.exp(-s / 2)]])


def exp_special_conformal(t):
    return I2 + t * K


def as_bool(m):
    return m.equals(zeros(*m.shape))


checks = {
    "P^2 = 0": as_bool(P**2),
    "D trace = 0": sp.simplify(D.trace()) == 0,
    "K^2 = 0": as_bool(K**2),
    "[D,P] = P": as_bool(comm(D, P) - P),
    "[D,K] = -K": as_bool(comm(D, K) + K),
    "[P,K] = 2D": as_bool(comm(P, K) - 2 * D),
    "exp(tP) = I + tP": as_bool(exp_translation(t) - Matrix([[1, t], [0, 1]])),
    "exp(sD) = diag(e^(s/2), e^(-s/2))": as_bool(
        exp_dilation(s) - Matrix([[sp.exp(s / 2), 0], [0, sp.exp(-s / 2)]])
    ),
    "exp(tK) = I + tK": as_bool(exp_special_conformal(t) - Matrix([[1, 0], [t, 1]])),
    "T acts as z -> z + 1": sp.simplify(mobius_action(T, z) - (z + 1)) == 0,
    "S acts as z -> -1/z": sp.simplify(mobius_action(S, z) + 1 / z) == 0,
    "T^m acts as z -> z + m": sp.simplify(mobius_action(projective_T_power(5), z) - (z + 5)) == 0,
    "S*T*S^{-1} is lower shear": (S * T * S_inv - Matrix([[1, 0], [-1, 1]])).equals(zeros(2)),
    "u^2 = 0": as_bool(u**2),
    "v^2 = 0": as_bool(v**2),
    "u v + v u = I": as_bool(u * v + v * u - I2),
    "J^2 = -I": as_bool(J**2 + I2),
    "J u J = v": as_bool(J * u * J - v),
    "J v J = u": as_bool(J * v * J - u),
}


aff_a, aff_b, aff_c, aff_d = sp.symbols("aff_a aff_b aff_c aff_d", nonzero=True)
aff_left = upper_affine(aff_a, aff_b)
aff_right = upper_affine(aff_c, aff_d)
aff_product = sp.simplify(aff_left * aff_right)
aff_group_closed = (
    aff_product[1, 0] == 0 and
    sp.simplify(aff_product.det() - 1) == 0
)
aff_action = sp.expand(mobius_action(aff_left, z))

# A clean projective-generator readout: translation/dilation/special conformal.
proj_span_rank = Matrix.hstack(
    sp.Matrix(P).reshape(4, 1),
    sp.Matrix(D).reshape(4, 1),
    sp.Matrix(K).reshape(4, 1),
).rank()

print("Conformal sl2 generator table:")
for key in ["P^2 = 0", "D trace = 0", "K^2 = 0", "[D,P] = P", "[D,K] = -K", "[P,K] = 2D"]:
    print(f"  {key}: {checks[key]}")

print("\nAffine subgroup readout:")
print(f"  upper-triangular closure: {aff_group_closed}")
print(f"  affine action: z -> {aff_action}")

print("\nProjective subgroup readout:")
for key in ["T acts as z -> z + 1", "S acts as z -> -1/z", "T^m acts as z -> z + m", "S*T*S^{-1} is lower shear"]:
    print(f"  {key}: {checks[key]}")

print("\nGenerator identification:")
print("  translation generator  P  = [[0,1],[0,0]]")
print("  dilation generator     D  = [[1/2,0],[0,-1/2]]")
print("  special conformal      K  = [[0,0],[1,0]]")
print("  affine subgroup         = upper-triangular PSL(2) slice generated by P and D")
print("  projective group        = PSL(2) generated by T and S on the affine chart")
print("  ambient conformal label = O(5,5) / Pin(5,5) projective-null readout")
print("  null pair               = u, v with u^2 = v^2 = 0 and uv + vu = I")
print("  inversion generator     = J = u - v")
print(f"  span rank of [P,D,K]    = {proj_span_rank}")
print(f"OVERALL: {all(checks.values()) and aff_group_closed and proj_span_rank == 3}")
