import Mathlib.Algebra.Order.Ring.Defs
import InfoGeometryCore.Basic
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Tactic

open InfoGeometryCore
open Complex
open Real
open Matrix
open scoped Matrix

noncomputable section

/-!
# Fibonacci Fusion Category — finite matrix readout, non-owner

The Fibonacci fusion category (Fib / SU(2)₃) is generated by two simple objects:
- `unit` (identity)
- `tau` (the non-trivial anyon)

Fusion rules: `tau ⊗ tau = unit ⊕ tau`.

This file is a finite matrix readout.  The categorical owner is
`InfoGeometry.Categorical.FibonacciBraiding`; this file does not construct a
`BraidedCategory` instance and does not prove categorical pentagon or hexagon
coherence.

## Proved theorems

* `phi_sq` — φ² = φ + 1 (golden ratio identity)
* `phiInv_identity` — φ⁻² + φ⁻¹ = 1 (F-matrix unitarity condition)
* `quantum_dimension_tau` — d_τ = φ

No extra global assumptions are introduced. All constants below are finite
matrix-level data derived from the fusion rules.
-/

namespace FibonacciFusion

/-! ### 1. Object type and fusion ring -/

inductive FibObject : Type
  | unit : FibObject
  | tau  : FibObject
  deriving DecidableEq, Inhabited

open FibObject

/-- Fusion tensor product on objects. Returns a list encoding the direct sum. -/
def tensorObjects : FibObject → FibObject → List FibObject
  | unit, x    => [x]
  | x, unit    => [x]
  | tau, tau   => [unit, tau]

/-- Fusion multiplicity: N_{ab}^c = dimension of Hom(a⊗b, c). -/
def fusionMultiplicity (a b c : FibObject) : ℕ :=
  (tensorObjects a b).count c

/-! ### 2. Golden ratio and its algebraic identities -/

/-- The golden ratio φ = (1 + √5)/2. -/
noncomputable abbrev phi := phiR

/-- The golden ratio conjugate φ̃ = (1 - √5)/2 = -φ⁻¹. -/
noncomputable def phiConj : ℝ := (1 - Real.sqrt 5) / 2

/-- φ⁻¹ = φ - 1 = (√5 - 1)/2. -/
noncomputable def phiInv : ℝ := phi - 1

/-- φ^(-1/2) — the coupling constant in the F-matrix. -/
noncomputable def phiInvSqrt : ℝ := Real.sqrt phiInv

/-- φ² = φ + 1.  This is the defining equation of the golden ratio. -/
theorem phi_sq : phi ^ 2 = phi + 1 := by
  dsimp [phi, phiR]
  calc
    ((1 + Real.sqrt 5) / 2)^2 = ((1 + Real.sqrt 5)^2) / 4 := by ring
    _ = (1 + 2 * Real.sqrt 5 + (Real.sqrt 5)^2) / 4 := by ring
    _ = (1 + 2 * Real.sqrt 5 + 5) / 4 := by rw [Real.sq_sqrt (by positivity : 0 ≤ (5 : ℝ))]
    _ = (6 + 2 * Real.sqrt 5) / 4 := by ring
    _ = (3 + Real.sqrt 5) / 2 := by ring
    _ = (1 + Real.sqrt 5) / 2 + 1 := by ring

/-- φ > 0. -/
theorem phi_pos : 0 < phi := by
  dsimp [phi, phiR]
  have h5pos : Real.sqrt 5 > 0 := Real.sqrt_pos.mpr (by positivity : (0 : ℝ) < 5)
  nlinarith

/-- φ > 1. -/
theorem phi_gt_one : (1 : ℝ) < phi := by
  dsimp [phi, phiR]
  have hsq : (1 : ℝ) ^ 2 < (5 : ℝ) := by norm_num
  have hsqrt : (1 : ℝ) < Real.sqrt 5 := by
    exact (Real.lt_sqrt (by positivity : (0 : ℝ) ≤ (1 : ℝ))).2 hsq
  nlinarith

/-- φ⁻¹ = φ - 1 > 0. -/
theorem phiInv_pos : 0 < phiInv := by
  unfold phiInv
  linarith [phi_gt_one]

/-- φ⁻² + φ⁻¹ = 1.  This is the identity needed for F-matrix unitarity. -/
theorem phiInv_sq_add_phiInv : phiInv ^ 2 + phiInv = 1 := by
  -- φ⁻¹ = φ - 1, so φ⁻² + φ⁻¹ = φ⁻¹(φ⁻¹ + 1) = φ⁻¹·φ = 1
  have h : phi * phiInv = 1 := by
    unfold phiInv
    nlinarith [phi_sq]
  have hsq_add : phiInv ^ 2 + phiInv = phiInv * (phiInv + 1) := by ring
  rw [hsq_add]
  have hphiInv_add_one : phiInv + 1 = phi := by
    unfold phiInv; ring
  rw [hphiInv_add_one, mul_comm, h]

/-! ### 3. Fusion matrix and quantum dimension -/

/-- The fusion matrix N_τ in the basis {unit, tau}:
    N_τ = [[0, 1], [1, 1]]. -/
noncomputable def fusionMatrixTau : Matrix (Fin 2) (Fin 2) ℝ :=
  ![![0, 1], ![1, 1]]

/-- The quantum dimension vector: d_unit = 1, d_tau = φ. -/
noncomputable def quantumDimension : FibObject → ℝ
  | unit => 1
  | tau  => phi

/--
**Theorem**: N_τ · d = φ · d.
The quantum dimension vector is the Perron-Frobenius eigenvector of the
fusion matrix, with eigenvalue φ (the golden ratio).
-/
theorem quantum_dimension_eigenvalue :
    fusionMatrixTau *ᵥ ![quantumDimension unit, quantumDimension tau]
    = (phi : ℝ) • ![quantumDimension unit, quantumDimension tau] := by
  unfold fusionMatrixTau quantumDimension
  ext i
  fin_cases i
  · -- component 0: (0, 0)·1 + (0, 1)·φ = φ·1
    simp [Matrix.mulVec]
  · -- component 1: (1, 0)·1 + (1, 1)·φ = φ·φ = φ*φ
    simp [Matrix.mulVec]
    have : phi ^ 2 = phi + 1 := phi_sq
    nlinarith

/-! ### 4. F-matrix (associator) for Fib -/

/--
The 2×2 F-matrix for the Fib category (all external legs = tau):
F = [[ φ⁻¹,   φ^{-½} ],
     [ φ^{-½}, -φ⁻¹   ]]
-/
noncomputable def F_matrix : Matrix (Fin 2) (Fin 2) ℝ :=
  ![![phiInv, phiInvSqrt], ![phiInvSqrt, -phiInv]]

/--
**Theorem**: F is unitary: FᵀF = I.

Proof: F = [[a, b], [b, -a]] with a² + b² = 1.
- a = φ⁻¹, b = φ^{-½}, so a² + b² = φ⁻² + φ⁻¹ = 1 (by phiInv_sq_add_phiInv).
-/
theorem F_matrix_unitary : F_matrix * F_matrix = (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  have ha2_add_b2 : phiInv ^ 2 + phiInvSqrt ^ 2 = 1 := by
    unfold phiInvSqrt
    rw [Real.sq_sqrt phiInv_pos.le]
    rw [phiInv_sq_add_phiInv]
  unfold F_matrix
  ext i j; fin_cases i <;> fin_cases j
  · -- (0,0): phiInv*phiInv + phiInvSqrt*phiInvSqrt = 1
    simp [Matrix.mul_apply, Fin.sum_univ_two]
    simpa [pow_two, add_comm] using ha2_add_b2
  · -- (0,1): phiInv*phiInvSqrt + phiInvSqrt*(-phiInv) = 0
    simp [Matrix.mul_apply, Fin.sum_univ_two]
    ring
  · -- (1,0): phiInvSqrt*phiInv + (-phiInv)*phiInvSqrt = 0
    simp [Matrix.mul_apply, Fin.sum_univ_two]
    ring
  · -- (1,1): phiInvSqrt*phiInvSqrt + (-phiInv)*(-phiInv) = 1
    simp [Matrix.mul_apply, Fin.sum_univ_two]
    simpa [pow_two, add_comm] using ha2_add_b2

/-! ### 5. R-matrix (braiding) for Fib -/

/--
The braid eigenvalue for the unit fusion channel:
R₁^{ττ} = e^{4πi/5}
-/
noncomputable def R1_phase : ℂ := Complex.exp (Complex.I * (4 * π / 5))

/--
The braid eigenvalue for the tau fusion channel:
R_τ^{ττ} = e^{-2πi/5}
-/
noncomputable def Rtau_phase : ℂ := Complex.exp (-Complex.I * (2 * π / 5))

/-- Both braid eigenvalues lie on the unit circle. -/
theorem R_phases_unitary : ‖R1_phase‖ = 1 ∧ ‖Rtau_phase‖ = 1 := by
  have h1 : ‖R1_phase‖ = 1 := by
    unfold R1_phase
    simpa [mul_comm] using Complex.norm_exp_ofReal_mul_I (4 * π / 5)
  have h2 : ‖Rtau_phase‖ = 1 := by
    unfold Rtau_phase
    simpa [mul_comm] using Complex.norm_exp_ofReal_mul_I (-(2 * π / 5))
  exact ⟨h1, h2⟩

/--
R₁^{ττ} · R_τ^{ττ} = e^{2πi/5}.

This is the relative topological phase between the two fusion channels.
The product equals the twist eigenvalue ratio θ_τ / θ_1 = e^{4πi/5}.
-/
theorem R_product : R1_phase * Rtau_phase = Complex.exp (Complex.I * (2 * π / 5)) := by
  unfold R1_phase Rtau_phase
  -- exp(i·4π/5) · exp(-i·2π/5) = exp(i·4π/5 - i·2π/5) = exp(i·2π/5)
  rw [← Complex.exp_add]
  congr 1
  ring

/-! ### 6. Explicit closure debt -/

/--
Closure debt: categorical pentagon coherence for the Fibonacci associator.

The finite `F_matrix_unitary` theorem above is useful matrix evidence, but it
is not the categorical pentagon equation.
-/
def pentagon_identity_closure_debt : String :=
  "Prove categorical Fibonacci pentagon coherence in InfoGeometry.Categorical.FibonacciBraiding."

/--
Closure debt: categorical hexagon coherence for the Fibonacci braiding.

The finite phase theorems above are useful matrix evidence, but they are not a
braided monoidal category instance.
-/
def hexagon_identities_closure_debt : String :=
  "Prove categorical Fibonacci hexagon coherence in InfoGeometry.Categorical.FibonacciBraiding."

end FibonacciFusion
