import InfoGeometry.Quantum.HurwitzFenchel
import InfoGeometry.Quantum.FenchelConjugation

/-!
# InfoGeometry.Quantum.FermionicOperators

This file records elementary identities for the complex-coordinate model from
`HurwitzFenchel`.  It does not assert an octonionic or non-associative
fermionic operator construction.

While full associativity is lost in the 8-dimensional octonions ($\mathbb{O}$) and 
split-octonions ($\mathbb{O}_s$), the algebra remains alternative. This guarantees that 
any subalgebra generated by just two elements is completely associative.

Consequently, an operator $x$ and its Fenchel dual $\overline{x}$ always associate 
with any target quantum state $y$:
$(x \bullet \overline{x}) \bullet y = x \bullet (\overline{x} \bullet y) = n(x)y$

This topological binding prevents the geometry from tearing itself apart during 
the non-commutative generation of fermionic creation and annihilation operators.
-/

namespace InfoGeometry.Quantum

/-- The finite complex-coordinate product associates for this conjugate pair. -/
theorem complex_coordinate_associativity_patch (x y : ComplexCoordinate) :
    hurwitz_mul (hurwitz_mul x (hurwitz_conj x)) y = 
      hurwitz_mul x (hurwitz_mul (hurwitz_conj x) y) := by
  ext
  · dsimp [hurwitz_mul, hurwitz_conj]
    ring
  · dsimp [hurwitz_mul, hurwitz_conj]
    ring

/-- Multiplication by a coordinate and its conjugate normalizes the state. -/
theorem complex_coordinate_state_normalization (x y : ComplexCoordinate) :
    hurwitz_mul (hurwitz_mul x (hurwitz_conj x)) y = (hurwitz_norm x * y.1, hurwitz_norm x * y.2) := by
  ext
  · dsimp [hurwitz_mul, hurwitz_conj, hurwitz_norm]
    ring
  · dsimp [hurwitz_mul, hurwitz_conj, hurwitz_norm]
    ring

end InfoGeometry.Quantum
