/-
Copyright (c) 2025 Kalle Kytölä. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kalle Kytölä
-/
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.GroupTheory.GroupAction.Ring
import Mathlib.Order.CompletePartialOrder

/-!
# Verma modules over algebras

This file defines a generalization of the notion of Verma modules used in Lie algebra
representation theory.

## Main definitions

* `vermaIdeal`: The left ideal in a `𝕜`-algebra `A` generated by elemements of the form `aᵢ - ηᵢ`,
  for some `aᵢ ∈ A` and `ηᵢ ∈ 𝕜`.
* `VermaModule`: The generalized Verma module for a `𝕜`-algebra `A`, defined as the quotient
  `A / vermaIdeal η`.
* `VermaModule.hwVec`: The "highest weight vector" of the Verma module.
* `VermaModule.universalMap`: The universal property of the Verma module:
  Given another module `M` over `A` and a "target" vector `hwv ∈ M` satisfying `aᵢ • hwv = ηᵢ • hwv`
  for all `i`, one obtains an `A`-module map from the Verma module to `M` uniquely specified by the
  requirement `hwVec η ↦ hwv`.

## Main statements

* `VermaModule.hwVec_cyclic`: The Verma module is generated by its highest weight vector.
* `VermaModule.range_universalMap_eq_span`: The map guaranteed by the universal property
  of the Verma module is surjective onto the submodule generated by the "target" vector.

## Implementation notes

The generalized Verma module for a `𝕜`-algebra `A` is defined as a quotient of `A` by a left ideal
generated by elemements of the form `aᵢ - ηᵢ`, for some `aᵢ ∈ A` and `ηᵢ ∈ 𝕜`. In the file
`LieVerma.lean` this is specialized to the most common case of Verma modules of Lie algebras
with a triangular decomposition. The generalized version applies beyond that case, e.g., with
Clifford algebras, it allows to construct fermionic Fock spaces.

## Tags

Verma module

-/

namespace VirasoroProject



section canonical_map_from_a_ring_to_a_submodule_generated_by_a_vector

variable (R : Type*) [Ring R] {M : Type*} [AddCommGroup M] [Module R M]

/-- A surjective module map from a ring to the submodule generated by a given vector. -/
def Ring.smulVectorₗ (m : M) :
    R →ₗ[R] M where
  toFun a := a • m
  map_add' a₁ a₂ := by simp [add_smul]
  map_smul' a₁ a₂ := by simp [mul_smul]

@[simp] lemma Ring.smulVectorₗ_one (m : M) :
    smulVectorₗ R m 1 = m := by
  simp [smulVectorₗ]

lemma Ring.range_smulVectorₗ_eq_span (m : M) :
    LinearMap.range (smulVectorₗ R m) = Submodule.span R {m} := by
  ext v
  rw [show v ∈ Submodule.span R {m} ↔ v ∈ (Submodule.span R {m} : Set M) from Eq.to_iff rfl]
  rw [Submodule.span_singleton_eq_range R m ]
  simp only [LinearMap.mem_range, Set.mem_range]
  rfl

end canonical_map_from_a_ring_to_a_submodule_generated_by_a_vector



section cyclic_vectors

/-- The submodule spanned by the unit `1` of a ring is the whole ring. -/
lemma one_cyclic {R : Type*} [Semiring R] :
    Submodule.span R {(1 : R)} = ⊤ :=
  (Submodule.span_singleton_eq_top_iff R 1).mpr fun a ↦ ⟨a, by simp⟩

/-- A surjective linear map maps any cyclic vector (a vector which generates the whole
module) to a cyclic vector. -/
lemma LinearMap.apply_cyclic_of_cyclic_of_surjective {R : Type*} [Semiring R]
    {M₁ M₂ : Type*} [AddCommGroup M₁] [AddCommGroup M₂] [Module R M₁] [Module R M₂]
    {f : M₁ →ₗ[R] M₂} (f_surj : LinearMap.range f = ⊤)
    (m : M₁) (cyclic : Submodule.span R {m} = ⊤) :
    Submodule.span R {f m} = ⊤ := by
  rw [Submodule.span_singleton_eq_top_iff] at *
  intro m₂
  obtain ⟨m₁, hm⟩ : ∃ m₁, f m₁ = m₂ := LinearMap.range_eq_top.mp f_surj m₂
  obtain ⟨a, ha⟩ := cyclic m₁
  refine ⟨a, by rw [← map_smul, ha, hm]⟩

end cyclic_vectors



section generalized_Verma_module

variable {𝕜 A : Type*} [CommRing 𝕜] [Ring A] [Algebra 𝕜 A]
variable {ι : Type*}

/-- The left ideal used in the construction of a (generalized) Verma module for an algebra `A`:
`η : ι → A × 𝕜` is an indexed collection of algebra elements and scalars by which they should act
on the "highest weight vector". -/
def vermaIdeal (η : ι → A × 𝕜) :
    Submodule A A :=
  Submodule.span A (Set.range <| fun (i : ι) ↦ (η i).1 - algebraMap 𝕜 A (η i).2)

/-- The (generalied) Verma module of an algebra `A`:
`η : ι → A × 𝕜` is an indexed collection of algebra elements and scalars by which they should act
on the "highest weight vector". -/
def VermaModule (η : ι → A × 𝕜) :=
  A ⧸ vermaIdeal η

/-- The highest weight vector in a (generalized) Verma module. -/
def VermaModule.hwVec (η : ι → A × 𝕜) :
    VermaModule η :=
  Submodule.Quotient.mk 1

instance (η : ι → A × 𝕜) :
    AddCommGroup (VermaModule η) :=
  Submodule.Quotient.addCommGroup _

instance (η : ι → A × 𝕜) :
    Module A (VermaModule η) :=
  Submodule.Quotient.module _

/-- The highest weight vector in a Verma module is cyclic. -/
lemma VermaModule.hwVec_cyclic (η : ι → A × 𝕜) :
    Submodule.span A {hwVec η} = ⊤ :=
  LinearMap.apply_cyclic_of_cyclic_of_surjective (Submodule.range_mkQ _) 1 one_cyclic

/-- The defining property of the highest weight vector in a Verma module. -/
lemma VermaModule.apply_hwVec_eq (η : ι → A × 𝕜) (i : ι) :
    (η i).1 • hwVec η = (algebraMap 𝕜 A (η i).2) • hwVec η := by
  rw [show (algebraMap 𝕜 A (η i).2) • hwVec η
            = Submodule.Quotient.mk ((algebraMap 𝕜 A (η i).2) • 1) from rfl]
  rw [hwVec, ← Submodule.Quotient.mk_smul, ← sub_eq_zero, ← Submodule.Quotient.mk_sub]
  apply (Submodule.Quotient.mk_eq_zero ..).mpr
  exact Submodule.mem_span_of_mem (by simp)

variable {M : Type*} [AddCommGroup M] [Module A M]

lemma vermaIdeal_le_ker_smulVectorₗ (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    vermaIdeal η ≤ LinearMap.ker (Ring.smulVectorₗ A hwv) := by
  simp only [vermaIdeal, Submodule.span_le]
  intro a ⟨i, a_eq⟩
  simp only [← a_eq, SetLike.mem_coe, LinearMap.mem_ker, map_sub, sub_eq_zero]
  exact hwv_prop i

/-- The map guaranteed by the universal property of a Verma module. -/
def VermaModule.universalMap (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    VermaModule η →ₗ[A] M :=
  Submodule.liftQ (vermaIdeal η) (Ring.smulVectorₗ A hwv) (vermaIdeal_le_ker_smulVectorₗ _ hwv_prop)

/-- The image of the highest weight vector of a Verma module under the map guaranteed by the
universal property is the assigned highest weight vector in the image module. -/
@[simp] lemma VermaModule.universalMap_hwVec (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    universalMap η hwv_prop (hwVec η) = hwv := by
  convert Submodule.liftQ_apply (vermaIdeal η) (Ring.smulVectorₗ A hwv) 1
  simp

/-- The range of the map guaranteed by the universal property of a Verma module is the submodule
generated by the assigned highest weight vector in the image module. -/
lemma VermaModule.range_universalMap_eq_span (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    LinearMap.range (universalMap η hwv_prop) = Submodule.span A {hwv} := by
  have key := VermaModule.hwVec_cyclic η ▸ Submodule.map_top (universalMap η hwv_prop)
  simp [← key, Submodule.map_span]

end generalized_Verma_module


section IsVerma

variable {𝕜 A : Type*} [CommRing 𝕜] [Ring A] [Algebra 𝕜 A]
variable {ι : Type*}

universe u

/-- The characteristic predicate of a Verma module. -/
structure IsVermaModule (η : ι → A × 𝕜) (M : Type u) (hwv : M) [AddCommGroup M] [Module A M] where
  hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv
  universal : ∀ (V : Type u) [AddCommGroup V] [Module A V] (v : V)
                (_ : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v),
                ∃! (φ : M →ₗ[A] V), φ hwv = v

/-- The universal map from a module satisfying the characteristic predicate of a Verma module. -/
noncomputable def IsVermaModule.universalMap {η : ι → A × 𝕜} {M : Type u} {hwv : M}
    [AddCommGroup M] [Module A M] (h : IsVermaModule η M hwv)
    {V : Type u} [AddCommGroup V] [Module A V] {v : V}
    (hv : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v) :
    M →ₗ[A] V :=
  (h.universal V v hv).choose

/-- The defining property of a universal map from a module satisfying the characteristic predicate
of a Verma module. -/
@[simp] lemma IsVermaModule.universalMap_hwv {η : ι → A × 𝕜} {M : Type u} {hwv : M}
    [AddCommGroup M] [Module A M] (h : IsVermaModule η M hwv) {V : Type u}
    [AddCommGroup V] [Module A V] {v : V} (hv : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v) :
    h.universalMap hv hwv = v :=
  (h.universal V v hv).choose_spec.1

/-- The uniqueness of the universal map from a module satisfying the characteristic predicate of a Verma module. -/
lemma IsVermaModule.universalMap_unique {η : ι → A × 𝕜} {M : Type u} {hwv : M}
    [AddCommGroup M] [Module A M] (h : IsVermaModule η M hwv) {V : Type u}
    [AddCommGroup V] [Module A V] {v : V} (hv : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v)
    {ψ : M →ₗ[A] V} (hψ : ψ hwv = v) :
    ψ = h.universalMap hv :=
  (h.universal V v hv).choose_spec.2 ψ hψ

lemma VermaModule.isVermaModule (η : ι → A × 𝕜) :
    IsVermaModule η (VermaModule η) (hwVec η) := by
  refine ⟨fun i ↦ apply_hwVec_eq η i, ?_⟩
  intro V _ _ v hv
  use universalMap η hv
  refine ⟨universalMap_hwVec η hv, ?_⟩
  intro ψ hψ
  ext u
  obtain ⟨a, hau⟩ : ∃ (a : A), a • hwVec η = u := by
    have key := hwVec_cyclic η ▸ Submodule.mem_top (R := A) (x := u)
    rwa [Submodule.mem_span_singleton] at key
  simp [← hau, hψ]

/-- Uniqueness up to isomorphism of a Verma module, phrased as the construction of an isomorphism
between two modules that satisfy the characteristic predicate `IsVermaModule`. -/
noncomputable def IsVermaModule.equiv_of_isVermaModule (η : ι → A × 𝕜) (M₁ M₂ : Type u) (hwv₁ : M₁) (hwv₂ : M₂)
    [AddCommGroup M₁] [Module A M₁] [AddCommGroup M₂] [Module A M₂]
    (h₁ : IsVermaModule η M₁ hwv₁) (h₂ : IsVermaModule η M₂ hwv₂) :
    M₁ ≃ₗ[A] M₂ where
  toFun := h₁.universalMap h₂.hwv_prop
  map_add' := LinearMap.map_add (h₁.universalMap h₂.hwv_prop)
  map_smul' := LinearMap.CompatibleSMul.map_smul (h₁.universalMap h₂.hwv_prop)
  invFun := h₂.universalMap h₁.hwv_prop
  left_inv := by
    have obs := h₁.universalMap_unique h₁.hwv_prop
                (ψ := h₂.universalMap h₁.hwv_prop ∘ₗ (h₁.universalMap h₂.hwv_prop)) (by simp)
    have obs' := h₁.universalMap_unique h₁.hwv_prop (ψ := LinearMap.id) rfl
    exact LinearMap.congr_fun (obs'.symm ▸ obs)
  right_inv := by
    have obs := h₂.universalMap_unique h₂.hwv_prop
                (ψ := h₁.universalMap h₂.hwv_prop ∘ₗ (h₂.universalMap h₁.hwv_prop)) (by simp)
    have obs' := h₂.universalMap_unique h₂.hwv_prop (ψ := LinearMap.id) rfl
    exact LinearMap.congr_fun (obs'.symm ▸ obs)

end IsVerma


end VirasoroProject
