import Mathlib.Tactic

set_option autoImplicit false

namespace InfoGeometry.QuantumMonodromy

variable {A : Type*} [Ring A]

/-!
#### BUCKET 1: CLOSED FINITE THEOREMS
[Fully verified lemmas with zero remaining dependencies or open goals. Fully checked by the kernel.]
- `nilpotent_jordan_power`: exact monodromy step of a Jordan cell generated by
  square-zero nilpotent modular transitions.

#### BUCKET 2: CONDITIONAL THEOREMS FROM EXPLICIT WITNESSES
- None.

#### BUCKET 3: OPEN CLOSURE DEBT
- None.
-/

/--
CLOSED THEOREM: the nilpotent Jordan power/monodromy step.

If `N² = 0` and `u` commutes with `N`, then the non-diagonal Jordan cell
`u + N` satisfies the exact finite power formula

`(u + N)^(n + 1) = u^(n + 1) + (n + 1) • (u^n * N)`.
-/
theorem nilpotent_jordan_power
    (u N : A)
    (h_comm : Commute u N)
    (h_nil : N * N = 0)
    (n : ℕ) :
    (u + N) ^ (n + 1) = u ^ (n + 1) + (n + 1) • (u ^ n * N) := by
  induction n with
  | zero =>
      simp
  | succ k ih =>
      have h_pow_L : (u + N) ^ (k + 2) = (u + N) ^ (k + 1) * (u + N) := by
        simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
          (pow_succ (u + N) (k + 1))
      rw [h_pow_L, ih]
      rw [add_mul, mul_add, mul_add]
      have h_pow_succ : u ^ (k + 1) * u = u ^ (k + 2) := by
        simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
          (pow_succ u (k + 1)).symm
      rw [h_pow_succ]
      have h_smul_mul1 :
          ((k + 1) • (u ^ k * N)) * u = (k + 1) • (u ^ (k + 1) * N) := by
        have hcore : (u ^ k * N) * u = u ^ (k + 1) * N := by
          calc
            u ^ k * N * u = u ^ k * (N * u) := by rw [mul_assoc]
            _ = u ^ k * (u * N) := by rw [h_comm.symm.eq]
            _ = (u ^ k * u) * N := by rw [← mul_assoc]
            _ = u ^ (k + 1) * N := by rw [pow_succ]
        simpa [nsmul_eq_mul, mul_assoc] using
          congrArg (fun x => ((k + 1 : ℕ) : A) * x) hcore
      have h_smul_mul2 : ((k + 1) • (u ^ k * N)) * N = 0 := by
        have h_zero : u ^ k * N * N = 0 := by
          calc
            u ^ k * N * N = u ^ k * (N * N) := by rw [mul_assoc]
            _ = u ^ k * 0 := by rw [h_nil]
            _ = 0 := by rw [mul_zero]
        simpa [nsmul_eq_mul, mul_assoc] using
          congrArg (fun x => ((k + 1 : ℕ) : A) * x) h_zero
      rw [h_smul_mul1, h_smul_mul2, add_zero]
      simp only [nsmul_eq_mul]
      calc
        u ^ (k + 2) + u ^ (k + 1) * N + ((k + 1 : ℕ) : A) * (u ^ (k + 1) * N)
            = u ^ (k + 2) +
                (u ^ (k + 1) * N + ((k + 1 : ℕ) : A) * (u ^ (k + 1) * N)) := by
              rw [add_assoc]
        _ = u ^ (k + 2) +
                ((1 : A) * (u ^ (k + 1) * N) +
                  ((k + 1 : ℕ) : A) * (u ^ (k + 1) * N)) := by
              rw [one_mul]
        _ = u ^ (k + 2) +
                (((1 : A) + ((k + 1 : ℕ) : A)) * (u ^ (k + 1) * N)) := by
              rw [add_mul]
        _ = u ^ (k + 1 + 1) +
                (((k + 1 + 1 : ℕ) : A) * (u ^ (k + 1) * N)) := by
              have hpow : u ^ (k + 2) = u ^ (k + 1 + 1) := by
                have hk : k + 2 = k + 1 + 1 := by omega
                rw [hk]
              have hcast :
                  (1 : A) + ((k + 1 : ℕ) : A) = ((k + 1 + 1 : ℕ) : A) := by
                calc
                  (1 : A) + ((k + 1 : ℕ) : A)
                      = 1 + (((k : ℕ) : A) + 1) := by
                        rw [Nat.cast_add, Nat.cast_one]
                  _ = (1 + ((k : ℕ) : A)) + 1 := by
                        rw [add_assoc]
                  _ = ((1 + k : ℕ) : A) + 1 := by
                        rw [Nat.cast_add, Nat.cast_one]
                  _ = ((1 + k + 1 : ℕ) : A) := by
                        have h :
                            (((1 + k) + 1 : ℕ) : A) =
                              ((1 + k : ℕ) : A) + ((1 : ℕ) : A) :=
                          Nat.cast_add (1 + k) 1
                        rw [Nat.cast_one] at h
                        exact h.symm
                  _ = ((k + 1 + 1 : ℕ) : A) := by
                        exact congrArg (fun m : ℕ => (m : A)) (by omega)
              rw [hpow]
              rw [hcast]

/--
Natural-number scalars are central in every ring.

This is the scalar bookkeeping lemma used by the abstract winding formula below.
-/
lemma commute_nat_cast (x : A) (n : ℕ) : Commute x (n : A) := by
  induction n with
  | zero =>
      simp
  | succ k ih =>
      rw [Nat.cast_succ]
      exact Commute.add_right ih (Commute.one_right x)

/--
One unipotent Jordan multiplication step:
`(1 + nε)(1 + ε) = 1 + (n + 1)ε` when `ε² = 0`.

The `lambda` and commutation hypothesis are retained so the step has the same
parameter surface as the full monodromy winding theorem.
-/
lemma monodromy_unipotent_step_mul
    (lambda epsilon : A)
    (h_nil : epsilon * epsilon = 0)
    (_h_comm : Commute lambda epsilon)
    (n : ℕ) :
    (1 + (n : A) * epsilon) * (1 + epsilon) =
      1 + ((n + 1 : ℕ) : A) * epsilon := by
  rw [add_mul, one_mul, mul_add, mul_one]
  have h_nil_term : (n : A) * epsilon * epsilon = 0 := by
    rw [mul_assoc, h_nil, mul_zero]
  rw [h_nil_term, add_zero]
  calc
    1 + epsilon + (n : A) * epsilon =
        1 + (1 * epsilon + (n : A) * epsilon) := by rw [one_mul, add_assoc]
    _ = 1 + ((1 + (n : A)) * epsilon) := by rw [add_mul]
    _ = 1 + (((n : A) + 1) * epsilon) := by rw [add_comm (1 : A) (n : A)]
    _ = 1 + ((n + 1 : ℕ) : A) * epsilon := by rw [Nat.cast_succ]

/--
Genuine abstract monodromy winding theorem.

If `ε² = 0` and the scalar/rotor part `λ` commutes with the nilpotent
logarithmic shear `ε`, then winding the local block `λ * (1 + ε)` exactly
`n` times preserves the phase/nilpotent separation:

`(λ * (1 + ε))^n = λ^n * (1 + n ε)`.

This is the ring-level theorem behind the Hadjiivanov logarithmic monodromy
power law and the parabolic `T`-sector readouts.
-/
theorem monodromy_winding_formula
    (lambda epsilon : A)
    (h_nil : epsilon * epsilon = 0)
    (h_comm : Commute lambda epsilon)
    (n : ℕ) :
    (lambda * (1 + epsilon)) ^ n =
      lambda ^ n * (1 + (n : A) * epsilon) := by
  induction n with
  | zero =>
      simp
  | succ n ih =>
      rw [pow_succ, ih]
      have h_comm_term : Commute lambda (1 + (n : A) * epsilon) := by
        apply Commute.add_right
        · exact Commute.one_right lambda
        · exact Commute.mul_right (commute_nat_cast lambda n) h_comm
      calc
        lambda ^ n * (1 + (n : A) * epsilon) * (lambda * (1 + epsilon))
            = lambda ^ n * ((1 + (n : A) * epsilon) * lambda) *
                (1 + epsilon) := by
              noncomm_ring
        _ = lambda ^ n * (lambda * (1 + (n : A) * epsilon)) *
              (1 + epsilon) := by
              rw [h_comm_term.eq]
        _ = (lambda ^ n * lambda) *
              ((1 + (n : A) * epsilon) * (1 + epsilon)) := by
              noncomm_ring
        _ = lambda ^ (n + 1) *
              ((1 + (n : A) * epsilon) * (1 + epsilon)) := by
              rw [pow_succ]
        _ = lambda ^ (n + 1) * (1 + ((n + 1 : ℕ) : A) * epsilon) := by
              rw [monodromy_unipotent_step_mul lambda epsilon h_nil h_comm n]

end InfoGeometry.QuantumMonodromy
