/-
Copyright (c) 2024-2026 Nikolay Goutev and Dimitar Tonev.
Institute for Nuclear Research and Nuclear Energy (INRNE-BAS),
Bulgarian Academy of Sciences.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Authors: Nikolay Goutev, Dimitar Tonev
-/

import DAG.Basic
import InfoGeometry.Canonical.Algebra
import InfoGeometry.Canonical.AlgebraicStationarity
import InfoGeometry.Canonical.ActionDuality
import InfoGeometry.Canonical.AnomalyInflow
import InfoGeometry.Canonical.AnomalyGauge
import InfoGeometry.Canonical.ArnoldMajoranaNetwork
import InfoGeometry.Canonical.ArnoldApproximationCore
import InfoGeometry.Canonical.NeuralOperatorCore
import InfoGeometry.Canonical.ArnoldNetworkPresentation
import InfoGeometry.Canonical.NavierStokesNeuralOperatorBridge
import InfoGeometry.Canonical.Attention
import InfoGeometry.Canonical.AttentionDiracBridge
import InfoGeometry.Canonical.AttentionEuclidean
import InfoGeometry.Canonical.AttentionSplit
import InfoGeometry.Canonical.AssociativeSuperBracket
import InfoGeometry.Canonical.BogoliubovFockSuper
import InfoGeometry.Canonical.BoundaryProjector
import InfoGeometry.Canonical.BottDirac
import InfoGeometry.Canonical.BottPeriodicity
import InfoGeometry.Canonical.BregmanTriality
import InfoGeometry.Canonical.CartanDecomposition
import InfoGeometry.Canonical.CayleyBregmanBridge
import InfoGeometry.Canonical.ChiralAnomaly
import InfoGeometry.Canonical.ChiralOperatorConeClosure
import InfoGeometry.Canonical.KKTConformalChiralContext
import InfoGeometry.Canonical.ChiralChargeFockNumberBridge
import InfoGeometry.Canonical.ChiralEinsteinBridge
import InfoGeometry.Canonical.ChiralGravity
import InfoGeometry.Canonical.ChiralRGFlow
import InfoGeometry.Canonical.Clifford
import InfoGeometry.Canonical.ClNNBottBridge
import InfoGeometry.Canonical.SplitCliffordHeadLift
import InfoGeometry.Canonical.SplitCliffordHeadEquivariance
import InfoGeometry.Canonical.ProjectorEquivariance
import InfoGeometry.Canonical.DilatedGapEquivariance
import InfoGeometry.Canonical.SplitCliffordHeadPhaseFlip
import InfoGeometry.Canonical.SplitCliffordHeadProjectors
import InfoGeometry.Canonical.SplitCliffordHeadSuperBracket
import InfoGeometry.Canonical.HyperbolicRotor
import InfoGeometry.Canonical.SplitCliffordTensorBridge
import InfoGeometry.Canonical.SplitCl44TKKJordanLieBridge
import InfoGeometry.Canonical.CliffordBridge
import InfoGeometry.Canonical.CurvatureRGFlow
import InfoGeometry.Core
import InfoGeometry.Core.Derivatives
import InfoGeometry.Core.DerivativesSmoke
import InfoGeometry.Core.Jordan
import InfoGeometry.Core.SymmetricLie
import InfoGeometry.Core.SymmetricLieGeneric
import InfoGeometry.Core.SymmetricSpaces
import InfoGeometry.Core.UnifiedGeometry
import InfoGeometry.Canonical.CertifiedInverseKernel
import InfoGeometry.Canonical.SignedParticleBridge
import InfoGeometry.Canonical.SouriauDensityWeightContext
import InfoGeometry.Canonical.SouriauConformalKKTContext
import InfoGeometry.Canonical.SouriauMetriplecticContext
import InfoGeometry.Canonical.SouriauKreinMetriplecticContext
import InfoGeometry.Canonical.SouriauFenchelOnsagerBridge
import InfoGeometry.Canonical.SouriauCoadjointOrbitMetriplecticTheorem
import InfoGeometry.Canonical.SuperSouriauFermionGasBridge
import InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge
import InfoGeometry.Canonical.CoordinatelessSouriauCocycleFisherBridge
import InfoGeometry.Canonical.SouriauLieThermoKKTBridge
import InfoGeometry.Canonical.SouriauTheoremTranslatorPacket
import InfoGeometry.Canonical.BulgarianThermodynamicGeometryPacket
import InfoGeometry.Canonical.BulgarianThermodynamicGeometryBridge
import InfoGeometry.Canonical.CasimirWeylDrazinContext

import InfoGeometry.Canonical.CoarseGraining
import InfoGeometry.Canonical.Determinant
import InfoGeometry.Canonical.Drazin
import InfoGeometry.Canonical.DiracSouriauOperator
import InfoGeometry.Canonical.DiracSouriauKKTChiralContext
import InfoGeometry.Canonical.DrazinExistenceBridge
import InfoGeometry.Canonical.DrazinInfiniteCore
import InfoGeometry.Canonical.DrazinWeylConstructive
import InfoGeometry.Canonical.ClosureDrazinBridge
import InfoGeometry.Canonical.DrazinWitnessElimination
import InfoGeometry.Canonical.DrazinKreinCompatibility
import InfoGeometry.Canonical.DrazinFredholmBridge
import InfoGeometry.Canonical.DrazinSpectralBridge
import InfoGeometry.Canonical.DrazinSpectralProjectorBridge
import InfoGeometry.Canonical.DrazinCoreFlow
import InfoGeometry.Canonical.DrazinPenroseDilationAlgebra
import InfoGeometry.Canonical.DrazinPenroseDilationKKT
import InfoGeometry.Canonical.DrazinSupercharge
import InfoGeometry.Canonical.Spin44CharacterShadow
import InfoGeometry.Canonical.TheoryShadowRepresentation
import InfoGeometry.Canonical.CertifiedModularReduction
import InfoGeometry.Canonical.ObserverDefect
import InfoGeometry.Canonical.ModularSourceBridge
import InfoGeometry.Canonical.ModularSurprisalThermoPacket
import InfoGeometry.Canonical.DrazinModularSingularityBridge
import InfoGeometry.Canonical.DrazinCentralChargeBridge
import InfoGeometry.Canonical.DrazinDescriptorSystems
import InfoGeometry.Canonical.InverseKernelAlgebra
import InfoGeometry.Canonical.InverseKernelCartanCore
import InfoGeometry.Canonical.InverseKernelNormalForm
import InfoGeometry.Canonical.LogGenerator
import InfoGeometry.Canonical.GeneratedFlow
import InfoGeometry.Canonical.LiteratureGrandCanonicalWeylTKK
import InfoGeometry.Canonical.LiteratureTwistorHodgePalatial
import InfoGeometry.Canonical.WeylGaugeField
import InfoGeometry.Canonical.WeylTransport
import InfoGeometry.Canonical.WeylCharacterVandermondeShadow
import InfoGeometry.Canonical.WeylAlternatingNumeratorShadow
import InfoGeometry.Canonical.WeylLocalCancellationShadow
import InfoGeometry.Canonical.WeylTwoNodeCancellationChart
import InfoGeometry.Canonical.WeylA2CancellationChart
import InfoGeometry.Canonical.WeylPolynomialDivisibilityShadow
import InfoGeometry.Canonical.WeylAntisymmetricDivisibilityShadow
import InfoGeometry.Canonical.WeylA2AlternatingDeterminantShadow
import InfoGeometry.Canonical.WeylA2ProductDivisibilityShadow
import InfoGeometry.Canonical.HestenesQVandermondeShadow
import InfoGeometry.Canonical.RiemannResonatorBridge
import InfoGeometry.Canonical.TopologicalGapShadow
import InfoGeometry.Canonical.SuperchargeHoppingBridge
import InfoGeometry.Canonical.SuperchargeOddOddDecomposition
import InfoGeometry.Canonical.UnifiedSuperchargeOddOddBridge
import InfoGeometry.Canonical.UnifiedTopologicalGapBridge
import InfoGeometry.Canonical.WeylTransportChiralBridge
import InfoGeometry.Canonical.MultiplicativeToAdditiveBridge
import InfoGeometry.Canonical.LogDetRadonNikodymMechanism
import InfoGeometry.Canonical.VolumeDeformationPrinciple
import InfoGeometry.Canonical.PartitionHierarchy
import InfoGeometry.Canonical.DualConnections
import InfoGeometry.Canonical.EmpiricalChecks
import InfoGeometry.Canonical.EPAndGroupInverse
import InfoGeometry.Canonical.EPDefectAlgebra
import InfoGeometry.Canonical.Fierz
import InfoGeometry.Canonical.FierzReadout
import InfoGeometry.Canonical.FierzStressProjectionBridge
import InfoGeometry.Canonical.FormalScaffold
import InfoGeometry.Canonical.Fock
import InfoGeometry.Canonical.Foundations
import InfoGeometry.Canonical.GaugeUnified
import InfoGeometry.Canonical.GaugeGroups
import InfoGeometry.Canonical.GaussianHolonomy
import InfoGeometry.Canonical.GeneralizedKL
import InfoGeometry.Canonical.GeneralizedMetricCore
import InfoGeometry.Canonical.GeneralizedMetricPolarizedBridge
import InfoGeometry.Canonical.GeneralizedMetricRecompositionBridge
import InfoGeometry.Canonical.Geometry
import InfoGeometry.Canonical.GrandCanonicalCore
import InfoGeometry.Canonical.GrandCanonicalGaugePotentialBridge
import InfoGeometry.Canonical.GrandCanonicalFockNumberBridge
import InfoGeometry.Canonical.GrandCanonicalExperts
import InfoGeometry.Canonical.GenerativeInferenceCore
import InfoGeometry.Canonical.PhysicsOfInformationCore
import InfoGeometry.Canonical.GrandUnification
import InfoGeometry.Canonical.GrandUnificationMetric
import InfoGeometry.Canonical.GrandCanonicalGaussianScaleShape
import InfoGeometry.Canonical.HeatKernel
import InfoGeometry.Canonical.IB
import InfoGeometry.Canonical.InformationNumber
import InfoGeometry.Canonical.InformationalLichnerowicz
import InfoGeometry.Canonical.InformationalLichnerowiczBottBridge
import InfoGeometry.Canonical.InformationTorsion
import InfoGeometry.Canonical.KKTCore
import InfoGeometry.Canonical.KKTLorentzOrbitBridge
import InfoGeometry.Canonical.Cl11LorentzAction
import InfoGeometry.Canonical.KKTGeneralizedInverseBridge
import InfoGeometry.Canonical.KKTGeneralizedMetricBridge
import InfoGeometry.Canonical.KKTNoetherCharges
import InfoGeometry.Canonical.KKTClosureSymmetry
import InfoGeometry.Canonical.KKFoundation
import InfoGeometry.Canonical.SuperchargeGapBridge
import InfoGeometry.Canonical.SuperchargeRoleBridge
import InfoGeometry.Canonical.SuperchargeTransportBridge

import InfoGeometry.Canonical.SuperchargeCARCCRBridge
import InfoGeometry.Canonical.SuperchargeGapHessianBridge
import InfoGeometry.Canonical.SuperchargeCentralChargeClosure
import InfoGeometry.Canonical.ModularSuperchargeClosure
import InfoGeometry.Canonical.ComplexMaskTransmutationBridge
import InfoGeometry.Canonical.UnifiedSuperchargeAlgebra
import InfoGeometry.Canonical.MajoranaLiftPacketBridge
import InfoGeometry.Canonical.ChiralHodgeDecomposition
import InfoGeometry.Canonical.ChiralHodgeLichnerowiczBridge
import InfoGeometry.Canonical.ChiralHodgeIndexBridge
import InfoGeometry.Canonical.TwistorHodgePalatialBridge
import InfoGeometry.Canonical.ChiralDefectIndexBridge
import InfoGeometry.Canonical.BoundaryChiralIndexBridge
import InfoGeometry.Canonical.SuperchargeEinsteinSourceBridge
import InfoGeometry.Canonical.BoundaryLocalizationIndexEquiv
import InfoGeometry.Canonical.CentralChargeKKTParityBridge
import InfoGeometry.Canonical.SuperJordanLie
import InfoGeometry.Canonical.VortexAnomalyLink
import InfoGeometry.Canonical.VandermondeExclusionBridge
import InfoGeometry.Canonical.SpinConnection
import InfoGeometry.Canonical.TransportLieDerivative
import InfoGeometry.Canonical.SuperAnomaly
import InfoGeometry.KL.EntropicInferenceTest
import InfoGeometry.SLT.ConditionalExpectation
import InfoGeometry.TransformationGroups
import InfoGeometry.Canonical.KMSSinkhornBridge
import InfoGeometry.Canonical.SinkhornGaugeThermodynamicsBridge
import InfoGeometry.Canonical.KMSCocycleGeneratorBridge
import InfoGeometry.Canonical.KreinDoubledAtom
import InfoGeometry.Canonical.KLinearRepresentation
import InfoGeometry.Canonical.PolarizedMadelungBridge
import InfoGeometry.Canonical.BohmMadelungOperatorialBridge
import InfoGeometry.Canonical.BogoliubovTransport
import InfoGeometry.Canonical.BogoliubovWeightedKMSCertification
import InfoGeometry.Canonical.BogoliubovOptimalTransport
import InfoGeometry.Canonical.PositiveMeasureSpectrum
import InfoGeometry.Canonical.UhlmannBuresHolonomy
import InfoGeometry.Canonical.BogoliubovClosedForms
import InfoGeometry.Canonical.BogoliubovProjectorTransport
import InfoGeometry.Canonical.BogoliubovProjectorFlux
import InfoGeometry.Canonical.OperatorDictionary
import InfoGeometry.Canonical.QuantumPresentation
import InfoGeometry.Canonical.GraphDiracPresentation
import InfoGeometry.Canonical.ArnoldNetworkPresentation
import InfoGeometry.Canonical.ArnoldNetworkIntertwiner
import InfoGeometry.Canonical.ModularOrientationContract
import InfoGeometry.Canonical.RealTomitaCore
import InfoGeometry.Canonical.SouriauTomitaModularFlowBridge
import InfoGeometry.Canonical.ModularSpectralWedge
import InfoGeometry.Canonical.ModularSpectralWedgeBridge
import InfoGeometry.Canonical.ModularSpectralConjugationBridge
import InfoGeometry.Canonical.DPDWedgeCompatibility
import InfoGeometry.Canonical.WedgeBoostModularBridge
import InfoGeometry.Canonical.TypeIIIContinuousCoreReal
import InfoGeometry.Canonical.TypeIIILambdaCore
import InfoGeometry.Canonical.PedersenTakesakiRNInterface
import InfoGeometry.Canonical.ConnesCocycleDeltaPrimaryBridge
import InfoGeometry.Canonical.OperatorLightconeCoordinates
import InfoGeometry.Canonical.DiscreteModularSpectrum
import InfoGeometry.Canonical.DiscreteMellinModularBridge
import InfoGeometry.Canonical.DiscreteModularMellinShift
import InfoGeometry.Canonical.OperatorSpacetimeObservables
import InfoGeometry.Canonical.KaehlerGeometry
import InfoGeometry.Canonical.JaynesRNMaxEnt
import InfoGeometry.Canonical.JaynesRNModularBridge
import InfoGeometry.Canonical.Krein
import InfoGeometry.Canonical.KreinLadder
import InfoGeometry.LLM
import InfoGeometry.LLM.MaskedTransformerBlock
import InfoGeometry.LLM.TransformerBlock
import InfoGeometry.Canonical.LLN
import InfoGeometry.Canonical.LogSumExp
import InfoGeometry.Canonical.LogSpineBridge
import InfoGeometry.Canonical.LorentzianRouting
import InfoGeometry.Canonical.ManifoldDegree
import InfoGeometry.Canonical.ManifoldHomology
import InfoGeometry.Canonical.ManifoldDegreeIntegration
import InfoGeometry.Canonical.MajoranaKitaevSpinorBridge
import InfoGeometry.Canonical.HestenesKramersBridge
import InfoGeometry.Canonical.HestenesRealStructures
import InfoGeometry.Canonical.TimeReversalKramers
import InfoGeometry.Canonical.KramersPhaseAxisReduction
import InfoGeometry.Canonical.ModularKramersBridge
import InfoGeometry.Canonical.ModularHamiltonianDoubledBridge
import InfoGeometry.Canonical.ModularHamiltonianPregSupportBridge
import InfoGeometry.Canonical.KramersMajoranaCompatibility
import InfoGeometry.Canonical.KramersSuperchargeBridge
import InfoGeometry.Canonical.MixtureOfExperts
import InfoGeometry.Canonical.SpinorModularBridge
import InfoGeometry.Canonical.ModularTwoStateCorrelation
import InfoGeometry.Canonical.CorrelationSymmetrization
import InfoGeometry.Canonical.CorrelationAntisymmetrization
import InfoGeometry.Canonical.CoordinateFreeSecondVariation
import InfoGeometry.Canonical.OnsagerCasimirJ
import InfoGeometry.Canonical.SpectroscopicGaugeKMSBridge
import InfoGeometry.Canonical.StateIndexedModularSeedBridge
import InfoGeometry.Canonical.SpectroscopicGauge
import InfoGeometry.Canonical.NoetherInference
import InfoGeometry.Canonical.NoetherRelationalBridge
import InfoGeometry.Canonical.OperatorialHessianBridge
import InfoGeometry.Canonical.ModularHessian
import InfoGeometry.Canonical.FisherVolumeBridge
import InfoGeometry.Canonical.PhaseVolumeDynamics
import InfoGeometry.Canonical.PhaseAxisCartanSymmetricLie
import InfoGeometry.Canonical.VariationalLadder
import InfoGeometry.Canonical.TopologicalResidue
import InfoGeometry.Canonical.OnsagerReciprocity
import InfoGeometry.Canonical.OnsagerSpineBridge
import InfoGeometry.Canonical.OnsagerSinkhornOperatorLift
import InfoGeometry.Canonical.OperatorialCentralCharge
import InfoGeometry.Canonical.CentralChargeAnomaly
import InfoGeometry.Canonical.OperatorialCramerRao
import InfoGeometry.Canonical.OperatorPartitionSupervolumeBridge
import InfoGeometry.Canonical.OperatorialCramerRaoStateFirstChunk1
import InfoGeometry.Canonical.OperatorialCramerRaoStateFirstChunk2
import InfoGeometry.Canonical.OperatorialCramerRaoStateFirstChunk3
import InfoGeometry.Canonical.OperatorialCramerRaoStateFirstChunk4
import InfoGeometry.Canonical.OperatorialCramerRaoStateFirstSemanticAudit
import InfoGeometry.Canonical.OperatorialUncertainty
import InfoGeometry.Canonical.PathIntegral
import InfoGeometry.Canonical.HestenesGibbsPathIntegral
import InfoGeometry.Canonical.PhaseSpaceRecompositionExample
import InfoGeometry.Canonical.Prequantum
import InfoGeometry.Canonical.Projective
import InfoGeometry.Canonical.ProjectiveSplitQ11Realization
import InfoGeometry.Canonical.ProjectiveSectorDecomposition
import InfoGeometry.Canonical.ProjectiveAlgebraComparison
import InfoGeometry.Canonical.RelativeModularCore
import InfoGeometry.Canonical.RelativeModularPotential
import InfoGeometry.Canonical.QuantumLieAlgebroidRosetta
import InfoGeometry.Canonical.CanonicalGaugeBridge
import InfoGeometry.Canonical.ReferenceSectorGaugeBridge
import InfoGeometry.Canonical.VortexReferenceGaugeBridge
import InfoGeometry.Canonical.WeightedWeylNormalizationBridge
import InfoGeometry.Canonical.SouriauPlanckVector
import InfoGeometry.Canonical.SouriauFlowCliffordBridge
import InfoGeometry.Canonical.SouriauThermodynamics
import InfoGeometry.Canonical.ThermodynamicAction
import InfoGeometry.Canonical.ThermodynamicGenerator
import InfoGeometry.Canonical.OperatorSuperKaehlerLift
import InfoGeometry.Canonical.MajoranaKreinCartanSplit
import InfoGeometry.Canonical.RelativeModularPolarizedBridge
import InfoGeometry.Canonical.RelativeModularProjectiveBridge
import InfoGeometry.Canonical.ModularKLDivergenceBridge
import InfoGeometry.Canonical.RelativeModularScaleShapeSplit
import InfoGeometry.Canonical.ThermodynamicClosureTargets
import InfoGeometry.Canonical.OddDefectFunctional
import InfoGeometry.Canonical.OperatorFenchelRegularCone
import InfoGeometry.Canonical.GlobalChiralDecomposition
import InfoGeometry.Canonical.SingularDecompositionSurrogate
import InfoGeometry.Canonical.CapstoneSemanticAudit
import InfoGeometry.Canonical.OperatorialVolumePreservation
import InfoGeometry.Canonical.RelativeModularRecomposition
import InfoGeometry.Canonical.RobustThermodynamicRegression
import InfoGeometry.Canonical.Quantum
import InfoGeometry.Canonical.QuantumInference
import InfoGeometry.Canonical.QFTTDFTLaunchpad
import InfoGeometry.Canonical.RGFlow
import InfoGeometry.Canonical.RicciMongeAmpere
import InfoGeometry.Canonical.MongeAmpereCramerRao
import InfoGeometry.Canonical.IncompressibleBitBridge
import InfoGeometry.Canonical.IncompressibleCramerRaoActionBridge
import InfoGeometry.Canonical.MongeAmpereDualSheetBridge
import InfoGeometry.Canonical.QuantumGeometryDualSheetBridge
import InfoGeometry.Canonical.RestrictedSheetContinuous
import InfoGeometry.Canonical.RestrictedVolumeCharacter
import InfoGeometry.Canonical.WeylGaugeOperatorLift
import InfoGeometry.Canonical.WeylKKTAnomalyIdentity
import InfoGeometry.Canonical.RealBdG
import InfoGeometry.Canonical.DIIICommutatorInitialization
import InfoGeometry.Canonical.RealBdGDIIIAtom
import InfoGeometry.Canonical.RealBdGSheetBridge
import InfoGeometry.Canonical.SpectralInference
import InfoGeometry.Canonical.StandardFormCore
import InfoGeometry.Canonical.TomitaTakesakiRealStandardForm
import InfoGeometry.Canonical.SingularBoundaryCorrection
import InfoGeometry.Canonical.CalabiYauSingularBridge
import InfoGeometry.Canonical.SingularTransportSystem
import InfoGeometry.Canonical.Statistics
import InfoGeometry.Canonical.SuperInference
import InfoGeometry.Canonical.Thermo
import InfoGeometry.Canonical.ThermoFromLogDet
import InfoGeometry.Canonical.TomitaTakesaki
import InfoGeometry.Canonical.TopologicalEuler
import InfoGeometry.Canonical.TopologicalInvariants
import InfoGeometry.Canonical.TopologicalInvariantInvariance
import InfoGeometry.Canonical.Triality
import InfoGeometry.Canonical.HeadTrialityCore
import InfoGeometry.Canonical.Twistor
import InfoGeometry.Canonical.Unification
import InfoGeometry.Canonical.OperatorPenroseUnification
import InfoGeometry.PositiveMeasure
import InfoGeometry.Quantum.BulkBoundaryIndexBridge
import InfoGeometry.Canonical.BulkBoundaryRegularizationBridge
import InfoGeometry.Quantum.ModularAnomaly
import InfoGeometry.Quantum.TriadicTransportCore
import InfoGeometry.Quantum.TriadicTransportProjective
import InfoGeometry.Quantum.TriadicTransportBarycenter
import InfoGeometry.Quantum.TriadicTransportModular
import InfoGeometry.Quantum.TriadicBogoliubovBridge
import InfoGeometry.Quantum.TriadicWeylBridge
import InfoGeometry.Volume.RadonNikodym
import InfoGeometry.Volume.LogPotential
import InfoGeometry.Volume.Pfaffian

-- Stable declaration-bearing canonical owners previously outside the umbrella coverage.
import InfoGeometry.Canonical.AQFTHilbertCompression
import InfoGeometry.Canonical.AQFTOperatorEndpoints
import InfoGeometry.Canonical.AQFTOperatorSignatures
import InfoGeometry.Canonical.AQFTReadiness
import InfoGeometry.Canonical.BerryConnection
import InfoGeometry.Canonical.BeliefAlgebra
import InfoGeometry.Canonical.CartanBerezinianCore
import InfoGeometry.Canonical.CalabiYauRNMongeAmpere
import InfoGeometry.Canonical.CalabiYauWBridge
import InfoGeometry.Canonical.ChiralTorsionGeneralizedKL
import InfoGeometry.Canonical.ChiralTorsionState
import InfoGeometry.Canonical.ChiralTorsionTwistor
import InfoGeometry.Canonical.ConnesArakiCore
import InfoGeometry.Canonical.ConnesArakiTomita
import InfoGeometry.Canonical.CountPositiveCoupling
import InfoGeometry.Canonical.CountProbabilityState
import InfoGeometry.Canonical.CountSinkhornFlow
import InfoGeometry.Canonical.GrandSynthesisBott
import InfoGeometry.Canonical.GrandSynthesisGeometry
import InfoGeometry.Canonical.GrandSynthesisSingular
import InfoGeometry.Canonical.GrandSynthesisThermo
import InfoGeometry.Canonical.OperatorAlgebraAQFTPackage
import InfoGeometry.Canonical.OperatorAlgebraKKBridge
import InfoGeometry.Canonical.OperatorAlgebraModularAtom
import InfoGeometry.Canonical.OperatorAlgebraReadiness
import InfoGeometry.Canonical.RelationalInformationCore
import InfoGeometry.Canonical.RelationalInformationDynamics
import InfoGeometry.Canonical.ResponseWeylAnomalyBridge
import InfoGeometry.Canonical.RosettaScaleTransport
import InfoGeometry.Canonical.WeylPathHysteresis
import InfoGeometry.Canonical.YangMillsFiniteBridge
import InfoGeometry.Canonical.YangMillsFiniteQFT

-- Stable depth ladder for the count/projective/operator/Krein/transport/attention spine.
-- L0: count / relative-volume substrate
import InfoGeometry.Canonical.RelativePotentialCountBridge
import InfoGeometry.Canonical.ModularVolumeDeformationBridge

-- L1: projective / gauge / scalar modular-potential layer
import InfoGeometry.Canonical.PositiveRayCore
import InfoGeometry.Canonical.RelativePotentialCore
import InfoGeometry.Canonical.RelativePotentialDiscreteBridge
import InfoGeometry.Canonical.RelativePotentialScalarBridge
import InfoGeometry.Projective.Normalize

-- L2: diagonal operator lift and partition calculus
import InfoGeometry.Canonical.InformationPartitionCore
import InfoGeometry.Canonical.RelativeModularOperator
import InfoGeometry.Canonical.RelativeModularHamiltonian
import InfoGeometry.Canonical.RelativeModularHamiltonianSupport
import InfoGeometry.Canonical.RelativeModularCommutingLift
import InfoGeometry.Canonical.RNDeterminantConnesChainBridge
import InfoGeometry.Canonical.RelativeModularBoundedCommutingInterface
import InfoGeometry.Canonical.RelativeModularSingularization
import InfoGeometry.Canonical.RelativeSurprisalOperatorLift
import InfoGeometry.Canonical.FirstQuantizationProbability
import InfoGeometry.Canonical.ModularWeldBridge

-- L3: spectral / metric coherence on the doubled carrier
import InfoGeometry.Canonical.DiagonalMetricModularBridge
import InfoGeometry.Canonical.RelativeModularBerezinianBridge
import InfoGeometry.Canonical.KreinDiracPolarizationBridge

-- L4: transported/Bogoliubov presentation
import InfoGeometry.Canonical.BogoliubovPolarizationBridge
import InfoGeometry.Canonical.KreinDiracSpectralLift
import InfoGeometry.Canonical.KreinDiracWeightFunctionalLift
import InfoGeometry.Canonical.SplitCliffordThermalBridge
import InfoGeometry.Canonical.OperatorialInformationLift
import InfoGeometry.Canonical.Operators
import InfoGeometry.Canonical.OperatorThermoBridge
import InfoGeometry.Canonical.OperatorialFierzBridge

-- L5: thermodynamic / attention surface
import InfoGeometry.Canonical.AttentionPolarizedSplit
import InfoGeometry.Canonical.AttentionPolarizedGibbsBridge
import InfoGeometry.Canonical.AttentionPolarizedSinkhornBridge

namespace InfoGeometry

/-!
# InfoGeometry.Canonical.All

Stable umbrella import for the canonical publication surface.

This file intentionally excludes modules listed in
`scripts/quality/quarantine_manifest.txt`. Quarantined synthesis/facade layers
must be imported explicitly from their owner modules while they remain on the
review surface.

This file is still only an import aggregator, not an authoritative description
of the current theory graph. For current repository state and workflow, prefer:
- `README.md`
- `docs/README.md`
- `lean/DAG/README.md`
- `tools/README.md`

Conceptual notes under `docs/` are orientation aids only. Exact ownership,
theorem names, and file boundaries must be checked against the current owner
modules in `lean/InfoGeometry/Canonical/`.
-/

end InfoGeometry
