import InfoGeometry.Canonical.BerryConnection
import InfoGeometry.Canonical.TopologicalInvariants

set_option linter.unusedSectionVars false

namespace InfoGeometry.Canonical.BerryPhase

open InfoGeometry.Canonical.BogoliubovTransport
open InfoGeometry.Canonical.WeylGaugeOperatorLift
open InfoGeometry.Krein
open InfoGeometry.Quantum
open InfoGeometry.Canonical.TopologicalInvariants
open InfoGeometry.Canonical.MoorePenrose
open InfoGeometry.Canonical.SpectralInference
open scoped InnerProductSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
  [FiniteDimensional ℝ E]

local notation "H₂" => DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂

/--
Hestenes-phase readout on doubled real space:
evaluate the operatorial Berry 2-form generated by the modular connection.
-/
noncomputable def hestenesBerryPhaseReadout
    (hMod A : EndH) (u v : H₂) : ℝ :=
  hestenesBerryTwoForm hMod A u v

/--
Combined Weyl/modular Hestenes-phase readout on doubled real space.
-/
noncomputable def hestenesWeylModularBerryPhaseReadout
    (g : LiftedSheetAut (E := E)) (hMod A : EndH) (u v : H₂) : ℝ :=
  hestenesWeylModularBerryTwoForm g hMod A u v

/--
Gauge-resolved Hestenes-phase source law:
when the modular gauge part commutes with the transported seed, the combined
Weyl/modular Berry readout is Weyl plus source channel.
-/
theorem hestenesWeylModularBerryPhaseReadout_eq_berryOf_hestenesWeylConnectionGenerator_add_relativeModularSourceDeriv_of_commute_gaugePart
    (g : LiftedSheetAut (E := E)) (hMod A : EndH)
    (hCommGauge : Commute A (modularGeneratorGaugePart (E := E) hMod))
    (u v : H₂) :
    hestenesWeylModularBerryPhaseReadout g hMod A u v
      =
    GeometricQuantumTensor.berryOfOperator
      (E := E)
      (hestenesWeylConnectionGenerator g A
        + relativeModularSourceDeriv (E := E) hMod A) u v := by
  simpa [hestenesWeylModularBerryPhaseReadout] using
    hestenesWeylModularBerryTwoForm_eq_berryOf_hestenesWeylConnectionGenerator_add_relativeModularSourceDeriv_of_commute_gaugePart
      g hMod A hCommGauge u v

/--
The Information Berry Phase `γ`.
Accumulated by the belief state when transported around a periodic path.
-/
noncomputable def informationBerryPhase (L : BayesianLoop E) (CST : ChiralSpectralTriple E) : ℝ :=
  (L.N : ℝ) * chiralAnomalyIndex CST

/-- Expanded form: Berry phase equals loop length times the chiral anomaly index. -/
theorem informationBerryPhase_eq_loopLength_mul_chiralAnomalyIndex
    (L : BayesianLoop E) (CST : ChiralSpectralTriple E) :
    informationBerryPhase L CST = (L.N : ℝ) * chiralAnomalyIndex CST := by
  rfl

/-- Expanded form: Berry phase equals loop length times `ε` times spectral projector rank. -/
theorem informationBerryPhase_eq_loopLength_mul_epsilon_mul_rank
    (L : BayesianLoop E) (CST : ChiralSpectralTriple E) :
    informationBerryPhase L CST
      = (L.N : ℝ) * CST.epsilon *
          (Module.finrank ℝ
            (LinearMap.range
              (InfoGeometry.Canonical.Drazin.IsDrazinInverse.projection CST.D CST.DD).toLinearMap) : ℝ) := by
  simp [informationBerryPhase, chiralAnomalyIndex, mul_assoc]

/-- Nonzero loop length and anomaly index force nonzero Berry phase. -/
theorem informationBerryPhase_ne_zero_of_loopLength_ne_zero_of_chiralAnomalyIndex_ne_zero
    (L : BayesianLoop E) (CST : ChiralSpectralTriple E)
    (hLoop : (L.N : ℝ) ≠ 0)
    (hIdx : chiralAnomalyIndex CST ≠ 0) :
    informationBerryPhase L CST ≠ 0 := by
  simpa [informationBerryPhase] using mul_ne_zero hLoop hIdx

omit [FiniteDimensional ℝ E] in
/-- The Berry phase vanishes on normal belief manifolds. -/
theorem berry_phase_vanishes_for_normal (L : BayesianLoop E) (CST : ChiralSpectralTriple E)
    (h_normal : chiralScale CST.D CST.DD CST.DP = 0) :
    informationBerryPhase L CST = 0 := by
  simp [informationBerryPhase, chiralAnomalyIndex, ChiralSpectralTriple.epsilon, h_normal]

end InfoGeometry.Canonical.BerryPhase
