import InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge

/-!
# Transitive axiom inspection for the Cartan--Pauli--Zorn realification bridge

These commands inspect the elaborated declarations after Lean builds the bridge.
An acceptable result contains only the standard logical axioms used by Mathlib,
or no axioms; any `sorryAx` or custom axiom is a failure.
-/

#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.cartanComplexLine_injective
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.cartanRealPlane_injective
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.cartanRealPlane_half_coordinates
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.Kboost_Kcirc_real_linear_independent
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.Kboost_Kcirc_complex_dependence
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.logarithmicCartanGenerator_eq_cartanRealPlane
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.logarithmicCartanGenerator_eq_cartanComplexLine
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedKcirc_eq_complexStructure_mul_realifiedKboost
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedKboost_Kcirc_commute
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedLogarithmicCartanGenerator_complexStructure_split
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedLogarithmicCartanGenerator_commutes_complexStructure
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedHalfLogLift_mul_inv
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedHalfLogLift_inv_mul
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.bipolarPauliAction_det
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.bipolarPauliAction_det_eq_minkowski
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.circularWittQuadratic_eq_bipolarPauliAction_det
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedBipolarPauliAction_factorization
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.realifiedBipolarPauliAction_commutes_complexStructure
#print axioms InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge.bipolar_cartan_pauli_zorn_realification_packet
