import InfoGeometry.Canonical.BipolarLogarithmicDerivationBridge
import InfoGeometry.Canonical.BipolarCartanLorentzBridge
import InfoGeometry.Canonical.Cl11JordanComplexRealificationBridge
import InfoGeometry.Geometry.PauliParavectorBridge
import InfoGeometry.Lie.SplitOctonionCircularMinkowskiPauliBridge
import Mathlib.Tactic

/-!
# Bipolar Cartan, Pauli, Zorn, and realification bridge

This file isolates the exact finite algebra hidden in the informal chain

`complex Cartan → Pauli/Minkowski → split-octonion Witt slice → real carrier`.

The two named generators

`Kboost = sigma3 / 2`, `Kcirc = I sigma3 / 2`

are linearly independent over `ℝ` but lie on one line over `ℂ`.  The existing
ring realification of `M₂(ℂ)` then sends scalar multiplication by `I` to a
concrete real complex structure whose square is `-1`.  This gives a genuine
real model of the complex Cartan line without identifying it with the distinct
noncommuting clock/Krein axes on `ℝ^2`.

The spacetime branch uses the repository-owned Hermitian Pauli soldering.  Its
determinant is the Minkowski quadratic form, and the existing diagonal
embedding into the split-octonion circular Witt carrier has the same quadratic
readout.  The bipolar `SL₂(ℂ)` action preserves this determinant.

No full biquaternion classification, `Cl(1,3)` grade equivalence, octonion
algebra homomorphism, `G₂(2)` action, Dirac spinor construction, or Nambu--Krein
functor is asserted here.  Those require additional concrete carriers and
intertwining theorems.
-/

noncomputable section

namespace InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge

open InfoGeometry.Analysis.BipolarCrossRatioLog
open InfoGeometry.Canonical.BipolarLogSL2
open InfoGeometry.Canonical.BipolarCartanLorentzBridge
open InfoGeometry.Canonical.BipolarTwoSheetOperatorConnectionBridge
open InfoGeometry.Canonical.BipolarLogarithmicDerivationBridge
open InfoGeometry.Canonical.MatrixStageLorentzKANSoldering
open InfoGeometry.Canonical.Cl11JordanComplexRealificationBridge
open InfoGeometry.Geometry.PauliParavectorBridge
open InfoGeometry.Lie.SplitOctonionCircularWittForm
open InfoGeometry.Lie.SplitOctonionCircularMinkowskiPauliBridge
open InfoGeometry.Physics.ChiralCausalCone

abbrev CartanRealCoordinates := Fin 2 → ℝ
abbrev CartanMatrix := Matrix (Fin 2) (Fin 2) ℂ
abbrev RealifiedCartanMatrix := Matrix (Fin 4) (Fin 4) ℝ
abbrev SpacetimeVector := InfoGeometry.Geometry.PauliParavectorBridge.Minkowski4

/-- The one-dimensional complex Cartan line generated by `sigma3`. -/
noncomputable def cartanComplexLine : ℂ →ₗ[ℂ] CartanMatrix where
  toFun z := z • σ3c
  map_add' z w := by
    simpa using add_smul z w σ3c
  map_smul' z w := by
    simp [smul_smul]

/-- The same complex line regarded as a two-dimensional real plane with
coordinates `(boost, circular)`. -/
noncomputable def cartanRealPlane :
    CartanRealCoordinates →ₗ[ℝ] CartanMatrix where
  toFun a := ((a 0 : ℂ) + (a 1 : ℂ) * Complex.I) • σ3c
  map_add' a b := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [σ3c, Matrix.smul_apply] <;>
      push_cast <;>
      ring
  map_smul' r a := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [σ3c, Matrix.smul_apply, smul_smul] <;>
      push_cast <;>
      ring

@[simp] theorem cartanComplexLine_apply (z : ℂ) :
    cartanComplexLine z = z • σ3c := rfl

@[simp] theorem cartanRealPlane_apply (a : CartanRealCoordinates) :
    cartanRealPlane a = ((a 0 : ℂ) + (a 1 : ℂ) * Complex.I) • σ3c := rfl

/-- Forgetting the real coordinate pair recovers the single complex
coefficient exactly. -/
theorem cartanRealPlane_eq_complexLine (a : CartanRealCoordinates) :
    cartanRealPlane a =
      cartanComplexLine ((a 0 : ℂ) + (a 1 : ℂ) * Complex.I) := rfl

/-- The complex Cartan parameterization is injective. -/
theorem cartanComplexLine_injective :
    Function.Injective cartanComplexLine := by
  intro z w h
  have h00 := congrArg (fun A : CartanMatrix => A 0 0) h
  simpa [cartanComplexLine, σ3c, Matrix.smul_apply] using h00

/-- The underlying real plane really has two independent coordinates. -/
theorem cartanRealPlane_injective :
    Function.Injective cartanRealPlane := by
  intro a b h
  have h00 := congrArg (fun A : CartanMatrix => A 0 0) h
  have hcoord :
      (a 0 : ℂ) + (a 1 : ℂ) * Complex.I =
        (b 0 : ℂ) + (b 1 : ℂ) * Complex.I := by
    simpa [cartanRealPlane, σ3c, Matrix.smul_apply] using h00
  have h0 : a 0 = b 0 := by
    simpa [Complex.mul_re, Complex.mul_im] using congrArg Complex.re hcoord
  have h1 : a 1 = b 1 := by
    simpa [Complex.mul_re, Complex.mul_im] using congrArg Complex.im hcoord
  funext i
  fin_cases i
  · exact h0
  · exact h1

/-- Half-scaled real Cartan coordinates are exactly the named boost and
circular generators. -/
theorem cartanRealPlane_half_coordinates (a b : ℝ) :
    cartanRealPlane ![a / 2, b / 2] =
      (a : ℂ) • Kboost + (b : ℂ) • Kcirc := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [cartanRealPlane, Kboost, Kcirc, σ3c, Matrix.smul_apply] <;>
    push_cast <;>
    ring

/-- The named generators are independent over the real scalars. -/
theorem Kboost_Kcirc_real_linear_independent
    (a b : ℝ)
    (h : (a : ℂ) • Kboost + (b : ℂ) • Kcirc = 0) :
    a = 0 ∧ b = 0 := by
  have hplane :
      cartanRealPlane ![a / 2, b / 2] = cartanRealPlane 0 := by
    rw [cartanRealPlane_half_coordinates, h]
    simp
  have hcoords := cartanRealPlane_injective hplane
  have h0 := congrFun hcoords 0
  have h1 := congrFun hcoords 1
  simp at h0 h1
  exact ⟨by linarith, by linarith⟩

/-- The same two real generators are dependent over `ℂ`: they span one complex
Cartan line. -/
theorem Kboost_Kcirc_complex_dependence :
    Kcirc = Complex.I • Kboost :=
  Kcirc_eq_I_smul_Kboost

/-- The bipolar logarithmic generator is the real-plane point with coordinates
`(eta/2, theta/2)`. -/
theorem logarithmicCartanGenerator_eq_cartanRealPlane (s : ℂ) :
    logarithmicCartanGenerator s =
      cartanRealPlane ![eta s / 2, theta s / 2] := by
  rw [logarithmicCartanGenerator_eq_half_bipolarLog_sigma3,
    bipolarLog_split]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [cartanRealPlane, σ3c, Matrix.smul_apply] <;>
    push_cast <;>
    ring

/-- The same generator is a single point on the complex Cartan line. -/
theorem logarithmicCartanGenerator_eq_cartanComplexLine (s : ℂ) :
    logarithmicCartanGenerator s =
      cartanComplexLine (bipolarLog s / 2) := by
  simpa [cartanComplexLine] using
    logarithmicCartanGenerator_eq_half_bipolarLog_sigma3 s

/-- Realification of the noncompact Cartan generator. -/
noncomputable def realifiedKboost : RealifiedCartanMatrix :=
  realify Kboost

/-- Realification of the compact Cartan generator. -/
noncomputable def realifiedKcirc : RealifiedCartanMatrix :=
  realify Kcirc

/-- Realification of the point-dependent logarithmic Cartan generator. -/
noncomputable def realifiedLogarithmicCartanGenerator
    (s : ℂ) : RealifiedCartanMatrix :=
  realify (logarithmicCartanGenerator s)

/-- Realification turns scalar multiplication by `I` into multiplication by the
repository-owned real complex structure. -/
theorem realifiedKcirc_eq_complexStructure_mul_realifiedKboost :
    realifiedKcirc = complexStructure * realifiedKboost := by
  calc
    realifiedKcirc = realify (Complex.I • Kboost) := by
      unfold realifiedKcirc
      rw [Kcirc_eq_I_smul_Kboost]
    _ = realify (((Complex.I : ℂ) • (1 : CartanMatrix)) * Kboost) := by
      congr 1
      ext i j
      fin_cases i <;> fin_cases j <;>
        simp [Kboost, σ3c, Matrix.mul_apply, Fin.sum_univ_two,
          Matrix.smul_apply]
    _ = realify ((Complex.I : ℂ) • (1 : CartanMatrix)) * realify Kboost := by
      rw [realify_mul]
    _ = complexStructure * realifiedKboost := rfl

/-- The real complex structure commutes with the realified Cartan line. -/
theorem realifiedKboost_commutes_complexStructure :
    realifiedKboost * complexStructure =
      complexStructure * realifiedKboost := by
  simpa [realifiedKboost] using realify_commutes_complexStructure Kboost

/-- Equivalent right-multiplication form of the compact generator. -/
theorem realifiedKcirc_eq_realifiedKboost_mul_complexStructure :
    realifiedKcirc = realifiedKboost * complexStructure := by
  calc
    realifiedKcirc = complexStructure * realifiedKboost :=
      realifiedKcirc_eq_complexStructure_mul_realifiedKboost
    _ = realifiedKboost * complexStructure :=
      realifiedKboost_commutes_complexStructure.symm

/-- Realification preserves commutativity of the two Cartan generators. -/
theorem realifiedKboost_Kcirc_commute :
    realifiedKboost * realifiedKcirc =
      realifiedKcirc * realifiedKboost := by
  have hcomm : Kboost * Kcirc = Kcirc * Kboost :=
    sub_eq_zero.mp Kboost_Kcirc_commute
  calc
    realifiedKboost * realifiedKcirc = realify (Kboost * Kcirc) := by
      simpa [realifiedKboost, realifiedKcirc] using
        (realify_mul Kboost Kcirc).symm
    _ = realify (Kcirc * Kboost) := by rw [hcomm]
    _ = realifiedKcirc * realifiedKboost := by
      simpa [realifiedKboost, realifiedKcirc] using
        realify_mul Kcirc Kboost

/-- Real scalar coordinates pass through realification without changing the
Cartan decomposition. -/
theorem realifiedLogarithmicCartanGenerator_split (s : ℂ) :
    realifiedLogarithmicCartanGenerator s =
      eta s • realifiedKboost + theta s • realifiedKcirc := by
  unfold realifiedLogarithmicCartanGenerator realifiedKboost realifiedKcirc
  rw [logarithmicCartanGenerator, realify_add,
    realify_real_smul, realify_real_smul]

/-- Intrinsically real form of `eta + I theta`: the real complex structure
supplies the circular direction. -/
theorem realifiedLogarithmicCartanGenerator_complexStructure_split (s : ℂ) :
    realifiedLogarithmicCartanGenerator s =
      eta s • realifiedKboost +
        theta s • (complexStructure * realifiedKboost) := by
  rw [realifiedLogarithmicCartanGenerator_split,
    realifiedKcirc_eq_complexStructure_mul_realifiedKboost]

/-- Every realified logarithmic Cartan generator belongs to the commutant of the
real complex structure. -/
theorem realifiedLogarithmicCartanGenerator_commutes_complexStructure
    (s : ℂ) :
    realifiedLogarithmicCartanGenerator s * complexStructure =
      complexStructure * realifiedLogarithmicCartanGenerator s := by
  simpa [realifiedLogarithmicCartanGenerator] using
    realify_commutes_complexStructure (logarithmicCartanGenerator s)

/-- Realification of the finite half-log lift. -/
noncomputable def realifiedHalfLogLift (s : ℂ) : RealifiedCartanMatrix :=
  realify (halfLogLift s)

/-- Realification of its explicit inverse. -/
noncomputable def realifiedHalfLogLiftInv (s : ℂ) : RealifiedCartanMatrix :=
  realify (halfLogLiftInv s)

/-- The realified lift has the realified explicit inverse on the right. -/
theorem realifiedHalfLogLift_mul_inv (s : ℂ) :
    realifiedHalfLogLift s * realifiedHalfLogLiftInv s = 1 := by
  calc
    realifiedHalfLogLift s * realifiedHalfLogLiftInv s =
        realify (halfLogLift s * halfLogLiftInv s) := by
      simpa [realifiedHalfLogLift, realifiedHalfLogLiftInv] using
        (realify_mul (halfLogLift s) (halfLogLiftInv s)).symm
    _ = realify 1 := by rw [halfLogLift_mul_inv]
    _ = 1 := realify_one

/-- The same explicit inverse is a left inverse after realification. -/
theorem realifiedHalfLogLift_inv_mul (s : ℂ) :
    realifiedHalfLogLiftInv s * realifiedHalfLogLift s = 1 := by
  calc
    realifiedHalfLogLiftInv s * realifiedHalfLogLift s =
        realify (halfLogLiftInv s * halfLogLift s) := by
      simpa [realifiedHalfLogLift, realifiedHalfLogLiftInv] using
        (realify_mul (halfLogLiftInv s) (halfLogLift s)).symm
    _ = realify 1 := by rw [halfLogLift_inv_mul]
    _ = 1 := realify_one

/-- The realified finite lift belongs to the complex-structure commutant. -/
theorem realifiedHalfLogLift_commutes_complexStructure (s : ℂ) :
    realifiedHalfLogLift s * complexStructure =
      complexStructure * realifiedHalfLogLift s := by
  simpa [realifiedHalfLogLift] using
    realify_commutes_complexStructure (halfLogLift s)

/-- Package the canonical Pauli matrix as the repository-native Hermitian
soldering carrier. -/
noncomputable def canonicalPauliHermitian
    (v : SpacetimeVector) : HermitianMat2 where
  mat := InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v
  herm :=
    InfoGeometry.Lie.SplitOctonionCircularMinkowskiPauliBridge.pauliMatrix_isHermitian v

/-- Apply the bipolar determinant-one Cartan element to a real spacetime
vector through its Hermitian Pauli representative. -/
noncomputable def bipolarPauliAction
    (s : ℂ) (v : SpacetimeVector) : HermitianMat2 :=
  bipolarSolderingAction s (canonicalPauliHermitian v)

/-- The bipolar action preserves the determinant of the canonical Pauli
representative. -/
theorem bipolarPauliAction_det (s : ℂ) (v : SpacetimeVector) :
    (bipolarPauliAction s v).mat.det =
      Matrix.det (InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v) := by
  simpa [bipolarPauliAction, canonicalPauliHermitian] using
    bipolarSolderingAction_det s (canonicalPauliHermitian v)

/-- Therefore the acted Pauli block still reads the Minkowski quadratic form. -/
theorem bipolarPauliAction_det_eq_minkowski
    (s : ℂ) (v : SpacetimeVector) :
    (bipolarPauliAction s v).mat.det = (v.q : ℂ) := by
  rw [bipolarPauliAction_det]
  exact InfoGeometry.Geometry.PauliParavectorBridge.det_pauliMatrix v

/-- The split-octonion diagonal Witt slice, the Pauli determinant, and the
bipolar Lorentz action form an exact invariant triangle. -/
theorem circularWittQuadratic_eq_bipolarPauliAction_det
    (s : ℂ) (v : SpacetimeVector) :
    (circularWittQuadratic (minkowskiDiagonalEmbedding v) : ℂ) =
      (bipolarPauliAction s v).mat.det := by
  calc
    (circularWittQuadratic (minkowskiDiagonalEmbedding v) : ℂ) =
        Matrix.det (InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v) :=
      circularWittQuadratic_diagonal_eq_canonical_pauliDet v
    _ = (bipolarPauliAction s v).mat.det :=
      (bipolarPauliAction_det s v).symm

/-- Realification of the canonical Pauli representative. -/
noncomputable def realifiedPauliMatrix
    (v : SpacetimeVector) : RealifiedCartanMatrix :=
  realify (InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v)

/-- The realified Pauli representative lies in the same complex-structure
commutant as the realified Cartan action. -/
theorem realifiedPauliMatrix_commutes_complexStructure
    (v : SpacetimeVector) :
    realifiedPauliMatrix v * complexStructure =
      complexStructure * realifiedPauliMatrix v := by
  simpa [realifiedPauliMatrix] using
    realify_commutes_complexStructure
      (InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v)

/-- Realification of the bipolar Lorentz action on the canonical Pauli
representative. -/
noncomputable def realifiedBipolarPauliAction
    (s : ℂ) (v : SpacetimeVector) : RealifiedCartanMatrix :=
  realify ((bipolarPauliAction s v).mat)

/-- Ring realification commutes with the complete double-sided Pauli action. -/
theorem realifiedBipolarPauliAction_factorization
    (s : ℂ) (v : SpacetimeVector) :
    realifiedBipolarPauliAction s v =
      realifiedHalfLogLift s * realifiedPauliMatrix v *
        realify ((halfLogLift s)ᴴ) := by
  change
    realify
        (halfLogLift s *
          InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v *
            (halfLogLift s)ᴴ) =
      realify (halfLogLift s) *
          realify (InfoGeometry.Geometry.PauliParavectorBridge.pauliMatrix v) *
        realify ((halfLogLift s)ᴴ)
  rw [realify_mul, realify_mul]

/-- The realified acted Pauli matrix remains in the complex-structure
commutant. -/
theorem realifiedBipolarPauliAction_commutes_complexStructure
    (s : ℂ) (v : SpacetimeVector) :
    realifiedBipolarPauliAction s v * complexStructure =
      complexStructure * realifiedBipolarPauliAction s v := by
  simpa [realifiedBipolarPauliAction] using
    realify_commutes_complexStructure ((bipolarPauliAction s v).mat)

/-- Compact statement of the corrected finite soldering chain. -/
theorem bipolar_cartan_pauli_zorn_realification_packet
    (s : ℂ) (v : SpacetimeVector) :
    Kcirc = Complex.I • Kboost ∧
      (∀ a b : ℝ,
        (a : ℂ) • Kboost + (b : ℂ) • Kcirc = 0 → a = 0 ∧ b = 0) ∧
      realifiedKcirc = complexStructure * realifiedKboost ∧
      complexStructure * complexStructure =
        -(1 : RealifiedCartanMatrix) ∧
      realifiedHalfLogLift s * realifiedHalfLogLiftInv s = 1 ∧
      (circularWittQuadratic (minkowskiDiagonalEmbedding v) : ℂ) =
        (bipolarPauliAction s v).mat.det := by
  exact ⟨Kcirc_eq_I_smul_Kboost,
    fun a b h => Kboost_Kcirc_real_linear_independent a b h,
    realifiedKcirc_eq_complexStructure_mul_realifiedKboost,
    complexStructure_sq,
    realifiedHalfLogLift_mul_inv s,
    circularWittQuadratic_eq_bipolarPauliAction_det s v⟩

end InfoGeometry.Canonical.BipolarCartanPauliZornRealificationBridge
