import InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Canonical.BipolarDeckPathClass

/-!
# Transitive axiom inspection for the intrinsic boundary and holonomy chain

This module is an executable audit surface.  It adds no mathematical claims;
the `#print axioms` commands expose the transitive dependencies of the public
theorems so that project-specific axioms and `sorryAx` cannot be hidden behind
the capstone.
-/

#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.boundaryKernel_eq_four_mul_inv_one_add_sq
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.integrable_boundaryKernel
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.integral_boundaryKernel
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.hasDerivAt_scaledImagePotential_half
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.inducedSurfaceDensity_eq_neg_epsilon_mul_leftNormalDerivative
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.integral_inducedSurfaceDensity
#print axioms InfoGeometry.Analysis.BipolarBoundaryKernelIntegral.intervalIntegral_boundaryKernel
#print axioms InfoGeometry.Analysis.BipolarBoundaryKernelIntegral.intervalIntegral_inducedSurfaceDensity

#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.tendsto_originTruncatedLength
#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.tendsto_oneTruncatedLength
#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.tendsto_infinityTruncatedLength

#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.circulationPeriod_eq_angularPeriod_mul_I
#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.u1Holonomy_integer_coupling
#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.u1Holonomy_half_origin_ne_one
#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.u1Holonomy_half_origin_sq

#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularOneFormAt_eq_omegaCoeff
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularDirectionalDerivative_analytic_witness
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularExteriorDerivativeAt_eq_zero
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.coupledAngularCurvatureAt_eq_zero
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularCircleIntegral_eq_contourAngularPeriod
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularCircleIntegral_origin
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularCircleIntegral_one
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.directContourU1Holonomy_origin_eq_winding
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.directContourU1Holonomy_one_eq_winding

#print axioms InfoGeometry.Analysis.BipolarCircleEnclosurePeriods.circleIntegral_dlog01_eq_circulationPeriod
#print axioms InfoGeometry.Analysis.BipolarCircleEnclosurePeriods.no_global_dlog01_primitive
#print axioms InfoGeometry.Canonical.BipolarContourSpinHolonomy.contourSpinHolonomy_eq_winding
#print axioms InfoGeometry.Canonical.BipolarContourSpinHolonomy.contourSpinHolonomy_adjoint_trivial

#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_boundary_image_core
#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.eta_zero_iff_re_eq_half
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_bisector_zero_locus
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_angular_flatness
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_elementary_holonomy
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_no_global_logarithmic_primitive

#print axioms InfoGeometry.Canonical.BipolarDeckPathClass.deckTransport_involutive
#print axioms InfoGeometry.Canonical.BipolarDeckPathClass.deckTransport_energy
#print axioms InfoGeometry.Canonical.BipolarDeckPathClass.deckPathTwice_homotopic_refl
#print axioms InfoGeometry.Canonical.BipolarDeckPathClass.deckPathClass_invariant
