import InfoGeometry.Canonical.BipolarTwoSheetOperatorConnectionBridge
import InfoGeometry.Information.ModularSurprisalDerivationBridge
import Mathlib.Tactic

/-!
# Bipolar logarithmic inner derivation

The correct operator replacement for a coordinate derivative is a genuine
Leibniz derivation.  This file applies the repository-owned inner derivation

`adK(K)(X) = KX - XK`

to the combined bipolar Cartan generator

`K(s) = η(s) Kboost + θ(s) Kcirc`.

The two parabolic sheet generators are eigenoperators with eigenvalues `±W(s)`,
and the already-proved finite adjoint flow integrates those infinitesimal
characters to `q(s)^{±1}`.
-/

noncomputable section

namespace InfoGeometry.Canonical.BipolarLogarithmicDerivationBridge

open InfoGeometry.Analysis.BipolarCrossRatioLog
open InfoGeometry.Canonical.BipolarTwoSheetOperatorConnectionBridge
open InfoGeometry.Information.ModularSurprisalDerivationBridge
open InfoGeometry.Physics.ChiralCausalCone

abbrev Matrix2C := Matrix (Fin 2) (Fin 2) ℂ

/-- Inner derivation generated by the bipolar logarithmic Cartan element. -/
def logarithmicDerivation (s : ℂ) : Matrix2C →+ Matrix2C :=
  adK (logarithmicCartanGenerator s)

@[simp] theorem logarithmicDerivation_apply (s : ℂ) (X : Matrix2C) :
    logarithmicDerivation s X =
      logarithmicCartanGenerator s * X - X * logarithmicCartanGenerator s :=
  rfl

/-- The logarithmic inner derivation satisfies the genuine Leibniz rule. -/
theorem logarithmicDerivation_leibniz (s : ℂ) (X Y : Matrix2C) :
    logarithmicDerivation s (X * Y) =
      logarithmicDerivation s X * Y + X * logarithmicDerivation s Y := by
  exact adK_is_derivation (logarithmicCartanGenerator s) X Y

/-- The derivation annihilates the identity. -/
@[simp] theorem logarithmicDerivation_one (s : ℂ) :
    logarithmicDerivation s (1 : Matrix2C) = 0 := by
  exact adK_one (logarithmicCartanGenerator s)

/-- Plus-sheet adjoint eigenoperator law. -/
theorem logarithmicDerivation_sigmaPlus (s : ℂ) :
    logarithmicDerivation s σPlus = bipolarLog s • σPlus := by
  rw [logarithmicDerivation_apply]
  rw [logarithmicCartan_comm_sigmaPlus, plusCartanWeight_eq_bipolarLog]

/-- Minus-sheet adjoint eigenoperator law. -/
theorem logarithmicDerivation_sigmaMinus (s : ℂ) :
    logarithmicDerivation s σMinus = (-bipolarLog s) • σMinus := by
  rw [logarithmicDerivation_apply, logarithmicCartan_comm_sigmaMinus]
  simp [minusCartanWeight, plusCartanWeight_eq_bipolarLog]

/-- The finite adjoint action integrates the plus-sheet derivation character. -/
theorem logarithmicDerivation_integrates_plus
    {s : ℂ} (hs : s ∈ punctured01) :
    logarithmicDerivation s σPlus = bipolarLog s • σPlus ∧
      finiteAdjointFlow s σPlus = crossRatio01 s • σPlus := by
  exact ⟨logarithmicDerivation_sigmaPlus s,
    finiteAdjointFlow_sigmaPlus_eq_crossRatio hs⟩

/-- The finite adjoint action integrates the minus-sheet derivation character. -/
theorem logarithmicDerivation_integrates_minus
    {s : ℂ} (hs : s ∈ punctured01) :
    logarithmicDerivation s σMinus = (-bipolarLog s) • σMinus ∧
      finiteAdjointFlow s σMinus = (crossRatio01 s)⁻¹ • σMinus := by
  exact ⟨logarithmicDerivation_sigmaMinus s,
    finiteAdjointFlow_sigmaMinus_eq_crossRatio_inv hs⟩

/-- Compact derivation/integration packet. -/
theorem bipolar_logarithmic_derivation_packet
    {s : ℂ} (hs : s ∈ punctured01) (X Y : Matrix2C) :
    logarithmicDerivation s (X * Y) =
        logarithmicDerivation s X * Y + X * logarithmicDerivation s Y ∧
      logarithmicDerivation s σPlus = bipolarLog s • σPlus ∧
      logarithmicDerivation s σMinus = (-bipolarLog s) • σMinus ∧
      finiteAdjointFlow s σPlus = crossRatio01 s • σPlus ∧
      finiteAdjointFlow s σMinus = (crossRatio01 s)⁻¹ • σMinus := by
  exact ⟨logarithmicDerivation_leibniz s X Y,
    logarithmicDerivation_sigmaPlus s,
    logarithmicDerivation_sigmaMinus s,
    finiteAdjointFlow_sigmaPlus_eq_crossRatio hs,
    finiteAdjointFlow_sigmaMinus_eq_crossRatio_inv hs⟩

end InfoGeometry.Canonical.BipolarLogarithmicDerivationBridge
