import InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain

/-!
# Transitive axiom inspection for the intrinsic boundary and holonomy chain

Run this file after building
`InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain`.

The commands inspect elaborated declarations and their transitive dependencies.
They do not certify the branch until Lean executes them.  Acceptable output
contains only standard logical axioms such as `propext`, `Classical.choice`, and
`Quot.sound`, or no axioms.  Any occurrence of `sorryAx` or a project-specific
axiom is a verification failure.
-/

#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.boundaryKernel_eq_four_mul_inv_one_add_sq
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.integrable_boundaryKernel
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.integral_boundaryKernel
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.hasDerivAt_scaledImagePotential_half
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.inducedSurfaceDensity_eq_neg_epsilon_mul_leftNormalDerivative
#print axioms InfoGeometry.Analysis.BipolarBoundarySurfaceCharge.integral_inducedSurfaceDensity
#print axioms InfoGeometry.Analysis.BipolarBoundaryKernelIntegral.intervalIntegral_boundaryKernel
#print axioms InfoGeometry.Analysis.BipolarBoundaryKernelIntegral.intervalIntegral_inducedSurfaceDensity

#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.tendsto_originTruncatedLength
#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.tendsto_oneTruncatedLength
#print axioms InfoGeometry.Analysis.BipolarMetricEndLengths.tendsto_infinityTruncatedLength

#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.circulationPeriod_eq_angularPeriod_mul_I
#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.u1Holonomy_integer_coupling
#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.u1Holonomy_half_origin_ne_one
#print axioms InfoGeometry.Canonical.BipolarU1PeriodHolonomy.u1Holonomy_half_origin_sq

#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularOneFormAt_eq_omegaCoeff
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularDirectionalDerivative_analytic_witness
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularExteriorDerivativeAt_eq_zero
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.coupledAngularCurvatureAt_eq_zero
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularCircleIntegral_eq_contourAngularPeriod
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularCircleIntegral_origin
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.angularCircleIntegral_one
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.directContourU1Holonomy_origin_eq_winding
#print axioms InfoGeometry.Canonical.BipolarAngularOneFormConnection.directContourU1Holonomy_one_eq_winding

#print axioms InfoGeometry.Analysis.BipolarCircleEnclosurePeriods.circleIntegral_dlog01_eq_circulationPeriod
#print axioms InfoGeometry.Analysis.BipolarCircleEnclosurePeriods.no_global_dlog01_primitive
#print axioms InfoGeometry.Canonical.BipolarContourSpinHolonomy.contourSpinHolonomy_eq_winding
#print axioms InfoGeometry.Canonical.BipolarContourSpinHolonomy.contourSpinHolonomy_adjoint_trivial

#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_boundary_image_core
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_metric_end_core
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_angular_connection_core
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_regular_circle_holonomy_core
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_no_global_logarithmic_primitive
#print axioms InfoGeometry.Canonical.BipolarIntrinsicBoundaryHolonomyPristineChain.pristine_intrinsic_boundary_holonomy_master
