import InfoGeometry.Canonical.TomitaTakesaki
import Mathlib.Tactic.Abel

/-!
# Bogoliubov Transport

Canonical doubled-carrier transport layer for the internal phase axis `Jε`.

This file is written directly on `DoubledSpace E`. It introduces no complex
scalars and no Euclidean proxy carrier. The owner surface consists of:

- the doubled-carrier Krein expectation,
- the exact Heisenberg commutator transport operator,
- the concrete phase-linear / phase-antilinear splitting relative to `Jε`,
- the operator-valued phase force generated by transport of the `Jε` axis,
- and the induced scalar Krein transport law.
-/

namespace InfoGeometry.Canonical.BogoliubovTransport

open InfoGeometry.Canonical.TomitaTakesaki
open InfoGeometry.Krein

section Basic

variable {E : Type*}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "H₂" => DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂
local notation "Kop" => modularComplexI (E := E)

noncomputable local instance : NormedRing EndH := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndH := inferInstance
local instance : IsTopologicalRing EndH := inferInstance
local instance : CompleteSpace EndH := inferInstance

/-- Krein evaluation of an endomorphism on the doubled real carrier. -/
noncomputable def kreinExpectation
    (ψ : H₂) (A : EndH) : ℝ :=
  KreinSpace.kreinInner (H := H₂) ψ (A ψ)

/-- Endomorphisms commuting with the doubled-space phase axis `K = Jε`. -/
def IsPhaseLinear (A : EndH) : Prop :=
  A.comp Kop = (modularComplexI (E := E)).comp A

/-- Endomorphisms anticommuting with the doubled-space phase axis `K = Jε`. -/
def IsPhaseAntilinear (A : EndH) : Prop :=
  A.comp Kop = -((modularComplexI (E := E)).comp A)

/-- Conjugation of an endomorphism by the doubled-space phase axis `K = Jε`. -/
noncomputable def phaseConjugate (A : EndH) : EndH :=
  (modularComplexI (E := E)).comp (A.comp Kop)

/-- The phase-linear projection of a doubled-space endomorphism. -/
noncomputable def phaseLinearPart (A : EndH) : EndH :=
  (1 / 2 : ℝ) • (A - phaseConjugate (E := E) A)

/-- The phase-antilinear projection of a doubled-space endomorphism. -/
noncomputable def phaseAntilinearPart (A : EndH) : EndH :=
  (1 / 2 : ℝ) • (A + phaseConjugate (E := E) A)

omit [CompleteSpace E] in
@[simp] theorem phaseLinearPart_add_phaseAntilinearPart
    (A : EndH) :
    phaseLinearPart (E := E) A + phaseAntilinearPart (E := E) A = A := by
  unfold phaseLinearPart phaseAntilinearPart
  calc
    (1 / 2 : ℝ) • (A - phaseConjugate (E := E) A) +
        (1 / 2 : ℝ) • (A + phaseConjugate (E := E) A)
      = ((1 / 2 : ℝ) • A - (1 / 2 : ℝ) • phaseConjugate (E := E) A) +
          ((1 / 2 : ℝ) • A + (1 / 2 : ℝ) • phaseConjugate (E := E) A) := by
            simp [smul_sub, smul_add]
    _ = (1 / 2 : ℝ) • A + (1 / 2 : ℝ) • A := by
          abel
    _ = (2 : ℝ) • ((1 / 2 : ℝ) • A) := by
          simpa [two_smul] using (two_smul ℝ ((1 / 2 : ℝ) • A)).symm
    _ = ((2 : ℝ) * (1 / 2 : ℝ)) • A := by
          simp [smul_smul]
    _ = (1 : ℝ) • A := by
          norm_num
    _ = A := by
          simp

omit [CompleteSpace E] in
lemma phaseConjugate_comp_phaseAxis
    (A : EndH) :
    (phaseConjugate (E := E) A).comp Kop = -((modularComplexI (E := E)).comp A) := by
  apply ContinuousLinearMap.ext
  intro x
  have hK2x : Kop (Kop x) = -x := by
    apply DoubledSpace.ext <;> simp [TomitaTakesaki.modularComplexI]
  unfold phaseConjugate
  calc
    (modularComplexI (E := E)) (A (Kop (Kop x)))
      = (modularComplexI (E := E)) (A (-x)) := by rw [hK2x]
    _ = -((modularComplexI (E := E)) (A x)) := by
          apply DoubledSpace.ext <;> simp [TomitaTakesaki.modularComplexI]

omit [CompleteSpace E] in
lemma phaseAxis_comp_phaseConjugate
    (A : EndH) :
    (modularComplexI (E := E)).comp (phaseConjugate (E := E) A) = -(A.comp Kop) := by
  apply ContinuousLinearMap.ext
  intro x
  have hK2Ax : Kop (Kop (A (Kop x))) = -(A (Kop x)) := by
    apply DoubledSpace.ext <;> simp [TomitaTakesaki.modularComplexI]
  unfold phaseConjugate
  simpa [ContinuousLinearMap.comp_apply] using hK2Ax

omit [CompleteSpace E] in
lemma neg_phaseConjugate_comp_phaseAxis
    (A : EndH) :
    -((phaseConjugate (E := E) A).comp Kop) = (modularComplexI (E := E)).comp A := by
  simpa using congrArg Neg.neg (phaseConjugate_comp_phaseAxis (E := E) A)

omit [CompleteSpace E] in
lemma neg_phaseAxis_comp_phaseConjugate
    (A : EndH) :
    -((modularComplexI (E := E)).comp (phaseConjugate (E := E) A)) = A.comp Kop := by
  simpa using congrArg Neg.neg (phaseAxis_comp_phaseConjugate (E := E) A)

theorem phaseLinearPart_isPhaseLinear
    (A : EndH) :
    IsPhaseLinear (E := E) (phaseLinearPart (E := E) A) := by
  unfold IsPhaseLinear phaseLinearPart
  rw [ContinuousLinearMap.smul_comp, ContinuousLinearMap.comp_smul]
  apply congrArg (fun T => (1 / 2 : ℝ) • T)
  calc
    (A - phaseConjugate (E := E) A).comp Kop
        = A.comp Kop - (phaseConjugate (E := E) A).comp Kop := by
            simp [ContinuousLinearMap.sub_comp]
    _ = A.comp Kop + (modularComplexI (E := E)).comp A := by
          rw [phaseConjugate_comp_phaseAxis (E := E)]
          abel
    _ = (modularComplexI (E := E)).comp A + A.comp Kop := by
          abel
    _ = (modularComplexI (E := E)).comp A - (modularComplexI (E := E)).comp (phaseConjugate (E := E) A) := by
          rw [← neg_phaseAxis_comp_phaseConjugate (E := E)]
          abel
    _ = (modularComplexI (E := E)).comp (A - phaseConjugate (E := E) A) := by
          simp [ContinuousLinearMap.comp_sub]

theorem phaseAntilinearPart_isPhaseAntilinear
    (A : EndH) :
    IsPhaseAntilinear (E := E) (phaseAntilinearPart (E := E) A) := by
  unfold IsPhaseAntilinear phaseAntilinearPart
  rw [ContinuousLinearMap.smul_comp, ContinuousLinearMap.comp_smul, ← smul_neg]
  apply congrArg (fun T => (1 / 2 : ℝ) • T)
  calc
    (A + phaseConjugate (E := E) A).comp Kop
        = A.comp Kop + (phaseConjugate (E := E) A).comp Kop := by
            simp [ContinuousLinearMap.add_comp]
    _ = A.comp Kop - (modularComplexI (E := E)).comp A := by
          rw [phaseConjugate_comp_phaseAxis (E := E)]
          abel
    _ = -((modularComplexI (E := E)).comp A - A.comp Kop) := by
          abel
    _ = -((modularComplexI (E := E)).comp A + (modularComplexI (E := E)).comp (phaseConjugate (E := E) A)) := by
          rw [← neg_phaseAxis_comp_phaseConjugate (E := E)]
          abel
    _ = -((modularComplexI (E := E)).comp (A + phaseConjugate (E := E) A)) := by
          simp [ContinuousLinearMap.comp_add]

/-- Exact Heisenberg commutator transport on the doubled real carrier. -/
noncomputable def transportCommutator (H A : EndH) : EndH :=
  H.comp A - A.comp H

/-- The doubled-space phase force generated by transport of the internal axis `Jε`. -/
noncomputable def phaseAxisForce (H : EndH) : EndH :=
  transportCommutator (E := E) H Kop

/-- Scalar Krein transport observable associated to the commutator transport term. -/
noncomputable def heisenbergKreinTransport
    (ψ : H₂) (H A : EndH) : ℝ :=
  kreinExpectation (E := E) ψ (transportCommutator (E := E) H A)

/-- Scalar Krein transport observable for the internal phase axis `Jε`. -/
noncomputable def phaseAxisTransport
    (ψ : H₂) (H : EndH) : ℝ :=
  kreinExpectation (E := E) ψ (phaseAxisForce (E := E) H)

omit [CompleteSpace E] in
theorem transportCommutator_split_generator
    (H A : EndH) :
    transportCommutator (E := E) H A
      = transportCommutator (E := E) (phaseLinearPart (E := E) H) A
        + transportCommutator (E := E) (phaseAntilinearPart (E := E) H) A := by
  have h_add_left (H1 H2 A : EndH) :
      transportCommutator (E := E) (H1 + H2) A
        = transportCommutator (E := E) H1 A + transportCommutator (E := E) H2 A := by
    apply ContinuousLinearMap.ext
    intro x
    simp [transportCommutator, sub_eq_add_neg]
    abel
  calc
    transportCommutator (E := E) H A
      = transportCommutator (E := E)
          (phaseLinearPart (E := E) H + phaseAntilinearPart (E := E) H) A := by
            rw [phaseLinearPart_add_phaseAntilinearPart (E := E) H]
    _ = transportCommutator (E := E) (phaseLinearPart (E := E) H) A
          + transportCommutator (E := E) (phaseAntilinearPart (E := E) H) A := by
            simpa using h_add_left (phaseLinearPart (E := E) H) (phaseAntilinearPart (E := E) H) A

omit [CompleteSpace E] in
theorem phaseAxisForce_eq_zero_of_IsPhaseLinear
    (H : EndH) (hH : IsPhaseLinear (E := E) H) :
    phaseAxisForce (E := E) H = 0 := by
  unfold phaseAxisForce transportCommutator IsPhaseLinear at *
  rw [hH]
  abel

omit [CompleteSpace E] in
theorem phaseAxisForce_eq_two_smul_comp_of_IsPhaseAntilinear
    (H : EndH) (hH : IsPhaseAntilinear (E := E) H) :
    phaseAxisForce (E := E) H = (2 : ℝ) • (H.comp Kop) := by
  have hKH : (modularComplexI (E := E)).comp H = -(H.comp Kop) := by
    calc
      (modularComplexI (E := E)).comp H = -(-((modularComplexI (E := E)).comp H)) := by simp
      _ = -(H.comp Kop) := by rw [← hH]
  apply ContinuousLinearMap.ext
  intro x
  apply DoubledSpace.ext <;> simp [phaseAxisForce, transportCommutator, hKH, two_smul]

theorem phaseAxisForce_of_phaseLinearPart_eq_zero
    (H : EndH) :
    phaseAxisForce (E := E) (phaseLinearPart (E := E) H) = 0 := by
  exact phaseAxisForce_eq_zero_of_IsPhaseLinear
    (E := E) (phaseLinearPart (E := E) H) (phaseLinearPart_isPhaseLinear (E := E) H)

theorem phaseAxisForce_of_phaseAntilinearPart_eq_two_smul
    (H : EndH) :
    phaseAxisForce (E := E) (phaseAntilinearPart (E := E) H)
      = (2 : ℝ) • ((phaseAntilinearPart (E := E) H).comp Kop) := by
  exact phaseAxisForce_eq_two_smul_comp_of_IsPhaseAntilinear
    (E := E) (phaseAntilinearPart (E := E) H) (phaseAntilinearPart_isPhaseAntilinear (E := E) H)

/--
The transport of the internal phase axis is sourced entirely by the
phase-antilinear part of the generator.
-/
theorem phaseAxisForce_eq_from_phaseAntilinearPart
    (H : EndH) :
    phaseAxisForce (E := E) H
      = (2 : ℝ) • ((phaseAntilinearPart (E := E) H).comp Kop) := by
  unfold phaseAxisForce
  rw [transportCommutator_split_generator (E := E) H Kop]
  have hlin : transportCommutator (E := E) (phaseLinearPart (E := E) H) Kop = 0 := by
    simpa [phaseAxisForce] using (phaseAxisForce_of_phaseLinearPart_eq_zero (E := E) H)
  have hanti : transportCommutator (E := E) (phaseAntilinearPart (E := E) H) Kop
      = (2 : ℝ) • ((phaseAntilinearPart (E := E) H).comp Kop) := by
    simpa [phaseAxisForce] using (phaseAxisForce_of_phaseAntilinearPart_eq_two_smul (E := E) H)
  rw [hlin, hanti]
  simp

/-- The concrete doubled Heisenberg/Krein transport splits through the phase parity decomposition. -/
theorem heisenbergKreinTransport_split_generator
    (ψ : H₂) (H A : EndH) :
    heisenbergKreinTransport (E := E) ψ H A
      = heisenbergKreinTransport (E := E) ψ (phaseLinearPart (E := E) H) A
        + heisenbergKreinTransport (E := E) ψ (phaseAntilinearPart (E := E) H) A := by
  unfold heisenbergKreinTransport kreinExpectation
  rw [transportCommutator_split_generator (E := E) H A]
  rw [ContinuousLinearMap.add_apply]
  rw [KreinSpace.kreinInner_add_right]

/-- The scalar phase-axis transport vanishes for phase-linear generators. -/
theorem phaseAxisTransport_eq_zero_of_IsPhaseLinear
    (ψ : H₂) (H : EndH) (hH : IsPhaseLinear (E := E) H) :
    phaseAxisTransport (E := E) ψ H = 0 := by
  unfold phaseAxisTransport kreinExpectation
  rw [phaseAxisForce_eq_zero_of_IsPhaseLinear (E := E) H hH]
  simp

/--
The scalar phase-axis transport is exactly the Krein expectation of the
Bogoliubov force term coming from the phase-antilinear sector.
-/
theorem phaseAxisTransport_eq_from_phaseAntilinearPart
    (ψ : H₂) (H : EndH) :
    phaseAxisTransport (E := E) ψ H
      = kreinExpectation (E := E) ψ
          ((2 : ℝ) • ((phaseAntilinearPart (E := E) H).comp Kop)) := by
  unfold phaseAxisTransport kreinExpectation
  rw [phaseAxisForce_eq_from_phaseAntilinearPart (E := E) H]


/-- Real Bogoliubov boost generated by the concrete doubled-space modular conjugation `J`. -/
noncomputable def JBoost (t : ℝ) : EndH :=
  NormedSpace.exp (t • modularConjugationJ (E := E))

/-- Real Bogoliubov boost generated by the concrete doubled-space signature operator `ε`. -/
noncomputable def epsilonBoost (t : ℝ) : EndH :=
  NormedSpace.exp (t • modularSignEpsilon (E := E))

/-- Internal phase rotation generated by the concrete doubled-space axis `K = Jε`. -/
noncomputable def KRotation (t : ℝ) : EndH :=
  NormedSpace.exp (t • modularComplexI (E := E))

omit [CompleteSpace E] in
@[simp] theorem JBoost_zero :
    JBoost (E := E) 0 = (1 : EndH) := by
  simp [JBoost]

omit [CompleteSpace E] in
@[simp] theorem epsilonBoost_zero :
    epsilonBoost (E := E) 0 = (1 : EndH) := by
  simp [epsilonBoost]

omit [CompleteSpace E] in
@[simp] theorem KRotation_zero :
    KRotation (E := E) 0 = (1 : EndH) := by
  simp [KRotation]

theorem JBoost_add (s t : ℝ) :
    JBoost (E := E) (s + t) = JBoost (E := E) s * JBoost (E := E) t := by
  have hComm : Commute (s • modularConjugationJ (E := E)) (t • modularConjugationJ (E := E)) := by
    exact ((Commute.refl (modularConjugationJ (E := E))).smul_left s).smul_right t
  calc
    JBoost (E := E) (s + t)
        = NormedSpace.exp ((s + t) • modularConjugationJ (E := E)) := rfl
    _ = NormedSpace.exp (s • modularConjugationJ (E := E) + t • modularConjugationJ (E := E)) := by
          simp [add_smul]
    _ = NormedSpace.exp (s • modularConjugationJ (E := E)) *
          NormedSpace.exp (t • modularConjugationJ (E := E)) := by
          rw [NormedSpace.exp_add_of_commute hComm]
    _ = JBoost (E := E) s * JBoost (E := E) t := rfl

theorem epsilonBoost_add (s t : ℝ) :
    epsilonBoost (E := E) (s + t) = epsilonBoost (E := E) s * epsilonBoost (E := E) t := by
  have hComm : Commute (s • modularSignEpsilon (E := E)) (t • modularSignEpsilon (E := E)) := by
    exact ((Commute.refl (modularSignEpsilon (E := E))).smul_left s).smul_right t
  calc
    epsilonBoost (E := E) (s + t)
        = NormedSpace.exp ((s + t) • modularSignEpsilon (E := E)) := rfl
    _ = NormedSpace.exp (s • modularSignEpsilon (E := E) + t • modularSignEpsilon (E := E)) := by
          simp [add_smul]
    _ = NormedSpace.exp (s • modularSignEpsilon (E := E)) *
          NormedSpace.exp (t • modularSignEpsilon (E := E)) := by
          rw [NormedSpace.exp_add_of_commute hComm]
    _ = epsilonBoost (E := E) s * epsilonBoost (E := E) t := rfl

theorem KRotation_add (s t : ℝ) :
    KRotation (E := E) (s + t) = KRotation (E := E) s * KRotation (E := E) t := by
  have hComm : Commute (s • modularComplexI (E := E)) (t • modularComplexI (E := E)) := by
    exact ((Commute.refl (modularComplexI (E := E))).smul_left s).smul_right t
  calc
    KRotation (E := E) (s + t)
        = NormedSpace.exp ((s + t) • modularComplexI (E := E)) := rfl
    _ = NormedSpace.exp (s • modularComplexI (E := E) + t • modularComplexI (E := E)) := by
          simp [add_smul]
    _ = NormedSpace.exp (s • modularComplexI (E := E)) *
          NormedSpace.exp (t • modularComplexI (E := E)) := by
          rw [NormedSpace.exp_add_of_commute hComm]
    _ = KRotation (E := E) s * KRotation (E := E) t := rfl

end Basic

end InfoGeometry.Canonical.BogoliubovTransport
