import Mathlib

/-!
# Branman countable-Stone finite core

Closed, domain-free Lean facts extracted from the finite parts of Branman et al.,
“Graphical models for topological groups: A case study on countable Stone
spaces” (BLMS 2025).

The paper's global classification of `Homeo(X_{α,n})` uses countable ordinals,
Cantor--Bendixson derivatives, Rosendal coarse boundedness, and
Cayley--Abels--Rosendal graphs.  This module proves the finite Mathlib core used by
that layer.

#### BUCKET 1: CLOSED FINITE THEOREMS
* Finite discrete spaces are Stone spaces: compact, Hausdorff, and totally
  disconnected.
* Self-homeomorphisms of a finite discrete space are exactly permutations.
* The finite homeomorphism group of a finite discrete space is finite.
* A homeomorphism preserving an indexed finite partition by a permutation is
  closed under identity and composition.
* A finite inverse-closed label set gives symmetric Cayley/CAR adjacency, and
  left translations preserve adjacency.

#### BUCKET 2: CONDITIONAL THEOREMS FROM EXPLICIT WITNESSES
* Cayley/CAR symmetry is conditional on the explicit premise
  `∀ f ∈ F, f⁻¹ ∈ F`.

#### Out of Scope
* No theorem here asserts Theorem A of the paper.
* The countable-ordinal Cantor--Bendixson classification of countable Stone
  spaces is not formalized here.
* Rosendal coarse boundedness, the Milnor--Schwarz lemma for Polish groups, and
  the full homeomorphism-group classification are not formalized here.
-/

noncomputable section

namespace InfoGeometry.Canonical.BranmanCountableStone

open Set

/-! ## Stone spaces and finite discrete homeomorphisms -/

/-- A Stone space, stated as the three Mathlib typeclass properties. -/
def IsStoneSpace (X : Type*) [TopologicalSpace X] : Prop :=
  CompactSpace X ∧ T2Space X ∧ TotallyDisconnectedSpace X

/-- Finite discrete spaces are Stone spaces. -/
theorem finiteDiscrete_isStoneSpace
    (X : Type*) [TopologicalSpace X] [Fintype X] [DiscreteTopology X] :
    IsStoneSpace X := by
  exact ⟨inferInstance, inferInstance, inferInstance⟩

section HomeomorphismGroup

variable {X : Type*} [TopologicalSpace X] [Fintype X] [DecidableEq X] [DiscreteTopology X]

/-- On a finite discrete Stone space, homeomorphisms are exactly permutations. -/
def homeomorphismsEquivPermutations : (X ≃ₜ X) ≃ (X ≃ X) where
  toFun h := h.toEquiv
  invFun e := e.toHomeomorphOfDiscrete
  left_inv h := by
    ext x
    rfl
  right_inv e := by
    ext x
    rfl

/-- The homeomorphism group of a finite discrete Stone space is finite. -/
instance finiteHomeomorphisms : Fintype (X ≃ₜ X) :=
by
  classical
  letI : Fintype (X ≃ X) := inferInstance
  exact Fintype.ofEquiv (X ≃ X) (homeomorphismsEquivPermutations (X := X)).symm

/-- Finite discrete Stone spaces have only finitely many self-homeomorphisms. -/
theorem finiteDiscreteStone_homeomorphismGroup_finite :
    Finite (X ≃ₜ X) := by
  infer_instance

end HomeomorphismGroup

/-- Homeomorphism group of a finite discrete `n`-point Stone space, represented canonically
as the permutation group of `Fin n`. -/
abbrev finiteDiscreteHomeomorphismGroup (n : ℕ) := Equiv.Perm (Fin n)

/-- The finite discrete homeomorphism group has factorial cardinality. -/
theorem finiteDiscreteHomeomorphismGroup_card (n : ℕ) :
    Fintype.card (finiteDiscreteHomeomorphismGroup n) = n.factorial := by
  simpa [finiteDiscreteHomeomorphismGroup] using (Fintype.card_perm (α := Fin n))

/-! ## Finite clopen-partition permutation skeleton -/

section IndexedPartitions

variable {X ι : Type*} [TopologicalSpace X]

/-- A homeomorphism permutes an indexed family of sets when it sends each part to
another part through an index permutation. -/
def PermutesIndexedFamily (P : ι → Set X) (h : X ≃ₜ X) : Prop :=
  ∃ σ : ι ≃ ι, ∀ i, h '' P i = P (σ i)

/-- The identity homeomorphism permutes every indexed family. -/
theorem permutesIndexedFamily_refl (P : ι → Set X) :
    PermutesIndexedFamily P (Homeomorph.refl X) := by
  refine ⟨Equiv.refl ι, ?_⟩
  intro i
  ext x
  simp

/-- Permuting an indexed family is closed under homeomorphism composition. -/
theorem permutesIndexedFamily_trans
    (P : ι → Set X) (h k : X ≃ₜ X)
    (hh : PermutesIndexedFamily P h) (hk : PermutesIndexedFamily P k) :
    PermutesIndexedFamily P (h.trans k) := by
  rcases hh with ⟨σ, hσ⟩
  rcases hk with ⟨τ, hτ⟩
  refine ⟨σ.trans τ, ?_⟩
  intro i
  calc
    (h.trans k) '' P i = k '' (h '' P i) := by
      ext x
      constructor
      · rintro ⟨y, hy, rfl⟩
        exact ⟨h y, ⟨y, hy, rfl⟩, rfl⟩
      · rintro ⟨y, ⟨z, hz, rfl⟩, rfl⟩
        exact ⟨z, hz, rfl⟩
    _ = k '' P (σ i) := by rw [hσ i]
    _ = P (τ (σ i)) := hτ (σ i)
    _ = P ((σ.trans τ) i) := rfl

end IndexedPartitions

/-! ## Finite Cayley--Abels--Rosendal graph skeleton -/

section CARGraph

variable {G : Type*} [Group G]

/-- Cayley/CAR adjacency generated by a finite label set. -/
def cayleyAdj (F : Finset G) (g h : G) : Prop :=
  ∃ f ∈ F, h = g * f

/-- Inverse-closed labels give symmetric adjacency. -/
theorem cayleyAdj_symm {F : Finset G}
    (hF : ∀ {f : G}, f ∈ F → f⁻¹ ∈ F) {g h : G} :
    cayleyAdj F g h → cayleyAdj F h g := by
  rintro ⟨f, hf, rfl⟩
  refine ⟨f⁻¹, hF hf, ?_⟩
  simp [mul_assoc]

/-- Left translation preserves Cayley/CAR adjacency. -/
theorem cayleyAdj_left_translate (F : Finset G) (k : G) {g h : G} :
    cayleyAdj F g h → cayleyAdj F (k * g) (k * h) := by
  rintro ⟨f, hf, rfl⟩
  exact ⟨f, hf, by simp [mul_assoc]⟩

/-- Insert one label and its inverse into a finite label set. -/
def insertSymmetric [DecidableEq G] (F : Finset G) (a : G) : Finset G :=
  insert a (insert a⁻¹ F)

/-- The inserted finite label set contains the label. -/
@[simp] theorem mem_insertSymmetric_self [DecidableEq G] (F : Finset G) (a : G) :
    a ∈ insertSymmetric F a := by
  simp [insertSymmetric]

/-- The inserted finite label set contains the inverse label. -/
@[simp] theorem mem_insertSymmetric_inv [DecidableEq G] (F : Finset G) (a : G) :
    a⁻¹ ∈ insertSymmetric F a := by
  simp [insertSymmetric]

/-- If the old label set is inverse-closed, inserting `a` and `a⁻¹` keeps it
inverse-closed. -/
theorem insertSymmetric_invClosed [DecidableEq G] {F : Finset G} (a : G)
    (hF : ∀ {f : G}, f ∈ F → f⁻¹ ∈ F) :
    ∀ {f : G}, f ∈ insertSymmetric F a → f⁻¹ ∈ insertSymmetric F a := by
  intro f hf
  simp only [insertSymmetric, Finset.mem_insert] at hf ⊢
  rcases hf with rfl | h
  · exact Or.inr (Or.inl rfl)
  · rcases h with rfl | hFmem
    · exact Or.inl (inv_inv a)
    · exact Or.inr (Or.inr (hF hFmem))

/-- The added label creates the corresponding edge. -/
theorem cayleyAdj_insertSymmetric_self [DecidableEq G] (F : Finset G) (a g : G) :
    cayleyAdj (insertSymmetric F a) g (g * a) :=
  ⟨a, by simp, rfl⟩

end CARGraph

section FiniteLabels

variable {G : Type*}

/-- Finite label carriers are finite subsets. -/
theorem labels_finite (F : Finset G) : (F : Set G).Finite :=
  F.finite_toSet

end FiniteLabels

end InfoGeometry.Canonical.BranmanCountableStone
