import InfoGeometry.Canonical.ChiralCausalConeSoldering

#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.carrierSolderAlg
#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.carrierSolderAlg_commutator
#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.sigmaPlus_alg_solder
#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.sigmaMinus_alg_solder
#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.sigmaThree_alg_solder
#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.carrierSolderAlg_car_packet
#print axioms InfoGeometry.Canonical.ChiralCausalConeSoldering.solder_preserves_causal_determinant
