import InfoGeometry.Clifford.Cl55CreationWordGradeObstruction
import InfoGeometry.Clifford.ExteriorBasisBoundaryWitness
import InfoGeometry.InformationGeometry.FiniteChannelLogRatioBarrier
import InfoGeometry.LinearAlgebra.RegularDyadCompression
import InfoGeometry.Streaming.TwoBoundaryDyadCompression
import InfoGeometry.Topology.AffineDeckFixedPointSeparation
