import InfoGeometry.Canonical.BosonizationConstructiveCurrent

/-!
# Current-to-Sugawara bridge

This file is a narrow adapter from a proved Heisenberg current representation
to the existing external Sugawara/Virasoro construction.

It does not reprove Sugawara and it does not assert a Lichnerowicz square
identity.  The only inputs are exactly the inputs required by
`VirasoroProject.sugawaraRepresentation`: current modes, local truncation, and
the Heisenberg commutator.
-/

namespace InfoGeometry.Canonical.CurrentSugawaraBridge

open Filter
open InfoGeometry.Canonical.BosonizationConstructiveCurrent

/--
The exact current-representation interface required by the external Sugawara
construction.
-/
structure CurrentHeisenbergRep
    (𝕜 V : Type*) [Field 𝕜] [CharZero 𝕜]
    [AddCommGroup V] [Module 𝕜 V] where
  /-- Heisenberg current modes. -/
  J : Int → V →ₗ[𝕜] V
  /-- Local truncation required for the Sugawara finite-support sums. -/
  trunc : ∀ v, atTop.Eventually (fun l => J l v = 0)
  /-- Heisenberg commutator law. -/
  comm :
    ∀ m n,
      (J m).commutator (J n) =
        if m + n = 0 then (m : 𝕜) • (1 : V →ₗ[𝕜] V) else 0

namespace CurrentHeisenbergRep

variable {𝕜 V : Type*} [Field 𝕜] [CharZero 𝕜]
variable [AddCommGroup V] [Module 𝕜 V]

/-- Sugawara stress-energy mode `L_n` attached to a current representation. -/
noncomputable def sugawaraStressMode
    (H : CurrentHeisenbergRep 𝕜 V) (n : Int) : V →ₗ[𝕜] V :=
  VirasoroProject.sugawaraGen (heiOper := H.J) H.trunc n

/--
The external Sugawara/Virasoro representation generated by the current modes.
-/
noncomputable def currentSugawaraRepresentation
    (H : CurrentHeisenbergRep 𝕜 V) :
    VirasoroProject.VirasoroAlgebra 𝕜 →ₗ⁅𝕜⁆ (V →ₗ[𝕜] V) :=
  sugawaraVirasoroRepresentation_from_heisenbergCurrent H.J H.trunc H.comm

/--
The Sugawara stress modes satisfy the Virasoro bracket with central charge
`c = 1`.
-/
theorem sugawaraStressMode_virasoroBracket
    (H : CurrentHeisenbergRep 𝕜 V) (m n : Int) :
    (H.sugawaraStressMode m).commutator (H.sugawaraStressMode n) =
      (m - n) • H.sugawaraStressMode (m + n)
        + if m + n = 0 then
            (((m ^ 3 - m : 𝕜) / (12 : 𝕜)) • (1 : V →ₗ[𝕜] V))
          else 0 :=
  sugawaraVirasoro_from_heisenbergCurrent H.J H.trunc H.comm m n

/-- In the current Sugawara representation, the Virasoro central generator acts as identity. -/
theorem currentSugawaraRepresentation_central
    (H : CurrentHeisenbergRep 𝕜 V) :
    H.currentSugawaraRepresentation (VirasoroProject.VirasoroAlgebra.cgen 𝕜) =
      (1 : V →ₗ[𝕜] V) :=
  sugawaraVirasoroRepresentation_central_from_heisenbergCurrent H.J H.trunc H.comm

end CurrentHeisenbergRep

end InfoGeometry.Canonical.CurrentSugawaraBridge
