import InfoGeometry.Meta.Architecture
import InfoGeometry.Canonical.Drazin
import Mathlib.Tactic

/-!
# InfoGeometry.Canonical.DrazinLightConeDictionary

Generic ring-level Drazin/light-cone dictionary.

This file is deliberately independent of Type III analytic claims.  It proves
the finite/bounded algebraic kernel used by the certified inverse-kernel lane:

* a projector split `P + P₀ = 1`;
* off-diagonal arrows `u⁺(X) = P X P₀` and `u⁻(X) = P₀ X P`;
* commutator with `P` is the difference of these arrows;
* same-direction arrow products vanish from projector orthogonality.

Concrete Drazin/Moore--Penrose owner data remain in `CertifiedInverseKernel`
and `DrazinSupercharge`.  Type III realization, if any, is a separate analytic
theorem or hypothesis and is not asserted here.
-/

namespace InfoGeometry.Canonical.DrazinLightConeDictionary

/-- Ring commutator. -/
@[rep_depth operator]
def commutator {A : Type*} [Ring A] (X Y : A) : A :=
  X * Y - Y * X

/--
A two-projector split `P + P₀ = 1`.

This is the abstract algebraic substrate of a regular/defect split.
-/
@[rep_depth operator]
structure ProjectorSplit (A : Type*) [Ring A] where
  P : A
  P0 : A
  P_idem : P * P = P
  P0_idem : P0 * P0 = P0
  P_add_P0 : P + P0 = 1
  P_mul_P0 : P * P0 = 0
  P0_mul_P : P0 * P = 0

namespace ProjectorSplit

variable {A : Type*} [Ring A]
variable (S : ProjectorSplit A)

/--
The canonical Drazin projector and its complement form the projector split used
by the light-cone dictionary.

This is the direct owner link: the fields are discharged by
`InfoGeometry.Canonical.Drazin.IsDrazinInverse` theorems, not by a separate
transport packet.
-/
@[rep_depth operator]
def ofDrazinInverse
    {a b : A} {k : ℕ}
    (h : InfoGeometry.Canonical.Drazin.IsDrazinInverse a b k) :
    ProjectorSplit A where
  P := InfoGeometry.Canonical.Drazin.IsDrazinInverse.projection a b
  P0 := InfoGeometry.Canonical.Drazin.IsDrazinInverse.complementaryProjection a b
  P_idem :=
    InfoGeometry.Canonical.Drazin.IsDrazinInverse.projection_is_idempotent h
  P0_idem :=
    InfoGeometry.Canonical.Drazin.IsDrazinInverse.complementaryProjection_is_idempotent h
  P_add_P0 :=
    InfoGeometry.Canonical.Drazin.IsDrazinInverse.projection_add_complementaryProjection
  P_mul_P0 :=
    InfoGeometry.Canonical.Drazin.IsDrazinInverse.projection_mul_complementaryProjection h
  P0_mul_P :=
    InfoGeometry.Canonical.Drazin.IsDrazinInverse.complementaryProjection_mul_projection h

/-- Off-diagonal arrow from defect sector to regular sector. -/
@[rep_depth operator]
def uPlus (X : A) : A :=
  S.P * X * S.P0

/-- Off-diagonal arrow from regular sector to defect sector. -/
@[rep_depth operator]
def uMinus (X : A) : A :=
  S.P0 * X * S.P

/-- Chiral Hodge grading attached to the projector split: `Γ = P - P₀`. -/
@[rep_depth operator]
def chiralGrading : A :=
  S.P - S.P0

/-- Cartan derivation / adjoint action generated by a chosen element. -/
@[rep_depth operator]
def cartanAdjoint (H X : A) : A :=
  H * X - X * H

/-- The chiral grading is a square-one involution. -/
@[rep_depth operator]
theorem chiralGrading_sq_one :
    S.chiralGrading * S.chiralGrading = (1 : A) := by
  unfold chiralGrading
  calc
    (S.P - S.P0) * (S.P - S.P0) = S.P + S.P0 := by
      noncomm_ring [S.P_idem, S.P0_idem, S.P_mul_P0, S.P0_mul_P]
    _ = 1 := S.P_add_P0

/--
Commutator with the regular projector is exactly the difference of the two
off-diagonal light-cone arrows.
-/
@[rep_depth operator]
theorem commutator_P_eq_uPlus_sub_uMinus (X : A) :
    commutator S.P X = S.uPlus X - S.uMinus X := by
  unfold commutator uPlus uMinus
  calc
    S.P * X - X * S.P
        = S.P * X * 1 - 1 * X * S.P := by
            simp
    _ = S.P * X * (S.P + S.P0) - (S.P + S.P0) * X * S.P := by
            rw [S.P_add_P0]
    _ = (S.P * X * S.P + S.P * X * S.P0)
          - (S.P * X * S.P + S.P0 * X * S.P) := by
            noncomm_ring
    _ = S.P * X * S.P0 - S.P0 * X * S.P := by
            noncomm_ring

/-- Same-arrow `u⁺` composition vanishes. -/
@[rep_depth operator]
theorem uPlus_mul_uPlus_eq_zero (X Y : A) :
    S.uPlus X * S.uPlus Y = 0 := by
  unfold uPlus
  calc
    (S.P * X * S.P0) * (S.P * Y * S.P0)
        = S.P * X * (S.P0 * S.P) * Y * S.P0 := by
            noncomm_ring
    _ = 0 := by
            rw [S.P0_mul_P]
            simp

/-- Same-arrow `u⁻` composition vanishes. -/
@[rep_depth operator]
theorem uMinus_mul_uMinus_eq_zero (X Y : A) :
    S.uMinus X * S.uMinus Y = 0 := by
  unfold uMinus
  calc
    (S.P0 * X * S.P) * (S.P0 * Y * S.P)
        = S.P0 * X * (S.P * S.P0) * Y * S.P := by
            noncomm_ring
    _ = 0 := by
            rw [S.P_mul_P0]
            simp

/-- The chiral grading acts by `+1` on `u⁺` from the left. -/
@[rep_depth operator]
theorem chiralGrading_mul_uPlus (X : A) :
    S.chiralGrading * S.uPlus X = S.uPlus X := by
  unfold chiralGrading uPlus
  have hP : S.P * (S.P * X * S.P0) = S.P * X * S.P0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P0) S.P_idem
  have hP0 : S.P0 * (S.P * X * S.P0) = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P0) S.P0_mul_P
  simp [sub_mul, hP, hP0]

/-- The chiral grading acts by `-1` on `u⁺` from the right. -/
@[rep_depth operator]
theorem uPlus_mul_chiralGrading (X : A) :
    S.uPlus X * S.chiralGrading = -S.uPlus X := by
  unfold chiralGrading uPlus
  have hP : (S.P * X * S.P0) * S.P = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P * X * Z) S.P0_mul_P
  have hP0 : (S.P * X * S.P0) * S.P0 = S.P * X * S.P0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P * X * Z) S.P0_idem
  simp [mul_sub, hP, hP0]

/-- The chiral grading acts by `-1` on `u⁻` from the left. -/
@[rep_depth operator]
theorem chiralGrading_mul_uMinus (X : A) :
    S.chiralGrading * S.uMinus X = -S.uMinus X := by
  unfold chiralGrading uMinus
  have hP : S.P * (S.P0 * X * S.P) = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P) S.P_mul_P0
  have hP0 : S.P0 * (S.P0 * X * S.P) = S.P0 * X * S.P := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P) S.P0_idem
  simp [sub_mul, hP, hP0]

/-- The chiral grading acts by `+1` on `u⁻` from the right. -/
@[rep_depth operator]
theorem uMinus_mul_chiralGrading (X : A) :
    S.uMinus X * S.chiralGrading = S.uMinus X := by
  unfold chiralGrading uMinus
  have hP : (S.P0 * X * S.P) * S.P = S.P0 * X * S.P := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P0 * X * Z) S.P_idem
  have hP0 : (S.P0 * X * S.P) * S.P0 = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P0 * X * Z) S.P_mul_P0
  simp [mul_sub, hP, hP0]

/-- The `u⁺ = P X P₀` arrow has Cartan weight `+2` for `Γ = P - P₀`. -/
@[rep_depth operator]
theorem cartanAdjoint_chiralGrading_uPlus (X : A) :
    cartanAdjoint S.chiralGrading (S.uPlus X) = S.uPlus X + S.uPlus X := by
  unfold cartanAdjoint
  rw [S.chiralGrading_mul_uPlus X, S.uPlus_mul_chiralGrading X]
  abel

/-- The `u⁻ = P₀ X P` arrow has Cartan weight `-2` for `Γ = P - P₀`. -/
@[rep_depth operator]
theorem cartanAdjoint_chiralGrading_uMinus (X : A) :
    cartanAdjoint S.chiralGrading (S.uMinus X) = -(S.uMinus X + S.uMinus X) := by
  unfold cartanAdjoint
  rw [S.chiralGrading_mul_uMinus X, S.uMinus_mul_chiralGrading X]
  abel

/-- The `u⁺` arrow is chiral-odd under conjugation by `Γ`. -/
@[rep_depth operator]
theorem chiralGrading_mul_uPlus_mul_chiralGrading (X : A) :
    S.chiralGrading * S.uPlus X * S.chiralGrading = -S.uPlus X := by
  calc
    S.chiralGrading * S.uPlus X * S.chiralGrading
        = S.uPlus X * S.chiralGrading := by rw [S.chiralGrading_mul_uPlus X]
    _ = -S.uPlus X := S.uPlus_mul_chiralGrading X

/-- The `u⁻` arrow is chiral-odd under conjugation by `Γ`. -/
@[rep_depth operator]
theorem chiralGrading_mul_uMinus_mul_chiralGrading (X : A) :
    S.chiralGrading * S.uMinus X * S.chiralGrading = -S.uMinus X := by
  calc
    S.chiralGrading * S.uMinus X * S.chiralGrading
        = (-S.uMinus X) * S.chiralGrading := by rw [S.chiralGrading_mul_uMinus X]
    _ = -S.uMinus X := by rw [neg_mul, S.uMinus_mul_chiralGrading X]

end ProjectorSplit

/-! ## Moore--Penrose light-cone readouts -/

/-- Right/range anomaly as a commutator with the regular projector. -/
@[rep_depth operator]
def mpChiR {A : Type*} [Ring A] (S : ProjectorSplit A) (PR : A) : A :=
  commutator S.P PR

/-- Left/domain anomaly as a commutator with the regular projector. -/
@[rep_depth operator]
def mpChiL {A : Type*} [Ring A] (S : ProjectorSplit A) (PL : A) : A :=
  commutator S.P PL

/-- Net Moore--Penrose light-cone mismatch current. -/
@[rep_depth operator]
def mpSupercharge {A : Type*} [Ring A] (S : ProjectorSplit A) (PR PL : A) : A :=
  mpChiR S PR - mpChiL S PL

/-- Right/range anomaly as light-cone off-diagonal mismatch of `PR`. -/
@[rep_depth operator]
theorem mpChiR_eq_uPlus_sub_uMinus
    {A : Type*} [Ring A]
    (S : ProjectorSplit A)
    (PR : A) :
    mpChiR S PR = S.uPlus PR - S.uMinus PR := by
  exact S.commutator_P_eq_uPlus_sub_uMinus PR

/-- Left/domain anomaly as light-cone off-diagonal mismatch of `PL`. -/
@[rep_depth operator]
theorem mpChiL_eq_uPlus_sub_uMinus
    {A : Type*} [Ring A]
    (S : ProjectorSplit A)
    (PL : A) :
    mpChiL S PL = S.uPlus PL - S.uMinus PL := by
  exact S.commutator_P_eq_uPlus_sub_uMinus PL

/-- The Moore--Penrose supercharge is the net light-cone mismatch current. -/
@[rep_depth operator]
theorem mpSupercharge_eq_net_lightcone_mismatch
    {A : Type*} [Ring A]
    (S : ProjectorSplit A)
    (PR PL : A) :
    mpSupercharge S PR PL =
      (S.uPlus PR - S.uMinus PR) - (S.uPlus PL - S.uMinus PL) := by
  rw [mpSupercharge, mpChiR_eq_uPlus_sub_uMinus, mpChiL_eq_uPlus_sub_uMinus]

end InfoGeometry.Canonical.DrazinLightConeDictionary
