import InfoGeometry.Canonical.CertifiedInverseKernel
import InfoGeometry.Canonical.InverseKernelAlgebra
import InfoGeometry.Canonical.InverseKernelCartanCore
import InfoGeometry.Canonical.SuperchargeCentralChargeClosure
import InfoGeometry.Meta.Architecture

open scoped InnerProductSpace

namespace InfoGeometry.Canonical.DrazinSupercharge

open InfoGeometry.Canonical

variable {E : Type*}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "EndH" => E →L[ℝ] E

noncomputable local instance : NormedRing EndH := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndH := inferInstance
noncomputable local instance : NormedAlgebra ℚ EndH :=
  NormedAlgebra.restrictScalars ℚ ℝ EndH
local instance : IsTopologicalRing EndH := inferInstance
local instance : SMulCommClass ℝ EndH EndH := inferInstance
local instance : IsScalarTower ℝ EndH EndH := inferInstance

/-- Repo-owned commutator. -/
@[rep_depth operator]
def commutator (X Y : EndH) : EndH := X * Y - Y * X

/-- Repo-owned anticommutator. -/
@[rep_depth operator]
def anticommutator (X Y : EndH) : EndH := X * Y + Y * X

/-- Krein-depth bridge wrapper for the commutator surface. -/
@[rep_depth krein]
def commutatorK (X Y : EndH) : EndH := commutator X Y

/-- Krein-depth bridge wrapper for the anticommutator surface. -/
@[rep_depth krein]
def anticommutatorK (X Y : EndH) : EndH := anticommutator X Y

namespace CertifiedInverseKernel

variable (CIK : CertifiedInverseKernel E)

/--
The canonical odd generator already latent in the certified inverse kernel:
`Q := χ_R - χ_L`.
-/
@[rep_depth operator]
def supercharge : EndH :=
  CIK.rightChiralAnomaly - CIK.chiralAnomaly

/--
Equivalent commutator presentation:
`Q = 2 • [P_D, G]`.
-/
theorem supercharge_eq_two_smul_commutator_spectralProjector_dilationGap :
    supercharge CIK = (2 : ℝ) • commutator CIK.spectralProjector CIK.dilationGap := by
  have h :=
    congrArg (fun Z : EndH => (2 : ℝ) • Z)
      CIK.spectralProjector_commutator_dilationGap_eq_half_sub_anomalies
  simpa [supercharge, commutator, smul_smul] using h.symm

/-- Krein-depth bridge form of `Q = 2 • [P_D, G]`. -/
@[rep_depth krein]
theorem supercharge_eq_two_smul_commutatorK_spectralProjector_dilationGap :
    supercharge CIK = (2 : ℝ) • commutatorK CIK.spectralProjector CIK.dilationGap := by
  simpa [commutatorK] using
    supercharge_eq_two_smul_commutator_spectralProjector_dilationGap (CIK := CIK)

/--
The supercharge is odd with respect to the spectral grading:
`{Γ_S, Q} = 0`.
-/
theorem supercharge_is_odd :
    anticommutator CIK.toInformationCartanTriple.GammaS (supercharge CIK) = 0 := by
  let ΓS := CIK.toInformationCartanTriple.GammaS
  have hR :
      CIK.rightChiralAnomaly * ΓS = -(ΓS * CIK.rightChiralAnomaly) := by
    simpa [ΓS] using CIK.rightChiralAnomaly_anticommutes_GammaS
  have hL :
      CIK.chiralAnomaly * ΓS = -(ΓS * CIK.chiralAnomaly) := by
    simpa [ΓS] using CIK.chiralAnomaly_anticommutes_GammaS
  unfold anticommutator supercharge
  calc
    CIK.toInformationCartanTriple.GammaS *
          (CIK.rightChiralAnomaly - CIK.chiralAnomaly)
        +
        (CIK.rightChiralAnomaly - CIK.chiralAnomaly) *
          CIK.toInformationCartanTriple.GammaS
      =
        (CIK.toInformationCartanTriple.GammaS * CIK.rightChiralAnomaly
            + CIK.rightChiralAnomaly * CIK.toInformationCartanTriple.GammaS)
          -
        (CIK.toInformationCartanTriple.GammaS * CIK.chiralAnomaly
            + CIK.chiralAnomaly * CIK.toInformationCartanTriple.GammaS) := by
          noncomm_ring
    _ = 0 := by
      rw [hR, hL]
      noncomm_ring

/-- Krein-depth bridge form of supercharge oddness. -/
@[rep_depth krein]
theorem supercharge_is_oddK :
    anticommutatorK CIK.toInformationCartanTriple.GammaS (supercharge CIK) = 0 := by
  simpa [anticommutatorK] using supercharge_is_odd (CIK := CIK)

/--
Derived sector statement: the supercharge lies in the spectral noncompact (`𝔭`) sector.
-/
theorem supercharge_isSpectralNonCompact :
    let T := CIK.toInformationCartanTriple
    T.IsSpectralNonCompact (supercharge CIK) := by
  let T := CIK.toInformationCartanTriple
  rw [CartanDecomposition.InformationCartanTriple.isSpectralNonCompact_iff_anticommute
        T CIK.hDrazin]
  have hOdd :
      anticommutator T.GammaS (supercharge CIK) = 0 := by
    simpa [T] using supercharge_is_odd CIK
  unfold anticommutator at hOdd
  have hOdd' :
      (supercharge CIK) * T.GammaS + T.GammaS * (supercharge CIK) = 0 := by
    simpa [add_comm] using hOdd
  exact eq_neg_of_add_eq_zero_left hOdd'

/-- Kinetic even operator generated by the odd supercharge. -/
@[rep_depth operator]
def superHamiltonian : EndH :=
  supercharge CIK * supercharge CIK

/-- Krein-depth bridge wrapper for the projected even generator `Q²`. -/
@[rep_depth krein]
def superHamiltonianK : EndH := superHamiltonian CIK

/--
Right-anticommutation form of the oddness law:
`Q * Γ_S = -(Γ_S * Q)`.
This is the algebraic input for the evenness of `Q²`.
-/
theorem supercharge_mul_GammaS_eq_neg :
    supercharge CIK * CIK.toInformationCartanTriple.GammaS =
      -(CIK.toInformationCartanTriple.GammaS * supercharge CIK) := by
  let T := CIK.toInformationCartanTriple
  have hQ : T.IsSpectralNonCompact (supercharge CIK) := by
    simpa [T] using supercharge_isSpectralNonCompact CIK
  exact
    (CartanDecomposition.InformationCartanTriple.isSpectralNonCompact_iff_anticommute
      T CIK.hDrazin).1 hQ

/--
The square of the odd supercharge commutes with the spectral grading:
`Q² * Γ_S = Γ_S * Q²`.
-/
theorem superHamiltonian_commutes_GammaS :
    superHamiltonian CIK * CIK.toInformationCartanTriple.GammaS =
      CIK.toInformationCartanTriple.GammaS * superHamiltonian CIK := by
  let T := CIK.toInformationCartanTriple
  have hAnti :
      supercharge CIK * T.GammaS = -(T.GammaS * supercharge CIK) := by
    simpa [T] using supercharge_mul_GammaS_eq_neg CIK
  unfold superHamiltonian
  calc
    (supercharge CIK * supercharge CIK) * T.GammaS
        = supercharge CIK * (supercharge CIK * T.GammaS) := by
            simp [mul_assoc]
    _ = supercharge CIK * (-(T.GammaS * supercharge CIK)) := by
          rw [hAnti]
    _ = -(supercharge CIK * (T.GammaS * supercharge CIK)) := by
          simp
    _ = -((supercharge CIK * T.GammaS) * supercharge CIK) := by
          simp [mul_assoc]
    _ = -((-(T.GammaS * supercharge CIK)) * supercharge CIK) := by
          rw [hAnti]
    _ = (T.GammaS * supercharge CIK) * supercharge CIK := by
          simp
    _ = T.GammaS * (supercharge CIK * supercharge CIK) := by
          simp [mul_assoc]

/--
The kinetic operator `Q²` lies in the spectral compact/even sector.
-/
theorem superHamiltonian_isSpectralCompact :
    let T := CIK.toInformationCartanTriple
    T.IsSpectralCompact (superHamiltonian CIK) := by
  let T := CIK.toInformationCartanTriple
  rw [CartanDecomposition.InformationCartanTriple.isSpectralCompact_iff_commute
        T CIK.hDrazin]
  simpa [T] using superHamiltonian_commutes_GammaS CIK

/--
Equivalently: the spectral Cartan involution fixes `Q²`.
-/
theorem thetaS_superHamiltonian :
    let T := CIK.toInformationCartanTriple
    T.thetaS (superHamiltonian CIK) = superHamiltonian CIK := by
  let T := CIK.toInformationCartanTriple
  show T.IsSpectralCompact (superHamiltonian CIK)
  simpa [T] using superHamiltonian_isSpectralCompact CIK

/--
The grading adjoint flow fixes the kinetic operator `Q²`.
This is the first flow-level consequence of evenness.
-/
theorem superHamiltonian_fixed_under_spectralGradingFlow
    (t : ℝ) :
    let T := CIK.toInformationCartanTriple
    T.spectralAdjointFlow T.GammaS t (superHamiltonian CIK) = superHamiltonian CIK := by
  let T := CIK.toInformationCartanTriple
  have hComm : Commute (superHamiltonian CIK) T.GammaS := by
    simpa [T] using superHamiltonian_commutes_GammaS CIK
  simpa [T] using
    T.spectralAdjointFlow_eq_self_of_commute_GammaS hComm t

/-- Krein-depth bridge: evenness of the projected generator. -/
@[rep_depth krein]
theorem superHamiltonianK_isSpectralCompact :
    let T := CIK.toInformationCartanTriple
    T.IsSpectralCompact (superHamiltonianK CIK) := by
  simpa [superHamiltonianK] using superHamiltonian_isSpectralCompact (CIK := CIK)

/-- Krein-depth bridge: grading-flow fixedness of the projected generator. -/
@[rep_depth krein]
theorem superHamiltonianK_fixed_under_spectralGradingFlow
    (t : ℝ) :
    let T := CIK.toInformationCartanTriple
    T.spectralAdjointFlow T.GammaS t (superHamiltonianK CIK) = superHamiltonianK CIK := by
  simpa [superHamiltonianK] using
    superHamiltonian_fixed_under_spectralGradingFlow (CIK := CIK) t

/--
The superHamiltonian commutes with the full grading flow.
-/
theorem superHamiltonian_commutes_spectralGradingFlow
    (t : ℝ) :
    let T := CIK.toInformationCartanTriple
    Commute (superHamiltonian CIK) (T.spectralGradingFlow t) := by
  let T := CIK.toInformationCartanTriple
  have hComm : Commute (superHamiltonian CIK) T.GammaS := by
    simpa [T] using superHamiltonian_commutes_GammaS CIK
  simpa [T] using
    T.commute_spectralGradingFlow_of_commute_GammaS hComm t

/--
Defect-support predicate on the Drazin singular block.

`Z` is defect-supported when its full action is carried by the complementary
spectral projector `Q₀ = 1 - P_D`.
-/
@[rep_depth operator]
def IsDefectSupported (Z : EndH) : Prop :=
  CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector = Z

/-- Krein-depth bridge wrapper for defect support. -/
@[rep_depth krein]
def IsDefectSupportedK (Z : EndH) : Prop := IsDefectSupported CIK Z

/--
Vanishing-defect-block predicate for a kinetic candidate.

`H` has no singular Drazin block when its `Q₀`-compressed component is zero.
-/
@[rep_depth operator]
def HasVanishingDefectBlock (H : EndH) : Prop :=
  CIK.spectralComplementaryProjector * H * CIK.spectralComplementaryProjector = 0

/-- Krein-depth bridge wrapper for vanishing defect block. -/
@[rep_depth krein]
def HasVanishingDefectBlockK (H : EndH) : Prop := HasVanishingDefectBlock CIK H

/--
Internal centrality predicate for the Drazin spectral lane.

`Z` is central on this lane when it commutes with both the regular and defect
spectral projectors.
-/
@[rep_depth operator]
def IsDrazinSpectralCentral (Z : EndH) : Prop :=
  Commute Z CIK.spectralProjector
    ∧ Commute Z CIK.spectralComplementaryProjector

/-- Krein-depth bridge wrapper for Drazin spectral centrality. -/
@[rep_depth krein]
def IsDrazinSpectralCentralK (Z : EndH) : Prop := IsDrazinSpectralCentral CIK Z

/--
Centrality predicate for the full Drazin algebra lane.

This extends spectral-projector centrality by requiring commutation with the
spectral grading `Γ_S`.
-/
@[rep_depth operator]
def IsDrazinLaneCentral (Z : EndH) : Prop :=
  IsDrazinSpectralCentral CIK Z
    ∧ Commute Z CIK.toInformationCartanTriple.GammaS

/-- Krein-depth bridge wrapper for full Drazin-lane centrality. -/
@[rep_depth krein]
def IsDrazinLaneCentralK (Z : EndH) : Prop := IsDrazinLaneCentral CIK Z

/--
Canonical defect-supported extraction from `Q²`.

This is the singular-block compression of the projected superHamiltonian.
-/
@[rep_depth operator]
def canonicalDefectCentral : EndH :=
  CIK.spectralComplementaryProjector * superHamiltonian CIK * CIK.spectralComplementaryProjector

/--
Canonical kinetic remainder after removing the defect-supported central channel.
-/
@[rep_depth operator]
def canonicalKineticPart : EndH :=
  superHamiltonian CIK - canonicalDefectCentral CIK

/-- The canonical defect-central part is supported on the defect block. -/
@[rep_depth operator]
theorem canonicalDefectCentral_isDefectSupported :
    IsDefectSupported CIK (canonicalDefectCentral CIK) := by
  set Q0 : EndH := CIK.spectralComplementaryProjector
  set SH : EndH := superHamiltonian CIK
  have hQ0 : Q0 * Q0 = Q0 := by
    simpa [Q0] using CIK.spectralComplementaryProjector_idempotent
  unfold IsDefectSupported canonicalDefectCentral
  change Q0 * (Q0 * SH * Q0) * Q0 = Q0 * SH * Q0
  calc
    Q0 * (Q0 * SH * Q0) * Q0 = ((Q0 * Q0) * SH) * (Q0 * Q0) := by
      simp [mul_assoc]
    _ = (Q0 * SH) * Q0 := by
      simpa [hQ0, mul_assoc]
    _ = Q0 * SH * Q0 := by
      simp [mul_assoc]

/-- The canonical kinetic remainder has vanishing defect block. -/
@[rep_depth operator]
theorem canonicalKineticPart_hasVanishingDefectBlock :
    HasVanishingDefectBlock CIK (canonicalKineticPart CIK) := by
  set Q0 : EndH := CIK.spectralComplementaryProjector
  set SH : EndH := superHamiltonian CIK
  have hQ0 : Q0 * Q0 = Q0 := by
    simpa [Q0] using CIK.spectralComplementaryProjector_idempotent
  unfold HasVanishingDefectBlock canonicalKineticPart canonicalDefectCentral
  change Q0 * (SH - Q0 * SH * Q0) * Q0 = 0
  have hcompress : Q0 * (Q0 * SH * Q0) * Q0 = Q0 * SH * Q0 := by
    calc
      Q0 * (Q0 * SH * Q0) * Q0 = ((Q0 * Q0) * SH) * (Q0 * Q0) := by
        simp [mul_assoc]
      _ = (Q0 * SH) * Q0 := by
        simpa [hQ0, mul_assoc]
      _ = Q0 * SH * Q0 := by
        simp [mul_assoc]
  calc
    Q0 * (SH - Q0 * SH * Q0) * Q0
        = Q0 * SH * Q0 - Q0 * (Q0 * SH * Q0) * Q0 := by
            simp [mul_sub, sub_mul, mul_assoc]
    _ = Q0 * SH * Q0 - Q0 * SH * Q0 := by
          simpa [hcompress]
    _ = 0 := by simp

/--
Defect support implies left compression by the complementary projector.
-/
@[rep_depth operator]
theorem spectralComplementaryProjector_mul_eq_of_isDefectSupported
    {Z : EndH}
    (hDefect : IsDefectSupported CIK Z) :
    CIK.spectralComplementaryProjector * Z = Z := by
  have hQ0 : CIK.spectralComplementaryProjector * CIK.spectralComplementaryProjector
      = CIK.spectralComplementaryProjector := CIK.spectralComplementaryProjector_idempotent
  unfold IsDefectSupported at hDefect
  calc
    CIK.spectralComplementaryProjector * Z
        = CIK.spectralComplementaryProjector
            * (CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector) := by
              rw [hDefect]
    _ = (CIK.spectralComplementaryProjector * CIK.spectralComplementaryProjector) * Z
          * CIK.spectralComplementaryProjector := by
            simp [mul_assoc]
    _ = CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector := by
          simpa [hQ0, mul_assoc]
    _ = Z := hDefect

/--
Defect support implies right compression by the complementary projector.
-/
@[rep_depth operator]
theorem mul_spectralComplementaryProjector_eq_of_isDefectSupported
    {Z : EndH}
    (hDefect : IsDefectSupported CIK Z) :
    Z * CIK.spectralComplementaryProjector = Z := by
  have hQ0 : CIK.spectralComplementaryProjector * CIK.spectralComplementaryProjector
      = CIK.spectralComplementaryProjector := CIK.spectralComplementaryProjector_idempotent
  unfold IsDefectSupported at hDefect
  calc
    Z * CIK.spectralComplementaryProjector
        = (CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector)
            * CIK.spectralComplementaryProjector := by
              rw [hDefect]
    _ = CIK.spectralComplementaryProjector * Z
          * (CIK.spectralComplementaryProjector * CIK.spectralComplementaryProjector) := by
            simp [mul_assoc]
    _ = CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector := by
          simpa [hQ0, mul_assoc]
    _ = Z := hDefect

/--
Defect support forces annihilation by the regular Drazin projector on the left.
-/
@[rep_depth operator]
theorem spectralProjector_mul_eq_zero_of_isDefectSupported
    {Z : EndH}
    (hDefect : IsDefectSupported CIK Z) :
    CIK.spectralProjector * Z = 0 := by
  unfold IsDefectSupported at hDefect
  calc
    CIK.spectralProjector * Z
        = CIK.spectralProjector
            * (CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector) := by
              conv_lhs => rw [← hDefect]
    _ = ((CIK.spectralProjector * CIK.spectralComplementaryProjector) * Z)
          * CIK.spectralComplementaryProjector := by
            simp [mul_assoc]
    _ = 0 := by
          simp [CIK.spectralProjector_mul_spectralComplementaryProjector]

/--
Defect support forces annihilation by the regular Drazin projector on the right.
-/
@[rep_depth operator]
theorem mul_spectralProjector_eq_zero_of_isDefectSupported
    {Z : EndH}
    (hDefect : IsDefectSupported CIK Z) :
    Z * CIK.spectralProjector = 0 := by
  unfold IsDefectSupported at hDefect
  calc
    Z * CIK.spectralProjector
        = (CIK.spectralComplementaryProjector * Z * CIK.spectralComplementaryProjector)
            * CIK.spectralProjector := by
              conv_lhs => rw [← hDefect]
    _ = CIK.spectralComplementaryProjector
          * Z * (CIK.spectralComplementaryProjector * CIK.spectralProjector) := by
            simp [mul_assoc]
    _ = 0 := by
          simp [CIK.spectralComplementaryProjector_mul_spectralProjector]

/--
Any defect-supported operator is central on the internal Drazin spectral lane.
-/
@[rep_depth operator]
theorem isDrazinSpectralCentral_of_isDefectSupported
    {Z : EndH}
    (hDefect : IsDefectSupported CIK Z) :
    IsDrazinSpectralCentral CIK Z := by
  refine ⟨?_, ?_⟩
  ·
    have hLeft :
        CIK.spectralProjector * Z = 0 :=
      spectralProjector_mul_eq_zero_of_isDefectSupported (CIK := CIK) hDefect
    have hRight :
        Z * CIK.spectralProjector = 0 :=
      mul_spectralProjector_eq_zero_of_isDefectSupported (CIK := CIK) hDefect
    calc
      Z * CIK.spectralProjector = 0 := hRight
      _ = CIK.spectralProjector * Z := by simpa [hLeft]
  ·
    have hLeft :
        CIK.spectralComplementaryProjector * Z = Z :=
      spectralComplementaryProjector_mul_eq_of_isDefectSupported (CIK := CIK) hDefect
    have hRight :
        Z * CIK.spectralComplementaryProjector = Z :=
      mul_spectralComplementaryProjector_eq_of_isDefectSupported (CIK := CIK) hDefect
    calc
      Z * CIK.spectralComplementaryProjector = Z := hRight
      _ = CIK.spectralComplementaryProjector * Z := hLeft.symm

/--
Spectral centrality implies commutation with the spectral grading `Γ_S`.
-/
@[rep_depth operator]
theorem commute_GammaS_of_isDrazinSpectralCentral
    {Z : EndH}
    (hCentral : IsDrazinSpectralCentral CIK Z) :
    Commute Z CIK.toInformationCartanTriple.GammaS := by
  rcases hCentral with ⟨hP, hQ0⟩
  have hGamma :
      CIK.toInformationCartanTriple.GammaS
        = CIK.spectralProjector - CIK.spectralComplementaryProjector := by
    simpa [CertifiedInverseKernel.GammaS] using
      CIK.GammaS_eq_spectralProjector_sub_spectralComplementaryProjector
  calc
    Z * CIK.toInformationCartanTriple.GammaS
        = Z * (CIK.spectralProjector - CIK.spectralComplementaryProjector) := by rw [hGamma]
    _ = Z * CIK.spectralProjector - Z * CIK.spectralComplementaryProjector := by
          simp [mul_sub]
    _ = CIK.spectralProjector * Z - CIK.spectralComplementaryProjector * Z := by
          rw [hP.eq, hQ0.eq]
    _ = (CIK.spectralProjector - CIK.spectralComplementaryProjector) * Z := by
          simp [sub_mul]
    _ = CIK.toInformationCartanTriple.GammaS * Z := by rw [hGamma]

/-- The canonical defect-central extraction is central on the Drazin spectral lane. -/
@[rep_depth operator]
theorem canonicalDefectCentral_isDrazinSpectralCentral :
    IsDrazinSpectralCentral CIK (canonicalDefectCentral CIK) := by
  exact isDrazinSpectralCentral_of_isDefectSupported (CIK := CIK)
    (canonicalDefectCentral_isDefectSupported (CIK := CIK))

/-- The canonical defect-central extraction is central on the full Drazin algebra lane. -/
@[rep_depth operator]
theorem canonicalDefectCentral_isDrazinLaneCentral :
    IsDrazinLaneCentral CIK (canonicalDefectCentral CIK) := by
  refine ⟨canonicalDefectCentral_isDrazinSpectralCentral (CIK := CIK), ?_⟩
  exact commute_GammaS_of_isDrazinSpectralCentral (CIK := CIK)
    (canonicalDefectCentral_isDrazinSpectralCentral (CIK := CIK))

/--
Internal operator-valued Drazin split:
`Q² = H + Z` with `Z` canonically extracted from the singular block.
-/
@[rep_depth operator]
theorem superHamiltonian_eq_canonicalKinetic_plus_canonicalDefectCentral :
    superHamiltonian CIK
      = canonicalKineticPart (CIK := CIK) + canonicalDefectCentral CIK := by
  unfold canonicalKineticPart
  exact (sub_add_cancel (superHamiltonian CIK) (canonicalDefectCentral CIK)).symm

/--
Canonical existence form of the Drazin central split `Q² = H + Z`.
-/
@[rep_depth operator]
theorem exists_superHamiltonian_canonical_split :
    ∃ H Z : EndH,
      IsDefectSupported CIK Z
        ∧ HasVanishingDefectBlock CIK H
        ∧ superHamiltonian CIK = H + Z := by
  refine ⟨canonicalKineticPart (CIK := CIK), canonicalDefectCentral CIK, ?_, ?_, ?_⟩
  · exact canonicalDefectCentral_isDefectSupported (CIK := CIK)
  · exact canonicalKineticPart_hasVanishingDefectBlock (CIK := CIK)
  · exact superHamiltonian_eq_canonicalKinetic_plus_canonicalDefectCentral (CIK := CIK)

/-- Krein-depth bridge form of the canonical internal split `Q² = H + Z`. -/
@[rep_depth krein]
theorem exists_superHamiltonian_canonical_splitK :
    ∃ H Z : EndH,
      IsDefectSupportedK CIK Z
        ∧ HasVanishingDefectBlockK CIK H
        ∧ superHamiltonianK CIK = H + Z := by
  rcases exists_superHamiltonian_canonical_split (CIK := CIK) with
    ⟨H, Z, hDef, hVan, hSplit⟩
  exact ⟨H, Z, hDef, hVan, by simpa [superHamiltonianK] using hSplit⟩

/--
Canonical Drazin split with an internal spectral centrality witness for `Z`.
-/
@[rep_depth operator]
theorem exists_superHamiltonian_canonical_split_with_spectral_centrality :
    ∃ H Z : EndH,
      IsDrazinSpectralCentral CIK Z
        ∧ IsDefectSupported CIK Z
        ∧ HasVanishingDefectBlock CIK H
        ∧ superHamiltonian CIK = H + Z := by
  refine ⟨canonicalKineticPart (CIK := CIK), canonicalDefectCentral CIK, ?_, ?_, ?_, ?_⟩
  · exact canonicalDefectCentral_isDrazinSpectralCentral (CIK := CIK)
  · exact canonicalDefectCentral_isDefectSupported (CIK := CIK)
  · exact canonicalKineticPart_hasVanishingDefectBlock (CIK := CIK)
  · exact superHamiltonian_eq_canonicalKinetic_plus_canonicalDefectCentral (CIK := CIK)

/-- Krein-depth bridge form of the centralized canonical split `Q² = H + Z`. -/
@[rep_depth krein]
theorem exists_superHamiltonian_canonical_split_with_spectral_centralityK :
    ∃ H Z : EndH,
      IsDrazinSpectralCentralK CIK Z
        ∧ IsDefectSupportedK CIK Z
        ∧ HasVanishingDefectBlockK CIK H
        ∧ superHamiltonianK CIK = H + Z := by
  rcases exists_superHamiltonian_canonical_split_with_spectral_centrality (CIK := CIK) with
    ⟨H, Z, hCentral, hDef, hVan, hSplit⟩
  exact ⟨H, Z, hCentral, hDef, hVan, by simpa [superHamiltonianK] using hSplit⟩

/--
Canonical Drazin split with full Drazin-lane centrality witness for `Z`.
-/
@[rep_depth operator]
theorem exists_superHamiltonian_canonical_split_with_drazin_lane_centrality :
    ∃ H Z : EndH,
      IsDrazinLaneCentral CIK Z
        ∧ IsDefectSupported CIK Z
        ∧ HasVanishingDefectBlock CIK H
        ∧ superHamiltonian CIK = H + Z := by
  refine ⟨canonicalKineticPart (CIK := CIK), canonicalDefectCentral CIK, ?_, ?_, ?_, ?_⟩
  · exact canonicalDefectCentral_isDrazinLaneCentral (CIK := CIK)
  · exact canonicalDefectCentral_isDefectSupported (CIK := CIK)
  · exact canonicalKineticPart_hasVanishingDefectBlock (CIK := CIK)
  · exact superHamiltonian_eq_canonicalKinetic_plus_canonicalDefectCentral (CIK := CIK)

/--
Krein-depth bridge form of the Drazin-lane centralized canonical split `Q² = H + Z`.
-/
@[rep_depth krein]
theorem exists_superHamiltonian_canonical_split_with_drazin_lane_centralityK :
    ∃ H Z : EndH,
      IsDrazinLaneCentralK CIK Z
        ∧ IsDefectSupportedK CIK Z
        ∧ HasVanishingDefectBlockK CIK H
        ∧ superHamiltonianK CIK = H + Z := by
  rcases exists_superHamiltonian_canonical_split_with_drazin_lane_centrality (CIK := CIK) with
    ⟨H, Z, hCentral, hDef, hVan, hSplit⟩
  exact ⟨H, Z, hCentral, hDef, hVan, by simpa [superHamiltonianK] using hSplit⟩

/--
Uniqueness of the canonical defect-central extraction:
any split with defect-supported `Z` and vanishing-defect-block `H`
must recover `Z = Q₀ Q² Q₀`.
-/
@[rep_depth operator]
theorem defectCentral_eq_of_split
    {H Z : EndH}
    (hDefect : IsDefectSupported CIK Z)
    (hKinetic : HasVanishingDefectBlock CIK H)
    (hSplit : superHamiltonian CIK = H + Z) :
    Z = canonicalDefectCentral CIK := by
  unfold IsDefectSupported at hDefect
  unfold HasVanishingDefectBlock at hKinetic
  unfold canonicalDefectCentral
  have hQSplit :
      CIK.spectralComplementaryProjector * superHamiltonian CIK *
          CIK.spectralComplementaryProjector
        =
      CIK.spectralComplementaryProjector * H *
          CIK.spectralComplementaryProjector
        +
      CIK.spectralComplementaryProjector * Z *
          CIK.spectralComplementaryProjector := by
    rw [hSplit]
    simp [add_mul, mul_add, mul_assoc]
  calc
    Z = CIK.spectralComplementaryProjector * Z *
          CIK.spectralComplementaryProjector := by
          symm
          exact hDefect
    _ =
      CIK.spectralComplementaryProjector * H *
          CIK.spectralComplementaryProjector
        +
      CIK.spectralComplementaryProjector * Z *
          CIK.spectralComplementaryProjector := by
            rw [hKinetic]
            simp
    _ =
      CIK.spectralComplementaryProjector * superHamiltonian CIK *
          CIK.spectralComplementaryProjector := by
            exact hQSplit.symm

/-- Uniqueness of the canonical kinetic remainder under the split axioms. -/
@[rep_depth operator]
theorem canonicalKineticPart_eq_of_split
    {H Z : EndH}
    (hDefect : IsDefectSupported CIK Z)
    (hKinetic : HasVanishingDefectBlock CIK H)
    (hSplit : superHamiltonian CIK = H + Z) :
    H = canonicalKineticPart (CIK := CIK) := by
  have hZ : Z = canonicalDefectCentral CIK :=
    defectCentral_eq_of_split (CIK := CIK) hDefect hKinetic hSplit
  have hH : H = superHamiltonian CIK - Z := by
    calc
      H = (H + Z) - Z := by simp
      _ = superHamiltonian CIK - Z := by rw [← hSplit]
  rw [hH, hZ]
  rfl

/-- Any two lawful defect/kinetic splits are equal to the canonical one. -/
@[rep_depth operator]
theorem canonical_split_unique
    {H₁ Z₁ H₂ Z₂ : EndH}
    (hDefect₁ : IsDefectSupported CIK Z₁)
    (hKinetic₁ : HasVanishingDefectBlock CIK H₁)
    (hSplit₁ : superHamiltonian CIK = H₁ + Z₁)
    (hDefect₂ : IsDefectSupported CIK Z₂)
    (hKinetic₂ : HasVanishingDefectBlock CIK H₂)
    (hSplit₂ : superHamiltonian CIK = H₂ + Z₂) :
    H₁ = H₂ ∧ Z₁ = Z₂ := by
  have hH₁ :
      H₁ = canonicalKineticPart (CIK := CIK) :=
    canonicalKineticPart_eq_of_split (CIK := CIK) hDefect₁ hKinetic₁ hSplit₁
  have hH₂ :
      H₂ = canonicalKineticPart (CIK := CIK) :=
    canonicalKineticPart_eq_of_split (CIK := CIK) hDefect₂ hKinetic₂ hSplit₂
  have hZ₁ :
      Z₁ = canonicalDefectCentral CIK :=
    defectCentral_eq_of_split (CIK := CIK) hDefect₁ hKinetic₁ hSplit₁
  have hZ₂ :
      Z₂ = canonicalDefectCentral CIK :=
    defectCentral_eq_of_split (CIK := CIK) hDefect₂ hKinetic₂ hSplit₂
  constructor
  · calc
      H₁ = canonicalKineticPart (CIK := CIK) := hH₁
      _ = H₂ := hH₂.symm
  · calc
      Z₁ = canonicalDefectCentral CIK := hZ₁
      _ = Z₂ := hZ₂.symm

end CertifiedInverseKernel

section CentralSupercharge

open InfoGeometry.Canonical.SuperchargeCentralChargeClosure
open InfoGeometry.Canonical.OperatorialCentralCharge
open InfoGeometry.Canonical.BogoliubovVielbein
open InfoGeometry.Canonical.SuperchargeGapHessianBridge
open InfoGeometry.Canonical.RelationalInformationDynamics
open InfoGeometry.Canonical.BogoliubovTransport
open InfoGeometry.KK
open InfoGeometry.KK.RealSplitKreinKasparovCycle
open InfoGeometry.Krein

variable {A B F : Type}
variable [NormedRing A] [NormedRing B]
variable [NormedAlgebra ℝ A] [NormedAlgebra ℝ B]
variable [NormedAddCommGroup F] [InnerProductSpace ℝ F] [CompleteSpace F]
variable [KreinSpace (DoubledSpace F)] [KreinGradedModule (DoubledSpace F)]

local notation "H₂" => DoubledSpace F

/--
Central supercharge theorem (repo-native root form):

1. root transported gap/Hessian closure (contains the root Lichnerowicz split),
2. transported analytical index equals operatorial central charge,
3. nonzero central charge forces nonvanishing transported index.
-/
@[rep_depth transport]
theorem central_supercharge_theorem
    (V : BogoliubovVielbeinBundle (E := F))
    (X : RealSplitKreinDiracFredholmModule A B H₂)
    (hX : ChiralFredholmSurface X)
    (hEven : KreinGradedModule.IsEven (H := H₂) V.connectionGenerator)
    (t : ℝ) :
    rootGapHessianClosure (E := F) V
      ∧
    (quasilatticeAnalyticalIndex V X t
        (quasilatticeChiralFredholmSurfaceOf (E := F) V X hX hEven t)
      =
    operatorialCentralCharge (A := A) (B := B) (E := F) X hX)
      ∧
    (operatorialCentralCharge (A := A) (B := B) (E := F) X hX ≠ 0 →
      quasilatticeAnalyticalIndex V X t
          (quasilatticeChiralFredholmSurfaceOf (E := F) V X hX hEven t)
        ≠ 0) := by
  exact root_gap_hessian_centralCharge_closure
    (A := A) (B := B) (E := F) V X hX hEven t

/--
Integrated central supercharge closure:
the local Drazin superHamiltonian `Q²` is spectrally even and grading-flow
fixed, and the root transported supercharge lane carries the
Lichnerowicz/central-charge closure package.
-/
@[rep_depth transport]
theorem central_supercharge_theorem_with_drazin_evenness
    (CIK : InfoGeometry.Canonical.CertifiedInverseKernel (DoubledSpace F))
    (V : BogoliubovVielbeinBundle (E := F))
    (X : RealSplitKreinDiracFredholmModule A B H₂)
    (hX : ChiralFredholmSurface X)
    (hEven : KreinGradedModule.IsEven (H := H₂) V.connectionGenerator)
    (τ t : ℝ) :
    (let T := CIK.toInformationCartanTriple;
      T.IsSpectralCompact
          (InfoGeometry.Canonical.DrazinSupercharge.CertifiedInverseKernel.superHamiltonianK CIK)
        ∧
      T.spectralAdjointFlow T.GammaS τ
          (InfoGeometry.Canonical.DrazinSupercharge.CertifiedInverseKernel.superHamiltonianK CIK)
        =
      InfoGeometry.Canonical.DrazinSupercharge.CertifiedInverseKernel.superHamiltonianK CIK)
      ∧
    rootGapHessianClosure (E := F) V
      ∧
    (quasilatticeAnalyticalIndex V X t
        (quasilatticeChiralFredholmSurfaceOf (E := F) V X hX hEven t)
      =
    operatorialCentralCharge (A := A) (B := B) (E := F) X hX)
      ∧
    (operatorialCentralCharge (A := A) (B := B) (E := F) X hX ≠ 0 →
      quasilatticeAnalyticalIndex V X t
          (quasilatticeChiralFredholmSurfaceOf (E := F) V X hX hEven t)
        ≠ 0) := by
  refine ⟨?_, ?_⟩
  · refine ⟨?_, ?_⟩
    · simpa using
        (InfoGeometry.Canonical.DrazinSupercharge.CertifiedInverseKernel.superHamiltonianK_isSpectralCompact
          (CIK := CIK))
    · simpa using
        (InfoGeometry.Canonical.DrazinSupercharge.CertifiedInverseKernel.superHamiltonianK_fixed_under_spectralGradingFlow
          (CIK := CIK) τ)
  · exact central_supercharge_theorem
      (A := A) (B := B) (F := F) V X hX hEven t

end CentralSupercharge

end InfoGeometry.Canonical.DrazinSupercharge
