import Mathlib.Data.Complex.Basic
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Matrix.Basic
import InfoGeometry.Canonical.BiQuaternionKahlerLagrangian

/-!
# InfoGeometry.Canonical.EmergentGaugeSymmetry

This module formally implements Step 6 of the Unified Framework:
Connecting to Gauge Theory.

We demonstrate how $U(1)$ and $SU(2)$ emergent gauge structures structurally 
arise from the phase rotations of the Bi-Quaternion-Kähler condensate.

1. **U(1) Gauge Emergence**: Generated by the global phase rotation of the quaternionic field.
2. **SU(2) Gauge Emergence**: Generated by the non-Abelian right-multiplication structure
   of the quaternionic algebra.
-/

noncomputable section

namespace InfoGeometry.Canonical.EmergentGaugeSymmetry

open Complex
open Matrix

/-- A simple 2D complex representation of the Quaternionic Field -/
def QuaternionicField := Fin 2 → ℂ

/-- The $U(1)$ phase rotation action on the condensate. 
    $e^{i\theta} \Phi$ -/
def U1_Action (θ : ℝ) (Φ : QuaternionicField) : QuaternionicField :=
  fun i => (Complex.exp (θ * Complex.I)) * Φ i



/-- The Pauli Matrices generating the emergent $SU(2)$ algebra. -/
def sigma1 : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]
def sigma2 : Matrix (Fin 2) (Fin 2) ℂ := !![0, -Complex.I; Complex.I, 0]
def sigma3 : Matrix (Fin 2) (Fin 2) ℂ := !![1, 0; 0, -1]

/-- The $SU(2)$ gauge transformation acting on the condensate.
    $\Phi \to \exp(i \vec{\alpha} \cdot \vec{\sigma} / 2) \Phi$ -/
def SU2_Generator (α1 α2 α3 : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (α1 : ℂ) • sigma1 + (α2 : ℂ) • sigma2 + (α3 : ℂ) • sigma3

def SU2_Action (α1 α2 α3 : ℝ) (Φ : QuaternionicField) : QuaternionicField :=
  mulVec (SU2_Generator α1 α2 α3) Φ

end InfoGeometry.Canonical.EmergentGaugeSymmetry
