import InfoGeometry.Canonical.FilteredQCCRParameterTopologicalColimit

/-!
# Compatible q-CCR points and their filtered TopCat colimit map

This owner isolates the universal-property step for a compatible family of
finite-stage q-CCR witnesses.  No stage is replaced by a scalar model: the
family lives in the closed noncommutative zero-fibres, and its global map is
the `TopCat` colimit map induced by naturality.
-/

noncomputable section

namespace InfoGeometry.Canonical.FilteredQCCRCompatiblePointColimit

universe u

open CategoryTheory CategoryTheory.Limits
open InfoGeometry.OperatorAlgebra.QCCRResidual
open InfoGeometry.Canonical.CStarCuntzCARCCRParameterTopCat
open InfoGeometry.Canonical.FilteredQCCRParameterTopologicalColimit
open CStarStateColimit.Native
open FilteredColimit.Native.Topological

variable {I : Type u} [Preorder I]
variable {Stage : I → Type u}
variable [∀ i, CStarAlgebra (Stage i)]
variable [∀ i, PartialOrder (Stage i)]
variable [∀ i, StarOrderedRing (Stage i)]
variable (sys : ContinuousStarInductiveSystem Stage)

/-- A point of every finite zero-fibre, compatible with every transition. -/
structure CompatibleQCCRPointFamily
    (sys : ContinuousStarInductiveSystem Stage) where
  point : ∀ i, {p : QCCRParameterSpace (Stage i) //
    p ∈ qCcrParameterZeroLocus (A := Stage i)}

def compatiblePointNatTrans
    (family : CompatibleQCCRPointFamily sys)
    (hcompatible : ∀ {i j : I} (hij : i ≤ j),
      qCcrParameterZeroFiberTransitionMap Stage sys hij (family.point i) =
        family.point j) :
    (Functor.const I).obj (TopCat.of PUnit) ⟶
      qCcrParameterZeroFiberTopologicalDiagram Stage sys where
  app i := TopCat.ofHom
    { toFun := fun _ => family.point i
      continuous_toFun := continuous_const }
  naturality := by
    intro i j f
    apply TopCat.hom_ext
    apply ContinuousMap.ext
    intro u
    apply Subtype.ext
    change (family.point j).1 =
      (qCcrParameterZeroFiberTransitionMap Stage sys (leOfHom f)
        (family.point i)).1
    exact congrArg Subtype.val (hcompatible (leOfHom f)).symm

/-- The colimit map generated by a compatible finite-stage point family. -/
noncomputable def compatiblePointColimitMap
    (family : CompatibleQCCRPointFamily sys)
    (hcompatible : ∀ {i j : I} (hij : i ≤ j),
      qCcrParameterZeroFiberTransitionMap Stage sys hij (family.point i) =
        family.point j) :
    colimit ((Functor.const I).obj (TopCat.of PUnit)) ⟶
      qCcrParameterZeroFiberTopologicalColimit Stage sys :=
  colim.map (compatiblePointNatTrans sys family hcompatible)

theorem compatiblePointColimitMap_stage
    (family : CompatibleQCCRPointFamily sys)
    (hcompatible : ∀ {i j : I} (hij : i ≤ j),
      qCcrParameterZeroFiberTransitionMap Stage sys hij (family.point i) =
        family.point j)
    (i : I) :
    colimit.ι ((Functor.const I).obj (TopCat.of PUnit)) i ≫
        compatiblePointColimitMap sys family hcompatible =
      (compatiblePointNatTrans sys family hcompatible).app i ≫
        qCcrParameterZeroFiberTopologicalInjection Stage sys i := by
  change
    colimit.ι ((Functor.const I).obj (TopCat.of PUnit)) i ≫
        colim.map (compatiblePointNatTrans sys family hcompatible) =
      (compatiblePointNatTrans sys family hcompatible).app i ≫
        colimit.ι (qCcrParameterZeroFiberTopologicalDiagram Stage sys) i
  exact colimit.ι_map (compatiblePointNatTrans sys family hcompatible) i

theorem compatiblePointColimitMap_stage_apply
    (family : CompatibleQCCRPointFamily sys)
    (hcompatible : ∀ {i j : I} (hij : i ≤ j),
      qCcrParameterZeroFiberTransitionMap Stage sys hij (family.point i) =
        family.point j)
    (i : I) (u : PUnit) :
    compatiblePointColimitMap sys family hcompatible
        (colimit.ι ((Functor.const I).obj (TopCat.of PUnit)) i u) =
      qCcrParameterZeroFiberTopologicalInjection Stage sys i (family.point i) := by
  have h := compatiblePointColimitMap_stage sys family hcompatible i
  exact congrArg (fun f => f u) h

end InfoGeometry.Canonical.FilteredQCCRCompatiblePointColimit
