import InfoGeometry.Canonical.CuntzStarInductiveSystem
import InfoGeometry.Canonical.FilteredGNSHilbertColimit

/-!
# Fixed-index noncommutative Cuntz towers

`CuntzStarTower` records the finite-cutoff convention in which the generator
labels are `Fin n`.  This companion owner keeps the generator type fixed.  It
is useful for genuine noncommutative towers whose stages are different
realizations of one fixed Cuntz family; no diagonal or scalar model is
introduced here.
-/

noncomputable section

namespace InfoGeometry.Canonical.FixedIndexCuntzStarTower

open InfoGeometry.Physics.CStarCuntzTensorQuotient
open CStarStateColimit.Native
open CStarStateColimit.Native.FilteredGNS
open CStarStateColimit.Native.FilteredGNSHilbertColimit

variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable (Stage : ℕ → Type)
variable [∀ n, CStarAlgebra (Stage n)]

/-- A coherent fixed-generator Cuntz tower in C⋆-algebras. -/
structure Data where
  family : ∀ n, CStarCuntzFamily (Stage n) ι
  map : ∀ {m n : ℕ}, m ≤ n → Stage m →⋆ₐ[ℂ] Stage n
  map_id : ∀ n, map (le_refl n) = StarAlgHom.id ℂ (Stage n)
  map_comp : ∀ {m n k : ℕ} (hmn : m ≤ n) (hnk : n ≤ k),
    (map hnk).comp (map hmn) = map (le_trans hmn hnk)
  map_generator : ∀ {m n : ℕ} (hmn : m ≤ n) (i : ι),
    map hmn ((family m).S i) = (family n).S i

namespace Data

variable (T : Data (ι := ι) Stage)
variable [∀ n, PartialOrder (Stage n)]
variable [∀ n, StarOrderedRing (Stage n)]

/-- The fixed-index tower is a native complex star-inductive system. -/
def toContinuousStarInductiveSystem :
    ContinuousStarInductiveSystem (I := ℕ) Stage where
  map := T.map
  map_id := T.map_id
  map_comp := T.map_comp

@[simp] theorem map_apply {m n : ℕ} (hmn : m ≤ n) (a : Stage m) :
    (T.toContinuousStarInductiveSystem.map hmn) a = T.map hmn a := rfl

@[simp] theorem map_generator_apply {m n : ℕ} (hmn : m ≤ n) (i : ι) :
    T.map hmn ((T.family m).S i) = (T.family n).S i :=
  T.map_generator hmn i

@[simp] theorem map_generator_star {m n : ℕ} (hmn : m ≤ n) (i : ι) :
    T.map hmn (star ((T.family m).S i)) = star ((T.family n).S i) := by
  rw [map_star, T.map_generator hmn i]

@[simp] theorem map_projector {m n : ℕ} (hmn : m ≤ n) (i : ι) :
    T.map hmn ((T.family m).S i * star ((T.family m).S i)) =
      (T.family n).S i * star ((T.family n).S i) := by
  rw [map_mul, T.map_generator hmn i, map_star, T.map_generator hmn i]

end Data

section ConstantGeneratedTower

variable {A : Type} [CStarAlgebra A]

/-- The constant tower on the closed C⋆-subalgebra generated by one genuine
Cuntz family.  This is a noncommutative categorical witness; it makes no
claim about the missing analytic construction of a varying-cutoff tower. -/
def constantGeneratedTower (F : CStarCuntzFamily A ι) :
    Data (ι := ι) (fun _ : ℕ => F.generatedCStarSubalgebra) where
  family := fun _ => F.generatedFamily
  map := fun {_ _} _ => StarAlgHom.id ℂ F.generatedCStarSubalgebra
  map_id := by intro n; rfl
  map_comp := by intro m n k hmn hnk; ext x; rfl
  map_generator := by intro m n hmn i; rfl

@[simp] theorem constantGeneratedTower_map
    (F : CStarCuntzFamily A ι) {m n : ℕ} (hmn : m ≤ n)
    (x : F.generatedCStarSubalgebra) :
    (constantGeneratedTower F).map hmn x = x := by rfl

@[simp] theorem constantGeneratedTower_generator
    (F : CStarCuntzFamily A ι) {m n : ℕ} (hmn : m ≤ n) (i : ι) :
    (constantGeneratedTower F).map hmn
        ((F.generatedFamily).S i) = (F.generatedFamily).S i := by rfl

end ConstantGeneratedTower

section GNS

variable {ωStage : ℕ → Type}
variable [∀ n, CStarAlgebra (ωStage n)]
variable [∀ n, PartialOrder (ωStage n)]
variable [∀ n, StarOrderedRing (ωStage n)]
variable (T : Data (ι := ι) ωStage)

/-- The continuous star-inductive system underlying a fixed-index tower. -/
abbrev fixedIndexSystem (T : Data (ι := ι) ωStage) :
    ContinuousStarInductiveSystem ωStage :=
  Data.toContinuousStarInductiveSystem (Stage := ωStage) T

variable
  (ω : ContinuousStarInductiveSystem.CompatibleStateFamily
    ωStage (fixedIndexSystem (ι := ι) T))

/-- Filtered GNS Hilbert colimit for a fixed-index noncommutative tower. -/
abbrev fixedIndexGNSHilbertColimit : Type :=
  GNSHilbertColimit ωStage (fixedIndexSystem (ι := ι) T) ω

/-- Canonical stage isometry into the fixed-index GNS colimit. -/
def fixedIndexStageToHilbertColimit (n : ℕ) :
    GNSStage ωStage (fixedIndexSystem (ι := ι) T) ω n →ₗᵢ[ℂ]
      fixedIndexGNSHilbertColimit (ι := ι) T ω :=
  gnsStageToHilbertColimit ωStage (fixedIndexSystem (ι := ι) T) ω n

@[simp] theorem fixedIndexStageToHilbertColimit_transition
    {m n : ℕ} (hmn : m ≤ n)
    (x : GNSStage ωStage (fixedIndexSystem (ι := ι) T) ω m) :
    fixedIndexStageToHilbertColimit (ι := ι) T ω n
        (filteredGNSMap ωStage (fixedIndexSystem (ι := ι) T) ω hmn x) =
      fixedIndexStageToHilbertColimit (ι := ι) T ω m x := by
  exact gnsStageToHilbertColimit_transition
    ωStage (fixedIndexSystem (ι := ι) T) ω hmn x

theorem dense_iUnion_range_fixedIndexStageToHilbertColimit :
    Dense
      (⋃ n : ℕ,
        Set.range (fixedIndexStageToHilbertColimit (ι := ι) T ω n)) :=
  dense_iUnion_range_gnsStageToHilbertColimit
    ωStage (fixedIndexSystem (ι := ι) T) ω

end GNS

end InfoGeometry.Canonical.FixedIndexCuntzStarTower
