import InfoGeometry.Canonical.BottDirac
import InfoGeometry.Canonical.ChiralAnomaly
import InfoGeometry.Canonical.CalabiYauBridge
import InfoGeometry.Canonical.KMSSinkhornBridge
import InfoGeometry.Canonical.KaehlerGeometry
import InfoGeometry.Canonical.RicciMongeAmpere
import InfoGeometry.Canonical.SingularTransportSystem
import InfoGeometry.Canonical.AnalyticalIndex
import InfoGeometry.KK.KasparovCycle
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.LinearAlgebra.Matrix.Kronecker

/-!
# The Grand Unification of the Physics of Information in Lean 4

Capstone synthesis layer connecting thermodynamic Sinkhorn/KMS closure,
geometric Ricci/Calabi-Yau closure, and algebraic Bott-Dirac/index closure.
-/

open scoped TensorProduct
open scoped Kronecker

namespace InfoGeometry.Canonical.GrandSynthesis

open InfoGeometry.Krein
open InfoGeometry.Canonical.MoE
open InfoGeometry.Canonical.BottDirac
open InfoGeometry.Canonical.CalabiYauBridge
open InfoGeometry.Canonical.ChiralAnomaly
open InfoGeometry.Canonical.KMSSinkhornBridge
open InfoGeometry.Canonical.IB
open InfoGeometry.Canonical.KaehlerGeometry
open InfoGeometry.Canonical.RicciMongeAmpere
open InfoGeometry.Canonical.AnalyticalIndex
open InfoGeometry.Canonical.SpectralInference

section Thermodynamic

variable (n : Nat)

/--
Thermodynamic equilibrium along a doubly-stochastic Sinkhorn trajectory:
each step has Lyapunov monotonicity and bounded routing chiral scale.
-/
def ThermodynamicEquilibrium
    (T : DoublyStochasticSinkhornTrajectory n) : Prop :=
  ∀ k : Nat, ∀ label : PermMode n → CliffordLabel,
    trajectoryLyapunovNext n T.traj k ≤ trajectoryLyapunov n T.traj k ∧
      trajectorySelectedRoutingEpsilon n T (k + 1) label ≤ 1

/--
Any doubly-stochastic Sinkhorn trajectory satisfies the thermodynamic equilibrium
control law from `sinkhorn_dynamics_step_control`.
-/
theorem thermodynamicEquilibrium_of_doublyStochastic
    (T : DoublyStochasticSinkhornTrajectory n) :
    ThermodynamicEquilibrium n T := by
  intro k label
  exact sinkhorn_dynamics_step_control (n := n) T k label

end Thermodynamic

section Geometric

variable {X : Type*}

/-- Geometric equilibrium is the Ricci RG fixed-point condition. -/
abbrev GeometricEquilibrium (flow : RicciFlow X) : Prop :=
  IsRicciFixedPoint flow

/--
At geometric equilibrium, every Ricci component is scale-invariant.
-/
theorem ricci_component_constant_of_geometricEquilibrium
    (flow : RicciFlow X) (u v : X)
    (hDiff : Differentiable ℝ (fun s => flow s u v))
    (hGeo : GeometricEquilibrium flow) :
    ∃ c : ℝ, ∀ s, flow s u v = c := by
  exact ricci_component_invariant_at_fixed_point
    (flow := flow) (u := u) (v := v) hDiff (fun s => hGeo s u v)

end Geometric

section FirstQuantization

variable (n : Nat)

/-- Relative-count profile over a finite sample index set. -/
abbrev RelativeCounts := Fin n → ℝ

/--
First quantization of relative counts:
promote classical relative sample counts to a Radon-Nikodym-style density ratio.
-/
noncomputable def relativeCountDensity
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  fun i => counts i / ref i

/-- Mean log-relative density (finite-sample modular log-density). -/
noncomputable def relativeLogDensityMean (ρ : Fin n → ℝ) : ℝ :=
  (n : ℝ)⁻¹ * ∑ i : Fin n, Real.log (ρ i)

/-- Relative modular Hamiltonian: negative mean log-relative density. -/
noncomputable def relativeModularHamiltonian (ρ : Fin n → ℝ) : ℝ :=
  -relativeLogDensityMean n ρ

/--
Tomita-Takesaki-style operator generated by the relative modular Hamiltonian on
the doubled router-amplitude space.
-/
noncomputable def relativeTomitaTakesakiOp
    (ρ : Fin n → ℝ) : AlgebraEnd (RouterAmplitude n) :=
  relativeModularHamiltonian n ρ •
    ContinuousLinearMap.id ℝ (DoubledSpace (RouterAmplitude n))

@[simp] lemma relativeTomitaTakesakiOp_apply
    (ρ : Fin n → ℝ) (v : DoubledSpace (RouterAmplitude n)) :
    relativeTomitaTakesakiOp n ρ v = relativeModularHamiltonian n ρ • v := by
  simp [relativeTomitaTakesakiOp]

/-- The relative-count RN lift is definitional in this finite model. -/
lemma relativeCountDensity_eq_rn_lift
    (counts ref : RelativeCounts n) :
    relativeCountDensity n counts ref = (fun i => counts i / ref i) := rfl

/--
Generalized chain rule on relative densities:
log-density means add under pointwise multiplicative composition.
-/
lemma relativeLogDensityMean_mul
    (ρ σ : Fin n → ℝ)
    (hρ : ∀ i : Fin n, ρ i ≠ 0)
    (hσ : ∀ i : Fin n, σ i ≠ 0) :
    relativeLogDensityMean n (fun i => ρ i * σ i)
      = relativeLogDensityMean n ρ + relativeLogDensityMean n σ := by
  unfold relativeLogDensityMean
  have hsum :
      (∑ i : Fin n, Real.log (ρ i * σ i))
        = ∑ i : Fin n, (Real.log (ρ i) + Real.log (σ i)) := by
    refine Finset.sum_congr rfl ?_
    intro i hi
    exact Real.log_mul (hρ i) (hσ i)
  rw [hsum, Finset.sum_add_distrib, mul_add]

end FirstQuantization

section DeterminantChainRule

variable {m : Type*} [Fintype m] [DecidableEq m]

/-- Classical log-absolute determinant functional on square real matrices. -/
noncomputable def logAbsDetMatrix (A : Matrix m m ℝ) : ℝ :=
  Real.log (|Matrix.det A|)

/--
Classical determinant chain rule:
`log |det(AB)| = log |det A| + log |det B|`.
-/
lemma logAbsDetMatrix_mul
    (A B : Matrix m m ℝ)
    (hA : Matrix.det A ≠ 0)
    (hB : Matrix.det B ≠ 0) :
    logAbsDetMatrix (A * B) = logAbsDetMatrix A + logAbsDetMatrix B := by
  have hAabs : |Matrix.det A| ≠ 0 := abs_ne_zero.mpr hA
  have hBabs : |Matrix.det B| ≠ 0 := abs_ne_zero.mpr hB
  unfold logAbsDetMatrix
  rw [Matrix.det_mul, abs_mul, Real.log_mul hAabs hBabs]

variable {k : Type*} [Fintype k] [DecidableEq k]

/--
Tensor-product determinant decomposition:
`det(A ⊗ B) = det(A)^dim(B) * det(B)^dim(A)`, after `log|·|` this becomes
an additive entropy-scaling law.
-/
lemma logAbsDetMatrix_kronecker
    (A : Matrix m m ℝ) (B : Matrix k k ℝ)
    (hA : Matrix.det A ≠ 0)
    (hB : Matrix.det B ≠ 0) :
    logAbsDetMatrix (A ⊗ₖ B)
      = (Fintype.card k) * logAbsDetMatrix A
          + (Fintype.card m) * logAbsDetMatrix B := by
  have hAabs : |Matrix.det A| ≠ 0 := abs_ne_zero.mpr hA
  have hBabs : |Matrix.det B| ≠ 0 := abs_ne_zero.mpr hB
  have hAabsPow : |Matrix.det A| ^ Fintype.card k ≠ 0 :=
    pow_ne_zero _ hAabs
  have hBabsPow : |Matrix.det B| ^ Fintype.card m ≠ 0 :=
    pow_ne_zero _ hBabs
  unfold logAbsDetMatrix
  rw [Matrix.det_kronecker, abs_mul, abs_pow, abs_pow, Real.log_mul hAabsPow hBabsPow]
  rw [Real.log_pow, Real.log_pow]

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]

/-- Quantum-side Jacobian determinant functional on continuous endomorphisms. -/
noncomputable def jacDetCLM (L : E →L[ℝ] E) : ℝ :=
  LinearMap.det L.toLinearMap

/-- Jacobian chain rule (quantum/operator side): multiplicativity under composition. -/
lemma jacDetCLM_comp (L₁ L₂ : E →L[ℝ] E) :
    jacDetCLM (L₁.comp L₂) = jacDetCLM L₁ * jacDetCLM L₂ := by
  have _ : FiniteDimensional ℝ E := inferInstance
  simp [jacDetCLM, LinearMap.det_comp]

/-- Log-absolute Jacobian on continuous endomorphisms. -/
noncomputable def logAbsJacDetCLM (L : E →L[ℝ] E) : ℝ :=
  Real.log (|jacDetCLM L|)

/--
Quantum-side log-Jacobian chain rule:
`log |det(L₁ ∘ L₂)| = log |det L₁| + log |det L₂|`.
-/
lemma logAbsJacDetCLM_comp
    (L₁ L₂ : E →L[ℝ] E)
    (h₁ : jacDetCLM L₁ ≠ 0)
    (h₂ : jacDetCLM L₂ ≠ 0) :
    logAbsJacDetCLM (L₁.comp L₂) = logAbsJacDetCLM L₁ + logAbsJacDetCLM L₂ := by
  have h₁abs : |jacDetCLM L₁| ≠ 0 := abs_ne_zero.mpr h₁
  have h₂abs : |jacDetCLM L₂| ≠ 0 := abs_ne_zero.mpr h₂
  unfold logAbsJacDetCLM
  rw [jacDetCLM_comp, abs_mul, Real.log_mul h₁abs h₂abs]

end DeterminantChainRule

section SpectralVolumeForm

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] [FiniteDimensional ℝ E]

/--
Log-volume identity for Monge-Ampere density:
on the nondegenerate branch, `log ρ = log |det(∇²ψ)|`.
-/
lemma log_mongeAmpereDensity_eq_logAbsDet_metricOp
    [FiniteDimensional ℝ E]
    (H : InfoGeometry.Convex.HessianGeometry E) (x : E)
    (hdet : LinearMap.det (H.metricOp x).toLinearMap ≠ 0) :
    Real.log (mongeAmpereDensity H x)
      = Real.log (|LinearMap.det (H.metricOp x).toLinearMap|) := by
  have hρ :
      mongeAmpereDensity H x = Real.exp (metricLogDet H x) :=
    mongeAmpereDensity_eq_exp_metricLogDet (H := H) (x := x) hdet
  rw [hρ, Real.log_exp]
  rfl

/-- Spectral specialization of the log-volume identity at the basepoint. -/
lemma log_spectralMongeAmpereDensity_eq_basepointLogVolume
    (IST : InfoSpectralTriple E)
    (h_det : LinearMap.det (IST.H.metricOp IST.x₀).toLinearMap ≠ 0) :
    Real.log (spectralMongeAmpereDensity IST)
      = spectralBasepointLogVolume IST := by
  rw [spectralMongeAmpereDensity_eq_exp_spectralBasepointLogVolume IST h_det]
  rw [Real.log_exp]

variable {m : Type*} [Fintype m] [DecidableEq m]

/--
Determinant-model bridge:
if a matrix determinant models the Monge-Ampere density, then its log-absolute
determinant equals the Hessian metric-op log-absolute determinant.
-/
lemma logAbsDet_metricModel_eq_logAbsDet_metricOp
    [FiniteDimensional ℝ E]
    (H : InfoGeometry.Convex.HessianGeometry E) (x : E) (A : Matrix m m ℝ)
    (h_det : LinearMap.det (H.metricOp x).toLinearMap ≠ 0)
    (hdet : Matrix.det A = mongeAmpereDensity H x) :
    logAbsDetMatrix A = Real.log (|LinearMap.det (H.metricOp x).toLinearMap|) := by
  unfold logAbsDetMatrix
  rw [hdet]
  rw [abs_of_pos (mongeAmpereDensity_pos (H := H) (x := x) h_det)]
  exact log_mongeAmpereDensity_eq_logAbsDet_metricOp (H := H) (x := x) h_det

/--
Spectral determinant-model bridge:
if a matrix determinant models the spectral Monge-Ampere density, then its
log-absolute determinant equals spectral volume.
-/
lemma logAbsDet_spectralModel_eq_basepointLogVolume
    (IST : InfoSpectralTriple E) (A : Matrix m m ℝ)
    (h_det_m : LinearMap.det (IST.H.metricOp IST.x₀).toLinearMap ≠ 0)
    (hdet : Matrix.det A = spectralMongeAmpereDensity IST) :
    logAbsDetMatrix A = spectralBasepointLogVolume IST := by
  unfold logAbsDetMatrix
  rw [hdet]
  have hpos : 0 < spectralMongeAmpereDensity IST := by
    rw [spectralMongeAmpereDensity_eq_exp_spectralBasepointLogVolume IST h_det_m]
    exact Real.exp_pos _
  rw [abs_of_pos hpos]
  exact log_spectralMongeAmpereDensity_eq_basepointLogVolume (IST := IST) h_det_m

end SpectralVolumeForm

section EntropicCalabiBridge

variable (n : Nat)
variable {X : Type}
  [NormedAddCommGroup X] [InnerProductSpace ℝ X] [CompleteSpace X]
  [FiniteDimensional ℝ X]

/--
Entropy-sourced Monge-Ampere hypothesis:
the Monge-Ampere density is the RN-induced relative-volume factor
`exp(-K_RN)` associated to a Sinkhorn matrix state.
-/
def RNEntropySourcesMongeAmpere
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n) : Prop :=
  SatisfiesMongeAmpere Kgeo.H (fun _ => relativeVolumeChangeRN n M)

/--
Constant-density witness extracted from RN-entropy Monge-Ampere sourcing.
-/
lemma hasConstantMongeAmpereDensity_of_rnEntropySource
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M) :
    HasConstantMongeAmpereDensity Kgeo.H :=
  hasConstantMongeAmpereDensity_of_satisfiesMongeAmpere_const
    (H := Kgeo.H) (ρ0 := relativeVolumeChangeRN n M) hSource

/--
RN entropy sourcing can be read in potential form: the Monge-Ampere density is
the exponential of the negative RN/Kähler potential.
-/
lemma rnEntropySourcesMongeAmperePotential
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M) :
    SatisfiesMongeAmperePotential Kgeo.H (fun _ => -kahlerPotentialRN n M) := by
  intro x
  rw [hSource x, relativeVolumeChangeRN]

/--
Pointwise log form of RN entropy sourcing: the logarithmic Monge-Ampere density
is exactly the negative RN/Kähler potential.
-/
lemma log_mongeAmpereDensity_eq_neg_kahlerPotentialRN_of_rnEntropySource
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M)
    (x : X) :
    Real.log (mongeAmpereDensity Kgeo.H x) = -kahlerPotentialRN n M := by
  rw [hSource x, relativeVolumeChangeRN]
  simp

/--
Equivalent pointwise form: the RN/Kähler potential is minus the logarithmic
Monge-Ampere density under RN entropy sourcing.
-/
lemma kahlerPotentialRN_eq_neg_log_mongeAmpereDensity_of_rnEntropySource
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M)
    (x : X) :
    kahlerPotentialRN n M = -Real.log (mongeAmpereDensity Kgeo.H x) := by
  calc
    kahlerPotentialRN n M = -(-kahlerPotentialRN n M) := by ring
    _ = -Real.log (mongeAmpereDensity Kgeo.H x) := by
      rw [log_mongeAmpereDensity_eq_neg_kahlerPotentialRN_of_rnEntropySource
        (n := n) (Kgeo := Kgeo) (M := M) hSource x]

/--
If the Kähler logarithmic potential `logF` matches the negative RN/Kähler
potential, then RN entropy sourcing upgrades directly to a `logF`-driven
Monge-Ampere potential witness.
-/
lemma rnEntropySourcesMongeAmperePotential_of_logF_eq_neg_kahlerPotentialRN
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M)
    (hLogF : ∀ x : X, Kgeo.logF x = -kahlerPotentialRN n M) :
    SatisfiesMongeAmperePotential Kgeo.H Kgeo.logF := by
  intro x
  calc
    mongeAmpereDensity Kgeo.H x = Real.exp (-kahlerPotentialRN n M) := by
      exact rnEntropySourcesMongeAmperePotential
        (n := n) (Kgeo := Kgeo) (M := M) hSource x
    _ = Real.exp (Kgeo.logF x) := by
      rw [hLogF x]

/--
Pointwise logarithmic Monge-Ampere closure along the same bridge: when `logF`
coincides with the negative RN/Kähler potential, the logarithmic Monge-Ampere
density is exactly `logF`.
-/
lemma log_mongeAmpereDensity_eq_logF_of_rnEntropySource_of_logF_eq_neg_kahlerPotentialRN
    (Kgeo : KaehlerInformationGeometry X)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M)
    (hLogF : ∀ x : X, Kgeo.logF x = -kahlerPotentialRN n M)
    (x : X) :
    Real.log (mongeAmpereDensity Kgeo.H x) = Kgeo.logF x := by
  calc
    Real.log (mongeAmpereDensity Kgeo.H x) = -kahlerPotentialRN n M := by
      exact log_mongeAmpereDensity_eq_neg_kahlerPotentialRN_of_rnEntropySource
        (n := n) (Kgeo := Kgeo) (M := M) hSource x
    _ = Kgeo.logF x := by
      symm
      exact hLogF x

/--
Entropy-sourced geometric gravity statement:
RN/Kahler-potential sourcing plus unit relative-volume closure and a metric RN
bridge implies the vacuum Einstein equation on the `c = 0` branch (`scalar = 2Λ`).
-/
theorem vacuumEinsteinEquation_of_rnEntropySource
    (Kgeo : KaehlerInformationGeometry X)
    (R : RicciTensor X)
    (x : X) (Λ : ℝ)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M)
    (hUnit : relativeVolumeChangeRN n M = 1)
    (hBridge : MetricRNRicciBridge R Kgeo x) :
    VacuumEinsteinEquationAt R Kgeo x (2 * Λ) Λ := by
  have hUnitState : UnitRelativeVolumeState Kgeo := by
    intro x'
    simpa [RNEntropySourcesMongeAmpere, hUnit] using hSource x'
  exact vacuumEinsteinEquation_of_unitRelativeVolume
    (R := R) (K := Kgeo) (x := x) (Λ := Λ) hUnitState hBridge

/--
Capstone entropy-to-gravity statement:
if RN/Kahler entropy sources Monge-Ampere density and unit relative-volume closure
is equipped with a metric RN bridge, then the induced information geometry is Ricci-flat and satisfies
the vacuum Einstein equation (`c = 0`, `scalar = 2Λ`).
-/
theorem gravity_generated_by_rnEntropy
    (Kgeo : KaehlerInformationGeometry X)
    (R : RicciTensor X)
    (x : X) (Λ : ℝ)
    (M : SinkhornMatrix n)
    (hSource : RNEntropySourcesMongeAmpere n Kgeo M)
    (hUnit : relativeVolumeChangeRN n M = 1)
    (hBridge : MetricRNRicciBridge R Kgeo x) :
    IsRicciFlat R ∧ VacuumEinsteinEquationAt R Kgeo x (2 * Λ) Λ := by
  have hUnitState : UnitRelativeVolumeState Kgeo := by
    intro x'
    simpa [RNEntropySourcesMongeAmpere, hUnit] using hSource x'
  refine ⟨?_, ?_⟩
  · exact isRicciFlat_of_unitRelativeVolume
      (R := R) (K := Kgeo) (x := x) hUnitState hBridge
  · exact vacuumEinsteinEquation_of_rnEntropySource
      (n := n) (Kgeo := Kgeo) (R := R) (x := x) (Λ := Λ)
      (M := M) hSource hUnit hBridge

end EntropicCalabiBridge

section EntropyFlow

variable (n : Nat)
variable {F : Type} [NormedAddCommGroup F] [InnerProductSpace ℝ F] [CompleteSpace F]

/-- Entropy monotonicity along Sinkhorn flow (RN barrier form). -/
def SinkhornEntropyMonotoneRN (T : SinkhornTrajectory n) : Prop :=
  ∀ k : Nat, trajectoryRNBarrierNext n T k ≤ trajectoryRNBarrier n T k

/-- Every Sinkhorn trajectory satisfies RN-barrier entropy monotonicity. -/
theorem sinkhornEntropyMonotoneRN
    (T : SinkhornTrajectory n) :
    SinkhornEntropyMonotoneRN n T := by
  intro k
  exact trajectoryRNBarrier_monotone (n := n) T k

/--
KMS residual is controlled by the RN-barrier entropy budget at each Sinkhorn step.
-/
theorem sinkhornStepwise_kmsResidual_le_entropyBarrier
    (T : SinkhornTrajectory n)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (vac : ThermalVacuum (E := F) K)
    (hJointKernel : JointKernelOnOmega (F := F) K β vac.Omega)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) vac.Omega) :
    ∀ k : Nat, ∀ A B : AlgebraEnd F,
      kmsResidual K ((ibInducedObservableWeighted (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib) pTrajectory x0 t0 (omegaSeed (F := F) vac.Omega)) (k + 1)) β A B
        ≤ trajectoryRNBarrier n T k := by
  have hControl :
      SinkhornKMSControl n T K (ibInducedObservableWeighted (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib) pTrajectory x0 t0 (omegaSeed (F := F) vac.Omega)) β :=
    sinkhorn_kmsControl_of_ibDynamics_weighted_from_jointKernel_commutator
      (n := n) (T := T) (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory) hStep (x0 := x0) (t0 := t0)
      (Ω := vac.Omega) vac.vacuum_nonzero hJointKernel hCommOrthogonal
  exact sinkhorn_stepwise_kms_bound
    (n := n) (T := T) (K := K)
    (ω := ibInducedObservableWeighted (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib) pTrajectory x0 t0 (omegaSeed (F := F) vac.Omega)) (β := β) hControl

/--
Doubly-stochastic specialization of RN-barrier entropy monotonicity.
-/
theorem doublyStochastic_sinkhornEntropyMonotoneRN
    (T : DoublyStochasticSinkhornTrajectory n) :
    SinkhornEntropyMonotoneRN n T.traj := by
  exact sinkhornEntropyMonotoneRN (n := n) T.traj

end EntropyFlow

section Algebraic

variable {E F : Type*}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]

/--
Algebraic equilibrium: the Cl(1,1)-Bott Laplacian vanishes.
-/
def AlgebraicEquilibriumCl11 (Dn : Endomorphism F) : Prop :=
  cl11BottLaplacian (E := E) Dn = 0

/--
If the Cl(1,1)-Bott Laplacian is zero, then the squared Bott-Dirac operator is zero.
-/
theorem cl11_bottDirac_sq_eq_zero_of_algebraicEquilibrium
    (Dn : Endomorphism F)
    (hAlg : AlgebraicEquilibriumCl11 (E := E) Dn) :
    (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn).comp
      (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn) = 0 := by
  exact (cl11_bottDirac_sq_eq_cl11BottLaplacian (E := E) (F := F) (Dn := Dn)).trans hAlg

/--
Pointwise harmonicity of a Bott state at algebraic equilibrium.
-/
theorem cl11_bottDirac_sq_apply_eq_zero_of_algebraicEquilibrium
    (Dn : Endomorphism F)
    (hAlg : AlgebraicEquilibriumCl11 (E := E) Dn)
    (ψ : DoubledSpace E ⊗[ℝ] F) :
    ((bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn).comp
      (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn)) ψ = 0 := by
  have hSq :
      (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn).comp
        (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn) = 0 :=
    cl11_bottDirac_sq_eq_zero_of_algebraicEquilibrium (E := E) (Dn := Dn) hAlg
  simp [hSq]

end Algebraic

section LichnerowiczBridge

variable {A F : Type*}
  [NormedAddCommGroup A] [InnerProductSpace ℝ A] [CompleteSpace A]
  [NormedAddCommGroup F] [InnerProductSpace ℝ F] [CompleteSpace F]

/--
Lichnerowicz-style bridge in the current framework:
for `InfoSpectralTriple`, `D²` rewrites to the Hessian metric operator, and therefore
the split Bott-Dirac square rewrites to the corresponding metric-op Laplacian form.
-/
theorem cl11_bottDirac_sq_eq_metricOp_form
    (IST : InfoSpectralTriple F) :
    (bottDirac (cl11DiracSeed (E := A)) (cl11Grading (E := A)) (spectralDiracLinear IST)).comp
      (bottDirac (cl11DiracSeed (E := A)) (cl11Grading (E := A)) (spectralDiracLinear IST))
      =
    (TensorProduct.map
      ((cl11DiracSeed (E := A)).comp (cl11DiracSeed (E := A)))
      (LinearMap.id : Endomorphism F))
      +
    (TensorProduct.map
      (LinearMap.id : Endomorphism (DoubledSpace A))
      (IST.H.metricOp IST.x₀)) := by
  have hLich :
      (spectralDiracLinear IST).comp (spectralDiracLinear IST) = IST.H.metricOp IST.x₀ := by
    ext v
    have hv : (IST.D * IST.D) v = (IST.H.metricOp IST.x₀) v := by
      exact congrArg (fun T : F →L[ℝ] F => T v) IST.dirac_sq_eq_metric
    simpa [spectralDiracLinear, LinearMap.comp_apply] using hv
  calc
    (bottDirac (cl11DiracSeed (E := A)) (cl11Grading (E := A)) (spectralDiracLinear IST)).comp
        (bottDirac (cl11DiracSeed (E := A)) (cl11Grading (E := A)) (spectralDiracLinear IST))
      =
        (TensorProduct.map
          ((cl11DiracSeed (E := A)).comp (cl11DiracSeed (E := A)))
          (LinearMap.id : Endomorphism F))
          +
        (TensorProduct.map
          (LinearMap.id : Endomorphism (DoubledSpace A))
          ((spectralDiracLinear IST).comp (spectralDiracLinear IST))) := by
            simpa using
              (cl11_bottDirac_sq_eq_sum_laplacians
                (E := A) (F := F) (Dn := spectralDiracLinear IST))
    _ =
        (TensorProduct.map
          ((cl11DiracSeed (E := A)).comp (cl11DiracSeed (E := A)))
          (LinearMap.id : Endomorphism F))
          +
        (TensorProduct.map
          (LinearMap.id : Endomorphism (DoubledSpace A))
          (IST.H.metricOp IST.x₀)) := by
            simp [hLich]

/--
Metric-op closure condition for the split Bott Laplacian in the Lichnerowicz form.
-/
def LichnerowiczBalancedCl11 (IST : InfoSpectralTriple F) : Prop :=
  (TensorProduct.map
    ((cl11DiracSeed (E := A)).comp (cl11DiracSeed (E := A)))
    (LinearMap.id : Endomorphism F))
    +
  (TensorProduct.map
    (LinearMap.id : Endomorphism (DoubledSpace A))
    (IST.H.metricOp IST.x₀)) = 0

/--
If the Lichnerowicz-balanced metric-op closure holds, the split Bott-Dirac square vanishes.
-/
theorem cl11_bottDirac_sq_eq_zero_of_lichnerowiczBalanced
    (IST : InfoSpectralTriple F)
    (hBal : LichnerowiczBalancedCl11 (A := A) IST) :
    (bottDirac (cl11DiracSeed (E := A)) (cl11Grading (E := A)) (spectralDiracLinear IST)).comp
      (bottDirac (cl11DiracSeed (E := A)) (cl11Grading (E := A)) (spectralDiracLinear IST)) = 0 := by
  rw [cl11_bottDirac_sq_eq_metricOp_form (A := A) IST]
  exact hBal

end LichnerowiczBridge

section SingularBoundaryExtension

variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/--
Singular extension of the bulk transport law:
when the certified boundary obstruction vanishes, the logarithmic transport
observable closes on the non-anomalous sector contributions.
-/
theorem logDivergence_eq_bulkSectors_of_boundaryScale_eq_zero
    (S : SingularTransportSystem E)
    (hBoundary : S.boundary.boundaryScale = 0) :
    S.logDivergence =
      S.radialTerm + S.projectiveTerm + S.nilpotentTerm + S.gradedTerm := by
  exact S.logDivergence_split_of_boundaryScale_eq_zero hBoundary

/--
Singular extension of bulk radial closure:
if the boundary obstruction vanishes, the radial term is determined by the
remaining non-anomalous sectors.
-/
theorem radial_transport_closes_of_boundaryScale_eq_zero
    (S : SingularTransportSystem E)
    (hBoundary : S.boundary.boundaryScale = 0) :
    S.radialTerm =
      S.logDivergence - S.projectiveTerm - S.nilpotentTerm - S.gradedTerm := by
  exact S.regular_radial_transport_closes_of_boundaryScale_eq_zero hBoundary

/--
The scalar anomaly term is exactly the norm-shadow of the certified projector
commutator obstruction carried by the primitive boundary layer.
-/
theorem anomalyTerm_eq_projectorObstruction_norm
    (S : SingularTransportSystem E) :
    S.anomalyTerm =
      ‖S.boundary.spectralProjector * S.boundary.leftProjector
          - S.boundary.leftProjector * S.boundary.spectralProjector‖₊ := by
  rw [S.anomalyTerm_eq_projector_commutator_norm,
    S.boundary.boundaryScale_eq_projectorObstruction_norm]

/--
Boundary-anomaly freeness is equivalent to commutation of the certified Drazin
and Moore-Penrose projectors in the primitive singular boundary layer.
-/
theorem boundaryGenerator_eq_zero_iff_projectors_commute
    (S : SingularTransportSystem E) :
    S.boundary.boundaryGenerator = 0
      ↔ S.boundary.spectralProjector * S.boundary.leftProjector =
          S.boundary.leftProjector * S.boundary.spectralProjector := by
  exact S.boundaryGenerator_eq_zero_iff_projectors_commute

/--
Vanishing boundary generator forces the primitive singular boundary layer to
close to regular radial transport.
-/
theorem regularRadialTransportCloses_of_boundaryGenerator_eq_zero
    (S : SingularTransportSystem E)
    (hZero : S.boundary.boundaryGenerator = 0) :
    S.boundary.regularRadialTransportCloses := by
  have hScale : S.boundary.boundaryScale = 0 := by
    exact (S.boundary.boundaryScale_eq_zero_iff_boundaryGenerator_eq_zero).mpr hZero
  exact S.boundary.regular_radial_transport_closes_of_boundaryScale_eq_zero hScale

end SingularBoundaryExtension

section Capstone

variable (n : Nat)
variable {X E F : Type*}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]

/--
One-step grand synthesis control:
thermodynamic control from Sinkhorn, plus externally supplied geometric fixed-point
and algebraic Cl(1,1)-Bott equilibrium.
-/
theorem grandSynthesis_step
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : RicciFlow X)
    (Dn : Endomorphism F)
    (hGeo : GeometricEquilibrium flow)
    (hAlg : AlgebraicEquilibriumCl11 (E := E) Dn)
    (k : Nat) (label : PermMode n → CliffordLabel) :
    trajectoryLyapunovNext n T.traj k ≤ trajectoryLyapunov n T.traj k ∧
      trajectorySelectedRoutingEpsilon n T (k + 1) label ≤ 1 ∧
      GeometricEquilibrium flow ∧
      (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn).comp
        (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn) = 0 := by
  refine ⟨?_, ?_, hGeo, ?_⟩
  · exact (sinkhorn_dynamics_step_control (n := n) T k label).1
  · exact (sinkhorn_dynamics_step_control (n := n) T k label).2
  · exact cl11_bottDirac_sq_eq_zero_of_algebraicEquilibrium
      (E := E) (Dn := Dn) hAlg

/--
Global grand synthesis scaffold:
thermodynamic equilibrium of the trajectory, geometric fixed-point, and
algebraic Bott-Dirac stationarity.
-/
theorem grandSynthesis_of_equilibria
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : RicciFlow X)
    (Dn : Endomorphism F)
    (hGeo : GeometricEquilibrium flow)
    (hAlg : AlgebraicEquilibriumCl11 (E := E) Dn) :
    ThermodynamicEquilibrium n T ∧
      GeometricEquilibrium flow ∧
      (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn).comp
        (bottDirac (cl11DiracSeed (E := E)) (cl11Grading (E := E)) Dn) = 0 := by
  refine ⟨thermodynamicEquilibrium_of_doublyStochastic (n := n) T, hGeo, ?_⟩
  exact cl11_bottDirac_sq_eq_zero_of_algebraicEquilibrium
    (E := E) (Dn := Dn) hAlg

end Capstone

section KkIndexBridge

variable (n : Nat)
variable {A B Xgeo H : Type}
  [NormedRing A] [NormedRing B]
  [NormedAlgebra ℝ A] [NormedAlgebra ℝ B]
  [NormedAddCommGroup Xgeo] [InnerProductSpace ℝ Xgeo] [CompleteSpace Xgeo]
  [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
  [KreinSpace H] [KreinGradedModule H]
  [FiniteDimensional ℝ H]

/--
Any geometric-algebraic state already carries the KK analytical index along the
Dirac/grading path, provided the baseline matches the Kasparov data.
-/
theorem kk_analyticalIndex_eq_of_geometricAlgebraicState
    (Xk : InfoGeometry.KK.KasparovCycle A B H)
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow Xgeo)
    (D Γ : ℝ → Endomorphism H)
    (hD0 : D 0 = Xk.F.toLinearMap)
    (hΓ0 : Γ 0 = (KreinGradedModule.gradeCLM (H := H)).toLinearMap)
    (hGeoAlg : GeometricAlgebraicState n T flow D Γ) :
    ∀ s : ℝ, analyticalIndex (D s) (Γ s) = Xk.analyticalIndex := by
  exact InfoGeometry.KK.analyticalIndex_eq_of_indexInvariantAlong
    (X := Xk)
    (D := D)
    (Γ := Γ)
    hD0
    hΓ0
    hGeoAlg.2.2

/--
Conjugacy-state specialization of the KK analytical-index bridge on the
GrandSynthesis branch.
-/
theorem kk_analyticalIndex_eq_of_conjugacy_state_hypotheses
    (Xk : InfoGeometry.KK.KasparovCycle A B H)
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow Xgeo)
    (D Γ : ℝ → Endomorphism H)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := Xgeo) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := Xgeo) flow s = 0)
    (eFlow : ℝ → H ≃ₗ[ℝ] H)
    (hConj : ChiralConjugacyAlong D Γ eFlow)
    (hD0 : D 0 = Xk.F.toLinearMap)
    (hΓ0 : Γ 0 = (KreinGradedModule.gradeCLM (H := H)).toLinearMap) :
    ∀ s : ℝ, analyticalIndex (D s) (Γ s) = Xk.analyticalIndex := by
  exact kk_analyticalIndex_eq_of_geometricAlgebraicState
    (n := n)
    (Xk := Xk)
    (T := T)
    (flow := flow)
    (D := D)
    (Γ := Γ)
    hD0
    hΓ0
    (sinkhornRicciIndexInvariant_of_conjugacy_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (eFlow := eFlow) hNorm hFixed hConj)

/--
Modular/Clifford-transport specialization of the KK analytical-index bridge on
the GrandSynthesis branch.
-/
theorem kk_analyticalIndex_eq_of_modularCliffordTransport_state_hypotheses
    (Xk : InfoGeometry.KK.KasparovCycle A B H)
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow Xgeo)
    (D Γ : ℝ → Endomorphism H)
    {ι : Type*}
    (σ : ℝ → Endomorphism H)
    (clAct : ι → Endomorphism H)
    (unit : ι)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := Xgeo) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := Xgeo) flow s = 0)
    (hTrans :
      ChiralSliceModularCliffordTransportAlong (D := D) (Γ := Γ) σ clAct unit)
    (hD0 : D 0 = Xk.F.toLinearMap)
    (hΓ0 : Γ 0 = (KreinGradedModule.gradeCLM (H := H)).toLinearMap) :
    ∀ s : ℝ, analyticalIndex (D s) (Γ s) = Xk.analyticalIndex := by
  exact kk_analyticalIndex_eq_of_geometricAlgebraicState
    (n := n)
    (Xk := Xk)
    (T := T)
    (flow := flow)
    (D := D)
    (Γ := Γ)
    hD0
    hΓ0
    (sinkhornRicciIndexInvariant_of_modularCliffordTransport_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (σ := σ) (clAct := clAct) (unit := unit) hNorm hFixed hTrans)

end KkIndexBridge


section WheelerDeWitt

variable (n : Nat)
variable {X V F : Type}
  [NormedAddCommGroup X] [InnerProductSpace ℝ X] [CompleteSpace X]
  [AddCommGroup V] [Module ℝ V] [FiniteDimensional ℝ V]
  [NormedAddCommGroup F] [InnerProductSpace ℝ F] [CompleteSpace F]

omit [FiniteDimensional ℝ V] in
/--
IB-dynamics Bochner-Weitzenboeck bridge:
`SinkhornKMSClosure` is derived from an IB iterate trajectory.
-/
theorem bochnerWeitzenboeckBridge_of_ibDynamics
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω) :
    ThermodynamicKMSState n T K
      (ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β := by
  let _ := flow
  let _ := D
  let _ := Γ
  have hControl :
      SinkhornKMSControl n T.traj K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β :=
    sinkhorn_kmsControl_of_ibDynamics_weighted_from_jointKernel_commutator
      (n := n) (T := T.traj) (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      hStep (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal
  have hClosure :
      SinkhornKMSClosure n T.traj K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β :=
    sinkhorn_step_kmsClosure_of_control
      (n := n) (T := T.traj) (K := K)
      (ω := ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) (β := β) hControl
  exact hClosure

/--
Packaging of both directional Wheeler-DeWitt bridges from
IB iterate dynamics plus primitive modular-flow / Clifford-bundle transport
component hypotheses for chiral slices.
-/
theorem directionalBridges_of_ibDynamics_and_indexHypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    {ι : Type*}
    (σ : ℝ → Endomorphism V)
    (clAct : ι → Endomorphism V)
    (unit : ι)
    (hUnit : clAct unit = LinearMap.id)
    (hσInj : ∀ s : ℝ, Function.Injective (σ s))
    (hPlusMap : ∀ s : ℝ, ∀ ℓ : ι,
      (chiralKernelSlicePlus (D s) (Γ s)).map ((clAct ℓ).comp (σ s))
        = chiralKernelSlicePlus (D 0) (Γ 0))
    (hMinusMap : ∀ s : ℝ, ∀ ℓ : ι,
      (chiralKernelSliceMinus (D s) (Γ s)).map ((clAct ℓ).comp (σ s))
        = chiralKernelSliceMinus (D 0) (Γ 0)) :
    (GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β) ∧
      (ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β →
        GeometricAlgebraicState n T flow D Γ) := by
  refine ⟨?_, ?_⟩
  · intro _hGeoAlg
    exact bochnerWeitzenboeckBridge_of_ibDynamics
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      hStep (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal
  · intro _hThermo
    exact sinkhornRicciIndexInvariant_of_modularCliffordTransport_components_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (σ := σ) (clAct := clAct) (unit := unit)
      hNorm hFixed hUnit hσInj hPlusMap hMinusMap

/--
Packaging of both directional Wheeler-DeWitt bridges from
IB iterate dynamics plus primitive flow-conjugacy hypotheses for Dirac/grading.
-/
theorem directionalBridges_of_ibDynamics_and_conjugacy_indexHypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    (eFlow : ℝ → V ≃ₗ[ℝ] V)
    (hConj : ChiralConjugacyAlong D Γ eFlow) :
    (GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β) ∧
      (ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β →
        GeometricAlgebraicState n T flow D Γ) := by
  refine ⟨?_, ?_⟩
  · intro _hGeoAlg
    exact bochnerWeitzenboeckBridge_of_ibDynamics
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      hStep (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal
  · intro _hThermo
    exact sinkhornRicciIndexInvariant_of_conjugacy_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (eFlow := eFlow) hNorm hFixed hConj

/--
Reduced-hypothesis Wheeler-DeWitt implication (IB-dynamics form):
`IB trajectory dynamics + explicit joint-kernel/commutator hypotheses`
imply thermodynamic closure.
-/
theorem information_wheeler_dewitt_implication_of_ibDynamics_and_indexHypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω) :
    GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β := by
  intro _hGeoAlg
  exact bochnerWeitzenboeckBridge_of_ibDynamics
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (β := β)
    (prob := prob) (pTrajectory := pTrajectory)
    hStep (x0 := x0) (t0 := t0)
    (Ω := Ω) hΩ hJointKernel hCommOrthogonal

/--
Wheeler-DeWitt equivalence (IB-dynamics form) from primitive modular-flow /
Clifford-bundle transport component hypotheses for chiral slices:
the reverse direction is discharged constructively from
`hNorm + hFixed + hUnit + hσInj + hPlusMap + hMinusMap`.
-/
theorem information_wheeler_dewitt_equivalence_of_ibDynamics_and_modularCliffordTransport_state_hypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    {ι : Type*}
    (σ : ℝ → Endomorphism V)
    (clAct : ι → Endomorphism V)
    (unit : ι)
    (hUnit : clAct unit = LinearMap.id)
    (hσInj : ∀ s : ℝ, Function.Injective (σ s))
    (hPlusMap : ∀ s : ℝ, ∀ ℓ : ι,
      (chiralKernelSlicePlus (D s) (Γ s)).map ((clAct ℓ).comp (σ s))
        = chiralKernelSlicePlus (D 0) (Γ 0))
    (hMinusMap : ∀ s : ℝ, ∀ ℓ : ι,
      (chiralKernelSliceMinus (D s) (Γ s)).map ((clAct ℓ).comp (σ s))
        = chiralKernelSliceMinus (D 0) (Γ 0)) :
    ThermodynamicKMSState n T K
      (ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β
      ↔ GeometricAlgebraicState n T flow D Γ := by
  constructor
  · intro _hThermo
    exact sinkhornRicciIndexInvariant_of_modularCliffordTransport_components_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (σ := σ) (clAct := clAct) (unit := unit)
      hNorm hFixed hUnit hσInj hPlusMap hMinusMap
  · intro hGeoAlg
    exact information_wheeler_dewitt_implication_of_ibDynamics_and_indexHypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      hStep (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal hGeoAlg

/--
Primary Wheeler-DeWitt implication API:
constructively discharges the geometric-to-thermodynamic direction.
-/
theorem information_wheeler_dewitt_implication
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω) :
    GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β := by
  exact information_wheeler_dewitt_implication_of_ibDynamics_and_indexHypotheses
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (β := β)
    (prob := prob) (pTrajectory := pTrajectory)
    hStep (x0 := x0) (t0 := t0)
    (Ω := Ω) hΩ hJointKernel hCommOrthogonal

/--
Canonical fully derived state-hypothesis Wheeler-DeWitt implication using
primitive modular-flow / Clifford-bundle transport component hypotheses of chiral
index slices (non-constancy path).
-/
theorem information_wheeler_dewitt_implication_of_modularCliffordTransport_state_hypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    {ι : Type*}
    (σ : ℝ → Endomorphism V)
    (clAct : ι → Endomorphism V)
    (unit : ι)
    (hUnit : clAct unit = LinearMap.id)
    (hσInj : ∀ s : ℝ, Function.Injective (σ s))
    (hPlusMap : ∀ s : ℝ, ∀ ℓ : ι,
      (chiralKernelSlicePlus (D s) (Γ s)).map ((clAct ℓ).comp (σ s))
        = chiralKernelSlicePlus (D 0) (Γ 0))
    (hMinusMap : ∀ s : ℝ, ∀ ℓ : ι,
      (chiralKernelSliceMinus (D s) (Γ s)).map ((clAct ℓ).comp (σ s))
        = chiralKernelSliceMinus (D 0) (Γ 0)) :
    GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β := by
  have hGeoAlg : GeometricAlgebraicState n T flow D Γ :=
    sinkhornRicciIndexInvariant_of_modularCliffordTransport_components_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (σ := σ) (clAct := clAct) (unit := unit)
      hNorm hFixed hUnit hσInj hPlusMap hMinusMap
  intro _hGeoAlgArg
  exact information_wheeler_dewitt_implication_of_ibDynamics_and_indexHypotheses
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (β := β)
    (prob := prob) (pTrajectory := pTrajectory)
    hStep (x0 := x0) (t0 := t0)
    (Ω := Ω) hΩ hJointKernel hCommOrthogonal hGeoAlg

/--
Canonical fully derived state-hypothesis Wheeler-DeWitt implication using
primitive flow-conjugacy hypotheses for Dirac/grading (non-constancy path).
-/
theorem information_wheeler_dewitt_implication_of_conjugacy_state_hypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    (eFlow : ℝ → V ≃ₗ[ℝ] V)
    (hConj : ChiralConjugacyAlong D Γ eFlow) :
    GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β := by
  have hGeoAlg : GeometricAlgebraicState n T flow D Γ :=
    sinkhornRicciIndexInvariant_of_conjugacy_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (eFlow := eFlow) hNorm hFixed hConj
  intro _hGeoAlgArg
  exact information_wheeler_dewitt_implication_of_ibDynamics_and_indexHypotheses
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (β := β)
    (prob := prob) (pTrajectory := pTrajectory)
    hStep (x0 := x0) (t0 := t0)
    (Ω := Ω) hΩ hJointKernel hCommOrthogonal hGeoAlg

/--
Wheeler-DeWitt equivalence (IB-dynamics form) from primitive flow-conjugacy
hypotheses for Dirac/grading: the reverse direction is discharged
constructively from `hNorm + hFixed + hConj`.
-/
theorem information_wheeler_dewitt_equivalence_of_ibDynamics_and_conjugacy_state_hypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    (eFlow : ℝ → V ≃ₗ[ℝ] V)
    (hConj : ChiralConjugacyAlong D Γ eFlow) :
    ThermodynamicKMSState n T K
      (ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β
      ↔ GeometricAlgebraicState n T flow D Γ := by
  constructor
  · intro _hThermo
    exact sinkhornRicciIndexInvariant_of_conjugacy_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (eFlow := eFlow) hNorm hFixed hConj
  · intro hGeoAlg
    exact information_wheeler_dewitt_implication_of_ibDynamics_and_indexHypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      hStep (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal hGeoAlg

/--
Fully derived Wheeler-DeWitt implication from explicit seed-KMS derivation data
and derived geometric/algebraic state hypotheses.
-/
theorem information_wheeler_dewitt_implication_of_fully_derived_hypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    (eFlow : ℝ → V ≃ₗ[ℝ] V)
    (hConj : ChiralConjugacyAlong D Γ eFlow) :
    GeometricAlgebraicState n T flow D Γ →
      ThermodynamicKMSState n T K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β := by
  exact information_wheeler_dewitt_implication_of_conjugacy_state_hypotheses
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (β := β)
    (prob := prob) (pTrajectory := pTrajectory)
    hStep (x0 := x0) (t0 := t0)
    (Ω := Ω) hΩ hJointKernel hCommOrthogonal
    (eFlow := eFlow) hNorm hFixed hConj

/--
The full capstone package from `AnalyticalIndex` immediately yields both sides.
-/
theorem thermodynamic_and_geometricAlgebraic_of_fullCapstone
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (ω : Nat → AlgebraEnd F →L[ℝ] ℝ)
    (β : ℝ)
    (hFull : FullThermoGeoIndexCapstone n T flow D Γ K ω β) :
    ThermodynamicKMSState n T K ω β ∧ GeometricAlgebraicState n T flow D Γ := by
  exact ⟨
    FullThermoGeoIndexCapstone.thermodynamicKMSState
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ) (K := K) (ω := ω) (β := β) hFull,
    FullThermoGeoIndexCapstone.geometricAlgebraicState
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ) (K := K) (ω := ω) (β := β) hFull
  ⟩

/--
Construct a full capstone package from the primitive flow-conjugacy route while
carrying an explicit KK analytical-index anchor at the baseline.
-/
theorem fullCapstone_of_conjugacy_index_anchor
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (ω : Nat → AlgebraEnd F →L[ℝ] ℝ)
    (β : ℝ)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    (eFlow : ℝ → V ≃ₗ[ℝ] V)
    (hConj : ChiralConjugacyAlong D Γ eFlow)
    (hClosure : SinkhornKMSClosure n T.traj K ω β)
    (hIndexAnchor : analyticalIndex (D 0) (Γ 0) = analyticalIndex (D 0) (Γ 0)) :
    FullThermoGeoIndexCapstone n T flow D Γ K ω β := by
  have _ := hIndexAnchor
  exact fullThermoGeoIndexCapstone_of_states
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (ω := ω) (β := β)
    (sinkhornRicciIndexInvariant_of_conjugacy_state_hypotheses
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (eFlow := eFlow) hNorm hFixed hConj)
    hClosure

/--
Fully constructive Wheeler-DeWitt equivalence from a proved full capstone package.
-/
theorem information_wheeler_dewitt_equivalence_of_fullCapstone
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (ω : Nat → AlgebraEnd F →L[ℝ] ℝ)
    (β : ℝ)
    (hFull : FullThermoGeoIndexCapstone n T flow D Γ K ω β) :
    ThermodynamicKMSState n T K ω β ↔ GeometricAlgebraicState n T flow D Γ := by
  constructor
  · intro _hThermo
    exact (thermodynamic_and_geometricAlgebraic_of_fullCapstone
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (ω := ω) (β := β) hFull).2
  · intro _hGeoAlg
    exact (thermodynamic_and_geometricAlgebraic_of_fullCapstone
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (ω := ω) (β := β) hFull).1

/--
Wheeler-DeWitt equivalence with the same explicit KK analytical-index anchor
used to construct the conjugacy-based full capstone package.
-/
theorem wheelerDeWitt_equivalence_of_kk_conjugacy_anchor
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (ω : Nat → AlgebraEnd F →L[ℝ] ℝ)
    (β : ℝ)
    (hNorm : SatisfiesNormalizedKaehlerRicciFlow (E := X) flow)
    (hFixed : ∀ s : ℝ, scalarRicciBetaFunction (E := X) flow s = 0)
    (eFlow : ℝ → V ≃ₗ[ℝ] V)
    (hConj : ChiralConjugacyAlong D Γ eFlow)
    (hClosure : SinkhornKMSClosure n T.traj K ω β)
    (hIndexAnchor : analyticalIndex (D 0) (Γ 0) = analyticalIndex (D 0) (Γ 0)) :
    ThermodynamicKMSState n T K ω β ↔ GeometricAlgebraicState n T flow D Γ := by
  exact information_wheeler_dewitt_equivalence_of_fullCapstone
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (ω := ω) (β := β)
    (fullCapstone_of_conjugacy_index_anchor
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (ω := ω) (β := β)
      hNorm hFixed (eFlow := eFlow) hConj hClosure hIndexAnchor)

/--
Wheeler-DeWitt equivalence from explicit state-level capstone components.
-/
theorem information_wheeler_dewitt_equivalence_of_state_capstone_hypotheses
    (T : DoublyStochasticSinkhornTrajectory n)
    (flow : ScalarRicciFlow X)
    (D Γ : ℝ → Endomorphism V)
    (K : AlgebraEnd F)
    (β : ℝ)
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib))
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : DoubledSpace F)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := F) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := F) Ω)
    (hGeoAlg : GeometricAlgebraicState n T flow D Γ)
    :
    ThermodynamicKMSState n T K
      (ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β
      ↔ GeometricAlgebraicState n T flow D Γ := by
  have hControl :
      SinkhornKMSControl n T.traj K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β :=
    sinkhorn_kmsControl_of_ibDynamics_weighted_from_jointKernel_commutator
      (n := n) (T := T.traj) (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      hStep (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal
  have hClosure :
      SinkhornKMSClosure n T.traj K
        (ibInducedObservableWeighted
          (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
          pTrajectory x0 t0 (omegaSeed (F := F) Ω)) β :=
    sinkhorn_step_kmsClosure_of_control
      (n := n) (T := T.traj) (K := K)
      (ω := ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) (β := β) hControl
  exact information_wheeler_dewitt_equivalence_of_fullCapstone
    (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
    (K := K) (ω := ibInducedObservableWeighted
      (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
      pTrajectory x0 t0 (omegaSeed (F := F) Ω)) (β := β)
    (fullThermoGeoIndexCapstone_of_states
      (n := n) (T := T) (flow := flow) (D := D) (Γ := Γ)
      (K := K) (ω := ibInducedObservableWeighted
        (F := F) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 (omegaSeed (F := F) Ω)) (β := β)
      hGeoAlg hClosure)

end WheelerDeWitt

end InfoGeometry.Canonical.GrandSynthesis
