import InfoGeometry.Canonical.EPAndGroupInverse
import Mathlib.Tactic.NoncommRing

namespace InfoGeometry.Canonical

open InfoGeometry.Canonical.CartanDecomposition
open InfoGeometry.Canonical.Drazin
open InfoGeometry.Canonical.MoorePenrose

/-!
# Inverse Kernel Cartan Core

This file exposes the spectral Cartan seed of the certified inverse-kernel
package through a stable owner surface. The underlying Cartan algebra lives in
`CartanDecomposition`; here we adapt it to the certified inverse-kernel center
and connect it to the projector/complement algebra.
-/

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "EndH" => E →L[ℝ] E
noncomputable local instance : NormedRing EndH := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndH := inferInstance
noncomputable local instance : NormedAlgebra ℚ EndH :=
  NormedAlgebra.restrictScalars ℚ ℝ EndH
local instance : IsTopologicalRing EndH := inferInstance
local instance : SMulCommClass ℝ EndH EndH := inferInstance
local instance : IsScalarTower ℝ EndH EndH := inferInstance

namespace CertifiedInverseKernel

variable (CIK : CertifiedInverseKernel E)

/-- Canonical spectral Cartan triple attached to the certified inverse kernel. -/
noncomputable abbrev cartanTriple : InformationCartanTriple EndH :=
  CIK.toInformationCartanTriple

/-- Spectral Cartan grading `Γ_S = 2 P_D - 1`. -/
noncomputable abbrev GammaS : EndH :=
  CIK.cartanTriple.GammaS

/-- Spectral Cartan involution `θ_S(X) = Γ_S X Γ_S`. -/
noncomputable abbrev thetaS : EndH → EndH :=
  CIK.cartanTriple.thetaS

/-- Spectral compact sector: fixed points of the Cartan involution. -/
noncomputable abbrev IsSpectralCompact (X : EndH) : Prop :=
  CIK.cartanTriple.IsSpectralCompact X

/-- Spectral noncompact sector: `-1` eigenspace of the Cartan involution. -/
noncomputable abbrev IsSpectralNonCompact (X : EndH) : Prop :=
  CIK.cartanTriple.IsSpectralNonCompact X

/-- Spectral Lie commutator. -/
abbrev spectralCommutator (X Y : EndH) : EndH :=
  InformationCartanTriple.spectralCommutator X Y

/-- Spectral compact exponential flow. -/
noncomputable abbrev spectralCompactFlow (X : EndH) (t : ℝ) : EndH :=
  CIK.cartanTriple.spectralCompactFlow X t

/-- Spectral adjoint transport by the compact flow. -/
noncomputable abbrev spectralAdjointFlow (X : EndH) (t : ℝ) (Y : EndH) : EndH :=
  CIK.cartanTriple.spectralAdjointFlow X t Y

/-- Distinguished grading flow generated by `Γ_S`. -/
noncomputable abbrev spectralGradingFlow (t : ℝ) : EndH :=
  CIK.cartanTriple.spectralGradingFlow t

/-- The spectral Cartan grading is exactly `2 P_D - 1`. -/
theorem GammaS_eq_two_mul_spectralProjector_sub_one :
    CIK.GammaS = 2 * CIK.spectralProjector - 1 := by
  rfl

/--
The spectral Cartan grading is the difference between the spectral projector
and its complement.
-/
theorem GammaS_eq_spectralProjector_sub_spectralComplementaryProjector :
    CIK.GammaS = CIK.spectralProjector - CIK.spectralComplementaryProjector := by
  change 2 * CIK.spectralProjector - 1 = CIK.spectralProjector - (1 - CIK.spectralProjector)
  noncomm_ring

/-- The spectral Cartan grading is involutive. -/
theorem GammaS_sq_eq_one :
    CIK.GammaS * CIK.GammaS = (1 : EndH) := by
  simpa [CertifiedInverseKernel.GammaS, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple] using
    InformationCartanTriple.GammaS_sq_eq_one CIK.toInformationCartanTriple CIK.hDrazin

/-- The spectral projector is the `+1` sector of the spectral grading. -/
theorem GammaS_mul_spectralProjector :
    CIK.GammaS * CIK.spectralProjector = CIK.spectralProjector := by
  simpa [CertifiedInverseKernel.GammaS, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple, CertifiedInverseKernel.spectralProjector,
    CertifiedInverseKernel.toInverseKernel'] using
    InformationCartanTriple.GammaS_mul_spectralProjector CIK.toInformationCartanTriple CIK.hDrazin

/-- The complementary spectral projector is the `-1` sector of the spectral grading. -/
theorem GammaS_mul_spectralComplementaryProjector :
    CIK.GammaS * CIK.spectralComplementaryProjector = -CIK.spectralComplementaryProjector := by
  change (2 * CIK.spectralProjector - 1) * (1 - CIK.spectralProjector) = -(1 - CIK.spectralProjector)
  noncomm_ring [CIK.spectralProjector_idempotent]

/-- The spectral Cartan involution squares to the identity. -/
theorem thetaS_involutive (X : EndH) :
    CIK.thetaS (CIK.thetaS X) = X := by
  simpa [CertifiedInverseKernel.thetaS, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple] using
    InformationCartanTriple.thetaS_involutive CIK.toInformationCartanTriple CIK.hDrazin X

/-- Spectral compactness is exactly commutation with `Γ_S`. -/
theorem isSpectralCompact_iff_commute_GammaS {X : EndH} :
    CIK.IsSpectralCompact X ↔ X * CIK.GammaS = CIK.GammaS * X := by
  simpa [CertifiedInverseKernel.IsSpectralCompact, CertifiedInverseKernel.GammaS,
    CertifiedInverseKernel.cartanTriple, CertifiedInverseKernel.toInformationCartanTriple] using
    (InformationCartanTriple.isSpectralCompact_iff_commute
      CIK.toInformationCartanTriple CIK.hDrazin (X := X))

/-- Spectral noncompactness is exactly anticommutation with `Γ_S`. -/
theorem isSpectralNonCompact_iff_anticommute_GammaS {X : EndH} :
    CIK.IsSpectralNonCompact X ↔ X * CIK.GammaS = -(CIK.GammaS * X) := by
  simpa [CertifiedInverseKernel.IsSpectralNonCompact, CertifiedInverseKernel.GammaS,
    CertifiedInverseKernel.cartanTriple, CertifiedInverseKernel.toInformationCartanTriple] using
    (InformationCartanTriple.isSpectralNonCompact_iff_anticommute
      CIK.toInformationCartanTriple CIK.hDrazin (X := X))

/-- The spectral projector lies in the compact Cartan sector. -/
theorem spectralProjector_isSpectralCompact :
    CIK.IsSpectralCompact CIK.spectralProjector := by
  simpa [CertifiedInverseKernel.IsSpectralCompact, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple, CertifiedInverseKernel.spectralProjector,
    CertifiedInverseKernel.toInverseKernel'] using
    InformationCartanTriple.spectralProjector_isSpectralCompact CIK.toInformationCartanTriple CIK.hDrazin

/-- The complementary spectral projector also lies in the compact Cartan sector. -/
theorem spectralComplementaryProjector_isSpectralCompact :
    CIK.IsSpectralCompact CIK.spectralComplementaryProjector := by
  simpa [CertifiedInverseKernel.IsSpectralCompact, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple, CertifiedInverseKernel.spectralComplementaryProjector,
    CertifiedInverseKernel.toInverseKernel'] using
    InformationCartanTriple.spectralComplement_isSpectralCompact CIK.toInformationCartanTriple CIK.hDrazin

/-- The grading flow is an additive one-parameter subgroup. -/
theorem spectralGradingFlow_add (s t : ℝ) :
    CIK.spectralGradingFlow (s + t) =
      CIK.spectralGradingFlow s * CIK.spectralGradingFlow t := by
  simpa [CertifiedInverseKernel.spectralGradingFlow, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple] using
    InformationCartanTriple.spectralGradingFlow_add CIK.toInformationCartanTriple s t

/-- The grading flow starts at the identity. -/
theorem spectralGradingFlow_zero :
    CIK.spectralGradingFlow 0 = (1 : EndH) := by
  simpa [CertifiedInverseKernel.spectralGradingFlow, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple] using
    InformationCartanTriple.spectralGradingFlow_zero CIK.toInformationCartanTriple

/-- Closed form for the grading flow generated by `Γ_S`. -/
theorem spectralGradingFlow_eq_cosh_add_sinh_GammaS (t : ℝ) :
    CIK.spectralGradingFlow t =
      Real.cosh t • (1 : EndH) + Real.sinh t • CIK.GammaS := by
  simpa [CertifiedInverseKernel.spectralGradingFlow, CertifiedInverseKernel.GammaS,
    CertifiedInverseKernel.cartanTriple, CertifiedInverseKernel.toInformationCartanTriple] using
    InformationCartanTriple.spectralGradingFlow_eq_cosh_add_sinh_GammaS
      CIK.toInformationCartanTriple CIK.hDrazin t

/-- The spectral projector commutes with the grading flow. -/
theorem spectralProjector_commutes_spectralGradingFlow (t : ℝ) :
    Commute CIK.spectralProjector (CIK.spectralGradingFlow t) := by
  simpa [CertifiedInverseKernel.spectralGradingFlow, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple, CertifiedInverseKernel.spectralProjector,
    CertifiedInverseKernel.toInverseKernel'] using
    InformationCartanTriple.spectralProjector_commutes_spectralGradingFlow
      CIK.toInformationCartanTriple CIK.hDrazin t

/-- The complementary spectral projector commutes with the grading flow. -/
theorem spectralComplementaryProjector_commutes_spectralGradingFlow (t : ℝ) :
    Commute CIK.spectralComplementaryProjector (CIK.spectralGradingFlow t) := by
  simpa [CertifiedInverseKernel.spectralGradingFlow, CertifiedInverseKernel.cartanTriple,
    CertifiedInverseKernel.toInformationCartanTriple, CertifiedInverseKernel.spectralComplementaryProjector,
    CertifiedInverseKernel.toInverseKernel'] using
    InformationCartanTriple.spectralComplement_commutes_spectralGradingFlow
      CIK.toInformationCartanTriple CIK.hDrazin t

/-- The grading adjoint flow fixes the spectral projector. -/
theorem spectralProjector_fixed_under_spectralGradingFlow (t : ℝ) :
    CIK.spectralAdjointFlow CIK.GammaS t CIK.spectralProjector = CIK.spectralProjector := by
  simpa [CertifiedInverseKernel.spectralAdjointFlow, CertifiedInverseKernel.GammaS,
    CertifiedInverseKernel.cartanTriple, CertifiedInverseKernel.toInformationCartanTriple,
    CertifiedInverseKernel.spectralProjector, CertifiedInverseKernel.toInverseKernel] using
    InformationCartanTriple.spectralProjector_fixed_under_spectralGradingFlow
      CIK.toInformationCartanTriple CIK.hDrazin t

/-- The grading adjoint flow fixes the complementary spectral projector. -/
theorem spectralComplementaryProjector_fixed_under_spectralGradingFlow (t : ℝ) :
    CIK.spectralAdjointFlow CIK.GammaS t CIK.spectralComplementaryProjector =
      CIK.spectralComplementaryProjector := by
  simpa [CertifiedInverseKernel.spectralAdjointFlow, CertifiedInverseKernel.GammaS,
    CertifiedInverseKernel.cartanTriple, CertifiedInverseKernel.toInformationCartanTriple,
    CertifiedInverseKernel.spectralComplementaryProjector, CertifiedInverseKernel.toInverseKernel] using
    InformationCartanTriple.spectralComplement_fixed_under_spectralGradingFlow
      CIK.toInformationCartanTriple CIK.hDrazin t

end CertifiedInverseKernel

end InfoGeometry.Canonical
