import InfoGeometry.Canonical.MadelungHydrodynamicPressureBridge
import InfoGeometry.Canonical.MadelungTopologicalSpin

noncomputable section

namespace InfoGeometry.Canonical.MadelungHydrodynamic

end InfoGeometry.Canonical.MadelungHydrodynamic
