import InfoGeometry.Canonical.NavierStokesBridge
import InfoGeometry.Canonical.OperatorialItakuraSaitoFramework
import InfoGeometry.Dynamics.KanDecomposition
import InfoGeometry.Physics.MetriplecticDynamicsDrivers

/-!
# Madelung--Metriplectic--Tomita frame

This is a typed assembly surface for four existing theorem owners:

* `FluidState` supplies the finite Madelung carrier;
* `TraceOperatorSpace` supplies the finite conservative/dissipative lane;
* `KanComponent` supplies the finite K/A/N signature label;
* `AlgebraEnd` supplies the modular Hamiltonian/complement lane.

The fields are intentionally kept separate.  In particular, this file does
not assert that a matrix-stage fluid is already a Hilbert-space modular
representation, nor that a zeta zero is a stationary state.
-/

noncomputable section

namespace InfoGeometry.Canonical.MadelungMetriplecticTomitaFrame

open InfoGeometry.Canonical
open InfoGeometry.Clifford.OpSignatureBridge
open InfoGeometry.Dynamics.KanDecomposition
open InfoGeometry.Physics
open InfoGeometry.Canonical.OperatorialItakuraSaitoFramework

variable {n : Type*} [Fintype n] [DecidableEq n]
variable {E : Type*}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- A theorem-safe packet of the four existing dynamical lanes. -/
structure Frame where
  /-- Finite Madelung density/velocity/pressure data. -/
  fluid : FluidState E
  /-- Hamiltonian-style finite trace-bimodule observable. -/
  H : TraceOperatorSpace n
  /-- Metric/Onsager finite trace-bimodule observable. -/
  S : TraceOperatorSpace n
  /-- Finite observable being transported. -/
  X : TraceOperatorSpace n
  /-- K/A/N signature selected for the finite coordinate chart. -/
  kan : KanComponent
  /-- Modular Hamiltonian on the doubled carrier. -/
  K : AlgebraEnd E
  /-- Relative modular operator on the doubled carrier. -/
  Delta : AlgebraEnd E

variable (F : Frame (n := n) (E := E))

/-- The finite metriplectic observable generated by the H and S lanes. -/
def finiteGenerator : TraceOperatorSpace n :=
  metriplecticGenerator F.H F.S F.X

/-! The coupling-weighted readout keeps the frame's existing carriers while
exposing the single total noncommutative driver. -/
def finiteWeightedGenerator (γ : ℝ) : TraceOperatorSpace n :=
  weightedMetriplecticGenerator γ F.H F.S F.X

theorem finiteWeightedGenerator_tracePairing_decomposition
    (γ : ℝ) (Y : TraceOperatorSpace n) :
    tracePairingNative (finiteWeightedGenerator F γ) Y =
      - tracePairingNative F.X (conservativeDriver F.H Y) +
        γ * tracePairingNative F.X (dissipativeDriver F.S Y) := by
  exact weighted_metriplectic_generator_decomposition γ F.H F.S F.X Y

theorem finiteWeightedGenerator_self_tracePairing
    (γ : ℝ) :
    tracePairingNative (finiteWeightedGenerator F γ) F.X =
      γ * tracePairingNative (dissipativeDriver F.S F.X) F.X := by
  exact weighted_metriplectic_generator_self_tracePairing γ F.H F.S F.X

theorem fluid_density_positive : 0 < F.fluid.ρ :=
  F.fluid.density_pos

theorem conservative_trace_skew (Y : TraceOperatorSpace n) :
    tracePairingNative (conservativeDriver F.H F.X) Y =
      -tracePairingNative F.X (conservativeDriver F.H Y) := by
  exact conservative_driver_trace_skew F.H F.X Y

theorem dissipative_trace_symmetric (Y : TraceOperatorSpace n) :
    tracePairingNative (dissipativeDriver F.S F.X) Y =
      tracePairingNative F.X (dissipativeDriver F.S Y) := by
  exact dissipative_driver_trace_symmetric F.S F.X Y

theorem finiteGenerator_tracePairing_decomposition
    (Y : TraceOperatorSpace n) :
    tracePairingNative (finiteGenerator F) Y =
      - tracePairingNative F.X (conservativeDriver F.H Y) +
        tracePairingNative F.X (dissipativeDriver F.S Y) := by
  exact metriplectic_generator_tracePairing_decomposition F.H F.S F.X Y

theorem finiteGenerator_self_tracePairing_eq_dissipative :
    tracePairingNative (finiteGenerator F) F.X =
      tracePairingNative (dissipativeDriver F.S F.X) F.X := by
  exact metriplectic_generator_self_tracePairing_eq_dissipative
    F.H F.S F.X

theorem conservative_energy_conserved :
    tracePairingNative F.H (conservativeDriver F.H F.X) = 0 := by
  exact conservative_energy_conservation F.H F.X

theorem kan_signature_square :
    toHypercomplexModel F.kan.signature * toHypercomplexModel F.kan.signature =
      opSignatureScalar F.kan.signature •
        (1 : InfoGeometry.Algebra.HypercomplexTriad.Mat2) := by
  exact KanComponent.signature_hypercomplex_square F.kan

/-- The modular IS complement obeys the existing Heisenberg derivative law. -/
theorem modular_complement_has_derivAt (t : ℝ) :
    HasDerivAt
      (fun s : ℝ =>
        InfoGeometry.Volume.ConnesInfinitesimal.modularHamiltonianAction
          (H := E) F.K (F.Delta - 1) s)
      (InfoGeometry.Volume.ConnesInfinitesimal.modularHamiltonianAction
        (H := E) F.K ⁅F.K, F.Delta⁆ t)
      t := by
  exact modularHamiltonianAction_relativeDeltaComplement_hasDerivAt
    (H := E) F.K F.Delta t

end InfoGeometry.Canonical.MadelungMetriplecticTomitaFrame
