import InfoGeometry.Canonical.ModularSpinorCl11MarkovJonesTopologicalColimitBridge
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Canonical.Cl11MarkovJonesTopologicalCyclicTransport
