import InfoGeometry.Canonical.BekensteinBound
import InfoGeometry.Canonical.RicciMongeAmpere
import Mathlib.Tactic

namespace InfoGeometry.Canonical.MongeAmpereCramerRao

open InfoGeometry.Convex
open InfoGeometry.Canonical.MoE
open InfoGeometry.Canonical.BekensteinBound
open InfoGeometry.Canonical.RicciMongeAmpere

section CramerRaoMetric

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- Cramer-Rao metric operator: Hessian metric operator of the information potential. -/
noncomputable abbrev cramerRaoMetricOp
    (H : HessianGeometry E) (x : E) : E →L[ℝ] E :=
  H.metricOp x

/-- Cramer-Rao metric bilinear form induced by `cramerRaoMetricOp`. -/
noncomputable abbrev cramerRaoMetric
    (H : HessianGeometry E) (x : E) (u v : E) : ℝ :=
  H.metric x u v

@[simp] theorem cramerRaoMetric_eq_inner_cramerRaoMetricOp
    (H : HessianGeometry E) (x : E) (u v : E) :
    cramerRaoMetric H x u v = inner ℝ u (cramerRaoMetricOp H x v) := rfl

end CramerRaoMetric

section MongeAmpereBridge

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [CompleteSpace E]

/-- Incompressible Monge-Ampere regime: Hessian density is identically one. -/
def IncompressibleMongeAmpere (H : HessianGeometry E) : Prop :=
  SatisfiesMongeAmpere H (fun _ => (1 : ℝ))

/-- Liouville regime: Monge-Ampere density is sourced by `exp(2 * Φ)`. -/
def LiouvilleMongeAmpere (H : HessianGeometry E) (Φ : E → ℝ) : Prop :=
  SatisfiesMongeAmperePotential H (fun x => 2 * Φ x)

@[simp] theorem liouvilleMongeAmpere_iff
    (H : HessianGeometry E) (Φ : E → ℝ) :
    LiouvilleMongeAmpere H Φ ↔
      ∀ x : E, mongeAmpereDensity H x = Real.exp (2 * Φ x) := Iff.rfl

/-- Log Monge-Ampere density equals log absolute determinant of the Cramer-Rao metric operator. -/
lemma log_mongeAmpereDensity_eq_logAbsDet_cramerRaoMetric
    (H : HessianGeometry E) (x : E) :
    Real.log (mongeAmpereDensity H x)
      = Real.log (|LinearMap.det (cramerRaoMetricOp H x).toLinearMap|) := by
  unfold mongeAmpereDensity cramerRaoMetricOp
  rw [Real.log_exp]

/-- Under nondegeneracy, Monge-Ampere density is absolute determinant of the Cramer-Rao metric. -/
lemma mongeAmpereDensity_eq_absDet_cramerRaoMetric_of_nondegenerate
    (H : HessianGeometry E) (x : E)
    (hdet : LinearMap.det (cramerRaoMetricOp H x).toLinearMap ≠ 0) :
    mongeAmpereDensity H x = |LinearMap.det (cramerRaoMetricOp H x).toLinearMap| := by
  unfold mongeAmpereDensity cramerRaoMetricOp
  rw [Real.exp_log]
  exact abs_pos.mpr hdet

/-- Incompressible Monge-Ampere plus nondegeneracy implies unit Cramer-Rao determinant magnitude. -/
theorem absDet_cramerRaoMetric_eq_one_of_incompressible
    (H : HessianGeometry E)
    (hIncomp : IncompressibleMongeAmpere H)
    (x : E)
    (hdet : LinearMap.det (cramerRaoMetricOp H x).toLinearMap ≠ 0) :
    |LinearMap.det (cramerRaoMetricOp H x).toLinearMap| = 1 := by
  calc
    |LinearMap.det (cramerRaoMetricOp H x).toLinearMap|
      = mongeAmpereDensity H x := by
          symm
          exact mongeAmpereDensity_eq_absDet_cramerRaoMetric_of_nondegenerate
            (H := H) (x := x) hdet
    _ = 1 := hIncomp x

/-- Incompressible Monge-Ampere implies zero log-volume mode of the Cramer-Rao metric. -/
theorem logAbsDet_cramerRaoMetric_eq_zero_of_incompressible
    (H : HessianGeometry E)
    (hIncomp : IncompressibleMongeAmpere H)
    (x : E) :
    Real.log (|LinearMap.det (cramerRaoMetricOp H x).toLinearMap|) = 0 := by
  have hUnit : mongeAmpereDensity H x = 1 := hIncomp x
  have hLog : Real.log (mongeAmpereDensity H x) = 0 := by
    simpa using congrArg Real.log hUnit
  exact (log_mongeAmpereDensity_eq_logAbsDet_cramerRaoMetric (H := H) (x := x)).symm.trans hLog

end MongeAmpereBridge

section SqueezingFlow

/-- Expanding eigenvalue generated by chiral squeezing at flow parameter `t`. -/
noncomputable def squeezingEigenPlus (t : ℝ) : ℝ :=
  Real.exp (2 * t)

/-- Contracting eigenvalue generated by chiral squeezing at flow parameter `t`. -/
noncomputable def squeezingEigenMinus (t : ℝ) : ℝ :=
  Real.exp (-2 * t)

/-- Logarithmic squeezing shear ratio. -/
noncomputable def squeezingLogShear (t : ℝ) : ℝ :=
  Real.log (squeezingEigenPlus t / squeezingEigenMinus t)

/-- Chiral squeezing preserves total volume. -/
@[simp] theorem squeezingEigen_product_eq_one (t : ℝ) :
    squeezingEigenPlus t * squeezingEigenMinus t = 1 := by
  unfold squeezingEigenPlus squeezingEigenMinus
  calc
    Real.exp (2 * t) * Real.exp (-2 * t)
      = Real.exp ((2 * t) + (-2 * t)) := by
          rw [← Real.exp_add]
    _ = Real.exp 0 := by ring_nf
    _ = 1 := by simp

/-- Logarithmic shear equals `4t` for the split `exp(±2t)` spectrum. -/
@[simp] theorem squeezingLogShear_eq_four_mul (t : ℝ) :
    squeezingLogShear t = 4 * t := by
  unfold squeezingLogShear squeezingEigenPlus squeezingEigenMinus
  have hPlus : Real.exp (2 * t) ≠ 0 := Real.exp_ne_zero _
  have hMinus : Real.exp (-2 * t) ≠ 0 := Real.exp_ne_zero _
  calc
    Real.log (Real.exp (2 * t) / Real.exp (-2 * t))
      = Real.log (Real.exp (2 * t)) - Real.log (Real.exp (-2 * t)) := by
          exact Real.log_div hPlus hMinus
    _ = (2 * t) - (-2 * t) := by simp
    _ = 4 * t := by ring

/-- Absolute logarithmic shear is `4|t|`. -/
@[simp] theorem abs_squeezingLogShear_eq_four_mul_abs (t : ℝ) :
    |squeezingLogShear t| = 4 * |t| := by
  rw [squeezingLogShear_eq_four_mul]
  calc
    |4 * t| = |4| * |t| := by simp [abs_mul]
    _ = 4 * |t| := by norm_num

/-- Any barrier bound on `|t|` yields a barrier bound on logarithmic squeezing shear. -/
theorem abs_squeezingLogShear_le_of_abs_time_le_barrier
    {t b : ℝ}
    (hTime : |t| ≤ b) :
    |squeezingLogShear t| ≤ 4 * b := by
  rw [abs_squeezingLogShear_eq_four_mul_abs]
  nlinarith [hTime]

end SqueezingFlow

section BekensteinBridge

variable {n : Nat} (T : SinkhornTrajectory n)

/--
Topological Bekenstein bound controls the absolute logarithmic squeezing shear,
provided the flow-time budget is bounded by the same RN barrier level.
-/
theorem abs_squeezingLogShear_le_of_topologicalBekensteinBound
    (hBound : TopologicalBekensteinBound n T)
    (k : Nat)
    (t : ℝ)
    (hTime : |t| ≤ trajectoryRNBarrier n T k) :
    |squeezingLogShear t| ≤ 4 * trajectoryRNBarrier n T k := by
  have hBarrierNonneg : 0 ≤ trajectoryRNBarrier n T k := hBound k
  rw [abs_squeezingLogShear_eq_four_mul_abs]
  nlinarith [hTime, hBarrierNonneg]

/-- Canonical specialization using the built-in Sinkhorn trajectory Bekenstein theorem. -/
theorem abs_squeezingLogShear_le_of_sinkhornTrajectory
    (k : Nat)
    (t : ℝ)
    (hTime : |t| ≤ trajectoryRNBarrier n T k) :
    |squeezingLogShear t| ≤ 4 * trajectoryRNBarrier n T k := by
  exact abs_squeezingLogShear_le_of_topologicalBekensteinBound
    (T := T)
    (hBound := topologicalBekensteinBound_of_sinkhornTrajectory (n := n) T)
    k t hTime

end BekensteinBridge

end InfoGeometry.Canonical.MongeAmpereCramerRao
