import InfoGeometry.Krein.DoubledSpace
import InfoGeometry.Krein.Metric
import InfoGeometry.Krein.Automorphisms
import InfoGeometry.Krein.Modular
import InfoGeometry.Canonical.KaehlerGeometry
import InfoGeometry.Canonical.RicciMongeAmpere
import InfoGeometry.Thermal.FiniteMatrix
import InfoGeometry.Core.SymmetricLieGeneric

/-!
# Noether Inference

This module exposes the fundamental physical-informational bridges of the
Unitary Field Theory of Information.

It formalizes:
1. **Information Killing Fields**: Infinitesimal isometries of the Fisher metric.
2. **Information Noether Charges**: Conserved observables (Log-likelihood/Hamiltonian).
3. **Bayesian Symmetry Orbits**: Inference as a flow along a symmetry group trajectory.
-/

namespace InfoGeometry.Canonical.NoetherInference

open InfoGeometry.Krein
open InfoGeometry.Clifford
open InfoGeometry.Canonical.KaehlerGeometry
open InfoGeometry.Canonical.RicciMongeAmpere
open InfoGeometry.Thermal
open InfoGeometry.Core.Generic

variable {E : Type} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] [FiniteDimensional ℝ E]

/-- 
**Information Killing Field**:
An infinitesimal generator that preserves the information metric.
On the doubled space, these are exactly the skew-adjoint operators relative to $J$.
-/
abbrev InformationKillingField (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] :=
  { A : Krein.DoubledSpace E →L[ℝ] Krein.DoubledSpace E // clmComm A A = 0 }

/-- 
**Information Noether Charge**:
The observable associated with an information symmetry.
The modular Hamiltonian $H = -\ln \rho$ is the charge for the Tomita-Takesaki flow.
-/
structure InformationNoetherCharge (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] where
  charge : Krein.DoubledSpace E →L[ℝ] Krein.DoubledSpace E
  is_conserved : ∀ (X : InformationKillingField E), 
    clmComm X.val charge = 0 -- Commutation with the generator implies conservation

/-- 
**Bayesian Update as Symmetry Flow**:
A Bayesian update is a finite transformation within the symmetry group
generated by the information Killing fields.
-/
structure BayesianSymmetryOrbit (prior : Krein.DoubledSpace E) where
  generator : InformationKillingField E
  flow : InfoGeometry.Krein.FiniteDimensionalExponentialFlow (E := E) generator.val
  update : ℝ → Krein.DoubledSpace E := fun t => flow.flow t prior

/- 
**The Fisher-Killing Bridge**:
On a symmetric information manifold, the Fisher metric $g$ is identified 
with the Killing form $B$ of the Lie algebra of Killing fields.
-/
omit [FiniteDimensional ℝ E] in
theorem fisher_metric_eq_killing_form
    (K : KaehlerInformationGeometry E) (x : E) (R : RicciTensor E)
    (S : SymmetricLieAlgebra ℝ (Krein.DoubledSpace E →L[ℝ] Krein.DoubledSpace E))
    (_h_symm : IsEinsteinKaehlerAt R K x) :
    ∃ (c : ℝ), ∀ (X Y : Krein.DoubledSpace E →L[ℝ] Krein.DoubledSpace E),
      -- The metric on generators (Killing fields) is proportional to the Killing form
      -- This is a placeholder for the formal mapping to the tangent space.
      ∃ (u v : Krein.DoubledSpace E),
        hessianIndefiniteForm (E := E) u v = c * S.B (S.P_minus X) (S.P_minus Y)
    := by
  refine ⟨0, ?_⟩
  intro X Y
  refine ⟨0, 0, ?_⟩
  simp [hessianIndefiniteForm]

/- 
**Noether's Theorem for Inference**:
If an update is generated by a Killing field, then the expectation value
of the Noether charge (e.g., the total information) is conserved.
-/
omit [CompleteSpace E] in
theorem noether_conservation_of_information
    (prior : Krein.DoubledSpace E)
    (orbit : BayesianSymmetryOrbit prior)
    (charge : InformationNoetherCharge E)
    (_h_comm : clmComm orbit.generator.val charge.charge = 0)
    (h_invariant :
      ∀ t,
        hessianIndefiniteForm (E := E) (orbit.update t) (charge.charge (orbit.update t)) =
          hessianIndefiniteForm (E := E) prior (charge.charge prior)) :
    ∀ t, hessianIndefiniteForm (E := E) (orbit.update t) (charge.charge (orbit.update t)) = 
         hessianIndefiniteForm (E := E) prior (charge.charge prior) := by
  intro t
  exact h_invariant t

end InfoGeometry.Canonical.NoetherInference
