import InfoGeometry.Canonical.OperatorValuedSouriauFamily
import InfoGeometry.Algebra.FiniteSpinAlgebra

/-!
# InfoGeometry.Canonical.OperatorValuedSouriauFamilyChecks

Smoke checks for the operator-valued Souriau family socket.
-/

namespace InfoGeometry.Canonical.OperatorValuedSouriauFamily.Checks

#check OperatorValuedSouriauFamily
#check OperatorValuedSouriauFamily.beta_is_operatorial
#check OperatorValuedSouriauFamily.time_is_operatorial
#check OperatorValuedSouriauFamily.scalar_time_chart_only
#check OperatorValuedSouriauFamily.scalar_beta_chart_shadow_only
#check OperatorValuedSouriauFamily.souriauGenerator_law_valid
#check OperatorValuedSouriauFamily.expWeight_law_valid
#check OperatorValuedSouriauFamily.duhamel_derivative_law
#check OperatorValuedSouriauFamily.scalar_readout_downstream_only
#check OperatorValuedSouriauFamily.exponentialFamily_K_beta_eq_souriauGenerator
#check OperatorValuedSouriauFamily.exponentialFamily_untraced_beta_eq_expWeight
#check OperatorValuedSouriauFamily.betaScalarReadout
#check OperatorValuedSouriauFamily.timeScalarReadout
#check OperatorValuedSouriauFamily.souriauGeneratorScalarReadout
#check OperatorValuedSouriauFamily.beta_mul_souriauGenerator_closed
#check OperatorValuedSouriauFamily.time_mul_souriauGenerator_closed
#check OperatorValuedSouriauFamily.betaSouriauAction
#check OperatorValuedSouriauFamily.timeSouriauAction

end InfoGeometry.Canonical.OperatorValuedSouriauFamily.Checks
