/-
InfoGeometry/Canonical/OperatorThermodynamics.lean

Operator-first thermodynamics over a modular operator and an operatorial
exponential family.  Scalar Massieu/free-energy values below are derived
readouts of the operatorial family; no independent scalar packet is stored.
-/

import Mathlib.Analysis.SpecialFunctions.Log.Basic
import InfoGeometry.Algebraic.SplitSuperGeometry
import InfoGeometry.Canonical.ModularSurprisalThermoPacket
import InfoGeometry.Canonical.RelativeModularHamiltonian
import InfoGeometry.Canonical.SouriauThermodynamics
import InfoGeometry.Canonical.SouriauOperatorialLogPotential
import InfoGeometry.Canonical.NativeOperatorialExponentialFamily
import InfoGeometry.Thermo.FromLogDet

noncomputable section

namespace InfoGeometry.Canonical.OperatorThermodynamics

open InfoGeometry.Canonical
open InfoGeometry.Canonical.ModularSurprisalThermoPacket
open InfoGeometry.Canonical.RelativeModularHamiltonian
open InfoGeometry.Canonical.SouriauThermodynamics
open InfoGeometry.Canonical.SouriauOperatorialLogPotential
open InfoGeometry.Algebraic.SplitSuperGeometry

/-!
The operator-first packet is the sole owner in this module.  The modular
negative-log operator and the untraced exponential family remain separate
native carriers; scalar thermodynamic quantities are readouts at one chosen
parameter.
-/
structure OperatorFirstThermodynamicsPacket
    (Param Op : Type*) [AddMonoid Param]
    [NormedRing Op] [NormedAlgebra ℝ Op] [CompleteSpace Op] where
  modular : ModularHamiltonianSurprisalContext (H := Op)
  family : NativeOperatorialExponentialFamily.Family Param Op
  referenceParam : Param
  partitionFunction_pos : 0 < family.partitionFunction referenceParam

namespace OperatorFirstThermodynamicsPacket

variable {Param Op : Type*} [AddMonoid Param]
variable [NormedRing Op] [NormedAlgebra ℝ Op] [CompleteSpace Op]

def modularHamiltonian
    (P : OperatorFirstThermodynamicsPacket Param Op) : Op →L[ℝ] Op :=
  P.modular.modularHamiltonian

def negativeLogModularOperator
    (P : OperatorFirstThermodynamicsPacket Param Op) : Op →L[ℝ] Op :=
  P.modular.negativeLogModularOperator

def partitionFunction
    (P : OperatorFirstThermodynamicsPacket Param Op) : ℝ :=
  P.family.partitionFunction P.referenceParam

def massieuPotential
    (P : OperatorFirstThermodynamicsPacket Param Op) : ℝ :=
  Real.log P.partitionFunction

def freeEnergy
    (P : OperatorFirstThermodynamicsPacket Param Op) : ℝ :=
  -Real.log P.partitionFunction

def negativeMassieuPotential
    (P : OperatorFirstThermodynamicsPacket Param Op) : ℝ :=
  -P.massieuPotential

def supervolumePotential
    (P : OperatorFirstThermodynamicsPacket Param Op) : ℝ :=
  P.freeEnergy

@[simp]
theorem modularHamiltonian_eq_negativeLogModularOperator
    (P : OperatorFirstThermodynamicsPacket Param Op) :
    P.modularHamiltonian = P.negativeLogModularOperator :=
  P.modular.modularHamiltonian_eq_negativeLog

@[simp]
theorem partitionFunction_eq_family_readout
    (P : OperatorFirstThermodynamicsPacket Param Op) :
    P.partitionFunction = P.family.partitionFunction P.referenceParam :=
  rfl

@[simp]
theorem massieuPotential_eq_log_partition
    (P : OperatorFirstThermodynamicsPacket Param Op) :
    P.massieuPotential = Real.log P.partitionFunction :=
  rfl

@[simp]
theorem freeEnergy_eq_neg_log_partition
    (P : OperatorFirstThermodynamicsPacket Param Op) :
    P.freeEnergy = -Real.log P.partitionFunction :=
  rfl

@[simp]
theorem negativeMassieuPotential_eq_neg_massieu
    (P : OperatorFirstThermodynamicsPacket Param Op) :
    P.negativeMassieuPotential = -P.massieuPotential :=
  rfl

@[simp]
theorem supervolumePotential_eq_freeEnergy
    (P : OperatorFirstThermodynamicsPacket Param Op) :
    P.supervolumePotential = P.freeEnergy :=
  rfl

/--
Static/zero-generator thermodynamics with unit partition readout.

The generator is identically zero so `exp(-K) = 1`.  When the trace readout
sends `1 ↦ 1`, the partition function is exactly `1 > 0`.  This is the
Boltzmann vacuum: no Hamiltonian, uniform measure, unit normalisation.
-/
noncomputable def ofStaticUnitPartition
    {Op : Type*}
    [NormedRing Op] [NormedAlgebra ℝ Op] [CompleteSpace Op]
    (traceReadout : Op → ℝ)
    (h_trace_one : traceReadout 1 = 1) :
    OperatorFirstThermodynamicsPacket Unit Op where
  modular := (0, 0)
  family :=
    { generator := fun _ => 0
      traceReadout := traceReadout
      generator_add := fun _ _ => (add_zero (0 : Op)).symm
      generator_commute := fun _ _ => Commute.zero_left _ }
  referenceParam := ()
  partitionFunction_pos := by
    show 0 < traceReadout (NormedSpace.exp (-(0 : Op)))
    simp [neg_zero, NormedSpace.exp_zero, h_trace_one]

/--
Linear 1-parameter exponential family generated by a fixed operator `K : Op`.

The generator is `t ↦ t • K`.  The partition function `trace(exp(-K))` is
witnessed positive at `t = 1`.
-/
noncomputable def ofLinearOneParameter
    {Op : Type*}
    [NormedRing Op] [NormedAlgebra ℝ Op] [CompleteSpace Op]
    (K : Op)
    (traceReadout : Op → ℝ)
    (modularPair : (Op →L[ℝ] Op) × (Op →L[ℝ] Op))
    (hpos : 0 < traceReadout (NormedSpace.exp (-K))) :
    OperatorFirstThermodynamicsPacket ℝ Op where
  modular := modularPair
  family :=
    { generator := fun t => t • K
      traceReadout := traceReadout
      generator_add := fun s t => add_smul s t K
      generator_commute := fun s t => by
        show (s • K) * (t • K) = (t • K) * (s • K)
        rw [Algebra.smul_mul_assoc, Algebra.mul_smul_comm, Algebra.smul_mul_assoc, Algebra.mul_smul_comm, smul_smul, smul_smul, mul_comm s t] }
  referenceParam := 1
  partitionFunction_pos := by
    dsimp [NativeOperatorialExponentialFamily.Family.partitionFunction,
           NativeOperatorialExponentialFamily.Family.untracedExponential]
    rw [one_smul]
    exact hpos

/--
Scalar vacuum instance: static zero generator on `ℝ` with positive trace readout.
-/
noncomputable def ofPositiveScalar
    (traceReadout : ℝ → ℝ)
    (htr : 0 < traceReadout 1) :
    OperatorFirstThermodynamicsPacket Unit ℝ where
  modular := (0, 0)
  family :=
    { generator := fun _ => 0
      traceReadout := traceReadout
      generator_add := fun _ _ => (add_zero (0 : ℝ)).symm
      generator_commute := fun _ _ => Commute.zero_left _ }
  referenceParam := ()
  partitionFunction_pos := by
    show 0 < traceReadout (NormedSpace.exp (-(0 : ℝ)))
    simp [neg_zero, NormedSpace.exp_zero, htr]

end OperatorFirstThermodynamicsPacket

end InfoGeometry.Canonical.OperatorThermodynamics
