import Mathlib.Tactic
import InfoGeometry.Algebra.FiniteSpinAlgebra

/-!
# Noncommutative Operator-Based Geometry and Graded Adjoint Actions

This file formalizes the transition from classical state carriers to 
noncommutative operator-based geometry. We move the geometry directly into 
the algebra of transformations, bypassing scalar diagonal models.

1. **Operator Algebra Grading**: The chirality operator `Γ` splits the full
   operator algebra into even and odd sectors: 
   `A_even = {X | ΓX = XΓ}`
   `A_odd = {X | ΓX = -XΓ}`
2. **Adjoint Action**: The Lorentz group action is lifted to the inner 
   automorphism `Ad_U(X) = U X U⁻¹`.
3. **Lorentz Grading Preservation**: Since the Lorentz generators are quadratic 
   CAR operators, they are intrinsically `even`. We prove that the Adjoint 
   action generated by any even operator identically preserves the `even/odd`
   observable grading.
-/

variable {A : Type*} [Ring A]
variable (Γ : A)

/-- The grading operator is an involution. -/
def OperatorChirality (Γ : A) : Prop := Γ * Γ = 1

namespace NoncommutativeGeometry

/-- The Even sector of the noncommutative observable algebra. 
    Defined by commutativity with the chiral grading operator. -/
def isEven (X : A) : Prop := Γ * X = X * Γ

/-- The Odd sector of the noncommutative observable algebra. 
    Defined by anticommutativity with the chiral grading operator. -/
def isOdd (X : A) : Prop := Γ * X + X * Γ = 0

/-- The inner Adjoint action of a group element U on the operator algebra. -/
def Ad (U : Aˣ) (X : A) : A := (U : A) * X * (↑(U⁻¹) : A)

/-- A Lorentz transformation U is generated by even quadratic operators,
    hence U itself must belong to the even sector. -/
class IsLorentzAutomorphism (U : Aˣ) where
  is_even : isEven Γ (U : A)

lemma lorentz_inv_is_even (U : Aˣ) [L : IsLorentzAutomorphism Γ U] :
    isEven Γ (↑(U⁻¹) : A) := by
  unfold isEven
  calc
    Γ * (↑(U⁻¹) : A) = 1 * Γ * (↑(U⁻¹) : A) := by rw [one_mul]
    _ = ((↑(U⁻¹) : A) * (U : A)) * Γ * (↑(U⁻¹) : A) := by simp
    _ = (↑(U⁻¹) : A) * ((U : A) * Γ) * (↑(U⁻¹) : A) := by simp only [mul_assoc]
    _ = (↑(U⁻¹) : A) * (Γ * (U : A)) * (↑(U⁻¹) : A) := by
      have he : Γ * (U : A) = (U : A) * Γ := L.is_even
      rw [he]
    _ = (↑(U⁻¹) : A) * Γ * ((U : A) * (↑(U⁻¹) : A)) := by simp only [mul_assoc]
    _ = (↑(U⁻¹) : A) * Γ * 1 := by simp
    _ = (↑(U⁻¹) : A) * Γ := by rw [mul_one]

/-- The Lorentz Adjoint action universally preserves the even observable sector. -/
theorem lorentz_ad_preserves_even (U : Aˣ) (X : A) [L : IsLorentzAutomorphism Γ U]
    (hX : isEven Γ X) : isEven Γ (Ad U X) := by
  unfold isEven Ad
  have hu : Γ * (U : A) = (U : A) * Γ := L.is_even
  have hinv : Γ * (↑(U⁻¹) : A) = (↑(U⁻¹) : A) * Γ := lorentz_inv_is_even Γ U
  calc
    Γ * Ad U X = (Γ * (U : A)) * X * (↑(U⁻¹) : A) := by simp [Ad, mul_assoc]
    _ = ((U : A) * Γ) * X * (↑(U⁻¹) : A) := by rw [hu]
    _ = (U : A) * (Γ * X) * (↑(U⁻¹) : A) := by simp only [mul_assoc]
    _ = (U : A) * (X * Γ) * (↑(U⁻¹) : A) := by rw [hX]
    _ = ((U : A) * X) * (Γ * (↑(U⁻¹) : A)) := by simp only [mul_assoc]
    _ = ((U : A) * X) * ((↑(U⁻¹) : A) * Γ) := by rw [hinv]
    _ = Ad U X * Γ := by simp [Ad, mul_assoc]

/-- The Lorentz Adjoint action universally preserves the odd observable sector. -/
theorem lorentz_ad_preserves_odd (U : Aˣ) (X : A) [L : IsLorentzAutomorphism Γ U]
    (hX : isOdd Γ X) : isOdd Γ (Ad U X) := by
  unfold isOdd Ad
  have hu : Γ * (U : A) = (U : A) * Γ := L.is_even
  have hinv : Γ * (↑(U⁻¹) : A) = (↑(U⁻¹) : A) * Γ := lorentz_inv_is_even Γ U
  have hX2 : Γ * X = - (X * Γ) := by
    calc
      Γ * X = Γ * X + X * Γ - X * Γ := by rw [add_sub_cancel_right]
      _ = 0 - X * Γ := by rw [hX]
      _ = - (X * Γ) := by rw [zero_sub]
  calc
    Γ * Ad U X + Ad U X * Γ
      = (Γ * (U : A)) * X * (↑(U⁻¹) : A) + ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by simp [Ad, mul_assoc]
    _ = ((U : A) * Γ) * X * (↑(U⁻¹) : A) + ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by rw [hu]
    _ = (U : A) * (Γ * X) * (↑(U⁻¹) : A) + ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by simp only [mul_assoc]
    _ = (U : A) * (- (X * Γ)) * (↑(U⁻¹) : A) + ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by rw [hX2]
    _ = - ((U : A) * (X * Γ) * (↑(U⁻¹) : A)) + ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by rw [mul_neg, neg_mul]
    _ = - (((U : A) * X * (↑(U⁻¹) : A)) * Γ) + ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by
      have hconj :
          (U : A) * (X * Γ) * (↑(U⁻¹) : A) =
            ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by
        calc
          (U : A) * (X * Γ) * (↑(U⁻¹) : A) =
              (U : A) * X * (Γ * (↑(U⁻¹) : A)) := by simp only [mul_assoc]
          _ = (U : A) * X * ((↑(U⁻¹) : A) * Γ) := by rw [hinv]
          _ = ((U : A) * X * (↑(U⁻¹) : A)) * Γ := by simp only [mul_assoc]
      rw [hconj]
    _ = 0 := by rw [neg_add_cancel]

end NoncommutativeGeometry
