import InfoGeometry.Clifford.Cl55WittPinNativeTwistedAction
import InfoGeometry.Clifford.Cl55WittPinKernelEvidence
import InfoGeometry.Clifford.Cl55WittNativeIsometryGroup

namespace InfoGeometry.Clifford.Clifford55

/-!
# Native Pin(5,5) orthogonal action

This owner exposes the already constructed native action on the canonical
quadratic-isometry group.  It records the genuine consequences available in
the current Clifford development: preservation of `Q55`, the explicit
reflection images, and the central sign in the kernel.  It deliberately does
not assert Cartan--Dieudonné surjectivity or equality of the full kernel with
`{±1}`.
-/

noncomputable abbrev pin55OrthogonalAction : Pin55 →* orthogonalGroup55 :=
  pinTwistedOrthogonalAction

noncomputable abbrev pin55NativeOrthogonalAction : Pin55 →* Q55.IsometryEquiv Q55 :=
  pinTwistedNativeOrthogonalAction

/-!
`Pin55` above is Mathlib's unitary `pinGroup Q55`.  The full real split
`Pin(5,5)` is the Clifford-unit subgroup generated by all normalized
anisotropic vectors.  Its native action and exact covering theorems are
already established by the Clifford owners imported below.
-/

abbrev RealPin55 := realSplitPin55

noncomputable abbrev realPin55OrthogonalAction :
    RealPin55 →* Q55.IsometryEquiv Q55 :=
  realSplitPinNativeOrthogonalAction

theorem pin55NativeOrthogonalAction_preserves_Q55
    (g : Pin55) (v : V55) :
    Q55 (pin55NativeOrthogonalAction g v) = Q55 v := by
  exact pinTwistedAction_preserves_Q55 g v

theorem pin55NativeOrthogonalAction_fNegPin
    (i : Fin 5) :
    pin55NativeOrthogonalAction (fNegPin i) =
      negativeReflectionIsometry i := by
  exact pinTwistedNativeOrthogonalAction_fNegPin_eq_negativeReflectionIsometry i

theorem pin55NativeOrthogonalAction_globalSheetPin :
    pin55NativeOrthogonalAction globalSheetPin =
      globalSheetReflectionIsometry := by
  exact pinTwistedNativeOrthogonalAction_globalSheetPin_eq_globalSheetReflectionIsometry

theorem negOnePin_mem_pin55NativeOrthogonalAction_kernel :
    negOnePin ∈ (pin55NativeOrthogonalAction).ker := by
  change pin55NativeOrthogonalAction negOnePin = 1
  rw [pinTwistedNativeOrthogonalAction_apply]
  exact congrArg orthogonalGroup55IsometryEquiv
    pinTwistedOrthogonalAction_negOnePin

theorem realPin55OrthogonalAction_surjective :
    Function.Surjective realPin55OrthogonalAction :=
  realSplitPinNativeOrthogonalAction_surjective

theorem realPin55OrthogonalAction_mem_kernel_iff_pm_one
    (g : RealPin55) :
    g ∈ (realPin55OrthogonalAction).ker ↔
      (g : Cl55ˣ) = 1 ∨ (g : Cl55ˣ) = -1 :=
  realSplitPinNativeOrthogonalAction_mem_kernel_iff_pm_one g

theorem realPin55OrthogonalAction_kernel_eq_signSubgroup :
    (realPin55OrthogonalAction).ker = realSplitPinSignSubgroup :=
  realSplitPinNativeOrthogonalAction_kernel_eq_signSubgroup

noncomputable def realPin55SignQuotientEquiv :
    (RealPin55 ⧸ (realSplitPinSignSubgroup : Subgroup RealPin55)) ≃*
      Q55.IsometryEquiv Q55 :=
  realSplitPinNativeSignQuotientEquiv

theorem realPin55SignQuotientEquiv_mk
    (g : RealPin55) :
    realPin55SignQuotientEquiv (QuotientGroup.mk g) =
      realPin55OrthogonalAction g :=
  realSplitPinNativeSignQuotientEquiv_mk g

end InfoGeometry.Clifford.Clifford55
