import InfoGeometry.Canonical.RelativePotentialDiscreteBridge
import InfoGeometry.Canonical.RelativePotentialScalarBridge
import InfoGeometry.Canonical.SinkhornKMSCore
import InfoGeometry.Canonical.KreinDoubledAtom
import InfoGeometry.Meta.Architecture

/-!
# InfoGeometry.Canonical.RelativePotentialCountBridge

Discrete count-side representation of the projective/affine relative-potential
spine.

This file keeps the raw finite-count presentation available while making its
status explicit: raw count ratios are representative-level objects, whereas the
canonical projective relative density is obtained only after quotienting by
positive rescaling and taking the canonical gauge.
-/

open scoped BigOperators

namespace RelativePotentialCountBridge

open InfoGeometry.Canonical.PositiveRayCore
open InfoGeometry.Canonical.RelativePotentialCore
open InfoGeometry.Canonical.KMSSinkhornBridge
open InfoGeometry.Krein

universe u

section Counts

variable (n : Nat)

/-- Relative-count profile over a finite sample index set. -/
abbrev RelativeCounts := Fin n → ℝ

/-- Raw relative count ratio. This is a representative-level density. -/
noncomputable def relativeCountDensity
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  fun i => counts i / ref i

/-- Pointwise logarithm of the raw relative count ratio. -/
@[rep_depth count]
noncomputable def relativeCountLogDensity
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  fun i => Real.log (relativeCountDensity n counts ref i)

/-- Raw count-side modular potential profile. -/
@[rep_depth count]
noncomputable def relativeCountModularProfile
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  fun i => -relativeCountLogDensity n counts ref i

/-- Raw count ratio as the commutative relative modular profile `Δ`. -/
noncomputable def rawCountDelta
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  relativeCountDensity n counts ref

/-- Raw logarithmic modular profile `log Δ`. -/
noncomputable def rawCountLogDelta
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  relativeCountLogDensity n counts ref

/-- Raw Hamiltonian modular profile `-log Δ`. -/
noncomputable def rawCountHamiltonianProfile
    (counts ref : RelativeCounts n) : Fin n → ℝ :=
  relativeCountModularProfile n counts ref

@[simp] theorem relativeCountDensity_common_smul
    (c : ℝ)
    (hc : c ≠ 0)
    (counts ref : RelativeCounts n) :
    relativeCountDensity n (c • counts) (c • ref) = relativeCountDensity n counts ref := by
  funext i
  simpa [relativeCountDensity, Pi.smul_apply, smul_eq_mul] using
    (mul_div_mul_left (counts i) (ref i) hc)

@[simp] theorem rawCountDelta_common_smul
    (c : ℝ)
    (hc : c ≠ 0)
    (counts ref : RelativeCounts n) :
    rawCountDelta n (c • counts) (c • ref) = rawCountDelta n counts ref := by
  simpa [rawCountDelta] using
    relativeCountDensity_common_smul (n := n) c hc counts ref

@[simp] theorem relativeCountLogDensity_common_pos_smul
    (c : ℝ)
    (hc : 0 < c)
    (counts ref : RelativeCounts n) :
    relativeCountLogDensity n (c • counts) (c • ref) = relativeCountLogDensity n counts ref := by
  funext i
  simp [relativeCountLogDensity, relativeCountDensity_common_smul (n := n) c hc.ne']

@[simp] theorem relativeCountModularProfile_common_pos_smul
    (c : ℝ)
    (hc : 0 < c)
    (counts ref : RelativeCounts n) :
    relativeCountModularProfile n (c • counts) (c • ref)
      = relativeCountModularProfile n counts ref := by
  simpa [relativeCountModularProfile] using
    congrArg (fun f => fun i => -f i)
      (relativeCountLogDensity_common_pos_smul (n := n) c hc counts ref)


/--
Mean logarithmic modular profile of a finite commutative `Δ` profile.

This is a derived scalar collapse of the owner count-side profile, not the
owner object itself.
-/
noncomputable def meanLogDeltaProfile (ρ : Fin n → ℝ) : ℝ :=
  (n : ℝ)⁻¹ * ∑ i : Fin n, Real.log (ρ i)

/--
Averaged modular Hamiltonian obtained by collapsing a finite commutative `Δ`
profile to its arithmetic mean.
-/
noncomputable def averagedModularHamiltonian (ρ : Fin n → ℝ) : ℝ :=
  -meanLogDeltaProfile n ρ

/--
Continuous avatar of the canonical doubled-atom grading `ε` on the doubled
router-amplitude carrier.
-/
noncomputable def doubledAtomEpsilonOp : AlgebraEnd (RouterAmplitude n) :=
  LinearMap.toContinuousLinearMap
    ((InfoGeometry.Canonical.cl11DoubledAtom (RouterAmplitude n)).eps)

@[simp] theorem doubledAtomEpsilonOp_eq_spectralEpsilon :
    doubledAtomEpsilonOp (n := n)
      = InfoGeometry.Krein.spectral_epsilon (E := RouterAmplitude n) := by
  rfl

/--
Averaged Krein-native Tomita-Takesaki operator generated by the scalar average
of the modular Hamiltonian on the doubled router-amplitude space.

This places the scalar collapse on the canonical doubled `ε`-action rather than
on the isotropic identity action.
-/
noncomputable def averagedKreinTomitaTakesakiOp
    (ρ : Fin n → ℝ) : AlgebraEnd (RouterAmplitude n) :=
  averagedModularHamiltonian n ρ • doubledAtomEpsilonOp (n := n)

@[simp] lemma averagedKreinTomitaTakesakiOp_apply
    (ρ : Fin n → ℝ) (v : DoubledSpace (RouterAmplitude n)) :
    averagedKreinTomitaTakesakiOp n ρ v =
      averagedModularHamiltonian n ρ •
        (InfoGeometry.Krein.spectral_epsilon (E := RouterAmplitude n) v) := by
  simp [averagedKreinTomitaTakesakiOp, doubledAtomEpsilonOp_eq_spectralEpsilon]

/--
Averaged Tomita-Takesaki-style operator generated by the scalar average of the
modular Hamiltonian on the doubled router-amplitude space.

This remains the isotropic compatibility collapse used by the older continuum
RN/modular lane. The Krein-native count action is `averagedKreinTomitaTakesakiOp`.
-/
noncomputable def averagedTomitaTakesakiOp
    (ρ : Fin n → ℝ) : AlgebraEnd (RouterAmplitude n) :=
  averagedModularHamiltonian n ρ •
    ContinuousLinearMap.id ℝ (DoubledSpace (RouterAmplitude n))

@[simp] lemma averagedTomitaTakesakiOp_apply
    (ρ : Fin n → ℝ) (v : DoubledSpace (RouterAmplitude n)) :
    averagedTomitaTakesakiOp n ρ v = averagedModularHamiltonian n ρ • v := by
  simp [averagedTomitaTakesakiOp]

/-- Averaged Hamiltonian obtained by collapsing the raw count-side `Δ` profile. -/
noncomputable def averagedRawCountHamiltonian
    (counts ref : RelativeCounts n) : ℝ :=
  averagedModularHamiltonian n (rawCountDelta n counts ref)

@[simp] theorem averagedRawCountHamiltonian_common_smul
    (c : ℝ)
    (hc : c ≠ 0)
    (counts ref : RelativeCounts n) :
    averagedRawCountHamiltonian n (c • counts) (c • ref)
      = averagedRawCountHamiltonian n counts ref := by
  simp [averagedRawCountHamiltonian, rawCountDelta_common_smul (n := n) c hc]

@[simp] theorem averagedRawCountHamiltonian_eq_mean_rawCountHamiltonianProfile
    (counts ref : RelativeCounts n) :
    averagedRawCountHamiltonian n counts ref
      = (n : ℝ)⁻¹ * ∑ i : Fin n, rawCountHamiltonianProfile n counts ref i := by
  unfold averagedRawCountHamiltonian averagedModularHamiltonian meanLogDeltaProfile
  calc
    -((n : ℝ)⁻¹ * ∑ i : Fin n, Real.log (rawCountDelta n counts ref i))
      = (n : ℝ)⁻¹ * (-(∑ i : Fin n, Real.log (rawCountDelta n counts ref i))) := by ring
    _ = (n : ℝ)⁻¹ * ∑ i : Fin n, -Real.log (rawCountDelta n counts ref i) := by
          rw [← Finset.sum_neg_distrib]
    _ = (n : ℝ)⁻¹ * ∑ i : Fin n, rawCountHamiltonianProfile n counts ref i := by
          refine congrArg ((n : ℝ)⁻¹ * ·) ?_
          refine Finset.sum_congr rfl ?_
          intro i hi
          rfl

/-- Averaged Krein-native Tomita-Takesaki operator attached to the raw count-side `Δ` profile. -/
noncomputable def averagedRawCountKreinTomitaTakesakiOp
    (counts ref : RelativeCounts n) : AlgebraEnd (RouterAmplitude n) :=
  averagedKreinTomitaTakesakiOp n (rawCountDelta n counts ref)

@[simp] theorem averagedRawCountKreinTomitaTakesakiOp_common_smul
    (c : ℝ)
    (hc : c ≠ 0)
    (counts ref : RelativeCounts n) :
    averagedRawCountKreinTomitaTakesakiOp n (c • counts) (c • ref)
      = averagedRawCountKreinTomitaTakesakiOp n counts ref := by
  simp [averagedRawCountKreinTomitaTakesakiOp, rawCountDelta_common_smul (n := n) c hc]

@[simp] lemma averagedRawCountKreinTomitaTakesakiOp_apply
    (counts ref : RelativeCounts n) (v : DoubledSpace (RouterAmplitude n)) :
    averagedRawCountKreinTomitaTakesakiOp n counts ref v =
      averagedRawCountHamiltonian n counts ref •
        (InfoGeometry.Krein.spectral_epsilon (E := RouterAmplitude n) v) := by
  simp [averagedRawCountKreinTomitaTakesakiOp, averagedRawCountHamiltonian]

/-- Averaged Tomita-Takesaki-style operator attached to the raw count-side `Δ` profile. -/
noncomputable def averagedRawCountTomitaTakesakiOp
    (counts ref : RelativeCounts n) : AlgebraEnd (RouterAmplitude n) :=
  averagedTomitaTakesakiOp n (rawCountDelta n counts ref)

@[simp] theorem averagedRawCountTomitaTakesakiOp_common_smul
    (c : ℝ)
    (hc : c ≠ 0)
    (counts ref : RelativeCounts n) :
    averagedRawCountTomitaTakesakiOp n (c • counts) (c • ref)
      = averagedRawCountTomitaTakesakiOp n counts ref := by
  simp [averagedRawCountTomitaTakesakiOp, rawCountDelta_common_smul (n := n) c hc]

@[simp] lemma averagedRawCountTomitaTakesakiOp_apply
    (counts ref : RelativeCounts n) (v : DoubledSpace (RouterAmplitude n)) :
    averagedRawCountTomitaTakesakiOp n counts ref v
      = averagedRawCountHamiltonian n counts ref • v := by
  simp [averagedRawCountTomitaTakesakiOp, averagedRawCountHamiltonian]

/-- Compatibility alias for `meanLogDeltaProfile`. -/
noncomputable def relativeLogDensityMean (ρ : Fin n → ℝ) : ℝ :=
  meanLogDeltaProfile n ρ

/-- Compatibility alias for `averagedModularHamiltonian`. -/
noncomputable def relativeModularHamiltonian (ρ : Fin n → ℝ) : ℝ :=
  averagedModularHamiltonian n ρ

/-- Compatibility alias for `averagedKreinTomitaTakesakiOp`. -/
noncomputable def relativeKreinTomitaTakesakiOp
    (ρ : Fin n → ℝ) : AlgebraEnd (RouterAmplitude n) :=
  averagedKreinTomitaTakesakiOp n ρ

@[simp] lemma relativeKreinTomitaTakesakiOp_apply
    (ρ : Fin n → ℝ) (v : DoubledSpace (RouterAmplitude n)) :
    relativeKreinTomitaTakesakiOp n ρ v =
      relativeModularHamiltonian n ρ •
        (InfoGeometry.Krein.spectral_epsilon (E := RouterAmplitude n) v) := by
  simp [relativeKreinTomitaTakesakiOp, relativeModularHamiltonian,
    averagedKreinTomitaTakesakiOp, averagedModularHamiltonian]

/-- Compatibility alias for `averagedTomitaTakesakiOp`. -/
noncomputable def relativeTomitaTakesakiOp
    (ρ : Fin n → ℝ) : AlgebraEnd (RouterAmplitude n) :=
  averagedTomitaTakesakiOp n ρ

@[simp] lemma relativeTomitaTakesakiOp_apply
    (ρ : Fin n → ℝ) (v : DoubledSpace (RouterAmplitude n)) :
    relativeTomitaTakesakiOp n ρ v = relativeModularHamiltonian n ρ • v := by
  simp [relativeTomitaTakesakiOp, relativeModularHamiltonian,
    averagedTomitaTakesakiOp, averagedModularHamiltonian]

/--
Generalized chain rule on relative densities: log-density means add under
pointwise multiplicative composition.
-/
lemma meanLogDeltaProfile_mul
    (ρ σ : Fin n → ℝ)
    (hρ : ∀ i : Fin n, ρ i ≠ 0)
    (hσ : ∀ i : Fin n, σ i ≠ 0) :
    meanLogDeltaProfile n (fun i => ρ i * σ i)
      = meanLogDeltaProfile n ρ + meanLogDeltaProfile n σ := by
  unfold meanLogDeltaProfile
  have hsum :
      (∑ i : Fin n, Real.log (ρ i * σ i))
        = ∑ i : Fin n, (Real.log (ρ i) + Real.log (σ i)) := by
    refine Finset.sum_congr rfl ?_
    intro i hi
    exact Real.log_mul (hρ i) (hσ i)
  rw [hsum, Finset.sum_add_distrib, mul_add]

theorem rawCountDelta_cocycle
    (counts ref base : RelativeCounts n)
    (href : ∀ i : Fin n, ref i ≠ 0)
    (hbase : ∀ i : Fin n, base i ≠ 0)
    (i : Fin n) :
    rawCountDelta n counts base i
      = rawCountDelta n counts ref i * rawCountDelta n ref base i := by
  unfold rawCountDelta relativeCountDensity
  field_simp [href i, hbase i]

@[simp] theorem relativeCountLogDensity_cocycle
    (counts ref base : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (hbase : ∀ i : Fin n, 0 < base i)
    (i : Fin n) :
    relativeCountLogDensity n counts base i
      = relativeCountLogDensity n counts ref i
        + relativeCountLogDensity n ref base i := by
  unfold relativeCountLogDensity relativeCountDensity
  rw [Real.log_div ((hcounts i).ne') ((hbase i).ne')]
  rw [Real.log_div ((hcounts i).ne') ((href i).ne')]
  rw [Real.log_div ((href i).ne') ((hbase i).ne')]
  ring

end Counts

section PositiveCounts

variable {n : Nat} [Nonempty (Fin n)]

/-- Positive count profile realized as a `PositiveMeasure`. -/
def positiveMeasureOfCounts
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i) :
    InfoGeometry.PositiveMeasure (Fin n) ℝ where
  mass := counts
  pos := hcounts

/-- Total mass of a strictly positive count profile. -/
noncomputable def countMass
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i) : ℝ :=
  InfoGeometry.PositiveMeasure.Z (positiveMeasureOfCounts counts hcounts)

lemma countMass_pos
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i) :
    0 < countMass counts hcounts := by
  unfold countMass
  exact InfoGeometry.PositiveMeasure.Z_pos (positiveMeasureOfCounts counts hcounts)

lemma countMass_ne_zero
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i) :
    countMass counts hcounts ≠ 0 :=
  (countMass_pos counts hcounts).ne'

/-- Global additive mass shift induced by normalizing positive count representatives. -/
@[rep_depth projective]
noncomputable def countMassShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : ℝ :=
  representativeMassShift
    (positiveMeasureOfCounts counts hcounts)
    (positiveMeasureOfCounts ref href)

@[simp] theorem countMassShift_self
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i) :
    countMassShift counts counts hcounts hcounts = 0 := by
  simpa only [countMassShift] using
    (representativeMassShift_self
      (α := Fin n)
      (μ := positiveMeasureOfCounts counts hcounts))

@[simp] theorem countMassShift_symm
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    countMassShift ref counts href hcounts = -countMassShift counts ref hcounts href := by
  simpa only [countMassShift] using
    (representativeMassShift_symm
      (α := Fin n)
      (μ := positiveMeasureOfCounts counts hcounts)
      (ν := positiveMeasureOfCounts ref href))

@[simp, rep_depth projective] theorem countMassShift_cocycle
    (counts ref base : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (hbase : ∀ i : Fin n, 0 < base i) :
    countMassShift counts base hcounts hbase
      = countMassShift counts ref hcounts href
        + countMassShift ref base href hbase := by
  simpa only [countMassShift] using
    (representativeMassShift_cocycle
      (α := Fin n)
      (μ := positiveMeasureOfCounts counts hcounts)
      (ν := positiveMeasureOfCounts ref href)
      (ξ := positiveMeasureOfCounts base hbase))

omit [Nonempty (Fin n)] in
@[simp] theorem representativeRelativeDensity_positiveMeasureOfCounts_eq_relativeCountDensity
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    representativeRelativeDensity
        (positiveMeasureOfCounts counts hcounts)
        (positiveMeasureOfCounts ref href) i
      = relativeCountDensity n counts ref i := by
  rfl

omit [Nonempty (Fin n)] in
@[simp] theorem representativeRelativeLogDensity_positiveMeasureOfCounts_eq_relativeCountLogDensity
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    representativeRelativeLogDensity
        (positiveMeasureOfCounts counts hcounts)
        (positiveMeasureOfCounts ref href) i
      = relativeCountLogDensity n counts ref i := by
  rfl

omit [Nonempty (Fin n)] in
@[simp] theorem representativeModularPotential_positiveMeasureOfCounts_eq_relativeCountModularProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    representativeModularPotential
        (positiveMeasureOfCounts counts hcounts)
        (positiveMeasureOfCounts ref href) i
      = relativeCountModularProfile n counts ref i := by
  rfl

omit [Nonempty (Fin n)] in
@[simp] theorem relativeCountDensity_eq_exp_relativeCountLogDensity
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeCountDensity n counts ref i = Real.exp (relativeCountLogDensity n counts ref i) := by
  simpa [relativeCountLogDensity] using
    (Real.exp_log (div_pos (hcounts i) (href i))).symm

omit [Nonempty (Fin n)] in
@[simp] theorem relativeCountDensity_eq_exp_neg_relativeCountModularProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeCountDensity n counts ref i = Real.exp (-(relativeCountModularProfile n counts ref i)) := by
  simpa [relativeCountModularProfile, relativeCountLogDensity] using
    (relativeCountDensity_eq_exp_relativeCountLogDensity
      (n := n) (counts := counts) (ref := ref)
      (hcounts := hcounts) (href := href) (i := i))

/-- Projective positive state carried by a positive count profile. -/
noncomputable def countRay
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i) : PositiveRay (Fin n) :=
  Quotient.mk _ (positiveMeasureOfCounts counts hcounts)

@[simp] theorem gaugeSection_countRay_apply
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (i : Fin n) :
    gaugeSection (α := Fin n) (countRay counts hcounts) i
      = counts i / countMass counts hcounts := by
  rw [countRay, gaugeSection_mk, InfoGeometry.PositiveMeasure.normalize_apply]
  simp [countMass, positiveMeasureOfCounts]

@[rep_depth projective, simp]
theorem gaugeSectionFinProb_countRay_apply_toReal
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (i : Fin n) :
    ((InfoGeometry.Canonical.RelativePotentialDiscreteBridge.gaugeSectionFinProb
        (α := Fin n) (countRay counts hcounts) i).toReal)
      =
    counts i / countMass counts hcounts := by
  rw [InfoGeometry.Canonical.RelativePotentialDiscreteBridge.gaugeSectionFinProb_apply_toReal]
  exact gaugeSection_countRay_apply (n := n) (counts := counts) (hcounts := hcounts) (i := i)

@[simp] theorem relativeDensity_countRay_eq_massRatio_mul_relativeCountDensity
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeDensity (α := Fin n) (countRay counts hcounts) (countRay ref href) i
      = (countMass ref href / countMass counts hcounts)
          * relativeCountDensity n counts ref i := by
  simpa only [countRay, countMass, positiveMeasureOfCounts, relativeCountDensity]
    using
      (relativeDensity_mk_eq_massRatio_mul_representativeRelativeDensity
        (α := Fin n)
        (μ := positiveMeasureOfCounts counts hcounts)
        (ν := positiveMeasureOfCounts ref href)
        (a := i))

@[simp] theorem relativeLogDensity_countRay_eq_relativeCountLogDensity_add_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeLogDensity (α := Fin n) (countRay counts hcounts) (countRay ref href) i
      = relativeCountLogDensity n counts ref i
        + countMassShift counts ref hcounts href := by
  unfold countMassShift representativeMassShift
  simpa only [countRay, positiveMeasureOfCounts,
    relativeCountLogDensity, relativeCountDensity]
    using
      (relativeLogDensity_mk_eq_representativeRelativeLogDensity_add_massShift
        (α := Fin n)
        (μ := positiveMeasureOfCounts counts hcounts)
        (ν := positiveMeasureOfCounts ref href)
        (a := i))

@[simp] theorem relativeModularPotential_countRay_eq_neg_relativeCountLogDensity_sub_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeModularPotential (α := Fin n) (countRay counts hcounts) (countRay ref href) i
      = -relativeCountLogDensity n counts ref i
        - countMassShift counts ref hcounts href := by
  unfold countMassShift representativeMassShift
  simpa only [countRay, positiveMeasureOfCounts,
    relativeCountLogDensity, relativeCountDensity]
    using
      (relativeModularPotential_mk_eq_representativeModularPotential_sub_massShift
        (α := Fin n)
        (μ := positiveMeasureOfCounts counts hcounts)
        (ν := positiveMeasureOfCounts ref href)
        (a := i))

/-- Multiplicative relative volume change induced by count normalization. -/
noncomputable def countRelativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : ℝ :=
  countMass counts hcounts / countMass ref href

private lemma countRelativeVolumeChange_pos
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    0 < countRelativeVolumeChange counts ref hcounts href := by
  exact div_pos (countMass_pos counts hcounts) (countMass_pos ref href)
omit [Nonempty (Fin n)] in
@[simp] theorem countMassShift_eq_neg_log_countRelativeVolumeChange
    [Nonempty (Fin n)]
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    countMassShift counts ref hcounts href =
      -Real.log (countRelativeVolumeChange counts ref hcounts href) := by
  unfold countMassShift representativeMassShift
  calc
    Real.log ((positiveMeasureOfCounts ref href).Z / (positiveMeasureOfCounts counts hcounts).Z)
      = Real.log ((countRelativeVolumeChange counts ref hcounts href)⁻¹) := by
          unfold countRelativeVolumeChange countMass
          field_simp [countMass_ne_zero counts hcounts, countMass_ne_zero ref href]
    _ = -Real.log (countRelativeVolumeChange counts ref hcounts href) := by
          rw [Real.log_inv]

@[simp] theorem countMassShift_eq_scalarModularPotential_relativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    countMassShift counts ref hcounts href =
      InfoGeometry.Canonical.RelativePotentialScalarBridge.scalarModularPotential
        (countRelativeVolumeChange counts ref hcounts href)
        (countRelativeVolumeChange_pos counts ref hcounts href) := by
  rw [InfoGeometry.Canonical.RelativePotentialScalarBridge.scalarModularPotential_eq_neg_log]
  exact countMassShift_eq_neg_log_countRelativeVolumeChange counts ref hcounts href

@[simp] theorem exp_neg_countMassShift_eq_countRelativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    Real.exp (-(countMassShift counts ref hcounts href)) =
      countRelativeVolumeChange counts ref hcounts href := by
  rw [countMassShift_eq_scalarModularPotential_relativeVolumeChange]
  exact InfoGeometry.Canonical.RelativePotentialScalarBridge.exp_neg_scalarModularPotential_eq
    (countRelativeVolumeChange counts ref hcounts href)
    (countRelativeVolumeChange_pos counts ref hcounts href)

@[simp] theorem relativeDensity_countRay_eq_relativeCountDensity_div_countRelativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeDensity (α := Fin n) (countRay counts hcounts) (countRay ref href) i
      = relativeCountDensity n counts ref i /
          countRelativeVolumeChange counts ref hcounts href := by
  have hratio :
      countMass ref href / countMass counts hcounts
        = (countRelativeVolumeChange counts ref hcounts href)⁻¹ := by
    unfold countRelativeVolumeChange
    field_simp [countMass_ne_zero counts hcounts, countMass_ne_zero ref href]
  rw [relativeDensity_countRay_eq_massRatio_mul_relativeCountDensity]
  rw [hratio]
  rw [div_eq_mul_inv]
  ring

@[simp] theorem relativeLogDensity_countRay_eq_relativeCountLogDensity_sub_log_countRelativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeLogDensity (α := Fin n) (countRay counts hcounts) (countRay ref href) i
      = relativeCountLogDensity n counts ref i
        - Real.log (countRelativeVolumeChange counts ref hcounts href) := by
  rw [relativeLogDensity_countRay_eq_relativeCountLogDensity_add_massShift]
  rw [countMassShift_eq_neg_log_countRelativeVolumeChange]
  ring

/-- Canonical projective count-side commutative relative modular operator profile. -/
noncomputable def projectiveCountDelta
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : Fin n → ℝ :=
  fun i =>
    relativeDensity (α := Fin n)
      (countRay counts hcounts) (countRay ref href) i

/-- Canonical projective logarithmic modular profile `log Δ̂`. -/
noncomputable def projectiveCountLogDelta
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : Fin n → ℝ :=
  fun i =>
    relativeLogDensity (α := Fin n)
      (countRay counts hcounts) (countRay ref href) i

/-- Canonical projective count-side modular potential profile. -/
noncomputable def projectiveCountModularProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : Fin n → ℝ :=
  fun i =>
    relativeModularPotential (α := Fin n)
      (countRay counts hcounts) (countRay ref href) i

/-- Canonical projective Hamiltonian modular profile `-log Δ̂`. -/
noncomputable def projectiveCountHamiltonianProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : Fin n → ℝ :=
  projectiveCountModularProfile counts ref hcounts href

@[rep_depth projective, simp]
theorem projectiveCountHamiltonianProfile_eq_relativeModularPotential_countRay
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountHamiltonianProfile counts ref hcounts href i
      =
    relativeModularPotential (α := Fin n)
      (countRay counts hcounts) (countRay ref href) i := by
  rfl

@[simp] theorem projectiveCountLogDelta_eq_relativeLogDensity_countRay
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    projectiveCountLogDelta counts ref hcounts href
      = fun i => relativeLogDensity (α := Fin n) (countRay counts hcounts) (countRay ref href) i := rfl

@[simp] theorem projectiveCountModularProfile_eq_neg_relativeLogDensity_countRay
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountModularProfile counts ref hcounts href i =
      -relativeLogDensity (α := Fin n) (countRay counts hcounts) (countRay ref href) i := by
  rw [projectiveCountModularProfile]
  exact relativeModularPotential_eq_neg_relativeLogDensity
    (q := countRay counts hcounts) (q0 := countRay ref href) (a := i)

@[simp] theorem projectiveCountDelta_eq_massRatio_mul_rawCountDelta
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountDelta counts ref hcounts href i
      = (countMass ref href / countMass counts hcounts)
          * rawCountDelta n counts ref i := by
  rw [projectiveCountDelta, rawCountDelta]
  exact relativeDensity_countRay_eq_massRatio_mul_relativeCountDensity
    (n := n) (counts := counts) (ref := ref)
    (hcounts := hcounts) (href := href) (i := i)

@[simp] theorem projectiveCountDelta_eq_raw_div_countRelativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountDelta counts ref hcounts href i
      = rawCountDelta n counts ref i /
          countRelativeVolumeChange counts ref hcounts href := by
  rw [projectiveCountDelta]
  exact relativeDensity_countRay_eq_relativeCountDensity_div_countRelativeVolumeChange
    (n := n) (counts := counts) (ref := ref) (hcounts := hcounts) (href := href) (i := i)

@[simp] theorem projectiveCountLogDelta_eq_rawCountLogDelta_add_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountLogDelta counts ref hcounts href i
      = rawCountLogDelta n counts ref i + countMassShift counts ref hcounts href := by
  rw [projectiveCountLogDelta, rawCountLogDelta]
  exact relativeLogDensity_countRay_eq_relativeCountLogDensity_add_massShift
    (n := n) (counts := counts) (ref := ref)
    (hcounts := hcounts) (href := href) (i := i)

@[simp] theorem projectiveCountModularProfile_eq_neg_log_projectiveCountDelta
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountModularProfile counts ref hcounts href i
      = -Real.log (projectiveCountDelta counts ref hcounts href i) := by
  rw [projectiveCountModularProfile_eq_neg_relativeLogDensity_countRay]
  rw [projectiveCountDelta]
  rw [relativeDensity_eq_exp_relativeLogDensity]
  rw [Real.log_exp]

@[simp] theorem projectiveCountDelta_eq_exp_neg_projectiveCountModularProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountDelta counts ref hcounts href i
      = Real.exp (-(projectiveCountModularProfile counts ref hcounts href i)) := by
  rw [projectiveCountDelta]
  rw [projectiveCountModularProfile_eq_neg_relativeLogDensity_countRay]
  rw [neg_neg]
  exact relativeDensity_eq_exp_relativeLogDensity
    (q := countRay counts hcounts)
    (q0 := countRay ref href)
    (a := i)


@[simp] theorem projectiveCountHamiltonianProfile_eq_rawCountHamiltonianProfile_sub_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountHamiltonianProfile counts ref hcounts href i
      = rawCountHamiltonianProfile n counts ref i
        - countMassShift counts ref hcounts href := by
  rw [projectiveCountHamiltonianProfile, rawCountHamiltonianProfile]
  exact relativeModularPotential_countRay_eq_neg_relativeCountLogDensity_sub_massShift
    (n := n) (counts := counts) (ref := ref)
    (hcounts := hcounts) (href := href) (i := i)

/-- Averaged Hamiltonian obtained by collapsing the projective count-side `Δ` profile. -/
noncomputable def averagedProjectiveCountHamiltonian
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : ℝ :=
  averagedModularHamiltonian n (projectiveCountDelta counts ref hcounts href)

@[simp] theorem averagedProjectiveCountHamiltonian_eq_mean_projectiveCountHamiltonianProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    averagedProjectiveCountHamiltonian counts ref hcounts href
      = (n : ℝ)⁻¹ * ∑ i : Fin n, projectiveCountHamiltonianProfile counts ref hcounts href i := by
  unfold averagedProjectiveCountHamiltonian averagedModularHamiltonian meanLogDeltaProfile
  calc
    -((n : ℝ)⁻¹ * ∑ i : Fin n, Real.log (projectiveCountDelta counts ref hcounts href i))
      = (n : ℝ)⁻¹ * (-(∑ i : Fin n, Real.log (projectiveCountDelta counts ref hcounts href i))) := by ring
    _ = (n : ℝ)⁻¹ * ∑ i : Fin n, -Real.log (projectiveCountDelta counts ref hcounts href i) := by
          rw [← Finset.sum_neg_distrib]
    _ = (n : ℝ)⁻¹ * ∑ i : Fin n, projectiveCountHamiltonianProfile counts ref hcounts href i := by
          refine congrArg ((n : ℝ)⁻¹ * ·) ?_
          refine Finset.sum_congr rfl ?_
          intro i hi
          change
            -Real.log (projectiveCountDelta counts ref hcounts href i) =
              projectiveCountModularProfile counts ref hcounts href i
          exact projectiveCountModularProfile_eq_neg_log_projectiveCountDelta
            (counts := counts) (ref := ref) (hcounts := hcounts) (href := href) i

@[simp] theorem averagedProjectiveCountHamiltonian_eq_averagedRawCountHamiltonian_sub_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) :
    averagedProjectiveCountHamiltonian counts ref hcounts href
      = averagedRawCountHamiltonian n counts ref
        - countMassShift counts ref hcounts href := by
  rw [averagedProjectiveCountHamiltonian_eq_mean_projectiveCountHamiltonianProfile]
  rw [averagedRawCountHamiltonian_eq_mean_rawCountHamiltonianProfile]
  have hsum :
      (∑ i : Fin n, projectiveCountHamiltonianProfile counts ref hcounts href i)
        = ∑ i : Fin n,
            (rawCountHamiltonianProfile n counts ref i - countMassShift counts ref hcounts href) := by
    refine Finset.sum_congr rfl ?_
    intro i hi
    exact projectiveCountHamiltonianProfile_eq_rawCountHamiltonianProfile_sub_massShift
      (counts := counts) (ref := ref) (hcounts := hcounts) (href := href) i
  rw [hsum, Finset.sum_sub_distrib, Finset.sum_const, nsmul_eq_mul]
  have hcard : ((((Finset.univ : Finset (Fin n)).card : ℕ) : ℝ) = n) := by simp
  rw [hcard]
  have hpos : 0 < n := by
    simpa using (Fintype.card_pos_iff.mpr ‹Nonempty (Fin n)›)
  have hn : (n : ℝ) ≠ 0 := by
    exact_mod_cast (Nat.ne_of_gt hpos)
  rw [mul_sub]
  rw [← mul_assoc, inv_mul_cancel₀ hn, one_mul]

/-- Averaged Krein-native Tomita-Takesaki operator attached to the projective count-side `Δ` profile. -/
noncomputable def averagedProjectiveCountKreinTomitaTakesakiOp
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i) : AlgebraEnd (RouterAmplitude n) :=
  averagedKreinTomitaTakesakiOp n (projectiveCountDelta counts ref hcounts href)

@[simp] lemma averagedProjectiveCountKreinTomitaTakesakiOp_apply
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (v : DoubledSpace (RouterAmplitude n)) :
    averagedProjectiveCountKreinTomitaTakesakiOp counts ref hcounts href v =
      averagedProjectiveCountHamiltonian counts ref hcounts href •
        (InfoGeometry.Krein.spectral_epsilon (E := RouterAmplitude n) v) := by
  simp [averagedProjectiveCountKreinTomitaTakesakiOp, averagedProjectiveCountHamiltonian]

theorem projectiveCountModularProfile_eq_raw_sub_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountModularProfile counts ref hcounts href i
      = relativeCountModularProfile n counts ref i
        - countMassShift counts ref hcounts href := by
  rw [projectiveCountModularProfile, relativeCountModularProfile]
  exact relativeModularPotential_countRay_eq_neg_relativeCountLogDensity_sub_massShift
    (n := n) (counts := counts) (ref := ref)
    (hcounts := hcounts) (href := href) (i := i)

@[simp] theorem projectiveCountModularProfile_eq_raw_sub_scalarModularPotential_relativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    projectiveCountModularProfile counts ref hcounts href i
      = relativeCountModularProfile n counts ref i
        - InfoGeometry.Canonical.RelativePotentialScalarBridge.scalarModularPotential
            (countRelativeVolumeChange counts ref hcounts href)
            (countRelativeVolumeChange_pos counts ref hcounts href) := by
  calc
    projectiveCountModularProfile counts ref hcounts href i
      = relativeCountModularProfile n counts ref i - countMassShift counts ref hcounts href := by
          exact projectiveCountModularProfile_eq_raw_sub_massShift
            (n := n) (counts := counts) (ref := ref)
            (hcounts := hcounts) (href := href) (i := i)
    _ = relativeCountModularProfile n counts ref i
          - InfoGeometry.Canonical.RelativePotentialScalarBridge.scalarModularPotential
              (countRelativeVolumeChange counts ref hcounts href)
              (countRelativeVolumeChange_pos counts ref hcounts href) := by
          rw [countMassShift_eq_scalarModularPotential_relativeVolumeChange]

@[simp] theorem relativeModularPotential_countRay_eq_relativeCountModularProfile_sub_scalarModularPotential_relativeVolumeChange
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    relativeModularPotential (α := Fin n) (countRay counts hcounts) (countRay ref href) i
      = relativeCountModularProfile n counts ref i
        - InfoGeometry.Canonical.RelativePotentialScalarBridge.scalarModularPotential
            (countRelativeVolumeChange counts ref hcounts href)
            (countRelativeVolumeChange_pos counts ref hcounts href) := by
  rw [relativeModularPotential_countRay_eq_neg_relativeCountLogDensity_sub_massShift]
  rw [countMassShift_eq_scalarModularPotential_relativeVolumeChange]
  rw [relativeCountModularProfile]

@[simp] theorem projectiveCountDelta_self
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (i : Fin n) :
    projectiveCountDelta counts counts hcounts hcounts i = 1 := by
  rw [projectiveCountDelta]
  exact relativeDensity_self (q := countRay counts hcounts) (a := i)

@[simp] theorem projectiveCountLogDelta_self
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (i : Fin n) :
    projectiveCountLogDelta counts counts hcounts hcounts i = 0 := by
  rw [projectiveCountLogDelta]
  exact relativeLogDensity_self (q := countRay counts hcounts) (a := i)

@[simp] theorem projectiveCountHamiltonianProfile_self
    (counts : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (i : Fin n) :
    projectiveCountHamiltonianProfile counts counts hcounts hcounts i = 0 := by
  rw [projectiveCountHamiltonianProfile]
  exact relativeModularPotential_self (q := countRay counts hcounts) (a := i)

theorem projectiveCountDelta_cocycle
    (counts ref base : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (hbase : ∀ i : Fin n, 0 < base i)
    (i : Fin n) :
    projectiveCountDelta counts base hcounts hbase i
      = projectiveCountDelta counts ref hcounts href i
          * projectiveCountDelta ref base href hbase i := by
  rw [projectiveCountDelta, projectiveCountDelta, projectiveCountDelta]
  exact relativeDensity_cocycle
    (q := countRay counts hcounts)
    (q0 := countRay ref href)
    (q1 := countRay base hbase)
    (a := i)

theorem projectiveCountLogDelta_cocycle
    (counts ref base : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (hbase : ∀ i : Fin n, 0 < base i)
    (i : Fin n) :
    projectiveCountLogDelta counts base hcounts hbase i
      = projectiveCountLogDelta counts ref hcounts href i
        + projectiveCountLogDelta ref base href hbase i := by
  rw [projectiveCountLogDelta, projectiveCountLogDelta, projectiveCountLogDelta]
  exact relativeLogDensity_cocycle
    (q := countRay counts hcounts)
    (q0 := countRay ref href)
    (q1 := countRay base hbase)
    (a := i)

theorem projectiveCountHamiltonianProfile_cocycle
    (counts ref base : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (hbase : ∀ i : Fin n, 0 < base i)
    (i : Fin n) :
    projectiveCountHamiltonianProfile counts base hcounts hbase i
      = projectiveCountHamiltonianProfile counts ref hcounts href i
        + projectiveCountHamiltonianProfile ref base href hbase i := by
  rw [projectiveCountHamiltonianProfile, projectiveCountHamiltonianProfile,
    projectiveCountHamiltonianProfile]
  exact relativeModularPotential_cocycle
    (q := countRay counts hcounts)
    (q0 := countRay ref href)
    (q1 := countRay base hbase)
    (a := i)

/--
The projective logarithmic generator on positive count rays is exactly the raw
count-side modular potential together with the expected global mass-shift.
-/
@[simp] theorem projectiveLogGenerator_countRay_eq_neg_relativeCountLogDensity_sub_massShift
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    InfoGeometry.MeasureProjective.ProjectiveState.logGenerator
        (InfoGeometry.Canonical.RelativePotentialDiscreteBridge.toProjectiveState
          (α := Fin n) (countRay ref href))
        (InfoGeometry.Canonical.RelativePotentialDiscreteBridge.toProjectiveState
          (α := Fin n) (countRay counts hcounts)) i
      = -relativeCountLogDensity n counts ref i
        - countMassShift counts ref hcounts href := by
  rw [InfoGeometry.Canonical.RelativePotentialDiscreteBridge.projectiveLogGenerator_eq_relativeModularPotential
    (α := Fin n) (q := countRay counts hcounts) (q0 := countRay ref href) (a := i)]
  exact relativeModularPotential_countRay_eq_neg_relativeCountLogDensity_sub_massShift
    (n := n) (counts := counts) (ref := ref) (hcounts := hcounts) (href := href) (i := i)

@[rep_depth projective, simp]
theorem projectiveLogGenerator_countRay_eq_projectiveCountHamiltonianProfile
    (counts ref : RelativeCounts n)
    (hcounts : ∀ i : Fin n, 0 < counts i)
    (href : ∀ i : Fin n, 0 < ref i)
    (i : Fin n) :
    InfoGeometry.MeasureProjective.ProjectiveState.logGenerator
        (InfoGeometry.Canonical.RelativePotentialDiscreteBridge.toProjectiveState
          (α := Fin n) (countRay ref href))
        (InfoGeometry.Canonical.RelativePotentialDiscreteBridge.toProjectiveState
          (α := Fin n) (countRay counts hcounts)) i
      =
    projectiveCountHamiltonianProfile counts ref hcounts href i := by
  rw [projectiveCountHamiltonianProfile_eq_relativeModularPotential_countRay]
  exact
    InfoGeometry.Canonical.RelativePotentialDiscreteBridge.projectiveLogGenerator_eq_relativeModularPotential
      (α := Fin n) (q := countRay counts hcounts) (q0 := countRay ref href) (a := i)

end PositiveCounts

end RelativePotentialCountBridge
