/-
InfoGeometry/Canonical/SiegelBerryBridge.lean

Pure real symplectic / Siegel Berry bridge.
No complex imports.
-/

import Mathlib.Order.Filter.AtTopBot.Basic
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Order.Filter.Tendsto
import Mathlib.Topology.Basic
import InfoGeometry.Algebraic.MatrixAutomorphyFactor
import InfoGeometry.Geometry.RealSiegelSpace

noncomputable section

namespace InfoGeometry.Canonical

open Filter
open scoped Topology

open InfoGeometry.Algebraic.Cartan
open InfoGeometry.Geometry.Cartan

/--
Complete data for the real symplectic / Siegel Berry bridge.

The bridge is stated as a regularized limit theorem. The hard analytic content
remains isolated as a field.
-/
structure RealSiegelBerryBridgeData
    (n : ℕ)
    (G R A : Type*)
    [Group G]
    [MulAction G (RealSiegelSpace n)]
    [Monoid A]
    [Group R]
    [TopologicalSpace R] where

  /-- The matrix-valued automorphy factor. -/
  J : MatrixAutomorphyFactor G (RealSiegelSpace n) A

  /-- The rotor or weight readout. -/
  weightReadout : A →* R

  /-- Limiting bulk readout. -/
  R_bulk : R

  /-- Limiting boundary readout. -/
  R_boundary : R

  /--
  The exponentiated truncated bulk expression has a limit.

  The concrete Siegel integral is left abstract here; this file only fixes the
  bridge contract.
  -/
  h_bulk_limit :
    Tendsto
      (fun _ : ℝ => R_bulk)
      atTop
      (𝓝 R_boundary)

  /-- The regularized Stokes statement for the bridge. -/
  regularizedStokesLimit :
    R_bulk = R_boundary

namespace RealSiegelBerryBridgeData

variable
    {n : ℕ}
    {G R : Type*}
    [Group G]
    [MulAction G (RealSiegelSpace n)]
    [Group R] [TopologicalSpace R]
    {A : Type*}
    [Monoid A]

/-- The canonical cocycle generated by the data. -/
def cocycle
    (D : RealSiegelBerryBridgeData n G R A) :
    CartanRotorCocycle G (RealSiegelSpace n) R :=
  D.J.toRotorCocycle D.weightReadout

/-- The limiting bulk readout is the regularized boundary readout. -/
theorem realSiegelBerryBridge
    (D : RealSiegelBerryBridgeData n G R A) :
    D.R_bulk = D.R_boundary :=
  D.regularizedStokesLimit

/-- The limit theorem extracted from the bridge contract. -/
theorem realSiegelBerryBridge_tendsto
    (D : RealSiegelBerryBridgeData n G R A) :
    Tendsto
      (fun _ : ℝ => D.R_bulk)
      atTop
      (𝓝 D.R_boundary) := by
  simpa [D.regularizedStokesLimit] using D.h_bulk_limit

end RealSiegelBerryBridgeData

end InfoGeometry.Canonical
