import InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge
import InfoGeometry.Canonical.StandardFormCore
import InfoGeometry.Canonical.TomitaTakesaki
import InfoGeometry.Meta.Architecture

/-!
# InfoGeometry.Canonical.SouriauTomitaModularFlowBridge

Dimension-agnostic bridge from Souriau geometric temperature to the
operator-algebraic Tomita modular-flow lane.

The finite `Spin(4,4)` Cartan character formulas are only representation
shadows.  The source-owned theorem here is the operatorial one:
the Souriau thermal generator selected by geometric temperature is the
logarithmic Tomita generator, and its additive modular flow is the existing
Connes/Tomita exponential conjugation flow.
-/

namespace InfoGeometry.Canonical.SouriauTomitaModularFlowBridge

open InfoGeometry.Volume.ConnesCocycle
open InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge
open InfoGeometry.Canonical.StandardFormCore

universe u v

section OperatorialBridge

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
variable {Symmetry : Type v}

local notation "Obs" => AlgebraEnd H

/--
Constructive Souriau/Tomita logarithm context.

The logarithmic modular generator (`K = -log Δ` in the manuscript convention)
is not an additional hypothesis in this bridge: it is definitionally the
Souriau thermal generator, i.e. the moment operator evaluated at the geometric
temperature.
-/
@[rep_depth operator]
structure SouriauTomitaLogContext where
  souriauMoment : OperatorSouriauMoment (H := H) Symmetry

namespace SouriauTomitaLogContext

variable (C : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))

/-- The real Tomita logarithm data exposed as an operator on the observable carrier. -/
@[rep_depth operator]
def toRealModularLogData : Obs :=
  C.souriauMoment.thermalGenerator

/-- The Tomita logarithm equals the Souriau thermal generator. -/
@[rep_depth operator]
theorem tomita_deltaLog_eq_thermalGenerator :
    C.toRealModularLogData = C.souriauMoment.thermalGenerator :=
  rfl

/--
Modular Hamiltonian selected by the Souriau geometric temperature.

This is the operatorial, dimension-agnostic carrier of the manuscript formula
`K = <β, H>`.  The current repo represents `<β, H>` as the moment operator
evaluated at `geometricTemperature`; no finite Cartan basis is introduced.
-/
@[rep_depth operator]
def modularHamiltonian : Obs :=
  C.souriauMoment.thermalGenerator

/-- Souriau additive modular flow generated by the geometric-temperature moment. -/
@[rep_depth operator]
noncomputable def souriauAdditiveModularFlow : AdditiveModularFlow (H := H) :=
  additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator

/-- Tomita additive modular flow generated by the logarithmic modular datum. -/
@[rep_depth operator]
noncomputable def tomitaAdditiveModularFlow : AdditiveModularFlow (H := H) :=
  additiveModularFlowOfGenerator (H := H) C.toRealModularLogData

/--
The logarithmic Tomita flow is already a generator-owned standard-form flow with
modular Hamiltonian `Δ_log = K` carried by the Souriau moment.
-/
@[rep_depth operator]
theorem tomitaAdditiveModularFlow_eq_generator_modularHamiltonian :
    C.tomitaAdditiveModularFlow =
      additiveModularFlowOfGenerator (H := H) C.modularHamiltonian := by
  unfold tomitaAdditiveModularFlow toRealModularLogData modularHamiltonian
  rfl

/--
Standard-form seed exposing the Souriau-selected Tomita modular flow while
retaining the owned doubled-carrier `(J, ε, Jε)` atom.
-/
@[rep_depth operator]
noncomputable def toStandardFormSeed : StandardFormSeed H where
  J := (tomitaAtomSeed (H := H)).J
  ε := (tomitaAtomSeed (H := H)).ε
  phaseAxis := (tomitaAtomSeed (H := H)).phaseAxis
  modularFlow := C.tomitaAdditiveModularFlow
  J_sq := (tomitaAtomSeed (H := H)).J_sq
  eps_sq := (tomitaAtomSeed (H := H)).eps_sq
  phase_sq := (tomitaAtomSeed (H := H)).phase_sq
  J_phase_anticommute := (tomitaAtomSeed (H := H)).J_phase_anticommute

/--
Concrete standard-form carrier for the Souriau/Tomita logarithmic lane.
This replaces bare `deltaLog = thermalGenerator` prose by a carrier whose flow
is explicitly generated by the modular Hamiltonian.
-/
@[rep_depth operator]
noncomputable def toStandardFormCarrier : StandardFormCarrier H where
  seed := C.toStandardFormSeed
  Delta := C.modularHamiltonian
  referenceState := ⟨0⟩
  modularFlow_eq_generator := C.tomitaAdditiveModularFlow_eq_generator_modularHamiltonian

/-- The standard-form carrier uses the Souriau modular Hamiltonian as its generator. -/
@[rep_depth operator]
theorem toStandardFormCarrier_Delta_eq_modularHamiltonian :
    C.toStandardFormCarrier.Delta = C.modularHamiltonian :=
  rfl

/-- Evaluation form of the standard-form carrier flow. -/
@[rep_depth operator]
theorem toStandardFormCarrier_modularFlow_apply
    (t : ℝ) (A : Obs) :
    C.toStandardFormCarrier.seed.modularFlow t A =
      InfoGeometry.Krein.modular_shift (E := H) C.modularHamiltonian t A := by
  calc
    C.toStandardFormCarrier.seed.modularFlow t A
        = C.tomitaAdditiveModularFlow t A := rfl
    _ = InfoGeometry.Krein.modular_shift (E := H) C.modularHamiltonian t A := by
          simpa [tomitaAdditiveModularFlow, toRealModularLogData, modularHamiltonian]
            using
              (additiveModularFlowOfGenerator_apply
                (H := H) C.modularHamiltonian t A)

/--
The Tomita flow generated by `deltaLog` is the Souriau modular transport flow
generated by the geometric-temperature moment.
-/
@[rep_depth operator]
theorem tomita_flow_eq_souriau_modularTransportFlow :
    C.tomitaAdditiveModularFlow = C.souriauAdditiveModularFlow := by
  change
    additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator =
      additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator
  rfl

/-- Evaluation form of the Souriau additive modular flow. -/
@[rep_depth operator]
theorem souriauAdditiveModularFlow_apply_eq_modular_shift
    (t : ℝ) (A : Obs) :
    C.souriauAdditiveModularFlow t A =
      InfoGeometry.Krein.modular_shift
        (E := H) C.souriauMoment.thermalGenerator t A :=
  additiveModularFlowOfGenerator_apply
    (H := H) C.souriauMoment.thermalGenerator t A

/-- The Souriau modular generator is the moment at geometric temperature. -/
@[rep_depth operator]
theorem souriauModularGenerator_eq_moment_geometricTemperature :
    C.souriauMoment.thermalGenerator =
      C.souriauMoment.momentOperator C.souriauMoment.geometricTemperature :=
  C.souriauMoment.thermalGenerator_eq_moment_geometricTemperature

/-- The modular Hamiltonian is the Souriau moment at geometric temperature. -/
@[rep_depth operator]
theorem modularHamiltonian_eq_moment_geometricTemperature :
    C.modularHamiltonian =
      C.souriauMoment.momentOperator C.souriauMoment.geometricTemperature :=
  C.souriauModularGenerator_eq_moment_geometricTemperature

/--
The Tomita logarithmic datum is the modular Hamiltonian in this bridge.
-/
@[rep_depth operator]
theorem tomita_deltaLog_eq_modularHamiltonian :
    C.toRealModularLogData = C.modularHamiltonian :=
  C.tomita_deltaLog_eq_thermalGenerator

/-- The generated automorphism acts by conjugation with the modular Hamiltonian. -/
@[rep_depth operator]
theorem souriauAdditiveModularFlow_apply_eq_modularHamiltonian_shift
    (t : ℝ) (A : Obs) :
    C.souriauAdditiveModularFlow t A =
      InfoGeometry.Krein.modular_shift (E := H) C.modularHamiltonian t A :=
  C.souriauAdditiveModularFlow_apply_eq_modular_shift t A

end SouriauTomitaLogContext

/--
KMS context for the Souriau-generated Tomita modular automorphism group.

This is deliberately proof-carrying: the repo has the algebraic KMS identity
as `KMSState`, but it does not own the full analytic strip theorem for arbitrary
Type III factors.  The constructive content here is that the KMS identity is
threaded through the exact modular flow generated by the Souriau modular
Hamiltonian.
-/
@[rep_depth operator]
structure SouriauTomitaKMSContext where
  logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry)
  beta : ℝ
  state : AlgebraicState (H := H)
  kms :
    KMSState (H := H)
      logContext.souriauAdditiveModularFlow beta
  kms_state_eq : kms.state = state

namespace SouriauTomitaKMSContext

variable (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry))

/-- The modular automorphism group is the Souriau/Tomita generated flow. -/
@[rep_depth operator]
noncomputable def sigma : AdditiveModularFlow (H := H) :=
  C.logContext.souriauAdditiveModularFlow

/-- The KMS modular time parameter carried by this context. -/
@[rep_depth operator]
def modularBeta : ℝ :=
  C.beta

/-- KMS identity over the Souriau-generated modular automorphism group. -/
@[rep_depth operator]
theorem kms_eval_mul_souriau_modular_eq_eval_flip
    (A B : Obs) :
    C.state.eval (A * C.sigma C.modularBeta B) =
      C.state.eval (B * A) := by
  calc
    C.state.eval (A * C.sigma C.modularBeta B)
        = C.kms.state.eval (A * C.sigma C.modularBeta B) := by
          rw [C.kms_state_eq]
    _ = C.kms.state.eval (B * A) :=
          C.kms.eval_mul_modular_eq_eval_flip A B
    _ = C.state.eval (B * A) := by
          rw [C.kms_state_eq]

/-- The Souriau/Tomita modular automorphism group is additive. -/
@[rep_depth operator]
theorem sigma_add (s t : ℝ) :
    C.sigma (s + t) = C.sigma s * C.sigma t :=
  AdditiveModularFlow.map_add C.sigma s t

/-- The Souriau/Tomita modular automorphism group starts at identity. -/
@[rep_depth operator]
theorem sigma_zero :
    C.sigma 0 = 1 :=
  AdditiveModularFlow.map_zero C.sigma

/-- The modular Hamiltonian is the Souriau moment at geometric temperature. -/
@[rep_depth operator]
theorem modularHamiltonian_eq_moment_geometricTemperature :
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature :=
  C.logContext.modularHamiltonian_eq_moment_geometricTemperature

/-- Search-facing packet for the constructed modular automorphism/KMS bridge. -/
@[rep_depth operator]
theorem constructive_kms_packet
    (A B : Obs) (s t : ℝ) :
    C.state.eval (A * C.sigma C.modularBeta B) =
        C.state.eval (B * A) ∧
    C.sigma (s + t) = C.sigma s * C.sigma t ∧
    C.sigma 0 = 1 ∧
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature := by
  exact ⟨
    C.kms_eval_mul_souriau_modular_eq_eval_flip A B,
    C.sigma_add s t,
    C.sigma_zero,
    C.modularHamiltonian_eq_moment_geometricTemperature⟩

end SouriauTomitaKMSContext

end OperatorialBridge

end InfoGeometry.Canonical.SouriauTomitaModularFlowBridge
