import InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge
import InfoGeometry.Canonical.StandardFormCore
import InfoGeometry.Canonical.TomitaTakesaki
import InfoGeometry.Meta.Architecture

/-!
# InfoGeometry.Canonical.SouriauTomitaModularFlowBridge

Dimension-agnostic bridge from Souriau geometric temperature to the
operator-algebraic Tomita modular-flow lane.

The finite `Spin(4,4)` Cartan character formulas are only representation
shadows.  The source-owned theorem here is the operatorial one:
the Souriau thermal generator selected by geometric temperature is the
logarithmic Tomita generator, and its additive modular flow is the existing
Connes/Tomita exponential conjugation flow.
-/

namespace SouriauTomitaModularFlowBridge

open InfoGeometry.Volume.ConnesCocycle
open InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge
open InfoGeometry.Canonical.StandardFormCore

universe u v

section OperatorialBridge

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
variable {Symmetry : Type v}

local notation "Obs" => AlgebraEnd H

/--
Constructive Souriau/Tomita logarithm context.

The logarithmic modular generator (`K = -log Δ` in the manuscript convention)
is not an additional hypothesis in this bridge: it is definitionally the
Souriau thermal generator, i.e. the moment operator evaluated at the geometric
temperature.
-/
@[rep_depth operator]
structure SouriauTomitaLogContext where
  souriauMoment : OperatorSouriauMoment (H := H) Symmetry

namespace SouriauTomitaLogContext

variable (C : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))

/-- The real Tomita logarithm data exposed as an operator on the observable carrier. -/
@[rep_depth operator]
def toRealModularLogData : Obs :=
  C.souriauMoment.thermalGenerator

/-- The Tomita logarithm equals the Souriau thermal generator. -/
@[rep_depth operator]
theorem tomita_deltaLog_eq_thermalGenerator :
    C.toRealModularLogData = C.souriauMoment.thermalGenerator :=
  rfl

/--
Modular Hamiltonian selected by the Souriau geometric temperature.

This is the operatorial, dimension-agnostic carrier of the manuscript formula
`K = <β, H>`.  The current repo represents `<β, H>` as the moment operator
evaluated at `geometricTemperature`; no finite Cartan basis is introduced.
-/
@[rep_depth operator]
def modularHamiltonian : Obs :=
  C.souriauMoment.thermalGenerator

/-- Souriau additive modular flow generated by the geometric-temperature moment. -/
@[rep_depth operator]
noncomputable def souriauAdditiveModularFlow : AdditiveModularFlow (H := H) :=
  additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator

/-- Tomita additive modular flow generated by the logarithmic modular datum. -/
@[rep_depth operator]
noncomputable def tomitaAdditiveModularFlow : AdditiveModularFlow (H := H) :=
  additiveModularFlowOfGenerator (H := H) C.toRealModularLogData

/--
The logarithmic Tomita flow is already a generator-owned standard-form flow with
modular Hamiltonian `Δ_log = K` carried by the Souriau moment.
-/
@[rep_depth operator]
theorem tomitaAdditiveModularFlow_eq_generator_modularHamiltonian :
    C.tomitaAdditiveModularFlow =
      additiveModularFlowOfGenerator (H := H) C.modularHamiltonian := by
  unfold tomitaAdditiveModularFlow toRealModularLogData modularHamiltonian
  rfl

/--
Standard-form seed exposing the Souriau-selected Tomita modular flow while
retaining the owned doubled-carrier `(J, ε, Jε)` atom.
-/
@[rep_depth operator]
noncomputable def toStandardFormSeed : StandardFormSeed H where
  J := InfoGeometry.Canonical.TomitaTakesaki.modularConjugationJ (E := H)
  ε := InfoGeometry.Canonical.TomitaTakesaki.modularSignEpsilon (E := H)
  phaseAxis := InfoGeometry.Canonical.TomitaTakesaki.modularComplexI (E := H)
  modularFlow := C.tomitaAdditiveModularFlow
  J_sq := InfoGeometry.Canonical.TomitaTakesaki.modularConjugationJ_sq (E := H)
  eps_sq := InfoGeometry.Canonical.TomitaTakesaki.modularSignEpsilon_sq (E := H)
  phase_sq := InfoGeometry.Canonical.TomitaTakesaki.modularComplexI_sq (E := H)
  J_phase_anticommute :=
    InfoGeometry.Canonical.TomitaTakesaki.modularConjugationJ_anticommutes_modularComplexI
      (E := H)

/--
Concrete standard-form carrier for the Souriau/Tomita logarithmic lane.
This replaces bare `deltaLog = thermalGenerator` prose by a carrier whose flow
is explicitly generated by the modular Hamiltonian.
-/
@[rep_depth operator]
noncomputable def toStandardFormCarrier : StandardFormCarrier H where
  seed := C.toStandardFormSeed
  Delta := C.modularHamiltonian
  referenceState := ⟨0⟩
  modularFlow_eq_generator := C.tomitaAdditiveModularFlow_eq_generator_modularHamiltonian

/-- The standard-form carrier uses the Souriau modular Hamiltonian as its generator. -/
@[rep_depth operator]
theorem toStandardFormCarrier_Delta_eq_modularHamiltonian :
    C.toStandardFormCarrier.Delta = C.modularHamiltonian :=
  rfl

/-- Evaluation form of the standard-form carrier flow. -/
@[rep_depth operator]
theorem toStandardFormCarrier_modularFlow_apply
    (t : ℝ) (A : Obs) :
    C.toStandardFormCarrier.seed.modularFlow t A =
      InfoGeometry.Krein.modular_shift (E := H) C.modularHamiltonian t A := by
  calc
    C.toStandardFormCarrier.seed.modularFlow t A
        = C.tomitaAdditiveModularFlow t A := rfl
    _ = InfoGeometry.Krein.modular_shift (E := H) C.modularHamiltonian t A := by
          exact additiveModularFlowOfGenerator_apply
            (H := H) C.modularHamiltonian t A

/--
The Tomita flow generated by `deltaLog` is the Souriau modular transport flow
generated by the geometric-temperature moment.
-/
@[rep_depth operator]
theorem tomita_flow_eq_souriau_modularTransportFlow :
    C.tomitaAdditiveModularFlow = C.souriauAdditiveModularFlow := by
  change
    additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator =
      additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator
  rfl

/-- Evaluation form of the Souriau additive modular flow. -/
@[rep_depth operator]
theorem souriauAdditiveModularFlow_apply_eq_modular_shift
    (t : ℝ) (A : Obs) :
    C.souriauAdditiveModularFlow t A =
      InfoGeometry.Krein.modular_shift
        (E := H) C.souriauMoment.thermalGenerator t A :=
  additiveModularFlowOfGenerator_apply
    (H := H) C.souriauMoment.thermalGenerator t A

/-- The Souriau modular generator is the moment at geometric temperature. -/
@[rep_depth operator]
theorem souriauModularGenerator_eq_moment_geometricTemperature :
    C.souriauMoment.thermalGenerator =
      C.souriauMoment.momentOperator C.souriauMoment.geometricTemperature :=
  C.souriauMoment.thermalGenerator_eq_moment_geometricTemperature

/-- The modular Hamiltonian is the Souriau moment at geometric temperature. -/
@[rep_depth operator]
theorem modularHamiltonian_eq_moment_geometricTemperature :
    C.modularHamiltonian =
      C.souriauMoment.momentOperator C.souriauMoment.geometricTemperature :=
  C.souriauModularGenerator_eq_moment_geometricTemperature

/--
The Tomita logarithmic datum is the modular Hamiltonian in this bridge.
-/
@[rep_depth operator]
theorem tomita_deltaLog_eq_modularHamiltonian :
    C.toRealModularLogData = C.modularHamiltonian :=
  C.tomita_deltaLog_eq_thermalGenerator

/-- The generated automorphism acts by conjugation with the modular Hamiltonian. -/
@[rep_depth operator]
theorem souriauAdditiveModularFlow_apply_eq_modularHamiltonian_shift
    (t : ℝ) (A : Obs) :
    C.souriauAdditiveModularFlow t A =
      InfoGeometry.Krein.modular_shift (E := H) C.modularHamiltonian t A :=
  C.souriauAdditiveModularFlow_apply_eq_modular_shift t A

end SouriauTomitaLogContext

/-- Zero thermal-moment Souriau datum on an arbitrary symmetry carrier. -/
@[rep_depth operator]
noncomputable def zeroThermalSouriauMoment (geometricTemperature : Symmetry) :
    OperatorSouriauMoment (H := H) Symmetry where
  momentOperator := fun _ => 0
  geometricTemperature := geometricTemperature

/--
Constructive identity-branch logarithmic context.

The modular Hamiltonian is not supplied as a zero hypothesis here: it is the
Souriau moment at the chosen geometric temperature, and this constructor makes
that moment definitionally zero.
-/
@[rep_depth operator]
noncomputable def SouriauTomitaLogContext.ofZeroThermalMoment
    (geometricTemperature : Symmetry) :
    SouriauTomitaLogContext (H := H) (Symmetry := Symmetry) where
  souriauMoment := zeroThermalSouriauMoment (H := H) geometricTemperature

namespace SouriauTomitaLogContext

/-- In the zero-thermal-moment constructor, the modular Hamiltonian vanishes by construction. -/
@[rep_depth operator]
theorem modularHamiltonian_zero_ofZeroThermalMoment
    (geometricTemperature : Symmetry) :
    (ofZeroThermalMoment (H := H) geometricTemperature).modularHamiltonian = 0 :=
  rfl

end SouriauTomitaLogContext

/--
KMS context for the Souriau-generated Tomita modular automorphism group.

This is deliberately proof-carrying: the repo has the algebraic KMS identity
as `KMSState`, but it does not own the full analytic strip theorem for arbitrary
Type III factors.  The constructive content here is that the KMS identity is
threaded through the exact modular flow generated by the Souriau modular
Hamiltonian.
-/
@[rep_depth operator]
structure SouriauTomitaKMSContext where
  logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry)
  beta : ℝ
  kms :
    KMSState (H := H)
      logContext.souriauAdditiveModularFlow beta

/--
Minimal constructive Souriau/Tomita KMS context.

This keeps only the genuinely owned constructive data:

* the Souriau/Tomita logarithmic context,
* the modular inverse temperature `beta`, and
* the proof-carrying `KMSState` packet.

The algebraic state is recovered definitionally as `kms.state`, so the
constructive branch no longer needs an additional `state` packet.
-/
@[rep_depth operator]
structure MinimalSouriauTomitaKMSContext where
  logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry)
  beta : ℝ
  kms :
    KMSState (H := H)
      logContext.souriauAdditiveModularFlow beta

namespace MinimalSouriauTomitaKMSContext

/-- The modular state is read directly from the KMS witness. -/
@[rep_depth operator]
def state (C : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge.AlgebraicState
      (H := H) :=
  C.kms.state

/-- Constructor theorem exposing the derived state on the minimal KMS branch. -/
@[rep_depth operator]
theorem mk_of_kms
    (logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))
    (beta : ℝ)
    (kms : KMSState (H := H) logContext.souriauAdditiveModularFlow beta) :
    ∃ ctx : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry),
      ctx.state = kms.state := by
  refine ⟨{ logContext := logContext, beta := beta, kms := kms }, by
    rfl⟩

variable (C : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry))

/-- The minimal Souriau/Tomita modular automorphism group is generated by the log context. -/
@[rep_depth operator]
noncomputable def sigma : AdditiveModularFlow (H := H) :=
  C.logContext.souriauAdditiveModularFlow

/-- The KMS modular time parameter carried by the minimal context. -/
@[rep_depth operator]
def modularBeta : ℝ :=
  C.beta

/-- The minimal Souriau/Tomita modular automorphism group is additive. -/
@[rep_depth operator]
theorem sigma_add (s t : ℝ) :
    C.sigma (s + t) = C.sigma s * C.sigma t :=
  AdditiveModularFlow.map_add C.sigma s t

/-- The minimal Souriau/Tomita modular automorphism group starts at identity. -/
@[rep_depth operator]
theorem sigma_zero :
    C.sigma 0 = 1 :=
  AdditiveModularFlow.map_zero C.sigma

/-- The modular Hamiltonian is the Souriau moment at geometric temperature. -/
@[rep_depth operator]
theorem modularHamiltonian_eq_moment_geometricTemperature :
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature :=
  C.logContext.modularHamiltonian_eq_moment_geometricTemperature

/--
Minimal constructive KMS identity over the Souriau-generated modular flow.

This theorem keeps the narrowed branch on `MinimalSouriauTomitaKMSContext`: the
state is read definitionally from the `KMSState` packet, and no separate
`state`/`kms_state_eq` hypothesis is exposed.
-/
@[rep_depth operator]
theorem kms_eval_mul_souriau_modular_eq_eval_flip
    (A B : Obs) :
    C.state.eval (A * C.sigma C.modularBeta B) =
      C.state.eval (B * A) := by
  exact C.kms.eval_mul_modular_eq_eval_flip A B

/--
Search-facing constructive KMS packet on the minimal Souriau/Tomita branch.

This keeps the narrowed branch on `MinimalSouriauTomitaKMSContext`: the KMS
state is still read definitionally from the proof-carrying `KMSState`, and no
separate `state` or `kms_state_eq` packet is reintroduced.
-/
@[rep_depth operator]
theorem constructive_kms_packet
    (A B : Obs) (s t : ℝ) :
    C.state.eval (A * C.sigma C.modularBeta B) =
        C.state.eval (B * A) ∧
    C.sigma (s + t) = C.sigma s * C.sigma t ∧
    C.sigma 0 = 1 ∧
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature := by
  exact ⟨
    C.kms_eval_mul_souriau_modular_eq_eval_flip A B,
    C.sigma_add s t,
    C.sigma_zero,
    C.modularHamiltonian_eq_moment_geometricTemperature⟩

/-- Compatibility adapter back to the broad Souriau/Tomita KMS context. -/
@[rep_depth operator]
noncomputable def toSouriauTomitaKMSContext
    (C : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) where
  logContext := C.logContext
  beta := C.beta
  kms := C.kms

end MinimalSouriauTomitaKMSContext

namespace SouriauTomitaKMSContext

/-- The modular state is read directly from the KMS witness. -/
@[rep_depth operator]
def state (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge.AlgebraicState
      (H := H) :=
  C.kms.state

/-- Convenience lemma: the derived `state` equals the KMS state's `state`. -/
@[rep_depth operator]
theorem state_eq_kms_state_readback (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    C.state = C.kms.state :=
  rfl

/-- Backward-compatible readback of the derived state. -/
@[rep_depth operator]
theorem kms_state_eq (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    C.state = C.kms.state :=
  rfl

/-- Constructor theorem exposing the state field from an explicit KMS witness packet. -/
@[rep_depth operator]
theorem mk_of_state_kms
    (logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))
    (beta : ℝ)
    (state : InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge.AlgebraicState
      (H := H))
    (kms : KMSState (H := H) logContext.souriauAdditiveModularFlow beta)
    (hstate : kms.state = state) :
    ∃ ctx : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry), ctx.state = state := by
  refine ⟨{ logContext := logContext, beta := beta, kms := kms }, ?_⟩
  simpa [SouriauTomitaKMSContext.state] using hstate

/-- Constructor theorem that builds a `SouriauTomitaKMSContext` directly from a `KMSState`
    without requiring an explicit `state` argument. The `state` field is defined
    definitionally as `kms.state`, and the `kms_state_eq` packet is `rfl`.
-/
@[rep_depth operator]
theorem mk_of_kms
    (logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))
    (beta : ℝ)
      (kms : KMSState (H := H) logContext.souriauAdditiveModularFlow beta) :
    ∃ ctx : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry),
      ctx.state = kms.state := by
  refine ⟨{ logContext := logContext, beta := beta, kms := kms }, by
    rfl⟩
/-- Direct constructor: build a `SouriauTomitaKMSContext` from a `KMSState`
    without carrying an explicit `state` field or `kms_state_eq` hypothesis.
    The state is derived from `kms.state` definitionally, removing the explicit
    hypothesis packet from the exposed surface on the constructive route while
    preserving the standard-form carrier and the KMS identity.
-/
@[rep_depth operator]
noncomputable def ofKMS
    (logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))
    (beta : ℝ)
    (kms : KMSState (H := H) logContext.souriauAdditiveModularFlow beta) :
    SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) where
  logContext := logContext
  beta := beta
  kms := kms

/-- The `ofKMS` constructor reads back the same `state` definitionally. -/
@[rep_depth operator]
theorem state_eq_kms_state_ofKMS
    (logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))
    (beta : ℝ)
    (kms : KMSState (H := H) logContext.souriauAdditiveModularFlow beta) :
    (ofKMS logContext beta kms).state = kms.state := rfl

/--
Compatibility adapter exposing the broad context through the same constructive
data carried by the minimal KMS branch.
-/
@[rep_depth operator]
noncomputable def toMinimalSouriauTomitaKMSContext
    (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) where
  logContext := C.logContext
  beta := C.beta
  kms := C.kms

/-- The broad-to-minimal adapter preserves the derived state definitionally. -/
@[rep_depth operator]
theorem toMinimalSouriauTomitaKMSContext_state_eq
    (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    C.toMinimalSouriauTomitaKMSContext.state = C.state :=
  rfl

/--
Compatibility constructor: a minimal constructive KMS witness immediately
rebuilds the broad Souriau/Tomita KMS context without re-supplying any explicit
state packet.
-/
@[rep_depth operator]
theorem mk_of_minimal_kms
    (C : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    ∃ ctx : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry),
      ctx.state = C.state := by
  refine ⟨C.toSouriauTomitaKMSContext, rfl⟩

variable (C : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry))

/-- The modular automorphism group is the Souriau/Tomita generated flow. -/
@[rep_depth operator]
noncomputable def sigma : AdditiveModularFlow (H := H) :=
  C.logContext.souriauAdditiveModularFlow

/-- The KMS modular time parameter carried by this context. -/
@[rep_depth operator]
def modularBeta : ℝ :=
  C.beta

/-- KMS identity over the Souriau-generated modular automorphism group. -/
@[rep_depth operator]
theorem kms_eval_mul_souriau_modular_eq_eval_flip
    (A B : Obs) :
    C.state.eval (A * C.sigma C.modularBeta B) =
      C.state.eval (B * A) := by
  calc
    C.state.eval (A * C.sigma C.modularBeta B)
        = C.kms.state.eval (A * C.sigma C.modularBeta B) := by
            rw [C.kms_state_eq]
    _ = C.kms.state.eval (B * A) :=
          C.kms.eval_mul_modular_eq_eval_flip A B
    _ = C.state.eval (B * A) := by
          rw [C.kms_state_eq]

/-- The Souriau/Tomita modular automorphism group is additive. -/
@[rep_depth operator]
theorem sigma_add (s t : ℝ) :
    C.sigma (s + t) = C.sigma s * C.sigma t :=
  AdditiveModularFlow.map_add C.sigma s t

/-- The Souriau/Tomita modular automorphism group starts at identity. -/
@[rep_depth operator]
theorem sigma_zero :
    C.sigma 0 = 1 :=
  AdditiveModularFlow.map_zero C.sigma

/-- The modular Hamiltonian is the Souriau moment at geometric temperature. -/
@[rep_depth operator]
theorem modularHamiltonian_eq_moment_geometricTemperature :
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature :=
  C.logContext.modularHamiltonian_eq_moment_geometricTemperature

/-- Search-facing packet for the constructed modular automorphism/KMS bridge. -/
@[rep_depth operator]
theorem constructive_kms_packet
    (A B : Obs) (s t : ℝ) :
    C.state.eval (A * C.sigma C.modularBeta B) =
        C.state.eval (B * A) ∧
    C.sigma (s + t) = C.sigma s * C.sigma t ∧
    C.sigma 0 = 1 ∧
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature := by
  exact ⟨
    C.kms_eval_mul_souriau_modular_eq_eval_flip A B,
    C.sigma_add s t,
    C.sigma_zero,
    C.modularHamiltonian_eq_moment_geometricTemperature⟩

end SouriauTomitaKMSContext

namespace MinimalSouriauTomitaKMSContext

/-- The broad adapter preserves the derived algebraic state definitionally. -/
@[rep_depth operator]
theorem toSouriauTomitaKMSContext_state_eq
    (C : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry)) :
    C.toSouriauTomitaKMSContext.state = C.state :=
  rfl

end MinimalSouriauTomitaKMSContext

/--
Constructive cyclic zero-thermal Souriau/Tomita KMS branch.

This is the honest infinite-dimensional narrowing where no explicit `kms`
packet is supplied.  Instead, the branch carries only:

* a cyclic algebraic state,
* a geometric temperature selecting the zero thermal moment, and
* the modular inverse temperature `beta`.

From these data the module constructs the zero modular Hamiltonian, the induced
Souriau/Tomita modular flow, and the KMS witness.
-/
@[rep_depth operator]
structure CyclicSouriauTomitaKMSContext where
  geometricTemperature : Symmetry
  state : CyclicAlgebraicState (H := H)
  beta : ℝ

namespace CyclicSouriauTomitaKMSContext

variable (C : CyclicSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry))

/-- The logarithmic Souriau/Tomita context is the zero-thermal-moment branch. -/
@[rep_depth operator]
noncomputable def logContext : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry) :=
  SouriauTomitaLogContext.ofZeroThermalMoment (H := H) C.geometricTemperature

/-- On the zero-thermal branch, the modular Hamiltonian vanishes. -/
@[rep_depth operator]
theorem modularHamiltonian_zero : C.logContext.modularHamiltonian = 0 :=
  SouriauTomitaLogContext.modularHamiltonian_zero_ofZeroThermalMoment
    (H := H) C.geometricTemperature

/-- The induced Souriau/Tomita modular flow is the identity on observables. -/
@[rep_depth operator]
theorem sigma_apply_eq_self (t : ℝ) (A : Obs) :
    C.logContext.souriauAdditiveModularFlow t A = A := by
  rw [SouriauTomitaLogContext.souriauAdditiveModularFlow_apply_eq_modularHamiltonian_shift]
  rw [C.modularHamiltonian_zero]
  simp [InfoGeometry.Krein.modular_shift, InfoGeometry.Krein.krein_modular_shift]

/-- Constructive KMS witness derived from cyclicity on the zero-thermal branch. -/
@[rep_depth operator]
noncomputable def kms :
    KMSState (H := H) C.logContext.souriauAdditiveModularFlow C.beta where
  state := C.state.state
  kms_identity := by
    intro A B
    rw [C.sigma_apply_eq_self C.beta B]
    simpa using C.state.cyclic A B

/-- The standard-form carrier extracted from the zero-thermal branch has `Δ = 0`. -/
@[rep_depth operator]
theorem toStandardFormCarrier_Delta_eq_zero :
    C.logContext.toStandardFormCarrier.Delta = 0 := by
  rw [C.logContext.toStandardFormCarrier_Delta_eq_modularHamiltonian]
  exact C.modularHamiltonian_zero

/-- The standard-form carrier flow is the identity on the cyclic zero-thermal branch. -/
@[rep_depth operator]
theorem toStandardFormCarrier_modularFlow_apply_eq_self (t : ℝ) (A : Obs) :
    C.logContext.toStandardFormCarrier.seed.modularFlow t A = A := by
  calc
    C.logContext.toStandardFormCarrier.seed.modularFlow t A
        = C.logContext.souriauAdditiveModularFlow t A := rfl
    _ = A := C.sigma_apply_eq_self t A

/-- Build the standard `SouriauTomitaKMSContext` without an explicit KMS packet. -/
@[rep_depth operator]
noncomputable def toSouriauTomitaKMSContext :
    SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) where
  logContext := C.logContext
  beta := C.beta
  kms := C.kms

/-- Build the minimal constructive KMS context on the cyclic zero-thermal branch. -/
@[rep_depth operator]
noncomputable def toMinimalSouriauTomitaKMSContext :
    MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) where
  logContext := C.logContext
  beta := C.beta
  kms := C.kms

/-- The minimal cyclic adapter reads back the cyclic algebraic state definitionally. -/
@[rep_depth operator]
theorem toMinimalSouriauTomitaKMSContext_state_eq :
    C.toMinimalSouriauTomitaKMSContext.state = C.state.state :=
  rfl

/-- The broad cyclic adapter also preserves the cyclic algebraic state. -/
@[rep_depth operator]
theorem toSouriauTomitaKMSContext_state_eq :
    C.toSouriauTomitaKMSContext.state = C.state.state :=
  rfl

/-- Constructor theorem for the cyclic zero-thermal KMS branch. -/
@[rep_depth operator]
theorem mk_of_cyclic :
    ∃ ctx : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry),
      ctx.state = C.state.state := by
  simpa [C.toMinimalSouriauTomitaKMSContext_state_eq] using
    (SouriauTomitaKMSContext.mk_of_minimal_kms
      (H := H) (Symmetry := Symmetry) C.toMinimalSouriauTomitaKMSContext)

/--
Search-facing constructive KMS packet on the cyclic zero-thermal branch.

This removes the explicit `kms : KMSState ...` packet from the theorem-facing
surface: cyclicity plus the zero-thermal logarithmic lane are enough to recover
all four readbacks through the constructed Souriau/Tomita KMS context.
-/
@[rep_depth operator]
theorem constructive_kms_packet
    (A B : Obs) (s t : ℝ) :
    C.state.state.eval (A * C.logContext.souriauAdditiveModularFlow C.beta B) =
        C.state.state.eval (B * A) ∧
    C.logContext.souriauAdditiveModularFlow (s + t) =
        C.logContext.souriauAdditiveModularFlow s *
          C.logContext.souriauAdditiveModularFlow t ∧
    C.logContext.souriauAdditiveModularFlow 0 = 1 ∧
    C.logContext.modularHamiltonian =
      C.logContext.souriauMoment.momentOperator
        C.logContext.souriauMoment.geometricTemperature := by
  simpa [C.toSouriauTomitaKMSContext_state_eq] using
    (C.toSouriauTomitaKMSContext.constructive_kms_packet A B s t)

/-- Backward-compatible broad constructor theorem from the cyclic zero-thermal branch. -/
@[rep_depth operator]
theorem mk_broad_of_cyclic :
    ∃ ctx : SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry),
      ctx.state = C.state.state :=
  C.mk_of_cyclic

end CyclicSouriauTomitaKMSContext

namespace MinimalSouriauTomitaKMSContext

/--
Direct constructive minimal KMS constructor from cyclicity on the zero-thermal
Souriau/Tomita branch.

This removes the explicit `kms : KMSState ...` packet from the minimal surface:
the KMS witness is constructed from the cyclic state, the zero-thermal
logarithmic context, and the inverse temperature.
-/
@[rep_depth operator]
noncomputable def ofCyclicZeroThermal
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ) :
    MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) :=
  let C : CyclicSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) :=
    { geometricTemperature := geometricTemperature
      state := state
      beta := beta }
  C.toMinimalSouriauTomitaKMSContext

/-- The direct cyclic zero-thermal constructor reads back the cyclic state. -/
@[rep_depth operator]
theorem ofCyclicZeroThermal_state_eq
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ) :
    (ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
      geometricTemperature state beta).state = state.state := by
  simp [ofCyclicZeroThermal, MinimalSouriauTomitaKMSContext.state,
    CyclicSouriauTomitaKMSContext.toMinimalSouriauTomitaKMSContext,
    CyclicSouriauTomitaKMSContext.kms]

/--
The direct cyclic zero-thermal minimal constructor satisfies the Souriau/Tomita
KMS identity without an explicit `kms : KMSState ...` argument.
-/
@[rep_depth operator]
theorem ofCyclicZeroThermal_kms_eval_mul_souriau_modular_eq_eval_flip
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ)
    (A B : Obs) :
    (ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
      geometricTemperature state beta).state.eval
        (A * (ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
          geometricTemperature state beta).logContext.souriauAdditiveModularFlow beta B) =
      (ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
        geometricTemperature state beta).state.eval (B * A) := by
  let C : CyclicSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) :=
    { geometricTemperature := geometricTemperature
      state := state
      beta := beta }
  simpa [MinimalSouriauTomitaKMSContext.state,
    CyclicSouriauTomitaKMSContext.toMinimalSouriauTomitaKMSContext] using
    (C.kms.eval_mul_modular_eq_eval_flip A B)

/-- Existential constructor theorem for the minimal cyclic zero-thermal branch. -/
@[rep_depth operator]
theorem mk_of_cyclic_zero_thermal
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ) :
    ∃ ctx : MinimalSouriauTomitaKMSContext (H := H) (Symmetry := Symmetry),
      ctx.state = state.state := by
  refine ⟨ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
    geometricTemperature state beta, ?_⟩
  simpa using ofCyclicZeroThermal_state_eq (H := H) (Symmetry := Symmetry)
    geometricTemperature state beta

end MinimalSouriauTomitaKMSContext

/--
Direct constructive broad KMS constructor from cyclicity on the zero-thermal
Souriau/Tomita branch.

This removes the explicit `kms : KMSState ...` packet from the broad theorem
surface while preserving the standard `SouriauTomitaKMSContext` API for
compatibility consumers.
-/
@[rep_depth operator]
noncomputable def SouriauTomitaKMSContext.ofCyclicZeroThermal
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ) :
    SouriauTomitaKMSContext (H := H) (Symmetry := Symmetry) :=
  (MinimalSouriauTomitaKMSContext.ofCyclicZeroThermal
    (H := H) (Symmetry := Symmetry) geometricTemperature state beta).toSouriauTomitaKMSContext

/-- The direct broad cyclic zero-thermal constructor reads back the cyclic state. -/
@[rep_depth operator]
theorem SouriauTomitaKMSContext.ofCyclicZeroThermal_state_eq
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ) :
    (SouriauTomitaKMSContext.ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
      geometricTemperature state beta).state = state.state := by
  simpa [SouriauTomitaKMSContext.ofCyclicZeroThermal] using
    (MinimalSouriauTomitaKMSContext.toSouriauTomitaKMSContext_state_eq
      (H := H) (Symmetry := Symmetry)
      (MinimalSouriauTomitaKMSContext.ofCyclicZeroThermal
        (H := H) (Symmetry := Symmetry) geometricTemperature state beta)).trans
      (MinimalSouriauTomitaKMSContext.ofCyclicZeroThermal_state_eq
        (H := H) (Symmetry := Symmetry) geometricTemperature state beta)

/--
The direct broad cyclic zero-thermal constructor satisfies the Souriau/Tomita
KMS identity without an explicit `kms : KMSState ...` argument.
-/
@[rep_depth operator]
theorem SouriauTomitaKMSContext.ofCyclicZeroThermal_kms_eval_mul_souriau_modular_eq_eval_flip
    (geometricTemperature : Symmetry)
    (state : CyclicAlgebraicState (H := H))
    (beta : ℝ)
    (A B : Obs) :
    (SouriauTomitaKMSContext.ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
      geometricTemperature state beta).state.eval
        (A * (SouriauTomitaKMSContext.ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
          geometricTemperature state beta).logContext.souriauAdditiveModularFlow beta B) =
      (SouriauTomitaKMSContext.ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
        geometricTemperature state beta).state.eval (B * A) := by
  simpa [SouriauTomitaKMSContext.ofCyclicZeroThermal, SouriauTomitaKMSContext.sigma,
    SouriauTomitaKMSContext.modularBeta] using
    ((SouriauTomitaKMSContext.ofCyclicZeroThermal (H := H) (Symmetry := Symmetry)
      geometricTemperature state beta).kms_eval_mul_souriau_modular_eq_eval_flip A B)
