import InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge
import InfoGeometry.Canonical.TomitaTakesaki
import InfoGeometry.Meta.Architecture

/-!
# InfoGeometry.Canonical.SouriauTomitaModularFlowBridge

Dimension-agnostic bridge from Souriau geometric temperature to the
operator-algebraic Tomita modular-flow lane.

The finite `Spin(4,4)` Cartan character formulas are only representation
shadows.  The source-owned theorem here is the operatorial one:
the Souriau thermal generator selected by geometric temperature is the
logarithmic Tomita generator, and its additive modular flow is the existing
Connes/Tomita exponential conjugation flow.
-/

namespace InfoGeometry.Canonical.SouriauTomitaModularFlowBridge

open InfoGeometry.Volume.ConnesCocycle
open InfoGeometry.Canonical.CoordinatelessSouriauKMSBridge

universe u v

section OperatorialBridge

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
variable {Symmetry : Type v}

local notation "Obs" => AlgebraEnd H

/--
Proof-carrying Souriau/Tomita logarithm context.

`deltaLog` is the logarithmic modular generator (`K = -log Δ`) and the witness
identifies it with `OperatorSouriauMoment.thermalGenerator`, i.e. with the
moment operator evaluated at the geometric temperature.
-/
@[rep_depth operator]
structure SouriauTomitaLogContext where
  souriauMoment : OperatorSouriauMoment (H := H) Symmetry
  deltaLog : Obs
  deltaLog_eq_thermalGenerator :
    deltaLog = souriauMoment.thermalGenerator

namespace SouriauTomitaLogContext

variable (C : SouriauTomitaLogContext (H := H) (Symmetry := Symmetry))

/-- The real Tomita logarithm data exposed as an operator on the observable carrier. -/
@[rep_depth operator]
def toRealModularLogData : Obs :=
  C.deltaLog

/-- The Tomita logarithm equals the Souriau thermal generator. -/
@[rep_depth operator]
theorem tomita_deltaLog_eq_thermalGenerator :
    C.toRealModularLogData = C.souriauMoment.thermalGenerator :=
  C.deltaLog_eq_thermalGenerator

/-- Souriau additive modular flow generated by the geometric-temperature moment. -/
@[rep_depth operator]
noncomputable def souriauAdditiveModularFlow : AdditiveModularFlow (H := H) :=
  additiveModularFlowOfGenerator (H := H) C.souriauMoment.thermalGenerator

/-- Tomita additive modular flow generated by the logarithmic modular datum. -/
@[rep_depth operator]
noncomputable def tomitaAdditiveModularFlow : AdditiveModularFlow (H := H) :=
  additiveModularFlowOfGenerator (H := H) C.toRealModularLogData

/--
The Tomita flow generated by `deltaLog` is the Souriau modular transport flow
generated by the geometric-temperature moment.
-/
@[rep_depth operator]
theorem tomita_flow_eq_souriau_modularTransportFlow :
    C.tomitaAdditiveModularFlow = C.souriauAdditiveModularFlow := by
  unfold tomitaAdditiveModularFlow souriauAdditiveModularFlow
  rw [C.tomita_deltaLog_eq_thermalGenerator]

/-- Evaluation form of the Souriau additive modular flow. -/
@[rep_depth operator]
theorem souriauAdditiveModularFlow_apply_eq_modular_shift
    (t : ℝ) (A : Obs) :
    C.souriauAdditiveModularFlow t A =
      InfoGeometry.Krein.modular_shift
        (E := H) C.souriauMoment.thermalGenerator t A :=
  additiveModularFlowOfGenerator_apply
    (H := H) C.souriauMoment.thermalGenerator t A

/-- The Souriau modular generator is the moment at geometric temperature. -/
@[rep_depth operator]
theorem souriauModularGenerator_eq_moment_geometricTemperature :
    C.souriauMoment.thermalGenerator =
      C.souriauMoment.momentOperator C.souriauMoment.geometricTemperature :=
  C.souriauMoment.thermalGenerator_eq_moment_geometricTemperature

end SouriauTomitaLogContext

end OperatorialBridge

end InfoGeometry.Canonical.SouriauTomitaModularFlowBridge
