import Mathlib.Tactic
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Analysis.Matrix.Order
import InfoGeometry.Physics.ChiralCausalCone
import InfoGeometry.Categorical.CuntzCliffordFibonacciBraid
import InfoGeometry.Canonical.SplitQuaternionMatrixModel

open Matrix
open InfoGeometry.Physics.ChiralCausalCone
open InfoGeometry.Categorical.CuntzCliffordFibonacciBraid
open InfoGeometry.Canonical.SplitQuaternionMatrixModel

noncomputable section

namespace InfoGeometry.Canonical.SplitQuaternionOperatorPoset

/-!
# BKM Causal Operator Poset for Split Quaternions & Cuntz Supercharges

This module formalizes the BKM information-geometric causal preorder
on operators generated by split quaternions $\mathbb{H}_{\text{split}}$ and Cuntz supercharges $Q_R, Q_L$.

Key Results:
1. Supercharge Vector Arrow: $\vec{v}_{\text{chiral}} = Q_R - Q_L = S_+ S_-^* - S_- S_+^*$.
2. Tomita Modular Anti-symmetry: $J (\Delta Q) J = -\Delta Q$.
3. Poincaré Lightcone & Spatial Momentum: $P_x = P_+ - P_- = S_+ S_+^* - S_- S_-^* = \sigma^3$.
4. Split-Quaternion Causal Cone & Norm: $N(q) = a^2 + d^2 - b^2 - c^2 \ge 0$.
5. Causal Preorder: $A \le_{\text{causal}} B \iff 0 \le \vec{v}(B) - \vec{v}(A)$.
6. Preorder Properties: Reflexivity and Transitivity natively proved; no
   antisymmetry is claimed because the arrow forgets the `a` and `d` components.
7. Chiral Cuntz Nilpotency: $Q_R^2 = (S_1 S_2^*)^2 = 0$ when $S_2^* S_1 = 0$.
-/

/-- Split quaternion operator representation: q = a·1 + b·i + c·j + d·k. -/
structure SplitQuaternion where
  a : ℝ
  b : ℝ
  c : ℝ
  d : ℝ

/-- Split-quaternion quadratic norm N(q) = a² + d² - b² - c². -/
def splitNorm (sq : SplitQuaternion) : ℝ :=
  sq.a ^ 2 + sq.d ^ 2 - sq.b ^ 2 - sq.c ^ 2

/-- Timelike / Null Causal Cone condition N(q) ≥ 0 with positive energy a ≥ 0. -/
def IsCausalFuture (sq : SplitQuaternion) : Prop :=
  0 ≤ splitNorm sq ∧ 0 ≤ sq.a

/-- The vector arrow determined by the difference of Right and Left supercharges Q_R - Q_L.
    In the chiral Pauli representation, Q_R = σ⁺, Q_L = σ⁻, so Q_R - Q_L = σ⁺ - σ⁻ = i σ². -/
def superchargeVectorArrow (sq : SplitQuaternion) : ℝ :=
  sq.b - sq.c

/-- **Poset Order Relation**: Operator A ≤_causal B iff the BKM supercharge vector arrow
    difference (B - A) · (Q_R - Q_L) is non-negative. -/
def CausalPosetOrder (A B : SplitQuaternion) : Prop :=
  0 ≤ superchargeVectorArrow B - superchargeVectorArrow A

instance : LE SplitQuaternion where
  le := CausalPosetOrder

/-- **Theorem**: Reflexivity of the Split Quaternion Causal Operator Poset. -/
theorem causal_refl (A : SplitQuaternion) : A ≤ A := by
  dsimp [LE.le, CausalPosetOrder]
  rw [sub_self]
  exact le_refl (0 : ℝ)

/-- **Theorem**: Transitivity of the Split Quaternion Causal Operator Poset. -/
theorem causal_trans (A B C : SplitQuaternion) (h1 : A ≤ B) (h2 : B ≤ C) : A ≤ C := by
  dsimp [LE.le, CausalPosetOrder] at *
  have h_sum : 0 ≤ (superchargeVectorArrow B - superchargeVectorArrow A) + (superchargeVectorArrow C - superchargeVectorArrow B) :=
    add_nonneg h1 h2
  have h_ring : (superchargeVectorArrow B - superchargeVectorArrow A) + (superchargeVectorArrow C - superchargeVectorArrow B) =
    superchargeVectorArrow C - superchargeVectorArrow A := by ring
  rwa [h_ring] at h_sum

/-- The causal relation is a preorder, rather than a partial order on all
split quaternions, because distinct elements may have the same arrow value. -/
instance : Preorder SplitQuaternion where
  le := CausalPosetOrder
  le_refl := causal_refl
  le_trans A B C := causal_trans A B C

/-- **Theorem**: Chiral Cuntz Supercharge Nilpotency of Right/Left Generators.
    Given orthogonal Cuntz operators S₁, S₂ with S₂* S₁ = 0, the Right supercharge
    Q_R = S₁ S₂* is nilpotent: Q_R² = 0. -/
theorem cuntz_supercharge_nilpotent
    {R : Type*} [Ring R] [StarRing R] (S1 S2 : R)
    (h_ortho : star S2 * S1 = 0) :
    (S1 * star S2) * (S1 * star S2) = 0 := by
  calc (S1 * star S2) * (S1 * star S2)
    _ = S1 * (star S2 * S1) * star S2 := by simp only [mul_assoc]
    _ = S1 * 0 * star S2 := by rw [h_ortho]
    _ = 0 := by simp only [mul_zero, zero_mul]

/-- **Theorem**: Poincaré spatial momentum projection P_x = S_+ S_+* - S_- S_-*.
    In the 2x2 matrix representation, P_+ = [1 0; 0 0], P_- = [0 0; 0 1],
    so P_x = P_+ - P_- = [1 0; 0 -1] = σ³. -/
theorem poincare_spatial_momentum_eq_sigma3 :
    (!![1, 0; 0, 0] : M2C) - !![0, 0; 0, 1] = σ3c := by
  dsimp [σ3c]
  ext i j
  fin_cases i <;> fin_cases j <;> simp

/-- **Theorem**: Tomita modular reflection anti-symmetry J (ΔQ) J = - ΔQ.
    For the vector arrow ΔQ = σ⁺ - σ⁻, modular conjugation J by Pauli σ¹ gives
    σ¹ (σ⁺ - σ⁻) σ¹ = - (σ⁺ - σ⁻). -/
theorem tomita_modular_reflection_arrow :
    (!![0, 1; 1, 0] : M2C) * (σPlus - σMinus) * !![0, 1; 1, 0] = - (σPlus - σMinus) := by
  dsimp [σPlus, σMinus]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [mul_apply]

/-! ## Genuine operator cone

The coordinate arrow above is retained for compatibility with the older
scalar packet.  The actual operator preorder is the positive-semidefinite
cone order on the existing split-quaternion matrix carrier.  Its coherence
uses Mathlib's `Matrix.PosSemidef` addition theorem and does not project an
operator to one scalar coordinate.
-/

abbrev Operator : Type :=
  InfoGeometry.Canonical.SplitQuaternionMatrixModel.Mat2

def operatorCausalOrder (A B : Operator) : Prop :=
  Matrix.PosSemidef (B - A)

theorem operator_causal_refl (A : Operator) :
    operatorCausalOrder A A := by
  dsimp [operatorCausalOrder]
  simpa using (Matrix.PosSemidef.zero : Matrix.PosSemidef (0 : Operator))

theorem operator_causal_trans (A B C : Operator)
    (hAB : operatorCausalOrder A B)
    (hBC : operatorCausalOrder B C) :
    operatorCausalOrder A C := by
  dsimp [operatorCausalOrder] at *
  have hsum : Matrix.PosSemidef ((B - A) + (C - B)) :=
    Matrix.PosSemidef.add hAB hBC
  have hEq : (B - A) + (C - B) = C - A := by
    abel
  rw [← hEq]
  exact hsum

instance : Preorder Operator where
  le := operatorCausalOrder
  le_refl := operator_causal_refl
  le_trans := operator_causal_trans

end InfoGeometry.Canonical.SplitQuaternionOperatorPoset
