import InfoGeometry.Canonical.TomitaTakesaki
import InfoGeometry.Canonical.RelativePotentialCore
import InfoGeometry.Volume.ConnesCocycle
import InfoGeometry.Meta.Architecture

open scoped InnerProductSpace

/-!
# InfoGeometry.Canonical.StandardFormCore

Minimal owner interfaces for a future standard-form / relative-modular layer.

This file deliberately stops short of a full Tomita-Takesaki standard-form
development. It packages:
- vector states on the doubled carrier,
- the current split-`Cl(1,1)` modular atom as a standard-form seed,
- a generator-based carrier for future modular operators,
- a bridge from operator cocycles to projective relative potentials.
-/

namespace InfoGeometry.Canonical.StandardFormCore

open InfoGeometry.Canonical.TomitaTakesaki
open InfoGeometry.Canonical.RelativePotentialCore
open InfoGeometry.Canonical.PositiveRayCore
open InfoGeometry.Volume.ConnesCocycle

section OperatorCarrier

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]

local notation "H2" => InfoGeometry.Krein.DoubledSpace H
local notation "EndH" => AlgebraEnd H

/-- Real vector state on the doubled carrier. -/
structure VectorState
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H] where
  vector : InfoGeometry.Krein.DoubledSpace H

/-- Expectation of an operator against a doubled-space vector state. -/
@[rep_depth krein]
noncomputable def VectorState.expectation
    (ω : VectorState H) (A : EndH) : ℝ :=
  ⟪A ω.vector, ω.vector⟫_ℝ

/--
Split-`Cl(1,1)` modular seed currently available in the repo:
conjugation `J`, sign `ε`, internal phase axis `Jε`, and the induced additive
modular flow on doubled-space endomorphisms.
-/
structure StandardFormSeed
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H] where
  J : AlgebraEnd H
  ε : AlgebraEnd H
  phaseAxis : AlgebraEnd H
  modularFlow : AdditiveModularFlow (H := H)
  J_sq : J.comp J = ContinuousLinearMap.id ℝ (InfoGeometry.Krein.DoubledSpace H)
  eps_sq : ε.comp ε = ContinuousLinearMap.id ℝ (InfoGeometry.Krein.DoubledSpace H)
  phase_sq : phaseAxis.comp phaseAxis =
    -(ContinuousLinearMap.id ℝ (InfoGeometry.Krein.DoubledSpace H))
  J_phase_anticommute : J.comp phaseAxis = -(phaseAxis.comp J)

/-- The current modular atom packaged as a standard-form seed. -/
@[rep_depth krein]
noncomputable def tomitaAtomSeed : StandardFormSeed H where
  J := modularConjugationJ (E := H)
  ε := modularSignEpsilon (E := H)
  phaseAxis := modularComplexI (E := H)
  modularFlow := modularSignAdditiveModularFlow (E := H)
  J_sq := modularConjugationJ_sq (E := H)
  eps_sq := modularSignEpsilon_sq (E := H)
  phase_sq := modularComplexI_sq (E := H)
  J_phase_anticommute := modularConjugationJ_anticommutes_modularComplexI (E := H)

@[rep_depth krein, simp] theorem tomitaAtomSeed_modularFlow_eq :
    (tomitaAtomSeed (H := H)).modularFlow = modularSignAdditiveModularFlow (E := H) := rfl

/-- The seed phase axis is exactly the doubled-space dilation operator. -/
@[rep_depth krein, simp] theorem tomitaAtomSeed_phaseAxis_eq_dilationOperator :
    (tomitaAtomSeed (H := H)).phaseAxis = InfoGeometry.Krein.dilationOperator (E := H) :=
  modularComplexI_eq_dilationOperator (E := H)

/--
Generator-based carrier for a future standard-form layer.

`Delta` is the prospective modular operator, while `seed.modularFlow` is already
required to be generated by `Delta`. Later files can strengthen this carrier
with cyclic/separating hypotheses and relative modular data.
-/
structure StandardFormCarrier
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H] where
  seed : StandardFormSeed H
  Delta : AlgebraEnd H
  referenceState : VectorState H
  modularFlow_eq_generator :
    seed.modularFlow = additiveModularFlowOfGenerator (H := H) Delta

/-- The carrier modular flow is exactly the inner flow generated by `Delta`. -/
@[rep_depth operator, simp] theorem StandardFormCarrier.modularFlow_apply
    (S : StandardFormCarrier H) (t : ℝ) (A : EndH) :
    S.seed.modularFlow t A = InfoGeometry.Krein.modular_shift (E := H) S.Delta t A := by
  have h :=
    congrArg (fun σ : AdditiveModularFlow (H := H) => σ t A) S.modularFlow_eq_generator
  simpa [additiveModularFlowOfGenerator_apply] using h

end OperatorCarrier

section ProjectiveBridge

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
variable {α : Type*} [Fintype α] [Nonempty α]

local notation "EndH" => AlgebraEnd H

/--
Bridge package joining:
- a generator-based modular carrier on doubled-space operators,
- a Connes cocycle on that carrier,
- a pair of projective positive states in the relative-potential layer.
-/
structure RelativeModularBridge
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] [CompleteSpace H]
    (α : Type*) [Fintype α] [Nonempty α] where
  carrier : StandardFormCarrier H
  source : PositiveRay α
  target : PositiveRay α
  cocycle : ℝ → AlgebraEnd H
  scalarBridge : ScalarCocycleBridge (H := H) carrier.seed.modularFlow
  isCocycle : IsConnesCocycle carrier.seed.modularFlow cocycle

/-- Projective relative log-density attached to the source/target pair. -/
@[rep_depth projective]
noncomputable def RelativeModularBridge.projectiveLogDensity
    (R : RelativeModularBridge (H := H) (α := α)) : α → ℝ :=
  relativeLogDensity R.source R.target

/-- Projective modular potential attached to the source/target pair. -/
@[rep_depth projective]
noncomputable def RelativeModularBridge.projectiveModularPotential
    (R : RelativeModularBridge (H := H) (α := α)) : α → ℝ :=
  relativeModularPotential R.source R.target

/-- Scalar logarithmic cocycle potential induced from the operator cocycle. -/
@[rep_depth operator]
noncomputable def RelativeModularBridge.operatorLogPotential
    (R : RelativeModularBridge (H := H) (α := α)) : ℝ → ℝ :=
  cocycleLogPotential (H := H) R.carrier.seed.modularFlow R.cocycle R.scalarBridge

/-- The operator cocycle log-potential is additive in time. -/
theorem RelativeModularBridge.operatorLogPotential_add
    (R : RelativeModularBridge (H := H) (α := α)) (s t : ℝ) :
    R.operatorLogPotential (s + t)
      = R.operatorLogPotential s + R.operatorLogPotential t := by
  simpa [RelativeModularBridge.operatorLogPotential] using
    cocycleLogPotential_add
      (H := H) R.carrier.seed.modularFlow R.cocycle R.isCocycle R.scalarBridge s t

/-- The projective modular potential is the negative projective log-density. -/
@[rep_depth projective, simp] theorem
    RelativeModularBridge.projectiveModularPotential_eq_neg_projectiveLogDensity
    (R : RelativeModularBridge (H := H) (α := α)) (a : α) :
    R.projectiveModularPotential a = -R.projectiveLogDensity a := by
  exact relativeModularPotential_eq_neg_relativeLogDensity R.source R.target a

/--
The projective modular potential is the target/source log-density difference on
the canonical gauge slice.
-/
@[rep_depth projective, simp] theorem
    RelativeModularBridge.projectiveModularPotential_eq_logDensity_target_sub_source
    (R : RelativeModularBridge (H := H) (α := α)) (a : α) :
    R.projectiveModularPotential a
      = InfoGeometry.Canonical.PositiveRayCore.logDensity (α := α) R.target a
        - InfoGeometry.Canonical.PositiveRayCore.logDensity (α := α) R.source a := by
  exact relativeModularPotential_eq_logDensity_base_sub_logDensity R.source R.target a

end ProjectiveBridge

end InfoGeometry.Canonical.StandardFormCore
