import InfoGeometry.Canonical.HestenesRealStructures
import InfoGeometry.Meta.Architecture

open scoped InnerProductSpace

/-!
# InfoGeometry.Canonical.TimeReversalKramers

Strict real time-reversal/Kramers interface on the doubled carrier.

This file encodes time reversal without external complex antiunitaries:
everything is real-linear on `H₂`, with phase-(anti)linearity measured against
the internal axis `K = J ∘ ε`.
-/

namespace InfoGeometry.Canonical.TimeReversalKramers

open InfoGeometry.Krein
open InfoGeometry.Canonical.HestenesRealStructures
open InfoGeometry.Canonical.HestenesKramersBridge
open InfoGeometry.Canonical.OperatorDictionary
open InfoGeometry.Canonical.BogoliubovTransport

section Core

variable {E : Type 0}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "H₂" => DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂

/--
Real time-reversal surrogate on the doubled carrier:
real-linear, Krein isometric, and phase-antilinear (`ΘK = -KΘ`).
-/
@[rep_depth krein]
structure RealTimeReversal where
  Θ : EndH
  kreinIsometric : KreinIsometric (E := E) Θ
  phaseAntilinear : KAntilinear (E := E) Θ

namespace RealTimeReversal

variable (R : RealTimeReversal (E := E))

/-- Carrier-native anticommutation law with the internal phase axis `K`. -/
@[rep_depth krein]
theorem anticomm_phaseAxisK :
    R.Θ.comp (phaseAxisK (E := E))
      =
    -((phaseAxisK (E := E)).comp R.Θ) := by
  have hAnti :
      transportAnticommutator (E := E) R.Θ (phaseAxisK (E := E)) = 0 := by
    exact
      (kAntilinear_iff_phaseAxisAnticommutator_eq_zero (E := E) R.Θ).2
        R.phaseAntilinear
  unfold transportAnticommutator at hAnti
  exact eq_neg_of_add_eq_zero_left hAnti

/-- The canonical doubled-carrier pair generated by real time reversal. -/
@[rep_depth krein]
noncomputable def pair (u : H₂) : H₂ × H₂ := (u, R.Θ u)

/-- Krein pairing is preserved along the real time-reversal action. -/
@[rep_depth krein]
theorem preserves_kreinInner (u v : H₂) :
    KreinSpace.kreinInner (H := H₂) (R.Θ u) (R.Θ v)
      = KreinSpace.kreinInner (H := H₂) u v :=
  R.kreinIsometric u v

/--
Owner bridge to the intrinsic Hestenes partner map:
every real time-reversal surrogate `Θ` sends `K u` to `-K(Θ u)`.
-/
@[rep_depth krein]
theorem map_phasePartner_eq_neg_phasePartner_map (u : H₂) :
    R.Θ (phasePartner (E := E) u)
      =
    -(phasePartner (E := E) (R.Θ u)) := by
  have hAnti := R.anticomm_phaseAxisK
  have hApply := congrArg (fun F : EndH => F u) hAnti
  simpa [phasePartner] using hApply

/--
Pair transport law against the intrinsic phase partner:
`pair (K u) = (K u, -K (Θ u))`.
-/
@[rep_depth krein]
theorem pair_phasePartner (u : H₂) :
    R.pair (phasePartner (E := E) u)
      = (phasePartner (E := E) u, -(phasePartner (E := E) (R.Θ u))) := by
  change (phasePartner (E := E) u, R.Θ (phasePartner (E := E) u))
      = (phasePartner (E := E) u, -(phasePartner (E := E) (R.Θ u)))
  rw [R.map_phasePartner_eq_neg_phasePartner_map (u := u)]

end RealTimeReversal

/-- Kramers specialization: real time reversal with square `-1`. -/
@[rep_depth krein]
structure KramersTimeReversal extends RealTimeReversal (E := E) where
  square_neg : Θ.comp Θ = -(ContinuousLinearMap.id ℝ H₂)

namespace KramersTimeReversal

variable (R : KramersTimeReversal (E := E))

/-- Forgetful map to the previously owned `KramersSymmetry` interface. -/
@[rep_depth krein]
def toKramersSymmetry : KramersSymmetry (E := E) where
  Θ := R.Θ
  kreinIsometric := R.kreinIsometric
  phaseAntilinear := R.phaseAntilinear
  square_neg := R.square_neg

/-- Nontriviality of Kramers partner for nonzero vectors. -/
@[rep_depth krein]
theorem partner_ne_self_of_ne_zero {u : H₂} (hu : u ≠ 0) :
    R.Θ u ≠ u := by
  simpa [toKramersSymmetry] using
    (KramersSymmetry.partner_ne_self_of_ne_zero (E := E) (S := R.toKramersSymmetry) hu)

/--
Kramers specialization of the intrinsic partner anti-transport law:
`Θ (K u) = -K (Θ u)`.
-/
@[rep_depth krein]
theorem map_phasePartner_eq_neg_phasePartner_map (u : H₂) :
    R.Θ (phasePartner (E := E) u)
      =
    -(phasePartner (E := E) (R.Θ u)) := by
  simpa using
    (RealTimeReversal.map_phasePartner_eq_neg_phasePartner_map
      (E := E) (R := R.toRealTimeReversal) u)

end KramersTimeReversal

end Core

end InfoGeometry.Canonical.TimeReversalKramers
