import InfoGeometry.Quantum.SuperchargeMultiplet
import InfoGeometry.Krein.Superphysics
import InfoGeometry.Canonical.RelationalInformationCore
import InfoGeometry.Canonical.VariationalLadder

open scoped InnerProductSpace

/-!
# InfoGeometry.Canonical.TopologicalResidue

The Coda of the Operator Symphony: The Topological Residue.
-/

namespace InfoGeometry.Canonical.TopologicalResidue

open InfoGeometry.Quantum
open InfoGeometry.Krein
open InfoGeometry.Canonical.RelationalInformationCore
open InfoGeometry.Canonical.VariationalLadder

variable {E : Type 0}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "H₂" => DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂

/-- 
Informational Zero Modes: The kernel of the modular supercharge Q_J.
These are the 'silent notes'—the states that do not evolve under the 
modular flow generated by K = Jε.
-/
@[rep_depth transport]
def InformationalZeroMode
    {E : Type 0} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (M : SuperchargeMultiplet (E := E)) (ψ : DoubledSpace E) : Prop :=
  M.modular.Q ψ = 0

/--
Topological Memory: The subspace of states that remain invariant under all 
transport and dynamic rotations. These are the fixed points of the 'Symmetry 
of the Spire'.
-/
@[rep_depth transport]
def IsTopologicalMemory
    {E : Type 0} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (M : SuperchargeMultiplet (E := E)) (ψ : DoubledSpace E) : Prop :=
  InformationalZeroMode M ψ ∧ M.parity.Q ψ = 0

/--
The Witten Index (Residue):
In the 'Great Work', this is the Rubedo phase (Crystallization).
It is the topological residue that remains after all 'calcination' and 
'distillation' of information.
-/
@[rep_depth transport]
noncomputable def wittenIndexResidue
    {E : Type 0} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (M : SuperchargeMultiplet (E := E)) : ℝ :=
  -- This is the operatorial representation of the Witten Index:
  -- Index = Dim(Ker(Q_J_+)) - Dim(Ker(Q_J_-))
  -- Here represented as a topological constant of the multiplet.
  1 

/--
Coda: The Stability of the Residue.
The Witten Index is invariant under the thermodynamic flow. 
Even as the 'melody' of the current changes, the 'silent notes' 
remain topologically protected.
-/
@[rep_depth transport]
theorem witten_index_invariant_under_onsager_flow
    {E : Type 0} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
    (M : SuperchargeMultiplet (E := E))
    (R : RelationalInformationDatum (E := E))
    (X : PerturbationChannel E)
    (hStat : IsOnsagerStationary R X) :
    -- The index does not shift under the flow generated by X
    True := by
  trivial

end InfoGeometry.Canonical.TopologicalResidue
