import Mathlib.Tactic
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Canonical.HolographicSouriauReconstruction

/-!
# Wallpaper symmetries compatible with the Klein-bottle Cartan shadow

Finite exact-rational audit layer for wallpaper point symmetries compatible with
the Brillouin Klein-bottle cell used in the five-graded `O(5,5)`/Pin socket.

The concrete finite result is the signed-permutation point group `D₄` generated
by the Brillouin twist `T² = -I` and glide `G T = - T G`.  These eight matrices
are the wallpaper point symmetries which normalize the Klein-bottle momentum
cell.  Full crystallographic wallpaper-group classification, Pin(5,5) bundle
construction, and global Cartan geometry remain explicit certificate layers.
-/

namespace InfoGeometry.Canonical.WallpaperKleinBottleCartan

open InfoGeometry.Canonical.HolographicSouriauReconstruction

noncomputable section

abbrev Mat2Q := InfoGeometry.Algebra.FiniteSpin.Mat2Q
abbrev Mat10Q := Matrix (Fin 10) (Fin 10) ℚ

/-- The eight signed-permutation wallpaper point symmetries generated by the
quarter-turn Brillouin twist and the glide reflection. -/
def wallpaperD4 : Fin 8 → Mat2Q
  | 0 => 1
  | 1 => brillouinTwist2
  | 2 => -1
  | 3 => -brillouinTwist2
  | 4 => brillouinGlide2
  | 5 => brillouinTwist2 * brillouinGlide2
  | 6 => -brillouinGlide2
  | 7 => -brillouinTwist2 * brillouinGlide2

/-- Compatibility with the Klein-bottle Brillouin cell: signed orthogonality and
normalization of the twist up to sign. -/
def IsKleinCompatibleWallpaper (S : Mat2Q) : Prop :=
  Matrix.transpose S * S = 1 ∧
    (S * brillouinTwist2 = brillouinTwist2 * S ∨
      S * brillouinTwist2 = -brillouinTwist2 * S)

/-- Every displayed wallpaper point symmetry is Klein-compatible. -/
theorem wallpaperD4_is_klein_compatible (i : Fin 8) :
    IsKleinCompatibleWallpaper (wallpaperD4 i) := by
  fin_cases i
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · left
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · left
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · left
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · left
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · right
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · right
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · right
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
  · constructor
    · ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]
    · right
      ext a b <;> fin_cases a <;> fin_cases b <;>
        norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]

/-- The displayed compatible symmetries preserve the fermionic square of the
Brillouin twist under conjugation/action. -/
theorem wallpaperD4_preserves_twist_square (i : Fin 8) :
    wallpaperD4 i * (brillouinTwist2 * brillouinTwist2) = -(wallpaperD4 i) := by
  fin_cases i <;> ext a b <;> fin_cases a <;> fin_cases b <;>
    norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]

/-- The four rotational elements commute with the twist. -/
theorem wallpaperD4_rotations_commute (i : Fin 4) :
    wallpaperD4 ⟨i.val, by omega⟩ * brillouinTwist2 =
      brillouinTwist2 * wallpaperD4 ⟨i.val, by omega⟩ := by
  fin_cases i <;> ext a b <;> fin_cases a <;> fin_cases b <;>
    norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]

/-- The four reflection/glide elements anticommute with the twist. -/
theorem wallpaperD4_reflections_anticommute (i : Fin 4) :
    wallpaperD4 ⟨i.val + 4, by omega⟩ * brillouinTwist2 =
      -brillouinTwist2 * wallpaperD4 ⟨i.val + 4, by omega⟩ := by
  fin_cases i <;> ext a b <;> fin_cases a <;> fin_cases b <;>
    norm_num [wallpaperD4, brillouinTwist2, brillouinGlide2, Matrix.mul_apply, Fin.sum_univ_two]

/-- A finite classification certificate: an owner can identify any wallpaper
point symmetry satisfying the Klein compatibility predicates with one of the
eight displayed `D₄` elements. -/
structure WallpaperKleinClassificationCertificate where
  candidate : Mat2Q → Prop
  candidate_compatible :
    ∀ S, candidate S → IsKleinCompatibleWallpaper S
  candidate_classified :
    ∀ S, candidate S → ∃ i : Fin 8, S = wallpaperD4 i

namespace WallpaperKleinClassificationCertificate

variable (C : WallpaperKleinClassificationCertificate)

/-- Read out the explicit eight-element classification from the certificate. -/
theorem classified_as_D4 {S : Mat2Q} (hS : C.candidate S) :
    ∃ i : Fin 8, S = wallpaperD4 i :=
  C.candidate_classified S hS

/-- Any classified candidate is compatible with the Klein-bottle cell. -/
theorem classified_is_compatible {S : Mat2Q} (hS : C.candidate S) :
    IsKleinCompatibleWallpaper S :=
  C.candidate_compatible S hS

end WallpaperKleinClassificationCertificate

/-- Five-graded Cartan shadow for the split `O(5,5)`/Pin socket.  The Cartan and
grade-compatibility claims are intentionally explicit predicates. -/
structure Pin55CartanWallpaperSocket where
  cartan : Set Mat10Q
  grade : Fin 5 → Set Mat10Q
  wallpaperAction : Fin 8 → Mat10Q → Mat10Q
  preservesCartan :
    ∀ i : Fin 8, ∀ X : Mat10Q,
      X ∈ cartan → wallpaperAction i X ∈ cartan
  preservesFiveGrade :
    ∀ i : Fin 8, ∀ g : Fin 5, ∀ X : Mat10Q,
      X ∈ grade g → wallpaperAction i X ∈ grade g
  kleinCompatible : ∀ i : Fin 8, IsKleinCompatibleWallpaper (wallpaperD4 i)
  cartan_readout :
    ∀ i : Fin 8, ∀ X : Mat10Q,
      X ∈ cartan → wallpaperAction i X ∈ cartan
  grade_readout :
    ∀ i : Fin 8, ∀ g : Fin 5, ∀ X : Mat10Q,
      X ∈ grade g → wallpaperAction i X ∈ grade g

namespace Pin55CartanWallpaperSocket

/-- The wallpaper `D₄` action preserves the supplied Cartan shadow. -/
theorem preserves_cartan_readout (S : Pin55CartanWallpaperSocket) :
    ∀ i : Fin 8, ∀ X : Mat10Q,
      X ∈ S.cartan → S.wallpaperAction i X ∈ S.cartan :=
  S.cartan_readout

/-- The wallpaper `D₄` action preserves the supplied five-grade decomposition. -/
theorem preserves_five_grade_readout (S : Pin55CartanWallpaperSocket) :
    ∀ i : Fin 8, ∀ g : Fin 5, ∀ X : Mat10Q,
      X ∈ S.grade g → S.wallpaperAction i X ∈ S.grade g :=
  S.grade_readout

/-- Each finite wallpaper point symmetry is Klein-compatible. -/
theorem klein_compatible_readout (S : Pin55CartanWallpaperSocket) (i : Fin 8) :
    IsKleinCompatibleWallpaper (wallpaperD4 i) :=
  S.kleinCompatible i

end Pin55CartanWallpaperSocket

/-- Canonical finite socket using the proved compatibility theorem for the eight
point symmetries; the Cartan/five-grade preservation premises are supplied by
the Pin(5,5) owner. -/
def pin55WallpaperSocketOfPremises
    (cartan : Set Mat10Q) (grade : Fin 5 → Set Mat10Q)
    (wallpaperAction : Fin 8 → Mat10Q → Mat10Q)
    (hCartan :
      ∀ i : Fin 8, ∀ X : Mat10Q,
        X ∈ cartan → wallpaperAction i X ∈ cartan)
    (hGrade :
      ∀ i : Fin 8, ∀ g : Fin 5, ∀ X : Mat10Q,
        X ∈ grade g → wallpaperAction i X ∈ grade g) :
    Pin55CartanWallpaperSocket where
  cartan := cartan
  grade := grade
  wallpaperAction := wallpaperAction
  preservesCartan := hCartan
  preservesFiveGrade := hGrade
  kleinCompatible := wallpaperD4_is_klein_compatible
  cartan_readout := hCartan
  grade_readout := hGrade

end

end InfoGeometry.Canonical.WallpaperKleinBottleCartan
