import InfoGeometry.Thermo.SplitChiralPolarizationBasis
import InfoGeometry.Canonical.WittenParityAnomalyBridge
import InfoGeometry.OperatorAlgebra.FiveGradeClosureSymmetry

/-!
# Witten--Möbius chiral parity index shadow

This file records a small theorem-safe bridge between three existing layers:

* the split chiral idempotents `ePlus`, `eMinus`;
* the Witten parity anomaly-free predicate from `WittenParityAnomalyBridge`;
* the five-graded closure owner `FiveGradeClosureSymmetry`.

Boundary: this is a finite algebraic parity-index shadow.  It does **not** prove
a global Möbius theorem, a full Witten index theorem, a 5-graded super-TKK
closure theorem, or globality of a Delaunay/Rohozhkin/pure-braid construction.
-/

namespace InfoGeometry.Canonical.WittenMoebiusChiralParityIndex

open InfoGeometry.Thermo.SplitChiralPolarizationBasis

/-- Chiral parity index: left idempotent multiplicity minus right idempotent multiplicity. -/
def chiralParityIndex (x : ChiralScalar) : ℝ :=
  leftPart x - rightPart x

@[simp] theorem chiralParityIndex_splitOne :
    chiralParityIndex splitOne = 0 := by
  simp [chiralParityIndex]

/-- The compensated `e₊ + e₋` channel has zero chiral parity index. -/
theorem wittenMoebiusChiralParityIndex_ePlus_eMinus_zero :
    chiralParityIndex (ePlus + eMinus) = 0 := by
  rw [ePlus_add_eMinus]
  exact chiralParityIndex_splitOne

/-- The zero Majorana-count shadow is anomaly-free in the finite Witten parity predicate. -/
theorem anomalyFree_zero :
    WittenParityAnomalyBridge.AnomalyFree 0 := by
  simp [WittenParityAnomalyBridge.AnomalyFree]

/-- One compensated chiral step.  This is multiplication by `e₊+e₋ = 1`. -/
def compensatedStep (x : ChiralScalar) : ChiralScalar :=
  chiralMul (ePlus + eMinus) x

@[simp] theorem compensatedStep_eq_self (x : ChiralScalar) :
    compensatedStep x = x := by
  rw [compensatedStep, ePlus_add_eMinus]
  cases x
  simp [chiralMul, splitOne]

/-- Finite recursion generated by repeated compensated `e₊/e₋` steps. -/
def compensatedRecursion : ℕ → ChiralScalar
  | 0 => splitOne
  | n + 1 => compensatedStep (compensatedRecursion n)

/-- The compensated recursion stays globally balanced at every finite stage. -/
theorem compensatedRecursion_eq_splitOne (n : ℕ) :
    compensatedRecursion n = splitOne := by
  induction n with
  | zero => rfl
  | succ n ih =>
      simp [compensatedRecursion, ih]

/-- The finite compensated recursion has zero chiral parity index at every stage. -/
theorem compensatedRecursion_chiralParityIndex_zero (n : ℕ) :
    chiralParityIndex (compensatedRecursion n) = 0 := by
  rw [compensatedRecursion_eq_splitOne]
  exact chiralParityIndex_splitOne

/-- A five-graded closure system can be paired with the finite compensated parity shadow.

The `fiveGrade` field keeps the actual five-graded closure owner explicit; this
structure does not derive it from the parity index. -/
structure FiveGradedCompensatedParityShadow
    (L : Type*) [AddCommGroup L] [Module ℝ L] where
  fiveGrade : InfoGeometry.OperatorAlgebra.FiveGradeClosureSymmetry L
  parityStage : ℕ

namespace FiveGradedCompensatedParityShadow

variable {L : Type*} [AddCommGroup L] [Module ℝ L]

/-- Readout: the attached compensated parity recursion has zero index. -/
theorem parity_index_zero (S : FiveGradedCompensatedParityShadow L) :
    chiralParityIndex (compensatedRecursion S.parityStage) = 0 :=
  compensatedRecursion_chiralParityIndex_zero S.parityStage

/-- Readout: the grade-zero sector remains setwise stable because the five-graded
owner already supplies that theorem. -/
theorem grade_zero_setwise_stable (S : FiveGradedCompensatedParityShadow L) :
    S.fiveGrade.closure.SetwiseStable S.fiveGrade.gZero :=
  S.fiveGrade.zero_setwise_stable

end FiveGradedCompensatedParityShadow

/-- The compact bridge packet: zero finite Witten anomaly shadow plus zero
compensated chiral parity index at every finite recursive stage. -/
theorem witten_moebius_chiral_parity_packet :
    WittenParityAnomalyBridge.AnomalyFree 0 ∧
      ∀ n : ℕ, chiralParityIndex (compensatedRecursion n) = 0 :=
  ⟨anomalyFree_zero, compensatedRecursion_chiralParityIndex_zero⟩

end InfoGeometry.Canonical.WittenMoebiusChiralParityIndex
