import InfoGeometry.Canonical.KMSSinkhornWeightedTransport
import InfoGeometry.Volume.ConnesCocycle
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.SpecialFunctions.Exponential
set_option linter.unnecessarySimpa false

/-!
# InfoGeometry.Canonical.YangMillsContinuum

Continuum-facing modular/inference bridge interfaces built on the canonical
Krein and IB layers.

This module formalizes:
- modular operator as a Radon-Nikodym-style relative density,
- modular Hamiltonian as negative logarithmic relative density,
- real-parameter modular automorphism flow,
- sampled IB-to-modular KMS bridge theorems.
-/

namespace InfoGeometry.Canonical.YangMillsContinuum

open InfoGeometry.Canonical.KMSSinkhornBridge
open InfoGeometry.Canonical.IB

/-- Doubled-space endomorphisms used in the continuum Yang-Mills bridge. -/
abbrev EndH (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] : Type _ :=
  AlgebraEnd (E := E)

/-- Identity endomorphism on doubled space. -/
noncomputable def idEndH
    (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] :
    EndH E :=
  ContinuousLinearMap.id ℝ (InfoGeometry.Krein.DoubledSpace E)

/--
Modular Radon-Nikodym data:
- `rnDerivative` represents `dμ/dν` and is strictly positive.

All operator-level objects are derived in namespace theorems/definitions from
this primitive scalar datum.
-/
structure ModularRadonNikodymData
    (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] where
  rnDerivative : ℝ
  rnDerivative_pos : 0 < rnDerivative

namespace ModularRadonNikodymData

variable {E : Type}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

noncomputable local instance : NormedRing (EndH E) := inferInstance
noncomputable local instance : NormedAlgebra ℝ (EndH E) := inferInstance
local instance : IsTopologicalRing (EndH E) := inferInstance
local instance : CompleteSpace (EndH E) := inferInstance

/-! ### Derived modular objects from primitive RN data -/

/-- Derived modular operator identified with the RN derivative. -/
noncomputable def modularOperator
    (M : ModularRadonNikodymData E) : EndH E :=
  M.rnDerivative • idEndH E

/-- Derived modular Hamiltonian identified with `-log(dμ/dν)`. -/
noncomputable def modularHamiltonian
    (M : ModularRadonNikodymData E) : EndH E :=
  (-Real.log M.rnDerivative) • idEndH E

/-- Operator commutator `[K, A] = K A - A K`. -/
def commutator (K A : EndH E) : EndH E :=
  K * A - A * K

@[simp] lemma modularOperator_eq_rn
    (M : ModularRadonNikodymData E) :
    M.modularOperator = M.rnDerivative • idEndH E := rfl

@[simp] lemma modularHamiltonian_eq_neg_log_rn
    (M : ModularRadonNikodymData E) :
    M.modularHamiltonian = (-Real.log M.rnDerivative) • idEndH E := rfl

@[simp] lemma modularOperator_apply
    (M : ModularRadonNikodymData E)
    (v : InfoGeometry.Krein.DoubledSpace E) :
    M.modularOperator v = M.rnDerivative • v := by
  simp [modularOperator, idEndH]

@[simp] lemma modularHamiltonian_apply
    (M : ModularRadonNikodymData E)
    (v : InfoGeometry.Krein.DoubledSpace E) :
    M.modularHamiltonian v = (-Real.log M.rnDerivative) • v := by
  simp [modularHamiltonian, idEndH]

/--
Real-parameter modular automorphism group generated by the modular Hamiltonian.
-/
noncomputable def modularAutomorphismGroup
    (M : ModularRadonNikodymData E) :
    ℝ → EndH E → EndH E :=
  fun t A => modularShift (E := E) M.modularHamiltonian t A

@[simp] lemma modularAutomorphismGroup_zero
    (M : ModularRadonNikodymData E)
    (A : EndH E) :
    modularAutomorphismGroup M 0 A = A := by
  simpa [modularAutomorphismGroup] using
    (InfoGeometry.Krein.modular_shift_zero
      (E := E) M.modularHamiltonian A)

/--
Infinitesimal generator identity at the origin:
\[
  \frac{d}{dτ}\Big|_{τ=0}\, \big(e^{τK} A e^{-τK}\big) = [K, A].
\]
-/
theorem hasDerivAt_modularShift_zero_eq_commutator
    (K A : EndH E) :
    HasDerivAt (fun τ : ℝ => modularShift (E := E) K τ A) (commutator K A) 0 := by
  have hExpL : HasDerivAt (fun τ : ℝ => NormedSpace.exp (τ • K)) K 0 := by
    simpa using (hasDerivAt_exp_smul_const (x := K) (t := (0 : ℝ)))
  have hExpR : HasDerivAt (fun τ : ℝ => NormedSpace.exp ((-τ) • K)) (-K) 0 := by
    simpa [neg_smul] using (hasDerivAt_exp_smul_const (x := -K) (t := (0 : ℝ)))
  have hProd :
      HasDerivAt
        (fun τ : ℝ =>
          (NormedSpace.exp (τ • K) * A) * NormedSpace.exp ((-τ) • K))
        (((K * A) * NormedSpace.exp ((-(0 : ℝ)) • K)) +
          ((NormedSpace.exp (0 • K) * A) * (-K)))
        0 := by
    simpa [mul_assoc] using (hExpL.mul_const A).mul hExpR
  simpa [commutator, modularShift, InfoGeometry.Krein.modular_shift,
    InfoGeometry.Krein.krein_modular_shift, sub_eq_add_neg, mul_assoc] using hProd

/-- Scalar derivative corollary of `hasDerivAt_modularShift_zero_eq_commutator`. -/
theorem deriv_modularShift_zero_eq_commutator
    (K A : EndH E) :
    deriv (fun τ : ℝ => modularShift (E := E) K τ A) 0 = commutator K A :=
  (hasDerivAt_modularShift_zero_eq_commutator (K := K) (A := A)).deriv

/--
Derived additive-time law for the modular automorphism group:
`σ_{s+t} = σ_s ∘ σ_t`.
-/
lemma modularAutomorphismGroup_add
    (M : ModularRadonNikodymData E)
    (s t : ℝ) (A : EndH E) :
    modularAutomorphismGroup M (s + t) A =
      modularAutomorphismGroup M s (modularAutomorphismGroup M t A) := by
  simpa [modularAutomorphismGroup] using
    (InfoGeometry.Krein.modular_shift_add
      (E := E) M.modularHamiltonian s t A)

/--
Additive-time law for modular automorphisms, stated directly as a theorem:
`σ_{s+t} = σ_s ∘ σ_t`.
-/
theorem modularAutomorphismGroup_additive
    (M : ModularRadonNikodymData E) :
    ∀ s t : ℝ, ∀ A : EndH E,
      modularAutomorphismGroup M (s + t) A =
        modularAutomorphismGroup M s (modularAutomorphismGroup M t A) := by
  intro s t A
  exact modularAutomorphismGroup_add (M := M) s t A

/--
Infinitesimal modular-flow generator at the origin:
the derivative of `σ_τ(A)` at `τ = 0` is the commutator with the modular Hamiltonian.
-/
theorem hasDerivAt_modularAutomorphismGroup_zero_eq_commutator
    (M : ModularRadonNikodymData E) (A : EndH E) :
    HasDerivAt (fun τ : ℝ => modularAutomorphismGroup M τ A)
      (commutator M.modularHamiltonian A) 0 := by
  simpa [modularAutomorphismGroup] using
    (hasDerivAt_modularShift_zero_eq_commutator
      (K := M.modularHamiltonian) (A := A))

/-- Scalar derivative corollary for the modular automorphism group at `τ = 0`. -/
theorem deriv_modularAutomorphismGroup_zero_eq_commutator
    (M : ModularRadonNikodymData E) (A : EndH E) :
    deriv (fun τ : ℝ => modularAutomorphismGroup M τ A) 0
      = commutator M.modularHamiltonian A :=
  (hasDerivAt_modularAutomorphismGroup_zero_eq_commutator (M := M) (A := A)).deriv

/--
Connes-Rovelli thermal-time identity (operator form):
identifying thermal parameters identifies modular evolution.
-/
theorem modularAutomorphismGroup_eq_of_time_eq
    (M : ModularRadonNikodymData E)
    {τ t : ℝ} (hτt : τ = t) (A : EndH E) :
    modularAutomorphismGroup M τ A = modularAutomorphismGroup M t A := by
  simp [hτt]

/--
Facade proposition for thermal-time interpretation:
equal thermal parameters yield equal modular automorphism action.
-/
def ConnesRovelliThermalTimeIdentity
    (M : ModularRadonNikodymData E) : Prop :=
  ∀ (τ t : ℝ) (A : EndH E), τ = t →
    modularAutomorphismGroup M τ A = modularAutomorphismGroup M t A

/--
Canonical proof of the Connes-Rovelli thermal-time identity.
-/
theorem connesRovelliThermalTimeIdentity
    (M : ModularRadonNikodymData E) :
    ConnesRovelliThermalTimeIdentity M := by
  intro τ t A hτt
  exact modularAutomorphismGroup_eq_of_time_eq (M := M) hτt A

/--
Canonical additive-time automorphism-group package attached to the modular
Hamiltonian.
-/
noncomputable def toAdditiveModularFlow
    (M : ModularRadonNikodymData E) :
    InfoGeometry.Volume.ConnesCocycle.AdditiveModularFlow (H := E) :=
  InfoGeometry.Volume.ConnesCocycle.additiveModularFlowOfGenerator
    (H := E) M.modularHamiltonian

@[simp] theorem toAdditiveModularFlow_apply
    (M : ModularRadonNikodymData E) (t : ℝ) (A : EndH E) :
    M.toAdditiveModularFlow t A = modularAutomorphismGroup M t A := rfl

/--
Formal Type III modular interface extracted from primitive RN data.

This packages the operator dictionary (`Δ`, `K`) together with the additive
flow law and infinitesimal commutator generator into a single canonical object.
-/
structure TypeIIIModularInterface
    (M : ModularRadonNikodymData E) : Prop where
  modularOperator_eq_rn :
    M.modularOperator = M.rnDerivative • idEndH E
  modularHamiltonian_eq_neg_log_rn :
    M.modularHamiltonian = (-Real.log M.rnDerivative) • idEndH E
  modularAutomorphismGroup_additive :
    ∀ s t : ℝ, ∀ A : EndH E,
      modularAutomorphismGroup M (s + t) A =
        modularAutomorphismGroup M s (modularAutomorphismGroup M t A)
  infinitesimal_generator_at_zero :
    ∀ A : EndH E,
      HasDerivAt (fun τ : ℝ => modularAutomorphismGroup M τ A)
        (commutator M.modularHamiltonian A) 0

/-- Canonical Type III modular interface, internalized from RN primitives. -/
theorem typeIIIModularInterface
    (M : ModularRadonNikodymData E) :
    TypeIIIModularInterface (E := E) M := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact modularOperator_eq_rn (M := M)
  · exact modularHamiltonian_eq_neg_log_rn (M := M)
  · exact modularAutomorphismGroup_additive (M := M)
  · exact hasDerivAt_modularAutomorphismGroup_zero_eq_commutator (M := M)

end ModularRadonNikodymData

/--
Sampled IB trajectory carrying a discrete-time inference flow together with a
real-time sampling map.
-/
structure IBSampledFlow
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib)) where
  pTrajectory : Nat → Xib → FinProb Tib
  step :
    ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k)
  sampleTime : Nat → ℝ

namespace IBSampledFlow

variable {E : Type}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
variable {n : Nat}
variable {Xib Yib Tib : Type}
variable [Fintype Xib] [Fintype Yib] [Fintype Tib]
variable [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
variable [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
variable [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
variable {prob : IBProblem (X := Xib) (Y := Yib)}

/--
Component-form sampled observable from a raw IB trajectory.
-/
noncomputable def sampledObservableOfTrajectory
    (pTrajectory : Nat → Xib → FinProb Tib)
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E) :
    Nat → EndH E →L[ℝ] ℝ :=
  ibInducedObservableWeighted
    (F := E) (Xib := Xib) (Yib := Yib) (Tib := Tib)
    pTrajectory x0 t0 (omegaSeed (F := E) Ω)

/--
Component-form theorem: sampled IB recursion implies Sinkhorn-KMS control for
the weighted expectation observable.
-/
theorem sinkhornControl_of_sampledIB_components
    (T : InfoGeometry.Canonical.MoE.SinkhornTrajectory n)
    (K : EndH E)
    (β : ℝ)
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := E) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := E) Ω) :
    SinkhornKMSControl n T K
      (sampledObservableOfTrajectory
        (E := E) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 Ω) β := by
  simpa [sampledObservableOfTrajectory] using
    (sinkhorn_kmsControl_of_ibDynamics_weighted_from_jointKernel_commutator
      (n := n) (T := T) (K := K) (β := β)
      (prob := prob) (pTrajectory := pTrajectory)
      (hStep := hStep) (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal)

/--
Component-form theorem: sampled IB recursion implies exact stepwise KMS
closure.
-/
theorem sinkhornClosure_of_sampledIB_components
    (T : InfoGeometry.Canonical.MoE.SinkhornTrajectory n)
    (K : EndH E)
    (β : ℝ)
    (pTrajectory : Nat → Xib → FinProb Tib)
    (hStep : ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := E) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := E) Ω) :
    SinkhornKMSClosure n T K
      (sampledObservableOfTrajectory
        (E := E) (Xib := Xib) (Yib := Yib) (Tib := Tib)
        pTrajectory x0 t0 Ω) β := by
  exact sinkhorn_step_kmsClosure_of_control
    (n := n) (T := T) (K := K)
    (ω := sampledObservableOfTrajectory
      (E := E) (Xib := Xib) (Yib := Yib) (Tib := Tib)
      pTrajectory x0 t0 Ω)
    (β := β)
    (sinkhornControl_of_sampledIB_components
      (n := n)
      (T := T) (K := K) (β := β)
      (pTrajectory := pTrajectory) (hStep := hStep)
      (x0 := x0) (t0 := t0) (Ω := Ω) hΩ hJointKernel hCommOrthogonal)

/-- Canonical weighted observable sampled from an IB trajectory. -/
noncomputable def sampledObservable
    (S : IBSampledFlow (Xib := Xib) (Yib := Yib) (Tib := Tib) (prob := prob))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E) :
    Nat → EndH E →L[ℝ] ℝ :=
  ibInducedObservableWeighted
    (F := E) (Xib := Xib) (Yib := Yib) (Tib := Tib)
    S.pTrajectory x0 t0 (omegaSeed (F := E) Ω)

/--
Sampled IB dynamics induce Sinkhorn-KMS control for the weighted expectation
observable.
-/
theorem sinkhornControl_of_sampledIB
    (T : InfoGeometry.Canonical.MoE.SinkhornTrajectory n)
    (K : EndH E)
    (β : ℝ)
    (S : IBSampledFlow (Xib := Xib) (Yib := Yib) (Tib := Tib) (prob := prob))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := E) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := E) Ω) :
    SinkhornKMSControl n T K
      (sampledObservable (prob := prob) S x0 t0 Ω) β := by
  simpa [sampledObservable] using
    (sinkhorn_kmsControl_of_ibDynamics_weighted_from_jointKernel_commutator
      (n := n) (T := T) (K := K) (β := β)
      (prob := prob) (pTrajectory := S.pTrajectory)
      (hStep := S.step) (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hJointKernel hCommOrthogonal)

/--
Sampled IB dynamics induce exact stepwise KMS closure.
-/
theorem sinkhornClosure_of_sampledIB
    (T : InfoGeometry.Canonical.MoE.SinkhornTrajectory n)
    (K : EndH E)
    (β : ℝ)
    (S : IBSampledFlow (Xib := Xib) (Yib := Yib) (Tib := Tib) (prob := prob))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E)
    (hΩ : Ω ≠ 0)
    (hJointKernel : JointKernelOnOmega (F := E) K β Ω)
    (hCommOrthogonal : CommutatorOrthogonalOnOmega (F := E) Ω) :
    SinkhornKMSClosure n T K
      (sampledObservable (prob := prob) S x0 t0 Ω) β := by
  exact sinkhorn_step_kmsClosure_of_control
    (n := n) (T := T) (K := K)
    (ω := sampledObservable (prob := prob) S x0 t0 Ω)
    (β := β)
    (sinkhornControl_of_sampledIB
      (n := n) (prob := prob)
      (T := T) (K := K) (β := β) (S := S)
      (x0 := x0) (t0 := t0) (Ω := Ω) hΩ hJointKernel hCommOrthogonal)

end IBSampledFlow

end InfoGeometry.Canonical.YangMillsContinuum
