import InfoGeometry.Canonical.KMSSinkhornBridge

/-!
# InfoGeometry.Canonical.YangMillsContinuum

Continuum-facing modular/inference bridge interfaces built on the canonical
Krein and IB layers.

This module formalizes:
- modular operator as a Radon-Nikodym-style relative density,
- modular Hamiltonian as negative logarithmic relative density,
- real-parameter modular automorphism flow,
- sampled IB-to-modular KMS bridge theorems.
-/

namespace InfoGeometry.Canonical.YangMillsContinuum

open InfoGeometry.Canonical.KMSSinkhornBridge
open InfoGeometry.Canonical.IB

/-- Doubled-space endomorphisms used in the continuum Yang-Mills bridge. -/
abbrev EndH (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] : Type _ :=
  AlgebraEnd (E := E)

/-- Identity endomorphism on doubled space. -/
noncomputable def idEndH
    (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] :
    EndH E :=
  ContinuousLinearMap.id ℝ (InfoGeometry.Krein.DoubledSpace E)

/--
Modular Radon-Nikodym data:
- `rnDerivative` represents `dμ/dν` and is strictly positive.

All operator-level objects are derived in namespace theorems/definitions from
this primitive scalar datum.
-/
structure ModularRadonNikodymData
    (E : Type) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E] where
  rnDerivative : ℝ
  rnDerivative_pos : 0 < rnDerivative

namespace ModularRadonNikodymData

variable {E : Type}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

noncomputable local instance : NormedRing (EndH E) := inferInstance
noncomputable local instance : NormedAlgebra ℝ (EndH E) := inferInstance
local instance : IsTopologicalRing (EndH E) := inferInstance
local instance : CompleteSpace (EndH E) := inferInstance

/-! ### Derived modular objects from primitive RN data -/

/-- Derived modular operator identified with the RN derivative. -/
noncomputable def modularOperator
    (M : ModularRadonNikodymData E) : EndH E :=
  M.rnDerivative • idEndH E

/-- Derived modular Hamiltonian identified with `-log(dμ/dν)`. -/
noncomputable def modularHamiltonian
    (M : ModularRadonNikodymData E) : EndH E :=
  (-Real.log M.rnDerivative) • idEndH E

@[simp] lemma modularOperator_eq_rn
    (M : ModularRadonNikodymData E) :
    M.modularOperator = M.rnDerivative • idEndH E := rfl

@[simp] lemma modularHamiltonian_eq_neg_log_rn
    (M : ModularRadonNikodymData E) :
    M.modularHamiltonian = (-Real.log M.rnDerivative) • idEndH E := rfl

@[simp] lemma modularOperator_apply
    (M : ModularRadonNikodymData E)
    (v : InfoGeometry.Krein.DoubledSpace E) :
    M.modularOperator v = M.rnDerivative • v := by
  simp [modularOperator, idEndH]

@[simp] lemma modularHamiltonian_apply
    (M : ModularRadonNikodymData E)
    (v : InfoGeometry.Krein.DoubledSpace E) :
    M.modularHamiltonian v = (-Real.log M.rnDerivative) • v := by
  simp [modularHamiltonian, idEndH]

/--
Real-parameter modular automorphism group generated by the modular Hamiltonian.
-/
noncomputable def modularAutomorphismGroup
    (M : ModularRadonNikodymData E) :
    ℝ → EndH E → EndH E :=
  fun t A => modularShift (E := E) M.modularHamiltonian t A

@[simp] lemma modularAutomorphismGroup_zero
    (M : ModularRadonNikodymData E)
    (A : EndH E) :
    modularAutomorphismGroup M 0 A = A := by
  simp [modularAutomorphismGroup, modularShift, InfoGeometry.Krein.modular_shift]

/--
Derived additive-time law for the modular automorphism group:
`σ_{s+t} = σ_s ∘ σ_t`.
-/
lemma modularAutomorphismGroup_add
    (M : ModularRadonNikodymData E)
    (s t : ℝ) (A : EndH E) :
    modularAutomorphismGroup M (s + t) A =
      modularAutomorphismGroup M s (modularAutomorphismGroup M t A) := by
  let K : EndH E := M.modularHamiltonian
  have h_comm : Commute (s • K) (t • K) :=
    ((Commute.refl K).smul_left s).smul_right t
  have h_comm_neg : Commute ((-t) • K) ((-s) • K) :=
    ((Commute.refl K).smul_left (-t)).smul_right (-s)
  unfold modularAutomorphismGroup modularShift InfoGeometry.Krein.modular_shift
  change
    NormedSpace.exp ((s + t) • K) * A * NormedSpace.exp ((-(s + t)) • K) =
      NormedSpace.exp (s • K) *
          (NormedSpace.exp (t • K) * A * NormedSpace.exp ((-t) • K)) *
        NormedSpace.exp ((-s) • K)
  calc
    NormedSpace.exp ((s + t) • K) * A * NormedSpace.exp ((-(s + t)) • K)
        = (NormedSpace.exp (s • K) * NormedSpace.exp (t • K)) * A *
            (NormedSpace.exp ((-t) • K) * NormedSpace.exp ((-s) • K)) := by
          rw [← NormedSpace.exp_add_of_commute h_comm]
          rw [← NormedSpace.exp_add_of_commute h_comm_neg]
          simp [K, add_smul, mul_assoc, add_comm]
    _ = NormedSpace.exp (s • K) *
          (NormedSpace.exp (t • K) * A * NormedSpace.exp ((-t) • K)) *
        NormedSpace.exp ((-s) • K) := by
          ring_nf
          simp [mul_assoc]

/--
Flow law interface for additive-time modular automorphisms.
This is the continuum group-law contract for `σ_{s+t} = σ_s ∘ σ_t`.
-/
structure AutomorphismFlowLaw (M : ModularRadonNikodymData E) : Prop where
  add :
    ∀ s t : ℝ, ∀ A : EndH E,
      modularAutomorphismGroup M (s + t) A =
        modularAutomorphismGroup M s (modularAutomorphismGroup M t A)

/-- Compatibility constructor: the flow-law interface is derivable from modular data. -/
theorem automorphismFlowLaw_of_modularRadonNikodymData
    (M : ModularRadonNikodymData E) :
    AutomorphismFlowLaw M := by
  refine ⟨?_⟩
  intro s t A
  exact modularAutomorphismGroup_add (M := M) s t A

end ModularRadonNikodymData

/--
Sampled IB trajectory carrying a discrete-time inference flow together with a
real-time sampling map.
-/
structure IBSampledFlow
    {Xib Yib Tib : Type}
    [Fintype Xib] [Fintype Yib] [Fintype Tib]
    [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
    [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
    [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
    (prob : IBProblem (X := Xib) (Y := Yib)) where
  pTrajectory : Nat → Xib → FinProb Tib
  step :
    ∀ k : Nat, pTrajectory (k + 1) = ibBlahutArimotoStep prob (pTrajectory k)
  sampleTime : Nat → ℝ

namespace IBSampledFlow

variable {E : Type}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
variable {n : Nat}
variable {Xib Yib Tib : Type}
variable [Fintype Xib] [Fintype Yib] [Fintype Tib]
variable [MeasurableSpace Xib] [MeasurableSingletonClass Xib]
variable [MeasurableSpace Yib] [MeasurableSingletonClass Yib]
variable [MeasurableSpace Tib] [MeasurableSingletonClass Tib]
variable {prob : IBProblem (X := Xib) (Y := Yib)}

/-- Canonical weighted observable sampled from an IB trajectory. -/
noncomputable def sampledObservable
    (S : IBSampledFlow (Xib := Xib) (Yib := Yib) (Tib := Tib) (prob := prob))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E) :
    Nat → EndH E →L[ℝ] ℝ :=
  ibInducedObservableWeighted
    (F := E) (Xib := Xib) (Yib := Yib) (Tib := Tib)
    S.pTrajectory x0 t0 (omegaSeed (F := E) Ω)

/--
Sampled IB dynamics induce Sinkhorn-KMS control for the weighted expectation
observable.
-/
theorem sinkhornControl_of_sampledIB
    (T : InfoGeometry.Canonical.MoE.SinkhornTrajectory n)
    (K : EndH E)
    (β : ℝ)
    (S : IBSampledFlow (Xib := Xib) (Yib := Yib) (Tib := Tib) (prob := prob))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E)
    (hΩ : Ω ≠ 0)
    (hStruct : ExpectationSeedKMSHypotheses (F := E) K β Ω) :
    SinkhornKMSControl n T K
      (sampledObservable (prob := prob) S x0 t0 Ω) β := by
  simpa [sampledObservable] using
    (sinkhorn_kmsControl_of_ibDynamics_weighted_from_expectationSeed
      (n := n) (T := T) (K := K) (β := β)
      (prob := prob) (pTrajectory := S.pTrajectory)
      (hStep := S.step) (x0 := x0) (t0 := t0)
      (Ω := Ω) hΩ hStruct)

/--
Sampled IB dynamics induce exact stepwise KMS closure.
-/
theorem sinkhornClosure_of_sampledIB
    (T : InfoGeometry.Canonical.MoE.SinkhornTrajectory n)
    (K : EndH E)
    (β : ℝ)
    (S : IBSampledFlow (Xib := Xib) (Yib := Yib) (Tib := Tib) (prob := prob))
    (x0 : Xib) (t0 : Tib)
    (Ω : InfoGeometry.Krein.DoubledSpace E)
    (hΩ : Ω ≠ 0)
    (hStruct : ExpectationSeedKMSHypotheses (F := E) K β Ω) :
    SinkhornKMSClosure n T K
      (sampledObservable (prob := prob) S x0 t0 Ω) β := by
  exact sinkhorn_step_kmsClosure_of_control
    (n := n) (T := T) (K := K)
    (ω := sampledObservable (prob := prob) S x0 t0 Ω)
    (β := β)
    (sinkhornControl_of_sampledIB
      (n := n) (prob := prob)
      (T := T) (K := K) (β := β) (S := S)
      (x0 := x0) (t0 := t0) (Ω := Ω) hΩ hStruct)

end IBSampledFlow

end InfoGeometry.Canonical.YangMillsContinuum
