import Mathlib.Analysis.Complex.Basic
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.NormedSpace.Basic
import Mathlib.Algebra.Module.Basic
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Tactic

/-!
# ZornDerivationExponentialAutomorphism

Generic proof that the exponential of a derivation on a finite-dimensional
non-associative algebra is an algebra automorphism.

This is the missing generic Lean owner for the canonical Zorn derivation space.
-/

import Mathlib.Analysis.Complex.Basic
import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.NormedSpace.Basic
import Mathlib.Algebra.Module.Basic
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Tactic

noncomputable section

open ContinuousLinearMap

namespace ZornDerivationExponentialAutomorphism

variable {R : Type*} [Field R] [NormedField R] [CompleteSpace R]
variable {A : Type*} [NormedAddCommGroup A] [Algebra R A] [CompleteSpace A]

/-- A derivation on a non-associative algebra A -/
structure Derivation (A : Type*) [NormedAddCommGroup A] [Algebra R A] [CompleteSpace A] where
  toLinearMap : A →L[R] A
  leibniz : ∀ (x y : A), toLinearMap (x * y) = toLinearMap x * y + x * toLinearMap y

/-- The flow U(t) = exp(tD) generated by a derivation D -/
def flow (D : Derivation A) (t : R) : A →L[R] A :=
  (D.toLinearMap).exp.map (t • (1 : A →L[R] A))

/-- THEOREM: The flow of a derivation is an algebra automorphism.
    exp(tD)(x * y) = exp(tD)(x) * exp(tD)(y) -/
theorem flow_is_automorphism (D : Derivation A) (t : R) (x y : A) :
    (flow D t) (x * y) = (flow D t) x * (flow D t) y := by
  have h₁ : flow D t = (D.toLinearMap).exp.map (t • (1 : A →L[R] A)) := rfl
  rw [h₁]
  -- Use the formal power series to prove the result
  have h₂ : ((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) (x * y) =
      (((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) x) * (((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) y) := by
    -- Use the property that exp(tD) preserves the product for a derivation D
    have h₃ : ∀ (n : ℕ), ((D.toLinearMap) ^ n) (x * y) = ∑ k in Finset.range (n + 1), ((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y) := by
      intro n
      induction n with
      | zero => simp [LinearMap.one_apply]
      | succ n ih =>
        rw [Function.iterate_succ_apply']
        rw [ih]
        have h₄ := D.leibniz _ _
        simp [Function.iterate_succ_apply', Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul] at h₄ ⊢
        <;> abel_nf at h₄ ⊢ <;>
        (try ring_nf at h₄ ⊢) <;>
        (try simp_all [Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul]) <;>
        (try
          {
            apply Eq.symm
            apply Finset.sum_bij' (fun i _ => n - i) (fun i _ => n - i)
            <;> simp_all [Finset.mem_range, Nat.lt_succ_iff]
            <;> omega
          }) <;>
        (try
          {
            rw [Finset.sum_range_succ, add_comm]
            <;> simp_all [Function.iterate_succ_apply', Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul]
            <;> ring_nf at * <;> abel_nf at * <;> aesop
          })
    -- Use the formal power series to prove the result
    have h₄ : ((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) (x * y) =
        (((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) x) * (((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) y) := by
      -- Use the formal power series of exp(tD)
      have h₅ : ((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) (x * y) =
          ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
        simp [LinearMap.exp_apply, smul_smul]
        <;> congr 1 <;> ext <;> simp [ContinuousLinearMap.comp_apply, smul_smul]
        <;> congr 1 <;> ext <;> simp [ContinuousLinearMap.comp_apply, smul_smul]
      rw [h₅]
      have h₆ : (((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) x) * (((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) y) =
          (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) := by
        simp [LinearMap.exp_apply, smul_smul]
        <;> congr 1 <;> ext <;> simp [ContinuousLinearMap.comp_apply, smul_smul]
        <;> congr 1 <;> ext <;> simp [ContinuousLinearMap.comp_apply, smul_smul]
      rw [h₆]
      -- Use the Cauchy product formula and the Leibniz rule
      have h₇ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
          ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
        -- Use the Leibniz rule and the Cauchy product formula
        have h₈ : ∀ n : ℕ, ((D.toLinearMap) ^ n) (x * y) = ∑ k in Finset.range (n + 1), ((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y) := by
          intro n
          induction n with
          | zero => simp [LinearMap.one_apply]
          | succ n ih =>
            rw [Function.iterate_succ_apply']
            rw [ih]
            have h₅ := D.leibniz _ _
            simp [Function.iterate_succ_apply', Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul] at h₅ ⊢
            <;> abel_nf at h₅ ⊢ <;>
            (try ring_nf at h₅ ⊢) <;>
            (try simp_all [Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul]) <;>
            (try
              {
                apply Eq.symm
                apply Finset.sum_bij' (fun i _ => n - i) (fun i _ => n - i)
                <;> simp_all [Finset.mem_range, Nat.lt_succ_iff]
                <;> omega
              }) <;>
            (try
              {
                rw [Finset.sum_range_succ, add_comm]
                <;> simp_all [Function.iterate_succ_apply', Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul]
                <;> ring_nf at * <;> abel_nf at * <;> aesop
              })
        -- Use the formal power series to prove the result
        have h₉ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
            ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
          -- This follows from the Leibniz rule and the Cauchy product formula
          have h₁₀ : ∀ n : ℕ, ((D.toLinearMap) ^ n) (x * y) = ∑ k in Finset.range (n + 1), ((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y) := by
            intro n
            exact (fun n => ∀ (x y : A), ((D.toLinearMap) ^ n) (x * y) = ∑ k in Finset.range (n + 1), ((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) n x y
          -- The proof uses the binomial theorem and the Leibniz rule
          have h₁₁ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
              ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
            -- This is a standard result in the theory of formal power series for derivations
            -- The key is that the product of the series equals the series of the product
            -- due to the Leibniz rule D(xy) = D(x)y + xD(y)
            classical
            have h₁₂ : Summable (fun n : ℕ => (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) := by
              -- The exponential series is summable
              have h₁₂ : Summable (fun n : ℕ => (t ^ n / n.factorial : R) : ℕ → R) := by
                exact summable_pow_div_factorial (t : R)
              -- The linear map is continuous, so the series is summable
              have h₁₃ : Summable (fun n : ℕ => (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) := by
                refine' Summable.of_norm _
                have h₁₄ : ∀ n : ℕ, ‖((t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x : A)‖ ≤ ‖(D.toLinearMap)‖ ^ n * ‖x‖ * (t ^ n / n.factorial : R) := by
                  intro n
                  calc
                    ‖((t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x : A)‖ = (t ^ n / n.factorial : R) * ‖((D.toLinearMap) ^ n) x‖ := by
                      simp [norm_smul, Real.norm_eq_abs, abs_of_nonneg (by positivity : (0 : R) ≤ t ^ n / n.factorial)]
                    _ ≤ (t ^ n / n.factorial : R) * (‖(D.toLinearMap)‖ ^ n * ‖x‖) := by
                      gcongr
                      <;> simp [ContinuousLinearMap.iterate_norm]
                    _ = ‖(D.toLinearMap)‖ ^ n * ‖x‖ * (t ^ n / n.factorial : R) := by ring
                have h₁₅ : Summable (fun n : ℕ => (‖(D.toLinearMap)‖ : R) ^ n * ‖x‖ * (t ^ n / n.factorial : R)) := by
                  have h₁₆ : Summable (fun n : ℕ => (‖(D.toLinearMap)‖ : R) ^ n * (t ^ n / n.factorial : R)) := by
                    have h₁₇ : Summable (fun n : ℕ => ((‖(D.toLinearMap)‖ * t : R) ^ n / n.factorial : R)) := by
                      exact summable_pow_div_factorial (‖(D.toLinearMap)‖ * t : R)
                    convert h₁₇ using 1
                    <;> ext n <;> ring_nf
                    <;> field_simp [Nat.factorial]
                    <;> ring_nf
                  exact Summable.mul_left (‖x‖ : R) h₁₆
                exact Summable.of_nonneg_of_le (fun n _ => by positivity) h₁₄ h₁₅
            exact h₁₃
          have h₁₉ : Summable (fun m : ℕ => (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) := by
            -- Same as above
            have h₂₀ : Summable (fun m : ℕ => (t ^ m / m.factorial : R) : ℕ → R) := by
              exact summable_pow_div_factorial (t : R)
            have h₂₁ : Summable (fun m : ℕ => (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) := by
              refine' Summable.of_norm _
              have h₂₂ : ∀ m : ℕ, ‖((t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y : A)‖ ≤ ‖(D.toLinearMap)‖ ^ m * ‖y‖ * (t ^ m / m.factorial : R) := by
                intro m
                calc
                  ‖((t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y : A)‖ = (t ^ m / m.factorial : R) * ‖((D.toLinearMap) ^ m) y‖ := by
                    simp [norm_smul, Real.norm_eq_abs, abs_of_nonneg (by positivity : (0 : R) ≤ t ^ m / m.factorial)]
                  _ ≤ (t ^ m / m.factorial : R) * (‖(D.toLinearMap)‖ ^ m * ‖y‖) := by
                    gcongr
                    <;> simp [ContinuousLinearMap.iterate_norm]
                  _ = ‖(D.toLinearMap)‖ ^ m * ‖y‖ * (t ^ m / m.factorial : R) := by ring
              have h₂₃ : Summable (fun m : ℕ => (‖(D.toLinearMap)‖ : R) ^ m * ‖y‖ * (t ^ m / m.factorial : R)) := by
                have h₂₄ : Summable (fun m : ℕ => (‖(D.toLinearMap)‖ : R) ^ m * (t ^ m / m.factorial : R)) := by
                  have h₂₅ : Summable (fun m : ℕ => ((‖(D.toLinearMap)‖ * t : R) ^ m / m.factorial : R)) := by
                    exact summable_pow_div_factorial (‖(D.toLinearMap)‖ * t : R)
                  convert h₂₅ using 1
                  <;> ext m <;> ring_nf
                  <;> field_simp [Nat.factorial]
                  <;> ring_nf
                exact Summable.mul_left (‖y‖ : R) h₂₄
              exact Summable.of_nonneg_of_le (fun m _ => by positivity) h₂₂ h₂₃
            exact h₂₁
          -- Use the Cauchy product theorem for summable series
          have h₂₀ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
              ∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) := by
            -- This is the Cauchy product formula
            have h₂₁ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
                ∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) := by
              -- Use the Cauchy product theorem for Banach algebras
              have h₂₂ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
                  ∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) := by
                -- Use the Cauchy product theorem
                have h₂₃ : (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) =
                    ∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) := by
                  -- This follows from the general Cauchy product theorem for complete normed algebras
                  classical
                  have h₂₄ : HasSum (fun n : ℕ => (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) := by
                    exact tsum_eq_sum h₁₂
                  have h₂₅ : HasSum (fun m : ℕ => (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) := by
                    exact tsum_eq_sum h₁₉
                  -- Use the Cauchy product theorem for HasSum
                  have h₂₆ : HasSum (fun n : ℕ => ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y)) (∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y)) := by
                    -- The Cauchy product of two summable series
                    have h₂₇ : HasSum (fun n : ℕ => ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y)) ((∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y)) := by
                      -- Use the Cauchy product theorem for HasSum in a Banach algebra
                      have h₂₈ : HasSum (fun n : ℕ => (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) (∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) := h₂₄
                      have h₂₉ : HasSum (fun m : ℕ => (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y) := h₂₅
                      -- The product is continuous and bilinear, so we can use the Cauchy product theorem
                      have h₃₀ : HasSum (fun n : ℕ => ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y)) ((∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) x) * (∑' m : ℕ, (t ^ m / m.factorial : R) • ((D.toLinearMap) ^ m) y)) := by
                        -- Use the general Cauchy product theorem for complete normed algebras
                        convert HasSum.mul h₂₈ h₂₉ using 1
                        <;>
                        (try simp_all [Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul])
                        <;>
                        (try ext)
                        <;>
                        (try simp_all [ContinuousLinearMap.comp_apply, smul_smul])
                        <;>
                        (try ring_nf)
                        <;>
                        (try norm_num)
                        <;>
                        (try aesop)
                      exact h₂₈
                    exact h₂₇
                  exact h₂₂
                exact h₂₁
              have h₂₂ : ∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) =
                  ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
                -- Use the Leibniz rule to combine the terms
                have h₂₃ : ∀ n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) = (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
                  intro n
                  have h₂₄ : ((D.toLinearMap) ^ n) (x * y) = ∑ k in Finset.range (n + 1), ((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y) := by
                    intro n
                    induction n with
                    | zero => simp [LinearMap.one_apply]
                    | succ n ih =>
                      rw [Function.iterate_succ_apply']
                      rw [ih]
                      have h₅ := D.leibniz _ _
                      simp [Function.iterate_succ_apply', Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul] at h₅ ⊢
                      <;> abel_nf at h₅ ⊢ <;>
                      (try ring_nf at h₅ ⊢) <;>
                      (try simp_all [Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul]) <;>
                      (try
                        {
                          apply Eq.symm
                          apply Finset.sum_bij' (fun i _ => n - i) (fun i _ => n - i)
                          <;> simp_all [Finset.mem_range, Nat.lt_succ_iff]
                          <;> omega
                        }) <;>
                      (try
                        {
                          rw [Finset.sum_range_succ, add_comm]
                          <;> simp_all [Function.iterate_succ_apply', Finset.sum_range_succ, add_smul, smul_add, ContinuousLinearMap.map_add, ContinuousLinearMap.map_smul]
                          <;> ring_nf at * <;> abel_nf at * <;> aesop
                        })
                  calc
                    ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) =
                        ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) * ((t : R) ^ (n - k) / (n - k).factorial : R) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) := by
                      apply Finset.sum_congr rfl
                      intro k hk
                      simp [smul_smul, mul_assoc, mul_comm, mul_left_comm]
                      <;> ring_nf
                      <;> simp_all [smul_smul, mul_assoc, mul_comm, mul_left_comm]
                      <;> field_simp [Nat.factorial]
                      <;> ring_nf
                    _ = ∑ k in Finset.range (n + 1), ((t : R) ^ n / (k.factorial * (n - k).factorial : R)) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) := by
                      apply Finset.sum_congr rfl
                      intro k hk
                      have h₂₅ : ((t : R) ^ k / k.factorial : R) * ((t : R) ^ (n - k) / (n - k).factorial : R) = (t : R) ^ n / (k.factorial * (n - k).factorial : R) := by
                        field_simp [pow_add, Nat.factorial]
                        <;> ring_nf
                        <;> field_simp [Nat.factorial]
                        <;> ring_nf
                      rw [h₂₅]
                      <;> simp [smul_smul, mul_assoc, mul_comm, mul_left_comm]
                      <;> ring_nf
                    _ = ∑ k in Finset.range (n + 1), (n.choose k : R) * ((t : R) ^ n / n.factorial : R) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) := by
                      apply Finset.sum_congr rfl
                      intro k hk
                      have h₂₆ : (n.choose k : R) = (n.factorial : R) / (k.factorial * (n - k).factorial : R) := by
                        norm_cast
                        <;> field_simp [Nat.choose_eq_factorial_div_factorial, Nat.factorial_succ]
                        <;> ring_nf
                        <;> field_simp [Nat.factorial]
                        <;> ring_nf
                      have h₂₇ : (t : R) ^ n / (k.factorial * (n - k).factorial : R) = (n.choose k : R) * ((t : R) ^ n / n.factorial : R) := by
                        rw [h₂₆]
                        <;> field_simp [Nat.factorial]
                        <;> ring_nf
                        <;> field_simp [Nat.factorial]
                        <;> ring_nf
                      rw [h₂₇]
                      <;> simp [smul_smul, mul_assoc, mul_comm, mul_left_comm]
                      <;> ring_nf
                    _ = (n.choose k : R) * ((t : R) ^ n / n.factorial : R) • ∑ k in Finset.range (n + 1), (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) := by
                      simp [Finset.mul_sum, Finset.sum_mul, mul_assoc, mul_comm, mul_left_comm]
                      <;> simp_all [Finset.sum_range_succ, add_smul, smul_add]
                      <;> ring_nf
                      <;> simp_all [smul_smul, mul_assoc, mul_comm, mul_left_comm]
                      <;> field_simp [Nat.factorial]
                      <;> ring_nf
                    _ = (t ^ n / n.factorial : R) • ∑ k in Finset.range (n + 1), (n.choose k : R) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) := by
                      simp [smul_sum, smul_smul, mul_assoc, mul_comm, mul_left_comm]
                      <;> ring_nf
                      <;> simp_all [Finset.sum_range_succ, add_smul, smul_add]
                      <;> field_simp [Nat.factorial]
                      <;> ring_nf
                    _ = (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
                      have h₂₈ : ∑ k in Finset.range (n + 1), (n.choose k : R) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) = ((D.toLinearMap) ^ n) (x * y) := by
                        calc
                          ∑ k in Finset.range (n + 1), (n.choose k : R) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) = ∑ k in Finset.range (n + 1), ((n.choose k : ℝ) : R) • (((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y)) := by rfl
                          _ = ∑ k in Finset.range (n + 1), ((D.toLinearMap) ^ k x) * ((D.toLinearMap) ^ (n - k) y) := by
                            -- This step uses the binomial theorem for the product in the algebra
                            -- For the specific case of the Zorn matrix algebra,
                            -- the derivation property ensures this holds for the exponential
                            simp_all [h₁₀]
                            <;> aesop
                          _ = ((D.toLinearMap) ^ n) (x * y) := by
                            rw [h₁₀]
                            <;> simp_all [Finset.sum_range_succ, add_smul, smul_add]
                            <;> aesop
                      rw [h₂₈]
                      <;> simp [smul_smul]
                      <;> ring_nf
                  <;> simp_all [Finset.sum_range_succ, add_smul, smul_add]
                  <;> aesop
                -- Now use this to prove the series equality
                calc
                  ∑' n : ℕ, ∑ k in Finset.range (n + 1), ((t : R) ^ k / k.factorial : R) • ((D.toLinearMap) ^ k x) * ((t : R) ^ (n - k) / (n - k).factorial : R) • ((D.toLinearMap) ^ (n - k) y) =
                      ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by
                    apply tsum_congr
                    intro n
                    rw [h₂₃ n]
                    <;> simp [smul_smul]
                    <;> ring_nf
                  _ = ∑' n : ℕ, (t ^ n / n.factorial : R) • ((D.toLinearMap) ^ n) (x * y) := by rfl
              rw [h₂₂]
            <;> simp_all [tsum_eq_sum]
            <;> aesop
          rw [h₁₁]
        <;> simp_all [tsum_eq_sum]
        <;> aesop
      rw [h₉]
    <;> simp_all [tsum_eq_sum]
    <;> aesop
  rw [h₄]
  <;> simp_all [tsum_eq_sum]
  <;> aesop
exact h₃ x y

/-- THEOREM: exp(tD) preserves the identity -/
theorem flow_preserves_one (D : Derivation A) (t : R) :
    (flow D t) (1 : A) = 1 := by
  have h₁ : (flow D t) (1 : A) = 1 := by
    have h₂ : flow D t = (D.toLinearMap).exp.map (t • (1 : A →L[R] A)) := rfl
    rw [h₂]
    have h₃ : ((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) (1 : A) = 1 := by
      have h₄ : ((D.toLinearMap).exp.map (t • (1 : A →L[R] A))) (1 : A) = 1 := by
        -- The exponential of a derivation preserves the identity
        have h₅ : ∀ (n : ℕ), ((D.toLinearMap) ^ n) (1 : A) = if n = 0 then (1 : A) else 0 := by
          intro n
          induction n with
          | zero => simp [LinearMap.one_apply]
          | succ n ih =>
            rw [Function.iterate_succ_apply']
            rw [ih]
            split_ifs <;> simp_all [LinearMap.map_zero]
            <;> aesop
        -- The exponential map applied to 1 gives 1
        simp [LinearMap.exp_apply, h₅]
        <;>
        norm_num
        <;>
        simp_all [Finset.sum_ite_eq']
        <;>
        aesop
      exact h₄
    exact h₃
  exact h₁

/-- THEOREM: exp(tD) preserves the product -/
theorem flow_preserves_mul (D : Derivation A) (t : R) (x y : A) :
    (flow D t) (x * y) = (flow D t) x * (flow D t) y := by
  exact flow_is_automorphism D t x y

end ZornDerivationExponentialAutomorphism