import Mathlib
import InfoGeometry.Quantum.MajoranaPfaffianNaturalClosure

open InfoGeometry.MajoranaPfaffianNaturalClosure
open Matrix

namespace InfoGeometry.Lie.BRSTCohomology

variable {V : Type*} [AddCommGroup V] [Module ℝ V]

/-- A BRST Differential Operator Q with Q ∘ Q = 0 -/
structure BRSTComplex (V : Type*) [AddCommGroup V] [Module ℝ V] where
  Q : V →ₗ[ℝ] V
  Q_sq_zero : Q.comp Q = 0

/-- Theorem: Im(Q) ⊆ Ker(Q) for any BRST operator Q -/
theorem range_le_ker (C : BRSTComplex V) :
    LinearMap.range C.Q ≤ LinearMap.ker C.Q := by
  rw [LinearMap.range_le_ker_iff]
  exact C.Q_sq_zero

/-- The Physical BRST Cohomology / State Space H_phys = Ker(Q) / Im(Q) -/
def PhysicalStateSpace (C : BRSTComplex V) : Type _ :=
  LinearMap.ker C.Q ⧸ (LinearMap.range C.Q).comap (LinearMap.ker C.Q).subtype

instance (C : BRSTComplex V) : AddCommGroup (PhysicalStateSpace C) :=
  Submodule.Quotient.addCommGroup _

instance (C : BRSTComplex V) : Module ℝ (PhysicalStateSpace C) :=
  Submodule.Quotient.module _

/-- 2D Nambu-Gor'kov BRST Complex generated by the CAR annihilation matrix unit a = (0 1; 0 0) -/
def nambuBRSTOp : (Fin 2 → ℝ) →ₗ[ℝ] (Fin 2 → ℝ) :=
  Matrix.mulVecLin annihilationR

theorem nambuBRSTOp_sq : nambuBRSTOp.comp nambuBRSTOp = 0 := by
  dsimp [nambuBRSTOp]
  rw [← Matrix.mulVecLin_mul, annihilationR_sq, Matrix.mulVecLin_zero]

def nambuBRSTComplex : BRSTComplex (Fin 2 → ℝ) where
  Q := nambuBRSTOp
  Q_sq_zero := nambuBRSTOp_sq

/-- Explicit kernel characterization: Ker(Q) = span { ![(1:ℝ), 0] } -/
theorem nambu_ker_characterization (v : Fin 2 → ℝ) :
    nambuBRSTOp v = 0 ↔ v 1 = 0 := by
  dsimp [nambuBRSTOp, annihilationR]
  constructor
  · intro h
    have h0 := congr_fun h 0
    simp [mulVec, dotProduct, Fin.sum_univ_two] at h0
    exact h0
  · intro h
    ext i
    fin_cases i <;> simp [mulVec, dotProduct, Fin.sum_univ_two, h]

/-- Explicit range characterization: Im(Q) = span { ![(1:ℝ), 0] } -/
theorem nambu_range_characterization (v : Fin 2 → ℝ) :
    v ∈ LinearMap.range nambuBRSTOp ↔ v 1 = 0 := by
  constructor
  · rintro ⟨u, rfl⟩
    have h := nambu_ker_characterization u
    dsimp [nambuBRSTOp, annihilationR]
    simp [mulVec, dotProduct, Fin.sum_univ_two]
  · intro h
    use ![0, v 0]
    ext i
    fin_cases i <;> simp [nambuBRSTOp, annihilationR, mulVec, dotProduct, Fin.sum_univ_two, h]

/-- BRST Quartet Decoupling Theorem: Ker(Q) = Im(Q) for the 2D Nambu boundary mode -/
theorem nambu_ker_eq_range :
    LinearMap.ker nambuBRSTOp = LinearMap.range nambuBRSTOp := by
  ext v
  rw [LinearMap.mem_ker, nambu_ker_characterization, ← nambu_range_characterization]

/-- Certified BRST Cohomology Triviality (Q-exact BRST Quartet Mechanism) -/
theorem nambu_physical_space_trivial (x : PhysicalStateSpace nambuBRSTComplex) :
    x = 0 := by
  obtain ⟨v, rfl⟩ := Quotient.mk''_surjective x
  change Submodule.Quotient.mk v = 0
  rw [Submodule.Quotient.mk_eq_zero, Submodule.mem_comap]
  have hv : (v.1 : Fin 2 → ℝ) ∈ LinearMap.ker nambuBRSTOp := v.2
  rw [nambu_ker_eq_range] at hv
  exact hv

end InfoGeometry.Lie.BRSTCohomology