import Mathlib.Tactic
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Physics.HestenesKreinOperatorCalculus

/-!
# Concrete Split Cartan Group A

This file establishes the "concrete split Cartan group A" as the continuous
one-parameter subgroup generated by a hyperbolic operator $K$ with $K^2 = 1$.

This is the rank-one "geometric atom" underlying the hyperbolic flow of the
Erlangen-Langlands program. It is independent of complexification and
isomorphism theorems, relying solely on the real algebra of $K^2 = 1$.
-/

noncomputable section

namespace InfoGeometry.Lie.ConcreteSplitCartan

open InfoGeometry.Physics.HestenesKreinOperatorCalculus

variable {A : Type*} [NormedRing A] [NormedAlgebra ℝ A] [CompleteSpace A]

local instance : NormedAlgebra ℚ A :=
  NormedAlgebra.restrictScalars ℚ ℝ A

/-- The hyperbolic exponential flow defines a continuous one-parameter group.
    We package it as a homomorphism from `Additive ℝ` to `Aˣ`. -/
def splitCartanHom (K : A) : Multiplicative ℝ →* Aˣ where
  toFun t :=
    let t_add := Multiplicative.toAdd t
    have h_comm : Commute (t_add • K) (-t_add • K) := by
      unfold Commute SemiconjBy
      rw [smul_mul_smul, smul_mul_smul, mul_comm t_add (-t_add)]
    have h_mul : NormedSpace.exp (t_add • K) * NormedSpace.exp (-t_add • K) = 1 := by
      rw [← NormedSpace.exp_add_of_commute h_comm]
      have h_zero : t_add • K + -t_add • K = 0 := by
        rw [← add_smul, add_neg_cancel, zero_smul]
      rw [h_zero, NormedSpace.exp_zero]
    have h_comm_rev : Commute (-t_add • K) (t_add • K) := h_comm.symm
    have h_mul_rev : NormedSpace.exp (-t_add • K) * NormedSpace.exp (t_add • K) = 1 := by
      rw [← NormedSpace.exp_add_of_commute h_comm_rev]
      have h_zero : -t_add • K + t_add • K = 0 := by
        rw [← add_smul, neg_add_cancel, zero_smul]
      rw [h_zero, NormedSpace.exp_zero]
    { val := NormedSpace.exp (t_add • K)
      inv := NormedSpace.exp (-t_add • K)
      val_inv := h_mul
      inv_val := h_mul_rev }
  map_one' := by
    ext
    change NormedSpace.exp (0 • K) = 1
    rw [zero_smul, NormedSpace.exp_zero]
  map_mul' t u := by
    ext
    change NormedSpace.exp ((Multiplicative.toAdd t + Multiplicative.toAdd u) • K) =
           NormedSpace.exp (Multiplicative.toAdd t • K) * NormedSpace.exp (Multiplicative.toAdd u • K)
    rw [add_smul]
    have h_comm : Commute (Multiplicative.toAdd t • K) (Multiplicative.toAdd u • K) := by
      unfold Commute SemiconjBy
      rw [smul_mul_smul, smul_mul_smul, mul_comm (Multiplicative.toAdd t) (Multiplicative.toAdd u)]
    exact NormedSpace.exp_add_of_commute h_comm

@[simp] theorem splitCartanHom_apply (K : A)
    (t : Multiplicative ℝ) :
    ((splitCartanHom K t : Aˣ) : A) =
      NormedSpace.exp (Multiplicative.toAdd t • K) := by
  rfl

/-- The concrete split-Cartan subgroup has the expected hyperbolic readout.

This is the first theorem using the involution hypothesis: the homomorphism
law itself only needs scalar commutativity, while the `cosh/sinh` expression
uses the native `K^2 = 1` exponential theorem.
-/
theorem splitCartanHom_apply_eq_cosh_sinh (K : A) (hK : K ^ 2 = 1)
    (t : Multiplicative ℝ) :
    ((splitCartanHom K t : Aˣ) : A) =
      Real.cosh (Multiplicative.toAdd t) • (1 : A) +
        Real.sinh (Multiplicative.toAdd t) • K := by
  rw [splitCartanHom_apply]
  exact exp_of_sq_eq_one K hK (Multiplicative.toAdd t)

/-- The Split Cartan group A generated by K. -/
def SplitCartanGroup (K : A) : Subgroup Aˣ :=
  (splitCartanHom K).range

end InfoGeometry.Lie.ConcreteSplitCartan
