import Mathlib
import InfoGeometry.Algebra.CyclotomicOperatorProjectors
import InfoGeometry.Algebra.IwasawaOperatorTwinLoxodromic

/-!
# Trifactor readout contracts

This owner separates three distinct semantic readouts that may be attached to
an algebraic operator:

* a finite spectral/Fourier projector readout;
* a power/grade (Mellin-style) readout;
* a positive-time multiplicative flow (Laplace/semigroup-style) readout.

The structures are deliberately independent.  In particular, an algebraic
identity `X ^ n = X` does **not** manufacture a grading, a semigroup, a Fourier
resolution, or a KAN decomposition.  Those meanings require explicit evidence
objects and compatibility bridges.

The existing `CyclotomicOperatorProjectors` owner supplies the algebraic
`n`-potent zero/nonzero projector split.  The existing
`IwasawaOperatorTwinLoxodromic` owner supplies algebraic K/A/N-type kernels and
finite rotor/Weyl identities.  This file only defines the semantic contracts
that later theorems may inhabit.

No analytic Fourier/Mellin/Laplace integral transform is asserted here.
No full Iwasawa decomposition `G = KAN` is asserted here.
-/

noncomputable section

namespace InfoGeometry.Geometry.TrifactorReadouts

open scoped BigOperators
open InfoGeometry.Algebra.CyclotomicOperatorProjectors

universe u v

/-! ## 1. Finite spectral / Fourier readout -/

/--
A finite spectral readout of `X` over a coefficient ring `K`.

`support` is the total projector carried by this readout.  It need not be the
identity: for an `n`-potent element with a nontrivial kernel it can be the
nonzero-sector projector `X^(n-1)`.
-/
structure FourierReadout
    {K : Type u} {A : Type v}
    [CommRing K] [Ring A] [Algebra K A]
    (X : A) (m : ℕ) where
  /-- Eigenvalue/phase label for each finite mode. -/
  phase : Fin m → K
  /-- Algebraic projector for each mode. -/
  projector : Fin m → A
  /-- Total support of the finite spectral family. -/
  support : A
  /-- Every mode projector is idempotent. -/
  idempotent : ∀ i, projector i * projector i = projector i
  /-- Distinct mode projectors are orthogonal. -/
  orthogonal : ∀ i j, i ≠ j → projector i * projector j = 0
  /-- The mode projectors resolve exactly the declared support. -/
  complete : (∑ i, projector i) = support
  /-- Each mode is an algebraic eigenprojector for `X`. -/
  eigen : ∀ i,
    X * projector i = algebraMap K A (phase i) * projector i
  /-- The finite modes reconstruct `X` on their support. -/
  reconstruction :
    X = ∑ i, algebraMap K A (phase i) * projector i

/--
Compatibility of a Fourier readout with the already-proved algebraic
`n`-potent splitting.  This is a bridge, not a consequence bundled into
`IsNPotent` itself.
-/
structure NPotentFourierCompatibility
    {K : Type u} {A : Type v}
    [CommRing K] [Ring A] [Algebra K A]
    (X : A) (n : ℕ)
    (hX : IsNPotent X n)
    (F : FourierReadout X (n - 1)) : Prop where
  /-- The Fourier family resolves precisely the nonzero `n`-potent sector. -/
  support_eq_nonzeroProjector :
    F.support = npotentNonzeroProjector X n

/-! ## 2. Power / Mellin-style readout -/

/--
The exact multiplicative character generated by the powers of `X`.

The domain is `Multiplicative ℕ`: addition of exponents is represented by
multiplication in the wrapper, so the homomorphism law expresses
`X^(k+l) = X^k * X^l` without calling this an analytic Mellin transform.
-/
structure PowerReadout
    {A : Type u} [Monoid A]
    (X : A) where
  powerCharacter : Multiplicative ℕ →* A
  power_apply : ∀ k : ℕ,
    powerCharacter (Multiplicative.ofAdd k) = X ^ k

/--
An explicit integer-indexed algebraic grading readout.  The grading is separate
from the bare power character because powers alone do not produce a grading of
an ambient algebra.
-/
structure GradeReadout
    {K : Type u} {A : Type v}
    [CommRing K] [Ring A] [Algebra K A]
    (X : A) where
  grade : ℤ → Submodule K A
  /-- Left multiplication by `X^k` shifts a degree-zero vector to degree `k`. -/
  grade_shift : ∀ (k : ℕ) (y : A),
    y ∈ grade 0 → X ^ k * y ∈ grade (Int.ofNat k)

/--
Compatibility between a finite Fourier readout and the power character of the
same element.  This is the algebraic content behind the statement that powers
read the finite spectral phases.
-/
structure FourierPowerCompatibility
    {K : Type u} {A : Type v}
    [CommRing K] [Ring A] [Algebra K A]
    (X : A) (m : ℕ)
    (F : FourierReadout X m)
    (P : PowerReadout X) : Prop where
  power_on_projector : ∀ (k : ℕ) (i : Fin m),
    X ^ k * F.projector i =
      algebraMap K A ((F.phase i) ^ k) * F.projector i

/-! ## 3. Positive-time semigroup / Laplace-style readout -/

/--
A positive-time multiplicative flow in `A`.

The homomorphism itself carries both the zero-time identity and the semigroup
law.  No derivative, logarithm, exponential series, generator theorem, or
Laplace integral is smuggled into this structure.
-/
structure PositiveSemigroupReadout
    {A : Type u} [Monoid A] where
  flow : Multiplicative NNReal →* A

namespace PositiveSemigroupReadout

variable {A : Type u} [Monoid A]

@[simp] theorem flow_zero (L : PositiveSemigroupReadout (A := A)) :
    L.flow (Multiplicative.ofAdd (0 : NNReal)) = 1 := by
  exact L.flow.map_one

@[simp] theorem flow_add
    (L : PositiveSemigroupReadout (A := A))
    (s t : NNReal) :
    L.flow (Multiplicative.ofAdd (s + t)) =
      L.flow (Multiplicative.ofAdd s) *
        L.flow (Multiplicative.ofAdd t) := by
  exact L.flow.map_mul _ _

end PositiveSemigroupReadout

/-! ## 4. Hypercomplex K/A/N kernels and soldering -/

/--
Purely algebraic hypercomplex K/A/N kernel data.

The names record the intended elliptic/hyperbolic/parabolic signatures only;
this structure does not claim a global Iwasawa factorization.
-/
structure HypercomplexKANKernel
    (A : Type u) [Ring A] where
  K : A
  Asem : A
  N : A
  elliptic_sq : K * K = -1
  hyperbolic_sq : Asem * Asem = 1
  parabolic_sq : N * N = 0

/--
An explicit factorization of a positive-time flow into three supplied
semigroup readouts.  The factorization is evidence.  It is not inferred from
`X^n = X` and is not promoted to a group-level theorem `G = KAN`.
-/
structure KANFlowSoldering
    {A : Type u} [Ring A]
    (H : HypercomplexKANKernel A) where
  kFlow : PositiveSemigroupReadout (A := A)
  aFlow : PositiveSemigroupReadout (A := A)
  nFlow : PositiveSemigroupReadout (A := A)
  totalFlow : PositiveSemigroupReadout (A := A)
  factor : ∀ t : NNReal,
    totalFlow.flow (Multiplicative.ofAdd t) =
      kFlow.flow (Multiplicative.ofAdd t) *
        aFlow.flow (Multiplicative.ofAdd t) *
          nFlow.flow (Multiplicative.ofAdd t)

/-! ## 5. Explicit semantic ledger -/

/--
A bundled ledger for clients that genuinely possess all three readouts.
Possessing an `NPotentTrifactorLedger` is stronger than merely proving
`X ^ n = X` because every semantic layer is supplied explicitly.
-/
structure NPotentTrifactorLedger
    {K : Type u} {A : Type v}
    [CommRing K] [Ring A] [Algebra K A]
    (X : A) (n : ℕ) where
  npotent : IsNPotent X n
  fourier : FourierReadout X (n - 1)
  fourier_npotent : NPotentFourierCompatibility X n npotent fourier
  powers : PowerReadout X
  fourier_powers : FourierPowerCompatibility X (n - 1) fourier powers
  grading : GradeReadout X
  semigroup : PositiveSemigroupReadout (A := A)

end InfoGeometry.Geometry.TrifactorReadouts
