import InfoGeometry.Signal.ComplexRealification
import InfoGeometry.Algebra.FiniteSpinAlgebra

/-!
# Steering-plane detector geometry

This file formalizes the finite algebraic core of Sangston's phase-unknown
complex-data detector: the detector readout is the squared length of the
projection onto the real two-plane generated by a steering vector and its
quadrature axis.

The module proves only finite coordinate identities.  It does not assert
statistical optimality, false-alarm behavior, or a stochastic detection theorem.
-/

noncomputable section

namespace InfoGeometry.Signal.SteeringBivectorDetector

open scoped BigOperators
open ComplexRealification

variable {ι : Type*} [Fintype ι]

/-- The quarter-turn of paired real data: `(x, y) ↦ (-y, x)`. -/
def quadratureAxis (x : RealPlaneData ι) : RealPlaneData ι :=
  fun i => (-(x i).2, (x i).1)

/-- Projection of `d` onto the explicitly supplied steering two-plane. -/
def steeringPlaneProjection
    (p q d : RealPlaneData ι) : RealPlaneData ι :=
  realDot p d • p + realDot q d • q

/-- The quadrature axis has the same squared norm as the original steering data. -/
theorem realNormSq_quadratureAxis (p : RealPlaneData ι) :
    realNormSq (quadratureAxis p) = realNormSq p := by
  unfold realNormSq quadratureAxis
  refine Finset.sum_congr rfl ?_
  intro i _
  ring_nf

/-- A steering vector and its quadrature axis are orthogonal in the realified plane. -/
theorem realDot_self_quadratureAxis (p : RealPlaneData ι) :
    realDot p (quadratureAxis p) = 0 := by
  unfold realDot quadratureAxis
  simp
  ring_nf
  simp

/-- Quadrature-axis dot product is the imaginary Hermitian readout. -/
theorem realDot_quadratureAxis_eq_quadratureDot (s z : RealPlaneData ι) :
    realDot (quadratureAxis s) z = quadratureDot s z := by
  unfold realDot quadratureDot quadratureAxis
  refine Finset.sum_congr rfl ?_
  intro i _
  ring

/--
Norm of an explicitly orthonormal two-plane projection.

The hypotheses say that `p` and `q` are unit and mutually orthogonal for the
finite real paired-plane dot product.
-/
theorem steeringPlaneProjection_normSq
    {p q d : RealPlaneData ι}
    (hp : realNormSq p = 1)
    (hq : realNormSq q = 1)
    (hpq : realDot p q = 0) :
    realNormSq (steeringPlaneProjection p q d) =
      realDot p d ^ 2 + realDot q d ^ 2 := by
  let a := realDot p d
  let b := realDot q d
  have hsum :
      realNormSq (a • p + b • q) =
        a ^ 2 * realNormSq p + 2 * a * b * realDot p q + b ^ 2 * realNormSq q := by
    calc
      realNormSq (a • p + b • q)
          =
            ∑ i, (a ^ 2 * ((p i).1 ^ 2 + (p i).2 ^ 2) +
              2 * a * b * ((p i).1 * (q i).1 + (p i).2 * (q i).2) +
              b ^ 2 * ((q i).1 ^ 2 + (q i).2 ^ 2)) := by
        unfold realNormSq
        refine Finset.sum_congr rfl ?_
        intro i _
        simp
        ring
      _ = a ^ 2 * realNormSq p + 2 * a * b * realDot p q +
            b ^ 2 * realNormSq q := by
        unfold realNormSq realDot
        rw [Finset.mul_sum, Finset.mul_sum, Finset.mul_sum]
        simp [Finset.sum_add_distrib]
  unfold steeringPlaneProjection
  change realNormSq (a • p + b • q) = a ^ 2 + b ^ 2
  rw [hsum, hp, hq, hpq]
  ring

/--
For a unit complex steering vector, the real steering-plane projection length
is the squared magnitude of the finite Hermitian readout.
-/
theorem steeringProjection_normSq_eq_hermitian_normSq
    {s z : ComplexData ι}
    (hs : complexNormSq s = 1) :
    realNormSq
        (steeringPlaneProjection
          (realify s) (quadratureAxis (realify s)) (realify z)) =
      Complex.normSq (hermitianInner s z) := by
  have hp : realNormSq (realify s) = 1 := by
    rw [realification_normSq_eq_complexNormSq, hs]
  have hq : realNormSq (quadratureAxis (realify s)) = 1 := by
    rw [realNormSq_quadratureAxis, hp]
  have hpq : realDot (realify s) (quadratureAxis (realify s)) = 0 :=
    realDot_self_quadratureAxis (realify s)
  rw [steeringPlaneProjection_normSq hp hq hpq]
  rw [realDot_quadratureAxis_eq_quadratureDot]
  rw [hermitian_normSq_eq_realDot_sq_add_quadratureDot_sq]

end InfoGeometry.Signal.SteeringBivectorDetector
