
This is the real/Krein replacement for a complex modular automorphism group.
The flow is represented by real bounded endomorphism rotors and their inverses.

The former generic `Prop` witness for the generator relation is replaced by
a concrete one-parameter group law `rotor(s+t) = rotor(s) * rotor(t)`.
-/


@[rep_depth operator]
structure HestenesRotorFlow
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (D : KreinHestenesModularDatum E) where
  /-- Real rotor implementing modular flow. -/
  rotor : ℝ → RealEnd E

  /-- Inverse rotor. -/
  rotorInv : ℝ → RealEnd E

  /-- Rotor at time zero is identity. -/
  rotor_zero :
    rotor 0 = ContinuousLinearMap.id ℝ E

  /-- Inverse rotor at time zero is identity. -/
  rotorInv_zero :
    rotorInv 0 = ContinuousLinearMap.id ℝ E

  /-- Left inverse law. -/
  rotor_left_inv :
    ∀ t : ℝ, rotorInv t * rotor t = ContinuousLinearMap.id ℝ E

  /-- Right inverse law. -/
  rotor_right_inv :
    ∀ t : ℝ, rotor t * rotorInv t = ContinuousLinearMap.id ℝ E

  /--
  One-parameter group law for the rotor flow.

  This is the concrete replacement for the former generic `Prop` generator
  relation. It states that the rotor family forms a one-parameter group,
  which is the defining property of being generated by an infinitesimal
  generator (the modular generator).
  -/
  rotor_group_True :
    ∀ s t : ℝ, rotor (s + t) = rotor s * rotor t

  /-- Predicate saying that an observable is fixed by the rotor flow. -/
  fixedByFlow : RealEnd E → Prop

  /--
  Flow-fixed observables are exactly monogenic observables.

  The bounded abstract flow stores this equivalence as part of its contract:
  differentiability of `t ↦ sigma_t(A)` is not present in this file.
  -/
  fixedByFlow_iff_monogenic :
    ∀ A : RealEnd E,
      fixedByFlow A ↔ KreinHestenesModularDatum.IsMonogenic D A


namespace HestenesRotorFlow

variable
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {D : KreinHestenesModularDatum E}
    (F : HestenesRotorFlow D)

/- Rotor conjugation action on observables. -/
def sigma (t : ℝ) (A : RealEnd E) : RealEnd E :=
  F.rotor t * A * F.rotorInv t

/-
Rotor conjugation at time zero is the identity on observables.
-/


theorem sigma_zero_apply (A : RealEnd E) :
    F.sigma 0 A = A := by
  ext v
  simp [sigma, F.rotor_zero, F.rotorInv_zero]

/- The inverse rotor satisfies the reversed group law. -/
theorem rotorInv_group (s t : ℝ) :
    F.rotorInv (s + t) = F.rotorInv t * F.rotorInv s := by
  let x : RealEnd E := F.rotor (s + t)
  let y : RealEnd E := F.rotorInv (s + t)
  let z : RealEnd E := F.rotorInv t * F.rotorInv s
  have hyx : y * x = ContinuousLinearMap.id ℝ E := by
    dsimp [x, y]
    exact F.rotor_left_inv (s + t)
  have hxz : x * z = ContinuousLinearMap.id ℝ E := by
    dsimp [x, z]
    calc
      F.rotor (s + t) * (F.rotorInv t * F.rotorInv s) =
          (F.rotor s * F.rotor t) * (F.rotorInv t * F.rotorInv s) := by
            rw [F.rotor_group_True]
        _ = F.rotor s * (F.rotor t * F.rotorInv t) * F.rotorInv s := by
          simp [mul_assoc]
        _ = F.rotor s * F.rotorInv s := by
          ext v
          simp [ContinuousLinearMap.mul_apply, F.rotor_right_inv t]