import InfoGeometry.Canonical.OperatorDictionary
import InfoGeometry.Canonical.OperatorModularTemperatureDuality
import InfoGeometry.Meta.Architecture
import Mathlib.Analysis.Normed.Algebra.Exponential

open scoped InnerProductSpace

noncomputable section

/-!
# InfoGeometry.Canonical.SouriauModularBregmanOperator

Bounded operator socket for the Souriau / modular / Bregman dictionary.

This file deliberately stays in the bounded doubled-carrier lane:

* `phaseAxisK = J ∘ ε` remains the internal real phase axis owned by
  `OperatorDictionary`;
* `modularHamiltonianK` is a separate modular/surprisal generator;
* `Δ - I` is formalized as deviation from the identity operator, not as a trace
  regularization;
* Bregman/Fenchel duality is routed through an operator product together with a
  scalar readout/pairing, not through an unpaired product alone.
-/

namespace InfoGeometry.Canonical.SouriauModularBregmanOperator

open InfoGeometry.Krein
open InfoGeometry.Canonical.OperatorDictionary
open InfoGeometry.Canonical.OperatorModularTemperatureDuality

/-! ## Product/readout sockets for operatorial Bregman geometry -/

section GenericOperatorBregman

variable {Op : Type*} [AddGroup Op]

/--
Minimal primal/dual operator socket.

The product supplies the algebraic composition channel. The readout turns that
product into the scalar pairing required by convex duality.
-/
@[rep_depth operator]
structure OperatorPrimalDualSocket (Op : Type*) [AddGroup Op] where
  /-- Operator product/composition channel. -/
  product : Op → Op → Op
  /-- Scalar readout; in concrete lanes this can be trace, weight, KMS state,
      vector expectation, or a regularized functional. -/
  readout : Op → ℝ
  /-- Right-zero law needed for the diagonal Bregman identity. -/
  product_zero_right_readout : ∀ X : Op, readout (product X 0) = 0

namespace OperatorPrimalDualSocket

variable (S : OperatorPrimalDualSocket Op)

/-- Scalar pairing induced by product plus readout. -/
@[rep_depth operator]
def pairing (X Y : Op) : ℝ :=
  S.readout (S.product X Y)

@[simp, rep_depth operator]
theorem pairing_zero_right (X : Op) :
    S.pairing X 0 = 0 :=
  S.product_zero_right_readout X

@[rep_depth operator]
theorem pairing_eq_readout_product (X Y : Op) :
    S.pairing X Y = S.readout (S.product X Y) :=
  rfl

end OperatorPrimalDualSocket

/--
Frobenius trace/product closures already present in the repo produce a Bregman
socket once the trace-readout of right multiplication by zero is supplied.
-/
@[rep_depth operator]
def operatorPrimalDualSocketOfFrobeniusClosure
    (F : OperatorFrobeniusClosure Op)
    (hzero : ∀ X : Op, F.trace (F.product X 0) = 0) :
    OperatorPrimalDualSocket Op where
  product := F.product
  readout := F.trace
  product_zero_right_readout := hzero

/-- Operatorial Bregman divergence generated by a scalar potential and gradient. -/
@[rep_depth operator]
def operatorBregman
    (S : OperatorPrimalDualSocket Op)
    (Φ : Op → ℝ)
    (gradientΦ : Op → Op)
    (X Y : Op) : ℝ :=
  Φ X - Φ Y - S.pairing (gradientΦ Y) (X - Y)

@[simp, rep_depth operator]
theorem operatorBregman_self
    (S : OperatorPrimalDualSocket Op)
    (Φ : Op → ℝ)
    (gradientΦ : Op → Op)
    (X : Op) :
    operatorBregman S Φ gradientΦ X X = 0 := by
  simp [operatorBregman]

/-- Fenchel gap through the same scalar pairing socket. -/
@[rep_depth operator]
def operatorFenchelGap
    (S : OperatorPrimalDualSocket Op)
    (Φ Ψ : Op → ℝ)
    (X Y : Op) : ℝ :=
  Φ X + Ψ Y - S.pairing X Y

@[rep_depth operator]
theorem operatorFenchelGap_eq_zero_of_contact
    (S : OperatorPrimalDualSocket Op)
    (Φ Ψ : Op → ℝ)
    (X Y : Op)
    (hcontact : Φ X + Ψ Y = S.pairing X Y) :
    operatorFenchelGap S Φ Ψ X Y = 0 := by
  simp [operatorFenchelGap, hcontact]

end GenericOperatorBregman

/-! ## Bounded modular beta family on the doubled real carrier -/

section BoundedDoubledModular

variable {E : Type 0}
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "H₂" => DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂

noncomputable local instance : NormedRing EndH := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndH := inferInstance
local instance : IsTopologicalRing EndH := inferInstance
local instance : CompleteSpace EndH := inferInstance
local instance : SMulCommClass ℝ EndH EndH := inferInstance
local instance : IsScalarTower ℝ EndH EndH := inferInstance

/--
The identity sector `I` in the bounded doubled-carrier lane.

Type III removes trace-normalized density matrices as owner objects; it does not
remove the identity operator of the standard representation.
-/
@[rep_depth operator]
noncomputable def modularIdentity : EndH :=
  (1 : EndH)

@[simp, rep_depth operator]
theorem modularIdentity_apply (u : H₂) :
    modularIdentity (E := E) u = u := by
  simp [modularIdentity]

/-- Alias for the already-owned internal phase axis `K_phase = J ∘ ε`. -/
@[rep_depth operator]
noncomputable def internalPhaseAxisK : EndH :=
  InfoGeometry.Canonical.OperatorDictionary.phaseAxisK (E := E)

/-- The internal phase axis is the old `J ∘ ε` clock axis, not the modular Hamiltonian. -/
@[rep_depth operator]
theorem internalPhaseAxisK_eq_phaseAxisK :
    internalPhaseAxisK (E := E)
      = InfoGeometry.Canonical.OperatorDictionary.phaseAxisK (E := E) :=
  rfl

/-- The internal phase axis squares to `-I`. -/
@[rep_depth operator]
theorem internalPhaseAxisK_sq_eq_neg_id :
    (internalPhaseAxisK (E := E)).comp (internalPhaseAxisK (E := E))
      = -(ContinuousLinearMap.id ℝ H₂) := by
  simpa [internalPhaseAxisK] using
    InfoGeometry.Canonical.OperatorDictionary.phaseAxisK_sq_eq_neg_id (E := E)

/-- `Δ - I`: bounded modular deviation from the identity sector. -/
@[rep_depth operator]
noncomputable def modularDeviation (Δ : EndH) : EndH :=
  Δ - modularIdentity (E := E)

@[simp, rep_depth operator]
theorem modularDeviation_identity :
    modularDeviation (E := E) (modularIdentity (E := E)) = 0 := by
  simp [modularDeviation, modularIdentity]

/-- `exp(-Kmod)` as a bounded modular operator proxy. -/
@[rep_depth operator]
noncomputable def modularDeltaFromHamiltonian (Kmod : EndH) : EndH :=
  NormedSpace.exp ((-1 : ℝ) • Kmod)

@[rep_depth operator]
theorem modularDeltaFromHamiltonian_eq_exp_neg (Kmod : EndH) :
    modularDeltaFromHamiltonian (E := E) Kmod = NormedSpace.exp (-Kmod) := by
  simp [modularDeltaFromHamiltonian]

/-- Modular beta family `β ↦ exp(-β Kmod)`. -/
@[rep_depth operator]
noncomputable def modularBetaFlow (Kmod : EndH) (β : ℝ) : EndH :=
  NormedSpace.exp ((-β) • Kmod)

@[simp, rep_depth operator]
theorem modularBetaFlow_zero (Kmod : EndH) :
    modularBetaFlow (E := E) Kmod 0 = modularIdentity (E := E) := by
  simp [modularBetaFlow, modularIdentity]

@[simp, rep_depth operator]
theorem modularBetaFlow_one (Kmod : EndH) :
    modularBetaFlow (E := E) Kmod 1 = modularDeltaFromHamiltonian (E := E) Kmod := by
  simp [modularBetaFlow, modularDeltaFromHamiltonian]

/-- Deviation of the beta family from the identity sector. -/
@[rep_depth operator]
noncomputable def modularBetaDeviation (Kmod : EndH) (β : ℝ) : EndH :=
  modularBetaFlow (E := E) Kmod β - modularIdentity (E := E)

@[simp, rep_depth operator]
theorem modularBetaDeviation_zero (Kmod : EndH) :
    modularBetaDeviation (E := E) Kmod 0 = 0 := by
  simp [modularBetaDeviation, modularIdentity]

@[rep_depth operator]
theorem modularBetaDeviation_one_eq_modularDeviation_delta
    (Kmod : EndH) :
    modularBetaDeviation (E := E) Kmod 1
      = modularDeviation (E := E) (modularDeltaFromHamiltonian (E := E) Kmod) := by
  simp [modularBetaDeviation, modularDeviation, modularIdentity]

/-- State/operator readout on the positive Hilbert metric. -/
@[rep_depth operator]
noncomputable def operatorStateExpectation (ψ : H₂) (A : EndH) : ℝ :=
  ⟪ψ, A ψ⟫_ℝ

@[simp, rep_depth operator]
theorem operatorStateExpectation_zero (ψ : H₂) :
    operatorStateExpectation (E := E) ψ 0 = 0 := by
  simp [operatorStateExpectation]

/-- Product/readout socket from vector-state expectation and operator product. -/
@[rep_depth operator]
noncomputable def stateExpectationProductSocket (ψ : H₂) :
    OperatorPrimalDualSocket EndH where
  product := fun A B => A * B
  readout := operatorStateExpectation (E := E) ψ
  product_zero_right_readout := by
    intro A
    simp [operatorStateExpectation]

/-- First-quantized surprisal readout of a bounded modular Hamiltonian proxy. -/
@[rep_depth operator]
noncomputable def modularSurprisalReadout (ψ : H₂) (Kmod : EndH) : ℝ :=
  operatorStateExpectation (E := E) ψ Kmod

/-- State readout of the deviation `Δ - I`. -/
@[rep_depth operator]
noncomputable def modularDeviationReadout (ψ : H₂) (Δ : EndH) : ℝ :=
  operatorStateExpectation (E := E) ψ (modularDeviation (E := E) Δ)

@[simp, rep_depth operator]
theorem modularDeviationReadout_identity (ψ : H₂) :
    modularDeviationReadout (E := E) ψ (modularIdentity (E := E)) = 0 := by
  simp [modularDeviationReadout, modularDeviation, modularIdentity, operatorStateExpectation]

/--
Bounded Souriau/modular family: a Lie/Souriau generator is read as a modular
Hamiltonian `Kmod`, while the associated modular operator is `exp(-Kmod)`.
-/
@[rep_depth thermo]
structure BoundedSouriauModularFamily (LieAlgebra : Type*) where
  /-- Operator-valued moment/Hamiltonian observable. -/
  lieObservable : LieAlgebra → EndH
  /-- Souriau inverse-temperature / Lie-algebra coordinate. -/
  beta : LieAlgebra
  /-- Modular Hamiltonian / relative surprisal generator. -/
  modularHamiltonianK : EndH
  /-- Calibration: the modular Hamiltonian is the beta-selected Souriau observable. -/
  modularHamiltonianK_eq_lieObservable_beta :
    modularHamiltonianK = lieObservable beta

namespace BoundedSouriauModularFamily

variable {LieAlgebra : Type*}
variable (F : BoundedSouriauModularFamily (E := E) LieAlgebra)

/-- Associated bounded modular operator proxy `Δ = exp(-Kmod)`. -/
@[rep_depth operator]
noncomputable def modularDelta : EndH :=
  modularDeltaFromHamiltonian (E := E) F.modularHamiltonianK

@[rep_depth operator]
theorem modularDelta_eq_betaFlow_one :
    F.modularDelta = modularBetaFlow (E := E) F.modularHamiltonianK 1 := by
  simp [modularDelta]

/-- The family-level `Δ - I` deviation. -/
@[rep_depth operator]
noncomputable def deltaDeviation : EndH :=
  modularDeviation (E := E) F.modularDelta

@[rep_depth operator]
theorem deltaDeviation_eq_betaOneDeviation :
    F.deltaDeviation = modularBetaDeviation (E := E) F.modularHamiltonianK 1 := by
  simp [deltaDeviation, modularDelta, modularBetaDeviation, modularDeviation, modularIdentity]

@[rep_depth thermo]
theorem modularHamiltonianK_eq_lieObservable_beta_theorem :
    F.modularHamiltonianK = F.lieObservable F.beta :=
  F.modularHamiltonianK_eq_lieObservable_beta

end BoundedSouriauModularFamily

/--
Souriau/Bregman packet on the bounded modular operator lane.

The Bregman divergence is operatorial, but scalar-valued only after the chosen
product/readout socket is supplied.
-/
@[rep_depth thermo]
structure SouriauOperatorialBregmanPacket (LieAlgebra : Type*) where
  family : BoundedSouriauModularFamily (E := E) LieAlgebra
  socket : OperatorPrimalDualSocket EndH
  potential : EndH → ℝ
  gradient : EndH → EndH

namespace SouriauOperatorialBregmanPacket

variable {LieAlgebra : Type*}
variable (P : SouriauOperatorialBregmanPacket (E := E) LieAlgebra)

/-- Operatorial Bregman divergence for the packet potential. -/
@[rep_depth thermo]
def divergence (X Y : EndH) : ℝ :=
  operatorBregman P.socket P.potential P.gradient X Y

@[simp, rep_depth thermo]
theorem divergence_self (X : EndH) :
    P.divergence X X = 0 := by
  simp [divergence]

/-- Bregman divergence after passing to the modular deviations `Δ - I`. -/
@[rep_depth thermo]
noncomputable def modularDeviationDivergence (Δ₁ Δ₀ : EndH) : ℝ :=
  P.divergence (modularDeviation (E := E) Δ₁) (modularDeviation (E := E) Δ₀)

@[simp, rep_depth thermo]
theorem modularDeviationDivergence_self (Δ : EndH) :
    P.modularDeviationDivergence Δ Δ = 0 := by
  simp [modularDeviationDivergence]

/-- Family-level modular deviation divergence at the same Souriau beta point is zero. -/
@[simp, rep_depth thermo]
theorem family_deltaDeviation_divergence_self :
    P.divergence P.family.deltaDeviation P.family.deltaDeviation = 0 := by
  simp [divergence]

end SouriauOperatorialBregmanPacket

end BoundedDoubledModular

end InfoGeometry.Canonical.SouriauModularBregmanOperator
