AbsQ := x -> AbsInt(NumeratorRat(x))/DenominatorRat(x);
y := -12/125;; sy := 37/1000;; yr := -51/500;; syr := 41/1000;;
obs := 90;; sobs := 35;; weighted := 72;; sweighted := 26;; pred := 190;;
b11 := 4/5;; b3k := 19/100;; b3o := 1/100;; b3 := b3k+b3o;;
weightedA := b11*(-2/3) + b3*(1/3);;
if AbsQ(y)/sy <> 96/37 then Error("weighted significance"); fi;
if AbsQ(yr)/syr <> 102/41 then Error("recoil significance"); fi;
if [obs-sobs,obs+sobs] <> [55,125] then Error("observed interval"); fi;
if [weighted-sweighted,weighted+sweighted] <> [46,98] then Error("weighted interval"); fi;
if obs/pred <> 9/19 then Error("observed ratio"); fi;
if weighted/pred <> 36/95 then Error("weighted ratio"); fi;
if 1-obs/pred <> 10/19 then Error("observed deficit"); fi;
if 1-weighted/pred <> 59/95 then Error("weighted deficit"); fi;
if b11+b3k+b3o <> 1 then Error("branch partition"); fi;
if b3 <> 1/5 then Error("branch total"); fi;
if weightedA <> -7/15 then Error("GT weighted asymmetry"); fi;
edges := ["decays_to","measures","implies","compares_with","motivates"];
if Length(edges) <> 5 then Error("edges"); fi;
Print(rec(yWeighted:=y, ySignificance:=AbsQ(y)/sy, recoilSignificance:=AbsQ(yr)/syr, observedInterval:=[obs-sobs,obs+sobs], weightedInterval:=[weighted-sweighted,weighted+sweighted], observedToPredicted:=obs/pred, weightedToPredicted:=weighted/pred, weightedGTAsymmetry:=weightedA, edges:=Length(edges)),"\n");
QUIT;
