needsPackage "Dmodules";
R = QQ[x11,x12,x21,x22,y11,y12,y21,y22,z11,z12,z21,z22,f11,f12,f21,f22,b,c,Q];
X = matrix(R, {{x11,x12},{x21,x22}});
Y = matrix(R, {{y11,y12},{y21,y22}});
Z = matrix(R, {{z11,z12},{z21,z22}});
F = matrix(R, {{f11,f12},{f21,f22}});
LieBracket = (A,B) -> A*B - B*A;
Trace2 = A -> A_(0,0) + A_(1,1);
KKS = (F,A,B) -> Trace2(F*LieBracket(A,B));
IsZeroMatrix = M -> all(flatten entries M, e -> e == 0_R);
if not IsZeroMatrix LieBracket(X,X) then error "self commutator failed";
if not IsZeroMatrix (LieBracket(X,Y) + LieBracket(Y,X)) then error "skew commutator failed";
if not IsZeroMatrix (LieBracket(X,LieBracket(Y,Z)) + LieBracket(Y,LieBracket(Z,X)) + LieBracket(Z,LieBracket(X,Y))) then error "Jacobi failed";
if KKS(F,X,X) != 0_R then error "KKS alternating failed";
if KKS(F,X,Y) + KKS(F,Y,X) != 0_R then error "KKS skew failed";
if KKS(F,X,LieBracket(Y,Z)) + KKS(F,Y,LieBracket(Z,X)) + KKS(F,Z,LieBracket(X,Y)) != 0_R then error "Souriau cocycle failed";
Massieu = t -> t^2/2;
if Massieu(b+1) - 2*Massieu(b) + Massieu(b-1) != 1_R then error "Fisher finite difference failed";
if c*Q - c*Q != 0_R then error "Legendre affine readout failed";
W = QQ[t, dt, WeylAlgebra => {t => dt}];
if dt*t - t*dt != 1_W then error "Dmodules Weyl lane failed";
print "barbaresco SPIGL2020 Macaulay2+Dmodules certificate: ok";
