needsPackage "Dmodules";
Tx = matrix(QQ, {{0,1},{1,0}});
Ty = matrix(QQ, {{1,0},{0,-1}});
I2 = id_(QQ^2);
minusI = -I2;
Txy = Tx*Ty;
if Tx*Tx != I2 then error "Tx square failed";
if Ty*Ty != I2 then error "Ty square failed";
if Tx*Ty != -(Ty*Tx) then error "anticommutation failed";
if Tx*Ty != minusI*(Ty*Tx) then error "central sign commutation failed";
if Txy*Txy != minusI then error "mixed channel square failed";
R = QQ[kx, ky, dx, WeylAlgebra => {kx => dx}];
if dx*kx - kx*dx != 1_R then error "Dmodules Weyl lane failed";
S = QQ[kx, ky];
glide = matrix(S, {{kx+1}, {-ky}});
glideInv = matrix(S, {{kx-1}, {-ky}});
yLoop = matrix(S, {{kx}, {ky+2}});
yLoopInv = matrix(S, {{kx}, {ky-2}});
if matrix(S, {{(kx-1)+1}, {-(-ky)}}) != matrix(S, {{kx}, {ky}}) then error "glide inverse failed";
if matrix(S, {{(kx-1)+1}, {-(-ky+2)}}) != yLoopInv then error "Klein conjugacy failed";
print "brillouin Klein bottle manifold Macaulay2+Dmodules certificate: ok";
