import proofs.FiniteMatrixKnillLaflamme
import proofs.PeirceTensorQEC
import proofs.CuntzWordSpaceQEC
import proofs.CuntzPeirceLogicalQubit

namespace CuntzPeirceQEC

#check CuntzPeirceLogicalCorner.logicalMatrixUnit_mul
#check CuntzPeirceLogicalCorner.logicalMatrixUnit_star
#check CuntzPeirceLogicalCorner.logicalMatrixUnit_diagonal_sum
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_mul
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_star
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_diagonal_sum
#check CuntzPeirceLogicalCorner.logicalMatrixUnit_error_compression
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_error_compression
#check LogicalWheelerDeWittHamiltonian.logicalWDW_constraint

end CuntzPeirceQEC
