needsPackage "Dmodules";
c = 5/4;
s = 3/4;
I2 = id_(QQ^2);
Z2 = 0*I2;
Pp = matrix(QQ, {{1,0},{0,0}});
Pm = matrix(QQ, {{0,0},{0,1}});
eta = Pp - Pm;
L = c*I2 - s*eta;
R = c*I2 + s*eta;
if Pp + Pm != I2 then error "partition failed";
if Pp*Pp != Pp then error "Pplus idempotent failed";
if Pm*Pm != Pm then error "Pminus idempotent failed";
if Pp*Pm != Z2 then error "orthogonality failed";
if Pm*Pp != Z2 then error "orthogonality failed";
if eta*eta != I2 then error "eta square failed";
if c*c - s*s != 1 then error "hyperbolic identity failed";
if L*R != I2 then error "left/right inverse failed";
if R*L != I2 then error "right/left inverse failed";
E00 = matrix(QQ, {{1,0},{0,0}});
E01 = matrix(QQ, {{0,1},{0,0}});
E10 = matrix(QQ, {{0,0},{1,0}});
E11 = matrix(QQ, {{0,0},{0,1}});
for X in {E00,E01,E10,E11} do (
  Delta := L*X*R;
  S := L*transpose Delta*R;
  if S != transpose X then error "Tomita cancellation failed";
);
Rweyl = QQ[x, dx, WeylAlgebra => {x => dx}];
if dx*x - x*dx != 1_Rweyl then error "Dmodules Weyl lane failed";
print "cuntz Tomita-Takesaki Macaulay2+Dmodules certificate: ok";
