# cuntz_algebra_qubits.sage
# Formulation of the Cuntz algebra O_2 isometries representing infinite binary qubit words
# (symbolic dynamics over the Cantor set).

print("Initializing Cuntz Algebra O_2...")

# Define the non-commutative polynomial ring for the isometries S1, S2 and their adjoints S1_star, S2_star
F.<S1, S2, S1_star, S2_star> = FreeAlgebra(QQ, 4)

# Cuntz algebra relations:
# S1_star * S1 = 1
# S2_star * S2 = 1
# S1 * S1_star + S2 * S2_star = 1

print("Cuntz algebra O_2 relations defined:")
print("S1* * S1 = 1")
print("S2* * S2 = 1")
print("S1 * S1* + S2 * S2* = 1")

# In this algebraic setting, the infinite binary qubit words correspond to the symbolic 
# dynamics generated by the shifts S1 and S2 over the Cantor set state space.
