import proofs.FiniteMatrixKnillLaflamme
import proofs.PeirceTensorQEC
import proofs.CuntzWordSpaceQEC
import proofs.CuntzPeirceLogicalQubit
import proofs.CuntzSyndromeRecovery

namespace CuntzPeirceQEC

#check CuntzWordSpaceQEC.logicalMatrixUnit_mul
#check CuntzWordSpaceQEC.logicalMatrixUnit_star
#check CuntzWordSpaceQEC.logicalMatrixUnit_sum_diagonal
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_mul
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_star
#check CuntzPeirceLogicalCorner.cuntzLogicalMatrixUnit_error_compression

end CuntzPeirceQEC
