-- D-module mapping the convex optimization gradient flow of the entropy functional
needsPackage "Dmodules"

-- Phase space variables x (position/probability) and p (momentum/dual)
W = QQ[x1, x2, p1, p2, dx1, dx2, dp1, dp2, WeylAlgebra => {x1=>dx1, x2=>dx2, p1=>dp1, p2=>dp2}]

-- Gradient flow for a quadratic approximation of entropy H = 1/2(x1^2 + x2^2)
-- dx/dt = -grad H(x)  =>  dx1/dt = -x1, dx2/dt = -x2
-- This is a vector field V = -x1*dx1 - x2*dx2

-- D-module generated by the differential operators annihilating the distribution
-- L = d/dt + div(V \cdot) = d/dt - x1 dx1 - x2 dx2 - 2
-- We consider the stationary distribution D-ideal:
I = ideal(dx1 + x1, dx2 + x2)

-- Compute the Holonomic Rank
holonomicRank(I)

-- Ext module to analyze the convex optimization flow
E = Ext^2(W^1/I, W)

print("D-module for entropy gradient flow initialized.");
