-- dmodule_entropy.m2
-- Construct the D-module mapping the strictly positive entropy production of the Modular Boltzmann Operator

needsPackage "Dmodules"

-- Define the Weyl algebra
W = QQ[t, x, Dt, Dx, WeylAlgebra => {{t, Dt}, {x, Dx}}]

-- Modular Boltzmann Operator K = -\ln \Delta (Symbolic representation)
-- We represent the flow related to entropy production. 
-- In D-module theory, we can look at the operator corresponding to t*Dt + x*Dx (Euler operator) 
-- representing scaling/flow, and add an entropy production term.
K = t*Dt - x*Dx + 1

-- Define the ideal generated by the operator K
I = ideal(K)

-- Calculate the holonomic rank and other properties
M = W^1 / I
print "D-module for Modular Boltzmann Operator defined."
print "Operator K:"
print K
