FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libvulkan1 \
        mesa-vulkan-drivers \
        libgomp1 \
        libc6 \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/opt/llama-vulkan/llama-server"]
