from sage.all import *

print("=== Gluing D4 Root Systems via Cl(1,1) to form D5 ===")
print("Theorem: Cl(5,5) ≅ Cl(1,1) ⊗ Cl(4,4)")
print("Lie Algebra: so(5,5) = so(4,4) ⊕ so(1,1) ⊕ (Vector(8) ⊗ 2)")

# D5 root system (so(5,5) dimension 45)
rs5 = RootSystem("D5")
roots5 = rs5.root_lattice().roots()

# D4 root system (so(4,4) dimension 28)
rs4 = RootSystem("D4")
roots4 = rs4.root_lattice().roots()

print(f"\nTotal Roots in D5: {len(roots5)}")
print(f"Total Roots in D4: {len(roots4)}")

# The Cartan subalgebra dimension
cartan_dim_5 = 5
cartan_dim_4 = 4

print(f"\nDimension of D5: {len(roots5) + cartan_dim_5} (40 roots + 5 Cartan)")
print(f"Dimension of D4: {len(roots4) + cartan_dim_4} (24 roots + 4 Cartan)")

print("\n--- Decomposition via Cl(1,1) Modular Atom ---")
print("We split the 45 generators of D5 as follows:")
print("1. The core D4 subalgebra (so(4,4)): 28 generators")
print("2. The Cl(1,1) modular atom core (so(1,1)): 1 generator (the 5th Cartan element)")
print("3. The gluing elements connecting D4 and Cl(1,1): 16 generators")

gluing_roots_count = len(roots5) - len(roots4)
print(f"\nNumber of 'gluing' roots: {gluing_roots_count}")

print("\nIn terms of D4 representations, by Cartan's Triality:")
print("The 16 gluing roots transform exactly as 2 copies of the 8-dimensional representation of D4!")
print("These are generated by the tensor product of the Cl(1,1) 2D vector space with the D4 8D vector space: 2 x 8 = 16.")
print("\nThus, Cl(1,1) acts as the 'modular atom' that bridges and clones the D4 structure.")
print("The involution operators (tripotents of Cl(1,1) ~ M2(R)) determine exactly how these 16 roots partition into chiral/anti-chiral or physical/ghost sectors!")
