R = QQ[yQ,yu,yd,yL,ye,ynu,q,dq, WeylAlgebra => {q=>dq}];
stablePage=3; e2Rank=8; survivorCount=8;
su3Generators=8; su2Generators=3; smRank=4; smGenerators=12; cartanGenerators=4; ladderCount=8;
assert(stablePage==3 and e2Rank==8 and survivorCount==8);
assert(su3Generators==8 and su2Generators==3 and smRank==4 and smGenerators==12 and cartanGenerators==4 and ladderCount==8);
C2su3Fund=4/3; C2su3Adj=3; C2su2Doublet=3/4; assert(C2su3Fund==4/3 and C2su2Doublet==3/4);
YQ=1/6; Yu=2/3; Yd=-1/3; YL=-1/2; Ye=-1; Ynu=0;
upCharge=1/2+YQ; downCharge=-1/2+YQ; neutrinoCharge=1/2+YL; electronCharge=-1/2+YL;
assert(upCharge==2/3 and downCharge==-1/3 and neutrinoCharge==0 and electronCharge==-1);
weylCount=6+3+3+2+1+1; assert(weylCount==16);
colorAnomaly=2*YQ-Yu-Yd; weakAnomaly=3*YQ+YL;
gravTrace=6*YQ-3*Yu-3*Yd+2*YL-Ye-Ynu;
cubicTrace=6*YQ^3-3*Yu^3-3*Yd^3+2*YL^3-Ye^3-Ynu^3;
assert(colorAnomaly==0 and weakAnomaly==0 and gravTrace==0 and cubicTrace==0);
I = ideal(q*dq - dq*q - 1); assert(numgens I == 1);
anomalyIdeal=ideal(2*yQ-yu-yd,3*yQ+yL,6*yQ-3*yu-3*yd+2*yL-ye-ynu,6*yQ^3-3*yu^3-3*yd^3+2*yL^3-ye^3-ynu^3);
assert(numgens anomalyIdeal==4);
edges={"extracts","generates_color","generates_weak","generates_hypercharge","carries","cancels"}; assert(#edges==6);
print {"stablePage",stablePage,"e2Rank",e2Rank,"survivorCount",survivorCount,"su3Generators",su3Generators,"su2Generators",su2Generators,"smRank",smRank,"smGenerators",smGenerators,"cartanGenerators",cartanGenerators,"ladderCount",ladderCount,"C2su3Fund",C2su3Fund,"C2su2Doublet",C2su2Doublet,"upCharge",upCharge,"downCharge",downCharge,"neutrinoCharge",neutrinoCharge,"electronCharge",electronCharge,"weylCount",weylCount,"colorAnomaly",colorAnomaly,"weakAnomaly",weakAnomaly,"gravTrace",gravTrace,"cubicTrace",cubicTrace,"dmoduleCCRGenerators",numgens I,"anomalyIdealGenerators",numgens anomalyIdeal,"graphEdges",#edges};
