Trip := d -> d*(d-1)*(d+1);
MobiusInv := function(e,o) return [(e+o)/2,(e-o)/2]; end;
MobiusRec := function(x,y) return [x+y,x-y]; end;
KleinAvg := function(a,b,c,d) return (a+b+c+d)/4; end;
octDim:=8;; imaginaryDim:=7;; orbitDim:=6;; g2Dim:=14;; su3Dim:=8;;
fanoLines:=7;; fanoDirectedProducts:=21;; associatorObstruction:=2;;
if octDim<>8 or imaginaryDim<>7 or orbitDim<>6 then Error("dims"); fi;
if g2Dim-su3Dim<>6 then Error("g2orbit"); fi;
if fanoLines<>7 or fanoDirectedProducts<>21 then Error("fano"); fi;
if associatorObstruction=0 then Error("assoc"); fi;
if -3*5<>-15 then Error("kks"); fi;
if [6,0][1]+[6,0][2]<>6 or [3,3][1]+[3,3][2]<>6 or [2,4][1]+[2,4][2]<>6 then Error("sig"); fi;
if 24+1+10+10<>45 then Error("so55su5"); fi;
if 1+10+5<>16 or 5+10+1<>16 then Error("spin"); fi;
mi:=MobiusInv(7,3);; if MobiusRec(mi[1],mi[2])<>[7,3] then Error("mobius"); fi;
if KleinAvg(1,2,3,4)<>5/2 then Error("klein"); fi;
if List([-1,0,1],Trip)<>[0,0,0] then Error("trip"); fi;
edges:=["generalizes_to","obstructed_by","induces","split_induces","bridges_to"];
Print(rec(octonionDim:=octDim,imaginaryDim:=imaginaryDim,orbitDim:=orbitDim,g2su3Orbit:=g2Dim-su3Dim,fanoLines:=fanoLines,fanoDirectedProducts:=fanoDirectedProducts,associatorObstruction:=associatorObstruction,kksSample:=-15,so55su5Partition:=45,spinEven16:=16,spinOdd16:=16,kleinAverage:=5/2,tripotentRoots:=[-1,0,1],edges:=Length(edges)),"\n");
QUIT;
