R = QQ[m,Eexact,Eadapt,delta];
octDim=8; imaginaryDim=7; orbitDim=6; g2Dim=14; su3Dim=8;
fanoLines=7; fanoDirectedProducts=21;
classicalFlags=3;
associatorObstruction=2;
nonSplitSignature={6,0}; splitSignature33={3,3}; splitSignature24={2,4};
assert(octDim==8 and imaginaryDim==7 and orbitDim==6);
assert(g2Dim-su3Dim==6);
assert(fanoLines==7 and fanoDirectedProducts==21);
assert(associatorObstruction != 0);
assert(nonSplitSignature#0+nonSplitSignature#1==6);
assert(splitSignature33#0+splitSignature33#1==6);
assert(splitSignature24#0+splitSignature24#1==6);
assert(-(3*5)==-15);
assert(24+1+10+10==45);
assert(1+10+5==16 and 5+10+1==16);
assert((7+3)/2 + (7-3)/2 == 7);
assert((7+3)/2 - ((7-3)/2) == 3);
assert((1+2+3+4)/4==5/2);
tripPoly=d -> d*(d-1)*(d+1);
assert(tripPoly(-1)==0 and tripPoly(0)==0 and tripPoly(1)==0);
C1=-m^2; stiffness=-C1; assert(stiffness==m^2);
W = QQ[q,dq, WeylAlgebra => {q=>dq}];
I = ideal(q*dq - dq*q - 1);
assert(numgens I == 1);
M = coker matrix{{Eexact*delta - Eexact + Eadapt}};
edges={"generalizes_to","obstructed_by","induces","split_induces","bridges_to"};
assert(#edges==5);
print {"octonionDim",octDim,"imaginaryDim",imaginaryDim,"orbitDim",orbitDim,"g2su3Orbit",g2Dim-su3Dim,"fanoLines",fanoLines,"associatorObstruction",associatorObstruction,"kksSample",-15,"so55su5Partition",45,"spinEven16",16,"spinOdd16",16,"kleinAverage",5/2,"dmoduleCCRGenerators",numgens I,"graphEdges",#edges};
