R = QQ[ft,deltaR,deltaC,Eexact,Eadapt,delta];
ckmSum = (3/5)^2 + (4/5)^2 + 0^2;
ckmDefect = ckmSum - 1;
assert(ckmSum == 1);
assert(ckmDefect == 0);
assert(10/100 == 1/10);
assert(100/100 == 1);
correctedFermi0 = 2*(1-0);
correctedFermi1pct = 2*(1-1/100);
assert(correctedFermi0 == 2);
assert(correctedFermi1pct == 99/50);
assert(ft*(1+0)*(1-0) == ft);
exactBeta = 7/13;
exactRadius = -7/13;
assert(exactBeta + exactRadius == 0);
assert(3/10 + (-1/5) == 1/10);
assert(2/40 == 1/20);
assert(20/4 == 5);
W = QQ[x,dx, WeylAlgebra => {x=>dx}];
I = ideal(x*dx - dx*x - 1);
assert(numgens I == 1);
M = coker matrix{{Eexact*delta - Eexact + Eadapt}};
edges={"constrains","measures","corrects","probes","cancels_under_exact_isospin"};
assert(#edges == 5);
print {"ckmSum", ckmSum, "ckmDefect", ckmDefect, "deltaCPercentRange", {1/10,1}, "correctedFermi1pct", correctedFermi1pct, "exactIsospinCombined", 0, "isbWitness", 1/10, "dmoduleCCRGenerators", numgens I, "graphEdges", #edges};
