V2 := x -> x*x;
CkmSum := function(vud,vus,vub) return V2(vud)+V2(vus)+V2(vub); end;
CkmDefect := function(vud,vus,vub) return CkmSum(vud,vus,vub)-1; end;
PermyriadToPercent := x -> x/100;
CorrectedFermi := dc -> 2*(1-dc);
Combined := function(beta,radius) return beta+radius; end;
ExactPair := x -> [x,-x];
Deviation := function(beta,radius) return Combined(beta,radius); end;
IsoScale := function(nminusz,A) return nminusz/A; end;
CoulombScale := function(Z,R) return Z/R; end;
if CkmSum(3/5,4/5,0) <> 1 then Error("ckm sum"); fi;
if CkmDefect(3/5,4/5,0) <> 0 then Error("ckm defect"); fi;
if PermyriadToPercent(10) <> 1/10 then Error("delta min"); fi;
if PermyriadToPercent(100) <> 1 then Error("delta max"); fi;
if CorrectedFermi(0) <> 2 then Error("fermi zero"); fi;
if CorrectedFermi(1/100) <> 99/50 then Error("fermi 1pct"); fi;
if Combined(ExactPair(7/13)[1],ExactPair(7/13)[2]) <> 0 then Error("exact isospin"); fi;
if Combined(3/10,-1/5) <> 1/10 then Error("witness"); fi;
if Deviation(3/10,-1/5) <> 1/10 then Error("deviation"); fi;
if IsoScale(2,40) <> 1/20 then Error("iso scale"); fi;
if CoulombScale(20,4) <> 5 then Error("coulomb scale"); fi;
edges := ["constrains","measures","corrects","probes","cancels_under_exact_isospin"];
Print(rec(ckmSum:=CkmSum(3/5,4/5,0), ckmDefect:=CkmDefect(3/5,4/5,0), deltaCPercentRange:=[1/10,1], correctedFermi1pct:=CorrectedFermi(1/100), exactIsospinCombined:=0, isbWitness:=Deviation(3/10,-1/5), isovectorScale:=IsoScale(2,40), coulombScale:=CoulombScale(20,4), edges:=Length(edges)),"\n");
QUIT;
