Sym := n -> n*(n+1)/2;
Anti := n -> n*(n-1)/2;
s := 1;; d := 5;; modes := s+d;;
u6 := modes*modes;; partition := 1+d+d+d*d;;
sp6 := Sym(3)+Sym(3)+3*3;;
collective := Anti(3)+Sym(3)+Sym(3)+Sym(3);;
raising := [1/2,-1/2,1/2,2];; lowering := [1/2,-1/2,-1/2,2];;
plus := [raising[1]+lowering[1], raising[2]+lowering[2], raising[3]+lowering[3]];;
Tdiff := raising[3]-lowering[3];;
C1 := m -> -m*m;; Kspring := C -> -C;; Vspring := function(m,lam) return m*m*lam*lam/2; end;; Bracket := C -> 2*C;; Ephonon := function(omega,n) return (n+1/2)*omega; end;;
UDim := n -> n*n;; SUDim := n -> n*n-1;; SODim := n -> n*(n-1)/2;; SPDimHalfRank := n -> n*(2*n+1);;
DeltaNat := function(i,j) if i=j then return 1; else return 0; fi; end;;
MatrixFirst := function(i,j,k,l) return DeltaNat(j,k); end;;
MatrixSecond := function(i,j,k,l) return -DeltaNat(l,i); end;;
if modes<>6 then Error("modes"); fi;
if u6<>36 then Error("u6"); fi;
if partition<>36 then Error("partition"); fi;
if Sym(3)<>6 or Anti(3)<>3 then Error("pairs"); fi;
if sp6<>21 or collective<>21 then Error("sp6"); fi;
if plus<>[1,-1,0] then Error("plus"); fi;
if Tdiff<>1 then Error("Tdiff"); fi;
if Kspring(C1(3))<>9 then Error("stiffness"); fi;
if Kspring(C1(0))<>0 then Error("massless"); fi;
if Vspring(3,2)<>18 then Error("potential"); fi;
if Bracket(C1(3))<>-18 then Error("bracket"); fi;
if Ephonon(5,1)<>15/2 then Error("energy"); fi;
if UDim(6)<>36 or SUDim(3)<>8 then Error("unitary dims"); fi;
if SODim(6)<>15 or SODim(5)<>10 or SODim(3)<>3 then Error("orthogonal dims"); fi;
if SPDimHalfRank(3)<>21 then Error("sp6 dim"); fi;
if [MatrixFirst(1,2,2,3),MatrixSecond(1,2,2,3)]<>[1,0] then Error("E12E23"); fi;
if [MatrixFirst(1,2,2,1),MatrixSecond(1,2,2,1)]<>[1,-1] then Error("E12E21"); fi;
edges := ["represented_by","counted_by","represented_by_sp6","decomposes_into","quantizes"];
Print(rec(ibmModes:=modes,u6Generators:=u6,ibmPartition:=partition,sp6Generators:=sp6,collectiveTensorCertificate:=collective,raisingPlusLowering:=plus,raisingMinusLoweringT:=Tdiff,springPotentialSample:=18,onePhononEnergy:=15/2,u6Dim:=UDim(6),su3Dim:=SUDim(3),so6Dim:=SODim(6),so5Dim:=SODim(5),so3Dim:=SODim(3),sp6RDim:=SPDimHalfRank(3),matrixE12E23:=[MatrixFirst(1,2,2,3),MatrixSecond(1,2,2,3)],matrixE12E21:=[MatrixFirst(1,2,2,1),MatrixSecond(1,2,2,1)],edges:=Length(edges)),"\n");
QUIT;
