

# This file was *autogenerated* from the file proofs/pin55_full_real.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_32 = Integer(32); _sage_const_10 = Integer(10)#!/usr/bin/env sage
# Exact SageMath certificate for the real Cl(5,5) coordinate reflections.

R = QQ
I2 = identity_matrix(R, _sage_const_2 )
X = matrix(R, [[_sage_const_0 , _sage_const_1 ], [_sage_const_1 , _sage_const_0 ]])
Y = matrix(R, [[_sage_const_0 , _sage_const_1 ], [-_sage_const_1 , _sage_const_0 ]])
Z = diagonal_matrix(R, [_sage_const_1 , -_sage_const_1 ])

def kron_all(parts):
    out = matrix(R, [[_sage_const_1 ]])
    for part in parts:
        out = out.tensor_product(part)
    return out

def gamma(local, i):
    return kron_all([Z] * i + [local] + [I2] * (_sage_const_4  - i))

gammas = [gamma(X, i) for i in range(_sage_const_5 )] + [gamma(Y, i) for i in range(_sage_const_5 )]
signs = [_sage_const_1 ] * _sage_const_5  + [-_sage_const_1 ] * _sage_const_5 
I32 = identity_matrix(R, _sage_const_32 )
eta = diagonal_matrix(R, signs)

for a in range(_sage_const_10 ):
    for b in range(_sage_const_10 ):
        expected = _sage_const_2  * signs[a] * I32 if a == b else zero_matrix(R, _sage_const_32 )
        assert gammas[a] * gammas[b] + gammas[b] * gammas[a] == expected

reflections = []
for a in range(_sage_const_10 ):
    ga = gammas[a]
    ga_inv = signs[a] * ga
    r = zero_matrix(R, _sage_const_10 )
    for b in range(_sage_const_10 ):
        image = -ga * gammas[b] * ga_inv
        for c in range(_sage_const_10 ):
            r[c, b] = (gammas[c] * image).trace() / (_sage_const_32  * signs[c])
    expected = identity_matrix(R, _sage_const_10 )
    expected[a, a] = -_sage_const_1 
    assert r == expected
    assert r.transpose() * eta * r == eta
    assert r.det() == -_sage_const_1 
    reflections.append(r)

# PBW monomials give the expected 2^10-dimensional matrix basis.
monomials = []
for mask in range(_sage_const_2 **_sage_const_10 ):
    value = I32
    for a in range(_sage_const_10 ):
        if mask & (_sage_const_1  << a):
            value *= gammas[a]
    monomials.append(vector(R, value.list()))
assert matrix(R, monomials).rank() == _sage_const_2 **_sage_const_10 

images = set()
kernel_count = _sage_const_0 
for mask in range(_sage_const_2 **_sage_const_10 ):
    image = identity_matrix(R, _sage_const_10 )
    for a in range(_sage_const_10 ):
        if mask & (_sage_const_1  << a):
            image *= reflections[a]
    images.add(tuple(image.list()))
    if image == identity_matrix(R, _sage_const_10 ):
        kernel_count += _sage_const_2 
assert len(images) == _sage_const_2 **_sage_const_10 
assert kernel_count == _sage_const_2 

print("pin55_full_real.sage: PASS")
print("Cl(5,5) matrix algebra dimension:", _sage_const_2 **_sage_const_10 )
print("coordinate reflections:", len(reflections))
print("metric inertia: (5,5)")
print("signed monomial image order:", len(images))
print("signed monomial kernel order:", kernel_count)

