import InfoGeometry.Canonical.AnomalyStrainRotation
import InfoGeometry.Canonical.AnomalyStrainRotationWitness
import InfoGeometry.Canonical.DiracKahlerSplitCurvature
import InfoGeometry.Canonical.KreinFlowConservation
import InfoGeometry.Canonical.NavierStokesPolarizedTransfers
import InfoGeometry.Canonical.PolarizedShearSpinEvolution
import InfoGeometry.Canonical.PolarizedShearSpinFrame
import InfoGeometry.Canonical.PolarizedShearSpinSolution
import InfoGeometry.Canonical.SpinorHydrodynamicReadout
import InfoGeometry.Canonical.SpinorReadoutOscillation
import InfoGeometry.Canonical.SpinorReadoutRegularity
import InfoGeometry.Canonical.SquareZeroStrainRotation
import InfoGeometry.Canonical.WeakValueKreinBoundary
import InfoGeometry.Canonical.WeakValueKreinGeometry
import InfoGeometry.Canonical.WeakValuePoleCriterion
import InfoGeometry.Canonical.WeakValuePoleExamples

#print axioms InfoGeometry.Canonical.AnomalyStrainRotation.anomaly_factorization
#print axioms InfoGeometry.Canonical.AnomalyStrainRotation.anomaly_mul_self_eq_zero
#print axioms InfoGeometry.Canonical.AnomalyStrainRotation.anomaly_eq_zero_of_regularization_selfAdjoint
#print axioms InfoGeometry.Canonical.AnomalyStrainRotation.anomaly_strain_rotation
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.source_idempotent
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.source_moorePenrose
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.source_drazin
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.source_anomaly
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.source_anomaly_ne_zero
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.spectral_readout_not_selfAdjoint
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.shear_mul_self_eq_zero
#print axioms InfoGeometry.Canonical.AnomalyStrainRotationWitness.normalized_split_pair
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.plus_square_curvature
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.minus_square_curvature
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.split_anticommutator_curvature
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.differential_laplacian_curvature
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.negativeDirac_square
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.dirac_negativeDirac_anticommutator
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.negativeDirac_anticommutes_chirality
#print axioms InfoGeometry.Canonical.DiracKahlerSplitCurvature.differential_commutes_laplacian
#print axioms InfoGeometry.Canonical.KreinFlowConservation.hasDerivAt_krein_square
#print axioms InfoGeometry.Canonical.KreinFlowConservation.krein_square_conserved
#print axioms InfoGeometry.Canonical.KreinFlowConservation.nonnull_preserved
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.baseLift_apply
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.upward_apply
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.downward_apply
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.upward_comp_upward
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.downward_comp_downward
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.upward_comp_downward
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.downward_comp_upward
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.upward_injective
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.downward_injective
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.pairedGenerator_sq
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.legacy_backwardWave_eq_zero
#print axioms InfoGeometry.Canonical.NavierStokesPolarizedTransfers.legacy_twinWaveHelicity_eq_zero
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energy_evolution
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energy_le_initial
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.coordinate_square_bound
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.generator_eq
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.generator_sq
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.plusMinus_corner
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.minusPlus_corner
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.generator_eq_offDiagonal_corners
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.symmetric_part
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.skew_part
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energy_lower_bound
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energy_upper_bound
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energy_nonneg
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energy_pos
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.velocity_zero_coordinate
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.velocity_one_coordinate
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energyRate_velocity
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.energyRate_velocity_nonpos
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.hasDerivAt_energy
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.frequency_exists
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.hasDerivAt_oscillator
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.solution_zero
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.hasDerivAt_solution
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.solution_energy
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.solution_ne_zero
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.solution_coordinate_bound
#print axioms InfoGeometry.Canonical.PolarizedShearSpinFrame.exists_bounded_solution
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.density_eq_inner
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.density_pos_iff
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_inner_im_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_inner_re_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_current_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_readout_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.readout_eq_same_state_weak_expression
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.hasDerivAt_density
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.hasDerivAt_current
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.hasDerivAt_readout
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.density_spinor
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.spinor_ne_zero
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.hasDerivAt_spinor_y
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.velocityComponent_eq
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.velocityComponent_nonneg
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.abs_velocityComponent_le
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.hasDerivAt_velocityComponent
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.hasDerivAt_velocityComponent_zero
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.deriv_velocityComponent_zero
#print axioms InfoGeometry.Canonical.SpinorReadoutOscillation.exists_arbitrarily_large_readout_derivative
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_densityRate_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_currentRate_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_readoutRate_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_deriv_readout_le
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.spatialReadout_eq_of_hasFDerivAt
#print axioms InfoGeometry.Canonical.SpinorHydrodynamicReadout.abs_spatialReadout_le
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.rangeProjector_mul_regularization
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.commutator_factorization
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.rangeProjector_mul_commutator
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.commutator_mul_rangeProjector
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.commutator_mixed_peirce_corner
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.commutator_mul_self_eq_zero
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.commutator_eq_zero_of_regularization_selfAdjoint
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.square_zero_star_pair
#print axioms InfoGeometry.Canonical.SquareZeroStrainRotation.square_zero_scaled_star_pair
#print axioms InfoGeometry.Canonical.WeakValueKreinBoundary.overlap_boundaryState
#print axioms InfoGeometry.Canonical.WeakValueKreinBoundary.weakValue_none_iff_two_quadratics
#print axioms InfoGeometry.Canonical.WeakValueKreinBoundary.identity_boundary_null_and_regular
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.diagonalQuadratic_eq_norm_difference
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.swapQuadratic_eq_two_re_overlap
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.phaseSwapQuadratic_eq_two_im_overlap
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.overlap_eq_zero_iff_two_swap_quadratics
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.phaseSwap_involutive
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.phaseSwap_modular_j_anticommutes
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.phaseSwap_eq_I_smul_complex_i
#print axioms InfoGeometry.Canonical.WeakValueKreinGeometry.equal_components_null_with_nonzero_overlap
#print axioms InfoGeometry.Canonical.WeakValuePoleCriterion.abs_deriv_real_ratio_le
#print axioms InfoGeometry.Canonical.WeakValuePoleCriterion.tendsto_denominator_slope
#print axioms InfoGeometry.Canonical.WeakValuePoleCriterion.eventually_denominator_ne_zero
#print axioms InfoGeometry.Canonical.WeakValuePoleCriterion.tendsto_complex_residue
#print axioms InfoGeometry.Canonical.WeakValuePoleCriterion.tendsto_real_residue
#print axioms InfoGeometry.Canonical.WeakValuePoleCriterion.eventually_abs_readout_lower_bound
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.pauliReal_eq
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.guarded_pauli_real
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.guarded_pauli_at_zero
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.pauliReal_tendsto_atTop
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.real_pole_with_zero_spatial_derivative
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.identity_readout_no_amplification
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.imaginary_pauli_numerator
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.imaginary_pauli_real_zero
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.postselectionBarrier_eq
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.postselectionBarrier_lower
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.postselectionBarrier_tendsto_atTop
#print axioms InfoGeometry.Canonical.WeakValuePoleExamples.guarded_real_pole
