massA:=88;; protonZ:=44;; neutronN:=44;; twoTz:=neutronN-protonZ;;
su2SpinGenerators:=3;; su2IsospinGenerators:=3;; cartanGenerators:=2;; totalGenerators:=6;;
if massA<>88 or protonZ<>44 or neutronN<>44 or twoTz<>0 then Error("nucleus"); fi;
if su2SpinGenerators<>3 or su2IsospinGenerators<>3 or cartanGenerators<>2 or totalGenerators<>6 then Error("generators"); fi;
spinC2I14:=14*15;; isospinC2T1:=1*2;;
if spinC2I14<>210 or isospinC2T1<>2 then Error("casimir"); fi;
isovectorMultiplicity:=3;; isoscalarMultiplicity:=3;;
if isovectorMultiplicity<>3 or isoscalarMultiplicity<>3 then Error("pair multiplicity"); fi;
band:=[0,2,4,6,8,10,12,14];; gammas:=[1063,1153,1253];;
if Length(band)<>8 or Sum(gammas)<>3469 then Error("band/gamma"); fi;
omegaNormal:=47/100;; omegaRu:=54/100;; omegaDelay:=omegaRu-omegaNormal;; omegaRatio:=omegaRu/omegaNormal;;
if omegaDelay<>7/100 or omegaRatio<>54/47 then Error("omega"); fi;
fpgdDegeneracies:=[2,4,6,10,6];; fpgdDegeneracy:=Sum(fpgdDegeneracies);;
if fpgdDegeneracy<>28 or 2*fpgdDegeneracy<>56 then Error("fpgd"); fi;
if 36+54-2<>88 or 18+26<>44 then Error("reaction"); fi;
S2:=SymmetricGroup(2);; if Size(S2)<>2 then Error("isospin reflection"); fi;
edges:=["has_spin_su2","has_isospin_su2","carries_T1_pair","carries_T0_pair","witnesses_delay","uses_fpgd"];
Print(rec(A:=massA,Z:=protonZ,N:=neutronN,twoTz:=twoTz,totalGenerators:=totalGenerators,cartanGenerators:=cartanGenerators,spinC2I14:=spinC2I14,isospinC2T1:=isospinC2T1,isovectorMultiplicity:=isovectorMultiplicity,isoscalarMultiplicity:=isoscalarMultiplicity,bandLength:=Length(band),gammaSum:=Sum(gammas),omegaDelay:=omegaDelay,omegaRatio:=omegaRatio,fpgdDegeneracy:=fpgdDegeneracy,fpgdPN:=2*fpgdDegeneracy,reactionA:=88,reactionZ:=44,isospinReflectionOrder:=Size(S2),graphEdges:=Length(edges)),"\n");
QUIT;
