

# This file was *autogenerated* from the file prl124_ru_pairing_symmetry.sage
from sage.all_cmdline import *   # import sage library

_sage_const_88 = Integer(88); _sage_const_44 = Integer(44); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_14 = Integer(14); _sage_const_210 = Integer(210); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_1063 = Integer(1063); _sage_const_1153 = Integer(1153); _sage_const_1253 = Integer(1253); _sage_const_3469 = Integer(3469); _sage_const_47 = Integer(47); _sage_const_100 = Integer(100); _sage_const_54 = Integer(54); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_28 = Integer(28); _sage_const_56 = Integer(56); _sage_const_36 = Integer(36); _sage_const_18 = Integer(18); _sage_const_26 = Integer(26)
Q=QQ
A=_sage_const_88 ; Z=_sage_const_44 ; N=_sage_const_44 ; twoTz=N-Z
su2_generators=['J+','J-','Jz']; iso_generators=['T+','T-','Tz']; cartan=['Jz','Tz']
assert len(su2_generators)==_sage_const_3  and len(iso_generators)==_sage_const_3  and len(cartan)==_sage_const_2 
assert A==N+Z and twoTz==_sage_const_0 
roots=[_sage_const_2 ,-_sage_const_2 ]
assert roots[_sage_const_0 ]+roots[_sage_const_1 ]==_sage_const_0 
casimir=lambda j: Q(j)*(Q(j)+_sage_const_1 )
assert casimir(_sage_const_0 )==_sage_const_0  and casimir(_sage_const_2 )==_sage_const_6  and casimir(_sage_const_14 )==_sage_const_210  and casimir(_sage_const_1 )==_sage_const_2 
isovector={'T':_sage_const_1 ,'I':_sage_const_0 ,'multiplicity':_sage_const_3 ,'components':['pp','np_T1','nn']}
isoscalar={'T':_sage_const_0 ,'I_min':_sage_const_1 ,'multiplicity':_sage_const_3 ,'components':['np_m1','np_0','np_p1']}
assert isovector['T']==_sage_const_1  and isovector['I']==_sage_const_0  and isovector['multiplicity']==_sage_const_3 
assert isoscalar['T']==_sage_const_0  and isoscalar['I_min']==_sage_const_1  and isoscalar['multiplicity']==_sage_const_3 
band=[_sage_const_0 ,_sage_const_2 ,_sage_const_4 ,_sage_const_6 ,_sage_const_8 ,_sage_const_10 ,_sage_const_12 ,_sage_const_14 ]
gammas=[_sage_const_1063 ,_sage_const_1153 ,_sage_const_1253 ]
assert len(band)==_sage_const_8  and sum(gammas)==_sage_const_3469 
omega_normal=Q(_sage_const_47 )/_sage_const_100 ; omega_ru=Q(_sage_const_54 )/_sage_const_100 
assert omega_ru>omega_normal and omega_ru-omega_normal==Q(_sage_const_7 )/_sage_const_100  and omega_ru/omega_normal==Q(_sage_const_54 )/_sage_const_47 
orbits={'1p1/2':_sage_const_1 ,'p3/2':_sage_const_3 ,'f5/2':_sage_const_5 ,'g9/2':_sage_const_9 ,'d5/2':_sage_const_5 }
degs={k:v+_sage_const_1  for k,v in orbits.items()}
assert list(degs.values())==[_sage_const_2 ,_sage_const_4 ,_sage_const_6 ,_sage_const_10 ,_sage_const_6 ] and sum(degs.values())==_sage_const_28  and _sage_const_2 *sum(degs.values())==_sage_const_56 
S=SymmetricGroup(_sage_const_2 ); assert S.order()==_sage_const_2 
assert _sage_const_36 +_sage_const_54 -_sage_const_2 ==_sage_const_88  and _sage_const_18 +_sage_const_26 ==_sage_const_44 
hamiltonian_terms=_sage_const_4 ; assert hamiltonian_terms==_sage_const_4 
print({'doi':'10.1103/PhysRevLett.124.062501','A':A,'Z':Z,'N':N,'twoTz':twoTz,'su2_spin_generators':len(su2_generators),'su2_isospin_generators':len(iso_generators),'cartan_generators':cartan,'total_generators':_sage_const_6 ,'su2_roots':roots,'spin_C2_I14':casimir(_sage_const_14 ),'isospin_C2_T1':casimir(_sage_const_1 ),'isovector_pair':isovector,'isoscalar_pair':isoscalar,'band_spins':band,'new_gamma_keV':gammas,'omega_normal':omega_normal,'omega_Ru88':omega_ru,'omega_delay':omega_ru-omega_normal,'omega_ratio':omega_ru/omega_normal,'fpgd_degeneracies':degs,'fpgd_total_per_species':sum(degs.values()),'fpgd_total_pn':_sage_const_2 *sum(degs.values()),'reaction_product':(_sage_const_88 ,_sage_const_44 ),'hamiltonian_terms':hamiltonian_terms,'isospin_reflection_order':S.order(),'edges':_sage_const_6 })

