R = QQ[J,T,omega,omegaN,omegaR,q,dq, WeylAlgebra => {q=>dq}];
A=88; Z=44; N=44; twoTz=N-Z;
su2SpinGenerators=3; su2IsospinGenerators=3; cartanGenerators=2; totalGenerators=6;
assert(A==88 and Z==44 and N==44 and twoTz==0);
assert(su2SpinGenerators==3 and su2IsospinGenerators==3 and cartanGenerators==2 and totalGenerators==6);
spinC2I14=14*15; isospinC2T1=1*2; assert(spinC2I14==210 and isospinC2T1==2);
isovectorMultiplicity=3; isoscalarMultiplicity=3; assert(isovectorMultiplicity==3 and isoscalarMultiplicity==3);
bandLength=8; gammaSum=1063+1153+1253; assert(bandLength==8 and gammaSum==3469);
omegaNormal=47/100; omegaRu=54/100; omegaDelay=omegaRu-omegaNormal; omegaRatio=omegaRu/omegaNormal;
assert(omegaDelay==7/100 and omegaRatio==54/47);
fpgdDegeneracy=2+4+6+10+6; assert(fpgdDegeneracy==28 and 2*fpgdDegeneracy==56);
reactionA=36+54-2; reactionZ=18+26; assert(reactionA==88 and reactionZ==44);
hamiltonianTerms=4; assert(hamiltonianTerms==4);
I = ideal(q*dq - dq*q - 1); assert(numgens I == 1);
pairingIdeal = ideal(J*(J+1)-210, T*(T+1)-2, 100*omegaN-47, 100*omegaR-54);
assert(numgens pairingIdeal == 4);
edges={"has_spin_su2","has_isospin_su2","carries_T1_pair","carries_T0_pair","witnesses_delay","uses_fpgd"};
assert(#edges==6);
print {"A",A,"Z",Z,"N",N,"twoTz",twoTz,"totalGenerators",totalGenerators,"cartanGenerators",cartanGenerators,"spinC2I14",spinC2I14,"isospinC2T1",isospinC2T1,"isovectorMultiplicity",isovectorMultiplicity,"isoscalarMultiplicity",isoscalarMultiplicity,"bandLength",bandLength,"gammaSum",gammaSum,"omegaDelay",omegaDelay,"omegaRatio",omegaRatio,"fpgdDegeneracy",fpgdDegeneracy,"fpgdPN",2*fpgdDegeneracy,"reactionA",reactionA,"reactionZ",reactionZ,"dmoduleCCRGenerators",numgens I,"pairingIdealGenerators",numgens pairingIdeal,"graphEdges",#edges};
