import proofs.Clifford55

/-! # Signature-correct real `Pin(5,5)` core

Mathlib's `pinGroup Q55` uses the Clifford-star unitary convention.  For an
indefinite form that convention contains the `Q = -1` vector generators but
not the `Q = +1` generators.  The real `Pin(5,5)` group is instead generated
by all normalized non-isotropic vectors, of square `+1` or `-1`.
-/

noncomputable section
namespace RealPin55Core

open Clifford55

/-- The canonical Clifford unit associated to a vector whose quadratic value
is a unit in the ground field. -/
def vectorUnit (v : V55) (hv : IsUnit (Q55 v)) : Cl55ˣ :=
  (CliffordAlgebra.isUnit_ι_of_isUnit Q55 hv).unit

@[simp] theorem coe_vectorUnit (v : V55) (hv : IsUnit (Q55 v)) :
    ((vectorUnit v hv : Cl55ˣ) : Cl55) = ι55 v :=
  (CliffordAlgebra.isUnit_ι_of_isUnit Q55 hv).unit_spec

/-- Unit Clifford vectors normalized to either sign of the real split form. -/
def normalizedVectorUnits : Set Cl55ˣ :=
  {u | ∃ v : V55, (Q55 v = 1 ∨ Q55 v = -1) ∧ (u : Cl55) = ι55 v}

/-- The full real `Pin(5,5)` group, as the subgroup generated by all
normalized positive and negative Clifford vectors. -/
def FullPin55 : Subgroup Cl55ˣ :=
  Subgroup.closure normalizedVectorUnits

theorem vectorUnit_mem_fullPin55 (v : V55) (hv : IsUnit (Q55 v))
    (hnorm : Q55 v = 1 ∨ Q55 v = -1) :
    vectorUnit v hv ∈ FullPin55 := by
  apply Subgroup.subset_closure
  exact ⟨v, hnorm, coe_vectorUnit v hv⟩

def ePosUnit (i : Fin 5) : Cl55ˣ :=
  vectorUnit (e_pos i) (by rw [Q55_e_pos]; exact isUnit_one)

def fNegUnit (i : Fin 5) : Cl55ˣ :=
  vectorUnit (f_neg i) (by
    rw [Q55_f_neg]
    exact isUnit_iff_ne_zero.mpr (by norm_num))

@[simp] theorem coe_ePosUnit (i : Fin 5) :
    ((ePosUnit i : Cl55ˣ) : Cl55) = ι55 (e_pos i) :=
  coe_vectorUnit _ _

@[simp] theorem coe_fNegUnit (i : Fin 5) :
    ((fNegUnit i : Cl55ˣ) : Cl55) = ι55 (f_neg i) :=
  coe_vectorUnit _ _

theorem ePosUnit_mem (i : Fin 5) : ePosUnit i ∈ FullPin55 := by
  apply vectorUnit_mem_fullPin55
  exact Or.inl (Q55_e_pos i)

theorem fNegUnit_mem (i : Fin 5) : fNegUnit i ∈ FullPin55 := by
  apply vectorUnit_mem_fullPin55
  exact Or.inr (Q55_f_neg i)

/-- Positive generators square to the identity in the unit group. -/
@[simp] theorem ePosUnit_sq (i : Fin 5) : ePosUnit i * ePosUnit i = 1 := by
  apply Units.ext
  change ι55 (e_pos i) * ι55 (e_pos i) = 1
  exact e_pos_mul_self i

/-- Negative generators square to the central sign in the Clifford algebra. -/
@[simp] theorem coe_fNegUnit_sq (i : Fin 5) :
    (((fNegUnit i * fNegUnit i : Cl55ˣ) : Cl55)) = -1 := by
  change ι55 (f_neg i) * ι55 (f_neg i) = -1
  exact f_neg_mul_self i

/-- Negative generators square to the central sign in the unit group. -/
@[simp] theorem fNegUnit_sq (i : Fin 5) :
    fNegUnit i * fNegUnit i = (-1 : Cl55ˣ) := by
  apply Units.ext
  change ι55 (f_neg i) * ι55 (f_neg i) = (-1 : Cl55)
  exact f_neg_mul_self i

/-! ## Native Lipschitz containment -/

set_option maxHeartbeats 800000 in
theorem normalizedVectorUnit_mem_lipschitz
    {u : Cl55ˣ}
    (hu : u ∈ normalizedVectorUnits) :
    u ∈ LipschitzGroup55 := by
  change ∃ v : V55,
    (Q55 v = 1 ∨ Q55 v = -1) ∧
      (u : Cl55) = ι55 v at hu
  rcases hu with ⟨v, _hv, huv⟩
  have hgen :
      u ∈ ((↑) ⁻¹' Set.range ι55 : Set Cl55ˣ) := by
    change (u : Cl55) ∈ Set.range ι55
    exact ⟨v, huv.symm⟩
  change u ∈ Subgroup.closure
    ((↑) ⁻¹' Set.range ι55 : Set Cl55ˣ)
  exact Subgroup.subset_closure hgen

/-- The signature-correct real Pin closure lies in the native Lipschitz group.
-/
theorem fullPin55_le_lipschitzGroup55 :
    FullPin55 ≤ LipschitzGroup55 := by
  rw [FullPin55, LipschitzGroup55, lipschitzGroup, Subgroup.closure_le]
  intro u hu
  exact normalizedVectorUnit_mem_lipschitz hu

theorem fullPin55_mem_lipschitzGroup55 (g : FullPin55) :
    (g : Cl55ˣ) ∈ LipschitzGroup55 :=
  fullPin55_le_lipschitzGroup55 g.2

/-- The central Clifford sign belongs to the signature-correct Pin group. -/
theorem neg_one_mem_fullPin55 :
    (-1 : Cl55ˣ) ∈ FullPin55 := by
  simpa using
    FullPin55.mul_mem
      (fNegUnit_mem (0 : Fin 5))
      (fNegUnit_mem (0 : Fin 5))

/-- The new group genuinely repairs the indefinite-signature gap: every
positive unit vector belongs to `FullPin55`, while it does not belong to the
older star-unitary `Clifford55.Pin55`. -/
theorem positive_generator_full_not_starUnitary (i : Fin 5) :
    ePosUnit i ∈ FullPin55 ∧ ¬ ι55 (e_pos i) ∈ Clifford55.Pin55 :=
  ⟨ePosUnit_mem i, e_pos_not_mem_pin55 i⟩

/-- All ten coordinate reflection lifts are present. -/
theorem coordinate_generators_mem :
    (∀ i : Fin 5, ePosUnit i ∈ FullPin55) ∧
      (∀ i : Fin 5, fNegUnit i ∈ FullPin55) :=
  ⟨ePosUnit_mem, fNegUnit_mem⟩

end RealPin55Core
end noncomputable section
