charges := [2,2,2,-3,-3];
rootsA4 := Filtered(Cartesian([1..5],[1..5]), p -> p[1] <> p[2]);
smRoots := Filtered(rootsA4, p -> charges[p[1]] = charges[p[2]]);
brokenRoots := Filtered(rootsA4, p -> charges[p[1]] <> charges[p[2]]);
su5Adjoint := 4 + Length(rootsA4);
smAdjoint := 4 + Length(smRoots);
fundamentalScalar := 5*5;
exteriorC5 := Sum([0..5], k -> Binomial(5,k));
so10Adjoint := 10*(10-1)/2;
cl55Dim := 2^10;
m32Dim := 32*32;
traceGamma32 := 16-16;
traceIdentity32 := 16+16;
weylA4Order := Size(SymmetricGroup(5));
if Length(rootsA4) <> 20 then Error("A4 roots"); fi;
if Length(smRoots) <> 8 then Error("SM roots"); fi;
if Length(brokenRoots) <> 12 then Error("broken roots"); fi;
if su5Adjoint <> 24 then Error("su5 adjoint"); fi;
if smAdjoint <> 12 then Error("SM adjoint"); fi;
if fundamentalScalar <> 25 then Error("fundamental scalar"); fi;
if fundamentalScalar = su5Adjoint then Error("not adjoint"); fi;
if fundamentalScalar - su5Adjoint <> 1 then Error("dimension gap"); fi;
if exteriorC5 <> 32 then Error("exterior"); fi;
if so10Adjoint <> 45 then Error("so10"); fi;
if cl55Dim <> m32Dim then Error("cl55=m32"); fi;
if m32Dim <> 1024 then Error("m32"); fi;
if traceGamma32 <> 0 then Error("trace gamma"); fi;
if traceIdentity32 <> 32 then Error("trace identity"); fi;
if weylA4Order <> 120 then Error("Weyl A4"); fi;
Print(rec(A4_roots:=Length(rootsA4), SM_roots:=Length(smRoots), broken_roots:=Length(brokenRoots), su5_adjoint:=su5Adjoint, sm_adjoint:=smAdjoint, fundamental_scalar:=fundamentalScalar, exterior_c5:=exteriorC5, so10_adjoint:=so10Adjoint, cl55_dim:=cl55Dim, trace_gamma32:=traceGamma32, trace_identity32:=traceIdentity32, odd_odd_target_even:=true, weyl_A4_order:=weylA4Order));
QUIT;
