gammaDiagonal = join(toList(16:1), toList(16:-1));
traceGamma = sum gammaDiagonal;
traceIdentity = 32;
a4Roots = 20;
smRoots = 8;
brokenRoots = 12;
su5Adjoint = 4 + a4Roots;
smAdjoint = 4 + smRoots;
fundamentalScalar = 5*5;
exteriorC5 = 1 + 5 + 10 + 10 + 5 + 1;
so10Adjoint = 10*(10-1)//2;
cl55Dim = 2^10;
m32Dim = 32*32;
assert(traceGamma == 0);
assert(traceIdentity == 32);
assert(a4Roots == 20);
assert(smRoots == 8);
assert(brokenRoots == 12);
assert(su5Adjoint == 24);
assert(smAdjoint == 12);
assert(fundamentalScalar == 25);
assert(fundamentalScalar != su5Adjoint);
assert(fundamentalScalar - su5Adjoint == 1);
assert(exteriorC5 == 32);
assert(so10Adjoint == 45);
assert(cl55Dim == m32Dim);
assert(m32Dim == 1024);
W = QQ[x, dx, WeylAlgebra => {x=>dx}];
I = ideal(x*dx - dx*x - 1);
M = W^1 / image matrix{{x*dx - dx*x - 1}};
assert(numgens I == 1);
assert(rank source presentation M == 1);
print {a4Roots=>a4Roots, smRoots=>smRoots, brokenRoots=>brokenRoots, su5Adjoint=>su5Adjoint, smAdjoint=>smAdjoint, fundamentalScalar=>fundamentalScalar, exteriorC5=>exteriorC5, so10Adjoint=>so10Adjoint, traceGamma=>traceGamma, traceIdentity=>traceIdentity, dmoduleCCRGenerators=>numgens I};
