gammaDiagonal = join(toList(16:1), toList(16:-1));
traceGamma = sum gammaDiagonal;
traceIdentity = 32;
omegaSquare55 = (-1)^45 * (-1)^5;
su5Lambda2 = binomial(5,2);
su5Adjoint = 5^2 - 1;
smAdjoint = (3^2 - 1) + (2^2 - 1) + 1;
xyBosons = su5Adjoint - smAdjoint;
so10Adjoint = 10*(10-1)//2;
exteriorC5 = 1 + 5 + 10 + 10 + 5 + 1;
sarsScalar5Fund = 5*5;
sarsDimensionGap = sarsScalar5Fund - su5Adjoint;
cl55MatrixDim = 32*32;
oddOddTargetEven = true;
assert(omegaSquare55 == 1);
assert(traceGamma == 0);
assert(traceIdentity == 32);
assert(su5Lambda2 == 10);
assert(su5Adjoint == 24);
assert(smAdjoint == 12);
assert(xyBosons == 12);
assert(so10Adjoint == 45);
assert(exteriorC5 == 32);
assert(sarsScalar5Fund == 25);
assert(sarsScalar5Fund != su5Adjoint);
assert(sarsDimensionGap == 1);
assert(cl55MatrixDim == 2^10);
assert(oddOddTargetEven == true);
W = QQ[x, dx, WeylAlgebra => {x=>dx}];
I = ideal(x*dx - dx*x - 1);
assert(numgens I == 1);
print {traceGamma=>traceGamma, traceIdentity=>traceIdentity, lambda2=>su5Lambda2, su5Adjoint=>su5Adjoint, so10Adjoint=>so10Adjoint, smAdjoint=>smAdjoint, xy=>xyBosons, exteriorC5=>exteriorC5, sarsScalar5Fund=>sarsScalar5Fund, sarsDimensionGap=>sarsDimensionGap, cl55MatrixDim=>cl55MatrixDim, oddOddTargetEven=>oddOddTargetEven, dmoduleCCRGenerators=>numgens I};
