R = QQ[m,lam,hbar,c,m0];
PR = matrix{{1_R,0_R},{0_R,0_R}};
PL = matrix{{0_R,0_R},{0_R,1_R}};
J = matrix{{0_R,1_R},{1_R,0_R}};
assert((PR*PL)_(0,0) == 0_R and (PR*PL)_(0,1) == 0_R and (PR*PL)_(1,0) == 0_R and (PR*PL)_(1,1) == 0_R);
assert((PR+PL)_(0,0) == 1_R and (PR+PL)_(1,1) == 1_R and (PR+PL)_(0,1) == 0_R and (PR+PL)_(1,0) == 0_R);
assert(J*PL*J == PR);
assert(J*PR*J == PL);
M = m*J;
assert(M_(0,0) == 0_R and M_(0,1) == m and M_(1,0) == m and M_(1,1) == 0_R);
assert(M_(0,0) == 0_R and M_(1,1) == 0_R);
assert(M_(0,1) == m and M_(1,0) == m);
spring = m^2*lam^2/2;
force = -m^2*lam;
assert(sub(spring,{lam=>0_R}) == 0_R);
W = QQ[q,dq, WeylAlgebra => {q=>dq}];
I = ideal(q*dq - dq*q - 1);
assert(numgens I == 1);
edges = {"swapped_by","couples_to","generates","breaks_weyl_scale_by","realizes_as","drives_orthogonal_transport"};
assert(#edges == 6);
print {projectorsOrthogonal=>true, tomitaSwap=>true, massOffblock=>true, hookeForce=>force, dmoduleCCRGenerators=>numgens I, graphEdges=>#edges};
