

# This file was *autogenerated* from the file sars_itakura_modular.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
var('x z')
modular = exp(x) - _sage_const_1  - x
itakura = z - log(z) - _sage_const_1 
itakura_exp = itakura.subs(z=exp(x))
assert simplify(itakura_exp - modular) == _sage_const_0 
assert modular.subs(x=_sage_const_0 ) == _sage_const_0 
for val in [-_sage_const_5 ,-_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_2 ,_sage_const_5 ]:
    assert RDF(modular.subs(x=val)) >= _sage_const_0 
edges = ['exp_coordinate_transform','bregman_dual','stabilizes_modular_flow']
assert len(edges) == _sage_const_3 
print({'identity':'dIS(exp(x)||1)=exp(x)-1-x','difference':simplify(itakura_exp-modular),'vacuum_zero':modular.subs(x=_sage_const_0 ),'sample_nonnegative':True,'edges':edges})

