

# This file was *autogenerated* from the file sars_gns_weyl.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
var('q p r s')
u = vector([q,p])
v = vector([r,s])
J1 = matrix(QQ, [[_sage_const_0 ,_sage_const_1 ],[-_sage_const_1 ,_sage_const_0 ]])
E = matrix(QQ, [[_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_1 ],[_sage_const_0 ,_sage_const_0 ]])
J2 = matrix(QQ, [[_sage_const_0 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ],[_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ],[-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],[_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ]])
sigma1 = (u.row()*J1*v.column())[_sage_const_0 ,_sage_const_0 ]
sigma2 = ((E*u).row()*J2*(E*v).column())[_sage_const_0 ,_sage_const_0 ]
norm1 = (u.row()*u.column())[_sage_const_0 ,_sage_const_0 ]
norm2 = ((E*u).row()*(E*u).column())[_sage_const_0 ,_sage_const_0 ]
assert expand(sigma2 - sigma1) == _sage_const_0 
assert expand(norm2 - norm1) == _sage_const_0 
print({
    'sigma_preserved': expand(sigma2 - sigma1),
    'norm_preserved': expand(norm2 - norm1),
    'fock_state_zero': _sage_const_1 ,
    'identity_trace_status': 'not_trace_class_in_infinite_GNS'
})

