R = QQ[m,C,lam];
COn = -m^2;
k = -C;
massK = m^2;
VC = -C*lam^2/2;
VM = m^2*lam^2/2;
FC = C*lam;
FM = -m^2*lam;
bracket = 2*C;
assert(sub(k-massK,{C=>COn}) == 0);
assert(sub(VC-VM,{C=>COn}) == 0);
assert(sub(FC-FM,{C=>COn}) == 0);
assert(sub(massK,{m=>0}) == 0);
assert(sub(VM,{lam=>0}) == 0);
assert(FM + massK*lam == 0);
S = QQ[q,dq, WeylAlgebra => {q=>dq}];
I = ideal(q*dq - dq*q - 1);
assert(numgens I == 1);
edges = {"labels","identical_to","gives_stiffness","resists","crosses","restores_to"};
assert(#edges == 6);
print {casimirOnShell=>COn, stiffnessDifference=>0, potentialDifference=>0, forceDifference=>0, dmoduleCCRGenerators=>numgens I, graphEdges=>#edges};
