dlaDimSYK := function(n) return 2^(2*n - 1) - 2; end;
dlaDimSK := function(L) return 2*(4^(L-1) - 1); end;
poolSizeSK := function(L) return L*(L-1); end;
poolSizeSYK := function(n) return n + 3*n*(n-1)/2; end;
majoranaCount := function(n) return 2*n; end;
hilbertDim := function(n) return 2^n; end;
matrixAlgDim := function(n) return hilbertDim(n)^2; end;
clBalancedDim := function(n) return 2^(2*n); end;
if dlaDimSYK(4) <> 126 then Error("SYK DLA"); fi;
if dlaDimSK(8) <> 32766 then Error("SK DLA"); fi;
if poolSizeSK(8) <> 56 then Error("SK pool"); fi;
if poolSizeSYK(4) <> 22 then Error("SYK pool"); fi;
if majoranaCount(4) <> 8 then Error("Majorana count"); fi;
if hilbertDim(10) <> 1024 then Error("Hilbert dim"); fi;
if matrixAlgDim(5) <> 1024 then Error("Matrix algebra dim"); fi;
if clBalancedDim(5) <> 1024 then Error("Cl balanced dim"); fi;
S5 := SymmetricGroup(5);
if Size(S5) <> 120 then Error("S5 order"); fi;
edges := ["has_pool_size","has_dla_dimension","embeds_by","realizes_cl55_block","scales_as"];
if Length(edges) <> 5 then Error("edges"); fi;
Print(rec(dlaDimSYK4:=dlaDimSYK(4), dlaDimSK8:=dlaDimSK(8), poolSK8:=poolSizeSK(8), poolSYK4:=poolSizeSYK(4), majoranas4:=majoranaCount(4), cl55MatrixDim:=32*32, S5Order:=Size(S5), edges:=Length(edges)), "\n");
QUIT;
