

# This file was *autogenerated* from the file sars_souriau_dilaton.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)
var('theta beta Z lam g')
weight = exp(-(theta*beta))
rho = weight / Z
weyl_scale = exp(_sage_const_2 *lam)
dilaton = exp(lam)
metric_component = weyl_scale * g
assert simplify(Z*rho - weight) == _sage_const_0 
assert simplify(dilaton**_sage_const_2  - weyl_scale) == _sage_const_0 
assert simplify(metric_component - exp(_sage_const_2 *lam)*g) == _sage_const_0 
edges = [('Souriau_Lie_Group_Thermodynamics','has_leaflet','Entropic_Leaflet'),('Entropic_Leaflet','tangent_reversible_flow','Sars_Weyl_Colimit'),('Sars_Weyl_Colimit','parameterizes_scale_orthogonal_to_leaves','Souriau_Lie_Group_Thermodynamics'),('Partition_Function_Normalization','normalizes_by_partition_function','Dilaton_Weyl_Gauge_Vector'),('Dilaton_Weyl_Gauge_Vector','generates_orthogonal_entropy_transport','Orthogonal_Entropy_Transport')]
assert len(edges) == _sage_const_5 
print({'partition_rescale':_sage_const_0 ,'dilaton_square_weyl_scale':_sage_const_0 ,'metric_component_verified':True,'edges':len(edges)})

