

# This file was *autogenerated* from the file sars_bregman_duality.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
var('x y z w')
modular = exp(x-y) - _sage_const_1  - (x-y)
exp_bregman = exp(x) - exp(y) - exp(y)*(x-y)
burg = z/w - log(z/w) - _sage_const_1 
burg_exp = burg.subs({z:exp(x), w:exp(y)})
itakura = z - log(z) - _sage_const_1 
itakura_exp = itakura.subs(z=exp(x))
assert simplify(exp_bregman - exp(y)*modular) == _sage_const_0 
assert simplify(burg_exp - modular) == _sage_const_0 
assert simplify(itakura_exp - (exp(x)-_sage_const_1 -x)) == _sage_const_0 
for a,b in [(-_sage_const_2 ,_sage_const_0 ),(_sage_const_0 ,_sage_const_0 ),(_sage_const_1 ,-_sage_const_1 ),(_sage_const_3 ,_sage_const_1 )]:
    assert RDF(modular.subs({x:a,y:b})) >= _sage_const_0 
edges = ['qft_modular_to_itakura_saito','bregman_coordinate_isomorphism','stabilizes_krein_entropy']
assert len(edges) == _sage_const_3 
print({'exp_bregman_factor':_sage_const_0 ,'burg_exp_coordinate':_sage_const_0 ,'itakura_exp_coordinate':_sage_const_0 ,'sample_nonnegative':True,'vacuum_zero':_sage_const_0 ,'edges':edges})

