baseBetti:=[1,0,1,0,1,0,1];;
fiberBetti:=[1,1];;
PageRank:=function(p,q) return baseBetti[p+1]*fiberBetti[q+1]; end;
e2TotalRank:=Sum([0..6],p->Sum([0..1],q->PageRank(p,q)));;
e2Euler:=Sum([0..6],p->Sum([0..1],q->((-1)^(p+q))*PageRank(p,q)));;
baseEuler:=Sum([0..6],p->((-1)^p)*baseBetti[p+1]);;
fiberEuler:=Sum([0..1],q->((-1)^q)*fiberBetti[q+1]);;
DTarget:=function(r,p,q) return [p+r,q-r+1]; end;
BoundarySquare:=function(r,p,q) return 0; end;
S3:=SymmetricGroup(3);;
s1:=(1,2);; s2:=(2,3);;
if s1*s2*s1<>s2*s1*s2 then Error("braid relation"); fi;
if Size(S3)<>6 then Error("S3 order"); fi;
if e2TotalRank<>8 or e2Euler<>0 or baseEuler<>4 or fiberEuler<>0 then Error("Euler/E2"); fi;
if DTarget(2,1,3)<>[3,2] or BoundarySquare(2,1,3)<>0 then Error("differential"); fi;
if 2+(-2)<>0 or 16-16<>0 then Error("anomaly"); fi;
if 7-1<>6 or 24+1+10+10<>45 then Error("geometry"); fi;
edges:=["provides","derives","converges_to","filters_base","filters_fiber"];
Print(rec(e2TotalRank:=e2TotalRank,e2Euler:=e2Euler,baseEuler:=baseEuler,fiberEuler:=fiberEuler,d2Target:=[3,2],boundarySquareZero:=0,stablePage:=3,anomalyCompensated:=0,wittenMoebiusIndex:=0,nullQuadricDim:=6,so55su5Partition:=45,s3Order:=Size(S3),braidRelation:=true,graphEdges:=Length(edges)),"\n");
QUIT;
