R = QQ[x0,x1,x2,x3,x4,x5,x6,x7,m,Eexact,Eadapt,delta];
nullQuadricIdeal = ideal(x0*x7 - x1*x4 - x2*x5 - x3*x6);
assert(numgens nullQuadricIdeal == 1);
assert(degree nullQuadricIdeal == 2);
baseEuler=4; fiberEuler=0; e2Euler=0; e2TotalRank=8; stablePage=3;
varlamovEven=1+10+5; varlamovOdd=5+10+1; wittenMoebiusIndex=varlamovEven-varlamovOdd;
anomalyCompensated=2-2; nullQuadricDim=7-1; so55su5Partition=24+1+10+10;
assert(e2TotalRank==8 and e2Euler==0 and baseEuler*fiberEuler==0);
assert(stablePage==3);
assert(varlamovEven==16 and varlamovOdd==16 and wittenMoebiusIndex==0);
assert(anomalyCompensated==0 and nullQuadricDim==6 and so55su5Partition==45);
W = QQ[q,dq, WeylAlgebra => {q=>dq}];
I = ideal(q*dq - dq*q - 1);
assert(numgens I == 1);
SS = QQ[p,q];
e2Ideal = ideal(p^2, q^2);
assert(numgens e2Ideal == 2);
edges={"provides","derives","converges_to","filters_base","filters_fiber"};
assert(#edges==5);
print {"e2TotalRank",e2TotalRank,"e2Euler",e2Euler,"baseEuler",baseEuler,"fiberEuler",fiberEuler,"stablePage",stablePage,"anomalyCompensated",anomalyCompensated,"wittenMoebiusIndex",wittenMoebiusIndex,"nullQuadricGenerators",numgens nullQuadricIdeal,"nullQuadricDegree",degree nullQuadricIdeal,"dmoduleCCRGenerators",numgens I,"e2IdealGenerators",numgens e2Ideal,"so55su5Partition",so55su5Partition,"graphEdges",#edges};
