TripPoly := d -> d*(d-1)*(d+1);
InvParity := function(diag,off) return [diag,-off]; end;
MobiusInv := function(e,o) return [(e+o)/2,(e-o)/2]; end;
MobiusRec := function(x,y) return [x+y,x-y]; end;
KleinAvg := function(a,b,c,d) return (a+b+c+d)/4; end;
Brillouin := k -> [k,-k];
KleinMode := k -> Sum(Brillouin(k));
n5 := 5;; nullDim := 2*n5;; so55Dim := nullDim*(nullDim-1)/2;; matrixDim := n5*n5;;
sl5Adj := matrixDim-1;; skew10 := n5*(n5-1)/2;; partition := sl5Adj+1+skew10+skew10;; block := matrixDim+skew10+skew10;;
if nullDim<>10 then Error("nullDim"); fi;
if so55Dim<>45 then Error("so55Dim"); fi;
if sl5Adj<>24 then Error("sl5Adj"); fi;
if skew10<>10 then Error("skew10"); fi;
if partition<>45 or block<>45 then Error("partition"); fi;
if 1+10+5<>16 or 5+10+1<>16 then Error("spinor"); fi;
if InvParity(InvParity(7/3,5/2)[1],InvParity(7/3,5/2)[2])<>[7/3,5/2] then Error("involution"); fi;
mi := MobiusInv(7,3);; if MobiusRec(mi[1],mi[2])<>[7,3] then Error("mobius"); fi;
if KleinAvg(1,2,3,4)<>5/2 then Error("klein avg"); fi;
if List([-1,0,1],TripPoly)<>[0,0,0] then Error("tripotent"); fi;
if KleinMode(11/7)<>0 then Error("brillouin"); fi;
edges := ["decomposes_to","trace_splits_to","skew_splits_B","skew_splits_C","quotients_modes"];
Print(rec(nullDim:=nullDim,so55Dim:=so55Dim,sl5Adj:=sl5Adj,dilaton:=1,skew10:=skew10,su5Partition:=partition,spinEven16:=16,spinOdd16:=16,kleinAverage:=5/2,tripotentRoots:=[-1,0,1],brillouinCancel:=0,edges:=Length(edges)),"\n");
QUIT;
