

# This file was *autogenerated* from the file souriau_casimir_entropy_leaves.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0); _sage_const_67 = Integer(67); _sage_const_20 = Integer(20); _sage_const_33 = Integer(33)
from sage.all import *

Q = QQ

def orbit(action, group_elements, x):
    return Set([action(g, x) for g in group_elements])

def invariant(action, group_elements, points, f):
    return all(f(action(g, x)) == f(x) for g in group_elements for x in points)

G = [-_sage_const_1 , _sage_const_1 ]
X = [Q(-_sage_const_1 ) / _sage_const_2 , Q(_sage_const_1 ) / _sage_const_2 ]
flip = lambda g, x: g * x
C_isospin = lambda x: x**_sage_const_2 
C_spin = lambda x: Q(_sage_const_3 ) / _sage_const_4 

assert invariant(flip, G, X, C_isospin)
assert invariant(flip, G, X, C_spin)

R = PolynomialRing(QQ, ["a", "b", "c"])
a, b, c = R.gens()

def entropy_from_casimirs(C1, C2, a0, b0, c0, x):
    return a0 * C1(x) + b0 * C2(x) + c0

S = lambda x: entropy_from_casimirs(C_isospin, C_spin, a, b, c, x)
assert invariant(flip, G, X, S)
assert orbit(flip, G, Q(_sage_const_1 ) / _sage_const_2 ) == Set([Q(-_sage_const_1 ) / _sage_const_2 , Q(_sage_const_1 ) / _sage_const_2 ])
assert S(Q(-_sage_const_1 ) / _sage_const_2 ) == S(Q(_sage_const_1 ) / _sage_const_2 )

def isospin_casimir(I):
    return I * (I + _sage_const_1 )

assert isospin_casimir(Q(_sage_const_1 ) / _sage_const_2 ) == Q(_sage_const_3 ) / _sage_const_4 
assert Q(-_sage_const_1 ) / _sage_const_2  + Q(_sage_const_1 ) / _sage_const_2  == _sage_const_0 

def poincare_mass_casimir(mass_sq):
    return -mass_sq

def dilation_spring_stiffness(C1):
    return -C1

assert dilation_spring_stiffness(poincare_mass_casimir(Q(_sage_const_67 ))) == _sage_const_67 

def ivgmr_coefficient(A, e, R0, deltaE0):
    return ((A - _sage_const_1 ) * e**_sage_const_2 ) / (_sage_const_4  * R0 * deltaE0)

def ivgmr_one_body_radial(ri, R0):
    return ri**_sage_const_3  / R0**_sage_const_2 

def ivgmr_two_body_radial(ri, rj, R0):
    return ri * rj**_sage_const_2  / R0**_sage_const_3 

def induced_isoscalar_e1_kernel(A, e, R0, deltaE0, ri, rj):
    return ivgmr_coefficient(A, e, R0, deltaE0) * (
        ivgmr_one_body_radial(ri, R0) +
        ivgmr_two_body_radial(ri, rj, R0))

assert induced_isoscalar_e1_kernel(_sage_const_67 , _sage_const_1 , _sage_const_1 , _sage_const_20 , _sage_const_1 , _sage_const_1 ) == Q(_sage_const_33 ) / _sage_const_20 

print({
    "isospin_casimir_half": isospin_casimir(Q(_sage_const_1 ) / _sage_const_2 ),
    "tz_flip_sum": Q(-_sage_const_1 ) / _sage_const_2  + Q(_sage_const_1 ) / _sage_const_2 ,
    "dilation_stiffness_67": dilation_spring_stiffness(poincare_mass_casimir(Q(_sage_const_67 ))),
    "ivgmr_kernel_A67": induced_isoscalar_e1_kernel(_sage_const_67 , _sage_const_1 , _sage_const_1 , _sage_const_20 , _sage_const_1 , _sage_const_1 ),
})

