R = QQ[m,Eexact,Eadapt,delta];
zornSlots=8; splitPositive=4; splitNegative=4; imaginaryPositive=3; imaginaryNegative=4;
zeroDivisorNorm=0; oneNorm=1; associatorWitness=1; associatorObstruction=2; anomalyCounterterm=-2;
posOrbitSig={2,4}; negOrbitSig={3,3}; subalgebraBound=4;
adPos=-4; adNeg=4; so55su5=24+1+10+10;
imaginaryNullQuadricDim=7-1; varlamovEven=1+10+5; varlamovOdd=5+10+1; wittenMoebiusIndex=varlamovEven-varlamovOdd;
assert(zornSlots==8);
assert(splitPositive+splitNegative==8);
assert(imaginaryPositive+imaginaryNegative==7);
assert(zeroDivisorNorm==0 and oneNorm==1);
assert(associatorWitness != 0);
assert(posOrbitSig#0+posOrbitSig#1==6 and negOrbitSig#0+negOrbitSig#1==6);
assert(subalgebraBound==4);
assert(adPos==-4 and adNeg==4);
assert(associatorObstruction+anomalyCounterterm==0);
assert(so55su5==45);
assert(imaginaryNullQuadricDim==6);
assert(varlamovEven==16 and varlamovOdd==16 and varlamovEven+varlamovOdd==32 and wittenMoebiusIndex==0);
assert((-(-7))==7 and 7+(-7)==0);
tripPoly=d -> d^3-d;
assert(tripPoly(-1)==0 and tripPoly(0)==0 and tripPoly(1)==0);
C1=-m^2; stiffness=-C1; assert(stiffness==m^2);
S = QQ[x_0..x_7];
nullQuadricIdeal = ideal(x_0*x_7 - x_1*x_4 - x_2*x_5 - x_3*x_6);
assert(numgens nullQuadricIdeal == 1);
W = QQ[q,dq, WeylAlgebra => {q=>dq}];
I = ideal(q*dq - dq*q - 1);
assert(numgens I == 1);
M = coker matrix{{Eexact*delta - Eexact + Eadapt}};
edges={"realizes","has","obstructs","compensated_by","bridges_to"};
assert(#edges==5);
print {"zornSlots",zornSlots,"splitSignature","(4,4)","imaginarySignature","(3,4)","imaginaryNullQuadricDim",imaginaryNullQuadricDim,"zeroDivisorNorm",zeroDivisorNorm,"oneNorm",oneNorm,"associatorWitness",associatorWitness,"positiveOrbitSignature","(2,4)","negativeOrbitSignature","(3,3)","subalgebraBound",subalgebraBound,"anomalyCompensated",0,"varlamovEven",varlamovEven,"varlamovOdd",varlamovOdd,"wittenMoebiusIndex",wittenMoebiusIndex,"nullQuadricGenerators",numgens nullQuadricIdeal,"dmoduleCCRGenerators",numgens I,"graphEdges",#edges};
