zornSlots:=8;; splitPositive:=4;; splitNegative:=4;; imaginaryPositive:=3;; imaginaryNegative:=4;;
zeroDivisorNorm:=0;; oneNorm:=1;; associatorWitness:=1;; associatorObstruction:=2;; anomalyCounterterm:=-2;;
AdCoeff := N -> -4*N;
Mobius := k -> -k;
Trip := d -> d^3-d;
imaginaryNullQuadricDim:=7-1;; varlamovEven:=Binomial(5,0)+Binomial(5,2)+Binomial(5,4);; varlamovOdd:=Binomial(5,1)+Binomial(5,3)+Binomial(5,5);;
if zornSlots<>8 then Error("slots"); fi;
if splitPositive+splitNegative<>8 then Error("split signature"); fi;
if imaginaryPositive+imaginaryNegative<>7 then Error("imag signature"); fi;
if zeroDivisorNorm<>0 or oneNorm<>1 then Error("norms"); fi;
if associatorWitness=0 then Error("assoc witness"); fi;
if associatorObstruction+anomalyCounterterm<>0 then Error("compensation"); fi;
if [2,4][1]+[2,4][2]<>6 or [3,3][1]+[3,3][2]<>6 then Error("orbit sig"); fi;
if AdCoeff(1)<>-4 or AdCoeff(-1)<>4 then Error("ad coeff"); fi;
if 24+1+10+10<>45 then Error("so55 su5"); fi;
if imaginaryNullQuadricDim<>6 then Error("null quadric"); fi;
if varlamovEven<>16 or varlamovOdd<>16 or varlamovEven+varlamovOdd<>32 or varlamovEven-varlamovOdd<>0 then Error("varlamov"); fi;
if Mobius(Mobius(7))<>7 or 7+Mobius(7)<>0 then Error("mobius"); fi;
if List([-1,0,1],Trip)<>[0,0,0] then Error("trip"); fi;
edges:=["realizes","has","obstructs","compensated_by","bridges_to"];
Print(rec(zornSlots:=zornSlots,splitSignature:=[4,4],imaginarySignature:=[3,4],imaginaryNullQuadricDim:=imaginaryNullQuadricDim,zeroDivisorNorm:=zeroDivisorNorm,oneNorm:=oneNorm,associatorWitness:=associatorWitness,positiveOrbitSignature:=[2,4],negativeOrbitSignature:=[3,3],subalgebraBound:=4,adSquareCoeffNpos:=AdCoeff(1),adSquareCoeffNneg:=AdCoeff(-1),anomalyCompensated:=0,so55su5Partition:=45,varlamovEven:=varlamovEven,varlamovOdd:=varlamovOdd,wittenMoebiusIndex:=varlamovEven-varlamovOdd,mobiusInvolutive:=true,kleinPairInvariant:=0,tripotentRoots:=[-1,0,1],edges:=Length(edges)),"\n");
QUIT;
