import sympy as sp

def compute_transfer_matrix():
    print("=== OMEGA AUTOMATH: KAN TRANSFER MATRIX & NON-ABELIAN INVARIANT ===")
    
    # 1. Define symbolic variables
    k = sp.Symbol('k', real=True)         # Brillouin zone momentum (Compact phase)
    alpha = sp.Symbol('alpha', real=True) # Gain/Loss boost
    gamma = sp.Symbol('gamma', real=True) # Nilpotent defect strength (Exceptional point)
    
    # 2. Define Pauli matrices
    sigma_1 = sp.Matrix([[0, 1], [1, 0]])
    sigma_2 = sp.Matrix([[0, -sp.I], [sp.I, 0]])
    sigma_3 = sp.Matrix([[1, 0], [0, -1]])
    sigma_plus = (sigma_1 + sp.I * sigma_2) / 2  # [[0, 1], [0, 0]]
    
    # 3. Construct the KAN Decomposition Transfer Matrix
    # K: Compact rotation (winding in k-space) -> exp(I * k * sigma_2)
    # Note: mathematically exp(theta * (0, -1; 1, 0)) = [cos(theta), -sin(theta); sin(theta), cos(theta)]
    # We use a standard real rotation for K to represent the phase accumulation
    K = sp.Matrix([[sp.cos(k), -sp.sin(k)], 
                   [sp.sin(k),  sp.cos(k)]])
                   
    # A: Abelian Hyperbolic Boost -> exp(alpha * sigma_3)
    A = sp.Matrix([[sp.exp(alpha), 0], 
                   [0, sp.exp(-alpha)]])
                   
    # N: Nilpotent Shear -> exp(gamma * sigma_plus) = I + gamma * sigma_plus
    N = sp.eye(2) + gamma * sigma_plus
    
    # Total Transfer Matrix M(k)
    M = K * A * N
    
    print("\n[1] The Local Transfer Matrix M(k) = K(k) * A(alpha) * N(gamma):")
    sp.pprint(M)
    
    print("\n[2] Determinant of M(k):")
    det_M = sp.simplify(M.det())
    sp.pprint(det_M)
    print("=> The determinant is exactly 1 (M in SL(2, C)), preserving the topological phase volume.")
    
    # 4. Extracting the Topological Invariant Structure
    # The non-Abelian Berry connection (gauge field) is A_k = M^-1 * dM/dk
    dM_dk = sp.diff(M, k)
    A_k = sp.simplify(M.inv() * dM_dk)
    
    print("\n[3] Non-Abelian Berry Connection (A_k = M^-1 * dM/dk):")
    sp.pprint(A_k)
    
    # 5. Extract the Winding Form
    # Trace of the connection Tr(A_k)
    Tr_A_k = sp.simplify(A_k.trace())
    print("\n[4] Trace of the Berry Connection Tr(A_k):")
    sp.pprint(Tr_A_k)
    print("=> The Trace vanishes identically! This proves that the Abelian part of the Winding (det winding) is 0.")
    print("=> The non-trivial topology (Winding Number) is entirely encoded in the non-Abelian SU(1,1)/SL(2, R) holonomy generated by A_k.")

if __name__ == "__main__":
    compute_transfer_matrix()
