import proofs.TwoSheetChiralClosure
import proofs.SplitOctonionChiralClosure
import proofs.CanonicalZornFiveGradedClosure

/-!
# Derivation and five-graded sectors of the two-sheet chiral algebra

The finite `M₄(ℂ)` algebra supplies the operator-image generators.  The
canonical conformal matrix algebra on `1 ⊕ ℂ⁸ ⊕ 1` supplies their honest
five-graded Lie envelope.  Mixed `g₋₁/g₁` brackets are explicit grade-zero
inner derivations, while the two independent `g±₁` blocks generate `g±₂`.
-/

noncomputable section

namespace TwoSheetChiralTKKDerivations

open TKKJordanPairData TKKJordanPairData.TKKGrade
open CanonicalZornFiveGradedClosure

abbrev L := CanonicalZornFiveGradedClosure.ConformalMatrix
abbrev Zorn := SplitOctonionBraidSU3.Zorn

/-- A common coordinate seed; the different conformal blocks distinguish the
two-sheet and chiral copies and make their extremal bracket nonzero. -/
def seed : Zorn := CanonicalZornFiveGradedClosure.zornCoordinateZero

/-- Concrete images of the two raising and two lowering generators. -/
def UPlus : L := zornPositive seed
def SPlus : L := zornPositiveSource seed
def UMinus : L := zornNegativeTarget seed
def SMinus : L := zornNegative seed

theorem generator_grades :
    UPlus ∈ conformalGrade p1 ∧ SPlus ∈ conformalGrade p1 ∧
    UMinus ∈ conformalGrade m1 ∧ SMinus ∈ conformalGrade m1 := by
  exact ⟨zornPositive_mem seed, zornPositiveSource_mem seed,
    zornNegativeTarget_mem seed, zornNegative_mem seed⟩

/-- Extremal sectors generated from the two independent copies of `g±₁`. -/
def QPlus : L := ⁅UPlus, SPlus⁆
def QMinus : L := ⁅UMinus, SMinus⁆

theorem extremal_grades :
    QPlus ∈ conformalGrade p2 ∧ QMinus ∈ conformalGrade m2 := by
  exact ⟨bracket_grade_closed canonicalFiveGradedLieAlgebra (by rfl)
      (zornPositive_mem seed) (zornPositiveSource_mem seed),
    bracket_grade_closed canonicalFiveGradedLieAlgebra (by rfl)
      (zornNegativeTarget_mem seed) (zornNegative_mem seed)⟩

theorem extremal_nonzero : QPlus ≠ 0 ∧ QMinus ≠ 0 := by
  simpa [QPlus, QMinus, UPlus, SPlus, UMinus, SMinus, seed,
    gradeTwoGenerator, gradeMinusTwoGenerator] using
      And.intro gradeTwoGenerator_ne_zero gradeMinusTwoGenerator_ne_zero

/-- Mixed brackets are the missing grade-zero derivation sector. -/
def D (X Y : Zorn) : L := ⁅zornNegative X, zornPositive Y⁆

theorem D_mem_grade_zero (X Y : Zorn) : D X Y ∈ conformalGrade z0 := by
  exact zorn_mixed_bracket_mem_grade_zero X Y

/-- The canonical diagonal derivation generated by the common seed. -/
def D0 : L := D seed seed

theorem D0_middle_entry : D0 (.middle 0) (.middle 0) = 1 := by
  change ((zornNegative seed * zornPositive seed) -
    (zornPositive seed * zornNegative seed)) (.middle 0) (.middle 0) = 1
  simp only [Matrix.sub_apply, Matrix.mul_apply]
  classical
  rw [Fintype.sum_eq_single ConformalIndex.plus]
  · simp [seed, zornNegative, zornPositive, zornCoordinates, zornCoordinateZero]
  · intro b hb
    cases b
    · simp [zornNegative]
    · rename_i i
      simp [zornNegative]
    · exact (hb rfl).elim

theorem D0_ne_zero : D0 ≠ 0 := by
  intro h
  have hentry := congrFun (congrFun h (.middle 0)) (.middle 0)
  rw [D0_middle_entry] at hentry
  simp at hentry

/-- Adjoint action of a grade-zero element. -/
def innerAction (H X : L) : L := ⁅H, X⁆

/-- Every adjoint action in the associative matrix Lie algebra is a genuine
derivation of the Lie bracket. -/
theorem innerAction_leibniz (H X Y : L) :
    innerAction H ⁅X, Y⁆ =
      ⁅innerAction H X, Y⁆ + ⁅X, innerAction H Y⁆ := by
  change H * (X * Y - Y * X) - (X * Y - Y * X) * H =
    (H * X - X * H) * Y - Y * (H * X - X * H) +
      (X * (H * Y - Y * H) - (H * Y - Y * H) * X)
  noncomm_ring

/-- Grade-zero derivations preserve each of the five sectors. -/
theorem grade_zero_action_closed (H : L) (hH : H ∈ conformalGrade z0)
    (g : TKKGrade) (X : L) (hX : X ∈ conformalGrade g) :
    innerAction H X ∈ conformalGrade g := by
  exact bracket_grade_closed canonicalFiveGradedLieAlgebra
    (gradeAdd_z0_left g) hH hX

theorem D_action_closed (X Y : Zorn) (g : TKKGrade) (A : L)
    (hA : A ∈ conformalGrade g) :
    innerAction (D X Y) A ∈ conformalGrade g :=
  grade_zero_action_closed (D X Y) (D_mem_grade_zero X Y) g A hA

/-- Full finite TKK packet: nonzero extremal grades, a nonzero grade-zero
derivation, and grade-preserving adjoint action satisfying Leibniz. -/
theorem two_sheet_chiral_tkk_derivation_synthesis :
    UPlus ∈ conformalGrade p1 ∧ SPlus ∈ conformalGrade p1 ∧
    UMinus ∈ conformalGrade m1 ∧ SMinus ∈ conformalGrade m1 ∧
    QPlus ∈ conformalGrade p2 ∧ QMinus ∈ conformalGrade m2 ∧
    QPlus ≠ 0 ∧ QMinus ≠ 0 ∧ D0 ∈ conformalGrade z0 ∧ D0 ≠ 0 ∧
    (∀ X Y : L, innerAction D0 ⁅X, Y⁆ =
      ⁅innerAction D0 X, Y⁆ + ⁅X, innerAction D0 Y⁆) ∧
    (∀ g A, A ∈ conformalGrade g →
      innerAction D0 A ∈ conformalGrade g) := by
  rcases generator_grades with ⟨hup, hsp, hum, hsm⟩
  rcases extremal_grades with ⟨hqp, hqm⟩
  rcases extremal_nonzero with ⟨hqpn, hqmn⟩
  exact ⟨hup, hsp, hum, hsm, hqp, hqm, hqpn, hqmn,
    D_mem_grade_zero seed seed, D0_ne_zero, innerAction_leibniz D0,
    fun g A hA => grade_zero_action_closed D0 (D_mem_grade_zero seed seed) g A hA⟩

end TwoSheetChiralTKKDerivations

end noncomputable section
