R = QQ;
I2 = matrix{{1_R,0_R},{0_R,1_R}};
e = matrix{{1_R,0_R},{0_R,-1_R}};
ebar = matrix{{0_R,1_R},{-1_R,0_R}};
S = e*ebar;
n = e + ebar;
nbar = e - ebar;
Z2 = matrix{{0_R,0_R},{0_R,0_R}};
comm = (A,B) -> A*B - B*A;
anticomm = (A,B) -> A*B + B*A;
H = -S;
E = (1_R/2_R)*n;
F = (1_R/2_R)*nbar;
Casimir = H*H + 2_R*(E*F + F*E);
assert(e*e == I2);
assert(ebar*ebar == -I2);
assert(anticomm(e,ebar) == Z2);
assert(S*S == I2);
assert(S*n == -n);
assert(n*S == n);
assert(S*nbar == nbar);
assert(nbar*S == -nbar);
assert(anticomm(S,n) == Z2);
assert(anticomm(S,nbar) == Z2);
assert(anticomm(n,nbar) == 4_R*I2);
assert(comm(S,n) == -2_R*n);
assert(comm(S,nbar) == 2_R*nbar);
assert(comm(n,nbar) == -4_R*S);
assert(comm(H,E) == 2_R*E);
assert(comm(H,F) == -2_R*F);
assert(comm(E,F) == H);
assert(Casimir == 3_R*I2);
assert(comm(Casimir,H) == Z2);
assert(comm(Casimir,E) == Z2);
assert(comm(Casimir,F) == Z2);
W = QQ[x,dx, WeylAlgebra => {x=>dx}];
J = ideal(x*dx - dx*x - 1);
assert(numgens J == 1);
edges = {"generated_by","anticommutes_with","closes_to","has_casimir","isomorphic_to"};
assert(#edges == 5);
print {"Ssquare", 1, "anticommutator_n_nbar", 4, "commutator_n_nbar", "-4S", "sl2", true, "casimir", 3, "dmoduleCCRGenerators", numgens J, "graphEdges", #edges};
