import InfoGeometry.Clifford.Cl11
import Mathlib.Analysis.Normed.Algebra.Exponential
import Mathlib.Analysis.Normed.Module.Basic
import Mathlib.Analysis.Normed.Operator.Basic

section KreinThermal

variable {E : Type} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Endomorphism algebra of the doubled space. -/
abbrev AlgebraEnd (E : Type) [NormedAddCommGroup E] [NormedSpace ℝ E] :=
  DoubledSpace E →L[ℝ] DoubledSpace E

/-- `AlgebraEnd` inherits bounded scalar multiplication from its normed-space structure. -/
instance instIsBoundedSMulAlgebraEnd : IsBoundedSMul ℝ (AlgebraEnd E) :=
  inferInstance

/-- Modular conjugation of an observable by the flow generated by `K`. -/
noncomputable def modularShift
    (K : AlgebraEnd E) (β : ℝ) (B : AlgebraEnd E) :
    AlgebraEnd E :=
  (NormedSpace.exp (β • K)) * B * (NormedSpace.exp (-β • K))

/-- Simplified KMS-like algebraic identity at inverse temperature `β`. -/
def SatisfiesKMSLike
    (K : AlgebraEnd E)
    (ω : AlgebraEnd E →L[ℝ] ℝ)
    (β : ℝ) : Prop :=
  ∀ A B : AlgebraEnd E,
    ω (A * modularShift (E := E) K β B) = ω (B * A)

/-- Compatibility alias for `SatisfiesKMSLike`. -/
def SatisfiesKMS
    (K : AlgebraEnd E)
    (ω : AlgebraEnd E →L[ℝ] ℝ)
    (β : ℝ) : Prop :=
  SatisfiesKMSLike (E := E) K ω β

/-- At `β = 0`, the KMS-like identity reduces to trace symmetry `ω (A B) = ω (B A)`. -/
lemma kmsLike_zero_implies_trace
    (K : AlgebraEnd E)
    (ω : AlgebraEnd E →L[ℝ] ℝ)
    (hKMS : SatisfiesKMSLike (E := E) K ω 0) :
    ∀ A B : AlgebraEnd E, ω (A * B) = ω (B * A) := by
  intro A B
  have h := hKMS A B
  simpa [SatisfiesKMSLike, modularShift, zero_smul, neg_zero] using h

/-- Compatibility alias for `kmsLike_zero_implies_trace`. -/
lemma kms_zero_implies_trace
    (K : AlgebraEnd E)
    (ω : AlgebraEnd E →L[ℝ] ℝ)
    (hKMS : SatisfiesKMS (E := E) K ω 0) :
    ∀ A B : AlgebraEnd E, ω (A * B) = ω (B * A) := by
  exact kmsLike_zero_implies_trace (E := E) K ω hKMS

/-- Thermal vacuum data for a chosen modular generator `K`. -/
structure ThermalVacuum (K : AlgebraEnd E) where
  Omega : DoubledSpace E
  modularJ_fixed : modularJ (E := E) Omega = Omega
  generator_annihilates : K Omega = 0
  vacuum_nonzero : Omega ≠ 0

lemma spectralEpsilon_eq_zero_iff (v : DoubledSpace E) :
    spectralEpsilon (E := E) v = 0 ↔ v = 0 := by
  rcases v with ⟨x, y⟩
  constructor
  · intro h
    have hx : x = 0 := by simpa [spectralEpsilon] using congrArg Prod.fst h
    have hy : y = 0 := by simpa [spectralEpsilon] using congrArg Prod.snd h
    ext <;> simp [hx, hy]
  · intro h
    simp [h]

lemma ThermalVacuum.modularJ_Omega
    {K : AlgebraEnd E}
    (Ω : ThermalVacuum (E := E) K) :
    modularJ (E := E) Ω.Omega = Ω.Omega :=
  Ω.modularJ_fixed

/-- Special case: if the generator is `spectralEpsilon`, the vacuum is forced to be zero. -/
lemma ThermalVacuum.eq_zero_of_spectralEpsilon
    (Ω : ThermalVacuum (E := E) (spectralEpsilon (E := E))) :
    Ω.Omega = 0 :=
  (spectralEpsilon_eq_zero_iff (E := E) Ω.Omega).1 Ω.generator_annihilates

/-- Degenerate special case: for generator `ε`, the modular flow fixes the (zero) vacuum. -/
lemma modularFlow_inv_Omega_of_spectralEpsilon
    (Ω : ThermalVacuum (E := E) (spectralEpsilon (E := E)))
    (t : ℝ) :
    (NormedSpace.exp (t • spectralEpsilon (E := E))) Ω.Omega = Ω.Omega := by
  have hzero : Ω.Omega = 0 := Ω.eq_zero_of_spectralEpsilon
  simp [hzero]

/-- Compatibility alias for the degenerate `ε`-generated flow statement. -/
lemma modularFlow_inv_Omega
    (Ω : ThermalVacuum (E := E) (spectralEpsilon (E := E)))
    (t : ℝ) :
    (NormedSpace.exp (t • spectralEpsilon (E := E))) Ω.Omega = Ω.Omega :=
  modularFlow_inv_Omega_of_spectralEpsilon (E := E) Ω t

end KreinThermal
