import Mathlib.Analysis.Complex.Basic
import InfoGeometry.Meta.Architecture

namespace InfoGeometry.Canonical.TopologicalGap

open Complex

/-- The Complex Boost Generator combining Non-Hermitian Gain/Loss and Optical Activity.
    Real part (alpha) corresponds to NHSE.
    Imaginary part (phi) corresponds to Synthetic Magnetic Field (Zeeman splitting). -/
structure ComplexBoost where
  alpha : ℝ
  phi : ℝ

/-- The topological mass gap generated by the complex boost.
    Mathematically, it corresponds to the absolute value of the Trace of the A-matrix. -/
@[rep_depth thermo]
noncomputable def mass_gap (b : ComplexBoost) : ℂ :=
  Complex.exp (b.alpha + b.phi * I) + Complex.exp (-(b.alpha + b.phi * I))

end InfoGeometry.Canonical.TopologicalGap
