import Architect
import InfoGeometry

/-!
AUTO-GENERATED FILE. DO NOT EDIT BY HAND.

Generated from the live Lean environment by `lean/Docs/AutoTag.lean`.
-/

-- auto-generated blueprint annotations
attribute [blueprint] InfoGeometry.Krein.DoubledSpace._proof_1
attribute [blueprint] InfoGeometry.Krein.DoubledSpace
attribute [blueprint] InfoGeometry.FinProb
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore
attribute [blueprint] InfoGeometry.Convex.HessianGeometry
attribute [blueprint] InfoGeometry.Krein.modular_j
attribute [blueprint] InfoGeometry.Core.InvolutiveAutomorphism
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.V
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.instAddCommGroup
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.instModule
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.EndS
attribute [blueprint] InfoGeometry.Convex.HessianGeometry.metricOp
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornMatrix
attribute [blueprint] InfoGeometry.Core.InvolutiveAutomorphism.toFun
attribute [blueprint] InfoGeometry.kl_div
attribute [blueprint] InfoGeometry.Krein.DoubledSpace.ext
attribute [blueprint] InfoGeometry.Canonical.IB.IBProblem
attribute [blueprint] InfoGeometry.Krein.HilbertDoubled
attribute [blueprint] InfoGeometry.fin_kl_div
attribute [blueprint] InfoGeometry.Krein.spectral_epsilon
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum
attribute [blueprint] InfoGeometry.Core.PreservesLinear
attribute [blueprint] InfoGeometry.Krein.NeutralSpace
attribute [blueprint] InfoGeometry.Canonical.MoE.rowSum
attribute [blueprint] InfoGeometry.Canonical.MoE.colSum
attribute [blueprint] InfoGeometry.Canonical.IB.condYGivenX
attribute [blueprint] InfoGeometry.Canonical.IB.IBProblem.beta
attribute [blueprint] InfoGeometry.Krein.HilbertDoubled.instCoeTCWithLpOfNatENNRealProd._proof_1
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornPhase
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornPhase.col
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornPhase.row
attribute [blueprint] InfoGeometry.Canonical.KaehlerGeometry.KaehlerInformationGeometry
attribute [blueprint] InfoGeometry.Canonical.InverseKernel
attribute [blueprint] InfoGeometry.ProbabilityDist
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.anticommutator._proof_2
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.K._proof_1
attribute [blueprint] InfoGeometry.Canonical.IB.baScoreFrozen
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.Pi
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra
attribute [blueprint] InfoGeometry.Clifford.splitQ11
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornTrajectory
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.instNormedSpaceReal
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.instNormedAddCommGroup
attribute [blueprint] InfoGeometry.Convex.HessianGeometry.metric
attribute [blueprint] InfoGeometry.Canonical.InverseKernel.A
attribute [blueprint] InfoGeometry.Canonical.MoE.CliffordLabel
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.instInnerProductSpaceReal
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.J
attribute [blueprint] InfoGeometry.Canonical.KaehlerGeometry.KaehlerInformationGeometry.H
attribute [blueprint] InfoGeometry.Krein.clmComm._proof_1
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.eps
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.SpectralTriple
attribute [blueprint] InfoGeometry.Canonical.InverseKernel.A_MP
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.Hom
attribute [blueprint] InfoGeometry.Canonical.IB.baScoreFrozen_ne_top
attribute [blueprint] InfoGeometry.Canonical.MoE.phaseAt
attribute [blueprint] InfoGeometry.Canonical.ConformalUnification.ConformalInference
attribute [blueprint] InfoGeometry.Canonical.IB.inducedMProjection
attribute [blueprint] InfoGeometry.Canonical.IB.inducedMarginalT
attribute [blueprint] InfoGeometry.Canonical.MoE.CliffordLabel.minus
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.instCompleteSpace
attribute [blueprint] InfoGeometry.Canonical.MoE.CliffordLabel.plus
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.RicciTensor
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.Hom.mk
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra.θ
attribute [blueprint] InfoGeometry.Canonical.InverseKernel.A_D
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornTrajectory.state
attribute [blueprint] InfoGeometry.Canonical.BottDirac.Endomorphism
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.Hom.hom
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.Polarization
attribute [blueprint] InfoGeometry.Canonical.Drazin.IsDrazinInverse.projection
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra.instPreservesLinear
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization
attribute [blueprint] InfoGeometry.Canonical.MoorePenrose.IsMoorePenroseInverse.leftProjector
attribute [blueprint] InfoGeometry.Canonical.ConformalUnification.ConformalInference.toInverseKernel
attribute [blueprint] InfoGeometry.Canonical.IB.ibBlahutArimotoStepFrozen
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect
attribute [blueprint] InfoGeometry.Krein.to_doubled
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.instKreinSpace
attribute [blueprint] InfoGeometry.Geometry.HessianGeometry
attribute [blueprint] InfoGeometry.Canonical.MoE.PermMode
attribute [blueprint] InfoGeometry.Krein.complex_i
attribute [blueprint] InfoGeometry.Canonical.Drazin.IsDrazinInverse
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit
attribute [blueprint] InfoGeometry.Canonical.MoE.HasPositiveRowSums
attribute [blueprint] InfoGeometry.Canonical.MoE.HasPositiveColSums
attribute [blueprint] InfoGeometry.Canonical.MoE.rowNormalize
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedMajorana
attribute [blueprint] InfoGeometry.Canonical.MoE.colNormalize
attribute [blueprint] InfoGeometry.Core.PreservesLieBracket
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.AlgebraEnd
attribute [blueprint] InfoGeometry.Krein.modular_shift
attribute [blueprint] InfoGeometry.Canonical.MoE.CliffordLabel.ctorIdx
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.RealMajoranaCore.instCategory
attribute [blueprint] InfoGeometry.GrandCanonical.GrandCanonicalParams
attribute [blueprint] InfoGeometry.Canonical.IB.ibBlahutArimotoStep
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.SpectralTriple.D
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.InfoSpectralTriple
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.V
attribute [blueprint] InfoGeometry.Volume.ConnesCocycle.AlgebraEnd
attribute [blueprint] InfoGeometry.Canonical.WeylGaugeField
attribute [blueprint] InfoGeometry.Projective.sameRaySetoid
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.instAddCommGroup
attribute [blueprint] InfoGeometry.Core.Generic.SymmetricLieAlgebra
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.instModule
attribute [blueprint] InfoGeometry.Canonical.IBMeasure.distortionRV
attribute [blueprint] InfoGeometry.Clifford.splitQ11_apply
attribute [blueprint] InfoGeometry.Projective.ProjectiveState
attribute [blueprint] InfoGeometry.Canonical.AdditiveLinearization
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealBogoliubovTransform
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.FockEnd
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.K
attribute [blueprint] InfoGeometry.Canonical.MoorePenrose.IsMoorePenroseInverse
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.kmsResidual._proof_1
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.SplitCliffordDatum
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.P
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum.J
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.feature
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedMajorana.core
attribute [blueprint] InfoGeometry.Geometry.dualCoord
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.index
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.energy
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornStep
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.prior
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.SuperParity
attribute [blueprint] InfoGeometry.Canonical.WeylDifferentialOperator
attribute [blueprint] InfoGeometry.bregmanDiv
attribute [blueprint] InfoGeometry.Canonical.ConformalUnification.ConformalInference.D._proof_4
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.kmsResidual._proof_2
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.SplitVielbein
attribute [blueprint] InfoGeometry.Volume.ConnesCocycle.AdditiveModularFlow
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.kmsResidual._proof_3
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.kmsResidual._proof_4
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.SuperParity.even
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.SuperParity.odd
attribute [blueprint] InfoGeometry.Canonical.WeylTrajectory
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.Atom
attribute [blueprint] InfoGeometry.Geometry.DualFlat.DualFlatStructure
attribute [blueprint] InfoGeometry.Convex.LegendrePotential
attribute [blueprint] InfoGeometry.Convex.HessianGeometry.potential
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.bogoliubovAnnihilation._proof_2
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.RealMajoranaCore
attribute [blueprint] InfoGeometry.Canonical.WeylGaugeField.gaugeOf
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.bogoliubovAnnihilation._proof_3
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.Polarization.Pplus
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.Polarization.Pminus
attribute [blueprint] InfoGeometry.LogPotential
attribute [blueprint] InfoGeometry.GrandCanonical.GrandCanonicalParams.energy
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.partition
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.InfoSpectralTriple.H
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.val
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.ScalarRicciFlow
attribute [blueprint] InfoGeometry.LLM.TransformerBlock
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.Hom
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.mongeAmpereDensity
attribute [blueprint] InfoGeometry.Canonical.IsDrazinInverse
attribute [blueprint] InfoGeometry.Canonical.ConformalUnification.ConformalInference.P_D
attribute [blueprint] InfoGeometry.Convex.HessianGeometry.dualMap
attribute [blueprint] InfoGeometry.Canonical.IB.baScore
attribute [blueprint] InfoGeometry.Krein.clmComm._proof_2
attribute [blueprint] InfoGeometry.Information.FiniteExpFamily
attribute [blueprint] InfoGeometry.Core.Projector.plus._proof_1
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealBogoliubovTransform.B
attribute [blueprint] InfoGeometry.Architecture.CartanInvolution
attribute [blueprint] InfoGeometry.Canonical.IBFreeEnergy.klDivENN
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.MajoranaCARWitness._proof_2
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit.Pplus
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit.Pminus
attribute [blueprint] InfoGeometry.Thermo.Z
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedMajorana.polarization
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.SplitCliffordDatum.Mode
attribute [blueprint] InfoGeometry.Canonical.GeneratedFlow
attribute [blueprint] InfoGeometry.Jordan.SPD
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.Hom.mk
attribute [blueprint] InfoGeometry.Krein.gradeMinusProj
attribute [blueprint] InfoGeometry.Canonical.ChiralAnomaly.DoublyStochasticSinkhornTrajectory
attribute [blueprint] InfoGeometry.Canonical.MoE.ExpertIdx
attribute [blueprint] InfoGeometry.Canonical.AnalyticalIndex.chiralKernelSliceMinus
attribute [blueprint] InfoGeometry.Canonical.AnalyticalIndex.chiralKernelSlicePlus
attribute [blueprint] InfoGeometry.GrandCanonical.partition
attribute [blueprint] InfoGeometry.Canonical.Triality.TriadicCore.route
attribute [blueprint] InfoGeometry.Krein.NeutralSpace.ext
attribute [blueprint] InfoGeometry.Canonical.WeylDifferentialOperator.diff
attribute [blueprint] InfoGeometry.GrandCanonical.GrandCanonicalTwoParam
attribute [blueprint] InfoGeometry.Convex.LegendrePotential.f
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.Atom.core
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.einsteinTensorAt
attribute [blueprint] InfoGeometry.Krein.HessianOrthogonalGroup
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit.Hom
attribute [blueprint] InfoGeometry.Canonical.IBFunctional.FiniteKLFamily
attribute [blueprint] InfoGeometry.Canonical.WeylTrajectory.point
attribute [blueprint] InfoGeometry.Canonical.SuperAnomaly.SuperParity
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.SplitVielbein.ePlus
attribute [blueprint] InfoGeometry.Quantum.creationOp
attribute [blueprint] InfoGeometry.Core.LinearInvolutiveAutomorphism
attribute [blueprint] InfoGeometry.Thermal.Hamiltonian
attribute [blueprint] InfoGeometry.Canonical.InformationTorsion.DualConnections
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealBogoliubovTransform.Binv
attribute [blueprint] InfoGeometry.Canonical.SuperAnomaly.SuperParity.odd
attribute [blueprint] InfoGeometry.MeasureProjective.Normalized.probMeasureToPMF
attribute [blueprint] InfoGeometry.KK.KasparovCycle
attribute [blueprint] InfoGeometry.Thermal.DiagonalObservable
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.gibbsProb
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.SpinConnection
attribute [blueprint] InfoGeometry.LogPotential.LegendreModel
attribute [blueprint] InfoGeometry.Krein.cl11RepLin
attribute [blueprint] InfoGeometry.Canonical.IsMoorePenroseInverse
attribute [blueprint] InfoGeometry.Canonical.TomitaTakesaki.modularSignEpsilon
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.BogoliubovParams
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.Hom
attribute [blueprint] InfoGeometry.Canonical.TomitaTakesaki.modularConjugationJ
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.SplitVielbein.eMinus
attribute [blueprint] InfoGeometry.Canonical.InformationTorsion.Connection
attribute [blueprint] InfoGeometry.Canonical.IB.scoreRayDegree
attribute [blueprint] InfoGeometry.LogPotential.ψ
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.instCategory._proof_1
attribute [blueprint] InfoGeometry.Canonical.WeylLineIntegrator
attribute [blueprint] InfoGeometry.MaxEnt.gibbs
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.Hom.hom
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.spectralBasepointLogVolume
attribute [blueprint] InfoGeometry.Core.Generic.SymmetricLieAlgebra.θ
attribute [blueprint] InfoGeometry.Quantum.annihilationOp
attribute [blueprint] InfoGeometry.Canonical.ExactAbelianizingBridge
attribute [blueprint] InfoGeometry.Volume.ConnesCocycle.ScalarCocycleBridge
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra.oddSubmodule
attribute [blueprint] InfoGeometry.Canonical.DefectiveAbelianizingBridge
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.MajoranaCARWitness._proof_1
attribute [blueprint] InfoGeometry.MaxEnt.ACProbMeasure
attribute [blueprint] InfoGeometry.Canonical.IBPythagorean.IBNextEncoder
attribute [blueprint] InfoGeometry.Canonical.WeylFieldStrength
attribute [blueprint] InfoGeometry.Krein.cl11Rep
attribute [blueprint] InfoGeometry.KK.EndH
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra.evenLieSubalgebra
attribute [blueprint] InfoGeometry.Analytic.logSumExpPartition
attribute [blueprint] InfoGeometry.Projective.SelfDualCone
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.RegularizedSpectralTriple
attribute [blueprint] InfoGeometry.Core.InvolutiveAutomorphism.mk
attribute [blueprint] InfoGeometry.LLM.CausalMask
attribute [blueprint] InfoGeometry.Projective.positiveOrthantCone
attribute [blueprint] InfoGeometry.Canonical.ExactMultiplicativeToAdditiveBridge
attribute [blueprint] InfoGeometry.Canonical.CertifiedInverseKernel
attribute [blueprint] InfoGeometry.SuperUnified.End
attribute [blueprint] InfoGeometry.Canonical.RealBdG.EndH
attribute [blueprint] InfoGeometry.Jordan.SPD.mat
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.mk
attribute [blueprint] InfoGeometry.Canonical.LogGenerator
attribute [blueprint] InfoGeometry.Architecture.CartanInvolution.toMulAut
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.superBracket
attribute [blueprint] InfoGeometry.Canonical.AnalyticalIndex.analyticalIndex
attribute [blueprint] InfoGeometry.Canonical.DefectiveMultiplicativeToAdditiveBridge
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit.Hom.mk
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.Atom.Hom
attribute [blueprint] InfoGeometry.Canonical.IB.ScoreSlice
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.LadderPresentation
attribute [blueprint] InfoGeometry.MeasureProjective.UState
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.scalarRicciBetaFunction
attribute [blueprint] InfoGeometry.Canonical.ChiralAnomaly.DoublyStochasticSinkhornTrajectory.traj
attribute [blueprint] InfoGeometry.Krein.HessianOrthogonalGroup.mk
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.Hom.mk
attribute [blueprint] InfoGeometry.Canonical.ConformalUnification.ConformalInference.chiralScale
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedMajorana.Hom
attribute [blueprint] InfoGeometry.Core.CartanDecomposition
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.gibbsDist
attribute [blueprint] InfoGeometry.Krein.HilbertDoubled.val
attribute [blueprint] InfoGeometry.GrandCanonical.gibbsWeight
attribute [blueprint] InfoGeometry.Canonical.WeylHolonomyMap
attribute [blueprint] InfoGeometry.ExponentialFamily.FiniteExponentialFamilyData
attribute [blueprint] InfoGeometry.Canonical.IBFunctional.IBGlobalFreeEnergy
attribute [blueprint] InfoGeometry.Information.density
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.SinkhornKMSClosure
attribute [blueprint] InfoGeometry.Canonical.GaugeGroups.SUN
attribute [blueprint] InfoGeometry.GrandCanonical.shiftedEnergy
attribute [blueprint] InfoGeometry.Canonical.DualConnections.ConnectionTensor
attribute [blueprint] InfoGeometry.CliffordTower.SplitSpace
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit.Hom.f
attribute [blueprint] InfoGeometry.Projective.projectivize
attribute [blueprint] InfoGeometry.Volume.ConnesCocycle.AdditiveModularFlow.toFun
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.anticommutator
attribute [blueprint] InfoGeometry.MaxEnt.JaynesRNMaxEnt.MomentFamily
attribute [blueprint] InfoGeometry.Krein.HessianOrthogonalGroup.equiv
attribute [blueprint] InfoGeometry.Core.LieTripleSystem
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.instCategory
attribute [blueprint] InfoGeometry.Krein.isOdd
attribute [blueprint] InfoGeometry.Canonical.GeometricResponse
attribute [blueprint] InfoGeometry.CliffordTower.splitSpaceAddCommGroup
attribute [blueprint] InfoGeometry.Canonical.IB.finProbMassNndist
attribute [blueprint] InfoGeometry.Krein.Supercharge
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.Atom.Hom.mk
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.spinorialScalarCurvature
attribute [blueprint] InfoGeometry.SuperUnified.SuperKaehlerStructure
attribute [blueprint] InfoGeometry.MaxEnt.JaynesInfoStatMech.ThermalDiagonal.DiagObservable
attribute [blueprint] InfoGeometry.MeasureProjective.NonzeroUState
attribute [blueprint] InfoGeometry.EmpiricalCounts
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.SplitCliffordDatum.majoranaField
attribute [blueprint] InfoGeometry.Canonical.GrandUnification.JordanKKTData.gradK
attribute [blueprint] InfoGeometry.Canonical.RGFlow.InformationFlow
attribute [blueprint] InfoGeometry.Geometry.DualFlat.divergence
attribute [blueprint] InfoGeometry.Canonical.InformationTorsion.informationTorsion
attribute [blueprint] InfoGeometry.CliffordTower.Q11
attribute [blueprint] InfoGeometry.Canonical.FunctionalCalculusLinearization
attribute [blueprint] InfoGeometry.MaxEnt.Finite.FiniteJaynesProblem.logPartition
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum.K
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.SplitCliffordDatum.majoranaPairing
attribute [blueprint] InfoGeometry.Canonical.WeylGaugeParameter
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.BogoliubovParams.u
attribute [blueprint] InfoGeometry.Thermal.DiagonalObservable.mk
attribute [blueprint] InfoGeometry.KL.EntropicInferenceTest.State
attribute [blueprint] InfoGeometry.Krein.HilbertDoubled.toLp
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.BogoliubovParams.v
attribute [blueprint] InfoGeometry.EntropicInference.Joint
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.Hom.f
attribute [blueprint] InfoGeometry.CliffordTower.splitSpaceModule
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedMajorana.Hom.mk
attribute [blueprint] InfoGeometry.Singular.MoorePenrose.IsMoorePenroseInverse
attribute [blueprint] InfoGeometry.Canonical.InformationTorsion.DualConnections.nabla
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedLadderRealization
attribute [blueprint] InfoGeometry.Canonical.FiniteCoarseGraining
attribute [blueprint] InfoGeometry.MaxEnt.LinearConstraint
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum.KAntilinear._proof_1
attribute [blueprint] InfoGeometry.CliffordTower.Qsplit
attribute [blueprint] InfoGeometry.Canonical.Gauge.Signature.split
attribute [blueprint] InfoGeometry.Geometry.DualFlat.nabla
attribute [blueprint] InfoGeometry.Canonical.GaugeGroups.SUNCenter
attribute [blueprint] InfoGeometry.Canonical.DualConnections.alphaConnection
attribute [blueprint] InfoGeometry.LLM.MaskedTransformerBlock
attribute [blueprint] InfoGeometry.MaxEnt.ShannonEntropy
attribute [blueprint] InfoGeometry.Thermo.ThermalModel
attribute [blueprint] InfoGeometry.Canonical.MoE.Expert
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.instCategory._proof_1
attribute [blueprint] InfoGeometry.Krein.hessian_indefinite_form
attribute [blueprint] InfoGeometry.Canonical.SpineFunctorKind
attribute [blueprint] InfoGeometry.KK.IsCompactEnd
attribute [blueprint] InfoGeometry.Convex.HessianGeometry1D
attribute [blueprint] InfoGeometry.Singular.Drazin.IsDrazinInverse
attribute [blueprint] InfoGeometry.Canonical.InformationTorsion.TwistedInference
attribute [blueprint] InfoGeometry.Thermo.gibbsProb
attribute [blueprint] InfoGeometry.Convex.ConvexFunctional
attribute [blueprint] InfoGeometry.Canonical.Attention.ContextWindow
attribute [blueprint] InfoGeometry.Canonical.DualConnections.fisherMetric
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.PolarizationSplit.Hom.finv
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.Polarization.mk
attribute [blueprint] InfoGeometry.Thermo.Op
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.SatisfiesNormalizedKaehlerRicciFlow
attribute [blueprint] InfoGeometry.ExponentialFamily.Gaussian.GaussianFamily
attribute [blueprint] InfoGeometry.MaxEnt.JaynesInfoStatMech.ConstraintFamily
attribute [blueprint] InfoGeometry.Canonical.IB.SameScoreRay
attribute [blueprint] InfoGeometry.Canonical.TopologicalInvariants.BayesianLoop
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.KPolarization.Hom.finv
attribute [blueprint] InfoGeometry.Canonical.IB.ibBlahutArimotoStepUnnormalized
attribute [blueprint] InfoGeometry.Thermo.energyFromBregman
attribute [blueprint] InfoGeometry.MaxEnt.JaynesInfoStatMech.Observable
attribute [blueprint] InfoGeometry.Canonical.DualConnections.amariChentsovTensor
attribute [blueprint] InfoGeometry.Canonical.IBPythagorean.IBNextMarginal
attribute [blueprint] InfoGeometry.GrandCanonical.partitionGC
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.cl11DoubledCore
attribute [blueprint] InfoGeometry.Canonical.MoE.SplitCliffordSuperData
attribute [blueprint] InfoGeometry.Thermal.DiagonalObservable.coeff
attribute [blueprint] InfoGeometry.Canonical.WeylGaugeField.mk
attribute [blueprint] InfoGeometry.Projective.positiveOrthant
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.CertifiedChiralSpectralTriple
attribute [blueprint] InfoGeometry.Projective.SelfDualCone.cone
attribute [blueprint] InfoGeometry.Canonical.MoE.Coupling
attribute [blueprint] InfoGeometry.Core.conjugationMap._proof_1
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.Atom.Hom.homCore
attribute [blueprint] InfoGeometry.Core.conjugationMap._proof_2
attribute [blueprint] InfoGeometry.Canonical.IB.BANormalizeLipschitzData
attribute [blueprint] InfoGeometry.Core.PreservesMul
attribute [blueprint] InfoGeometry.LLM.PositionalEncoding
attribute [blueprint] InfoGeometry.Canonical.ConformalUnification.CertifiedConformalInference
attribute [blueprint] InfoGeometry.Canonical.Triality.TriadicCore.interact
attribute [blueprint] InfoGeometry.Canonical.MoE.switchMatrix
attribute [blueprint] InfoGeometry.Core.Generic.SymmetricLieAlgebra.𝔨
attribute [blueprint] InfoGeometry.Canonical.ScaleEquivariantFlow
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.FockEndomorphism
attribute [blueprint] InfoGeometry.Canonical.BekensteinBound.phaseRNGeneratorBefore
attribute [blueprint] InfoGeometry.Core.conjugationMap._proof_3
attribute [blueprint] InfoGeometry.Canonical.GrandUnification.JordanKKTData.K
attribute [blueprint] InfoGeometry.Core.Generic.SymmetricLieAlgebra.𝔭
attribute [blueprint] InfoGeometry.LogPotential.LegendreModel.massieu
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.IsEinsteinKaehlerAtWith
attribute [blueprint] InfoGeometry.SuperUnified.lieBracket._proof_2
attribute [blueprint] InfoGeometry.Clifford.splitB11
attribute [blueprint] InfoGeometry.Projective.ConeInteriorStateSpace
attribute [blueprint] InfoGeometry.Canonical.Cayley.Transport.toBounded
attribute [blueprint] InfoGeometry.EntropicInference.marginal_x
attribute [blueprint] InfoGeometry.Canonical.MoE.SplitCliffordAlg
attribute [blueprint] InfoGeometry.MeasureProjective.ProjectiveState
attribute [blueprint] InfoGeometry.Canonical.Determinant.SpectralZetaLogDetData
attribute [blueprint] InfoGeometry.Architecture.SymmetricSpace
attribute [blueprint] InfoGeometry.Architecture.SymmetricPair
attribute [blueprint] InfoGeometry.Core.SymmetricSpace
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.ChiralSpectralTriple
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.anticommutator
attribute [blueprint] InfoGeometry.Canonical.CartanDecomposition.InformationCartanTriple
attribute [blueprint] InfoGeometry.Krein.ThermalVacuum
attribute [blueprint] InfoGeometry.Canonical.RealBdG.RealBdGDatum
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.cl11SplitCliffordDatum
attribute [blueprint] InfoGeometry.Canonical.SuperAnomaly.EndH
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.PolarizedMajorana.Hom.homCore
attribute [blueprint] InfoGeometry.Canonical.ExactDescentLogGenerator
attribute [blueprint] InfoGeometry.Canonical.SuperInference.SuperState
attribute [blueprint] InfoGeometry.Canonical.KreinLadder.InformationLadder
attribute [blueprint] InfoGeometry.Singular.Architecture.SingularNaturalGradientFlow
attribute [blueprint] InfoGeometry.Canonical.WeylLineIntegrator.holonomy
attribute [blueprint] InfoGeometry.Prequantum.ProjectivePrequantumBundle
attribute [blueprint] InfoGeometry.Canonical.Attention.Vec
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.VacuumEinsteinOnTransportedSplit
attribute [blueprint] InfoGeometry.Canonical.BottDirac.cl11DiracSeed
attribute [blueprint] InfoGeometry.Canonical.WeylLineIntegrator.integrateCurvature
attribute [blueprint] InfoGeometry.MaxEnt.CanonicalProblem
attribute [blueprint] InfoGeometry.Core.OddLocalModel
attribute [blueprint] InfoGeometry.Canonical.DefectiveDescentLogGenerator
attribute [blueprint] InfoGeometry.Core.CartanDecomposition.θ
attribute [blueprint] InfoGeometry.Canonical.MoE.trajectoryRNBarrier
attribute [blueprint] InfoGeometry.Jordan.JordanAlgebra
attribute [blueprint] InfoGeometry.Volume.RadonNikodym.HasScalarRNBridge
attribute [blueprint] InfoGeometry.Geometry.GradientBijection
attribute [blueprint] InfoGeometry.Canonical.SpinConnection
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.ibInducedObservableWeighted
attribute [blueprint] InfoGeometry.Canonical.WeylTransportBridge.FlatCurvatureChiralScaleBridge
attribute [blueprint] InfoGeometry.Krein.spectralMinusProj
attribute [blueprint] InfoGeometry.Krein.spectralPlusProj
attribute [blueprint] InfoGeometry.Canonical.TomitaTakesaki.RoutingSplitCliffordAlg
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.StrongRicciFromHessian
attribute [blueprint] InfoGeometry.Canonical.SpectralInference.CertifiedRegularizedSpectralTriple
attribute [blueprint] InfoGeometry.MaxEnt.totalCount
attribute [blueprint] InfoGeometry.MaxEnt.JaynesInfoStatMech.ProbDist
attribute [blueprint] InfoGeometry.Clifford.Soldering.Vec22
attribute [blueprint] InfoGeometry.Canonical.GrandSynthesis.kahlerPotentialRN
attribute [blueprint] InfoGeometry.Projective.InfoGeometry.Projective.PhysicalKinematics
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra.plusPart
attribute [blueprint] InfoGeometry.Core.SymmetricLieAlgebra.minusPart
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum.Pi
attribute [blueprint] InfoGeometry.Convex.OneD.IsGradientDual
attribute [blueprint] InfoGeometry.Canonical.SuperAnomaly.superComm
attribute [blueprint] InfoGeometry.Quantum.RealKCategory.RealKVect.complexToRealK
attribute [blueprint] InfoGeometry.Convex.OneD.DualFlatPotential
attribute [blueprint] InfoGeometry.Canonical.QuantumInference.CCR
attribute [blueprint] InfoGeometry.Canonical.ChiralRGFlow.ChiralAsymptoticModel
attribute [blueprint] InfoGeometry.MaxEnt.MaxEntProblem
attribute [blueprint] InfoGeometry.Geometry.DualFlat.ProjectiveBridge.UnnormalizedMeasure
attribute [blueprint] InfoGeometry.Canonical.ChiralRGFlow.ChiralMassFlow
attribute [blueprint] InfoGeometry.Thermal.Hamiltonian.gibbsWeight
attribute [blueprint] InfoGeometry.Canonical.GaugeGroups.SU2N
attribute [blueprint] InfoGeometry.MaxEnt.JaynesInfoStatMech.ThermalDiagonal.gibbsProb
attribute [blueprint] InfoGeometry.Canonical.MoE.SinkhornCertificate
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.BogoliubovMixingParams
attribute [blueprint] InfoGeometry.KK.FinModelE
attribute [blueprint] InfoGeometry.Canonical.WeylGaugeField.IsFlat
attribute [blueprint] InfoGeometry.Canonical.OperatorLogGenerator
attribute [blueprint] InfoGeometry.Canonical.IBMeasure.IBUnnormalized
attribute [blueprint] InfoGeometry.Canonical.GrandSynthesis.relativeVolumeChangeRN
attribute [blueprint] InfoGeometry.Canonical.CalabiYauBridge.UnitRelativeVolumeState
attribute [blueprint] InfoGeometry.Canonical.GaugeGroups.PSUN
attribute [blueprint] InfoGeometry.Canonical.Attention.Head
attribute [blueprint] InfoGeometry.MaxEnt.BurgModel
attribute [blueprint] InfoGeometry.Canonical.GaugeGroups.SUN.carrier
attribute [blueprint] InfoGeometry.Canonical.BottDirac.bottDirac
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.anticommutator
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.omegaSeed
attribute [blueprint] InfoGeometry.Canonical.InformationTorsion.FlatDualConnections
attribute [blueprint] InfoGeometry.Canonical.MoE.MoELayer
attribute [blueprint] InfoGeometry.SuperUnified.SuperKaehlerStructure.J
attribute [blueprint] InfoGeometry.Thermo.FiniteDiagonal.gibbsWeight
attribute [blueprint] InfoGeometry.Canonical.SuperAnomaly.SuperWeightLike
attribute [blueprint] InfoGeometry.Quantum.SplitCliffordAtom.Atom.instCategory
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.JointKernelOnOmega
attribute [blueprint] InfoGeometry.KK.KasparovProductData
attribute [blueprint] InfoGeometry.Core.CartanLieStructure
attribute [blueprint] InfoGeometry.KK.KasparovCycle.F
attribute [blueprint] InfoGeometry.Quantum.RealMajoranaCategory.LadderMajorana
attribute [blueprint] InfoGeometry.Projective.Gauge
attribute [blueprint] InfoGeometry.Canonical.KMSSinkhornBridge.CommutatorOrthogonalOnOmega
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.RicciData
attribute [blueprint] InfoGeometry.Canonical.BogoliubovFockSuper.einsteinInducedChemicalPotential
attribute [blueprint] InfoGeometry.Krein.FiniteDimensionalExponentialFlow
attribute [blueprint] InfoGeometry.Geometry.HilbertHessian
attribute [blueprint] InfoGeometry.Canonical.GrandUnification.JordanKKTData.DBregman
attribute [blueprint] InfoGeometry.Geometry.HessianManifold
attribute [blueprint] InfoGeometry.MaxEnt.AsymptoticEquipartitionWitness
attribute [blueprint] InfoGeometry.Canonical.RicciMongeAmpere.VacuumEinsteinEquationAt
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum.weylPlus
attribute [blueprint] InfoGeometry.Core.CartanLieAlgebra
attribute [blueprint] InfoGeometry.Volume.ConnesCocycle.IsConnesCocycle
attribute [blueprint] InfoGeometry.Core.Generic.SymmetricLieAlgebra.CartanLieAlgebra
attribute [blueprint] InfoGeometry.Canonical.ExponentialGeneratedFlow
attribute [blueprint] InfoGeometry.Canonical.BeliefAlgebra.BeliefSystem
attribute [blueprint] InfoGeometry.Projective.instSMulGaugeDoubledSpace
attribute [blueprint] InfoGeometry.Quantum.RealMajorana.RealMajoranaDatum.weylMinus
attribute [blueprint] InfoGeometry.Canonical.RelativeWeight
