import InfoGeometry.ErlangenLanglandsLane
import InfoGeometry.ErlangenLanglandsGeometryLane
import InfoGeometry.GromovWittenProjectiveLane
import InfoGeometry.GromovWittenErlangen.Entry
import InfoGeometry.GrandUnification.ModularTransport
import InfoGeometry.GrandUnification.SpectralThermalNormalization
import InfoGeometry.LanglandsGWBridge
import InfoGeometry.GromovHomologicalProbabilityRoadmap
import InfoGeometry.ModularVolumePotential

noncomputable section

-- Geometry → operator-Erlangen spine
/-
#check InfoGeometry.Geometry.BilingualUpperHalfPlane
#check InfoGeometry.Geometry.PhaseLinear.map_K
#check InfoGeometry.Geometry.BilingualUpperHalfPlane.moebiusMap

-- Finite optics/Erlangen bridge
#check InfoGeometry.OperatorAlgebra.FiniteJonesOptics.diagonalEvent
#check InfoGeometry.OperatorAlgebra.FiniteJonesOptics.det2
#check InfoGeometry.OperatorAlgebra.FiniteJonesOptics.det2_brewsterEvent_jones
#check InfoGeometry.OperatorAlgebra.FiniteJonesErlangerBridge.DiagonalJonesGauge
#check InfoGeometry.OperatorAlgebra.FiniteJonesErlangerBridge.brewsterCoreProjector_is_fixed_Erlanger_object
#check InfoGeometry.OperatorAlgebra.FiniteJonesErlangerBridge.FiniteJonesErlangerBridgeOwnerTarget

-- Invariants and casimir socket
#check IndividuatedCasimir.VerifiedCasimir
#check IndividuatedCasimir.VerifiedCasimir.mem_center

-- Conformal crossover/reset layer
#check InfoGeometry.OperatorAlgebra.ConformalCyclicCosmology.AeonConformalCrossover
#check InfoGeometry.OperatorAlgebra.ConformalCyclicCosmology.CrossoverLightlikeGrammar
#check InfoGeometry.OperatorAlgebra.ConformalCyclicCosmology.CrossoverMemoryRecoveryBridge.residue_recovers_old_memory

-- Automorphic projection/spectral layer
#check InfoGeometry.Automorphic.KreinBridge.AutomorphicKreinBridge.cuspidalProjector_yields_PCuspidal
#check InfoGeometry.Automorphic.LFunctionResonance.cuspidalLFunction
#check InfoGeometry.Automorphic.SiegelResonance.rawLFunction
#check InfoGeometry.Automorphic.SiegelResonance.CompletedLFunctionWitness.completed_functional_equation_valid
#check InfoGeometry.Automorphic.RoelckeSelbergSpectral.AutomorphicLFunctionDatum.potential_eq_zero_of_abs_eq_one

-- Langlands bridge layer
#check InfoGeometry.Automorphic.LanglandsSugawaraBridge.centralCharge_eq_completedL
#check InfoGeometry.Automorphic.LanglandsPrimeResonance.LanglandsSugawaraBridge.central_zero_iff_L_zero
#check InfoGeometry.Automorphic.LanglandsPrimeResonance.LanglandsSugawaraBridge.bulk_central_zero_iff_prime_resonance

-- Physical Langlands/duality sockets
#check InfoGeometry.OperatorAlgebra.KapustinWittenDualitySocket.SDualityDatum.wilsonEigen_transports_to_tHooftEigen
#check InfoGeometry.OperatorAlgebra.KapustinWittenDualitySocket.operatorSDualityOwnerTarget
#check InfoGeometry.OperatorAlgebra.PhysicalLanglandsHolonomy.KWPhysicalDualityWitness.wilson_readout_eq_dual_thooft
#check InfoGeometry.OperatorAlgebra.PhysicalLanglandsHolonomy.physicalLanglandsHolonomyOwnerTarget

-- Return and boundary interpretation
#check InfoGeometry.OperatorAlgebra.KleinianReturn.ProjectiveTomitaReturn
#check InfoGeometry.OperatorAlgebra.SelfDualChiralConeBoundary.SelfDualChiralConeBoundary
#check InfoGeometry.Canonical.KleinBottleOrientifold.KleinBottleOrientifold
#check InfoGeometry.Canonical.zeta_trace_bridge

-- Modular/holonomy refinement
#check InfoGeometry.Canonical.BerryRotorBridge.AbelianModularBerryData.modularBerryRotor_eq_curvatureIntegral_plus_anomaly

-- Lane core artifacts
#check InfoGeometry.ErlangenLanglandsLane.LanglandsLaneArithmeticPacket
#check InfoGeometry.ErlangenLanglandsLane.constructLanglandsLanePacket
#check InfoGeometry.ErlangenLanglandsLane.LanglandsLaneCoreTarget
#check InfoGeometry.ErlangenLanglandsLane.LanglandsGeometryArithmeticIntertwiner
#check InfoGeometry.ErlangenLanglandsLane.LanglandsGeometryToArithmetic
#check InfoGeometry.ErlangenLanglandsLane.LanglandsGeometryCorrespondence
#check InfoGeometry.ErlangenLanglandsLane.constructLanglandsLanePacket_withGeometry
#check InfoGeometry.ErlangenLanglandsLane.LanglandsLaneGeometryPacket
#check InfoGeometry.ErlangenLanglandsLane.LanglandsLaneFullPacket
#check InfoGeometry.ErlangenLanglandsLane.constructFullLanglandsLanePacket
#check InfoGeometry.ErlangenLanglandsLane.LanglandsLaneFullTarget
#check InfoGeometry.GromovWittenProjectiveLane.ErlangenLanglandsGromovLaneTarget
#check InfoGeometry.GromovWittenProjectiveLane.constructErlangenLanglandsGWFromPacket
#check InfoGeometry.GromovWittenErlangen.LieOrbitCurveWitness
#check InfoGeometry.GromovWittenErlangen.LocalizationGraphWitness
#check InfoGeometry.GromovWittenErlangen.LanglandsDualOrbitCurveWitness
#check InfoGeometry.GromovWittenErlangen.VirtualLocalizationOrbitPacket
#check InfoGeometry.GromovWittenErlangen.KleinGromovPacket
#check InfoGeometry.GromovWittenErlangen.constructKleinGromovPacket
#check InfoGeometry.LanglandsGWBridge.SymplecticQuotientWitness
#check InfoGeometry.LanglandsGWBridge.WeylIntegrationWitness
#check InfoGeometry.LanglandsGWBridge.SymplecticWeylVolumePacket
#check InfoGeometry.LanglandsGWBridge.SymplecticWeylVolumeTarget
#check InfoGeometry.LanglandsGWBridge.constructSymplecticWeylVolumeTarget
#check InfoGeometry.LanglandsGWBridge.constructSymplecticWeylVolumePacket
#check InfoGeometry.ModularVolumePotential.LogRadonNikodymPacket
#check InfoGeometry.ModularVolumePotential.RelativeSurprisalPacket
#check InfoGeometry.ModularVolumePotential.GibbsFreeEnergyPacket
#check InfoGeometry.ModularVolumePotential.ModularFlowPacket
#check InfoGeometry.ModularVolumePotential.SupervolumePacket
#check InfoGeometry.ModularVolumePotential.GKSLPacket
#check InfoGeometry.ModularVolumePotential.SpectralBoltzmannPacket
#check InfoGeometry.ModularVolumePotential.FiniteSpectralBoltzmannPartition
#check InfoGeometry.ModularVolumePotential.FiniteSpectralThermalNormalizationTarget
#check InfoGeometry.ModularVolumePotential.constructSpectralThermalNormalizationTarget
#check InfoGeometry.ModularVolumePotential.SpectralThermalNormalizationPacket
#check InfoGeometry.ModularVolumePotential.SpectralThermalNormalizationTarget
#check InfoGeometry.ModularVolumePotential.constructSpectralThermalNormalizationPacketTarget
#check InfoGeometry.ModularVolumePotential.ModularTransportBridgePacket
#check InfoGeometry.ModularVolumePotential.ModularTransportBridgeTarget
#check InfoGeometry.ModularVolumePotential.constructModularTransportBridgeTarget
#check InfoGeometry.ModularVolumePotential.finiteSpectralPartitionNormalization
#check InfoGeometry.ModularVolumePotential.FiniteSpectralThermodynamicNormalizationSchema
#check InfoGeometry.ModularVolumePotential.constructFiniteSpectralThermodynamicNormalizationSchema
#check InfoGeometry.ModularVolumePotential.modularPartitionNormalization
#check InfoGeometry.ModularVolumePotential.modularPartitionNormalization_trace
#check InfoGeometry.ModularVolumePotential.modularPartitionNormalization_kms
#check InfoGeometry.ModularVolumePotential.ModularVolumeBridgePacket
#check InfoGeometry.ModularVolumePotential.ModularVolumeBridgeTarget
#check InfoGeometry.ModularVolumePotential.constructModularVolumeBridgeTarget
#check InfoGeometry.GrandUnification.ModularTransportBridgePacket
#check InfoGeometry.GrandUnification.ModularTransportBridgeTarget
#check InfoGeometry.GrandUnification.constructModularTransportBridgeTarget
#check InfoGeometry.ModularVolumePotential.TomitaGromovBridgePacket
#check InfoGeometry.ModularVolumePotential.TomitaGromovBridgeTarget
#check InfoGeometry.ModularVolumePotential.constructTomitaGromovBridgeTarget
#check InfoGeometry.GrandUnification.TomitaGromovBridgePacket
#check InfoGeometry.GrandUnification.TomitaGromovBridgeTarget
#check InfoGeometry.GrandUnification.constructTomitaGromovBridgeTarget
#check InfoGeometry.ModularVolumePotential.ModularVolumePotentialPacket
#check InfoGeometry.ModularVolumePotential.ModularVolumePotentialTarget
#check InfoGeometry.ModularVolumePotential.constructModularVolumePotentialTarget
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.MomentumMapProbabilityPacket
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.HomologicalMeasurePacket
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.MovingBallConfigurationPacket
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.CycleVolumeSpectrumPacket
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.WeylVolumeGaugePacket
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.GromovHomologicalProbabilityRoadmapPacket
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.GromovHomologicalProbabilityRoadmapTarget
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.constructGromovHomologicalProbabilityRoadmapTarget
#check InfoGeometry.GromovHomologicalProbabilityRoadmap.constructGromovHomologicalProbabilityRoadmapPacket
-/

#check InfoGeometry.GrandUnification.modularTransportBridgeTarget
#check InfoGeometry.GrandUnification.tomitaGromovBridgeTarget
#check InfoGeometry.GrandUnification.spectralThermalNormalization_partition_pos
