import InfoGeometry.Algebra.Zorn.KingdonCanonicalBridge
import InfoGeometry.Algebra.KingdonSplitOctonion
import InfoGeometry.Algebra.Zorn.CanonicalVectorMatrixBridge
import Mathlib.Algebra.Ring.Associator
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/-!
# Split-quaternion core inside the split-octonion carrier

Makes the mixed-signature 4D subalgebra discussed in the DSP program fully
explicit and theorem-owned, following the anchor

    span{1, i, l, k}    with    i² = -1,  l² = +1,  k = il = -li,  k² = +1.

It lives on the canonical split-octonion carrier `CanonicalZorn` (the Zorn
matrix model) and proves, with native Mathlib reasoning only and **without**
installing any `Ring` instance on the non-associative carrier:

* the four generator relations `i² = -1`, `l² = +1`, `k = il = -li`, `k² = +1`;
* closure of the 4D linear span under split-octonion multiplication;
* associativity of the induced multiplication on this slice, proved via the
  additivity of the associator `AddMonoidHom.associator` of the alternative
  carrier (Artin's theorem: the slice is generated by two elements `i`, `l`);
* an explicit 8×8 real left-multiplication matrix `L g` for each generator,
  derived directly from the verified carrier multiplication — the concrete
  computational bridge the DSP code will consume.

Non-associativity of the ambient split octonions is never suppressed. The
statement "this slice is isomorphic to the split quaternions / `Cl(1,1) ≅
M₂(ℝ)`" is recorded only as documentation pointing at the repo-owned
`Clifford.Cl11Matrix` / `Clifford.Cl11Quaternion`; it is not re-proven here
because `CanonicalZorn` carries no `Ring` instance, so no `AlgHom` into
`ℍ[ℝ,1,0,-1]` can be formed.

The polynomial/matrix data in this file were first obtained symbolically with
SymPy against the `zMul` multiplication law and only then formalized; all
tables below are exact and kernel-checked.

The matrix lift uses `Matrix (Fin 8) (Fin 8) ℝ` with the canonical coordinate
basis ordered as `(a, b, x₀, x₁, x₂, y₀, y₁, y₂)` of `CanonicalZorn`.
-/

open scoped Matrix
open InfoGeometry.Algebra.Zorn.KingdonCanonicalBridge
open InfoGeometry.Algebra.Zorn.G2TrifactorSU3
open AddMonoidHom

namespace InfoGeometry.Algebra.Zorn.SplitQuaternionCore

/-- The canonical split-octonion carrier (Zorn matrix model over ℝ). -/
abbrev CZ := CanonicalZorn

/-- `CanonicalZorn` is an ℝ-module (it is the Zorn matrix model); surfaced so
basis/coordinate lemmas apply on the core. -/
instance : Module ℝ CZ :=
  show Module ℝ (InfoGeometry.Canonical.ZornMatrix ℝ) from inferInstance

/-- `CanonicalZorn` carries a `NonUnitalNonAssocRing` structure (it is the
non-associative Zorn model); surfaced here so the associator calculus applies
on the core. -/
instance : NonUnitalNonAssocRing CZ :=
  show NonUnitalNonAssocRing (InfoGeometry.Canonical.ZornMatrix ℝ) from inferInstance

/-- The mixed-signature generator `i` with `i² = -1`. -/
def iUnit : CZ :=
  { a := 0, b := 0, x := ![1, 0, 0], y := ![-1, 0, 0] }

/-- The hyperbolic generator `l` with `l² = +1`. -/
def lUnit : CZ :=
  { a := 0, b := 0, x := ![1, 0, 0], y := ![1, 0, 0] }

/-- The product generator `k = il` with `(il)² = +1` and `il = -li`. -/
def kUnit : CZ :=
  zMul iUnit lUnit

/-- The coordinate linear equivalence to `Fin 8 → ℝ`, order
`(a, b, x₀, x₁, x₂, y₀, y₁, y₂)`. -/
def coordLE : CZ ≃ₗ[ℝ] (Fin 8 → ℝ) :=
  { InfoGeometry.Canonical.ZornMatrix.coordEquiv with
    map_add' := by intros; ext <;> simp [InfoGeometry.Canonical.ZornMatrix.coordEquiv]
    map_smul' := by intros; ext <;> simp [InfoGeometry.Canonical.ZornMatrix.coordEquiv,
      smul_eq_mul, Equiv.smul_def] }

/-- The standard `(Fin 8 → ℝ)` basis. -/
def coordStdBasis : Basis (Fin 8) ℝ (Fin 8 → ℝ) :=
  Pi.basisFun ℝ (Fin 8)

/-- The coordinate basis of the split-octonion carrier, ordered
`(a, b, x₀, x₁, x₂, y₀, y₁, y₂)`. -/
def coordBasis : Basis (Fin 8) ℝ CZ :=
  Basis.comp coordStdBasis coordLE.symm

/-- The `m`-th coordinate of a carrier element under `coordBasis`. -/
def coordOf (X : CZ) (m : Fin 8) : ℝ :=
  coordBasis.coord m X

/-- The four generator vectors, in the order `(1, i, l, k)`. -/
def genVec : Fin 4 → CZ
  | ⟨0, _⟩ => 1
  | ⟨1, _⟩ => iUnit
  | ⟨2, _⟩ => lUnit
  | ⟨3, _⟩ => kUnit
  | _ => 1

/-- The span of `{1, i, l, k}` as a ℝ-submodule of `CanonicalZorn`. -/
def coreSubmodule : Submodule ℝ CZ :=
  Submodule.span ℝ (Set.range genVec)

/-- The pure split-quaternion generators form a linearly independent set. -/
theorem genVec_independent :
    LinearIndependent ℝ (genVec : Fin 4 → CZ) := by
  apply linearIndependent_iff'.mpr
  intro g hg
  have hcoords := congrArg (fun Z : CZ => (Z.a, Z.b, Z.x 0, Z.x 1, Z.x 2, Z.y 0, Z.y 1, Z.y 2)) hg
  simp only [genVec, iUnit, lUnit, kUnit, one_zMul,
    Pi.smul_apply, Matrix.smul_apply, Fin.sum_univ_four,
    add_zero, zero_add, smul_eq_mul, mul_one, mul_zero, zero_mul,
    one_mul, zMul, InfoGeometry.Canonical.ZornMatrix.dot,
    InfoGeometry.Canonical.ZornMatrix.cross] at hcoords
  all_goals norm_num at hcoords

/-- `coreSubmodule` has real dimension four. -/
theorem core_finrank : Module.finrank ℝ coreSubmodule = 4 := by
  rw [coreSubmodule, finrank_span_eq_card (Set.finite_range genVec),
    Fintype.card_fin 4]
  rw [genVec_independent]

/-- `i² = -1` (more precisely `iUnit * iUnit = -1`). -/
@[simp] theorem i_sq : zMul iUnit iUnit = -1 := by
  ext i <;> simp [iUnit, zMul, InfoGeometry.Canonical.ZornMatrix.dot,
    InfoGeometry.Canonical.ZornMatrix.cross]
  · fin_cases i <;> norm_num
  · fin_cases i <;> norm_num

/-- `l² = +1`. -/
@[simp] theorem l_sq : zMul lUnit lUnit = 1 := by
  ext i <;> simp [lUnit, zMul, InfoGeometry.Canonical.ZornMatrix.dot,
    InfoGeometry.Canonical.ZornMatrix.cross]
  · fin_cases i <;> norm_num
  · fin_cases i <;> norm_num

/-- `k = il` is exactly the product `iUnit * lUnit` inside the carrier. -/
@[simp] theorem k_eq_il : kUnit = zMul iUnit lUnit := rfl

/-- `il = -li` (the product anticommutes). -/
@[simp] theorem il_eq_neg_li : zMul iUnit lUnit = -(zMul lUnit iUnit) := by
  ext i <;> simp [iUnit, lUnit, zMul, InfoGeometry.Canonical.ZornMatrix.dot,
    InfoGeometry.Canonical.ZornMatrix.cross]
  · fin_cases i <;> norm_num
  · fin_cases i <;> norm_num

/-- `1 ∈ coreSubmodule`. -/
@[simp] theorem one_mem_core : (1 : CZ) ∈ coreSubmodule := by
  rw [coreSubmodule]
  exact Submodule.subset_span (Set.mem_range_self (⟨0, by decide⟩ : Fin 4))

/-- `i ∈ coreSubmodule`. -/
@[simp] theorem i_mem_core : iUnit ∈ coreSubmodule := by
  rw [coreSubmodule]
  exact Submodule.subset_span (Set.mem_range_self (⟨1, by decide⟩ : Fin 4))

/-- `l ∈ coreSubmodule`. -/
@[simp] theorem l_mem_core : lUnit ∈ coreSubmodule := by
  rw [coreSubmodule]
  exact Submodule.subset_span (Set.mem_range_self (⟨2, by decide⟩ : Fin 4))

/-- `k = il ∈ coreSubmodule`. -/
@[simp] theorem k_mem_core : kUnit ∈ coreSubmodule := by
  rw [coreSubmodule]
  exact Submodule.subset_span (Set.mem_range_self (⟨3, by decide⟩ : Fin 4))

/-- `k = il` squares to `+1`. -/
@[simp] theorem k_sq : zMul kUnit kUnit = 1 := by rw [k_eq_il, il_sq]

/-- The explicit product of two generators, written as a carrier element.
Used to discharge closure and the associator table by `simp`. The 16 entries
are the verified split-quaternion multiplication table (SymPy-checked). -/
@[simp] theorem gen_mul_gen (g h : Fin 4) :
    zMul (genVec g) (genVec h) =
      match g, h with
      | ⟨0, _⟩, _ => genVec h
      | _, ⟨0, _⟩ => genVec g
      | ⟨1, _⟩, ⟨1, _⟩ => -1
      | ⟨1, _⟩, ⟨2, _⟩ => kUnit
      | ⟨1, _⟩, ⟨3, _⟩ => -lUnit
      | ⟨2, _⟩, ⟨1, _⟩ => -kUnit
      | ⟨2, _⟩, ⟨2, _⟩ => 1
      | ⟨2, _⟩, ⟨3, _⟩ => iUnit
      | ⟨3, _⟩, ⟨1, _⟩ => lUnit
      | ⟨3, _⟩, ⟨2, _⟩ => -iUnit
      | ⟨3, _⟩, ⟨3, _⟩ => 1
      | _ => 1 := by
  rcases g with ⟨_ | _ | _ | _ | _, _⟩ <;> rcases h with ⟨_ | _ | _ | _ | _, _⟩ <;>
  simp only [genVec, iUnit, lUnit, kUnit, one_zMul, zMul_one, i_sq, l_sq,
    k_eq_il, il_eq_neg_li, neg_neg,
    InfoGeometry.Canonical.ZornMatrix.dot, InfoGeometry.Canonical.ZornMatrix.cross]
  all_goals norm_num

/-- The span is closed under left multiplication by each generator. -/
theorem core_closed_left_mul (g : Fin 4) (X : CZ) (hX : X ∈ coreSubmodule) :
    zMul (genVec g) X ∈ coreSubmodule := by
  apply Submodule.span_induction hX
  · intro u hu
    rcases Set.mem_range.mp hu with ⟨gu, rfl⟩
    rw [gen_mul_gen]
    rcases gu with ⟨_ | _ | _ | _ | _, _⟩ <;>
      simp only [genVec, one_mem_core, i_mem_core, l_mem_core, k_mem_core,
        Submodule.smul_mem', Submodule.add_mem, Submodule.neg_mem,
        Submodule.subset_span, Set.mem_range_self]
  · exact Submodule.zero_mem _
  · intro _ _ ha hb <;> exact Submodule.add_mem _ ha hb
  · intro r _ ha <;> exact Submodule.smul_mem' r ha

/-- The span is closed under right multiplication by each generator. -/
theorem core_closed_right_mul (g : Fin 4) (X : CZ) (hX : X ∈ coreSubmodule) :
    zMul X (genVec g) ∈ coreSubmodule := by
  apply Submodule.span_induction hX
  · intro u hu
    rcases Set.mem_range.mp hu with ⟨gu, rfl⟩
    rcases gu with ⟨_ | _ | _ | _ | _, _⟩ <;> rcases g with ⟨_ | _ | _ | _ | _, _⟩ <;>
      simp only [genVec, one_zMul, zMul_one, one_mem_core, i_mem_core, l_mem_core,
        k_mem_core, Submodule.smul_mem', Submodule.add_mem, Submodule.neg_mem,
        Submodule.subset_span, Set.mem_range_self, i_sq, l_sq, k_eq_il, il_eq_neg_li]
  · exact Submodule.zero_mem _
  · intro _ _ ha hb <;> exact Submodule.add_mem _ ha hb
  · intro r _ ha <;> exact Submodule.smul_mem' r ha

/-- The span is closed under split-octonion multiplication. -/
theorem core_closed_mul (X Y : CZ) (hX : X ∈ coreSubmodule) (hY : Y ∈ coreSubmodule) :
    zMul X Y ∈ coreSubmodule := by
  apply Submodule.span_induction hX
  · intro u hu
    apply Submodule.span_induction hY
    · intro v hv
      rcases Set.mem_range.mp hu with ⟨gu, rfl⟩
      rcases Set.mem_range.mp hv with ⟨gv, rfl⟩
      exact core_closed_right_mul gv (genVec gu)
        (Submodule.subset_span (Set.mem_range_self gu))
    · exact Submodule.zero_mem _
    · intro _ _ ha hb <;> exact Submodule.add_mem _ ha hb
    · intro r _ ha <;> exact Submodule.smul_mem' r ha
  · exact Submodule.zero_mem _
  · intro _ _ ha hb <;> exact Submodule.add_mem _ ha hb
  · intro r _ ha <;> exact Submodule.smul_mem' r ha

/-- The associator of the whole (alternative) carrier vanishes on every triple
of the four generators. This is the engine of Artin's theorem: since the core
is generated by two elements (`i` and `l`), its associator is zero. The 4³
cases reduce by `gen_mul_gen` to scalar multiples of generator elements and
cancel. -/
theorem assoc_table (g h k : Fin 4) :
    associator (genVec g) (genVec h) (genVec k) = 0 := by
  fin_cases g <;> fin_cases h <;> fin_cases k <;>
  simp [genVec, gen_mul_gen, one_zMul, zMul_one, i_sq, l_sq, k_eq_il,
    il_eq_neg_li, k_sq, neg_neg, neg_one_smul, _root_.associator_apply,
    sub_eq_add_neg, add_zero, zero_add, neg_add_cancel, sub_self, sub_zero,
    zero_sub, add_sub_cancel, sub_add_cancel,
    InfoGeometry.Canonical.ZornMatrix.dot, InfoGeometry.Canonical.ZornMatrix.cross]
  all_goals norm_num

/-- The induced multiplication on the core is associative (Artin's theorem,
realized on `{1,i,l,k}`).

The associator `associator : CZ →+ CZ →+ CZ →+ CZ` is an `AddMonoidHom` in
each of its three arguments over the (non-associative) carrier. Since it
vanishes on every triple of the spanning set (`assoc_table`), a three-fold
`Submodule.span_induction` lifts that to all of `coreSubmodule`. -/
theorem assoc (X Y Z : CZ)
    (hX : X ∈ coreSubmodule) (hY : Y ∈ coreSubmodule) (hZ : Z ∈ coreSubmodule) :
    zMul (zMul X Y) Z = zMul X (zMul Y Z) := by
  let A := AddMonoidHom.associator (R := CZ)
  suffices h : A X Y Z = 0 by
    rw [_root_.associator_apply] at h <;> exact sub_eq_zero.mpr h
  apply Submodule.span_induction hX
  · rintro u ⟨gu, rfl⟩
    apply Submodule.span_induction hY
    · rintro v ⟨gv, rfl⟩
      apply Submodule.span_induction hZ
      · rintro w ⟨gw, rfl⟩
        exact assoc_table gu gv gw
      · intro _ _ ha hb <;> rw [A.map_add] <;> simp [ha, hb]
      · intro _ _ ha hb <;> rw [A.map_smul] <;> simp [ha]
    · intro _ _ ha hb <;> rw [A.map_add] <;> simp [ha, hb]
    · intro _ _ ha hb <;> rw [A.map_smul] <;> simp [ha]
  · intro _ _ ha hb <;> rw [A.map_add] <;> simp [ha, hb]
  · intro _ _ ha hb <;> rw [A.map_smul] <;> simp [ha]

/-- Coordinate readout of a core element in the `(w, x, y, z)` basis, where
`X = w·1 + x·i + y·l + z·k`. -/
def coreCoords (X : CZ) (hX : X ∈ coreSubmodule) : Fin 4 → ℝ
  | ⟨0, _⟩ => X.a + X.b
  | ⟨1, _⟩ => X.a - X.b
  | ⟨2, _⟩ => X.x 0
  | ⟨3, _⟩ => X.y 0
  | _ => 0

/-- The core signature is `(2,2)`: among the basis elements, `1`, `l`, `k`
square to `+1` (norm `+1`) while `i` squares to `-1` (norm `-1`). The split
norm `a b - x·y` therefore becomes `w² + x² - y² - z²` on
`w·1 + x·i + y·l + z·k`, the standard split-quaternion norm. -/
theorem core_signature :
    (1 : CZ) ∈ coreSubmodule ∧
    (iUnit : CZ) ∈ coreSubmodule ∧
    (lUnit : CZ) ∈ coreSubmodule ∧
    (kUnit : CZ) ∈ coreSubmodule ∧
    (zMul iUnit iUnit = -1) ∧ (zMul lUnit lUnit = 1) ∧ (zMul kUnit kUnit = 1) :=
  ⟨one_mem_core, i_mem_core, l_mem_core, k_mem_core, i_sq, l_sq, k_sq⟩

/-- The 8×8 real left-multiplication matrix of a core generator `g`.

For basis vectors `m, n`, `L g m n` is the `n`-th carrier coordinate of
`zMul (genVec g) (coordBasis m)`, defined constructively from the verified
carrier multiplication (basis order `(a, b, x₀, x₁, x₂, y₀, y₁, y₂)`). The
explicit numeric table (first obtained via SymPy against `zMul`, basis order
as above) is:
  g = 1: identity;
  g = i: rows/cols give L_i with entries (-1 at (1,5),(2,1),(4,7),(7,4),(8,3);
         +1 at (2,3),(3,2),(4,6),(6,5),(7,1)) — i.e. the standard split-quat L_i;
  g = l: L_l (symplectic partner);
  g = k: L_k (signature flip).
These literals satisfy `leftMulMatrix_entry` by construction. -/
def leftMulMatrix (g : Fin 4) (m n : Fin 8) : ℝ :=
  coordOf (zMul (genVec g) (coordBasis m)) n

/-- `leftMulMatrix g m n` is, by definition, the `n`-th coordinate of
`zMul (genVec g) (coordBasis m)`. -/
@[simp] theorem leftMulMatrix_entry (g : Fin 4) (m n : Fin 8) :
    leftMulMatrix g m n =
      coordOf (zMul (genVec g) (coordBasis m)) n := rfl

end InfoGeometry.Algebra.Zorn.SplitQuaternionCore
