import Mathlib.Combinatorics.SimpleGraph.AdjMatrix
import InfoGeometry.Algebra.FiniteSpinAlgebra
import Mathlib.Combinatorics.SimpleGraph.Clique
import Mathlib.Data.Complex.Basic
import Mathlib.LinearAlgebra.QuadraticForm.Basic
import InfoGeometry.Clifford.BudinichCliqueSpinor
import InfoGeometry.Clifford.BudinichSpinorsNullVectors
import InfoGeometry.Twistor.NullProjective

/-!
# Budinich maximum-clique / pure-spinor kernel

This module packages the paper-safe constructive core of the Budinich
maximum-clique formulation:

* the graph side is read through an explicit complex Gram matrix;
* the clique predicate is the vanishing of the off-diagonal Gram readout;
* the pure-spinor side is the one-dimensional null annihilator line in the
  concrete split `2 × 2` spinor model;
* projective null rays are obtained from an explicit quadratic form on the
  same two-component spinor carrier.

The file is intentionally conservative:

* it does not claim a universal theorem that every graph admits a specific
  complex factorization witness;
* it packages factorization witnesses explicitly when they are supplied;
* it reuses the already-proved clique/Gram and null-action results from the
  existing Budinich owner files.
-/

noncomputable section

namespace InfoGeometry.Clifford.BudinichMaximumCliquePureSpinor

open InfoGeometry.Twistor
open InfoGeometry.Clifford.BudinichCliqueSpinor
open InfoGeometry.Clifford.BudinichSpinorsNullVectors

variable {α : Type*}

/-! ## 1. Graph side: explicit square-root packet -/

/--
An explicit complex symmetric adjacency square-root witness.

This is the paper's `A = B²` layer, represented as an explicit packet.
No existence theorem is claimed here.
-/
structure GraphAdjacencySquareRoot (G : SimpleGraph α) [Fintype α]
    [DecidableRel G.Adj] [DecidableEq α] where
  /-- Complex matrix witness. -/
  B : Matrix α α ℂ
  /-- Symmetry of the witness. -/
  symmetric : Matrix.transpose B = B
  /-- The square recovers the adjacency matrix. -/
  square_eq : B * B = G.adjMatrix ℂ

/-- The graph Gram readout is the existing Budinich complex kernel. -/
abbrev graphCliqueGramReadout (G : SimpleGraph α) [DecidableEq α] [DecidableRel G.Adj] :
    α → α → ℂ :=
  graphCliqueGram G

/-- Clique membership is the vanishing of the graph Gram readout. -/
theorem isClique_iff_isGramClique
    (G : SimpleGraph α) [DecidableEq α] [DecidableRel G.Adj] (s : Set α) :
    G.IsClique s ↔ IsGramClique G s :=
  InfoGeometry.Clifford.BudinichCliqueSpinor.isClique_iff_isGramClique G s

/-- Finite-clique version of the Gram criterion. -/
theorem isClique_finset_iff_isFinsetGramClique
    (G : SimpleGraph α) [DecidableEq α] [DecidableRel G.Adj] (s : Finset α) :
    G.IsClique (s : Set α) ↔ IsFinsetGramClique G s :=
  InfoGeometry.Clifford.BudinichCliqueSpinor.isClique_finset_iff_isFinsetGramClique G s

/-- Maximum clique cardinality is equivalent to maximum Gram-clique cardinality. -/
theorem maximumCliqueCard_iff_maximumGramCliqueCard
    (G : SimpleGraph α) [DecidableEq α] [DecidableRel G.Adj] (k : ℕ) :
    IsMaximumCliqueCard G k ↔ IsMaximumGramCliqueCard G k :=
  InfoGeometry.Clifford.BudinichCliqueSpinor.maximumCliqueCard_iff_maximumGramCliqueCard G k

/-! ## 2. Pure-spinor side: explicit null line and projective null ray -/

/--
Explicit quadratic form on the concrete two-component split spinor carrier.

This is the simplest paper-safe null model: the product of the two coordinates.
-/
noncomputable def spinor2Q : QuadraticForm ℝ Spinor2 :=
  QuadraticMap.linMulLin
    (LinearMap.proj (ι := Fin 2) (φ := fun _ => ℝ) 0)
    (LinearMap.proj (ι := Fin 2) (φ := fun _ => ℝ) 1)

@[simp] theorem spinor2Q_apply (ψ : Spinor2) :
    spinor2Q ψ = ψ 0 * ψ 1 :=
  rfl

@[simp] theorem spinor2Q_e0 :
    spinor2Q spinor2e0 = 0 := by
  simp [spinor2Q, spinor2e0]

@[simp] theorem spinor2Q_e1 :
    spinor2Q spinor2e1 = 0 := by
  simp [spinor2Q, spinor2e1]

/-- The canonical projective null ray generated by the first basis spinor. -/
noncomputable def spinor2ProjectiveNullRay0 :
    InfoGeometry.Twistor.TwistorSpace spinor2Q :=
  InfoGeometry.Twistor.twistorMk spinor2Q spinor2e0 spinor2e0_ne_zero
    (by simp [spinor2Q, spinor2e0])

/-- The canonical projective null ray generated by the second basis spinor. -/
noncomputable def spinor2ProjectiveNullRay1 :
    InfoGeometry.Twistor.TwistorSpace spinor2Q :=
  InfoGeometry.Twistor.twistorMk spinor2Q spinor2e1 spinor2e1_ne_zero
    (by simp [spinor2Q, spinor2e1])

/--
A spinor annihilated by the upper null action lies on the canonical pure-spinor line.

This is the concrete one-dimensional pure-spinor kernel used in the paper-safe
Budinich formulation.
-/
theorem spinor_on_pureLine_of_nullPlus
    (ψ : Spinor2) (hψ : nullPlusAction ψ = 0) :
    ∃ a : ℝ, ψ = a • spinor2e0 :=
  nullPlusAction_spinor_eq_span_singleton ψ hψ

/--
A spinor annihilated by the lower null action lies on the canonical pure-spinor line.
-/
theorem spinor_on_pureLine_of_nullMinus
    (ψ : Spinor2) (hψ : nullMinusAction ψ = 0) :
    ∃ a : ℝ, ψ = a • spinor2e1 :=
  nullMinusAction_spinor_eq_span_singleton ψ hψ

/-! ## 3. Paper packet: graph square root + maximum clique + pure spinor kernel -/

/--
Paper-safe bundle of the graph Gram side and the pure-spinor null side.

This packages the two constructive ingredients the paper uses:

* a graph witness with a complex symmetric square-root packet;
* a maximum-clique witness, read either as clique or Gram-clique;
* a concrete pure-spinor null line in the split `2 × 2` seed.
-/
structure BudinichCliqueSpinorPacket (G : SimpleGraph α) [Fintype α]
    [DecidableEq α] [DecidableRel G.Adj] where
  /-- Complex symmetric square-root witness for the adjacency matrix. -/
  squareRoot : GraphAdjacencySquareRoot G
  /-- Maximum clique cardinality witness. -/
  cliqueCard : ℕ
  /-- Maximum clique witness. -/
  maximumClique : IsMaximumCliqueCard G cliqueCard
  /-- Concrete pure spinor carrier. -/
  spinor : Spinor2
  /-- Null action annihilation. -/
  spinorNull : nullPlusAction spinor = 0

namespace BudinichCliqueSpinorPacket

variable {G : SimpleGraph α} [Fintype α] [DecidableRel G.Adj]
variable [DecidableEq α]

/-- The packet's maximum clique is also a maximum Gram clique. -/
theorem maximumGramClique
    (P : BudinichCliqueSpinorPacket (α := α) G) :
    IsMaximumGramCliqueCard G P.cliqueCard := by
  exact (maximumCliqueCard_iff_maximumGramCliqueCard (G := G) P.cliqueCard).1
    P.maximumClique

/-- The packet's pure spinor lies on the canonical one-dimensional line. -/
theorem pureSpinor_on_line
    (P : BudinichCliqueSpinorPacket (α := α) G) :
    ∃ a : ℝ, P.spinor = a • spinor2e0 :=
  spinor_on_pureLine_of_nullPlus P.spinor P.spinorNull

end BudinichCliqueSpinorPacket

/-! ## 4. Finite maximum-clique witness -/

/--
An explicit maximum-clique finset witness.

This is the finite combinatorial normalization used by the paper:
it packages the existence of a maximum clique as an explicit finset and its
cardinality.
-/
structure MaximumCliqueFinsetPacket (G : SimpleGraph α) [Finite α] where
  /-- A concrete maximum clique finset. -/
  clique : Finset α
  /-- The clique is maximal by cardinality. -/
  isMaximum : G.IsMaximumClique clique
  /-- Its cardinality is the graph clique number. -/
  card_eq_cliqueNum : clique.card = G.cliqueNum

namespace MaximumCliqueFinsetPacket

variable {G : SimpleGraph α} [Finite α]

/-- Maximum cliques exist as explicit finsets. -/
theorem existsMaximumCliqueFinsetPacket (G : SimpleGraph α) :
    ∃ P : MaximumCliqueFinsetPacket (α := α) G, P.clique.card = G.cliqueNum := by
  obtain ⟨s, hs⟩ := SimpleGraph.maximumClique_exists (G := G)
  refine ⟨⟨s, hs, ?_⟩, ?_⟩
  · exact SimpleGraph.maximumClique_card_eq_cliqueNum (G := G) s hs
  · simpa using SimpleGraph.maximumClique_card_eq_cliqueNum (G := G) s hs

/-- The packet remembers the clique number. -/
theorem cliqueNum_eq_card (P : MaximumCliqueFinsetPacket (α := α) G) :
    P.clique.card = G.cliqueNum :=
  P.card_eq_cliqueNum

end MaximumCliqueFinsetPacket

/-! ## 5. Saturated vector family of a maximum clique -/

/--
The pairwise-null Budinich graph-vector package for a chosen clique.

This is the clean form of the paper's "saturated vector" language:
the clique determines a family of graph vectors whose pairwise Witt pairing
vanishes off the diagonal.
-/
structure SaturatedCliqueVectorPacket (n : ℕ) (G : SimpleGraph (Fin n))
    [DecidableRel G.Adj] where
  /-- A concrete maximum-clique finset. -/
  maximumClique : MaximumCliqueFinsetPacket (α := Fin n) G
  /-- The clique's graph vectors are pairwise null. -/
  pairwiseNull :
    ∀ i ∈ maximumClique.clique, ∀ j ∈ maximumClique.clique, i ≠ j →
      wittPairing (budinichGraphVector G i) (budinichGraphVector G j) = 0

namespace SaturatedCliqueVectorPacket

variable {n : ℕ} {G : SimpleGraph (Fin n)} [DecidableRel G.Adj]

/-- A maximum clique canonically yields a saturated Budinich vector family. -/
def ofMaximumClique (P : MaximumCliqueFinsetPacket (α := Fin n) G) :
    SaturatedCliqueVectorPacket n G where
  maximumClique := P
  pairwiseNull := by
    intro i hi j hj hne
    have hclique : G.IsClique (P.clique : Set (Fin n)) := P.isMaximum.isClique
    exact (InfoGeometry.Clifford.BudinichCliqueSpinor.finsetClique_iff_budinichVectors_pairwise_null
      (n := n) G P.clique).1 hclique i hi j hj hne

/-- The saturated packet remembers the maximum clique card. -/
theorem clique_card_eq_cliqueNum (P : SaturatedCliqueVectorPacket n G) :
    P.maximumClique.clique.card = G.cliqueNum :=
  P.maximumClique.card_eq_cliqueNum

/-- The pairwise-null vector family is exactly the clique predicate. -/
theorem pairwiseNull_iff_clique
    (s : Finset (Fin n)) :
    G.IsClique (s : Set (Fin n)) ↔
      ∀ i ∈ s, ∀ j ∈ s, i ≠ j →
        wittPairing (budinichGraphVector G i) (budinichGraphVector G j) = 0 :=
  InfoGeometry.Clifford.BudinichCliqueSpinor.finsetClique_iff_budinichVectors_pairwise_null G s

end SaturatedCliqueVectorPacket

end InfoGeometry.Clifford.BudinichMaximumCliquePureSpinor
