import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic
import InfoGeometry.Clifford.Cl11TensorTower

set_option autoImplicit false

noncomputable section

namespace InfoGeometry.Clifford.Cl11LocalTrifactorFlows

open Matrix
open InfoGeometry.Clifford.Cl11TensorTower

/-- The native second dyadic matrix stage, of real dimension `4 × 4`. -/
abbrev StageTwo : Type := MatStage 2

/-! ## Canonical stage-two square-class axes

These are not new carriers.  They are the existing local `Cl(1,1)` atoms
transported one step by the repository-owned bonding map `stageEmbed 1`.
-/

/-- Elliptic/Hestenes axis at stage two. -/
def ellipticAxis : StageTwo :=
  stageEmbed 1 hestenesPhaseBase

/-- Hyperbolic/split involution at stage two. -/
def hyperbolicAxis : StageTwo :=
  stageEmbed 1 modularSignBase

/-- Parabolic/Witt nilpotent axis at stage two. -/
def parabolicAxis : StageTwo :=
  stageEmbed 1 wittCreationBase

@[simp] theorem ellipticAxis_sq :
    ellipticAxis * ellipticAxis = -(1 : StageTwo) := by
  calc
    ellipticAxis * ellipticAxis
        = stageEmbed 1 (hestenesPhaseBase * hestenesPhaseBase) := by
            exact (map_mul (stageEmbed 1) hestenesPhaseBase hestenesPhaseBase).symm
    _ = stageEmbed 1 (-(1 : MatStage 1)) := by
          rw [hestenesPhaseBase_sq]
    _ = -(1 : StageTwo) := by simp

@[simp] theorem hyperbolicAxis_sq :
    hyperbolicAxis * hyperbolicAxis = (1 : StageTwo) := by
  calc
    hyperbolicAxis * hyperbolicAxis
        = stageEmbed 1 (modularSignBase * modularSignBase) := by
            exact (map_mul (stageEmbed 1) modularSignBase modularSignBase).symm
    _ = stageEmbed 1 (1 : MatStage 1) := by
          rw [modularSignBase_sq]
    _ = (1 : StageTwo) := by simp

@[simp] theorem parabolicAxis_sq :
    parabolicAxis * parabolicAxis = (0 : StageTwo) := by
  calc
    parabolicAxis * parabolicAxis
        = stageEmbed 1 (wittCreationBase * wittCreationBase) := by
            exact (map_mul (stageEmbed 1) wittCreationBase wittCreationBase).symm
    _ = stageEmbed 1 (0 : MatStage 1) := by
          rw [wittCreationBase_sq]
    _ = (0 : StageTwo) := by simp

/-! ## Polynomial multiplication laws for the three square classes -/

/-- Multiplication in the elliptic two-plane generated by an element with square `-1`. -/
theorem elliptic_plane_mul
    (J : StageTwo) (hJ : J * J = -(1 : StageTwo))
    (a b c d : ℝ) :
    (a • (1 : StageTwo) + b • J) * (c • (1 : StageTwo) + d • J) =
      (a * c - b * d) • (1 : StageTwo) + (a * d + b * c) • J := by
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm,
    one_mul, mul_one, hJ, smul_neg]
  module

/-- Multiplication in the hyperbolic two-plane generated by an involution. -/
theorem hyperbolic_plane_mul
    (H : StageTwo) (hH : H * H = (1 : StageTwo))
    (a b c d : ℝ) :
    (a • (1 : StageTwo) + b • H) * (c • (1 : StageTwo) + d • H) =
      (a * c + b * d) • (1 : StageTwo) + (a * d + b * c) • H := by
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm,
    one_mul, mul_one, hH]
  module

/-- Multiplication in the parabolic two-plane generated by a square-zero element. -/
theorem parabolic_plane_mul
    (N : StageTwo) (hN : N * N = (0 : StageTwo))
    (a b c d : ℝ) :
    (a • (1 : StageTwo) + b • N) * (c • (1 : StageTwo) + d • N) =
      (a * c) • (1 : StageTwo) + (a * d + b * c) • N := by
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm,
    one_mul, mul_one, hN, smul_zero, add_zero]
  module

/-! ## Native stage-two one-parameter flows -/

/-- Elliptic flow generated by `J² = -1`. -/
def ellipticFlow (J : StageTwo) (t : ℝ) : StageTwo :=
  Real.cos t • (1 : StageTwo) + Real.sin t • J

/-- Hyperbolic flow generated by `H² = 1`. -/
def hyperbolicFlow (H : StageTwo) (t : ℝ) : StageTwo :=
  Real.cosh t • (1 : StageTwo) + Real.sinh t • H

/-- Parabolic flow generated by `N² = 0`. -/
def parabolicFlow (N : StageTwo) (t : ℝ) : StageTwo :=
  (1 : ℝ) • (1 : StageTwo) + t • N

@[simp] theorem ellipticFlow_zero (J : StageTwo) :
    ellipticFlow J 0 = (1 : StageTwo) := by
  simp [ellipticFlow]

@[simp] theorem hyperbolicFlow_zero (H : StageTwo) :
    hyperbolicFlow H 0 = (1 : StageTwo) := by
  simp [hyperbolicFlow]

@[simp] theorem parabolicFlow_zero (N : StageTwo) :
    parabolicFlow N 0 = (1 : StageTwo) := by
  simp [parabolicFlow]

/-- The elliptic polynomial flow is a one-parameter subgroup. -/
theorem ellipticFlow_add
    (J : StageTwo) (hJ : J * J = -(1 : StageTwo))
    (s t : ℝ) :
    ellipticFlow J s * ellipticFlow J t = ellipticFlow J (s + t) := by
  unfold ellipticFlow
  rw [elliptic_plane_mul J hJ]
  rw [Real.cos_add, Real.sin_add]
  module

/-- The hyperbolic polynomial flow is a one-parameter subgroup. -/
theorem hyperbolicFlow_add
    (H : StageTwo) (hH : H * H = (1 : StageTwo))
    (s t : ℝ) :
    hyperbolicFlow H s * hyperbolicFlow H t = hyperbolicFlow H (s + t) := by
  unfold hyperbolicFlow
  rw [hyperbolic_plane_mul H hH]
  rw [Real.cosh_add, Real.sinh_add]
  module

/-- The square-zero polynomial flow is a one-parameter subgroup. -/
theorem parabolicFlow_add
    (N : StageTwo) (hN : N * N = (0 : StageTwo))
    (s t : ℝ) :
    parabolicFlow N s * parabolicFlow N t = parabolicFlow N (s + t) := by
  unfold parabolicFlow
  rw [parabolic_plane_mul N hN]
  module

/-- Opposite parameter is a right inverse for the elliptic flow. -/
theorem ellipticFlow_mul_neg
    (J : StageTwo) (hJ : J * J = -(1 : StageTwo))
    (t : ℝ) :
    ellipticFlow J t * ellipticFlow J (-t) = (1 : StageTwo) := by
  rw [ellipticFlow_add J hJ]
  simp

/-- Opposite parameter is a right inverse for the hyperbolic flow. -/
theorem hyperbolicFlow_mul_neg
    (H : StageTwo) (hH : H * H = (1 : StageTwo))
    (t : ℝ) :
    hyperbolicFlow H t * hyperbolicFlow H (-t) = (1 : StageTwo) := by
  rw [hyperbolicFlow_add H hH]
  simp

/-- Opposite parameter is a right inverse for the parabolic flow. -/
theorem parabolicFlow_mul_neg
    (N : StageTwo) (hN : N * N = (0 : StageTwo))
    (t : ℝ) :
    parabolicFlow N t * parabolicFlow N (-t) = (1 : StageTwo) := by
  rw [parabolicFlow_add N hN]
  simp

/-- Opposite parameter is a left inverse for the elliptic flow. -/
theorem ellipticFlow_neg_mul
    (J : StageTwo) (hJ : J * J = -(1 : StageTwo))
    (t : ℝ) :
    ellipticFlow J (-t) * ellipticFlow J t = (1 : StageTwo) := by
  rw [ellipticFlow_add J hJ]
  simp

/-- Opposite parameter is a left inverse for the hyperbolic flow. -/
theorem hyperbolicFlow_neg_mul
    (H : StageTwo) (hH : H * H = (1 : StageTwo))
    (t : ℝ) :
    hyperbolicFlow H (-t) * hyperbolicFlow H t = (1 : StageTwo) := by
  rw [hyperbolicFlow_add H hH]
  simp

/-- Opposite parameter is a left inverse for the parabolic flow. -/
theorem parabolicFlow_neg_mul
    (N : StageTwo) (hN : N * N = (0 : StageTwo))
    (t : ℝ) :
    parabolicFlow N (-t) * parabolicFlow N t = (1 : StageTwo) := by
  rw [parabolicFlow_add N hN]
  simp

/-! ## Elliptic orthogonality and commuting loxodromic flow -/

/-- A skew-transpose elliptic generator has transpose equal to the opposite-parameter flow. -/
theorem ellipticFlow_transpose
    (J : StageTwo) (hJt : Jᵀ = -J) (t : ℝ) :
    (ellipticFlow J t)ᵀ = ellipticFlow J (-t) := by
  simp [ellipticFlow, Matrix.transpose_add, hJt,
    Real.cos_neg, Real.sin_neg]

/-- A skew-transpose square-minus-one generator produces an orthogonal flow. -/
theorem ellipticFlow_transpose_mul
    (J : StageTwo)
    (hJ : J * J = -(1 : StageTwo))
    (hJt : Jᵀ = -J)
    (t : ℝ) :
    (ellipticFlow J t)ᵀ * ellipticFlow J t = (1 : StageTwo) := by
  rw [ellipticFlow_transpose J hJt]
  exact ellipticFlow_neg_mul J hJ t

/-- Commuting elliptic and hyperbolic generators yield commuting polynomial flows. -/
theorem ellipticFlow_hyperbolicFlow_commute
    (J H : StageTwo)
    (hJH : J * H = H * J)
    (s t : ℝ) :
    ellipticFlow J s * hyperbolicFlow H t =
      hyperbolicFlow H t * ellipticFlow J s := by
  unfold ellipticFlow hyperbolicFlow
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm,
    one_mul, mul_one, hJH]
  module

/-- Commuting elliptic/hyperbolic product flow. -/
def loxodromicFlow (J H : StageTwo) (t : ℝ) : StageTwo :=
  ellipticFlow J t * hyperbolicFlow H t

/-- For commuting square-class generators the loxodromic product is a one-parameter subgroup. -/
theorem loxodromicFlow_add
    (J H : StageTwo)
    (hJ : J * J = -(1 : StageTwo))
    (hH : H * H = (1 : StageTwo))
    (hJH : J * H = H * J)
    (s t : ℝ) :
    loxodromicFlow J H s * loxodromicFlow J H t =
      loxodromicFlow J H (s + t) := by
  unfold loxodromicFlow
  calc
    (ellipticFlow J s * hyperbolicFlow H s) *
        (ellipticFlow J t * hyperbolicFlow H t)
        = ellipticFlow J s *
            (hyperbolicFlow H s * ellipticFlow J t) *
              hyperbolicFlow H t := by
            simp [mul_assoc]
    _ = ellipticFlow J s *
            (ellipticFlow J t * hyperbolicFlow H s) *
              hyperbolicFlow H t := by
            rw [(ellipticFlow_hyperbolicFlow_commute J H hJH t s).symm]
    _ = (ellipticFlow J s * ellipticFlow J t) *
            (hyperbolicFlow H s * hyperbolicFlow H t) := by
            simp [mul_assoc]
    _ = ellipticFlow J (s + t) * hyperbolicFlow H (s + t) := by
            rw [ellipticFlow_add J hJ, hyperbolicFlow_add H hH]

/-- The canonical stage-two axes instantiate all three local flow laws. -/
theorem canonical_trifactor_group_laws (s t : ℝ) :
    ellipticFlow ellipticAxis s * ellipticFlow ellipticAxis t =
        ellipticFlow ellipticAxis (s + t) ∧
      hyperbolicFlow hyperbolicAxis s * hyperbolicFlow hyperbolicAxis t =
        hyperbolicFlow hyperbolicAxis (s + t) ∧
      parabolicFlow parabolicAxis s * parabolicFlow parabolicAxis t =
        parabolicFlow parabolicAxis (s + t) := by
  exact ⟨ellipticFlow_add ellipticAxis ellipticAxis_sq s t,
    hyperbolicFlow_add hyperbolicAxis hyperbolicAxis_sq s t,
    parabolicFlow_add parabolicAxis parabolicAxis_sq s t⟩

end InfoGeometry.Clifford.Cl11LocalTrifactorFlows
