import InfoGeometry.Clifford.Cl44Witt

namespace InfoGeometry.Clifford.Cl44Spinors

open InfoGeometry.Clifford.Cl44Witt

/--
Primitive vacuum idempotent built from the Witt basis.

Usually `p = ∏ᵢ aᵢ adagᵢ` or the opposite convention.
-- DEBT_KIND: SORRY
-/
noncomputable def vacuumIdempotent : Cl44 := by
  sorry

/--
Idempotency target for the vacuum projector.

-- DEBT_KIND: SORRY
-/
theorem vacuumIdempotent_idem :
    vacuumIdempotent * vacuumIdempotent = vacuumIdempotent := by
  sorry

/--
The real minimal left ideal generated by the vacuum idempotent.
-/
def MinimalSpinor :=
  { x : Cl44 // x * vacuumIdempotent = x }

/--
The chirality / volume element of `Cl(4,4)`.

For signature `(4,4)`, the volume element squares to `+1`,
so it gives real semi-spinor projectors.
-- DEBT_KIND: SORRY
-/
noncomputable def volumeElement : Cl44 := by
  sorry

/--
Square law target for the chirality / volume element.

-- DEBT_KIND: SORRY
-/
theorem volumeElement_sq :
    volumeElement * volumeElement = 1 := by
  sorry

noncomputable def evenSemiSpinorProj : Cl44 :=
  (1 / 2 : ℝ) • (1 + volumeElement)

noncomputable def oddSemiSpinorProj : Cl44 :=
  (1 / 2 : ℝ) • (1 - volumeElement)

/--
Idempotency target for the even semi-spinor projector.

-- DEBT_KIND: SORRY
-/
theorem evenSemiSpinorProj_idem :
    evenSemiSpinorProj * evenSemiSpinorProj = evenSemiSpinorProj := by
  sorry

/--
Idempotency target for the odd semi-spinor projector.

-- DEBT_KIND: SORRY
-/
theorem oddSemiSpinorProj_idem :
    oddSemiSpinorProj * oddSemiSpinorProj = oddSemiSpinorProj := by
  sorry

end InfoGeometry.Clifford.Cl44Spinors
