import InfoGeometry.Clifford.CliffordLieAlgebra
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Clifford.Cl55SpinorAlgebraEquiv

/-!
# The strict `Spin(5,5)` bivector image in the spinor matrix algebra

This module composes two existing owners: the Clifford commutator Lie algebra
and the proved `Cl(5,5) ≃ M₃₂(ℝ)` algebra equivalence.  Membership in the
resulting linear range is the precise hypothesis required before an arbitrary
spinor matrix coefficient is promoted to a `Spin(5,5)` connection coefficient.
-/

noncomputable section

namespace InfoGeometry.Clifford.Cl55SpinBivectorImage

open scoped Matrix
open CliffordAlgebra
open InfoGeometry.Clifford.Clifford55
open InfoGeometry.Clifford.SpinorRep

/-- The native Clifford bivector Lie algebra for the `(5,5)` quadratic form. -/
abbrev SpinBivector55 := soLieAlgebra Q55

/-- Matrix realization of a native `Cl(5,5)` bivector. -/
def spinBivectorMatrixLinear :
    SpinBivector55 →ₗ[ℝ] SpinorMatrix 5 :=
  cl55SpinorAlgEquiv.toLinearMap.comp SpinBivector55.subtype

/-- The strict matrix image of the `Spin(5,5)` bivector Lie algebra. -/
def spinBivectorMatrixRange : Submodule ℝ (SpinorMatrix 5) :=
  LinearMap.range spinBivectorMatrixLinear

/-- Proof-carrying criterion for a matrix-valued connection coefficient. -/
def IsSpinConnectionCoefficient (A : SpinorMatrix 5) : Prop :=
  A ∈ spinBivectorMatrixRange

/-- A native commutator bivector generated by two vectors. -/
def commutatorBivector (u v : V55) : SpinBivector55 :=
  ⟨⁅ι55 u, ι55 v⁆,
    LieSubalgebra.subset_lieSpan (Set.mem_range_self (u, v))⟩

theorem commutatorBivector_isSpinConnectionCoefficient (u v : V55) :
    IsSpinConnectionCoefficient
      (spinBivectorMatrixLinear (commutatorBivector u v)) := by
  exact LinearMap.mem_range_self _ _

theorem zero_isSpinConnectionCoefficient :
    IsSpinConnectionCoefficient (0 : SpinorMatrix 5) :=
  spinBivectorMatrixRange.zero_mem

theorem add_isSpinConnectionCoefficient {A B : SpinorMatrix 5}
    (hA : IsSpinConnectionCoefficient A)
    (hB : IsSpinConnectionCoefficient B) :
    IsSpinConnectionCoefficient (A + B) :=
  spinBivectorMatrixRange.add_mem hA hB

theorem smul_isSpinConnectionCoefficient (r : ℝ) {A : SpinorMatrix 5}
    (hA : IsSpinConnectionCoefficient A) :
    IsSpinConnectionCoefficient (r • A) :=
  spinBivectorMatrixRange.smul_mem r hA

/-- The strict matrix image is closed under the associative commutator. -/
theorem lie_isSpinConnectionCoefficient {A B : SpinorMatrix 5}
    (hA : IsSpinConnectionCoefficient A)
    (hB : IsSpinConnectionCoefficient B) :
    IsSpinConnectionCoefficient ⁅A, B⁆ := by
  rcases hA with ⟨X, rfl⟩
  rcases hB with ⟨Y, rfl⟩
  refine ⟨⁅X, Y⁆, ?_⟩
  change cl55SpinorAlgEquiv ⁅(X : Cl55), (Y : Cl55)⁆ =
    ⁅cl55SpinorAlgEquiv (X : Cl55), cl55SpinorAlgEquiv (Y : Cl55)⁆
  simp [Ring.lie_def]

end InfoGeometry.Clifford.Cl55SpinBivectorImage
