import Mathlib.Algebra.Lie.OfAssociative
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Clifford.Cl55OperatorDiracSystem

/-!
# Quadratic spin action from a Dirac operator system

This owner records the noncommutative operator identity behind the spin
representation: commutators of quadratic gamma operators act linearly on the
gamma generators.  No commutativity of the operator coefficient algebra is
assumed.
-/

namespace InfoGeometry.Clifford

open InfoGeometry.Clifford.Cl55OperatorDiracSystem
open InfoGeometry.Clifford.Cl55SpinorChirality
open InfoGeometry.Clifford.SpinorRep

variable {ι R Op : Type*} [CommRing R] [Ring Op] [Algebra R Op]

def diracBivector (gamma : ι → Op) (i j : ι) : Op :=
  gamma i * gamma j - gamma j * gamma i

/-- The inner derivation generated by an operator. -/
def commutatorAction (D X : Op) : Op := D * X - X * D

/-- The inner derivation `X ↦ D X - X D` as an `R`-linear operator. -/
def commutatorActionLinear (D : Op) : Op →ₗ[R] Op :=
  { toFun := commutatorAction D
    map_add' := by
      intro X Y
      unfold commutatorAction
      noncomm_ring
    map_smul' := by
      intro r X
      unfold commutatorAction
      simp only [Algebra.smul_def]
      change D * (algebraMap R Op r * X) -
          (algebraMap R Op r * X) * D =
        algebraMap R Op r * (D * X - X * D)
      have hleft : D * algebraMap R Op r = algebraMap R Op r * D :=
        (Algebra.commutes r D).symm
      calc
        D * (algebraMap R Op r * X) -
              (algebraMap R Op r * X) * D =
            (D * algebraMap R Op r) * X -
              algebraMap R Op r * (X * D) := by
                rw [← mul_assoc D (algebraMap R Op r) X,
                  mul_assoc (algebraMap R Op r) X D]
        _ = (algebraMap R Op r * D) * X -
              algebraMap R Op r * (X * D) := by rw [hleft]
        _ = algebraMap R Op r * (D * X) -
              algebraMap R Op r * (X * D) := by rw [mul_assoc]
        _ = algebraMap R Op r * (D * X - X * D) := by
              noncomm_ring }

@[simp] theorem commutatorActionLinear_apply (D X : Op) :
    commutatorActionLinear (R := R) D X = commutatorAction D X :=
  by
    change commutatorAction D X = commutatorAction D X
    rfl

theorem commutatorActionLinear_eq_lieAlgebra_ad (D : Op) :
    commutatorActionLinear (R := R) D = LieAlgebra.ad R Op D := by
  ext X
  rfl

theorem diracBivector_swap (gamma : ι → Op) (i j : ι) :
    diracBivector gamma j i = -diracBivector gamma i j := by
  unfold diracBivector
  noncomm_ring

theorem diracBivector_self (gamma : ι → Op) (i : ι) :
    diracBivector gamma i i = 0 := by
  unfold diracBivector
  noncomm_ring

theorem diracBivector_derivation
    (gamma : ι → Op) (i j : ι) (X Y : Op) :
    diracBivector gamma i j * (X * Y) -
        (X * Y) * diracBivector gamma i j =
      (diracBivector gamma i j * X - X * diracBivector gamma i j) * Y +
        X * (diracBivector gamma i j * Y - Y * diracBivector gamma i j) := by
  unfold diracBivector
  noncomm_ring

theorem commutatorAction_mul (D X Y : Op) :
    commutatorAction D (X * Y) =
      commutatorAction D X * Y + X * commutatorAction D Y := by
  unfold commutatorAction
  noncomm_ring

theorem commutatorAction_commutator (D E X : Op) :
    commutatorAction D (commutatorAction E X) -
        commutatorAction E (commutatorAction D X) =
      commutatorAction (D * E - E * D) X := by
  unfold commutatorAction
  noncomm_ring

theorem diracBivector_action
    {g : ι → ι → R} {gamma : ι → Op}
    (hdirac : IsDiracMatrixSystem g gamma) (i j k : ι) :
    diracBivector gamma i j * gamma k -
        gamma k * diracBivector gamma i j =
      (2 : Op) * algebraMap R Op (2 * g j k) * gamma i -
        (2 : Op) * algebraMap R Op (2 * g i k) * gamma j := by
  unfold diracBivector
  calc
    (gamma i * gamma j - gamma j * gamma i) * gamma k -
        gamma k * (gamma i * gamma j - gamma j * gamma i) =
      gamma i * (gamma j * gamma k + gamma k * gamma j) -
        (gamma i * gamma k + gamma k * gamma i) * gamma j -
        gamma j * (gamma i * gamma k + gamma k * gamma i) +
        (gamma j * gamma k + gamma k * gamma j) * gamma i := by
          noncomm_ring
    _ = gamma i * algebraMap R Op (2 * g j k) -
        algebraMap R Op (2 * g i k) * gamma j -
        gamma j * algebraMap R Op (2 * g i k) +
        algebraMap R Op (2 * g j k) * gamma i := by
          rw [show gamma j * gamma k + gamma k * gamma j =
              algebraMap R Op (2 * g j k) by
                simpa [operatorAnticommutator] using hdirac j k]
          rw [show gamma i * gamma k + gamma k * gamma i =
              algebraMap R Op (2 * g i k) by
                simpa [operatorAnticommutator] using hdirac i k]
    _ = (2 : Op) * algebraMap R Op (2 * g j k) * gamma i -
        (2 : Op) * algebraMap R Op (2 * g i k) * gamma j := by
          have hi : gamma i * algebraMap R Op (2 * g j k) =
              algebraMap R Op (2 * g j k) * gamma i :=
            (Algebra.commutes (2 * g j k) (gamma i)).symm
          have hj : gamma j * algebraMap R Op (2 * g i k) =
              algebraMap R Op (2 * g i k) * gamma j :=
            (Algebra.commutes (2 * g i k) (gamma j)).symm
          rw [hi, hj]
          noncomm_ring

theorem diracBivector_lieAd_action
    {g : ι → ι → R} {gamma : ι → Op}
    (hdirac : IsDiracMatrixSystem g gamma) (i j k : ι) :
    LieAlgebra.ad R Op (diracBivector gamma i j) (gamma k) =
      (2 : Op) * algebraMap R Op (2 * g j k) * gamma i -
        (2 : Op) * algebraMap R Op (2 * g i k) * gamma j := by
  simpa only [LieAlgebra.ad_apply, LieRing.of_associative_ring_bracket] using
    diracBivector_action hdirac i j k

theorem gammaBasis55_bivector_action (i j k : Fin 10) :
    diracBivector InfoGeometry.Clifford.Cl55SpinorChirality.gammaBasis55 i j *
          InfoGeometry.Clifford.Cl55SpinorChirality.gammaBasis55 k -
        InfoGeometry.Clifford.Cl55SpinorChirality.gammaBasis55 k *
          diracBivector InfoGeometry.Clifford.Cl55SpinorChirality.gammaBasis55 i j =
      (2 : SpinorMatrix 5) * algebraMap ℝ (SpinorMatrix 5) (2 *
          gammaBasisMetric55 j k) * gammaBasis55 i -
        (2 : SpinorMatrix 5) * algebraMap ℝ (SpinorMatrix 5) (2 *
          gammaBasisMetric55 i k) * gammaBasis55 j := by
  exact diracBivector_action
    InfoGeometry.Clifford.Cl55OperatorDiracSystem.gammaBasis55_isDiracMatrixSystem i j k

end InfoGeometry.Clifford
