import InfoGeometry.Clifford.Pin55KramersKleinAll

#print axioms InfoGeometry.Quantum.ComplexKramersAntiunitary.timeReversal_sq
#print axioms InfoGeometry.Quantum.ComplexKramersAntiunitary.timeReversal_antiunitary
#print axioms InfoGeometry.Quantum.ComplexKramersAntiunitary.timeReversal_kramers_orthogonal
#print axioms InfoGeometry.Quantum.ComplexKramersAntiunitary.kramers_eigenpair_packet
#print axioms InfoGeometry.Quantum.KramersPhaseGlideRepresentation.kramers_phase_inverse
#print axioms InfoGeometry.Topology.KleinDeckNormalForm.klein_conjugation_relation
#print axioms InfoGeometry.Topology.KleinDeckNormalForm.deckAct_eq_self_iff
#print axioms InfoGeometry.Topology.KleinDeckNormalForm.abelianReadout_mul
#print axioms InfoGeometry.Topology.KleinDeckNormalForm.abelianReadout_surjective
#print axioms InfoGeometry.Topology.KleinDeckNormalForm.horizontal_class_order_two
#print axioms InfoGeometry.Topology.KleinAffineOrbitQuotient.quotientMap_eq_iff
#print axioms InfoGeometry.Topology.KleinAffineOrbitQuotient.affine_orbit_quotient_packet
#print axioms InfoGeometry.Quantum.FiveGradedKramersModule.euler_kramers_anticommute
#print axioms InfoGeometry.Quantum.FiveGradedKramersModule.kramers_include
#print axioms InfoGeometry.Exceptional.Freudenthal.symplecticContact_lie_mem_multigrade
#print axioms InfoGeometry.Clifford.O55SymmetricBlockGrading.commutator_mem_o55
#print axioms InfoGeometry.Clifford.O55SymmetricBlockGrading.o55_symmetric_grading_packet
#print axioms InfoGeometry.Clifford.O55FiveGradeKramersBridge.o55_commutator_multigrade
#print axioms InfoGeometry.Clifford.O55FiveGradeKramersBridge.native_o55_five_lane_packet
#print axioms InfoGeometry.Clifford.O55FiveGradeKramersBridge.o55_five_grade_kramers_packet
#print axioms InfoGeometry.Clifford.Pin55KramersContactMultigrading.pin55_crosscap_projective_null_swap
#print axioms InfoGeometry.Clifford.Pin55KramersKleinFiveGradeClosure.complex_kramers_phase_packet
#print axioms InfoGeometry.Clifford.Pin55KramersKleinFiveGradeClosure.klein_quotient_readout_packet
#print axioms InfoGeometry.Clifford.Pin55KramersKleinFiveGradeClosure.pin55_kramers_klein_five_grade_packet
