import InfoGeometry.Thermo.JacobianBregmanBridge
import InfoGeometry.Algebra.FiniteSpinAlgebra

open InfoGeometry.Thermo

#check jacobianLogVolumeEnergy
#check freeEnergyFromJacobianLogVolume
#check jacobianLogVolumeBarrierEnergy
#check freeEnergyFromJacobianLogVolumeBarrier
#check spdOneExp
#check spdOneExp_det
#check logDetBregman_spdOneExp_zero
#check energyFromBregman_eq_jacobianLogVolumeEnergy
#check freeEnergyFromBregman_eq_freeEnergyFromJacobianLogVolume
#check energyFromLogDet_eq_jacobianLogVolumeEnergy
#check freeEnergyFromLogDet_eq_freeEnergyFromJacobianLogVolume
#check InfoGeometry.Topology.ThermodynamicSL2MobiusFlow.ThermodynamicSL2Variation.finiteOrbitJacobian_zero
#check InfoGeometry.Topology.ThermodynamicSL2MobiusFlow.ThermodynamicSL2Variation.logJacobianNorm_zero
#check InfoGeometry.Topology.ThermodynamicSL2MobiusFlow.ThermodynamicSL2Variation.boltzmannLogJacobianEntropy_zero
#check bregmanSelf_calibrates_zeroTimeJacobianLogVolume
#check freeEnergyFromBregman_self_eq_zeroTimeJacobianLogVolume
#check logDetSelf_calibrates_zeroTimeJacobianLogVolume
#check freeEnergyFromLogDet_self_eq_zeroTimeJacobianLogVolume
#check logDet_spdOneExp_calibrates_jacobianLogVolumeBarrier
#check freeEnergyFromLogDet_spdOneExp_eq_jacobianLogVolumeBarrier
