import InfoGeometry.Convex.Bregman

/-!
# Log Potential

Minimal abstraction for log-partition style potentials.
-/

namespace InfoGeometry

/-- A log-partition style potential on parameter space `θ`. -/
abbrev LogPotential (θ : Type _) := θ → ℝ

namespace LogPotential

/-- Compatibility accessor for the native function-space carrier. -/
def ψ (L : LogPotential θ) : θ → ℝ := L

@[simp] lemma ψ_apply (L : LogPotential θ) (x : θ) : L.ψ x = L x := rfl

/-- Canonical Bregman divergence generated by a 1D log potential. -/
noncomputable def bregman (L : LogPotential ℝ) (η θ₀ : ℝ) : ℝ :=
  bregmanDiv L.ψ η θ₀

@[simp]
lemma bregman_def (L : LogPotential ℝ) (η θ₀ : ℝ) :
    bregman L η θ₀ = bregmanDiv L.ψ η θ₀ := rfl

end LogPotential

end InfoGeometry
