import Mathlib
import proofs.ZornOPParavector

/-!
# Furey-Style Zorn Fermion Bridge

This module records the finite algebraic dictionary suggested by the
division-algebra/Zorn-matrix picture:

* diagonal Zorn idempotents act as lepton/projector slots;
* `Fin 3 → ℂ` off-diagonal lanes are the color triplet/anti-triplet slots;
* pure upper and lower lanes are square-zero ladder lanes;
* right multiplication by the complementary diagonal idempotent selects the
  corresponding off-diagonal lane, while the other idempotent annihilates it.

No analytic Standard Model representation theorem is asserted here.  This is the
checked algebraic scaffold needed before adding gauge-group actions.
-/

noncomputable section

namespace FureyZornFermionBridge

open ZornOPParavector

/-- The color-lane carrier used by the Zorn vector entries. -/
abbrev ColorTriplet : Type := Fin 3 → ℂ

/-- Upper diagonal color-singlet projector slot. -/
def leptonProjectorPlus : Zorn := Eplus

/-- Lower diagonal color-singlet projector slot. -/
def leptonProjectorMinus : Zorn := Eminus

/-- Upper off-diagonal triplet lane. -/
def quarkTripletLane (u : ColorTriplet) : Zorn := Nup u

/-- Lower off-diagonal anti-triplet lane. -/
def antiquarkTripletLane (v : ColorTriplet) : Zorn := Ndown v

/-- Right ideal generated by a Zorn idempotent. -/
def rightIdealSlot (P X : Zorn) : Zorn := X * P

theorem upper_lane_selected_by_lower_projector (u : ColorTriplet) :
    rightIdealSlot leptonProjectorMinus (quarkTripletLane u) = quarkTripletLane u := by
  change zornMul (Nup u) Eminus = Nup u
  apply Zorn.ext'
  · simp [Nup, Eminus, zornMul, dot3]
  · funext i
    fin_cases i <;> simp [Nup, Eminus, zornMul, cross3]
  · funext i
    fin_cases i <;> simp [Nup, Eminus, zornMul, cross3]
  · simp [Nup, Eminus, zornMul, dot3]

theorem upper_lane_annihilated_by_upper_projector (u : ColorTriplet) :
    rightIdealSlot leptonProjectorPlus (quarkTripletLane u) = 0 := by
  change zornMul (Nup u) Eplus = ⟨0, 0, 0, 0⟩
  apply Zorn.ext'
  · simp [Nup, Eplus, zornMul, dot3]
  · funext i
    fin_cases i <;> simp [Nup, Eplus, zornMul, cross3]
  · funext i
    fin_cases i <;> simp [Nup, Eplus, zornMul, cross3]
  · simp [Nup, Eplus, zornMul, dot3]

theorem lower_lane_selected_by_upper_projector (v : ColorTriplet) :
    rightIdealSlot leptonProjectorPlus (antiquarkTripletLane v) = antiquarkTripletLane v := by
  change zornMul (Ndown v) Eplus = Ndown v
  apply Zorn.ext'
  · simp [Ndown, Eplus, zornMul, dot3]
  · funext i
    fin_cases i <;> simp [Ndown, Eplus, zornMul, cross3]
  · funext i
    fin_cases i <;> simp [Ndown, Eplus, zornMul, cross3]
  · simp [Ndown, Eplus, zornMul, dot3]

theorem lower_lane_annihilated_by_lower_projector (v : ColorTriplet) :
    rightIdealSlot leptonProjectorMinus (antiquarkTripletLane v) = 0 := by
  change zornMul (Ndown v) Eminus = ⟨0, 0, 0, 0⟩
  apply Zorn.ext'
  · simp [Ndown, Eminus, zornMul, dot3]
  · funext i
    fin_cases i <;> simp [Ndown, Eminus, zornMul, cross3]
  · funext i
    fin_cases i <;> simp [Ndown, Eminus, zornMul, cross3]
  · simp [Ndown, Eminus, zornMul, dot3]

/-- Consolidated finite dictionary from Zorn projectors and nilpotent lanes to
the fermion/lane vocabulary. -/
theorem furey_zorn_fermion_bridge_synthesis :
    leptonProjectorPlus * leptonProjectorPlus = leptonProjectorPlus ∧
    leptonProjectorMinus * leptonProjectorMinus = leptonProjectorMinus ∧
    (∀ u : ColorTriplet, SquareZero (quarkTripletLane u)) ∧
    (∀ v : ColorTriplet, SquareZero (antiquarkTripletLane v)) ∧
    (∀ u : ColorTriplet,
      rightIdealSlot leptonProjectorMinus (quarkTripletLane u) = quarkTripletLane u) ∧
    (∀ u : ColorTriplet,
      rightIdealSlot leptonProjectorPlus (quarkTripletLane u) = 0) ∧
    (∀ v : ColorTriplet,
      rightIdealSlot leptonProjectorPlus (antiquarkTripletLane v) = antiquarkTripletLane v) ∧
    (∀ v : ColorTriplet,
      rightIdealSlot leptonProjectorMinus (antiquarkTripletLane v) = 0) := by
  exact ⟨Eplus_sq,
    Eminus_sq,
    Nup_sq,
    Ndown_sq,
    upper_lane_selected_by_lower_projector,
    upper_lane_annihilated_by_upper_projector,
    lower_lane_selected_by_upper_projector,
    lower_lane_annihilated_by_lower_projector⟩

end FureyZornFermionBridge

end noncomputable section
