import InfoGeometry.Lie.ContinuousDerivationExponential
import InfoGeometry.Lie.CanonicalZornDerivation
import InfoGeometry.OperatorAlgebra.SplitOctonionPseudoReal
import InfoGeometry.Canonical.ZornCliffordRepresentation
import Mathlib.Topology.Algebra.Module.FiniteDimensionBilinear

/-!
# Exponentiating canonical Zorn derivations

This module instantiates the generic continuous-derivation exponential theorem
on the canonical real Zorn split-octonion carrier.

The nonassociative Zorn product is transported through the existing coordinate
linear equivalence

`coordLE : ZornMatrix ℝ ≃ₗ[ℝ] (Fin 8 → ℝ)`.

The coordinate carrier is finite-dimensional, hence all linear endomorphisms
and the bilinear Zorn multiplication are continuous.  Consequently every
canonical Zorn derivation exponentiates to a genuine multiplicative linear
automorphism.  No associative `AlgEquiv` structure is imposed on the Zorn
algebra.
-/

noncomputable section

namespace InfoGeometry.Lie.CanonicalZornDerivationExponential

open InfoGeometry.Canonical
open InfoGeometry.Canonical.ZornMatrix
open InfoGeometry.Canonical.ZornClifford
open InfoGeometry.OperatorAlgebra.SplitOctonionPseudoReal

namespace CDE := InfoGeometry.Lie.ContinuousDerivationExponential
namespace CZD := InfoGeometry.Lie.CanonicalZornDerivation

abbrev CZ := CZD.CZ
abbrev EndCZ := CZD.EndCZ
abbrev V8 := Fin 8 → ℝ

/-- Zorn multiplication transported to the native coordinate carrier. -/
def coordMulLinear : V8 →ₗ[ℝ] V8 →ₗ[ℝ] V8 where
  toFun u :=
    { toFun := fun v => coordLE (coordLE.symm u * coordLE.symm v)
      map_add' := by
        intro v w
        rw [map_add, mul_add', map_add]
      map_smul' := by
        intro r v
        rw [map_smul, mul_smul', map_smul] }
  map_add' := by
    intro u v
    ext w
    rw [map_add, add_mul', map_add]
  map_smul' := by
    intro r u
    ext v
    rw [map_smul, smul_mul', map_smul]

/--
The transported Zorn multiplication as a continuous bilinear map.
Continuity is automatic in the finite-dimensional coordinate model.
-/
noncomputable def coordMul : V8 →L[ℝ] V8 →L[ℝ] V8 :=
  coordMulLinear.toContinuousBilinearMap

@[simp]
theorem coordMul_apply (u v : V8) :
    coordMul u v = coordLE (coordLE.symm u * coordLE.symm v) := by
  rfl

@[simp]
theorem coordMul_coordLE (X Y : CZ) :
    coordMul (coordLE X) (coordLE Y) = coordLE (X * Y) := by
  simp [coordMul]

/-- Transport a canonical Zorn endomorphism to the eight-dimensional coordinate space. -/
def coordEndLinear (D : EndCZ) : Module.End ℝ V8 :=
  (coordLE : CZ →ₗ[ℝ] V8).comp
    (D.comp (coordLE.symm : V8 →ₗ[ℝ] CZ))

/-- Every transported endomorphism is continuous because `V8` is finite-dimensional. -/
noncomputable def coordEnd (D : EndCZ) : V8 →L[ℝ] V8 :=
  (coordEndLinear D).toContinuousLinearMap

@[simp]
theorem coordEnd_apply (D : EndCZ) (u : V8) :
    coordEnd D u = coordLE (D (coordLE.symm u)) := by
  rfl

@[simp]
theorem coordEnd_coordLE (D : EndCZ) (X : CZ) :
    coordEnd D (coordLE X) = coordLE (D X) := by
  simp [coordEnd]

/-- The Leibniz property is invariant under the coordinate transport. -/
theorem coordEnd_isDerivation
    (D : EndCZ)
    (hD : CZD.IsDerivation D) :
    CDE.IsDerivation coordMul (coordEnd D) := by
  intro u v
  apply coordLE.injective
  simp only [coordEnd_apply, coordMul_apply, Equiv.apply_symm_apply]
  rw [hD]
  simp

/-- The exponential flow on coordinates generated by a canonical Zorn endomorphism. -/
noncomputable def coordFlow (D : EndCZ) (t : ℝ) : V8 →L[ℝ] V8 :=
  CDE.flow (coordEnd D) t

/-- The coordinate exponential flow of a derivation preserves transported Zorn multiplication. -/
theorem coordFlow_map_mul
    (D : EndCZ)
    (hD : CZD.IsDerivation D)
    (t : ℝ)
    (u v : V8) :
    coordFlow D t (coordMul u v) =
      coordMul (coordFlow D t u) (coordFlow D t v) := by
  exact CDE.flow_map_mul
    coordMul (coordEnd D) (coordEnd_isDerivation D hD) t u v

/--
The exponential flow transported back to the canonical real Zorn carrier.
Its inverse is the same construction for the negative generator.
-/
noncomputable def zornFlowLinearEquiv (D : EndCZ) (t : ℝ) : CZ ≃ₗ[ℝ] CZ :=
  coordLE.trans
    ((CDE.flowLinearEquiv (coordEnd D) t).trans coordLE.symm)

@[simp]
theorem zornFlowLinearEquiv_apply (D : EndCZ) (t : ℝ) (X : CZ) :
    zornFlowLinearEquiv D t X =
      coordLE.symm (CDE.flow (coordEnd D) t (coordLE X)) := by
  rfl

@[simp]
theorem coordLE_zornFlowLinearEquiv (D : EndCZ) (t : ℝ) (X : CZ) :
    coordLE (zornFlowLinearEquiv D t X) =
      CDE.flow (coordEnd D) t (coordLE X) := by
  simp [zornFlowLinearEquiv]

/--
A canonical Zorn derivation exponentiates to a multiplication-preserving
linear equivalence of the nonassociative split-octonion carrier.
-/
theorem zornFlow_map_mul
    (D : EndCZ)
    (hD : CZD.IsDerivation D)
    (t : ℝ)
    (X Y : CZ) :
    zornFlowLinearEquiv D t (X * Y) =
      zornFlowLinearEquiv D t X * zornFlowLinearEquiv D t Y := by
  apply coordLE.injective
  rw [coordLE_zornFlowLinearEquiv]
  rw [coordLE_zornFlowLinearEquiv]
  rw [coordLE_zornFlowLinearEquiv]
  rw [← coordMul_coordLE]
  exact coordFlow_map_mul D hD t (coordLE X) (coordLE Y)

/--
The full exponential family as native `MulEquiv`s.

`MulEquiv` only packages a bijection and multiplication preservation; it does
not impose associativity, so it is appropriate for the Zorn algebra.
-/
noncomputable def zornFlowMulEquiv
    (D : CZD.canonicalZornDerivations)
    (t : ℝ) : CZ ≃* CZ where
  toEquiv := (zornFlowLinearEquiv D.1 t).toEquiv
  map_mul' := by
    intro X Y
    exact zornFlow_map_mul D.1 D.2 t X Y

@[simp]
theorem zornFlowMulEquiv_apply
    (D : CZD.canonicalZornDerivations)
    (t : ℝ)
    (X : CZ) :
    zornFlowMulEquiv D t X = zornFlowLinearEquiv D.1 t X := by
  rfl

/-- Time-zero Zorn flow is the identity. -/
theorem zornFlowLinearEquiv_zero_apply
    (D : EndCZ)
    (X : CZ) :
    zornFlowLinearEquiv D 0 X = X := by
  apply coordLE.injective
  simp [zornFlowLinearEquiv, CDE.flow]

/-- The inverse flow is generated by the negative derivation. -/
theorem zornFlowLinearEquiv_neg_apply
    (D : EndCZ)
    (t : ℝ)
    (X : CZ) :
    zornFlowLinearEquiv (-D) t (zornFlowLinearEquiv D t X) = X := by
  apply coordLE.injective
  simp [zornFlowLinearEquiv, CDE.flowLinearEquiv]

/-- Time-one exponential automorphism of a canonical Zorn derivation. -/
noncomputable def zornDerivationExpAutomorphism
    (D : CZD.canonicalZornDerivations) : CZ ≃* CZ :=
  zornFlowMulEquiv D 1

/-- Main time-one capstone: `exp(D)` preserves the Zorn product. -/
theorem zornDerivationExpAutomorphism_map_mul
    (D : CZD.canonicalZornDerivations)
    (X Y : CZ) :
    zornDerivationExpAutomorphism D (X * Y) =
      zornDerivationExpAutomorphism D X *
        zornDerivationExpAutomorphism D Y := by
  exact map_mul (zornDerivationExpAutomorphism D) X Y

/-- Every standard canonical derivation therefore has a genuine finite automorphism flow. -/
theorem canonical_derivation_exponential_packet
    (D : CZD.canonicalZornDerivations)
    (t : ℝ)
    (X Y : CZ) :
    zornFlowMulEquiv D t (X * Y) =
      zornFlowMulEquiv D t X * zornFlowMulEquiv D t Y := by
  exact map_mul (zornFlowMulEquiv D t) X Y

end InfoGeometry.Lie.CanonicalZornDerivationExponential

end noncomputable section
