import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Analysis.Normed.Operator.Bilinear
import Mathlib.Tactic

/-!
# Exponential flow of a continuous derivation

This module proves a generic theorem for a complete real normed vector space
`A` equipped with an arbitrary continuous bilinear multiplication

`mul : A →L[ℝ] A →L[ℝ] A`.

No associativity hypothesis is imposed on `mul`.

For a bounded linear endomorphism `D : A →L[ℝ] A` satisfying the Leibniz rule

`D (mul x y) = mul (D x) y + mul x (D y)`,

the operator exponential

`Φ_t = exp (t D)`

is proved to satisfy

`Φ_t (mul x y) = mul (Φ_t x) (Φ_t y)`.

The inverse is `Φ_{-t}`.  Thus every continuous derivation integrates to a
one-parameter family of multiplicative linear equivalences.  The proof uses
only the associative Banach algebra of continuous linear endomorphisms; the
original multiplication on `A` may be nonassociative.
-/

noncomputable section

namespace InfoGeometry.Lie.ContinuousDerivationExponential

variable {A : Type*}
variable [NormedAddCommGroup A] [NormedSpace ℝ A] [CompleteSpace A]

local notation "EndA" => A →L[ℝ] A

noncomputable local instance : NormedRing EndA := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndA := inferInstance
local instance : IsTopologicalRing EndA := inferInstance
local instance : CompleteSpace EndA := inferInstance

/-- Leibniz predicate for an arbitrary continuous bilinear multiplication. -/
def IsDerivation
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA) : Prop :=
  ∀ x y : A, D (mul x y) = mul (D x) y + mul x (D y)

/-- The exponential flow generated by `D`. -/
noncomputable def flow (D : EndA) (t : ℝ) : EndA :=
  NormedSpace.exp (t • D)

@[simp]
theorem flow_zero (D : EndA) :
    flow D 0 = 1 := by
  simp [flow]

/-- Scalar multiples of one operator commute. -/
theorem smul_commute_smul (D : EndA) (s t : ℝ) :
    Commute (s • D) (t • D) := by
  exact ((Commute.refl D).smul_left s).smul_right t

/-- The exponential flow is a one-parameter group. -/
theorem flow_add (D : EndA) (s t : ℝ) :
    flow D (s + t) = flow D s * flow D t := by
  simpa [flow, add_smul] using
    (NormedSpace.exp_add_of_commute (smul_commute_smul D s t))

@[simp]
theorem flow_neg_generator (D : EndA) (t : ℝ) :
    flow (-D) t = flow D (-t) := by
  simp [flow, smul_neg, neg_smul]

/-- `Φ_t Φ_{-t} = 1`. -/
theorem flow_mul_flow_neg (D : EndA) (t : ℝ) :
    flow D t * flow (-D) t = 1 := by
  rw [flow_neg_generator]
  simpa using (flow_add D t (-t)).symm

/-- `Φ_{-t} Φ_t = 1`. -/
theorem flow_neg_mul_flow (D : EndA) (t : ℝ) :
    flow (-D) t * flow D t = 1 := by
  rw [flow_neg_generator]
  simpa using (flow_add D (-t) t).symm

@[simp]
theorem flow_apply_flow_neg (D : EndA) (t : ℝ) (x : A) :
    flow D t (flow (-D) t x) = x := by
  have h := congrArg (fun T : EndA => T x) (flow_mul_flow_neg D t)
  simpa [mul_apply_eq_comp] using h

@[simp]
theorem flow_neg_apply_flow (D : EndA) (t : ℝ) (x : A) :
    flow (-D) t (flow D t x) = x := by
  have h := congrArg (fun T : EndA => T x) (flow_neg_mul_flow D t)
  simpa [mul_apply_eq_comp] using h

/-- Left-generator derivative formula `Φ'_t = D Φ_t`. -/
theorem hasStrictDerivAt_flow_left (D : EndA) (t : ℝ) :
    HasStrictDerivAt (flow D) (D * flow D t) t := by
  simpa [flow] using
    (hasStrictDerivAt_exp_smul_const' D t)

/-- Right-generator derivative formula `Φ'_t = Φ_t D`. -/
theorem hasStrictDerivAt_flow_right (D : EndA) (t : ℝ) :
    HasStrictDerivAt (flow D) (flow D t * D) t := by
  simpa [flow] using
    (hasStrictDerivAt_exp_smul_const D t)

/-- Evaluation of an endomorphism on a vector as a continuous bilinear map. -/
private noncomputable def evalOp : EndA →L[ℝ] A →L[ℝ] A :=
  (ContinuousLinearMap.apply ℝ A).flip

@[simp]
private theorem evalOp_apply (T : EndA) (x : A) :
    evalOp T x = T x := by
  rfl

/-- Orbit equation `d/dt (Φ_t x) = D (Φ_t x)`. -/
theorem hasStrictDerivAt_orbit (D : EndA) (x : A) (t : ℝ) :
    HasStrictDerivAt
      (fun s : ℝ => flow D s x)
      (D (flow D t x))
      t := by
  have h :=
    (evalOp (A := A)).hasStrictDerivAt_of_bilinear
      (hasStrictDerivAt_flow_left D t)
      (hasStrictDerivAt_const t x)
  simpa [evalOp, mul_apply_eq_comp] using h

/-- Equivalent orbit equation `d/dt (Φ_t x) = Φ_t (D x)`. -/
theorem hasStrictDerivAt_orbit_right (D : EndA) (x : A) (t : ℝ) :
    HasStrictDerivAt
      (fun s : ℝ => flow D s x)
      (flow D t (D x))
      t := by
  have h :=
    (evalOp (A := A)).hasStrictDerivAt_of_bilinear
      (hasStrictDerivAt_flow_right D t)
      (hasStrictDerivAt_const t x)
  simpa [evalOp, mul_apply_eq_comp] using h

/-- The generator commutes with its own exponential flow on every vector. -/
theorem flow_apply_derivation (D : EndA) (t : ℝ) (x : A) :
    flow D t (D x) = D (flow D t x) := by
  have h :=
    (hasStrictDerivAt_orbit D x t).unique
      (hasStrictDerivAt_orbit_right D x t)
  exact h.symm

/-- Product of two exponential orbits satisfies the same linear evolution law. -/
theorem hasStrictDerivAt_mul_orbit
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA)
    (hD : IsDerivation mul D)
    (x y : A) (t : ℝ) :
    HasStrictDerivAt
      (fun s : ℝ => mul (flow D s x) (flow D s y))
      (D (mul (flow D t x) (flow D t y)))
      t := by
  have h :=
    mul.hasStrictDerivAt_of_bilinear
      (hasStrictDerivAt_orbit D x t)
      (hasStrictDerivAt_orbit D y t)
  convert h using 1
  rw [hD]
  abel

/-- Interaction-picture product used in the multiplicativity proof. -/
noncomputable def interaction
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA)
    (x y : A)
    (t : ℝ) : A :=
  flow (-D) t (mul (flow D t x) (flow D t y))

/-- The interaction-picture product has identically zero derivative. -/
theorem hasStrictDerivAt_interaction_zero
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA)
    (hD : IsDerivation mul D)
    (x y : A)
    (t : ℝ) :
    HasStrictDerivAt (interaction mul D x y) 0 t := by
  let p : ℝ → A := fun s => mul (flow D s x) (flow D s y)

  have hp : HasStrictDerivAt p (D (p t)) t := by
    simpa [p] using hasStrictDerivAt_mul_orbit mul D hD x y t

  have hback :
      HasStrictDerivAt (flow (-D)) (flow (-D) t * (-D)) t :=
    hasStrictDerivAt_flow_right (-D) t

  have h :=
    (evalOp (A := A)).hasStrictDerivAt_of_bilinear hback hp

  have hz :
      flow (-D) t (D (p t)) + (flow (-D) t * (-D)) (p t) = 0 := by
    rw [mul_apply_eq_comp]
    simp

  simpa [interaction, p, evalOp, mul_apply_eq_comp, hz] using h

/-- The interaction-picture product is constant and equal to its value at zero. -/
theorem interaction_eq_initial
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA)
    (hD : IsDerivation mul D)
    (x y : A)
    (t : ℝ) :
    interaction mul D x y t = mul x y := by
  have hder :
      ∀ s : ℝ, HasDerivAt (interaction mul D x y) 0 s :=
    fun s => (hasStrictDerivAt_interaction_zero mul D hD x y s).hasDerivAt

  have hdiff : Differentiable ℝ (interaction mul D x y) :=
    fun s => (hder s).differentiableAt

  have hzero : ∀ s : ℝ, deriv (interaction mul D x y) s = 0 :=
    fun s => (hder s).deriv

  have hconst := is_const_of_deriv_eq_zero hdiff hzero t 0
  simpa [interaction] using hconst

/--
The exponential of a derivation preserves the multiplication.

No associativity assumption on `mul` is used.
-/
theorem flow_map_mul
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA)
    (hD : IsDerivation mul D)
    (t : ℝ)
    (x y : A) :
    flow D t (mul x y) = mul (flow D t x) (flow D t y) := by
  have h := congrArg (fun z : A => flow D t z)
    (interaction_eq_initial mul D hD x y t)
  simpa [interaction] using h.symm

/-- Exponential flow as a genuine linear equivalence, with inverse generated by `-D`. -/
noncomputable def flowLinearEquiv (D : EndA) (t : ℝ) : A ≃ₗ[ℝ] A where
  toFun := flow D t
  invFun := flow (-D) t
  left_inv := flow_neg_apply_flow D t
  right_inv := flow_apply_flow_neg D t
  map_add' := (flow D t).map_add
  map_smul' := (flow D t).map_smul

@[simp]
theorem flowLinearEquiv_apply (D : EndA) (t : ℝ) (x : A) :
    flowLinearEquiv D t x = flow D t x := by
  rfl

@[simp]
theorem flowLinearEquiv_symm_apply (D : EndA) (t : ℝ) (x : A) :
    (flowLinearEquiv D t).symm x = flow (-D) t x := by
  rfl

/-- Strong automorphism statement in multiplicative linear-equivalence form. -/
theorem exponential_derivation_is_automorphism
    (mul : A →L[ℝ] A →L[ℝ] A)
    (D : EndA)
    (hD : IsDerivation mul D)
    (t : ℝ)
    (x y : A) :
    flowLinearEquiv D t (mul x y) =
      mul (flowLinearEquiv D t x) (flowLinearEquiv D t y) := by
  exact flow_map_mul mul D hD t x y

/-- The infinitesimal generator of the automorphism flow is `D`. -/
theorem deriv_flow_at_zero (D : EndA) :
    deriv (flow D) 0 = D := by
  exact (hasStrictDerivAt_flow_left D 0).deriv

end InfoGeometry.Lie.ContinuousDerivationExponential

end noncomputable section
