import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Mathlib.Tactic
import InfoGeometry.Canonical.A2WeylFin3Action
import InfoGeometry.Canonical.SixStateWeylReflection

/-!
# The order-twelve dihedral factorisation on the six-state carrier

The concrete six-state matrices `sixWeylX` and `thetaSix` already satisfy the
order-six and reflection relations.  This file packages the finite group
behind those relations without introducing a new presentation or an
unproved matrix-subgroup cardinality claim.

The standard finite factorisation is made explicit as
`DihedralGroup 6 ≃* C₂ × DihedralGroup 3`; the second factor is the native
order-six model of `S₃` used by Mathlib's dihedral group API.  The matrix
operators are promoted to a faithful `DihedralGroup 6` representation: the
homomorphism is injective, its range is the subgroup generated by the two
concrete units, and the resulting range equivalence is explicit.
-/

open scoped Matrix

namespace InfoGeometry.Canonical.SixStateD6C2S3

open InfoGeometry.Canonical.SixStateGeneralizedCliffordAlgebra
open InfoGeometry.Canonical.SixStateWeylReflection
open InfoGeometry.Canonical.A2WeylFin3Action

noncomputable section

abbrev D6 := DihedralGroup 6
abbrev S3Model := DihedralGroup 3
abbrev S3 := Equiv.Perm (Fin 3)
abbrev C2 := Multiplicative (ZMod 2)
abbrev D6Product := C2 × S3Model

private def d6ProductMap : D6 → D6Product
  | .r i =>
      ((((i.val % 2 : Nat) : ZMod 2) : C2),
        .r ((i.val % 3 : Nat) : ZMod 3))
  | .sr i =>
      ((((i.val % 2 : Nat) : ZMod 2) : C2),
        .sr ((i.val % 3 : Nat) : ZMod 3))

private theorem d6ProductMap_mul (a b : D6) :
    d6ProductMap (a * b) = d6ProductMap a * d6ProductMap b := by
  cases a with
  | r i =>
    cases b with
    | r j =>
      fin_cases i <;> fin_cases j <;>
        simp only [DihedralGroup.r_mul_r, d6ProductMap] <;> native_decide
    | sr j =>
      fin_cases i <;> fin_cases j <;>
        simp only [DihedralGroup.r_mul_sr, d6ProductMap] <;> native_decide
  | sr i =>
    cases b with
    | r j =>
      fin_cases i <;> fin_cases j <;>
        simp only [DihedralGroup.sr_mul_r, d6ProductMap] <;> native_decide
    | sr j =>
      fin_cases i <;> fin_cases j <;>
        simp only [DihedralGroup.sr_mul_sr, d6ProductMap] <;> native_decide

def d6ProductHom : D6 →* D6Product where
  toFun := d6ProductMap
  map_one' := by
    change d6ProductMap (1 : D6) = 1
    change d6ProductMap (.r 0) = 1
    rfl
  map_mul' := d6ProductMap_mul

private theorem d6ProductHom_injective : Function.Injective d6ProductHom := by
  native_decide

theorem d6ProductHom_bijective : Function.Bijective d6ProductHom := by
  apply (Fintype.bijective_iff_injective_and_card d6ProductHom).2
  constructor
  · exact d6ProductHom_injective
  · simp [D6Product, DihedralGroup.card]

/- The canonical finite factorisation `D₆ ≅ C₂ × S₃`. -/
def d6ProductEquiv : D6 ≃* D6Product :=
  MulEquiv.ofBijective d6ProductHom d6ProductHom_bijective

theorem d6ProductEquiv_card : Fintype.card D6Product = 12 := by
  simp [D6Product, DihedralGroup.card]

private def d3PermutationMap : S3Model → S3
  | .r i => shiftC3 ^ i.val
  | .sr i => rho3 * shiftC3 ^ i.val

def d3PermutationHom : S3Model →* S3 where
  toFun := d3PermutationMap
  map_one' := by
    change d3PermutationMap (.r 0) = 1
    rfl
  map_mul' := by
    intro a b
    cases a with
    | r i =>
      cases b with
      | r j =>
        rw [DihedralGroup.r_mul_r]
        fin_cases i <;> fin_cases j <;>
          dsimp [d3PermutationMap] <;> native_decide
      | sr j =>
        rw [DihedralGroup.r_mul_sr]
        fin_cases i <;> fin_cases j <;>
          dsimp [d3PermutationMap] <;> native_decide
    | sr i =>
      cases b with
      | r j =>
        rw [DihedralGroup.sr_mul_r]
        fin_cases i <;> fin_cases j <;>
          dsimp [d3PermutationMap] <;> native_decide
      | sr j =>
        rw [DihedralGroup.sr_mul_sr]
        fin_cases i <;> fin_cases j <;>
          dsimp [d3PermutationMap] <;> native_decide

private theorem d3PermutationHom_injective :
    Function.Injective d3PermutationHom := by
  native_decide

theorem d3PermutationHom_bijective :
    Function.Bijective d3PermutationHom := by
  apply (Fintype.bijective_iff_injective_and_card d3PermutationHom).2
  constructor
  · exact d3PermutationHom_injective
  · simp [DihedralGroup.card, Fintype.card_perm]
    norm_num

def d3PermutationEquiv : S3Model ≃* S3 :=
  MulEquiv.ofBijective d3PermutationHom d3PermutationHom_bijective

abbrev D6C2S3 := C2 × S3

/- The requested concrete finite group isomorphism `D₆ ≃ C₂ × S₃`. -/
def d6C2S3Equiv : D6 ≃* D6C2S3 :=
  d6ProductEquiv.trans
    (MulEquiv.prodCongr (MulEquiv.refl C2) d3PermutationEquiv)

theorem d6C2S3Equiv_card : Fintype.card D6C2S3 = 12 := by
  simp [D6C2S3, Fintype.card_perm]
  norm_num

abbrev SixMatrix := SixStateGeneralizedCliffordAlgebra.SixMatrix

def sixWeylXUnit : SixMatrixˣ where
  val := sixWeylX
  inv := sixWeylX ^ 5
  val_inv := by rw [← pow_succ', sixWeylX_six]
  inv_val := by rw [← pow_succ, sixWeylX_six]

def thetaSixUnit : SixMatrixˣ where
  val := thetaSix
  inv := thetaSix
  val_inv := by simpa [pow_two] using thetaSix_sq
  inv_val := by simpa [pow_two] using thetaSix_sq

@[simp] theorem sixWeylXUnit_val :
    (sixWeylXUnit : SixMatrix) = sixWeylX := rfl

@[simp] theorem thetaSixUnit_val :
    (thetaSixUnit : SixMatrix) = thetaSix := rfl

theorem sixWeylXUnit_pow_six : sixWeylXUnit ^ 6 = 1 := by
  apply Units.ext
  exact sixWeylX_six

theorem thetaSixUnit_pow_two : thetaSixUnit ^ 2 = 1 := by
  apply Units.ext
  exact thetaSix_sq

/- The concrete operator reflection conjugates the order-six shift to its inverse. -/
theorem thetaSixUnit_conj_sixWeylXUnit :
    thetaSixUnit * sixWeylXUnit * thetaSixUnit = sixWeylXUnit ^ 5 := by
  apply Units.ext
  exact thetaSix_conj_sixWeylX

/-- The two concrete generators do not commute.  This is a consequence of
the reflection conjugacy law together with the exact order-six certificate;
no matrix-entry argument is needed. -/
theorem thetaSixUnit_not_commute_sixWeylXUnit :
    thetaSixUnit * sixWeylXUnit ≠
      sixWeylXUnit * thetaSixUnit := by
  intro h
  have hconj :
      thetaSixUnit * sixWeylXUnit * thetaSixUnit = sixWeylXUnit := by
    calc
      thetaSixUnit * sixWeylXUnit * thetaSixUnit =
          (sixWeylXUnit * thetaSixUnit) * thetaSixUnit := by rw [h]
      _ = sixWeylXUnit * (thetaSixUnit * thetaSixUnit) := by rw [mul_assoc]
      _ = sixWeylXUnit := by rw [← pow_two, thetaSixUnit_pow_two]; simp
  have hx : sixWeylXUnit ^ 5 = sixWeylXUnit := by
    rw [← thetaSixUnit_conj_sixWeylXUnit]
    exact hconj
  have hx4 : sixWeylXUnit ^ 4 = 1 := by
    apply mul_left_cancel (a := sixWeylXUnit)
    calc
      sixWeylXUnit * sixWeylXUnit ^ 4 = sixWeylXUnit ^ 5 := by
        rw [← pow_succ']
      _ = sixWeylXUnit := hx
      _ = sixWeylXUnit * 1 := by simp
  have hne4 : sixWeylXUnit ^ 4 ≠ 1 := by
    intro h4
    apply sixWeylX_four_ne_one
    exact congrArg Units.val h4
  exact hne4 hx4

theorem sixWeylXUnit_order : orderOf sixWeylXUnit = 6 := by
  have hpow : sixWeylXUnit ^ 6 = 1 := sixWeylXUnit_pow_six
  have hne : sixWeylXUnit ^ 3 ≠ 1 := by
    intro h
    apply sixWeylX_cube_ne_one
    exact congrArg Units.val h
  have hne4 : sixWeylXUnit ^ 4 ≠ 1 := by
    intro h
    apply sixWeylX_four_ne_one
    exact congrArg Units.val h
  have hdvd : orderOf sixWeylXUnit ∣ 6 := orderOf_dvd_of_pow_eq_one hpow
  have hpos : 0 < orderOf sixWeylXUnit :=
    (isOfFinOrder_iff_pow_eq_one.mpr ⟨6, by norm_num, hpow⟩).orderOf_pos
  have hle : orderOf sixWeylXUnit ≤ 6 := Nat.le_of_dvd (by decide) hdvd
  generalize hk : orderOf sixWeylXUnit = k at hdvd hpos hle ⊢
  have hk_cases : k = 1 ∨ k = 2 ∨ k = 3 ∨ k = 6 := by
    interval_cases k <;> omega
  rcases hk_cases with h | h | h | h
  · have : sixWeylXUnit = 1 := by
      have : orderOf sixWeylXUnit = 1 := hk.trans h
      simpa only [this, pow_one] using pow_orderOf_eq_one sixWeylXUnit
    exact False.elim (hne (by simpa [this]))
  · have h2 : sixWeylXUnit ^ 2 = 1 := by
      have : orderOf sixWeylXUnit = 2 := hk.trans h
      simpa only [this] using pow_orderOf_eq_one sixWeylXUnit
    exact False.elim (hne4 (by
      calc
        sixWeylXUnit ^ 4 = (sixWeylXUnit ^ 2) ^ 2 := by rw [← pow_mul]
        _ = 1 := by rw [h2]; simp))
  · exact False.elim (hne (by
      have : orderOf sixWeylXUnit = 3 := hk.trans h
      simpa only [this] using pow_orderOf_eq_one sixWeylXUnit))
  · exact h

private theorem thetaSixUnit_mul_sixWeylXUnit :
    thetaSixUnit * sixWeylXUnit =
      sixWeylXUnit ^ 5 * thetaSixUnit := by
  calc
    thetaSixUnit * sixWeylXUnit =
        thetaSixUnit * sixWeylXUnit *
          (thetaSixUnit * thetaSixUnit) := by
      rw [show thetaSixUnit * thetaSixUnit = 1 by
        simpa [← pow_two] using thetaSixUnit_pow_two]
      simp
    _ = (thetaSixUnit * sixWeylXUnit * thetaSixUnit) * thetaSixUnit := by
      noncomm_ring
    _ = sixWeylXUnit ^ 5 * thetaSixUnit := by
      rw [thetaSixUnit_conj_sixWeylXUnit]

private theorem sixWeylXUnit_mul_thetaSixUnit :
    sixWeylXUnit * thetaSixUnit =
      thetaSixUnit * sixWeylXUnit ^ 5 := by
  calc
    sixWeylXUnit * thetaSixUnit =
        (thetaSixUnit * thetaSixUnit) * sixWeylXUnit * thetaSixUnit := by
      rw [show thetaSixUnit * thetaSixUnit = 1 by
        simpa [← pow_two] using thetaSixUnit_pow_two]
      simp
    _ = thetaSixUnit * (thetaSixUnit * sixWeylXUnit * thetaSixUnit) := by
      noncomm_ring
    _ = thetaSixUnit * sixWeylXUnit ^ 5 := by
      rw [thetaSixUnit_conj_sixWeylXUnit]

private theorem thetaSixUnit_mul_sixWeylXUnit_pow (k : ℕ) :
    thetaSixUnit * sixWeylXUnit ^ k =
      sixWeylXUnit ^ (5 * k) * thetaSixUnit := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ, ← mul_assoc, ih, mul_assoc,
      thetaSixUnit_mul_sixWeylXUnit, ← mul_assoc, ← pow_add]
    rw [show 5 * k + 5 = 5 * (k + 1) by omega]

private theorem sixWeylXUnit_pow_mul_thetaSixUnit (k : ℕ) :
    sixWeylXUnit ^ k * thetaSixUnit =
      thetaSixUnit * sixWeylXUnit ^ (5 * k) := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ, mul_assoc, sixWeylXUnit_mul_thetaSixUnit, ← mul_assoc, ih,
      mul_assoc, ← pow_add]
    rw [show 5 * k + 5 = 5 * (k + 1) by omega]

private theorem sixWeylXUnit_pow_mod_six (n : ℕ) :
    sixWeylXUnit ^ (n % 6) = sixWeylXUnit ^ n := by
  calc
    sixWeylXUnit ^ (n % 6) =
        sixWeylXUnit ^ (n % 6 + 6 * (n / 6)) := by
      rw [pow_add, pow_mul, sixWeylXUnit_pow_six]
      simp
    _ = sixWeylXUnit ^ n := by rw [Nat.mod_add_div]

private theorem sixWeylXUnit_pow_zmod_add (i j : ZMod 6) :
    sixWeylXUnit ^ (i + j).val =
      sixWeylXUnit ^ i.val * sixWeylXUnit ^ j.val := by
  rw [ZMod.val_add]
  rw [sixWeylXUnit_pow_mod_six]
  rw [← pow_add]

private theorem sixWeylXUnit_pow_zmod_sub (i j : ZMod 6) :
    sixWeylXUnit ^ (j - i).val =
      sixWeylXUnit ^ (5 * i.val + j.val) := by
  rw [← sixWeylXUnit_pow_mod_six ((j - i).val),
    ← sixWeylXUnit_pow_mod_six (5 * i.val + j.val)]
  congr 1
  fin_cases i <;> fin_cases j <;> native_decide

private def d6MatrixMap : D6 → SixMatrixˣ
  | .r i => sixWeylXUnit ^ i.val
  | .sr i => thetaSixUnit * sixWeylXUnit ^ i.val

private theorem d6MatrixMap_mul (a b : D6) :
    d6MatrixMap (a * b) = d6MatrixMap a * d6MatrixMap b := by
  cases a with
  | r i =>
    cases b with
    | r j =>
      rw [DihedralGroup.r_mul_r]
      change sixWeylXUnit ^ (i + j).val =
        sixWeylXUnit ^ i.val * sixWeylXUnit ^ j.val
      exact sixWeylXUnit_pow_zmod_add i j
    | sr j =>
      rw [DihedralGroup.r_mul_sr]
      change thetaSixUnit * sixWeylXUnit ^ (j - i).val =
        sixWeylXUnit ^ i.val *
          (thetaSixUnit * sixWeylXUnit ^ j.val)
      symm
      calc
        sixWeylXUnit ^ i.val *
              (thetaSixUnit * sixWeylXUnit ^ j.val) =
            (sixWeylXUnit ^ i.val * thetaSixUnit) *
              sixWeylXUnit ^ j.val := by rw [mul_assoc]
        _ = (thetaSixUnit * sixWeylXUnit ^ (5 * i.val)) *
              sixWeylXUnit ^ j.val := by
          rw [sixWeylXUnit_pow_mul_thetaSixUnit]
        _ = thetaSixUnit *
              (sixWeylXUnit ^ (5 * i.val) * sixWeylXUnit ^ j.val) := by
          rw [mul_assoc]
        _ = thetaSixUnit *
              sixWeylXUnit ^ (5 * i.val + j.val) := by
          rw [← pow_add]
        _ = thetaSixUnit * sixWeylXUnit ^ (j - i).val := by
          rw [sixWeylXUnit_pow_zmod_sub]
  | sr i =>
    cases b with
    | r j =>
      rw [DihedralGroup.sr_mul_r]
      change thetaSixUnit * sixWeylXUnit ^ (i + j).val =
        (thetaSixUnit * sixWeylXUnit ^ i.val) * sixWeylXUnit ^ j.val
      calc
        thetaSixUnit * sixWeylXUnit ^ (i + j).val =
            thetaSixUnit *
              (sixWeylXUnit ^ i.val * sixWeylXUnit ^ j.val) := by
          rw [sixWeylXUnit_pow_zmod_add]
        _ = (thetaSixUnit * sixWeylXUnit ^ i.val) *
              sixWeylXUnit ^ j.val := by rw [mul_assoc]
    | sr j =>
      rw [DihedralGroup.sr_mul_sr]
      change sixWeylXUnit ^ (j - i).val =
        (thetaSixUnit * sixWeylXUnit ^ i.val) *
          (thetaSixUnit * sixWeylXUnit ^ j.val)
      symm
      calc
        (thetaSixUnit * sixWeylXUnit ^ i.val) *
              (thetaSixUnit * sixWeylXUnit ^ j.val) =
            thetaSixUnit * (sixWeylXUnit ^ i.val * thetaSixUnit) *
              sixWeylXUnit ^ j.val := by noncomm_ring
        _ = thetaSixUnit *
              (thetaSixUnit * sixWeylXUnit ^ (5 * i.val)) *
              sixWeylXUnit ^ j.val := by
          rw [sixWeylXUnit_pow_mul_thetaSixUnit]
        _ = (thetaSixUnit * thetaSixUnit) *
              (sixWeylXUnit ^ (5 * i.val) * sixWeylXUnit ^ j.val) := by
          noncomm_ring
        _ = sixWeylXUnit ^ (5 * i.val + j.val) := by
          rw [show thetaSixUnit * thetaSixUnit = 1 by
            simpa [← pow_two] using thetaSixUnit_pow_two]
          rw [← pow_add]
          simp
        _ = sixWeylXUnit ^ (j - i).val := by
          rw [sixWeylXUnit_pow_zmod_sub]

def d6MatrixHom : D6 →* SixMatrixˣ where
  toFun := d6MatrixMap
  map_one' := by
    change d6MatrixMap (.r 0) = 1
    simp [d6MatrixMap]
  map_mul' := d6MatrixMap_mul

def sixStateDihedralSubgroup : Subgroup SixMatrixˣ := d6MatrixHom.range

def sixStateGeneratorClosure : Subgroup SixMatrixˣ :=
  Subgroup.closure ({sixWeylXUnit, thetaSixUnit} : Set SixMatrixˣ)

private theorem sixWeylXUnit_pow_eq_iff (i j : ZMod 6)
    (h : sixWeylXUnit ^ i.val = sixWeylXUnit ^ j.val) : i = j := by
  have hp : i.val % orderOf sixWeylXUnit =
      j.val % orderOf sixWeylXUnit :=
    (pow_inj_mod (x := sixWeylXUnit)).mp h
  rw [sixWeylXUnit_order] at hp
  have hi : i.val % 6 = i.val := Nat.mod_eq_of_lt i.isLt
  have hj : j.val % 6 = j.val := Nat.mod_eq_of_lt j.isLt
  apply ZMod.val_injective 6
  simpa [hi, hj] using hp

theorem d6MatrixHom_injective : Function.Injective d6MatrixHom := by
  intro a b h
  cases a with
  | r i =>
    cases b with
    | r j =>
      exact congrArg DihedralGroup.r (sixWeylXUnit_pow_eq_iff i j h)
    | sr j =>
      have hcomm : thetaSixUnit * sixWeylXUnit =
          sixWeylXUnit * thetaSixUnit := by
        have ht : thetaSixUnit = sixWeylXUnit ^ i.val *
            (sixWeylXUnit ^ j.val)⁻¹ := by
          change sixWeylXUnit ^ i.val =
            thetaSixUnit * sixWeylXUnit ^ j.val at h
          calc
            thetaSixUnit = (thetaSixUnit * sixWeylXUnit ^ j.val) *
                (sixWeylXUnit ^ j.val)⁻¹ := by group
            _ = sixWeylXUnit ^ i.val *
                (sixWeylXUnit ^ j.val)⁻¹ := by rw [h]
        rw [ht]
        group
      exact False.elim (thetaSixUnit_not_commute_sixWeylXUnit hcomm)
  | sr i =>
    cases b with
    | r j =>
      have hcomm : thetaSixUnit * sixWeylXUnit =
          sixWeylXUnit * thetaSixUnit := by
        have ht : thetaSixUnit = sixWeylXUnit ^ j.val *
            (sixWeylXUnit ^ i.val)⁻¹ := by
          change thetaSixUnit * sixWeylXUnit ^ i.val =
            sixWeylXUnit ^ j.val at h
          calc
            thetaSixUnit = (thetaSixUnit * sixWeylXUnit ^ i.val) *
                (sixWeylXUnit ^ i.val)⁻¹ := by group
            _ = sixWeylXUnit ^ j.val *
                (sixWeylXUnit ^ i.val)⁻¹ := by rw [h]
        rw [ht]
        group
      exact False.elim (thetaSixUnit_not_commute_sixWeylXUnit hcomm)
    | sr j =>
      have h' : sixWeylXUnit ^ i.val = sixWeylXUnit ^ j.val := by
        change thetaSixUnit * sixWeylXUnit ^ i.val =
            thetaSixUnit * sixWeylXUnit ^ j.val at h
        exact mul_left_cancel h
      exact congrArg DihedralGroup.sr (sixWeylXUnit_pow_eq_iff i j h')

def d6MatrixRangeHom : D6 →* sixStateDihedralSubgroup :=
  d6MatrixHom.codRestrict _ (fun g => ⟨g, rfl⟩)

theorem d6MatrixRangeHom_injective :
    Function.Injective d6MatrixRangeHom := by
  intro a b h
  apply d6MatrixHom_injective
  exact congrArg Subtype.val h

def d6MatrixRangeEquiv : D6 ≃* sixStateDihedralSubgroup :=
  MulEquiv.ofBijective d6MatrixRangeHom ⟨
    d6MatrixRangeHom_injective,
    fun y => by
      rcases y.property with ⟨g, hg⟩
      refine ⟨g, ?_⟩
      apply Subtype.ext
      exact hg⟩

theorem d6MatrixHom_range_eq_generatorClosure :
    sixStateDihedralSubgroup = sixStateGeneratorClosure := by
  apply le_antisymm
  · rintro y ⟨g, rfl⟩
    have hX : sixWeylXUnit ∈ sixStateGeneratorClosure :=
      Subgroup.subset_closure (by simp [sixStateGeneratorClosure])
    have hT : thetaSixUnit ∈ sixStateGeneratorClosure :=
      Subgroup.subset_closure (by simp [sixStateGeneratorClosure])
    cases g with
    | r i =>
      exact sixStateGeneratorClosure.pow_mem hX i.val
    | sr i =>
      exact sixStateGeneratorClosure.mul_mem hT
        (sixStateGeneratorClosure.pow_mem hX i.val)
  · refine (Subgroup.closure_le _).2 ?_
    intro y hy
    have hy' : y = sixWeylXUnit ∨ y = thetaSixUnit := by
      simpa using hy
    rcases hy' with rfl | rfl
    · refine ⟨.r 1, ?_⟩
      change sixWeylXUnit ^ (1 : ZMod 6).val = sixWeylXUnit
      have hv : (1 : ZMod 6).val = 1 := by decide
      rw [hv]
      simp
    · refine ⟨.sr 0, ?_⟩
      change thetaSixUnit * sixWeylXUnit ^ (0 : ZMod 6).val =
        thetaSixUnit
      have hv : (0 : ZMod 6).val = 0 := by decide
      rw [hv]
      simp

def d6MatrixGeneratorClosureEquiv : D6 ≃* sixStateGeneratorClosure :=
  d6MatrixRangeEquiv.trans
    (MulEquiv.subgroupCongr d6MatrixHom_range_eq_generatorClosure)

end
end InfoGeometry.Canonical.SixStateD6C2S3
