-- tools/macaulay2/cft_primary.m2

-- Define the base ring with scalar Delta
R = QQ[Delta];

-- Define the Weyl algebra W = R<z, Dz> where [Dz, z] = 1, i.e., Dz * z = z * Dz + 1
W = R[z, Dz, WeylAlgebra => {z=>Dz}];

-- We want to model the field V = z^{-Delta} as a cyclic D-module.
-- By the product rule, Dz(z^{-Delta}) = -Delta * z^{-Delta - 1}
-- So multiplying by z gives: z * Dz(z^{-Delta}) = -Delta * z^{-Delta}
-- Therefore, (z*Dz + Delta) * V = 0.
-- We can define the D-module M = W / I where I is the left ideal generated by z*Dz + Delta.
I = ideal(z*Dz + Delta);
M = W^1 / I;

-- Let V be the generator of this module, corresponding to z^{-Delta}.
V = M_{0};

-- The Virasoro operator L_0 in the Witt algebra representation is -z*Dz.
L0 = -z*Dz;

-- Apply L0 natively to the algebraic field expansion V
L0V = L0 * V;

-- We want to prove that L0 * V factors out exactly the scalar Delta.
expected = Delta * V;

-- Prove mathematically by checking equality in the module
if L0V == expected then (
    print("Success: L_0(V) = Delta * V");
) else (
    print("Error: L_0(V) != Delta * V");
    print("L0V = ", L0V);
    print("expected = ", expected);
    exit(1);
);
