-- tools/macaulay2/mobius_poles_dmodule.m2
-- Formalizes the D-module corresponding to the poles of the Möbius transformation.
-- The transformation is f(z) = (az+b)/(cz+d).
-- The pole in the source is zInfty = -d/c.
-- The limit at infinity (pole of the inverse) is ZInfty = a/c.

needsPackage "Dmodules"

-- Define the parameter field K = QQ(a,b,c,d)
K = frac(QQ[a,b,c,d])

-- Define the Weyl algebra W = K[z, Dz]
W = K[z, Dz, WeylAlgebra => {z=>Dz}]

-- Define the poles
zInfty = -d/c
ZInfty = a/c

-- The singularities are at z = zInfty and z = ZInfty.
-- The corresponding D-module for a function with simple poles at these points
-- (e.g., u = 1/((z - zInfty)*(z - ZInfty))) is generated by the annihilator.
-- Let P(z) = (z - zInfty)*(z - ZInfty).
P = (z - zInfty)*(z - ZInfty)

-- Differentiating u = 1/P gives Dz u = -P'/P^2, so P Dz u = -P' u
-- Therefore, the generator of the D-module ideal is P*Dz + P'
dP = diff(z, P)
I = ideal(P*Dz + dP)

print "--- D-module ideal I ---"
print I

-- Compute the characteristic variety / characteristic ideal
-- It should be the zero section \xi = 0 and the fibers over the poles.
C = charIdeal I

print "--- Characteristic Ideal ---"
print C

-- Let's also compute the holonomic rank
r = holonomicRank I
print "--- Holonomic Rank ---"
print r

exit()
