-- Koroteev-Zeitlin 3D Mirror Symmetry Macaulay2 Verification
-- Hilbert scheme of points and ADHM construction

print "=== 1. Hilbert scheme of 2 points on C^2 ==="
-- ADHM data for k=2, N=1 (Hilb^2[C^2])
-- B1, B2: 2x2 matrices
-- I: 2x1 matrix (vector)
-- J: 1x2 matrix (covector)
-- Moment map: [B1, B2] + IJ = 0

-- To compute the dimension we'll create the polynomial ring for the entries
-- B1 = (b1_ij), B2 = (b2_ij), I = (i_k), J = (j_k)
R = QQ[b1_11, b1_12, b1_21, b1_22,
       b2_11, b2_12, b2_21, b2_22,
       i_1, i_2, j_1, j_2]

B1 = matrix {{b1_11, b1_12}, {b1_21, b1_22}}
B2 = matrix {{b2_11, b2_12}, {b2_21, b2_22}}
I_mat = matrix {{i_1}, {i_2}}
J_mat = matrix {{j_1, j_2}}

-- Commutator [B1, B2]
Comm = B1*B2 - B2*B1

-- IJ
IJ = I_mat * J_mat

-- Moment map equations
mu = Comm + IJ

-- The ideal generated by the moment map equations
eqs = flatten entries mu
I_mu = ideal eqs

print "Moment map ideal generated."

-- Compute the dimension of the scheme cut out by the moment map
-- Note: the actual Hilb^k[C^2] is the GIT quotient by GL(2).
-- Dim of representation space = 2k^2 + 2kN = 2(4) + 2(2) = 12
-- Moment map takes values in sl(k) dual, so we impose k^2 = 4 equations.
-- Then quotient by GL(k) (dim k^2 = 4).
-- Total expected dimension: 12 - 4 - 4 = 4 = 2Nk = 2*1*2 = 4.

dim_mu = dim I_mu
print("Dimension of mu^-1(0): " | toString(dim_mu))
-- Should be 12 - 4 + 1 = 9  (since trace(mu) = 0 is automatic, only 3 independent eqs)
if dim_mu == 9 then
    print "  [PASS] Moment map level set dimension is correct (9)."
else
    print "  [FAIL] Moment map level set dimension incorrect."
end if

print "\n=== 2. Quiver Variety Dimension ==="
-- N = 1, k = 2
N_val = 1
k_val = 2
dim_expected = 2 * N_val * k_val
dim_actual = dim_mu - (k_val^2) + 1 -- subtracting PGL(k)
if dim_actual == dim_expected then
    print "  [PASS] GIT quotient dimension is 2Nk = 4."
else
    print "  [FAIL] GIT quotient dimension incorrect."
end if

print "\n=== 3. 3D Mirror Symmetry ==="
print "M(N,k) mirror is M(k,N)."
-- If we swap N=1, k=2 -> N=2, k=1
N2 = 2
k2 = 1
dim2 = 2 * N2 * k2
if dim_actual == dim2 then
    print "  [PASS] Dimension is preserved under mirror symmetry: dim M(1,2) = dim M(2,1) = 4."
else
    print "  [FAIL] Dimension not preserved."
end if

print "\n=== All tests completed ==="
