        = (-S.uMinus X) * S.chiralGrading := by rw [S.chiralGrading_mul_uMinus X]
    _ = -S.uMinus X := by rw [neg_mul, S.uMinus_mul_chiralGrading X]

end ProjectorSplit

/--
Bounded Drazin/Moore--Penrose horizon surrogate.

`PD/P0` are represented by `split.P/split.P0`; `PR` and `PL` are metric
range/domain projectors.  The anomaly laws are explicit equations, not Type III
claims.
-/
@[rep_depth operator]
structure DrazinMPHorizonDatum (A : Type*) [Ring A] where
  split : ProjectorSplit A
  PR : A
  PL : A
  PR_idem : PR * PR = PR
  PL_idem : PL * PL = PL
  chiR : A
  chiL : A
  chiR_True : chiR = commutator split.P PR
  chiL_True : chiL = commutator split.P PL
  Q : A
  Q_True : Q = chiR - chiL

namespace DrazinMPHorizonDatum

variable {A : Type*} [Ring A]
variable (H : DrazinMPHorizonDatum A)

/-- Right/range anomaly as light-cone off-diagonal mismatch of `PR`. -/
@[rep_depth operator]
theorem chiR_eq_uPlus_sub_uMinus :
    H.chiR = H.split.uPlus H.PR - H.split.uMinus H.PR := by
  rw [H.chiR_True]
  exact H.split.commutator_P_eq_uPlus_sub_uMinus H.PR

/-- Left/domain anomaly as light-cone off-diagonal mismatch of `PL`. -/
@[rep_depth operator]
theorem chiL_eq_uPlus_sub_uMinus :
    H.chiL = H.split.uPlus H.PL - H.split.uMinus H.PL := by
  rw [H.chiL_True]
  exact H.split.commutator_P_eq_uPlus_sub_uMinus H.PL

/-- The supercharge is the net light-cone mismatch current. -/
@[rep_depth operator]
theorem Q_eq_net_lightcone_mismatch :
    H.Q =
      (H.split.uPlus H.PR - H.split.uMinus H.PR)
        - (H.split.uPlus H.PL - H.split.uMinus H.PL) := by
  rw [H.Q_True, H.chiR_eq_uPlus_sub_uMinus, H.chiL_eq_uPlus_sub_uMinus]

end DrazinMPHorizonDatum

end InfoGeometry.Canonical.DrazinLightConeDictionary

-- [STITCHER: MISSING OVERLAP] --
import InfoGeometry.Meta.Architecture
import Mathlib

/-!
# InfoGeometry.Canonical.DrazinLightConeDictionary

Generic ring-level Drazin/light-cone dictionary.

This file is deliberately independent of Type III analytic claims.  It proves
the finite/bounded algebraic kernel used by the certified inverse-kernel lane:

* a projector split `P + P₀ = 1`;
* off-diagonal arrows `u⁺(X) = P X P₀` and `u⁻(X) = P₀ X P`;
* commutator with `P` is the difference of these arrows;
* same-direction arrow products vanish from projector orthogonality.

Concrete Drazin/Moore--Penrose owner data remain in `CertifiedInverseKernel`
and `DrazinSupercharge`.  Type III realization, if any, is a separate analytic
witness and is not asserted here.
-/

namespace InfoGeometry.Canonical.DrazinLightConeDictionary

/-- Ring commutator. -/
@[rep_depth operator]
def commutator {A : Type*} [Ring A] (X Y : A) : A :=
  X * Y - Y * X

/--
A two-projector split `P + P₀ = 1`.

This is the abstract algebraic substrate of a regular/defect split.
-/
@[rep_depth operator]
structure ProjectorSplit (A : Type*) [Ring A] where
  P : A
  P0 : A
  P_idem : P * P = P
  P0_idem : P0 * P0 = P0
  P_add_P0 : P + P0 = 1
  P_mul_P0 : P * P0 = 0
  P0_mul_P : P0 * P = 0

namespace ProjectorSplit

variable {A : Type*} [Ring A]
variable (S : ProjectorSplit A)

/-- Off-diagonal arrow from defect sector to regular sector. -/
@[rep_depth operator]
def uPlus (X : A) : A :=
  S.P * X * S.P0

/-- Off-diagonal arrow from regular sector to defect sector. -/
@[rep_depth operator]
def uMinus (X : A) : A :=
  S.P0 * X * S.P

/-- Chiral Hodge grading attached to the projector split: `Γ = P - P₀`. -/
@[rep_depth operator]
def chiralGrading : A :=
  S.P - S.P0

/-- Cartan derivation / adjoint action generated by a chosen element. -/
@[rep_depth operator]
def cartanAdjoint (H X : A) : A :=
  H * X - X * H

/-- The chiral grading is a square-one involution. -/
@[rep_depth operator]
theorem chiralGrading_sq_one :
    S.chiralGrading * S.chiralGrading = (1 : A) := by
  unfold chiralGrading
  calc
    (S.P - S.P0) * (S.P - S.P0) = S.P + S.P0 := by
      noncomm_ring [S.P_idem, S.P0_idem, S.P_mul_P0, S.P0_mul_P]
    _ = 1 := S.P_add_P0

/--
Commutator with the regular projector is exactly the difference of the two
off-diagonal light-cone arrows.
-/
@[rep_depth operator]
theorem commutator_P_eq_uPlus_sub_uMinus (X : A) :
    commutator S.P X = S.uPlus X - S.uMinus X := by
  unfold commutator uPlus uMinus
  calc
    S.P * X - X * S.P
        = S.P * X * 1 - 1 * X * S.P := by
            simp
    _ = S.P * X * (S.P + S.P0) - (S.P + S.P0) * X * S.P := by
            rw [S.P_add_P0]
    _ = (S.P * X * S.P + S.P * X * S.P0)
          - (S.P * X * S.P + S.P0 * X * S.P) := by
            noncomm_ring
    _ = S.P * X * S.P0 - S.P0 * X * S.P := by
            noncomm_ring

/-- Same-arrow `u⁺` composition vanishes. -/
@[rep_depth operator]
theorem uPlus_mul_uPlus_eq_zero (X Y : A) :
    S.uPlus X * S.uPlus Y = 0 := by
  unfold uPlus
  calc
    (S.P * X * S.P0) * (S.P * Y * S.P0)
        = S.P * X * (S.P0 * S.P) * Y * S.P0 := by
            noncomm_ring
    _ = 0 := by
            rw [S.P0_mul_P]
            simp

/-- Same-arrow `u⁻` composition vanishes. -/
@[rep_depth operator]
theorem uMinus_mul_uMinus_eq_zero (X Y : A) :
    S.uMinus X * S.uMinus Y = 0 := by
  unfold uMinus
  calc
    (S.P0 * X * S.P) * (S.P0 * Y * S.P)
        = S.P0 * X * (S.P * S.P0) * Y * S.P := by
            noncomm_ring
    _ = 0 := by
            rw [S.P_mul_P0]
            simp

/-- The chiral grading acts by `+1` on `u⁺` from the left. -/
@[rep_depth operator]
theorem chiralGrading_mul_uPlus (X : A) :
    S.chiralGrading * S.uPlus X = S.uPlus X := by
  unfold chiralGrading uPlus
  have hP : S.P * (S.P * X * S.P0) = S.P * X * S.P0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P0) S.P_idem
  have hP0 : S.P0 * (S.P * X * S.P0) = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P0) S.P0_mul_P
  simp [sub_mul, hP, hP0]

/-- The chiral grading acts by `-1` on `u⁺` from the right. -/
@[rep_depth operator]
theorem uPlus_mul_chiralGrading (X : A) :
    S.uPlus X * S.chiralGrading = -S.uPlus X := by
  unfold chiralGrading uPlus
  have hP : (S.P * X * S.P0) * S.P = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P * X * Z) S.P0_mul_P
  have hP0 : (S.P * X * S.P0) * S.P0 = S.P * X * S.P0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P * X * Z) S.P0_idem
  simp [mul_sub, hP, hP0]

/-- The chiral grading acts by `-1` on `u⁻` from the left. -/
@[rep_depth operator]
theorem chiralGrading_mul_uMinus (X : A) :
    S.chiralGrading * S.uMinus X = -S.uMinus X := by
  unfold chiralGrading uMinus
  have hP : S.P * (S.P0 * X * S.P) = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P) S.P_mul_P0
  have hP0 : S.P0 * (S.P0 * X * S.P) = S.P0 * X * S.P := by
    simpa [mul_assoc] using congrArg (fun Z : A => Z * X * S.P) S.P0_idem
  simp [sub_mul, hP, hP0]

/-- The chiral grading acts by `+1` on `u⁻` from the right. -/
@[rep_depth operator]
theorem uMinus_mul_chiralGrading (X : A) :
    S.uMinus X * S.chiralGrading = S.uMinus X := by
  unfold chiralGrading uMinus
  have hP : (S.P0 * X * S.P) * S.P = S.P0 * X * S.P := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P0 * X * Z) S.P_idem
  have hP0 : (S.P0 * X * S.P) * S.P0 = 0 := by
    simpa [mul_assoc] using congrArg (fun Z : A => S.P0 * X * Z) S.P_mul_P0
  simp [mul_sub, hP, hP0]

/-- The `u⁺ = P X P₀` arrow has Cartan weight `+2` for `Γ = P - P₀`. -/
@[rep_depth operator]
theorem cartanAdjoint_chiralGrading_uPlus (X : A) :
    cartanAdjoint S.chiralGrading (S.uPlus X) = S.uPlus X + S.uPlus X := by
  unfold cartanAdjoint
  rw [S.chiralGrading_mul_uPlus X, S.uPlus_mul_chiralGrading X]
  abel

/-- The `u⁻ = P₀ X P` arrow has Cartan weight `-2` for `Γ = P - P₀`. -/
@[rep_depth operator]
theorem cartanAdjoint_chiralGrading_uMinus (X : A) :
    cartanAdjoint S.chiralGrading (S.uMinus X) = -(S.uMinus X + S.uMinus X) := by
  unfold cartanAdjoint
  rw [S.chiralGrading_mul_uMinus X, S.uMinus_mul_chiralGrading X]
  abel

/-- The `u⁺` arrow is chiral-odd under conjugation by `Γ`. -/
@[rep_depth operator]
theorem chiralGrading_mul_uPlus_mul_chiralGrading (X : A) :
    S.chiralGrading * S.uPlus X * S.chiralGrading = -S.uPlus X := by
  calc
    S.chiralGrading * S.uPlus X * S.chiralGrading
        = S.uPlus X * S.chiralGrading := by rw [S.chiralGrading_mul_uPlus X]
    _ = -S.uPlus X := S.uPlus_mul_chiralGrading X

/-- The `u⁻` arrow is chiral-odd under conjugation by `Γ`. -/
@[rep_depth operator]
theorem chiralGrading_mul_uMinus_mul_chiralGrading (X : A) :
    S.chiralGrading * S.uMinus X * S.chiralGrading = -S.uMinus X := by
  calc
    S.chiralGrading * S.uMinus X * S.chiralGrading
        = (-S.uMinus X) * S.chiralGrading := by rw [S.chiralGrading_mul_uMinus X]
    _ = -S.uMinus X := by rw [neg_mul, S.uMinus_mul_chiralGrading X]

end ProjectorSplit

/--
Bounded Drazin/Moore--Penrose horizon surrogate.

`PD/P0` are represented by `split.P/split.P0`; `PR` and `PL` are metric
range/domain projectors.  The anomaly laws are explicit equations, not Type III
claims.
-/
@[rep_depth operator]
structure DrazinMPHorizonDatum (A : Type*) [Ring A] where
  split : ProjectorSplit A
  PR : A
  PL : A
  PR_idem : PR * PR = PR
  PL_idem : PL * PL = PL
  chiR : A
  chiL : A
  chiR_True : chiR = commutator split.P PR
  chiL_True : chiL = commutator split.P PL
  Q : A
  Q_True : Q = chiR - chiL

namespace DrazinMPHorizonDatum

variable {A : Type*} [Ring A]
variable (H : DrazinMPHorizonDatum A)

/-- Right/range anomaly as light-cone off-diagonal mismatch of `PR`. -/
@[rep_depth operator]
theorem chiR_eq_uPlus_sub_uMinus :
    H.chiR = H.split.uPlus H.PR - H.split.uMinus H.PR := by
  rw [H.chiR_True]
  exact H.split.commutator_P_eq_uPlus_sub_uMinus H.PR

/-- Left/domain anomaly as light-cone off-diagonal mismatch of `PL`. -/
@[rep_depth operator]
theorem chiL_eq_uPlus_sub_uMinus :
    H.chiL = H.split.uPlus H.PL - H.split.uMinus H.PL := by
  rw [H.chiL_True]
  exact H.split.commutator_P_eq_uPlus_sub_uMinus H.PL

/-- The supercharge is the net light-cone mismatch current. -/
@[rep_depth operator]
theorem Q_eq_net_lightcone_mismatch :
    H.Q =
      (H.split.uPlus H.PR - H.split.uMinus H.PR)
        - (H.split.uPlus H.PL - H.split.uMinus H.PL) := by
  rw [H.Q_True, H.chiR_eq_uPlus_sub_uMinus, H.chiL_eq_uPlus_sub_uMinus]

end DrazinMPHorizonDatum

end InfoGeometry.Canonical.DrazinLightConeDictionary
