#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


PLACEHOLDER_PATTERNS = (
    (re.compile(r"\.\.\."), "signature still contains ellipsis placeholders"),
    (
        re.compile(r"local hypotheses specialized to the target declaration"),
        "signature still contains placeholder hypotheses",
    ),
    (
        re.compile(r"direct transport / invariance / closure statement feeding the frontier"),
        "signature still contains placeholder goal text",
    ),
    (re.compile(r"^theorem\s+auto_", re.M), "signature is still the autogenerated scaffold"),
    (
        re.compile(r"constructive replacement target generated from the tracked debt packet"),
        "signature is still a generated debt-replacement scaffold",
    ),
    (re.compile(r":=\s*by\s*$", re.S), "signature ends with an empty `:= by` body"),
)


MATERIALIZATION_BANNER = "/-- External proof-driver materialization of the selected candidate sketch. -/\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Conservative external proof driver for optimization-cycle quarantine runs. "
            "It reads the context JSON, materializes only concrete theorem sketches, "
            "and otherwise emits a report explaining why no mutation was attempted."
        )
    )
    parser.add_argument("--context", required=True, help="Path to the proof-attempt context JSON.")
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def placeholder_reasons(signature_sketch: str) -> list[str]:
    reasons: list[str] = []
    for pattern, message in PLACEHOLDER_PATTERNS:
        if pattern.search(signature_sketch):
            reasons.append(message)
    return reasons


def selected_sketch(candidate: dict[str, Any]) -> tuple[str, str, list[str]]:
    signature_sketch = str(candidate.get("signature_sketch", "")).strip()
    materialization_sketch = str(candidate.get("materialization_sketch", "")).strip()
    review_verdict = str(candidate.get("review_verdict", "")).strip().lower()
    quarantine_recommendation = str(candidate.get("quarantine_recommendation", "")).strip().lower()

    reasons: list[str] = []
    if materialization_sketch:
        if quarantine_recommendation != "yes":
            reasons.append("candidate packet does not explicitly approve quarantine materialization")
        if review_verdict == "reject":
            reasons.append("candidate review verdict is reject")
        return materialization_sketch, "materialization_sketch", reasons
    if not signature_sketch:
        reasons.append("context is missing a candidate signature sketch")
    return signature_sketch, "signature_sketch", reasons


def insert_before_namespace_end(file_text: str, insertion: str) -> str:
    marker = "\nend InfoGeometry.Unstable.AutoOptCycle\n"
    if marker not in file_text:
        raise SystemExit("quarantine file does not end with `end InfoGeometry.Unstable.AutoOptCycle`")
    return file_text.replace(marker, f"\n{insertion.rstrip()}\n\nend InfoGeometry.Unstable.AutoOptCycle\n", 1)


def materialize_signature(quarantine_path: Path, signature_sketch: str) -> bool:
    existing = quarantine_path.read_text(encoding="utf-8")
    inserted_block = MATERIALIZATION_BANNER + signature_sketch
    if inserted_block in existing:
        return False
    updated = insert_before_namespace_end(existing, inserted_block)
    quarantine_path.write_text(updated, encoding="utf-8")
    return True


def write_report(
    report_path: Path,
    payload: dict[str, Any],
    verdict: str,
    reasons: list[str],
    materialized: bool,
    sketch_source: str,
) -> None:
    chosen = payload.get("chosenFrontier", {})
    candidate = payload.get("selectedCandidate", {})
    lines = [
        "# Proof Driver Report",
        "",
        f"- run id: `{payload.get('runId', '')}`",
        f"- attempt: `{payload.get('attempt', '')}`",
        f"- verdict: `{verdict}`",
        f"- materialized: `{materialized}`",
        f"- quarantine file: `{payload.get('quarantineFile', '')}`",
        f"- candidate: `{candidate.get('name', '')}`",
        f"- frontier target: `{', '.join(chosen.get('primaryProduces', []))}`",
        f"- sketch source: `{sketch_source}`",
        f"- review verdict: `{candidate.get('review_verdict', '')}`",
        f"- quarantine recommendation: `{candidate.get('quarantine_recommendation', '')}`",
        "",
        "## Reasons",
    ]
    if reasons:
        for reason in reasons:
            lines.append(f"- {reason}")
    else:
        lines.append("- none")
    lines.append("")
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    context_path = Path(args.context).resolve()
    payload = load_json(context_path)

    candidate = payload.get("selectedCandidate", {})
    quarantine_file = payload.get("quarantineFile")
    if not quarantine_file:
        raise SystemExit("context is missing `quarantineFile`")
    quarantine_path = Path(str(quarantine_file)).resolve()
    report_path = context_path.with_suffix(".report.md")

    sketch, sketch_source, reasons = selected_sketch(candidate)
    reasons.extend(placeholder_reasons(sketch))

    verdict = "defer"
    materialized = False
    if not reasons:
        materialized = materialize_signature(quarantine_path, sketch)
        verdict = "materialized" if materialized else "already-present"

    write_report(report_path, payload, verdict, reasons, materialized, sketch_source)
    print(f"[proof-driver] report: {report_path}")
    print(f"[proof-driver] verdict: {verdict}")
    if reasons:
        print(f"[proof-driver] reasons: {len(reasons)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())