#!/usr/bin/env python3
"""Heuristic theorem vacuity triage — Layer B of the vacuity enforcement system.

Reads the DAG-exported declaration and edge JSONs and produces a per-theorem
rule-based vacuity classification. Combined with the Lean-side linter (Layer A,
``Vacuity.lean``) and the CI policy gate (Layer C, ``check_vacuity_policy.py``),
this gives a three-layer vacuity enforcement system.

Violation classes produced:

  V0  syntactic vacuity — rfl-like proof screen
  V1  public wrapper inflation — proof forwards to single prior theorem
  V2  dead public theorem — zero reverse edges, no capstone annotation
  V3  statement redundancy — (placeholder, not yet computed)
  V4  bridge infrastructure promoted — infrastructure in bridge file
  V5  unjustified canonicality — (requires NLP, placeholder)
  V6  quotient fraud — (requires semantic analysis, placeholder)

Usage::

    python3 tools/theorem_significance.py \\
        [--decls FILE] [--edges FILE] \\
        [--out FILE] [--md FILE] \\
        [--strict-paths PREFIX ...] \\
        [--bridge-hints WORD ...]

Output:  JSON array of classified declarations and a Markdown summary report.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent))

from pathing import repo_root

# ─── data model ───────────────────────────────────────────────

@dataclass
class DeclInfo:
    name: str
    kind: str              # theorem | def | inductive | constructor | …
    file: str | None = None
    module: str | None = None
    line: int = 0
    doc: str = ""
    attrs: list[str] = field(default_factory=list)

@dataclass
class GraphStats:
    reverse_type: int = 0   # how many declarations reference this in type position
    reverse_value: int = 0  # how many declarations reference this in value (proof) position
    forward_type: int = 0   # how many declarations this references in type position
    forward_value: int = 0  # how many declarations this references in value position
    is_sink: bool = False   # no forward value edges
    depth: int = 0          # longest reverse chain (computed lazily)

@dataclass
class ProofShapeInfo:
    """Proof-shape classification inferred from the edge graph (no Lean elaboration)."""
    forward_value_targets: list[str] = field(default_factory=list)
    forward_theorem_targets: list[str] = field(default_factory=list)
    n_forward_value: int = 0
    n_forward_theorem: int = 0

    @property
    def is_exact_forward(self) -> bool:
        return self.n_forward_value == 1 and self.n_forward_theorem == 1

    @property
    def exact_forward_target(self) -> str | None:
        if not self.is_exact_forward or len(self.forward_theorem_targets) != 1:
            return None
        return self.forward_theorem_targets[0]

    @property
    def is_rfl_like(self) -> bool:
        return self.n_forward_value == 0

@dataclass
class ScoredDecl:
    name: str
    kind: str
    file: str | None
    module: str | None
    attrs: list[str]
    graph: GraphStats
    proof: ProofShapeInfo
    tags: list[str] = field(default_factory=list)
    violations: list[tuple[str, str]] = field(default_factory=list)  # (level, code)

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "kind": self.kind,
            "file": self.file,
            "module": self.module,
            "attrs": self.attrs,
            "reverse_type": self.graph.reverse_type,
            "reverse_value": self.graph.reverse_value,
            "forward_type": self.graph.forward_type,
            "forward_value": self.graph.forward_value,
            "is_sink": self.graph.is_sink,
            "n_forward_value": self.proof.n_forward_value,
            "n_forward_theorem": self.proof.n_forward_theorem,
            "tags": self.tags,
            "violations": [{"level": v[0], "code": v[1]} for v in self.violations],
        }


# ─── classification engine ────────────────────────────────────

BRIDGE_HINTS_DEFAULT = ["Bridge", "Lift", "Rosetta"]
STRICT_PATHS_DEFAULT = [
    "lean/InfoGeometry/Canonical/",
    "lean/InfoGeometry/Quantum/",
]

# Tags that exempt from vacuity checks.  Must match Lean attribute names.
EXEMPT_ATTRS = {"infrastructure", "capstone", "terminal", "expository"}

# Name suffixes that identify Lean-generated theorems (inductive eliminators,
# injection lemmas, sizeof specs, etc.).  These are auto-generated by the
# kernel or deriving handlers and should not receive vacuity violations.
_GENERATED_SUFFIXES = (
    ".rec", ".recOn", ".casesOn", ".below", ".brecOn", ".noConfusion",
    ".noConfusionType", ".sizeOf_spec", ".mk.inj", ".mk.injEq",
    ".eq_def", ".eta",
    ".eq_1", ".eq_2", ".eq_3",
    ".congr_simp",
    ".ofNat_ctorIdx",
)
# Name fragments that identify generated families regardless of position.
_GENERATED_FRAGMENTS = (
    ".match_", ".proof_", "._uniq.",
)


def _is_generated(name: str) -> bool:
    """Return True if the declaration name matches a Lean auto-generated pattern."""
    if any(name.endswith(s) for s in _GENERATED_SUFFIXES):
        return True
    return any(f in name for f in _GENERATED_FRAGMENTS)


def classify_tags(decl: DeclInfo, graph: GraphStats, proof: ProofShapeInfo) -> list[str]:
    """Assign semantic tags based on graph role and proof shape."""
    tags: list[str] = []

    # Dead candidate: no reverse edges at all
    if graph.reverse_type == 0 and graph.reverse_value == 0:
        tags.append("dead-candidate")

    # Statement-bearing: has reverse type consumers
    if graph.reverse_type > 0:
        tags.append("statement-bearing")

    # Proof-infrastructure: used in proofs but not in statements
    if graph.reverse_value > 0 and graph.reverse_type == 0:
        tags.append("proof-infrastructure")

    # Wrapper candidate: exact forwarding proof
    if proof.is_exact_forward:
        tags.append("wrapper-candidate")

    # rfl-like: proof body references zero value edges (trivial)
    if proof.is_rfl_like:
        tags.append("rfl-like")

    # Capstone candidate: sink with significant dependency cone
    if graph.is_sink and (graph.forward_value + graph.forward_type) >= 5:
        tags.append("capstone-candidate")

    # High fan-in: many reverse consumers
    if graph.reverse_type + graph.reverse_value >= 10:
        tags.append("high-fan-in")

    return sorted(set(tags))


def is_bridge_file(file_path: str | None, bridge_hints: list[str]) -> bool:
    """Return True when the declaration lives in an explicitly bridge-like file.

    Bridge hints are matched against the file stem only, not directory names,
    to avoid classifying all `Canonical/` or `Core/` files as bridge surfaces.
    """
    if file_path is None:
        return False
    stem = Path(file_path).stem
    return any(hint and hint in stem for hint in bridge_hints)


def compute_violations(
    decl: DeclInfo,
    tags: list[str],
    file_path: str | None,
    bridge_hints: list[str],
    strict_paths: list[str],
) -> list[tuple[str, str]]:
    """Determine violations based on tags and file context."""
    out: list[tuple[str, str]] = []
    if file_path is None:
        return out

    is_bridge = is_bridge_file(file_path, bridge_hints)
    is_strict = any(file_path.startswith(p) for p in strict_paths)

    # V0: syntactic vacuity (rfl-like proof)
    if "rfl-like" in tags:
        level = "warning"
        if is_bridge:
            level = "warning"  # V0 only warns even in bridge files
        out.append((level, "V0/syntactic-vacuity"))

    # V1: public wrapper inflation (exact forwarding proof)
    if "wrapper-candidate" in tags:
        level = "error" if is_bridge else "warning"
        out.append((level, "V1/public-wrapper-inflation"))

    # V2: dead public theorem
    if "dead-candidate" in tags:
        level = "error" if (is_bridge or is_strict) else "warning"
        out.append((level, "V2/dead-public-theorem"))

    # V4: bridge infrastructure promoted (rfl-like or wrapper in bridge file)
    if is_bridge and ("rfl-like" in tags or "wrapper-candidate" in tags):
        if "dead-candidate" not in tags:  # don't double-count with V2
            out.append(("warning", "V4/bridge-infrastructure-promoted"))

    return out


# ─── data loading ─────────────────────────────────────────────

def load_decls(path: Path) -> dict[str, DeclInfo]:
    decls: dict[str, DeclInfo] = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            decls[d["name"]] = DeclInfo(
                name=d["name"],
                kind=d["kind"],
                file=d.get("file"),
                module=d.get("module"),
                line=d.get("line", 0),
                doc=d.get("doc", ""),
                attrs=list(d.get("attrs", [])),
            )
    return decls


def load_edges(path: Path) -> tuple[
    dict[str, list[tuple[str, str]]],   # forward: src -> [(dst, kind)]
    dict[str, list[tuple[str, str]]],   # reverse: dst -> [(src, kind)]
]:
    forward: dict[str, list[tuple[str, str]]] = defaultdict(list)
    reverse: dict[str, list[tuple[str, str]]] = defaultdict(list)
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            e = json.loads(line)
            src, dst, kind = e["src"], e["dst"], e["kind"]
            forward[src].append((dst, kind))
            reverse[dst].append((src, kind))
    return dict(forward), dict(reverse)


# ─── scoring pipeline ─────────────────────────────────────────

def build_graph_stats(
    name: str,
    forward: dict[str, list[tuple[str, str]]],
    reverse: dict[str, list[tuple[str, str]]],
) -> GraphStats:
    fwd = forward.get(name, [])
    rev = reverse.get(name, [])
    gs = GraphStats()
    for _, kind in rev:
        if kind == "type":
            gs.reverse_type += 1
        elif kind == "value":
            gs.reverse_value += 1
    for _, kind in fwd:
        if kind == "type":
            gs.forward_type += 1
        elif kind == "value":
            gs.forward_value += 1
    gs.is_sink = gs.forward_value == 0
    return gs


def build_proof_shape(
    name: str,
    forward: dict[str, list[tuple[str, str]]],
    decls: dict[str, DeclInfo],
) -> ProofShapeInfo:
    fwd = forward.get(name, [])
    value_targets = [dst for dst, kind in fwd if kind == "value"]
    # Filter to only theorem targets (forwarding to a theorem)
    theorem_targets = [t for t in value_targets if t in decls and decls[t].kind == "theorem"]
    return ProofShapeInfo(
        forward_value_targets=value_targets,
        forward_theorem_targets=theorem_targets,
        n_forward_value=len(value_targets),
        n_forward_theorem=len(theorem_targets),
    )


def relative_path(abspath: str | None, root: Path) -> str | None:
    if abspath is None:
        return None
    try:
        return str(Path(abspath).relative_to(root))
    except ValueError:
        return abspath


def score_all(
    decls: dict[str, DeclInfo],
    forward: dict[str, list[tuple[str, str]]],
    reverse: dict[str, list[tuple[str, str]]],
    bridge_hints: list[str],
    strict_paths: list[str],
    root: Path,
) -> list[ScoredDecl]:
    results: list[ScoredDecl] = []
    for name, info in sorted(decls.items()):
        # Only score theorems
        if info.kind != "theorem":
            continue
        graph = build_graph_stats(name, forward, reverse)
        proof = build_proof_shape(name, forward, decls)
        rel_file = relative_path(info.file, root)
        tags = classify_tags(info, graph, proof)
        exempt_attrs = sorted({attr for attr in info.attrs if attr in EXEMPT_ATTRS})
        if exempt_attrs:
            tags = sorted(set(tags + ["role-exempt"] + [f"attr:{attr}" for attr in exempt_attrs]))
        # Auto-generated theorems (eliminators, injection lemmas, etc.)
        # are tagged but exempt from violations — they are not authored proofs.
        if _is_generated(name):
            tags.append("auto-generated")
            violations = []
        elif exempt_attrs:
            violations = []
        else:
            violations = compute_violations(info, tags, rel_file, bridge_hints, strict_paths)
        results.append(ScoredDecl(
            name=name,
            kind=info.kind,
            file=rel_file,
            module=info.module,
            attrs=info.attrs,
            graph=graph,
            proof=proof,
            tags=tags,
            violations=violations,
        ))
    return results


# ─── report generation ────────────────────────────────────────

def generate_json_report(scored: list[ScoredDecl]) -> list[dict]:
    return [s.to_dict() for s in scored]


def generate_md_report(scored: list[ScoredDecl]) -> str:
    lines: list[str] = []
    lines.append("# Theorem Vacuity Triage Report\n")

    # Summary stats
    total = len(scored)
    n_violations = sum(1 for s in scored if s.violations)
    n_errors = sum(1 for s in scored if any(v[0] == "error" for v in s.violations))
    n_warnings = sum(1 for s in scored if any(v[0] == "warning" for v in s.violations) and not any(v[0] == "error" for v in s.violations))
    n_clean = total - n_violations

    lines.append(f"**Theorems scored:** {total}  ")
    lines.append(f"**With violations:** {n_violations} ({n_errors} error, {n_warnings} warning-only)  ")
    lines.append(f"**Clean:** {n_clean}  \n")

    # Tag distribution
    tag_counts: Counter[str] = Counter()
    for s in scored:
        for t in s.tags:
            tag_counts[t] += 1
    lines.append("## Tag Distribution\n")
    lines.append("| Tag | Count |")
    lines.append("|-----|-------|")
    for tag, count in tag_counts.most_common():
        lines.append(f"| `{tag}` | {count} |")
    lines.append("")

    # Violation distribution
    viol_counts: Counter[str] = Counter()
    for s in scored:
        for _, code in s.violations:
            viol_counts[code] += 1
    lines.append("## Violation Distribution\n")
    lines.append("| Violation | Count |")
    lines.append("|-----------|-------|")
    for code, count in viol_counts.most_common():
        lines.append(f"| `{code}` | {count} |")
    lines.append("")

    # Errors (bridge/canonical files)
    errors = [s for s in scored if any(v[0] == "error" for v in s.violations)]
    if errors:
        lines.append("## Errors (require action)\n")
        # Group by file
        by_file: dict[str, list[ScoredDecl]] = defaultdict(list)
        for s in errors:
            by_file[s.file or "(unknown)"].append(s)
        for fpath in sorted(by_file):
            lines.append(f"### `{fpath}`\n")
            for s in by_file[fpath]:
                vcodes = ", ".join(f"`{v[1]}`" for v in s.violations if v[0] == "error")
                lines.append(f"- **`{s.name}`** — {vcodes}")
                if s.proof.exact_forward_target is not None:
                    lines.append(f"  - Forwards to: `{s.proof.exact_forward_target}`")
                lines.append(f"  - Tags: {', '.join(f'`{t}`' for t in s.tags)}")
            lines.append("")

    # Per-file summary (top 20 most-affected files)
    file_violation_count: Counter[str] = Counter()
    for s in scored:
        if s.violations and s.file:
            file_violation_count[s.file] += 1
    if file_violation_count:
        lines.append("## Most-Affected Files (top 20)\n")
        lines.append("| File | Violations |")
        lines.append("|------|------------|")
        for fpath, count in file_violation_count.most_common(20):
            lines.append(f"| `{fpath}` | {count} |")
        lines.append("")

    return "\n".join(lines)


# ─── main ─────────────────────────────────────────────────────

def main() -> None:
    root = repo_root()
    parser = argparse.ArgumentParser(description="Heuristic theorem vacuity triage")
    parser.add_argument("--decls", type=Path, default=root / "artifacts" / "dag" / "index" / "decls.jsonl")
    parser.add_argument("--edges", type=Path, default=root / "artifacts" / "dag" / "index" / "edges.jsonl")
    parser.add_argument("--out", type=Path, default=root / "reports" / "theorem-significance.json")
    parser.add_argument("--md", type=Path, default=root / "reports" / "theorem-significance.md")
    parser.add_argument("--strict-paths", nargs="*", default=STRICT_PATHS_DEFAULT)
    parser.add_argument("--bridge-hints", nargs="*", default=BRIDGE_HINTS_DEFAULT)
    args = parser.parse_args()

    print(f"Loading declarations from {args.decls} ...")
    decls = load_decls(args.decls)
    print(f"  {len(decls)} declarations loaded")

    print(f"Loading edges from {args.edges} ...")
    forward, reverse = load_edges(args.edges)
    n_edges = sum(len(v) for v in forward.values())
    print(f"  {n_edges} edges loaded")

    print("Scoring theorems ...")
    scored = score_all(decls, forward, reverse, args.bridge_hints, args.strict_paths, root)
    print(f"  {len(scored)} theorems scored")

    n_violations = sum(1 for s in scored if s.violations)
    n_errors = sum(1 for s in scored if any(v[0] == "error" for v in s.violations))
    print(f"  {n_violations} with violations ({n_errors} errors)")

    # Write JSON
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(generate_json_report(scored), f, indent=2)
    print(f"JSON report → {args.out}")

    # Write Markdown
    args.md.parent.mkdir(parents=True, exist_ok=True)
    with open(args.md, "w") as f:
        f.write(generate_md_report(scored))
    print(f"Markdown report → {args.md}")


if __name__ == "__main__":
    main()
