import InfoGeometry.Convex.BinaryBarrierCoordinateHessian

#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.interval_barrier_log_cosh

#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_chart_hasDerivAt
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_chart_second_derivative
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_hessian_pullback
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_hessian_coordinate_defect
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_second_order_chain_rule
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_chart_hessian_le_pullback
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.barrier_chart_third_derivative
#print axioms InfoGeometry.Convex.BinaryBarrierCoordinateHessian.transformed_barrier_self_concordance_counterexample
