import Mathlib.Tactic
import InfoGeometry.Algebra.FiniteSpinAlgebra

/-!
# InfoGeometry.Convex.BregmanLegendreProofs

Direct convex-analysis identities in formula form:

* Bregman divergence algebra
* affine pullback invariance
* Fenchel-Young gap specialization
* primal-dual Bregman identity
-/

namespace InfoGeometry.Convex

/-- Bregman divergence generated by `F` and gradient field `dF`. -/
def bregman (F dF : ℝ → ℝ) (x y : ℝ) : ℝ :=
  F x - F y - dF y * (x - y)

@[simp]
theorem bregman_self (F dF : ℝ → ℝ) (x : ℝ) :
    bregman F dF x x = 0 := by
  simp [bregman]

theorem bregman_nonneg_of_firstOrderConvex
    (F dF : ℝ → ℝ)
    (hconv : ∀ x y : ℝ, F x ≥ F y + dF y * (x - y))
    (x y : ℝ) :
    0 ≤ bregman F dF x y := by
  have hxy : F x - (F y + dF y * (x - y)) ≥ 0 := sub_nonneg.mpr (hconv x y)
  simpa [bregman, sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using hxy

theorem bregman_pos_of_firstOrderStrictConvex
    (F dF : ℝ → ℝ)
    (hstrict : ∀ x y : ℝ, x ≠ y → F x > F y + dF y * (x - y))
    {x y : ℝ} (hxy : x ≠ y) :
    0 < bregman F dF x y := by
  have h : F x - (F y + dF y * (x - y)) > 0 := sub_pos.mpr (hstrict x y hxy)
  simpa [bregman, sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using h

theorem bregman_add
    (F G dF dG : ℝ → ℝ) (x y : ℝ) :
    bregman (fun t => F t + G t) (fun t => dF t + dG t) x y
      = bregman F dF x y + bregman G dG x y := by
  unfold bregman
  ring

theorem bregman_smul
    (a : ℝ) (F dF : ℝ → ℝ) (x y : ℝ) :
    bregman (fun t => a * F t) (fun t => a * dF t) x y
      = a * bregman F dF x y := by
  unfold bregman
  ring

/-- Affine action on the line. -/
def affine (a b x : ℝ) : ℝ :=
  a * x + b

theorem affine_comp (a b c d x : ℝ) :
    affine a b (affine c d x) = affine (a * c) (a * d + b) x := by
  unfold affine
  ring

/-- Pullback of a potential along `x ↦ a*x + b`. -/
def affinePullback (F : ℝ → ℝ) (a b : ℝ) : ℝ → ℝ :=
  fun x => F (affine a b x)

/-- Gradient field of the affine pullback (chain rule for affine map). -/
def affinePullbackGrad (dF : ℝ → ℝ) (a b : ℝ) : ℝ → ℝ :=
  fun x => a * dF (affine a b x)

theorem bregman_affine_pullback
    (F dF : ℝ → ℝ) (a b x y : ℝ) :
    bregman (affinePullback F a b) (affinePullbackGrad dF a b) x y =
      bregman F dF (affine a b x) (affine a b y) := by
  unfold bregman affinePullback affinePullbackGrad affine
  ring

/-- Fenchel-Young gap. -/
def fenchelYoungGap (F Fstar : ℝ → ℝ) (x η : ℝ) : ℝ :=
  F x + Fstar η - x * η

theorem fenchelYoungGap_eq_bregman_at_dual
    (F Fstar dF : ℝ → ℝ) (x y : ℝ)
    (hstar : Fstar (dF y) = y * dF y - F y) :
    fenchelYoungGap F Fstar x (dF y) = bregman F dF x y := by
  unfold fenchelYoungGap bregman
  rw [hstar]
  ring

theorem bregman_dual_identity
    (F Fstar dF dFstar : ℝ → ℝ) (x y : ℝ)
    (hstar_x : Fstar (dF x) = x * dF x - F x)
    (hstar_y : Fstar (dF y) = y * dF y - F y)
    (hinv_x : dFstar (dF x) = x) :
    bregman F dF x y = bregman Fstar dFstar (dF y) (dF x) := by
  unfold bregman
  rw [hstar_y, hstar_x, hinv_x]
  ring

end InfoGeometry.Convex

