import Mathlib.Tactic

/-!
# InfoGeometry.Convex.RadialLogBarrier

Radial log-barrier formulas for the trace-normalized Bloch/Poincare ball
coordinate.

This file is deliberately only real-variable convex algebra.  It formalizes
the safe identities behind the slogan:

* trace fixes scale;
* the radial purity coordinate is `s = |r|`;
* the logarithmic radial coordinate is `τ = log s`;
* radial inversion sends `τ` to `-τ`;
* the log barrier `-log (1 - s^2)` generates the dual radial coordinate
  `q = 2s / (1 - s^2)`;
* in `τ` coordinates, the dual coordinate is
  `η = 2 exp(2τ) / (1 - exp(2τ))`.

No density-matrix theorem.
No entropy theorem.
No Type III or weak-limit claim.
-/

noncomputable section

namespace InfoGeometry.Convex.RadialLogBarrier

/-! ## Radial inversion and logarithmic coordinate -/

/-- Radial inversion on positive radial scale. -/
def radialInversion (s : ℝ) : ℝ :=
  s⁻¹

/-- Logarithmic radial coordinate. -/
def radialTau (s : ℝ) : ℝ :=
  Real.log s

/-- Radial inversion is sign flip in logarithmic coordinates. -/
theorem radialTau_inversion
    (s : ℝ) :
    radialTau (radialInversion s) = -radialTau s := by
  rw [radialTau, radialInversion, radialTau, Real.log_inv]

/-- Exponentiating the logarithmic radial coordinate recovers a positive radius. -/
theorem exp_radialTau
    {s : ℝ}
    (hs : 0 < s) :
    Real.exp (radialTau s) = s := by
  simp [radialTau, Real.exp_log hs]

/-! ## Radial log barrier -/

/-- Interior radial log barrier `-log (1 - s^2)`. -/
def radialBarrier (s : ℝ) : ℝ :=
  -Real.log (1 - s ^ (2 : ℕ))

/-- Epsilon-regularized radial log barrier `-log (1 - s^2 + ε)`. -/
def radialBarrierEps (ε s : ℝ) : ℝ :=
  -Real.log (1 - s ^ (2 : ℕ) + ε)

/-- At the unit boundary, the epsilon-regularized radial barrier is `-log ε`. -/
theorem radialBarrierEps_boundary :
    radialBarrierEps ε 1 = -Real.log ε := by
  simp [radialBarrierEps]

/-- Radial Fenchel/Legendre dual coordinate generated by `-log (1 - s^2)`. -/
def radialDualNorm (s : ℝ) : ℝ :=
  2 * s / (1 - s ^ (2 : ℕ))

/--
The radial dual-coordinate equation is equivalent to a quadratic relation.

This is the algebraic form of

`q = 2s / (1 - s^2)` iff `q * (1 - s^2) = 2s`.
-/
theorem radialDualNorm_mul_denominator
    (s : ℝ)
    (hden : 1 - s ^ (2 : ℕ) ≠ 0) :
    radialDualNorm s * (1 - s ^ (2 : ℕ)) = 2 * s := by
  unfold radialDualNorm
  field_simp [hden]

/--
If `q` is the radial dual coordinate, it satisfies the quadratic equation
`q*s^2 + 2s - q = 0`.
-/
theorem radialDualNorm_quadratic
    (s q : ℝ)
    (hden : 1 - s ^ (2 : ℕ) ≠ 0)
    (hq : q = radialDualNorm s) :
    q * s ^ (2 : ℕ) + 2 * s - q = 0 := by
  rw [hq]
  have h := radialDualNorm_mul_denominator s hden
  linear_combination -h

/--
The positive radial branch recovered from the dual norm:

`s(q) = q / (sqrt (1 + q^2) + 1)`.
-/
def radialPrimalFromDual (q : ℝ) : ℝ :=
  q / (Real.sqrt (1 + q ^ (2 : ℕ)) + 1)

/-- The denominator in `radialPrimalFromDual` is strictly positive. -/
theorem radialPrimalFromDual_den_pos (q : ℝ) :
    0 < Real.sqrt (1 + q ^ (2 : ℕ)) + 1 := by
  positivity

/-- The denominator in `radialPrimalFromDual` is nonzero. -/
theorem radialPrimalFromDual_den_ne_zero (q : ℝ) :
    Real.sqrt (1 + q ^ (2 : ℕ)) + 1 ≠ 0 :=
  ne_of_gt (radialPrimalFromDual_den_pos q)

/-- Nonnegative dual norm gives a nonnegative recovered primal radius. -/
theorem radialPrimalFromDual_nonneg
    {q : ℝ}
    (hq : 0 ≤ q) :
    0 ≤ radialPrimalFromDual q := by
  unfold radialPrimalFromDual
  positivity

/--
The recovered primal radius is below the unit wall for nonnegative dual norm.

This is the algebraic form of the fact that finite dual norm stays inside the
open radial ball.
-/
theorem radialPrimalFromDual_lt_one
    {q : ℝ}
    (hq : 0 ≤ q) :
    radialPrimalFromDual q < 1 := by
  unfold radialPrimalFromDual
  have hden_pos : 0 < Real.sqrt (1 + q ^ (2 : ℕ)) + 1 :=
    radialPrimalFromDual_den_pos q
  rw [div_lt_one hden_pos]
  have hsqrt_sq :
      q ^ (2 : ℕ) ≤ (Real.sqrt (1 + q ^ (2 : ℕ))) ^ (2 : ℕ) := by
    rw [Real.sq_sqrt (by positivity : 0 ≤ 1 + q ^ (2 : ℕ))]
    nlinarith [sq_nonneg q]
  have hq_le_sqrt : q ≤ Real.sqrt (1 + q ^ (2 : ℕ)) := by
    exact (sq_le_sq₀ hq (Real.sqrt_nonneg _)).1 hsqrt_sq
  linarith

/--
The Fenchel/Legendre radial inverse formula.

For `q ≥ 0`, the radius
`s(q) = q / (sqrt (1+q^2)+1)` satisfies
`2s(q)/(1-s(q)^2) = q`.
-/
theorem radialDualNorm_radialPrimalFromDual
    {q : ℝ}
    (hq : 0 ≤ q) :
    radialDualNorm (radialPrimalFromDual q) = q := by
  unfold radialDualNorm radialPrimalFromDual
  let a := Real.sqrt (1 + q ^ (2 : ℕ))
  have ha_sq : a ^ (2 : ℕ) = 1 + q ^ (2 : ℕ) := by
    exact Real.sq_sqrt (by positivity : 0 ≤ 1 + q ^ (2 : ℕ))
  have hden : a + 1 ≠ 0 := by
    exact ne_of_gt (by positivity : 0 < a + 1)
  have hwall : 1 - (q / (a + 1)) ^ (2 : ℕ) ≠ 0 := by
    have hlt : q / (a + 1) < 1 := by
      change radialPrimalFromDual q < 1
      exact radialPrimalFromDual_lt_one hq
    have hnonneg : 0 ≤ q / (a + 1) := by
      positivity
    have hsq_lt : (q / (a + 1)) ^ (2 : ℕ) < 1 := by
      exact (sq_lt_one_iff₀ hnonneg).2 hlt
    nlinarith
  have hden_expr : 1 - (q / (a + 1)) ^ (2 : ℕ) = 2 / (a + 1) := by
    field_simp [hden]
    nlinarith [ha_sq]
  calc
    2 * (q / (a + 1)) / (1 - (q / (a + 1)) ^ (2 : ℕ))
        = 2 * (q / (a + 1)) / (2 / (a + 1)) := by
          rw [hden_expr]
    _ = q := by
          field_simp [hden]

/-! ## Epsilon-regularized radial dual coordinate -/

/--
Epsilon-regularized radial dual coordinate generated by
`-log (1 - s^2 + ε)`.
-/
def radialDualNormEps (ε s : ℝ) : ℝ :=
  2 * s / (1 - s ^ (2 : ℕ) + ε)

/--
The epsilon-regularized dual coordinate clears denominators to
`q * (1 - s^2 + ε) = 2s`.
-/
theorem radialDualNormEps_mul_denominator
    (ε s : ℝ)
    (hden : 1 - s ^ (2 : ℕ) + ε ≠ 0) :
    radialDualNormEps ε s * (1 - s ^ (2 : ℕ) + ε) = 2 * s := by
  unfold radialDualNormEps
  field_simp [hden]

/--
At the original unit wall, epsilon regularization cuts off the radial dual
force at `2/ε`.
-/
theorem radialDualNormEps_boundary
    {ε : ℝ}
    (hε : ε ≠ 0) :
    radialDualNormEps ε 1 = 2 / ε := by
  unfold radialDualNormEps
  rw [show 1 - (1 : ℝ) ^ (2 : ℕ) + ε = ε by ring]
  field_simp [hε]

/--
The true singular wall of the epsilon-regularized denominator is
`s² = 1 + ε`, not necessarily `s = 1`.
-/
theorem radialDualNormEps_den_eq_zero_iff
    (ε s : ℝ) :
    1 - s ^ (2 : ℕ) + ε = 0 ↔ s ^ (2 : ℕ) = 1 + ε := by
  constructor <;> intro h <;> nlinarith

/-! ## Tau-coordinate barrier and dual coordinate -/

/-- Interior log barrier in `τ = log s` coordinates. -/
def tauBarrier (τ : ℝ) : ℝ :=
  -Real.log (1 - Real.exp (2 * τ))

/-- Epsilon-regularized wall potential in `τ` coordinates. -/
def tauBarrierEps (ε τ : ℝ) : ℝ :=
  -Real.log (1 - Real.exp (2 * τ) + ε)

/-- Inversion-symmetric epsilon-regularized wall potential. -/
def symmetricTauBarrierEps (ε τ : ℝ) : ℝ :=
  -Real.log (1 - Real.exp (-2 * |τ|) + ε)

/-- At the radial wall `τ = 0`, the epsilon-regularized barrier is `-log ε`. -/
theorem tauBarrierEps_wall :
    tauBarrierEps ε 0 = -Real.log ε := by
  simp [tauBarrierEps]

/-- The inversion-symmetric regularized wall potential has value `-log ε` at `τ=0`. -/
theorem symmetricTauBarrierEps_wall :
    symmetricTauBarrierEps ε 0 = -Real.log ε := by
  simp [symmetricTauBarrierEps]

/-- The `τ`-coordinate dual variable generated by the radial log barrier. -/
def tauDual (τ : ℝ) : ℝ :=
  2 * Real.exp (2 * τ) / (1 - Real.exp (2 * τ))

/--
The `τ`-dual equation solves algebraically for the purity parameter
`exp(2τ)`.

If `η = 2e^{2τ}/(1-e^{2τ})`, then
`e^{2τ} = η/(η+2)`.
-/
theorem exp_two_tau_eq_of_tauDual
    (τ η : ℝ)
    (hden : 1 - Real.exp (2 * τ) ≠ 0)
    (hη : η = tauDual τ) :
    Real.exp (2 * τ) = η / (η + 2) := by
  let u := Real.exp (2 * τ)
  have hu_pos : 0 < u := Real.exp_pos _
  have hdenu : 1 - u ≠ 0 := by
    simpa [u] using hden
  have hηu : η * (1 - u) = 2 * u := by
    rw [hη]
    unfold tauDual
    change (2 * u / (1 - u)) * (1 - u) = 2 * u
    field_simp [hdenu]
  have hsum : η + 2 ≠ 0 := by
    intro hzero
    have hcalc : η * (1 - u) = -2 * (1 - u) := by
      nlinarith
    rw [hcalc] at hηu
    nlinarith [hu_pos]
  have hmain : u * (η + 2) = η := by
    nlinarith
  calc
    Real.exp (2 * τ) = u := rfl
    _ = η / (η + 2) := by
      field_simp [hsum]
      exact hmain

/-- Log-coordinate reconstruction from a positive dual coordinate. -/
def tauOfDual (η : ℝ) : ℝ :=
  (1 / 2 : ℝ) * Real.log (η / (η + 2))

/--
If `η = tauDual τ`, then the formal inverse relation is
`τ = 1/2 log (η/(η+2))`.
-/
theorem tau_eq_tauOfDual_of_tauDual
    {τ η : ℝ}
    (hden : 1 - Real.exp (2 * τ) ≠ 0)
    (hη : η = tauDual τ) :
    τ = tauOfDual η := by
  unfold tauOfDual
  have h := exp_two_tau_eq_of_tauDual τ η hden hη
  have hlog :
      Real.log (η / (η + 2)) = 2 * τ := by
    rw [← h]
    exact Real.log_exp (2 * τ)
  rw [hlog]
  ring

end InfoGeometry.Convex.RadialLogBarrier
