import Mathlib

/-!
# Noncommutative tiling algebra anchors

Finite formal anchors for the Connes/Penrose tiling picture:

* groupoid convolution is modeled finitely by matrix convolution;
* Fibonacci/Penrose substitution has Perron--Frobenius eigenvalue `φ`;
* trace/gap labels land in `Z + φ Z`;
* Robinson/Penrose tile frequencies are `1/φ` and `1/φ²`.
-/

noncomputable section

namespace NoncommutativeTilingAlgebra

open Matrix

/-! ## Finite groupoid convolution as matrix multiplication -/

/-- A finite pair-groupoid kernel; convolution is matrix multiplication. -/
abbrev PairKernel (α : Type*) [Fintype α] := Matrix α α ℂ

/-- Finite convolution model for groupoid convolution. -/
def conv {α : Type*} [Fintype α] [DecidableEq α]
    (f g : PairKernel α) : PairKernel α :=
  f * g

/-- Groupoid convolution is associative in the finite pair-groupoid model. -/
theorem conv_assoc {α : Type*} [Fintype α] [DecidableEq α]
    (f g h : PairKernel α) : conv (conv f g) h = conv f (conv g h) := by
  simp [conv, mul_assoc]

/-- Delta kernel for an arrow `(i,j)`. -/
def deltaKernel {α : Type*} [DecidableEq α] (i j : α) : Matrix α α ℂ :=
  fun r c => if r = i ∧ c = j then 1 else 0

/-! ## Fibonacci substitution, Perron--Frobenius vector, and gap labels -/

/-- Golden ratio. -/
def phi : ℝ := (1 + Real.sqrt 5) / 2

/-- Golden-ratio algebraic equation. -/
theorem phi_sq_eq_phi_add_one : phi ^ 2 = phi + 1 := by
  unfold phi
  have h5 : 0 ≤ (5 : ℝ) := by norm_num
  have hs : (Real.sqrt 5) ^ 2 = (5 : ℝ) := Real.sq_sqrt h5
  nlinarith [hs]

/-- Fibonacci/Penrose substitution matrix over the reals. -/
def FibR : Matrix (Fin 2) (Fin 2) ℝ :=
  !![1, 1;
     1, 0]

/-- Perron--Frobenius eigenvector `[φ,1]` with eigenvalue `φ`. -/
theorem FibR_pf_eigen :
    FibR.mulVec ![phi, 1] = phi • ![phi, 1] := by
  funext i
  fin_cases i
  · simp [FibR, Matrix.mulVec]
    rw [← phi_sq_eq_phi_add_one]
    ring
  · simp [FibR, Matrix.mulVec]

/-- Trace/gap-label subgroup element `m+nφ`. -/
def gapLabel (m n : ℤ) : ℝ :=
  (m : ℝ) + (n : ℝ) * phi

/-- The gap-label values are closed under addition. -/
theorem gapLabel_add (m n p q : ℤ) :
    gapLabel m n + gapLabel p q = gapLabel (m + p) (n + q) := by
  simp [gapLabel]
  ring

/-- The gap-label values are closed under negation. -/
theorem gapLabel_neg (m n : ℤ) :
    -gapLabel m n = gapLabel (-m) (-n) := by
  simp [gapLabel]
  ring

/-- The algebraic `K₀`/dimension-group coordinate module generated by two tile
classes.  Evaluation sends `(m,n)` to the gap label `m+nφ`. -/
abbrev ZPhiModule := ℤ × ℤ

/-- Evaluation of the dimension-group coordinate into the real trace/gap-label
module `ℤ + φℤ`. -/
def evalTrace (v : ZPhiModule) : ℝ :=
  gapLabel v.1 v.2

/-- Fibonacci inflation action on `ℤ + φℤ`: multiplication by `φ` sends
`m+nφ` to `n+(m+n)φ`, using `φ²=φ+1`. -/
def inflationAction (v : ZPhiModule) : ZPhiModule :=
  (v.2, v.1 + v.2)

/-- Algebraic core of the gap-labeling theorem: the discrete substitution action
on the `K₀` coordinates corresponds exactly to multiplication of the trace label
by the Perron--Frobenius scale `φ`. -/
theorem gap_labeling_trace_scaling (v : ZPhiModule) :
    evalTrace (inflationAction v) = phi * evalTrace v := by
  rcases v with ⟨m, n⟩
  simp [evalTrace, inflationAction, gapLabel]
  calc
    (n : ℝ) + ((m : ℝ) + (n : ℝ)) * phi
        = (m : ℝ) * phi + (n : ℝ) * (phi + 1) := by ring
    _ = (m : ℝ) * phi + (n : ℝ) * phi ^ 2 := by rw [phi_sq_eq_phi_add_one]
    _ = phi * ((m : ℝ) + (n : ℝ) * phi) := by ring

/-- Matrix form of the same dimension-group action. -/
def K0InflationMatrix : Matrix (Fin 2) (Fin 2) ℤ :=
  !![0, 1;
     1, 1]

/-- The coordinate action `(m,n) ↦ (n,m+n)` is multiplication by the transpose
Fibonacci/inflation matrix. -/
theorem K0InflationMatrix_action (m n : ℤ) :
    K0InflationMatrix.mulVec ![m, n] = ![n, m + n] := by
  funext i
  fin_cases i <;> simp [K0InflationMatrix, Matrix.mulVec]

/-- Algebraic identity behind normalized Penrose/Robinson tile frequencies. -/
theorem phi_inv_add_phi_inv_sq : phi⁻¹ + (phi ^ 2)⁻¹ = 1 := by
  have hphi : phi ≠ 0 := by
    unfold phi
    positivity
  have hphi2 : phi ^ 2 ≠ 0 := pow_ne_zero 2 hphi
  field_simp [hphi, hphi2]
  rw [phi_sq_eq_phi_add_one]

/-- Thick/large tile frequency. -/
def thickFreq : ℝ := phi⁻¹

/-- Thin/small tile frequency. -/
def thinFreq : ℝ := (phi ^ 2)⁻¹

/-- The two normalized Robinson/Penrose frequency weights sum to one. -/
theorem thickFreq_add_thinFreq : thickFreq + thinFreq = 1 := by
  exact phi_inv_add_phi_inv_sq

/-- The thick tile frequency is the gap label `-1 + φ`. -/
theorem thickFreq_eq_gapLabel : thickFreq = gapLabel (-1) 1 := by
  unfold thickFreq gapLabel
  have hphi : phi ≠ 0 := by
    unfold phi
    positivity
  field_simp [hphi]
  norm_num
  calc
    1 = phi ^ 2 - phi := by
      rw [phi_sq_eq_phi_add_one]
      ring
    _ = phi * (-1 + phi) := by ring

/-- The thin tile frequency is the gap label `2 - φ`. -/
theorem thinFreq_eq_gapLabel : thinFreq = gapLabel 2 (-1) := by
  have hsum : thickFreq + thinFreq = 1 := thickFreq_add_thinFreq
  have hthick : thickFreq = gapLabel (-1) 1 := thickFreq_eq_gapLabel
  calc
    thinFreq = 1 - thickFreq := by linarith
    _ = 1 - gapLabel (-1) 1 := by rw [hthick]
    _ = gapLabel 2 (-1) := by
      simp [gapLabel]
      ring

/-- Two Robinson/Penrose prototile frequency classes. -/
inductive TileType where
  | thick
  | thin
  deriving DecidableEq, Repr

/-- Frequency of each normalized tile type. -/
def tileFrequency : TileType → ℝ
  | .thick => thickFreq
  | .thin => thinFreq

/-- K₀/gap-label coordinates of each tile-frequency projector. -/
def tileGapCoords : TileType → ZPhiModule
  | .thick => (-1, 1)
  | .thin => (2, -1)

/-- The trace/gap-label evaluation of the tile projector coordinates gives the
actual Penrose/Robinson tile frequency. -/
theorem tileFrequency_eq_evalTrace (t : TileType) :
    tileFrequency t = evalTrace (tileGapCoords t) := by
  cases t
  · exact thickFreq_eq_gapLabel
  · exact thinFreq_eq_gapLabel

/-- The two tile frequencies are explicit members of the `ℤ+φℤ` trace range. -/
theorem tile_frequencies_in_gapLabel_range :
    (∃ v : ZPhiModule, evalTrace v = thickFreq) ∧
    (∃ v : ZPhiModule, evalTrace v = thinFreq) := by
  constructor
  · use tileGapCoords .thick
    exact (tileFrequency_eq_evalTrace .thick).symm
  · use tileGapCoords .thin
    exact (tileFrequency_eq_evalTrace .thin).symm

/-! ## Cuntz--Krieger -/

/-- Finite Cuntz--Krieger relation schema for an adjacency matrix `A`. -/
structure CuntzKriegerFamily (ι Aop : Type*) [Fintype ι] [DecidableEq ι]
    [Mul Aop] [AddCommMonoid Aop] [Star Aop] [OfNat Aop 0] where
  Adj : ι → ι → Bool
  S : ι → Aop
  ck_relation : ∀ i : ι,
    star (S i) * S i = ∑ j, (if Adj i j then S j * star (S j) else 0)

/-! ## Cuntz as the all-ones Cuntz--Krieger special case -/

/-- The all-ones adjacency matrix/relation.  This is the Cuntz case inside the
Cuntz--Krieger family. -/
def allOnesAdj (ι : Type*) : ι → ι → Bool :=
  fun _ _ => true

/-- A finite Cuntz family: isometric generators with total range projection one.
This is an algebraic schema, not a full C*-completion. -/
structure CuntzFamily (ι Aop : Type*) [Fintype ι] [DecidableEq ι]
    [Mul Aop] [AddCommMonoid Aop] [Star Aop] [OfNat Aop 1] where
  S : ι → Aop
  isometry : ∀ i : ι, star (S i) * S i = 1
  range_sum : ∑ j, S j * star (S j) = 1

/-- Every finite Cuntz family is a Cuntz--Krieger family for the all-ones
adjacency matrix.  Algebraically, `S_i^*S_i=1=Σ_j S_jS_j^*`. -/
def CuntzFamily.toAllOnesCK {ι Aop : Type*} [Fintype ι] [DecidableEq ι]
    [Mul Aop] [AddCommMonoid Aop] [Star Aop] [OfNat Aop 0] [OfNat Aop 1]
    (C : CuntzFamily ι Aop) : CuntzKriegerFamily ι Aop where
  Adj := allOnesAdj ι
  S := C.S
  ck_relation := by
    intro i
    rw [C.isometry i, ← C.range_sum]
    simp [allOnesAdj]

/-- In the all-ones case, the Cuntz--Krieger right-hand side is independent of
`i`; it is exactly the total range projection. -/
theorem allOnesCK_rhs {ι Aop : Type*} [Fintype ι] [DecidableEq ι]
    [Mul Aop] [AddCommMonoid Aop] [Star Aop] [OfNat Aop 0]
    (S : ι → Aop) (i : ι) :
    (∑ j, (if allOnesAdj ι i j then S j * star (S j) else 0)) =
      ∑ j, S j * star (S j) := by
  simp [allOnesAdj]

/-- For two generators, the all-ones CK relation is the standard `O₂` boundary
relation: each source projection equals `P₀+P₁`. -/
theorem allOnesCK_two_rhs (S : Fin 2 → Aop) [Mul Aop] [AddCommMonoid Aop]
    [Star Aop] [OfNat Aop 0] (i : Fin 2) :
    (∑ j, (if allOnesAdj (Fin 2) i j then S j * star (S j) else 0)) =
      S 0 * star (S 0) + S 1 * star (S 1) := by
  simp [allOnesAdj, Fin.sum_univ_two]


/-- Finite algebraic package supporting the noncommutative tiling interpretation. -/
theorem finite_tiling_algebra_anchors :
    phi ^ 2 = phi + 1 ∧
    FibR.mulVec ![phi, 1] = phi • ![phi, 1] ∧
    thickFreq + thinFreq = 1 ∧
    (∀ m n p q : ℤ, gapLabel m n + gapLabel p q = gapLabel (m + p) (n + q)) := by
  constructor
  · exact phi_sq_eq_phi_add_one
  · constructor
    · exact FibR_pf_eigen
    · constructor
      · exact thickFreq_add_thinFreq
      · exact gapLabel_add

end NoncommutativeTilingAlgebra
