import InfoGeometry.Probability.DetectorCopulaDecoupling

/-!
# Audit for Detector Copula Decoupling & Independence Restoration
-/

#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.productCopula_one_right
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.productCopula_one_left
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.productCopula_zero_right
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.productCopula_zero_left
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.productCopula_comm
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.productCopula_assoc
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.bayes_independence
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.bayes_factorization
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.copulaCovariance_eq
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.copulaCovariance_zero
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.angularCopula_uncorrelated
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.marginal_correlation_invariant
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.marginal_angularCopula_eq_product
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.quadratic_marginal_restoration
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.coincidence_loss_restoration
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.restoredProduct_factorization
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.restoredProduct_eq_productCopula
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.restoredProduct_eq_productCopula_explicit
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.copulaQuotient_scale_invariant
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.copulaQuotient_dilation_invariant
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.copula_activity_recovery
#print axioms InfoGeometry.Probability.DetectorCopulaDecoupling.certified_detector_copula_decoupling_synthesis
