import InfoGeometry.Probability.DetectorOperatorSplitting

#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.linearTransport_hom
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.quadraticLoss_hom
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.dissipation_ratio
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.dissipation_linear_modulation
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.restoration_recovers_linear
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.restoration_add
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.gauge_invariance_transport
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.gauge_invariance_loss
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.gauge_invariance_response
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.gauge_invariance_coincidence
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.gauge_invariance_restoration
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.gauge_invariance_dissipation_ratio
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.campion_invariant_exact
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.campion_microscopic_cancellation
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.campion_local_gauge_invariance
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.rankOne_minor_2x2
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.rankOne_collinear_columns
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.rankOne_collinear_rows
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.volume_integral_cancellation
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.apollonianLinearizer_root
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.apollonianLinearizer_extract_d0
#print axioms InfoGeometry.Probability.DetectorOperatorSplitting.apollonianLinearizer_sq
