import InfoGeometry.Probability.DetectorRankTwoResponse

#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.response_factorization
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.response_gauge_invariant
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.restored_response
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.product_closure
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.contact_gauge_unique
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.closureSlope_gauge_invariant
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.activity_gauge_invariant
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.rank_two_basis_rotation
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.quadratic_coordinate_identification
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.activity_recovers_activity
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.activity_with_conversion
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.three_line_linear_dependence
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.three_geometry_linear_dependence
#print axioms InfoGeometry.Probability.DetectorRankTwoResponse.det_matrix3x3_zero
