import InfoGeometry.Probability.DetectorCrossSectionDuality
import InfoGeometry.Algebra.FiniteSpinAlgebra

#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.linearizer_root
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.linearizer_extract_d0
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.restored_linear_rate
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.activity_coincidence_relation
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.photopeakArea_eq_activityFree
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.cross_quotient_parameter_form
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.photopeakArea_microscopic
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.virtualSummingArea_microscopic
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.crossQuotient_microscopic
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.unit_branching_peak_to_total
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.virtualSummingArea_microscopic_angular
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.crossQuotient_microscopic_angular
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.peak_to_total_recovery_general
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.peak_to_total_parameter_form
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.peak_to_total_parameter_concordant_angular
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.legendreP2_one
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.legendreP4_one
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.directionalCorrelation_zero
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.co60_angular_correlation_exact
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.eu152_gd_angular_correlation_pureE1
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.eu152_sm_1408_angular_correlation_pureE1
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.tl208_angular_correlation_pure
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.effectiveAngularFactor_eq_reciprocal
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.effectiveAngularFactor_recovers_W
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.coincidence_anchored_daughter_cancellation
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.coincidence_anchored_intermediate_link
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.coincidence_anchored_ingrowth_equivalence
#print axioms InfoGeometry.Probability.DetectorCrossSectionDuality.coincidence_anchored_relative_efficiency_invariant


