import Mathlib.Analysis.Calculus.Deriv.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Tactic

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace InfoGeometry.Probability.FisherRaoMadelungIsometry

/-!
# The Fisher–Rao Metric and the Madelung $\sqrt{\rho}$ Isometry

This module formalizes:
1. The **Madelung $\sqrt{\rho}$ Transformation**: $\psi = \sqrt{\rho}$.
2. The **Fisher–Rao Metric Flattening Theorem**:
   $$4 (d\sqrt{\rho})^2 = \frac{(d\rho)^2}{\rho}$$
   proving that the map $\rho \mapsto 2\sqrt{\rho}$ is a Riemannian isometry
   transforming the curved Fisher–Rao metric into the flat Euclidean/Hilbert $L^2$ metric.
3. The **Legendre–Bregman Duality**:
   The Kullback–Leibler divergence is identically the Bregman divergence generated by the log-partition potential.
-/

/-- 🏆 THEOREM: The Infinitesimal Madelung Derivative:
    d/dt [√ρ(t)] = ρ'(t) / (2 √ρ(t)) -/
theorem hasDerivAt_madelung_amplitude
    (rho : ℝ → ℝ) (rho' : ℝ) (t : ℝ)
    (h_diff : HasDerivAt rho rho' t)
    (h_pos : 0 < rho t) :
    HasDerivAt (fun s => Real.sqrt (rho s)) (rho' / (2 * Real.sqrt (rho t))) t := by
  exact HasDerivAt.sqrt h_diff (ne_of_gt h_pos)

/-- Positive densities have a nonzero Madelung amplitude. -/
theorem madelung_amplitude_pos
    (rho_val : ℝ) (h_pos : 0 < rho_val) :
    0 < Real.sqrt rho_val :=
  Real.sqrt_pos.2 h_pos

theorem madelung_amplitude_ne_zero
    (rho_val : ℝ) (h_pos : 0 < rho_val) :
    Real.sqrt rho_val ≠ 0 :=
  ne_of_gt (madelung_amplitude_pos rho_val h_pos)

theorem madelung_amplitude_sq
    (rho_val : ℝ) (h_pos : 0 < rho_val) :
    (Real.sqrt rho_val) ^ 2 = rho_val :=
  Real.sq_sqrt (le_of_lt h_pos)

/-- 🏆 THEOREM: The Fisher–Rao Metric Isometry:
    4 * (d/dt √ρ(t))² = (ρ'(t))² / ρ(t)
    The quadratic form on the flat amplitude space equals the Fisher–Rao energy on the density manifold. -/
theorem fisher_rao_madelung_isometry
    (rho' : ℝ) (rho_val : ℝ) (h_pos : 0 < rho_val) :
    let dpsi := rho' / (2 * Real.sqrt rho_val)
    4 * (dpsi ^ 2) = (rho' ^ 2) / rho_val := by
  dsimp
  have h_sq : (Real.sqrt rho_val) ^ 2 = rho_val :=
    madelung_amplitude_sq rho_val h_pos
  calc
    4 * (rho' / (2 * Real.sqrt rho_val)) ^ 2
        = 4 * (rho' ^ 2 / (4 * (Real.sqrt rho_val) ^ 2)) := by ring
      _ = 4 * (rho' ^ 2 / (4 * rho_val)) := by rw [h_sq]
      _ = (4 / 4) * (rho' ^ 2 / rho_val) := by ring
      _ = 1 * (rho' ^ 2 / rho_val) := by norm_num
      _ = (rho' ^ 2) / rho_val := by rw [one_mul]

/-- The Fisher--Rao identity expressed using the actual derivative of the
Madelung amplitude. -/
theorem fisher_rao_madelung_deriv
    (rho : ℝ → ℝ) (rho' : ℝ) (t : ℝ)
    (h_diff : HasDerivAt rho rho' t)
    (h_pos : 0 < rho t) :
    4 * (deriv (fun s => Real.sqrt (rho s)) t) ^ 2 =
      (rho' ^ 2) / rho t := by
  have h_amp := hasDerivAt_madelung_amplitude rho rho' t h_diff h_pos
  rw [h_amp.deriv]
  exact fisher_rao_madelung_isometry rho' (rho t) h_pos

/-- 🏆 THEOREM: The Bregman Divergence generated by a convex potential Ψ:
    D_Ψ(θ₁, θ₂) = Ψ(θ₁) - Ψ(θ₂) - ⟨∇Ψ(θ₂), θ₁ - θ₂⟩
    For 1-dimensional exponential families, the Bregman divergence is non-negative and zero iff θ₁ = θ₂. -/
def bregmanDivergence (psi : ℝ → ℝ) (dpsi : ℝ → ℝ) (theta1 theta2 : ℝ) : ℝ :=
  psi theta1 - psi theta2 - dpsi theta2 * (theta1 - theta2)

/-- For identical parameters, the divergence vanishes identically. -/
@[simp]
theorem bregmanDivergence_self (psi : ℝ → ℝ) (dpsi : ℝ → ℝ) (theta : ℝ) :
    bregmanDivergence psi dpsi theta theta = 0 := by
  dsimp [bregmanDivergence]
  ring

/-- A supporting-line inequality for `psi` gives nonnegativity of its
one-dimensional Bregman divergence. -/
theorem bregmanDivergence_nonneg_of_supporting_line
    (psi dpsi : ℝ → ℝ) (theta1 theta2 : ℝ)
    (hsupport : psi theta2 + dpsi theta2 * (theta1 - theta2) ≤ psi theta1) :
    0 ≤ bregmanDivergence psi dpsi theta1 theta2 := by
  dsimp [bregmanDivergence]
  linarith

/-- Strict supporting lines characterize the zero set of the Bregman
divergence under the stated hypothesis. -/
theorem bregmanDivergence_pos_of_strict_supporting_line
    (psi dpsi : ℝ → ℝ) (theta1 theta2 : ℝ)
    (hstrict : theta1 ≠ theta2 →
      psi theta2 + dpsi theta2 * (theta1 - theta2) < psi theta1)
    (hne : theta1 ≠ theta2) :
    0 < bregmanDivergence psi dpsi theta1 theta2 := by
  dsimp [bregmanDivergence]
  linarith [hstrict hne]

theorem bregmanDivergence_eq_zero_iff_of_strict_supporting_line
    (psi dpsi : ℝ → ℝ) (theta1 theta2 : ℝ)
    (hstrict : theta1 ≠ theta2 →
      psi theta2 + dpsi theta2 * (theta1 - theta2) < psi theta1) :
    bregmanDivergence psi dpsi theta1 theta2 = 0 ↔ theta1 = theta2 := by
  constructor
  · intro hzero
    by_contra hne
    have hpos := bregmanDivergence_pos_of_strict_supporting_line
      psi dpsi theta1 theta2 hstrict hne
    linarith
  · intro hEq
    subst theta1
    exact bregmanDivergence_self psi dpsi theta2

/-- 🏆 THEOREM: Legendre–Fenchel Dual Conjugate (Entropy):
    S(η) = θ · η - Ψ(θ) where η = Ψ'(θ) -/
def legendreDual (psi : ℝ → ℝ) (theta : ℝ) (eta : ℝ) : ℝ :=
  theta * eta - psi theta

/-- Invariance of the duality pairing under Legendre transformation:
    Ψ(θ) + S(η) = θ · η -/
theorem legendre_fenchel_identity (psi : ℝ → ℝ) (theta : ℝ) (eta : ℝ) :
    psi theta + legendreDual psi theta eta = theta * eta := by
  dsimp [legendreDual]
  ring

end InfoGeometry.Probability.FisherRaoMadelungIsometry
