import InfoGeometry.Probability.SimplexQuadraticResponse

#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.response_hasDerivAt
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.dilation_defect
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.probability_coordinate
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.vertex_gap
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.response_le_vertex
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.response_reflection
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.binary_variance
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.binary_variance_peak
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.amplitude_circle
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.product_amplitude_normalization
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.complementary_product_positive
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.metrics_distinct
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.rational_residual
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.exponential_lower_bound
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.log_odds_hasDerivAt
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.log_odds_pullback
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.logistic_field_geodesic
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.kinetic_energy_along_field
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.radial_inversion_involutive
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.inverted_radius_probability
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.response_noninjective
#print axioms InfoGeometry.Probability.SimplexQuadraticResponse.response_in_rapidity
