import Mathlib.Tactic

/-!
# Arnold-Cohen Relation Surfaces

This module formalizes the combinatorial structure of the Arnold-Cohen algebra,
which is the algebraic target used by the projective twistor/amplituhedron
bridge files.

The fundamental Arnold mixed relation for 3 points is:
  `ω₁₂ ∧ ω₂₃ + ω₂₃ ∧ ω₃₁ + ω₃₁ ∧ ω₁₂ = 0`
where `ω_ij = d log Q(x_i - x_j)`.

This file does not prove a BCFW recursion theorem.  Such a comparison must be
supplied by an amplituhedron owner file.
-/

namespace InfoGeometry.Projective.ArnoldRelations

variable (R : Type*) [CommRing R]
variable (M : Type*) [AddCommGroup M] [Module R M]

/-- Exterior carrier used for finite Arnold relation readouts. -/
abbrev ArnoldExterior :=
  ExteriorAlgebra R M

/-- The three-edge Arnold mixed relation term. -/
def arnoldMixedRelation
    (w12 w23 w31 : ArnoldExterior R M) : ArnoldExterior R M :=
  w12 * w23 + w23 * w31 + w31 * w12

/--
If a model's ring homomorphism kills the mixed relation, then the relation
evaluates to zero in that model.
-/
theorem arnold_mixed_relation_vanishes_under_kernel_membership
    {A : Type*} [Semiring A]
    (w12 w23 w31 : ArnoldExterior R M)
    (φ : ArnoldExterior R M →+* A)
    (hKer : arnoldMixedRelation R M w12 w23 w31 ∈ RingHom.ker φ) :
    φ (arnoldMixedRelation R M w12 w23 w31) = 0 := by
  simpa using (RingHom.mem_ker.mp hKer)

end InfoGeometry.Projective.ArnoldRelations

namespace InfoGeometry.Projective.Amplituhedron

variable (R : Type*) [CommRing R]
variable (ι : Type*)

/-- The free R-module generated by pairs of points (edges) -/
abbrev EdgeModule := (ι × ι) →₀ R

/-- The canonical injection of a pair into the Exterior Algebra -/
noncomputable def w (i j : ι) : ExteriorAlgebra R (EdgeModule R ι) :=
  ExteriorAlgebra.ι R (Finsupp.single (i, j) (1 : R))

/-- 
The Arnold-Cohen relation.
We define an inductive relation on the exterior algebra generated by the
symmetry of the logarithmic form and the global residue mixed relation.
-/
inductive ArnoldRel : ExteriorAlgebra R (EdgeModule R ι) → ExteriorAlgebra R (EdgeModule R ι) → Prop
  | symm (i j : ι) : ArnoldRel (w R ι i j) (w R ι j i)
  | mixed (i j k : ι) : ArnoldRel (w R ι i j * w R ι j k + w R ι j k * w R ι k i + w R ι k i * w R ι i j) 0

/-- The Arnold-Cohen Algebra (Orlik-Solomon Algebra) 
    representing the configuration space cohomology ring. -/
noncomputable def ArnoldAlgebra := RingQuot (ArnoldRel R ι)

/-- The image of an edge generator in the Arnold-Cohen quotient algebra. -/
noncomputable def omega (i j : ι) : ArnoldAlgebra R ι :=
  (RingQuot.mkRingHom (ArnoldRel R ι)) (w R ι i j)

/-- Edge symmetry holds in the Arnold-Cohen quotient algebra. -/
theorem omega_symm (i j : ι) :
    omega R ι i j = omega R ι j i := by
  simpa [omega] using
    RingQuot.mkRingHom_rel (ArnoldRel.symm (R := R) (ι := ι) i j)

/--
The three-edge Arnold mixed relation maps to the quotient image of source zero.

This is a quotient-level combinatorial readout.  It does not identify the
generators with concrete `d log Q` differential forms.
-/
theorem arnold_mixed_relation_quotient_zero (i j k : ι) :
    (RingQuot.mkRingHom (ArnoldRel R ι))
      (w R ι i j * w R ι j k +
        w R ι j k * w R ι k i +
        w R ι k i * w R ι i j) =
      (RingQuot.mkRingHom (ArnoldRel R ι)) 0 :=
  RingQuot.mkRingHom_rel (ArnoldRel.mixed (R := R) (ι := ι) i j k)

end InfoGeometry.Projective.Amplituhedron
