import InfoGeometry.Categorical.Holonomy
import InfoGeometry.Categorical.FilteredColimitExactness
import InfoGeometry.Categorical.TensorColimit
import InfoGeometry.Categorical.CuntzCantorKMSColimitBridge
import InfoGeometry.Categorical.FiniteWordPathWeights
