import InfoGeometry.Categorical.Holonomy
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Categorical.FilteredColimitExactness
import InfoGeometry.Categorical.TensorColimit
import InfoGeometry.Categorical.HadjiivanovRMatrixBraid
import InfoGeometry.Categorical.RindlerFilteredColimit
import InfoGeometry.Categorical.PrimeThermodynamicLimitCapstone
import InfoGeometry.Categorical.PrimonParafermionGrandCanonicalColimitCapstone

import InfoGeometry.Categorical.BraidGroup3S3QuotientBridge
import InfoGeometry.Categorical.ArtinGarsideCenterBridge
import InfoGeometry.Categorical.UniversalArtinBraidRepresentation
import InfoGeometry.Categorical.BraidPermutationQuotient
import InfoGeometry.Categorical.MajoranaUniversalB3Bridge
import InfoGeometry.Categorical.FibonacciUniversalB3Bridge
