import InfoGeometry.Categorical.LogNilpotentMonoidalCategory
import InfoGeometry.Categorical.QuantumG2RMatrixBraidingDatum

/-!
# InfoGeometry.Categorical.LogNilpotentCheckedRAdapter

Thin adapter from the repository-owned checked-`R` infrastructure to the
finite-nilpotent logarithmic monoidal category.

No new `R`-matrix datum is introduced here.  The input is the existing
`QuantumG2RMatrixDatum`, which already owns:

* an invertible checked `R : V ⊗ V ≃ V ⊗ V`;
* the derived three-site operators `R₁₂` and `R₂₃`;
* the Yang--Baxter / Artin relation;
* a nontrivial monodromy witness.

The only extra hypothesis required to enter the logarithmic category is the
missing representation-theoretic compatibility:

`R ∘ N_(X⊗X) = N_(X⊗X) ∘ R`.

Under that hypothesis the checked `R` is promoted to an automorphism of the
logarithmic tensor object.  Its local actions on three tensor factors are then
built using the already-owned logarithmic associator and tensor product, and
the pre-existing Yang--Baxter theorem is transported verbatim to categorical
morphisms.
-/

noncomputable section

namespace InfoGeometry.Categorical.LogNilpotentCheckedRAdapter

open CategoryTheory
open scoped TensorProduct CategoryTheory.MonoidalCategory

open InfoGeometry.Categorical.LogEndModuleCategory
open InfoGeometry.Categorical.LogEndModuleCategory.LogEndModule
open InfoGeometry.Categorical.LogNilpotentModuleCategory
open InfoGeometry.Categorical.LogNilpotentModuleCategory.LogNilpotentModule
open InfoGeometry.Categorical.QuantumG2RMatrixBraidingDatum

universe u v

variable {𝕜 : Type u} [Field 𝕜]

/-- Two-fold tensor object generated by one logarithmic object. -/
abbrev PairObj (X : LogNilpotentModule 𝕜) : LogNilpotentModule 𝕜 :=
  LogNilpotentModule.tensorObj X X

/-- Right-associated three-fold tensor object generated by one logarithmic
object. -/
abbrev TripleObj (X : LogNilpotentModule 𝕜) : LogNilpotentModule 𝕜 :=
  LogNilpotentModule.tensorObj X (LogNilpotentModule.tensorObj X X)

/-- A repository-owned checked `R` becomes a logarithmic morphism as soon as it
commutes with the distinguished tensor nilpotent. -/
def checkedRHom
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    PairObj X ⟶ PairObj X where
  hom := D.checkR.toLinearMap
  comm := hR

/-- The inverse checked `R` automatically intertwines the logarithmic
nilpotent whenever `R` itself does. -/
def checkedRInvHom
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    PairObj X ⟶ PairObj X where
  hom := D.checkR.symm.toLinearMap
  comm := by
    apply LinearMap.ext
    intro x
    have hx := LinearMap.congr_fun hR (D.checkR.symm x)
    change D.checkR.symm ((PairObj X).N x) = (PairObj X).N (D.checkR.symm x)
    calc
      D.checkR.symm ((PairObj X).N x) =
          D.checkR.symm ((PairObj X).N (D.checkR (D.checkR.symm x))) := by
            rw [D.checkR.apply_symm_apply]
      _ = D.checkR.symm (D.checkR ((PairObj X).N (D.checkR.symm x))) := by
            exact congrArg D.checkR.symm hx.symm
      _ = (PairObj X).N (D.checkR.symm x) := by
            simp

/-- The checked `R` is therefore an isomorphism in the finite-nilpotent
logarithmic category. -/
def checkedRIso
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    PairObj X ≅ PairObj X where
  hom := checkedRHom X D hR
  inv := checkedRInvHom X D hR
  hom_inv_id := by
    apply LogEndModule.Hom.ext
    ext x
    simp [checkedRHom, checkedRInvHom]
  inv_hom_id := by
    apply LogEndModule.Hom.ext
    ext x
    simp [checkedRHom, checkedRInvHom]

/-- Local checked `R` acting on tensor slots 2 and 3. -/
def checkedR23Hom
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    TripleObj X ⟶ TripleObj X :=
  LogNilpotentModule.tensorHom (𝟙 X) (checkedRHom X D hR)

/-- Local checked `R` acting on tensor slots 1 and 2, transported through the
canonical logarithmic associator. -/
def checkedR12Hom
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    TripleObj X ⟶ TripleObj X :=
  (LogNilpotentModule.associatorIso X X X).inv ≫
    LogNilpotentModule.tensorHom (checkedRHom X D hR) (𝟙 X) ≫
    (LogNilpotentModule.associatorIso X X X).hom

/-- Readback of the categorical 2--3 action is exactly the repository-owned
`map23` construction. -/
theorem checkedR23Hom_hom
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    (checkedR23Hom X D hR).hom = (map23 𝕜 X D.checkR).toLinearMap := by
  ext x y z
  simp [checkedR23Hom, checkedRHom, LogNilpotentModule.tensorHom,
    LogEndModule.tensorHom, map23]

/-- Readback of the categorical 1--2 action is exactly the repository-owned
`map12` construction. -/
theorem checkedR12Hom_hom
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    (checkedR12Hom X D hR).hom = (map12 𝕜 X D.checkR).toLinearMap := by
  apply LinearMap.ext
  intro t
  simp [checkedR12Hom, checkedRHom, LogNilpotentModule.tensorHom,
    LogNilpotentModule.associatorIso, LogEndModule.tensorHom,
    LogEndModule.associatorHom, LogEndModule.associatorInv,
    map12, LinearEquiv.trans_apply]
  rfl

/-- The repository-owned Yang--Baxter theorem lifts to equality of genuine
morphisms in the logarithmic tensor-power sector. -/
theorem checkedR_yangBaxter
    (X : LogNilpotentModule 𝕜)
    (D : QuantumG2RMatrixDatum 𝕜 X)
    (hR : D.checkR.toLinearMap.comp (PairObj X).N =
      (PairObj X).N.comp D.checkR.toLinearMap) :
    checkedR12Hom X D hR ≫ checkedR23Hom X D hR ≫ checkedR12Hom X D hR =
      checkedR23Hom X D hR ≫ checkedR12Hom X D hR ≫ checkedR23Hom X D hR := by
  apply LogEndModule.Hom.ext
  ext t
  have hYB := D.yangBaxter
  rw [D.checkR12_eq, D.checkR23_eq] at hYB
  have ht := LinearMap.congr_fun hYB t
  simpa [LogNilpotentModule.hom_comp, checkedR12Hom_hom,
    checkedR23Hom_hom, LinearMap.comp_apply] using ht

end InfoGeometry.Categorical.LogNilpotentCheckedRAdapter
