/-
InfoGeometry/OperatorAlgebra/ChiralPolarization.lean

Circular polarization and defect predicates.

This module keeps the ambient algebra/module fixed. Nilpotents, zero divisors,
and chiral sectors are predicates or projector data inside that ambient object;
they are not modeled as replacement ambient types.

The circular chiral basis is generated by an involution `χ² = 1`, morally
`χ = iK` after scalar complexification of a real phase operator `K² = -1`.
-/

import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Tactic

noncomputable section

namespace InfoGeometry.OperatorAlgebra

/-! ## 1. Krein isotropic cone as carrier geometry -/

/--
A Krein fundamental symmetry or metric operator on the carrier, with its
self-adjointness and involutivity expressed by native continuous-linear-map
equalities.
-/
structure KreinMetricDatum
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    [CompleteSpace H] where
  eta : H →L[ℝ] H
  eta_self_adjoint :
    ContinuousLinearMap.adjoint eta = eta
  eta_involutive :
    eta.comp eta = ContinuousLinearMap.id ℝ H

/-- Krein bilinear form associated to `eta`. -/
def kreinForm
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    [CompleteSpace H]
    (K : KreinMetricDatum H)
    (v w : H) : ℝ :=
  inner (𝕜 := ℝ) v (K.eta w)

/--
The isotropic cone is the nonzero null locus of the Krein quadratic form.

This is the geometric primitive; algebraic zero-divisor or nilpotent defects
are represented detection loci related to it by bridge witnesses.
-/
def IsIsotropicVector
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]
    [CompleteSpace H]
    (K : KreinMetricDatum H)
    (v : H) : Prop :=
  v ≠ 0 ∧ kreinForm K v v = 0

/--
Projective ray equivalence by nonzero real scalar rescaling.
-/
def SameProjectiveRay
    {H : Type*} [NormedAddCommGroup H] [NormedSpace ℝ H]
    (v w : H) : Prop :=
  ∃ lam : ℝ, lam ≠ 0 ∧ w = lam • v

/-! ## 2. Defect predicates inside a fixed ambient algebra -/

/--
A nilpotent element in an ambient power-with-zero structure.

This repository-local version requires a nonzero exponent.  Mathlib also has
`IsNilpotent x := ∃ n, x ^ n = 0`.
-/
def IsNilpotentElement
    {A : Type*} [Zero A] [Pow A ℕ]
    (x : A) : Prop :=
  ∃ n : ℕ, n ≠ 0 ∧ x ^ n = 0

/--
Repository-local nonzero-exponent nilpotence implies Mathlib nilpotence.
-/
theorem isNilpotent_of_isNilpotentElement
    {A : Type*} [Zero A] [Pow A ℕ]
    {x : A}
    (h : IsNilpotentElement x) :
    IsNilpotent x := by
  rcases h with ⟨n, _hn_ne, hn⟩
  exact ⟨n, hn⟩

/-- A square-zero element. -/
def IsSquareZeroElement
    {A : Type*} [MulZeroClass A]
    (x : A) : Prop :=
  x * x = 0

/--
A square-zero element is nilpotent with exponent `2`.
-/
theorem isNilpotentElement_of_squareZero
    {A : Type*} [MonoidWithZero A]
    {x : A}
    (h : x * x = 0) :
    IsNilpotentElement x := by
  refine ⟨2, by norm_num, ?_⟩
  simpa [pow_two] using h

/-- A nonzero square-zero element. -/
def IsNonzeroSquareZeroElement
    {A : Type*} [MulZeroClass A]
    (x : A) : Prop :=
  x * x = 0 ∧ x ≠ 0

/--
A left zero divisor: some nonzero element is killed on the right by `x`.

This is a predicate inside an ambient algebra, not a new ambient type.
-/
def IsLeftZeroDivisor
    {A : Type*} [MulZeroClass A]
    (x : A) : Prop :=
  ∃ y : A, y ≠ 0 ∧ x * y = 0

/--
A right zero divisor: some nonzero element kills `x` on the left.

This is a predicate inside an ambient algebra, not a new ambient type.
-/
def IsRightZeroDivisor
    {A : Type*} [MulZeroClass A]
    (x : A) : Prop :=
  ∃ y : A, y ≠ 0 ∧ y * x = 0

/--
A one-sided zero divisor in a possibly noncommutative ambient algebra.
-/
def IsOneSidedZeroDivisor
    {A : Type*} [MulZeroClass A]
    (x : A) : Prop :=
  IsLeftZeroDivisor x ∨ IsRightZeroDivisor x

/--
A two-sided zero divisor in a possibly noncommutative ambient algebra.

This requires both left and right annihilator data. For the weaker
left-or-right condition, use `IsOneSidedZeroDivisor`.
-/
def IsTwoSidedZeroDivisor
    {A : Type*} [MulZeroClass A]
    (x : A) : Prop :=
  IsLeftZeroDivisor x ∧ IsRightZeroDivisor x

/-- A two-sided zero divisor is, in particular, a one-sided zero divisor. -/
theorem IsTwoSidedZeroDivisor.oneSided
    {A : Type*} [MulZeroClass A]
    {x : A}
    (h : IsTwoSidedZeroDivisor x) :
    IsOneSidedZeroDivisor x :=
  Or.inl h.1

/--
A minimal division-core-like condition: no nonzero square-zero elements.

This avoids pretending that quaternions/octonions are ordinary commutative
integral domains while still capturing the needed nilpotent obstruction.
-/
class NoSquareZero
    (A : Type*) [MulZeroClass A] : Prop where
  eq_zero_of_square_eq_zero :
    ∀ x : A, x * x = 0 → x = 0

/-- Square-zero elements vanish in a `NoSquareZero` ambient algebra. -/
theorem square_zero_forces_zero
    {A : Type*} [MulZeroClass A] [NoSquareZero A]
    {x : A}
    (hx : x * x = 0) :
    x = 0 :=
  NoSquareZero.eq_zero_of_square_eq_zero x hx

/-- No-square-zero algebras have no nonzero square-zero elements. -/
theorem not_nonzero_squareZero_of_noSquareZero
    {A : Type*} [MulZeroClass A] [NoSquareZero A]
    (x : A) :
    ¬ IsNonzeroSquareZeroElement x := by
  intro hx
  exact hx.2 (NoSquareZero.eq_zero_of_square_eq_zero x hx.1)

/-- A semiring with no zero divisors has no nonzero square-zero elements. -/
instance noSquareZero_of_noZeroDivisors
    {A : Type*} [Semiring A] [NoZeroDivisors A] :
    NoSquareZero A where
  eq_zero_of_square_eq_zero := by
    intro x hx
    exact (mul_eq_zero.mp hx).elim id id

/-! ## 2. Circular polarization inside an associative operator algebra -/

/--
A circular polarization datum inside an associative operator algebra.

The intended model is `χ = iK`, where `K² = -1`, hence `χ² = 1`.  The
projectors are packaged with their laws because, in a general noncommutative
operator algebra, the precise scalar compatibility belongs to the concrete
representation layer.
-/
structure CircularPolarization
    (Op : Type*) [Ring Op] [Module ℝ Op] where
  /-- The chiral involution, morally `χ = iK`. -/
  chi : Op

  /-- The involution law. -/
  chi_sq :
    chi * chi = 1

  /-- Left/circular-positive projector. -/
  P_left : Op

  /-- Right/circular-negative projector. -/
  P_right : Op

  /-- Formula for the left projector. -/
  P_left_def :
    P_left = (1 / 2 : ℝ) • ((1 : Op) + chi)

  /-- Formula for the right projector. -/
  P_right_def :
    P_right = (1 / 2 : ℝ) • ((1 : Op) - chi)

  /-- Idempotence of the left projector. -/
  P_left_idem :
    P_left * P_left = P_left

  /-- Idempotence of the right projector. -/
  P_right_idem :
    P_right * P_right = P_right

  /-- Orthogonality. -/
  P_left_mul_right :
    P_left * P_right = 0

  /-- Orthogonality in the other order. -/
  P_right_mul_left :
    P_right * P_left = 0

  /-- Completeness. -/
  P_sum :
    P_left + P_right = 1

namespace CircularPolarization

variable {Op : Type*} [Ring Op] [Module ℝ Op]
variable (C : CircularPolarization Op)

/-- Re-export left idempotence. -/
@[simp]
theorem left_idempotent :
    C.P_left * C.P_left = C.P_left :=
  C.P_left_idem

/-- Re-export right idempotence. -/
@[simp]
theorem right_idempotent :
    C.P_right * C.P_right = C.P_right :=
  C.P_right_idem

/-- Re-export left/right disjointness. -/
@[simp]
theorem left_mul_right :
    C.P_left * C.P_right = 0 :=
  C.P_left_mul_right

/-- Re-export right/left disjointness. -/
@[simp]
theorem right_mul_left :
    C.P_right * C.P_left = 0 :=
  C.P_right_mul_left

/-- Re-export completeness. -/
theorem left_add_right :
    C.P_left + C.P_right = 1 :=
  C.P_sum

end CircularPolarization

/-! ## 3. Phase-preserving algebra morphisms preserve circular projectors -/

/--
A real-linear multiplicative map between polarized operator algebras that
preserves the chiral involution.

This is the algebra-level version of the naturality statement:

`f χ_A = χ_B`.
-/
structure PhasePreservingAlgebraMap
    {OpA OpB : Type*}
    [Ring OpA] [Module ℝ OpA]
    [Ring OpB] [Module ℝ OpB]
    (CA : CircularPolarization OpA)
    (CB : CircularPolarization OpB) where
  toLinearMap : OpA →ₗ[ℝ] OpB

  map_one :
    toLinearMap 1 = 1

  map_mul :
    ∀ x y : OpA,
      toLinearMap (x * y) = toLinearMap x * toLinearMap y

  map_chi :
    toLinearMap CA.chi = CB.chi

namespace PhasePreservingAlgebraMap

variable {OpA OpB : Type*}
variable [Ring OpA] [Module ℝ OpA]
variable [Ring OpB] [Module ℝ OpB]
variable {CA : CircularPolarization OpA}
variable {CB : CircularPolarization OpB}
variable (f : PhasePreservingAlgebraMap CA CB)

/-- A phase-preserving algebra map preserves the left circular projector. -/
theorem map_P_left :
    f.toLinearMap CA.P_left = CB.P_left := by
  rw [CA.P_left_def, CB.P_left_def]
  simp [f.map_one, f.map_chi]

/-- A phase-preserving algebra map preserves the right circular projector. -/
theorem map_P_right :
    f.toLinearMap CA.P_right = CB.P_right := by
  rw [CA.P_right_def, CB.P_right_def]
  simp [f.map_one, f.map_chi]

end PhasePreservingAlgebraMap

/-! ## 4. Module-level circular polarization and naturality -/

/--
Circular polarization on a real module.

This is the representation-level form: `χ` is a real-linear involution, and
the chiral projectors split the carrier module.
-/
structure ModuleCircularPolarization
    (X : Type*) [AddCommGroup X] [Module ℝ X] where
  /-- Chiral involution. -/
  chi : X →ₗ[ℝ] X

  /-- Involution law. -/
  chi_sq :
    chi.comp chi = LinearMap.id

  P_left : X →ₗ[ℝ] X
  P_right : X →ₗ[ℝ] X

  P_left_def :
    P_left =
      (1 / 2 : ℝ) •
        ((LinearMap.id : X →ₗ[ℝ] X) + chi)

  P_right_def :
    P_right =
      (1 / 2 : ℝ) •
        ((LinearMap.id : X →ₗ[ℝ] X) - chi)

  P_left_idem :
    P_left.comp P_left = P_left

  P_right_idem :
    P_right.comp P_right = P_right

  P_left_comp_right :
    P_left.comp P_right = 0

  P_right_comp_left :
    P_right.comp P_left = 0

  P_sum :
    P_left + P_right = LinearMap.id

/--
A phase-preserving linear map between circularly polarized modules.

This is the precise categorical content:

`f ∘ χ_X = χ_Y ∘ f`.
-/
structure PhasePreservingLinearMap
    {X Y : Type*}
    [AddCommGroup X] [Module ℝ X]
    [AddCommGroup Y] [Module ℝ Y]
    (CX : ModuleCircularPolarization X)
    (CY : ModuleCircularPolarization Y) where
  toLinearMap : X →ₗ[ℝ] Y

  preserves_chi :
    toLinearMap.comp CX.chi = CY.chi.comp toLinearMap

namespace PhasePreservingLinearMap

variable {X Y : Type*}
variable [AddCommGroup X] [Module ℝ X]
variable [AddCommGroup Y] [Module ℝ Y]
variable {CX : ModuleCircularPolarization X}
variable {CY : ModuleCircularPolarization Y}
variable (f : PhasePreservingLinearMap CX CY)

/-- Pointwise phase-preservation. -/
theorem preserves_chi_apply
    (x : X) :
    f.toLinearMap (CX.chi x) =
      CY.chi (f.toLinearMap x) := by
  have h :=
    congrArg
      (fun L : X →ₗ[ℝ] Y => L x)
      f.preserves_chi
  simpa [LinearMap.comp_apply] using h

/--
A phase-preserving map preserves the left chiral projector:

`f ∘ P_L^X = P_L^Y ∘ f`.
-/
theorem comp_P_left :
    f.toLinearMap.comp CX.P_left =
      CY.P_left.comp f.toLinearMap := by
  ext x
  rw [CX.P_left_def, CY.P_left_def]
  simp [LinearMap.comp_apply, f.preserves_chi_apply x]

/--
A phase-preserving map preserves the right chiral projector:

`f ∘ P_R^X = P_R^Y ∘ f`.
-/
theorem comp_P_right :
    f.toLinearMap.comp CX.P_right =
      CY.P_right.comp f.toLinearMap := by
  ext x
  rw [CX.P_right_def, CY.P_right_def]
  simp [LinearMap.comp_apply, f.preserves_chi_apply x]

/--
A phase-preserving map splits on the domain chiral projectors.

This is the raw left/right decomposition before applying the target
projectors.
-/
theorem split_on_domain_projectors
    (f : PhasePreservingLinearMap CX CY)
    (x : X) :
    f.toLinearMap x =
      f.toLinearMap (CX.P_left x) + f.toLinearMap (CX.P_right x) := by
  have hsum : CX.P_left x + CX.P_right x = x := by
    have h :=
      congrArg (fun L : X →ₗ[ℝ] X => L x) CX.P_sum
    simpa [LinearMap.add_apply, LinearMap.id_apply] using h
  calc
    f.toLinearMap x = f.toLinearMap (CX.P_left x + CX.P_right x) := by
      exact congrArg f.toLinearMap hsum.symm
    _ = f.toLinearMap (CX.P_left x) + f.toLinearMap (CX.P_right x) := by
      exact f.toLinearMap.map_add (CX.P_left x) (CX.P_right x)

/--
A phase-preserving map lands in the codomain chiral decomposition.

This is the output-side projector decomposition; combined with
`split_on_domain_projectors`, it gives the closed left/right split package.
-/
theorem split_on_target_projectors
    (f : PhasePreservingLinearMap CX CY)
    (x : X) :
    CY.P_left (f.toLinearMap x) + CY.P_right (f.toLinearMap x) =
      f.toLinearMap x := by
  have hsum : CY.P_left + CY.P_right = LinearMap.id := by
    simpa [add_comm] using CY.P_sum
  have h := congrArg (fun L : Y →ₗ[ℝ] Y => L (f.toLinearMap x)) hsum
  simpa [LinearMap.add_apply, LinearMap.id_apply] using h

end PhasePreservingLinearMap

end InfoGeometry.OperatorAlgebra
