import InfoGeometry.OperatorAlgebra.DiracHodgeSpinZornAll

#print axioms InfoGeometry.OperatorAlgebra.FaithfulOperatorZornEnvelope.diagonal_injective
#print axioms InfoGeometry.OperatorAlgebra.FaithfulOperatorZornEnvelope.leftRegularRepresentation_injective
#print axioms InfoGeometry.OperatorAlgebra.FiniteTwoTermDiracHodgeZorn.diracHodge_sq_eq_hodgeLaplacian
#print axioms InfoGeometry.OperatorAlgebra.FiniteTwoTermDiracHodgeZorn.exterior_codifferential_adjoint
#print axioms InfoGeometry.OperatorAlgebra.FiniteTwoTermDiracHodgeZorn.sumSheets_diracZornBlock_intertwines
#print axioms InfoGeometry.OperatorAlgebra.RealWeylAdjointSpinRepresentation.rightWeyl_mul
#print axioms InfoGeometry.OperatorAlgebra.RealWeylAdjointSpinRepresentation.actWeylPair_mul
#print axioms InfoGeometry.OperatorAlgebra.RealWeylAdjointSpinRepresentation.real_weyl_spin_packet
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.cl55EnvelopeMap_commutator
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.contactEnvelopeMap_bracket
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.cl55EnvelopeMap_injective
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.contactEnvelopeMap_injective
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.cl55EnvelopeMap_preserves_grade
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.contactEnvelopeMap_preserves_grade
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner.spinorRepresentation_intertwines_leftRegular
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornRestrictedGradeMaps.commutator_mem_jointGradeSpace_add
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornRestrictedGradeMaps.cl55RestrictedGradeMap_injective
#print axioms InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornRestrictedGradeMaps.contactRestrictedGradeMap_injective
#print axioms InfoGeometry.OperatorAlgebra.DiracHodgeSpinZornIntertwinerClosure.finite_dirac_hodge_zorn_packet
#print axioms InfoGeometry.OperatorAlgebra.DiracHodgeSpinZornIntertwinerClosure.cl55_freudenthal_joint_envelope_packet
