import InfoGeometry.OperatorAlgebra.FaithfulOperatorZornEnvelope
import InfoGeometry.OperatorAlgebra.FiniteTwoTermDiracHodgeZorn
import InfoGeometry.OperatorAlgebra.RealWeylAdjointSpinRepresentation
import InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornGradeIntertwiner
import InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornRestrictedGradeMaps
import InfoGeometry.OperatorAlgebra.Cl55FreudenthalZornLieRepresentation
import InfoGeometry.OperatorAlgebra.DiracHodgeSpinZornIntertwinerClosure
