import Mathlib
import InfoGeometry.Canonical.KantorPeirceFiveGrading
import InfoGeometry.OperatorAlgebra.OperatorExteriorAlgebra

/-!
# Noncommutative operator five-grading

This is the associative operator-algebra layer.  It deliberately does not
identify a nonassociative carrier with its regular operators.  The grading is
defined by an inner commutator in an associative algebra, so the Leibniz law
and the product-grade rule are kernel-level consequences of associativity.
-/

namespace InfoGeometry.OperatorAlgebra

open ExteriorAlgebra

section

variable {A : Type*} [Ring A] [Algebra ℝ A]

/-- The inner derivation generated by `h` on an associative operator algebra. -/
def innerOperatorDerivation (h : A) : OpDerivation ℝ A where
  toLinearMap :=
    { toFun := fun x => h * x - x * h
      map_add' := by
        intro x y
        noncomm_ring
      map_smul' := by
        intro r x
        simp only [Algebra.smul_mul_assoc, Algebra.mul_smul_comm,
          RingHom.id_apply, smul_sub] }
  leibniz' := by
    intro x y
    change h * (x * y) - (x * y) * h =
      (h * x - x * h) * y + x * (h * y - y * h)
    noncomm_ring

@[simp] theorem innerOperatorDerivation_apply (h x : A) :
    innerOperatorDerivation h x = h * x - x * h := rfl

theorem innerOperatorDerivation_leibniz (h x y : A) :
    innerOperatorDerivation h (x * y) =
      innerOperatorDerivation h x * y + x * innerOperatorDerivation h y := by
  exact OpDerivation.leibniz (innerOperatorDerivation h) x y

theorem innerOperatorDerivation_add (h x y : A) :
    innerOperatorDerivation h (x + y) =
      innerOperatorDerivation h x + innerOperatorDerivation h y := by
  exact OpDerivation.map_add (innerOperatorDerivation h) x y

theorem innerOperatorDerivation_sub (h x y : A) :
    innerOperatorDerivation h (x - y) =
      innerOperatorDerivation h x - innerOperatorDerivation h y := by
  exact OpDerivation.map_sub (innerOperatorDerivation h) x y

theorem innerOperatorDerivation_smul (h : A) (r : ℝ) (x : A) :
    innerOperatorDerivation h (r • x) = r • innerOperatorDerivation h x := by
  exact OpDerivation.map_smul (innerOperatorDerivation h) r x

/-- A weight component for the inner derivation `ad h`. -/
def HasInnerOperatorWeight (h x : A) (r : ℝ) : Prop :=
  innerOperatorDerivation h x = r • x

theorem innerOperatorWeight_mul
    {h x y : A} {r s : ℝ}
    (hx : HasInnerOperatorWeight h x r)
    (hy : HasInnerOperatorWeight h y s) :
    HasInnerOperatorWeight h (x * y) (r + s) := by
  unfold HasInnerOperatorWeight at *
  rw [innerOperatorDerivation_leibniz, hx, hy]
  rw [Algebra.smul_mul_assoc, Algebra.mul_smul_comm, ← add_smul]

theorem innerOperatorWeight_commutator
    {h x y : A} {r s : ℝ}
    (hx : HasInnerOperatorWeight h x r)
    (hy : HasInnerOperatorWeight h y s) :
    HasInnerOperatorWeight h (x * y - y * x) (r + s) := by
  unfold HasInnerOperatorWeight at *
  rw [innerOperatorDerivation_sub]
  rw [innerOperatorWeight_mul hx hy, innerOperatorWeight_mul hy hx]
  rw [smul_sub]
  simp only [add_comm]

end

end InfoGeometry.OperatorAlgebra
