import InfoGeometry.OperatorAlgebra.SplitOctonionMultiplication
import InfoGeometry.OperatorAlgebra.SplitOctonionSymplecticFoundation

namespace InfoGeometry.OperatorAlgebra.SplitOctonions.Multiplication
open InfoGeometry.OperatorAlgebra.SplitOctonions.SymplecticFoundation

/-- Left ideal generated by the ePlus Peirce projector. -/
def leftIdeal (X : SplitOct) : SplitOct := mulZ ePlus X

/-- Right ideal generated by the eMinus Peirce projector. -/
def rightIdeal (X : SplitOct) : SplitOct := mulZ X eMinus

/-- Two-sided ideal / corner generated by both projectors. -/
def twoSidedIdeal (X : SplitOct) : SplitOct := mulZ (mulZ ePlus X) eMinus

/-- The left ideal action is idempotent. -/
theorem leftIdeal_idempotent (X : SplitOct) : leftIdeal (leftIdeal X) = leftIdeal X := by
  cases X
  dsimp [leftIdeal, mulZ, ePlus]
  ext <;> ring

/-- The right ideal action is idempotent. -/
theorem rightIdeal_idempotent (X : SplitOct) : rightIdeal (rightIdeal X) = rightIdeal X := by
  cases X
  dsimp [rightIdeal, mulZ, eMinus]
  ext <;> ring

/-- Annihilation of the trace-one diagonal unit by the two-sided ideal map. -/
theorem twoSidedIdeal_annihilation : twoSidedIdeal (addZ ePlus eMinus) = zeroZ := rfl

end InfoGeometry.OperatorAlgebra.SplitOctonions.Multiplication
