/-
InfoGeometry/OperatorAlgebra/TKKClosure.lean

Tits-Kantor-Koecher closure sockets for the reflection-sensitive
O(4,4)/Pin(4,4) and projective Möbius stack.

The architectural point is:

* The algebraic closure is a 3-graded TKK Lie algebra

      g = g₋₁ ⊕ g₀ ⊕ g₊₁

  where the negative grade is the translation/system side, the zero grade is
  the structure algebra, and the positive grade is the special-conformal/
  mirror side.

* The symmetry-group closure is not `SO(4,4)` or `Spin(4,4)`.  Those forget
  reflection/chiral components.  The reflection-sensitive base is `O(4,4)`
  and `Pin(4,4)`.

* Möbius inversion is not a base projective transformation on `P(R⁴,⁴)`; it
  belongs to the ambient conformal compactification, modeled here by the
  projective null rays of signature `(5,5)` and by `O(5,5)`/`Pin(5,5)` data.

This file is an owner-level socket.  It does not construct a concrete Clifford
algebra or a concrete Jordan triple system; it records the dependency graph and
proof-carrying closure laws needed by concrete models.
-/

import Mathlib
import InfoGeometry.OperatorAlgebra.O44PinMobiusProjective
import InfoGeometry.OperatorAlgebra.KleinianTwist
import InfoGeometry.Meta.OwnerTarget
import InfoGeometry.Meta.SocketTarget

noncomputable section

namespace InfoGeometry.OperatorAlgebra

/-! ## 1. Jordan triple input for TKK -/

/--
A real Jordan triple system socket.

The intended product is written `{x y z}` and is symmetric in the outer
variables.  The Jordan triple identity is included explicitly because concrete
operator models may use different analytic domains or completions.
-/
structure JordanTripleSystem
    (J : Type*) [AddCommGroup J] [Module ℝ J] where
  /-- Triple product `{x y z}`. -/
  triple : J → J → J → J

  /-- Outer symmetry: `{x y z} = {z y x}`. -/
  outer_symm :
    ∀ x y z : J, triple x y z = triple z y x

  /-- Linearity/continuity/domain certificate for the triple product. -/
  triple_regular : Prop

  /-- Jordan triple identity. -/
  triple_identity :
    ∀ u v x y z : J,
      triple u v (triple x y z) - triple x y (triple u v z)
        =
      triple (triple u v x) y z -
        triple x (triple v u y) z

namespace JordanTripleSystem

variable
    {J : Type*} [AddCommGroup J] [Module ℝ J]
    (T : JordanTripleSystem J)

/-- Box operator associated to the pair `(x,y)`: `z ↦ {x y z}`. -/
def box
    (x y : J) : J → J :=
  fun z => T.triple x y z

/-- Re-export outer symmetry. -/
theorem outer_symm_apply
    (x y z : J) :
    T.triple x y z = T.triple z y x :=
  T.outer_symm x y z

/-- Re-export the Jordan triple identity. -/
theorem triple_identity_apply
    (u v x y z : J) :
      T.triple u v (T.triple x y z) -
          T.triple x y (T.triple u v z)
        =
      T.triple (T.triple u v x) y z -
          T.triple x (T.triple v u y) z :=
  T.triple_identity u v x y z

end JordanTripleSystem

/-! ## 2. Abstract Lie socket and TKK grades -/

/-- TKK grading labels. -/
inductive TKKGrade where
  | negative
  | zero
  | positive
deriving DecidableEq, Repr

namespace TKKGrade

/-- Inversion swaps the two outer grades and fixes grade zero. -/
def mirror : TKKGrade → TKKGrade
  | negative => positive
  | zero => zero
  | positive => negative

@[simp]
theorem mirror_mirror
    (g : TKKGrade) :
    mirror (mirror g) = g := by
  cases g <;> rfl

end TKKGrade

/--
A lightweight Lie algebra socket.

This avoids committing the repository to a concrete `LieAlgebra` realization at
this owner layer.  Downstream modules can replace it by Mathlib's Lie algebra
API once the concrete carrier is chosen.
-/
@[socket_debt_tag]
structure LieSocket
    (L : Type*) [AddCommGroup L] [Module ℝ L] where
  bracket : L → L → L

  bracket_skew :
    ∀ x y : L, bracket x y = - bracket y x

  bracket_bilinear : Prop
  jacobi : Prop

namespace LieSocket

variable
    {L : Type*} [AddCommGroup L] [Module ℝ L]
    (𝔤 : LieSocket L)

/-- Re-export skew-symmetry. -/
theorem skew
    (x y : L) :
    𝔤.bracket x y = -𝔤.bracket y x :=
  𝔤.bracket_skew x y

end LieSocket

/-! ## 3. TKK Lie closure -/

/--
Tits-Kantor-Koecher closure of a Jordan triple system.

The conventional picture is

`g = g₋₁ ⊕ g₀ ⊕ g₊₁`,

with `g₋₁` carrying the original triple system, `g₀` carrying the structure
operators, and `g₊₁` carrying the inversion-conjugate/special-conformal copy.
-/
structure TKKLieClosure
    (J L : Type*)
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L] where
  jordan : JordanTripleSystem J
  lie : LieSocket L

  /-- Negative grade, interpreted as translations/system states. -/
  neg : J →ₗ[ℝ] L

  /-- Positive grade, interpreted as special-conformal/mirror states. -/
  pos : J →ₗ[ℝ] L

  /-- Grade-zero structure operator generated by a pair of Jordan elements. -/
  zero : J → J → L

  gradeSet : TKKGrade → Set L

  neg_mem :
    ∀ x : J, neg x ∈ gradeSet TKKGrade.negative

  pos_mem :
    ∀ x : J, pos x ∈ gradeSet TKKGrade.positive

  zero_mem :
    ∀ x y : J, zero x y ∈ gradeSet TKKGrade.zero

  /-- Negative grade is abelian. -/
  neg_abelian :
    ∀ x y : J, lie.bracket (neg x) (neg y) = 0

  /-- Positive grade is abelian. -/
  pos_abelian :
    ∀ x y : J, lie.bracket (pos x) (pos y) = 0

  /-- Cross-bracket closes into the structure grade. -/
  neg_pos_bracket :
    ∀ x y : J, lie.bracket (neg x) (pos y) = zero x y

  /-- Grade zero acts on the negative grade by the triple product. -/
  zero_neg_action :
    ∀ x y z : J,
      lie.bracket (zero x y) (neg z) =
        neg (jordan.triple x y z)

  /-- Grade zero acts contragrediently on the positive grade. -/
  zero_pos_action :
    ∀ x y z : J,
      lie.bracket (zero x y) (pos z) =
        -pos (jordan.triple y x z)

  /-- Closure of all grade brackets in the 3-grading. -/
  three_grading_closed : Prop

  /-- The three grades generate the declared TKK Lie algebra. -/
  generated_by_three_grades : Prop

namespace TKKLieClosure

variable
    {J L : Type*}
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    (T : TKKLieClosure J L)

/-- Re-export: the negative grade is abelian. -/
theorem bracket_neg_neg
    (x y : J) :
    T.lie.bracket (T.neg x) (T.neg y) = 0 :=
  T.neg_abelian x y

/-- Re-export: the positive grade is abelian. -/
theorem bracket_pos_pos
    (x y : J) :
    T.lie.bracket (T.pos x) (T.pos y) = 0 :=
  T.pos_abelian x y

/-- Re-export: the cross-bracket is the grade-zero structure element. -/
theorem bracket_neg_pos
    (x y : J) :
    T.lie.bracket (T.neg x) (T.pos y) = T.zero x y :=
  T.neg_pos_bracket x y

/-- Re-export: structure-grade action on translations. -/
theorem bracket_zero_neg
    (x y z : J) :
    T.lie.bracket (T.zero x y) (T.neg z) =
      T.neg (T.jordan.triple x y z) :=
  T.zero_neg_action x y z

/-- Re-export: structure-grade action on special conformal elements. -/
theorem bracket_zero_pos
    (x y z : J) :
    T.lie.bracket (T.zero x y) (T.pos z) =
      -T.pos (T.jordan.triple y x z) :=
  T.zero_pos_action x y z

end TKKLieClosure

/-! ## 4. TKK inversion closure -/

/--
Inversion closure of a TKK algebra.

This is the infinitesimal algebraic form of the Möbius fact that inversion
conjugates translations into special conformal transformations.
-/
structure TKKInversionClosure
    (J L : Type*)
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    (T : TKKLieClosure J L) where
  /-- Algebraic inversion on the TKK Lie carrier. -/
  inversion : L ≃ₗ[ℝ] L

  /-- Inversion is involutive. -/
  inversion_involutive : Prop

  /-- Negative grade is sent to positive grade. -/
  maps_neg_to_pos :
    ∀ x : J, inversion (T.neg x) = T.pos x

  /-- Positive grade is sent back to negative grade. -/
  maps_pos_to_neg :
    ∀ x : J, inversion (T.pos x) = T.neg x

  /-- Grade zero is preserved or reflected according to the concrete model. -/
  zero_grade_compatibility : Prop

namespace TKKInversionClosure

variable
    {J L : Type*}
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    {T : TKKLieClosure J L}
    (I : TKKInversionClosure J L T)

/-- Inversion sends a translation generator to its special-conformal mirror. -/
theorem neg_to_pos
    (x : J) :
    I.inversion (T.neg x) = T.pos x :=
  I.maps_neg_to_pos x

/-- Inversion sends a special-conformal generator back to a translation. -/
theorem pos_to_neg
    (x : J) :
    I.inversion (T.pos x) = T.neg x :=
  I.maps_pos_to_neg x

end TKKInversionClosure

/-! ## 5. Projective Möbius group closure -/

/--
A projective null state in the ambient conformal `(5,5)` model.
-/
structure TKKProjectiveNullState
    {W : Type*} [AddCommGroup W] [Module ℝ W]
    (Q : SplitQuadratic55 W) where
  ray : ProjectiveRay W
  null : Q.q ray.vec = 0

/--
Reflection-sensitive TKK group closure.

The base linear symmetry is `O(4,4)`/`Pin(4,4)`.  The full projective Möbius
closure lives upstairs in the conformal ambient `O(5,5)`/`Pin(5,5)` model.
-/
structure TKKMobiusGroupClosure
    (J L V W PinBase PinConf : Type*)
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    [AddCommGroup V] [Module ℝ V]
    [AddCommGroup W] [Module ℝ W]
    [Monoid PinBase] [Monoid PinConf] where
  tkk : TKKLieClosure J L
  inversionClosure : TKKInversionClosure J L tkk

  /-- The reflection-sensitive projective conformal stack. -/
  pinMobius : PinMobiusProjective44 V W PinBase PinConf

  /-- **Open debt socket**: negative grade integrates to translation-like projective transformations.
  Should be replaced with a concrete equation-level law. -/
  negative_grade_projective_action_statement : Prop

  /-- Proof that the negative grade integrates to translation-like transformations. -/
  negative_grade_projective_action_holds :
    negative_grade_projective_action_statement

  /-- **Open debt socket**: grade zero structure group integration.
  Should be replaced with a concrete equation-level law. -/
  zero_grade_structure_action_statement : Prop

  /-- Proof that grade zero integrates to the structure group. -/
  zero_grade_structure_action_holds :
    zero_grade_structure_action_statement

  /-- **Open debt socket**: positive grade inversion-conjugate generation.
  Should be replaced with a concrete equation-level law. -/
  positive_grade_is_inversion_conjugate_statement : Prop

  /-- Proof that the positive grade is generated by inversion conjugation. -/
  positive_grade_is_inversion_conjugate_holds :
    positive_grade_is_inversion_conjugate_statement

  /-- **Open debt socket**: full closure action on projective null states.
  Should be replaced with a concrete equation-level law. -/
  acts_on_projective_null_states_statement : Prop

  /-- Proof that the full closure acts on ambient projective null rays/states. -/
  acts_on_projective_null_states_holds :
    acts_on_projective_null_states_statement

  /-- **Open debt socket**: reflection-sensitive group-closure certificate.
  Should be replaced with a concrete equation-level law. -/
  full_reflection_sensitive_group_closure_statement : Prop

  /-- Proof of the full reflection-sensitive group-closure certificate. -/
  full_reflection_sensitive_group_closure_holds :
    full_reflection_sensitive_group_closure_statement

namespace TKKMobiusGroupClosure

variable
    {J L V W PinBase PinConf : Type*}
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    [AddCommGroup V] [Module ℝ V]
    [AddCommGroup W] [Module ℝ W]
    [Monoid PinBase] [Monoid PinConf]
    (G : TKKMobiusGroupClosure J L V W PinBase PinConf)

/-- The declared closure keeps reflection/chiral data rather than passing to Spin. -/
theorem reflection_sensitive :
    G.full_reflection_sensitive_group_closure_statement :=
  G.full_reflection_sensitive_group_closure_holds

/-- The positive grade is the inversion-conjugate of the negative grade. -/
theorem positive_is_inversion_conjugate :
    G.positive_grade_is_inversion_conjugate_statement :=
  G.positive_grade_is_inversion_conjugate_holds

end TKKMobiusGroupClosure

/-! ## 6. Stinespring-Tomita/TKK clinch -/

/--
The Stinespring-Tomita interpretation of TKK closure.

The negative grade is the system/observable side, the positive grade is the
commutant/environment mirror side, and inversion is the algebraic gear shift
that swaps them.  This is a compatibility socket, not a theorem of bare TKK.
-/
structure StinespringTomitaTKKClinch
    (Op J L : Type*)
    [Ring Op]
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L] where
  tomita : TomitaCartanSplit.TomitaCommutantDatum Op
  tkk : TKKLieClosure J L
  inversionClosure : TKKInversionClosure J L tkk

  /-- System algebra corresponds to the negative TKK grade. -/
  system_is_negative_grade : Prop

  /-- Commutant/environment algebra corresponds to the positive TKK grade. -/
  commutant_is_positive_grade : Prop

  /-- Tomita mirror and TKK inversion are the same routing operation in this model. -/
  tomita_mirror_matches_tkk_inversion : Prop

  /-- Boundary/Möbius inversion routes system states into commutant states. -/
  boundary_routes_system_to_commutant : Prop

  /-- Chiral/projective/reflection classification is preserved by the full Pin closure. -/
  chiral_reflection_classification_closed : Prop

/-! ## 7. Owner target -/

/--
Compatibility data for constructing a TKK/Möbius closure.

This is the non-vacuous replacement for the former compatibility socket: a
compatible model carries exactly the Jordan triple, three-graded Lie closure,
inversion closure, reflection-sensitive Pin/Möbius projective action, and group
closure certificates required to build `TKKMobiusGroupClosure`.
-/
structure TKKClosureCompatibility
    (J L V W PinBase PinConf : Type*)
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    [AddCommGroup V] [Module ℝ V]
    [AddCommGroup W] [Module ℝ W]
    [Monoid PinBase] [Monoid PinConf] where
  /-- The Tits-Kantor-Koecher Lie closure of the Jordan triple system. -/
  tkk : TKKLieClosure J L

  /-- Algebraic inversion swapping the negative and positive grades. -/
  inversionClosure : TKKInversionClosure J L tkk

  /-- Reflection-sensitive projective conformal Pin/Möbius stack. -/
  pinMobius : PinMobiusProjective44 V W PinBase PinConf

  /-- **Open debt socket**: negative grade integrates to translation-like projective transformations.
  Should be replaced with a concrete equation-level law. -/
  negative_grade_projective_action_statement : Prop

  /-- Proof that the negative grade integrates to translation-like transformations. -/
  negative_grade_projective_action_holds :
    negative_grade_projective_action_statement

  /-- **Open debt socket**: grade zero structure group integration.
  Should be replaced with a concrete equation-level law. -/
  zero_grade_structure_action_statement : Prop

  /-- Proof that grade zero integrates to the structure group. -/
  zero_grade_structure_action_holds :
    zero_grade_structure_action_statement

  /-- **Open debt socket**: positive grade inversion-conjugate generation.
  Should be replaced with a concrete equation-level law. -/
  positive_grade_is_inversion_conjugate_statement : Prop

  /-- Proof that the positive grade is generated by inversion conjugation. -/
  positive_grade_is_inversion_conjugate_holds :
    positive_grade_is_inversion_conjugate_statement

  /-- **Open debt socket**: full closure action on projective null states.
  Should be replaced with a concrete equation-level law. -/
  acts_on_projective_null_states_statement : Prop

  /-- Proof that the full closure acts on ambient projective null rays/states. -/
  acts_on_projective_null_states_holds :
    acts_on_projective_null_states_statement

  /-- **Open debt socket**: reflection-sensitive group-closure certificate.
  Should be replaced with a concrete equation-level law. -/
  full_reflection_sensitive_group_closure_statement : Prop

  /-- Proof of the full reflection-sensitive group-closure certificate. -/
  full_reflection_sensitive_group_closure_holds :
    full_reflection_sensitive_group_closure_statement

namespace TKKClosureCompatibility

variable
    {J L V W PinBase PinConf : Type*}
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    [AddCommGroup V] [Module ℝ V]
    [AddCommGroup W] [Module ℝ W]
    [Monoid PinBase] [Monoid PinConf]

/-- Construct the TKK/Möbius group closure from explicit compatibility data. -/
def toTKKMobiusGroupClosure
    (C : TKKClosureCompatibility J L V W PinBase PinConf) :
    TKKMobiusGroupClosure J L V W PinBase PinConf where
  tkk := C.tkk
  inversionClosure := C.inversionClosure
  pinMobius := C.pinMobius
  negative_grade_projective_action_statement :=
    C.negative_grade_projective_action_statement
  negative_grade_projective_action_holds :=
    C.negative_grade_projective_action_holds
  zero_grade_structure_action_statement :=
    C.zero_grade_structure_action_statement
  zero_grade_structure_action_holds :=
    C.zero_grade_structure_action_holds
  positive_grade_is_inversion_conjugate_statement :=
    C.positive_grade_is_inversion_conjugate_statement
  positive_grade_is_inversion_conjugate_holds :=
    C.positive_grade_is_inversion_conjugate_holds
  acts_on_projective_null_states_statement :=
    C.acts_on_projective_null_states_statement
  acts_on_projective_null_states_holds :=
    C.acts_on_projective_null_states_holds
  full_reflection_sensitive_group_closure_statement :=
    C.full_reflection_sensitive_group_closure_statement
  full_reflection_sensitive_group_closure_holds :=
    C.full_reflection_sensitive_group_closure_holds

end TKKClosureCompatibility

/--
Construct the TKK closure layer from explicit compatibility data.

Concrete modules must supply the Jordan triple system, the three-grade Lie
closure, and the conformal/projective Pin-Möbius action.
-/
theorem tkkClosureOwnerTarget :
  ∀ (J L V W PinBase PinConf : Type*)
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    [AddCommGroup V] [Module ℝ V]
    [AddCommGroup W] [Module ℝ W]
    [Monoid PinBase] [Monoid PinConf],
    ∀ C : TKKClosureCompatibility J L V W PinBase PinConf,
      C.negative_grade_projective_action_statement ∧
        C.zero_grade_structure_action_statement ∧
        C.positive_grade_is_inversion_conjugate_statement ∧
        C.acts_on_projective_null_states_statement ∧
        C.full_reflection_sensitive_group_closure_statement := by
  intro J L V W PinBase PinConf _ _ _ _ _ _ _ _ _ _ C
  exact ⟨C.negative_grade_projective_action_holds,
    C.zero_grade_structure_action_holds,
    C.positive_grade_is_inversion_conjugate_holds,
    C.acts_on_projective_null_states_holds,
    C.full_reflection_sensitive_group_closure_holds⟩

/-- Packet readout for a concrete TKK/Möbius compatibility datum. -/
theorem tkkClosure_packet
    (J L V W PinBase PinConf : Type*)
    [AddCommGroup J] [Module ℝ J]
    [AddCommGroup L] [Module ℝ L]
    [AddCommGroup V] [Module ℝ V]
    [AddCommGroup W] [Module ℝ W]
    [Monoid PinBase] [Monoid PinConf]
    (C : TKKClosureCompatibility J L V W PinBase PinConf) :
    C.negative_grade_projective_action_statement ∧
      C.zero_grade_structure_action_statement ∧
      C.positive_grade_is_inversion_conjugate_statement ∧
      C.acts_on_projective_null_states_statement ∧
      C.full_reflection_sensitive_group_closure_statement :=
  tkkClosureOwnerTarget J L V W PinBase PinConf C

end InfoGeometry.OperatorAlgebra
