import InfoGeometry.Canonical.BogoliubovVielbein
import InfoGeometry.OperatorAlgebra.SpatialDerivativeLogarithmicVariation
import InfoGeometry.Topology.ThermodynamicGauge

/-!
# Bogoliubov frame deformation: noncommutative owner bridge

This module joins the existing Bogoliubov-frame transport to the existing
noncommutative logarithmic-variation API.

The deformation carrier is the unit group of the doubled-space endomorphism
algebra.  Consequently the relative frame is an actual noncommutative
multiplicative cocycle.  An operator `K` is called a logarithmic generator only
when the relative frame is certified to be the unit-valued path `exp (-K)`.
Under the native commuting-tangent hypothesis, the existing Banach-algebra
calculus then proves `Delta⁻¹ Delta' = -K'`.

No matrix diagonalization, scalar determinant, trace, polar decomposition,
operator logarithm, or de Rham identification is introduced here.
-/

noncomputable section

namespace InfoGeometry.Canonical.BogoliubovFrameDeformationEntropy

open scoped InnerProductSpace
open InfoGeometry.Canonical.BogoliubovVielbein
open InfoGeometry.OperatorAlgebra.SpatialDerivativeLogarithmicVariation
open InfoGeometry.Topology.ThermodynamicGauge

variable {E : Type}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

local notation "H₂" => InfoGeometry.Krein.DoubledSpace E
local notation "EndH" => H₂ →L[ℝ] H₂

noncomputable local instance : NormedRing EndH := inferInstance
noncomputable local instance : NormedAlgebra ℝ EndH := inferInstance
local instance : IsTopologicalRing EndH := inferInstance
local instance : CompleteSpace EndH := inferInstance

/-- A realization of a Bogoliubov reference frame by an invertible operator. -/
structure UnitFrameRealization
    (V : BogoliubovVielbeinBundle (E := E)) where
  referenceUnit : EndHˣ
  coe_referenceUnit : (referenceUnit : EndH) = V.reference

namespace UnitFrameRealization

variable {V : BogoliubovVielbeinBundle (E := E)}

/-- The transported frame as a unit of the doubled-space endomorphism algebra. -/
def transportedFrameUnit
    (R : UnitFrameRealization V) (t : ℝ) : EndHˣ :=
  expNegUnit (-(t • V.connectionGenerator)) *
    R.referenceUnit *
      expNegUnit (t • V.connectionGenerator)

/--
The unit-valued transported frame has exactly the existing Bogoliubov local
frame as its underlying operator.
-/
@[simp]
theorem coe_transportedFrameUnit
    (R : UnitFrameRealization V) (t : ℝ) :
    (R.transportedFrameUnit t : EndH) = V.localFrame t := by
  simp [transportedFrameUnit, expNegUnit_val, R.coe_referenceUnit,
    BogoliubovVielbeinBundle.localFrame,
    InfoGeometry.Canonical.expTransport, smul_neg]

/-- Current-over-reference relative Bogoliubov frame deformation. -/
def relativeVielbein
    (R : UnitFrameRealization V) (t : ℝ) : EndHˣ :=
  R.transportedFrameUnit t * R.referenceUnit⁻¹

/-- At the reference parameter, the relative frame deformation is the identity. -/
@[simp]
theorem relativeVielbein_zero
    (R : UnitFrameRealization V) :
    R.relativeVielbein 0 = 1 := by
  apply Units.ext
  simp [relativeVielbein, transportedFrameUnit, expNegUnit_val]

/-- Underlying-operator formula for the relative Bogoliubov vielbein. -/
@[simp]
theorem coe_relativeVielbein
    (R : UnitFrameRealization V) (t : ℝ) :
    (R.relativeVielbein t : EndH) =
      V.localFrame t * (↑R.referenceUnit⁻¹ : EndH) := by
  simp [relativeVielbein]

/-- Left Maurer--Cartan logarithmic variation `Delta⁻¹ Delta'`. -/
def dLnDelta
    (R : UnitFrameRealization V) (t : ℝ) : EndH :=
  leftLogarithmicDerivative R.relativeVielbein t

/-- Right Maurer--Cartan logarithmic variation `Delta' Delta⁻¹`. -/
def dLnDeltaRight
    (R : UnitFrameRealization V) (t : ℝ) : EndH :=
  rightLogarithmicDerivative R.relativeVielbein t

end UnitFrameRealization

/-- Relative units for arbitrary invertible frames. -/
def relativeUnit (current reference : EndHˣ) : EndHˣ :=
  current * reference⁻¹

omit [CompleteSpace E] in
@[simp]
theorem relativeUnit_self (frame : EndHˣ) :
    relativeUnit frame frame = 1 := by
  simp [relativeUnit]

omit [CompleteSpace E] in
/-- Three-frame multiplicative cocycle law. -/
theorem relativeUnit_cocycle
    (frame₂ frame₁ frame₀ : EndHˣ) :
    relativeUnit frame₂ frame₀ =
      relativeUnit frame₂ frame₁ * relativeUnit frame₁ frame₀ := by
  simp [relativeUnit, mul_assoc]

omit [CompleteSpace E] in
/-- Reversing the ordered frame pair inverts the relative deformation. -/
theorem relativeUnit_reverse
    (current reference : EndHˣ) :
    relativeUnit reference current =
      (relativeUnit current reference)⁻¹ := by
  simp [relativeUnit]

/--
Certificate that a relative Bogoliubov frame path is generated by the
operator path `K` through `Delta(t) = exp (-K(t))`.
-/
structure ExponentialGenerator
    {V : BogoliubovVielbeinBundle (E := E)}
    (R : UnitFrameRealization V) where
  K : ℝ → EndH
  relativeVielbein_eq_expNegUnitsPath :
    R.relativeVielbein = expNegUnitsPath K

namespace ExponentialGenerator

variable {V : BogoliubovVielbeinBundle (E := E)}
variable {R : UnitFrameRealization V}

/--
For a differentiable exponential generator with commuting tangent, the left
operator logarithmic variation is exactly `-K'`.
-/
theorem dLnDelta_eq_neg_generatorDerivative
    (G : ExponentialGenerator R)
    {t : ℝ} {K' : EndH}
    (hK : HasDerivAt G.K K' t)
    (hcomm : Commute K' (G.K t)) :
    R.dLnDelta t = -K' := by
  rw [UnitFrameRealization.dLnDelta,
    G.relativeVielbein_eq_expNegUnitsPath]
  exact leftLogarithmicDerivative_expNegUnitsPath hK hcomm

/--
For the same commuting tangent, the right operator logarithmic variation is
also `-K'`.
-/
theorem dLnDeltaRight_eq_neg_generatorDerivative
    (G : ExponentialGenerator R)
    {t : ℝ} {K' : EndH}
    (hK : HasDerivAt G.K K' t)
    (hcomm : Commute K' (G.K t)) :
    R.dLnDeltaRight t = -K' := by
  rw [UnitFrameRealization.dLnDeltaRight,
    G.relativeVielbein_eq_expNegUnitsPath]
  exact rightLogarithmicDerivative_expNegUnitsPath hK hcomm

/-- Left and right logarithmic variations agree on the certified path. -/
theorem dLnDelta_eq_dLnDeltaRight
    (G : ExponentialGenerator R)
    {t : ℝ} {K' : EndH}
    (hK : HasDerivAt G.K K' t)
    (hcomm : Commute K' (G.K t)) :
    R.dLnDelta t = R.dLnDeltaRight t := by
  rw [G.dLnDelta_eq_neg_generatorDerivative hK hcomm,
    G.dLnDeltaRight_eq_neg_generatorDerivative hK hcomm]

end ExponentialGenerator

/--
Exact identification data connecting the ring-level thermodynamic-gauge
symbol `Q, d_ln_Q` to a relative Bogoliubov unit and its analytic logarithmic
variation at one parameter.
-/
structure ThermodynamicGaugeLift
    {V : BogoliubovVielbeinBundle (E := E)}
    (R : UnitFrameRealization V)
    (flow : CausalNonequilibriumFlow EndH)
    (t : ℝ) where
  Q_eq_relativeVielbein :
    flow.Q = (R.relativeVielbein t : EndH)
  d_ln_Q_eq_dLnDelta :
    flow.d_ln_Q = R.dLnDelta t

/--
On a certified exponential relative frame, the thermodynamic-gauge variation
of the negative logarithmic generator is the derivative `K'`.
-/
theorem logGeneratorVariation_eq_generatorDerivative
    {V : BogoliubovVielbeinBundle (E := E)}
    {R : UnitFrameRealization V}
    (G : ExponentialGenerator R)
    (flow : CausalNonequilibriumFlow EndH)
    {t : ℝ} {K' : EndH}
    (lift : ThermodynamicGaugeLift R flow t)
    (hK : HasDerivAt G.K K' t)
    (hcomm : Commute K' (G.K t)) :
    logGeneratorVariation flow = K' := by
  rw [logGeneratorVariation, lift.d_ln_Q_eq_dLnDelta,
    G.dLnDelta_eq_neg_generatorDerivative hK hcomm]
  simp

end InfoGeometry.Canonical.BogoliubovFrameDeformationEntropy
