# Birkhoff-von Neumann Routing - GAP Formalization
# GAP (Groups, Algorithms, Programming) for permutation group aspects

# Load required packages
LoadPackage("orthogonality");

Print("============================================================\n");
Print("Birkhoff-von Neumann Routing - GAP Verification\n");
Print("============================================================\n\n");

# 1. Permutation matrices as group elements
Print("1. Permutation Matrices in S_n\n");

n := 3;
S := SymmetricGroup(n);
Print("Symmetric group S_", n, " has order: ", Size(S), "\n");

# Convert permutation to matrix
PermutationToMatrix := function(perm, n)
    local M, i;
    M := NullMat(n, n);
    for i in [1..n] do
        M[i][i ^ perm] := 1;
    od;
    return M;
end;

# Generate all permutation matrices for S_3
Print("\nPermutation matrices in S_3:\n");
perms := AsList(S);
for i in [1..Length(perms)] do
    Print("\nPermutation ", i, ": ", perms[i], "\n");
    Print(PermutationToMatrix(perms[i], n), "\n");
od;

# 2. Doubly stochastic matrices form a convex polytope
Print("\n2. Birkhoff Polytope B_", n, "\n");

# Dimension of Birkhoff polytope = (n-1)²
dim_birkhoff := (n-1)^2;
Print("Dimension of B_", n, ": ", dim_birkhoff, "\n");

# Number of vertices = n!
num_vertices := Factorial(n);
Print("Number of vertices (permutations): ", num_vertices, "\n");

# 3. Verify Birkhoff-von Neumann theorem for specific example
Print("\n3. BvN Decomposition Example\n");

# Example doubly stochastic matrix
W := [
    [1/2, 1/3, 1/6],
    [1/3, 1/2, 1/6],
    [1/6, 1/6, 2/3]
];

Print("Doubly stochastic matrix W:\n");
for i in [1..n] do
    Print(W[i], "\n");
od;

# Verify row sums
Print("\nRow sums: ");
for i in [1..n] do
    Print(Sum(W[i]), " ");
od;
Print("\n");

# Verify column sums
Print("Column sums: ");
for j in [1..n] do
    col_sum := Sum([1..n], i -> W[i][j]);
    Print(col_sum, " ");
od;
Print("\n");

# 4. Convex combination verification
Print("\n4. Convex Structure\n");

# Positive cone generated by permutation matrices
Print("Positive cone generated by permutation matrices is the set of\n");
Print("nonnegative linear combinations of vertices of the Birkhoff polytope.\n");

ConeWitness := function(weights, perm_mats)
    local i, nrows, ncols, M, j;
    nrows := Length(perm_mats[1]);
    ncols := Length(perm_mats[1][1]);
    M := NullMat(nrows, ncols);
    for i in [1..Length(weights)] do
        M := M + weights[i] * perm_mats[i];
    od;
    return M;
end;

# Two permutation matrices
p1 := (1,2);  # Transposition
p2 := (1,2,3); # 3-cycle

P1 := PermutationToMatrix(p1, n);
P2 := PermutationToMatrix(p2, n);

Print("\nPermutation matrix P1 (transposition):\n");
Print(P1, "\n");

Print("\nPermutation matrix P2 (3-cycle):\n");
Print(P2, "\n");

# Convex combination
theta := 2/5;
convex_comb := theta * P1 + (1-theta) * P2;

Print("\nConvex combination 0.4·P1 + 0.6·P2:\n");
Print(convex_comb, "\n");

# Verify it's doubly stochastic
row_sums_ok := ForAll([1..n], i -> Sum(convex_comb[i]) = 1);
col_sums_ok := ForAll([1..n], j -> Sum([1..n], i -> convex_comb[i][j]) = 1);

Print("Is doubly stochastic: ", row_sums_ok and col_sums_ok, "\n");

cone_weights := [1/2, 1/3, 1/6];
cone_perms := [P1, P2, P1];
cone_matrix := ConeWitness(cone_weights, cone_perms);
Print("Cone witness matrix from positive weights:\n");
Print(cone_matrix, "\n");

# 5. Character table connection (representation theory)
Print("\n5. Representation Theory Connection\n");

char_table := CharacterTable(S);
Print("Character table of S_", n, ":\n");
Display(char_table);

# Permutation representation character
perm_char := Character(char_table, [3, 1, 0]);  # Action on 3 points
Print("\nPermutation character: ", perm_char, "\n");

Print("\n============================================================\n");
Print("GAP verification complete!\n");
Print("============================================================\n");
