import InfoGeometry.Spectral.Algebra.IteratedPageStabilization
import InfoGeometry.Spectral.Algebra.ExactCoupleFiltration
import InfoGeometry.Spectral.Algebra.ConvergenceCore
import Mathlib.Algebra.Module.Submodule.Basic

/-! ## Short exact sequences -/

/-- A short exact sequence of additive commutative groups. -/
structure ShortExactSequence
    (A B C : Type*)
    [AddCommGroup A] [AddCommGroup B] [AddCommGroup C] where
  f : A →+ B
  g : B →+ C
  f_injective : Function.Injective f
  g_surjective : Function.Surjective g
  range_eq_kernel : Set.range f = { b | g b = 0 }

namespace ShortExactSequence

variable {A B C : Type*}
variable [AddCommGroup A] [AddCommGroup B] [AddCommGroup C]

theorem range_eq_kernel' (S : ShortExactSequence A B C) :
    Set.range S.f = { b | S.g b = 0 } :=
  S.range_eq_kernel

end ShortExactSequence

/-! ## Bounded exact couples and convergence -/

namespace InfoGeometry.Spectral.Algebra

universe u v

namespace GradedExactCouple

variable {R : Type u} [Ring R]
variable {I : Type v}
variable {D E : I → Type u}
variable [∀ p, AddCommGroup (D p)] [∀ p, AddCommGroup (E p)]
variable [∀ p, Module R (D p)] [∀ p, Module R (E p)]
variable {iDeg jDeg kDeg : I ≃ I}

/-! ### Boundedness -/

/--
Boundedness for a graded exact couple.

There are three functions `B`, `B'`, `B''` giving bounds on how many times the
`i` map must be iterated before the corresponding `D` or `E` term becomes
contractible (zero).

* `B p ≤ s` implies `D ((deg i)^[s] p) = 0`.
* `B' p ≤ s` implies `i` is surjective onto the next `D` after `s` iterations.
* `B'' p ≤ s` implies `E ((deg i)⁻¹^[s] p) = 0`.

In the finite spectral port, "contractible" means the zero module, so these are
finiteness bounds.
-/
structure IsBounded (C : GradedExactCouple R I D E iDeg jDeg kDeg) where
  B : I → ℕ
  B' : I → ℕ
  B'' : I → ℕ
  Dub : ∀ ⦃p : I⦄ ⦃s : ℕ⦄, B p ≤ s → ∀ x : D ((iDeg^[s]) p), x = 0
  Dlb : ∀ ⦃p : I⦄ ⦃s : ℕ⦄, B' p ≤ s →
    Function.Surjective (C.incomingIIterate (n := s + 1) p)
  Elb : ∀ ⦃p : I⦄ ⦃s : ℕ⦄, B'' p ≤ s → ∀ x : E ((iDeg.symm^[s]) p), x = 0
  pageIncoming : ∀ ⦃p : I⦄ ⦃s : ℕ⦄, B'' p ≤ s →
    ∀ x : page C.toStage s
      ((iteratedStage C.toStage s).couple.differentialDegree.symm p), x = 0
  pageOutgoing : ∀ ⦃p : I⦄ ⦃s : ℕ⦄, B p ≤ s →
    ∀ x : page C.toStage s
      ((iteratedStage C.toStage s).couple.differentialDegree p), x = 0

/-- The maximum of the three bounds at `p`. -/
def IsBounded.bound {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) (p : I) : ℕ :=
  max (hB.B p) (max (hB.B' p) (hB.B'' p))

/-- Every bound is bounded by `bound p`. -/
theorem IsBounded.B_le_bound {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) (p : I) : hB.B p ≤ hB.bound p :=
  le_max_left _ _

theorem IsBounded.B'_le_bound {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) (p : I) : hB.B' p ≤ hB.bound p :=
  le_trans (le_max_left (hB.B' p) (hB.B'' p))
    (le_max_right (hB.B p) (max (hB.B' p) (hB.B'' p)))

theorem IsBounded.B''_le_bound {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) (p : I) : hB.B'' p ≤ hB.bound p :=
  le_trans (le_max_right (hB.B' p) (hB.B'' p))
    (le_max_right (hB.B p) (max (hB.B' p) (hB.B'' p)))

/-- Once past the `D` bound, iterating `i` keeps producing zero. -/
theorem IsBounded.Dub_iterate {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    {hB : C.IsBounded} {p : I} {s : ℕ} (h : hB.B p ≤ s) :
    ∀ x : D ((iDeg^[s]) p), x = 0 :=
  hB.Dub h

/-- Once past the `E` bound, the source module is zero. -/
theorem IsBounded.Elb_iterate {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    {hB : C.IsBounded} {p : I} {s : ℕ} (h : hB.B'' p ≤ s) :
    ∀ x : E ((iDeg.symm^[s]) p), x = 0 :=
  hB.Elb h

/-- After `bound p` iterations, the `E` module at the inverse-iterate of `p` is
zero. -/
theorem IsBounded.Elb_at_bound {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) (p : I) :
    ∀ x : E ((iDeg.symm^[IsBounded.bound hB p]) p), x = 0 :=
  hB.Elb (IsBounded.B''_le_bound hB p)

/-- After `bound p` iterations, the `D` module at the iterate of `p` is zero. -/
theorem IsBounded.Dub_at_bound {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) (p : I) :
    ∀ x : D ((iDeg^[IsBounded.bound hB p]) p), x = 0 :=
  hB.Dub (IsBounded.B_le_bound hB p)

/-- `D` is surjectively generated by `i` after `B' p` preimages. -/
theorem IsBounded.Dlb_iterate {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    {hB : C.IsBounded} {p : I} {s : ℕ} (h : hB.B' p ≤ s) :
    Function.Surjective (C.incomingIIterate (n := s + 1) p) :=
  hB.Dlb h

/-- The historical boundedness record supplies the page-level vanishing
contract used by the current convergence core. -/
noncomputable def IsBounded.toBoundedPageStabilization
    {C : GradedExactCouple R I D E iDeg jDeg kDeg}
    (hB : C.IsBounded) :
    BoundedPageStabilization C.toStage :=
  { bound := hB.bound
    eventual := fun p =>
      { incoming_zero := fun n hn x =>
          hB.pageIncoming (p := p) (s := n)
            (le_trans (IsBounded.B''_le_bound hB p) hn) x
        outgoing_zero := fun n hn x =>
          hB.pageOutgoing (p := p) (s := n)
            (le_trans (IsBounded.B_le_bound hB p) hn) x } }

/-! ### Stabilization -/

/-- The stabilization equivalence between successive derived pages once past the
bound, assuming the later index is not before the earlier one. -/
noncomputable def iteratedPageEquivOfBounded
    (C : GradedExactCouple R I D E iDeg jDeg kDeg)
    (hB : C.IsBounded) (p : I) (n m : ℕ) (hn : IsBounded.bound hB p ≤ n) (hNm : n ≤ m) :
    (page (C.toStage) n p : Type u) ≃ₗ[R] (page (C.toStage) m p : Type u) :=
  (iteratedPageEquivOfEventuallyAdjacentTermsZero
    (C.toStage) p n m hNm
    (fun k hk => by
      have hle : IsBounded.B'' hB p ≤ k :=
        le_trans (IsBounded.B''_le_bound hB p) (le_trans hn hk)
      exact hB.pageIncoming (p := p) (s := k) hle)
    (fun k hk => by
      have hle : IsBounded.B hB p ≤ k :=
        le_trans (IsBounded.B_le_bound hB p) (le_trans hn hk)
      exact hB.pageOutgoing (p := p) (s := k) hle)).symm

/-- Once past the bound, all later pages are equivalent to the bound page. -/
noncomputable def iteratedPageEquivOfBounded_from
    (C : GradedExactCouple R I D E iDeg jDeg kDeg)
    (hB : C.IsBounded) (p : I) (m : ℕ) (hm : IsBounded.bound hB p ≤ m) :
    (page (C.toStage) m p : Type u) ≃ₗ[R] (page (C.toStage) (IsBounded.bound hB p) p : Type u) :=
  (C.iteratedPageEquivOfBounded hB p (IsBounded.bound hB p) m le_rfl hm).symm

/-- The stabilization equivalence between any two pages past the bound,
obtained by transitivity through the bound page. -/
noncomputable def iteratedPageEquivOfBounded_any
    (C : GradedExactCouple R I D E iDeg jDeg kDeg)
    (hB : C.IsBounded) (p : I) (n m : ℕ) (hn : IsBounded.bound hB p ≤ n) (hm : IsBounded.bound hB p ≤ m) :
    (page (C.toStage) n p : Type u) ≃ₗ[R] (page (C.toStage) m p : Type u) := by
  exact (C.iteratedPageEquivOfBounded_from hB p n hn).trans
    (C.iteratedPageEquivOfBounded_from hB p m hm).symm

end GradedExactCouple

end InfoGeometry.Spectral.Algebra
