import InfoGeometry.Algebra.HypercomplexTriad
import InfoGeometry.Canonical.ModularLorentzBoost
import InfoGeometry.Canonical.ModularSL2R
import InfoGeometry.Canonical.MobiusHyperbolicCompactification
import InfoGeometry.Potential.Thermo

/-!
# InfoGeometry.Canonical.HypercomplexMobiusLegendreCapstone

Honest capstone packaging the theorem surfaces that are already kernel-checked in
this repository:

* the concrete hypercomplex triad `(I,E,N)` in `M₂(ℝ)`;
* the modular/`sl(2,ℝ)` closure lane generated by `K = E`, `N`, and `Nᵀ`;
* the compactified Möbius boundary exchange `0 ↔ ∞` on `ℝ≥0∞`;
* the Legendre/Fenchel gap lane for abstract convex-thermodynamic models.

This file is deliberately conservative. It does **not** claim:

* a full theorem identifying the generated group with all Möbius transformations;
* a concrete projective fixed-point classification of `I`, `E`, and `N` on one
  shared carrier;
* a native theorem identifying the Drazin dilation gap with the Fenchel gap.

Instead, it records the strongest honest common packet already available from
existing owner files.
-/

namespace InfoGeometry.Canonical.HypercomplexMobiusLegendreCapstone

open InfoGeometry.Algebra.HypercomplexTriad
open InfoGeometry.Canonical.ModularLorentzBoost
open InfoGeometry.Canonical.ModularSL2R
open InfoGeometry.Canonical.MobiusHyperbolicCompactification
open InfoGeometry
open InfoGeometry.LogPotential
open InfoGeometry.LogPotential.LegendreModel

abbrev Mat2 : Type := Matrix (Fin 2) (Fin 2) ℝ
noncomputable abbrev NtBoost : Mat2 := InfoGeometry.Canonical.ModularLorentzBoost.Nt
noncomputable abbrev NtSL2 : Mat2 := InfoGeometry.Canonical.ModularSL2R.Nt

/--
Concrete algebraic packet already proved on the triad/modular side.
-/
theorem triad_modular_packet :
    I * I = -(1 : Mat2) ∧
    E * E = (1 : Mat2) ∧
    N * N = (0 : Mat2) ∧
    K = E ∧
    K * N - N * K = (2 : ℝ) • N ∧
    K * NtBoost - NtBoost * K = (-2 : ℝ) • NtBoost ∧
    N * NtSL2 - NtSL2 * N = K := by
  refine ⟨I_sq, E_sq, N_sq, rfl, modular_commutator_N, ?_, ?_⟩
  · simpa [NtBoost] using modular_commutator_Nt
  · simpa [NtSL2] using comm_N_Nt

/--
Concrete trace-form packet for the `sl(2,ℝ)` modular triple.
-/
theorem modular_trace_packet :
    traceForm K K = 2 ∧
    traceForm N N = 0 ∧
    traceForm NtSL2 NtSL2 = 0 ∧
    traceForm N NtSL2 = 1 := by
  refine ⟨traceForm_K_K, traceForm_N_N, ?_, ?_⟩
  · simpa [NtSL2] using traceForm_N_transpose_N_transpose
  · simpa [NtSL2] using traceForm_N_N_transpose

/--
Möbius compactification packet on the positive compactified chart.
-/
theorem mobius_boundary_packet :
    mobiusInv ePlus = eMinus ∧
    mobiusInv eMinus = ePlus ∧
    Function.Involutive mobiusInv := by
  exact ⟨mobiusInv_ePlus, mobiusInv_eMinus, mobiusInv_involutive⟩

/--
Two-sheet compactified readout is swapped by Möbius inversion.
-/
theorem mobius_two_sheet_packet (x : HyperChart) :
    twoSheet (mobiusInv x) = Prod.swap (twoSheet x) :=
  twoSheet_mobius_swap x

/--
Abstract Legendre/Fenchel theorem packet already proved in `Potential/Thermo`.
-/
theorem fenchel_legendre_packet
    (M : LegendreModel) (θ η ε β : ℝ)
    (hε : 0 ≤ ε) (hβ : 0 ≤ β) :
    0 ≤ M.fenchelGap θ η ∧
    0 ≤ M.scaledFenchelGap ε θ η ∧
    0 ≤ M.temperatureRegularizedHamiltonian β θ η ∧
    M.fenchelGap θ (M.dualCoord θ) = 0 ∧
    M.scaledFenchelGap ε θ (M.dualCoord θ) = 0 ∧
    M.temperatureRegularizedHamiltonian β θ (M.dualCoord θ) = 0 := by
  refine ⟨M.fenchelGap_nonneg θ η,
    M.scaledFenchelGap_nonneg ε θ η hε,
    M.temperatureRegularizedHamiltonian_nonneg β θ η hβ,
    M.fenchelGap_eq_zero_at_contact θ,
    M.scaledFenchelGap_eq_zero_at_contact ε θ,
    M.temperatureRegularizedHamiltonian_eq_zero_at_contact β θ⟩

/--
Unified conservative capstone: algebraic triad/modular closure, compactified
Möbius boundary exchange, and abstract Fenchel-gap positivity/contact vanishing.
-/
theorem conservative_unification_capstone
    (M : LegendreModel) (θ η ε β : ℝ)
    (hε : 0 ≤ ε) (hβ : 0 ≤ β) :
    (I * I = -(1 : Mat2)
      ∧ E * E = (1 : Mat2)
      ∧ N * N = (0 : Mat2)
      ∧ K = E
      ∧ K * N - N * K = (2 : ℝ) • N
      ∧ K * NtBoost - NtBoost * K = (-2 : ℝ) • NtBoost
      ∧ N * NtSL2 - NtSL2 * N = K)
    ∧ (mobiusInv ePlus = eMinus
      ∧ mobiusInv eMinus = ePlus
      ∧ Function.Involutive mobiusInv)
    ∧ (0 ≤ M.fenchelGap θ η
      ∧ 0 ≤ M.scaledFenchelGap ε θ η
      ∧ 0 ≤ M.temperatureRegularizedHamiltonian β θ η
      ∧ M.fenchelGap θ (M.dualCoord θ) = 0
      ∧ M.scaledFenchelGap ε θ (M.dualCoord θ) = 0
      ∧ M.temperatureRegularizedHamiltonian β θ (M.dualCoord θ) = 0) := by
  exact ⟨triad_modular_packet, mobius_boundary_packet,
    fenchel_legendre_packet M θ η ε β hε hβ⟩

end InfoGeometry.Canonical.HypercomplexMobiusLegendreCapstone
