import Mathlib
import InfoGeometry.Canonical.ModularTomitaLorentzSynthesis
import InfoGeometry.Canonical.KMSSubstateKMSCondition
import InfoGeometry.OperatorAlgebra.OperatorThermodynamics

namespace InfoGeometry.Canonical

/-- 
1. The Unruh-Thermal Modular Hamiltonian K_l.
For the split-octonions, this is exactly the modular Hamiltonian flow 
generated by the shared hyperbolic modular edge `l` (the intersection of the 3 chiral planes).
-/
def unruhModularHamiltonian
    (l_axis : StandardIntegralSplitOctonion) : StandardIntegralSplitOctonion → StandardIntegralSplitOctonion :=
  modularHamiltonianFlow l_axis

/--
2. The Unruh Thermal Relative Entropy Operator.
The relative entropy S(ω || A) of an observable `A` with respect to 
the algebraic KMS state `ω` is defined as the expectation value of the modular Hamiltonian 
evaluated on `A` (i.e., S = ⟨K_l A⟩_ω). 
In the true algebraic QFT (Araki's relative entropy), this is derived from the 
Tomita-Takesaki modular operator ∆ = exp(-K). Here, we evaluate the action of the generator K_l.
-/
def unruhRelativeEntropy
    (state :
      InfoGeometry.OperatorAlgebra.OperatorThermodynamics.AlgebraicState
        StandardIntegralSplitOctonion)
    (l_axis A : StandardIntegralSplitOctonion) : ℂ :=
  state.eval (unruhModularHamiltonian l_axis A)

end InfoGeometry.Canonical
