import InfoGeometry.Arithmetic.MobiusDirichletInverseBridge
import InfoGeometry.Algebra.FiniteSpinAlgebra

/-!
# InfoGeometry.Arithmetic.MobiusDirichletInverseBridgeChecks

Availability checks for the finite Möbius/Witten inverse bridge.
-/

namespace InfoGeometry.Arithmetic.MobiusDirichletInverseBridge.Checks

#check finiteMobiusDirichletPolynomial
#check finiteFermionicEulerProduct
#check finiteMobiusDirichletPolynomial_eq_finiteFermionicEulerProduct
#check finiteMobiusDirichletPolynomial_empty
#check finiteFermionicEulerProduct_empty

end InfoGeometry.Arithmetic.MobiusDirichletInverseBridge.Checks
