import Mathlib
import InfoGeometry.Arithmetic.PrimeCyclotomicDirectedTower

/-!
# Ambient realization of the six-prime cyclotomic directed tower

The arithmetic spine in `PrimeCyclotomicDirectedTower` uses separately
constructed `CyclotomicField (conductor i) ℚ` types.  This owner realizes the
same conductor chain inside one common ambient field

  `K∞ = ℚ(ζ₃₀₀₃₀)`.

The seven ambient stages are the `ℚ`-subalgebras generated by

  `ζ^30030, ζ^15015, ζ^5005, ζ^1001, ζ^143, ζ^13, ζ`,

corresponding to conductors

  `1, 2, 6, 30, 210, 2310, 30030`.

Consecutive inclusions are proved only from the exact power relations.  Thus
this is a literal nested tower of intermediate `ℚ`-algebras in one carrier;
no identification of separately constructed cyclotomic-field types is used.
-/

noncomputable section

namespace InfoGeometry.Arithmetic.PrimeCyclotomicAmbientTower

open InfoGeometry.Arithmetic.PrimeCyclotomicDirectedTower

abbrev K∞ : Type := CyclotomicField 30030 ℚ

/-- Chosen primitive terminal root. -/
def ζ∞ : K∞ := IsCyclotomicExtension.zeta 30030 ℚ K∞

/-- Exponent that converts the terminal primitive root to the root at stage `i`. -/
def rootExponent (i : Fin 7) : ℕ :=
  ![30030, 15015, 5005, 1001, 143, 13, 1] i

/-- Root generator of the `i`-th ambient stage. -/
def stageRoot (i : Fin 7) : K∞ := ζ∞ ^ rootExponent i

/-- The actual intermediate `ℚ`-algebra inside the common ambient field. -/
def ambientStage (i : Fin 7) : Subalgebra ℚ K∞ :=
  Algebra.adjoin ℚ ({stageRoot i} : Set K∞)

@[simp] theorem rootExponent_values :
    List.ofFn rootExponent = [30030, 15015, 5005, 1001, 143, 13, 1] := by
  native_decide

/-- The root exponents are exactly terminal conductor divided by stage conductor. -/
theorem rootExponent_mul_conductor (i : Fin 7) :
    rootExponent i * conductor i = 30030 := by
  fin_cases i <;> native_decide

/-- Each consecutive generator is a prime root of the previous generator. -/
theorem stageRoot_step (i : Fin 6) :
    stageRoot i.castSucc = (stageRoot i.succ) ^ casPrime i := by
  fin_cases i <;>
    simp [stageRoot, rootExponent, casPrime, ζ∞, pow_mul]

/-- A generator belongs to its own adjoined stage. -/
theorem stageRoot_mem (i : Fin 7) : stageRoot i ∈ ambientStage i := by
  exact Algebra.subset_adjoin (by simp [ambientStage])

/-- Consecutive ambient stages are literally nested subalgebras. -/
theorem ambientStage_step_le (i : Fin 6) :
    ambientStage i.castSucc ≤ ambientStage i.succ := by
  rw [ambientStage, ambientStage]
  refine Algebra.adjoin_le ?_
  intro x hx
  simp only [Set.mem_singleton_iff] at hx
  subst x
  rw [stageRoot_step]
  exact (ambientStage i.succ).pow_mem (stageRoot_mem i.succ) (casPrime i)

/-- The first stage is contained in every later ambient stage. -/
theorem ambientStage_initial_le (j : Fin 7) :
    ambientStage 0 ≤ ambientStage j := by
  fin_cases j
  · exact le_rfl
  · exact ambientStage_step_le 0
  · exact (ambientStage_step_le 0).trans (ambientStage_step_le 1)
  · exact ((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
      (ambientStage_step_le 2)
  · exact (((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
      (ambientStage_step_le 2)).trans (ambientStage_step_le 3)
  · exact ((((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
      (ambientStage_step_le 2)).trans (ambientStage_step_le 3)).trans
      (ambientStage_step_le 4)
  · exact (((((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
      (ambientStage_step_le 2)).trans (ambientStage_step_le 3)).trans
      (ambientStage_step_le 4)).trans (ambientStage_step_le 5)

/-- Endpoint inclusion for an arbitrary directed path.  The finite proof is
path-independent because the index category is thin. -/
theorem ambientStage_le_of_directedPath {i j : Fin 7}
    (p : DirectedPath i j) : ambientStage i ≤ ambientStage j := by
  fin_cases i <;> fin_cases j <;>
    simp only [DirectedPath] at p
  all_goals first
    | exact le_rfl
    | exact ambientStage_step_le 0
    | exact ambientStage_step_le 1
    | exact ambientStage_step_le 2
    | exact ambientStage_step_le 3
    | exact ambientStage_step_le 4
    | exact ambientStage_step_le 5
    | exact (ambientStage_step_le 0).trans (ambientStage_step_le 1)
    | exact (ambientStage_step_le 1).trans (ambientStage_step_le 2)
    | exact (ambientStage_step_le 2).trans (ambientStage_step_le 3)
    | exact (ambientStage_step_le 3).trans (ambientStage_step_le 4)
    | exact (ambientStage_step_le 4).trans (ambientStage_step_le 5)
    | exact ((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
        (ambientStage_step_le 2)
    | exact ((ambientStage_step_le 1).trans (ambientStage_step_le 2)).trans
        (ambientStage_step_le 3)
    | exact ((ambientStage_step_le 2).trans (ambientStage_step_le 3)).trans
        (ambientStage_step_le 4)
    | exact ((ambientStage_step_le 3).trans (ambientStage_step_le 4)).trans
        (ambientStage_step_le 5)
    | exact (((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
        (ambientStage_step_le 2)).trans (ambientStage_step_le 3)
    | exact (((ambientStage_step_le 1).trans (ambientStage_step_le 2)).trans
        (ambientStage_step_le 3)).trans (ambientStage_step_le 4)
    | exact (((ambientStage_step_le 2).trans (ambientStage_step_le 3)).trans
        (ambientStage_step_le 4)).trans (ambientStage_step_le 5)
    | exact ((((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
        (ambientStage_step_le 2)).trans (ambientStage_step_le 3)).trans
        (ambientStage_step_le 4)
    | exact ((((ambientStage_step_le 1).trans (ambientStage_step_le 2)).trans
        (ambientStage_step_le 3)).trans (ambientStage_step_le 4)).trans
        (ambientStage_step_le 5)
    | exact (((((ambientStage_step_le 0).trans (ambientStage_step_le 1)).trans
        (ambientStage_step_le 2)).trans (ambientStage_step_le 3)).trans
        (ambientStage_step_le 4)).trans (ambientStage_step_le 5)

/-- Thin directed homotopy gives proof-level path independence for ambient
transport as well. -/
theorem ambient_transport_path_independent {i j : Fin 7}
    (p q : DirectedPath i j) :
    ambientStage_le_of_directedPath p = ambientStage_le_of_directedPath q := by
  apply Subsingleton.elim

/-- The terminal ambient stage is generated by the chosen primitive root itself. -/
theorem terminal_stage_eq_adjoin_zeta :
    ambientStage 6 = Algebra.adjoin ℚ ({ζ∞} : Set K∞) := by
  rfl

/-- Mathlib's cyclotomic generation theorem identifies the terminal stage with
all of `K∞`. -/
theorem terminal_stage_eq_top : ambientStage 6 = ⊤ := by
  rw [terminal_stage_eq_adjoin_zeta]
  exact IsCyclotomicExtension.adjoin_rootSet_eq_top
    (B := ℚ) (K := K∞) (S := ({30030} : Set ℕ))

/-- Constant-size endpoint statement: every ambient stage embeds in the common
terminal cyclotomic field. -/
theorem ambientStage_le_terminal (i : Fin 7) : ambientStage i ≤ ambientStage 6 := by
  exact ambientStage_le_of_directedPath (by
    change i ≤ (6 : Fin 7)
    omega)

end InfoGeometry.Arithmetic.PrimeCyclotomicAmbientTower
