import InfoGeometry.Arithmetic.PrimeSpinorWittenIndex.Readout
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Arithmetic.PrimeSpinorWittenIndex.PairCancellation
import InfoGeometry.Arithmetic.PrimeSpinorWittenIndex.Pfaffian
import InfoGeometry.Arithmetic.PrimeSpinorWittenIndex.Packet
