import Mathlib
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Arithmetic.PrimeCyclotomicGaloisDirectedClosure

/-!
# Genuine cyclotomic field embeddings for the fixed prime tower

This owner upgrades the arithmetic conductor spine
`2 -> 6 -> 30 -> 210 -> 2310 -> 30030`
to actual `ℚ`-algebra embeddings between Mathlib `CyclotomicField`s.

Each edge is obtained from Mathlib's equivalence between embeddings of an
`n`-cyclotomic extension and primitive `n`-th roots in the target.  The target
primitive root is the appropriate power of the chosen primitive root at the
larger conductor.

No CAS result is trusted here.
-/

noncomputable section

namespace InfoGeometry.Arithmetic.PrimeCyclotomicGaloisFieldTower

open InfoGeometry.Arithmetic.PrimeCyclotomicGaloisDirectedClosure

abbrev K2 : Type := CyclotomicField 2 ℚ
abbrev K6 : Type := CyclotomicField 6 ℚ
abbrev K30 : Type := CyclotomicField 30 ℚ
abbrev K210 : Type := CyclotomicField 210 ℚ
abbrev K2310 : Type := CyclotomicField 2310 ℚ
abbrev K30030 : Type := CyclotomicField 30030 ℚ

private noncomputable def embeddingOfPoweredPrimitiveRoot
    (n m q : ℕ) [NeZero n] [NeZero m]
    (hmpos : 0 < m) (hnpos : 0 < n)
    (hfactor : m = q * n) :
    CyclotomicField n ℚ →ₐ[ℚ] CyclotomicField m ℚ := by
  let ζn : CyclotomicField n ℚ :=
    IsCyclotomicExtension.zeta n ℚ (CyclotomicField n ℚ)
  let ζm : CyclotomicField m ℚ :=
    IsCyclotomicExtension.zeta m ℚ (CyclotomicField m ℚ)
  have hζn : IsPrimitiveRoot ζn n := by
    exact IsCyclotomicExtension.zeta_spec n ℚ (CyclotomicField n ℚ)
  have hζm : IsPrimitiveRoot ζm m := by
    exact IsCyclotomicExtension.zeta_spec m ℚ (CyclotomicField m ℚ)
  have hroot : IsPrimitiveRoot (ζm ^ q) n := by
    exact hζm.pow hmpos hfactor
  have hmem : ζm ^ q ∈ primitiveRoots n (CyclotomicField m ℚ) := by
    exact (mem_primitiveRoots hnpos).2 hroot
  exact
    (hζn.embeddingsEquivPrimitiveRoots
      (CyclotomicField m ℚ)
      (Polynomial.cyclotomic.irreducible_rat hnpos)).symm
      ⟨ζm ^ q, hmem⟩

/-- `ℚ(ζ₂) -> ℚ(ζ₆)`, generated by the primitive root `ζ₆^3`. -/
def emb2_6 : K2 →ₐ[ℚ] K6 :=
  embeddingOfPoweredPrimitiveRoot 2 6 3 (by norm_num) (by norm_num) (by norm_num)

/-- `ℚ(ζ₆) -> ℚ(ζ₃₀)`, generated by the primitive root `ζ₃₀^5`. -/
def emb6_30 : K6 →ₐ[ℚ] K30 :=
  embeddingOfPoweredPrimitiveRoot 6 30 5 (by norm_num) (by norm_num) (by norm_num)

/-- `ℚ(ζ₃₀) -> ℚ(ζ₂₁₀)`, generated by the primitive root `ζ₂₁₀^7`. -/
def emb30_210 : K30 →ₐ[ℚ] K210 :=
  embeddingOfPoweredPrimitiveRoot 30 210 7 (by norm_num) (by norm_num) (by norm_num)

/-- `ℚ(ζ₂₁₀) -> ℚ(ζ₂₃₁₀)`, generated by the primitive root `ζ₂₃₁₀^11`. -/
def emb210_2310 : K210 →ₐ[ℚ] K2310 :=
  embeddingOfPoweredPrimitiveRoot 210 2310 11 (by norm_num) (by norm_num) (by norm_num)

/-- `ℚ(ζ₂₃₁₀) -> ℚ(ζ₃₀₀₃₀)`, generated by the primitive root `ζ₃₀₀₃₀^13`. -/
def emb2310_30030 : K2310 →ₐ[ℚ] K30030 :=
  embeddingOfPoweredPrimitiveRoot 2310 30030 13 (by norm_num) (by norm_num) (by norm_num)

/-- Every stage is a genuine cyclotomic extension of `ℚ`. -/
theorem stage_isCyclotomicExtension :
    IsCyclotomicExtension {2} ℚ K2 ∧
    IsCyclotomicExtension {6} ℚ K6 ∧
    IsCyclotomicExtension {30} ℚ K30 ∧
    IsCyclotomicExtension {210} ℚ K210 ∧
    IsCyclotomicExtension {2310} ℚ K2310 ∧
    IsCyclotomicExtension {30030} ℚ K30030 := by
  exact ⟨inferInstance, inferInstance, inferInstance, inferInstance,
    inferInstance, inferInstance⟩

/-- The five actual field embeddings form the fixed directed cyclotomic tower. -/
structure PrimeCyclotomicFieldTower where
  e01 : K2 →ₐ[ℚ] K6
  e12 : K6 →ₐ[ℚ] K30
  e23 : K30 →ₐ[ℚ] K210
  e34 : K210 →ₐ[ℚ] K2310
  e45 : K2310 →ₐ[ℚ] K30030

/-- Canonical field-level realization of the six-stage certificate. -/
def fieldTower : PrimeCyclotomicFieldTower where
  e01 := emb2_6
  e12 := emb6_30
  e23 := emb30_210
  e34 := emb210_2310
  e45 := emb2310_30030

/-- The full composite is a genuine `ℚ`-algebra embedding from the first to
last stage. -/
def emb2_30030 : K2 →ₐ[ℚ] K30030 :=
  emb2310_30030.comp
    (emb210_2310.comp
      (emb30_210.comp
        (emb6_30.comp emb2_6)))

/-- Mathlib computes each cyclotomic field degree as Euler's totient. -/
theorem stage_finrank_eq_totient :
    Module.finrank ℚ K2 = Nat.totient 2 ∧
    Module.finrank ℚ K6 = Nat.totient 6 ∧
    Module.finrank ℚ K30 = Nat.totient 30 ∧
    Module.finrank ℚ K210 = Nat.totient 210 ∧
    Module.finrank ℚ K2310 = Nat.totient 2310 ∧
    Module.finrank ℚ K30030 = Nat.totient 30030 := by
  exact ⟨
    IsCyclotomicExtension.finrank K2 (Polynomial.cyclotomic.irreducible_rat (by norm_num)),
    IsCyclotomicExtension.finrank K6 (Polynomial.cyclotomic.irreducible_rat (by norm_num)),
    IsCyclotomicExtension.finrank K30 (Polynomial.cyclotomic.irreducible_rat (by norm_num)),
    IsCyclotomicExtension.finrank K210 (Polynomial.cyclotomic.irreducible_rat (by norm_num)),
    IsCyclotomicExtension.finrank K2310 (Polynomial.cyclotomic.irreducible_rat (by norm_num)),
    IsCyclotomicExtension.finrank K30030 (Polynomial.cyclotomic.irreducible_rat (by norm_num))⟩

/-- Exact degree readout agreeing with the frozen CAS rows, but reproved from
Mathlib cyclotomic extension theory. -/
theorem stage_finrank_exact :
    Module.finrank ℚ K2 = 1 ∧
    Module.finrank ℚ K6 = 2 ∧
    Module.finrank ℚ K30 = 8 ∧
    Module.finrank ℚ K210 = 48 ∧
    Module.finrank ℚ K2310 = 480 ∧
    Module.finrank ℚ K30030 = 5760 := by
  rcases stage_finrank_eq_totient with ⟨h2, h6, h30, h210, h2310, h30030⟩
  constructor
  · simpa using h2.trans (totient_conductorAt 0)
  constructor
  · simpa using h6.trans (totient_conductorAt 1)
  constructor
  · simpa using h30.trans (totient_conductorAt 2)
  constructor
  · simpa using h210.trans (totient_conductorAt 3)
  constructor
  · simpa using h2310.trans (totient_conductorAt 4)
  · simpa using h30030.trans (totient_conductorAt 5)

/-- Every stage is a Galois extension of `ℚ` by the native cyclotomic theorem. -/
theorem stage_isGalois :
    IsGalois ℚ K2 ∧
    IsGalois ℚ K6 ∧
    IsGalois ℚ K30 ∧
    IsGalois ℚ K210 ∧
    IsGalois ℚ K2310 ∧
    IsGalois ℚ K30030 := by
  exact ⟨
    IsCyclotomicExtension.isGalois {2} ℚ K2,
    IsCyclotomicExtension.isGalois {6} ℚ K6,
    IsCyclotomicExtension.isGalois {30} ℚ K30,
    IsCyclotomicExtension.isGalois {210} ℚ K210,
    IsCyclotomicExtension.isGalois {2310} ℚ K2310,
    IsCyclotomicExtension.isGalois {30030} ℚ K30030⟩

end InfoGeometry.Arithmetic.PrimeCyclotomicGaloisFieldTower
