import Mathlib
import InfoGeometry.Algebra.FiniteSpinAlgebra
import InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor
import InfoGeometry.Arithmetic.RiemannZetaEvidenceLogosMap

/-!
# Focused diagnostics for the Riemann-zeta theorem/evidence corridor
-/

#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.finite_prime_entrance
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.primeEulerProduct_eq_zeta
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.dirichletSeries_eq_zeta
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.riemannZeta_differentiable_off_one
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.completed_zeta_functional_equation
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.critical_strip_reflection
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.critical_line_fixed_locus
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.actualXi_criticalLine_zero_iff
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.finiteCriticalLine_selfAdjoint
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.finite_riemann_weil_trace_packet
#check InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.theorem_owned_corridor_packet

#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.finite_prime_entrance
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.primeEulerProduct_eq_zeta
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.dirichletSeries_eq_zeta
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.riemannZeta_differentiable_off_one
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.completed_zeta_functional_equation
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.critical_strip_reflection
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.critical_line_fixed_locus
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.actualXi_criticalLine_zero_iff
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.finiteCriticalLine_selfAdjoint
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.finite_riemann_weil_trace_packet
#print axioms InfoGeometry.Arithmetic.RiemannZetaEvidenceCorridor.theorem_owned_corridor_packet

#audit_riemann_zeta_evidence_logos

