import InfoGeometry.Arithmetic.PrimeParafermionRecurrence
import InfoGeometry.Algebra.FiniteSpinAlgebra

open InfoGeometry.Arithmetic.PrimeParafermionGrandCanonicalClock

#check finiteParafermionLocalFactor_succ
#check finiteParafermionLocalFactor_mul_one_sub
#check finiteGrandParafermionPartition_insert
#check finiteGrandParafermionPartition_mul_denominator
