import Mathlib
import InfoGeometry.Arithmetic.PrimonFinite
import InfoGeometry.Arithmetic.PrimeBitWittenIndex
import InfoGeometry.Arithmetic.PrimonFreeEnergyRelativeTrace
import InfoGeometry.Meta.Architecture

/-!
# InfoGeometry.Arithmetic.ZetaSouriauThermodynamics

Finite complex-Souriau grand-canonical thermodynamics for the prime/zeta lane.

This module implements the theorem-safe part of the requested architecture:

* complex Souriau inverse temperature `β : ℂ`;
* finite grand-canonical weights `q_p = exp(-β(E_p - μ_p))`;
* finite bosonic, fermionic, and signed/Möbius partition readouts;
* Massieu--Planck potential `Φ = log Z`;
* grand potential `Ω = -β⁻¹ Φ`;
* finite complex KMS boundary/periodicity law for kernels;
* generic regularized Bregman divergence for a real Massieu potential on the
  complex temperature plane;
* finite zeta-plane symmetry labels generated by `s ↦ 1 - s` and conjugation;
* socketed analytic zeta/Souriau/von Mangoldt moment-map layer.

No infinite Euler product, analytic continuation, Lee--Yang theorem,
Hilbert--Pólya operator, or RH claim is asserted here.
-/

noncomputable section

open scoped BigOperators

namespace InfoGeometry.Arithmetic.ZetaSouriauThermodynamics

/-! ## 1. Complex Souriau temperature and grand-canonical weights -/

/-- Complex Souriau geometric inverse temperature. -/
@[rep_depth thermo]
abbrev SouriauTemperature : Type :=
  ℂ

/-- Complex Souriau inverse-temperature datum. -/
@[rep_depth thermo]
structure ComplexSouriauBeta where
  beta : SouriauTemperature

/--
Positive real-part complex Souriau inverse temperature.

This is a finite-side guard for the usual thermal half-plane.  Infinite
normalizability is not asserted here.
-/
@[rep_depth thermo]
structure PositiveComplexSouriauBeta extends ComplexSouriauBeta where
  re_pos : 0 < beta.re

variable {ι : Type*}

/-- Fermionic/Fock state over a finite mode set. -/
@[rep_depth thermo]
abbrev FState (ι : Type*) :=
  InfoGeometry.Arithmetic.PrimonFinite.FState ι

/-- Particle number of a finite fermionic/Fock state. -/
@[rep_depth thermo]
def particleNumber (S : FState ι) : ℕ :=
  S.card

/-- Additive energy readout of a finite state. -/
@[rep_depth thermo]
def stateEnergy (energy : ι → ℝ) (S : FState ι) : ℝ :=
  S.sum energy

/-- Additive chemical-potential readout of a finite state. -/
@[rep_depth thermo]
def chemicalPotentialReadout (mu : ι → ℝ) (S : FState ι) : ℝ :=
  S.sum mu

/-- Grand-canonical effective real energy `K = H - μN`. -/
@[rep_depth thermo]
def grandEnergy (energy mu : ι → ℝ) (S : FState ι) : ℝ :=
  stateEnergy energy S - chemicalPotentialReadout mu S

/-- Complexified grand-canonical effective energy. -/
@[rep_depth thermo]
def grandEnergyC (energy mu : ι → ℝ) (S : FState ι) : ℂ :=
  (grandEnergy energy mu S : ℂ)

/--
Complex grand-canonical local mode weight

`q_p(β, μ) = exp(-β(E_p - μ_p))`.
-/
@[rep_depth thermo]
def complexGrandModeWeight
    (β : SouriauTemperature) (energy mu : ι → ℝ) (p : ι) : ℂ :=
  Complex.exp (-(β * ((energy p - mu p : ℝ) : ℂ)))

section FiniteModes

variable [DecidableEq ι]

/-- Finite fermionic grand-canonical partition at complex Souriau temperature. -/
@[rep_depth thermo]
def complexFermionGrandPartition
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) : ℂ :=
  InfoGeometry.Arithmetic.PrimonFinite.ZF
    modes (complexGrandModeWeight β energy mu)

/-- Euler-product form of the finite fermionic grand partition. -/
theorem complexFermionGrandPartition_eq_prod
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) :
    complexFermionGrandPartition modes β energy mu =
      ∏ p ∈ modes, (1 + complexGrandModeWeight β energy mu p) := by
  simpa [complexFermionGrandPartition] using
    (InfoGeometry.Arithmetic.PrimonFinite.ZF_eq_prod
      (modes := modes) (q := complexGrandModeWeight β energy mu))

/-- Finite signed/Möbius grand-canonical supertrace. -/
@[rep_depth thermo]
def complexFermionGrandSupertrace
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) : ℂ :=
  InfoGeometry.Arithmetic.PrimonFinite.STrF
    modes (complexGrandModeWeight β energy mu)

/-- Euler-product form of the finite signed/Möbius grand supertrace. -/
theorem complexFermionGrandSupertrace_eq_prod
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) :
    complexFermionGrandSupertrace modes β energy mu =
      ∏ p ∈ modes, (1 - complexGrandModeWeight β energy mu p) := by
  simpa [complexFermionGrandSupertrace] using
    (InfoGeometry.Arithmetic.PrimonFinite.STrF_eq_prod
      (modes := modes) (q := complexGrandModeWeight β energy mu))

/-- Finite bosonic grand-canonical partition as reciprocal Euler factors. -/
@[rep_depth thermo]
def complexBosonGrandPartition
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) : ℂ :=
  InfoGeometry.Arithmetic.PrimonFinite.ZB
    modes (complexGrandModeWeight β energy mu)

/-- Product form of the finite bosonic grand partition. -/
theorem complexBosonGrandPartition_eq_prod_inv
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) :
    complexBosonGrandPartition modes β energy mu =
      ∏ p ∈ modes, (1 - complexGrandModeWeight β energy mu p)⁻¹ := by
  rfl

/-- Finite boson/signed-fermion cancellation. -/
theorem complexBoson_mul_signedFermionGrandSupertrace_eq_one
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ)
    (h :
      ∀ p ∈ modes,
        (1 - complexGrandModeWeight β energy mu p) ≠ 0) :
    complexBosonGrandPartition modes β energy mu *
      complexFermionGrandSupertrace modes β energy mu = 1 := by
  rw [complexBosonGrandPartition_eq_prod_inv,
      complexFermionGrandSupertrace_eq_prod]
  rw [← Finset.prod_mul_distrib]
  exact
    InfoGeometry.Arithmetic.PrimonFinite.local_susy_cancellation
      (modes := modes)
      (q := complexGrandModeWeight β energy mu)
      h

/--
Normalized finite fermionic grand-canonical density on the square-free sector.

This is finite; no infinite trace-class statement is made.
-/
@[rep_depth thermo]
def normalizedComplexFermionGrandDensity
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ) (S : FState ι) : ℂ :=
  InfoGeometry.Arithmetic.PrimonFinite.weight
      (complexGrandModeWeight β energy mu) S *
    (complexFermionGrandPartition modes β energy mu)⁻¹

/-- The normalized finite density sums to one if the finite partition is nonzero. -/
theorem normalizedComplexFermionGrandDensity_sum_eq_one
    (modes : Finset ι) (β : SouriauTemperature)
    (energy mu : ι → ℝ)
    (hZ : complexFermionGrandPartition modes β energy mu ≠ 0) :
    (∑ S ∈ modes.powerset,
      normalizedComplexFermionGrandDensity modes β energy mu S) = 1 := by
  unfold normalizedComplexFermionGrandDensity
  rw [← Finset.sum_mul]
  have hpart :
      (∑ S ∈ modes.powerset,
        InfoGeometry.Arithmetic.PrimonFinite.weight
          (complexGrandModeWeight β energy mu) S) =
        complexFermionGrandPartition modes β energy mu := by
    rfl
  rw [hpart]
  exact mul_inv_cancel₀ hZ

end FiniteModes


/-! ## 2. Massieu--Planck potential, free energy, and Legendre socket -/

/-- Massieu--Planck potential `Φ = log Z`. -/
@[rep_depth thermo]
def massieuPlanck (Z : ℂ) : ℂ :=
  Complex.log Z

/-- Complex free energy `F = -log Z`. -/
@[rep_depth thermo]
def complexFreeEnergy (Z : ℂ) : ℂ :=
  - massieuPlanck Z

/-- Grand potential `Ω = -β⁻¹ log Z`. -/
@[rep_depth thermo]
def grandPotential (β Z : ℂ) : ℂ :=
  - β⁻¹ * massieuPlanck Z

/-- Definitional readout of the grand potential in Massieu--Planck form. -/
theorem grandPotential_eq_neg_inv_beta_mul_massieu
    (β Z : ℂ) :
    grandPotential β Z = -β⁻¹ * massieuPlanck Z := by
  rfl

/-- The Legendre-Massieu potential Φ = S - β(E - μN). -/
def massieuFromLegendre
    {Param : Type*}
    (entropy beta energy chemicalPotential particleNumber : Param → ℂ) :
    Param → ℂ :=
  fun θ =>
    entropy θ -
      beta θ * (energy θ - chemicalPotential θ * particleNumber θ)

/-- The grand potential Ω = -β⁻¹Φ. -/
def grandPotentialFromMassieu
    {Param : Type*}
    (beta massieu : Param → ℂ) :
    Param → ℂ :=
  fun θ => - (beta θ)⁻¹ * massieu θ

/--
Legendre/Massieu calibration socket.

This is the generic information-geometric layer: a model supplies a Massieu
potential, entropy, energy, particle number, chemical potential, and the
Legendre laws.
-/
structure MassieuPlanckLegendreCalibration (Param : Type*) where
  beta : Param → ℂ
  chemicalPotential : Param → ℂ
  entropy : Param → ℂ
  energy : Param → ℂ
  particleNumber : Param → ℂ
  massieu : Param → ℂ
  grandPotential : Param → ℂ

  /-- Massieu transform law: `Φ = S - β(E - μN)`. -/
  massieu_legendre_law :
    ∀ θ : Param,
      massieu θ =
        massieuFromLegendre entropy beta energy chemicalPotential particleNumber θ

  /-- Grand-potential law: `Ω = -β⁻¹Φ`. -/
  grandPotential_law :
    ∀ θ : Param,
      grandPotential θ = grandPotentialFromMassieu beta massieu θ

namespace MassieuPlanckLegendreCalibration

variable {Param : Type*}
variable (C : MassieuPlanckLegendreCalibration Param)

/-- Re-export of the Massieu Legendre transform law. -/
@[rep_depth thermo]
theorem massieu_eq_legendre (θ : Param) :
    C.massieu θ =
      massieuFromLegendre C.entropy C.beta C.energy C.chemicalPotential C.particleNumber θ :=
  C.massieu_legendre_law θ

/-- Re-export of the grand-potential law. -/
@[rep_depth thermo]
theorem grandPotential_eq (θ : Param) :
    C.grandPotential θ = grandPotentialFromMassieu C.beta C.massieu θ :=
  C.grandPotential_law θ

end MassieuPlanckLegendreCalibration


/-! ## 3. Complex KMS periodicity for the grand-canonical thermal vacuum -/

section ComplexKMS

variable [DecidableEq ι]

/-- Complex kernel on the finite Fock carrier. -/
@[rep_depth thermo]
abbrev Kernel :=
  FState ι → FState ι → ℂ

/-- Grand-canonical thermal Boltzmann weight `exp(-β(H-μN))`. -/
@[rep_depth thermo]
def complexGrandThermalWeight
    (β : SouriauTemperature) (energy mu : ι → ℝ) (S : FState ι) : ℂ :=
  Complex.exp (-(β * grandEnergyC energy mu S))

/-- Grand-canonical thermal-vacuum half-density. -/
@[rep_depth thermo]
def complexGrandThermalVacuumAmplitude
    (β : SouriauTemperature) (energy mu : ι → ℝ) (S : FState ι) : ℂ :=
  Complex.exp (-(β / 2 * grandEnergyC energy mu S))

/-- The complex thermal-vacuum amplitude squares to the Boltzmann weight. -/
theorem complexGrandThermalVacuumAmplitude_mul_self_eq_weight
    (β : SouriauTemperature) (energy mu : ι → ℝ) (S : FState ι) :
    complexGrandThermalVacuumAmplitude β energy mu S *
      complexGrandThermalVacuumAmplitude β energy mu S =
    complexGrandThermalWeight β energy mu S := by
  unfold complexGrandThermalVacuumAmplitude complexGrandThermalWeight
  rw [← Complex.exp_add]
  congr 1
  ring

/--
Imaginary-time complex grand-canonical modular shift of a finite kernel.

`σ_{iβ}(K)(S,T) = exp(-β(K(S)-K(T))) K(S,T)`,
where `K(S)=H(S)-μ(S)`.
-/
@[rep_depth thermo]
def complexImaginaryTimeGrandShift
    (β : SouriauTemperature) (energy mu : ι → ℝ)
    (A : Kernel (ι := ι)) : Kernel (ι := ι) :=
  fun S T =>
    Complex.exp
      (-(β * (grandEnergyC energy mu S - grandEnergyC energy mu T))) *
      A S T

/--
Finite complex grand-canonical KMS periodicity / boundary condition.

This is the finite kernel form

`ρ(S) A(S,T) = ρ(T) σ_{iβ}(A)(S,T)`.
-/
theorem complexGrandKMS_periodicity_condition
    (β : SouriauTemperature) (energy mu : ι → ℝ)
    (A : Kernel (ι := ι))
    (S T : FState ι) :
    complexGrandThermalWeight β energy mu S * A S T =
      complexGrandThermalWeight β energy mu T *
        complexImaginaryTimeGrandShift β energy mu A S T := by
  unfold complexGrandThermalWeight complexImaginaryTimeGrandShift
  have hExp :
      Complex.exp (-(β * grandEnergyC energy mu S)) =
        Complex.exp (-(β * grandEnergyC energy mu T)) *
          Complex.exp
            (-(β * (grandEnergyC energy mu S - grandEnergyC energy mu T))) := by
    rw [← Complex.exp_add]
    congr 1
    ring
  rw [hExp]
  ring

end ComplexKMS


/-! ## 4. Regularized Bregman divergence on the complex temperature plane -/

/--
Generic Bregman divergence on the complex temperature plane, with a supplied
first-order pairing.

`firstOrderAt η δη` represents the derivative of the potential at `η` applied
to the displacement `δη`.
-/
@[rep_depth thermo]
def bregmanComplex
    (A : ℂ → ℝ)
    (firstOrderAt : ℂ → ℂ → ℝ)
    (θ η : ℂ) : ℝ :=
  A θ - A η - firstOrderAt η (θ - η)

/--
Regularized Bregman divergence on the complex temperature plane.

The regularizer is `ε * ‖θ - η‖²`.
-/
@[rep_depth thermo]
def regularizedBregmanComplex
    (A : ℂ → ℝ)
    (firstOrderAt : ℂ → ℂ → ℝ)
    (ε : ℝ)
    (θ η : ℂ) : ℝ :=
  bregmanComplex A firstOrderAt θ η + ε * ‖θ - η‖ ^ 2

/-- Regularized Bregman divergence is nonnegative if the base Bregman term is. -/
theorem regularizedBregmanComplex_nonneg
    (A : ℂ → ℝ)
    (firstOrderAt : ℂ → ℂ → ℝ)
    (ε : ℝ)
    (hε : 0 ≤ ε)
    (θ η : ℂ)
    (hB : 0 ≤ bregmanComplex A firstOrderAt θ η) :
    0 ≤ regularizedBregmanComplex A firstOrderAt ε θ η := by
  unfold regularizedBregmanComplex
  have hdist : 0 ≤ ‖θ - η‖ ^ 2 := sq_nonneg _
  exact add_nonneg hB (mul_nonneg hε hdist)

/--
Self-contained regularized Bregman packet for a Massieu potential.

The convexity/self-concordance facts are witness-gated.  The finite theorem
above proves only elementary nonnegativity once the model supplies base
Bregman nonnegativity.
-/
structure RegularizedMassieuBregmanPacket where
  potential : ℂ → ℝ
  firstOrderAt : ℂ → ℂ → ℝ
  epsilon : ℝ
  epsilon_nonneg : 0 ≤ epsilon
  base_bregman_nonneg :
    ∀ θ η : ℂ, 0 ≤ bregmanComplex potential firstOrderAt θ η

namespace RegularizedMassieuBregmanPacket

variable (B : RegularizedMassieuBregmanPacket)

/-- The packet's regularized divergence. -/
@[rep_depth thermo]
def divergence (θ η : ℂ) : ℝ :=
  regularizedBregmanComplex B.potential B.firstOrderAt B.epsilon θ η

/-- The packet's regularized divergence is nonnegative. -/
theorem divergence_nonneg (θ η : ℂ) :
    0 ≤ B.divergence θ η :=
  regularizedBregmanComplex_nonneg
    B.potential B.firstOrderAt B.epsilon B.epsilon_nonneg
    θ η (B.base_bregman_nonneg θ η)

end RegularizedMassieuBregmanPacket


/-! ## 5. Zeta Massieu potential and Souriau moment-map socket -/

/--
Analytic zeta Massieu potential socket.

The intended analytic specialization is

`Φ(s) = -log ζ(s)`,

but the completed zeta construction and analytic continuation are not native
finite theorems here.
-/
structure ZetaMassieuPotentialSocket where
  zetaPartition : ℂ → ℂ

  /-- Formal complex Souriau gradient of the Massieu potential. -/
  gradient : ℂ → ℂ

/-- The zeta Massieu potential as an explicit derived formula. -/
def massieu (zetaPartition : ℂ → ℂ) : ℂ → ℂ :=
  fun s => -Complex.log (zetaPartition s)

/-- Re-export of the derived Massieu identity. -/
@[rep_depth thermo]
theorem massieu_eq_neg_log_zeta_of_region
    (P : ZetaMassieuPotentialSocket) (s : ℂ) :
    massieu P.zetaPartition s = -Complex.log (P.zetaPartition s) :=
  rfl

/--
Souriau moment-map / von-Mangoldt bridge.

The intended analytic identity is

`∇(-log ζ)(s) = -ζ'(s)/ζ(s) = Σ Λ(n)n^{-s}`

in the half-plane where the Dirichlet series converges.  The equality is kept
as a socket field.
-/
structure VonMangoldtMomentMapBridge where
  souriauMoment : ℂ → ℂ
  vonMangoldtDirichletSeries : ℂ → ℂ
  moment_eq_vonMangoldt :
    ∀ s : ℂ, souriauMoment s = vonMangoldtDirichletSeries s

namespace VonMangoldtMomentMapBridge

variable (M : VonMangoldtMomentMapBridge)

/-- Re-export of the supplied Souriau/von-Mangoldt moment-map identity. -/
@[rep_depth thermo]
theorem moment_eq (s : ℂ) :
    M.souriauMoment s = M.vonMangoldtDirichletSeries s :=
  M.moment_eq_vonMangoldt s

end VonMangoldtMomentMapBridge

/--
Zeta entropy via the Massieu Legendre expression

`S(s) = Q(s) * s - Φ(s)`,

where `Q` is the supplied Souriau moment map.
-/
@[rep_depth thermo]
def zetaEntropy
    (Phi : ZetaMassieuPotentialSocket)
    (Moment : ℂ → ℂ)
    (s : ℂ) : ℂ :=
  Moment s * s - massieu Phi.zetaPartition s

/--
Zeta Bregman divergence from the supplied analytic Massieu socket.

This is complex-valued and therefore not an ordered metric.  For ordered
optimization use `regularizedBregmanComplex` with a real potential/readout.
-/
@[rep_depth thermo]
def zetaBregmanDivergence
    (Phi : ZetaMassieuPotentialSocket)
    (s₁ s₂ : ℂ) : ℂ :=
  massieu Phi.zetaPartition s₁ - massieu Phi.zetaPartition s₂ -
    Phi.gradient s₂ * (s₁ - s₂)

/-- The complex zeta Bregman divergence vanishes on the diagonal. -/
theorem zetaBregmanDivergence_self_eq_zero
    (Phi : ZetaMassieuPotentialSocket)
    (s : ℂ) :
    zetaBregmanDivergence Phi s s = 0 := by
  unfold zetaBregmanDivergence
  ring


/-! ## 6. Zeta-plane symmetry and Souriau Lie-group thermodynamics -/

/-- Critical line predicate on the complex zeta plane. -/
@[rep_depth thermo]
def CriticalLine (s : ℂ) : Prop :=
  s.re = (1 / 2 : ℝ)

/--
Finite Klein symmetry generated by the functional-equation involution
`s ↦ 1 - s` and complex conjugation.
-/
@[rep_depth thermo]
inductive ZetaKleinSymmetry where
  | id
  | functionalEquation
  | conjugation
  | functionalConjugation
deriving DecidableEq, Repr

/-- Action of the finite zeta symmetry labels on the complex plane. -/
@[rep_depth thermo]
def zetaKleinAct : ZetaKleinSymmetry → ℂ → ℂ
  | ZetaKleinSymmetry.id, s => s
  | ZetaKleinSymmetry.functionalEquation, s => 1 - s
  | ZetaKleinSymmetry.conjugation, s => star s
  | ZetaKleinSymmetry.functionalConjugation, s => 1 - star s

/-- Each finite zeta Klein symmetry is involutive on the complex plane. -/
theorem zetaKleinAct_involutive
    (g : ZetaKleinSymmetry) (s : ℂ) :
    zetaKleinAct g (zetaKleinAct g s) = s := by
  cases g <;> simp [zetaKleinAct]

/-- The finite zeta Klein symmetries preserve the critical line. -/
theorem zetaKleinAct_preserves_criticalLine
    (g : ZetaKleinSymmetry) {s : ℂ}
    (hs : CriticalLine s) :
    CriticalLine (zetaKleinAct g s) := by
  cases g
  · simpa [CriticalLine, zetaKleinAct] using hs
  · have h1 : (1 - s : ℂ).re = 1 - s.re := by simp
    rw [CriticalLine, zetaKleinAct, h1, hs]
    norm_num
  · simpa [CriticalLine, zetaKleinAct] using hs
  · have h1 : (1 - star s : ℂ).re = 1 - s.re := by simp
    rw [CriticalLine, zetaKleinAct, h1, hs]
    norm_num

/--
Functional-equation / zeta-plane thermodynamic symmetry socket.

The actual analytic zeta/xi functional equation is not proved here.  A model
supplies the partition function, its Massieu readout, and the invariance law.
-/
structure ZetaFunctionalEquationThermodynamics where
  partition : ℂ → ℂ

  /-- Functional equation / mirror duality of the completed partition. -/
  partition_duality :
    ∀ β : ℂ, partition β = partition (1 - β)

namespace ZetaFunctionalEquationThermodynamics

variable (Z : ZetaFunctionalEquationThermodynamics)

/-- The functional-equation Massieu potential as an explicit derived formula. -/
def massieuFromFunctionalEquation (partition : ℂ → ℂ) : ℂ → ℂ :=
  fun β => Complex.log (partition β)

/-- Re-export of the derived Massieu/log-partition law. -/
@[rep_depth thermo]
theorem massieu_eq_log_partition_of_socket (β : ℂ) :
    massieuFromFunctionalEquation Z.partition β = Complex.log (Z.partition β) :=
  rfl

variable (Z : ZetaFunctionalEquationThermodynamics)

/-- Zeros reflect under the supplied partition duality. -/
@[rep_depth thermo]
theorem partition_zero_reflects {β : ℂ}
    (h : Z.partition β = 0) :
    Z.partition (1 - β) = 0 := by
  rw [← Z.partition_duality β]
  exact h

end ZetaFunctionalEquationThermodynamics

/-- The Souriau Massieu potential Φ = log Z. -/
def massieuFromPartition (partition : ℂ → ℂ) : ℂ → ℂ :=
  fun β => Complex.log (partition β)

/--
Abstract Souriau thermodynamics for a group acting on the complex zeta plane.

This is the Lie-group/Souriau layer.  The group action and invariance law are
supplied by the model; finite partition identities live in the finite ensemble
layer above.
-/
structure SouriauZetaLieGroupThermodynamics
    (G : Type*) [Group G] where
  actOnBeta : G → ℂ → ℂ
  one_act :
    ∀ β : ℂ, actOnBeta 1 β = β
  mul_act :
    ∀ (g h : G) (β : ℂ),
      actOnBeta (g * h) β = actOnBeta g (actOnBeta h β)

  partition : ℂ → ℂ
  
  /-- The supplied Massieu potential. -/
  massieu : ℂ → ℂ
  
  massieu_eq_log_partition :
    ∀ β : ℂ, massieu β = massieuFromPartition partition β

  /-- Symmetry subgroup/locus on which the completed thermodynamic readout is invariant. -/
  isThermalSymmetry : G → Prop

  partition_invariant :
    ∀ (g : G) (β : ℂ),
      isThermalSymmetry g →
        partition (actOnBeta g β) = partition β

namespace SouriauZetaLieGroupThermodynamics

variable {G : Type*} [Group G]
variable (S : SouriauZetaLieGroupThermodynamics G)

/-- Re-export of the supplied group-action identity. -/
@[rep_depth thermo]
theorem one_smul_beta (β : ℂ) :
    S.actOnBeta 1 β = β :=
  S.one_act β

/-- Re-export of the supplied group-action composition law. -/
@[rep_depth thermo]
theorem mul_smul_beta (g h : G) (β : ℂ) :
    S.actOnBeta (g * h) β = S.actOnBeta g (S.actOnBeta h β) :=
  S.mul_act g h β

/-- Re-export of the Massieu/log-partition law. -/
@[rep_depth thermo]
theorem massieu_eq_log_partition_of_souriau (β : ℂ) :
    S.massieu β = Complex.log (S.partition β) :=
  S.massieu_eq_log_partition β

/-- Re-export of partition invariance under a supplied thermal symmetry. -/
@[rep_depth thermo]
theorem partition_invariant_of_symmetry
    (g : G) (β : ℂ)
    (hg : S.isThermalSymmetry g) :
    S.partition (S.actOnBeta g β) = S.partition β :=
  S.partition_invariant g β hg

end SouriauZetaLieGroupThermodynamics


/-! ## 7. Finite prime specialization -/

namespace PrimeSpecialization

open InfoGeometry.Arithmetic.PrimeBitWittenIndex (PrimeRegister)

/-- Prime energy `E_p = log p`. -/
@[rep_depth thermo]
def primeEnergy (p : ℕ) : ℝ :=
  Real.log p

/-- Zero chemical potential. -/
@[rep_depth thermo]
def zeroChemicalPotential (_p : ℕ) : ℝ :=
  0

/-- Complex local prime grand-canonical weight at zero chemical potential. -/
@[rep_depth thermo]
def primeGrandModeWeight (β : ℂ) (p : ℕ) : ℂ :=
  complexGrandModeWeight β primeEnergy zeroChemicalPotential p

/-- Finite prime bosonic grand-canonical partition. -/
@[rep_depth thermo]
def finitePrimeBosonGrandPartition
    (P : PrimeRegister) (β : ℂ) : ℂ :=
  complexBosonGrandPartition P.primes β primeEnergy zeroChemicalPotential

/-- Product form of the finite prime bosonic grand partition. -/
theorem finitePrimeBosonGrandPartition_eq_prod
    (P : PrimeRegister) (β : ℂ) :
    finitePrimeBosonGrandPartition P β =
      ∏ p ∈ P.primes, (1 - primeGrandModeWeight β p)⁻¹ := by
  rfl

/-- Finite prime signed/Möbius grand-canonical supertrace. -/
@[rep_depth thermo]
def finitePrimeSignedGrandSupertrace
    (P : PrimeRegister) (β : ℂ) : ℂ :=
  complexFermionGrandSupertrace P.primes β primeEnergy zeroChemicalPotential

/-- Product form of the finite prime signed/Möbius grand supertrace. -/
theorem finitePrimeSignedGrandSupertrace_eq_prod
    (P : PrimeRegister) (β : ℂ) :
    finitePrimeSignedGrandSupertrace P β =
      ∏ p ∈ P.primes, (1 - primeGrandModeWeight β p) := by
  exact
    complexFermionGrandSupertrace_eq_prod
      P.primes β primeEnergy zeroChemicalPotential

/-- Finite prime bosonic Massieu--Planck potential. -/
@[rep_depth thermo]
def finitePrimeBosonicMassieu
    (P : PrimeRegister) (β : ℂ) : ℂ :=
  massieuPlanck (finitePrimeBosonGrandPartition P β)

/-- Finite prime free-energy readout `F = -log Z`. -/
@[rep_depth thermo]
def finitePrimeFreeEnergy
    (P : PrimeRegister) (β : ℂ) : ℂ :=
  complexFreeEnergy (finitePrimeBosonGrandPartition P β)

/-- Finite prime grand potential. -/
@[rep_depth thermo]
def finitePrimeGrandPotential
    (P : PrimeRegister) (β : ℂ) : ℂ :=
  grandPotential β (finitePrimeBosonGrandPartition P β)

theorem finitePrimeGrandPotential_eq
    (P : PrimeRegister) (β : ℂ) :
    finitePrimeGrandPotential P β =
      -β⁻¹ * finitePrimeBosonicMassieu P β := by
  rfl

end PrimeSpecialization

end InfoGeometry.Arithmetic.ZetaSouriauThermodynamics
