-- Generated by generate_amplituhedron_bounds.py
-- Define the coordinate ring for Gr(2,4)
R = QQ[p_12, p_13, p_14, p_23, p_24, p_34]

-- Define the Plucker ideal (quadratic Plucker relations)
I_Plucker = ideal( p_23*p_14 - p_13*p_24 + p_12*p_34,  p_24*p_13 - p_14*p_23 + p_12*p_34,  p_34*p_12 - p_14*p_23 + p_13*p_24,  p_34*p_12 - p_24*p_13 + p_23*p_14)

-- Define a specific positroid cell ideal (fixing boundary variables)
I_cell = ideal(p_12, p_13)

-- Compute the dimension of the coordinate ring modulo the ideals
D = dim(R / (I_Plucker + I_cell))

-- Export the result
print(toString(D))
exit 0
