/-
InfoGeometry/OperatorAlgebra/ModularSignCPT.lean

Modular sign, CPT reflection, and emergent Hestenes complex structure.

The primitive relation is

  J eps = - eps J

where `eps` is the sign of the modular Hamiltonian and `J` is modular
conjugation/CPT reflection.

The product

  Kmod = J eps

is the real Hestenes phase axis / complex structure on the active modular
support.
-/

import Mathlib
import InfoGeometry.OperatorAlgebra.ModularWeightTrace

noncomputable section

namespace InfoGeometry.OperatorAlgebra.ModularSignCPT

/-! ## 0. Bounded real operator notation -/

/-- Real bounded endomorphisms. -/
abbrev EndR
    (H : Type*) [NormedAddCommGroup H] [NormedSpace ℝ H] :=
  H →L[ℝ] H

/-! ## 1. Full/gapped modular sign-CPT datum -/

/--
Full, gapped modular sign/CPT datum.

This is the clean case where the modular Hamiltonian has no zero-mode sector,
so the sign operator satisfies `eps² = 1`.

The field `Kmod` is required to be `J ∘ eps`; the complex-structure law is
stored as a proof-carrying field at this socket layer.
-/
structure ModularSignCPTDatum
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] where
  /-- Modular sign/parity: `eps = sign(log Delta)`. -/
  eps : EndR H

  /-- Modular conjugation/CPT reflection, represented real-linearly. -/
  J : EndR H

  /-- Emergent Hestenes complex structure, intended as `J ∘ eps`. -/
  Kmod : EndR H

  /-- `eps² = 1` on the active modular sector. -/
  eps_square :
    eps.comp eps = 1

  /-- `J² = 1`. -/
  J_square :
    J.comp J = 1

  /-- Clifford anticommutation relation: `J eps = - eps J`. -/
  J_eps_anticomm :
    J.comp eps = -(eps.comp J)

  /-- The modular complex structure is `J eps`. -/
  Kmod_eq :
    Kmod = J.comp eps

  /-- Complex-structure law: `Kmod² = -1`. -/
  Kmod_square :
    Kmod.comp Kmod = -1

namespace ModularSignCPTDatum

variable
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

variable (M : ModularSignCPTDatum H)

/-- The opposite anticommutation relation follows from `J eps = - eps J`. -/
theorem eps_J_anticomm :
    M.eps.comp M.J = -(M.J.comp M.eps) := by
  rw [M.J_eps_anticomm]
  simp

/-- The modular sign is the supergrading/parity operator. -/
def parity : EndR H :=
  M.eps

/-- The modular CPT/reflection operator. -/
def cpt : EndR H :=
  M.J

/-- The dynamically generated Hestenes phase axis. -/
def complexStructure : EndR H :=
  M.Kmod

/-- `Kmod` is the product `J eps`. -/
theorem Kmod_eq_J_eps :
    M.Kmod = M.J.comp M.eps :=
  M.Kmod_eq

/--
The dynamically generated modular phase axis squares to `-1`.

This is the real Clifford calculation:

At this abstract socket layer this is re-exported from the datum. A concrete
functional-calculus layer can later prove the witness from `eps_square`,
`J_square`, and `J_eps_anticomm`.
-/
theorem Kmod_square_apply :
    M.Kmod.comp M.Kmod = -(1 : EndR H) := by
  simpa using M.Kmod_square

/-- The defining square law for the dynamically generated complex structure. -/
theorem complexStructure_square :
    M.complexStructure.comp M.complexStructure = -(1 : EndR H) := by
  simpa [complexStructure] using M.Kmod_square_apply

/--
An operator is even with respect to the modular sign when it commutes with
`eps`.
-/
def IsEvenOperator
    (T : EndR H) : Prop :=
  M.eps.comp T = T.comp M.eps

/--
An operator is odd with respect to the modular sign when it anticommutes with
`eps`.
-/
def IsOddOperator
    (T : EndR H) : Prop :=
  M.eps.comp T = -(T.comp M.eps)

/--
The primitive four-dimensional real Clifford/CPT span.

Mathematically this is the real span of

`{1, eps, J, Jeps}`,

with `eps² = 1`, `J² = 1`, and `Jeps = -epsJ`.
-/
structure CliffordCPTBasis where
  scalarUnit : EndR H := 1
  modularParity : EndR H := M.eps
  modularReflection : EndR H := M.J
  hestenesPhase : EndR H := M.Kmod

/--
The primitive four-dimensional real Clifford/CPT span generated by
`{1, eps, J, J eps}`.
-/
def cliffordCPTSpan : Submodule ℝ (EndR H) :=
  Submodule.span ℝ ({1, M.eps, M.J, M.Kmod} : Set (EndR H))

end ModularSignCPTDatum

/-! ## 2. Partial/zero-mode modular sign-CPT datum -/

/--
Partial modular sign/CPT datum.

This is the correct version when `0` lies in the spectrum of the modular
Hamiltonian. Then `eps²` is a support projection rather than the identity.

The field `support` should be read as the active modular support, usually
`1 - Pker(log Delta)`.
-/
structure PartialModularSignCPTDatum
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] where
  /-- Active support projection, usually `1 - Pker(log Delta)`. -/
  support : EndR H

  /-- Modular sign/parity on the active support. -/
  eps : EndR H

  /-- Modular conjugation/CPT reflection. -/
  J : EndR H

  /-- Partial Hestenes complex structure, intended as `J ∘ eps`. -/
  Kmod : EndR H

  /-- The active support is idempotent. -/
  support_idempotent :
    support.comp support = support

  /-- `eps² = support`. -/
  eps_square :
    eps.comp eps = support

  /-- The support acts as identity on `eps` from the left. -/
  support_eps :
    support.comp eps = eps

  /-- The support acts as identity on `eps` from the right. -/
  eps_support :
    eps.comp support = eps

  /-- `J² = 1`. -/
  J_square :
    J.comp J = 1

  /-- Clifford anticommutation relation on the active sector. -/
  J_eps_anticomm :
    J.comp eps = -(eps.comp J)

  /-- Opposite orientation of the Clifford anticommutation relation. -/
  eps_J_anticomm :
    eps.comp J = -(J.comp eps)

  /--
  The active support is preserved by modular reflection.

  This models the functional-calculus fact that the zero-mode sector is sent
  to itself by `J`.
  -/
  J_support_comm :
    J.comp support = support.comp J

  /-- The partial modular complex structure is `J eps`. -/
  Kmod_eq :
    Kmod = J.comp eps

  /-- Partial complex-structure law: `Kmod² = -support`. -/
  Kmod_square :
    Kmod.comp Kmod = -support

  /-- The support acts as identity on the partial complex structure from the left. -/
  support_Kmod :
    support.comp Kmod = Kmod

  /-- The partial complex structure is supported on the right. -/
  Kmod_support :
    Kmod.comp support = Kmod

namespace PartialModularSignCPTDatum

variable
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

variable (M : PartialModularSignCPTDatum H)

/-- Re-export the opposite anticommutation relation. -/
theorem eps_J_anticomm_apply :
    M.eps.comp M.J = -(M.J.comp M.eps) := by
  exact M.eps_J_anticomm

/-- The partial modular phase axis. -/
def partialComplexStructure : EndR H :=
  M.Kmod

/-- The partial Hestenes phase is `J eps`. -/
theorem Kmod_eq_J_eps :
    M.Kmod = M.J.comp M.eps :=
  M.Kmod_eq

/--
The partial modular phase axis squares to `-support`.

This is the zero-mode-corrected Clifford calculation:

At this abstract layer this is re-exported from the datum; concrete modular
functional calculus should prove the witness.
-/
theorem Kmod_square_apply :
    M.Kmod.comp M.Kmod = -M.support := by
  simpa using M.Kmod_square

/-- The partial square law on the active modular support. -/
theorem partialComplexStructure_square :
    M.partialComplexStructure.comp M.partialComplexStructure = -M.support := by
  simpa [partialComplexStructure] using M.Kmod_square_apply

/-- The support projection is a projector/idempotent. -/
theorem support_isProjector :
    M.support.comp M.support = M.support :=
  M.support_idempotent

/-- The active support is the identity on the sign operator from both sides. -/
theorem support_absorbs_eps :
    M.support.comp M.eps = M.eps ∧ M.eps.comp M.support = M.eps :=
  ⟨M.support_eps, M.eps_support⟩

/-- The active support is the identity on the partial complex structure from both sides. -/
theorem support_absorbs_Kmod :
    M.support.comp M.Kmod = M.Kmod ∧ M.Kmod.comp M.support = M.Kmod :=
  ⟨M.support_Kmod, M.Kmod_support⟩

/-- An operator is supported on the active modular sector from the left. -/
def IsLeftActiveSupported
    (T : EndR H) : Prop :=
  M.support.comp T = T

/-- An operator is supported on the active modular sector from both sides. -/
def IsActiveSupported
    (T : EndR H) : Prop :=
  M.support.comp T = T ∧ T.comp M.support = T

end PartialModularSignCPTDatum

/-! ## 3. Dynamic modular CPT algebra -/

/--
Dynamic modular CPT algebra.

This packages the Clifford sign/CPT algebra together with the modular flow.
The analytic statement that `eps` is actually `sign(log Delta)` remains a
proof-carrying field.
-/
structure DynamicModularCPTAlgebra
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] where
  /-- Full/gapped modular sign-CPT algebra. -/
  signCPT :
    ModularSignCPTDatum H

  /-- Modular flow on represented observables/operators. -/
  modularFlow : ℝ → EndR H → EndR H

  flow_zero :
    ∀ T : EndR H, modularFlow 0 T = T

  flow_add :
    ∀ s t T,
      modularFlow (s + t) T = modularFlow s (modularFlow t T)

  /-- Multiplicativity of the modular flow on represented operators. -/
  flow_mul :
    ∀ t A B,
      modularFlow t (A.comp B) = (modularFlow t A).comp (modularFlow t B)

  /--
  Optional link to the type-III modular integration backend.

  This is optional because one may want to study the sign/CPT algebra before a
  concrete weight has been chosen.
  -/
  modularWeightBackend :
    Option (InfoGeometry.OperatorAlgebra.ModularWeightDatum (EndR H))

  /--
  Certificate that `eps` is the sign of the modular Hamiltonian generating the
  flow.
  -/
  eps_is_sign_of_modular_hamiltonian : Prop

  /-- Certificate that `J` reverses modular time/CPT orientation. -/
  J_reverses_modular_flow : Prop

  /--
  Certificate that the generated algebra is the intended split Clifford/CPT
  superalgebra.
  -/
  split_clifford_cpt_superalgebra : Prop

namespace DynamicModularCPTAlgebra

variable
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℝ H]

variable (M : DynamicModularCPTAlgebra H)

/-- Re-export of the modular flow identity law. -/
@[simp]
theorem modularFlow_zero_apply
    (T : EndR H) :
    M.modularFlow 0 T = T :=
  M.flow_zero T

/-- Re-export of the modular flow additive law. -/
theorem modularFlow_add_apply
    (s t : ℝ)
    (T : EndR H) :
    M.modularFlow (s + t) T =
      M.modularFlow s (M.modularFlow t T) :=
  M.flow_add s t T

/-- Multiplicativity of the modular flow. -/
theorem modularFlow_mul_apply
    (t : ℝ)
    (A B : EndR H) :
    M.modularFlow t (A.comp B) = (M.modularFlow t A).comp (M.modularFlow t B) :=
  M.flow_mul t A B

/-- The dynamically generated phase axis squares to `-1`. -/
theorem complexStructure_square :
    M.signCPT.Kmod.comp M.signCPT.Kmod = -(1 : EndR H) :=
  M.signCPT.Kmod_square_apply

end DynamicModularCPTAlgebra

/-! ## 4. Owner targets -/

/--
Compatibility predicate for constructing a modular sign/CPT datum from
Tomita-Takesaki data.

A concrete theorem will require modular operator, modular Hamiltonian,
functional calculus, sign operator, active support, and conjugation relations.
-/
def ModularSignCPTCompatibility
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] : Prop :=
  True

/--
Owner target for the full/gapped modular sign-CPT construction.

This remains intentionally compatibility-gated: abstract normed real Hilbert
data alone do not construct the modular sign and conjugation witnesses.
-/
def ModularSignCPTDatumOwnerTarget : Prop :=
  ∀ (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H],
    ModularSignCPTCompatibility H →
      Nonempty (ModularSignCPTDatum H)

/-- Compatibility predicate for constructing the partial zero-mode-aware datum. -/
def PartialModularSignCPTCompatibility
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H] : Prop :=
  True

/-- Owner target for the partial modular sign-CPT construction. -/
def PartialModularSignCPTDatumOwnerTarget : Prop :=
  ∀ (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H],
    PartialModularSignCPTCompatibility H →
      Nonempty (PartialModularSignCPTDatum H)

/--
Owner target for the full/gapped modular sign-CPT algebra.

This is intentionally witness-gated: the sign operator, modular conjugation,
and anticommutation relation are analytic input.
-/
def ModularSignCPTOwnerTarget : Prop :=
  ∀ (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H],
    ModularSignCPTDatum H →
      Nonempty (ModularSignCPTDatum H)

/-- The full/gapped owner target is satisfied once the datum is supplied. -/
theorem modularSignCPTOwnerTarget :
    ModularSignCPTOwnerTarget := by
  intro H _ _ M
  exact ⟨M⟩

/-- Owner target for the partial/zero-mode modular sign-CPT algebra. -/
def PartialModularSignCPTOwnerTarget : Prop :=
  ∀ (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℝ H],
    PartialModularSignCPTDatum H →
      Nonempty (PartialModularSignCPTDatum H)

/-- The partial owner target is satisfied once the datum is supplied. -/
theorem partialModularSignCPTOwnerTarget :
    PartialModularSignCPTOwnerTarget := by
  intro H _ _ M
  exact ⟨M⟩

end InfoGeometry.OperatorAlgebra.ModularSignCPT
